### ISSUE TITLE
Jacoco support for Java 9

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1006]
Jacoco now supports Java 9 with its latest version: https://groups.google.com/forum/#!msg/jacoco/Zf0Cwj13G2g/wpyrYAEECAAJ

**Comment by eriwen** [comment]
@bmuschko is this just upgrading our default version or is there more to it?

**Comment by big-guy** [comment]
I think it's a version bump, a review of our test coverage and _maybe_ something to check that someone doesn't try to use an older version of Jacoco with Java 9? 

I think we're not performing any cross-version testing right now because of this `@Requires`: https://github.com/gradle/gradle/blob/master/subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/JacocoVersionIntegTest.groovy#L24-L24

**Comment by bmuschko** [comment]
@big-guy I agree with Sterling. It shouldn't be a big change. Let's tackle it before releasing Gradle 4.0.

> "maybe something to check that someone doesn't try to use an older version of Jacoco with Java 9"

Do you think that version of Jacoco definitely won't be backward compatible with older Java versions?

**Comment by bmuschko** [comment]
The PR has been merged.
