### ISSUE TITLE
Deprecate eager task configuration methods

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#10163]
The ones like `tasks.all` and `tasks.iterator()` that force *everything* to be configured should be nuked.

**Comment by SUPERCILEX** [comment]
It creates issues like this: https://github.com/Triple-T/gradle-play-publisher/issues/649#issuecomment-517969845

**Comment by lacasseio** [comment]
We are not ready to deprecate those methods, but maybe we can warn is a user script use an lazy API but then has some code logic that is using one of those methods to bring awareness.

**Comment by adammurdoch** [comment]
I think we should start deprecating the methods that already have a stable replacement. For example `all { }` can go, because you can use `configureEach {}` instead. However, `iterator()` should stay because there is currently no other query method that allows you to get all of the elements of a container.

**Comment by SUPERCILEX** [comment]
With 7.0 around the corner, this seems like a good time.

**Comment by SUPERCILEX** [comment]
Closing old issues.
