### ISSUE TITLE
gradle builds projects with the same Java version that it itself uses

### ISSUE THREAD

**Issue by yurivict** [gradle/gradle#10252]
I have Java 8 and Java 12 installed.

gradle-5 was built with Java 8, but I tried to use it to build CrateDB with Java 12. CrateDB requires Java 11+.

gradle is an executable that builds other projects, and therefore it shouldn't matter what Java version it itself uses. But it ignores the current Java settings that are supposed to be used for the build and reuses the same Java that it runs with. This imposes unreasonable limitations on what projects gradle can build.

This caused the CrateDB build to fail because gradle used Java 8 instead of Java 12.

**Comment by big-guy** [comment]
I'm not sure what you mean.  It doesn't matter which version of Java Gradle was built with, you can use Gradle with Java 8-Java 11 (for Gradle 5.0-5.3) and Java 8-Java 12 (for Gradle 5.4+). 

By default, Gradle will use whatever `JAVA_HOME` is pointing at, but there are other ways to configure your build to use a different version.

**Comment by big-guy** [comment]
I know this can't be the case for official Gradle releases because we use Java 11 to build final releases and just target Java 8 bytecode. 

Is the "Gradle FreeBSD port" a custom build with patches that might change that behavior? My only suggestion would be to check the environment that you're trying to build with.  What's JAVA_HOME set to?  Are any other environment variables set (like GRADLE_OPTS or JAVA_OPTS) that might be changing the version of Java? Does `gradle -v` show the version of Java you expect?
