### ISSUE TITLE
cannot compile a kotlin application depending on a scala library 

### ISSUE THREAD

**Issue by rlsf** [gradle/gradle#10260]
### Expected Behavior
code should compile the kotlin app, using the scala library 

### Current Behavior
kotlin application compilation is broken, because it doesn't refer the scala library dependency.

### Context
i am trying to migrate a maven project to gradle, however i have a hybrid project, using a scala library and a kotlin wrapper, which i can't compile. 

### Steps to Reproduce 
attached is a zip file containing a sample project reproducing the issue, just run gradle build.

[gradle-scala-test.zip](https://github.com/gradle/gradle/files/3492919/gradle-scala-test.zip)

### Your Environment
Build scan URL:  https://gradle.com/s/6qlteqio5ig74

**Comment by rlsf** [comment]
this issue can be worked around using this logic (which i believe should be part of the kotlin/scala plugins), in kotlin-app/build.gradle.kts:
```
afterEvaluate {
    val scalaCompileTask = tasks.getByPath(":scala-lib:compileScala")
    tasks {
        withType<KotlinCompile> {
            classpath = classpath.plus(files(scalaCompileTask.outputs))
            dependsOn(scalaCompileTask)
        }
    }
}
```

**Comment by ljacomet** [comment]
Could you try again with Gradle 5.6?
There were some changes around core JVM plugin setup that should have fixed this.

Note that, while your workaround works, you are fixing the problem on the consumer side while really it is the producer, the scala plugin, that has the issue since it does not exposes the right things.
See #8788 for details.
