### ISSUE TITLE
Honor api and implementation separation for ivy consumers

### ISSUE THREAD

**Issue by mockitoguy** [gradle/gradle#10299]
Hey guys!

The api/impl separation is honored by default by pom consumers, but not by ivy consumers. This seems like a missing feature/bug given that Gradle has first class support for both ivy and pom. I found a similar ticket: #3854

More context: if I create a "java-library", use api + implementation configurations, the "implementation" dependencies are not leaking to compile classpath of pom consumer (Gradle project that consumes poms). That's great and [documented](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation). However, Gradle projects that consume ivy dependencies will get "implementation" dependencies leaking to the compile classpath. To reproduce this, see https://github.com/mockitoguy/gradle-java-library-demo

**Comment by big-guy** [comment]
@ljacomet could you chime in here?

**Comment by jjohannes** [comment]
@mockitoguy I was just looking into this. 

Gradle uses variant aware dependency management for the api and implementation separation. For this it needs to know about the _variants_ that are published with a module. When using the new Gradle Module Metadata format, this information is published with the module and everything works.

For maven POMs, we derive some variants automatically, because they follow a strict pattern. I.e. there are always a `compile` and `runtime` scopes and the publisher can not define custom scopes.

In Ivy, the "issue" is that you can publish arbitrary configurations. If you use the default ivy publishing with Gradle for Java, you will get the `compile` and `runtime` ivy configurations. But in general a producer (customized publishing with Gradle or published with other tool) can decide to publish different configurations or wire configurations named `compile` and `runtime` differently etc. 

That's the reason why we do not have a general _variant derivation strategy_ for ivy as we have for Maven. However, you could write your own strategy with _Component Metadata Rules_. Only that it does not work yet for Ivy (the rules are just not used in the ivy case). I am about to propose that we change that. I have an implementation on this branch, which is already working:
https://github.com/gradle/gradle/tree/jjohannes/ivy-variant-derivation-with-rules

With that you can write a rule like this:
```
dependencies {    
    components { all(IvyVariantDerivationRule) }
}

@CacheableRule
class IvyVariantDerivationRule implements ComponentMetadataRule {
    @javax.inject.Inject
    ObjectFactory getObjects() { }

    void execute(ComponentMetadataContext context) {
        if (context.getDescriptor(IvyModuleDescriptor)) { // a check that matches all the ivy modules that follow runtime/implementation separation convention
            context.details.withVariant('compile') {
                attributes {
                    attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.JAR))
                    attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
                    attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_API))
                }
            }
            context.details.withVariant('runtime') {
                attributes {
                    attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.JAR))
                    attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
                    attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
                }
            }
        }
    }
}
```
These rules turn the ivy configurations `compile` and `runtime` into Gradle variants by assigning attributes to them (attributes are what make variants distinguishable during resolution). The attributes used are the default Java ecosystem attributes we defined. The important one here is `USAGE_ATTRIBUTE` which is different in the two variants.

If you use ivy and know that the `compile` and `runtime` configurations are used consistently throughout your organisation, you can encapsulate such a rule in a plugin for example and share it across all builds.

Feel free to build Gradle from the branch and give it a try.

**Comment by ljacomet** [comment]
This is a complex issue, which has two parts: publication _and_ consumption.

For publication, and using the sample provided, the producer outputs:
```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="com.sample.producer" module="producer" revision="1.0" status="integration" publication="20190828184734"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="runtime" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="producer" type="jar" ext="jar" conf="compile"/>
  </publications>
  <dependencies>
    <dependency org="org.apache.commons" name="commons-math3" rev="3.6.1" conf="compile-&gt;default"/>
    <dependency org="com.google.guava" name="guava" rev="27.0.1-jre" conf="runtime-&gt;default"/>
  </dependencies>
</ivy-module>
```

which in itself is not fully correct, if this happened to be consumed by plain Ivy, as the `compile` dependency on `commons-math3` is not visible from the `runtime` configuration, while it should be according to the Gradle build that produced this file.

As suggested in #3854, we could improve the configuration mapping in the `ivy.xml` output to be better.
But even doing that is not trivial, because Gradle only consumed the `default` configurations of `commons-math3` and `guava`, which happen to be Maven dependencies even and thus result in consuming their `runtime` scope. So finding the right mapping is a challenge by itself, especially as the consumer may have picked a specific Ivy configuration, so there needs to be support for _implicit_ and _explicit_ configurations consumption.

And then, for this to work as requested, something needs to be done in Gradle so that a single dependency declaration on an Ivy module can behave similarly to what is done for Maven.

The main reason this was done for Maven only and not Ivy is that Maven is easy to map given its fixed set of scopes, especially as for transitiveness, only `compile` and `runtime` are relevant.
Of course, Gradle itself, when producing ivy.xml, uses a fixed set of configurations as well.

So Gradle could evolve to allow variant derivation from Ivy configurations but we need to be careful there. As discussed around the sample above, the current Gradle mapping is problematic and would be _correct_ only if we used the `compile` configuration for compilation but the `default` configuration at runtime.

Also, this kind of change is a breaking change, unless it requires opt-in, as showed by the same change for Maven and its impact on existing projects in Gradle 5.0.

So before moving forward with this, could you, @mockitoguy, elaborate on your use case?
Given the above reflection, what must work for you? How _transparent_ would it need to be?

**Comment by ljacomet** [comment]
To be clear, the consumption part relates to this in the `ivy-consumer` sample:
```
dependencies {    
    // uncommenting the "configuration" setting below prevents leaking compile dependencies
    implementation group: 'com.sample.producer', name: 'producer', version: '1.0' // , configuration: 'compile'
}
```

which, in order to be fully correct and do proper compile / runtime separation would need to become:
```
dependencies {    
    compileOnly group: 'com.sample.producer', name: 'producer', version: '1.0', configuration: 'compile'
    runtimeOnly group: 'com.sample.producer', name: 'producer', version: '1.0'
    // which implicitly means: ", configuration: 'default'"
    // note that using ", configuration: 'runtime'" here would be incorrect as stated in the previous comment
}
```

**Comment by jjohannes** [comment]
The solution proposed above is now available in the latest 6.0 nightly `gradle-6.0-20190910220033+0000`.

You can add the following rules to your build to get runtime/api separation for ivy modules (without Gradle Module Metadata) if the modules were published in a way where the `compile` configuration represents all files and dependencies required for compilation and the `default` configuration represents all files and dependencies required at runtime. This is the case if you used Gradle with _ivy-publish_ for publishing.

```
dependencies {    
    components { all(IvyVariantDerivationRule) }
}

@CacheableRule
class IvyVariantDerivation implements ComponentMetadataRule {
    @javax.inject.Inject
    ObjectFactory getObjects() { }

    void execute(ComponentMetadataContext context) {
        context.details.addVariant('runtimeElements', 'default') { 
            attributes { 
                attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.JAR))
                attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
            }
        }
        context.details.addVariant('apiElements', 'compile') {
            attributes { 
                attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements, LibraryElements.JAR))
                attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.LIBRARY))
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_API))
            }
        }
    }
}
```

We also made some improvement in _ivy-publish_ (#10450). One of them is that if you publish with Gradle 6+, the `runtime` configuration also represents the full runtime classpath (and may be used instead of `default`).

**Comment by jjohannes** [comment]
The above is now documented and will be part of Gradle 6.0. 

https://docs.gradle.org/nightly/userguide/modeling_features.html#sub:ivy-mapping-to-variants

**Comment by jjohannes** [comment]
The above has been delivered with Gradle 6.0.

**Comment by DPUkyle** [comment]
> The above is now documented and will be part of Gradle 6.0.
> 
> https://docs.gradle.org/nightly/userguide/modeling_features.html#sub:ivy-mapping-to-variants

Static link: https://docs.gradle.org/6.0/userguide/variant_model.html#sub:ivy-mapping-to-variants
