### ISSUE TITLE
`dependsOn configuration.myConf` has no effect

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#10294]
If I create a task with `dependsOn configuration.myConf`, it has no effect, however, `dependsOn configuration.myConf.allArtifacts` works. I think it makes sense to support the shorter syntax, because `myConf` is essentially a collection of buildables, thus `dependsOn` could iterate on it...

*Edit:* Even if you don't support this idea, at least Gradle could issue a warning or an error, because silently ignoring the dependency is still worse and can cause headaches during debugging.

Example code reproducible with Gradle 5.6:

```
clean {
	delete 'test1.zip'
	delete 'test2.zip'
	delete 'test-all.zip'
}

task task1ForBuildingMyConf(type: Zip) {
	from 'test1.txt'
	archiveFileName = 'test1.zip'
	destinationDir = file '.'
}

task task2ForBuildingMyConf(type: Zip) {
	from 'test2.txt'
	archiveFileName = 'test2.zip'
	destinationDir = file '.'
}

configurations {
	myConf
}

artifacts {
	myConf task1ForBuildingMyConf
	myConf task2ForBuildingMyConf
}

// ==> Does NOT work
task task1ForUsingMyConf(type: Zip) {
	dependsOn configurations.myConf

	from('.') {
		include 'test1.zip'
		include 'test2.zip'
	}
	archiveFileName = 'test-all.zip'
	destinationDir = file '.'
}

// ==> Works
task task2ForUsingMyConf(type: Zip) {
	dependsOn configurations.myConf.allArtifacts

	from('.') {
		include 'test1.zip'
		include 'test2.zip'
	}
	archiveFileName = 'test-all.zip'
	destinationDir = file '.'
}
```
They produce the following results:

```
$ gw clean t2FU

> Task :clean UP-TO-DATE
> Task :task1ForBuildingMyConf
> Task :task2ForBuildingMyConf
> Task :task2ForUsingMyConf

BUILD SUCCESSFUL in 531ms
4 actionable tasks: 3 executed, 1 up-to-date

$ gw clean t1FU

> Task :clean
> Task :task1ForUsingMyConf NO-SOURCE

BUILD SUCCESSFUL in 529ms
1 actionable task: 1 executed
```

**Comment by big-guy** [comment]
This does work, but it's a little different from what you're doing.  A configuration is used two different ways--as a bucket of dependencies and as a bucket of artifacts. When you add buildable things to your artifacts, those are outputs of the project. `configurations.myConf` is a file collection of the dependencies and not the artifacts.

Instead of registering the files as artifacts of the project, you can add them as dependencies to `myConf`:
```
dependencies {
    myConf files(task1ForBuildingMyConf)
    myConf files(task2ForBuildingMyConf)
}
```
Then `dependsOn configurations.myConf` works as you expected.

The explicit `dependsOn` is unnecessary if you simplify your task a bit:
```
task task1ForUsingMyConf(type: Zip) {
	from(configurations.myConf)
	archiveFileName = 'test-all.zip'
	destinationDir = file '.'
}
```

And unless you absolutely need the zip files put into the project directory, I would just apply the `base` plugin and only configure the file names for each `Zip` task. The destinationDir and clean task would come for free with the base plugin.

**Comment by rkrisztian** [comment]
Wow, thanks for telling that, it does explain a lot.

I agree that I should have referenced `'test1.zip'` indirectly via `myConf`, in my original code I just used `configuration.myConf*.file`, but then I indeed missed out on the auto-configuration of the task dependency.

And yes, normally I use the `base` plugin, but good to know what it does.
