### ISSUE TITLE
Test tasks should send tooling events when up-to-date or from-cache

### ISSUE THREAD

**Issue by trevjonez** [gradle/gradle#10319]
### Expected Behavior

Currently when running test tasks via an Intellij Idea run config if the task runs you will get a nice overview of the test and how long it took to ran etc...

The listing of tests should be populated even when the tasks are up-to-date or from-cache.

### Current Behavior

Test events are only sent to the IDE when the task is ran

### Context

Total test counts displayed in the IDE appear off and in large multi module projects that can look very similar at a high level view to a module failing to compile and not running tests. This is especially true when ran with `--continue` for me.

Focusing on consistency it may be more appropriate to still populate the list of tests based on buildDir report data since an up-to-date or from-cache task is referentially the same as one that did run successfully?

**Comment by wolfs** [comment]
We decided not to send the tooling API when a task is up-to-date or from-cache. The events should only be sent when actual tests execute. I think it is important to distinguish between the case when the test task did actual work as opposed to not doing any work at all.

As a general rule, the build cache and incremental build will only make sure the state on the disk are as if the task executed. All other side effects (like tooling api events, console log, etc.) are not reproduced.

I agree that the presentation in IDEA could be better, e.g. IDEA could show the outcome of the test task (the test task was up-to-date/from-cache/did not execute) instead of showing that now test results have been received.
