### ISSUE TITLE
Create SourceSetProvider that extends NamedDomainObjectProvider<SourceSet> to provide task & configuration name methods

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#10326]
`NamedDomainObjectProvider<SourceSet>` should be replaced everywhere with a new `SourceSetProvider extends NamedDomainObjectProvider<SourceSet>`, which should add all the `SourceSet#get*[Task|Configuration]Name(…)` methods.

This will allow builds to lazily register `SourceSet`s, yet still use these methods to safely & extensibly generate associated `Task` and `Configuration` names for lazy wiring.

**Comment by big-guy** [comment]
This isn't how we see this evolving.

Instead of `SourceSetProvider` gathering the properties from `SourceSet`, we'd rather make this work at the container level.  IOW, instead of fat-`Provider` objects, the containers would have a way to realize/find elements from a `Provider` when necessary.

e.g., maybe a new method to add an element via a `Provider` that's a transformation of a `Provider` of another type:
```
NamedDomainObjectProvider<SourceSet> customSourceSet = sourceSets.register("customSourceSet")
configurations.newMethodForComposing(customSourceSet.flatMap { sourceSet ->
    configurations.createWithoutAdding(sourceSet.getCompileClasspathConfigurationName())
})
// wire other things
```
or, in reaction to new source sets:
```
sourceSets.whenObjectRealized { sourceSet ->
    configurations.create(sourceSet.getCompileClasspathConfigurationName())
    // other things
}
```
Or something higher level that ties source sets, tasks and configurations when the higher level thing is created.

At the moment, it's not particularly useful to use register/lazy configuration with other types of containers because inevitably, something is going to iterate over the collection and realize everything.

**Comment by rgoldberg** [comment]
@big-guy Thanks for the info.  A somewhat related question, if you cam help.

I noticed that, in a project using the `java` plugin, all `SourceSets` are eagerly created, even if I used `register`.

This occurs because when the `JavaPlugin` is applied, `pluginConvention.getSourceSets().all(…)` is called (see https://github.com/gradle/gradle/blob/7a0c5fcfe06b62bdcaaf5e8c724cd128f2da2366/subprojects/plugins/src/main/java/org/gradle/api/plugins/JavaPlugin.java#L304).

Is that intentional? Or should `all` be changed to `configureEach`?

**Comment by lacasseio** [comment]
At the moment, only the `TaskContainer` should be used with `register`/`configureEach`. The issue is mainly centred around the restrictiveness of the lazy method on the containers. With `configureEach`, you aren't allowed to create additional element inside the container, as such. Most code outside the `TaskContainer` depends on some of the restricted behaviours so they can't be simply swapped. Once we implement the missing APIs to link containers together in a lazy way, we should be able to move forward with using `configureEach` everywhere.

**Comment by rgoldberg** [comment]
@lacasseio Thanks for the info.
