### ISSUE TITLE
Calling build instead of jar for substituted dependencies

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#10399]
Gradle 5.6.1 composite builds seem to perform dependency substitution by calling the `jar` task of the included build that will be substituted for a dependency or for a plugin.  This is probably the case for all dependency substitutions, not just included builds.

Can you add a way to configure Gradle to instead call any task that depends on `jar`, e.g., `build`?

I imagine that most people would expect that, when building a composite build, `build` would actually run on all the substituted dependencies, so people might expect tests to have run that were not actually run.  Therefore, you might also want to change the default from calling `jar` to calling `build`.

**Comment by big-guy** [comment]
I wouldn't quite think about it this way.  We wouldn't want to add an option/flag to change this behavior.

Gradle doesn't simply call "jar" on an included build--it's much deeper than that.  Gradle looks at the coordinates (group and artifact) and attributes (type of packaging) of a given dependency and matches that with available substitutions.  So in the simple case, a java project produces a jar and that's substituted for an external/prebuilt dependency.  Since the jar task builds the jar file, that's the task that gets put into the execution plan. This works generically, so if the jar was built by `notTheJar` task, that task would be executed instead.

You're right that we should have a way to treat a composite as something closer to a multi-project build.  It would be nice to be able to run arbitrary tasks in other builds, so running `gradle build` in a multi-project build or a composite would behave in a similar way.  Here's an [issue](https://github.com/gradle/gradle/issues/5433) for something along those lines.  You can manually get something close to this now.

In a multi-project build (not a composite), I don't think it would make sense that when I run `gradle subproject:assemble` it would run `gradle dependencyOfSubproject:build` before assembling `subproject`. 

We do have `buildDependents` (build things that depend on me) and `buildNeeded` (build things that I depend on) that sort of do what you want, but I don't think these work in composites or at least, I've never tried it.  Making that work, if it doesn't, would be good option.
