### ISSUE TITLE
Artifactory repositories work with new plugins syntax

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle#1050]
### Expected Behavior

As an [Artifactory](https://www.jfrog.com/artifactory/) maintainer I want my artifactory instance to be able to serve all of the plugins on the [Gradle Plugins Portal](https://plugins.gradle.org/) to my internal network in a way which is compatible with the new [plugins syntax](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) so that I can easily resolve all of the plugins for my builds using this clearly superior new style of specifying all my plugins.

### Current Behavior

Even when I configure Artifactory to mirror the whole Gradle Plugins Portal, I am unable to specify this Artifactory mirror as a [custom plugin repository](https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories) and successfully resolve plugins from it.

### Context

Enterprise users of Gradle rely on local Artifactory servers to fulfill security and latency goals for their builds. If the Artifactory servers cannot act as faithful proxies for the plugins in the Gradle Plugins Portal, then, they have to do considerable more work to gain access to those plugins for their developers.

## Technical Notes

What's going on is that the normal process of publishing a plugin to the Gradle Plugins Portal does not include deploying [plugin marker artifacts](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers). There is a special plugin resolution protocol implemented by the Gradle Plugins Portal which allows it to resolve plugins using the new plugins syntax without requiring the plugin marker artifacts.

The straight-forward way to make this work would be to take three steps:
 1. Change the Gradle plugin which publishes plugins to the plugin portal to also include plugin marker artifacts.
 1. Write a script against the Gradle Plugin Portal to update all of the existing versions of plugins to also have plugin marker artifacts.
1. Support version listing on the Plugin Portal's m2 repository, so Artifactory will be able to mirror it

At this point, the normal way in which Artifactory acts as a proxy for the m2 repository which underpins the Gradle Plugin Portal should be sufficient to serve as a custom plugin repository.

**Comment by eljobe** [comment]
There is a related feature request on JFrog's Jira, but I think this is ours to fix: https://www.jfrog.com/jira/browse/RTFACT-12701

**Comment by javacody** [comment]
Are there any updates on this? What's the recommended work around?

**Comment by edeandrea** [comment]
Just like those above - we are trying to proxy the gradle plugin portal, but when I do this in `settings.gradle`

```
pluginManagement {
	repositories {
		maven { url 'http://internal.artifactory.host:port/artifactory/gradle-plugins-proxy-remote-repo' }
	}
}
```

I get this:

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/user/workspaces/Stuff/project/build.gradle' line: 12

* What went wrong:
Plugin [id: 'com.jfrog.artifactory', version: '4.4.9'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- maven(http://internal.artifactory.host:port/artifactory/gradle-plugins-proxy-remote-repo) (Could not resolve plugin artifact 'com.jfrog.artifactory:com.jfrog.artifactory.gradle.plugin:4.4.9')

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

CONFIGURE FAILED
```

**Comment by SchwingSK** [comment]
I would also be interested in this feature. Today some builds failed because Gradle's server was choking:

     Could not HEAD 'https://plugins.gradle.org/m2/com/thoughtworks/xstream/xstream/1.3.1/xstream-1.3.1.pom'. Received status code 500 from server: Internal Server Error

We already have an Artifactory set up to avoid this kind of external server problem, so a fix or workaround would be really appreciated.

**Comment by SourceNode** [comment]
I really like the simplicity of the new pluginManagement configuration in settings.gradle and easily configuring plugins in my project. However, I am running into this same issue. My company mandates all dependency resolution, including plugins, come from our enterprise Artifactory. I am having to use the older style buildscript { ... } notation to get this to work currently. I am surprised this is not assigned to anyone yet.

**Comment by eskatos** [comment]
@SourceNode thanks for the heads up, I assigned this issue so that it reflects current work in progress

**Comment by wemu** [comment]
does the kotlin dsl have that old way of specifying plugins? it seems to rely on the new dsl. for example the [multi-kotlin-project](https://github.com/gradle/kotlin-dsl/tree/master/samples/multi-kotlin-project) suddenly jumps to https://plugins.gradle.org/api/gradle/4.2/plugin/use/org.jetbrains.kotlin.jvm/1.1.4-3 -- passing by all repositories and proxy settings we have to do (authenticated http(s) proxy for all the things). 

Nexus 3 does allow you to proxy "raw" repositories - becoming mainly a http proxy. Maybe artifactory has something like that as well? We use that for the wrapper distributions quite successfully. Is there no way to create such a raw proxy for the plugins repository and pass that base url into gradle somehow?

**Comment by alexkleiman** [comment]
@eskatos @bamboo I'm sorry to be just one more voice asking about this, but is there currently an estimated timeline for this fix? My organization is trying to determine whether we can wait for a fix, or whether we need to revert to use of the `buildscript {}` style of plugin dependency declaration.

Thank you for prioritizing this issue!

**Comment by bamboo** [comment]
@alexkleiman we should have good news for you soon.

**Comment by mkobit** [comment]
Looking at https://github.com/gradle/kotlin-dsl/issues/429 , should this also be resolved?

**Comment by reegnz** [comment]
Tried it with a private cache of https://plugins.gradle.org/m2/ in Artifactory, configured as a remote maven repository.
Also configured it like in the documentation of gradle:
https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories
Works like a charm.

**Comment by eriwen** [comment]
📣 The Gradle Plugin Portal is now mirrorable.

Here are instructions to setup your own mirror for Artifactory: https://plugins.gradle.org/docs/mirroring 

I believe this completely resolves this issue. If you have troubles, please contact us through the [plugin-portal topic on the Gradle forums](https://discuss.gradle.org/c/help-discuss/plugin-portal).

Closing as shipped

**Comment by edeandrea** [comment]
The whole way `settings.gradle`'s `pluginManagement` block works has always been a headache for us within a large organization.

I work in an organization with thousands of projects for which we ship our own custom Gradle distribution which encapsulates all the different things we want to do within our organization. One of those things is to direct dependencies into our own internal repositories rather than going out to the internet.

The problem I consistently run into with this architecture is that there is no way for a custom Gradle distribution to manipulate the `pluginManagement` block on behalf of a project. We simply can't have each & every project with their own `settings.gradle` file where they put in their own URLs. We have custom logic which can override the resolve URL, repos, etc, as well as a hierarchy of how those overrides work (i.e. we even use [Spring Cloud Config Server](https://spring.io/guides/gs/centralized-configuration) for managing various properties that can be overridden on a per-project basis, per-environment basis (local dev vs CI), or even on a geographic basis).

Because of this we do not use the `plugins` closure but instead revert back to the `apply plugin:` syntax to get around this issue.

Is there a better way to do this? Essentially I need to be able to manipulate the object model that `settings.gradle` provides, but do it from an init script or an init plugin (which is applied from an init script). Anything that involves a file checked into a specific project's source tree or placed in a folder on a user's/CI machine is just unacceptable for our use cases.

Thoughts? Should I move this to a separate issue?

**Comment by edeandrea** [comment]
I just looked through #932 & #1343 - it looks like the hooks are there but I had a question about how to get at the information that I need.

The `settingsEvaluated` hook is called very early on in the lifecycle correct? Long before `projectsLoaded`/`projectsEvaluated`.

The way we've structured our code is that all the information we need to make decisions are added as extensions to the root project. This is where we read all of the information we need to pre-configure repositories, publishing, etc. Seems in the `settingsEvaluated` block I wouldn't have access to any of that information since none of the projects would have been evaluated yet.

I don't want to copy/paste code, nor do I want to have to do the logic twice, since it does involve a network request to the config server to pull down the information. I don't want to have to do that both in the `settingsEvaluated` and in the plugin that gets applied to each & every root project.

Thoughts about how to go about this?

**Comment by eriwen** [comment]
@edeandrea Yes, `settingsEvaluated` is triggered right after Gradle determines which projects shall participate in the build. This is done just before it starts evaluating build scripts.

It may be best to continue use of `apply plugin:` syntax. I would imagine that construct will live for a very long time, maybe forever. You should use that if it works. 

I don't have any further advice here, but others may.

**Comment by bamboo** [comment]
@edeandrea There's also [`Gradle.rootProject(Action)`](https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:rootProject(org.gradle.api.Action)).
