### ISSUE TITLE
[Question] What is the recommended way to reuse parts of the buildscript with kotlin dsl?

### ISSUE THREAD

**Issue by hannespernpeintner** [gradle/gradle#10545]
Hey guys, another question from me :)

We used to use Groovy based builds and we often organize our build in reusable fragments. For example we have a script plugin that configures jvm compilation tasks, like bytecode targetVersion and the like. With groovy, it's not a problem at all to just write for example
```
compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
    kotlinOptions.freeCompilerArgs = ["-Xjvm-default=enable"]
}
```
I think it's because of the dynamic nature of Groovy, because at evaluation time, everything that's needed is in place.
Ǹow with Kotlin, I tried to extract something like
```
tasks {
    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = "1.8"
    }
}
```
to a script plugin. And now I would have to import KotlinCompile class. The very same thing happens when I try to extract things to the buildSrc project. This is expected because of the static compilation, but I wonder what's the recommended way to handle dependencies to classes from plugins in these situations. For script plugins, as well as for stuff in buildSrc project. We usually have multi project projects, just as a side note.

Is there any documentation I may have overlooked? What dependencies can I expect to be available in script plugins at all?

If you need any further information, versions, explanations or anything, please give me a hint.

Thanks in advance :)
Hannes

**Comment by lacasseio** [comment]
Could you clarify why this issue was marked as `a:regression`. From my understanding of the question, you are asking if you can use the following Kotlin code without importing `KotlinCompile`?
```
tasks {
    withType<KotlinCompile> {
        kotlinOptions.jvmTarget = "1.8"
    }
}
```

Groovy is a dynamic language so it will resolve the object type at runtime. However, if you annotate your Groovy code with `@CompileStatic`, it will require you to specify the types of that `compileKotlin` which will behave a lot like Kotlin by checking the types.

For questions, I encourage you to use the [user forum](https://discuss.gradle.org/) instead.

**Comment by lacasseio** [comment]
I asked about the `a:regression` label as I don't think it's a regression. I will close this issue now. Reopen if it's a real regression, but giving more information about the difference of behaviour across Gradle version (not between DSL language implementation).
