### ISSUE TITLE
Feature Request: Allow fine grained task logging control with SFL4J integration

### ISSUE THREAD

**Issue by samsieber** [gradle/gradle#1058]
It would be great if the logger provided by task.getLogger() was unique to that task, and if you could add add libraries to the task path.

### Expected Behavior
I should be able to specify jars that are SFL4J bindings as build script dependencies to force gradle into using custom loggers. It'd be great if I could use custom loggers as written in the buildSrc folder as well, as opposed to being defined in a jar.

Additionally, when I call task.getLogger(), I'd like to get a unique logger.

Lastly, the ability to add / remove appenders on a per-task basis (or the logger for any other logger) would be great. 

### Current Behavior
The logger from task.getLogger() is the same logger across all tasks, and there is no way to add appenders.

### Context
We run CI using about a dozen subprojects and we running using the --parallel flag so we can keep build speeds down to a reasonable time. However, when something fails, it's not very easy to go back and figure out what failed - with tests, it's not too bad because of test reports, but with any custom task or compiling code, it's hard to track down the cause. We usually end up rerunning the build locally without the --parallel switch so we can grok the logs.

What I'd like to be able to do is to record one log file for every task OR even just the logs of every task that failed to their own log files. That'd make it really easy to track down build failures and their causes.

Additionally, it seems like people have been asking this from the digging around I've done:

https://discuss.gradle.org/t/how-do-i-add-an-appender-to-the-gradle-logger-via-a-plugin/3733
https://github.com/gradle/gradle/blob/master/design-docs/improved-logging.md

**Comment by eriwen** [comment]
@samsieber Thank you for the well written issue, it is appreciated. We will probably have to make this an `epic` and split this up into multiple features. 

I believe that very many users (including myself) would benefit from this, especially as we improve parallelism in Gradle builds, so I'm giving this a 👍 

IIUC, we used to have unique loggers per task, but we found that it came at significant performance cost and so had to flatten our Logger structure. 

Managing appenders is complex due to our ClassLoader structure (at least it is to me) and I haven't figured out a model that gives users fine grained control of logging without introducing significant DSL complexity or complexity in Gradle itself. 

We are thinking about how to make this better, and will probably start with small steps like the ability to customize the log format such that you can, say, have task names prepended to each log statement; that would make your `--parallel` build at least more `grep`-able.

**Comment by samsieber** [comment]
@eriwen The prepending with task name would be awesome. It would solve most, if not all, of our needs since it makes all types of post-processing possible.

**Comment by eriwen** [comment]
@samsieber Thank you for the feedback, and stay tuned :)
