### ISSUE TITLE
Add some examples to Checkstyle section of manual.

### ISSUE THREAD

**Issue by huxi** [gradle/gradle#1060]
I had a hard time configuring the `checkstyle` plugin in a multi-module scenario.

The multi-module scenario has a hidden trap where everything works if `check` is executed from the root of the directory but fails if executed from one of the submodule-directories if referenced files aren't specified using a placeholder containing the checkstyle configuration directory.

The main issues I was facing were how to configure the filename of `suppressions.xml` in `checkstyle.xml` and how `configProperties` are supposed to be used in the XML.

Javadoc of `configProperties` just states "The properties available for use in the configuration file. These are substituted into the configuration file." so one has to guess/hope that `${propertyName} ` will work - which it does.

Because of that, I'd suggest to add something *like* the following example to the **Checkstyle** section of the manual. It would have helped me a lot.

## `build.gradle`
```groovy
subprojects {
	apply plugin: 'checkstyle'
	
	checkstyle {
		configFile = rootProject.file('config/checkstyle/checkstyle.xml')
		configProperties = [
				'configDir': rootProject.file('config/checkstyle'),
				'baseDir': rootDir,
			]
		toolVersion = '7.3'
		//ignoreFailures = true
	}
}
```

## `/config/checkstyle/checkstyle.xml`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC
    "-//Puppy Crawl//DTD Check Configuration 1.3//EN"
    "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">
<module name="Checker">
	<!--
		If you set the basedir property below, then all reported file
		names will be relative to the specified directory. See
		http://checkstyle.sourceforge.net/config.html#Checker
	-->
	<property name="basedir" value="${baseDir}"/>
	<property name="charset" value="UTF-8"/>
	<property name="localeCountry" value="US"/>
	<property name="localeLanguage" value="en"/>
	<property name="fileExtensions" value="java, xml, properties"/>
	<module name="SuppressionFilter">
		<property name="file" value="${configDir}/suppressions.xml"/>
		<property name="optional" value="false"/>
	</module>
	<module name="TreeWalker">
		<module name="IllegalImport"/>
		<module name="UnusedImports"/>
		<module name="AvoidStarImport"/>
		<module name="UpperEll"/>
		<module name="ArrayTrailingComma"/>
	</module>
	<module name="NewlineAtEndOfFile">
		<property name="lineSeparator" value="lf"/>
	</module>
</module>
```

## `/config/checkstyle/suppressions.xml`
```xml
<?xml version="1.0"?>
<!DOCTYPE suppressions PUBLIC
	"-//Puppy Crawl//DTD Suppressions 1.1//EN"
	"http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">
<suppressions>
	<suppress checks="ArrayTrailingComma" files="generated"/>
</suppressions>
```

**Comment by snodnipper** [comment]
Totally agreed that examples should be part of the documentation.

I'd also go further, gradle should encourage best practice by including code quality plugins in project generation code - e.g. `gradle init --type java-library`

**Comment by ljacomet** [comment]
Sorry for the late reply

This is a valid documentation issue.

**Comment by lkasso** [comment]
Closing this as resolved. The Checkstyle plugin chapter now includes comprehensive, tested, working examples in both Groovy and Kotlin DSLs, covering usage, dependency management, configuration, Java toolchains, built-in variables, and HTML/SARIF reports.

This was addressed incrementally across several releases:

- Worked Groovy + Kotlin DSL examples since **5.0** ([`[2b26f36](https://github.com/gradle/gradle/commit/2b26f360443)`](https://github.com/gradle/gradle/commit/2b26f360443))
- Worker memory configuration example in **8.0** ([`[af346d1](https://github.com/gradle/gradle/commit/af346d14ad8)`](https://github.com/gradle/gradle/commit/af346d14ad8))
- SARIF report docs in **8.1** ([`[2a131c4](https://github.com/gradle/gradle/commit/2a131c47b94)`](https://github.com/gradle/gradle/commit/2a131c47b94))
- Java Toolchains guidance in **9.0** ([`[13976d2](https://github.com/gradle/gradle/commit/13976d22057)`](https://github.com/gradle/gradle/commit/13976d22057))
- Examples converted to tested snippets in **9.6** ([`[26e6701](https://github.com/gradle/gradle/commit/26e6701f857)`](https://github.com/gradle/gradle/commit/26e6701f857))

See the current [[Checkstyle plugin documentation](https://docs.gradle.org/current/userguide/checkstyle_plugin.html)](https://docs.gradle.org/current/userguide/checkstyle_plugin.html). Setting milestone to **9.6.0**.
