### ISSUE TITLE
Allow a task to be registered for each task that matches some criteria

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#10639]
For example, allow build logic to register a report task for each test task, without realizing either task until required.

The implementation should also work for any kind of container that supports registration.

**Comment by mcumings** [comment]
I just encountered this as well.

In my scenario, I'm attempting to add a finalizer task to all instances of a task type I do not own/control.  The problem I've encountered is that all of the task  configuration avoidance APIs deal in `TaskProvider` instances, which implies that I have foreknowledge of the task name,  which in my case I do not.

Typically, a `Plugin` would register a task to obtain a `TaskProvider` instance, then use `TaskCollection#named` to obtain another task's `TaskProvider` instance, at which point the two instances can be linked with a `dependsOn` call without having to perform the linkage at configuration-time.

Because I do not know the task names and the task may appear in an unknown number of instances per Project, my Plugin cannot leverage this approach, since I do not know how many instances of my task I'd need to create, nor do I know the names of the tasks I need to link to.  All that remains are configuration-time approaches and workarounds, which are sub-optimal.

What I had envisioned as a hypothesized solution was a method being added to `TaskCollection` such that I could call `project.tasks.whenRegistered` to gain knowledge of the task name and type.  Perhaps `whenRegistered` would invoke its callback and provide `TaskProvider` instances which have been extended to be able to expose the type, i.e., `TaskPovider#getTaskType()`.  At that point we'd have the name and the type and could call existing API to stay within the confines of task configuration avoidance.
