### ISSUE TITLE
Merge `ExtensionContainer` with other named domain object containers

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#10658]
These two containers do essentially the same thing, but in very different ways.

How do we register public/implementation types in named domain object containers?  This is something the extension container can do.

How do we keep track of public types in named domain object containers? This is something the extension container does.

**Comment by trejkaz** [comment]
And: how do we get lazy configuration in the extension container? This is something that named domain object containers do. :)

**Comment by lacasseio** [comment]
To add on @trejkaz comment, there is still a missing feature of deriving values in once container from another container. Because of this, it's only recommended to use the lazy configuration on the `TaskContainer`. It's still a valid reason to move toward a single type of object containers so we can move toward fully lazy builds.
