### ISSUE TITLE
Question: Obtain Scala library version from a Plugin

### ISSUE THREAD

**Issue by adrianbn** [gradle/gradle#10784]
Hi,

this is an unusual case, so please bear with me while I describe the setup.

One of the static analysis vendors we use requires us to add a dependency to the projects being scanned that looks like the following:
```groovy
dependencies {
  vendorSCAPlugin group: 'com.vendor', name: "scala-plugin_${scalaVersion}", version: vendorSCAPluginVersion, classifier: "assembly"
}
```

As you can see, the Scala Version is required to resolve the dependency. Due to internal constraints, _we can't modify the build code of our dozens of development teams and hundreds of projects_ to add the dependency and carry out the static analysis. The solution we came up with was to use an Init script that does something like this:

```gradle
class SCATranslate implements Plugin<Gradle> {
    private static scaVendorPluginVersion = '1.0'

    void apply(Gradle gradle) {
        gradle.taskGraph.whenReady {
            gradle.allprojects { project ->
                /*
                * Multiple scala versions will break the translation so to be on the safe side we stick with the first one found
                */
                if (null == this.scalaVersion) {
                    this.scalaVersion = getScalaVersion(project)
                }

                if (null != this.scalaVersion) {
                    dependencies {
                        scaVendorPlugin group: 'com.vendor', name: "scala-vendor_${this.scalaVersion}", version: scaVendorPluginVersion, classifier: "assembly"
                    }
                }
            }
        }
    }

    private String getScalaVersion(Project scalaProject) {
        try {
            // apply default scala plugin to access scalaRuntime (should be already there most of the time but just in case)
            scalaProject.plugins.apply("scala")

            def configs = scalaProject.configurations.findAll { it.name == "play" || it.name == "compile" }
            def dependencies = configs.inject(new java.util.LinkedHashSet()) { acc, elem -> acc.addAll(elem.resolve()); acc }
            def runtime = scalaProject.scalaRuntime
            def scalaClasspath = runtime.inferScalaClasspath(dependencies)
            def compilerJar = runtime.findScalaJar(scalaClasspath, "compiler")
            def version = compilerJar ? runtime.getScalaVersion(compilerJar) : null

            return version
        } catch (Exception ignored) {
            return null
        }
    }
}
```

As you can see, we use the Scala Runtime present in the project's dependencies to determine the Scala Library version. I understand that resolving the configurations in this way is not always safe, but we haven't found a better way to go about it. Nonetheless, this has worked well for us up until the introduction of the `implementation` and `api` configuration labels.

It turns out neither `implementation` nor `api` allow direct resolution, making the above code fail. Even when forcing the resolution via `setCanBeResolved(true)` there would be a cascade of errors ensuing, mostly referencing

```
org.gradle.api.InvalidUserDataException: Cannot change role of configuration ':project_name_2.12:<configuration>' after it has been resolved.
```
My understanding is that this is project dependent and that it won't fail for every project out there, but it does for us since many of our developers' projects have a far amount of gradle code. As more and more projects migrate to the new `implementation` / `api` definitions, we're having more and more trouble to operate our static analysis solution. 

My question is, is there a way to obtain the Scala version at runtime when using the `implementation` / `api` configurations as there was for `compile` / `play`? If there is a better way to go about this given our constraints we'd be happy to implement those changes as well. Honestly, any help is welcome. Thank you!

### Expected Behavior
The Scala Runtime version is returned.

### Current Behavior
Either the configuration cannot be resolved directly, or when forced, an exception is thrown such as:
```
org.gradle.api.InvalidUserDataException: Cannot change role of configuration ':project_name_2.12:compile' after it has been resolved.
```

### Context
See above. 

### Steps to Reproduce 
Still trying to create a smaller reproduction sample that does not require publishing some of the internal code and dependencies.

### Your Environment
Gradle version: 5.6.2
Build Scan Plugin version: 2.3
OS: OSX 10.14.6
JDK: 1.8

**Comment by ljacomet** [comment]
Since Gradle 3.4 you can use instead the `compileClasspath` and/or `runtimeClasspath` configurations for doing what you need with a resolution of the configuration.

But as users need to add a dependency to the `scala-library` for their projects, maybe you do not need the resolution step and can instead use `runtimeClasspath.allDependencies` which will give you all the _declared_ dependencies found in _all_ the configurations that contribute to the `runtimeClasspath`.

An alternative would be to leverage the `scalaRuntime` extension, see [its javadoc](https://docs.gradle.org/5.6.2/javadoc/org/gradle/api/tasks/ScalaRuntime.html)

**Comment by ljacomet** [comment]
Reading once more your setup, you should not have to do this once the task graph is ready but instead use a `pluginManager.withPlugin('scala')` which will only do the required computation once the scala plugin is applied. Though the computation may have to be `afterProjectEvaluated` so that the dependencies have indeed been added.

Another path could be to do this computation after the scala compile task has run but before your tool's task runs. Then you know everything is in place for computing.

**Comment by adrianbn** [comment]
Hi @ljacomet,

thank you for the responses. As for your first post, I'm already using `scalaRutime`, but still requires the configurations to be resolved, which causes the problems described in the original post.

I'm not sure I understand the suggestion on the second post, could you elaborate how would that change the code I pasted? I definitely need to do this before the scala compile task has run, since the dependency added interacts with it.

Thank you!

**Comment by adrianbn** [comment]
Hi,

I would love for any advice or way in Gradle to determine the scala version at runtime when `implementation` is used (see top post for whole story). This continues to be a problem and is becoming more and more of an issue the more teams move onto new Gradle versions and the use of `implementation`.

Thanks!

**Comment by ljacomet** [comment]
With Gradle 6.0 the team has attempted to clarify the [different kind of configurations](https://docs.gradle.org/6.4/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs):
* `implementation` is a bucket of dependencies, that cannot be resolved.
* `compileClasspath` on the other hand is made to be resolved and combines the declarations of `implementation` and other dependency buckets.

So the easiest path for you is to move to resolving `compileClasspath`.

If that causes trouble because the configuration is resolved and then other project configurations elements attempt to add more dependencies later, then you could also create a resolvable configuration, with [the right attributes](https://docs.gradle.org/6.4/userguide/variant_attributes.html), that extends `compileClasspath` (so you get the same hierarchy) and resolve that.

[This code](https://github.com/gradle/gradle/blob/296f27a819d63081eb8b7fd1cf7d59a2585f2928/subprojects/plugins/src/main/java/org/gradle/api/plugins/internal/JvmPluginsHelper.java#L232-L236) shows how we setup such configurations internally.

**Comment by adrianbn** [comment]
Hey @ljacomet ,

thanks for the insights. I should have posted here but I forgot. I figured out that I should use `compileClasspath` and moved on with the project but didn't remember the case was open. This is solved and can be closed. Thank you for all the support.

Cheers

**Comment by ljacomet** [comment]
Great, good to know! And happy to hear you were not stuck on this ... took me a while to get back here 😞
