### ISSUE TITLE
HTML5 JavaDoc is not reproducible in OpenJDK

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#10782]
### Expected Behavior

There should be a way to generate reproducible JavaDocs.
Unfortunately, HTML5 mode uses javascript-based full text search, and it works off a `.zip` (!) file that is generated by `javadoc` and placed inside `javadoc.jar`.

See https://github.com/openjdk/jdk/blob/341090a3a42a7e878b4cd27df62a1713572a1480/src/jdk.javadoc/share/classes/jdk/javadoc/internal/doclets/formats/html/AbstractIndexWriter.java#L499-L502

### Current Behavior

HTML5 javadoc is not reproducible even when timestamps are turned off.

Of course the issue has to be resolved at OpenJDK level (I'll try to push a patch there), however it would taker a while for everybody to move to Java 15, so I suggest Gradle could implement a workaround by repacking the zip file and resetting its timestamp and so on.

Having reproducible javadoc artifacts might slightly improve overall build cacheability.

### Context

Javadoc is often included to software distributions (e.g. binary distribution of Apache JMeter).
The sad thing is the build becomes non-reproducible due to javadoc-generated zip file.

### Steps to Reproduce 

```kotlin
            withType<Javadoc>().configureEach {
                (options as StandardJavadocDocletOptions).apply {
                    noTimestamp.value = true
                    showFromProtected()
                    docEncoding = "UTF-8"
                    charSet = "UTF-8"
                    encoding = "UTF-8"
                    docTitle = "${project.name} API"
                    windowTitle = "${project.name} API"
                    header = "<b>${project.name}</b>"
                    addStringOption("source", "8")
                    addBooleanOption("html5", true) // <-- this activates HTML5
                    links("https://docs.oracle.com/javase/9/docs/api/")
                }
            }
```

### Your Environment

Gradle 5.5.1

**Comment by lptr** [comment]
The impact of this on caching is negligible in a typical setting. For this to cause significant cache misses you'd have to have some cacheable task consuming the Javadoc `.jar` file, which we haven't yet seen much in the wild.

As you mention, there is an easy workaround to repackage the archives if the problem is severe. It can be done by using an artifact transform or a task. Again, if we see many use cases where this causes extra trouble, we could ship such a transform built-in, but I doubt this will be the case.

If we had to do something about unreproducible archives on our end, instead of "fixing them up" post production, I'd push for extending `@Classpath` normalization and allowing users to declare inputs in a way that archive timestamps are ignored for caching purposes.

For making sure the whole build is reproducible I'd wait for the fix on the JDK side. Thanks for pushing that.

**Comment by vlsi** [comment]
>I'd push for extending @Classpath normalization and allowing users to declare inputs in a way that archive timestamps are ignored for caching purposes.

That does not help reproducibility.
In other words, if a developer claims that they build sources from Git SHA cafebabe... and the resulting binary has SHA512 of deadbeef..., then it should be verifiable.
Normalization won't help there because the artifact is already broken (it is different every time).

Unfortunately, `html5` is what Gradle documentation suggests: https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:complete_example

```kotlin
tasks.javadoc {
    if (JavaVersion.current().isJava9Compatible) {
        (options as StandardJavadocDocletOptions).addBooleanOption("html5", true)
    }
}
```

Of course extra treatment can be added on a project-per-project level, however making "non-reproducible builds" by default is really sad (especially taking into account that Gradle itself has unit tests on the SHA of the produced binaries).
