### ISSUE TITLE
CheckableComponentSpec.checkedBy silently fails to run if TestingModelBasePlugin is not applied

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#10851]
### Expected Behavior
The tasks added to `checkedBy` get ran no matter what plugins are applied.

### Current Behavior

The tasks added only get ran if `TestingModelBasePlugin` is applied.

TestingModelBasePlugin adds the lifecycle check task to all binaries, however this plugin is not added by default when a component is added. So a component can have check tasks added to it without the test plugin being applied, but the check tasks just will not get ran, and just silently not run.

**Comment by lacasseio** [comment]
Thank you very much for this issue. Unfortunately, this issue deal with the Software Model which is on limited development. To extract something more meaningful out of this issue would you mind sharing your use case for using the `TestingModelBasePlugin`? Are you implementing your own testing framework support? If so, which testing framework are you adding?

We will look at solving those issues instead of this one given the Software Model is being phased out.

**Comment by ThadHouse** [comment]
I'm not implementing my own testing framework, and wasn't actually using `TestingModelBasePlugin` for anything. I was just adding a check task to check that the right symbols were generated by using `checkedBy`, and was noticing that the check task just occasionally wasn't running, but some times it was. Finally traced that down to the check task being null, and found the lifecycle check task was only created when `TestingModelBasePlugin`, and not when the actual component was created.

**Comment by ThadHouse** [comment]
The trivial fix is to move this function

https://github.com/gradle/gradle/blob/3ddd28435a432942446ca2f65e7f4c9b6867fef8/subprojects/testing-base/src/main/java/org/gradle/testing/base/plugins/TestingModelBasePlugin.java#L81

to the base native plugin, so it gets ran whenever any native binary is added. That way functions added to `checkedBy` work without needing a testing base applied.
