### ISSUE TITLE
Improve CLI Project Properties User Experience

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#1088]
### Expected Behavior
Project properties passed by CLI flags should have these added features:
1. Use existing `Project` properties setter method; or
2. Produce a warning to the user for existing read-only properties

In the second case, the CLI property value will be ignored.

No breaking change will be introduced with this work. It serves to notify the user about property that may be ignored due to read-only properties already present on the `Project` object.

#### Example 1
When:
`$ ./gradlew :some:task -PbuildDir=/some/path`
Then:
```
project(':some') {
  assert buildDir == '/some/path'
}
```

The property `buildDir` on `Project` will be updated because [`Project.setBuildDir`](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/Project.java#L258-L265) is available.

#### Example 2
When:
`$ ./gradlew :some:task -Pname=someName`

A warning message will be printed explaining the CLI property `name` will be ignored because `Project.setName` doesn't exists.

### Current Behavior
In any of the cases where a property already exists in `Project`/`ProjectInternal` and implementations/super classes, the provided CLI property value will be ignored which is confusing for the user as expressed in issue https://github.com/gradle/gradle/issues/1072.

### Context
This issue addresses the discussion regarding https://github.com/gradle/gradle/issues/1072.

### Open Issues
- Should we limit this feature only to `Project` (public API) and threat internal API setter as read-only?
- Should the provided value be the default values or overwrite whatever was set by the build script? _Note that overwriting may be tricky as some other configuration closure may already be using the property._

**Comment by samsieber** [comment]
We use custom project properties to override some predefined configuration. If I'm reading correctly, this proposal makes that a no-no.

If I did read this right, and there's no other preferred way for passing in custom values from the command line, I would rework the proposal to allow for:
1. Use existing Project properties setter method; 
2. Use a property name register in a build script
3. Produce a warning to the user for existing read-only properties

Our use case is that we use a ConfigSlurper to read a config file into an object and we use that config object all over the place. We have some support code in place that allows us to specify a property name and the corresponding config object path that it should override - not quite a DSL, but a handy function we wrote because we use it so often.

I think using calls to the hasProperty / getProperty methods to register the property names as valid would work.

**Comment by lacasseio** [comment]
Sorry for the confusion @samsieber. The properties will/should behave like it behaved in previous Gradle version. The only assertion we will be adding is making sure we use setter when available (to ensure the properties aren't ignored) and producing a warning if the property exists but is read-only (to notify the user that a property is ignored).

Everything else we work as expected. In fact, no breaking change should happen with this work. We simply want to provide a clear message when there is a property collision that we can't fix.

Thanks for the input, I will change the description to reflect what was discuss here.
