### ISSUE TITLE
Reproducible WAR builds cause issues with Tomcat caches

### ISSUE THREAD

**Issue by joankaradimov** [gradle/gradle#10917]
### Expected Behavior
Gradle could expose an option for explicit timestamps in generated archives when doing reproducible builds.

### Current Behavior
Archive tasks have options that facilitate reproducible builds: `reproducibleFileOrder` and `preserveFileTimestamps`. But the `preserveFileTimestamps` option always puts the same hard-coded date in the archives.

### Context
When a war generated by gradle with the said flags is exploded by Tomcat, the zip timestamps are preserved. When Tomcat sees the timestamp coming from `preserveFileTimestamps` it does not bother to look at the file contents. It then decides that the file in unchanged and it generates the same etag in responses. 

Here's a [thread](https://mail-archives.apache.org/mod_mbox/tomcat-users/201909.mbox/%3c615FC777-A449-4EE7-A882-08B39142D693@apache.org%3e) in the Tomcat mailing list referring to the problem.

I've implemented the option in gradle, called it `timeForArchiveEntries`, built it, and tested it like that:

```groovy
war {
	reproducibleFileOrder = true
	preserveFileTimestamps = false

	def time = 'git log -1 --format=%cd --date=format-local:%Y-%m-%dT%H:%M:%S.00Z'.execute(['TZ=UTC'], null).text.trim()
	timeForArchiveEntries = Date.from(Instant.parse(time))
}
```

It correctly sets the timestamps for archive entries. If the suggestion sounds good, I can write some integration tests and documentation and make a PR.

**Comment by joankaradimov** [comment]
I'm not sure that the `@build-cache` label is correct. I'd assume it's for gradle's internal caches. And this is about the Tomcat cache handling.

Anyway, my WIP can be seen [here](https://github.com/joankaradimov/gradle/commits/explicit-archive-timestamp).

**Comment by wolfs** [comment]
@joankaradimov Currently, we don't want to support setting an archive entry timestamp which is used for reproducible archives. The main reason for this is that it is hard to obtain a timestamp which is the same across different timezones, operating systems and servers. It also somewhat defeats the idea behind reproducible archives since you also would need to find out the timestamp which was set for the archive entries so you actually can reproduce it.

It seems like Tomcat doesn't seem to work well with reproducible archives. Why can't you use non-reproducible archives? What are you trying to achieve by using reproducible WARs in the first place?
