### ISSUE TITLE
Project#afterEvaluate cannot be executed in current context

### ISSUE THREAD

**Issue by jfbibeau** [gradle/gradle#10923]
Raising this as per @lptr 's request. We've been running into more and more issues with `Project.afterEvaluate` when switching to the lazy task configuration API. Here's a sample reproduction scenario, I'd like confirmation whether this is working as expected or whether this is a bug in Gradle (note that if you remove the `doCopy` task everything works fine..?)
```
plugins {
  id "com.github.node-gradle.node" version "2.1.1"
}

tasks.register('runSomething', YarnTask) {
    args = ['run', 'anything']
}

tasks.register('doCopy', Copy) {
    from runSomething
}
```

Run `./gradlew doCopy`

### Expected Behavior
Even though the plugin's `YarnTask` calls `project.evaluate {...}`, I'm not sure of the reason why this wouldn't work.

### Current Behavior
Exception in configuration phase:
```
> Could not create task ':projectA:doCopy'.
   > Could not create task ':projectA:runSomething'.
      > Could not create task of type 'YarnTask'.
         > Project#afterEvaluate(Closure) on project ':projectA' cannot be executed in the current context.
...
Caused by: org.gradle.api.internal.AbstractMutationGuard$IllegalMutationException: Project#afterEvaluate(Closure) on project ':projectA' cannot be executed in the current context.
        at org.gradle.api.internal.AbstractMutationGuard.createIllegalStateException(AbstractMutationGuard.java:39)
        at org.gradle.api.internal.AbstractMutationGuard.assertMutationAllowed(AbstractMutationGuard.java:34)
        at org.gradle.api.internal.project.DefaultProject.assertMutatingMethodAllowed(DefaultProject.java:1434)
        at org.gradle.api.internal.project.DefaultProject.afterEvaluate(DefaultProject.java:1005)
        at org.gradle.api.Project$afterEvaluate.call(Unknown Source)
        at com.moowork.gradle.node.yarn.YarnTask.<init>(YarnTask.groovy:29)
        at com.moowork.gradle.node.yarn.YarnTask_Decorated.<init>(Unknown Source)
```

### Context
We have other issues where Gradle complains about `project.evaluate` as more and more things are switched to the lazy task configuration API, this is the simplest repro scenario I could think of. The use cases where `project.evaluate` is safe to use is not clear. 

### Steps to Reproduce 
See above.

### Your Environment
```
------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.2 (Oracle Corporation 11.0.2+9)
OS:           Mac OS X 10.14.6 x86_64
```

**Comment by lacasseio** [comment]
With the lazy APIs, we tried to lock down what we consider to be unsafe. Practically, `afterEvaluate` differ some action as do `register` so it doesn't make sense to call `afterEvaluate` from a `register`. The `register` is also not a straight one-to-one replacement of `create` so you may need to refactor some code to avoid unsafe behaviours. Looking at the code used inside the constructor of `YarnTask`, I can confirm that Gradle is correct. The quick solution would be to move the content of `afterEvaluate` to the `@TaskAction` annotated method. If some other task depends on some of the behaviours before the execution time, it would be recommended to migrate toward the Provider API so you can bind some values in a much better way.

I will close this issue as working as expected. The real issue here is about the documentation aspect of the lazy task APIs. Would you care to share your experience on what you which the documentation would mention or any other piece of information that would help you migrate to these new APIs?

**Comment by jfbibeau** [comment]
Thank you @lacasseio, I've passed your feedback along to the plugin owner. I can't think of any specific examples of documentation being misleading, but should `project.evaluate` be deprecated if it's not compatible with the lazy task configuration API?

**Comment by dcabasson** [comment]
+1 with @jfbibeau on the depreciation. If `project.afterEvaluate` is going to break in very unexpected way depending on when projects are loaded, I think plugin developers should be strongly discouraged from using it.
