### ISSUE TITLE
Cannot apply a plugin to itself

### ISSUE THREAD

**Issue by CristianGM** [gradle/gradle#10921]
I cannot apply the last published version of a plugin to itself

### Expected Behavior

just to work

### Current Behavior
> Could not apply requested plugin [id: 'jacoco-convention', version: '1.0'] as it does not provide a plugin with id 'jacoco-convention'. This is caused by an incorrect plugin implementation. Please contact the plugin author(s).
> 
> &gt; Plugin with id 'jacoco-convention' not found.

### Context

I want to apply the last published version of a plugin to itself for dogfooding but Gradle fails to find the plugin.

### Steps to Reproduce 

https://github.com/CristianGM/plugin-inception-kts
as pointed on the readme ( @eskatos found the workaround ) it seems related to having the group in the `gradle.properties`

### Your Environment

Build scan URL:

**Comment by ejjcase** [comment]
I was about to report the same thing: https://github.com/ejjcase/dogfood-plugin

Is Gradle looking for the plugin in the project's own `buildSrc`?  Surely it shouldn't do that if the version doesn't match.

**Comment by TheMrMilchmann** [comment]
I feel bad for necroing this issue, but I've been running into this recently. I wonder if this could be reconsidered now because this is more relevant now in light of the growing relevance of convention plugins.

I have two(-ish) real-life use cases where proper support for this would be useful right now:
1. I have a handful of convention plugins (including for publishing) that I would love to use for their own builds.
2. I have a plugin that is essentially used for API compatibility testing and would like to use previous versions to verify the plugin itself.

(I guess this is related to #1629)

**Comment by ov7a** [comment]
Sorry for the late reply

This issue is no longer reproducible since 9.0.0
