### ISSUE TITLE
OOM building large project with JDK13

### ISSUE THREAD

**Issue by dpeger** [gradle/gradle#11097]
I'm working on a large Java project (139 sub-projects, ~950k lines of code). With gradle 6 (latest nightly - as the time of writing - 6.0-20191020230029+0000) and JDK13 I can see that the memory consumption significantly increased when building the project. With gradle 6 and JDK12 the build consumes round about 750 MB heap (build is started with `-Xmx1024M`) but with JDK13 this results in an out of memory error during the build. When started with 2GB heap, the build succeeds but has a peak heap usage of up to 1.7GB.

In a heapdump I can see that half of the memory on OOM (>500MB) is accumulated in the `pathsAndContainersByLocationAndRelativeDirectory` HashMap member in a single instance of `com.sun.tools.javac.file.JavacFileManager`.

I'm unsure if this is a JDK or gradle issue. So any help would be appreciated.

[gc_gradle.log](https://github.com/gradle/gradle/files/3751402/gc_gradle.log)

**Comment by big-guy** [comment]
It looks like that map is new in JDK13:
https://bugs.openjdk.java.net/browse/JDK-8220792
http://hg.openjdk.java.net/jdk/client/rev/3326be37cd9a

Since you're seeing a single instance of `JavacFileManager` taking a lot of memory, that probably means it's a single compile task that's running into this.  If you could figure out which it is, it would help find a test case to reproduce the failure, e.g. how many source files, how many jars on the compile classpath, etc.

If you give the build 2GB and run it multiple times, does it eventually fail again? 

Would you be able to share a heap dump?

**Comment by dpeger** [comment]
I was able to pin it down to a single project (and it's dependencies of course - however the dependencies build fine).

This project hat ~ 64.500 LOC and 478 compilePath dependencies (117 of which are projects). It's a functional testing project that depends on nearly everything of the built application.

I tried to create a MVCE but a multiproject build with 200 subprojects and a single aggregator project (resulting in 510 unique compilePath dependencies) that depends on all subprojects did not encounter the observed OOM. However each of these projects contains a single Java file only...

Sharing a heapdump of the actual project is not an option - sadly.

But I can share some screenshots of my findings:

**Path 2 GC roots that I got from a full build on the root project**
![path2gc_01](https://user-images.githubusercontent.com/8697665/67303222-6bd69a00-f4f2-11e9-906c-094e75e39799.png)

**Path 2 GC roots that I got from a build of the failing project only**
![path2gc_02](https://user-images.githubusercontent.com/8697665/67303372-ae987200-f4f2-11e9-8917-48d9170a89b8.png)

The paths in the second screenshot look kind of odd as it look like the worker thread is holding a direct reference to the 750MB `HashMap$Node`. In the first screenshot one can clearly see that `JavacFileManager` is holding the problematic reference.

**Map Contents Example**
![2019-10-22_18h01_37](https://user-images.githubusercontent.com/8697665/67306003-8d398500-f4f6-11e9-96d3-b9e3e859304f.png)

The single `HasMap$Node` is linked to 5,539 other nodes each of which has a list with over 17,000 entries as value.
The contents of the map look somehow awkward as well. As you can see in the above screenshot the key `io/netty/handler/traffic/` is referenced by a path `C:\...\<project-name>\build\libs\bsh-2.0b6.jar`. The strange thing is that the library `bsh-2.0b6.jar` is not copied to the project's build-libs folder. The only jar in this folder is typically the `<project-name>-<version>.jar` file. However there are thousands of these references for each project.

Perhaps this already provides some insights to you?! I there is more I can provide, please let me know.

**Comment by big-guy** [comment]
Hrm, I've tried to reproduce it locally too.   Which version of JDK13 are you trying with?  Is it OpenJDK or Oracle or some other vendor?

I don't believe the JavacFileManager are shared across compilation tasks, so I think the number of files being compiled by a single task may make a big difference.  Could you try to generate the same number of Java files that you have in the failing build for the JavaCompile task that fails?  I've tried 15k files, but I had a much simpler dependency graph.

Thanks for your help.

As a workaround for your situation, instead of increasing the amount of memory given to the Gradle process, you could make Java compilation use a separate daemon:
```
tasks.withType(JavaCompile) {
   options.fork = true
}
```
The separate compiler daemon defaults to 512MB max memory, so it might need a bit more, but that can be controlled separately from the Gradle daemon itself.

**Comment by dpeger** [comment]
We are using OpenJDK 13.0.0

I was able to create an example project setup that compiles fine with OpenJDK 12.0.1 and goes OOM with OpenJDK 13.0.0. But the resulting heapdump look different compared to the one I got from our actual project.

The example setup has 200 subprojects each with 1000 Java files and a single project that has all of the subprojects as compileClasspath dependency ([zipped project](https://core.opentext.com/pdfjs/web/viewer.html?shortLink=72482d7e89afede22f86e16a56ce74d4a001634e466058af)). If you're interested in the heapdump I can upload the dump as well, but you're probably faster reproducing the problem yourself.

But as mentioned as the dumps look so different from what I get when building the actual project, I'm afraid this might be a different issue...
