### ISSUE TITLE
Potential memory issues caused by large cache size in CachingPatternSpecFactory

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#11114]
### Context

After upgrading AGP to `3.6.0-beta-01` we got memory issues and failures in `santaTrackerAndroidBuild` performance test:

```
Expiring Daemon because JVM heap space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
Expiring Daemon because JVM heap space is exhausted
```

It turns out to be [Android `OssLicensesPlugin` incorrectly using fileTree searching large directories](https://github.com/google/play-services-plugins/issues/106):

![image](https://user-images.githubusercontent.com/12689835/67396214-c0a11000-f5d9-11e9-8757-abc222e288ad.png)

Each pattern searches large transforms cache directory (which has nearly 30k files in my computer) - these 30k file paths will be cached in [`CachingPatternSpecFactory $CachingSpec.resultCache`](https://github.com/gradle/gradle/blob/3c8d919834f11a67472565b94d6e74c58fba40ce/subprojects/core-api/src/main/java/org/gradle/api/tasks/util/internal/CachingPatternSpecFactory.java#L63). 30+ such patterns can result in OOM in Gradle daemon.

@oehme Can we reduce the cache size? It seems like previously the overall result cache size is 1200K, then you changed "per pattern cache size" to 100K: https://github.com/gradle/gradle/commit/e3f5bac15364722cb55a46f9d896e6f748f9c20e
 . This seems still a little large in this situation.

CC @wolfs @big-guy

**Comment by blindpirate** [comment]
Branch: https://github.com/gradle/gradle/compare/blindpirate/decrease-cache-size

I'm wondering if we need to clean the cache in `CachingPatternSpecFactory
` or make them weak references.

**Comment by oehme** [comment]
Yeah, 10K results sounds like a more reasonable baseline. Also, supporting 30K instances seems totally overblown. How many patterns do we expect people to create? 100 maybe?

**Comment by adammurdoch** [comment]
We should reuse the `CrossBuildInMemoryCache` infrastructure to take care of caching the patterns, rather than reimplement another cross-build cache that behaves differently to the others. Then we have a centralized place to improve the strategies for cache sizing and cleaning up unused values and so on.

**Comment by big-guy** [comment]
For 6.0, could we reduce the size of the cache and put a proper fix in for 6.1?

**Comment by adammurdoch** [comment]
Absolutely.

**Comment by jjohannes** [comment]
Per discussion in the dependency management planing today, I move this to `6.1`. The PR shows that there is an impact on performance of our own scenarios and we have to investigate this deeper if we want to change something here.

@blindpirate will suggest to use another API in the licensing plugin so that the cache directory does not need to be scanned anymore. See: https://docs.gradle.org/5.6.2/userguide/working_with_dependencies.html#accessing_a_modules_metadata_file
