### ISSUE TITLE
Ignore mainClassName if --module is present

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#11124]
### Context

We did some changes in https://github.com/gradle/gradle/pull/11073 , which supports Java 9+'s `--module <module>/<main-class>`. However, the tests in that PR behave flaky after merging into `release`: https://builds.gradle.org/viewLog.html?buildId=28004642&buildTypeId=Gradle_Check_Quick_1_core_4 

There's an issue in the test, and Gradle also has a bug.

#### What's wrong in the test

Java 9+ allows `java --module <module>/<main-class> your java program parameters`. In this case, no main class name is needed. This test use empty string as "main class name", which is recognized by JVM as parameters:

```
            plugins {
                id 'application'
            }

            mainClassName = "my.module/io.greeting.HelloWorld"
            run {
                doFirst {
                    args = ['Gradle']
                    main = '' <----- This is wrong
                    jvmArgs = [
                        '-ea',
                        '--module-path', classpath.asPath,
                        '--module', mainClassName
                    ]
                    classpath = files()
                    println ":run Task's command line: $commandLine"
                }
            }
```

The result java command is `java -ea --module-path XXX --module my.module/io.greeting.HelloWorld '' Gradle`, that's why the test fails:

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:709)
	at my.module/io.greeting.HelloWorld.lambda$hasOnlyAppArgs$0(HelloWorld.java:21)
    ....
	at my.module/io.greeting.HelloWorld.main(HelloWorld.java:13)
```

#### What's wrong in Gradle

In this script, it's surprising that `JavaExec.getMain()` returns nondeterministic result: sometimes it returns "my.module/io.greeting.HelloWorld" via convention mapping, sometimes it returns empty string set by the script.

See https://github.com/gradle/gradle/issues/11125

```
            plugins {
                id 'application'
            }

            mainClassName = "my.module/io.greeting.HelloWorld"
            run {
                doFirst {
                    args = ['Gradle']
                    main = '' 
                }
            }
```

#### Proposed solution

For 6.0RC2, let's simply recognize `--module` and don't add main class name to the commands.

**Comment by lingocoder** [comment]
Hey @blindpirate, thanks for the heads-up. 

What you encountered is probably related to [*this strikingly similar flakiness*](http://bit.ly/FlakyMain) I reported a couple months ago.

In fact, the only reason I did *`main = ''`* in #11073's test, is because at first TestKit was reporting the same thing I encountered previously. 

It's from that experience, where I got the idea to set  *`main`*  to *anything* non-null. I did it just to appease the *flaky gods* of #10412— so to speak.

Thank you so, so much for this solution! I hope it also finally fixes the *`:run`* task's  flaky *`main`* once and for all :+1:

**Comment by big-guy** [comment]
I reverted the changes from #11073 for 6.0.  Since this is the RC period, I should have been more strict about what was going in, but I was hopeful that it would be small enough and not cause problems.  Since it has, we should avoid delaying the next RC/causing another RC.  

We can revisit this for 6.1.

**Comment by lingocoder** [comment]
I understand @big-guy. 

So, how likely is it that what @blindpirate's reporting here is caused by the same thing that's happening in #10412?

I recall [*what you and I talked about*](http://bit.ly/MyObjFact) in Slack back then...

>> „...*This is needed until we have a way to connect a Provider<String> to JavaExec's main property*...“

Same deal?

**Comment by jjohannes** [comment]
Will be superseded by the implementation for #12428 which will be worked on for 6.4.
