### ISSUE TITLE
Support for FileSystemLocation in InputChanges API

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#11163]
Currently (Gradle 5.6.3) the `InputChanges` API only supports `FileCollection` and `Provider<out FileSystemLocation>`.
If there is not a technical reason against, I'd like to suggest to also support `FileSystemLocation` directly and maybe even `Provider<out FileCollection>`.
Currently you for example cannot do
```kotlin
val inputDirectory = project
        .layout
        .projectDirectory
        .dir("src")
```
You need to do either
```kotlin
val inputDirectory = project.provider { project
        .layout
        .projectDirectory
        .dir("src")
}
```
or
```kotlin
val inputDirectory = project
        .layout
        .projectDirectory
        .dir("src")
        .asFileTree
```
while I think this should not be necessary.

**Comment by wolfs** [comment]
Thank you for reporting this issue. The `InputChanges` API allows querying for changes to an input property of a task. That means that the property needs to have an identity. `FileSystemLocation` is a value object, so it doesn't really have an identity.

The reason for the identity requirement is that Gradle needs to map the input property to a declared input property of the task. Doing this by value seems very brittle and we don't want to allow that in the future. The pattern should actually be that the task declares a `RegularFileProperty` or a `DirectoryProperty` which is then set to the corresponding input by the plugin creating the task. See also the [user manual](https://docs.gradle.org/current/userguide/custom_tasks.html#sec:implementing_an_incremental_task).

Regarding file collection: `Provider<FileCollection>` should never be used, since file collection is already a lazy type. You should declare a `final` (or `val`) ConfigurableFileCollection on your task type and then add any lazy constructs you want to it. What is your use-case for using a `Provider<FileCollection>`?

**Comment by Vampire** [comment]
Forget `Provider<FileCollection>`, it was just a side-thought.
My use-case was actually what I exampled above, having a `Directory` property.
In my case I don't have a plugin creating that task.
It is just a task for this one project and created in the build script directly, but only one instance will ever exist and the property does not need to be defined from outside, it can simply be defined inside the task as shown.

So now I use
```kotlin
val inputDirectory = project
        .layout
        .projectDirectory
        .dir("src")
        .asFileTree
```
(Actually even an added `.matching` as I only need a subset of the files in this case.)

I didn't understand why this is too much different to
```kotlin
val inputDirectory = project
        .layout
        .projectDirectory
        .dir("src")
```

But if you say it is a technical / conceptual limitation, just close this issue, I just wondered that it doesn't work with a `Directory` directly and that I either have to transform it to a `FileCollection` or wrap it in a `Provider`.
