### ISSUE TITLE
Cannot set custom attribute value of dependency

### ISSUE THREAD

**Issue by Lanchon** [gradle/gradle#11190]
I have to interact with this piece of code which I do not control and cannot change:

```
import static org.gradle.api.internal.artifacts.ArtifactAttributes.ARTIFACT_FORMAT

def view = config.incoming.artifactView {
    it.attributes.attribute ARTIFACT_FORMAT, MAGIC_VALUE
}
def result = view.artifacts.artifactFiles
```

Specifically, I control `config` and I need this piece of code to return a `result` (FileCollection) populated the way I choose (with my local files). But there seems to be no way in Gradle to define a dependency or configuration with a custom ARTIFACT_FORMAT attribute value.

My current work-around is declaring and registering an identity transform just to alter the ARTIFACT_FORMAT default value to a custom one.

Is there a way to directly declare a custom ARTIFACT_FORMAT attribute value for a dependency instead of relying on a transform? This does not work:

```
config.attributes.attribute ARTIFACT_FORMAT, MAGIC_VALUE
config.dependencies.add project.dependencies.create(project.files(...))
```

Thank you very much for your help!

NOTE: All tests were done with Gradle 4.10.3. But if a later Gradle version provides a solution for this, I am willing to upgrade.

**Comment by ljacomet** [comment]
Attributes defined on `artifactView`, `configuration` or even at the `dependency` level are all _consumer_ attributes. That is they help the Gradle dependency management engine figure out which variant of a dependency to select.

If you need artifacts to _expose_ specific attributes, you have to do that through their metadata. Usually this means using a `ComponentMetadataRule`. But a project `files` have no metadata and so that solution is not applicable.

In addition, the attribute `ARTIFACT_FORMAT` is somewhat special.

You might be able to trick the system by giving your files an extension that matches `MAGIC_VALUE`. But that would be nothing more than a trick.

Give your constraints, I am not sure of another solution.

Of course the ideal would be for you to be able to change that artifact view code, so it matches what you need.

**Comment by Lanchon** [comment]
Thank you very much.

> You might be able to trick the system by giving your files an extension that matches `MAGIC_VALUE`.

I cannot use this workaround: the code I am interacting with (which, FYI, is the Android Gradle plugin) expects a specific filename and extension for the files in question. Also,  does not exist outside the context of this code, so no extension is associated with the value.

(Also: I had seen before that Gradle assigns values to this attribute based on heuristics (say, extensions), but only observed this in Gradle >= 5.3. Gradle < 5.3 seems to always assign the empty string to this attribute. This change is worrisome for transform implementers. My current solution for handling this unspecified behavior is a task that resolves the configuration and extracts the attribute value from the result. Only then it registers a transform to reach `MAGIC_VALUE` from the extracted value. Way too hacky for my taste...)

> a project [local] files have no metadata

I have been bitten by this before in other contexts. It really looks like a general issue to solve. Having to abuse the transform mechanism to define metadata is horrible.

We can consider my issue solved, as I already have implemented the best workaround we could find. I am leaving it for you to close in case you want to file your own RFE based on this issue.

Thank you very much for your help!

**Comment by ljacomet** [comment]
Making changes based on this issue is not currently planned, closing
