### ISSUE TITLE
Provide a link to GitHub from new sample pages

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#11271]
Currently the new sample pages (e.g. https://docs.gradle.org/nightly/samples/groovyBasicApplication/) provide buttons to download zips in Kotlin and Groovy DSL which is good. We should also provide a way link to browse the sample in GitHub.

**Comment by pioterj** [comment]
On the other hand, we already inline the samples on the page with the Kotlin / Groovy switcher so perhaps it's not that important.

**Comment by big-guy** [comment]
I don't think we want to do this.  We don't want to limit the layout of the checked-in samples to be something that's "browsable" because some samples may be composed of several different parts.

We weren't planning on doing it now, but we had thought about making it so you could browse more of the sample's files on the sample page in a file browser-like structure.

**Comment by pioterj** [comment]
@big-guy Sounds good. I think that for some samples it matters more than others. For example in https://github.com/gradle-guides/gradle-site-plugin, the code is more important than the build files.
