### ISSUE TITLE
Support Build Cancellation in `JavaExec` Task

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#1128]
_Edit: Improved description to reference the more generic solution (build cancel event) as oppose to the specific usage of this feature (Ctrl-D) explained by [Gary's comment](https://github.com/gradle/gradle/issues/1128#issuecomment-271299381)._

### Expected Behavior
When `JavaExec` task waits for the completion of the Java application, it should support cancel event and terminate the Java application only. This exposes a deterministic build cancellation to Java shutdown hook execution delay to the user as well as avoid killing a perfectly healthy daemon. It would also be possible to support continuous mode for any `JavaExec` task.

### Current Behavior
`JavaExec` doesn't support cancel event. The only way to cancel an application ran through that task is to send a Ctrl-C which will cause the daemon to exit as the `JavaExec` task doesn't return:
1. There is a, up to, 10 seconds delay between Ctrl-C and the execution of the shutdown hook in the Java application
2. The `System.{out|err}` output of the Java application isn't piped to the console.

### Context
Initial discussion in https://github.com/gradle/gradle/issues/1109

### Steps to Reproduce (for bugs)
build.gradle:
```
apply plugin: 'java'
apply plugin: 'application'

mainClassName = 'Runner'
```

src/main/java/Runner.java
```
import java.io.File;
import java.util.Random;
import java.util.concurrent.CompletableFuture;

public class Runner {
    public static void main(String[] args) throws Exception {
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Clean shutdown");
        }));
        File lock = new File("LOCK" + new Random().nextInt(20));
        lock.createNewFile();
        lock.deleteOnExit();
        System.out.println("Created lock");
        new CompletableFuture<Void>().get();
    }
}
```

**Comment by pkubowicz** [comment]
One more comment: the 10s delay is not acceptable in many scenarios. For example when developing a server application you will frequently restart you application. You will require a fast restart and a clean restart, that leaves a coherent state.

Idea 2016.3 has an option to delegate run task to Gradle. Then, when you run the application, Idea executes 'run' for you, although you may not know what exactly is happening under the hood. When not using delegating, using the 'restart' button for a server app in Idea is smooth and fast. With delegating to Gradle, it often failed for me because of port still being used. Probably this is because Gradle daemon waits 10s but Idea starts a new build immediately. Also restarting feels not right, because you don't see console logs about server being stopped - again, because of the 10s delay of running shutdown hooks.

**Comment by ghale** [comment]
The 10s delay is a byproduct of the fact that the task never finishes.  What happens when you send a ctrl-c is that it terminates the daemon client.  The client disappearing then causes the daemon to cancel any running builds associated with that client.  The build cancellation logic (as it currently exists) checks in between tasks to see if the build has been canceled, so it relies on the currently running task(s) to complete before it can stop the build.  In this case, the `JavaExec` task never completes, so the 10s delay is the timeout on the daemon waiting for the currently `JavaExec` task to finish.  When this timeout expires, the daemon has no guarantee that the task will ever finish (in this case it won't) so it kills itself to clean up the resources.  

So, another way to handle this is to provide better mechanics for tasks to respond to cancellation.  For instance, allow tasks to register a cancellation hook so that when a cancellation occurs, we can notify a running task that we are waiting for it to finish and it could stop early rather than running to completion.  In the case of the `JavaExec` task, it could stop the child process and finish.  In the case of say a `Test` task, it could stop executing tests. Etc.

For a more controlled shutdown (i.e. allowing any stdout/stderr to make it back to the client) we might generalize ctrl-d to more formally mean "cancel the build" in which case it would send a cancellation request to the daemon which would work exactly the same as the ctrl-c case except that the client would remain connected until the cancellation was complete (and any output would be piped back to the console).

**Comment by lacasseio** [comment]
Thanks @ghale for the detailed information. I saw in `PlayRun` that [it handle Ctrl-D manually](https://github.com/gradle/gradle/blob/master/subprojects/platform-play/src/main/java/org/gradle/play/tasks/PlayRun.java#L105-L116) and I was thinking something similar to that in `JavaExec`. However, what you expose is probably better as the solution. I will edit the title and description to reflect your suggestion.

**Comment by big-guy** [comment]
@lacasseio `PlayRun` handles ctrl+d manually because it predates continuous build, so `run` blocking the build was the way it worked.

I think we wouldn't make `JavaExec` work with continuous build, or at the very least, that's a separate issue.  It would be better to make it easier/possible for plugins to contribute their own `DeploymentHandle` implementations.

**Comment by lacasseio** [comment]
Thanks for pitching in @big-guy. It's very valuable feedback.

**Comment by pkubowicz** [comment]
Yet another problem manifesting in Idea 2016.3 and 2017.1. If you create a Run Configuration for 'gradle run', run it, then try to close the current project or the whole Idea, you will be asked if you want to Terminate, Disconnect or Cancel. 'Terminate' will hang forever.

**Comment by rroels** [comment]
I have similar issues where I have a JavaExec-based "run" task for testing. I'm working on an application that runs continuously in the background and it doesn't stop by itself. This means I have to ctrl-c the process which kills the daemon as discussed earlier. I assume IntelliJ does something similar when I re-run my project from the IDE with a Gradle run/build configuration that only allows one instance to be running at the same time. 

Except for the huge time delay I am also running into issues because my app cannot shut down gracefully (e.g. the WebSocket server not shutting down gracefully which keeps ports blocked for another 10-20 seconds after the ctrl-c).

I would also really like to have a method for telling the daemon to stop the running JavaExec task and to let it shut down gracefully.

**Comment by Apertum** [comment]
I have similar issues. A red square button in Idea or NetBeans for stopping application is not make stop of app immediately. I Have to wait about 10 sec. Inconvenient. I haven't solved it yourself.

**Comment by fab1an** [comment]
I worked around that by putting the start in a shellscript like `./gradlew
build && java -jar ...`
Then call that script in IDEA and terminate it with the button.

**Comment by orange-buffalo** [comment]
This is also a problem for anyone who is using `Project#exec(...)`. Underlying implementation `DefaultExecHandle` uses `ShutdownHookActionRegister` which in turn registers a shutdown hook to cancel the created process. One example where this issue appears are `npm` tools to run dev servers / watch files (see srs/gradle-node-plugin#238, srs/gradle-node-plugin#143).

**Comment by ahmedmohiduet** [comment]
I'm facing similar issue. On my Git Bash "gradle clean bootrun" now not responding for Ctrl+C

**Comment by oehme** [comment]
This was fixed in 4.8, see the duplicate ticket https://github.com/gradle/gradle/issues/2128

**Comment by BrassyPanache** [comment]
I'd like some more information on one of the points in this ticket:
> The `System.{out|err}` output of the Java application isn't piped to the console.

I've got a Java application which prints important status information from within a shutdown hook.  None of this output makes its way to the console after Ctrl+C is issued when running the application from a `JavaExec` task.

I've verified that the shutdown hook is actually being run as I've inserted the following snippet:
```
Files.touch(new File("/tmp/shutdown.log"));
```
I can see this file is created.

Is there any mechanism to ensure all output is piped to the console until the application has shutdown successfully, or been killed by the Gradle client?

**Comment by oehme** [comment]
@BrassyPanache This is intentional. We disconnect the output before shutting down, to prevent all kinds of error messages from being printed to the user. Most applications don't respond gracefully to a shutdown, but print all kinds of "interrupted" errors, which wouldn't make for a good user experience.

**Comment by BrassyPanache** [comment]
@oehme thanks for the response!  How possible would it be to make this configurable? I see your point, and agree that wouldn't make for a nice experience by default. But given that there can be important output it would be nice to give the user a configuration to override this behaviour.

**Comment by oehme** [comment]
If it's imporant to you, a PR is welcome. 

Note though that shutdown hooks won't work on many systems. E.g. on Windows, calling `Process.destroy()` (as we do) will terminate the process immediately without running shutdown hooks.

**Comment by purpleP** [comment]
@oehme What other systems don't support `shutDownHooks`?

**Comment by oehme** [comment]
Sorry for the confusing wording. By systems I meant actual machines running your software, many of which may be on Windows.
