### ISSUE TITLE
Support for compiling Scala with Triplequote Hydra Scala compiler

### ISSUE THREAD

**Issue by dotta** [gradle/gradle#11353]
With the recent release of Gradle 6.0.0 the [Hydra Gradle plugin](https://plugins.gradle.org/plugin/com.triplequote.hydra), which enables compilation of Scala with [Triplequote Hydra](https://triplequote.com/), is no longer working.

The Gradle Hydra plugin is built on top of the Scala Gradle support. In essence, here is what the Hydra Gradle support does:

1) Replace the zinc compiler-bridge with the hydra-bridge (both are sources components).
2) Include some additional jars in the classpath used by the compiler (essentially, in the `ScalaInstance`)
3) Replace the scala-compiler and scala-reflect jars with the Triplequote ones.
4) Set extra compiler flags.

I've created this ticket with the hope you'd be open to have an API that allows integrating Hydra with Gradle on top of the existing Scala support (instead of forcing us to duplicate code). I expect this work will be useful later on to integrate [Dotty](http://dotty.epfl.ch/) (a.k.a., Scala 3) with Gradle, as there are similar requirements as far as I know (replacing the bridge and using a different compiler).

If you are ok with having an API, I'm happy to take a stab at it. Though, I'd appreciate your input on what would be the preferred way to extend the functionality. In particular, the [ZincScalaCompilerFactory.java](https://github.com/gradle/gradle/blob/45b67bc956a921b8691882af1d4662ec2ccb248c/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java) implementation, as I believe that class is the main obstacle.

### Expected Behavior

It would be ideal to have an API allowing compilation of Scala with Hydra.

### Current Behavior

The [compiler-bridge](https://github.com/gradle/gradle/blob/45b67bc956a921b8691882af1d4662ec2ccb248c/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java#L65) and [scala-compiler](https://github.com/gradle/gradle/blob/45b67bc956a921b8691882af1d4662ec2ccb248c/subprojects/language-scala/src/main/java/org/gradle/api/internal/tasks/scala/ZincScalaCompilerFactory.java#L89) names are hardcoded, making it impossible to integrate Hydra without some major code duplication. A similar mismatch will likely occur if contemplating Dotty support down the line.

**Comment by big-guy** [comment]
Hi @dotta 

I would suggest taking a look at [the worker API](https://docs.gradle.org/current/userguide/custom_tasks.html#worker_api).  If I had things to do over again, the ScalaCompile task would have been implemented on top of that instead of the internal compiler daemon code we have now.  The worker API will give you a couple of things:
- Task level parallel-by-default execution 
- Long-lived worker daemon
- Stable API (vs internal compiler daemon infrastructure)

I don't think your goal should be to build on top of the Scala plugin with the one plugin supporting both compilers.  I'd suggest building on top of the `java-library` plugin and stealing some of the ideas from the Scala Base and Scala plugins.  Users can then choose to use the "hydra scala" plugin instead of the built-in scala plugin. 

HTH.

**Comment by dotta** [comment]
Hi @big-guy, really appreciate the prompt followup and pointers. Thanks!
