### ISSUE TITLE
Make System.getProperty("user.home") return GRADLE_USER_HOME

### ISSUE THREAD

**Issue by mathjeff** [gradle/gradle#11433]
When a Gradle plugin calls `System.getProperty("user.home")` (running inside the Gradle Daemon) it would be great if this would return the same value that the Gradle Wrapper considers to be the home dir (that is, the GRADLE_USER_HOME environment variable or the -g argument)

Currently, the value of `System.getProperty("user.home")` seems to be the user's true home dir.

To reproduce, run https://github.com/mathjeff/gradle-samples/blob/368b12d93c591efb09155d57467912a728fd760/home-dir-not-modifying-system-property/test.sh

The reason that this would be nice is because our build (AndroidX ( https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/README.md )) would like to be as deterministic as possible. It is easier to provide deterministic builds if we know all of the places where miscellaneous Gradle plugins may be storing state, and it is common for miscellaneous Gradle plugins to be storing state in the home directory. For example, the kotlin multiplatform plugin seems to be storing utils in this directory: https://github.com/JetBrains/kotlin/commit/2251440f04e5bdb4bdfef2dc47c30356b7f39411#diff-f89fa696d969377895849163650e6a57R12

**Comment by mathjeff** [comment]
I eventually ended up discovering that passing "-Duser.home=$GRADLE_USER_HOME" as an argument to gradlew could control the value returned by `System.getProperty("user.home")`, but this wasn't what I expected.

If it is intentional to support separately setting the value of `System.getProperty("user.home")`, it would be cool for that override to be a separate flag. For example, perhaps users could still pass "-Duser.home=somethingElse" to gradlew which could then be passed through to the daemon, even if Gradle does pass $GRADLE_USER_HOME to the daemon by default

**Comment by big-guy** [comment]
This is available via the `Gradle` object: https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:gradleUserHomeDir

So in a build script (or plugin), you can use `project.gradle.gradleUserHomeDir` to find the current build's Gradle User Home.

I don't think it makes sense to make `user.home` == Gradle User Home, since `user.home` is usually going to be the user's home directory and Gradle User Home is going to be the user's Gradle directory, which is usually in the user's home directory.

For what you want to do, would it make sense to sequester `user.home` in some well-known directory and keep Gradle user home separate?

**Comment by mathjeff** [comment]
The problem that we're encountering is that it's not unusual for third-party plugins to try to save their state into `System.getPropery("user.home")` (even though it's possible to look up the gradleUserHomeDir as you've noted).

Unfortunately, we often only discover that plugins are doing this after it causes inconsistencies in our builds, so we're moving this directory to be in a place where we already expect to find generated files.

Alternatively it could be helpful if `./gradlew --help` were to remind the user that although the "-g" argument changes gradleUserHome, it doesn't change `System.getEnv("user.home")` (because we expected that it would)
