### ISSUE TITLE
Inexplicable deprecation warnings in Gradle 6

### ISSUE THREAD

**Issue by graemerocher** [gradle/gradle#11437]
Running `./gradlew test --warning-mode` on a Micronaut project with Gradle result outputs the following warnings:

```
Property 'options.compilerArgumentProviders.apt$0.name' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'options.compilerArgumentProviders.apt$0.publicType' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

I have googled for what this means and there is nothing in the release notes nor anything to track down the meaning of said deprecation warnings and what action the user is supposed to take

### Expected Behavior

Documentation our explanation on what action to take

### Current Behavior

No docs or explanation

### Steps to Reproduce 

Create  a Micronaut app and upgrade it to Gradle 6

```
sdk install micronaut
mn create-app myapp
cd myapp 
gradle test --warning-mode all
```

**Comment by big-guy** [comment]
This is coming out of the APT plugin: https://github.com/tbroyer/gradle-apt-plugin

This deprecation is caused by new checks Gradle is doing in 6.0 to identify missing inputs to a task.  

`options.compilerArgumentProviders.apt$0` is trying to say that the property `options` has a property `compilerArgumentProviders` has a property `apt` that doesn't explicitly declare how the properties `publicType` and `name` influence up-to-date checks.  This is a problem in the build logic or plugin that adds the `apt` element to `compilerArgumentProviders`.  

I think all of the functionality that the gradle-apt-plugin adds now has built-in equivalents for Gradle 5.2+, so you could remove that plugin from your project template.

**Comment by graemerocher** [comment]
Yes we have already done so for new templates. Thanks for the feedback.

**Comment by graemerocher** [comment]
However, the reason we still have the APT plugin is because of https://github.com/gradle/gradle/issues/9314

Since the built in Gradle functionality does not correctly configure IDE support in Eclipse or Visual Studio Code. So basically we have a choice between inexplicable deprecation warnings or broken IDE support 😕

**Comment by nedtwigg** [comment]
With @tbroyer's blessing, we have fixed the Gradle 6 compile warnings in gradle-apt-plugin for eclipse, and republished as `com.diffplug.eclipse.apt` as part of the [goomph](https://github.com/diffplug/goomph) plugin.  We will continue to maintain and fix any deprecations in the future.
