### ISSUE TITLE
Kotlin Build Script configuration is different taken using Gradle TAPI and using Kotlin Scripting API

### ISSUE THREAD

**Issue by NataliaUkhorskaya** [gradle/gradle#11499]
Since 1.3.70 Kotlin Plugin uses Gradle TAPI to get configurations for build.gradle.kts during project import in Intellij IDEA (using KotlinDslScriptsModel)
But in case when script configuration may be changed the request for configuration goes through old mehanism (using Kotlin Scripting API).

The problem is that those two configurations are different for the build script.
![image](https://user-images.githubusercontent.com/968879/69804519-d2d12800-11ef-11ea-972e-d8d2854adeef.png)

### Expected Behavior
The configurations should be equal

### Current Behavior
Kotlin DSL Accessors are different

### Steps to Reproduce 
I can reproduce it with a simple project with at least **two** modules

### Your Environment
Gradle 6.0.1

related issue in Kotlin Project https://youtrack.jetbrains.com/issue/KT-34626

**Comment by eskatos** [comment]
> But in case when script configuration may be changed

If you changed the script in a way that change the dynamic model, like adding a plugin for example, the accessors will be different, that's expected. 

What modifications did you do to the script that caused the accessors to change?

**Comment by NataliaUkhorskaya** [comment]
Actually I didn't do any changes, we have an additional request on file opening, that checks if configuration is up to date. 
So I import project, after this script configurations from import are saved, than I open the script and receive the new configuration that differs from the one from import.

**Comment by eskatos** [comment]
Thanks Natalia, this is indeed a problem. I'll try to reproduce.

**Comment by eskatos** [comment]
@NataliaUkhorskaya I can't reproduce out of IntelliJ, I get the same models. Could it be possible that the import process contribute Gradle model elements, maybe via init scripts, that the scripting api process do not? That would explain the difference.

**Comment by eskatos** [comment]
IntelliJ injects things in the build on import. For one it applies the `idea` plugin. That means that accessors for the `idea` extensions and tasks contributed by that plugin will be generated. That doesn't happen via the Kotlin Scripting API. That alone explains the difference reported above.

This also means that accessors to things that are not available when building from the command line will be made available in the script editor. In other words, the model is wrong and users could start using things that will make the build fail on the CLI or CI.

We can't simply blacklist those extensions or tasks because the build may itself have them available e.g. by applying the `idea` plugin always.

Also, the diff shown in the issue description suggests that only core Gradle plugins or scripts are injected, no external plugins. Otherwise there would be more difference in the returned classpath.

**Comment by vladsoroka** [comment]
`idea` plugin is indeed applied for the import but by the Gradle's model builder itself - https://github.com/gradle/gradle/blob/v6.0.1/subprojects/ide/src/main/java/org/gradle/plugins/ide/internal/tooling/IdeaModelBuilder.java#L74

**Comment by eskatos** [comment]
Then the safe path would be to issue a separate TAPI request right after import to only query the scripts models. That way you’d be sure nothing can get in the way and you get correct models.

**Comment by vladsoroka** [comment]
`IdeaProject` is requested on `BuildActionExecuter.Builder#buildFinished` phase, so maybe scripts models should be requested on `BuildActionExecuter.Builder#projectsLoaded` phase using the single TAPI request?

**Comment by eskatos** [comment]
@vladsoroka iff this is the only thing contributing to the project model during import, then yes that could work

**Comment by NataliaUkhorskaya** [comment]
We decided to fix it on Kotlin side.
