### ISSUE TITLE
Allow removing the "To honour the JVM settings for this build a new JVM will be forked" message

### ISSUE THREAD

**Issue by rickardp** [gradle/gradle#11517]
We use Gradle from within a Docker environment, making the daemon unfeasible. In our Gradle configuration, we disable the daemon, but the following message is always printed

    To honour the JVM settings for this build a new JVM will be forked. 
    Please consider using the daemon: https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html.

This does not make any sense for our usecase and only serves to confuse developers that they somehow screwed up their JVM settings.

By looking at the code, there is no easy way to disable this message.

### Expected Behavior
Allow silencing this message (perhaps only show it if --no-daemon is used, but not if disabled via property, or create a new property for turning this off).

### Current Behavior
I see no way to disable this message since it is logged with lifecycle level.

### Context
My use case has no need for the daemon and I am fine with forking the JVM. I don't want the message printed all the time.

**Comment by big-guy** [comment]
This message is trying to tell you that Gradle is using a daemon even though you asked for the daemon to be disabled. If you don't care if the daemon is running, just use the daemon.  Is there a downside to that?

**Comment by rickardp** [comment]
The difference is that the daemon does not shut down when the build is complete, while the forked JVM cleans up after itself, unless something has changed in the latest releases.

**Comment by chanseokoh** [comment]
Is there a way to force `--no-daemon` no matter what? Right now, I cannot figure out why it is forking a new JVM. I don't set any JVM settings myself anywhere.

**Comment by chanseokoh** [comment]
Regarding https://github.com/gradle/gradle/issues/11517#issuecomment-601850632, here's what worked as a workaround.

First, run with `--no-daemon --debug` and the check what JVM arguments are being used. They will be shown at the beginning of the output.
```
14:27:17.775 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /home/chanseok/.gradle/native
14:27:17.957 [LIFECYCLE] [org.gradle.launcher.daemon.client.SingleUseDaemonClient] To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/5.2.1/userguide/gradle_daemon.html.
14:27:17.987 [DEBUG] [org.gradle.launcher.daemon.client.DefaultDaemonStarter] Using daemon args: [/home/chanseok/jdk1.8.0_171/bin/java, -XX:MaxMetaspaceSize=256m, -XX:+HeapDumpOnOutOfMemoryError, -Xmx512m, -Dfile.encoding=UTF-8, -Duser.country=US, -Duser.language=en, -Duser.variant, -cp, /home/chanseok/gradle-5.2.1/lib/gradle-launcher-5.2.1.jar]
```
In my case, they were
```
-XX:MaxMetaspaceSize=256m
-XX:+HeapDumpOnOutOfMemoryError
-Xmx512m
-Dfile.encoding=UTF-8
-Duser.country=US
-Duser.language=en
-Duser.variant
```
Then, use the exact same arguments via `GRADLE_OPTS` on the command line. That is,

```
GRADLE_OPTS="-XX:MaxMetaspaceSize=256m
             -XX:+HeapDumpOnOutOfMemoryError
             -Xmx512m
             -Dfile.encoding=UTF-8
             -Duser.country=US
             -Duser.language=en
             -Duser.variant" \
    ./gradlew --no-daemon --debug
```
Now it runs without using a daemon.
```
10:23:22.608 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /home/chanseok/.gradle/native                                                                  
10:23:23.281 [INFO] [org.gradle.internal.work.DefaultWorkerLeaseService] Using 8 worker leases.                                                                                                                    
10:23:23.337 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Creating new cache for fileHashes, path /home/chanseok/.gradle/caches/5.1/fileHashes/fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@4aa83f4f                                                                                                                                                                                                 
```

**Comment by chanseokoh** [comment]
Actually, looks like I don't need to pass `-D` arguments. The following worked in my case.
```
GRADLE_OPTS="-XX:MaxMetaspaceSize=256m
             -XX:+HeapDumpOnOutOfMemoryError
             -Xmx512m" ./gradlew --no-daemon --debug
```
However, removing `-Xmx512m` causes Gradle to use a single-use daemon.

**Comment by landsman** [comment]
yes please!

**Comment by john-peterson** [comment]
i am trying to build on a low memory system e2-micro and i can not match the settings as described

is there some way to print the difference between my GRADLE_OPTS and the comparison to see what i did wrong 

could there be as little as a single letter wrong or a single space wrong? i tried different sub sets without luck

can someone dig up the source file for this so i can finally fix it

this is what i tried

```
./gradlew --debug |grep daemonArgs>>args 2>&1

sed 's/.*daemonArgs//' args>arg
sed -i 's/.*java,//' arg
sed -i 's/,//g' arg
sed -i 's/.$//' arg

cat arg
--add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xmx256m -Dfile.encoding=UTF-8 -Duser.country -Duser.language=en -Duser.variant -cp /home/a/.gradle/wrapper/dists/gradle-8.6-all/3mbtmo166bl6vumsh5k2lkq5h/gradle-8.6/lib/gradle-launcher-8.6.jar -javaagent:/home/a/.gradle/wrapper/dists/gradle-8.6-all/3mbtmo166bl6vumsh5k2lkq5h/gradle-8.6/lib/agents/gradle-instrumentation-agent-8.6.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.6

export GRADLE_OPTS=$(cat arg)

./gradlew
To honour the JVM settings for this build a single-use Daemon process will be f...

export GRADLE_OPTS="
-Xmx256m
-Dfile.encoding=UTF-8
-Duser.country
-Duser.language=en
-Duser.variant"

./gradlew
To honour the JVM settings for this build a single-use Daemon pr...

**Comment by ljacomet** [comment]
Keeping closed as a duplicate of:
* #2660

**Comment by ctrueden** [comment]
@ljacomet I don't think this is a duplicate of #2660, exactly. This issue here is about one thing only: the ability to disable the "a new JVM will be forked" message. Whereas #2660 is about improving the message itself in various ways, as well as the accompanying documentation.

Personally, the single-use daemon notification message irritates me greatly. Every time I see it, I get worked up:

* I don't want my build system to leave a daemon process lying around post-build (what other build system does this, *especially* by default rather than opt in?), so I pass the `--no-daemon` flag to prevent that from happening.

* I don't care that another transient process is being forked -- other build systems like Maven do this all the time e.g. to invoke javac in its own process, and they don't spam the user about it. At minimum, I would expect there to be some kind of verbosity control, so that I can silence the message.

As such, I asked Claude whether it is possible to disable this message by configuring Gradle's logger, and if not, how to go about modifying
the source code to add support for such a toggle. I'm including the exchange here in case it is useful to others.

<details><summary>How to disable the single-use daemon message?</summary>

<blockquote>

> I want to modify Gradle (this working copy) to support disabling the "a single-use Daemon will be forked" message. This one:
> ```
> $ git grep 'honour the JVM settings'
> platforms/core-runtime/client-services/src/main/java/org/gradle/launcher/daemon/client/SingleUseDaemonClient.java:    public static final String MESSAGE = "To honour the JVM settings for this build a single-use Daemon process will be forked.";
> ```
>
> I see that this message is published via the line:                                                                    
> ```
> LOGGER.lifecycle(MESSAGE + " {}", documentationRegistry.getDocumentationRecommendationFor("on this", "gradle_daemon", "sec:disabling_the_daemon"));
> ```
>
> Can this logger already be configured via system properties? If not, what would you recommend as the best/simplest/cleanest way to support disabling this message?

## Is it already configurable?

Not in any targeted way. It is logged at Gradle's lifecycle level, which is the default level. The only existing knobs are the global log-level controls:

- `--quiet` / `-q` on the CLI, or
- `org.gradle.logging.level=quiet` in `gradle.properties`

Any of those would hide the message — but they suppress all lifecycle output (including `BUILD SUCCESSFUL`, incubating-feature notices, etc.), so it's far too blunt. There is no per-message toggle for this specific line today.

One important architectural fact that shapes the fix: this message is printed by the client/launcher JVM (`SingleUseDaemonClient` runs in the launcher, it's the thing that forks the daemon). That matters for where a system property is readable — see below.

## Recommendation

Gradle itself already has a precedent for exactly this kind of opt-out: `WelcomeMessageAction` gates its output on the system property `org.gradle.internal.launcher.welcomeMessageEnabled`. I'd mirror that pattern. There are two levels of effort:

### Option A — minimal, one-file change

Downgrade the message from lifecycle to info when a system property is set. In SingleUseDaemonClient.execute():
```java
String recommendation = documentationRegistry.getDocumentationRecommendationFor("on this", "gradle_daemon", "sec:disabling_the_daemon");
if (Boolean.getBoolean("org.gradle.daemon.singleUseMessage.disabled")) {
    LOGGER.info(MESSAGE + " {}", recommendation);
} else {
    LOGGER.lifecycle(MESSAGE + " {}", recommendation);
}
```
Downgrading to info (rather than deleting the call) keeps the message discoverable with `--info`/`--debug` and preserves the existing `SingleUseDaemonClientTest` expectations if you run at info.

Caveat on how you set it: because this runs in the launcher JVM, the property must be a real JVM system property of that process. That means one of:
- `gradle -Dorg.gradle.daemon.singleUseMessage.disabled=true …`
- `export GRADLE_OPTS="-Dorg.gradle.daemon.singleUseMessage.disabled=true"`

A plain systemProp entry in `gradle.properties` will not work here —  those are forwarded to the daemon JVM, not applied to the launcher.

### Option B — the "clean" Gradle-idiomatic way

If you want it configurable via `gradle.properties` like `org.gradle.welcome`, thread a boolean down from `BuildActionsFactory.runBuildInSingleUseDaemon` (where `DaemonParameters` — which has parsed `gradle.properties` — is available) through `DaemonClientFactory.createSingleUseDaemonClientServices` → `SingleUseDaemonClientServices` → `SingleUseDaemonClient`. That's the properly-plumbed version and would let you use a real `org.gradle.*` build option, but it touches ~4 files and, to be a first-class option, ideally also a `BuildOption` subclass + serializer entry.

</blockquote>

</details>

I was tempted to file a PR along the lines of Option A (a simple boolean property check directly around the `LOGGER.lifecycle` line), but the fact that it would then not work as expected via `gradle.properties` would likely bite people.

For my primary use case, which is actually invoking Gradle from a Maven build (!), I am able to get away with just passing `-q` to silence Gradle more thoroughly. But it's not a good general solution, and I suggest to reopen this issue.

Here's an even simpler solution than a boolean property check: how about just changing `LOGGER.lifecycle` to `LOGGER.info` for this message? That way, people still see it in verbose mode, but are not bothered in normal mode. What's the downside?
