### ISSUE TITLE
Gradle swift code generation

### ISSUE THREAD

**Issue by bitsydarel** [gradle/gradle#11530]
I would like to create annotationProcessor like plugin for swift.

Currently I’m just outputting string to some directory and formatting the string using swift formatted, it’s a little bit hacks.

I would like to have a dsl for querying method, field and other information available in swift source code.

**Comment by lacasseio** [comment]
This issue seems more like a question than a feature. The annotation processor is handled by the compiler. Gradle simply create the right compile path so everything can be incremental, etc. If want you ask is provide a demonstration of annotation processor that generate some other language binding that are then compiled and released as a library in the target language then it is certainly possible to achieve today and we could work on building a sample for this specific use case. My understanding would then be "published Swift language binding of a Java library using annotation processor". Could you confirm this is what you are after? Else we would need more details of what feature you are requesting.

**Comment by bitsydarel** [comment]
Let me re-phrase it:
i would like to be able to create gradle plugin that can process swift source code using and output source code.

The use case's code generation.

Java library to swift would be great but i would prefer a dsl to process swift source code.

**Comment by bitsydarel** [comment]
@lacasseio  For example javax provide a api to process java source code:
https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/package-summary.html

**Comment by lacasseio** [comment]
My understanding of this feature request would be better addressed by the team behind the Swift language. Gradle only expose features provided by those tools. There is little we can do to provide features at the tool level. That being said, it doesn't mean you can't do it in Gradle, it's just not something the team would be developing as a core feature of Gradle. I suggest you look at extending Gradle through a plugin instead and ask for help on the [user forum](https://discuss.gradle.org/) or the [community Slack](https://gradle-community.slack.com). There is also a lot of information in the [documentation](https://docs.gradle.org).
