### ISSUE TITLE
Make deprecation warning clearer

### ISSUE THREAD

**Issue by melix** [gradle/gradle#11621]
## Context

Currently, if a build issues deprecation warnings, the output will show this:

```
Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.1-branch-lptr_vfs_darwin_file_watcher-20191203160126+0000/userguide/command_line_interface.html#sec:command_line_warnings
```

I've read several comments from folks not really understanding what this means. I think we could make the message a bit clearer:

```
Deprecated Gradle features were used in this build. This means that your build is likely to break when you'll upgrade to the next major release (Gradle 7.0).

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/6.1-branch-lptr_vfs_darwin_file_watcher-20191203160126+0000/userguide/command_line_interface.html#sec:command_line_warnings
```

Note the presence of additional blank lines to make it clearer too.
Ideally we should even detect if the deprecation warning comes from the user scripts or external plugins.

**Comment by IfIWantedTo** [comment]
Hi @melix , I'm completely new to all of this. I have gotten this error message when trying to `gradle generateSource` for JabRef. When I got this the Build failed, is this because of possible incompability to future gradle versions? To me this doesn't sound like it could be responsible for failing the Built. Anyway, I am very desperate for a solution, if you have any idea how I can fix this I would really appreciate it.

**Comment by melix** [comment]
The message above is a warning. It doesn't fail the build unless you explicitly have set warning mode to fail. The message tells you the build is going to fail _if you upgrade Gradle to the next major_.

**Comment by IfIWantedTo** [comment]
Yes, that makes more sense! Thank you for the quick response.
