### ISSUE TITLE
@InputFiles task property providers executed too often (and too early?)

### ISSUE THREAD

**Issue by lkoe** [gradle/gradle#11633]
The documentation (https://docs.gradle.org/current/userguide/lazy_configuration.html#sec:creating_property_provider) suggests to use properties and providers to lazily configure tasks. This would imply that providers connected to a property are only executed once and potentially as late as possibe.

However, when toying with task input properties annotated with `@get:InputFiles` and `@get:Classpath` I found that the providers attached to such a property are executed too often and potentially too early (during configuration phase).
This is not the case for "simple" input properties using `@get:Input` - those are only executed once (during execute phase as expected)

Please see attached project for a simple scenario.
[gradle-provider-test.zip](https://github.com/gradle/gradle/files/3943984/gradle-provider-test.zip)

Task output:
```
D:\git\spielwiese\repo\gradle-provider-test>g clean providerTest
Configuration on demand is an incubating feature.
Getting input files...
Getting input files...

> Task :providerTest
Getting input files...
Calculating the answer
The Answer to the Ultimate Question of Life, the Universe, and Everything is...42
Number of input files 33
```

### Expected Behavior
I would expect the provider for task property `inputFiles` to only be executed once and (if possible) during execute phase.

### Current Behavior
The provider is executed 2 times in configuration phase and once in execute phase during task execution (expected), totalling 3 times.

### Context
I am trying to use recommended gradle patterns to keep our build as efficient as possible. The current behaviour seems counter-intuitive.
I came up with a workaround using a kotlin delegate, though I can't fully assess if it is recommended to do it this way. Using the workaround, the provider is still executed during configuration, but only once total:
```
fun <T> Project.lazyProvider(value: Callable<T>): Provider<T> {
    return LazyProvider(value)
}

private class LazyProvider<T>(value: Callable<T>) : DefaultProvider<T>(value) {

    val lazyVal: T by lazy { super.getOrNull() }

    override fun getOrNull(): T {
        return lazyVal
    }

    override fun isPresent(): Boolean {
        return true
    }
}
```

### Steps to Reproduce 
Please see attached sample project

### Your Environment
Windows
Gradle 6.0.1

Build scan URL: can't publish as build-scan is not honoring proxy settings

**Comment by big-guy** [comment]
In your example, you have a `Property<FileCollection>`.  A `FileCollection` is like a `Property`, so you should treat it as one.  To make it configurable, you should use a `ConfigurableFileCollection` instead.  The multiple calls are coming from Gradle trying to extract dependency information from inputFiles and unraveling the multiple layers of Property -> FileCollection -> Provider.  The value of inputFiles is only finalized just before task execution.

If you switch to `ConfigurableFileCollection`, that changes how you configure the value of inputFiles:
```
    inputFiles.from(provider {
        logger.quiet("Getting input files...")
        fileTree(projectDir)
    })
```
This should take you from 3 calls to only 2.

You can go another step by dropping the `provider {}`.  `fileTree(...)` returns a `ConfigurableFileTree` that's `Provider`-like, so that layer is unnecessary too.

`projectDir` could be a `File` or `RegularFile` or a provider itself.  You can change things again:
```
    inputFiles.from(fileTree(projectDir))
```
Since this removes the logging, you can't see the effect, but this only gets evaluated once.  Just to confirm that, you can do this (this is unnecessary):
```
    inputFiles.from(
        fileTree(provider {
            logger.quiet("Getting input files...")
            projectDir
        })
    )
```
This will only show one "Getting input files" message.

We don't do it today, but we're going to start warning about things like `Provider<T>` or `Property<T>` where `T` is already a Provider-like thing.

HTH.
