### ISSUE TITLE
With Gradle 5.0 and above, lombok plugin not supported for compileOnly? 

### ISSUE THREAD

**Issue by yansongfu** [gradle/gradle#11659]
Following line in build.gradle works fine for lombok plugin up to 4.10.3 (latest gradle 4 version)
```compileOnly "org.projectlombok:lombok"```
for classes like 
```
@Getter
@Setter
public class SomeClass {
  private String name;
}
```
But with 5.0 and above, project fails to compile, complaining any service classes that call someClass.getName() or someClass.setName(): error: cannot find symbol. It seems 5.0 and above do not honor lombok's @Getter and @Setter any more. Or done by a new task?

**Comment by big-guy** [comment]
I think you're running into a change in behavior that's deprecated in 4.x and removed in 5.0:
https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel4.6:annotation_processor_configuration

Before 5.0, Gradle used to use annotation processors like lombok when they were on the compile classpath. This mixed the dependencies needed to execute annotation processors with the dependencies needed to compile the project, which made it harder for Gradle to avoid compilation when dependencies changed.

Instead of adding lombok to your `compileOnly` configuration, you should add it to the `annotationProcessor` configuration.
