### ISSUE TITLE
Publish gradle subprojects with proper dependencies to maven repository

### ISSUE THREAD

**Issue by donat** [gradle/gradle#11671]
Right now, we use a legacy publishing to deploy subprojects to [repo.gradle.org](https://repo.gradle.org/gradle/list/libs-snapshots/org/gradle/). Unfortunately, the deployed artifacts don't define any dependencies. With those dependencies present, users could reference a Gradle as Maven dependency from a build, and can potentially be an alternative/replacement for the `gradleApi()` dependency: https://github.com/gradle/gradle/issues/1003

**Comment by donat** [comment]
@rieske and I did some poking in the code and it seems that the only way to achieve this is to replace the legacy publishing with `maven-publish`.

**Comment by wolfs** [comment]
See https://github.com/gradle/gradle/issues/6454 for using `maven-publish` in our build.

**Comment by donat** [comment]
Thanks, @wolfs. We generated a local Maven repository from gradle/gradle, although the dependencies seem broken. Chances are, we will need to get some guidance on how the components should be defined (probably with Gradle metadata).

**Comment by adammurdoch** [comment]
I don't think we want to publish the Gradle project structure as it is right now, because this doesn't represent the Gradle API, and so would make it harder for us to evolve things in the future. I very much don't want to make the current Gradle structure any kind of public contract.

Some examples:

- there's no single Gradle project currently that represents the Gradle API as it currently is defined for `gradleApi()`. It's not `coreApi`, nor `core`. These things are subsets of the APIs.
- the dependencies declared for the projects currently expose a whole bunch of libraries that are not part of the API.
- there's no single Gradle project whose output is embeddable at runtime, as `gradleApi()` currently is.

These things are certainly things we can address, but I would definitely not just publish the existing structure and have people use it. We should instead do some planning and come up with a strategic view of where we want to go for plugin development. And we should start with the why here: Why exactly is it useful to publish this stuff? what problem are we trying to solve here? what are the alternative options? how to the options interact with other things we want to do?

**Comment by donat** [comment]
We started to look into https://github.com/gradle/gradle/issues/1003 as a learning exercise with @rieske. This is more of an experimentation and we poke around how we can improve the code.
