### ISSUE TITLE
Gradle considers tasks up-to-date when it should not

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1168]
Here's a doozy.

Given a task like this (distilled to just the important parts):
```
class CustomTask extends DefaultTask {
    @OutputDirectory File outputDir = new File(project.buildDir, "output")
    
    @TaskAction
    public void generate() {
        File outputFile = new File(outputDir, "file.txt")
        outputFile.text = "generated"
        outputFile.lastModified = 0
    }
}
```
and a build file:
```
task customTask(type: CustomTask)
```

If you run this sequence of steps, the `customTask` will be up-to-date even though `build/output/file.txt` does not exist.

1. Run `gradle customTask` as usual. (Gradle will execute the task, the file is created.)
2. Upgrade Gradle or delete the project `.gradle`.
3. Run `gradle customTask`. (Gradle will execute the task, the file is not overwritten.)
4. Run `gradle clean`. (Gradle will delete the file.)
5. Run `gradle customTask`.  (Gradle will mark `customTask` as up-to-date.)  This is wrong.

### Expected Behavior

Gradle should not consider the task up-to-date.

### Current Behavior

Gradle considers the task up-to-date.  The only way to get out of this state is to change an input to the task or run with `clean` and `--rerun-tasks`.  A `clean` alone isn't enough to cause the task to re-execute.

### Context

This problem was found with a task that uses `javah` to generate header files.  `javah` will not overwrite header files if the source file has not changed.  This combined with a Gradle upgrade (or loss of the `.gradle` directory) caused the up-to-date checks to consider a task up-to-date because it had _no_ output snapshots.

I think the problem has something to do with this check:
https://github.com/gradle/gradle/blob/b708c31ed0e78ecf1bcc2d63812ab09418c1498e/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/OutputFilesSnapshotter.java#L79-L79

When a file exists in an output directory before the task executes and the file doesn't change (modification time or content), we don't consider it part of the output snapshot.  

### Steps to Reproduce (for bugs)

See integration test: https://github.com/gradle/gradle/blob/master/subprojects/core/src/integTest/groovy/org/gradle/api/tasks/IncrementalBuildIntegrationTest.groovy#L1132-L1132

### Your Environment

Observed on macOS, but I would suspect any OS would do.

**Comment by wolfs** [comment]
If #1074 is merged, we could register the output file for cleanup and that would fix the problem, right?
For caching, we would cache the right thing on the first run since we cache all of the outputs but we wouldn't pull from the cache after the clean since the task is `UP-TO-DATE`, right?
If we would not have overlapping output directories then we should just consider everything in the output directory as an output for a task - regardless if it has been modified or not.

**Comment by big-guy** [comment]
Yes, i think that would have helped.

**Comment by adammurdoch** [comment]
When we know that the task owns the output directory (using the same information by which we know that we can clean the directory on version change) then we certainly should consider the entire contents of the directory to be the task's outputs.

We'd also need to do some form of cleanup prior to running the task's actions, to deal with other tools that scribble into the output directory. We might remove those output files that have changed since the task was last run (where 'add' is-a kind of change), or just remove all of the outputs when we need to run the task's actions (for tasks that aren't incremental of course).

**Comment by jjustinic** [comment]
This issue was of significant impact to us after our last Gradle upgrade. In our case, the Gradle tasks that delegate to our gulp tasks are being incorrectly marked as UP-TO-DATE, which causes the WAR file to be built without CSS and other front-end files.

We're seeing the scope of this issue to be greater than what is listed here, specifically:
- Step 1 is extraneous. We can reproduce this issue whether or not the task was run previously prior to the upgrade or removal of the .gradle folder.
- Step 2 can also include a fresh clone of the repository. Issue occurs after the first clean.
- Only changing an input resolves the incorrect state. Running `clean` with `--rerun-tasks` does not resolve the issue.
- We see the issue even when the files are rewritten and the modification time changes. (*)
- We can also reproduce this with 3.2.

This was particularly challenging to track down as most of our developers are not updating front-end files and were considering most actions they took _other than clean_ to be the trigger. This also causes unreliable builds in CI systems that clean but do not nuke the entire working directory.

(*) While I can reproduce this reliably in our project with Gradle releases >= 3.2, so far the modification time is the only item above that I've been able to simulate in the integration test, so I'm still looking for an additional contributing variable.

**Comment by ketan** [comment]
> This issue was of significant impact to us after our last Gradle upgrade. In our case, the Gradle tasks that delegate to our gulp tasks are being incorrectly marked as UP-TO-DATE, which causes the WAR file to be built without CSS and other front-end files.

This is exactly the same problem for us, and it's biting us really bad.

**Comment by jjustinic** [comment]
Although the symptoms spread to the gulp tasks, it's the `npmInstall` task that has similar behavior to the `javah` command where files in the `node_modules` dependency folders are not touched when the task runs if they already exist.

@ketan: We are working around the problem by adding a task action that updates the last modified time of any output file of tasks with the problem (only `npmInstall` in our case). See this gist for the details: https://gist.github.com/jjustinic/f86451edc3ff1de41966a687630664e1.

**Comment by wolfs** [comment]
This will be fixed in 4.2.

**Comment by ketan** [comment]
I'm running on a recent nightly `Gradle 4.2-20170810012648+0000` with revision `569d3e31713898f8f7e6b90882841dc666427cfd`. I'm still hitting the same issue.

My [custom task](https://github.com/ketan/gocd/blob/faster-builds/buildSrc/src/main/groovy/com/thoughtworks/go/build/YarnRunTask.groovy) is a wrapper around that executes `yarn run ${inputArgs}`, and generates JS assets for a webapp. Since this is usually an expensive operation, I've added a `@CacheableTask` annotation to it.

However when I manually remove the assets dir (declared as an `@OutputDirectory`) using `rm -rf ...`, gradle says that the task is `UP-TO-DATE` and does nothing.

I've read my code to make sure that I'm not doing something obviously wrong, and I'm fairly confident it's not. If there's any specific debugging I can help with to resolve this issue, I'm happy to help out in any way.

**Comment by wolfs** [comment]
@ketan Thanks for the feedback. Could you describe how you got into that situation? Could you provide a reproducible way how to get into that situation?
Does the asset dir live within the `build` directory?

**Comment by ketan** [comment]
> Thanks for the feedback. Could you describe how you got into that situation? Could you provide a reproducible way how to get into that situation?

> Does the asset dir live within the build directory?

No, it does not. I'm not sure how to reproduce this issue anymore. I blew away the `.gradle` dir in my project root and cleared the gradle cache under `~/.gradle/cache/build-cache-*` and things are back to what's expected....

**Comment by wolfs** [comment]
@ketan The bug is only fixed for outputs which we think are safe to delete. This is everything the `clean` task would remove. So if you add the output directory of your task as a clean target to the `clean` task, then the problem should be gone. You can do something like this:
```
clean {
    delete 'path-to-output-dir'
}
```

**Comment by Jonatha1983** [comment]
Hi @wolfs  

Why only safe to delete outputs? 
Is in it better maybe a new annotation which force outputs to be taken in consideration ? 

thanks ahead Jonathan

**Comment by Jonatha1983** [comment]
Hi @wolfs  
I was able to reproduce the  issue even when setting the 'path-to-output-dir' in the clean task. 
Step to reproduce:
        1. Create a root  folder with a build gradle script
        2. Add the following code to the script:
apply plugin: 'base'
defaultTasks 'create'
task create {
    inputs.file "${projectDir}/in.txt"
    outputs.dir "${projectDir}/result"
   doLast {
        def f1 = file("${projectDir}/result/file1.txt")
        if (!f1.exists()) {
            f1.text = "Foo"
            println "File was created in executrion: ${f1}"
        }
    }
}
clean { delete file("${projectDir}/result") }

  3.  Run the task create , it will create the result/file1.txt file
 .4. Change the task name create to create1 
 5. Run the task create1 it will run (execute) but without creating the file (since it exists already) 
 6. Delete manually the file1.txt and re-run the task create1 - it will show as up-to-date and it will not create 
    the file

I tried in the clean task to set the delete with task.create1 then task.create1.outputs  then with path to the Dir hard-coded, each time same result: Up-To-Date

Thanks
Jonathan

**Comment by wolfs** [comment]
@Jonatha1983 Thank you for the example. You are right, renaming a task will not result in the files from the now non-existing tasks to be cleaned up. The simple reason is that Gradle has now way to know that the task has been removed. So the `result/file1.txt` is still an output of the `create` task. I can't see how Gradle could track the renaming of tasks.
What could be possible is that a task could declare that it has exclusive access to the output directories and Gradle could clean up the output directories if that is the case. But that is a different story.

**Comment by Jonatha1983** [comment]
@wolfs  Thanks for your answer. 

I meant to demonstrate files created by a different source and with some logic that they would not be created when run the 2nd time - the rename of the task is confusing in this regard and I did not mean to refer the rename operation itself.

Since a lot of tools (npm included) perform some caching and optimization, the combination with Gradle's incremental feature will results in hard-to-find bugs until such an annotation of exclusive output for a task will exist. For the sake of exclusive outputs - I think it would be better for gradle to cache whatever exists in the folder before the task runs rather than cleaning.

We used to work around it by touching the files during the execution phase, but obviously it is a fragile workaround that lacks real optimization.

Thanks again

**Comment by koppor** [comment]
I think, the issue still persists.

First run:

```
> Task :jablib:generateCitationStyleCatalog
Caching disabled for task ':jablib:generateCitationStyleCatalog' because:
  Caching has not been enabled for the task
Task ':jablib:generateCitationStyleCatalog' is not up-to-date because:
  Output property '$1' file C:\git-repositories\JabRef\jablib\build\generated\resources\citation-style-catalog.json has been removed.
```

I delete the output file afterwards.

Second run:

```
> Task :jablib:generateCitationStyleCatalog UP-TO-DATE
Caching disabled for task ':jablib:generateCitationStyleCatalog' because:
  Caching has not been enabled for the task
Skipping task ':jablib:generateCitationStyleCatalog' as it is up-to-date.
```
