### ISSUE TITLE
Could not extract native JNI library 

### ISSUE THREAD

**Issue by ragv1** [gradle/gradle#11746]
Trying to install gradle in windows 7 but when I do gradle -v in the command prompt I get the following error:

FAILURE: Build failed with an exception.

* What went wrong:
Could not extract native JNI library.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with
--scan to get full insights.

* Get more help at https://help.gradle.org

Trying to install gradle in windows 7 but when I do gradle -v in the command prompt I get the following error:

CMD screen capture

I installed gradle from the gradle.org official page manually extract it to c:\gradle folder then cd c:\gradle\gradle-6.0.1\bin and there did gradle -v. 

The error "Could not extract native JNI library" keeps showing up.

I am Using Windows 7 Professional with Service Pack 1 and the gradle version 6.0.1

**Comment by lacasseio** [comment]
Although this error seems like an issue with Gradle it's almost certain to be question that should be asked on the [user forum](https://discuss.gradle.org/).

As for the issue itself, this error message is lacking a better message. This failure is always attributed to strange permission with the user home directory (`%USERPROFILE%`). To validate, use [`--gradle-user-home`](https://docs.gradle.org/current/userguide/command_line_interface.html#environment_options) flag to point to a new directory that you know for certain you have write access. Gradle should execute correctly. In this case, it may be something cause the `~/.gradle` directory to be miscreated, or there are some domain policy preventing users from creating the directory in the user home. It could also be that user home have a size limitation imposed by the domain. You can try to validate those. If none apply, try deleting the `~/.gradle` directory and executing Gradle again without the `--gradle-user-home` flag.

If it still persist, reopen this issue and we can start debugging further. At this point, you should provide a stacktrace using `--stacktrace` flag.

**Comment by ragv1** [comment]
@lacasseio i agree that the error message does not give you  valuable information. I will try your suggestions and let you know

**Comment by ragv1** [comment]
@lacasseio I've been trying your suggestions but still I am not able to run a single command with gradle. To be clear not even `gradle -v`. This is what i checked:
I have administrator permissions in the whole system, nevertheless i set manually the permissions to Allow full control to my %userprofile% folder and subfolders. 
I don't see how  `--stacktrace` will help since i am not building anything yet. I am just trying to run `gradle -v`.
I noticed that when i run the gradle -v command the following route is created in my %userprofile% folder `%userprofile%\.gradle\native\30\windows-amd64\native-platform.dll.lock` this lock file have a size of 0kb so i assume is empty.
when i do `gradle -v --gradle-user-home="c:\gradle"` then the same route of folders and the same lock file is created but now in the c:\gradle directory. 
I try deleting the .gradle folder and running gradle -v again. But it does the same thing creates the lock file in the same route of directorys, meanwhile in the cmd the  error hasn't change.
Anything i can provide to you I am more than willing to do it. And Thank you for responding me i have posted the question all over and nobody so far has been able to answer me.

**Comment by lacasseio** [comment]
I'm not sure if this will help, but could you try to run `gradle -d` and paste the output? I'm not sure if Gradle is crashing before or after the debug logging enabling but it may give us some more information. I will reopen just to make sure we can help you on this.

**Comment by ragv1** [comment]
@lacasseio Thank you for taking the time. I ran `gradle -d` but the exact same output as before is displayed in the cmd. I installed gradle in a virtual machine and is running just fine. I'm sure there is a problem in my system which is making gradle crash. But since the error is so vague it is hard to debug. I don't know if this is helpful but when i ran `gradle -v` in the virtual machine there are a couple of folders and a couple of files that are getting created that in my host machine they are not.
In my virtual machine:
`%USERPROFILE%\.gradle\native\30\windows-i386\native-platform.dll`
`%USERPROFILE%\.gradle\native\30\windows-i386\native-platform.dll.lock`
`%USERPROFILE%\.gradle\native\jansi\1.18\windows32\jansi.dll`
`%USERPROFILE%\.gradle\notifications\6.0.1\release-features.rendered`

But in my host:
`%userprofile%\.gradle\native\30\windows-amd64\native-platform.dll.lock`

**Comment by lacasseio** [comment]
Thanks for this additional comment. This is a wild shot in the dark but could you confirm the architecture of your installed Java? Is it Java 32-bit or 64-bit that you are running on your machine. It seems your virtual machine is somehow a 32-bit windows (i386) vs your host being 64-bit windows (amd64). They may be an issue if you are running a WOW64 Java binary where it may detect AMD64 and try to load a 64-bit binary in a 32-bit process which will obviously fail.

If you could confirm the virtual machine is in fact a 32-bit Windows and that your host machine is 64-bit as well as what architecture of the installed Java. If you could also include what is the version of Java you are using it could be useful. Another useful debugging step would be to try another Gradle version to see if it fail in the same way, like trying out Gradle 5.6.3.

**Comment by ragv1** [comment]
Indeed I was running java 32-bit in my host machine with Windows x64. It took me a couple of re-installations to setup java correctly because it was insisting in installing java 32-bit. To get it working  I uninstalled java from my system and deleted the folders in `C:\Program Files (x86)\java`  then reinstalled java in my computer and confirmed with  `java -d64 -version`  that I am now running java with x64 architecture.  But the issue still persist. As for my Virtual machine in fact is a 64-bit process running Windows 7 x64. 
If it helps when I run `java -d64 -version` the output is as follows:
`openjdk version "1.8.0_192"`
`OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_192-b12)`
`OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.192-b12, mixed mode)`
In the virtual Machine everything is okey and Gradle runs just fine.  but still i am not able to run Gradle in my host and the test with other versions of  Gradle, 5.6.3 and 5.4.1  Throws the same error.
I think i will go with the nuclear option and reinstalled Windows since it is a problem with my environment and my installation

**Comment by ragv1** [comment]
@lacasseio Thank you for your time, i really appreciate it.

**Comment by lacasseio** [comment]
Sorry we couldn't debug this further. Something is really up the setup but the solution of reinstalling windows, although would probably solve the issue, is not something that should be the normal path for the solution. Some other questions to try to resolve the issue:
- Is the computer would be on any kind of domain controller that may be pushing policies that are incompatible with Gradle.
- What antivirus is installed?
- Is there anything in the antivirus logs that would hint on the dll is quanrentine as soon as Gradle drops it on disk? For the Windows Defender, you may have to look into the Windows Event log.
- Check the distribution you are using the DLL files are in fact part of the JAR. If you installed Gradle by downloading it from the website check the folder you unzipped, if you used a Gradle wrapper, check the folder corresponding to the version inside `%USERPROFILE%\.gradle\dists\`. Inside the `lib` folder of the distribution, locate `native-platform-windows-amd64-0.18.jar`. Open with any uncompress tool that support zip format and check to see if the file is present at `net/rubygrapefruit/platform/windows-amd64/native-platform.dll`. Be careful here not to unzip but to open the archive in case something is quarantining the DLL on write it may get quarantine again. We are verifying the integrity of the JAR not that we can unzip the file.

I hope this helps solve the issue. Since you may be going to reinstalling which may solve the issue, I will close it for now. If you still have the same problem, lets reopen the issue so we can get to the bottom of this and hopefully modify Gradle to provide a better error message when whatever environmental issue we find here is detected for the other users.
