### ISSUE TITLE
Investigate why changes are not reported when both VFS retention and Instant Execution is enabled

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#11835]
---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I tracked down the problems I was seeing and it seems like nothing is registered in `BuildOutputCleanupRegistry.registerOutputs()`: https://github.com/gradle/gradle/blob/dbf5680659900a5a0532ae2ae49677026390cf66/subprojects/core/src/main/java/org/gradle/internal/cleanup/BuildOutputCleanupRegistry.java#L26

That means that nothing is safe to delete and the stale cleanup code does nothing.

And that is caused since the `base` plugin code is not run. I'll check out how to fix `BuildOutputCleanupRegistry` to work with instant execution.

**Comment by lptr** [comment]
I understand that this is a problem, but how does not registering outputs lead to changes not being detected?

**Comment by wolfs** [comment]
See https://github.com/gradle/instant-execution/issues/165.
