### ISSUE TITLE
Wrapper causes java.nio.file.NoSuchFileException when using non-default distributionPath

### ISSUE THREAD

**Issue by breucode** [gradle/gradle#11842]
### Expected Behavior
After downloading and unzipping the gradle distribution zip file, the gradlew should work properly.

### Current Behavior
When using the gradle wrapper, I get a java.nio.file.NoSuchFileException for the file
{PROJECT_FOLDER}/wrapper/dists/gradle-6.0.1-all/99d3u8wxs16ndehh90lbbir67/gradle-6.0.1/lib/plugins/gradle-diagnostics-6.0.1.jar.
I however have gradle/wrapper/dists/unpacked set as the distributionPath in gradle-wrapper.properties. Gradle should look for the file in
{PROJECT_FOLDER}/gradle/wrapper/dists/unpacked/gradle-6.0.1-all/99d3u8wxs16ndehh90lbbir67/gradle-6.0.1/lib/plugins/
instead of the one mentioned in the error message.

### Context

Stopped working with: 6.0.1
Last version working: 6.0

### Steps to Reproduce 
1. Create a basic build.gradle.kts with the content:
```kotlin
tasks.wrapper {
    distributionType = Wrapper.DistributionType.ALL
    archiveBase = Wrapper.PathBase.PROJECT
    archivePath = "gradle/${archivePath}/archives"
    distributionBase = Wrapper.PathBase.PROJECT
    distributionPath = "gradle/${distributionPath}/unpacked"
}
```
2. Execute `gradle wrapper --gradle-version 6.0.1`
3. Execute any gradle task like `./gradlew wrapper` (Note: `./gradlew --version` does not work

### Your Environment
macOS Catalina 10.15.2 (19C57)

**Comment by big-guy** [comment]
I don't see this behavior.  Do you have the full stacktrace of the failure?

I created a new directory, copied your configuration and ran `./gradlew -v`.  I see the distribution downloaded+unpacked as expected.

You may not want to do this because it has a surprising behavior in multi-project builds.  The distribution gets copied into the subproject if you run Gradle from that project's directory.  This is a really old area of the code, so this configurability might not really make sense to be configurable.

**Comment by asarkar** [comment]
For anyone else stumbling across this ticket, I faced a similar exception today when running `./gradlew clean` on a brand new project with no source code.
```
java.nio.file.NoSuchFileException: /path/to/project/gradle-8.14/lib/gradle-runtime-api-info-8.14.jar
> /path/to/project/gradle-8.14/lib/gradle-runtime-api-info-8.14.jar
```

The `gradle-8.14` shown was used to generate the Gradle Wrapper, and deleted thereafter. The solution was to stop all Gradle daemons by running `./gradlew --stop`.
