### ISSUE TITLE
Dependency stopped working coming from Gradle 4.x

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#11875]
### Expected Behavior
Code compiles just fine.

### Current Behavior
`error: package ... does not exist` and `cannot find symbol` compile errors in Java

### Context
I'm upgrading one of my projects and it started failing when upgraded Gradle. Nothing else changed.

It looks like the transitive dependency just disappeared from the compile classpath (below is a diff between 4.10.3 and 6.0.1):
```diff
compileClasspath - Compile classpath for source set 'main'.
\--- org.ajoberstar:gradle-git:1.7.2
-     +--- org.ajoberstar:grgit:1.9.3
-     |    +--- org.eclipse.jgit:org.eclipse.jgit:4.5.2.201704071617-r
-     |    |    +--- com.jcraft:jsch:0.1.53 -> 0.1.54
-     |    |    +--- com.googlecode.javaewah:JavaEWAH:0.7.9
-     |    |    +--- org.apache.httpcomponents:httpclient:4.3.6
-     |    |    |    +--- org.apache.httpcomponents:httpcore:4.3.3
-     |    |    |    +--- commons-logging:commons-logging:1.1.3
-     |    |    |    \--- commons-codec:commons-codec:1.6
-     |    |    \--- org.slf4j:slf4j-api:1.7.2 -> 1.7.25
-     |    +--- org.eclipse.jgit:org.eclipse.jgit.ui:4.5.2.201704071617-r
-     |    |    \--- org.eclipse.jgit:org.eclipse.jgit:4.5.2.201704071617-r (*)
-     |    +--- com.jcraft:jsch.agentproxy.jsch:0.0.9
-     |    |    +--- com.jcraft:jsch:0.1.49 -> 0.1.54
-     |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
-     |    +--- com.jcraft:jsch.agentproxy.pageant:0.0.9
-     |    |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
-     |    |    +--- net.java.dev.jna:jna:4.1.0
-     |    |    \--- net.java.dev.jna:jna-platform:4.1.0
-     |    |         \--- net.java.dev.jna:jna:4.1.0
-     |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.9
-     |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
-     |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.9
-     |    |    +--- com.jcraft:jsch.agentproxy.core:0.0.9
-     |    |    +--- net.java.dev.jna:jna:4.1.0
-     |    |    \--- net.java.dev.jna:jna-platform:4.1.0 (*)
-     |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.9
-     |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.9
-     |    +--- com.jcraft:jsch:0.1.54
-     |    \--- org.slf4j:slf4j-api:1.7.25
-     \--- com.github.zafarkhaja:java-semver:0.9.0
```

### Steps to Reproduce 
https://github.com/TWiStErRob/repros/tree/master/gradle/transitive-dependency-5

### Your Environment
 * Gradle 4.10.3: works https://gradle.com/s/wdt4mdstdr4eu
 * Gradle 5.1.1: fails https://gradle.com/s/cbnufqqpvkerq
 * Gradle 5.6.4: fails https://gradle.com/s/jin3pubzwklow
 * Gradle 6.0.1: fails https://gradle.com/s/stzmvsx7axyd4

**Comment by TWiStErRob** [comment]
I tried these workarounds (didn't work):
 * `{ transitive = true }`
 * `compileOnly 'org.ajoberstar:gradle-git:1.7.2'`
 * `compile 'org.ajoberstar:gradle-git:1.7.2'`

before I managed to work around by adding the dependencies I'm using:
```gradle
    implementation 'org.ajoberstar:gradle-git:1.7.2'
    implementation /*+--- */ 'org.ajoberstar:grgit:1.9.3'
    implementation /*|    +--- */ 'org.eclipse.jgit:org.eclipse.jgit:4.5.2.201704071617-r'
```

**Comment by jjohannes** [comment]
@TWiStErRob the behavior you are observing is expected. Starting with 5.0, Gradle respects the separation of API and runtime dependencies. That means, for modules with POM metadata, that only dependencies with `compile` scope are visible on the compile classpath.

The dependency that "disappeared" - `org.ajoberstar:grgit` - is declared in [runtime scope](https://repo1.maven.org/maven2/org/ajoberstar/gradle-git/1.7.2/gradle-git-1.7.2.pom).

If you need the dependency at compile time, you need to declare them directly as you did already as "workaround": `implementation 'org.ajoberstar:grgit:1.9.3'`

If you believe that the metadata is wrong, because you do not use classes of `grgit` directly (the error message seems to indicate that), you can also write a component metadata rule to "fix" the wrong scope in the metadata:
https://docs.gradle.org/current/userguide/component_metadata_rules.html#fixing_wrong_dependency_details

Something like:
```
context.details.variant("compile") {
  withDependencies {
    add("org.ajoberstar:grgit:1.9.3")
  }
}
```
