### ISSUE TITLE
LongCommandLineDetectionUtil: Improve limits of MAX_ARG for creating path jar

### ISSUE THREAD

**Issue by rpalcolea** [gradle/gradle#11909]
Hi folks!

Related to https://github.com/gradle/gradle/pull/11908 and https://github.com/gradle/gradle/issues/11907

Current implementation of `LongCommandLineDetectionUtil` uses hardcoded values for Unix/Linux and the proposed new value for OSX in https://github.com/gradle/gradle/pull/11908

While this is the default setup for these OS, after doing some reading on https://unix.stackexchange.com/questions/120642/what-defines-the-maximum-size-for-a-command-single-argument and https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b6a2fea39318e43fee84fa7b0b90d68bed92d2ba... it seems like it would be ideal if gradle reads the value `getconf ARG_MAX` to get current system configuration in case people either increased/decreased the stack size or just modified the `ARG_MAX` in `limits.h`. 

wondering if any of the following ideas makes sense:

* Option 1: read `ARG_MAX` from the system every time `LongCommandLineDetectionUtil` is invoked, maybe some cache would be required here to avoid doing it on every build

* Option 2: Set a low limit by default in `LongCommandLineDetectionUtil` for every system. For example: 5000. While the path jar might make sense to be created only when argument list is too long, it is also important to note that if we had `2097151` in linux (under the limit), if you were to analyze a process, the details of the process would be just massive in a terminal. This way, gradle would always create a path jar after a hard limit that still human readable. Since Gradle creates the Jar with the manifest, the manifest could be also exposed in a friendly folder in case users would like to check the classpath of the path jar (the original arguments).

* Option 3: Always do a path jar, which might seem aggressive but would reduce the need for system based configuration. Also it would improve readability of processes.

Thoughts?

**Comment by chali** [comment]
From the consistency point of view, I would prefer Option 3.

**Comment by lacasseio** [comment]
We voted initially for having a good enough maximum that is not exactly the one set by the OS but close enough. The macOS vs Linux difference was a confusion from different source of information. It's not a trivial process to extra the right value which led to setting a good enough maximum size for most cases. When you encounter issue like you had, it's good to tell us so we can adjust those artificial limits.

We don't want to always create a pathing JAR because it has some implication on performance and may fail because of the pathing JAR. Instead, we will create a pathing JAR when we are guesstimating that what you ask Gradle to do would most likely fail so if the pathing JAR introduce cause a failure, it's a better result than failing and having to deal with the pathing JAR yourself. With time and as people report any issues, we can adjust the logic to address corner cases.

It is unlikely that we will head in a different direction so I will just close this issue.

**Comment by rpalcolea** [comment]
Hi @lacasseio ,

Thanks for sharing this info. This is very helpful!
