### ISSUE TITLE
KotlinCachingSmokeTest should be reworked to test supported Kotlin versions

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#11904]
At the time of writing this Build Cache test is running against Kotlin 1.2.70-eap-40, so it's been a while it hasn't been updated.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
The problem is we are running this test via https://github.com/gradle/kotlin-relocation-test, which is not maintained anymore. I'd fix this by the following:

1) reimplement the test to build Santa Tracker instead of Spek
2) move the test to `gradle/gradle`
3) drop the https://github.com/gradle/kotlin-relocation-test repo

**Comment by ljacomet** [comment]
I know I worked on that test for Gradle 6.0 and I am pretty sure it is working with a more recent Kotlin version.
`KotlinCachingSmokeTest` on `gradle/gradle` `master` uses the `gradle-6.0` branch of `gradle/kotlin-relocation-test` which defaults to Kotlin 1.3.30 [in the test class](https://github.com/gradle/kotlin-relocation-test/blob/8773fea79aa2278db59238adb4bd701ed24d2246/src/test/groovy/org/gradle/kotlin/test/RelocationTest.groovy#L25-L26) while the Gradle version is injected when running.

The proposal of @lptr to improve this test gets 👍 from me.

**Comment by eskatos** [comment]
Hardcoded to a given Kotlin version this smoke test is of no use at all.
Moreover it gets in the way because it starts to fail when trying to upgrade the embedded Kotlin to 1.4.
After discussing this with the execution team https://github.com/gradle/gradle/pull/14547 simply removes it.
