### ISSUE TITLE
German umlaute are replaced with cryptic characters after unpacking zip-archive

### ISSUE THREAD

**Issue by leozent** [gradle/gradle#11983]
I'm trying to extract a zip-file, which includes files with a german umlaut in its filename.
After unpacking the zip-file, all umlaute are replaced with cryptic characters.

**My Gradle Task**

```groovy
task extractZip(dependsOn: clean){
    doLast{
        copy {
            FileTree updateZip = zipTree(file("$projectDir/UmlauteInside.zip"))
            from updateZip
            into file("$buildDir/extractedZipfile")
        }
    }
}
```
| Filenames inside the Zip-Archive | Filenames after extracting the Zip-Archive|
| ------------------------------------ | ------------------------------------ |  
|  Umlaute-ÄÖÜ.txt | Umlaute-Ž™š.txt|  
|  Ä.txt | Ž.txt |  
|  Ö.txt | ™.txt |  
|  Ü.txt | š.txt |  

### Expected Behavior
The umlaute should be taken over as they are

### Current Behavior
The umlaute are replaced with special or cryptic characters

### Steps to Reproduce 
Example Project on GitHub: https://github.com/leozent/gradleExtractZip
Usage on commandline: `.\gradlew extractZip`

### Your Environment
Build scan URL: https://scans.gradle.com/s/zxfl4sltrmzqi

**Comment by jeffalder** [comment]
@leozent 
This is an interesting problem, but I think it's fundamentally about code page mismatches.

The first file in the attached zip, "Umlaute-ÄÖÜ.txt", encodes Ä as hex 0x8e (dec 216):
```
% hexdump -c -x -s 30 -n 15 UmlauteInside.zip
000001e   U   m   l   a   u   t   e   - 216 231 232   .   t   x   t
000001e    6d55    616c    7475    2d65    998e    2e9a    7874    0074
```

That encoding looks consistent with [Code page 437](https://en.wikipedia.org/wiki/Code_page_437), which indicates to me that the files were created with a computer or file system running on CP437.

The linked gradle scan indicates that Windows-1252 is in use. According to [Wikipedia](https://en.wikipedia.org/wiki/Windows-1252), you would see Ž™š because 0x8e encodes Ž, 0x99 encodes ™, and 0x9a encodes š. The translation you report matches that, so the hypothesis seems to be consistent.

I notice that on my Mac, which is UTF-8, I'm getting even odder glyphs because none of those (0x8e, 0x99, or 0x9a) are valid UTF-8 code points alone.

The [Zip file format](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT), as far as I can tell, doesn't provide a way for the Zip file to denote the encoding of the file names. So your most expedient fix is to resolve this via tools, like 7zip and bsdtar, that can pre-convert encodings as-is.

I want to experiment with supporting the specification of a `Charset` in `zipTree`, since the underlying library in use does support passing an encoding name, and there is explicit support in that library for CP437 encoding. Then the code would be something like:
```
FileTree updateZip = zipTree(file("$projectDir/UmlauteInside.zip"), "CP437")
```
Would that be sufficient for your use case?
