### ISSUE TITLE
strictly does not override constraint version from a project dependency

### ISSUE THREAD

**Issue by anuraaga** [gradle/gradle#12016]
### Expected Behavior

When a project depends on another project with a constraint version, it should be able to downgrade the version using `strictly`.

### Current Behavior
Another project's constraint version cannot be downgraded and the build fails to resolve versions. There doesn't seem to be a way to exclude the constraints either.

### Context
I use constraints to apply dependency management to projects in a multi-project build. There is one set of versioned dependencies and all projects have the versions applied using something like

```groovy
dependencies {
  constraints {
    versions.each {
      api "${version.group}:${version.module}:${version.version}"
    }
  }
}
```

This means that many constraints are added to projects even though there is no dependency declaration. I found that when adding a project dependency, all of it's constraints are applied even if the project does not have a dependency matching them. This means that for dependency A, there is no way to exclude the transitive dependency A from this project dependency - it is not a listed dependency, but it's constraint is applied either way.

This would be fine, but it seems that `strictly` does not override the version in this case. `force` works fine, but is deprecated

https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#forced_dependencies_vs_strict_dependencies

The language "If, for some reason, you can’t use strict versions, you can force a dependency doing this:" makes me think that this is not an intended case.

### Steps to Reproduce 

~~- git clone https://github.com/anuraaga/gradle-constraint-overrides~~
~~- cd gradle-constraint-overrides~~
~~- ./gradlew :consumer:dependencies~~

Apologies for the complex example, my attempt above at simplifying it didn't reproduce yet.

- git clone https://github.com/anuraaga/armeria/
- git fetch origin modern-gradle
- git checkout modern-gradle
- Comment out https://github.com/anuraaga/armeria/blob/modern-gradle/thrift0.9/build.gradle#L14
- ./gradlew :thrift0.9:dependencies --configuration compileClasspath
  - Note the thrift dependencies have `FAILED` to resolve

### Your Environment

Build scan URL: https://gradle.com/s/s3hab734ooyzi

**Comment by jjohannes** [comment]
Hi @anuraaga, 
The behavior that the constraints provided by a project/module down the graph are used even if that project/module does not have a corresponding dependency is expected. It's one of the features of constraints that you can say: "I do not necessarily need X, so I do not depend on X, but **if** X is used, then the following constraints apply". 

In the example and the build scan you shared, there are no repository declarations. Because of that, Gradle fails before it can resolve the versions and the conflict (that's why there are failures for both versions).

If I add a `mavenCentral()` to your sample, _strictly_ works as expected.

Do I miss something?

**Comment by anuraaga** [comment]
Thanks @jjohannes - I tried to extract a simple example from a complex repo but obviously didn't do a good job. 

For now, let me also link the complex example

https://github.com/anuraaga/armeria/tree/modern-gradle

Note this build file

https://github.com/anuraaga/armeria/blob/modern-gradle/thrift0.9/build.gradle#L13

If you run `./gradlew :thrift0.9:dependencies --configuration compileClasspath` it fails to resolve the thrift dependencies if you comment out the `resolutionStrategy.force` line.

Constraints are added here

https://github.com/anuraaga/armeria/blob/modern-gradle/gradle/scripts/lib/common-dependencies.gradle#L75

**Comment by jjohannes** [comment]
@anuraaga what you are seeing is expected. You have this situation:

```
> Cannot find a version of 'org.apache.thrift:libthrift' that satisfies the version constraints:
  Dependency path 'com.linecorp.armeria:thrift0.9:0.97.1-SNAPSHOT' --> 'org.apache.thrift:libthrift:{strictly 0.9.3-1}'
  Constraint path 'com.linecorp.armeria:thrift0.9:0.97.1-SNAPSHOT' --> 'org.apache.thrift:libthrift:0.13.0'
  Constraint path 'com.linecorp.armeria:thrift0.9:0.97.1-SNAPSHOT' --> 'org.apache.thrift:libthrift:0.13.0'
  Constraint path 'com.linecorp.armeria:thrift0.9:0.97.1-SNAPSHOT' --> 'com.linecorp.armeria:core:0.97.1-SNAPSHOT' --> 'org.apache.thrift:libthrift:0.13.0'
```
It means that you are defining multiple dependency version constraints to `org.apache.thrift:libthrift` from **the same** project (com.linecorp.armeria:thrift0.9). Strictly only "overrides" versions down the dependency graph. This is by design.

Instead of using an `allprojects` to define constraints, you should use a separate [platform project](https://docs.gradle.org/current/userguide/java_platform_plugin.html) and define dependencies to that from all projects. Then the constraints are defined "further down the graph" and strictly will "override" them.

**Comment by anuraaga** [comment]
Thanks @jjohannes - I'll go with a platform. I was trying to avoid it since we don't want to publish it (we publish with resolved versions instead) so an extra project seems like overkill for dependency management. Any thoughts on having constraints in the same project being considered "further down the graph" than direct dependency declarations? Might not make sense but just a thought, it would have been most natural behavior for me here.

**Comment by jjohannes** [comment]
@anuraaga if you use resolved version, you can sue the following pattern with an additional configuration for the platform dependency to **not publish** the platform: https://github.com/gradle/gradle/issues/10861#issuecomment-576562961

(we might provide a built-in solution for that use case is the future)

Regarding

> having constraints in the same project being considered "further down the graph" 

You can do that by adding a separate _variant_ to the project that carries the constraints and then depend on that _variant_. Something similar to this: https://github.com/jjohannes/agp-strict-classpath/blob/master/app/build.gradle

- Define a configuration (variant) -like `strictRuntimePlatform` [here](https://github.com/jjohannes/agp-strict-classpath/blob/master/app/build.gradle#L52-L56)
- Add constraints to that configurations (instead of api or implementation)
- depend on yourself, but request the "strict platform" variant like [here](https://github.com/jjohannes/agp-strict-classpath/blob/master/app/build.gradle#L78-L81)

**Comment by anuraaga** [comment]
Thanks a lot for these tips they're really helpful! I would have never thought of using a variant but it would be a nice trick.

If I can ask just one more question (hope these are good suggestions for documentation additions :) ), I notice in https://github.com/gradle/gradle/issues/10861#issuecomment-576562961 you suggest adding the platform to leaf configurations compileClasspath, runtimeClasspath, etc

I usually do the opposite, apply to roots using something like

```
dependencies { configurations.each { configuration -> // Add to root configurations if (configuration.extendsFrom.isEmpty() && // Gradle bug prevents managing jacoco versions through platform. // https://github.com/gradle/gradle/issues/11209 configuration.name != 'jacocoAnt' && configuration.name != 'jacocoAgent') { add(configuration.name, platform(dependencyProject)) }
```

This allows managing configurations like `annotationProcessor` too. Is there a recommendation for applying to leaves vs roots? Unfortunately I don't know a code pattern to get all leaf configurations very easily vs root and checking extendsFrom.

Though having one method, which allows applying a platform to all dependency resolution ever, would be nice to have instead of worrying about configurations perhaps it's too powerful though.

**Comment by jjohannes** [comment]
_configurations_ are now distinguished in three categories

1. to declare dependencies (e.g. implementation)
2. to resolve dependencies (e.g. compileClasspath)
3. to declare something to be consumed by other project (consumable configuration), this is also what usually gets published (e.g. apiElements)

More details: https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs

If you want to do something _generic_ it is recommended to follow these categories. The API is a bit awkward because this evolved. But basically you can use these tests:

```
if (configuration.canBeConsumed && !configuration.canBeResolved) {
  // all configurations that are published (apiElements, runtimeElements, ...)
}
if (!configuration.canBeConsumed && configuration.canBeResolved) {
  // all configurations that are resolved in the project (compileClasspath, runtimeClasspath, ...)
}
if (!configuration.canBeResolved && !configuration.canBeConsumed) {
  // all configurations used to declare dependencies (implementation, api, ...)
}
if (configuration.canBeResolved && configuration.canBeConsumed) {
  // legacy, should be avoided and will be removed (compile, runtime, ...)
}
```

So https://github.com/gradle/gradle/issues/10861#issuecomment-576562961 adds a new configuration to declare dependencies that only goes into the resolution (by making the _resolvable_ configurations extend from it) but not into publishing (by **not** making the _consumable_ configurations extend from it).

So a more generic script for that would be:
```
configurations.each { configuration ->
  if (configuration.canBeResolved && !configuration.canBeConsumed) {
    it.extendsFrom internal
  }
}
```
A danger here is that you need to make sure that the configuration code runs after the `canBeResolved` and `canBeConsumed` have been set on the corresponding configuration (e.g. by the Java plugin). We don't have a good API for making sure that this has already been done. So you need to make sure to put your code after the Java plugin was applied and configured (if you add additional source sets or feature variants) or do it in `afterEvaluate {}`.

**Comment by anuraaga** [comment]
Thanks a lot for this! I have tried to grok these properties of configurations but your comments make them very clear. Will try applying them to simplify my code :)
