### ISSUE TITLE
dependencyLocking.lockMode = STRICT outputs error about missing compileOnly lockfile

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#12010]
`./gradlew dependencies --write-locks` does not generate a lockfile for the compileOnly configuration, as it shouldn't be used for resolution.

If I include the following in my `build.gradle.kts`, however, Gradle 6.1.1 outputs an error:

```kotlin
dependencyLocking {
    lockAllConfigurations()
    lockMode = STRICT
}
```

Error:

```
Configuration ':compileOnly' is locked but does not have a lockfile.
```

### Expected Behavior
I expect no compileOnly lockfile, and no complaints from `lockMode = STRICT` that the compileOnly lockfile doesn't exist.  The same should occur for any other non-resolution configurations.

### Current Behavior
I get the aforementioned error.

**Comment by ljacomet** [comment]
You can only get this error if `compileOnly` is _effectively resolved_ in your build. Then it will complain that it does not have a lockfile.

The following will _not_ mark `compileOnly` as locked, because this generic method pays attention to the role of each configuration:
```
dependencyLocking {
    lockAllConfigurations()
    lockMode = STRICT
}
```
Similarly, running `dependencies` will not resolve `compileOnly`

If you cannot prevent `compileOnly` from being resolved in your build, you can still lock it explicitly:
`configurations.compileOnly.resolutionStrategy.activateDependencyLocking()`

And then make sure a lockfile is produced for it.

**Comment by jjohannes** [comment]
Not that you might need to uses this workaround in IDEA currently to avoid this issue which will be fixed in IDEA 2020.1: https://youtrack.jetbrains.com/issue/IDEA-229075

**Comment by rgoldberg** [comment]
@ljacomet Thanks for the info.  I cannot remember if I ran the build in IntelliJ or from the command line.

I don't use `compileOnly` myself.  I'll have to investigate why it was used (either from IntelliJ or some other source).

I'm not I understand:

> The following will _not_ mark `compileOnly` as locked, because this generic method pays attention to the role of each configuration:
> 
> ```
> dependencyLocking {
>     lockAllConfigurations()
>     lockMode = STRICT
> }
> ```

If that doesn't mark `compileOnly` as locked, then why did `lockMode = STRICT` cause an error that said that `compileOnly` is locked?

Error:

```
Configuration ':compileOnly' is locked but does not have a lockfile.
```

**Comment by jjohannes** [comment]
We have this situation because `compileOnly` was introduced before the distinction between _resolvable_ and _not-resolvable_ configurations. Resolving `compileOnly` is deprecated and also prints a deprecation warning. Builds/plugins/tools can still trigger it (but should be updated to not do it). This will become an error in Gradle 7 and then the situation described in this issue will not happen anymore.

**Comment by ljacomet** [comment]
Ah, there is indeed a flaw in my logic right there 🤔 

So I double checked and went a bit too fast.
* `lockAllConfigurations()` will indeed end up locking `compileOnly`
* `dependencies` does not resolve `compileOnly` and thus does not create a lockfile for it.

**Comment by rgoldberg** [comment]
So far today, I've only seen this issue in IntelliJ 2020.1 EAP.  The next release of that EAP should include the aforementioned fix, so hopefully this issue will disappear for me very soon.

**Comment by ljacomet** [comment]
Removed the bug label and closing as the behavior is correct, though it can be surprising.
