### ISSUE TITLE
Add a command-line flag to enable watching the file system for changes

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#12053]
This replaces the `org.gradle.unsafe.vfs.retention` property, though we should probably introduce a non-`unsafe` property as well, so that users can still turn it on via `gradle.properties`.

For the name I like `--watch-changes` best for now. I don't like `--watch-file-system` because it's too long, `--watch-fs` is too cryptic. `--with-vfs-retention` is another option, though we don't want to mention the VFS in public APIs, so this one is out, too.

---
cc: @gradle/build-cache

**Comment by lptr** [comment]
Some ideas for how the flag could work: https://docs.google.com/document/d/1ot_bJm8VLO8McJTPPLeZ9NZN6ancjPSSBD1-nfj-t08/

**Comment by lptr** [comment]
We'll need this for the public release, and I think it would make sense to do this asap.

**Comment by wolfs** [comment]
We should use the same mechanics as for the instant execution flag: https://github.com/gradle/instant-execution/issues/161

**Comment by big-guy** [comment]
@rieske has been thinking about "build options" a bit in the context of asking for credentials and I've had some conversations with Adam about what a "build option" might be.  So if there's something that you guys and the IE team need, we might be able to help if you have other things that need to get done first. /cc @eskatos 

My 2 cents is to avoid a name that makes this sound like continuous build or file watching in the sense that it triggers something. `--watch-changes` sounds a bit like that. What about "track" or "monitor"? e.g., `--track-files` `--track-content` `--monitor`.  I think the negative works best with "monitor" (`--no-monitor`), since `--no-track-files` makes it sound like we're disabling up-to-date checking completely.

**Comment by lptr** [comment]
`--track-fs`? I don't like `--track-files` for the same reason as @big-guy.

**Comment by ldaley** [comment]
I've mentioned it elsewhere, but I think we need to consider this in a larger context.

IIUC, this feature is “just” an optimisation. I always want it, if I'm going to execute more than one build, unless it doesn't work for me for some reason. Instant execution is in the same boat. Ideally, users would just tell Gradle somehow that more builds are expected so optimisations for that are justified.

I get that until we are confident in stability we may want it to be opt-in instead of opt-out, but whatever we do now should keep this in mind.

**Comment by wolfs** [comment]
For the optimization (and later the disabling of this particular optimization) of file system watching, we ended up with the following name:

`--[no-]watch-fs` / “file system watching” and the gradle build option `org.gradle.unsafe.watch-fs`.

For the final release, we will change the namespace of the build option to ` org.gradle.watch-fs` (enabled by default). We could add further properties in this namespace, e.g. `org.gradle.watch-fs.windows.buffer-size=128k`
