### ISSUE TITLE
Gradle tooling api doesn't respect proxy configuration for distribution downloading

### ISSUE THREAD

**Issue by vladsoroka** [gradle/gradle#12060]
Given all the necessary proxy settings and credentials are in gradle.properties and command line gradlew is able to successfully use it.

### Expected Behavior
No, further proxy configuration is needed for the project import in IDE.
Or at least it should be possible to pass similar proxy configuration to the Gradle tooling api.

### Current Behavior
The import might fail since Gradle tooling client side code doesn't use proxy information for Gradle distribution downloading.
`LongRunningOperation#setJvmArguments` doesn't help to make Gradle distribution downloader aware of proxy system properties.

Related issue from the IntelliJ IDEA issue tracker: https://youtrack.jetbrains.com/issue/IDEA-184697

**Comment by sschuberth** [comment]
I believe this is a duplicate of https://github.com/gradle/gradle/issues/6825, @vladsoroka.

**Comment by oehme** [comment]
This was not a duplicate and should be reopened. The cause of this issue is that the distribution download happens in-process in the Tooling API and so the proxy settings of the IDE are used, rather than the proxy settings in gradle.properties. The command line client reads gradle.properties and modifies its own system properties. This approach wouldn't work in the IDE, because we can't mutate the IDE's system properties. This leaves us with two options:

1. For a new VM for the distribution download
2. Explicitly configure proxy settings for the download from gradle.properties
