### ISSUE TITLE
Gradle last versions does not work with jupiter

### ISSUE THREAD

**Issue by yekaterinasavelyeva** [gradle/gradle#12191]
Gradle is not running tests during 'test' phase if org.junit.jupiter:junit-jupiter:5.6.0 is applied

### Expected Behavior
Tests should be ran 

### Current Behavior
tests do not run. 
Intellij Displays message: test events were not received

### Context
Error appears when trying to run java project tests with the latest jupiter library

### Steps to Reproduce 
-create tests with the latest jupiter dependency in Java project in IntelliJ
-run tests.

### Your Environment
gradle version tried  - 6.1.1 and older
build.gradle
```
plugins {
    id 'org.springframework.boot' version '2.2.4.RELEASE'
    id "com.palantir.docker" version "0.21.0"
    id "io.freefair.lombok" version "4.1.6"
    id 'org.liquibase.gradle' version '2.0.1'
    id "com.github.ManifestClasspath" version "0.1.0-RELEASE"
}

repositories {
    mavenCentral()
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'com.palantir.docker'
apply plugin: "io.freefair.lombok"
apply plugin: "com.github.ManifestClasspath"
apply plugin: 'application'

group '...'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

springBoot {
    mainClassName = '...'
}

repositories {
    mavenCentral()
}

dependencies {
//other dependencies

    runtimeOnly 'com.h2database:h2:1.4.193'

    compile group: 'org.yaml', name: 'snakeyaml', version: '1.25'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.4.2'
    testRuntimeOnly  'org.junit.jupiter:junit-jupiter-engine:5.4.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.4.2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    // Enable JUnit 5 (Gradle 4.6+).
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
}
```

**Comment by vlsi** [comment]
@yekaterinasavelyeva , Can you please check https://github.com/junit-team/junit5-samples ?

This looks like a sample of using Gradle + JUpiter 5.6.0 + Gradle, and it works: https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle-groovy

**Comment by yekaterinasavelyeva** [comment]
> @yekaterinasavelyeva , Can you please check https://github.com/junit-team/junit5-samples ?
> 
> This looks like a sample of using Gradle + JUpiter 5.6.0 + Gradle, and it works: https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle-groovy


These are groovy tests, but I need to set up java tests, which worked fine with jupiter 5,4,2, but are broken with 5,6,0

this is what I hade before jupiter update to 5.6.0

 testImplementation 'org.junit.jupiter:junit-jupiter-api:5.4.2'
    testRuntimeOnly  'org.junit.jupiter:junit-jupiter-engine:5.4.2'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.4.2'

**Comment by vlsi** [comment]
Here's Jupiter 5.6.0, Java: https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle

**Comment by ljacomet** [comment]
One thing that could be happening:

Gradle up-to-date checking: if you ran the tests once and run them again without changing anything, Gradle will skip running them, resulting the IntelliJ showing that message
> test events were not received

Can you verify by changing the test and attempting to run it again? Can you attempt running it on the CLI?

**Comment by bjornvester** [comment]
If it is the problem Louis mentioned, and you have caching enabled, there is an open issue for it on the JetBrains issue tracker here: https://youtrack.jetbrains.com/issue/IDEA-210779. You can up-vote it to give it more attention.

A work-around is to put in the following configuration in your build file:

```
tasks.withType(Test).configureEach { it.outputs.upToDateWhen { System.getProperty("idea.version") == null } }
```

**Comment by yekaterinasavelyeva** [comment]
I have tried changing tests, but with no luck. I have even invalidated caches, restarted, but that did not help. With previous version nothing like that happened.
Workarounds are great, thanks, but as for me - I changed for previous version, because even the newest Gradle version does not work with the newest jupiter, but works fine with jupiter 5.4.2.

**Comment by yekaterinasavelyeva** [comment]
And no, I do not have caching enabled, as you can see from build.gradle above.

**Comment by yekaterinasavelyeva** [comment]
> Here's Jupiter 5.6.0, Java: https://github.com/junit-team/junit5-samples/tree/master/junit5-jupiter-starter-gradle

Do you think it is jupiter 5.6.0 issue and I have to contact them?

**Comment by bjornvester** [comment]
I tried your build file and ran a JUnit 5 test in IntelliJ. It worked with JUnit 5.4.2, but with 5.6.0 it gave me the following error:

```
> Task :test FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':test'.
> No tests found for given includes: [jupiter.LibraryTest](filter.includeTestsMatching)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```

It worked fine outside IntelliJ (with the Gradle CLI) without specifying the a particular test suite.

I looked into it, and it seems it is actually the Spring Dependency Management plugin that is causing you issues. If you run `gradle dependencies --configuration testRuntimeClasspath`, you should see that it downgrades some JUnit libraries from 5.6.0 to 5.5.2 but not others, and I assume that just won't fly.

The idea behind the plugin is to lock dependencies into versions that have been tested and are supposed to be compatible with each other. You can even remove the versions from your build file, and Spring will still select what it thinks is the best for you.

I don't use the plugin myself (even on my Spring Boot projects) so I don't know how to configure it. But what I do instead of the plugin is to import the Spring Boot BOM as a platform like this:

```
// apply plugin: 'io.spring.dependency-management' <-- Delete this
dependencies {
    implementation platform('org.springframework.boot:spring-boot-dependencies:2.2.4.RELEASE')
}
```

It will still use sensible default versions if you don't supply them yourself, and it will upgrade them if you have selected a lower version. But it will not downgrade them like the plugin does.

If this works for you, may I suggest you close this issue (these are mostly for actual bugs in Gradle)? We can continue talking about it in on the Gradle forums or the Gradle Slack channel if you like.

By the way, caching is not something you enable in the build.gradle file. It can be done in several ways, but most commonly in a gradle.properties file :)

**Comment by yekaterinasavelyeva** [comment]
> implementation platform(

Thank you very much, looks like you are 100% right. So I am closing an issue.

**Comment by lukaszlenart** [comment]
Thanks @bjornvester for you solution, it fixed my problem as well :)
