### ISSUE TITLE
UtilsKt.copyTo throws FileNotFoundException

### ISSUE THREAD

**Issue by aeiplatform** [gradle/gradle#12239]
[Kotlin issue: KT-36643](https://youtrack.jetbrains.com/issue/KT-36643)

_Gradle 5.6.4_

This issue was created to be linked to **Kotlin** because it occurs in `build.gradle.kts`.

**Comment by big-guy** [comment]
If this is a Kotlin issue, it's best left there.  Looking at the issue raised there, I would recommend a couple of things:

- Never use `File(String)` (or `new File(String)` in Java) in your build scripts or plugins.  This constructor is relative to the _current working directory of the process_ and that's not going to be the project directory.  I can't quite tell if this is what's causing your problem.
- Consider using Gradle's file related APIs instead of Kotlin's.  This is a balance between convenience (using the Kotlin APIs) and consistency (getting the same kind of Gradle behavior).  Gradle has a `Project.copy(CopySpec)` and `Project.sync(CopySpec)` that will probably do what you want just as well.
- From your snippet, I can't tell where that bit of code actually is.  If it's just in your build.gradle.kts and not in a task's action, you should consider moving it to a task action.  Otherwise, the build will be doing potentially expensive work during configuration time and failures here will be harder to deal with.  e.g., when importing into the IDE, Gradle has to configure the build and if that requires copying 100's of MBs of files, your sync time will be slower.

**Comment by aeiplatform** [comment]
- Might be, but the `root` directory is created without any problem.
- I'm gonna try that since Kotlin isn't capable to do that.
- Yeah, don't worry the code snipped is from the root **build.gradle.kts** `tasks.register...`
