### ISSUE TITLE
Add official local.properties support

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#12283]
It would be awesome if gradle officially supported `local.properties` so we don't' have to load the file into memory ourselves

**Comment by big-guy** [comment]
I don't think we want to do this for a couple of reasons:

- We already have several layers of `gradle.properties` and the CLI.  Adding another properties file blurs the precedence of these files.  
- We would rather provide an API for plugins/build scripts to get values for properties from files like `local.properties` without allowing just anything to be put in a file like that.  

If you have common configuration that is user level `GRADLE_USER_HOME/gradle.properties` is the place for that.

**Comment by ZakTaccardi** [comment]
Maybe I should specify what I am hoping Gradle provides a solution for.

`gradle.properties` allows us to define default properties in a file. This can be checked in and shared via source control. We however, may want to override these properties **without** checking in the code to do that (on a per-project basis).

For example, I may want to test out an unreleased (non-stable) version of the Android Gradle Plugin locally (defined in a `local.properties` style file that is not checked in to source control), while CI and the rest of my team rely on the stable version (in `gradle.properties`, part of source control).

> We would rather provide an API for plugins/build scripts to get values for properties from files like local.properties without allowing just anything to be put in a file like that.

Is there an issue tracking this?

**Comment by ZakTaccardi** [comment]
note: our current solution is to manually load data from `local.properties` with a higher precedence than gradle properties, which is a bit frustrating as it is a completely manual process. Personally, I would like to see Gradle properties automatically loaded given the following precedence: 

1. command line param
2. local property file
3. gradle property file

**Comment by ZakTaccardi** [comment]
I've started using APIs like:

```
val firebaseApiKey = providers.gradleProperty("firebase.apiKey")
```

but this does not work well as I have custom scripting for `local.properties` support, as an API key cannot be checked in to GitHub.

Official support for `local.properties` would save a lot of headaches here

**Comment by CristianGM** [comment]
If you don't add the Firebase key to your repository, how does your CI work?

We use environment variables for that (encrypted for CI) and our local builds can use another key (just for the debug build) because ewe don't want to polite our production data.

I guess there are valid reasons for this issue, but I don't think that is a good example

**Comment by Vampire** [comment]
I also second the request to have a project specific properties file that is meant to not be checked into version control that is precedence-wise between GRADLE_USER_HOME `gradle.properties` and `-P` arguments.
I usually used https://github.com/stevesaliman/gradle-properties-plugin/ for this, and thus had it called `gradle-local.properties`, but with the rules for configuration cache this plugin will probably not work anymore as intended, because it reads the standard locations plus the extra file in order and then sets those values as extra properties, so that then if someone gets the property from the project, the extra property with the added overwriting logic is used.

But starting with configuration cache safely using `providers.gradleProperty` instead, this trick will no longer work and thus the plugin greatly loose in value.

Also having user-specific values only in GRADLE_USER_HOME is not sufficient, because you might need different values for different projects you work on for the same property and that is not realizable with one common `gradle.properties` for all projects. Or another use-case would be to have different values for different worktrees of the same project.

So I'd also welcome a built-in solution for a work-tree specific local properties file that is not checked into version control and that is able to set project properties in a configuration cache safe way.

**Comment by dlin-ta** [comment]
If I place this in `~/.gradle/init.d/local-properties.gradle.kts`, it seems to have some of the the desired behavior (`local.properties` overrides `gradle.properties` but not `./gradlew -P...`). It seems too late to change the effect of some properties like `org.gradle.jvmargs` though.

```kotlin
import java.util.Properties

val localProps = Properties()

settingsEvaluated {
    File(rootDir, "local.properties").takeIf { it.exists() }?.inputStream()?.use(localProps::load)
    for (key in localProps.stringPropertyNames() - startParameter.projectProperties.keys) {
        extra[key] = localProps.getProperty(key)
    }
}

rootProject {
    for (key in localProps.stringPropertyNames() - startParameter.projectProperties.keys) {
        extra[key] = localProps.getProperty(key)
    }
}
```

**Comment by ephemient** [comment]
If I place this in `~/.gradle/init.d/local-properties.gradle.kts`, it seems to have some of the the desired behavior (`local.properties` overrides `gradle.properties` but not `./gradlew -P...`). It seems too late to change the effect of some properties like `org.gradle.jvmargs` though.

```kotlin
import java.util.Properties

val localProps = Properties()

settingsEvaluated {
    File(rootDir, "local.properties").takeIf { it.exists() }?.inputStream()?.use(localProps::load)
    for (key in localProps.stringPropertyNames() - startParameter.projectProperties.keys) {
        extra[key] = localProps.getProperty(key)
    }
}

rootProject {
    for (key in localProps.stringPropertyNames() - startParameter.projectProperties.keys) {
        extra[key] = localProps.getProperty(key)
    }
}
```

**Comment by Vampire** [comment]
As said before, there are existing work-arounds, usually using extra properties, like the gradle-properties plugin.
But those solutions, including this local init script which is not too user-friendly for the average developer that has to manually place that file to make it work, have the major drawback that you cannot properly do it like that if some code (that you maybe do not control as it is in some plugin) queries project properties in the new configuration cache safe way.

**Comment by ephemient** [comment]
Yes, it's a (simple) workaround and not a real solution.

That being said, even without my init script or other plugins, `-P` breaks configuration cache…

**Comment by Vampire** [comment]
If you have an example where it breaks, you should report it.
It is working perfectly fine and as expected with `-P` here.

**Comment by ZakTaccardi** [comment]
Had an idea to work around lack of official `local.properties` support.

What if we created a `./gradleLocal` script that just delegated to `./gradlew` but injected `local.properties` as start parameters (`-Pprop=someValue`).

In theory, this could be taken further, with something like `./gradleCi` or `./gradleDev` that loaded from `ci.properties` (for CI server) or `dev.properties` (for local development and guaranteed to have remote cache hits)

Thoughts?

**Comment by Vampire** [comment]
Loading a properties file from a shell script and / or batch script is not not trivial.
You either have to violate the rules for properties files or have strict restrictions so that there are no unicode escapes and so on to be able to work with it in a simplified fashion.
But actually you could also simply leave out the properties file and just have those scripts, set the `-P` properties in there and add them to your VCS ignore file.
Having the same `-P` multiple times would also be no problem as the last one wins.
But this would still feel a bit hacky and inconsistent.
I would really greatly prefer a way to do this properly with property files, either built-in or with a plugin.

I really think this issue should be reopened until either there is official support for `gradle-local.properties` or until there is an API that allows plugins to configuration-cache safe set Gradle properties, so that the properties plugin can be made configuration-cache safe.

**Comment by ZakTaccardi** [comment]
I almost found a workaround to fully support this with the configuration cache - but was unable to identify what gradle properties were passed on the command line as a StartParameter in a way that supported config caching

https://github.com/gradle/gradle/issues/19474

**Comment by ZakTaccardi** [comment]
That said - the solution above does work without config caching

**Comment by Vampire** [comment]
The main problem I see is, that it only works for properties that are read using that custom extension function. This will just increase confusion about what property you can set where. You cannot just set a property in one of the custom locations and it will work. The configuration-cache unsafe solution of the properties plugin to set the final properties as extension properties worked fine, but if now a plugin even uses the standard `providers.gradleProperty`, it will not work anymore. :-(

**Comment by ZakTaccardi** [comment]
> that it only works for properties that are read using that custom extension function

@vampire yep that's the caveat. If `providers.gradleProperty(..)` ever gets proper support for this use case, it's just a single line change to modify `providers.gradleProperty(project, ..)` (extension function) to `providers.gradleProperty(..)` (built in function). As they both return `Provider<String>` - the migration is trivial.

**Comment by autonomousapps** [comment]
I would also _desperately_ like something like local.properties support. See [conversation in community slack](https://gradle-community.slack.com/archives/CAHSN3LDN/p1656692009520239).

**Comment by joffrey-bion** [comment]
> If you have common configuration that is user level GRADLE_USER_HOME/gradle.properties is the place for that.

@big-guy I have personal secrets that are only relevant to one specific project. I certainly won't check them in, so the project's `gradle.properties` is out of the question, but I don't want *all* gradle builds on my machine in *any* project to access those secrets either.

What is the proper approach for this use case, if not a git-ignored `local.properties`?

**Comment by ephemient** [comment]
If it isn't doable inside Gradle, it's still possible outside of Gradle. One could use [direnv](https://direnv.net/) with
```sh
# .envrc
export ORG_GRADLE_PROJECT_someProperty=someValue
```
for example.

**Comment by joffrey-bion** [comment]
True, but the question is about what is worth supporting in Gradle itself. If there is a good case for it, and common enough, it probably has its place.

Also, I dev on windows, so `direnv` cannot really help me 😆

**Comment by ZakTaccardi** [comment]
> If you have common configuration that is user level GRADLE_USER_HOME/gradle.properties is the place for that.

I don't agree here. This is a global user configuration, and is overridden by project level properties.  The main use case for `local.properties` is to have it override project level `gradle.properties`, without needed to be checked into source control. For example:

```properties
# gradle.properties
# by default (in CI or a random dev's machine), I want:
org.gradle.jvmargs=-Xmx8G

# local.properties
# But my laptop has 32gb of ram, So let's bump it here
org.gradle.jvmargs=-Xmx16G
```

I can't use `GRADLE_USER_HOME/gradle.properties` for this value, because I don't want _every_ gradle project to have 16GB of RAM.

> We already have several layers of gradle.properties and the CLI. Adding another properties file blurs the precedence of these files.

I don't think this is too complex, as when you have:
  * `project/gradle.properties`
  * `project/local.properties` 
 
`project/local.properties` just takes precedence over `project/gradle.properties`. Downstream of this, there is no additional complication, because you simply merge `project/gradle.properties` with `project/local.properties`. The rest of the property loading layers (CLI) don't need to account for the existence of `local.properties`.

**Comment by Vampire** [comment]
That's actually questionable.
I'd say `<GRADLE_USER_HOME>/gradle.properties` beats `project/gradle.properties`
and `project/gradle-local.properties` beats `<GRADLE_USER_HOME>/gradle.properties`.
Because you want to be able to define a value for a property for all local builds, but then ovewrite that in `gradle-local.properties` of specific builds.

The current built-in order in Gradle is

- command line, as set using `-D`
- `gradle.properties` in `GRADLE_USER_HOME` directory
- `gradle.properties` in the project’s directory, then its parent project’s directory up to the build’s root directory
- `gradle.properties` in Gradle installation directory

Imho the desired order is

- command line, as set using `-D`
- `gradle-local.properties` in the project’s directory, then its parent project’s directory up to the build’s root directory
- `gradle.properties` in `GRADLE_USER_HOME` directory
- `gradle.properties` in the project’s directory, then its parent project’s directory up to the build’s root directory
- `gradle.properties` in Gradle installation directory

**Comment by joffrey-bion** [comment]
Is there anyone at Gradle following this thread? It seems there is a good case for reopening the issue, and yet all comments since the closure of the issue seem to have been ignored.

**Comment by shaquibimdad** [comment]
It would be super useful if project-wise direct local.properties support is present that directly correspond to .env or .env.local in most of the individual node projects. In terms of version controlling or at some point every dev looks at it and what we get is workarounds.

**Comment by kelemen** [comment]
I would like to add another specific story for this that came up: I want to enable the configuration cache for a particular project, but I can't check in this into the `<project-dir>/gradle.properties`, because it doesn't work for everything, so I can't force it on everyone. However, I'm willing to live with limitation for this project. However, I definitely can't turn it for every project I check out, because most project crashes with configuration cache turned on. To be honest, even if only the root project was allowed to have a local Gradle properties override, it would be more than enough (I believe it would be true for most).

As an additional note: If this was ever reconsidered, then I would prefer it to be put into `<project-dir>/.gradle/gradle.properties`. This way, the filename remains the same (which is just aesthetically pleasing to me), and `.gradle` is already excluded in pretty much all projects anyway.

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

It's unlikely that this feature will be implemented as described in the first message, but there are scenarios in the comments that we need to consider. 

The responsible team will take another look.

Related:
* https://github.com/gradle/gradle/issues/24976
* https://github.com/gradle/gradle/issues/19660

**Comment by joffrey-bion** [comment]
I'm not particularly attached to a specific solution, but I guess the need can be expressed more generally.

We need a way to define Gradle properties that are:

* defined locally by some developer (i.e. not shared in VCS, so not in `<project>/gradle.properties`)
* applied to a specific project, not machine-wide nor user-wide (so not in `$GRADLE_USER_HOME`, `$GRADLE_HOME`, or other global places that would affect other projects)
* persisted somewhere that is resilient to machine restarts (so not just passed on the command line, or set in a terminal session)

**Comment by marcskow** [comment]
+1 to what @joffrey-bion said. I would like to test some gradle configuration locally e.g. enabling org.gradle.configuration-cache, but only for myself and only for one project.

Adding it to command line every time is not an option because it is tedious and hard to automate, also IDE does not work well with such a solution.

I would like to have `local.properties` (name doesn't matter) to override some properties only for myself (it can be added to gitgnore so that it is not tracked by VCS).

**Comment by bric3** [comment]
This is really annoying to not have a solution provided by Gradle.

@big-guy closed this in 2020, but the landscape show it is still needed. Applying Gradle properties to a single project on a local machine that works consistently over multiple interactions (the IDE or command line) can be irritating.

Not to mention, that when one has multiple worktrees, one may need / want different configuration for these worktrees. (Or other clones)

And https://github.com/gradle/gradle/issues/24976 is not exactly the same, in my opinion this issue should be reopned.

**Comment by woj-tek** [comment]
I came here from https://discuss.gradle.org/t/precedence-of-gradle-properties/41366/2 looking for the exact same solution - to have an option to have "local properties override that won't be checked in the repository".

There are a number of use-cases for that and while there are other solutions they are mostly workarounds (and some may be quite inconvenient, for example using ENV vars or CLI properties, especially in the context of a sync in IDE).

I know it adds certain layer of complexity but, judging by the whole thread and voices in this issue, it seems that there is a rather huge demand for this feature so I would like to ask for @big-guy to re-evaluate closing of this issue and re-open it.

**Comment by steve-cuzzort** [comment]
also came from [https://discuss.gradle.org/t/precedence-of-gradle-properties/41366/2](url) and want to voice my need for `local.properties`

I make Android apps, and I always end up rolling my own system to do this.  So does every Android app developer I've ever worked with.  Everyone has their own non-standard way to accomplish `local.properties`, which is another headache to maintain.

Call it `local.properties` or whatever you want, but I need something to Allow me to locally override `gradle.properties`, and can (and probably should) only be at the root of the gradle project.  My main use-case is stuff like API Urls and Database info.  I may want to test locally without worrying about nuking everyone else.

**Comment by rocketraman** [comment]
> It's unlikely that this feature will be implemented as described in the first message, but there are scenarios in the comments that we need to consider.
> The responsible team will take another look.

@ov7a Given this comment, perhaps this issue should be reopened?

**Comment by steve-cuzzort** [comment]
@ov7a My main (and pretty much only need) is a standard way for individual developers to change config variables ON THEIR SYSTEM ONLY without having to edit ~/.gradle global config OR modify a checked-in file.

**Comment by autonomousapps** [comment]
Hey folks, we (at Block, fka Square) have an internal library that provides a kind of local.properties support. It isn't directly wired into gradle, so plugins have to actually request values directly from the local.properties file. It works for our use-cases.

If this is something that other teams think would be interesting, I could see about open sourcing it.

**Comment by dweiss** [comment]
I think everyone who ever faced this problem wrote something of their own... in Apache Lucene, we use a plugin I wrote - it adds "build options" which are basically value providers with layered sources (property file, properties, env variables, etc.). This does require an explicit declaration of such options - like here:

https://github.com/apache/lucene/blob/main/build-tools/build-infra/src/main/java/org/apache/lucene/gradle/plugins/java/TestsAndRandomizationPlugin.java#L174-L196

but the upside is that the options are then typed and can be organized into an overview printing all the available options, with all their current values, sources, etc. It's a good thing to have.

The plugin is not documented well, sorry. I'm just throwing it here as an idea more than a solution.
https://github.com/carrotsearch/gradle-opts-plugin

**Comment by devinrsmith** [comment]
I think making projects opt into a special configuration plugin to support this would be less-than-ideal. At least in my case a developer working on multiple projects from different organizations, I think trying to get organizational buy-in everywhere is a non-starter.

I do think that establishing a `local.properties`, or similar, convention is probably the best solution. Asking organizations to add `local.properties` into their `.gitignore` seems like a minimal lift.

Another potential way to implement this feature would be at the `~/.gradle` configuration layer, with some way to associated property files with their respective projects. As a quick sketch:

```sh
$ tree ~/.gradle/projects 
/home/devin/.gradle/projects
├── deephaven-core
│   ├── gradle.properties
│   └── project -> /home/devin/dev/deephaven/deephaven-core
└── iceberg
    ├── gradle.properties
    └── project -> /home/devin/dev/apache/iceberg

5 directories, 2 files
```

**Comment by alllex** [comment]
Sorry for the delayed reply. On behalf of the responsible team, we'd like to reopen the issue.

We are not committing to implementing the proposed solution, but we recognize the validity of the use cases highlighted by the discussion. We will keep this issue open until we either support the use cases in some form or explicitly decide not to support some of them.

We will also update the issue title and add a clarification next to the original description to make it easier for people to discover.

Having said that, this area is not an immediate priority, so it may take a while before we get to this.
Thank you for your patience!

**Comment by Shawlaw** [comment]
I think this can be implemented in the wrapper shell.

My solution to use per project's local.properties to determine jdk:
https://github.com/Shawlaw/gradlew-jdk-local/blob/main/README.en.md

**Comment by kelemen** [comment]
@Shawlaw Sadly, that is not a solution. It would be horrible if your build would behave differently if you started it via `gradlew` scripts or an IDE (or whatever other way).

**Comment by Shawlaw** [comment]
@kelemen I got your point. So I have adjusted my wording.

But in this issue, behaving differently is the desiring use case since `local.properties` should not be checked into the repository.

My solution is quite specific to patch the wrapper because I need to determine jdk that before gradle actual running.

UpdateDaemonJvm is the official solution, but in my case many projects are not allowed to upgrade the toolchains so then the patch it is.

**Comment by oasis9** [comment]
Chiming in to also voice my desire for this. I feel like I'm probably just looking in all the wrong places, but I'm finding it hard to determine what best practice is here for authenticating with a private repository while avoiding putting credentials into git or my ~/.gradle folder.

I have a CI pipeline that provides environment variables with credentials for my private dependency repo, which I check for in my build.gradle.kts file, with a fallback to gradle properties if they don't exist. I don't want to set these properties in my ~/.gradle folder as that seems like a cumbersome approach where different tokens are needed for different projects, but putting credentials in any checked in file isn't an option either.

From what I've been reading here, I should probably just load properties manually from a file that I gitignore. It certainly does make me wonder if I'm missing something obvious though, since this can't be the first time someone's come up against this.

Edit: I forgot to mention, I'd have just set the same environment variables in IntelliJ for use when I sync my gradle project, but I can't find a way to do this barring starting IntelliJ with those environment variables, which isn't desirable.

**Comment by kelemen** [comment]
@oasis9 I don't think different credentials for repositories using the same property name is very common. Nevertheless, I would not use environment variables if I were you (they are quite annoying). What I would do is that I would use different property names (as an override) for each credential. Say, I would read it like this:

```kotlin
val repoPassword = providers.gradleProperty("mycompany.myproject.repoPassword")
  .orElse(providers.gradleProperty("mycompany.default.repoPassword"))
  .get()
```

Depending on your circumstances, I might consider setting up the repositories in an init script (in `~/.gradle/init.d/`). In this case, I would make the `myproject` part of the property name match the directory name of your project (so that the init script can conveniently apply the repositories). You might combine this with an additional Gradle property to flag repositories who want the automatic repository setup from the init script (and let the init script skip those projects who do not opt-in for this).

**Comment by oasis9** [comment]
@kelemen I opted against bloating my ~/.gradle/gradle.properties file and instead went for the local.properties approach. Thank you though.

Edit: to clarify, I understand the risks with .gitignore and secrets, and I imagine the use of a file outside the repository guards against these risks, so I will endeavour to use that where possible. If this is the reason or one thereof for not using a local.properties file, I'd appreciate if the documentation around this were easier to find. Thanks for your time.
