### ISSUE TITLE
org.gradle.daemon=false not working

### ISSUE THREAD

**Issue by jzdayz** [gradle/gradle#12333]
### Expected Behavior

Don't using the daemon

### Current Behavior

Start with daemon

### Context

Daemons shouldn't run, right?

### Steps to Reproduce 

1. open the project
2. run gradle --no-parallel publish

console info :
```txt
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
```
jps -l
```txt
38704 org.gradle.launcher.daemon.bootstrap.GradleDaemon
30864 org.gradle.launcher.daemon.bootstrap.GradleDaemon
71729 
73424 sun.tools.jps.Jps
39464 org.gradle.launcher.daemon.bootstrap.GradleDaemon
71822 org.jetbrains.idea.maven.server.RemoteMavenServer36
```
### Your Environment

gradle 6.1.1
macos 10.15.3

#### gradle.properties
```properties
org.gradle.caching=true
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.workers.max=4
```

**Comment by blindpirate** [comment]
Thanks for reporting, if you have `--no-daemon` specified, Gradle will:

- Check if current JVM (Gradle client process) is compatible with daemon settings (e.g. `-Xmx`, but there're more possibilities). If yes, use the current JVM.
- If no, start a disposable daemon for build. 

So in your case, it's clearly your daemon settings is not compatible so a new JVM was forked.

> To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing

It's all expected behavior. You need to check `jps` before and after the build.

**Comment by jzdayz** [comment]
> Thanks for reporting, if you have `--no-daemon` specified, Gradle will:
> 
> * Check if current JVM (Gradle client process) is compatible with daemon settings (e.g. `-Xmx`, but there're more possibilities). If yes, use the current JVM.
> * If no, start a disposable daemon for build.
> 
> So in your case, it's clearly your daemon settings is not compatible so a new JVM was forked.
> 
> > To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.1.1/userguide/gradle_daemon.html.
> > Daemon will be stopped at the end of the build stopping after processing
> 
> It's all expected behavior. You need to check `jps` before and after the build.

ok, i got it
