### ISSUE TITLE
tasks --all does not list root tasks

### ISSUE THREAD

**Issue by mwos-sl** [gradle/gradle#12343]
`./gradlew tasks --all` does not include tasks accessable by root and llisted by `./gradlew tasks` (without flag `--all`), e.g.: `build` without any subproject.

### Expected Behavior
`tasks --all` should include ALL tasks, including those accessible for root project.

### Current Behavior
```
(base) mwos@mwos-mac$ ./gradlew tasks --all | grep "^build"
buildEnvironment - Displays all buildscript dependencies declared in root project 'YesReader'.
(base) mwos@mwos-mac:$ ./gradlew tasks | grep "^build"

build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
buildEnvironment - Displays all buildscript dependencies declared in root project 'YesReader'.
```

### Your Environment
tested on 2 different project:
1) Normal project, gradle 5.4.6
2) Android project, gradle 5.4.1

**Comment by big-guy** [comment]
This is a quirk with the way tasks are selectable from the command-line and how we try to show that in `gradle tasks`. You can run tasks that are in subprojects only by name. There is no `build` task in the root project, so the `build` task that shows up with `gradle tasks` is the roll-up from the subprojects.  That's why the task doesn't show up with `--all`.

Would you be interested in submitting a PR? I think it would make sense to be consistent here so that `gradle tasks` behaves the way it does now and `gradle tasks --all` would show all tasks (like it does now) and the roll-up tasks (like `gradle tasks`). 

I think the changes would be around `org.gradle.api.tasks.diagnostics.TaskReportTask` and `org.gradle.api.tasks.diagnostics.internal.AggregateMultiProjectTaskReportModel` and whatever tests break.

**Comment by mwos-sl** [comment]
Yeah, this is exactly around this places. But actually I created a completaly new task for generating cache for gradle-completion. `tasks --all` are not suitable for us. I described it here: https://github.com/gradle/gradle-completion/issues/88
I can share the code if anyone would like to.

**Comment by mlopatkin** [comment]
This is an indication of a greater problem with CLI inconsistencies. We'll address this issue in a dedicated effort in the future.
