### ISSUE TITLE
More insights into task exclusion

### ISSUE THREAD

**Issue by chali** [gradle/gradle#12357]
I have a project and invoked a built with the following parameters.

`./gradlew build -x integtest --info`

### Expected Behavior
The build has `integrationTest` task and I wanted to exclude it.

### Current Behavior
The build excluded:
- `compileIntegTestJava`
- `processIntegTestResources`
- `integTestClasses`

The result was somehow surprising and confusing.

My question is: Is it expected and if it is can we get better output to represent excluded tasks?

### Context
Changing command to `./gradlew build -x integTest --info` excludes the task for test execution as I originally intended.

Here is the sample repository https://github.com/chali/task-exclude-example

**Comment by big-guy** [comment]
Exclusions follow the same task matching rules as you'd see if you ran `gradle integtest`.  There isn't a task exactly named `integtest`, so we go through some fuzzy matching rules.  I'm not super fond of the rules, but they're usually pretty good when you're selecting tasks to execute:

1. We look for a task that matches exactly, ignoring case.
1. We look for a task that matches based on camel-notation.
1. We look for a task that matches based on a case-insensitive camel-notation prefix.
1. Finally, we look for a task that is "close" based on case-insensitive Levenshtein distance.

The task `integTestClasses` has the prefix `integtest`, and so it gets selected by fuzzy matching  based on 3 above.

With `integTest` (capital T), Gradle selects`integrationTest` because the case-sensitive camel notation (2) wins.

You can see the list of tasks that would be executed by running with `--dry-run` (`-m`).   

For the most part, I try to avoid using `-x` if it's something I want to do often and just add another task that does what I want instead.  e.g., instead of excluding integrationTest, maybe you just want a `gradle quickTest` or just run `gradle test` (if you only care about tests).  The other task can have a description that explains what it does and be discovered via `gradle tasks`.  

Ergonomic weirdness like this may mean we should disallow fuzzy matching for excludes so these sorts of problems are more obvious.

**Comment by chali** [comment]
Hey @big-guy thank you for the clarification. I hoped that even the tool itself could be more clear about what is being excluded. The experience here is that the user wanted to exclude a subset of integration tests and made a typo. He was now flooded with compilation errors since there were other source sets depending on excluded compilation output. Would it be possible to output tasks which were excluded as part of `--info` output?

**Comment by big-guy** [comment]
Yes, we can, but I think `--dry-run` or `-m` would probably be easier to check in a lot of cases if you're unsure which tasks were executed.
