### ISSUE TITLE
Problem building Scala 2.13.1 with Gradle 6.2 (worked with 5.6.2)

### ISSUE THREAD

**Issue by barrybecker4** [gradle/gradle#12392]
See also my corresponding [stack overflow](https://stackoverflow.com/questions/60363749/problem-building-scala-2-13-1-with-gradle-6-2-worked-with-5-6-2) post that I posted last week.

### Expected Behavior
It should build as it did with the earlier 5.6.2 version.

### Current Behavior
```
> Could not resolve all dependencies for configuration ':zinc'.
   > Conflict(s) found for the following module(s):
       - org.scala-lang:scala-library between versions 2.12.8, 2.12.2, 2.12.1 and 2.12.0
       - com.google.protobuf:protobuf-java between versions 3.7.0 and 3.3.1
       - org.scala-lang.modules:scala-xml_2.12 between versions 1.0.6 and 1.0.5
```

### Context
I want to use the new 6.2 version of Gradle because it contains the Scadoc fix.

### Steps to Reproduce 
Checkout my branch https://github.com/bb4/bb4-common/tree/gradle-6.2-upgrade
and try to build using ./gradlew

### Your Environment
Build scan URLs:
[Original working build scan using gradle 5.6.2](https://scans.gradle.com/s/3tiuw3op4y42i)
[Failing build scan using gradle 6.2](https://scans.gradle.com/s/kwyho5ogmeays)

**Comment by big-guy** [comment]
Gradle resolves the 'zinc' configuration to get the classpath needed to run the Zinc incremental compiler (this also happens in 5.6.2). Your build has `failOnVersionConflict` enabled which causes strict version checking and will fail the build if there are any conflicts where multiple dependencies disagree on a particular version of another dependency:
https://github.com/bb4/bb4-common/blob/gradle-6.2-upgrade/bb4.gradle#L104

Before 6.x, Gradle used a different, unmaintained version of the Zinc compiler (`com.typesafe.zinc:zinc`).  This compiler had [fewer dependencies and no conflicts](https://scans.gradle.com/s/3tiuw3op4y42i/dependencies?focusedDependency=WzAsOCw4LFswLDgsWzhdXV0&focusedDependencyView=dependencies_or_failure&toggled=W1swXSxbMCw4XV0).

In 6.0, Gradle switched to the sbt Zinc compiler (`org.scala-sbt:zinc`).  This compiler has [dependencies on more things](https://scans.gradle.com/s/kwyho5ogmeays/dependencies?focusedDependency=WzAsMywxMixbMCwzLFsxMl1dXQ&focusedDependencyView=dependencies_or_failure&toggled=W1swXSxbMCwzXSxbMCwzLFsxMl1dXQ). It looks like there are conflicts with [scala-library](https://scans.gradle.com/s/kwyho5ogmeays/dependencies?configurationFilter=WyJ6aW5jIl0&dependencies=scala-library&expandAll&focusedDependencyView=dependencies_or_failure), [scala-xml](https://scans.gradle.com/s/kwyho5ogmeays/dependencies?configurationFilter=WyJ6aW5jIl0&dependencies=scala-xml&expandAll&focusedDependencyView=dependencies_or_failure) and [protobuf](https://scans.gradle.com/s/kwyho5ogmeays/dependencies?configurationFilter=WyJ6aW5jIl0&dependencies=protobuf-java&expandAll&focusedDependencyView=dependencies_or_failure). This is coming from the Zinc compiler dependencies as they're published.  [scala-xml](https://scans.gradle.com/s/kwyho5ogmeays/dependencies?configurationFilter=WyJ6aW5jIl0&dependencies=scala-xml&expandAll&focusedDependency=WzAsMyw1NyxbMCwwLFswXV1d&focusedDependencyView=versions) is probably the easiest one to see where the different versions come from. scala-compiler wants version 1.06 and sbinary wants version 1.0.5.

The reason you see Gradle trying to find Scala 2.12 is that the Zinc compiler that Gradle uses requires Scala 2.12 to run, but this is separate from the version of Scala your project needs to build with. 

I think your options are:
1. Disable `failOnVersionConflict` for the zinc configuration and just accept whatever versions will be selected for that.
2. Keep `failOnVersionConflict`, but resolve the conflicts for the zinc configuration. 

I would lean towards 1 since the version of Zinc's dependencies aren't as interesting as your own. 

HTH @barrybecker4

**Comment by barrybecker4** [comment]
Thanks for the detailed response. Yes, removing `failOnVersionConflict` worked and I can build with Scala 2.13.1 now. Thanks!
