### ISSUE TITLE
Java incremental build works incorrectly

### ISSUE THREAD

**Issue by abeyn** [gradle/gradle#12426]
There is a problem with incremental compilation:

**build.gradle:**
tasks.compileJava {
    options.incremental = true
}

**ClassA.java:**
public final class ClassA {
  public static final int field=45;
}

**ClassB.java:**
public final class ClassB {
  public int field = 0;
  public ClassB()
  {
     field = ClassA.field;
  }
}

Steps:

1. Run gradlew.bat :app:compileJava;
2. Edit 'ClassA.field' value in ClassA.java   
   public static final int field=100;
3. Run gradlew.bat :app:compileJava;
4. Decompile file: app\build\classes\java\main\com\test\ClassB.class;
5. Constructor of ClassB has incorrect value 'ClassA.field'
  public ClassB() {
    this.field = 45;	//expected value: 100
  }

Project to reproduce issue at [javaCompile.zip](https://github.com/gradle/gradle/files/4288380/javaCompile.zip)

com.android.tools.build:gradle:3.6.0
gradle:5.6.4

**Comment by ljacomet** [comment]
Your reproducer is using a wrong setup, which is most likely what breaks incremental compilation.

Because of the following in `app/build.gradle`:

```
sourceSets {
    main {
        java {
            srcDirs = ["src/main/java/com"]
        }
    }
}
```
the source files are not in the right location, compared to their declared package name.

And this indeed breaks incremental compilation.

Use a standard project layout and the problem will disappear. That is delete the whole block copied above.

**Comment by abeyn** [comment]
Thank you very much, it works with:
srcDirs = ["src/main/java"]

**Comment by ljacomet** [comment]
As an FYI, this is listed as a [known limitation](https://docs.gradle.org/6.2.2/userguide/java_plugin.html#sec:incremental_compilation_known_issues).
