### ISSUE TITLE
gradle and gradlew are failing to work properly on solaris 10.

### ISSUE THREAD

**Issue by jt214** [gradle/gradle#1248]
This is a regression.   This is the same as previous issue 'GRADLE-63'.

The problem was fixed, but is now occurring again in gradle-3.2 and above.

On solaris, the 'sh' shell is not 'bash'.   The 'gradle' and 'gradlew' scripts are using bash specific code, but specifying to use the 'sh' shell.

On solaris 10, this is what happens:

**% ./gradle 
./gradle: syntax error at line 173: `i=$' unexpected
zsh: exit 2 ./gradle**

**Comment by wolfs** [comment]
@jt214 Do you have the same problem with Gradle 3.2.1? The `gradle` and `gradlew` scripts should now work with `sh`. Note that in order to generate the right `gradlew` script you need to either run the `wrapper` command with Gradle 3.2.1 or run the `wrapper` command twice with your current `gradlew`.
Did you try Gradle 3.3 or 3.4-rc-1, too? I think there shouldn't be any changes in behavior.

**Comment by jt214** [comment]
Yes, the behavior is the same in all versions above 3.2.   

The gradle scripts were all changed to use the shell command:

#!/usr/bin/env sh

Before this, the shell command was:

#!/usr/bin/env bash

The scripts contain the line of code:

        i=$((i+1))

around line #141.

This code is bash code, and it fails in the sh shell.

**Comment by kasperfrederiksen** [comment]
We are experiencing the same problem on gradle version version 3.4. If i change the first line back to:

    #!/usr/bin/env bash

it works.

**Comment by bmuschko** [comment]
@wolfs @jjohannes Can you guys have a look at the issue? You are probably the most familiar with the changes we made in this area.

**Comment by jjohannes** [comment]
@jt214 What exactly is not `sh` compatible in this line `i=$((i+1))`? Do you know what would be the `sh` equivalent?

We are testing with `dash` and there the script parses and executes. Also, on unix systems `i=$((i+1))` should never be reached, since it is in the `cygwin` specific script block. Which exact shell/shell version is causing the error for you (i.e. which shell is `sh` on solaris 10)?

**Comment by rajesheq** [comment]
I get the same error and I am using Solaris as well.

**Comment by jjohannes** [comment]
I think this needs clarification.

The switch to `#!/usr/bin/env sh` means that gradle now uses whatever shell the underlying UNIX system links as default and `gradlew` is supposed to conform so `sh` standards so that any shell could interpret it.

From the original error it looks as if some version of `zsh` is used here.

I tested with `zsh` on Solaris 11 (because I had a VM at hand). Which had `zsh 5.0.7 (i386-pc-solaris2.11)` installed (although `sh` was linked to `ksh` which worked smoothly).

With `zsh` I found indeed a problem. Looks as if it is interpreting the _space_ between paranthesis in a function definition like `warn ( ) {`. Changing in to `warn () {` solves the problem.

Here is a fixed `gradlew`: https://gist.github.com/jjohannes/5f99ef34e42d18a3ccf93a94efd1bce7

@jt214 @rajesheq could you verify if the fix works for you?

If not, could you post the shell and shell version you are using (e.g. do `ls -l /usr/bin/sh` to check where it is linked to and `sh --version` for version details). Thanks!

**Comment by rajesheq** [comment]
Still getting the same error. /usr/bin/sh is linked to /sbin/sh

**Comment by jjohannes** [comment]
I have checked this on Solaris 10 and I get the same error. It seems like the Solaris 10 default `sh` is not POSIX compatible (see for example this discussion https://github.com/github/backup-utils/issues/85#issuecomment-66808497).

We can not provide support for that shell.

The comment referenced above also suggests to use `/usr/xpg4/bin/sh` which is able to execute `gradle` as it is now. You should use that or `bash` (as you probably did before) to execute the script. Since the script now declares `#!/usr/bin/env sh` you can schive this by making sure you have one of these shells on the `PATH` as the first `sh` command.

I would still suggest to merge #1768 as it fixes the gradle script for `ksh`. @bmuschko what do you think?

**Comment by jjohannes** [comment]
Since the fix described above is for Solaris 11 only, I created a new issue to track it: #1804

**Comment by vladmir-lima** [comment]
Hi guys,
I have the same issue in FreeBSD, I am working with Gradle 3.3 

--stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /usr/local/jenkins/workspace/fis-mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
/dados/android-sdk-linux/build-tools/27.0.1/aapt: 1: Syntax error: "(" unexpected

**Comment by enkai** [comment]
You can use i++; as a replacement for  i=$((i+1)) on Solaris 10
