### ISSUE TITLE
War#webInf CopySpec does not inherit parent's reproducible archive settings

### ISSUE THREAD

**Issue by DPUkyle** [gradle/gradle#12492]
### Expected Behavior

_original example edited for clarify and simplicity_

This is related to #12440 

When I apply the following configuration:
```
    project.tasks.withType(AbstractArchiveTask).all(archive -> {
      archive.preserveFileTimestamps = false
      archive.reproducibleFileOrder = true
      archive.dirMode = 0755
      archive.fileMode = 0644
```
Then the jars in the `WEB-INF/lib/` of the generated war file should have 644 permissions. 

### Current Behavior

On a system with an unusual  umask value like 0002, the above setting is insufficient.

I can workaround using the following configuration, but is this really necessary or expected?

```
    project.tasks.withType(AbstractArchiveTask).all(archive -> {
      archive.preserveFileTimestamps = false
      archive.reproducibleFileOrder = true
      archive.dirMode = 0755
      archive.fileMode = 0644
      if (archive in War) {
        archive.rootSpec().dirMode = 0755
        archive.rootSpec().fileMode = 0644
      }
```
### Context

The relation of parent/child CopySpecs has never been very clear to me; Is this expected behavior, or should the child webInf spec have inherited from the initial configuration?

After looking more closely at the War task's source code, the `getWebInf()` method always returns a new spec, detached from the main (as @wolfs mentions). Since these "orphaned" child specs (my term) are inaccessible via any public API, I have no choice to to grab the rootSpec of the War.

**Comment by wolfs** [comment]
It seems that there is a `rootSpec` and a child of the `rootSpec` - the `mainSpec` - for all copy like tasks. All the `CopySpec` methods called on the task itself affect only the `mainSpec`. Now `webInf` is a child spec of the `rootSpec` and a sibling of the `mainSpec`. Therefore, your `eachFile` doesn't affect the `webInf` spec.

I don't know if the above is intentional. I wonder what is more surprising - doing a rename on the `War` task which also affects the `webInf` directory, or only applying the rename to the files which are in the rest of the war file.

**Comment by wolfs** [comment]
@DPUkyle I'll close this issue now, since it doesn't look like we will address the issue soon or ever. There is a workaround, though it is not nice. If you think this issue is important to address, please re-open it.
