### ISSUE TITLE
Dependency substitution not resolving project artifact

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#12506]
External dependency is not replaced by project dependency in some cases. More specifically, for `app -> lib2 -> lib`, where `androidTest` variant of `app` also has dependency on `com.repro:lib:1.0`, external dependency will be used. However, if `lib` is added explicitly to `app`, when building `androidTest` variant, local project is chosen. Note that the local project has version higher than the external dependency.

Running `./gradlew :app:assembleDebugAndroidTest` fails for the attached project. If `app/build.gradle` is updated to contain `implementation project(":lib")`, task will succeed.

[dependencySub.zip](https://github.com/gradle/gradle/files/4320824/dependencySub.zip)

Please note that issue is not reproducible with AGP 4.0. However, in AGP 4.1 runtime classpath of androidTest does not extend the tested runtime classpath. In addition to that, we sync compile and runtime classpath for variants. I am not sure if this could be a root cause, but if so, I would not expect explicit addition of `implementation project(":lib")` to fix the issue.

Let me know if you need additional info on how configurations are set up in AGP.

**Comment by ljacomet** [comment]
So the issue is most likely coming from the fact that `debugAndroidTestRuntimeClasspath` has no reference to `project(":lib")` and thus when you create strict constraints from its resolution and inject them in `debugAndroidTestCompileClasspath`, the strictly results in the engine selecting `com.repro:lib:1.0` as it is what is strictly selected.

Does that make sense?

Now to understand better the relationships between configurations, I am interested in knowing the full `extends` hierarchy of both configurations named above.

**Comment by gavra0** [comment]
In AGP 4.1 configurations are the following:
- `debugAndroidTestCompileClasspath` extends from all androidTest specific configurations (`androidTest - api/implementation/compile/compileOnly`), and it also extends all tested compile configurations (`api/implementation/compile/compileOnly`). While it would make sense to have androidTest compile classpath contain only packaged dependencies from the tested variant, because of backwards compatibility we are doing what is described above.
- `debugAndroidTestRuntimeClasspath` extends from all androidTest specific configurations (`androidTest - api/implementation/compile/runtimeOnly`). In AGP 4.0, it also extends from tested runtime configurations. I believe this is why everything works in 4.0. In 4.1 we decided to clean this up as e.g. if `guava` is packaged in the tested APK, it should not be packaged in the test one. We want the runtime classpath to reflect the packaged classpath more, and that's why we changed how we model test-tested dependency.

**Comment by ljacomet** [comment]
Thanks for the explanation. It confirms what I stated.
Because Android wants to enforce the `compile` / `runtime` consistent resolution, the solution is indeed to add the missing dependency to the runtime classpath so that the compile classpath can be properly constrained.

Otherwise the resolution you would like to happen for `debugAndroidTestCompileClasspath` will be disconnected from what will be available at runtime.

**Comment by gavra0** [comment]
I am not sure if that is the cause. In the sample project adding `implementation project(":lib")` to `app/build.gradle` actually fixes the issue. This dependency is added only to compile classpath for androidTest, not the runtime classpath. It seems that if this dependency is "a direct dependency", it wins when constrains are enforced. However, if only `lib2` is added as a dependency, that is not the case.

**Comment by ljacomet** [comment]
You are right, there is indeed an issue. The problem is that Gradle never checks that a project selector is not rejected, which should be the case here given the `com.repro:lib:{strictly 1.0}` that is injected.
This constraint should prevent the selection of anything but that version for `com.repro:lib` and if I change the version of `project(':lib')` to be `1.0`, you can see that the project is selected indeed.

Fixing Gradle however would result in the build failing, as you have effectively incompatible dependency declarations.

**Comment by ljacomet** [comment]
Gradle is considering to fix the project not checking rejected versions in 7.0 but not before given the potential impact on existing builds.
