### ISSUE TITLE
Lazy Types in JVM Plugin Extensions and Tasks

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#12546]
The _extensions_ (`JavaPluginExtension`, `ApplicationPlugin`, ...) and _tasks_ (`JavaCompile`, `JavaExec`, ...) for Java/JVM development exist since the early days of Gradle and are in parts still based on "old" concepts. Since the new lazy types in Gradle are now ready to fully replace the old "convention" concept, we can now fully migrate the extensions and tasks to these new concepts. 

This will not only lead to a better and more consistent API, but also will simplify the implementation, where currently _extensions_ and _conventions_ exist side-by-side.

Since this changes public API, all changes need to go through a deprecation/incubation cycle:

- In a minor release: Introduce new API and build on new lazy types instead of _conventions_
  - Introduce new _properties_ to replace the existing getters/setters in tasks and extensions.
  - Make the existing getters/setters delegate to the new properties.
  - Replace lazy configuration based on a _convention_ (currently backing the corresponding _extension_) with lazy configuration based on the properties. Keep backward compatibility by making each existing convention field a `convention()` for the corresponding property (e.g.: `mainClass = objectFactory.property(String.class).convention(providerFactory.provider(convention::getMainClassName))`). Conventions then no longer back the extensions directly and can simply be removed in the next major release.
- In one of the minor releases after:
  - Deprecate the getters/setters and de-incubate the new properties.
- In the next major release:
  - Remove the conventions completely and perform other breaking changes (e.g. changes to inheritance hierarchy).

**Comment by adammurdoch** [comment]
I think it would be good to split this up into several stages. For example, I would perhaps start with just the input and output file properties that are used to wire tasks together in the core JVM plugins. We've already mostly done this but there are a few things to clean up there:

- Add a property to `processResources` (`Copy`) represent the output directory.
- Remove the `dependsOn` calls that explicitly wire in compile and process resource outputs and wire this via the source set outputs.
- Replace the convention mapping with a `convention()` for the output locations of the JVM tasks.
- Deprecate `SourceSetOutput.dir(builtBy: x)` so as to encourage people to wire in other source set content using `Provider<Directory>`.

This will make the JVM plugins more reliable when people rewire these input/output relationships or attempt to change the locations at odd times.

Then, some other potential chunks of improvement could be:

- Add lazy typed properties for the Java compile properties that you need to use to cross compile, such as `options.fork` or `options.javaHome`. This will help build logic (including the JVM plugins in the future) set up cross compilation in a lazy way, and do so in a way that does not invalidate the instant execution cache (for example by eagerly reading a system property at configuration time).
- Add lazy typed properties for convention locations, such as the reporting base dir or test results dir. This makes the things that use these conventions more reliable as people reconfigure locations.
- Add lazy typed properties so that all convention mappings in the JVM plugins can be replaced with `convention()`. This allows us to deprecate and remove convention mappings.
- Replace the "convention" objects that are attached to source sets to add support for a non-Java language (Groovy, Scala, Kotlin, Antlr, Protobuf, etc) with extensions or a domain object container of languages. This makes the new languages visible to statically typed languages and tooling that makes use of this (Kotlin DSL, IDEA, etc) and allows us to deprecate and remove "convention" objects.
- Whatever's left, but I could continue to do this in a use case focused way like the above.

**Comment by keturn** [comment]
I expect this would help clarify source set dependencies and make it easier to do things like #2137.

**Comment by grossws** [comment]
Still relevant imho

**Comment by big-guy** [comment]
This falls under the overarching goals of the Provider API migration: https://github.com/gradle/build-tool-roadmap/issues/28

Closing this particular issue for that.
