### ISSUE TITLE
Build buildSrc tips wrong

### ISSUE THREAD

**Issue by YiHan-HuaHua** [gradle/gradle#12702]
The compile configuration has been deprecated for dependency declaration. This will fail with an error in Gradle 7.0. Please use the implementation configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
	at ijinit1_a87h1lyfqlfzvum13tk6fpulp$_run_closure1$_closure2.doCall(/private/var/folders/6x/7c5rlr993694t0lwg45np_5h0000gn/T/ijinit1.gradle:76)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
The compileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
The compile configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the compileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations
The testCompileOnly configuration has been deprecated for resolution. This will fail with an error in Gradle 7.0. Please resolve the testCompileClasspath configuration instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#dependencies_should_no_longer_be_declared_using_the_compile_and_runtime_configurations

**Comment by YiHan-HuaHua** [comment]
![1585829601537](https://user-images.githubusercontent.com/27755602/78248037-7a53c380-751e-11ea-951f-38217f3c02bf.jpg)

**Comment by ljacomet** [comment]
What is the issue? What do you expect?

You should update your build script to have this warning disappear.

**Comment by YiHan-HuaHua** [comment]
My project only includes the buildSrc build. I removed buildSrc from my project and the build was normal. Check that the ijinit plugin uses compile, so this error is prompted.

**Comment by YiHan-HuaHua** [comment]
Idea installed gradle plugin error

**Comment by YiHan-HuaHua** [comment]
![1585833596420](https://user-images.githubusercontent.com/27755602/78253930-bdfefb00-7527-11ea-942e-dc0e796ed162.jpg)
![1585833445834](https://user-images.githubusercontent.com/27755602/78253945-c35c4580-7527-11ea-9e36-5ae23f9428f3.jpg)

**Comment by YiHan-HuaHua** [comment]
No builds have been added to my build script

**Comment by ljacomet** [comment]
Looks like you need to upgrade your IntelliJ version then. Nothing Gradle can do about that.

**Comment by YiHan-HuaHua** [comment]
My Idea version is already up to date (2019.3.4)

**Comment by ljacomet** [comment]
Any chance you can share a reproducer?

**Comment by YiHan-HuaHua** [comment]
Of course, I think I can try to see if it can be reproduced on other devices. If it can be reproduced, I think I can provide you with the source code.

**Comment by blindpirate** [comment]
@ljacomet when IDEA imports Gradle project, it silently applies an init script internally, I think that might be the issue.

@YiHan-HuaHua If you can provide the reproducible sample that would be great.

**Comment by rpalcolea** [comment]
This is definitely IntelliJ issue

The `ijinit` script is generated here: https://github.com/JetBrains/intellij-community/blob/master/plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelper.java#L505

This also makes use of a `buildSrc` -> https://github.com/JetBrains/intellij-community/blob/master/plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelper.java#L515 so this: https://github.com/JetBrains/intellij-community/blob/master/plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelper.java#L553

If you look at the latest of that file on master, it handles the old versions of gradle correctly: https://github.com/JetBrains/intellij-community/blob/master/plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/internal/init/buildSrcInit.gradle

However, this change was introduced back in January https://github.com/JetBrains/intellij-community/commit/e24627711f753cea8cd56a03bdbb9d0385215d3e#diff-72be1e088f2b900f4601111e4bd0c203

I'm not familiar with Jetbrains release process but I would expect this change to be part of 2020.1 instead of a bug fix in 2019.3.x

**Comment by YiHan-HuaHua** [comment]
Thanks @rpalcolea @ljacomet @blindpirate for the answer. At present, I can only wait for IntelliJ to release a new version to solve this problem. Thanks.

**Comment by YiHan-HuaHua** [comment]
Also provides my reproduction (IntelliJ 2019)
[Services.zip](https://github.com/gradle/gradle/files/4425371/Services.zip)
