### ISSUE TITLE
Ignore `MODIFIED` events for directories on Windows

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#12756]
If a file or directory is created in a directory, then on Windows the file watcher will report a `CREATED` event for the new file/directory and a `MODIFIED` event for the existing directory.

That causes too many things to be invalidated on Windows, since creating or removing a new directory in the `build` dir will cause all the outputs to be removed from the VFS. The best thing would probably be to ignore `MODIFIED` events for directories, either on the native-platform side or the Gradle side. I wonder if we could somehow obtain the information that the changed location is a directory when we receive the change event.

---
cc: @gradle/build-cache

**Comment by wolfs** [comment]
I tried out if I still get MODIFIED events for directories. I pulled latest master on `windows35`, installed the `test-app` and then ran

```
\build\install\native-platform-test\bin\native-platform-test.bat --watch watched
```

Then I opened a different ssh connection to `windows35`, started `bash`, and then started to create files in the watched/hello directory:

```
echo some > test5.txt
When doing so, I see this log from the test app:
Change detected: CREATED / 'C:\Users\vmadmin\wolf\native-platform\test-app\watched\hello\test5.txt'
Change detected: MODIFIED / 'C:\Users\vmadmin\wolf\native-platform\test-app\watched\hello\test5.txt'
Change detected: MODIFIED / 'C:\Users\vmadmin\wolf\native-platform\test-app\watched\hello'
```

It seems like the `MODIFIED` events for the directory arrive
- some times when using `cmd`,
- always when using cywgin bash,
- and never when using powershell

**Comment by wolfs** [comment]
We should ignore `MODIFIED` events for directories on the Gradle side, since this is where we know whether something is a directory or not. For the Windows file watching, the events don't tell us about the file type.

Moreover, we should try to reproduce the `MODIFIED` events for directories in a native platform test. It seems like the events come in when we create a subdirectory of the project directory when running a Gradle build.

**Comment by lptr** [comment]
Actually, when using `cmd` I could reproduce the event when exiting `cmd` itself. The same could be true for PowerShell.

**Comment by lptr** [comment]
There's a new Windows API: `ReadDirectoryChangesExW`. This gives more details about each event, including the attributes of the entry in question:

```cpp
typedef struct _FILE_NOTIFY_EXTENDED_INFORMATION {
  DWORD         NextEntryOffset;
  DWORD         Action;
  LARGE_INTEGER CreationTime;
  LARGE_INTEGER LastModificationTime;
  LARGE_INTEGER LastChangeTime;
  LARGE_INTEGER LastAccessTime;
  LARGE_INTEGER AllocatedLength;
  LARGE_INTEGER FileSize;
  DWORD         FileAttributes;
  DWORD         ReparsePointTag;
  LARGE_INTEGER FileId;
  LARGE_INTEGER ParentFileId;
  DWORD         FileNameLength;
  WCHAR         FileName[1];
} FILE_NOTIFY_EXTENDED_INFORMATION, *PFILE_NOTIFY_EXTENDED_INFORMATION;
```

https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readdirectorychangesexw

The `FileAttributes` filed can be checked against `FILE_ATTRIBUTE_DIRECTORY` to tell if this thing in question is a directory.

The API is supported since Windows 10, version 1709 ([September 26, 2017](https://en.wikipedia.org/wiki/Windows_10_version_1709)), so it's likely to be available to most of our Windows users.

I guess if we switched to this API, older Windows version would simply refuse to load our DLL because of the missing symbol, and thus file system watching would be disabled.

If we wanted to keep the current implementation using the universally available `ReadDirectoryChangesW` API, then we'd have to have two variants of the DLL probably. Not sure how we'd be loading that.

Using the new API it might not even be necessary to filter `MODIFIED` events, assuming the underlying issue has been addressed.

**Comment by lptr** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/Windows_10_version_history) there are only two LTSC versions of Windows 10 still supported out there by Microsoft that don't include this API, while the most recent LTSC version does include it:

![image](https://user-images.githubusercontent.com/495366/121192766-8c8d6800-c86d-11eb-9748-4c17d11c0213.png)

I think it sounds reasonable to drop FSW support for the previous LTSC versions.
