### ISSUE TITLE
Multi-Module Gradle Project - Main class name has not been configured and it could not be resolved

### ISSUE THREAD

**Issue by hanct** [gradle/gradle#12789]
Gradle 6.3

Hi,

I setup a multi-module gradle project. At the parent level, i have a build.gradle, which looks like this

```
plugins {
	id 'org.springframework.boot' version '2.2.6.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}


repositories {
	mavenCentral()
}

allprojects{
	group = 'com.Marvel'
	version = '0.0.1-SNAPSHOT'
}
subprojects{
	apply plugin: "java"
	apply plugin: "org.springframework.boot"
	apply plugin: "io.spring.dependency-management"
	repositories {
        	mavenCentral()
    	}
	
	sourceCompatibility = '1.8'
	

	dependencies {
		implementation 'org.springframework.boot:spring-boot-starter-actuator'
		implementation 'org.springframework.boot:spring-boot-starter-webflux'
		testImplementation('org.springframework.boot:spring-boot-starter-test') {
			exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
		}
		testImplementation 'io.projectreactor:reactor-test'
	}
	
	
}
bootJar { enabled = false}	

```

In my settings.gradle, i have this
```
include ':microservices:product-service'
```

I did have  the following subfolders - microservices/product-service.

When i do **gradlew.bat :microservices:product-service:build**, the build is successful. This shows the subproject folder and its content is setup properly.

When i do **gradlew.bat build**, the build is not successful. I got the below error

```
* What went wrong:
Execution failed for task ':microservices:bootJar'.
> Main class name has not been configured and it could not be resolved
```

My query is  
- When I perform the latter build, doesn't gradle suppose to automatically build all my subprojects (specified in the settings.gradle)?

**Comment by rpalcolea** [comment]
I don’t think this is a gradle but

You are applying the spring boot plugin at root level by doing 

```
plugins {
	id 'org.springframework.boot' version '2.2.6.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}
```

Since you are doing this, the spring boot project expects that your root project is a sb app requiring a `mainClassName` For the `bootJar` task.

You should only apply the spring boot project to the projects that are SB apps 

The fact that you disable `bootJar` in the root project is a smell that shouldn’t be applied there

**Comment by hanct** [comment]
Hi,
Thanks for the reply. I believe that the build.gradle should be correct.
Because i do another experiement,

1) Instead of putting the products-service folder as a subfolder of microservices folder, i copy it out, and put it at the parent folder.  
2) Then i modify the settings.gradle to 
```
include ':product-service'
```

Then i run the same build command again, the build is successful.
This make me wonder if gradle is not able to support multiple level of folders for the child gradle projects?

**Comment by ljacomet** [comment]
`include ':microservices:product-service'` will result in _two_ projects being included: `microservices` and `product-service`, where the later is a child of the former.

You have two options for resolving your build issue:
* If you do not need the hierarchy in project names, but want it on disk, you can tell Gradle that the project `product-service` lives in `microservices/product-service` with something like:
```
include 'product-service'
project(':product-service').projectDir = file('microservices/product-service')
```
* If you want the hierarchy in project names as well as on disk, then you need to be conditional in the `subprojects` block to not configure intermediate marker projects with all plugins.

Note that I would recommend going with the first point since that will show you faster if you start having colliding project names, which is another type of issue you could encounter with your initial structure.

**Comment by hanct** [comment]
> `include ':microservices:product-service'` will result in _two_ projects being included: `microservices` and `product-service`, where the later is a child of the former.
> 
> You have two options for resolving your build issue:
> 
> * If you do not need the hierarchy in project names, but want it on disk, you can tell Gradle that the project `product-service` lives in `microservices/product-service` with something like:
> 
> ```
> include 'product-service'
> project(':product-service').projectDir = file('microservices/product-service')
> ```
> 
> * If you want the hierarchy in project names as well as on disk, then you need to be conditional in the `subprojects` block to not configure intermediate marker projects with all plugins.
> 
> Note that I would recommend going with the first point since that will show you faster if you start having colliding project names, which is another type of issue you could encounter with your initial structure.

Thank you so much. It works!! 
But really there a few things need to highlight to gradle support team:
1) **include 'project-service'**seem optional to prefix colon in front of the project-service wording
    But project(':product-service') needs the colon, otherwise build will fail.  Does not seem to be 
    consistent here.

2) to allow shorthand such as **include 'microservices/product-service'**  to achieve the same thing as the verbose statement of setting the projectDir

**Comment by wanlinus** [comment]
in rootProject build.gradle add 

> bootJar {
>     enabled = false
> }

**Comment by hanct** [comment]
> in rootProject build.gradle add
> 
> > bootJar {
> > enabled = false
> > }

Thanks. But as u can see from my first thread, this setting is already there.
