### ISSUE TITLE
Output cache keys not stable across platforms

### ISSUE THREAD

**Issue by dansanduleac** [gradle/gradle#12854]
```groovy
task foo {
  outputs.files(new HashSet(['foo', 'bar'])).withPropertyName("foo")
}
```

The cache keys generated for this, to the best of my knowledge, get determined in this line of code: https://github.com/gradle/gradle/blob/eed8b30076e55e981d3f1a7b1a700ada69db4ff5/subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/FileParameterUtils.java#L150

and would be:

```
foo$1
foo$2
```

However, which file maps to which of these properties depends on the iteration order, which is not guaranteed to be the same across platforms!

### Expected Behavior

Derive cache key in a stable way.

I imagine we could instead use the relative path of each file, but it feels weird that this is not already configurable (via the `@PathSensitivity` annotation).

I know you can use PathSensitivity on input files, but it's not obvious how that would translate into how output files get cached.

### Current Behavior

We've actually hit this with one of our plugins, where a cached `task.getOutputs().outputFiles(...)` generated in CircleCI was picked up from a developer's machine and successfully restored all the right directories, but each one with the files that were meant to be in a different directory.

This was with gradle 6.3.

### Your Environment

Build scan URL:

**Comment by lptr** [comment]
Relative path normalization is built-in for outputs, that's why you can't change it. The normalization means that Gradle considers the relative paths _under_ `foo` and `bar` when storing and comparing outputs.

As for `foo` and `bar` themselves, Gradle does not consider these paths at all. They could be different when we load the results, and Gradle would happily unpack stuff to those new locations. This is by design.

Basically, Gradle needs an _identity_ to attach to each output property. In your example it tries to make do with what you give it, namely the string `foo` and the iteration order. And yes, this can be a wrong way to identify those outputs.

Gradle used to disable caching for tasks with collection output properties, exactly because of this problem. We re-enabled caching for such tasks recently, because it seemed like an arbitrary limitation for many people, but as your case shows it is indeed a problem.

There are a couple of options you can use to fix this:

- Use a type with a predictable iteration order like a `List` or a `LinkedHashSet`. Note that even in this case you are responsible for keeping the outputs in the same order.
- Explain the identity of the outputs to Gradle using a `Map` instead of a collection. You can give a name to each entry, and Gradle will use those to identify them instead of the iteration index.
- Declare two separate output properties for each output using `outputs.file()` or `dir()`.
- Declare your task as a type, and use annotated output properties for each output separately.

What we can do (and were planning to do) is to deprecate the use of collections known to not retain iteration order as output properties. Again, this will only remove part of the problem, as it is entirely possible to put your outputs in a `List` or something in a non-reproducible order (e.g. by using `File.listFiles()` without ordering the results).

**Comment by dansanduleac** [comment]
Thanks for the write-up @lptr.

I think it's fine to allow people to do this, but I'd suggest maybe putting such behaviour behind an opt-in flag on `TaskOutputFilePropertyBuilder` that clearly indicates the user is responsible for always mantaining the order in that collection, because I think the default logic is extremely surprising.

Whether people use FileCollection or sets of files, I think there's a reasonable expectation that some part of the path is used as a cache key. This is similar to how people already model consuming the outputs of another task when using `@InputFiles` / `@InputDirectories`, so it's the most reasonable thing to expect.

Otherwise, people might get the mistaken assumption, like me, that they are keyed by something else than just index.

In my mind, there should only be two ways of using this API by default:
* with a map, which makes the cache keys explicit and enforces uniqueness
* (in the case of `files`/`dirs`): with a set of files, be it a FileCollection or somrthing else, where gradle would infer the cache key by relative path. This also enforces uniqueness by design

This of course is not a problem for `.dir` because the property name should uniquely identify that subtree.

**Comment by lptr** [comment]
> * (in the case of `files`/`dirs`): with a set of files, be it a FileCollection or something else, where gradle would infer the cache key by relative path. This also enforces uniqueness by design

I still don't understand what you mean by Gradle infering the cache key by relative path. Relative to what?

Take this example. We have a cacheable task with an `@OutputDirectories outputDirs` property configured originally to point to these two locations:

- `C:\Dev\MyProject\build\output-dir-1/`
- `C:\Dev\MyProject\build\output-dir-2/`

You run a build with this task, its output gets stored and uploaded to the remote cache. Now someone else runs the same task, but with `outputDirs` property configured thus:

- `/home/lptr/Workspace/my-project/build/output/`
- `/tmp/we-configure-things-differently-on-linux/because-we-can/`

Now what? How do you match the stored content to these?

Yes, using a `Map` solves it, because there you need to specify a key which we can match. But with a collection there is no way to "infer the cache key by relative path."
