### ISSUE TITLE
Runtime dependencies imported as RUNTIME and TEST

### ISSUE THREAD

**Issue by vladsoroka** [gradle/gradle#1286]
```
dependencies {
  runtime 'dep:dep:1.0'
}
```

### Expected Behavior
Generated IML should contain orderEntry related to "dep:dep:1.0" only with scope RUNTIME

### Current Behavior
Generated IML contains two orderEntries related to "dep:dep:1.0" with scope RUNTIME and TEST

### Context
Classes from "dep:dep:1.0" should not be available during tests compilation.
Also the compilation fails if you run gradle `compileTest` task

### Steps to Reproduce (for bugs)
generate IDEA project using `idea` task with some runtime dependency defined as above.

### Your Environment
Gradle 3.4-rc-1

**Comment by bmuschko** [comment]
I can confirm that the generated `iml` files differs between versions 3.3 and 3.4-rc-1.

**Example build script:**

```
apply plugin: 'java'
apply plugin: 'idea'

repositories {
    mavenCentral()
}

dependencies {
    runtime 'commons-lang:commons-lang:2.5'
}
```

**Gradle 3.3:**

```
<orderEntry type="module-library" scope="RUNTIME">
  <library>
    <CLASSES>
      <root url="jar:///Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/b0236b252e86419eef20c31a44579d2aee2f0a69/commons-lang-2.5.jar!/"/>
    </CLASSES>
    <JAVADOC/>
    <SOURCES>
      <root url="jar:///Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/bb75ef699b349b6e02d17d41556cebcd755d07ab/commons-lang-2.5-sources.jar!/"/>
    </SOURCES>
  </library>
</orderEntry>
```

**Gradle 3.4-rc-1:**

```
<orderEntry type="module-library" scope="RUNTIME">
  <library>
    <CLASSES>
      <root url="jar:///Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/b0236b252e86419eef20c31a44579d2aee2f0a69/commons-lang-2.5.jar!/"/>
    </CLASSES>
    <JAVADOC/>
    <SOURCES>
      <root url="jar:///Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/bb75ef699b349b6e02d17d41556cebcd755d07ab/commons-lang-2.5-sources.jar!/"/>
    </SOURCES>
  </library>
</orderEntry>
<orderEntry type="module-library" scope="TEST">
  <library>
    <CLASSES>
      <root url="jar:///Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/b0236b252e86419eef20c31a44579d2aee2f0a69/commons-lang-2.5.jar!/"/>
    </CLASSES>
    <JAVADOC/>
    <SOURCES>
      <root url="jar:///Users/bmuschko/.gradle/caches/modules-2/files-2.1/commons-lang/commons-lang/2.5/bb75ef699b349b6e02d17d41556cebcd755d07ab/commons-lang-2.5-sources.jar!/"/>
    </SOURCES>
  </library>
</orderEntry>
```

**Comment by oehme** [comment]
As discussed in our chat, this is expected. We no longer do any hardcoded "massaging" of the scopes, but have a simple mapping (see the release notes). The user-facing symptom is that `runtime` dependencies are now visible when auto-completing in test sources. This was already the case with `testRuntime` dependencies before.

Since we don't want to go back to the hacks we did before, there are two solutions we can explore going forward to make classpaths in IDEA more correct in general:

1. IDEA separates TEST_COMPILE and TEST_RUNTIME, just like it separates COMPILE and RUNTIME. That would allow us to do a better mapping out of the box.
2. The Gradle `idea` plugin is enhanced to support nested modules, so the user can create separate submodules for `main` and `test. IDEA already has an option for that, but the code is currently maintained by JetBrains and has to do a lot of workarounds because Gradle doesn't support this well.

I'd be happy to explore both of those options, as they would be more flexible and correct than any of the workarounds we had before.
