### ISSUE TITLE
6.4-rc-2 - Java Modules project does not support ServiceLoader

### ISSUE THREAD

**Issue by pull-vert** [gradle/gradle#12890]
My project's code is https://github.com/pull-vert/limo. In this jigsaw module project I previously used 'org.javamodularity.moduleplugin' (branch master) with gradle 6.3.

I have a ServiceLoader in limo-core, that is declared in its module-info.java :
```java
uses OffHeapFactory;
```

Module limo-core-jdk14 provide an implementation to this Service, in its module-info.java the following line does this :
```java
provides OffHeapFactory with MemorySegmentOffHeapFactory;
```
tests in this 'limo-core-jdk14' should use the MemorySegmentOffHeapFactory, this is the log from master branch with gradle 6.3 + 'org.javamodularity.moduleplugin' that proves it :
```
[Test worker] INFO io.limo.internal.memory.OffHeapServiceLoader - ServiceLoader<OffHeapFactory> loaded : io.limo.internal.jdk14.memory.MemorySegmentOffHeapFactory
```

In branch ```gradle-6.4``` I switched to native module support from gradle 6.4, and removed 'org.javamodularity.moduleplugin'.

This is the log for this same test, it didn't load the Service from module-info.java.
```
[Test worker] INFO io.limo.internal.memory.OffHeapServiceLoader - ServiceLoader<OffHeapFactory> loaded : io.limo.internal.memory.BaseByteBufferOffHeapFactory
```
I tried it from IntelliJ and using ./gradlew command line, result is the same.

**Comment by jjohannes** [comment]
@pull-vert thanks for trying out the RC and the module support.

What you are seeing is expected. Gradle only treats _source sets_ with a `module-info.java` file as modules. If the file is not there, everything will be processed on the _classpath_ and all module information of dependencies (like your main sources) will be ignored. This is often fine for unit tests (whitebox testing with _classpath_).

For the sample you gave, I would suggest to do a blackbox test, where the tests are defined in their own module. This way, everything is set up as it is in production without the need to add any additional patch parameters to module compilation **and** execution.

If you add a file `limo-core-jdk14/src/test/java/module-info.java` with this content:
```
open module limo.core.jdk14.test {
    requires org.junit.jupiter.api;
    requires org.assertj.core;

    requires limo.core;
    requires limo.core.jdk14;
}
```
Then you have the expected result.

The 'org.javamodularity.moduleplugin' does some module patching so that it works like you describe. The downside is that this does not exactly match the production environment as the module information of your main module under test is modified.
There is no special support for this specific kind of module testing (whitebox with module path) at the moment – although you could do something like that by manually adding patch parameters [like in this example](https://github.com/jjohannes/gradle-jpms-experiments/blob/master/module-b/build.gradle.kts#L10-L16).
We did not yet discover the use cases that really require this (which can not be solved well proper black box or simple classpath whitebox testing). So we don't know what the "common case" is and what would be useful defaults to support this.

**Comment by pull-vert** [comment]
@jjohannes thanks a lot for your answer !

Your solution solved my use case perfectly, I knew that module was patched but I thought this was needed for tests. Now with a module-info.java in test this is the normal behavior.
