### ISSUE TITLE
java.lang.ClassCastException when compiling groovy gradle source

### ISSUE THREAD

**Issue by davidobber** [gradle/gradle#12903]
### Expected Behavior
Gradle script compilation should be successful

### Current Behavior
Got a java.lang.ClassCastException: org.codehaus.groovy.ast.stmt.ReturnStatement cannot be cast to org.codehaus.groovy.ast.stmt.BlockStatement error when compiling the gradle file

### Context
Declaring the function setupContainer() with "def" return value **worked with Gradle 3, 4, 6.2.2**. With version **6.3 I had to clearly declare it as a void function**, to avoid a ClassCastException.

### Steps to Reproduce 
Extract the content of the attached zip in a new folder and **run gradlew**. It should raise an exception.
Then **change the return** value of the setupContainer() function  from **def** to **void**. Re-run gradlew and everything should be fine.

### Your Environment
Build scan URL:
Windows 10, Java 8.241
Build Scan: https://gradle.com/s/e5junkzht52vu
[gradle-issue.zip](https://github.com/gradle/gradle/files/4529486/gradle-issue.zip)

**Comment by big-guy** [comment]
This is a bug in Groovy: https://issues.apache.org/jira/browse/GROOVY-9438

We can fix this in Gradle 6.5 since there's a fix available in Groovy 2.5.11.

Based on the way you're using the method, I think using `void` is appropriate.  The other workaround is to add something after the switch statement (e.g., `return`).
