### ISSUE TITLE
Incorrect variant resolved for `compileClasspath` when dependency substitution rules are applied

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#12951]
In some circumstances, the `compileClasspath` for a `java-library` project will resolve the `default` variants of some Maven dependencies, rather than the `compile` variant as expected.

This happens in the following situation:
- `prj-lib` is a simple `java-library` project
- `prj-resolve` has a single configuration `conf` with a vanilla project dependency on `prj-lib` (no attributes)
- There is a dependency substitution rule that forces `conf.resolutionStrategy.resolveGraphToDetermineTaskDependencies` (or the build is executed with `-Dorg.gradle.resolution.assumeFluidDependencies`)

https://github.com/bigdaz/issue-incorrect-variant provides a minimal project that reproduces this issue.

**Comment by melix** [comment]
So this error is a variation of https://github.com/gradle/gradle/issues/12728 which is exercised in a different manner.

The problem is that our component metadata caching strategy assumes that all projects in a multi-project build use the same module metadata (it's one cache per _build_, not per _project_). As a consequence, depending on the order of the tasks, or, depending on the _order_ of the tasks (for this dependency substitution case), the _first_ project to be resolved matters. In this case, if the first project being resolved is a Java project, everything is fine. But if the first project being resolved is `prj-resolve`, then the Java derivation strategy is _not_ applied and you get inconsistent results.

The current workaround is to make sure all projects apply the derivation strategy, by applying the `java-base` plugin.

Ideally, the cache key should include the derivation strategy, I'm going to look into this.

**Comment by ljacomet** [comment]
@melix FYI #9415
