### ISSUE TITLE
Build dashboard calls "all" rather than "configureEach", breaks other plugins

### ISSUE THREAD

**Issue by binkley** [gradle/gradle#12967]
# Expected Behavior

Other plugins do not always combine nicely with the "build dashboard" plugin.  To wit: In a simple project using these plugins:
- build dashboard
- testsets
- quality

The build breaks with:

```
Caused by: org.gradle.api.InvalidUserDataException: Cannot change dependencies of dependency configuration ':a:spotbugs' after it has been resolved.
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.preventIllegalMutation(DefaultConfiguration.java:1124)
```

Drilling into this shows the source code says:

```
project.getTasks().all(new Action<Task>() {
```

when it should say (based on https://github.com/xvik/gradle-quality-plugin/issues/24):

```
project.getTasks().configureEach(new Action<Task>() {
```

Apologies if the explanation is off.

### Current Behavior
Gradle dies with a stacktrace.

### Context
I'm trying to add the [quality plugin](https://github.com/xvik/gradle-quality-plugin) to this project: https://github.com/binkley/gradle-multiple-test-roots.

See this commit which demonstrates the described behavior: https://github.com/binkley/gradle-multiple-test-roots/tree/64612f3a194d61de8054fa0a1a07169ad0e15ef5

The purpose of my project is as demonstration for (client, others) of how to use multiple test source roots in gradle (eg, unit tests _vs_ integration tests), and apply full code quality measures.

### Steps to Reproduce 

```
$ git clone https://github.com/binkley/gradle-multiple-test-roots
$ git checkout 64612f3a194d61de8054fa0a1a07169ad0e15ef5
$ ./gradlew build
```

### Your Environment

Build scan: https://gradle.com/s/w5ocyui4dk52o

**Comment by jjohannes** [comment]
To clarify. This is about using `configureEach {}` here: https://github.com/gradle/gradle/blob/master/subprojects/reporting/src/main/java/org/gradle/api/reporting/GenerateBuildDashboard.java#L102

**Comment by jjohannes** [comment]
I tried to change this as suggested (#16814), but it makes the "build dashboard lists the reports which have not been generated" test fail. Because the build dashboard does also render information for tasks that have not been executed.

I agree that using `all { }` here is still not good. But we can't just change it.

Since the BuilDashboardPlugin is essentially unmaintained, and a candidate for deprecation and removal from core, I can't spend more time on this. I would be willing to accept a PR if there is a simple solution to this though.

I don't fully understand why this is a problem with a quality plugin. Maybe this could be solved differently? Or maybe now (almost one year later) it already works with the latest Gradle version and the latest version of the plugin?

**Comment by binkley** [comment]
Commenting to reopen this
