### ISSUE TITLE
Allow buildSrc to use and see other included builds

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#12978]
This is one of the limitations of `buildSrc` project when compared to regular included builds.

### Expected Behavior
`buildSrc` project should allow to include builds.
`buildSrc` should see builds included by the root project - this is how regular included builds behave.

### Current Behavior
`buildSrc` explicitly prohibits including a build in its `settings.gradle`: `Cannot include build 'some-build' in build 'buildSrc'. This is not supported yet.`
`buildSrc` project does not see the builds included by the root project.

### Context
This prevents sharing certain conventions or build logic via binary plugins when using `buildSrc` - conventions/logic that a project author wants to be shared between production software build and the build logic build (`buildSrc`).

**Comment by Vampire** [comment]
You can (probably since the change that the settings script is evaluated before `buildSrc` is built) include a build in the parent builds settings script and then reference it in the `buildSrc` build. I just tried it as the question came up in the community slack and it works just fine. I guess that is as far as it will get without `buildSrc` being a "regular" included build yet.

**Comment by adammurdoch** [comment]
This is fixed in Gradle 8.0 via https://github.com/gradle/gradle/pull/22540.
