### ISSUE TITLE
Release gradle main artifacts on central

### ISSUE THREAD

**Issue by rmannibucau** [gradle/gradle#13081]
Hi all,

I wonder if there is any reason to not release gradle on central - at least for each major release.
Goal is to enable other build based project to create more easily gradle plugins without having to hack the build and dependency system.
Typically, a maven build based project which want to provide a gradle plugin, should be able to consume gradle core/api from central directly IMHO.

Romain

**Comment by big-guy** [comment]
We think that developing a Gradle plugin with Gradle is a lot better because we can provide checks and features that wouldn't be possible in other tools. What I've seen other people do is wrap the Gradle build (to build the plugin) in another tool.  

It's not as simple as publishing all of the jars from Gradle because the actual Gradle API may not match the individual jars because we relocate dependencies.  Eventually, we'd also like to enforce a public API/internal API separation.

**Comment by rmannibucau** [comment]
@big-guy hmm, it is actually as simple as that cause relocations and all these things are the flavor pushed to central, concretely gradle/lib should be pushed to central IMHO. This is how several plugins are done using older releases available on maven repositories but v5-6 are nowhere and wrapping the build with gradle has downsides compared to just pulling jars (so generally gradle is grabbed and added locally in the build but it is not satisfying).

Side note: it is fine to push only a mock of the public API as some other libs do.

Regarding checks, I suspect it can be replaced by a maven plugin or just a `main(String[])` taking as input all required data like dependencies and things like that. Then it is easy to execute it.

**Comment by melix** [comment]
Let's clarify a few things here because there are different ideas mixed up. First, the use case is not "downloading from Maven Central", but rather how to build Gradle plugins from another build system, in particular Maven here.

In general, as @big-guy explained, we're not very keen on letting external tools do this because we can provide much more validation with Gradle than we do with external tools. This includes, but is not limited to, validation of the task input and output declarations, use of deprecated APIs, ...

So the question is, if a project uses Maven as its main build tool, how to publish a Gradle plugin. There are several strategies for this. The first, obvious one, is to use some CLI integration to call a Gradle build. This is the approach taken for example by the [ByteBuddy build](https://github.com/raphw/byte-buddy/blob/master/byte-buddy-gradle-plugin/pom.xml). It works but requires some integration with Maven to share the artifacts from the Maven build with the Gradle build.

Another solution would be to write a Maven plugin which makes use of the [Gradle Tooling API](https://docs.gradle.org/current/userguide/embedding.html). This would be a step forward because instead of relying on the CLI, the TAPI is capable of downloading Gradle itself, and executing a Gradle build. But more importantly it can share a model with the consumer, which means that the Maven build could be made aware of what Gradle produces, while Gradle itself could be made aware of what the Maven build produces. This would be my preferred approach, honestly.

The last solution that you tried is unsafe. Basically, you're reusing artifacts published at [our internal repository](https://repo.gradle.org/gradle/libs-releases-local/). This led to this ticket, basically stating that it would be nicer to have those on Central. The thing is, those libraries were never intended to be public. Actually, what is published here is side effects of our own build.

More importantly, even if we published those on Maven Central, there would be a lot of issues:

- the artifacts published here are inconsistent in time. The only artifact which was intentionally published and intended for external use is the Tooling API mentioned above. I think that it would make sense to publish the TAPI artifacts to Maven Central, because that one is pretty clean and safe.
- the metadata of those artifacts is not correct. Historically Gradle was designed as an application, not as a set of reusable external libraries. Don't ask me why it was done like that, I don't know and I guess most of the Gradle folks today ignore it. The thing is, Gradle wasn't published to a Maven repository and was always distributed... as a zip distribution, that's it. We are several folks at Gradle thinking it would be much easier for us (for our own reuse in different products) and for external people willing to reuse parts of Gradle (the community) if everything was published in a repository, then sync'ed on Central. We started taking steps towards this. That's the reason why you see all those different modules on our internal repository. Yet, the metadata (POM files) is incorrect, it doesn't have Gradle metadata and the published artifacts to not always reflect what you have in the distribution (transforms).
- the most problematic point is that even if we _did_ publish all those artifacts and that you could use them, a plugin written against those artifacts would _not_ be a plugin compiled against the Gradle API. When you build a Gradle plugin, Gradle first generates a number of jars which are the "Gradle API", which consists of the "Gradle API jar", the "TestKit" jar, and potentially Kotlin extensions. In order to reduce the size of the distribution, the decision was made several years ago to generate this at runtime, from the Gradle distribution itself. This step includes additional transformations, such as relocations to hide dependencies which shouldn't be visible to plugins (internal dependencies hidden at runtime by Gradle) or decorations for backwards compatibility. We are, internally, discussing the possibility to publish those jars to an external repository too, but it's a significant amount of work, and it wouldn't solve problems we'd like to solve at the same time. One of them being capable of building a plugin for several releases of Gradle at once. This is why the approach of directly depending on Gradle jars is inherently wrong.
- eventually, mirroring to Central and publishing libraries require some infrastructure changes. It also requires signing, which is a good thing to do in general, but is orthogonal to this issue. All those infrastructure changes are not cheap.

Hope this helps better understanding the decisions we make.

**Comment by rmannibucau** [comment]
Thanks  @melix, this is a good summary. I would just add that bytebuddy setup is still partial (no sync-up of target/classes for example which can break living doc setup or maven deployment depending the plugins used to give just two trivial examples).

Is the validation mainly about https://github.com/gradle/gradle/blob/b2832614041cd8272f9ee09377c555e48920e07b/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/internal/ValidateAction.java#L52 ? If so two small thoughts on that:

1. It is close to what a runtime IoC would do (actually gradle is ;)) and most of them don't do build time validations so I guess users can live with it
2. it does not look crazy to abstract or even do a maven plugin doing it

I recall in first gradle version the philosophy was really to stay close and not reuse maven infra because it was the concurrent (I almost not exagerate but was kind of rude) but I have the feeling things changed and that this small competition is behind so I think this topic can probably be revised now (even if it does not urge to do it because there are workarounds even if they all have drawbacks).

That said, you are totally write "deploy on central" actually means "make it easier to dev a plugin with another build tool" (maven being my immediate need indeed).

**Comment by melix** [comment]
> Is the validation mainly about 

I'm not super familiar with this code but I _think_ so.

> most of them don't do build time validations so I guess users can live with it

This is more about making sure the plugin authors use the right APIs and don't do silly mistakes, like forgetting to declare an input, attaching the wrong types to inputs, having redundant declarations, making sure they are compatible with the build cache, ... Those are done at _plugin build time_, before the plugin is actually published to the portal (or another repo).

> I recall in first gradle version the philosophy was really to stay close and not reuse maven infra because it was the concurrent 

To be honest I don't think it has ever been the case that we wouldn't like to reuse Maven infra. Quite the opposite: we reused Maven POM files from day 1. We supported publishing to Maven repos too, and we actually support publishing to other kinds of repos too (Ivy, file, ...). So Gradle has always been quite open. What we were _not_ and still not fond of is the Maven model itself (POM as the build file). POM as publication was ok'ish, until we started with our own format (Gradle Module Metadata) ;)

**Comment by rmannibucau** [comment]
Oki, so think it means delivering a reusable main (can need to use asm/bcel instead of doing reflection to avoid the dependency management to keep it simple or just request the classpath to the caller) and publishing it on a public repo, then sounds like all would be good for everybody :).
