### ISSUE TITLE
Gradle believes 1.0.0.M2 is newer than 1.0.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by jameskleeh** [gradle/gradle#13116]
I have a bom declared with `platform`, that has entries with version `1.0.0.BUILD-SNAPSHOT`. There are transitives in the graph that reference `1.0.0.M2` of the same depdendency and that version is chosen over the snapshot version declared in the bom.

### Expected Behavior
Gradle should recognize that the snapshot version is newer and use it

### Current Behavior
Gradle uses the M2 version

### Context
This is causing an issue because some modules are using the snapshot and some modules are using M2, and they are not compatible.

Ideally, a new platform type option would be ideal. Platform is less than ideal because of the above scenario. Enforced platform is less than ideal because you can't simply express a dependency with a version in the build and have that respected. A platform like option that was enforced only for transitives and explicit dependencies without a version would be ideal.

### Steps to Reproduce 
This is currently possible by running `./gradlew classes` on https://github.com/jameskleeh/gradle-platform-bug

### Your Environment
macOS
JDK8
Gradle 6.3

**Comment by ljacomet** [comment]
Hello,

This is expected behavior as Gradle first splits the version in parts - `[1,0,0,M,2]` and `[1,0,0,BUILD,SNAPSHOT]` then compare them. So when it compares `M` with `BUILD`, `M` is larger and wins.

Note that Maven "works" because `BUILD` is not special cased and is thus greater than `M`, special cased for _milestone_, _and greater than `1.0.0` or `1.0.0.RELEASE`_.

What did you expect to happen exactly with this versioning scheme?

**Comment by jameskleeh** [comment]
I guess I at least expected this to be recognized as an issue. Should have
known better.
