### ISSUE TITLE
Kotlin Gradle Script is too limited when it comes to reuse

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#13112]
This is sort of a meta comment, but I think it's worth sharing. Kotlin Gradle Script is great! However, it actively prevents reuse at times. I understand that the current Gradle advice for this is to wrap them up in a precompiled plugin, but this solution is both heavy handed and often not actually correct.

* `buildSrc` adds a nontrivial amount of overhead to your project, especially once you start adding tests (which run every time). It becomes easy to make changes that bork your build cache too
* precompiled scripts are not the same as having indexable APIs for reusable functions, constants, etc.
* Reusing individual `common.gradle.kts` files are limited solely to whatever gradle provides API-wise. Now allowance of imports (even if they're APIs available in applied plugins or buildSrc)
* Certain scopes do not allow access to buildSrc APIs, such as `buildscript` blocks or `pluginManagement`. Furthermore, the "rules" of these blocks are inconsistent. Using buildSrc APIs in root project `buildscript` block _does_ work _if_ your entry point to that API _has no package name_.
* If you want to share logic in buildSrc/build.gradle.kts with the rest of the project, you are basically out of luck
* Different configurations have different sets of gradle APIs available. In a regular project repositories block, you can call things like `findProperty`, etc. In buildscript or pluginManagement, you cannot. However, in those same two blocks, you _can_ call `apply()`, but the files you apply from have way of knowing what context they're running in, nor can they expose usable APIs back to the buildscript block. Groovy somewhat gets away with this because of the magic duck typing where everything goes into `extras`.

It would be great if Kotlin DSL could improve consistency in some of these areas and better facilitate reusability. As a possible stretch, it would be ideal if precompiled scripts could have APIs (functions, etc) that are actually usable from scripts that import them (possibly via code gen that offers a statically linked API and just invokes it via `withGroovyBuilder` under the hood, hiding the gradle/groovy magic)

**Comment by ZacSweers** [comment]
Closing due to lack of feedback from Gradle

**Comment by robercoding** [comment]
It's been 3 years since this issue was mentioned and I have a few use cases that would have been nice to make this code accessible/reusable from multiple places. I'm going to provide 2 use cases that would help a lot to avoid these tricky solutions.   

It could also be due to my limited knowledge on Gradle. So after you see my use cases, you could see an improvement or maybe a solution! Let me know if that's the case

**Use case 1**:
I have extension functions that I want to use in my `pluginManagement` repositories block & `dependencyResolutionManagement`.  I can't create these function extensions outside of my `pluginManagement` so I would have to duplicate the functions in each block which end up in a lot of code.
_Solution_:
Inside `pluginManagement` block you can also set `dependencyResolutionManagement`. So I ended creating them inside this block and then using them for each block. Something like this:

```
pluginManagement {
   fun RepositoryHandler.myRepo() = something...

  repositories {
    myRepo()
  }

  dependencyResolutionManagement {
    myRepo()
  
}
```

**Use case 2**:
I want to use a function that checks for an extra from my `gradle.properties` and based on what I have set I can do multiple things. Which leads to a primitive type output (_i.e: Boolean_).
This function would be used in my `pluginManagement` from `settings.gradle.kts`, `buildscript` block from build.gradle.kts project level and so thanks to the latter it'd be available for my subprojects

_Solution_:
Set the function in my pluginManagement and then set a new extra to be reused across other kts files.
```
pluginManagement {
  fun myBigFunctionCheckingExtras(): String {
    ...
  }

  val isUsingSomething: Boolean = myBigFunctionCheckingExtras() == "something"
  val isUsingSomething2: Boolean = myBigFunctionCheckingExtras() == "something"

  (gradle as ExtensionAware).extensions.extraProperties.set("isUsingSomething", isUsingSomething)
  (gradle as ExtensionAware).extensions.extraProperties.set("isUsingSomething2", isUsingSomething2)


  repositories {
    If(isUsingSomething) {
      myRepo()
    }
  }
}

And in my `build.gradle.kts` `buildscript` block:

buildscript {
  val isUsingSomething = (gradle as ExtensionAware).extensions.extraProperties.get("isUsingSomething") as Boolean
  val isUsingSomething2 = (gradle as ExtensionAware).extensions.extraProperties.get("isUsingSomething2") as Boolean

  if(isUsingSomething) {
    classpath(...)
  }
}
