### ISSUE TITLE
Please make it possible to use script plugins in buildscript with kotlin

### ISSUE THREAD

**Issue by denis-zhdanov** [gradle/gradle#13215]
**Problem**

With groovy `*.gradle` scripts, we can externalize common setup like repositories definition and re-use it either in regular project setup or `buildscript` section.

E.g. we might have `src/main/resources/include/repository.gradle` with the following content:

```
repositories {
    mavenCentral()
    jcenter()
}
```

and use it like this:

```
buildscript { scriptHandler ->
    apply from: 'src/main/resources/include/repository.gradle', to: scriptHandler

    dependencies {
        classpath "org.jfrog.buildinfo:build-info-extractor-gradle:4.15.2"
    }
}
```

However, looks like it's not possible to do the same thing with `gradle.kts`:

```
buildscript {

//    apply(from = "src/main/resources/include/repository.gradle.kts")

//    apply {
//        from("src/main/resources/include/repository.gradle.kts")
//    }

    rootProject.apply {
        from("src/main/resources/include/repository.gradle.kts")
    }

    dependencies {
        classpath("org.jfrog.buildinfo:build-info-extractor-gradle:4.15.2")
    }
}
```

Getting the following:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'spring-boot-gradle-dist'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Cannot resolve external dependency org.jfrog.buildinfo:build-info-extractor-gradle:4.15.2 because no repositories are defined.
     Required by:
         project :
```

**Task**

Please allow importing `gradle.kts` script plugins in `buildscript` section

**Comment by big-guy** [comment]
Sorry, we're not going to do this for a couple of reasons.

We have [other mechanisms for describing where to get plugins](https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories). This is configured in a single place (`settings.gradle(.kts)`).

Instead of adding dependencies directly to the classpath of the buildscript, you can use the `plugins` block. In your example, that becomes:
```
plugins {
  id("com.jfrog.artifactory") version "4.15.2"
}
```

In the cases where it is useful to share a script plugin, we're instead moving people to use [precompiled script plugins](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins). These behave like binary plugins with a script-like syntax and have fewer shortcomings than script plugins.

Is there anything stopping you from using `pluginManagement` and the `plugins` blocks instead?
