### ISSUE TITLE
Broken non-incremental compilation with Scala

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#13224]
The Zinc integration rolled out with Gradle 6.0 has broken **non-** incremental compilation for Scala.

Given two Scala classes in the same package, if one changes, the compilation output of the unchanged class disappears **when disabling incremental compilation**.

This needs further investigation to fully understand the problem.

**Edits in bold following further analysis**

**Comment by ljacomet** [comment]
@SheliakLyr @ijuma @retronym Excuse the ping folks, but in case the above report immediately makes you think about a potential issue in the way Gradle integrates with Zinc, that would help 😉 

Effectively, when Zinc is involved and has an analysis file, only changed sources appear in the output, all the rest gets cleared. From what I can tell - though I need to investigate further tbh - the deletion is done by the forked worker taking care of the Scala compilation. Aside from invoking Zinc, that worker does not have logic to clear output.

**Comment by ljacomet** [comment]
Incremental compilation actually works perfectly well.

It is when opting out of it that Gradle has an issue. The `ScalaCompile` setup will query the `ScalaCompileOptions.isForce` and if `true`, it will delete the compilation output.

However Gradle still handles the SBT analysis file, both by feeding its information into SBT and by serializing the information after compilation.
This means that SBT believes it only needs to compile what changed ... while in fact Gradle nuked _all outputs_.

Fix incoming.

**Comment by ijuma** [comment]
Nice find!

**Comment by ljacomet** [comment]
An easy workaround for Gradle 6.0 to Gradle 6.4 is to delete the analysis file in a `doLast` on `ScalaCompile`:

```
doLast {
    if (scalaCompileOptions.force) {
        scalaCompileOptions.incrementalOptions.analysisFile.get().asFile.delete()
    }
}
```

**Comment by ijuma** [comment]
@ljacomet In what scenarios would `isForce` return true?

**Comment by ljacomet** [comment]
When you attempt to disable incremental compilation - see the explanation and sample in [the documentation](https://docs.gradle.org/current/userguide/scala_plugin.html#sec:scala_incremental_compilation).

**Comment by ijuma** [comment]
OK, so only if one tries to disable incremental compilation explicitly. I wasn't sure if Gradle did it automatically under some cases.

**Comment by rpalcolea** [comment]
This is related to https://github.com/gradle/gradle/issues/12631

**Comment by ljacomet** [comment]
Oh indeed @rpalcolea, did not link both!

**Comment by rpalcolea** [comment]
I wasn’t that off I guess 😅 https://github.com/gradle/gradle/issues/12631#issuecomment-629590120 interesting finding! Thanks for fixing

**Comment by ivan-klass** [comment]
Please remove "NON" part as this also affects incremental compiler also. We use default incremental compilation and sometimes experience that
ScalaCompile task may successfully complete but compiler output is incomplete - some classes are missing in build/classes and in target jar, as result. However, compileScala task is marked as complete and the output is cached, which require extra tricks with --rerun-tasks --no-build-cache to fix.
 when something invalidating the project happens. 
These issues start to raise very often when we start switching to api/implementation configurations with `java-library` which is recommended replacement of deprecated `compile` configuration. Looks like Gradle invalidates the output because of different project "layout" while nothing changed for Zinc.

So our guess is that's a kind of Zinc integration issue - when zinc is not writing a some class it is probably skipping the compilation output because there were no incremental changes to it and it is "already compiled" in zinc state, but that state is not properly invalidated by gradle - i.e. gradle task incremental build state and zinc compiler incremental state are out of sync.

**Comment by ljacomet** [comment]
@ivan-klass Thanks for the feedback. I will keep this issue as-is since that is definitely broken, it is trivial to reproduce and a fix has been found.

Please open another issue for the Scala incremental compilation problem and provide as much information as possible so we can attempt to reproduce the issue. Of course a reproducer would be ideal, but I understand this might be tricky to provide.
