### ISSUE TITLE
Allow shared fork pool between tasks; ideally automatically

### ISSUE THREAD

**Issue by idontusenumbers** [gradle/gradle#13311]
### Expected Behavior

Tests (or otherwise) in multiple sub projects should be able to share the same fork pool or, ideally, auto-fork to use available CPU and memory but not beyond.

### Current Behavior

Currently, each tasks gets its own fork pool which can overwhelm a system, especially when each task also consumes significant amounts of memory). This puts an upper limit on the number of subprojects (since each one defaults to a pool of size 1) and also precludes two large sub-projects from sharing a pool.

### Context
We have multiple sub projects, each with their own set of tests. We can only have one of those sub projects run tests with a maxParallelForks set above 1 because that fork count is multiplied by n where n is the number of sub projects.

We use TestContainers, which itself uses Docker to start containers for various tests; this can quickly overwhelm the machine's memory with too many forks.

* 20 sub projects with `maxParallelForks=1` means effectively 20 forks, which could be considered over-parallelization on a machine with 2 cores.
* 2 subprojects, one with 100 tests and another with 5; developers have to manually optimize `maxParallelForks` settings, which could be different depending on machine resources, or could mean idle cores and thus wasted performance 
* 10 sub projects with 100 tests each, Setting to `maxParallelForks = Runtime.runtime.availableProcessors()` means each core is starting 10 tests, on a high core CPU with high-memory tests, this could easily overwhelm available memory.

**Comment by DPUkyle** [comment]
Hi Charlie, thanks for reporting.

I don't have much background with TestContainers or Docker, but I am curious as to where you're creating the fork pool? Some of the limits on resource sharing between tasks is likely by design.

While I understand this might not match your use-case, our recommended approach for threading/parallelism and resource sharing is via the [Worker API](https://docs.gradle.org/current/userguide/worker_api.html). Parallelism can then be controlled by the `org.gradle.workers.max` property or `--max-workers` CLI argument.

Please have a read and let us know if this doesn't address your use-case. We can open another issue for that.

**Comment by idontusenumbers** [comment]
@DPUkyle The fork pool is created implicitly by gradle when we invoke `gradle test` based on this example: https://docs.gradle.org/current/userguide/performance.html#parallel_test_execution

And the presence of gradle.settings:
```
org.gradle.parallel=true
```
The suggestion I'm making here is to modify the behavior of the existing, built-in test tasks to fork more consistently.
