### ISSUE TITLE
Fix IDEA support for `kotlin-dsl` subproject

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#13360]
The Kotlin compiler dependencies are not picked up by IDEA for the `kotlin-dsl` subproject, so classes like [`Lexer.kt`](https://github.com/gradle/gradle/blob/691cc03e066763aae6fc6ea13c47ca0de224d3c5/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/execution/Lexer.kt#L19-L26) show errors.

![image](https://user-images.githubusercontent.com/423186/84001843-be70a380-a967-11ea-8c85-3946c7e63c7a.png)

We somehow should add the Kotlin compiler embeddable (patched or unpatched) to the compile (only?) classpath of the `kotlin-dsl` project so IDEA recognizes it. Unpatched would probably be better since that would also show the sources for the compiler.

**Comment by wolfs** [comment]
The IDEA support may have worked at some point by unpacking the patched Kotlin compiler, though it stop working. Since unpacking the compiler is pretty expensive, we should avoid doing so. See https://github.com/gradle/gradle/issues/11693 and for more context.

**Comment by jjohannes** [comment]
The issue here is most likely that "kotlin-compiler-embeddable" is a Java project that does not actually have sources. Instead, it patches the already compiled Kotlin compiler. IDEA probably expects the project to have the sources. We should get IDEA to treat this project similar to an external dependency.

We could revisit if we can get rid of the patched Kotlin compiler:
https://github.com/gradle/gradle-private/issues/1691

**Comment by eskatos** [comment]
Fixed by https://github.com/gradle/gradle/pull/14524
