### ISSUE TITLE
Allow dependency resolve rule to influence variant selection

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1340]
Original issue: https://issues.gradle.org/browse/GRADLE-2763

### Expected Behavior

A dependency resolve rule can set or change the classifier attribute or a requested module.

**For example:**

```
configurations.all {
     resolutionStrategy.eachDependency { DependencyResolveDetails details ->
         def req = details.requested
         if(req.group == 'org.codehaus.groovy') {
             details.useTarget group: req.group, name: req.name, version: req.version, classifier: 'indy'
         }
    }
}
```

### Current Behavior

Only the attributes `group`, `name` and `version` can be set/changed.

### Context

Enforcing a module with a specific classifier.

**Comment by socketbind** [comment]
Hi bmuschko,

This would be particularly great when somebody needs to replace dependencies with their obfuscated counterparts which are usually published with the "obfuscated" classifier.

**Comment by jhansche** [comment]
Should also support `ext` as well.  I.e., to switch between `zip` vs `jar` vs `aar`, etc, packaging.

**Comment by kazvictor** [comment]
I ran into this for the `ext` property. Here is a link to a stackoverflow question that details the use case:
https://stackoverflow.com/questions/50477558/changing-default-gradle-dependency-file-extension

**Comment by rustyTheClone** [comment]
Hi,
any update ? 
I have the same issue.

**Comment by paplorinc** [comment]
@ljacomet, @jjohannes, @melix, this would be useful for e.g. using the `no_aop` variant of Guice, i.e. `useTarget group: requested.group, name: requested.name, version: "4.2.2", classifier: 'no_aop'` in GE.
Is there another way of doing this?

**Comment by ljacomet** [comment]
Dependency management in Gradle has now established the use of variants as a better solution to this problem.
Nonetheless, the problem remains as it is not possible to select a specific variant with this API.

Updating the title to reflect the direction of a possible fix.

**Comment by jjohannes** [comment]
I am not sure if we want to add more variant awareness to resolve rules. I think the use cases should rather be solved *without* resolve rules if possible. So if we need to do something at all here, I would currently tend to do what was originally requested (if it is easy to do).

But to concretely answer @paplorinc question and offer alternative solutions:
With Gradle 6, you can solve this with feature variants and capabilities. Since Guice does not publish these variants (yet, maybe they will in the future :)), you can use _component metadata rules_ to add the missing information.
This is actually a sample in the new docs: https://docs.gradle.org/release-nightly/userguide/component_metadata_rules.html#making_different_flavors_of_a_library_available_through_capabilities
(I just saw that the second part of the example is wrong there, should be [this](https://github.com/gradle/gradle/blob/01b2aa7a4f73ebc018be75964bc883cd3f04764b/subprojects/docs/src/samples/userguide/dependencyManagement/customizingResolution/metadataRule/kotlin/build.gradle.kts#L223-L232))

In the case described in this issue, where a transitive dependency already brought in the other variant of _guice_,  you'll probably end up with a conflict. This can then be resolved like this:

```
configurations.all {
    resolutionStrategy.capabilitiesResolution.withCapability("com.google.inject:guice") {
        select(candidates.first { !it.variantName.contains("noAop") })
    }
}
```

Or you add another metadata rule 'correcting' the dependencies in the metadata of whatever brought in the 'wrong' variant.

Note you need Gradle 6 (RC will be available shortly) for this.
