### ISSUE TITLE
JavaExec task should support executable JAR

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1346]
Original issue: https://issues.gradle.org/browse/GRADLE-1274

### Expected Behavior

Support equivalent of `java -jar MyApp.jar`. The user should be able to set a property that references the JAR file that defines the main class and classpath in the manifest file.

### Current Behavior

Users have to set `main = '-jar'` as workaround which is not very useable.

### Context

From a user:

>  Just seems that a powerful build tool should support a standard Java invocation mechanism.

**Comment by cmakshin** [comment]
There's an identical problem with "-m"/"--module" in Java 9. An example of affected software is test launcher in JUnit 5 plugin (https://github.com/gradle/gradle/issues/1346).

**Comment by mkobit** [comment]
Would be nice to see this feature get added as https://github.com/gradle/gradle/pull/2419 is open (although out-of-date right now). Executing fat JAR's and tasks using modules in Java 9 both require nonintuitive workaround that is confusing to read when coming back to a build script.

**Comment by stovocor** [comment]
I updated #2419 so that it can be merged again.

**Comment by stovocor** [comment]
Next month, my pull request will celebrate its first birthday. Could someone please tell me what is keeping it from being merged?

**Comment by trevjonez** [comment]
@stovocor I do have a suggestion about your PR and the implementation, but first I would like to address the passive aggressive nature of your birthday comment by reminding you of the [`Contributor Covenant Code of Conduct`](https://gradle.org/conduct/). Specifically: `Other conduct which could reasonably be considered inappropriate in a professional setting`

Now for the actual feedback... 
Your portion of the PR checklist has uncompleted items and so that may be a part of why it has not been touched or reviewed. Also I was not able to quickly find any conversation between you and the Gradle team about the implementation plan of your proposed fix. And finally it is likely a very widely used api that is modified in the change set, so while all of the current test suite might be passing it isn't impossible down stream users would not be broken by the change. I would dare say your change set is in violation of the open/closed principle and interface segregation principle. Why not create a subclass of `JavaExecTask` with a name something like `JarExecTask`? At that point the change could be proposed as a pull request to gradle directly or published as a stand alone jar for your own usage until you can get a response from one of the project maintainers.

**Comment by stovocor** [comment]
@trevjonez Thank you for the quick response!

> but first I would like to address the passive aggressive nature of your birthday comment

I am truly sorry if this comment could be misunderstood as "passive aggressive", because this is not what I wanted to express. It was meant in a funny way while also expressing a bit of frustration because of the lacking progress for unknown reasons.

However, as a potential contributor I feel a bit left alone here. As far as I understand your comment, you do not know exactly why there has been no merge yet, but you provide some suggestions. If someone who could merge my PR decides it is not ready yet, it would be helpful to know why. Modifying the code again by myself without any advice about what is wrong with it, just because the PR gets old, seems not to be the right way.

Regarding the missing PR checklist: My change does not affect more than one public API or 20 files, so as far as I understand it, no link to the design spec is required. That is why I did not check the item. Should I remove it in this case instead?

**Comment by trevjonez** [comment]
You might try reaching out directly to a team member on the `gradle-community` slack group although even that might be futile this week [based on this tweet](https://twitter.com/gradle/status/1006566120294375424). I am not sure if the checklist has anything to do with the silence, but I know I tend to ignore PR's at work until all the checkboxes get hit and status checks go green, or until someone DM's me to help/look/review.

**Comment by stovocor** [comment]
I just realized that the pull request template has been changed in the meantime, removing the "design spec" item. So I am going to update my PR in the next days, making sure that all items are being checked. Thanks again for the support.

**Comment by stovocor** [comment]
#2419 has been updated again. I performed a rebase against the current master and added documentation for the DSL reference. All items from the checklist are now done, in my opinion the PR is ready to be reviewed.

**Comment by lingocoder** [comment]
Hi all,

_**CC**_: _@bmuschko, @mkobit, @trevjonez_ 
  
You have probably solved this for yourself by now, I presume, @stovocor. But in case anybody else is interested I've made a [*JarExec plugin*](http://bit.ly/JarExecPi) available to the community.

In addition to the core Jar executing capability, if you pass it an optional classpath and the name of a class with a main method, it'll also run plain old non-executable Jars too. 

The plugin also adds a super useful *`jarhelper`* property to the build. With that helper, you can do things like retrieve resolved artifacts from Gradle's dependency cache. I discussed an example of such a use case in [*a recent Gradle forums discussion*](http://bit.ly/LngoJar).

Please have a play-around with the plugin and let me know if it foots your bill?

**Comment by big-guy** [comment]
A version of this'll be in 5.6 and works with `JavaExec` and `project.javaexec {}`. 

If the `main` class is not defined for the `JavaExec` and the classpath is a single jar, we will try to execute java with an executable jar.
