### ISSUE TITLE
Make `application` plugin support the configuration cache

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#13463]
This issue is about making the `application` core Gradle plugin support the configuration cache.

Upon completion, all configuration and tasks provided by the `application` plugin are compatible with the configuration cache.

**Comment by ljacomet** [comment]
Follow up issue:
* #21505

**Comment by mlopatkin** [comment]
#15239 is still reproducible, but even without CC, so it is not relevant here.

**Comment by jasonsparc** [comment]
@mlopatkin PR #23924 seems relevant to issue #15239

From what I can understand, the PR sets up `applicationDefaultJvmArgs` via the new `jvmArguments` as its `convention()` value. What this means is that, should `jvmArguments` be set to any other value, such as simply, using `jvmArguments.add()` for example, then what you end up getting is that `applicationDefaultJvmArgs` is now effectively lost **unintuitively**. Moreover, there's nothing in the docs that say that, `applicationDefaultJvmArgs` is only applied if you don't apply your own `jvmArgs`.

Also note that, `jvmArgs()` delegates to `jvmArguments.add()` now (as of Gradle 8.4 at least). See, https://github.com/gradle/gradle/blob/v8.4.0/platforms/jvm/language-java/src/main/java/org/gradle/api/tasks/JavaExec.java#L230

I don't feel like opening a new issue since I merely glanced at that PR and noticed this issue, so I could be wrong.

---

Also, regarding what I said about the docs about `applicationDefaultJvmArgs`, check out the following:

- https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaApplication.html#org.gradle.api.plugins.JavaApplication:applicationDefaultJvmArgs
- https://docs.gradle.org/8.4/userguide/application_plugin.html#sec:application_extension:~:text=can%20configure%20the-,applicationDefaultJvmArgs,-property.%20These%20JVM

    Quote from the above link:

    > If your application requires a specific set of JVM settings or system properties, you can configure the `applicationDefaultJvmArgs` property. These JVM arguments are applied to the run task and also considered in the generated start scripts of your distribution.
