### ISSUE TITLE
`buildSrc/build` should not be added to classpath if `buildSrc` contains no sources or build files.

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#13491]
### Expected Behavior
If `buildSrc` contains no source files and no build files `buildSrc/build` should not be added to the buildscript classpath.

### Current Behavior
`buildSrc/build` is always added to the buildscript classpath.

### Context

Projects may remove the `buildSrc` in favor of using either composite/included builds or publishing plugins to a nexus repository. Since `buildSrc/build` is not checked in to source control, it may linger around causing inconsistent build behavior.

This also causes remote build cache misses since the buildscript classpath will be different for all tasks in comparison to the remote server which ran the same build.

We encountered this at SoundCloud and made a little presentation about it: https://speakerdeck.com/runningcode/remote-build-cache-misses-and-how-to-solve-them-by-annoying-your-colleagues?slide=59
And you can watch it here: https://youtu.be/2frfDMJwvf4?t=1485

**Comment by jduan** [comment]
Thanks for filing this issue! Just subscribed.

**Comment by wolfs** [comment]
I think this may not even be a problem with the `buildSrc/build` directory existing, but only that the `buildSrc` directory exists. Gradle automatically uses a certain build file for `buildSrc` if there isn't any `build.gradle` in `buildSrc`. And then it will run the `jar` task in `buildSrc` which has been automatically added by Gradle. The `jar` task will create an empty JAR with only a manifest inside, since there are no sources in `buildSrc`. That empty JAR is then added to the classpath of the root project.

Maybe Gradle could somehow detect the situation and not create the empty JAR when there are no inputs apart from the manifest to `buildSrc`'s JAR.
