### ISSUE TITLE
Cannot mix file and http protocols when resolving artifacts from a single maven repository

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1350]
Given the following build.gradle snippet:

```groovy
repositories {
    flatDir dirs: "${rootProject.projectDir}/repo"
    mavenRepo url: "https://..."
}
```

Gradle will not resolve artifacts from `${rootProject.projectDir}/repo` after failing to resolve from the HTTP-based repo. 

### Expected Behavior
Gradle should allow `file://` dependencies to be resolved locally if remote methods fail. 

### Current Behavior
Gradle fails with "Could not resolve all dependencies ..."

### Context
From https://discuss.gradle.org/t/making-gradle-find-a-jar-in-a-flatdir-repo-when-it-is-missing-from-a-maven-repo/7587

**Comment by adammurdoch** [comment]
Can probably just swap the order of the repositories.

**Comment by adammurdoch** [comment]
It would be good to rename this issue to reflect a use case instead of a proposed solution.

**Comment by bigdaz** [comment]
We treat modules as atomic elements of a repository. So all artifacts for a module must be sourced from the same repository. The original poster can address the missing jar issue by replicating the module (metadata and all) in a local file repository.

I don't think we'll fix this as described, so I'm going to close this pending a more compelling use case.

**Comment by mauromol** [comment]
The original reasoning behind this report, as depicted in the linked forum post, is for those dependencies that, for legal reasons, have their POM on Maven Central, but the corresponding JAR is not their. Or for dependencies with no source attached on the remote repository. Having the ability to put the missing JARs in a flat repository would be straightforward (and "natural", I would say), while setting up a local Maven repository for just this reason is quite of a work.
