### ISSUE TITLE
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Cannot resolve external dependency com.android.tools.build:gradle:5.6.4 because no repositories are defined.

### ISSUE THREAD

**Issue by patricefote** [gradle/gradle#13500]

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

In this case, the most likely root cause is actually in the error message: `no repositories are defined`
