### ISSUE TITLE
Scala compilation succeeds despite missing dependency

### ISSUE THREAD

**Issue by msogrin** [gradle/gradle#13535]
Scala compilation succeeds despite missing the dependency on `org.scala-lang.modules:scala-xml_2.12` and having code that uses `scala.xml` APIs.

### Expected Behavior

Gradle build stops with an error in compileScala step, with an explanation that `scala.xml.***` classes not found.

### Current Behavior

Gradle build succeeds (most likely, because scala-xml is a dependency of the Zinc compiler, so it's on classpath during compilation.
But scala-xml is not at runtime classpath, so it breaks at runtime.

It's probably doing the same with any other dependency brought in by Zinc.

### Steps to Reproduce 

- do NOT add scala-xml dependency to your build.gradle and ensure it's not brought in transitively.
- use APIs from scala-xml module.
- gradle assemble succeeds.
- program fails in runtime due to class not being found.

### Your Environment

Gradle 6.3 on MacOSX, using Gradle Kotlin DSL.

Build scan URL:

**Comment by msogrin** [comment]
Code to reproduce the problem at https://github.com/msogrin/gradle-scala-xml

**Comment by rpalcolea** [comment]
hey @ljacomet 

Looks like this is a change in Gradle 6.x

Gradle 5.6 shows the compilation error:

```
Compiling 1 Scala source to /Users/rperezalcolea/Projects/github/msogrin/gradle-scala-xml/build/classes/scala/main...
/Users/rperezalcolea/Projects/github/msogrin/gradle-scala-xml/src/main/scala/ScalaXml.scala:1: object xml is not a member of package scala
import scala.xml.Text
             ^
/Users/rperezalcolea/Projects/github/msogrin/gradle-scala-xml/src/main/scala/ScalaXml.scala:5: not found: type Text
    val text = new Text("test")
                   ^
two errors found

``` 

iirc, the new zinc compiler was introduced in Gradle 6

**Comment by ljacomet** [comment]
@SheliakLyr Hey, would you also be willing to look into this one?
I would also fully understand if you do not have the time.

**Comment by SheliakLyr** [comment]
Yes, seems be easy to reproduce, won't take much time.

**Comment by SheliakLyr** [comment]
The problem is caused by leaking incremental compiler classpath to classpath used for compilation. This is done in two places:

In `ZincScalaCompilerFactory.java`, `ClasspathOptionsUtil.auto()` should be replaced by `ClasspathOptionsUtil.boot()`.
```scala
        ScalaCompiler scalaCompiler = new AnalyzingCompiler(
            scalaInstance,
            ZincUtil.constantBridgeProvider(scalaInstance, bridgeJar),
            ClasspathOptionsUtil.boot(),
            k -> scala.runtime.BoxedUnit.UNIT,
            Option.apply(COMPILER_CLASSLOADER_CACHE)
        );
```

In `ZincScalaCompiler.scala`:
```scala
 .withClasspath(Iterables.toArray(Iterables.concat(Arrays.asList(scalaInstance.allJars()), spec.getCompileClasspath()), File.class))
```
should be changed to:
```scala
.withClasspath(Iterables.toArray(spec.getCompileClasspath(), File.class))
```
Commit with fixes: https://github.com/SheliakLyr/gradle/commit/d2660cc196a1296419e53658314dc618e2331ca9

This two changes make the compilation correctly fail for the provided test case. Tests in :scala pass correctly. I have however a problem with integTests in :language-scala. Those fail completely, as they depend (wrongly) on the leaking behaviour. They use 'scala-lang' plugin, for which I can't find any documentation. It is also deprecated. Any idea what to do with those tests?
