### ISSUE TITLE
Provide more public API for publishing (if required)

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#1361]
We noticed that renaming `o.g.api.internal.component.Usage`to `o.g.api.internal.component.UsageContext` in `3.4` broke functionality in at lease two publishing related plugins that rely on this internal API:
- gradle-docker - https://github.com/palantir/gradle-docker/issues/106
- bintray-release - https://github.com/novoda/bintray-release/issues/112

The use of internal APIs in these plugins indicate that there might be a need for more public API in this area.

The purpose of this issue is to identify if there is a need, and if, what the requirements are.

**Comment by eriwen** [comment]
@jjohannes Could you please break out stories for each API here?

**Comment by jjohannes** [comment]
I mainly created the issue here to have a place to collect thoughts on this topic from plugin developers who might be in need of additional API here. So there are no concrete APIs yet we have in mind for which I could create stories.

@eriwen if this is to vague at the moment to be part of #716 you may remove the link.

**Comment by eriwen** [comment]
I'll defer to @bmuschko's organization here.

**Comment by bmuschko** [comment]
Both plugins create a class that implements the internal class `SoftwareComponentInternal`. It's to be expected that the code might break.

- https://github.com/palantir/gradle-docker/blob/develop/src/main/groovy/com/palantir/gradle/docker/DockerComponent.java#L29
- https://github.com/novoda/bintray-release/blob/master/core/src/main/groovy/com/novoda/gradle/release/AndroidLibrary.groovy#L12

I am going to have a look at the use case they are trying to solve and identify the need. For future reference: we are organizing public API issues under the epic you assigned.

**Comment by bmuschko** [comment]
I commented on both plugins:

- https://github.com/novoda/bintray-release/issues/112#issuecomment-280699566
- https://github.com/palantir/gradle-docker/commit/c553eb684988f46af7879e7d92fb3b7603277320

From my perspective there's no good reason to use the internal API. You can achieve it with an existing, public API.

**Comment by eriwen** [comment]
You rock @bmuschko!

**Comment by mkobit** [comment]
Chiming in since it seems sort of related, but using the `PublishingPlugin` and trying to use [`Publication`](https://docs.gradle.org/current/javadoc/org/gradle/api/publish/Publication.html) requires the implementor to use internal APIs because of the [` PublicationInternal internalPublication = (PublicationInternal) publication`](https://github.com/gradle/gradle/blob/master/subprojects/publish/src/main/java/org/gradle/api/publish/plugins/PublishingPlugin.java#L90) line.

**Comment by bmuschko** [comment]
@mkobit I guess it depends on what you are trying to do. If you give me a concrete use case then I'd be able to comment.

**Comment by wolfs** [comment]
@bmuschko The Gradle jpi plugin (plugin for building Jenkins plugins with Gradle) is also broken: https://github.com/jenkinsci/gradle-jpi-plugin/pull/84
Is there a way to use a public API for solving the problems there, too?

**Comment by mkobit** [comment]
@bmuschko hopefully this gives some context into what we were doing and what we ran into.

We developed a Docker plugin internally at around `2.13` or `2.14` with the notion that we would be building against the model API as that was noted to be a core feature for `3.0`.

We wanted to model it similar to how the [_Maven Publishing (new)_](https://docs.gradle.org/current/userguide/publishing_maven.html)  models publishing Maven bundles, since that is how most of our developers had already become familiar with creating Maven publications.

The idea was to provide something like this:

```
model {
  components {
    myImagePublication(DockerImageComponent) {
      name = 'mkobit/myapp'
      tags = ['latest']
      // Make sure Docker image is built after application is built
      consumes $.components.java
    }
  }
  publishing {
    publications {
      myApplicationPublication(DockerImagePublication) {
        from $.components.myImagePublication
      }
    }
  }
}
```

So, we started to implement some of the types that seemed to be required based upon looking at the Gradle source code for `MavenPublishingPlugin`.

* Need to define a `DockerImagePublication` type that uses [`Publication`](https://docs.gradle.org/current/javadoc/org/gradle/api/publish/Publication.html)
* Define a [`NamedDomainObjectFactory`](https://docs.gradle.org/current/javadoc/org/gradle/api/NamedDomainObjectFactory.html) implementation (like `DockerImagePublicationFactory`)
* Register the factory type by calling [`publications.registerFactory`](https://docs.gradle.org/current/javadoc/org/gradle/api/ExtensiblePolymorphicDomainObjectContainer.html)

When we tried to test against this, we found out that the `PublishingPlugin` had a model rule (the [previously mentioned one](https://github.com/gradle/gradle/blob/master/subprojects/publish/src/main/java/org/gradle/api/publish/plugins/PublishingPlugin.java#L90)). This required us to then implement [`ModuleVersionIdentifier`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ModuleVersionIdentifier.html) and [`ModuleIdentifier`](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ModuleIdentifier.html). It wasn't clear to us why these were needed or how they were used, but we were required to implement them to support the `PublicationInternal`.

**Comment by bmuschko** [comment]
@wolfs I had a look at the JPI plugin. It looks like the main artifact that should be published is a WAR file. The plugin applies the `War` plugin. Instead of creating a custom task type `Jpi` that extends from `War` (there's no point in doing so anyway) I'd just use the task named `war` that's already provided by the `War` plugin. If you do that then you can just refer to the component via the following code:

```
publishingExtension.publications {
    mavenJpi(MavenPublication) {
        components.web
    }
}
```

You can avoid the use of the internal APIs altogether. Correct me if I misunderstood the code or how the plugin works internally.

**Comment by bmuschko** [comment]
@mkobit Can we continue to discuss your concerns on the forum? This issue is increasingly becoming a "catch all" issue for publishing problems and question. Please open a post on the forum and link it here so I can comment.

**Comment by wolfs** [comment]
@bmuschko It is not building a war file but a jpi (jenkins plugin interface?). You can see the format definition here: https://wiki.jenkins-ci.org/display/JENKINS/Plugin+Structure.
The jpi/hpi format is somewhat similar to a war file, I suppose this is why the `Jpi` task started out to extend `War`. It is required to use the new publishing plugin, since this supports to have to artifacts without classifier which only differ by extension.See https://github.com/gradle/gradle/pull/341.
Can we continue this discussion on the [PR](https://github.com/jenkinsci/gradle-jpi-plugin/pull/84) for the gradle-jpi-plugin?

**Comment by bmuschko** [comment]
@wolfs I commented on the PR.

**Comment by bmuschko** [comment]
The [Jenkins PR](https://github.com/jenkinsci/gradle-jpi-plugin/pull/85) shows a way to solve the problem with an existing public API. At the moment there's no need to solve the initial problem reported with a new public API.

**Comment by wolfs** [comment]
Thanks @bmuschko!
