### ISSUE TITLE
JaCoCo execution data don't match since 6.5

### ISSUE THREAD

**Issue by koral--** [gradle/gradle#13614]
I'm the author of https://github.com/koral--/jacoco-gradle-testkit-plugin and I've recently received a bug report: https://github.com/koral--/jacoco-gradle-testkit-plugin/issues/17
However, I haven't found anything about breaking changes in 6.5 release notes https://docs.gradle.org/6.5/release-notes.html so I'm trying to report issue here as a regression.

### Expected Behavior
Coverage execution data should match.

### Current Behavior
Coverage execution data don't match.

### Context
Which version did this stop working with? - 6.5
Which version do you know it works? 6.4.1

### Steps to Reproduce 
1. Clone this project: https://github.com/jGleitz/broken-testkit-coverage
1. Run `./gradlew test jacocoTestReport`
1. Observe eg. `Execution data for class de/joshuagleitze/gradle/CoverageTestPlugin$apply$1 does not match.`
1. Change Gradle to 6.4.1
1. Repeat step 2.
1. Execution data mismatch has gone.

### Your Environment
Build scan URL:
With Gradle 6.5: https://scans.gradle.com/s/3ttg627m7xz36
With Gradle 6.4.1: https://scans.gradle.com/s/y6uqlwxwvtvem

**Comment by radarsh** [comment]
Can confirm this. Something was broken in Gradle 6.2 (or even before, not sure) that caused my Coveralls to report less coverage. Whatever it was, got fixed in Gradle 6.3 through 6.4.1 and now it's broken again in 6.5.

**Comment by CristianGM** [comment]
To make it even funnier, I have 2 plugins with the same basic setup, both using kotlin-dsl and this plugin, one of them works perfectly, the other suffers of this issue.

**Comment by CristianGM** [comment]
On 6.5 I did a contribution that could be near to this issue, I did add @Generated to all the generated files in kotlin-dsl (mostly accessors), so JaCoCo doesn't report coverage for those files anymore.
I don't imagine how that could be the issue, but, I had to mention it.

**Comment by adammurdoch** [comment]
This problem is happening because Gradle now applies some instrumentation to plugin classes, to help implement configuration caching, and this means the Jacoco agent will instrument the bytecode that has been modified by Gradle and this does not match the bytecode that the Jacoco report uses.

For 6.6-RC1, we've just added a work around, where we disable the instrumentation when a Java agent is applied to a TestKit build, but we will need to fix this properly at some point.

From our side, perhaps the most reliable fix would for the 'jacoco-gradle-testkit' plugin to use the Jacoco offline instrumentation to instrument the classes under test prior to injecting them into the TestKit build. For example, the plugin might add a task that takes the test classes and instruments them, and then wire these in to the test source set so that they are used by the test task. Is this a possibility? If not, we can consider the options we have for fixing this in some way on the TestKit side.

**Comment by koral--** [comment]
@adammurdoch could you elaborate on
> use the Jacoco offline instrumentation to instrument the classes under test prior to injecting them into the TestKit build. For example, the plugin might add a task that takes the test classes and instruments them, and then wire these in to the test source set so that they are used by the test task.

or post a link to some documentation?

**Comment by jGleitz** [comment]
This bug does not happen with Gradle 6.6 RC 4 anymore (verified with https://github.com/jGleitz/broken-testkit-coverage).

Thanks to @mateuszkwiecinski  for pointing that out with her/his commit messages.

**Comment by jGleitz** [comment]
@adammurdoch: could Gradle implement offline instrumentation in the Jacoco plugin (https://github.com/gradle/gradle/issues/2429) before removing the workaround that is present in version 6.6?

This way, users that need it could easily adapt to the changes by Gradle. `jacoco-gradle-testkit-plugin ` could enable offline instrumentation without also having to maintain the code that enables offline instrumentation (via Ant or the like).

**Comment by jjohannes** [comment]
Closing as the issue has been fixed for 6.6 and potential follow up work is captured in #2429.
