### ISSUE TITLE
Scala incremental compilation should be part of build outputs

### ISSUE THREAD

**Issue by alpar-t** [gradle/gradle#13719]
When using a remote build cache Gradle downloads the class files from the cache if there's no change, 
but substantially does a full re-compile, even if there's only a small one class change.

Note that this might be conditioned by sbt/zinc#707 - I'm not sure the analysis file is portable. 

### Expected Behavior
The zinc analysis file is part of the build outputs, so it too is downloaded from the build cache so on the next run we get incremental compilation.  

### Current Behavior
The zinc analysis file is not considered part of build outputs, one can see 
'Zinc is doing a full recompile since the analysis file doesn't exist' in the info log.
This causes zinc to do a full re-compile even trough all the class files are present and a single class changed.

### Context
We switched to building a large multi project Scala project with Gradle and have been mostly happy with it, but ran into some challenges for local development in small iterations of changing a few lines and running tests. We are working around these by using bloop and the bloop Gradle integration, but we'd rather use a single build tool with a single IDE setup. We use IntelliJ so our IDE builds default to Gradle too.

**Comment by ijuma** [comment]
Zinc 1.4.0 has now been released.

**Comment by alpar-t** [comment]
I think this is still relevant

**Comment by alpar-t** [comment]
@wolfs can we keep this open for the community please? I think it's still relevant.

**Comment by q-willboulter** [comment]
Hey @alpar-t I've been thinking about this too and considering implementing a custom solution at work but I'm not sure that it fits well with the way caching works in gradle because I don't think zincs inputs should be cached by the same set of "@inputs" as the compilation task. 

If I add a new class and recompile locally, zinc takes advantage of the existing class files and zinc outputs and works out what needs to be done incrementally given the source changes. This means that the previous zinc outputs that it's using are useful even though the source of the project has changed - i.e. the outputs shouldn't be cached using the source files as an @Input or else the cache fingerprint would be updated and it would mark them as stale and not use them. 

When considering how I'd try and do this in a custom way I was thinking along the lines of caching a projects zinc and class files outputs purely by the git branch or something simple like that. Then, given a fresh workspace it would pre download the "previous" classes and zinc outputs regardless of whether sources have changed, and use them to incrementally compile on top of. This seems like it could be fraught especially if the cached outputs are significantly diverged from the local sources though.

If you're still interested in this problem, I'd love to hear any thoughts you have, especially if you think this can be properly integrated with the way gradle caching works. I tried putting a post `compileScala` task in that only caches based on the git branch but I don't think gradle likes that it needs to cache build/classes one way for the `compileScala` task with strict fingerprinting of everything and another way to store a zinc usable version. I also don't see a way to create a pre compile task to pull the zinc outputs down since it would have to be the same task as the post compile task in order to use it's cache and I don't think you can have the same task twice on a project without creating a cyclic dependency.
