### ISSUE TITLE
Gradle 3.4-rc-1+ handling of transative dependencies is non-passive

### ISSUE THREAD

**Issue by rwinch** [gradle/gradle#1371]
### Expected Behavior

Gradle 3.4-rc-1+ transitive dependencies should not be included in projects that consume them. There is a complete project in the [Steps to Reproduce (for bugs)]()

### Current Behavior

Gradle 3.4-rc-1+ the transitive dependencies are included in projects that consume them.

### Context

The issue has impacted the spring-framework trying to update to Gradle 3.4. Specifically, we have a project named `spring-test` that depends on `spring-web`. The `spring-web` module has an optional dependency on Jackson.

When running a test in `spring-test` with Gradle 3.3 Jackson is not found on the classpath, so JAXB is used to marshal some XML in one way. When running a test in  `spring-test` with Gradle 3.4-rc-1+ Jackson is found on the classpath, so Jackson is used to marshal some XML in a slightly different way causing the test to fail.

In the real world we are experiencing this using the [Spring propdeps plugin](https://github.com/spring-gradle-plugins/propdeps-plugin). The goal is that this plugin will be able to provide a runtime only dependency using the 'optional' scope. At minimum I would expect the plugin to work for any Gradle 3.x version.

### Steps to Reproduce (for bugs)

You can see the problem highlighted in https://github.com/rwinch/gradle-optional-bug The project has no external dependencies to simplify things. In the real world, we would like the  [Spring propdeps plugin](https://github.com/spring-gradle-plugins/propdeps-plugin) to work for Gradle 3.x (i.e. I prefer to avoid a workaround that only works with Gradle 3.4+).

### Your Environment

* Gradle 3.3 works 
* Gradle 3.4-rc-1 and 3.4-rc-2 fail

**Comment by eriwen** [comment]
@rwinch Thanks for the awesomely written issue. We'll follow up on this before the next RC in one way or another.

**Comment by oehme** [comment]
If I understand the goal of `optional`, then you want those dependencies to

- appear on the compile classpath of the declaring project
- appear on the runtime classpath of the declaring project
- not appear in downstream projects

This can now be modeled properly:

```
configurations {
  optional
  compileClasspath.extendsFrom(optional)
  runtimeClasspath.extendsFrom(optional)
  testCompileClasspath.extendsFrom(optional)
  testRuntimeClasspath.extendsFrom(optional)
}

//no exclude rules or the like needed
```

Filtering them out of `default` is a brittle workaround, since downstream projects are free to consume other configurations. This is what happens with Gradle 3.4, which now consumes `apiElements` and `runtimeElements`, depending on what the downstream project wants to do.

So the solution would be to change the plugin to the above behavior for Gradle >= 3.4 and remove the old behavior once you no longer support versions <3.4.

**Comment by oehme** [comment]
Actually, there is another way to do this in a way that is compatible with all Gradle versions and automatically applies to all custom SourceSets created by users (if that's what you want):

```
configurations {
  optional
}

sourceSets.all {
  compileClasspath += configurations.optional
  runtimeClasspath += configurations.optional
}
```

You'd still need the `default` filtering for Gradle <3.4, but could remove that for >=3.4

**Comment by rwinch** [comment]
@oehme Thanks for the quick suggestions!

Is Gradle going to remain non-passive in this regard or is this just a workaround?

**Comment by oehme** [comment]
Sorry I don't know what you mean by non-passive.

**Comment by rwinch** [comment]
Once again thank you for the fast response @oehme!

The approach I demonstrated has worked for a very long time. Now in Gradle 3.4 it does not work. This seems like a non-passive change to me.

Will Gradle fix this in the next release or will I be required to make changes? I'm trying to determine if what you have provided is going to be required or if it is a workaround until 3.4-rc-3 comes out.

**Comment by oehme** [comment]
This is working as intended. The `default` configuration is just what the name implies - the default. There is no guarantee that downstream projects will consume it. It just so happened that they mostly did in the past.

The way the plugin currently wires up the optional dependencies is not reflecting what you actually want it to do. It lets `compile` extend from `optional`, which basically means "anyone compiling against me should also see optional stuff". What you really want is "I want to see these dependencies when compiling and running, but no one else should".

The solution below is a refinement of my proposal above:

```
[sourceSets.main, sourceSets.test].each {
  compileClasspath += configurations.optional
  runtimeClasspath += configurations.optional
}
```

It only applies to the standard main and test SourceSets instead of every SourceSet (which might not be what users want). I also thought about the excludes again and they are not necessary for any Gradle version if you go with the code above. Thus making your plugin much simpler and compatible with all versions.

**Comment by rwinch** [comment]
@oehme Thank you for your explanation.

Unfortunately modifying the sourceSets does not work importing into Eclipse with Buildship or `gradle eclipse`. It is possible I will need to modify the Eclipse setup as well, but I haven't looked into this. I have yet to check if this is going to work with the Maven pom integration we have as well.

It is worth noting that the first solution does appear to work with the Eclipse import.

PS: For those looking at this, I am guessing the modified code should be:

```groovy
[sourceSets.main, sourceSets.test].each { sourceSet ->
  sourceSet.compileClasspath += configurations.optional
  sourceSet.runtimeClasspath += configurations.optional
}
```

**Comment by rwinch** [comment]
Thanks again for your help. My initial tests show that this may be doing the trick. I need to do some more thorough testing, but have to run for now. I will report back tomorrow after I have tested more thoroughly. 

My configuration (I like the .all better for the moment as I also have integration tests)

```groovy
configurations {
	optional
}

sourceSets.all {
	compileClasspath += configurations.optional
	runtimeClasspath += configurations.optional
}

eclipse {
	classpath {
		plusConfigurations += [configurations.optional]
	}
}
```

**Comment by oehme** [comment]
Sorry I went all Ninja on you earlier. I edited my post and recommended using my first proposal (using the `extendsFrom` relationship) instead of using `SourceSet.compileClasspath` for exactly this reason. It's not just the `eclipse` plugin, but also `idea` and probably many others that don't pick up changes to `SourceSet.compileClasspath`.

You can also make my first proposal work for all sourceSets if that is what you want to do. The name of the configurations is available on the `SourceSet` interface (if you are compiling against the latest). Otherwise you can compute it as `${sourceSetName}CompileClasspath` (except for `main`, where it is just `compileClasspath`.

**Comment by rwinch** [comment]
> Sorry I went all Ninja on you earlier. 

Not a problem at all. I am very grateful for all your help!

It does appear that built in IntelliJ / gradle import is working with the `sourceSets` with no changes and the Eclipse import is also working.

I believe using `compileClasspath.extendsFrom(optional)`  worked for 3.4.x. However, it sounded as though it would not work in < 3.4.x. Is that accurate or did I miss something? It is important to me that I can support Gradle 3.x with the same solution.

Things are going to be a bit busy today, but I am going to try and update the code to the new suggestion and test by the end of the day. 

Thanks again!

**Comment by oehme** [comment]
> I believe using compileClasspath.extendsFrom(optional) worked for 3.4.x. However, it sounded as though it would not work in < 3.4.x. Is that accurate or did I miss something? It is important to me that I can support Gradle 3.x with the same solution.

I think it would be better to use the simpler solution in the future (which is `compileClasspath.extendsFrom(optional)`) and keep the old solutions for older versions. You can then delete that code once you no longer support versions <3.4.

Using this solution you are better off in the long term because once you drop support for <3.4 you:

- no longer need eclipse mapping
- no longer need idea mapping
- no longer need JavaDoc task customization

You could of course also do a hybrid approach: Go with the `SourceSets` solution today and clean up your code with the `extendsFrom` solution in the future.

**Comment by rwinch** [comment]
@oehme Thanks for the additional information!

**Comment by oehme** [comment]
Is this issue solved from your point of view?

**Comment by rwinch** [comment]
I needed to verify the other versions of Gradle. I was able to check that it works and so this is solved.

Thanks again for your help!
