### ISSUE TITLE
JDK16 support in Gradle

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#13774]
We have an [experimental pipeline](https://builds.gradle.org/viewQueued.html?itemId=36626140) set up that tests Gradle against an early access release of JDK16.

So far the Groovy build scripts are failing to compile using JDK16. The errors look to be coming from the asm library that is bundled in our groovy-all distribution.
[asm](https://asm.ow2.io/versions.html) library does not yet support JDK16. From this [commit](https://gitlab.ow2.org/asm/asm/-/commit/a024b77cfdb022f400fdae4a540d3d3514b472d7) it looks like the support is being worked on and will come out with version 9.
We should keep an eye for the release and probably coordinate with Groovy team to see if they could incorporate the update in the next iteration of Groovy 2.5

This is the first issue that needs to be overcome to get visibility on other potential breakages.

**Comment by rieske** [comment]
A beta of asm version 9 is now available: https://asm.ow2.io/versions.html

**Comment by dreis2211** [comment]
@rieske Since September ASM 9 should be available

**Comment by msgilligan** [comment]
Can JDK 16 support be added to Gradle 6.x?

**Comment by ljacomet** [comment]
See #15538 for existing problem with Java compilation

**Comment by big-guy** [comment]
We're waiting for the Groovy 3 upgrade #15566

**Comment by tbroyer** [comment]
Fwiw, besides Groovy 3 (already merged and available in 7.0-M2 AFAICT), there are other issues due to https://openjdk.java.net/jeps/396:
* using ProjectBuilder: https://scans.gradle.com/s/yzcxrlwrb5ote/tests/:test/net.ltgt.gradle.errorprone.ErrorProneOptionsTest/classMethod
* using configuration-cache: https://scans.gradle.com/s/yzcxrlwrb5ote/tests/:test/net.ltgt.gradle.errorprone.ErrorPronePluginIntegrationTest/is%20configuration-cache%20friendly (I use an AtomicBoolean in gradle-errorprone-plugin)

I was able to workaround the first one by passing `--illegal-access=permit` in the `test` task's `jvmArgs`: https://scans.gradle.com/s/dy7knrif4vt3w/tests (other failures besides "is configuration-cache friendly" are currently expected)
