### ISSUE TITLE
Supports build scan for build using source dependencies

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#13795]
### Expected Behavior

Produce a build scan when using source dependencies.

### Current Behavior

No build scan is produced and the following error message is shown: `This build uses Gradle features that are incompatible with build scans (code: late-load-build-op).`

### Context

Build scan is awesome and consuming project from source is also pretty rad, having both is amazing. Instead, we need to work around by publishing binary artifacts to be consumed by the other projects. Those are unnecessary steps for projects evolving rapidly side-by-side.

**Comment by lacasseio** [comment]
Any plan on supporting build scan for source dependencies?

**Comment by ldaley** [comment]
@lacasseio no concrete plans.

@gradle/core what is the status and plans for the source dependencies feature?

**Comment by jjohannes** [comment]
The status of the source dependencies feature is that it works as far as it does and that we won't break it. However it is still undocumented/experimental. There are no plans to work on it more at the moment.

However, under the hood these are all composite builds. And we are generally improving composite build support and will likely continue work on this in the coming month. The underlying problem here seems to be that the late addition of a build to the composite does not work well with build scans right now. It might be that we need to look into this for other reasons than source dependencies. And that this might be fixed as a "by-product".
