### ISSUE TITLE
Only watch project directory by default

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#13887]
This is the first step towards https://github.com/gradle/gradle/issues/13598.

We want to limit the number of hierarchies to watch on macOS, because there is a low limit of a few hundred hierarchies that we can watch at the same time.

The idea is to only watch the project root at first, and discard anything in the VFS at the end of the build that is not a) under the project root directory, or b) in the global cache directory (which is not watched but it's additive only, so we don't have to).

---
cc: @gradle/execution

**Comment by wolfs** [comment]
This is the current plan:
- Only watch locations which are within the root build dir
- If a new root build dir comes in, remove everything in the root build dir from the VFS which we are not watching. We should do this since we don't know if the data at that location is still current.
- At the end of the build, remove everything from the VFS which we aren't watching or ignoring (global caches).

**Comment by wolfs** [comment]
Maybe we should fail the build when we detect some state in the VFS for a directory which we are about to be watching.

**Comment by wolfs** [comment]
I wonder what we should do for missing project directories. I suppose we should watch the first existing parent until something appears in the directory.

**Comment by wolfs** [comment]
I wonder what we watch do for source dependencies. It seems like the checkout directories are not within Gradle's cache directories.
