### ISSUE TITLE
Use fully paths when displaying JacocoCoverageVerification errors

### ISSUE THREAD

**Issue by digitalbuddha** [gradle/gradle#13896]
Hi folks, we have a multi module project with modules that look like:

```
featurea:presenter
featurea:repository
featureb:presenter
```
When running the verification task at a bundle granularity we get messages such as:
```
[ant:jacocoReport] Rule violated for bundle presenter: lines covered ratio is 0.69, but expected minimum is 0.80
```

From that message it is difficult to see which `presenter` module failed coverage. Would it be possible to include the path or an api where we can get a list of all failing projects?

Thank you kindly

**Comment by digitalbuddha** [comment]
I'd be happy to contribute a fix if either of my suggestions above are desirable

**Comment by big-guy** [comment]
We don't have a lot of control over that message, but if you'd like to take a stab at making it better I would start here:

https://github.com/gradle/gradle/blob/e08fbe020f23f177cd7117b9f6e477cc2475c0ce/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoCoverageVerification.java#L78

This should be using the display name for the project since it's used in error messages.  That'll include the full path information like you'd see in other Gradle messages.

After that, you could run these tests to see what falls out:
https://github.com/gradle/gradle/blob/e1ceaa3f860709f8245a1583f0f2e7cf6aa80a29/subprojects/jacoco/src/integTest/groovy/org/gradle/testing/jacoco/plugins/rules/JacocoPluginCoverageVerificationIntegrationTest.groovy

We'd also want to add a test that uses subprojects like your build and verify that we're happy with those messages.

Here are our [contributing guidelines](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) if you haven't seen them already.

**Comment by digitalbuddha** [comment]
Got it!
Currently I have been subclassing the task and catching the exception. That gave me all the control I needed. 
```
open class DbxJacocoCoverageVerification : JacocoCoverageVerification() {
    @TaskAction
    override fun check() {
        try {
            super.check()
        } catch (e: GradleException) {
            val errorMessage = e.message!!
            verificationBuilder.append(" \"${project.path}\" to ${getActualCoverage(errorMessage)}, \n")
            JacocoVerificationReporter.addFailure(
                project.path,
                getActualCoverage(errorMessage),
                getExpectedCoverage(errorMessage)
            )
        }
    }
}
```
I'd still love to contribute the rename of the error message, question I have is any reason to use DisplayName rather than project.path and vice versa?

**Comment by big-guy** [comment]
`project.path` will look weird for the root project (just `:`) and display name is likely to look better.
