### ISSUE TITLE
Gradle ran out of memory with 4GB max heap

### ISSUE THREAD

**Issue by DSteve595** [gradle/gradle#13902]
In an Android build, invoked by Android Studio, my daemon ran out of memory towards the end of the build. The build spent a huge amount of time in GC. I wouldn't expect this with 4GB heap and the Kotlin compiler daemon in a separate process.

Also reported this to Android Studio's issue tracker [here](https://issuetracker.google.com/issues/161826152).

### Your Environment
Build scan URL: https://scans.gradle.com/s/l32go6q5veasu

Heap dump: https://drive.google.com/file/d/1DNt4rVm7elTxJkK83GrCFSwBjsCVX5dH/view?usp=sharing

Another heap dump after `GC.run`: https://drive.google.com/file/d/1QCrMjkRirAGWFWsJSkWyfv3HZXJY46vt/view?usp=sharing

Info from Android Studio feedback tool:
>Build: AI-201.7846.76.42.6682321, 202007151459,
>AI-201.7846.76.42.6682321, JRE 1.8.0_242-release-1644-b01x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080
>AS: 4.2 Canary 5; Kotlin plugin: 1.4-M3-release-Studio4.1-1; Android Gradle Plugin: 4.0.0; Gradle: 6.3; NDK: from local.properties: (not specified), latest from SDK: (not found); LLDB: pinned revision 3.1 not found, latest from SDK: (package not found); CMake: from local.properties: (not specified), latest from SDK: 3.10.2, from PATH: (not found)

**Comment by oehme** [comment]
There are several `Gradle` instances held transitively by a metadata rule of the Android plugin. I'm not sure whether the problem is in the Android plugin's usage of the API or whether Gradle passed in the wrong `ObjectFactory` (one that references the whole Project state, which then cannot be released).

![metadata_rules_leak](https://user-images.githubusercontent.com/1191797/88455609-02b3f680-ce77-11ea-8838-92bd8aa2fb24.png)

**Comment by DSteve595** [comment]
Anything I can do to help narrow it down?

**Comment by oehme** [comment]
No, the above should be enough for the Gradle and/or Android team to fix it.

**Comment by gavra0** [comment]
I was able to reproduce with 6.5 and 6.6-rc-3, but this issue is gone with 6.5.1. 

@DSteve595 Can you please update your Gradle version to 6.5.1 and try it out?

Using [samples_variant_rule.zip](https://github.com/gradle/gradle/files/4987486/samples_variant_rule.zip) should produce this issue. You need to open this project in Android Studio `4.2.0-alpha05` and trigger sync (`ctrl + shift + A`, search for "Sync Project with Gradle files").

**Comment by gavra0** [comment]
Ignore my previous comment, it seems that IDE was not actually running sync and it was using cached state. That's why leak did not show up on some heap dumps.

The issue is in Android Studio implementation of `ComponentMetadataRule` where `ComponentMetadataContext.details.addVariant` accepts an action which captures `ObjectFactory` injected in the rule. Feel free to close this issue, we can track this in https://issuetracker.google.com/161826152.

**Comment by DSteve595** [comment]
🎉
