### ISSUE TITLE
Composite build plugin dependencies can require user projects to add repositories to their buildscript block

### ISSUE THREAD

**Issue by MrSlateZB** [gradle/gradle#13916]
We are using a composite build to provide a plugin to our project. Unfortunately, if the plugin uses a dependency that requires a repository other than https://plugins.gradle.org/m2/, projects using that plugin will fail to build unless we add that repository to the project's buildscript repository set as well. 

### Expected Behavior
The plugin would not require user projects to add repositories its dependencies require to the buildscript block. 

### Current Behavior
The project using the plugin will fail to build until the repository is provided in the 

### Context
I am trying to use a plugin we develop locally without requiring extra buildscript dependencies whenever our plugin requires a dependency not present at https://plugins.gradle.org/m2/. 

### Steps to Reproduce 
The following git repo exhibits the behavior. 
https://github.com/MrSlateZB/composite-build-plugin-dependency-behavior

### Your Environment
Build scan URL: https://gradle.com/s/nor2jsbgodyko

**Comment by big-guy** [comment]
This is intentional as we don't want plugins to be able to add repositories that can be used by plugin resolution as part of plugin application, but I can understand it's not what you want.

There are a few options:
1. Make it so the dependencies that come from another repository are resolved later (e.g., as a dependency in the project).
2. Bundle the dependency in your plugin.
3. Document that the plugin requires another repository definition.

This isn't specific to composite builds or plugins.  All projects should usually have the same set of repositories.

**Comment by MrSlateZB** [comment]
I think I'm confused by "plugins to be able to add repositories that can be used by plugin resolution". My understanding of the composite build is that my plugins binary will be exported to my main project to be used. Is that not whats happening here? Or its happening but the plugin doesn't have the dependent jar (and thats what you mean by 2)?

Just to be clear, you are saying that if a plugin is using a dependency that has no effect on the end user of the plugin, we leak that abstraction such that any user of the plugin needs to know about it and add it right?

Is there a resource you can point me to that would tell me how to do 1 or 2? My example plugin is the standard composite build example if you could hopefully point me in the right direction.
