### ISSUE TITLE
Cache remote build cache entries locally

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#13928]
### Expected Behavior

Gradle should cache entries locally in case of successful fetch from the remote cache even in case the local build cache is disabled.

I guess local build cache should have `cacheRemoteEntries=true` option which would work even in case local build cache is disabled.

### Current Behavior

Gradle downloads remote cache entries every time, which might result in a significant traffic increase for the developers.

### Context

I'm configuring a remote build cache for Apache Calcite, and turns out "cached build" downloads 20MiB from the cache: https://scans.gradle.com/s/qtbs5qpujlspu/performance/buildCache?cacheDetails=WyJyZW1vdGUtSGl0Il0#remote-hit
It is OK for CI servers which are stateless anyway.

However, it is sad to download remote entries every time from the developer's point of view.

**Comment by wolfs** [comment]
@vlsi Thank you for opening the feature request!

If the local build cache is enabled, Gradle will download artifacts from the remote build cache to the local build cache, so it doesn't need to download it the next time. What is your reason for disabling the local build cache?

**Comment by vlsi** [comment]
@wolf, as I read Gradle recommendations, it strongly suggests that build caching should be used only for `clean` builds to avoid unexpected leftovers being cached.

For instance: https://guides.gradle.org/using-build-cache/#share_results_between_developers

>If you want to share task output from incremental builds, i.e. non-clean builds, you have to make sure that all cacheable tasks are properly configured and implemented to deal with stale output. 

Then there's a possibility to alter files as the build is running:


https://guides.gradle.org/using-build-cache/#share_results_between_developers

>Allowing developers to upload their results to a shared cache is possible, but not recommended. **Developers can make changes to task inputs or outputs while the task is executing**. They can do this unintentionally and without noticing, for example by making changes in their IDEs while a build is running. Currently, Gradle has no good way to defend against these changes, and will simply cache whatever is in the output directory once the task is finished

AFAIK that means Gradle could cache invalid results into my local build cache if I edit files while the build is running. Is my understanding correct?

Note: even though I am aware of this behavior, however, it might be tricky to introduce local build cache to a large team which do not always know what Gradle is :)

That is why I plan to introduce build cache step by step. The first step seems to use read-only configuration everywhere except CI agent which is known to execute from a clean checkout.

**Comment by wolfs** [comment]
When running a build, there is a small window between determining the inputs to a task and actually running the task. If an input change happens in that small window, then the build cache key is for the inputs before the change, while the outputs (on disk or in the build cache) are for the inputs after the change. If you re-run the build, then the task will re-execute (the inputs changed), and the build cache entry will be correct.

Since the window for making the change is very small, it is not very probable for it to happen. And even if it happens, it is not a big deal since the next build will re-run the task anyway. As long as the build cache entry is not shared between developers, there is not much to worry about.

Having said that, we could make the change to store artifacts from the remote cache in the local cache even when `push = false` on the local cache. Note that developers won't benefit too much from that setting, since they probably will have each remote cache it only once, as long as they don't go much back and forth between changes.

**Comment by vlsi** [comment]
Thanks for the clarification. Let me see how it works with local cache always enabled.
