### ISSUE TITLE
How do I compile multiple sourceSets together 6.5 v

### ISSUE THREAD

**Issue by BoopathySrinivasan** [gradle/gradle#14018]
Hi,
I new to Gradle and I'm facing issues while compiling multiple source sets.

I have generated source code(.java classes) under the build directory. 
So now how can I include both source set('\build\generated' and 'src/main/java') while running compileJava task?

The way I did the configuration like below in build script

sourceSets {
    main {
         java {
            srcDirs = [project.buildDir.absolutePath]
         }
    }
}

but it doesn't include the code under 'src/main/java' for compilation

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

By using `srcDirs` and passing a list, you overwrite any previous value. Instead you should add a location by using `srcDir` (note the missing `s`). See [the documentation](https://docs.gradle.org/6.5.1/userguide/building_java_projects.html#sec:custom_java_source_set_paths), in particular example 4
