### ISSUE TITLE
Task configuration avoidance produced unhelpful nag messages about deprecations

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#14034]
Full story is at: https://youtrack.jetbrains.com/issue/KT-40865
Shortly summarized, there is a depreaction nag but he stacktrace only shows Gradle frames.
There is no trace of where the actual problem is.
I suspect task configuration avoidance causing this.

**Comment by big-guy** [comment]
Thanks @Vampire 

This isn't related to configuration avoidance, but it's a deprecation for tasks that directly extend `AbstractTask` (an internal type) instead of `DefaultTask`.  

The task needs to be changed to extend `DefaultTask` here: https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/js/dukat/DukatTask.kt#L19

I pushed a change to include more information about which type and task has this problem, since we don't keep track of where the task was originally registered.

**Comment by Vampire** [comment]
You got me wrong I think.
What I complained here is not the deprecation, but that the message has no trace where to complain to but only showed Gradle stack frames.
And that (the missing information of where or who registered the task or what type it is) I suspected is due to task configuration avoidance.
Getting rid of the deprecated usage I already reported to JetBrains in the linked issue.
But what I got from your message, you actually fixed what I complained about even if not getting me right. :-D
I had to use the debugger to find out whom to blame for that deprecation. :-)
