### ISSUE TITLE
Consider discouraging allprojects/subprojects for cross-project configuration

### ISSUE THREAD

**Issue by rieske** [gradle/gradle#14074]

**Comment by lacasseio** [comment]
Could the Gradle team expand on this issue? I can't quite see a clear cut between completely discouraging (what this issue seems to be focusing) vs discouraging in some cases (my current understanding of the issue). That would be very helpful to ensure a meaningful discussion.

**Comment by big-guy** [comment]
It's specifically to address the pattern of using `allprojects {}` or `subprojects {}` to do cross-configuration of other projects since this has a few downsides. 

- Projects can't be configured in parallel if one may configure subprojects or all projects
- Gradle needs to configure all projects, even if only one is needed since other projects may configure allprojects
- IDE support is difficult since the `allprojects` or `subprojects` blocks may see a completely different set of available extensions
- Project configuration is spread out over several places (the project's build script and possibly any parent build scripts)
- It encourages "reaching into" other projects

We're not looking at cases where `allprojects` or `subprojects` is used at task execution time right now (although, that might be discouraged for separate reasons).

**Comment by runningcode** [comment]
Not sure if this is the right place to comment, but what's the best way of doing something like this without using `allprojects`?
```
allprojects {
    repositories {
        mavenCentral()
    }
}
```

**Comment by melix** [comment]
I think this is the missing piece, basically, and for me one reason to keep the "root" project as a "cross-project configuration" utility. I'm not convinced we can/should deprecate `allprojects`/`subprojects` yet because we don't have good conveniences to cross-configure projects like that. Having to apply a plugin to all projects defeats the intent IMO.

**Comment by lacasseio** [comment]
The example shown is just one such example of cross-project configuration. There's also configuring default when a plugin is applied in all- or sub-projects, aligning the version/group of all projects, etc. Could the `allprojects`/`subprojects` be isolated to be just a way to inject build configuration? It would avoid the over-reaching problem.

**Comment by big-guy** [comment]
We've updated the docs to not encourage this, but we'll revisit this if we need a stronger discourage/deprecation/etc message

**Comment by vlsi** [comment]
A note for someone finding the issue laste: `allprojects { repositories {...}}` can now be configured in `settings.gradle.kts` via `dependencyResolutionManagement {...}`, see https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration

**Comment by realdadfish** [comment]
A workaround for an "all-project" / "sub-project" configuration for me is to create a custom plugin and register a plugin extension only when this plugin is applied to the root project. Then, in the submodule projects, I retrieve the rootProject's extension and read out the configuration from there to apply it to the specific project.
