### ISSUE TITLE
make implemention transtive true force

### ISSUE THREAD

**Issue by jiqimaogou** [gradle/gradle#14090]
hello, I hello a project(:A) and project(:A) api project(:B), but the project(:B) implementaion project(:C), I can not modify the project(:B), how do I make to let project(:A) references project(:C)'s class to make compile sucess?

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

Simply add an implementation dependency to `:C` in `:A`
