### ISSUE TITLE
Investigate intermittent OOM errors on master

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1413]
Several engineers are getting errors like this on master:

```
Expiring Daemon because JVM Tenured space is exhausted
Failed to execute org.gradle.cache.internal.AsyncCacheAccessDecoratedCache$2@70553f6d.
java.lang.OutOfMemoryError: Java heap space
> Building 95% > :testKit:checkstyleTest
```

and like this:

```
Expiring Daemon because JVM Tenured space is exhausted
Daemon will be stopped at the end of the build after running out of JVM memory
```

### Context
This was likely introduced in the last week. Reports began Feb 8th. It is frequent enough to be considered a major issue we must fix very soon.

### Steps to Reproduce (for bugs)
This issue is intermittent, but seems to be related to use of either the Daemon or the new workers architecture. Grab the latest nightly and run some checkstyle tasks.

### Your Environment
Gradle 3.5 nightly, macOS. Build scan pending.

**Comment by eriwen** [comment]
@bmuschko Could you please characterize your investigation results on this issue here?

**Comment by bmuschko** [comment]
From what I could see the following two classes kept growing in the daemon JVM with every run of the Gradle build:

- `org.gradle.api.internal.changedetection.state.IndexNormalizedFileSnapshot` - (after first build: 1,019,715 instances)
- `org.gradle.api.internal.changedetection.state.FileHashSnapshot`- (after first build: 924,604 instances)

I inspected the daemon VM with VisualVM. Triggering GC did not reduce the number of instances which might indicate a memory leak.

**Comment by ghale** [comment]
What I've done is run `clean quickCheck` with a profiler attached and attempted to soak it for a number of builds to see if I could identify any sort of leakage.  I couldn't reproduce the problem by running just a few tasks - it seems like running a lot of tasks (like what quickCheck does) is what triggers the issue. 

With current master and the default heap size (1024m) the daemon runs low on memory reliably on even the first build (i.e. it slows to a crawl, garbage collection runs continuously, we eventually get a Daemon expiration, etc).  Looking at the heap, I see roughly 50% tied up in cache, mostly in the two classes @bmuschko references above.  There were about 1.5 million instances of `FileHashSnapshot` and 1.9 million instances of `IndexedNormalizedFileSnapshot` for about 82mb.  The tenured heap jumped up to its maximum size and stayed there.  At this heap size, the build was just crawling, so I didn't wait for an OOM, I just got a heap dump and stopped it rather than waiting for it to finish.  It took so long to run, I didn't bother trying to do repeated runs.

If I bump the heap by only 128m (-Xmx1152m) the builds complete in a reasonable amount of time. I ran 6 builds with this setting and the performance was quite a bit better and I didn't get a daemon expiration or anything.  There was still a little bit of GC and I didn't see any shrinkage in the tenured space (it went up to its maximum and stayed there).  After the first build, there were about 1.7 million instances of `FileHashSnapshot` and 2 million instances of `IndexedNormalizedFileSnapshot` for a total size of about 90mb.  After the 6 builds, there were about 1.6 million instances of `FileHashSnapshot` and 2 million instances of `IndexedNormalizedFileSnapshot` for a total of about 90mb.  So, we actually got a little bit of _reduction_ here in the number of objects, possibly due to cache ejection, but it didn't have a dramatic effect on their total footprint.  An example build scan: https://e.grdev.net/s/sdwd4vbul5rys.

When I bumped the heap by 512m (-Xmx1536m) the builds ran quite a bit better (speed-wise) and I observed the tenured heap growing and shrinking more normally (usually getting up to about 1GB and then dropping down to 820MB with a major GC).  After the first build, we ended up with 1.7 million instances of `FileHashSnapshot` and 2 million instances of `IndexedNormalizedFileSnapshot` for a total of about 92mb.  After 10 builds at this heap size, we ended up with about 1.9 million instances of `FileHashSnapshot` and 2.2 million instances of `IndexedNormalizedFileHashSnapshot` for a total of 100mb.  An example build scan: https://e.grdev.net/s/wh4q53s5uzlwq.

I then switched to release and set the wrapper to 3.4-rc-3.  First of all, I was able to run the `clean quickCheck` builds with the current 1024m heap size without any debilitating performance impacts.  There was a good bit of garbage collection, but the builds ran reasonably well.  However, the heap looked very different.  First of all, there were many, many fewer instances of the snapshot classes.  After the first build there were 371,282 `FileHashSnapshot` and 294,826 `IndexedNormalizedFileHashSnapshot` for a total of about 16mb.  After the 10th build, there were 352,021 `FileHashSnapshot` and 281,955 `IndexedNormalizedFileHashSnapshot` for about 15mb.  So, like the 3.5/1152mb case, the total number of objects actually went down (possibly due to cache ejection).  An example build scan: https://e.grdev.net/s/yk5fgmjumrqao.

I saw slightly better performance when I went up to 1536m heap with 3.4-rc-3.  Basically, no garbage collection to speak of.  In fact, much of the time I did not see the heap fully expanded and there was definite heap shrinkage in between builds.  After the first build, there were 403,724 `FileHashSnapshot` and 319,232 `IndexedNormalizedFileSnapshot` objects for a total of about 17mb.  After the 10th build, there were   
470,714 `FileHashSnapshot` and 389,138 `IndexedNormalizedFileSnapshot` objects for about 20mb.  I'm guessing we don't see the same reduction in objects because the cache is larger and they aren't being ejected (pure speculation).  Example build scan:  https://e.grdev.net/s/fd5j7v4ldgme6

So, I don't think we have a problem with 3.4 - whatever introduced this issue didn't show up until 3.5.  And I don't think we have a leak, or at least if we have a leak it's a secondary issue.  The primary cause is that we are simply using more memory with 3.5.  What's interesting is that the footprint of the mentioned file snapshot objects differs between the two releases by about 80mb, which is roughly what we have to add to the 3.5 heap (128mb) to avoid the low heap situation.  It's also interesting to point out that looking at just the run times, the performance of the 3.4/1024mb build is roughly the same as the 3.5/1152mb heap (around 15min).  I think we were right on the edge of using too much heap (and starting to feel the effects a little bit) with 3.4 and this increase in memory usage in 3.5 has pushed us over.

Lastly, I did an experiment where I ran `quickCheck` on the release branch but using the latest 3.5 wrapper.    Interestingly enough, we don't see the massive numbers of snapshots.  We see numbers similar to the 3.4 numbers: 385,661 `FileHasSnapshot` objects and 305,655 `IndexedNormalizedFileSnapshot` elements for around 16mb.  This implies to me that this number is scaling not based on the version of Gradle we are building _with_ but based on the version of Gradle that we are building.  In other words, we've changed something about the build of gradle that is triggering this change of behavior.  This makes me wonder if the conversions to the `java-library` plugin are possibly what has increased memory usage.  These changes have trickled in to the code base and maybe we just finally pushed things over the edge around Feb 8th (I see a couple more projects were converted on the 6th).  I'm not sure if the added snapshots would be an expected side effect of this change or not.

If anyone is interested, all of the dumps that I produced can be found here: https://drive.google.com/drive/folders/0B-NsnVCAN5DgMVpmZWdTTWhqZ2M?usp=sharing

**Comment by bigdaz** [comment]
Great analysis, thanks @ghale

**Comment by melix** [comment]
I added a [note in the documentation](https://github.com/gradle/gradle/commit/73f32d68824582945f5ac1810600e8d87794c3d4) on the release branch.
