### ISSUE TITLE
Release compiler flag configuration based on targetCompatibility results in stack overflow 

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#14141]
Configuring the `--release` compiler flag based on the targetCompatibility of a project causes a stackoverflow.

### Expected Behavior

When configuring the release flag via

```
compileTask.getOptions().getRelease().set(
    project.provider(() -> { 
        JavaVersion javaVersion =    
        JavaVersion.toVersion(compileTask.getTargetCompatibility());
            return Integer.parseInt(javaVersion.getMajorVersion());
        }
    }
)
```

I would expect the release flag to be derived from the targetCompatibility property.

### Current Behavior

The snippet above causes a stackoverflow as by default the targetCompatibility level is calculated from the new release flag. To fix this behaviour locally
it is required to override the convention mapping:

```
compileTask.getConventionMapping().map("targetCompatibility", () -> java.getTargetCompatibility().toString());
```
 
### Context

We have a 300+ projects multiproject build with different configured targetCompatibilities and make heavy use of this. 
Before Gradle we configured the `--release` flag manually via commandlineArguments deriving the version as mentioned. Changing the order in our setup to use the `release` property and derive compatibilty settings from that property is quite invasive and potential error prone as it introduces a change in behaviour in our build: 
E.g. developers set the targetCompatibility and will be surprised of that setting not taking any effect.  

### Steps to Reproduce 

Our build is open source at https://github.com/elastic/elasticsearch

**Comment by ljacomet** [comment]
So we have been thinking some more about this decision, and we need to keep it as-is. We are even using the same principle for the upcoming toolchains feature in Gradle 6.7.

The main reason is compatibility. IDE imports and other ecosystem integrations rely on the `sourceCompatibility` or `targetCompatibility` both at the project and compile task level to expose the configured language level.
When introducing first class support for the `release` flag or for toolchains, we need builds that opt-in to use the new feature to still reflect that choice on these properties so that tooling makes the right decision.

While the request makes sense for some use cases, it would break IDE import and other features out there.

So neither `release` nor toolchains should be set based on the values of `sourceCompatibility` or `targetCompatibility`. This will cause the exception described here.

**Comment by ljacomet** [comment]
No changes planned on the Gradle side - closing
