### ISSUE TITLE
Performance bottleneck for large projects when file system watching is enabled

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#14158]
Looks like with large projects we can have a performance bottleneck with FSW enabled. The issue has been observed on macOS. The effect is that the build runs much slower than the same build without FSW.

An almost fully up-to-date build with 23K tasks and 163K files in 75K directories + 16K missing files takes 9+ minutes with FSW _enabled,_ while only 3 minutes with FSW _disabled._

The issue seems to be that we update the watched hierarchies every time anything changes on the file system, i.e. whenever we create a new snapshot. This seems like the expensive part of the code:

https://github.com/gradle/gradle/blob/60ef90a54fb0185174cc5b61a941686d057bac0d/subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java#L215-L220

It's the adding the snapshot to a `Set` that seems to be creating gigabytes of garbage.

In Gradle 6.6 GA we have similar code with a slightly different `Set` being added to:

https://github.com/gradle/gradle/blob/d119144684a0c301aea027b79857815659e431b9/subprojects/file-watching/src/main/java/org/gradle/internal/watch/registry/impl/HierarchicalFileWatcherUpdater.java#L158-L178

Internal details: https://github.com/gradle/gradle-private/issues/3170

---
cc: @gradle/execution

**Comment by wolfs** [comment]
The problem should only exist for hierarchical watchers (aka macOS and Windows). Linux determines what to watch differently. Did a similar problem also appear on Linux?

For determining what to watch for hierarchical watchers, we only need to check whether there is anything at the watchable locations in the VFS. IIUC, this is currently slow because we try to tighten the possible watch points during the build by using `FilterAlreadyCoveredSnapshotsVisitor`.

To make determining the watched hierarchies during the build faster, we can
- remove the `FilterAlreadyCoveredSnapshotsVisitor` visitor during the build and only try to tighten the watch points at the end of the build once. We can also tighten the watch points by using a `FileHierarchySet` instead of a `HashSet` at the end of the build, though I don't think that makes a big difference when we only do it once.
- additionally make the check if there is anything at the watchable location faster by allowing to short-circuit visiting the snapshot roots at the location. Currently, we run through all the snapshot roots even though we already determined that there is a snapshot worth watching at the watchable hierarchy.

**Comment by lptr** [comment]
> The problem should only exist for hierarchical watchers (aka macOS and Windows). Linux determines what to watch differently. Did a similar problem also appear on Linux?

No, it seems that the code quoted above is responsible for the bottleneck, so I don't expect it to happen on Linux. That said, the main issue here is that we have no performance tests of this scale yet, so we can't reproduce the problem in-house.

> * remove the `FilterAlreadyCoveredSnapshotsVisitor` visitor during the build and only try to tighten the watch points at the end of the build once. We can also tighten the watch points by using a `FileHierarchySet` instead of a `HashSet` at the end of the build, though I don't think that makes a big difference when we only do it once.

This is what I did roughly in #14157 above.
