### ISSUE TITLE
Directories are not able to be included in a FileTree

### ISSUE THREAD

**Issue by klawson88** [gradle/gradle#14152]
### Expected Behavior
**Given:**

    /
    |_dir_1
      |_ foo.bar
      |_ dir_2
        |_ bar.baz

**When:**

    tasks.register<Delete>("remove") {
        delete (
            fileTree("/dir_1").matching {
                include("dir*")
            }
        )
    }

and

    ./gradlew remove

**Then:**

    /
    |_dir_1
      |_ foo.bar

### Current Behavior

The directory structure specified in the prior section remains unchanged, unless there are one or more files with the "dir" prefix in the base directory, in which case said files would be removed.

### Context

Discovered during the creation of a task to delete subdirectories matching a given pattern.  Verified to not be a bug with in deletion logic with the following code, given the directory structure specified in the **Expected Behavior** section:

    tasks.register("testFileTree") {
        val fileSet = fileTree("/dir_1").matching {
            include("dir*")
        }.files

        println("The size of this file tree is: ${fileSet.size}")
    }

When the task is executed, the output is: `The size of this file tree is: 0`.

This issue appears to have been discovered before and has a [ticket](http://issues.gradle.org//browse/GRADLE-2822) created for it in the old issue tracker, but it seems it wasn't ported over.

Here are some other reports of this issue, or other issues which have this one as the root cause:
- https://stackoverflow.com/questions/24274966/deleting-directories-via-gradle-filetree-include
- https://stackoverflow.com/questions/19299455/how-to-delete-an-empty-directory-or-the-directory-with-all-contents-recursively

This issue, combined with fact that [pattern arguments in commands executed with Exec#commandLine are processed as literal strings](https://github.com/gradle/gradle/issues/14151), makes the creation of pattern-based tasks which target directories a lot harder than it should be, and the resultant task a lot more verbose and imperative than it should be.

### Steps to Reproduce 

Replicate the **Given** and **When** parts of the scenario specified in the **Expected Behavior** section, and confirm the behavior is that described in the **Current Behavior** section.

### Your Environment

Build scan URL: N/A

**Comment by ghilainm** [comment]
Same problem here, I don't know how to solve that issue nicely :). 

I have a directory containing files and directories. I want to delete all the directories but keep the file. For me the natural solution is:

```
task deleteFileFromDirectory(type: Delete) {
    delete fileTree('myDir').filter {
        !it.isFile()
    }
}
```

This does not work.

**Comment by TWiStErRob** [comment]
@wolfs so is my understanding correct that this is still the case, and the only way to achieve what this code intuitively asks to delete:
```kotlin
project.tasks.register<Delete>("cleanDebug") {
    delete(fileTree(rootProject.file("docs/debug")) {
        include("*/.gradle")
        include("*/build")
        include("*/buildSrc/.gradle")
        include("*/buildSrc/build")
    })
}
```
is something like:
```kotlin
project.tasks.register<Delete>("cleanDebug") {
    fileTree(rootProject.file("docs/debug")) {
    	include("*/.gradle")
    	include("*/buildSrc/.gradle")
    }.visit { if (name == ".gradle") delete(file) }
    fileTree(rootProject.file("docs/debug")) {
    	include("*/build")
    	include("*/buildSrc/build")
    }.visit { if (name == "build") delete(file) }
}
```
with a huge caveat, that if this is participating in a chain of tasks with dependencies and such, where the `fileTree` would be lazily deleting things, the actual viable solution won't remove those files and folders, because at the time of fileTree visiting those folders don't exist.

**Comment by TWiStErRob** [comment]
Nope, @wolfs, it keeps the whole hierarchy of directories because of how `fileTree` iterates only on files, hence the comment on this issue.
| https://github.com/gradle/gradle/issues/14152#issuecomment-1243896708 (`/**`) | 2nd code in https://github.com/gradle/gradle/issues/14152#issuecomment-1236398023 (`visit`) |
| - |  - |
| ![image](https://user-images.githubusercontent.com/2906988/189744274-ebb3881c-e6cd-44ed-9db5-beea1b0e5329.png) | ![image](https://user-images.githubusercontent.com/2906988/189744626-be11ffca-df3e-478c-a1d4-6c34a4ee2f47.png) |

Note 1st code in https://github.com/gradle/gradle/issues/14152#issuecomment-1236398023 doesn't do anything, it's just illustrative, adding a trailing `/` to the dirs yields the same as `/**` (as documented).
