### ISSUE TITLE
Add Gradle support for C# and .NET

### ISSUE THREAD

**Issue by wilhe215** [gradle/gradle#1428]
Gradle has out of the box support for languages like Java, C, C++.  Please add similar support for C# and .NET

**Comment by eriwen** [comment]
Maybe we can form an open-source partnership with Microsoft will sponsor our work on such a thing. Know anyone we can contact @wilhe215?

**Comment by nallar** [comment]
As a workaround/temporary solution, [gradle-msbuild-plugin](https://github.com/Ullink/gradle-msbuild-plugin) allows easier delegating to msbuild, although this means there's no proper sense of source sets and other concepts normally used in gradle.

**Comment by coactivechris** [comment]
The msbuild plugin support is spotty at best, particularly when the versions of msbuild vary wildly, particularly between the .Net Framework and Visual Studio.

While there are a number of GitHub projects trying to fill this void, I'd agree that full support for .NET would be really helpful.

With the rise of .NET Core, and a more standard mechanism for building / deploying code within .NET ecosystem, this seems to have increasing weight as a feature.  It's that, or someone in the .NET space will start building a .NET-specific version of Gradle, which feels wrong.

**Comment by mathiasbn** [comment]
I have a dream... A dream of C# projects configured by gradle. A dream of never ever entering a .sln or .csproj file ever again! By autogenerating the ide files (yes I called them IDE files) instead of GUI editors.

Would that be possible. Wouldn't that be nice? 

There should be a market for this. Huge xml files generated through GUIs yields conflicts and hinders the flexibilities of Gradle.

For this vision gradle-msbuild-plugin sadly falls short.

**Comment by lacasseio** [comment]
I'm with you on this @mathiasbn. However, in the short to medium term, we aren't planning to work on this story. The two possibilities are 1) you roll out your plugin, you can look the next native plugin we are rolling out which will hopefully give a better structure for new language community plugins or 2) find a sponsor for the development effort.

**Comment by adammurdoch** [comment]
I think there's some other possibilities between option 1 and option 2. We can probably find a way to work on this together in some form, if anyone is interested in doing so. At the moment, Gradle can't invest much time into the development and support for a C# integration (this may change in the future), as we are focussing on C++ first. But we can help out in certain ways because I think this is an important capability for Gradle to have, and I think Gradle has a lot to offer developers here. The process of developing C# support would also be really useful input into the evolution of the C++  plugins, as adding a new language and runtime platform should be "easy" if the native plugins are doing their job correctly ("easy" means "not super painful" rather than "easy").

What we could do is set up a github repo where whoever is interested in growing a solution can help out. The solution might start out as not much more than a sample plugin with a task that just compiles some C#. We can evolve this over time and integrate it nicely into Gradle's dependency management and native component model, and make the native component model work better.

**Comment by mathiasbn** [comment]
Wauw two Gradle team responses. I would love to say I'm your Dev for the job, but...
I'm coming from Java/kotlin resently, so I'm not that knowledgeable in .net (only suffering)
I've been using Gradle for years, but never been really into the machine room. Only created plugins and wrapped/decorated others plugins.

Maybe I will look into the c++ plugin and/or the msbuild-plugin 

Thanks for responding, even with the not so great news

**Comment by adammurdoch** [comment]
I would start with a super simple 'c# application' plugin, that just takes some C# source with no dependencies and builds an executable from it. It would just need a single compile task. Then, we can grow it from there, eg by adding a library plugin, adding some basic dependency management, integrate with the c++ plugins and the visual studio plugin, and so on.

I wouldn't try to duplicate the c++ plugins at this stage, they need to be further simplified before then. Instead, I would just aim to have the same basic structure for now.

**Comment by rrmayer** [comment]
Is there a set of requirements out there for what a c# plugin would need to do?

**Comment by mathiasbn** [comment]
In my mind, one should start with generating csproj files from a gradle script only containing project dependencies. 
Here after single increments like:
 - nuget dependencies
 - build with rebuild
 - generate solution
 - ...

**Comment by lacasseio** [comment]
I would avoid generating csproj files to execute the build. Instead, just like Adam said, starts with a plugin for a simple application. The plugin can be called `csharp-application` that generate a compile task nothing related to the current native compile task and a link task. From there you add strictly what is needed and move along with use cases. To help with use cases write samples of actual code that you want to compile instead of what is theorically possible. As the code evolve then we can look at what the core of Gradle could provide to make the endeavor simplier. We don't yet have an out of the box experience for adding new language to Gradle. The native team will look into this as we port the C, Assembly, Objective C/C++ from the software model. Until then, if you want to move forward with such plugin, you need to start small and grow the solution out of it.

**Comment by mathiasbn** [comment]
Of cause you know way better than me how to do this. 
In my (should we call it) user-level understanding / need. I was thinking of starting with just calling msbuild. Maybe like gradle calling ant. 
But, if I understand you correctly, you go directly to the compiler. Which now I think about it seems right.

My reason to suggest to generate csproj/solution files was primarily to make the project usefull early on.
I would guess most people writing C# code are using an IDE. And they use those files (at least for now)(I know Rider has standard IDEA files, but they are still needed).

Just like Jetbrains started with a plugin to visual studio, then did an full IDE, but still using Visual Studio project files. It allows for incremental transitions in teams.

Without any experience, it seems like there is a long way to go before a "from scratch" (no msbuild shortcut) version can be used in anything near a real project?

Still sounds very interesting

**Comment by lacasseio** [comment]
You do have a great point. The alternative for shorter term would be to have a similar integration as ant in the sense that we could parse the msbuild  files to extract task names and allow you to depend on those task like normal Gradle task but they would outsource to msbuild. This would be aligned with our build wrapping effort that you can see some cmake samples in the [native sample repo] (https://github.com/gradle/native-samples). Both solution aren't mutually exclusive. It depends what you want to end up with. Basically, if the csproj already exist, you could wrap the build with Gradle. If they don't, then you can either decide to generate them based on a custom DSL then wrap them with Gradle or model the compilation in Gradle (and generate the csproj file in a way they delegate to Gradle for compilation).

**Comment by redradist** [comment]
Hi guys, any updates on this topic ?

**Comment by lacasseio** [comment]
Unfortunately, haven't made any progress on this front. We most likely going to concentrate the effort on documenting and providing helper implementation to implement new language support. C# is a great candidate for this. At the moment, we are working on polishing the native support (C++ and Swift). What will come out of this will roll back into JVM language plugins and be the basis for C support. It will also be communicated with other language support such as Kotlin to document and provide guidance for new languages.

**Comment by SupinePandora43** [comment]
2 years this issue opened!

**Comment by lacasseio** [comment]
I can understand the frustration, but C# and .NET is currently not a priority for us. We welcome any community plugins that would enable these languages to be built in Gradle.

**Comment by SupinePandora43** [comment]
i think .NET already has good dependency manager and build tool . "nuget" and "dotnet" (.NET Core SDK)

**Comment by DJViking** [comment]
Maybe more relevant now that Microsoft has release **.NET 5** for **Linux**, **MacOS** and **Windows**
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by ljacomet** [comment]
To conclude on this: Implementing this as core Gradle is not going to happen. However the design of Gradle is to be extensible and a community plugin could provide this support.

Missing functionality and blockers which prevent that implementation should be handled as separate issues.
