### ISSUE TITLE
Add single/multi-project choice to 'gradle init --type application'

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14305]
I could imagine having an addition choice after selecting _type_ and _language_. Initially this would only be supported for _application_ and the JVM languages:

```
Modularize project?:
  1: no
  2: yes
  3: yes (with Java Module System) // this maybe for later
```

The project would be based on the samples we have now with two library and one application project: https://docs.gradle.org/current/samples/sample_jvm_multi_project_build.html

Based on this, we would do a sample generation - similar to what we now do for 'application' and 'library' (https://github.com/gradle/gradle/issues/14291) .

Then we will have one generated sample for each JVM language. We already have example src code files for Java/Groovy/Kotlin. We can decide if we add the same for Scala (and maybe also C++ and Swift) if it's not too much effort.

The content of the generated readme should be based on what we have in the "Creating Multi-project Builds" (as far as that is still valid) and the README of the sample linked above:

Then we will have:
- `gradle init` for multi-projects with convention plugins in buildSrc
- Individual Samples for multi-projects in each languge (instead of the one generic JVM one)
- Each sample will be in the "guide style" and hence this will be a better replacement for the guide that can then be removed (https://github.com/gradle/guides/pull/380)

**Comment by big-guy** [comment]
Would this be another type or would this be a variation of the application type?

application, library and Gradle plugin are all very much in the "what do you want to build" category.  basic is an odd one out (but we've talked about that one before). I don't think someone wants to build a "multi-project".

**Comment by jjohannes** [comment]
I also don't like to name this "multi-proejct". I just did not have a better idea yet.

Putting it as a choice behind "application" is an option.

I guess my thought was that you might also want to build a multi-project library. Or a multi-project Plugin.

But then that maybe yet be another combination of things. Or for that we just offer another mode later, where you can add additional subprojects to an existing project using `init`.

So yes. I think it makes sense to make this a choice for `application`; adjusting description and title.

**Comment by alexismanin** [comment]
I think it's common to get "multi-module" projects. 

Currently, doing it manually can be difficult. When following official documentation, I find it not clear how to handle subproject init. Doc says ["create a build script"](https://guides.gradle.org/creating-multi-project-builds/#add_a_groovy_library_subproject).
So, how ? 
* Manually ? But that won't prepare a lot of stuff that gradle init would (for example, in java it creates source and test package skeleton).
* Using gradle init works fine **but** it generates wrapper in the subproject, instead of detecting there's one in the root.

IMHO, multi-module initialization could be improved in one of following ways:
 * add a "multi-module" or "multi-project" (not sure of the semantic) advanced option
 * add a "submodule" option, so user can specify he is initializing a subproject (so skip wrapper, and possibly other magic)
 * When init is launched, scan parent dir for gradle script, and if it is present, ask user if current init is a subproject
 * Or, all works fine currently, but I lack understanding of subproject init workflow. In that case, maybe official documentation could be amended to explain in details some concepts.

**Comment by adammurdoch** [comment]
I think what we want to do here is provide a way for the user to request that the software (of whatever kind it happens to be)  be composed of a project containing the software's entry point plus one or more projects containing libraries used by the entry point. In other words, we should add a cross cutting option to add some library projects with the relevant implementation language to the generated build.

This isn't really something that applies only to applications. It's perhaps something we can start with for applications, as an experiment, as this is the type of software where this is most likely to be useful (maybe). It should at some point be available for all kinds of software. I wouldn't implement it as a new type/template but instead implement this as an (interactive) option for the template, just like the package name or DSL language or test framework are options.
