### ISSUE TITLE
Gradle forces extension and type to 'jar' when a classifier is specified for a dependency

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#1438]
Reproducing build script:
```
repositories {
    ivy {
        name 'localRepo'
        url 'local-repo'
    }
}

configurations {
    myconf
}

dependencies {
    // not working, prints:
    // TYPE:jar
    // NAME:swt-3.104.2-eclipse452-win32-win32-x86_64.jar
    myconf([group:'org.eclipse.swt', name:'swt', classifier:'win32-win32-x86_64', version:'3.104.2-eclipse452'])
    // working, prints:
    // TYPE:bundle
    // NAME:swt-3.104.2-eclipse452.jar
    myconf([group:'org.eclipse.swt', name:'swt', version:'3.104.2-eclipse452'])
}

task printDependencies {
    doLast {
        println "---"
        project.configurations.getByName("myconf").resolvedConfiguration.resolvedArtifacts.each { ResolvedArtifact artifact ->
            println "TYPE:$artifact.type"
            println "NAME:$artifact.file.name"
            println "---"
        }
    }
}
```

When we resolve the first dependency (the one with the classifier), we look for artifacts with type and extension == "jar", even though the ivy.xml lists the artifact with type = bundle and extension = jar.  Without specifying a classifier, you'll see the correct type come through.

I tracked this down to this bit of old code:
https://github.com/gradle/gradle/blob/c8143c9bcf412a2d19053b8c926c7787c1dc8087/subprojects/core/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/ModuleFactoryHelper.java#L26-L28

It seems like this might not be needed any more, but I'm not familiar enough with the dependency management infrastructure to know what the side effects would be.

@bigdaz could you weigh in on what's going on here?  I can share the local-repo.

**Comment by eljobe** [comment]
@bigdaz, It would be great to get some input from you on this request. It came in through one of our customers via a support ticket.

**Comment by bigdaz** [comment]
When a `classifier` or `type` attribute is specified on a dependency declaration, then we ignore the published metadata, I think. I don't really understand the original motivation for this, but it's likely that this was done in order to handle artifacts with `classifier` from a `maven` repository.

It's important to realize that this dependency declaration will work fine _even if the artifact is not declared in the published `ivy.xml`_. (Maven POM files have no way to declare an additional artifact, so we just jam the classifier on the end of the default artifact name).

To fix this bug, we should probably first look in the published metadata for a matching artifact, and use the artifact metadata if found. If no artifact is found we would use the default `type` attribute as we do now. I don't think this would be too big of a breaking change. I think we need to continue to handle undeclared artifacts in both Ivy and Maven repositories: `-src.jar` publications are a common example.

**Comment by bigdaz** [comment]
Providing a `classifier` on the dependency declaration is a shorthand for:
```
dependencies {
    compile('org.foo:bar:1.0') {
        artifact {
            classifier 'classy'
        }
    }
}
```
We want to replace the use of these 'dependency-declared artifacts' with custom variants. We don't have any plans to change the current behaviour for `classifier`.

See https://github.com/gradle/gradle/issues/3771#issuecomment-350870658 for more context.
