### ISSUE TITLE
Gradle daemon starts anyway even if I use --no-daemon

### ISSUE THREAD

**Issue by anshbansal** [gradle/gradle#1439]
Same as GRADLE-3003 but happening on Ubuntu 14.04

Running

> gradle --no-daemon jettyRun -Dorg.gradle.java.home=/usr/lib/jvm/java-1.8.0-openjdk-amd64

### Expected Behavior

The daemon should not be started

### Current Behavior

Daemon is starting

### Context

I do not have enough RAM so don't want the daemon to be running.

### Steps to Reproduce (for bugs)

> gradle --no-daemon jettyRun -Dorg.gradle.java.home=/usr/lib/jvm/java-1.8.0-openjdk-amd64

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
Gradle has to start a new process if the client VM's settings don't satisfy the project settings. You are passing `-Dorg.gradle.java.home` and probably pointing it to a different Java home than the Gradle client VM is running on. Thus it has to start a new process to satisfy your request. Use `JAVA_HOME` if you want to influence which JVM the client is started with.

> I do not have enough RAM so don't want the daemon to be running.

You can configure the `org.gradle.jvmargs` to specify how much memory the daemon should use. It doesn't have to be the 1GB that Java 8 uses by default. The same is true for the Gradle client VM, whose memory settings you can influence through `GRADLE_OPTS`. You can set that pretty low since it only handles the output coming from the daemon. 

I strongly encourage you to use the daemon as it will make your builds way faster. Just give it a reasonable amount of memory for the projects you are working on.

**Comment by gushengyuan** [comment]
I see this bug in jira [GRADLE-2357](https://issues.gradle.org/browse/GRADLE-2357), but it's still not fixed.
I want to disable the daemon just because the JVM crashed if the gradle is run in another process.

**Comment by oehme** [comment]
We **have to** fork another process if you give us JVM args that don't match the client VM. If you want to run inside the client VM, you'd have to use GRADLE_OPTS instead of org.gradle.jvmargs.

> I want to disable the daemon just because the JVM crashed if the gradle is run in another process.

Instead of disabling the daemon you should find out why it crashes. That's not normal and probably caused by some badly written plugin. Not using the daemon will significantly slow down all your builds.

**Comment by JessHolle** [comment]
The daemon forking seems to louse up Coverity...
