### ISSUE TITLE
flywayMigrate command does not respect version of flyway described in dependencies

### ISSUE THREAD

**Issue by AlexSlusarenko** [gradle/gradle#14486]
### Expected Behavior
'gradle flywayMigrate' command should respect version of flyway plugin described in dependencies

### Current Behavior
Currently some internal version of flyway plugin is used for 'flywayMigrate' task.

### Context
Gradle version: 6.5.1
Flyway version: 'org.flywaydb:flyway-core:5.2.4'
Mysql version: 5.6

### Steps to Reproduce 
'gradle build' with all migration steps passed successfully and application startup from jar processed successfully
However
'gralde flywayMigrate' command fails with error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Error occurred while executing flywayMigrate
  Flyway Enterprise Edition or MySQL upgrade required: MySQL 5.6 is no longer supported by Flyway Community Edition, but still supported by Flyway Enterprise Edition.

### Your Environment
Build scan URL:
https://gradle.com/s/qwppydweggddw

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This looks like an issue with an external plugin not provided by Gradle core.

Consider reporting it to the plugin maintainers.

If you believe this is a Gradle issue, please provide more information, including a reproducer, otherwise it will not be possible to act upon this report.

The linked build scan does not even execute the problematic task.

**Comment by AlexSlusarenko** [comment]
Thanks a lot! 
Indeed, that's probably should be flyway plugin issue. 
I will address this question to them. And this ticket may be closed.
