### ISSUE TITLE
Samples use nightly build instead of RC

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#14522]
Check the sample zip from:
https://docs.gradle.org/6.7-rc-1/samples/sample_sharing_convention_plugins_with_build_logic.html

The wrapper should be using the 6.7 RC1, instead it's using what looks like a nightly build. I suspect this is actually the timestamp for whenever the sample was generated and not a real nightly build.

This used to work: https://docs.gradle.org/6.6-rc-1/samples/sample_composite_builds_basics.html

**Comment by jjohannes** [comment]
@big-guy the wrapper in the zips of the linked sample is correct. Did you see this somewhere else maybe?

There was an issue that wrong links (that do not correspond to the wrapper) are in generated readme's because the version is not input the generation and they may be taken from cache. But I fixed this already for RC2 (by removing the links):
https://github.com/gradle/gradle/commit/ab6aa267aa58dc148932b3ee3c68af3e37557e26

**Comment by big-guy** [comment]
Whew, I must have had a previous zip that I downloaded with a nightly. Thanks!
