### ISSUE TITLE
Setting dependencies in allprojects buildscript

### ISSUE THREAD

**Issue by sirinath** [gradle/gradle#14558]
Cannot add `dependencies` in `allprojects` `buildscript`

### Expected Behavior
Should be able to add dependencies.

### Current Behavior
```
Build file 'C:\Users\...\GitHub\leo\build.gradle' line: 43

A problem occurred evaluating root project '...'.
> Cannot change dependencies of dependency configuration ':classpath' after it has been resolved.
```

### Context
As `plugins` cannot be used in `allprojects` and `subprojects` I want to specify the plugin `classpath` which are common to all projects using `apply plugin:`.

### Alternative

Alternatively, enable `plugins` in `allprojects` and `subprojects`.

**Comment by jjohannes** [comment]
Hi @sirinath. It is unlikely that support for this will be added in Gradle. We are moving away from the pattern of using `allprojects {}` / `subprojects {}` to configure mutiple projects from "the outside". 

We recommend using _convention plugins_ in `buildSrc` instead. We just updated documentation/samples on the topic:
- https://docs.gradle.org/6.7-rc-1/samples/sample_convention_plugins.html
- https://docs.gradle.org/6.7-rc-1/userguide/sharing_build_logic_between_subprojects.html

You can then use the `plugins {}` block and define dependencies for you plugins in the build script of `buildSrc` (https://docs.gradle.org/6.7-rc-1/samples/sample_convention_plugins.html#applying_an_external_plugin_in_precompiled_script_plugin).

**Comment by sirinath** [comment]
What is the `myproject` prefix?

**Comment by sirinath** [comment]
Through `allprojects {}` / `subprojects {}` does have its flaws please keep it and also enhance it as there are existing build scripts which use it and in some cases, this is convenient to use.

**Comment by ljacomet** [comment]
This support will never be added to Gradle.
Aside from recommending to move away from these constructs, there is a fundamental lifecycle issue at play there:

- You cannot change the buildscript classpath of the current project except by doing that first. Supporting `allprojects` violates that
- Even with `subprojects` only, there is still an issue between loading the project to apply the block from `subprojects` but not loading enough of it so that `buildscript` still appears "first"

Given the complexity listed above, I am closing this as Gradle will not support it.
