### ISSUE TITLE
TAPI: Offer API to obtain all included builds with nested builds and buildSrc

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14563]
Currently, tools such as IDEA need to separately request a model of buildSrc. Nested included builds are not found at all (https://youtrack.jetbrains.com/issue/IDEA-204526).

This could be solved by making [GradleBuild.getIncludedBuilds()](https://github.com/gradle/gradle/blob/7f371d8a1dc49006abed56bf75412326ed31f2ee/subprojects/tooling-api/src/main/java/org/gradle/tooling/model/gradle/GradleBuild.java#L57) return all this information or by adding a new API for it.

**Comment by big-guy** [comment]
youtrack.jetbrains.com/issue/IDEA-204526

**Comment by vladsoroka** [comment]
Recently we've added the support of importing `buildSrc` projects which uses included builds, the  [feature](https://docs.gradle.org/6.7-rc-1/release-notes.html#build-src) introduced in Gradle since 6.7.
However the change we made (usage of `--include-build` tapi arguments for `buildSrc` model requests) can break some composite projects like reported in https://youtrack.jetbrains.com/issue/IDEA-257366

There is an ugly workaround but to make it works properly we rely on your support.

**Comment by jjohannes** [comment]
The fix in IDEA linked above has caused another issue (https://github.com/gradle/gradle/issues/15583).

We should really address this issue here so the whole setup is less complex and less likely to introduce regressions again.

**Comment by adammurdoch** [comment]
https://github.com/gradle/gradle/pull/17307 adds support for this. In this change, all of the builds that are available to be imported into the IDE (all of the included builds and all of the `buildSrc` builds) are available via the `GradleBuild.getEditableBuilds()` property.

To make it work, you need a tooling API version that includes this property (which is anything later than 4.10) and a Gradle build that is using a 7.2 nightly.

**Comment by vladsoroka** [comment]
@adammurdoch is it possible to apply Gradle `init-script` to `buildSrc` builds?

**Comment by oehme** [comment]
@jjohannes @adammurdoch IntelliJ registers its model builder with an init script. Since the `--init-script` parameter is not passed to `buildSrc`, IntelliJ has no way of adding its model builder to buildSrc. The only `buildSrc` models that can currently be queried with this feature are the ones that are built into Gradle. IntelliJ relies on numerous custom models. So right now this feature isn't useable for them.

The simplest fix would be to pass init-scripts on to `buildSrc`. This would be in line with how included builds work. 

@vladsoroka FYI I'm working on a PR for IntelliJ that would make use of this new API as soon as it works properly.

**Comment by nskvortsov** [comment]
Absence of model builders in `buildSrc` available in composite structure now can break the sync: https://github.com/gradle/gradle/issues/20898
