### ISSUE TITLE
could not resolve all files for configuration '"eclipsePlugin:compileClasspath'

### ISSUE THREAD

**Issue by sampson17471** [gradle/gradle#14584]
When I compile the project using the gradle assemble command, the following error occurred。My Eclipse installation path is D:Eclipse_all/eclipse_noweclipse-jee-photon-R-win32-x86_64/eclipse-jee-photon-R-win32-x86_64/eclipse/.And i was escaped。
This path is not resolved。I changed my Eclipse path to D:/eclipse, it builds sucess.

### Current Behavior

failure:build failed with an exception.
*what went wrong:
could not normalize path for file  'D:\Eclipse_all\eclipse-workspace\spotbugs_wfei_for\spotbugs\eclipsePlugin\D:Eclipse_alleclipse_noweclipse-jee-photon-R-win32-x86_64eclipse-jee-photon-R-win32-x86_64eclipse\plugins'.
### Your Environment
Eclipse Java EE IDE for Web Developers.
Version: Photon Release (4.8.0)
Build id: 20180619-1200
jdk1.8
Build scan URL:

**Comment by ljacomet** [comment]
The issue comes from using an invalid absolute path. `D:Eclipse_all` is not recognized as absolute because it misses a `\` after the `D`. Because of that, Gradle considered the path to be relative and thus failed to resolve it.
As you stated, the fix was to properly add the missing character. And indeed a `/` works as well.

There is nothing to be fixed in Gradle.
