### ISSUE TITLE
Compare different setups of large/huge hierarchical Gradle projects

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#14713]
Different setups to compare:
1. Build logic in _buildSrc_ or in an _included build_
2. Main build in a single project with a hierarchy of subprojects
3. Main build as a hierarchy of included builds (requires build logic in _included build_)

Feature wise: What are differences? What is better, what is worth? What are advantages of one over the other?

Performance: How does performance of configuration time and IDE sync time compare?

Build to use for comparison:
- `gradle/gradle` build (using spike branch that turns it into a hierarchy)
- Spring Boot build
- Huge artificial build with thousands of projects

**Comment by jjohannes** [comment]
Builds with two different setups - multi-project hierarchy vs. composite hierarchy - that have been used for this analysis:

1. Spring boot:
    - multi-project hierarchy: https://github.com/jjohannes/spring-boot/tree/performance/baseline
    - composite: https://github.com/jjohannes/spring-boot/tree/performance/compositeHierarchy
2. gradle/gradle:
    - multi-project hierarchy: https://github.com/gradle/gradle/tree/performance/baseline
    - composite: https://github.com/gradle/gradle/tree/performance/compositeHierarchy
3. Huge artificial project (without sources):
    - multi-project hierarchy: https://github.com/jjohannes/huge-gradle-project/tree/performance/baseline
    - composite: https://github.com/jjohannes/huge-gradle-project/tree/performance/compositeHierarchy

### Functionality / Features

⚠️ Things that don't work well with composite builds that should be fixed to provide a similar experience as with large subproject hierarchies:

- Too strict cycle check (https://github.com/gradle/gradle/issues/6229)
- Properties from `gradle.properties` (e.g. version) are not passed down (https://github.com/gradle/gradle/issues/2534)
- Can’t define a convention settings plugin in a local build - this never works, but for a single build it is not that important (https://github.com/gradle/gradle/issues/14562)
- Can’t run tasks directly from command line (https://github.com/gradle/gradle/issues/2533)
- Hard to use a “root extension” across the whole composite (https://github.com/gradle/gradle/issues/14697)
- (Indirect; you may hit when moving from `buildSrc` to an included `build-src` build - which you need to do in order to share the logic in all builds)
Plugin already on classpath still needs version  (https://github.com/gradle/gradle/issues/14704)

⭐  Thing that are better in included builds:

- Split up the structuring of your project into multiple setting files
    - Have local dependency of one component (nested build there)
    - Define the internal structure of one component (set of subprojects) only in the setting file of that component (1 component = 1 build)
    - No more [3k+ lines settings files](https://github.com/jjohannes/huge-gradle-project/blob/performance/baseline/settings.gradle)
- `includeBuild` allows you to include a build from any location (`include` requires you to jump some loops to have another physical location for a subproject #14561) 
- A composite hierarchy makes multi-repo and mono-repo structures very similar. If desired, a component can be built on its own without the need to know all of its outer context.
- Safe configuration on demand - an included build is only fully configured when needed. No opt-in needed.

⭐  Future improvements only possible with composite builds
- More optimisations: avoid configuration of included builds in more cases, allow for more parallelism during configuration time (e.g. parallel build script compilation).
- Allow import of only one component (1 build) into the IDE (already working to a certain degree)


### Current Performance

Only some initial measurements of configuration time for now.

They indicate that most penalty is introduced when moving from a single build to a composite. E.g. just doing an `includeBuild()` with an empty project has the effect. In the future we should understnad why this is.

Measurements:

1. [Spring boot configuration time](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/38540639:id/results/performance/build/test-results-springBootBuildPerformanceAdHocTest.zip!/performance-tests/report/tests/configuration-time---springBootBuild.html)
2. [gradle/gradle configuration time](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/38796883:id/results/performance/build/test-results-gradleBuildPerformanceAdHocTest.zip!/performance-tests/report/tests/configuration-time---gradleBuild.html)
3. [Huge artificial project configuration time](url)

Legend:
- Baseline - subproject hierarchy (single build)
- CompositeSimple - adding a includeBuild (second build is empty)
- CompositeBuildSrc - turning buildSrc into an included build
- CompositeHierarchy - splitting the hierarchy into multiple builds

**Comment by adammurdoch** [comment]
This is a good write up.

> Properties from gradle.properties (e.g. version) are not passed down

I think this is a good thing. This is not really different to the `allprojects` case. In general, we want each build to declare and 'pull' the things it needs and avoid depending on implicit inheritance or 'push'.

There are good reasons to want to share data from a configuration file in multiple places. I think it might be better to allow a plugin to declare this and make it explicit. There's several ways you can think about this:
- Consider this data as values exported by the parent build and imported by the child build. A plugin can say "please import this value". We might use the same mechanism to allow a plugin to query data "exported" or "published" from another project.
- Consider this data as a "build option" and allow a plugin to declare the build options it needs and query their value. There can be a convention for the places to look for the value and perhaps the parent's gradle.properties is one of the candidates.
- Add a convenience to 'pull' a gradle.properties file into a build.

> No more 3k+ lines settings files

This isn't _really_ an advantage of using an included build. You can easily write a very small amount of code that discovers the projects of a multi-project build rather than listing them explicitly. You can also easily put this in a settings plugin and publish it.

I think we should start recommending people do this rather than explicitly listing each project to include. We can help them out either with a sample or by adding a convention plugin or both.
