### ISSUE TITLE
CopySpec.expand(Map) fails when map has only one entry

### ISSUE THREAD

**Issue by birukoff** [gradle/gradle#14733]
### Expected Behavior
```
            project.copy {
                from("template.txt")
                into(...)
                expand(mapOf("templateVar" to "Some content"))
            }
```
The code above should succeed.

### Current Behavior
The code fails with `java.lang.UnsupportedOperationException (no error message)`, unless you add an extra dummy entry to the map, like `expand(mapOf("templateVar" to "Some content", "dummy" to "blah"))`.

### Steps to Reproduce 
See Github project: https://github.com/birukoff/gradle-copy-bug
1) Create template file that uses only one variable.
2) Invoke copy operation with expand(Map). Pass a map with only one required entry there.
3) See the task fail.
4) Add a useless dummy entry into the map.
5) The task succeeds.

**Comment by tfedyanin** [comment]
I found that problem in method mapOf. It returns a singleton map which is unmodifiable.

I wrote a test that throws the same java.lang.UnsupportedOperationException, and try to make a modifiable copy of properties org.gradle.api.internal.file.copy.FilterChain#expand.
But it's not working, because of groovy.text.SimpleTemplateEngine.SimpleTemplate#make(java.util.Map) uses these properties to write property with key 'out' that used in other parts of Gradle:
org.gradle.api.tasks.CopyTaskIntegrationSpec#useful help message when property cannot be expanded
org.gradle.api.tasks.CopyTaskIntegrationSpec#useful help message when property cannot be expanded in filter chain
org.gradle.api.tasks.CopyTaskIntegrationSpec#useful help message when property cannot be expanded in filter chain

I can create modifiable copy of properties in org.gradle.api.internal.file.copy.DefaultCopySpec#expand, but there are many places with similar signatures and possibly similar problems

**Comment by tfedyanin** [comment]
![expand](https://user-images.githubusercontent.com/1610914/96366139-59fff500-114e-11eb-8886-f5a10b279c67.png)
I found that only one class makes real work in the expand method.

**Comment by tfedyanin** [comment]
I wrote an integration test for this problem and fix in DefaultCopyDetails#expand

**Comment by bmuskalla** [comment]
Seems this has been fixed by the linked PR.

**Comment by fdw** [comment]
I am still running into this error. Gradle is on `7.0.2`, which seems to be the latest.

Offending Gradle config:
```
tasks.withType<ProcessResources> {
    val properties = mapOf("version" to project.version)

    inputs.properties(properties)

    filesMatching("version.properties") {
        expand(properties)
    }
}
```
With just this, I get
```
* What went wrong:
Execution failed for task ':ug-gradle-plugin:processResources'.
> Could not copy file '<snip>/src/main/resources/version.properties' to '<snip>/build/resources/main/version.properties'.
   > java.lang.UnsupportedOperationException (no error message)
```

If I add a gratuitous second entry to the map, it fails.
