### ISSUE TITLE
InputChanges API bug when there is one gradle root project nested inside another

### ISSUE THREAD

**Issue by scott-pollom** [gradle/gradle#14803]
[CompressAssetsTask](https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/tasks/CompressAssetsTask.kt#67) and [PackageAndroidArtifact](https://android.googlesource.com/platform/tools/base/+/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/tasks/PackageAndroidArtifact.java#151) in the Android Gradle Plugin use Gradle's InputChanges API, but [this bug](https://issuetracker.google.com/issues/169701279) shows an example when they don't behave as expected in some cases when one Gradle root project is nested inside another.

### Expected Behavior
Gradle's InputChanges API should yield the correct incremental and non-incremental behavior for cases when one Gradle root project is nested inside another.

### Steps to Reproduce 
Repro project and repro steps are [here](https://issuetracker.google.com/issues/169701279#comment11)

### Your Environment
Gradle 6.6.1
AGP 4.2-alpha13
MacOS

**Comment by liutikas** [comment]
Note, repro project is here (non-google private link):
https://issuetracker.google.com/issues/169701279#comment11

**Comment by wolfs** [comment]
This is the project structure of the reproducer:
```
├── foo
│   ├── build.gradle
│   ├── mylibrary
│   └── settings.gradle
└── settings.gradle
```

The top-level `settings.gradle` includes `:foo:mylibrary`, while `foo/settings.gradle` includes `:mylibrary` as subprojects. That means we have two separate builds, with two separate tasks: `:foo:mylibrary:compressDebugAndroidTestAssets` and `:mylibrary:compressDebugAndroidTestAssets`. Those two tasks output to the same directory, though they have a different task history. That means that those task have overlapping outputs. You can see the overlapping outputs reported in [this build scan](https://ge.gradle.org/s/sw3yudnp5hvxk/timeline?details=sw2vg5yjycllu).

Now we run:
1. `./gradlew :foo:mylibrary:packageDebugAndroidTest`
2. `cd foo`
3. `./gradlew :mylibrary:packageDebugAndroidTest`
4. `cp mylibrary/src/androidTest/assets/checkbox_checked.png mylibrary/src/androidTest/assets/checkbox_checked2.png`
5. `./gradlew :mylibrary:packageDebugAndroidTest`
6. `cd ..`
7. `./gradlew :foo:mylibrary:packageDebugAndroidTest`

So both `:mylibrary:packageDebugAndroidTest` (5) and `:foo:mylibrary:packageDebugAndroidTest` (6) run incrementally and report `checkbox_checked2.png` as a new input file, which is correct.

You can fix the problem by using `includeBuild 'foo'` instead of `include 'foo'`, so there is only one task in an included build.

**Comment by scott-pollom** [comment]
Thanks for investigating, @wolfs . Very useful insights.

I think this is WAI since the overlapping outputs are reported in the build scan.

What I've realized is that the the structure of the *original* project in https://issuetracker.google.com/issues/169701279 is slightly different than the repro example I created here, and so we still have some investigation to do on our side to either (1) modify the original project based on your advise above or (2) create a new repro project and upload it here. But I'm closing this bug for now since I don't think there's any action to be done on your side.
