### ISSUE TITLE
Add support for toolchain selection for vendor/implementation

### ISSUE THREAD

**Issue by bmuskalla** [gradle/gradle#14802]
Not only the version of the JDK is relevant, but also from which vendor as there are some significant differences. Toolchain selection needs to support defining more specific attributes to select the correct toolchain. 

Working on this requires a discussion of how we structure the different dimensions of a java installation as they may overlap:
* Vendor (Oracle, SAP, AdoptOpenJDK, ...)
* Implementation (Hotspot vs J9)
* Packaging (Zulu with or without JavaFX)

**Comment by bmuskalla** [comment]
We need to look into the `JavaInstallationProbe` with regard to more recent JDK vendors. Not all are detected right now (e.g. Coretto).

**Comment by anuraaga** [comment]
@bmuskalla Thanks for working on this. Looking through the documentation PR, it's not clear to me how to specify OpenJ9 for AdoptOpenJDK (hotspot and openj9 are both same jdk vendor but different vm vendor I guess). Would it be worth adding that to the docs? Checking in since now that #14692 and this issue are closed, just wanting to confirm the vm implementation selection is in place :)

**Comment by bmuskalla** [comment]
@anuraaga Thanks for the feedback. Yes, we decided to not make J9 a thing that is selected via a vendor. We instead went with a orthogonal filter. Please checkout this PR that should make it into 6.8. And feel free to provide any feedback (docs are included in the PR as well):
https://github.com/gradle/gradle/pull/15195
