### ISSUE TITLE
More newbie-friendly documentation for the CodeNarc plugin regarding Groovy 3

### ISSUE THREAD

**Issue by rkrisztian** [gradle/gradle#14853]
### Expected Behavior
The documentation could be more verbose about the `codenarc` dependency configuration. It surely says enough for the experienced user (The CodeNarc libraries to use), but it could tell more, like, that `groovy-all` could also be needed to be added there, and that none of the deps in `implementation` or `*Implementation` are reused.

### Context
When someone wants to set up CodeNarc linting for a project with Groovy 3 code, it is not so obvious what pitfalls one might step into. That's what I experienced in https://github.com/CodeNarc/CodeNarc/issues/564 with my example project as demonstration.

**Comment by rkrisztian** [comment]
Well, I tried...

**Comment by eskatos** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

----

On the Gradle side of things this is just a documentation issue but this requires some CodeNarc knowledge.

**Comment by jayg2309** [comment]
is this still active?
can i work on it?
