### ISSUE TITLE
Unable to apply maven metadata to gradle Project

### ISSUE THREAD

**Issue by darshanmehta10** [gradle/gradle#15055]
As per Gradle 6 upgrade [documentation](https://docs.gradle.org/current/userguide/upgrading_version_5.html), artefacts are not queried without metadata (mentioned in [this](https://docs.gradle.org/current/userguide/upgrading_version_5.html#maven_or_ivy_repositories_are_no_longer_queried_for_artifacts_without_metadata_by_default) section of the documentation).

I am writing a `maven plugin` for Gradle which does the following:

- Download maven binary from repo
- Run commands against that binary (i.e. `clean install` etc)

Users will typically have the following in their `gradle` files:

```
apply plugin: 'my-maven'
myMavenVersion = '3.6.0'
```
Users will then be able to pass a command which would be run against this `maven` version.

### Expected Behavior
I am working on upgrading gradle version for this plugin from `5.x` to `6.6`. There are a couple of caveats for this:

- My repo doesn't have `pom` (or metadata) file for maven 3.6.0 (only binaries/zip are available)
- I do not have access to users' projects, so I can't modify their `build.gradle` files to have the following snippet:

    ```
    repositories {
        maven {
            url "http://repo.mycompany.com/repo"
            metadataSources {
                mavenPom()
                artifact()
            }
        }
    }
    ```

To overcome these caveats, I am dynamically adding these in my plugin file, e.g.:

```
class MavenPlugin implements Plugin<Project> {
    //other variables
    void apply(Project project) {
        applyDefaultMavenRepoConfig(project, 'http://repo.mycompany.com/repo')
    }

    void applyDefaultMavenRepoConfig(Project project, String repoUrl){
            project.repositories{ maven { url=repoUrl ; metadataSources { mavenPom(); artifact() } } }
    }
}
```

I expect this to add the required `metaData` to project and work fine.

### Current Behavior
Instead of applying the command, it fails with the following error:
```
> Could not find org.apache.maven:my-maven:3.6.0.
     Searched in the following locations:
       - http://http://repo.mycompany.com/repo/org/apache/maven/my-maven/3.6.0/my-maven-3.6.0.pom
```

### Context
- This works fine with `gradle 5.x`
- My repo has `pom` files for `maven 3.0` so it works fine with `maven 3.0` as well
- I do not have access to users' `gradle` files so I can't ask them to explicitly add `metaData` snippet to their files

### Steps to Reproduce 
- Try applying a plugin with project that requires a dependency which doesn't have `pom` file in repo
- Try applying `metaData` configuration to a `Project` in gradle plugin imperatively (i.e. not by explicitly declaring it in `build.gradle`)

### Your Environment
- Gradle 6.6
- Maven 3.6.0

**Comment by darshanmehta10** [comment]
@big-guy @ljacomet any thoughts on this?

**Comment by ljacomet** [comment]
There a couple things to keep in mind when something like that is needed:
* Your attempt at adding the repository does not work because what you do is add a _different_ repository at the end of the user's repositories list, with the metadata and artifact instructions.
* Were you to modify the snippet to edit the repository definition from users, it could have some weird side effects depending on when your code is executed compared to when their build does resolution. In short, there could be resolution before your modification and resolution after which could lead to different results in corner cases.

However, assuming this is a company plugin and not a public one, it might be OK to identify the repository by its URL and then update its metadata sources.
Something like:

```
project.repositories
    .withType(MavenArtifactRepository)
    .matching { it.url == repoUrl }
    .all { it.metadataSources { mavenPom(); artifact() } }
```

The above is safe whether or not it is executed before or after the repository is added.
(I did not fully test the code so there could be some tweaks to the syntax required)

**Comment by ljacomet** [comment]
Closing as there is no work planned on the Gradle side.
