### ISSUE TITLE
Breaking points are ignored when using 'doLast' in tasks

### ISSUE THREAD

**Issue by IgorJoin** [gradle/gradle#15100]
Hello

In a Kotlin + Gradle + IntelliJ project, I noticed that I can run \ debug (hitting breakpoints) my Main class using one of following tasks defined in gradle.build:

```
// debug works!!
task debugTest1(type:JavaExec) {
    group = "Execution"
    description = "Run the main class with JavaExecTask"
    classpath = sourceSets.main.runtimeClasspath
    main = "temp.Main"
}

// debug works!
task debugTest2() {
    javaexec{
        group = "Execution"
        description = "Run the main class with JavaExecTask"
        classpath = sourceSets.main.runtimeClasspath
        main = "temp.Main"
    }
}
```

However, when adding 'doLast', the debug in IntelliJ runs but ignores breakpoints:
```
// debug ignores breakpoint!
task debugTest3() {
    doLast {
        javaexec{
            group = "Execution"
            description = "Run the main class with JavaExecTask"
            classpath = sourceSets.main.runtimeClasspath
            main = "temp.Main"
        }
    }
}
```

My build.gradle file is similar to this
```
plugins {
    //id 'org.jetbrains.kotlin.jvm' version '1.3.72'
    id 'org.jetbrains.kotlin.jvm' version "1.4.20-RC"
}

group 'MY-COMPANY-GROUP'
version '1.0-SNAPSHOT'


repositories {
    mavenCentral()
}

allprojects {
    compileJava { options.encoding = "UTF-8" }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}
```

I first came to this problem working in a project using Cucumber + Gradle and Kotlin. All my breakpoints are ignored in this project too. The task declaration in that project is as follows:
```
task cucumber() {
    dependsOn assemble, testClasses
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = [/*'--plugin','pretty', */
                    '--glue', 'COMPANY-PACKAGE.cucumber.steps', 'src/test/resources/features',
                    '--tags','not @inProgress']
        }
    }
}
```

My specs are:
- Java: 11
- OS: Windows 10
- Intellij: IntelliJ IDEA 2020.2.3, October 6th build

**Comment by IgorJoin** [comment]
It might be related to this: https://youtrack.jetbrains.com/issue/IDEA-253394

**Comment by mlopatkin** [comment]
@IgorJoin could you please clarify a bit how exactly are you starting a debug session?  Are you using IDEA's GUI to start debugging?
![image](https://user-images.githubusercontent.com/7620037/126813870-8bb00877-433c-4c6e-ba2c-669a0d6fdf09.png)
I see that in this case IDEA is trying to debug a Gradle process instead of the process you're trying to launch. In the first case, it is smart enough to switch to debugging of the spawned process. I suspect (but don't know for sure) that IDEA may have special handling for the JavaExec tasks.

The reproducer project in an archive or as a Github repo may also come in handy because your debugTest2 either gives me errors or debug is not working. Actually, `debugTest2` isn't what you typically want because it executes the `Main` during the configuration phase (so it will spawn the process when executing any task from this project).

**Comment by IgorJoin** [comment]
> @IgorJoin could you please clarify a bit how exactly are you starting a debug session? Are you using IDEA's GUI to start debugging?
> ![image](https://user-images.githubusercontent.com/7620037/126813870-8bb00877-433c-4c6e-ba2c-669a0d6fdf09.png)
> I see that in this case IDEA is trying to debug a Gradle process instead of the process you're trying to launch. In the first case, it is smart enough to switch to debugging of the spawned process. I suspect (but don't know for sure) that IDEA may have special handling for the JavaExec tasks.
> 
> The reproducer project in an archive or as a Github repo may also come in handy because your debugTest2 either gives me errors or debug is not working. Actually, `debugTest2` isn't what you typically want because it executes the `Main` during the configuration phase (so it will spawn the process when executing any task from this project).

@mlopatkin answering your question: I used the built-in debug from IntelliJ, that is, clicking on the build.gradle file and selecting debug as. The key point of this problem is the 'doLast' option in the script. Why, when it is present, the debug behaves like it is not debugging the java process (ignoring breakpoint)? Just out of curiosity, I had to use Cucumber's JUnit runner framework [here](https://github.com/ZupIT/beagle/blob/main/tests/appium/project/src/test/kotlin/br/com/zup/beagle/cucumber/steps/Runner.kt) to be able to hit breakpoints

**Comment by big-guy** [comment]
This is probably the "best" way to do this:
```
task debugTest1(type:JavaExec) {
    group = "Execution"
    description = "Run the main class with JavaExecTask"
    classpath = sourceSets.main.runtimeClasspath
    main = "temp.Main"
}
```
IntelliJ has special handling to enable debug because this is a JavaExec task.

Like Mike said, this version runs this java command every time you run any Gradle task, which isn't what you want:
```
task debugTest2() {
    javaexec{
        group = "Execution"
        description = "Run the main class with JavaExecTask"
        classpath = sourceSets.main.runtimeClasspath
        main = "temp.Main"
    }
}
```

This doesn't work because IntelliJ can't see that a Java process is going to be started. If you wanted to make debugging work, I think you'd have to add the debug options to the `javaexec {}` all the time.
```
task debugTest3() {
    doLast {
        javaexec{
            group = "Execution"
            description = "Run the main class with JavaExecTask"
            classpath = sourceSets.main.runtimeClasspath
            main = "temp.Main"
        }
    }
}
```
