### ISSUE TITLE
java core dumps on jansi lib on Sles10

### ISSUE THREAD

**Issue by aflat** [gradle/gradle#1519]
OS: sles10
java: build 1.8.0_121-b13
gradle: 3.3

Trying to run a basic gradle build on sles 10 and the jvm core dumps due to libjansi.so. Looks like this issue https://github.com/fusesource/jansi/issues/6 old, but still relevant. Started as of gradle 3.1. 3.0 works.

**Comment by aflat** [comment]
if I run with --console plain option, everything works. I assume it's due to skipping to load jansi

**Comment by bmuschko** [comment]
Gradle 3.1 usesjansi-1.13. Gradle 3.0 uses a much older version: jansi-1.2.1. That's is purely a Jansi issue as stated in the issue you are referring to:

> Jansi is known to not work on SUSE 10.

For now you'll need to run with the `--console` option which does not use Jansi. The the long run [we want to bring in our own native console support](https://groups.google.com/forum/#!searchin/gradle-dev/jansi%7Csort:relevance/gradle-dev/6oXYgcISq_M/cd7owKXtAQAJ) so we don't have to rely on Jansi anymore due to its known issues.
