### ISSUE TITLE
projects foreach

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#15204]
inspired by https://yarnpkg.com/cli/workspaces/foreach

## Goal

realistically my goal is to have a good way to do `--write-locks` or not automatically delegated to subprojects tasks ...

## Proposed

```
gradle projects foreach dependencies --write-locks
```

or

```
gradle projects foreach dependencyInsight --project log
```

## some of the filtering functionality
it's kind of poorly documented but in workspaces you can do this

```json
    ":g:wsrun": "yarn $DIR workspaces foreach --parallel --topological-dev --recursive --verbose --interlaced run",
```

which is obscure for, do the obvious things by default.... but the one thing here that is not an obvious thing... is the recursive option and a directory that can be passed before workspaces, personally I think it's a bit crazy that it's a directory. 

What these options mean in gradle language would be. Run this task, and any tasks it depends on in this project, and any project it depends on. Perhaps more simply put, pick a project, run that task and make sure that any dependents also run it, not running for every single workspace just those. Not entirely dissimilar  from doing `gradle :foo:build` 

given a project dependency structure like

```
  |- app
       |- lib
  |- e2e
       |- app
```

```
gradle projects foreach --from app dependencies
```
would run dependencies for app and lib, but not e2e

## Workarounds

currently doing this

```kotlin
tasks.dependencies { dependsOn(subprojects.map { it.tasks.dependencies }) }
```

```
gradle dependencies --write-locks
```

sorry if this is somehow already possible

**Comment by donat** [comment]
The problem you are facing is the special handling of the `dependencies` task.

If you execute `gradle anyOther` then the `anyOther` task will be executed in the current project and all of the subbprojects. In other words, `anyOther` is a [task selector](https://docs.gradle.org/current/userguide/command_line_interface.html#executing_tasks_in_multi_project_builds).

The `dependencies` task is special, because it will be executed only on the current project, even it is invoked as a task selector. We'll discuss internally whether we can remove this special handling in a future Gradle version.

The dependency locking documentation shows a [solution](https://docs.gradle.org/current/userguide/dependency_locking.html#lock_all_configurations_in_one_build_execution) for your case: introduce a new task in all subprojects that forces dependency resolution for all configurations:

```
allprojects {
	  tasks.register("resolveAndLockAll") {
	      doFirst {
	          require(gradle.startParameter.isWriteDependencyLocks)
	      }
	      doLast {
	          configurations.filter {
	              // Add any custom filtering on the configurations to be resolved
	              it.isCanBeResolved
	          }.forEach { it.resolve() }
	      }
	  }
}
```

With the following snippet in place you can lock dependencies in all subprojects in a build with  

    gradle resolveAndLockAll --write-locks

**Comment by xenoterracide** [comment]
I'm curious, why is that better than this (at the root project)? With the same `--write-locks`

```
tasks.dependencies {
  dependsOn(subprojects.map { it.tasks.dependencies })
}
```

**Comment by donat** [comment]
The only difference is that the proposed solution doesn't introduce task dependencies crossing project boundaries.

I agree, it's counterintuitive that you cannot write a task that launches a build that does dependency locking without `--write-locks` in the command line.

**Comment by xenoterracide** [comment]
But why make an easy thing easy right? Why not have to make two paragraphs of code in order to actually have something that should probably work out of the box work.
