### ISSUE TITLE
Provide a property to set a custom user agent for http/s requests

### ISSUE THREAD

**Issue by bernardladenthin** [gradle/gradle#1521]
A custom user agent will be required in a restricted environment. Some companies only allow traffic through a proxy and expect a registered and/or modified user agent.

### Expected Behavior
Gradle should provide a setting to change the user agent. It should be similar to the proxy settings desribed in the [build environment](https://docs.gradle.org/current/userguide/build_environment.html) documentation.

### Current Behavior
There is no possibility. You have to modify the class files and patch your gradle installation.

### Steps to Reproduce (for bugs)
Monitor the traffic. Use a firewall.

**Comment by bernardladenthin** [comment]
If accepted, this feature should be added to the [build environment](https://docs.gradle.org/current/userguide/build_environment.html) documentation.

**Comment by bmuschko** [comment]
We discussed this request a while back internally and feel very reluctant to make such a change.

The http transport is essentially an implementation detail:

- We want to be able to change the http transport at any time, to use whichever implementation we think is appropriate and to make whatever http requests we think are appropriate. The more we expose the less we can change.
- We want to add features that serve a good range of use cases. So far, there haven’t really been any good use cases for tweaking the http requests, they’ve all been really some missing higher level feature, such as credentials.

> There is no possibility. You have to modify the class files and patch your gradle installation.

Does this mean that you cannot use Gradle at all because your organization does not allow requests with the default user agent?

**Comment by bernardladenthin** [comment]
Hi, thank you for the internal discussion.

In many companies exist an internal rule that require a fixed user agent. The gradle user agent is dynamic, the version might be constant for builds. But thats not the only restriction and risk coming from gradle currently.

Gradle lacks information which could be used for user / company tracking and yell internal versions. Gradle sends the operating system and its version, as well as the java vendor and its version.

A simple question might be, why are you sending this information? A simple Gradle/\<Version\> should be enough. Is there a reason why you require a very verbose user agent? In the next release you may include the mac address or an UUID? *joke*

There exist a very wide range of java implementations (e.g. https://developer.ibm.com/javasdk/downloads/ ). In combination with an unique IP address range an ISP or an IXP could track downloads and can combine specific java versions with specific artifacts. The result is a local nexus repository and gradle could not be used with a direct connection.

You are right that you don't want to implement a specific detail, especially in the http layer. And that's the reason why this should be a complete user specific property, which could be completely overwritten.

I'm not talking about private developers sitting with their laptop in a coffeehouse, carrying the complete source code on an unencrypted USB flash drive. I'm talking about professional developers in companies with a security policy. The environment should be secure and less verbose as much as possible. That's what I'm expect from an enterprise grade solution.

Best regards from Berlin, Bernard

**Comment by bmuschko** [comment]
> In many companies exist an internal rule that require a fixed user agent.

Over the past 4 years I have worked with many organizations, big and small, enterprises and startups. So far I have not encountered that rule. I think that's a generalized statement though I won't deny that it might be the case for an organization.

> But thats not the only restriction and risk coming from gradle currently.

I can't quite see what the risk is. Can you elaborate?

> Gradle sends the operating system and its version, as well as the java vendor and its version. A simple question might be, why are you sending this information?

Not quite sure. It might not have been conscious decision based on a specific reason. I can see anyone else knows more. 

> The environment should be secure and less verbose as much as possible. That's what I'm expect from an enterprise grade solution.

I still don't get why setting a custom user agent would be a "secure" solution. Are you saying this because your organization requires a specific user agent for HTTP requests? I am not sure if I'd necessarily call that "secure".

**Comment by bernardladenthin** [comment]
I'm sorry I can not be more specific. The information should not be disclosed to the public.

From my (disclosable) point of view, there are two points that Gradle can/should officially support:

* There might be the requirement for Gradle not to send out details to the outside. A specific Java environment is not directly exposed. No matter how safe or unsafe these information are judged by strangers. The word gradle and some java peroperties should not appear. As user agent the following could be set:
  * "Apache-HttpClient/4.5.2 (Java/1.8.0_45)" or
  * "Apache-HttpClient/4.5.1 (Java/1.7.0_09)" or
  * "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; P&G/Gillette - RK; .NET CLR 1.1.4322; .NET CLR 2.0.50727)"

You can find some interesting user agents on http://ua.theafh.net/

* Gradle could also be used in a kind of an undercover mode. There could be an environment in which as far as possible not to be known, gradle is used at all, for whatever reasons for strangers. This has something to do with law and the attitude and contracts of the company. Gradle should be able to identify as Maven. When Gradle sends this information first, it is immediately recognized that Gradle is being used. May set the user agent to
  * "Apache-Maven/3.3.9 (Java 1.8.0_121; Windows 10 10.0)".

Btw., Maven allows changing the user agent: http://stackoverflow.com/questions/1561658/how-can-the-user-agent-be-changed-in-maven

Currently, the user is forced to disclose this information and I see no reason why you have to enforcing it. If a user whish to change it, whyever, he is prevented from doing so. The user doing this on his own risk.

As an additional note:
Commit 71cd39fd546237e3958feada516816e08ebebe9a introduce "Added JVM and OS information to the user agent.".

Afterwards, tests were added by René, commit 5139195ecdd5e13ca8b750f81487e46cf3c3d56e and 5460740e98df6536213a216d9dc9ef55ec6e518c are interesting.

Best regards from Berlin, Bernard

**Comment by bmuschko** [comment]
> This has something to do with law and the attitude and contracts of the company. Gradle should be able to identify as Maven.

I'll be honest - this sounds very wrong. I understand that you might want to set a user agent for tracking purposes but your use cases sound more like disguising what tool you are actually using.

> Commit 71cd39f introduce "Added JVM and OS information to the user agent.".

I am not quite sure why this was introduced but it's only for the download of the Wrapper and not for other HTTP downloads. @breskeby Maybe you remember. This was before I was with the company.

Either way I don't think we will want to introduce magic properties for reasons mentioned above. @adammurdoch Could you please give you opinion as well so we make the final call?

**Comment by bernardladenthin** [comment]
I think you misunderstand me fundamentally wrong. I personally do not care whether you implement this or not. The changes I'll need to build a hardened gradle I can implement on my own. This mistake is in my opinion dangerous and I just want to announce it.

You may have a certain responsibility towards your user. If somebody don't want that anybody can see what environment is in use, you say this is wrong and want enforce it? Why? Then please vote against TOR, Obfsproxy and any network traffic obfuscation. In your opinion all of these seems pointless.

You did not even look at the problem properly:
> I am not quite sure why this was introduced but it's only for the download of the Wrapper and not for other HTTP downloads.

The method UriTextResource#getUserAgentString() will be used for **many or _all_ downloads and outgoing connections.** The source of the initial creator was copy and pasted. The static method will be called from HttpClientConfigurer. You send the user agent with every request for an artifact into the world.

And for the question why any server should see my operating system / version I dont get an answer. Simple downloads should work without any os version / name / java version / vendor.

If you really want to enjoy the reputation and want to send `Gradle/\<Version\>` through the network, please remove the java and operating system details. You don't have to implement the system property. This is a standard use case of many tools and you call it *magic property*.

If you wouldn't overwriting everywhere the useragent, the **standard java property** http.agent would work. So this isn't a new magic property. You have explicit disabled a **default property** with your code. http://download.java.net/jdk7/archive/b123/docs/api/java/net/doc-files/net-properties.html

If somebody uses `-Dhttp.agent=` and this wont work you say he shouldn't use it because you don't want it?

Best regards from Berlin, Bernard

**Comment by Mathiasdm** [comment]
> Over the past 4 years I have worked with many organizations, big and small, enterprises and startups. So far I have not encountered that rule. I think that's a generalized statement though I won't deny that it might be the case for an organization.

Unfortunately, I have this problem at my company. Only a select number of user agents are allowed to be used through our company proxy, so I need to be able to set the user agent (or at least add a specific string to it).

**Comment by conspicuousClockwork** [comment]
@bmuschko what do you think of at least appending information to the default user agent value? I can definitely see why the team would not want to allow overriding the whole value.

>We want to be able to change the http transport at any time, to use whichever implementation we think is appropriate and to make whatever http requests we think are appropriate. The more we expose the less we can change.

Appending a string to the end of the user agent should not affect the team's ability to use whichever implementation they'd like.

>We want to add features that serve a good range of use cases. So far, there haven’t really been any good use cases for tweaking the http requests, they’ve all been really some missing higher level feature, such as credentials.

1 - The aforementioned company policy. In most cases where user agent modification is needed, the proxy in question whitelists user agents instead of blacklisting them. Usually this also means that they are looking for a specific substring. In my case we use a specific developer tag to track activity and also allow those requests through while foregoing some other proxy specific formalities.

2 - Keeping track of internal Gradle use. While the default user agent value provides plenty of valuable information, having the ability to add our own information can be invaluable given the proper context.

I'll open a PR when I get the chance, but I would absolutely appreciate to hear your thoughts on this.

**Comment by rpalcolea** [comment]
+1 for this. This would be useful for us, too
