### ISSUE TITLE
Android build fails with Unresolved reference issue with Gradle 6.8-rc-1

### ISSUE THREAD

**Issue by kozaxinan** [gradle/gradle#15397]
### Expected Behavior

Android build needs to finish without problem.

### Current Behavior

Android build fails with `Unresolved reference` issues.

### Context

Problem occurs with Gradle 6.8-rc-1 version. It doesnt exist with Gradle 6.7 and 6.7.1
We use Kotlin 1.4.20 and I tested with AGP 4.1.1 and 4.2.0-beta01

### Steps to Reproduce 

I couldnt reproduce it on simple sample repository.

Gradle tasks for resource compilation/generations are up-to-date or from cache but `build/intermediates` folder is mostly empty.
<img width="433" alt="Screenshot 2020-12-02 at 11 47 17" src="https://user-images.githubusercontent.com/2559837/100849951-237b0100-3494-11eb-96c3-6d774bf1fe0c.png">

When running gradle tasks (assembleDebug) with -rerun-tasks, build finish without problem.
~Disabling gradle cache doesnt change the failed usecase.~
Running tasks with --rerun-tasks put necessart files in build folder and next build without rerun-task finish with success. But issue come again after clean build.

### Your Environment

Please find scan dumps. Successful one is run with --rerun-tasks.
[Archive 2.zip](https://github.com/gradle/gradle/files/5627945/Archive.2.zip)

Cache and vfs watch are enabled.

**Comment by big-guy** [comment]
Hi @kozaxinan 

Is this something you've been able to reproduce with your real project?

Could you take a look in your local build cache (default `~/.gradle/caches/build-cache-1`) for the cache entries...

f4d88a6899a9ab010d2ad6fe267051eb (this should be from the failed build)
d0cca04be6bf6c3e8c6dcfadca88033b (this should be from the successful build)

These are tar files that you should be able to extract.  The contents should be for the `:base-android:generateDebugRFile` task.  Are the generated R files different between these two cache entries?

My suspicion is that one of the tasks that are up-to-date/from cache should really be running and that's why `--rerun-tasks` fixes it.

On your GE instance, could you go to the failing build scan, find `:base-android:generateDebugRFile` from the timeline view and click "View origin build scan" on the pop-up. This should take you to the build scan that produced this cache entry. Could you send us that build scan too? If you don't have the "View origin" link, it just means that we don't have a build scan for it.

Thanks!

**Comment by kozaxinan** [comment]
`f4d88a6899a9ab010d2ad6fe267051eb` and `d0cca04be6bf6c3e8c6dcfadca88033b` have same content.

Please find the origin build for `f4d88a6899a9ab010d2ad6fe267051eb` cache entry.
[ufroklz6dtol4.scandump.zip](https://github.com/gradle/gradle/files/5641010/ufroklz6dtol4.scandump.zip)

There is also a difference for task dependencies of 

With 6.7.1

<img width="250" alt="Screenshot 2020-12-04 at 09 52 55" src="https://user-images.githubusercontent.com/2559837/101131525-7da3cf80-3616-11eb-96d0-d905e8d648b8.png">

With 6.8-rc-1

<img width="241" alt="Screenshot 2020-12-04 at 09 58 19" src="https://user-images.githubusercontent.com/2559837/101131985-3f5ae000-3617-11eb-864b-603ac6d7678b.png">

I tested 6.8-rc-1 today. base-android cache problem is gone but `Unresolved reference` problem still exists for other modules. I can reproduce this issue for every build after a clean call.

**Comment by eskatos** [comment]
Hi @kozaxinan,

Would it be possible for you to run those build again and share the build scan dumps with _Capturing task input files_ enabled?
See https://docs.gradle.com/enterprise/gradle-plugin/#capturing_task_input_files about how to do that.

Reproducing the _origin_ scan won't be easy. But the _success_ and _failure_ scans with the extra inputs data should help understand what is happening.

Thanks in advance

**Comment by kozaxinan** [comment]
`captureTaskInputFiles` should be enabled in the dumps I already shared. If they dont have, I dont know what is missing from our configuration.

**Comment by eskatos** [comment]
@kozaxinan indeed they have the data already, I was not looking at the right place and missed that, thanks! Digging further

**Comment by big-guy** [comment]
Hi @kozaxinan - could you look at `:base-android:packageDebugResources` for the failing build and send us the origin build scan for that cache entry?

It looks to me that on the successful build, this task has >100 files as an output and on the failing build, this task has 10 files restored from the cache.

Do you have a set of steps you can run on your real build to cause this to happen reliably?

**Comment by kozaxinan** [comment]
@big-guy I can reproduce this again tomorrow. But last time I checked, issue moved to different module but same issue. I run assembleDebug after clean call. Thats all. I can verify that build folder has less files in it when I upgrade to 6.8rc1.

Tomorrow i will build again with 6.8 and get the dumps you asked.

**Comment by big-guy** [comment]
@kozaxinan that would be great.  In particular, please pay attention to the steps you take and which version of Gradle you're running with at each point. 

I'm curious if you're doing something like this:

- Build with 6.7
- Upgrade to 6.8 RC1
- Build with 6.8 RC1
- Run clean with 6.8 RC1
- Build again (this fails)

**Comment by kozaxinan** [comment]
[Archive 3.zip](https://github.com/gradle/gradle/files/5665951/Archive.3.zip)


- Build with 6.7 ------------ clean assembleDebug -> succeess
- Upgrade to 6.8 RC1 ------ wrapper -> success
- Build with 6.8 RC1 ------- assembleDebug -> fail
- Run clean with 6.8 RC1 --- clean assembleDebug -> fail

**Comment by eskatos** [comment]
Thanks @kozaxinan.

The last scans confirm our suspicions but don't provide enough detail to pinpoint the problem.

Could you please try running the sequence below with some added diagnostics?

You would use `6.8-branch-am_diagnostics-20201209135902+0000` instead of `6.8-rc-1` and run with the `GRADLE_TASK_DIAGNOSTICS` environment variable set to `true`.

Each run will produce a file named `task-diagnostics-<some-id>.log` in the build root directory. Please attach these here linking them to what step you took the same way you named the scan dumps attached above.

Sequence is as follows:

1. `./gradlew wrapper --gradle-version=6.8-branch-am_diagnostics-20201209135902+0000`
2. `GRADLE_TASK_DIAGNOSTICS=true ./gradlew clean assembleDebug`
3.  `GRADLE_TASK_DIAGNOSTICS=true ./gradlew --rerun-tasks clean assembleDebug`

Step 2 is expected to fail.
Step 3 is expected to succeed.

**Comment by kozaxinan** [comment]
Build fails with a plugin issue with gradle enterprise. @eskatos I couldnt find root cause of that. With `GRADLE_TASK_DIAGNOSTICS=false`, this problem doesnt happen.

```
GRADLE_TASK_DIAGNOSTICS=true ./gradlew clean assembleDebug --stacktrace

FAILURE: Build failed with an exception.

* Where:
Settings file '/Users/skozak/StudioProjects/is24-android-app/settings.gradle' line: 2

* What went wrong:
An exception occurred applying plugin request [id: 'com.gradle.enterprise', version: '3.5']
> Failed to apply plugin 'com.gradle.enterprise'.
   > Could not create service of type TaskExecutionGraphInternal using GradleScopeServices.createTaskExecutionGraph().
      > The root project is not yet available for build.

```

**Comment by eskatos** [comment]
Sorry about that. It worked fine on the builds I tried with.
Please try with `6.8-branch-am_diagnostics-20201210122012+0000`, this version should fix that problem.

**Comment by kozaxinan** [comment]
[Archive.zip](https://github.com/gradle/gradle/files/5675472/Archive.zip)

As expected normal run failed and running with --rerun-tasks succeed.

**Comment by big-guy** [comment]
Hey @kozaxinan - which task failed on the normal run?

**Comment by kozaxinan** [comment]
I run the task requested at here https://github.com/gradle/gradle/issues/15397#issuecomment-741822744
And added task names to log file name.
`clean assemleDebug` failed in compile stage because of missing resource generation.

**Comment by big-guy** [comment]
OK, in the failing build, we've seen it fail for `:cosma-android:compileDebugKotlin` and `:base-android:compileDebugJavaWithJavac` when running assembleDebug.  Which task failed now? We're trying to work backwards from the failing task to figure out what may be different between the working/failing builds.

**Comment by kozaxinan** [comment]
This time `:cosma-android:compileDebugKotlin` is failed. Please also find the scan dumps of the diagnostic runs
[Archive 4.zip](https://github.com/gradle/gradle/files/5675718/Archive.4.zip)

Diagnostic logs
[Archive.zip](https://github.com/gradle/gradle/files/5675721/Archive.zip)

**Comment by eskatos** [comment]
Thanks @kozaxinan 
It seems the `MergeResources` tasks are part of a hard to solve puzzle.

We noticed that you use the 1.0.13 version of the android.cache-fix plugin.
Could you try upgrading it to 1.0.14? That version added support for AGP 4.1.1 and 4.2.0-beta01

**Comment by kozaxinan** [comment]
In the latest scans we have 1.0.14 of Cache fix plugin. So I already tested with 1.0.13 and 1.0.14.

**Comment by eskatos** [comment]
Ah we missed that. Too many moving pieces. Thanks

**Comment by big-guy** [comment]
Hi @kozaxinan,

A few more things we'd like you to try...

1. Can you disable parallel execution (run with `--no-parallel` or disable it in your gradle.properties) and try running `gradle clean assembleDebug`? You'll need to clean your local build cache first so that we don't get hits from the previous builds. Please leave the build cache enabled. Does this fail?
2. Keeping parallel off, can you add this to your root project's build script:
```
allprojects {
    tasks.withType( com.android.build.gradle.tasks.MergeResources).configureEach {
        outputs.cacheIf { false }
    }
}
```
and run `gradle clean assembleDebug` again. Does this pass?
3. Assuming 2 passed, remove the code from the root build script and keep parallel off.  Run `gradle clean assembleDebug -Dorg.gradle.caching.debug=true` with 6.8 RC1.  Run this again with 6.7.1.  Does this fail? Can you send us the logs for each of these builds?

**Comment by kozaxinan** [comment]
Please find the result and dumps.

1. Failed 
2. Failed
3_1. Failed
3_2. Success

[Archive 5.zip](https://github.com/gradle/gradle/files/5681569/Archive.5.zip)

**Comment by kozaxinan** [comment]
Build succeed without 'gradle/gradle-cache-fix.gradle' plugin.

[ohpczmn3xy632.scandump.zip](https://github.com/gradle/gradle/files/5681670/ohpczmn3xy632.scandump.zip)

**Comment by eskatos** [comment]
Thanks again @kozaxinan, this round of tests confirmed a hunch we had, especially the fact that the build succeeds without the android cache fix plugin.

Could you please re-enable that plugin and try with version `6.8-branch-wolfs_resolve_task_props_later-20201212152225+0000`?
It's 6.8 branch plus a tentative fix.

**Comment by kozaxinan** [comment]
[2xfozamifvtre.scandump.zip](https://github.com/gradle/gradle/files/5683447/2xfozamifvtre.scandump.zip)

`clean assemble` is successful with `6.8-branch-wolfs_resolve_task_props_later-20201212152225+0000` even when gradle cache fix plugin is applied.

**Comment by eskatos** [comment]
Awesome, thank you @kozaxinan!

**Comment by wolfs** [comment]
Fixed via https://github.com/gradle/gradle/pull/15531 for 6.8 RC2.
