### ISSUE TITLE
Deprecate BuildInvocations Tooling API model

### ISSUE THREAD

**Issue by donat** [gradle/gradle#15408]
The TAPI offers confusing functionality with regard to the available tasks. The `BuildInvocations` and the `GradleProject` model both exposes the available task graphs.  Alone that should call for a cleanup. On top of that, the `BuildInvocations` model itself is confusing for the reasons below:
- It doesn't expose project hierarchy. The model has generated in the context of the root project and all task paths are relative to that.
- The exposed `TaskSelector` instances implement an arbitrary grouping of tasks. Executing a task selector runs the same task on the target projects and all of the subprojects where it exists. This imitates the CLI use-case when the user executes `gradle someTask` in a subproject. However, if needed this can be easily implemented with the `GradleProject` model (as it is done in[ Buildship](https://github.com/eclipse/buildship/blob/17909a1ddf5bc62f63d15f18d1bdf3de569d0665/org.eclipse.buildship.ui/src/main/java/org/eclipse/buildship/ui/internal/view/task/BuildInvocations.java)).

**Comment by adammurdoch** [comment]
> This imitates the CLI use-case when the user executes gradle someTask in a subproject. However, if needed this can be easily implemented with the GradleProject model (as it is done in Buildship).

We should not be duplicating this logic in the tooling API client, as Buildship is doing. The logic is specific to the target version of Gradle, and may change over time, as just happened in 6.8. Instead of hard coding version specific behaviour in the client, the client should query the target Gradle version for the ways the build can be invoked (that is, the available build invocations) and then ask the target Gradle version to run a specific invocation.

That is, we should not deprecate Buildinvocations, but improve it if it has short-comings. We definitely should not be duplicating the behaviour in the client.
