### ISSUE TITLE
wrapper failed to upgrade to 6.7, possibly choice wrong local installation

### ISSUE THREAD

**Issue by iceback** [gradle/gradle#15415]
I am/was on version 6.3.  I'm moving to java 15 and read that gradle 6.7 was more compatible so I ran (in my current active project directory)

> ./gradlew wrapper --gradle-version=6.7

### Expected Behavior
gradle 6.7 installed
### Current Behavior

> ./gradlew wrapper --gradle-version=6.7
Downloading https://services.gradle.org/distributions/gradle-5.2.1-all.zip
..............................................................................................................................

Welcome to Gradle 5.2.1!

Here are the highlights of this release:
 - Define sets of dependencies that work together with Java Platform plugin
 - New C++ plugins with dependency management built-in
 - New C++ project types for gradle init
 - Service injection into plugins and project extensions

For more details see https://docs.gradle.org/5.2.1/release-notes.html

Starting a Gradle Daemon (subsequent builds will be faster)
java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7
	at org.codehaus.groovy.vmplugin.VMPluginFactory.<clinit>(VMPluginFactory.java:43)
	at org.codehaus.groovy.reflection.GroovyClassValueFactory.<clinit>(GroovyClassValueFactory.java:35)
	at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
        
         Many stacktrace elements elided

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.reflection.ReflectionCache

gitanmax:sgs4$ gradle --version

------------------------------------------------------------
Gradle 6.6
------------------------------------------------------------

Build time:   2020-08-10 22:06:19 UTC
Revision:     d119144684a0c301aea027b79857815659e431b9

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          15.0.1 (Oracle Corporation 15.0.1+9-18)
OS:           Linux 5.4.0-54-generic amd64

### Context

Here's my .gradle/wrapper/dists dir list
.gradle/wrapper/dists:
  total used in directory 20 available 817713520
  drwxr-xr-x 5 rob rob 4096 Dec  2 22:31 .
  drwxr-xr-x 3 rob rob 4096 Apr  8  2020 ..
  drwxrwxr-x 3 rob rob 4096 Dec  2 22:31 gradle-5.2.1-all
  drwxrwxr-x 3 rob rob 4096 Nov  4 07:27 gradle-6.1.1-bin
  drwxrwxr-x 3 rob rob 4096 Sep 24 17:32 gradle-6.1-bin
And my .gradle/deamon
  /home/rob/.gradle/daemon:
  total used in directory 88 available 817726296
  drwxr-xr-x  9 rob rob  4096 Aug 21 13:59 .
  drwxr-xr-x 11 rob rob  4096 Apr 21  2020 ..
  drwx------  2 rob rob  4096 Apr  2  2020 4.4.1
  drwx------  2 rob rob  4096 Dec  2 22:33 5.2.1
  drwx------  2 rob rob  4096 Dec  2 14:30 6.1
  drwx------  2 rob rob 12288 Nov  4 07:28 6.1.1
  drwx------  2 rob rob 12288 Sep 15 12:27 6.3
  drwx------  2 rob rob  4096 Aug 11 16:09 6.5
  drwx------  2 rob rob 36864 Dec  2 22:11 6.6

### Steps to Reproduce 

Not sure this is possible?
### Your Environment

Build scan URL:
 ./gradlew build --scan

FAILURE: Build failed with an exception.

* What went wrong:
Could not initialize class org.codehaus.groovy.runtime.InvokerHelper

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s

**Comment by iceback** [comment]
More anomalies:
which gradle
/opt/gradle/latest/bin/gradle  #pretty normal
gitanmax:sgs4$ cd /opt/gradle
gitanmax:gradle$ ls
gradle-6.6  latest
gitanmax:gradle$ ls -lF
total 4
drwxr-xr-x 5 root root 4096 Feb  1  1980 gradle-6.6/
lrwxrwxrwx 1 root root   10 Aug 21 13:58 latest -> gradle-6.6/
gitanmax:gradle$ cd gradle-6.6/
gitanmax:gradle-6.6$ ls -l
total 44
drwxr-xr-x 2 root root  4096 Feb  1  1980 bin
drwxr-xr-x 2 root root  4096 Feb  1  1980 init.d
drwxr-xr-x 3 root root  4096 Feb  1  1980 lib
-rw-r--r-- 1 root root 23606 Feb  1  1980 LICENSE
-rw-r--r-- 1 root root   803 Feb  1  1980 NOTICE
-rw-r--r-- 1 root root   976 Feb  1  1980 README
"Feb 1 1980" seems a stretch!  I just built this machine a year ago

**Comment by ljacomet** [comment]
The most likely explanation is that when you ran `./gradlew wrapper --gradle-version=6.7` your `gradle/wrapper/gradle-wrapper.properties` contained a reference to Gradle version 5.2.1.

In order to update that file, Gradle will still evaluate your project. For doing so, it needs the _current_ version referenced by the `gradle-wrapper.properties`. And because that was an older version than expected, it failed to setup your project after being downloaded.

You have two options:
* Edit the `gradle-wrapper.properties` by hand, then run `./gradlew wrapper --gradle-version=6.7` to make sure the scripts and `wrapper.jar` are up-to-date as well
* Run `gradle wrapper --gradle-version=6.7` which will use your local 6.6 and thus should be able to setup your project and then update the wrapper.

It is quite unlikely there is anything wrong in Gradle itself given what happened.

**Comment by iceback** [comment]
Thank you!

Not wanting to get bitten again, I opted for the first path and set the 
property to version 6.6.1.  This succeed in the sense that I was back to 
at running version 6.6.  I did not realize that these steps were only 
going to upgrade the current project to gradle 6.7.  Maybe that's a good 
thing.

I do understand that my situation is an extreme edge case but still take 
it as a bug that, even within the confines of a specific project, gradle 
would allow itself to retrograde to a version incompatible with the 
project's chosen jvm.

Thanks again for the quick and accurate response

rjs

**Comment by ljacomet** [comment]
> gradle
would allow itself to retrograde to a version incompatible with the
project's chosen jvm

According to my understanding, this is not exactly what happened: the project was updated using an _local_ Gradle installation to use more recent features, including upgrading the Java version used to run Gradle.
But when doing that, the wrapper information was never updated in the project.

So when the wrapper was invoked next, it failed.

There is nothing Gradle can do in that situation. As a project maintainer, if you use the wrapper, make sure it stays up-to-date. If you do not use it, then delete it so that no one stumbles into such a situation.

Note that running the Gradle `wrapper` task can be done from a locally installed Gradle. It does not have to be run from `gradlew`.
