### ISSUE TITLE
Gradle ignoring <snapshotVersions> while downloading from Nexus

### ISSUE THREAD

**Issue by Shriranjanidev** [gradle/gradle#15632]
**Steps to reproduce:**
1) Publish a jar with 0.0.1-SNAPSHOT as version.
2) Make changes to the JAR and publish using the same snapshot version.
3) Now import the jar with version 0.0.1-SNAPSHOT.

**Expected:**
Pickup last published snapshotVersion (Step 2 JAR)

**Actual:**
Picks up the first snapshotVersion (Step 1 JAR)

**Related stackoverflow discussion:**
https://stackoverflow.com/questions/56041471/copy-newest-jar-file-from-nexus-server-with-gradle

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

As [documented](https://docs.gradle.org/current/userguide/dynamic_versions.html#sub:declaring_dependency_with_changing_version), Gradle caches changing versions for 24h by default.

You can either change that value in your build script or force a refresh with the CLI flag `--refresh-dependencies`.
