### ISSUE TITLE
`–tests` does not override include filters

### ISSUE THREAD

**Issue by masc3d** [gradle/gradle#1571]
Documentation states that
 > When the command line option is used, the inclusion filters declared in the build script are ignored. 

when  `--tests`  refers to a class/method outside of the `include` scope, the behaviour varies depending on which method is used to configure inclusion, but will never be as expected

* `test.include`: test will never be found if it's out of scope of this expression
* `test.filter.includeTestsMatching` or `test.filter.setIncludePatterns`: test will run, but so will all other ones matching the include

### Expected Behavior
Inclusion filters should be ignored

### Current Behavior
Doesn't override inclusion filters

**Comment by masc3d** [comment]
in addition I would also expect `--tests` to override category filters `useJUnit.includeCategories` which is also not the case.

**Comment by bmuschko** [comment]
@masc3d Would you be interested in provide a pull request to fix this?

**Comment by masc3d** [comment]
@bmuschko as I'm not familiar enough with the codebase, I can't supply a comprehensive fix at this time

**Comment by blindpirate** [comment]
@bmuschko I have created #2172 , would you please take a look and give me some advice?

**Comment by jjohannes** [comment]
@blindpirate thanks for the PR. The changes look good to me. But we should extend the test coverage as we are changing some behavior here. I added comments abut that to the PR.

**Comment by jjohannes** [comment]
Thanks @blindpirate! The PR was merged and will be part of 4.1.

**Comment by jjohannes** [comment]
@masc3d @blindpirate I am afraid I have to reopen this.

We had an internal discussion about this change. Now that we are able to actually try this, we realized that filters defined in build scripts are an intended way to organise tests. For example, to split them into several test tasks (e.g. `slowTest` and `fastTest`). 
The intention of `--tests` filtering is to only run part of your build (e.g. during local development for faster feedback) and **not** to alter the build structure.
So overriding definitions from the build scripts with `--tests` does not seem right for most cases.

Still, we have an inconsistency here, because of different behaviours for `test.include` and
`test.filter.includeTestsMatching`. And the documentation is definitely misleading. 

So my proposal is to turn this change around. Rather than making `--tests` override everything, we make sure that the `--tests` filters are always applied on top of the filtering defined in the build scripts. And we change the documentation to be clear about this.

**Comment by blindpirate** [comment]
I agree. It seems that `--tests` shouldn't enable some tests which are NOT appear in normal build.  I just thought the documentation as original design intention.

**Comment by jjohannes** [comment]
I have created a new PR that implements the solution proposed above: https://github.com/gradle/gradle/pull/2327

Feedback is welcome!

**Comment by jjohannes** [comment]
#2327 was merged.

**Comment by masc3d** [comment]
@jjohannes I believe both use cases make sense. some tests may be excluded from automation and it shouldn't be that cumbersome (having to modify build script filters every single time) to execute them manually.

**Comment by jjohannes** [comment]
@masc3d true. But I am not sure if we need something specific in Gradle for the second use case (the one you describe above). 
- If I do not configure any includes/exculdes in my build `--tests` will just work
- If I do, but I want an opportunity to execute tests that are excluded in the _test_ tasks I automatically execute as part of my build (e.g. on CI), I can easily define another test task that includes all tests (e.g. `testAll`) for manual usage. With that I can then use `--tests`.

**Comment by masc3d** [comment]
generally I do agree that inclusion filters should apply when filtering the test run by category (eg. fast/slow) but I believe this is rarely how `--tests` is used atm.

running tests by category are much more suitable for custom test tasks and changing the behaviour of an existing switch is intrusive and will introduce breakage, eg. intellij currently creates a simple (afaik non-customizable) `--tests` switch when specifically running test methods or classes to run from the IDE (which is an excellent and convenient way to run test asks which are normally excluded from automated runs)

**Comment by masc3d** [comment]
@jjohannes just for notification, as I'm not quite sure those are sent on closed tickets.
