### ISSUE TITLE
After upgrading to 6.8, library project is not "locked" error is occurred

### ISSUE THREAD

**Issue by takke** [gradle/gradle#15743]
My project contains some external libraries and these `build.gradle` is migrated to `build.gradle.kts`.
After upgrading to 6.8, this project cannot build due to the following error.

```
$ ./gradlew :app:assembleDebug
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > A problem occurred configuring project ':ext:ExternalLibrarySample:library'.
      > org.gradle.api.internal.initialization.DefaultClassLoaderScope@2f28a39 must be locked before it can be used to compute a classpath!
      > com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle
```

### Expected Behavior

built successfully.

### Current Behavior

happen error above.

### Context

This stopped working in 6.8. It works in 6.7.1.

### Steps to Reproduce 

 
1.  `git clone git@github.com:takke/Gradle68ErrorSample.git`
2.  `./gradlew wrapper --gradle-version=6.8`
3. `vim local.properties`  (add sdk.dir like `sdk.dir=C\:\\Users\\user\\AppData\\Local\\Android\\sdk`)
4. ` ./gradlew :app:assembleDebug`
```
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all dependencies for configuration ':app:debugRuntimeClasspath'.
   > A problem occurred configuring project ':ext:ExternalLibrarySample:library'.
      > org.gradle.api.internal.initialization.DefaultClassLoaderScope@4affe9cd must be locked before it can be used to compute a classpath!
      > com.android.builder.errors.EvalIssueException: compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
```

### Your Environment

Build scan URL: https://gradle.com/s/x2k53zmwhjqa2

**Comment by ljacomet** [comment]
configure-on-demand and the Kotlin DSL are [not fully functional together](https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:limitations)

Could you see what happens if you turn that feature off. Is the problem gone?

**Comment by jjohannes** [comment]
I can confirm that this exists and that it goes away if you turn off _configure on demand_.

**But the problem exists with 6.7.1 as well!** If I clone the reproducer and run it (on 6.7.1), I get it:
https://scans.gradle.com/s/n3ylpmzo6tdeu

(Older Gradle versions don't work with the Android plugin version used.) 

@takke can you double check if there really is a regression? The build scan you linked is also not showing this problem (it is a successful build)

**Comment by takke** [comment]
> Could you see what happens if you turn that feature off. Is the problem gone?

Yes, it's gone when I turn off the `configure-on-demand` feature.

```
$ export ANDROID_SDK_ROOT=C:\Users\takke\AppData\Local\Android\sdk
$ git clone git@github.com:takke/Gradle68ErrorSample.git
$ cd Gradle68ErrorSample
$ ./gradlew wrapper --gradle-version=6.8
$ vim gradle.properties
$ cat gradle.properties | grep configureondemand
org.gradle.configureondemand=false
$ ./gradlew :app:assembleDebug --scan

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 10s
45 actionable tasks: 45 executed
```
https://gradle.com/s/x3laajamatsic

**Comment by takke** [comment]
> The build scan you linked is also not showing this problem (it is a successful build)

I mistakenly thought that `scan` must be successful.

Here is the scan result when it failed in Gradle 6.8.

```
$ export ANDROID_SDK_ROOT=C:\\Users\\takke\\AppData\\Local\\Android\\sdk
$ git clone git@github.com:takke/Gradle68ErrorSample.git
$ cd Gradle68ErrorSample
$ ./gradlew wrapper --gradle-version=6.8
$ ./gradlew :app:assembleDebug --scan
```
https://gradle.com/s/rdvv774n5alp2

> @takke can you double check if there really is a regression? 

I tried it on Gradle 6.7.1, but I faced curious result.

It succeeded when I ran it without `--scan`.
And it failed when I ran it with `--scan`.

```
$ export ANDROID_SDK_ROOT=C:\\Users\\takke\\AppData\\Local\\Android\\sdk
$ git clone git@github.com:takke/Gradle68ErrorSample.git
$ cd Gradle68ErrorSample
$ ./gradlew :app:assembleDebug

Configuration on demand is an incubating feature.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 9s
45 actionable tasks: 45 executed

$ ./gradlew :app:assembleDebug --scan
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all dependencies for configuration ':app:debugCompileClasspath'.
   > A problem occurred configuring project ':ext:ExternalLibrarySample:library'.
      > Could not open cache directory wdps4wq1j7kj6j2ra9etbq84 (C:\Users\takke\.gradle\caches\6.7.1\gradle-kotlin-dsl\wdps4wq1j7kj6j2ra9etbq84).
         > org.gradle.api.internal.initialization.DefaultClassLoaderScope@14796f22 must be locked before it can be used to compute a classpath!
...
```

https://gradle.com/s/v6ogqlyrma4qc


In my actual project, of course, don't specify `--scan` option, no problem on Gradle 6.7.1, so I think this problem is `regression`.
Thanks.

**Comment by jjohannes** [comment]
Thanks @takke I now see that the errors are slightly different.

However, I can also reproduce the exception without `--scan` in Gradle 6.7.1 under _certain conditions_. I also got it working now _sometimes_. I assume that if a certain classpath/classloader is coincidentally already cached it works. Otherwise it fails attempting to access the cache at the wrong moment.

So this is already a problem in 6.7.1 and what changed in 6.8 is only the cases/frequency you would hit it. It's somehow connected to when `ConfigurationOnDemandProjectAccessListener.evaluateProjectAndDiscoverTasks` runs and what it does.

Basically, if the setup **always** works for you in 6.7.1, you were just coincidentally hitting a spot where something broken works just good enough for you.

As stated above, "configure-on-demand" is a feature that is not stable and where we can give no guarantees. There are a number of features in Gradle it does not work with. Because we can't make it work. Basically it was an attempt for a feature that ultimately failed.

Going forward, it will be replaced with the _configuration cache_. Later, we might have something similar, but stable, in _composite builds_.

I would strongly recommend not to use it.

If you see a big benefit from it in your project which you can't get otherwise, I would recommend to:

- **Not** use Kotlin DSL
- **Not** use deeper subproject hierarchies. There are also known issues with that when using configure in demand. In the sample this means, instead of `include(":ext:ExternalLibrarySample:library")` do `include("library")`. You can still keep the `ext/ExternalLibrarySamle/library` folder as documented [here](https://docs.gradle.org/current/userguide/fine_tuning_project_layout.html#sub:modifying_element_of_the_project_tree).

**Comment by takke** [comment]
Thank @jjohannes 

I'm glad to have gained new insights that I did not know before.

Also in the actual project, the error was resolved by avoiding deeper subproject hierarchies.
