### ISSUE TITLE
Update embedded dependencies to latest versions

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#15744]
- Need to check for CVEs (if they require an advisory on our side)
- Need to check for runtime compatibility problems (e.g., doesn't work on Java 8)
- Need to check for compatibility problems with plugins

**Comment by lptr** [comment]
I've reopened https://github.com/gradle/gradle/issues/11920. The problem there is that we still depend on the Java 7-variant because switching over to the Java 8-variant would cause a performance regression. I still think we should do the switch in Gradle 7.0, as the Java 8-variant of Guava has features that we could finally start using, writing better code, that would lead to performance gains.
