### ISSUE TITLE
Node DexingWithClasspathTransform has not been encoded yet with 7.0

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#15889]
Using Gradle 7.0 nightly, `7.0-20210120054716+0000`, configuration cache build started failing with
```
> Configuration cache state could not be cached: field 'collection' from type 'org.gradle.configurationcache.serialization.codecs.FilteredFileCollectionSpec': error writing value of type 'org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection'
   > Node DexingWithClasspathTransform has not been encoded yet.
```

Using [test_project.zip](https://github.com/gradle/gradle/files/5843285/test_project.zip) and running `./gradlew :app:assembleDebug :app:assembleDebugAndroidTest --configuration-cache` reproduces the issues. It passes with Gradle 6.8. 

Build scan https://scans.gradle.com/s/qyumtgqyom57g/failure#1

**Comment by eskatos** [comment]
@gavra0, how is this affecting you? was it from a test in AGP test suite or from some real build out there?

**Comment by gavra0** [comment]
It was one of AGP integration tests that triggered this issue.

**Comment by adammurdoch** [comment]
It looks like the `:app:debugAndroidTestRuntimeClasspath` configuration contains a project dependency (on project :lib) that is not present when the task graph is calculated but is added some point later. This means that the task dependencies will be incorrect for this configuration.

In 7.0 we removed some leniency when a file collection contains transformed project dependencies, and those project dependencies are not included when the task graph. In older versions, we would ignore this problem and just try to run the transform anyway. The error message is not great, and we will do something to improve that.

It would be better to fix this on your side, so that the project dependency is visible when the task graph is calculated, if it is possible. We can potentially add the leniency back again for the short term, but we're a bit reluctant to do this.

**Comment by gavra0** [comment]
For `:app:debugAndroidTestRuntimeClasspath` we will substitute `com.test:lib:1.0` with `project(":lib")` as we try to sync application runtime classpath and the android test one. So if a project substitution happens in the application, we'd like to have the same artifact in the android test.

This is done in AGP [ConstraintHandler](https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-master-dev:build-system/gradle-core/src/main/java/com/android/build/gradle/internal/dependency/ConstraintHandler.kt;l=66?q=ConstraintHandler). Is there another API we should use? Also, we can probably avoid doing this by creating a single configuration which extends app and androidTest and then forcing androidTest and app to synchronize with it, but we never got to it (and we need to examine performance/memory impact of doing that).

**Comment by big-guy** [comment]
We put a workaround for this issue for now and fix it properly as part of https://github.com/gradle/gradle/issues/16403
