### ISSUE TITLE
Reading sys properties from task actions in buildSrc breaks configuration caching

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#15900]
System properties read from task actions should not break configuration caching. However, for tasks executed in `buildSrc`, accessing system properties from the task action breaks configuration caching.

Using [system_properties.zip](https://github.com/gradle/gradle/files/5849406/system_properties.zip) project, and running `./gradlew someTask --configuration-cache -DsomeDestination=dest` fails with `- Build file 'buildSrc/build.gradle': read system property 'someDestination'`.

**Comment by gavra0** [comment]
The issue seems to be `DefaultConfigurationCache.save()` does not run for `buildSrc` as it does not consider conf caching to be enabled for this build.

**Comment by bamboo** [comment]
`buildSrc` task actions can influence the build logic executed by the root build thus, inputs to `buildSrc` tasks, declared or otherwise, are considered inputs to the configuration cache since they can indirectly influence the final shape of the task graph.

In other words, `buildSrc` task actions run at `configuration time` from the point of view of the root build.

**Comment by gavra0** [comment]
(@bamboo and I spoke offline, but adding here for posterity)

Motivation for capturing access to system properties during task actions in `buildSrc` is to avoid configuring `buildSrc`. Accesses system properties are part of the configuration cache state, in addition to e.g `buildSrc/build.gradle` file.

However, this behavior seems inconsistent with task actions that are executed outside of `buildSrc` project. Secondly, it is possible to have undeclared task inputs for `buildSrc` tasks, and handling only system properties feel somewhat arbitrary. Ideally, there'd be a way to run tasks with full isolation i.e in "sandboxed" mode as a way to make sure any build operation is well-defined.

**Comment by adammurdoch** [comment]
Do you mind if we close this? Or perhaps change the title. The behaviour is by design and we would prefer to not make this check less lenient, because these reads do in fact represent undeclared inputs to the configuration cache entry. Instead, we would rather eventually apply the check to all task actions regardless of what they produce and also add checks for more kinds of undeclared inputs.

**Comment by gavra0** [comment]
I'll close this as this seems to be by design. Introducing input validation incrementally is good, but documentation should mention that and there should be a configuration caching mode (or a flag) which catches this in testing.
