### ISSUE TITLE
Could not start Gradle wrapper on Windows if path contains letters with accents

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#15977]
### Expected Behavior

I could run `gradlew.bat tasks` without issues for projects whose path contains accent letters, for example `D:\test\ktlint_accent_error\ktlint_àccent_error`.

### Current Behavior

Running `gradlew.bat tasks` produces following error:
```java
Error: Could not find or load main class org.gradle.wrapper.GradleMainWrapper
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleMainWrapper
```

Replacing accent letters with non-accent one solves the issue.

### Context

Trying to investigate https://github.com/JLLeitschuh/ktlint-gradle/issues/429 issue, but could not even run the test project.

### Steps to Reproduce 

- Clone https://github.com/NarcAle/ktlint_accent_error repo
- Add missing `gradle/wrapper/gradle-wrapper.jar` file
- Try to run `gradlew.bat tasks`

### Your Environment

Build scan URL: not possible to create
OS: Windows 10.0.18363.1316
Java version: OpenJDK 11.0.8+10

**Comment by lptr** [comment]
Not sure if this is completely related, but the same error is produced on Linux when the user home has quotes in the name, e.g. `/home/"no"`.

**Comment by mlopatkin** [comment]
It seems that Java is not able to understand Unicode characters in the command-line arguments. This is related to the default encoding of the non-Unicode software setting:
![image](https://user-images.githubusercontent.com/7620037/127163353-ceaddc14-5275-457e-8e9a-878a3a05727f.png)
If I change this setting from "Russian (Russia)" to "English (USA)" then the reproducer starts to work but projects with cyrillic letters in path break instead.

[The issue to support unicode path in classpath argument](https://bugs.openjdk.java.net/browse/JDK-4488646) was filed against Java 1.4 but not much happened since then.  I suspect that we cannot do anything on our side besides championing the fix into the OpenJDK. I tried to convert the paths to the ancient 8.3 format but it isn't supported on non-system drives by default (and can be disabled globally) for a while so this won't help.

This is obviously the Windows-specific problem so the issues with double quotes should be handled separately as they are most likely related to the POSIX script (and paths on Windows cannot contain quotes anyway)

**Comment by JoseIANEZ** [comment]
Hello,

I am a French developer and for 10 years I have been using a French IDE called "Windev Mobile" under Windows from PCSOFT to develop applications running on Android.
In 2018, my coding environment (Windev Mobile version 23) was using Gradle version 4 to build Android apps and I'm still using this version which works well.
A week ago I purchased the latest Windev Mobile version 27 update which now uses Gradle version 7.0.2 and I have an issue that PCSOFT seems to attribute to Gradle.
In fact, my user profile folder contains an accent (C:\Users\José) and apparently Gradle no longer works if this directory contains an accent.
I remind you that with this profile I have no problem with Gradle v4.
So I would like to know if you are aware of this regression and if there is a solution.

Thanks.

**Comment by JoseIANEZ** [comment]
Hello,

Sorry but I don’t know why this issue has benn closed ?
Sorry but I’m a new user of github and I think there is something I missed.
Could you help me please ?

I’d like my issue to be took into consideration because it’s a real problem for us.

Thanks in advance ?

José IANEZ
Directeur Informatique


[Logo fip petit] [bisico]
Plan ***@***.***,5.1361942,17z/data=!4m7!1m4!3m3!1s0x12c9fc253aa30bad:0x7038b6cdd11edef!2sBISICO+France!3b1!3m1!1s0x12c9fc253aa30bad:0x7038b6cdd11edef>
Financière de Participation / BISICO France
208 allée de la Coudoulette – 13680 Lançon Provence

• 04 90 42 95 50 | 06 89 15 71 74
• ***@***.******@***.***>




De : Louis Jacomet ***@***.***
Envoyé : vendredi 16 septembre 2022 10:48
À : gradle/gradle ***@***.***>
Cc : José IANEZ ***@***.***>; Comment ***@***.***>
Objet : Re: [gradle/gradle] Could not start Gradle wrapper on Windows if path contains letters with accents (#15977)


Closed #15977<https://github.com/gradle/gradle/issues/15977> as not planned.

**Comment by ljacomet** [comment]
As indicated in the comment above, this is really a JDK bug. Until that is fixed, there is nothing that can be done in Gradle.

**Comment by JoseIANEZ** [comment]
OK, thank you.
Do you know who is in charge for this issue in the JDK ? Is it Google ?
If yes I’m afraid not to have a solution quickly…

José IANEZ
Directeur Informatique


[Logo fip petit] [bisico]
Plan ***@***.***,5.1361942,17z/data=!4m7!1m4!3m3!1s0x12c9fc253aa30bad:0x7038b6cdd11edef!2sBISICO+France!3b1!3m1!1s0x12c9fc253aa30bad:0x7038b6cdd11edef>
Financière de Participation / BISICO France
208 allée de la Coudoulette – 13680 Lançon Provence

• 04 90 42 95 50 | 06 89 15 71 74
• ***@***.******@***.***>




De : Louis Jacomet ***@***.***
Envoyé : vendredi 16 septembre 2022 11:22
À : gradle/gradle ***@***.***>
Cc : José IANEZ ***@***.***>; Comment ***@***.***>
Objet : Re: [gradle/gradle] Could not start Gradle wrapper on Windows if path contains letters with accents (#15977)


As indicated in the comment above, this is really a JDK bug. Until that is fixed, there is nothing that can be done in Gradle.
