### ISSUE TITLE
Deprecate the jcenter() convenience method

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#16018]
Soon (01.05.2021) JCenter will not be available anymore: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
It should probably be deprecated as soon as possible and then also removed.

**Comment by vlsi** [comment]
What if `jcenter()` becomes an alias to `mavenCentral()`?

**Comment by LifeIsStrange** [comment]
Of course the deprecation message should tell to replace jcenter() with mavenCentral() if not present. This should be backported as a hotfix to all supported gradle versions and the doc should remove mentions of jcenter too.
This should be prioritarized as it will break so many projects, unfortunately many people will not update the Gradle wrapper in time.
Hence why for such citrical hotfix (or for high security issues) gradle should take responsibility and autoupdate or ask to update on any ./gradlew run

**Comment by LifeIsStrange** [comment]
@vlsi yes jcenter() should implicitly alias to mavenCentral for convenience while still being marked as deprecated (so that devs can eventually properly replace it)

**Comment by LifeIsStrange** [comment]
I believe this also affects urls containing bintray such as 
```Groovy
maven { url "https://kotlin.bintray.com/kotlin-datascience" }
```
Or 
```Kotlin
maven("https://dl.bintray.com/kotlin/kotlin-datascience")
```

**Comment by Vampire** [comment]
Freetext urls are freetext urls.
It can always happen that a repository you reference explicitly does go down.
Gradle should imho not check arbitrary urls just because it knows they are down. Latest when you try to use then you will see that.
`jcenter()` is differently as there is a convenience helper function and that should be deprecated and removed.

**Comment by big-guy** [comment]
We're in contact with JFrog to understand the full impact and what we can do about it.

Any change in behavior with `jcenter()` will need to go through the same sort of deprecation cycle. We can start warning earlier, but I don't think we want `jcenter()` to automatically change behavior immediately (maybe in the future after the public API is gone).

**Comment by ben-manes** [comment]
Will this impact the gradle plugin portal, which is hosted by JCenter?

**Comment by big-guy** [comment]
@ben-manes Originally, plugins could be published to Bintray (less than 10% of all plugins were published this way) and synced to the plugin portal, but no plugin artifacts are actually served from JCenter.

There will be some impact on the plugin portal because plugins that were only ever published via Bintray will now need to publish directly to the plugin portal. The plugin portal also implicitly redirects non-plugin artifacts to JCenter. We're assessing what to do. Expect more details soon.

**Comment by ben-manes** [comment]
This is how the gradle-versions-plugin does it, due to being an early adopter. I am one of those who needs to figure out how to upgrade. 😄 

I am glad to hear its not actually served by Bintray, thanks for the clarification. That history and knowing of the implicit redirect made me think it was co-hosted. Thanks a lot for jumping on to this, I'm sure it was a surprising distraction.

**Comment by s1monw1** [comment]
> Any change in behavior with jcenter() will need to go through the same sort of deprecation cycle as we usually do. We can start warning earlier, but I don't think we want jcenter() to automatically change behavior immediately (maybe in the future after the public API is gone).

Agreed. Implicit aliasing to mavenCentral is a bad idea as you'd be contributing to directing folks into dependency hell by confusing people about where things are actually being pulled from.

**Comment by jjohannes** [comment]
We will start by deprecating the `jcenter()` method in 7.0 or 7.1

**Comment by LifeIsStrange** [comment]
Why not deprecate it also for the next minor release 6.8.x ? The sooner devs get aware of the Jcenter apocalypse the better.

**Comment by jjohannes** [comment]
> Why not deprecate it also for the next minor release 6.8.x ?

Yes that might be a good idea. At the moment 7.0 is in focus and another 6.8.x will most likely be done afterwards. We will consider to add it there.
