### ISSUE TITLE
`testFixturesImplementation` doesn't propagate dependencies to test runtime.

### ISSUE THREAD

**Issue by jwChung** [gradle/gradle#16011]
```groove
implementation("com.abc:foo:1.0.0")
```

If production code depends on the foo library as shown above, the foo library can be used automatically in test code.

```groove
testFixturesImplementation("com.abc:foo:1.0.0")
```

With the same sense, even if the foo library is depended with `testFixturesImplementation` instead of `implementation`, shouldn't the foo library be available in the test code?

### Expected Behavior

The foo library which is depended with `testFixedImplementation` would be available in the test code.

### Current Behavior
The foo library which is depended with `testFixedImplementation` cannot be available in the test code.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

I am sorry but I do not fully understand the question and am unable to craft an answer. Could you share a reproducer indicating what you expect and where?

**Comment by jwChung** [comment]
[My colleague has just informed me that this issue was intended.](https://github.com/gradle/gradle/blob/124712713a77a6813e112ae1b68f248deca6a816/subprojects/plugins/src/integTest/groovy/org/gradle/java/fixtures/AbstractJavaTestFixturesIntegrationTest.groovy#L154) I don't understand the intention, but I will look for it separately. Thank you.
