### ISSUE TITLE
Change in behaviour when resolving custom project dependencies

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#16028]
In the elasticsearch build we're seeing a change in behaviour when consuming custom configurations in a project dependency.

 
### Current Behavior or error

Given this snippet:

```

project(":producer") {
  configurations {
    testArtifacts.extendsFrom testRuntime
    testArtifacts.extendsFrom testImplementation
  }

  TaskProvider testJar = tasks.register("testJar", Jar) {
    appendix 'test'
    from sourceSets.test.output
  }

  artifacts {
    archives tasks.named("jar")
    testArtifacts testJar
  }
}

project(":consumer") {
  repositories {
    mavenCentral()
  }
  dependencies {
    testImplementation "junit:junit:4.12"
    testImplementation project(path: ":producer", configuration:'testArtifacts')
  }
}
```

With 6.8.1 this resolves the test artifact AND the default artifact of `:producer`. Can you please shed some light if this is an intentional change. It could also be related to https://github.com/gradle/gradle/issues/16027

### Steps to Reproduce 

A sample project that shows the change in behaviour is attached.

[gradle7-test-artifact-dependency-issue.zip](https://github.com/gradle/gradle/files/5926668/gradle7-test-artifact-dependency-issue.zip)

### Your Environment
This issue showed up testing 7.0-milestone-1

**Comment by melix** [comment]
So here is what is happening in this case. In 7.0, we removed the `runtime` configuration. This configuration had the "main" artifact attached to it.

In your build file, you're writing:

```
  configurations {
    testArtifacts.extendsFrom testRuntime
    testArtifacts.extendsFrom testImplementation
  }
```

Because it's the Groovy DSL, `testArtifacts.extendsFrom testRuntime` won't fail, and a configuration called `testRuntime` is going to be created!

What we didn't cover is a deprecation message in case you _extend from_ a deprecated configuration...

The fix for this is to use a different configuration, and attach the main artifact to it, something like:

```
project(":producer") {
  configurations {
    testArtifacts.extendsFrom testRuntimeElements
  }

  TaskProvider testJar = tasks.register("testJar", Jar) {
    appendix 'test'
    from sourceSets.test.output
  }

  artifacts {
    archives tasks.named("jar")
    testArtifacts testJar, tasks.named('jar')
  }
}
```

**Comment by breskeby** [comment]
Thank you @melix for looking into this. Nice catch. Moving away from testRuntime seems the way to go. Will look into this over the next days and keep you posted. Thanks again! Still I wonder how many other projects will tap into similar problems

**Comment by big-guy** [comment]
@ljacomet can we add something to the 7.0 upgrade guide to warn about this explicitly?

**Comment by jjohannes** [comment]
Moved to 6.8.x to add the deprecation warning if you extend.

**Comment by ljacomet** [comment]
Adding the deprecation to 6.9 turns out to be more a negative than a positive because we do not have enough context to know when the call to `extendsFrom` actually can cause the configuration to be created.

However a note will be added to [this section](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#sec:configuration_removal) of the upgrade guide for this particular case.
