### ISSUE TITLE
Change in behaviour when resolving project dependencies

### ISSUE THREAD

**Issue by breskeby** [gradle/gradle#16027]
### Current Behavior or error

With our elasticsearch build, we noticed a regression in behaviour when resolving project dependencies in 7.0-milestone-1 in comparison to 6.8.1:

We have dependencies declared like this:

```
project(":consumer") {
  dependencies {
    implementation project(path: ":producer", configuration:'default')
  }
}
```

which doesn't work as expected in 7.0-milestone-1.

I notice the only way to fix this is using the following syntax:

```
project(":consumer") {
  dependencies {
    implementation project(path: ":producer")
  }
}
```  
### Steps to Reproduce 

A sample project showing this issue is attached

[gradle7-project-dep-issue-.zip](https://github.com/gradle/gradle/files/5926539/gradle7-project-dep-issue-.zip)

### Your Environment

This problem is not environment specific

**Comment by breskeby** [comment]
Here's the complete sample project demoing the issue

[gradle7-project-dependency-issue.zip](https://github.com/gradle/gradle/files/5926551/gradle7-project-dependency-issue.zip)

**Comment by melix** [comment]
Can you clarify "doesn't work"? I think you mean "resolves differently", and I think a build scan would tell you it selects the "default" configuration, but that there's no artifact attached to the default configuration anymore.

I _think_ this is an expected behavior due to the deprecation.of the `archives` and `default` configurations in 6.x.

**Comment by breskeby** [comment]
Indeed I mean _resolve_ differently. Is there some more information on deprecating archives and default configurations and maybe further migration guiding. I'm surprised to see this as we don't see any depreciation warnings in our build with 6.8.1 and therefore I wouldn't have expected any change in behaviour between 6.8.1 and 7.0M1

**Comment by breskeby** [comment]
I saw the information in the migration guide now. Though still think this will cause some builds to struggle in the update as there was no deprecation message logged before, so people are not aware making use of this deprecated configurations.

**Comment by melix** [comment]
Yes, I think there's an issue there that we don't have a good way to display a deprecation message when something is _consuming explicitly_ a deprecated configuration...

**Comment by melix** [comment]
So after checking what is _really_ going on, in 7.0 we kept the `default` configuration, but we don't attach artifacts to it anymore. I think we can workaround this issue by detecting that you have an explicit dependency on the `default` configuration and drop it, in order to fallback to variant aware selection instead.

**Comment by breskeby** [comment]
We're fine with moving away from the explicit usage of "default" I think.

**Comment by ljacomet** [comment]
After further discussions, this change will be reverted. The behavior will need to be properly deprecated first before removal.

**Comment by ljacomet** [comment]
#16104 will be the follow up for this
