### ISSUE TITLE
unix gradle wrapper fails when path contains $ character

### ISSUE THREAD

**Issue by keturn** [gradle/gradle#16055]
### Expected Behavior
gradle wrapper works regardless of the name of the current directory or its ancestors.

### Current Behavior

When the project directory or any of its ancestors contain a `$` character, `gradlew` fails with

```
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

### Context

I was debugging problems in our build that occur when there is a space in the name (e.g. home directories where the username is multiple words). For extra spice, I added some other characters to my directory names too.

`%` and `👿` cause problems that might be at a deeper level, but the `$` is specific to the gradlew shell script.

### Steps to Reproduce 

```
mkdir 'foo$bar-baz' && cd 'foo$bar-baz'
gradle init
./gradlew
```

### Your Environment

Ubuntu 20.10 here, but I suspect this is widely reproducible.

**Comment by keturn** [comment]
This patch against the _generated_ `gradlew` Works For Me.

[gradlew.diff.txt](https://github.com/gradle/gradle/files/5936067/gradlew.diff.txt)

A real fix will need to be done against unixStartScript.txt with an additional layer of escape gymnastics for the [template engine](https://docs.groovy-lang.org/docs/next/html/documentation/template-engines.html#_simpletemplateengine).

I have not run this against any test suite to ensure it works with other edge cases or shell implementations.

**Comment by Korov** [comment]
mark

**Comment by kurahaupo** [comment]
@keturn 

The last ten lines of the `gradlew` file need to be rewritten, and much of the file needs an overhaul (which is in progress elsewhere, see #17666).

But in relation to your change, the fix isn't to use the "save" function, but rather to alter the quoting in the eval line so that it doesn't mangle the parameters that are already correct, including $CLASSPATH and $@.

I would change:

* `"\"-Dorg.gradle.appname=$APP_BASE_NAME\""` to `'"-Dorg.gradle.appname=$APP_BASE_NAME"'`
* `"$CLASSPATH"` to `'"$CLASSPATH"'`
* `"$APP_ARGS"` to `'"$@"'`

and get rid of the `save` function and the assignment to `APP_ARGS`.
