### ISSUE TITLE
Mark log output from BuildOperations with the task that generated it

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1611]
### Expected Behavior
Associate a BuildOperation ID to each OutputEvent to denote the BuildOperation that generated it.

### Context
All ProgressOperations happen in the context of a BuildOperation

Blocks #1610 — with the removal of task execution logging in the main area, users need to get some additional context when warnings or errors occur. 

Avoid porting things to BuildOperations for this work.

**Comment by oehme** [comment]
With the introduction of the "parallel by default" API that @ghale is working on, this is even more important. It will allow tasks to run concurrently (e.g. one task is waiting for background work to complete, while another starts snapshotting its inputs). This means that their output could be interleaved. This is already a problem with `--parallel` today, but will now also affect builds without `--parallel`.

**Comment by lacasseio** [comment]
[Some discussion](https://gradle.slack.com/archives/C03A0MT6S/p1491580580313047) on Slack.

**Comment by lacasseio** [comment]
I looked at this a bit more as part of trying to get `BuildOperation` working with the console. I was able to hack together two branches that [forward all `BuildOperation` to the console](https://github.com/gradle/gradle/tree/dl-convert-to-build-operation) and that [attach an `OperationIdentifier` to all logs](https://github.com/gradle/gradle/tree/dl-issue-699-spike). Both solutions are hideous and need cleaning which is the reason for this comment. Here are the open questions:

1. To attach `OperationIdentifier` to each log, we require access to the [current running `ProgressLogger`](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/progress/DefaultProgressLoggerFactory.java#L32). Exposing it through the `ProgressLoggerFactory` interface leads to passing the factory to lots of separate places. It's also not possible to pass a reference to the factory in [some code path](https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/slf4j/OutputEventListenerBackedLogger.java#L129-L138) as they are statically constructed. The question is around how we can pass the `OperationIdentifier` around to all log generating classes? Note that this problem also exists with raw `BuildOperation` as we need to attach the id to the generated logs (e.g. `System.out`, `System.err`).
2. The worker process has some added complexity. The thread receiving the log events isn't the thread that started the `BuildOperation` (and, by definition, `ProgressLogger`). The `OperationIdentifier` isn't accessible. To access it, you need to [jump through some hoops](https://github.com/gradle/gradle/commit/311a1df313c38ca1dbe1c20255764ac21a3b59ae). It's more complicated when the worker process is reused. We could use a general solution if the worker process could know his `OperationIdentifier`.

For issue 1, we could have a registry that contains the `OperationIdentifier` for all thread. We could pass around this lightweight object around and access a singleton reference where we can't pass a reference.

For issue 2, we could pass the `OperationIdentifier` to the worker process and set it in the registry so that all log generated code can retrieve it and attach it on the log.

I would appreciate suggestions on other solutions for those two issues.

**Comment by eriwen** [comment]
This is also addressed in #1855
