### ISSUE TITLE
Spec for declaring dependency on Gradle's public and internal API

### ISSUE THREAD

**Issue by bmuschko** [gradle/gradle#1614]
Write spec and agree on individual stories.

**Comment by bmuschko** [comment]
Spec for review: https://github.com/gradle/gradle/blob/master/design-docs/internal-apis-made-public.md#story-dependencyhandler-exposes-methods-for-declaring-public-and-internal-gradle-api

**Comment by melix** [comment]
I think the spec as it is now is a bit too optimistic. Using `gradleApi()` today, we get both the internal and public API classes, true. But they are also bound together. In other words, the private API is leaking into the public API. The most relevant example is `DefaultTask`, which extends `AbstractTask`.

So, if we do: `gradlePublicApi()`, and that this filters out the private API classes, while sounding like a good idea, is very likely turning to be a nightmare because of this leakage: it would become impossible to compile a plugin.

There are several solutions for this:
1. fix the public API, by not leaking the private API anymore. This often involves binary breaking changes, so I'm not super happy with this.
2. make those leaking classes part of the public API. This is not something we want to do, I think.
3. stub the leaking classes into the public API. They would allow compiling the plugins, but at the same time, they would still be visible. Could be a reasonable trade-off.

The second thing I'd like to see if we do this is to address a long standing issue: we can only depend on the _current Gradle_ API. So to build a plugin for Gradle 3.0, you need to use Gradle 3.0. To build a plugin for Gradle 4.1, you need Gradle 4.1. This has been a pain for users (and me included for a long time). If we introduce a new API, I'd like it to take this into consideration. This means multiple things:

1. I'd like the API to look more like `gradlePublicApi(String version)`
2. we need to publish the API (and maybe no big deal if _older_ APIs are not published)
3. it makes it possible for a single Gradle version to build plugins for multiple releases (variants)

What do you think?

**Comment by lptr** [comment]
We tried to stub some of the leaking classes via load time weaving for core classes here: https://github.com/gradle/gradle/pull/1021. We still had to fix tooling API invocations, and we never ended up merging the PR. It might be worth revisiting.
