### ISSUE TITLE
Allow work to be marked explicitly not cacheable via annotation

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#16209]
Tasks can be marked as `@CacheableTask` and artifact transforms can be marked as `@CacheableTransform` when the author of these work items deems them worthwhile to store in the cache. There are however tasks and transforms that are inherently not cacheable. For example, tasks that only move things around the local disk, like `Copy`: these should not be stored in any cache.

Currently when looking at the code of a task or transform that is not marked as cacheable it is hard to tell if it is not marked because it shouldn't be cacheable or if it was just never considered to be made cacheable.

* We could add something like like a `@NonCacheable` annotation could help. If we add something like this, providing a reason for not caching in the annotation could be a good idea, too.
* Another option would be to add parameters to the existing annotations, like `@CacheableTask(disable = true, because = "...")`.
* Yet another option would be to add a new annotation to mark work as cacheable that could supersede `@CacheableTask` and `@CacheableTransfrom` (e.g. a new `@Cacheable` annotation), and add parameters to that to disable caching.

No matter how we mark tasks as non-cacheable, it would allow both people looking at the source code, as well as Gradle's own validations to check whether cacheability has been considered for a task, and warn if it hasn't.

---
cc: @gradle/execution

**Comment by lptr** [comment]
We should consider this in 7.1.

**Comment by cmwarrington** [comment]
This looks good :)

I like the idea in general of marking something as Cacheable, but with a marker that it's probably slower to fetch from the cache than just compute, as it leaves open the possibility that in the future Gradle and/or the build author could make a more nuanced choice, while also addressing our immediate need. i.e
I wonder if we should pick annotations to distinguish "this can't be cached for a fundamental reason" from "this probably isn't worth caching" That could mean providing e.g.
 1. `@Cacheable`
 2. `@Cacheable(likelyFasterToRecomputeThanToFetchFromCache=true)` (with a better name :))
 3. `@NotCacheable`
 Where initially 2 & 3 behave the same other than for reporting to the build author.

**Comment by bigdaz** [comment]
I wonder if we should start to introduce a distinction between `cacheable` and `should cache` for Tasks. If I understand correctly, with the new enforced input/output declarations in Gradle 7 almost all tasks should be inherently cacheable. Whether it makes sense to cache the task outputs is separate, and can be a lot more dependent on the particular Task invocation.
For example, I'm sure there are `Copy` tasks with very expensive filtering logic that would make sense to cache.

The nice thing about this distinction is that it can lead to smarter infrastructure to make decisions about when to cache build outputs, rather than relying on the plugin author making this decision up front.

Perhaps this is mostly about language: I would find it unfortunate to label something as `@NotCacheable` when in fact the outputs _could be_ cached, but in 99% of cases this doesn't make sense.

**Comment by ducrohet** [comment]
I agree that `NotCacheable` should be used only if something is truly not cacheable, and I'm not sure what the reason could be. There is a potential issue with relocability when task inputs point to things outside of the project (like an SDK installed somewhere) using absolute paths on the machine. This is different than using absolute path for things inside your project which should be fixable, but it impacts remote cache.

So I agree that we should have more granularity in the annotation. Something like:
1. cacheable
2. cacheable but potentially not worth it. 
3. cacheable but only works on the same machine (so this can be part of a local cache but not a remote cache)
4. not cacheable.

4. should be very rare, and definitively not used for Jar/Copy/etc...
1/2/3 could be combined technically, so it makes sense that it's the same annotation with some parameters.

The challenge is figuring out how much to declare for 2, as I hope we can get to a point where Gradle can adapt its strategy for using remote cache based on machine performance vs network speed.
