### ISSUE TITLE
Rename application plugin to java-application

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#16328]
### Expected Behavior
````kotlin 
plugins {
    `java-application`
     // or with Kotlin DSL
     application(java)
}
````

### Current Behavior
````kotlin 
plugins {
    application // what is the application target/language?
}
````

### Context
Currently, there are 3 applications plugins (`application`, `cpp-application`, `swift-application`), but only the `application` plugin does not contain the language. This behavior is wanted and it is total clear in the documentation, that this plugin creates a JVM application and based on the `java` plugin, but it is not intuitiv from reading the `plugins` block only. As a beginner, you need to look up the `application` plugin in the documentation. 
Of course, you should read the documentation ;) but explicit providing the language is clearer.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle.

Changing a plugin name is not something done easily because it can have an impact on existing script. Think about other plugins that detect the application of this plugin: they would have to consider multiple names.

In addition, as you stated, this plugin is really a JVM application, irrelevant of the language used to code it. So `java-application` is incorrect as well.

Given all the other priorities, this is very unlikely to get any traction.
