### ISSUE TITLE
Deprecate command-line options that describe the build layout

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#16402]
The `-b` and `-c` command-line options are effectively used to describe a non-standard build layout to Gradle. This is problematic because it means that a specific combination of options must be used whenever Gradle is used on that build, for example whenever invoked from the IDE, CI, command-line or some other tool. These command-line options also have some potentially surprising behaviours, such as running a settings script present in the target directory.

We don't think there are any use cases that are strong enough to justify keeping these options, and we should remove them (via deprecation). If we discover there are some use cases, we might consider replacing the options with more self-describing contracts, for example conventions for build script names.

### Expected Behavior

It is not possible to structure a build in such a way that it requires special command-line options in order to be used.

### Current Behavior

It is possible to structure a build in such a way that special command-line options are required to use that build.

**Comment by melix** [comment]
Related: https://github.com/gradle/gradle/issues/14756

**Comment by rieske** [comment]
Do we want to also deprecate setting a custom build file location via `GradleBuild` task?
https://github.com/gradle/gradle/blob/eee7487396c2e6c27747b8ee85c9c42ff478cb92/subprojects/core/src/main/java/org/gradle/api/tasks/GradleBuild.java#L103-L120

**Comment by rieske** [comment]
Related https://github.com/gradle/gradle/issues/3828

**Comment by jimshowalter** [comment]
I can describe a use case. The Nebula release plugin is opinionated (that's their own assessment, not mine, see https://github.com/nebula-plugins/nebula-release-plugin/issues/182). It does not have any support for excluding modules. We have a multi-module repo that is a combination of libraries that we want to publish, and services that we don't want to publish. Without excludes, our current solution is to modify the Gradle configuration with a script in our Jenkins sign/publish pipeline. But security and compliance regard any monkeying around with configuration as no better than monkeying around with code--they want to be able to say, forensically, what you see in this git repo is what went to production. So we were investigating using Gradle command-line options to tell the sign/publish pipeline "use this other Gradle configuration that does not include the services' modules". Because the alternative Gradle configuration would be checked in, it's not a security/compliance issue--it's in github, and is used unchanged. Is there some other way in Gradle to have a multi-module repo that builds and tests all modules but only signs and publishes a subset of those modules, and all without modifying any files in the pipeline? If so, we'll use that instead of trying to use command-line options.

**Comment by big-guy** [comment]
@jimshowalter If the only difference between your two settings files are the list of modules, another way to do this would be to conditionally include the subprojects based on a property:

In settings.gradle:
```
if (!hasProperty("publishing")) {
    include("a", "b", "c")
}

include("x", "y", "z")
```

And then invoke the build with `gradle -Ppublishing ...` which would _exclude_ subprojects a, b, and c.

I'm not super familiar with the release plugin, but you might also be able to push this down into the configuration of the plugin by selectively disabling the tasks for subprojects that should not be published.

How do you deal with project dependencies on the "service" projects if you're removing them from the build when publishing?

**Comment by jimshowalter** [comment]
Thanks! Ironically it turns out we have a big repo that uses conditionals in settings.gradle. It never occurred to me to try that, which in retrospect is silly (it's all just code).

With that solution, there's no need for the command-line options.

**Comment by MarkRx** [comment]
Use case: Separation of concerns. We use Gradle for Enterprise SDLC operations. Teams may also opt to use Gradle for the own builds.

Team build configuration goes in build.gradle (owned by team)
SDLC workflow goes in sdlc.gradle (owned by devops)

By separating out build scripts it allows sdlc.gradle to be managed and upgraded independently of team build configurations. The DevOps organization only needs to manage sdlc.gradle and doesn't need to worry about plugin/gradle version missmatches with teams using their own gradle setup.

If merged into the same Gradle invocation then the Gradle version used by teams and the one supported by the DevOps organization must be in sync. At scale this is no easy task and requires both a pulse on teams updating their Gradle as well as supporting many different versions for in-house plugins at once. Additionally, sometimes 3rd party plugins can stomp on internal sdlc workflows/plugins (such as spring boot messing with classloaders).

If --build-file and --settings-file is removed then this can only be achieved by using folders to separate out independent build scripts

**Comment by jpbottinelli** [comment]
@MarkRx  I ran into this issue and am having the exact same problem you have. We have to gradle projects that one (dev) uses the other (sdlc) and because of this, we are losing the dev context when running the sdlc project, which is forcing me to rewrite everything.

Were you able to solve it? If so, would you mind sharing it, please?
Thanks

**Comment by MarkRx** [comment]
@jpbottinelli yes we worked around it by putting the extra build script in a separate child directory with its own settings.gradle file that sets up the build script to point to the parent directory. Note the extra `build.gradle` script will have its own independent `.gradle` cache directory.

```
parent_folder/build.gradle
parent_folder/settings.gradle
parent_folder/child_folder/build.gradle
parent_folder/child_folder/settings.gradle
```

parent_folder/settings.gradle
```
// Note - do not import child_folder as a subproject. Instead it is invoked as an independent "project" that uses the parent_folder directory  
```


parent_folder/child_folder/settings.gradle:
```
rootProject.projectDir = file("$parentDir")
rootProject.buildFileName = "$childDir/build.gradle"
```

**Comment by jpbottinelli** [comment]
Thanks @MarkRx! I'll try this approach. Really appreciate the quick response
