### ISSUE TITLE
DependencyHandler should accept a ListProperty<String> for lazy dependency notation

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#16419]
DependencyHandler accepts a `List<Provider<String>>` for dependency notations. It should allow a `ListProperty<String>` as well for consistency.

**Comment by big-guy** [comment]
I think this behavior is different between Groovy and Kotlin DSLs.  Groovy allows lists because it translates `List<Provider<String>>` to multiple calls.

In the `DependencyCollector`-based APIs, we do not directly support lists of dependencies.  So you need to call `add` on each element or use `.bundle`. 

I don't think we want to expand `DependencyHandler` to support lists more than what `DependencyCollector` supports.
