### ISSUE TITLE
Add compiler forkOptions switch to shutdown directly after task completes

### ISSUE THREAD

**Issue by leonard84** [gradle/gradle#16438]
This issue was first [discussed in slack](https://gradle-community.slack.com/archives/CAHSN3LDN/p1614290817067700).

In https://github.com/spockframework/spock/pull/1278 I try to capture the coverage of Spocks AST transforms during compilation of our specs. The problem is that the compiler is kept alive instead of directly being shutdown after the compilation finishes. This causes multiple issues, i.e., the jacoco.exec file can't be declared as output, and it can't be directly aggregated in the same run. 

```groovy
compileTestGroovy {
  def compileTestGroovyExec = "$buildDir/jacoco/compileTestGroovy.exec"
  outputs.file(compileTestGroovyExec)
  groovyOptions.fork jvmArgs: ["-javaagent:${configurations.jacocoAgentRuntime.asPath}=destfile=$compileTestGroovyExec,dumponexit=true,includes=org.spockframework.*".toString()]
  doFirst {
    file(compileTestGroovyExec).delete()
  }
}
```

I'd propose to add a switch like `keepAlive`/`reuse` to the forkOptions that can be set to `false`, so that the compiler jvm will directly be shutdown after if finished the task.

### Expected Behavior
The compiler jvm exits directly after the compilation finishes and `$buildDir/jacoco/compileTestGroovy.exec` gets properly written.
The output is correctly captured.

### Current Behavior
The compiler jvm is kept alive, but can't be reused since, the `jvmArgs` are unique to that execution anyway.
The `$buildDir/jacoco/compileTestGroovy.exec` is only written to at the end of the gradle run.
The task output is detected as modified, since it was written to after the compile finishes.

### Context
There are potential workarounds, e.g., disabling `dumpOnExit` and using JMX to connect to the compiler jvm and triggering a dump in a `doLast` step. However, I'd consider them to be quite hacky, and would like a proper solution in gradle.

**Comment by leonard84** [comment]
Still relevant

**Comment by big-guy** [comment]
I recognize the usefulness of being able to add something like JaCoCo to the compiler process, but I don't think we want to expose worker management-like functions to the compile tasks. 

A few alternatives:
1. Instead of collecting the JaCoCo results into a single file, send them to a centralized collector process. This still doesn't solve the underlying "stop the worker now" problem. 
2. Force Gradle to run compilation as if it were calling javac.  This gets rid of the worker process.
3. Don't use Gradle to do this data collection because there's just too many unnecessary layers of indirection.
