### ISSUE TITLE
Kotlin DSL should support map notation for declaration of platform/BOM dependencies

### ISSUE THREAD

**Issue by markslater** [gradle/gradle#16498]
### Expected Behavior

Using the Groovy DSL, I can declare platform dependencies using map notation, e.g.
```groovy
implementation platform(group: 'org.http4k', name: 'http4k-bom', version: '4.4.0.1')
```
I'd like to be able to do the same using the Kotlin DSL, e.g.
```kotlin
implementation(platform(group = "org.http4k", name = "http4k-bom", version = "4.4.0.1"))
```

### Current Behavior
Kotlin DSL platform dependencies, according to [the documentation](https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import), should be declared using string notation, e.g.
```kotlin
implementation(platform("org.http4k:http4k-bom:4.4.0.1"))
``` 
In fact, inspecting the code, it's also possible to supply a Kotlin map, though this is undocumented (and possibly an implementation detail subject to change without notice):
```kotlin
implementation(platform(mapOf("group" to "org.http4k", "name" to "http4k-bom", "version" to "4.4.0.1")))
```
For regular module dependencies, the Kotlin DSL already has explicit support for map notation, meaning this is valid:
```kotlin
implementation(group = "org.http4k", name = "http4k-core")
```
### Context
In the interests of consistency, and hence intuitiveness, platform/BOM dependencies should be declared in the same way as regular module dependencies.  For the same reason, notation that is valid in the Groovy DSL should have an analog in the Kotlin DSL.

In my opinion, map notation is easier to understand, and less prone to fat-finger errors.

I'd be happy to put together a pull request if there's support for making this change.

**Comment by markslater** [comment]
Can you reopen this?  I've attached a pull request, that's waiting for someone to approve the CI workflow.

**Comment by tresat** [comment]
The Kotlin example you provided:

`implementation(platform(group = "org.http4k", name = "http4k-bom", version = "4.4.0.1"))`

 uses a Kotlin language feature: [Named Arguments](https://www.baeldung.com/kotlin/default-named-arguments):

_When invoking a Kotlin function, we can name one or more arguments. The name used for the argument must match the parameter name specified in the function declaration._

The Groovy example:
 
 `implementation platform(group: 'org.http4k', name: 'http4k-bom', version: '4.4.0.1')`

is [syntactic sugar](http://docs.groovy-lang.org/latest/html/documentation/#_named_parameters) for constructing a `Map` and providing it as an argument to a method which takes a single `Map` argument:

_When the first argument is a Map, Groovy combines all named parameters into a Map (regardless of ordering) and supplies the map as the first parameter. This can be a good approach if your properties are declared as final (since they will be set in the constructor rather than after the fact with setters)._

So these 2 are not equivalent; a corresponding Kotlin call should use the `mapOf` method.  This is a language feature difference, not a difference in the Gradle DSLs.

If you can point out where in the Gradle docs this syntax is undocumented, or could use more clarity, we would be interested in improving this section.

**Comment by tresat** [comment]
Thanks for the feedback.  It's looking right now like we might decide to remove the `Map` overloads entirely in favor of overloads which use named args and default values.  These would look similar and be more discoverable in both DSLs.  As I mentioned in the other issue, we're working with the Test Suites `dependencies` block first before addressing the top-level `dependencies` block.  We'll keep track of this issue though, and use it to help inform our discussions.
