### ISSUE TITLE
Provide public API for providing Java toolchains

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#1652]
We currently have rudimentary support for Java toolchains. There is `JavaToolChain` which can be set on `JavaCompile`. For Java compilation, we detect the desired toolchain by looking at the fork options.
The [Gradle error-prone plugin](https://github.com/tbroyer/gradle-errorprone-plugin) provides its own Java toolchain which compiles Java by using the error-prone compiler. To be able to do so it needs to resort to the use of quite some amount of internal Gradle APIs. This can lead to breakage when changing internal APIs as seen in #1645.
We should make it possible for plugin authors to provide its own Java toolchain via a public API. The internal API is currently even exposed on the `JavaCompile` task: [setToolChain](https://github.com/gradle/gradle/blob/e7b5241392239bd7651aa50850aa5ba6f60c4031/subprojects/language-java/src/main/java/org/gradle/api/tasks/compile/JavaCompile.java#L144-L144) should only use the Gradle public API.

**Comment by adammurdoch** [comment]
There are several use cases, so we might split this issue up:

1. Build logic asks Gradle for a java tool chain given a Java home, and then attaches it to a task that uses a java tool chain, eg compile task, javadoc task, java exec task, test task, task that uses a worker daemon, and so on.
2. Build logic asks Gradle for a java tool chain given a Java version, and attaches it to a task
3. Build logic defines a java tool chain by pointing at the relevant executables.
4. Build logic accepts a java tool chain and uses the tool chain to do something, eg compile source, generate java doc, run a java app, etc.

We should deprecate specifying the Java tool chain as an executable or as a java home on tasks, and instead pass around tool chain instances. We should also ensure that java tool chains and native tool chains are defined in a consistent way.

**Comment by tbroyer** [comment]
Actually, I believe there are more use-cases than this (depending on what we call a "tool chain" actually).

 * For example, if I need to use JavaC 1.8 (because I have annotation processors that require Java 8) but target Java 7, I then need/want to pass a `-bootclasspath` with the `rt.jar` for a JDK 7 (if I used Java 9, I could use `-release 7` instead). Admittedly this might not fit the definition of "tool chain" though.

 * The use case that triggered this issue: using a specific compiler. Here, there are 2 subcases:
   * the compiler is a standalone tool, e.g. `ikvmc` (not sure if it really qualifies here, as it doesn't produce Java bytecode), or GCJ (now dead); this is undeniably a "tool chain".
   * the compiler is itself a Java application and/or could be embedded (called with its own API, or `javax.tools.JavaCompiler`; e.g. Error Prone, ECJ/JDT, Janino, or something like the Android Jack&Jill experiment); in this case you may want to select a Java tool chain to actually run the compiler (e.g. Error Prone requires Java 8, fails with Java 9, so you may want to run your Gradle build with either Java 7 or Java 9, and configure a Java 8 toolchain to run Error Prone – and then you'll possibly want to pass a `-bootclasspath` to target another platform, see above).

The Error Prone / ECJ / etc. use case might be different from the Java tool chains usecases. The gradle-errorprone-plugin current uses a `JavaToolChain` because I don't think there's an alternative; but it needs to duplicate a bunch of code from Gradle internals, and does not use a daemon process (IIRC because internal APIs have changed between Gradle versions). Having an API to plug those alternate compilers (resolving their dependencies from the project's configurations) while benefiting from all that Gradle has to offer would be great; but that would likely be a different API than `JavaToolChain`.

WDYT?

**Comment by jgsuess** [comment]
We use gradle for our internal SE experiments and have intensive use of toolchain configurations. It is necessary for us to use very old versions of the Java toolchain and also to configure and access the members of the toolchain and environment. While we currently roll our own this pretty quickly sown and I would love to replace our designs with something that writes to a clean standard API.

**Comment by tbroyer** [comment]
Fwiw, Error Prone can be crossed out of the usecases here, as it's converging towards being used through `-Xplugin` (implementing `com.sun.source.util.Plugin`). It even works with Java 8 **if** you fork the compiler and add the Error Prone javac to the bootclasspath (see https://github.com/google/error-prone/issues/535#issuecomment-414165838)

**Comment by ams-tschoening** [comment]
Please have the following use case in mind as well: When using Gradle within Eclipse, it uses the JVM used to run Eclipse itself by default. Eclipse requires JDK 11 for itself since 2020-09, depending on plugins maybe even since 2020-06 already. When one has JDK 8-projects only, those are build by default using JDK 11 now, when Gradle tasks are executed using the Gradle task view in Eclipse. To change that, one needs to [configure a JDK for Gradle only](https://github.com/eclipse/buildship/issues/802#issuecomment-646743650) within Eclipse.

It would be great if that manual configuration wasn't necessary and instead one could make Gradle aware of different installed JDKs and tell in the project to always use some of those. Regardless what the JDK used to execute a parent process like Eclipse.

This is especially important because when one uses a shell within Eclipse to execute Gradle tasks, the system wide JDK might be used again, which might differ from the one used to run Eclipse itself. In my case I really configured to use JDK 11 for Eclipse only in `eclipse.ini`:

	[...]
	openFile
	--launcher.appendVmargs

	-vm
	C:\Program Files\Java\jdk-11\bin\client\jvm.dll

	-vmargs
	-Dosgi.requiredJavaVersion=1.8
	[...]

**Comment by bmuskalla** [comment]
Toolchains are going to be [part of the 6.7 release](https://docs.gradle.org/6.7-rc-4/release-notes.html#jvm-toolchains). Given this issue started to collect multiple distinct use-cases (several of them are already covered), I'm going to close this one for now. If you find a use-case that is not yet covered by the current toolchain feature, please feel free to create specific issues for those. You can also watch the epic #2203 which is going to track the work we plan on doing for 6.8 as well.
