### ISSUE TITLE
Cacheability of compileJava-Task not given in a multi project with dependency substitution and java-library-plugin

### ISSUE THREAD

**Issue by lschwahn** [gradle/gradle#16650]
In our java-multi-project build we are using the dependency substitution ([as documented in "Conditionally substituting a dependency"](https://docs.gradle.org/current/userguide/resolution_rules.html#sub:conditional_dependency_substitution)) to make sure, a developer does not have to checkout all subprojects, but only the ones he is working on ("sparse checkout"): 
- projects, which exists in the local workspace, are referenced as a project-dependency.
- projects, which do not exists in the local workspace, are referenced as a module-dependency and therefore downloaded from a repository.

Additionaly we are using a remote-build-cache, which is filled by our CI-build. The CI-build always works with a fully checked out workspace. So all subprojects are built. The local builds are pulling from this remote-build-cache.

Recently we switched from the java-Plugin to the java-library-Plugin. Since then the cacheability of the compileJava-Task is not given anymore, when using a sparse-checkout. With the java-plugin a compileJava-Task had the jar-Files of all projects, it depends on, in it's compile classpath. This behaviour changed with the java-library-plugin: instead of a jar-File a projects "build/classes" folder is now used inside the compile classpath. 
This breaks the cacheability of the compileJava task in local builds, because the compile classpath differs from the on from the CI-Build:

![image](https://user-images.githubusercontent.com/3949818/112617595-7272ea80-8e25-11eb-9948-aff83fcc9e16.png)

As a workaround we set the System-Property "org.gradle.java.compile-classpath-packaging" to true, as documented in the [Java-Library-Doc](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_classes_usage). Therefore the compileJava-Tasks uses jars instead of class folders, as the java-plugin did. But it is documented to only "activate this if you suffer from the described performance issue on Windows".

### Expected Behavior
The cacheability should be given, because the class-files inside the jar are binary identical to the ones inside the classes folder.

### Current Behavior
The cacheabililty is not given, because the compile classpath differs. 

### Steps to Reproduce 
Extract the attached tar.gz file [gradle-multi-project-cache-sample.tar.gz](https://github.com/gradle/gradle/files/6211460/gradle-multi-project-cache-sample.tar.gz):

```// Build of the whole project, as our CI-Build does:
./gradlew clean build showClasspath publishToMavenLocal --build-cache

// output shows that projectB uses projectA's classes folder
// projectB: (...)/gradle-multi-project-cache-sample/projectA/build/classes/java/main

// "Remove" a Project to simulate a sparse checkout:
mv projectA projectA-backup

// Build of the "sparse-workspace", as a developer does:
./gradlew clean build showClasspath publishToMavenLocal --build-cache

// output shows that projecB:compileJava is not FROM-CACHE and uses projectA's jar file from the local maven-repo:
// projectB: (...)/.m2/repository/org/sample/projectA/1.0/projectA-1.0.jar
```

### Your Environment
Build scan URL of a Build with complete workspace: https://scans.gradle.com/s/dwdlojcav4b7u
Build scan URL of a Build with sparse workspace: https://scans.gradle.com/s/riqmfnuuhg6zg

**Comment by jjohannes** [comment]
@lschwahn Using the "classes" instead of the "jar" is an optimisation that improves performance on Unix/Linux systems for large projects.

What you are doing is a quite specific setup (using maven local as alternative to local projects). It's fine, but then you also need to deal with the sideffects. 

I would say using **org.gradle.java.compile-classpath-packaging=true** option to make sure "Jar"s are used everywhere is **the solution for you**.

In the doc it says "recommended" if you suffer performance issues on Windows. It does not mean you cannot use it to solve other special cases like yours.

Note: The "conditional subsitution" is an outdated pattern - see note on top of the [Customizing resolution of a dependency directly](https://docs.gradle.org/current/userguide/resolution_rules.html#sub:conditional_dependency_substitution) section. It was written before the build cache even existed. Now that you use the remote build cache, maybe you do not need to do this at all and can just clone the whole project and rely only on the build cache? 

There is nothing we can or plan to do to make this setup produce a cache hit. Hence I am closing the issue.
