### ISSUE TITLE
Version Catalog + Extensions

### ISSUE THREAD

**Issue by JvmName** [gradle/gradle#16665]
Extension (`@aar`, `@jar`) are not idiomatic to use with the new Version Catalog format. 

### Current Behavior or error
Say I have a coordinate `com.fullstory:instrumentation-full:1.2.3@aar`. 

I can add everything except the extension to my TOML file (and probably `settings.gradle.kts`, but I haven't tried that):

```TOML
[versions]
fullstory = "1.2.3"

[libraries]
fullstory = { module = "com.fullstory:instrumentation-full", version.ref = "fullstory" }
```

Then, when I actually _use_ the artifact, I have to do this: 
```kotlin
implementation(libs.fullstory) { 
    artifact {
        name = "instrumentation-full"
        type = "aar"
    }
}
```

Although this technically works (thanks to @melix for the syntax help), it does mean that there's additional code I must now copy-paste everywhere that I want to use `libs.fullstory`. Also this is clearly not an optimal solution, since I have to duplicate the artifact name (`instrumentation-full`) everywhere. 

### My Suggestions
I understand that the catalog ought not have any knowledge of name/type/classifier/excludes, but I really do think this would be the easiest "fix" for most naive users: 

```TOML
# TOML suggestion
fullstory = { module = "com.fullstory:instrumentation-full", version.ref = "fullstory", type = "aar" }
```

My other suggestion is to add some sort of overload to `DependencyHandler` that allows the user to specify the type/extension/classifier as part of the `implementation`: 

```kotlin
# Kotlin suggestion
implementation(libs.fullstory, type = "aar")
```

**Comment by melix** [comment]
Long story short: this is intentional and very unlikely to change. 

A version catalog talks about dependency coordinates. The `type`, `name`, `classifier` or even `excludes` are not part of the coordinates: they belong to the dependency declaration site: for the same GAV coordinates, different consumers may use different "variants" of the same thing, or not exclude the same things.

The `type` or `classifier` correspond to a _variant selector_, and that's why you have to use them at the declaration site:

```
dependencies {
    implementation(libs.fullstory) { 
        artifact {
            type = "aar"
        }
    }
}
```

However, the `name` that you had to use shouldn't be required in this case, this looks like a bug. So in practice, I can only agree on _declaration site_ DSL improvements.

Note that wrt to the `@aar` notation, this is just an "artifact" (pun not intended) of the way aar libraries are published today using the "pom format". With proper Gradle module metadata, you wouldn't have to declare `@aar` at all because Gradle would figure out automatically what variant to use. This makes it even clearer that the `type="aar"` doesn't belong to the catalog.

**Comment by vlsi** [comment]
My 2c: classifier-like files in Maven lack their own metadata (e.g. you can't determine third-party dependencies for -tests.jar artifact :( ), so I agree embracing proper project modelling (e.g. standalone artifacts with their own pom or variants via Gradle Metadata) at cost of having to repeat type=.. for non-idiomatic cases makes sense.

**Comment by wetted** [comment]
Same complaint here. I have a module with multiple artifacts (e.g. `classifier=native, ext=zip` and `classifier=programs, ext=zip`), so I want tp be able to use something, like,

```
    native64(libs.nativefoo) {
        // 'name' is required and leaks catalog implementation details
        // name = 'native-bar'
        classifier = 'native'
        type =  'zip'
    }
    programs(libs.nativefoo) {
        // 'name' is required and leaks catalog implementation details
        // name = 'native-bar'
        classifier = 'programs'
        type =  'zip'
    }
```

But since it requires `name` I have to know something about what `nativefoo` is an alias for, which  in turn means if the artifact name changes I have to change it in all my projects, and not just the catalog. That defeats an advantage of catalogs if details leaked into multiple builds and have to be maintained.

I probably won't use the catalog for custom classifiers and types just yet,  until I have a way to do that without leaking details of the catalog into builds (i.e. the name thing is fixed). Otherwise, this looks to be a very cool and useful feature. 

I am OK with using this syntax:
```
    native64(libs.nativefoo) {
        classifier = 'native'
        type =  'zip'
    }
    programs(libs.nativefoo) {
        classifier = 'programs'
        type =  'zip'
    }
```

But it would be nice if something like this worked too:
`native64("${libs.nativefoo}:native:zip")`

**Comment by Vampire** [comment]
That's a different complain actually.
You just seem to miss wrapping your type and classifier in `artifact { ... }`.

**Comment by wetted** [comment]
> That's a different complain actually.
> You just seem to miss wrapping your type and classifier in `artifact { ... }`.

Is there some other way for me to use catalogs to resolve artifacts with custom classifiers/types or should I open a separate issue for this?

**Comment by melix** [comment]
I don't understand what you're asking for. You should be able to write:

```
native64(libs.nativefoo) {
      artifact {
        classifier = 'native'
        type =  'zip'
    }
}
```

**Comment by wetted** [comment]
@melix 

That construct is perfectly suitable, but without `name` it fails with the error,
```
Could not resolve all dependencies for configuration ':compileClasspath'.
Artifact name must not be null!
```

I don't want to use `name` because that exposes a hidden detail of the catalog definition, and if that changes every build that uses that artifact has to change too. For now -- and I'm using 7.0-r2-2 -- I am forced to use 

```
native64(libs.nativefoo) {
    artifact {
        name = 'native-bar' // this is a hidden implementation detail of the catalog :(
        classifier = 'native'
        type =  'zip'
    }
}
```

In my comment above I mistakenly omitted the `artifact` closure. I meant to have it there. Nevertheless, it won't work without `name`.

**Comment by melix** [comment]
The fact the `name` is mandatory _sounds like a bug_, as I said before (I'm saying sounds like, because there are often edge cases we don't think about with this kind of dependency management bugs). Please open an issue for this.

**Comment by wetted** [comment]
Done, see #16768

**Comment by kenshin171** [comment]
```
[versions]
fullstory = "1.2.3@aar"

[libraries]
fullstory = { module = "com.fullstory:instrumentation-full", version.ref = "fullstory" }
```

is this technically workable? appending the extension to the `version.ref`?

**Comment by JvmName** [comment]
> is this technically workable? appending the extension to the version.ref?

@kenshin171 good idea! Unfortunately that doesn't work because Gradle appends the `@aar` when constructing the maven repo URL, like so:

```https://maven.fullstory.com/com/fullstory/instrumentation-full/1.16.2@aar/instrumentation-full-1.16.2@aar.pom```

**Comment by wetted** [comment]
I still wish the catalog feature would add support for something like (given a `native64` configuration) `native64("${libs.foo}:native@zip")` so we can resolve artifacts with specific classifiers irrespective of the jar (i.e. unclassified) artifact. Without that support it's rather kludgy to manage classified artifacts with regard to version catalogs, and defeats the reason for using one.

**Comment by hakanai** [comment]
I tried to use this `artifact {}` syntax in a Kotlin Multiplatform project, and was shot down because the method apparently doesn't exist. So add me to the list of people who want a decent way to do this. :(

**Comment by Vampire** [comment]
What did you try? Which method is not available?

**Comment by hakanai** [comment]
```kotlin
kotlin {
    sourceSets {
        val jvmMain by getting {
            dependencies {
                implementation(libs.lwjgl)
                runtimeOnly(variantOf(libs.lwjgl) { // <- Unresolved reference: variantOf
                    classifier("natives-windows")
                })
```

**Comment by Vampire** [comment]
If the KGP API does not support it, don't use its syntax sugar and use the normal Gradle API. ;-)
For example:
```kts
kotlin {
    jvm()
}
val jvmMainRuntimeOnly by configurations
dependencies {
    jvmMainRuntimeOnly(libs.lwjgl) {
        artifact {
            classifier = "natives-windows"
        }
    }
}
```
or:
```kts
kotlin {
    jvm()
    sourceSets {
        val jvmMain by getting {
            dependencies {
                runtimeOnly(libs.lwjgl.map {
                    project.dependencies.create(it, closureOf<ExternalModuleDependency> {
                        artifact {
                            classifier = "natives-windows"
                        }
                    })
                })
            }
        }
    }
}
```
