### ISSUE TITLE
Using java toolChain should produce the same output than default compilation

### ISSUE THREAD

**Issue by vgalloy** [gradle/gradle#16704]
### Context
I'm currently trying to use the java module system (jigsaw) on my existing java project. This project use the java toolchain.
Every seems ok until I accidentally remove the tool chain definition. Since I'm using the same version of Java on my computer, I'm expecting the same result.

### Expected Behavior
On Java 11 building with `toolchain.languageVersion.set(JavaLanguageVersion.of(11))` should not change the compilation result

### Steps to Reproduce
I extracted with the minimal amount of code to reproduce the bug. This code can also be founded at: https://github.com/vgalloy/gradle-strange-behaviour

**build.gradle.kts**
```
plugins {
  id ("java-library")
}

java {
  modularity.inferModulePath.set(true)
//  toolchain.languageVersion.set(JavaLanguageVersion.of(11))
}

dependencies {
  api("eu.europa.ec.joinup.sd-dss:dss-pades:5.7")
}

repositories {
  mavenCentral()
  maven {
    url = uri("https://ec.europa.eu/cefdigital/artifact/content/repositories/esignaturedss/")
  }
}
```

**src/main/java/com/vgalloy/sample/Main.java**
```
package com.vgalloy.sample;

import eu.europa.esig.dss.pades.PAdESSignatureParameters;

public class Main {

  public static void main(String[] args) {
    new PAdESSignatureParameters().setSignatureFieldId("sample");
  }
}
```

**src/main/java/module-info.java**
```
module com.vgalloy.sample {
  requires jpms_dss_pades;
  requires jpms_dss_cades;
}
```

Running `$ ./gradlew build` as long as the line `toolchain.languageVersion.set(JavaLanguageVersion.of(11))` is commented
with the following error:

```$ ./gradlew build

> Task :compileJava FAILED
vgalloy/gradle-strange-behaviour/src/main/java/com/vgalloy/sample/Main.java:8: error: cannot access CAdESSignatureParameters
    new PAdESSignatureParameters().setSignatureFieldId("sample");
                                  ^
  class file for eu.europa.esig.dss.cades.CAdESSignatureParameters not found
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.
```

The same problem occurred if
* You change the java version (14, 15)
* You upgrade gradle to version `7.0-rc-1`
* You define `sourceCompatibility` / `targetCompatibility`
* You change the toolchain vendor

### Your Environment

```$./gradlew --version

------------------------------------------------------------
Gradle 6.8.3
------------------------------------------------------------

Build time:   2021-02-22 16:13:28 UTC
Revision:     9e26b4a9ebb910eaa1b8da8ff8575e514bc61c78

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11 (Oracle Corporation 11+28)
OS:           Linux 5.4.0-70-generic amd64
```

**Comment by vgalloy** [comment]
Any news on this subject ? 
This behaviour/bug is still present with version 7.1.
To be honest I don't know if this example should compile (or not) but I expect the result be the same regardless of the toolchain usage. Did I miss something ?

**Comment by ljacomet** [comment]
For some reason when Gradle issues the compiler command with `-source 11 -target 11` the compilation fails.
When the setup changes that command to use `--release 11` then the compilation succeeds.

The later is what happens when you select a toolchain with Java > 9 or if you do it by hand `tasks.compileJava.options.release.set(11)`

**Comment by ov7a** [comment]
Sorry for the late reply.

Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

As @ljacomet said, when you set the toolchain, that implies the `release` compiler option is set, and when the toolchain is unspecified, the JVM running Gradle is used, so only `-source 11 -target 11` options are set. And this does not mean that JVM 11 is used, because other JVM can be used with these options.

See also [java compiler documentation](https://docs.oracle.com/en/java/javase/11/tools/javac.html#GUID-AEEC9F07-CB49-4E96-8BC7-BCC2C7F725C9)
