### ISSUE TITLE
Dependency on a subproject module should be caught early

### ISSUE THREAD

**Issue by ncimino** [gradle/gradle#16754]
### Current Behavior

Gradle will allow a developer to create a module dependency e.g.

        implementation 'com.company:artifact_id:1.0.0'

...even if the module is produced by this build. The solution is as simple as: 'don't do that' ;)

However, for large multi-project builds developers may not be aware that the module that they are depending on is coming from the same root-project.  

### Expected Behavior

Gradle should be able to detect this case for multi-project builds and if the module is a module that will be published from any of the sub-projects issue an error.

The correct way to do create this dependency is a project dependency:

    implementation project(':artifact_id')

### Context

This case can be encountered when adding a new project and this circular dependency will only be caught when building from a clean repository - as the previously generated artifacts can actually be depended on via a module dependency.

### Steps to Reproduce 
Create project with two sub-projects
Publish sub-project 1 to maven local
Create module dependency in sub-project 2 on sub-project 1
Build sub-project 2
NOTICE: It worked
Remove maven local repo
Build sub-project 2
NOTICE: It failed

### Your Environment
Gradle 6.8.3

**Comment by ncimino** [comment]
I have to run right now, but I will try to put together an example soon.

**Comment by jjohannes** [comment]
@ncimino I am not sure which issue there is you want to have solved as you never submitted a complete example. But from the description it sounds like you are doing something that Gradle won't support better. For published dependencies, cycles are allowed (to be more lenient, as published metadata is sometimes "weird"). We won't change that.

Notes:

- `mavenLocal()` is only for the interaction with Maven builds. You should not use it if you are Gradle only.
- Normally, you should directly depend on the projects in your build and not on a published versions of them. From the description, it is also not clear why you want to do it anyway.
- If you want to use coordinates instead of `project(...)` notation, you can opt-into that (starting with Gradle 6.8.x) by [making your build a composite build](https://docs.gradle.org/current/userguide/composite_builds.html#included_build_declaring_substitutions). The coordinates will then be resolved to the project and Gradle will build it when required or fail when there is a cycle.
