### ISSUE TITLE
HttpBuildCache should allow custom headers

### ISSUE THREAD

**Issue by fkorotkov** [gradle/gradle#1680]
It appeared https://github.com/uber/buck-http-cache is perfectly working with Gradle 3.5! It supports horizontal scaling which is crucial for speed and tolerance for a failed node

It will be great to allow pass custom headers within `GET` and `PUT` requests to the cache. That way we'll be able to distinguish CI and user traffic, add `AUTHORIZATION` header support and many other features.

I think it will be also great for other custom implementations `HttpCache`

**Comment by big-guy** [comment]
Hey @fkorotkov,

Thanks for trying it out. Looking at what the [Buck HTTP cache](https://buckbuild.com/concept/http_cache_api.html#binary_http) expects, I'm not sure if this should be working.  The Gradle build cache has a simpler GET/PUT scheme. When we PUT, we don't include metadata keys and we don't expect to get metadata in a GET.

We will probably add things to the built-in `HttpBuildCache` that may make these more different.  We also don't plan on making the built-in `HttpBuildCache` more configurable (with custom headers) and support for other authentication schemes will follow what we do for repositories.

We intended to make it possible for plugin authors to create their own `BuildCache` connector implementations, so it's feasible to have a connector to the uber/buck-http-cache. It would be very similar to the [Hazelcast plugin](https://github.com/gradle/gradle-hazelcast-plugin) that Lorant created.

I'm closing this since we're unlikely to test the `HttpBuildCache` against this backend. Thanks again for the feedback!

**Comment by fkorotkov** [comment]
Thanks for responding @big-guy. Metadata you referring is an implementation detail of artifacts. Essentially build cache is a binary blob storage by key.

I can verify `BuildCache` is working if you point it to `<buck-cache-host>/artifacts/key/`.

My request to add headers is very generic and not tied to concrete Buck Cache implementation. I bet people will ask for that as well. Headers can be used for authorization, load balancing, distinguishing CI and personal traffic, etc.

I'm more then happy to work on a patch if you'll accept it. You already add a custom `X-Gradle-Version` header to all requests. If you are still opposite to this it's also fine. We'll just build a custom plugin as you mentioned.

cc: @Rooz-sf this is the issue I was talking on Tuesday.
