### ISSUE TITLE
Switch to Gradle 7.0 causes "unknown property 'runtime'"

### ISSUE THREAD

**Issue by hannesa2** [gradle/gradle#16823]
When I switch to Gradle 7.0 https://github.com/ytai/ioio/pull/250/files I run into a build error

It's a follow up of #16822

### Expected Behavior
No error should appear

### Current Behavior
I run into 
```
> Could not create task ':HelloIOIOConsole:distJar'.
   > Could not create task of type 'OneJar'.
      > Could not get unknown property 'runtime' for configuration container of type org.gradle.api.internal.artifacts.configurations.DefaultConfigurationContainer.
```

This is the causing block

```
plugins {
    id "com.github.onslip.gradle-one-jar" version "1.0.6"
}

task distJar(type: OneJar) {                              <--- This is the error line !
    mainClass = 'ioio.examples.hello_console.HelloIOIOConsole'
}
```

### Steps to Reproduce 
https://github.com/ytai/ioio/pull/250/files

### Your Environment

Here you see the error https://github.com/ytai/ioio/pull/250/checks?check_run_id=2340438978

**Comment by jjohannes** [comment]
The `runtime` configuration has been removed in Gradle 7.0 after it has been deprecated for a while.

Please use `runtimeOnly` instead. see: https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

If the error is caused by the `com.github.onslip.gradle-one-jar` please open an issue there.
