### ISSUE TITLE
Download core plugins on demand

### ISSUE THREAD

**Issue by pioterj** [gradle/gradle#1684]
Reduce the size of the distribution by downloading core plugins on demand, similarly to community plugins. 

### Expected Behavior

Core plugins are downloaded on the first time they are actually used and then cached. Distribution size is significantly reduced. 

### Current Behavior

Core plugins are included in the distribution. Binary only distribution weights about 70 MB. It can take a while to download, especially on a slow connection.  

### Context

Most user only use a fraction of plugins provided in the distribution.  

From user perspective the benefit would be improved performance after upgrading Gradle, when using Gradle for the first time or on a new machine. The last point may be especially beneficial for some CI environments. 

From Gradle team perspective it would allow gathering better data on how often different core plugins are used and on Gradle's adoption in different ecosystems.

### Additional considerations

IDEs should be able to continue to provide the same level of assistance. For example Intellij IDEA prompts to "configure Gradle wrapper to use distribution with sources" for better integration.

**Comment by bmuschko** [comment]
This issue is pretty much an epic for epics and will require a lot of stories that need to be implemented before we get to the essence of this issue. 

It will touch on the following aspects:

- Core plugins do not use any more internal Gradle API
- Internal APIs are made public
- Core plugins can be declared in a build with their own dependency notation
- Gradle provides a dependency notation for public and internal API
- Core plugins can be developed and published separately from the rest of Gradle

**Comment by adammurdoch** [comment]
Something we need to be careful of is making this some massive exercise that we never start. We can easily implement this right now. We don't need any of those things mentioned above in order to bust up the distribution, even though each of the features above is very useful.

All we need to do make this work is to take the existing distribution, bust it into several smaller zips, publish them in exactly the same way we do now, to exactly the same place we do now, alongside the larger -bin and -all distributions. When a core plugin is referenced, either by id or by one of its types, we go and download the relevant chunk.

Of course it's better if we used entirely the same mechanics for core plugins and community plugins at every step of the plugin authoring, testing, releasing, discovery and provisioning lifecycle, but we shouldn't be blocked waiting for this long term change to be complete. There's already a lot of value going from "core plugins are provisioned by bundling them in the distribution, community plugins are provisioned by downloading them" to "all plugins are provisioned by downloading them" even if no other difference between core and community plugins is addressed.

**Comment by adammurdoch** [comment]
In other words, this is _explicitly not_ an epic of epics. It's a single feature we can implement in a handful of stories.

**Comment by ov7a** [comment]
Related:
* https://github.com/gradle/gradle/issues/3513
