### ISSUE TITLE
Add a deprecation warning (in 6.x and earlier) when there is no settings.gradle file

### ISSUE THREAD

**Issue by hiljusti** [gradle/gradle#16859]
### Expected Behavior

Running Gradle with the latest 6.x version warns me that upgrading to 7.0 will require a settings.gradle file

### Current Behavior

Running (e.g.) `gradle build --warning-mode fail` passes with no warnings in Gradle 6.8.3

### Context

Building a gradle project without a `settings.gradle` file in Gradle 7.0 results in the following build failure:

```
FAILURE: Build failed with an exception.

* What went wrong:
Executing Gradle tasks as part of an undefined build is not supported. Make sure that you are executing Gradle from a folder within your Gradle project. Your project should have a 'settings.gradle(.kts)' file in the root folder.
```

This is a reasonable, documented failure. It's also easy enough to address with a simple `touch settings.gradle`.

It would be nice, though, if I had gotten a deprecation warning on this change in Gradle 6.8.3 (which I was using earlier)

**Comment by hiljusti** [comment]
Beautiful, thanks!

**Comment by big-guy** [comment]
@hiljusti I looked at this again and I think I was a bit confused by what you were reporting.

In 6.8, if you're missing both a build.gradle and a settings.gradle, you'll get a deprecation warning.
In 7.0, you only get a failure when you're missing both a build.gradle and a settings.gradle file. 

In 6.9 RC1, I made it so if you're missing a settings.gradle (but still have a build.gradle), you'll get a deprecation warning. I think this was wrong because I thought 7.0 would generate an error for the same scenario. 

Could you confirm if you were seeing an error with 7.0 when you were only missing a settings file?

**Comment by hiljusti** [comment]
Yeah I was seeing failures in 7.0 with a `build.gradle` (or `build.gradle.kts`) but no `settings.gradle` file.

**Comment by big-guy** [comment]
@hiljusti do you have a reproducer? if I do the naive thing, I don't see an error with 7.0 when I have a build.gradle but no settings.gradle file.

**Comment by hiljusti** [comment]
I tried to replicate with a `gradle init` basic projects and it didn't complain when I removed the `settings.gradle` file.

Some context: We have plugins that teach Gradle how to resolve dependencies from our internal (non-maven-shaped) package management system. We are definitely doing some weird things and adding a deprecation warning _just for us_ is overkill since we already know about it.

So... @big-guy I think it's not worth pursuing. I'm fine to leave this closed, or If you need to roll back changes that's ok too. I was assuming this was the behavior of 6 -> 7, but kinda fired from the hip without checking if this was actually the out-of-the-box behavior.
