### ISSUE TITLE
RootProject extension can be changed by subProjects

### ISSUE THREAD

**Issue by YaoWang0515** [gradle/gradle#16873]
when ceate a 'myTest' extension in a root project's build.gradle like this：
![image](https://user-images.githubusercontent.com/29978458/115100219-d2186d80-9f6d-11eb-96f6-0926f2a77f38.png)

and then there have a java library module, I can also use the 'myTest' extension in build.gradle like this：
![image](https://user-images.githubusercontent.com/29978458/115100123-3c7cde00-9f6d-11eb-95ee-d0f4697d7252.png)
The result after sync is:
![image](https://user-images.githubusercontent.com/29978458/115100142-633b1480-9f6d-11eb-918b-2c357eeae406.png)
so I have two questions:
1.why subProjects can use extension defined in rootProject
2.subProject's extension will change the  rootProject extension value after gradle.projectEvaluated

**Comment by oesolutions** [comment]
1. One of the scopes that properties are resolved from is, "The extra properties and convention properties are inherited from the project's parent, recursively up to the root project.". https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#N14A39 So when you access a property/extension that does not exist on the subproject, it is instead found on its parent.
2. Due to #1 and the fact that there is no `myTest` extension on the `:lib` project:
    1. The root project is evaluated, `sss` is printed.
    2. The `:lib` subproject is evaluated, `myTest` does not exist, it is found in the parent/root. The root project's extension value is changed to `aaaaa` and that's what is printed from then on.

**Comment by YaoWang0515** [comment]
Thank you for your reply,So I guess it's a feature,However,sometimes this can cause some unexpected problem,Is there any way to 
mask this feature?

**Comment by ljacomet** [comment]
This is an unfortunate consequence of the way the Gradle Groovy DSL handles delegation.
The Gradle team is working on better isolating projects so that cross configuration is no longer possible, this may end up resolving this issue.
