### ISSUE TITLE
gradle -v - OS reported as x86_64 on Apple Silicon

### ISSUE THREAD

**Issue by theq86** [gradle/gradle#16917]
I installed Gradle 7.0 on my mac using the binary only release. I was wondering why my OS would be shown as x86_64, although I'm using an Apple M1 chip and that should be supported by now.

```
gradle -v

------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          16 (AdoptOpenJDK 16+36)
OS:           Mac OS X 10.16 x86_64
```

My terminal does not run under Rosetta2, also the /bin/gradle script runs natively (checked like so: https://cutecoder.org/software/detecting-apple-silicon-shell-script/)

### Expected Behavior

I would expect the correct arch to be printed out

### Current Behavior

OS:           Mac OS X 10.16 x86_64 is printed out

### Context

Stumbled upon it after installation. Seems to be just a display error

### Your Environment

Build scan URL:

**Comment by oesolutions** [comment]
Gradle's version output displays the value of the `os.arch` system property. Realistically, this is actually the architecture of the JDK, not the operating system/kernel. Since I don't see a native ARM/M1 build of AdoptOpenJDK on their website, I guess you must be running the x86_64 build and that's why the architecture is reported as such.

Related; you might also notice discrepancies with the displayed OS version, which is also coming from the JDK, not Gradle.
https://discuss.gradle.org/t/incorrect-mac-os-version-reported-by-gradle/39168

**Comment by Thunderforge** [comment]
> OS: Mac OS X 10.16 x86_64 is printed out

Shouldn't it also say macOS 11? There is no macOS 10.16 (10.15 was followed by 11).

**Comment by ljacomet** [comment]
Nothing to do on the Gradle side as these values are coming from the JVM directly.
