### ISSUE TITLE
Declaring and Building Sets of Dependency Versions

### ISSUE THREAD

**Issue by eaaltonen** [gradle/gradle#17009]
In response to your recent post about [Version Catalogs](https://melix.github.io/blog/2021/03/version-catalogs.html)

Having looked at:
* https://docs.gradle.org/current/userguide/variant_attributes.html#variant_attributes
* https://docs.gradle.org/current/userguide/component_metadata_rules.html#sec:custom_status_scheme
* https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:documenting-dependencies

I was not sure if this is covered so I'll ask here.

As a developer, I have two very common needs:
* compile and test the _stable, reproducible build_
* compile and test the _latest, bleeding edge build_, in order to notice needed changes.

In pseudo, I would like to declare the following(ish) `build.gradle`

```
dependencySets {
    set {
        name 'stable'
        dependencies {
            foo 1.2
            bar 2.3
        }
    }
    set {
        name 'latest'
        dependencies {
            foo 1+
            bar 2+
        }
    }
}
```

And then build these with the flick of a switch:

* `./graldlew build` would build the `stable` by default
* `./graldlew build --dependencySet=latest` would fetch the latest versions and build and test against those.

It wasn't immediately clear if this is yet possible, so I'll classify this as a feature request for now.

_Note: some projects might want to declare further sets, such as_ `next-stable`.

**Comment by melix** [comment]
Thanks for the feature request @eaaltonen! I'm actually not convinced we need another DSL for this particular feature. It's actually pretty simple to implement yourself. For example, let's imagine that you have 2 files, `libs.stable.versions.toml` and `libs.canary.versions.toml`.

Then you can easily tell Gradle to use one or the other depending on a system property:

.settings.gradle
```groovy
dependencyResolutionManagement {
    versionCatalogs {
        libs {
	        def channel = providers.systemProperty('channel')
	           .forUseAtConfigurationTime()
	           .getOrElse('stable')
	        println("Using versions from $channel channel")   
	        
	        from(files("gradle/libs.${channel}.versions.toml"))
	    }
    }
}
```

Then to use the "canary" versions, you'd just need to run with `-Dchannel=canary`.

Now it doesn't mean that there's no interest in providing a way to _override_ versions in a more adhoc way. For example we're thinking of binding system properties automatically to version catalog "versions" definitions so that you can easily change a version from CLI, e.g `-Doverride.libs.versions.myLib=1.5`.

**Comment by eaaltonen** [comment]
> I'm actually not convinced we need another DSL for this particular feature.

Glad to hear it.

My pseudo proposition would show in git as added and removed lines. The files will show as deleted, moved and added. While I have a slight preference for added and removed lines. It's indeed questionable whether new DSL is justified.

> Now it doesn't mean that there's no interest in providing a way to override versions in a more adhoc way. For example we're thinking of binding system properties automatically to version catalog "versions" definitions so that you can easily change a version from CLI, e.g -Doverride.libs.versions.myLib=1.5.

Also very good. The need for injecting version overrides comes up very often when working with Continuous Integration pipelines. I assume this feature would be welcomed by the developer community.

**Comment by eaaltonen** [comment]
Also overlaps with [dependency locking](https://docs.gradle.org/current/userguide/dependency_locking.html#selectively_updating_lock_state_entries).
