### ISSUE TITLE
Follow up on WorkerExecutor.submit() deprecation with third-party plugins

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#17047]
The deprecation of `WorkerExecutor.submit()` broke the following smoke tests:

- `AndroidPluginsSmokeTest.android library and application APK assembly (agp=#agpVersion, ide=#ide)`
- `AndroidSantaTrackerCachingSmokeTest.can cache Santa Tracker Android application (agp=#agpVersion)`
- `AndroidSantaTrackerSmokeTest.can lint Santa-Tracker (agp=#agpVersion)`
- `AndroidSantaTrackerSmokeTest.check deprecation warnings produced by building Santa Tracker (agp=#agpVersion)`
- `AndroidSantaTrackerSmokeTest.incremental Java compilation works for Santa Tracker (agp=#agpVersion)`
- `KotlinPluginSmokeTest.kotlin javascript (kotlin=#version, workers=#workers)`
- `KotlinPluginSmokeTest.kotlin jvm (kotlin=#version, workers=#workers)`
- `ThirdPartyGradleModuleMetadataSmokeTest.publish`

We should follow up with the respective plugin authors as necessary, and add a link to the issue where fixing the deprecation is tracked:

- [x] Android Gradle plugin
- [x] Kotlin Gradle plugin
- [x] Gradle publish plugin (is that what broke `ThirdPartyGradleModuleMetadataSmokeTest`?)

See https://github.com/gradle/gradle/pull/17044 for details on why the deprecations were not detected earlier.

**Comment by rieske** [comment]
This is an issue in JetBrains tracker for 7.1 deprecations in the Kotlin plugin: https://youtrack.jetbrains.com/issue/KT-46019

**Comment by lptr** [comment]
@rieske Great, thanks. Does this Kotlin issue cover all the occurrences listed above?

**Comment by rieske** [comment]
I will double-check and make sure it does.

**Comment by rieske** [comment]
I double-checked the deprecations coming from Android plugin - those I have followed up on in Slack when I was adding the deprecations - they will be fixed in AGP 7.0.

**Comment by rieske** [comment]
Fix for GMM test: https://github.com/gradle/gradle/pull/17064

**Comment by lptr** [comment]
> I double-checked the deprecations coming from Android plugin - those I have followed up on in Slack when I was adding the deprecations - they will be fixed in AGP 7.0.

Do we have a link to an issue on issuetracker.google.com?

**Comment by rieske** [comment]
I am not aware of an issue for Android deprecations in the Google tracker.
However, it looks like latest versions of AGP (`4.2.0-rc01` and `7.0.0-alpha14`) that we smoke test no longer emit deprecation warnings and the ones we have come from AGP `4.1.x` line.

The only remaining TODOs for followup are in `ThirdPartyGradleModuleMetadataSmokeTest` https://github.com/gradle/gradle/pull/17044/files#diff-4c90691aa5d3f8edabaa3d62fc482aaf3ea7a6a35401ca716c21705e56a48a23 and most likely because of AGP `4.1.3` being tested. I'll see if I can bump it after the current change gets through the pipeline.

**Comment by ljacomet** [comment]
All done
