### ISSUE TITLE
extendsFrom is not working with custom configurations in new Gradle 7.

### ISSUE THREAD

**Issue by Marek00Malik** [gradle/gradle#17042]
I'm trying to setup a new project that has custom configuration modules (named `integrationTest`) that extends dependencies from the test module.  Currently running the configuration on the latest Gradle 7, the custom module is not inheriting any dependencies from the pointed configuration.

Bellow, you can find a link to the project that has the problem.
https://github.com/Marek00Malik/makromapa-pay

The same configuration but on Gradle 6.8 is working correctly. I couldn't find any information about a breaking change regarding the `extendsFrom` function in the configuration section for the release notes (https://docs.gradle.org/current/userguide/upgrading_version_6.html).

**Comment by jjohannes** [comment]
@Marek00Malik I think you are running into this: https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

Some configurations that were deprecated are now removed. This changes the hierarchy of configurations and gives the impression, that `extendsFrom` is not working. Unfortunately, if you do the following in a _Groovy DSL_ build script, instead of giving you an error, Gradle just silently creates new empty configurations:

```
integrationTestRuntime.extendsFrom(testRuntime) // integrationTestRuntime and testRuntime no longer exists (!)
integrationTestCompile.extendsFrom(testImplementation) // integrationTestCompile no longer exists (!)
```

In your example, I think your setup should look like this:
```
configurations {
    ...
    
    developmentOnly
    runtimeClasspath.extendsFrom(developmentOnly)

    integrationTestRuntimeOnly.extendsFrom(testRuntimeOnly)
    integrationTestImplementation.extendsFrom(testImplementation)
    integrationTestCompileOnly.extendsFrom(testCompileOnly)
}
```
