### ISSUE TITLE
All BuildOperations should generate log events

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1709]
### Expected Behavior
All BuildOperations should be available to be logged. Right now BuildOperations logs do not have some way to state their level of detail, so we may need to add this concept in order to complete this. Progress Logging all build operations by default shows too much detail.

![screen shot 2017-03-30 at 10 40 32 am](https://cloud.githubusercontent.com/assets/51534/24518048/544d790c-1535-11e7-9bfc-f1f4754dad81.png)

### Current Behavior
Only 3 BuildOperations set a "progress display name" and are therefore logged. 

### Context
In order to unify BuildOperations and ProgressLogger, one must be a superset of the other. @adammurdoch has suggested it may be the simplest strategy to have all BuildOperations generate progress logs, then convert all other usages of the ProgressLogger API to BuildOperations.

**Comment by lacasseio** [comment]
Just pitching an idea here. Could we use some qualifier on the detail level for each `BuildOperation` and attach the detail level to the log level? We could have a debug work-in-progress which would show all `BuildOperation` and the lifecycle work-in-progress would show up to a certain level? The problem is `BuildOperation` don't and, most likely, shouldn't have a log level attached to them. It become hard to filter them in the console as we only have access to [`OperationStartEvent`, `OperationEvent` and `BuildOperationInternal`](https://github.com/gradle/gradle/blob/3ee024012afb1ca075cd6e411a884723a944783e/subprojects/logging/src/main/java/org/gradle/internal/logging/sink/OutputEventRenderer.java#L296-L314). We could simply set the `progressDisplayName` for the `BuildOperation` we want to display in the console but that may couple those two concepts together in ways we may not want.

**Comment by eriwen** [comment]
This seems to be necessary for #1818 so I'm picking this up now.

**Comment by eriwen** [comment]
Complete
