### ISSUE TITLE
Switching from all to bin wrapper in an existing project fails the build

### ISSUE THREAD

**Issue by AMilassin** [gradle/gradle#17178]
Given an existing project. Switching from an _all_ wrapper to a _bin_ wrapper will fail all builds if the `~/.gradle/wrapper` folder does not contain both wrappers. Something is cached in the projects `.gradle` folder and the `./gradlew` execution will try to access the _all_ wrapper for the project even though it should use the _bin_.

The following exception is present:
 ```
> java.nio.file.NoSuchFileException: /Users/<username>/.gradle/wrapper/dists/gradle-7.0.1-all/9uuh8w1zvoizo76q69rcku82c/gradle-7.0.1/lib/plugins/gradle-diagnostics-7.0.1.jar`
```

### Expected Behavior
Switching from all to bin wrapper works without issues.

### Current Behavior
Removing `<project>/.gradle` is required or having both _all_ and _bin_ wrappers downloaded in the `~/.gradle/wrapper` folder

### Steps to Reproduce 
 - create a project, with an empty `settings.gradle`
 - run `gradle --wrapper-version 7.0.1 --distribution-type all`
 - run `./gradlew build`
 - run `gradle --wrapper-version 7.0.1 --distribution-type bin`
 - remove the wrapper cache `~/gradle/wrapper`
 - run `./gradlew build`

Build will fail with the exception mentioned above.

**Comment by ljacomet** [comment]
@gradle/execution Could you take a look?

**Comment by wolfs** [comment]
I took a look. Here are closer reproduction instructions:
```
> gradle wrapper --gradle-version 7.0.1 --distribution-type all

> ./gradlew build

> ./gradlew --status
   PID STATUS   INFO
 19642 IDLE     7.0.1

> gradle wrapper --gradle-version 7.0.1 --distribution-type bin

> rm -rf ~/.gradle/wrapper/dists/gradle-7.0.1-*

> ./gradlew --status
   PID STATUS   INFO
 19642 IDLE     7.0.1

> ./gradlew build
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'daemon-all-vs-bin'.
> java.nio.file.NoSuchFileException: ~/.gradle/wrapper/dists/gradle-7.0.1-all/9uuh8w1zvoizo76q69rcku82c/gradle-7.0.1/lib/plugins/gradle-diagnostics-7.0.1.jar

> ./gradlew --status
   PID STATUS   INFO
 19642 IDLE     7.0.1
```

So the problem is that a Gradle daemon is running, and we re-use this Gradle daemon no matter if the all distribution is used or the bin distribution is used. So if a daemon is running started from the all distribution, then the distribution type is changed and then you run another build the daemon running with the all distribution is still in use.

If you now remove the downloaded distributions, when running a new build the wrapper will correctly re-download the bin distribution, though the daemon is still running with the classpath pointing to the all distribution. So on the next invocation the build fails.

It is not very surprising that a Gradle daemon does not work after the files from its distribution have been deleted. The only thing you need to do is to run `./gradlew --stop` before/after deleting the downloaded wrapper directory. Then everything will work again afterwards.

I am not sure we need to do something on the Gradle side here. We could make the distribution type an input to the daemon, so we would automatically start a new daemon when the distribution type changes. Though I am not sure that is necessary.

**Comment by ljacomet** [comment]
I agree with the analysis provided. Since you can only hit this issue when actually deleting a downloaded wrapper _and_ leaving a daemon running, I do not see us prioritizing making the distribution type an input to the daemon.
