### ISSUE TITLE
Java modules not getting added to the module path

### ISSUE THREAD

**Issue by durganmcbroom** [gradle/gradle#17271]
I am currently trying to create a project using Java 9 Jigsaw modules, Gradle and Kotlin. When trying to build, the compilation fails due to my api module not getting added to the module graph.

### Expected Behavior
When building/testing i expect all modules to be added to the module graph and the compilation to have no errors.

### Current Behavior

When building, running etc. The required module(in this case `api.example`) is not added to the module graph and then fails to build. If i build the api module independently then it works fine as api doest depend on any other module.

This is the error: `e: Module api.example cannot be found in the module graph`

### Context
I am trying to use this to create a API with modules API and Base, they should both be able to compile into a single jar or the api should be able to compile into a jar itself(which works).

### Steps to Reproduce 

Here is a GitHub repo with the bare minimum to reproduce this issue: https://github.com/durganmcbroom/jigsaw-multiproject-test

### Your Environment

IDE: IntelliJ Ultimate
Java version: 11 
Operating system: MacOS Catalina 10.15.7

Build scan URL: https://scans.gradle.com/s/iiobgj4eaykjq

**Comment by durganmcbroom** [comment]
The issue appears to be with gradle and is solved by adding a `java` sources root in the same level as the kotlin and moving the `module-info.java`there, then apply the plugin 'org.javamodularity.moduleplugin' and running works fine.

**Comment by bmuskalla** [comment]
I think you're missing to properly enable JPMS support (`java.modularity.inferModulePath` is only enabled by default in Gradle 7 and up). Please [check the documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular) as well how to setup JPMS module support.

**Comment by durganmcbroom** [comment]
> I think you're missing to properly enable JPMS support (`java.modularity.inferModulePath` is only enabled by default in Gradle 7 and up). Please [check the documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_modular) as well how to setup JPMS module support.

I have followed that documentation almost to the line, and I still had the same issues as before. I mostly fixed it as mentioned above by using [this](https://github.com/java9-modularity/gradle-modules-plugin) and moving my `module-info.java` from the kotlin source set to a java one. However i still have issues with building and running tests.

If I go back and use the `java-library` plugin and upgrade to Gradle 7.0.2 my root project's `build.gradle` will look like this:

```groovy
plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm' version '1.5.0'
}

group 'org.example'
version '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'org.jetbrains.kotlin.jvm'

    repositories {
        mavenCentral()
    }

    dependencies {
        implementation "org.jetbrains.kotlin:kotlin-stdlib"
    }
}
```

Project Structure
```
jigsaw-multiproject-test/
├─ build.gradle
├─ settings.gradle
├─ base.example/
│  ├─ src/
│  │  ├─ main/
│  │  │  ├─ java/
│  │  │  │  ├─ module-info.java
│  │  │  ├─ kotlin/
│  │  │  │  ├─ source stuff...../
│  │  │  ├─ resources/
│  ├─ build.gradle
```

Then I get the error:
```
PATH_TO_MY_PROJECT/jigsaw-multiproject-test/api.example/src/main/java/module-info.java:2: error: package is empty or does not exist: org.example.api
    exports org.example.api;
```

The package specified is not empty and does exist.

**Comment by durganmcbroom** [comment]
Here is a new version of the test project i have created outlining the issue: https://github.com/durganmcbroom/jigsaw-multiproject-test

And a new scan: https://scans.gradle.com/s/542pc3z4nolam

**Comment by donat** [comment]
I took a look at your updated sample. I was able to fix the compilation error by introducing a class in the `org.example.api` package in `api.example/src/main/java`. @durganmcbroom let me know if it solves your issue.

**Comment by durganmcbroom** [comment]
> I took a look at your updated sample. I was able to fix the compilation error by introducing a class in the `org.example.api` package in `api.example/src/main/java`. @durganmcbroom let me know if it solves your issue.

Thanks for your response! 

I just tried that again, it seems to fix the issue for any classes in the java sources directory but then the kotlin sources seem to get completely ignored and then will throw the equivalent of a ClassNotFound when compiled.

Here is a screenshot of this:
![Screen Shot 2021-06-01 at 8 54 39 AM](https://user-images.githubusercontent.com/52637817/120354040-01cdcb80-c2b7-11eb-8bc3-c753f3c11c84.png)

And the error:
```
Error: Could not find or load main class org.example.base.MainKt in module base.example
```

**Comment by durganmcbroom** [comment]
After alot more looking i found a answer that works for me! Adding 
```groovy
compileKotlin.destinationDir = compileJava.destinationDir

test {
   useJUnitPlatform()
}
```
to all subprojects appears to do the trick!

Does this make sense to you all? It might be a good idea for this to be mentioned in the documentation since there is very little on java 9 modules or java 9 modules + kotlin!

Thanks for all the help!

**Comment by donat** [comment]
I'm happy you found a solution that works for you. I don't have any objections here. You are right though; we'll take a pass at the jpms documentation.

**Comment by durganmcbroom** [comment]
> I'm happy you found a solution that works for you. I don't have any objections here. You are right though; we'll take a pass at the jpms documentation.

One quick question actually! When trying to build my multiproject into one monolith style build running `./gradlew build` or `./gradlew jar` Just builds a jar with a manifest when i would like to build all the subprojects into one jar.

**Comment by jasin** [comment]
I'm having the exact same issue and can't seem to figure out how to debug this. I'm getting the below error
`e: Module com.zaxxer.hikari cannot be found in the module graph`

I have one subproject that relies on HikariCP. I'm also using Kotlin build file so compileKotlin and compileJava are unamed references. I don't know how to apply the destination fix posted by durgan. If I try

```
val compileKotlin by tasks
val compileJava by tasks

compileKotlin.destinationDirectory = compileJava.destinationDirectory
```
it doesn't work because val cannot be reassigned. but it has to be a val??? Let me know if there is something I can add to help me resolve this issue.

**Comment by MinnDevelopment** [comment]
> it doesn't work because val cannot be reassigned. but it has to be a val??? 

You need to do `compileKotlin.destinationDirectory.set(compileJava.destinationDirectory.get())`

**Comment by tkruse** [comment]
@[durganmcbroom](https://github.com/durganmcbroom) Why did you close this issue? This seems very much a bug in gradle, having to use some 3rdparty plugin can be a mitigation, but not a solution.

**Comment by ianbrandt** [comment]
@durganmcbroom,

I would like to see this issue reopened for the reasons @tkruse mentioned. It would be nice to not have to:

* Put the module-info.java file in 'src/main/java', not 'src/main/kotlin', even though other .java and .kt files can otherwise be placed in either source root.
* Add something, e.g. a package-info.java file, to an otherwise empty 'src/main/java/my/package' for a 'src/main/kotlin/my/package/Main.kt' to be recognized as a member of a module.
* Configure the Kotlin compiler `destinationDirectory` to be the same as the Java compiler `destinationDirectory`.

At the very least it would be good to get these requirements documented, either in the Gradle or [Kotlin docs](https://kotlinlang.org/docs/gradle.html), but preferably these things wouldn't have to be done by the user at all.

**Comment by durganmcbroom** [comment]
@ianbrandt 

This issue was purely about Gradle being completely inoperable with the JPMS. If you wanted to make another issue about specific problems with Kotlin + Modular java I would 100% support that.

Ive still seen bugs with certain dependencies not being added to the module path when compiling (think I mentioned it above? Mostly happened with kotlinx stuff)  though. Haven't gotten around to reproducing it but if someone else does or I find time I would be very willing to reopen this issue for that.

**Comment by ianbrandt** [comment]
Filed #22657 and #22658 with reproducers for addressing the destination directory and module-info.java location requirements for Kotlin modules respectively.

I didn't yet manage to get a separate reproducer for my "Add something, e.g. a package-info.java file, to an otherwise empty 'src/main/java/my/package' for a 'src/main/kotlin/my/package/Main.kt' to be recognized as a member of a module" bullet above. I remember hitting that issue, but I can't recall the specific circumstance. Perhaps it comes up when depending on a module built without it from another module. My initial reproducer is a single module project, so I'll need to expand it to try that case.
