### ISSUE TITLE
Make build scan simply available

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#17281]
### Expected Behavior
Make the build scan available at the URL shown at the end of the build. The user already has to agree to the legalities, so there's no reason to introduce two levels of indirection other than collecting their personal information that you don't need. 

### Current Behavior
Running build scan prints a URL to go to, where the user needs to provide their email, and make sure to uncheck "Subscribe to the Gradle newsletter". This really looks like spam or phishing; why do you need their email address, and why are you opting in to receiving the newsletter by default.

### Context
Not applicable.

**Comment by etiennestuder** [comment]
In order to activate the published build scan, we ask for your email once. During that process, you can enable the 'remember me' functionality to skip this step of the process for future build scan activations, and you can also disable receiving any infos about Gradle and Gradle Enterprise. We have no plans to change this process.

scans.gradle.com is a service offered for free to the software community by Gradle. If you are interested in activation-free viewing of build scans as well as many other features that improve developer productivity llike build caching, test distributions, test analytics, etc., please have a look at [Gradle Enterprise](https://gradle.com/enterprise).

**Comment by relgames** [comment]
Hi, can you reopen this issue? "remember me" doesn't work, and I have to click an email link every time.

**Comment by CDRussell** [comment]
> "remember me" doesn't work, and I have to click an email link every time.

I found this issue because of that exactly that 👆
