### ISSUE TITLE
Archive's `archiveAppendix` and Maven Publish don't work well together

### ISSUE THREAD

**Issue by kdubb** [gradle/gradle#17291]
With the tasks below I would expect a valid publication without warnings..

We create a new `Jar` task (we use it for ShadowJar) in addition to the normal `Jar`.
```kotlin
tasks.register<ShadowJar>("uberJar") {

  archiveAppendix.set("all")     /// <<<--- we set the "appendix"

  manifest {
    from(jar.get().manifest)
  }
  from(mainSourceSet.output)
  configurations = listOf(project.configurations["runtimeClasspath"])
}
```

Then we add both in the publication. The 
```kotlin

    publications {

      register<MavenPublication>("std") {

        // configure the pom with shared pomCfg function
        pom(pomCfg)

        from(components["java"])

        artifact(tasks.named<Jar>("sourcesJar").get())
        artifact(tasks.named<Jar>("javadocJar").get())
      }

      register<MavenPublication>("uber") {

        // configure the pom with shared pomCfg function
        pom(pomCfg)

        artifact(tasks.named("uberJar").get()).   // <<<--- this task has the "appendix" set to "all"

        artifact(tasks.named<Jar>("sourcesJar").get())
        artifact(tasks.named<Jar>("javadocJar").get())
      }

    }
```

Given that the `uberJar` task has an appendix I would expect the Maven Publishing extension to generate the coordinates (specifically the `artifactId`) to include the appendix. It does not and we get warnings (that are more probably errors).

We must "correct the `artifactId` manually to get rid of the issues.
```kotlin

    publications {

      register<MavenPublication>("std") {

        // configure the pom with shared pomCfg function
        pom(pomCfg)

        from(components["java"])

        artifact(tasks.named<Jar>("sourcesJar").get())
        artifact(tasks.named<Jar>("javadocJar").get())
      }

      register<MavenPublication>("uber") {

        val task = tasks.named("uberJar").get()

        // CORRECT THE ARTIFACT ID
        artifactId = "${task.archiveBaseName.get()}-${task.archiveAppendix.get()}"

        // configure the pom with shared pomCfg function
        pom(pomCfg)

        artifact(task)

        artifact(tasks.named<Jar>("sourcesJar").get())
        artifact(tasks.named<Jar>("javadocJar").get())
      }

    }
```

_Originally posted by @kdubb in https://github.com/gradle/gradle/issues/7567#issuecomment-848161148_

**Comment by melix** [comment]
The concept of "appendix" isn't supported by Maven repositories. The fact you can set an appendix on an archive is for Ivy/file repositories, but as soon as you publish on Maven repositories, you have to understand that this isn't supported (not by us, but by the repository layout itself). Changing the artifact id isn't a solution to this, because you _don't_ want to change the artifact id: an appendix is a modifier.

**Comment by kdubb** [comment]
We are creating multiple separate publications, each with their own coordinates. I can assure this is supported and we do want to do this.

Publishing an uber jar along with the standard jar requires that the Maven coordinates be _different_ to allow it to have its own dependency reduced `pom.xml`.  Using `classifier` does not work for this because it adds jar(s) to the same `pom.xml` publication; we need to publish with new coordinates.

According to `AbstractArchiveTask`, using an `appendix` generates a full name like `<base-name>(-<appendix>)?-<version>(-<classifier>)`.  So, using `appendix` _should_ generate a name that maps to new Maven coordinates. The problem is that Maven Publish doesn't set the `artifactid` to what `AbstractArchiveTask` suggests it should be (`<base-name>(-<appendix)?`.

So, `appendix` seems to be the right tool. If Maven Publish used it to create the complete `artifactId` all would be working harmoniously.

Btw, the example's above are working for our publish to Maven Central (with the manually corrected `artifactId`). it publishes the normal `example-1.0.0.jar` as well as a `example-all-1.0.0.jar` with a dependency stripped `pom.xml`.

**Comment by melix** [comment]
What I'm saying is that you _can_ use appendix to encode whatever you want about artifacts, but you shouldn't _assume_ that Gradle will do this by default because appendix has different semantics. It's your choice to say that you want to use the appendix to generate different artifact ids. There's no reason for Gradle to do it out of the box, because that's not the semantics of appendix. Appendix has defined semantics for Ivy publications and that's pretty much it. Appendix is a modifier of an _artifact_, not a _module_. If we changed that, it would mean that depending on what repository you publish to, you'd get either different _modules_ (things published at different GAV coordinates) or different _artifacts_ (things which are effectively the same module, but a different variant of this module), which is totally inconsistent.

If what you want to represent is different _things_, then using an appendix is not the right choice: you should aim at using different publications, using custom components (see https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components).

**Comment by ljacomet** [comment]
Closing since there will be no change in Gradle to map different appendix to different publications.
