### ISSUE TITLE
Unable to use `Provider<FileTree>` as source directory input to `CompileGroovy` task

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#17435]
```
> Task :jenkinsfile:jenkinsfile-shared:compileGroovy FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jenkinsfile:jenkinsfile-shared:compileGroovy'.
> Failed to query the value of task ':jenkinsfile:jenkinsfile-shared:syncSharedGroovyWithoutPipeline' property 'input'.
   > Querying the mapped value of provider(interface java.util.Set) before task ':jenkinsfile:jenkinsfile-shared:syncSharedGroovyWithPipeline' has completed is not supported
```

```kts
// note - this is output of a `Sync` task
val modifiedByTaskSharedGroovyCode: Provider<FileTree> = TODO()

val sharedGroovySource: SourceDirectorySet = objects.sourceDirectorySet("SharedGroovyCode", "Shared Groovy Code")

sharedGroovySource.srcDir(modifiedByTaskSharedGroovyCode)

sourceSets {
    main {
        withConvention(GroovySourceSet::class) {
            groovy {
                srcDir(sharedGroovySource)
            }
        }
    }
}
```

**Comment by ZakTaccardi** [comment]
To workaround this, I had to do the following:

```kotlin
val fileCollectionSource = objects.fileCollection()

// Provider API is preferred over this because here we need to manually set task dependencies
fileCollectionSource
    .from(layout.sharedGroovyModifiedSourceDir)
    .builtBy(modifySharedGroovyTask)

sharedGroovySource.srcDir(fileCollectionSource)
```

It seems like I should be able to use the `Provider<T>` API here though?

**Comment by ljacomet** [comment]
What the error says is that the failing tasks attempts to read something which is the output of another task which is not finished.
So you might be missing a task dependency there. I am not sure I link your snippet to the issue tbh.

You should also look at [the documentation for working with files in a lazy way](https://docs.gradle.org/current/userguide/lazy_configuration.html#working_with_files_in_lazy_properties) because `FileTree` is lazy already, it makes little sense to have a `Provider<FileTree>`.

**Comment by wolfs** [comment]
I can second @ljacomet's comment here: `Provider<FileTree>` seems to be wrong, since `FileTree` is already lazy. What is stopping you from using `FileTree` directly?

**Comment by ljacomet** [comment]
Closing as there is nothing to change on the Gradle side given the information provided.
