### ISSUE TITLE
Move ConfigureUtil to public API again

### ISSUE THREAD

**Issue by dreis2211** [gradle/gradle#17446]
Hi,

Gradle 7.1 has moved some things from org.gradle.util to org.gradle.util.internal and/or deprecated stuff. One of those things was `ConfigureUtil`. This utility class is in my opinion used in many projects. Just to name a few I'm aware of from the top of my head:

- [Spring-Boot](https://github.com/spring-projects/spring-boot/blob/main/buildSrc/src/main/java/org/springframework/boot/build/bom/BomExtension.java#L96)
- [Hibernate](https://github.com/hibernate/hibernate-orm/blob/main/tooling/hibernate-gradle-plugin/src/main/groovy/org/hibernate/orm/tooling/gradle/EnhanceTask.groovy#L35)

Is there maybe a replacement API for it that could be used?

On that note: https://docs.gradle.org/7.1/userguide/upgrading_version_7.html#changes_7.1 doesn't seem to mention this specific one at all.

Cheers,
Christoph

**Comment by oehme** [comment]
It's right there: https://github.com/gradle/gradle/blob/master/subprojects/model-core/src/main/java/org/gradle/util/ConfigureUtil.java. It was not moved, only deprecated.

**Comment by dreis2211** [comment]
The feature request stays the same, though @oehme . Or in case of a replacement, mentioning it in the release notes.

**Comment by oehme** [comment]
The replacement is also given directly in the JavaDoc: https://github.com/gradle/gradle/blob/master/subprojects/model-core/src/main/java/org/gradle/util/ConfigureUtil.java#L37

**Comment by dreis2211** [comment]
Yeah, I noticed already. The mentioned JavaDoc only says something about the easiest replacement, though.

E.g. how to move away from the following?
- ConfigureUtil.configureByMap
- ConfigureUtil.configureUsing (likely replaceable with `Project.configure` as well, but less convenient and needs the project available, which is not always the case)

**Comment by oehme** [comment]
Plugins shouldn't make users use Maps for configuration. They should use strongly typed domain objects instead. The only usage I found of configureByMap in the Gradle codebase is the WTP plugin, which isn't really maintained. So I'd say the replacement for configureByMap is "don't do that, your users will hate you".

**Comment by dreis2211** [comment]
Usages of those things could be might as well happen in `buildSrc` - so it's not just code exposed to the user.

**Comment by big-guy** [comment]
@dreis2211 Except for the configureByMap methods, all of the other methods can be replicated with public APIs. 

For example, in the Spring Boot example, instead of doing:
```
    public void upgrade(Closure<?> closure) {
        ConfigureUtil.configure(closure, this.upgradeHandler);
    }
```
This should be equivalent:
```
    public void upgrade(Action<UpgradeHandler> action) {
        action.execute(this.upgradeHandler);
    }
```

For Hibernate, instead of:
```
    void options(Closure closure) {
        options = new EnhanceExtension()
        ConfigureUtil.configure( closure, options )
    }
```
This should be the equivalent:
```
    void options(Action<EnhanceExtension> action) {
        // assuming options is initialized elsewhere
        action.execute(options)
    }
```

This is better for users because `Action` is a language agnostic, public API. Closure taking methods are Groovy specific and difficult to call in Java and Kotlin. 

@donat Maybe we can guide people towards the right answer here by explicitly telling people to not use `Closure` directly and to prefer `Action` instead.

**Comment by wilkinsona** [comment]
In my experience when implementing a DSL, replacing `Closure` with `Action` isn't always enough. You also have to make sure that the instance of any class with an `Action` method on it was created by Gradle so that you get the "correct" delegation behaviour when calling the method with a `Closure`. I think it'd be useful to mention that when pointing people away from the use of `ConfigureUtil`.
