### ISSUE TITLE
Task "test" is triggered by any other task

### ISSUE THREAD

**Issue by quaff** [gradle/gradle#17469]
### Expected Behavior

task "test" should run on demand

### Current Behavior

task "test" is triggered by any task, even add `-x test`

### Steps to Reproduce 
1. `git clone --depth 1 https://github.com/spring-projects/spring-boot.git && cd spring-boot`
2. `gradle tasks` `gradle tasks -x test` `gradle clean` will tirgger `> Task :buildSrc:test`, but `./gradlew`(6.9) works as expected.

### Your Environment
```
------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_271 (Oracle Corporation 25.271-b09)
OS:           Mac OS X 10.16 x86_64
```

**Comment by big-guy** [comment]
When you have a `buildSrc` directory, Gradle always runs the "build" task from buildSrc before evaluating any build scripts in the root build. There hasn't been any change in that area between 6.x and 7.x.

Here's running `gradle tasks` in 6.9, which runs 104 tests:
https://scans.gradle.com/s/rcbrgocjkamf6/tests

Here's running `gradle tasks` in 7.1, which also runs 104 tests. I assume the failures are related to the upgrade:
https://scans.gradle.com/s/5eyixjgna4kd2/tests

I suspect you don't normally see tests running in 6.9 because they're up-to-date or from the build cache.
