### ISSUE TITLE
Allow setting a custom timeout for gradle wrapper download

### ISSUE THREAD

**Issue by goughy000** [gradle/gradle#17575]
### Expected Behavior
It should be possible to set custom timeouts for the download of the wrapper jar

### Current Behavior
The connect and read timeouts are [hardcoded to 10s](https://github.com/gradle/gradle/blob/f54ff0afbd0b40a6d0cc4cc25d44e909fc1df0dc/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L98..L99)

### Context
This causes us a problem sometimes, in our organisation we don't have direct access to maven central and so set a custom download URL in gradle-wrapper.properties to download from an internal artifact cache that proxies out to central.  When the artifact cache is busy (it has thousands of users, and runs anti virus scans etc) the read can timeout.

I'm happy to contribute a PR for this, however I'd like some advice on the preferred approach?

- Create new properties in gradle-wrapper.properties for the connection and read timeouts
- Read system properties for connection and read timeouts (like [other things](https://github.com/gradle/gradle/blob/f54ff0afbd0b40a6d0cc4cc25d44e909fc1df0dc/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L188) do currently)

Any preference on naming for these properties?
Would it be acceptable to get this in both gradle v6 and v7 (again, happy to contribute)

Thanks!

**Comment by ljacomet** [comment]
Thanks for raising the issue and the contribution proposal.
Given this focuses on the wrapper download, I would recommend going with properties to be defined in `gradle-wrapper.properties`. I wonder if it makes sense to have a different properties there or if a single would be enough.
As for the name, since the properties are scope limited, a simple name sounds like the best approach. Something like `connectionTimeout` and `readTimeout` if going with two or `networkTimeout` if going for a single one.

**Comment by goughy000** [comment]
Thanks kindly for your feedback @ljacomet, I went for the option of having a single `networkTimeout` and have raised PR #17830 for this change :)

**Comment by markproxy** [comment]
It looks like the linked PR was closed and its associated branch was deleted. Is there still a plan to add timeout configuration to distribution download?
