### ISSUE TITLE
Annotated `package-info.java` breaks incremental compilation for 6.8+

### ISSUE THREAD

**Issue by torbsto** [gradle/gradle#17572]
### Expected Behavior
Compilations tasks shouldn't throw an exception when recompiling.

### Current Behavior
The build fails  ([full stacktrace](https://github.com/torbsto/micronaut-issue/blob/main/incremental-gradle-compilation/stacktrace.txt)):
```
Execution failed for task ':compileJava'.
> Not a valid class name: com.example.test.package-info
```

### Context

Micronaut's [`@Configuration`](https://docs.micronaut.io/2.3.3/api/io/micronaut/context/annotation/Configuration.html) allows loading a package only if the specified requirement is met.

### Steps to Reproduce 
[https://github.com/torbsto/micronaut-issue](https://github.com/torbsto/micronaut-issue) (the application is in the directory `incremental-gradle-compilation`)

1. Go into the project's subdirectory: `cd ./micronaut-issue/incremental-gradle-compilation`.
1. Run `./gradlew compileJava`: The build should be successful.
1. Change something in the `com.example.test` package, e.g., `sed -i '/1/s//2/' src/main/java/com/example/test/TestSingleton.java`.
1. Run `./gradlew compileJava` again. This throws an exception ([full stacktrace](https://github.com/torbsto/micronaut-issue/blob/main/incremental-gradle-compilation/stacktrace.txt)).
1. Running `./gradlew compileJava` once more doesn't throw an exception.

### Your Environment
```
------------------------------------------------------------
Gradle 7.0
------------------------------------------------------------

Build time:   2021-04-09 22:27:31 UTC
Revision:     d5661e3f0e07a8caff705f1badf79fb5df8022c4

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.11 (Ubuntu 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OS:           Linux 5.4.72-microsoft-standard-WSL2 amd64
```

### Description

Original Micronaut issue: https://github.com/micronaut-projects/micronaut-core/issues/5679

It seems incremental compilation doesn't work with Micronaut's `@Configuration` (like used [here](https://github.com/torbsto/micronaut-issue/blob/6dd53fd2b1693efb10ddaadcd90c34672fda6fcd/incremental-gradle-compilation/src/main/java/com/example/test/package-info.java#L1)). Whenever I change source code located in the annotated package (`com.example.test`), the  compilation task throws an exception ([full stacktrace](https://github.com/torbsto/micronaut-issue/blob/main/incremental-gradle-compilation/stacktrace.txt)). Simply running the task again fixes it, but it's still somewhat annoying. I don't get an error with `micronaut.processing.incremental` set to `false` (i.e., the compiler argument `-Amicronaut.processing.incremental=true` is NOT set).
As far as I can tell, the problem was introduced with version 6.8, as everything works fine with 6.7.

**Comment by wolfs** [comment]
@torbsto Can you try a 7.1.1 nightly (e.g.  `7.1.1-20210628233848+0000`)? There have been quite some changes in incremental compilation.

**Comment by wolfs** [comment]
I think I understand the problem. `@Configuration` is an aggregating annotation processor. That means everytime something changes, we need to re-run the aggregating processor again. We currently decide which classes to process to run the aggregating processor by [getting the origin of the generated classes](https://github.com/gradle/gradle/blob/6957c9fc5daf6d05af96bbf9d6747c4b7cdf0b18/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L189-L198).

For the classes generated by the the `@Configuration` annotation on the `package-info` class, the origin class is `package-info`. So we would try to [get a compile task](https://github.com/gradle/gradle/blob/762c7d1e4f88f89fae0ac27119de381fcbf9ecf3/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/JdkJavaCompiler.java#L70) for `package-info` as classes to process.

And it seems like that doesn't work, since the package info class is not a valid class name.

So I suppose we need to recompile the package info class instead of trying to pass it as classes to the Java compile task.

@oehme @melix Does this make sense? Or do you see another way to fix this?

**Comment by oehme** [comment]
We should filter anything named `x.x.x.package-info` out of [typesToReprocess](https://github.com/gradle/gradle/blob/38f109f2a607e2b0a7eb982be0c610e48fd5101b/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L189). An annotation processor never processes the package directly, but only inspects it by calling `getPackage` on processed classes.

**Comment by wolfs** [comment]
@oehme Are you sure? It seems that the [https://github.com/micronaut-projects/micronaut-core/blob/b581ba6b2a16da720b91ff4e60541f964aafd082/inject-java/src/main/java/io/micronaut/annotation/processing/PackageConfigurationInjectProcessor.java](PackageConfigurationInjectProcessor) from Micronaut visits `package-info` classes annotated with `@Configuration`. At least that is my understanding.

**Comment by oehme** [comment]
You're right, I was mistaken. Too bad javac doesn't treat it like a normal class when it works like one for all other purposes. In that case I guess we should still filter it out [here](https://github.com/gradle/gradle/blob/38f109f2a607e2b0a7eb982be0c610e48fd5101b/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L189), but instead include it [here](https://github.com/gradle/gradle/blob/38f109f2a607e2b0a7eb982be0c610e48fd5101b/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/deps/ClassSetAnalysis.java#L181), i.e. treat it like a class that always needs to be recompiled.
