### ISSUE TITLE
File system watching breaks with TestKit + included build

### ISSUE THREAD

**Issue by melix** [gradle/gradle#17621]
### Expected Behavior

I have a project in which I'm using composite builds for integration, in order to avoid deploying snapshots to a repository. This is a Gradle plugin, which therefore depends on a library X, which is included. However, when I'm testing the plugin, I _also_ need a dependency to X and inject it as a composite.

When I run the functional tests, I'm seeing this error:

```
Unable to watch the file system for changes
java.lang.IllegalStateException: Found existing snapshot at '/tmp/composite-build-fsw-bug/included/lib/build/libs/lib.jar' for unwatched hierarchy '/tmp/composite-build-fsw-bug/included'
```

It should be possible to use a composite both in the build _and_ in Gradle builds executed as part of tests simultaneously.

### Current Behavior

Gradle fails, workaround is to disable file system watching.

### Context

I'm facing this issue while developing the Micronaut Gradle plugin which relies on an _unmerged_ PR on the GraalVM plugin.

### Steps to Reproduce 

Use the [attached project](https://github.com/gradle/gradle/files/6768716/composite-build-fsw-bug.tar.gz) and run `./gradlew funTest`

### Your Environment

Build scan URL: https://scans.gradle.com/s/l57ntm3l4daow

**Comment by ljacomet** [comment]
@gradle/execution Can you take a look?

**Comment by wolfs** [comment]
@melix Thank you for reporting. I was able to reproduce the issue in a smaller test case. I understand what is going on: The build script adds a file dependency to a library in another build, and later that build is included as well. I think we can't make this work with the strict validation we have right now when starting to watch things, so I think we need to be more lenient there. See https://github.com/gradle/gradle/pull/17726 for a fix.

**Comment by wolfs** [comment]
@melix Coming back to this. So what is your use-case? In your functional test, you want your plugin to use the dependency from the included build. This already works without including the build again in the functional test, since testkit injects a classpath which contains the JAR of the included build in the plugin classpath.

Why you include the build in the functional test, since this is not necessary for the plugin. If you want to include the same artifact for some other things in the functional build, I think you should include a new checkout.

**Comment by wolfs** [comment]
@melix Please re-open if this is an important use case to you.
