### ISSUE TITLE
Adding a task dependency removes a finalizer dependency

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#17633]
If a task A is finalized by a task F, and F has an explicit dependency on A, the finalizer dependency is dropped. This is admittedly an unusual setup, but the behavior strikes me as incorrect, so I thought it wouldn't hurt to report :)

This repros in 7.1.1 and the latest nightly as of today (7.2-20210704221017+0000), and I put up a small repro here: https://github.com/cesar1000/dropped-finalizer.

**Comment by wolfs** [comment]
Thank you for reporting. The problem here is the following: A task can only execute if all its dependencies finished _successfully_. In your example, the dependency of the finalizer (which is the task to be finalized) fails. So Gradle cannot run the finalizer. If the task succeeds, then the finalizer runs as expected.

I'll close this issue now, since this works as expected.

**Comment by cesar1000** [comment]
Thanks, Wolf! That makes sense. Since this is essentially an invalid configuration, I'd expect Gradle to report it – but, then again, it's admittedly a rare setup so it probably doesn't matter than much anyway :)

**Comment by wolfs** [comment]
> Since this is essentially an invalid configuration, I'd expect Gradle to report it

That could be an option. The configuration still has an effect: The finalizer runs if the task finishes successful.

**Comment by cesar1000** [comment]
The inconsistently only makes it more confusing though!
