### ISSUE TITLE
gradle7.x is not compatible with org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:4.0.0-RC1 

### ISSUE THREAD

**Issue by J-TIGGER** [gradle/gradle#17744]
### Title
gradle7.x is not compatible with org.apache.shardingsphere:sharding-jdbc-spring-boot-starter:4.0.0-RC1 

### Context
gradle 6.x can compile normally ：
![image](https://user-images.githubusercontent.com/52161906/125923597-42349f09-b50f-4390-b2d6-2dde54d093a1.png)

but gradle 7.x cannot compile normally :
![image](https://user-images.githubusercontent.com/52161906/125924009-bb310863-19fd-444a-9b15-37e75c012280.png)

### Your Environment
gradle 7.x

**Comment by mlopatkin** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it. It would be great to also see the version of the IDEA you're using.

The issue might be caused by IDEA indexing the project and it will go away after some time. Reloading the project (in "Gradle" view) might also help

This issue will be closed after 7 days, unless you can provide more information.

**Comment by J-TIGGER** [comment]
@mlopatkin 
Thank you for taking the time to help me solve this problem, I am now ready to upgrade the gradle in the project to 7.x, please help me to solve this problem.

My IDEA version is IntelliJ IDEA 2021.1.1 (Ultimate Edition), and I have reproduced this problem in other IDEA versions. 

The following pictures are the error messages suggested by IDEA :
![image](https://user-images.githubusercontent.com/52161906/126137670-b064179a-3eed-4f5f-bb0c-5fce51338c6f.png)
![image](https://user-images.githubusercontent.com/52161906/126138122-c8a8ed74-05f0-4903-afaa-d5643456d686.png)

**Comment by mlopatkin** [comment]
This type of issues doesn't typically affect your ability to build things though it may be annoying to no have autocomplete and other goodies when editing Gradle files. You may consider switching to [Kotlin DSL](https://docs.gradle.org/current/userguide/kotlin_dsl.html) as a workaround but there are certain trade-offs. Kotlin, being a statically typed language, typically makes it easier for the IDE to provide robust autocompletion.

In my sample project I managed to reproduce similar issue (though with IDEA 2021.1.3) but the errors went away after reloading the project: 
![image](https://user-images.githubusercontent.com/7620037/126173491-cc4b3e4e-860b-49dd-ab05-d9cba96de330.png)

Overall this issue is more about IDEA than Gradle and it is unlikely that we can do much in the Gradle Core. The Jetbrains team is tracking a similar issue in https://youtrack.jetbrains.com/issue/IDEA-270846, please add your vote there.
