### ISSUE TITLE
`CppApplicationInitIntegrationTest` and `CppLibraryInitIntegrationTest` are not executable without installed toolchain

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#17759]
The mentioned tests fail with `No tool chain is available to build C++ for host operating system 'Windows 10' architecture 'x86-64'` message.
Maybe they should be conditionally skipped if no toolchain is available on the system running the tests.

**Comment by ov7a** [comment]
Thank you for providing a valid description.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

---

The default should be to ignore the error. For CI there should be a setting to fail on the missing toolchain.
