### ISSUE TITLE
Jacoco plugin relies on Jar filename for version information

### ISSUE THREAD

**Issue by toryhaavik** [gradle/gradle#1783]
The Jacoco plugin relies on a Jar file that has the version in the name.  If a user has the Jacoco Agent jar named as `jacocoagent.jar` (or any other arbitrary name), an exception is thrown.

### Expected Behavior
This should work:
```
dependencies {
    jacocoAgent files("path/to/jacoco.zip")
}
```
where jacoco.zip contains a Jacoco Agent jar named anything other than the [expected format](https://github.com/gradle/gradle/blob/c92fc0f5c9007605d20eaaea7cff81b5dd2ba56a/subprojects/jacoco/src/main/java/org/gradle/internal/jacoco/JacocoAgentJar.java#L97)
### Current Behavior
The plugin throws an exception (taken from [a previous report](https://discuss.gradle.org/t/jacoco-plugin-relies-on-jar-file-name-for-version-information/18289)):
`Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -6`

### Context
We build our classpath in-house, and so our collection of Jars (and their names) are not the default.  

### Proposal
Use the Jar's manifest to obtain the version rather than expect

**Comment by bmuskalla** [comment]
@toryhaavik Thanks for writing up this request. At this point, we don't have the capacity to look further into this as there is a reasonable workaround. If you still feel this should be fixed in Gradle itself, please feel free to reopen this issue with a PR. Let me know if you need any help with that.
