### ISSUE TITLE
Make MinimalExternalModuleDependency#toString work

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#17882]
Consider:
```
fun getDependencyAsString(dependencyProvider: Provider<MinimalExternalModuleDependency>): String {
    val dependency = dependencyProvider.get()
    return dependency.module.toString() + ":" + dependency.versionConstraint.toString()
}

fun Project.createConfiguration(): FileCollection { 
    val configuration = configurations.findByName("metalava") ?: configurations.create("metalava") {
        val libs = project.extensions.getByType(
            VersionCatalogsExtension::class.java
        ).find("libs").get()
        val dependency = dependencies.create(
            getDependencyAsString(libs.findDependency("metalava").get())
        )
        it.dependencies.add(dependency)
    }
    return project.files(configuration)
```
and `gradle/libs.versions.toml`
```
[libraries]
metalava = { module = "com.android.tools.metalava:metalava", version = "1.0.0-alpha04" }
```

### Expected Behavior
`MinimalExternalModuleDependency.toString()` returns `com.android.tools.metalava:metalava:1.0.0-alpha04`

### Current Behavior
`MinimalExternalModuleDependency.toString()` returns `org.gradle.api.internal.artifacts.dependencies.DefaultMinimalDependency@5e055771`, so we have to write our own getDependencyAsString function.

### Context
It is very common to need string representation of a dependency and thus it should work out of the box or at least have getAsString() type method.

**Comment by asodja** [comment]
Fix for this will be in 7.3. Note that for complex versions output won't be that nice, since they cannot be nicely written with gav coordinates, outputs can be seen here:
https://github.com/gradle/gradle/blob/65a1a59aa531a939758c05f550d18831d007e1fe/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/catalog/VersionCatalogExtensionIntegrationTest.groovy#L1743-L1748
