### ISSUE TITLE
`clean` task does not remove `buildSrc/build`

### ISSUE THREAD

**Issue by carlosame** [gradle/gradle#17919]
### Expected Behavior
When I execute `gradle clean`, the `$projectDir/build` directory is removed and I'd expect that `buildSrc/build` was removed as well.

### Current Behavior
`buildSrc/build` is not removed.

### Context
When releasing software, I typically execute a few release tasks then `./gradlew clean` and `rm -fr .gradle */.gradle`, previous to packaging the directory. But I have to `rm -fr buildSrc/build` as well (why do I have to do that, and not `rm -fr build`?).

I have seen a few similar complaints about that elsewhere, like:

- https://discuss.gradle.org/t/buildsrc-build-is-not-cleared-after-build/1572/2
- https://bugs.openjdk.java.net/browse/JDK-8098260
- https://bz.apache.org/bugzilla/show_bug.cgi?id=63914

but could not find an issue at this tracker, so I decided to open one.

### Steps to Reproduce 
On any Gradle project with a `buildSrc` tree, build the project then execute `gradle clean` or `./gradlew clean`.

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

This is quite hard to implement because the main build needs `buildSrc/build` contents during configuration/execution and the `clean` task isn't special in this regard. So removing it may cause unexpected errors because of missing classes albeit in some corner cases. Another aspect is that in a significant amount of `clean` usages keeping `buildSrc/build` is fine and desirable to avoid rebuilding buildSrc during the next build invocation.

The custom implementation of your request is not particularly complicated (add `cleanBuildSrc` task and then add it as a dependency/finalizer to the `clean` task):
```
tasks.register("cleanBuildSrc") {
    doLast {
        delete("buildSrc/build")
    }
}

tasks.named("clean") {  // or tasks.register("clean") if this is a root project without plugins applied
    finalizedBy("cleanBuildSrc")
}
```

Given all the above this request is unlikely to be implemented in the core Gradle.
