### ISSUE TITLE
Clarify in the docs what filesystem types are supported

### ISSUE THREAD

**Issue by manueljordan** [gradle/gradle#17932]
### Expected Behavior

Indicate through the official documentation that a possible cause of locking is for the special scenario when a secondary hard disk exists that is used how repository for Gradle **but** it has a different _format type_ than the main hard disk.

### Current Behavior

It does not exist

### Context

The solution is here:

* https://github.com/gradle/gradle/issues/4329#issuecomment-891924000

Without that the Daemon hangs because exists a locking approach.

**Comment by mlopatkin** [comment]
@manueljordan, I'm not sure that the problem is about the "format" of the secondary being different but more about it being unsupported. For example, if you have NTFS primary drive and exFAT secondary then you'll have problems with secondary (as indicated in the linked issue). The problems will go away when you reformat secondary as NTFS but this only means that NTFS works while exFAT does not.

Could you please provide more details about what filesystems (or combinations) worked for you and what didn't?

**Comment by manueljordan** [comment]
Thanks for the explanation, I see, but then consider to indicate (if it does not exist) in the official documentation what are the type formats that supports Gradle. - in my case FAT32 was not supported. Was mandatory to format in NTFS and "OS X Extended (Journaled)" each drive

**Comment by eskatos** [comment]
This is now documented at
https://docs.gradle.org/current/userguide/file_system_watching.html#supported_file_systems

**Comment by manueljordan** [comment]
Thank you!
