### ISSUE TITLE
Allow project-wide opt-in for insecure URLs

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#18006]
Gradle 7 blocks insecure URIs, so the following no longer works:
```
maven { url "http://mycompany.com/mvn" }
apply from: "http://mycompany.com/buildscript.gradle"
```

The workaround is to opt-in for each and every URL.
```
maven {
    url "http://mycompany.com/mvn"
    allowInsecureProtocol = true
}
apply from: resources.text.fromInsecureUri("http://mycompany.com/buildscript.gradle")
```
But this is not practical for anything more than a handful of projects.

### Expected Behavior
Provide `org.gradle.allow-insecure-protocol=true` to be set in the gradle.properties or elsewhere for a project wide opt-in.

### Current Behavior
Opt-in required for each and every unsecure URL.

### Context
Build fails.

**Comment by asarkar** [comment]
@tresat That doesn’t solve the problem with applying the scripts. Please reopen.
I’m not seeing reopen button, perhaps it’s reserved for maintainers only. In the future, if you’re waiting for feedback, please actually wait for feedback before closing.

**Comment by tresat** [comment]
@asarkar I'm sorry, I see I failed to address the application of script plugins from insecure URLs in my original reply.  I've discussed this matter with my colleagues, and unfortunately we are not going to be able to make the change you suggested.

It is intentional that you must individually opt-in to **each** usage of an insecure URL.  We do not want to enable the scenario where a global flag is set in a project and forgotten, then a later update adds an insecure URL by mistake, and the project continues to build without alerting the user to the potential risk.

Per the docs on [`fromInsecureUrl`](https://docs.gradle.org/current/dsl/org.gradle.api.resources.TextResourceFactory.html#org.gradle.api.resources.TextResourceFactory:fromInsecureUri(java.lang.Object)) we want to encourage minimal usage of method, and only by people aware of the downside.

The central repository declaration I mentioned previously will allow you a single location to define and allow each insecure Maven repo.  For applying script plugins you would need to add an `apply from: <LOCATION>` line in each location using the plugin regardless of whether or not you have to handle insecure URLs, so I don't understand why this isn't practical.  Perhaps you can provide more details?

I'll leave this issue open for awhile until you have a chance to reply.

**Comment by asarkar** [comment]
> For applying script plugins you would need to add an apply from: <LOCATION> line in each location

@tresat We have common scripts that we liberally apply in almost all projects, which, in  turn, have scripts applied in them. This heavy handed approach by Gradle means we have to go and update each one of them, instead of simply (and perhaps programmatically) adding the proposed property to `gradle.properties`. The same applies for repos as well, no matter where those are defined.

What I’m having a hard time understanding is that is “forced security” that is at play here. Gradle, or any other tool for that matter, shouldn’t make the choices for the user. It should make secure options available and then get out of the way.  Imagine your bank forced 2PA on you or blocked you from accessing your own account unless you changed your password every week.

If you still believe that forcing the users is the most secure way, go ahead and close the ticket.

**Comment by asarkar** [comment]
>  Gradle, or any other tool for that matter, shouldn’t make the choices for the user

There are innumerable instances of this, but the JPMS flags are the most recent and widely known. You are not required to modularize your app; you may choose to bypass the JPMS using command-line flags. What’d have happened if the JDK designers decided that they had to force their grand idea upon everyone without an adoption path?

**Comment by tresat** [comment]
@asarkar We've reviewed your suggestions, and have decided not to implement any project-wide flags for allowing insecure URLs.

If you wish to continue applying script plugins from insecure URLs, you will have to continue opting-in on each `apply` call as you are already doing.  Sorry for any inconvenience this may cause.

**Comment by PJYGit** [comment]
This is insane! What if there is one more the so-called insecure url in one script which we have applied from. What if this becomes a chain.

apply from: 'http://temp.gradle'
where temp.gradle is like this:
    apply from: 'http://temp1.gradle'

We have no access to modify temp.gradle by ourselves.

Disgusting！

**Comment by topherbuckley** [comment]
At the very least I'm hoping the stacktrace would show which file/line this error was generated. I see no http urls in any gradle files I'm touching, so just doing blanket searches through the entire project adding this flag...I agree something seems wrong about this approach.

**Comment by Saad-Bashar** [comment]
I am not even finding the http URL anywhere :/ How do I even solve this?

**Comment by tresat** [comment]
As this issue came up again recently in internal discussion, we'd like to clarify that while we cannot permit project-wide insecure URLs via a flag, we're all for making it easier to determine the source of an insecure URL in a project, to aid with updating it (or, if need be, permitting access via a flag).

Any community PRs suggesting ways of improving this would certainly help influence future work in this area.

**Comment by asarkar** [comment]
> we cannot permit project-wide insecure URLs

You can, if you reconsider your stance from being a decision maker to an enabler. Are you familiar with how a browser handles insecure URLs? It presents the user a choice.

**Comment by chaoky** [comment]
in conjunction with settings like `org.gradle.internal.plugins.portal.url.override` this would make integrating with `nix` a lot easier, it's already very hard to build a gradle project without internet access when subproject repos can't be configured, mandatory https is one more nail on the coffin

**Comment by dpozinen** [comment]
this is also quite unfortunate for migration tools like https://github.com/openrewrite . A recipe could have been made to replace all those urls with secure ones, but alas it can not even be run
