### ISSUE TITLE
Document change in behaviour of VersionCatalog.findDependency for 7.2 in release notes

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#18050]
In `libs.versions.toml`: 
```
[versions]
kotlin = "1.5.21"

[libraries]
kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "kotlin" }
```

In 7.1.1, this works in `buildSrc/src/main/kotlin/plugin.gradle.kts` 
```
val libs = extensions.getByType(VersionCatalogsExtension::class.java).named("libs")
dependencies {
    implementation(libs.findDependency("kotlin-stdlib-jdk8"))
}  
```
In 7.2, the above ☝️ now gives: 

```
   > Cannot convert the provided notation to an object of type Dependency: Optional.empty.
     The following types/formats are supported:
       - Instances of Dependency.
       .
       .
       .       
``` 

In 7.2, you have to do this instead in `buildSrc/src/main/kotlin/plugin.gradle.kts`, 
```
val libs = extensions.getByType(VersionCatalogsExtension::class.java).named("libs")
dependencies {
    implementation(libs.findDependency("kotlin.stdlib.jdk8"))
}  
```

Notice you have to swap `.` for `-` 

**Expected:**

Add this to the release notes for 7.2

**Comment by ljacomet** [comment]
This was indeed a consequence of the changes for the sub item about sub accessors in [version catalog improvements](https://docs.gradle.org/current/release-notes.html#version-catalog-improvements) which is only made explicit in the note in [this documentation section](https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog-declaration).

Is the mention in these notes clear enough though?

**Comment by mgingios** [comment]
So, I can validate that part of the issue is due to ticket #18078.  When I used the values in the posting, which did not include a settings file, I had no issues building and running the test application.  However, IntelliJ Build #IU-212.4746.92 is unhappy with the version information format.  The crucial item for users to understand is that in the toml file we must use dashes and underscores as separators, but not dots.  Outside of the toml file, we must use dots as separators.  I've attached a zipped file with images that capture my testing and may be useful in the docs or here for others to see. 

Unfortunately, my further testing seems to show an issue when using aliases in a settings file.  I used the working version of my test application, which I've slimmed up from my initial posting and have attached herein.  All that I've done is configured the plugins block to use the version catalog for the Kotlin JVM plugin.  Within the build.gradle.kts file, I've applied the plugin.  When I try to build, the VersionCatalogsExtension is not found, despite using the correct alias format.

Attachments:
 versions2.zip: The code that builds with the aforementioned error.
 successful_build_images.zip: Images showing valid combinations of toml and build file configurations.
 
[versions2.zip](https://github.com/gradle/gradle/files/7018599/versions2.zip)
[successful-build-images.zip](https://github.com/gradle/gradle/files/7018601/successful-build-images.zip)
```
// settings.gradle.kts

plugins {
        extensions.findByType(VersionCatalogsExtension::class.java)?.let { versionCatalogsExtension ->
            versionCatalogsExtension.named("libs").apply {
                alias(findPlugin("kotlin.jvm.gradle").get())
            }
        }?: throw kotlin.NullPointerException("VersionCatalogsExtension::class.java does not exist")
    }
```
// build.gradle.kts

plugins {
    id("org.jetbrains.kotlin.jvm")
    application
}
```

[successful-build-images.zip](https://github.com/gradle/gradle/files/7018605/successful-build-images.zip)
[versions2.zip](https://github.com/gradle/gradle/files/7018606/versions2.zip)

**Comment by yogurtearl** [comment]
> Is the mention in these notes clear enough though?

@ljacomet IMO, no. :) 

The user guide and the javadoc should describe the format of the string that need to be passed into `findDependency`, `findBundle`, `findVersion`, `findPlugin`, and how it maps to what is in the version catalog.

**Comment by mgingios** [comment]
Hello Guys, Based on yogurtearl's response, it looks like I am using incorrect aliases?  If so, please tell me what to correct in the version2 sample that I've posted, and I can let you know the results.  I continued to investigate with that project and found that whenever I try find the VersionCatalogsExtension in the following code, it fails and returns a null.  If I comment out that code and don't set global plugin versions in that block of code, then everything is okay.  I tried the same tests using a version catalog in a Jar, with the same results.  Please advise if I can help validate a solution with my versions2 mini-app.

**Comment by ljacomet** [comment]
Indeed, that is a good suggestion. Let's see about improving the documentation there.
