### ISSUE TITLE
wrong implicit dependency warning in plugin build

### ISSUE THREAD

**Issue by hauner** [gradle/gradle#18200]
### Expected Behavior
no warning regarding `/build/pluginDescriptors`

### Current Behavior

Gradle prints the following warning when building my plugin:

> Gradle  detected a problem with the following location:  '/Users/hauner/Development/openapi/openapi-processor-gradle/build/pluginDescriptors'.  Reason: Task ':processResources' uses this output of task  ':generateVersion' without declaring an explicit or implicit dependency.  This can lead to incorrect results being produced, depending on what  order the tasks are executed. Please refer to  https://docs.gradle.org/7.2/userguide/validation_problems.html#implicit_dependency  for more details about this problem. 

The `generateVersion` task in the plugin creates a single java file in the `build` output directory before compiling the plugin. The task does not touch or create the `/pluginDescriptors` folder. 

I wonder why gradle thinks that it is a output of my `generateVersion` task?  

### Steps to Reproduce 
build or run check on https://github.com/openapi-processor/openapi-processor-gradle/tree/gradle-7

### Your Environment
Build scan URL: https://scans.gradle.com/s/7nacdnxnxzc7m

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

I believe a number of improvements can be made to your `VersionPlugin` that should help Gradle figure things out:
* Change the setup of the `VersionTask` so that its output directory is `<buildDir>/version`.
* Changing the above might help you add a `srcDirs` by directly using that task. This can and should be done in your version plugin.
* I think - but did not test - that you can do the above with `srcDirs <versionTask>` and it might then correctly track inputs which should allow you to remove the `compileJava` explicit `dependsOn`. And by extension fix the missing one about `processResources`.

**Comment by hauner** [comment]
Adding the `/version` directory fixed the issue. To make `srcDirs <versionTask>` work I had to move task setup out of the `afterEvaluate`. I didn't know this was possible.

Thanks a lot :-)
