### ISSUE TITLE
VFS couldn't add watch, error = 2

### ISSUE THREAD

**Issue by dsvoronin** [gradle/gradle#18294]
### Expected Behavior

File system watching just works

### Current Behavior

Form time to time getting:

```
Gradle was unable to watch the file system for changes
net.rubygrapefruit.platform.NativeException: Couldn't add watch, error = 2: /home/dsvoronin/Work/avito-android-github/subprojects/test-runner/test-inhouse-runner/build/tmp/kotlin-classes/release/META-INF
        at net.rubygrapefruit.platform.internal.jni.AbstractFileEventFunctions$NativeFileWatcher.startWatching0(Native Method)
```

Full stacktrace: https://pastebin.com/LLMVA39r

### Context

Not sure if it's affecting build correctness, and can't measure performance for sure, but looks like a bug
I am disabling VFS for now, because of the issue

### Steps to Reproduce 

https://github.com/avito-tech/avito-android
`./gradlew checkAll`, from time to time it fails with this error
commit sha: 9231a903b4545f847cab550a0c3141b762dca0eb

### Your Environment

OS: Ubuntu 21.04 x86_64
Kernel: 5.11.0-34-generic
Gradle: 7.2
Configuration cache is enabled, not sure if this issue reproducing without it.

Was not able to gather build scan because of other issue: https://github.com/gradle/gradle/issues/14536

**Comment by wolfs** [comment]
Hi @dsvoronin, thank you for reporting. This error 2 means that the directory Gradle tried to watch did not exist any more. This may happen when re-using the same daemon for integration tests which run Gradle and which delete the test project directories afterwards.

All in all, this is not a bad thing. In Gradle 7.3 we silenced this warning if you use the default setting for file system watching, because it is not actionable and not a problem.
