### ISSUE TITLE
[Feature] Add Build Scan plugin to Gradle core

### ISSUE THREAD

**Issue by jaredsburrows** [gradle/gradle#1834]
Can the build scan plugin be added to gradle so existing and new users can integrate build scans into their existing and new projects, can we add the gradle build scan plugin into gradle itself?

This way we do not have to check https://plugins.gradle.org/plugin/com.gradle.build-scan for updates, we can simply upgrade gradle itself and create a normal build like so: `gradlew assemble --scan`.

**Comment by eriwen** [comment]
@eljobe do you have any thoughts we can share here?

**Comment by eljobe** [comment]
@jaredsburrows, thanks for the suggestion. We've considered something like this several times. Unfortunately, due to the licensing differences, the Build Scan Plugin cannot be shipped with the Gradle Build Tool. The plugin is not open-source.

One thing we will probably tackle in the long-term (i.e. it is not yet scheduled) is making the downloading and updating of the build scan functionality more automatic and lower-effort than typical plugins. From the end-user's perspective it would "seem" like the build scan functionality is shipped with the Build Tool, but it would actually be downloaded on demand when the user has configured the Build Tool to publish build scans.

One other subtlety is that often, it is more important that the version of the Build Scan Plugin match the version of the Gradle Enterprise installation to which it is publishing than that it match the version of the Build Tool which is running the build. For that reason, our future "automatic" download would likely function differently than regular plugin downloads in that it would contact the targeted build scan server to figure out which version of the plugin should be downloaded.

I hope this all makes sense. Again. We haven't worked out all of the technical details of the plan, and we do have a lot of higher-priority work scheduled for before the Gradle Summit in June. But, we have a longer-term plan to make this smoother.

Thanks again for the suggestion.

@eriwen, since we are tracking this work internally, can we close this request, or should we leave it open as a placeholder and use it to update the community once we've implemented our plan?

**Comment by eriwen** [comment]
@eljobe I think it would be good to have this open for community members who want to comment or vote. I expect that Jared is not the only one who wants this.

**Comment by jaredsburrows** [comment]
@eljobe @eriwen Thanks for the response. Is the build scan plugin not open source? I believe it should be since we can now run `gradlew --scan` via command line when the plugin is applied which makes it tightly coupled with Gradle. It would be nice to just have the latest build scan plugin with the latest version of Gradle!

Similar to other plugins, you have to "apply" it to your project to enable it. The only difference I see here is adding it to your build then accepting the license after.

**Comment by alkemist** [comment]
We should be clearer about what we are trying to achieve here. Adding the build scan plugin to the core is not a feature. It might be an implementation detail of a feature.

My understanding based on the original description is that the feature would be the ability to create a scan on scans.gradle.com for a build without making any modifications to it. That is, I take any Gradle build, run with `--scan` and I get a scans.gradle.com build scan. If so, I suggest we re-title to “Create build scan for build without modifying the project”.

This would only really be useful in a subset of cases where build scans are useful. For example, build scans are most useful when _all builds_ are being recorded, which at least currently requires some build script opt-in. Regardless, this may be a worthwhile feature for easing on-boarding and other ad-hoc use cases.

**Comment by jaredsburrows** [comment]
@alkemist Yes, not a "feature" just merging an existing plugin into the core code base.

> "Create build scan for build without modifying the project"

 -- I love it!

Where is the source for the build scan plugin? Who all needs to agree in order to get this merged in?

**Comment by jaredsburrows** [comment]
Bump. Any update on this?

**Comment by eriwen** [comment]
@jaredsburrows I expect that we will not include the build scan plugin in 4.0 or 4.1 (next 2 releases). 

We are considering applying plugins on-demand, which one could use to create a scan without applying the build scan plugin in the build script. However, we also need to ensure we have a mechanism for users to confirm that they accept the privacy agreement in the same mechanism.

Is there any particular urgency from your side?

**Comment by jaredsburrows** [comment]
@eriwen Thanks for the update. There is no urgency. I just think it is odd that Gradle provides a plugin outside of the normal source repository and it is not bundled with Gradle.

@w25r Thanks. This issue was really just more of a question. Also I like using `hasProperty` to toggle on and off certain plugins.

**Comment by jaredsburrows** [comment]
Any update on this?

**Comment by alkemist** [comment]
Hi @jaredsburrows. There's no update on this at this time. It's something we are continuously evaluating in the list of priorities.

**Comment by oehme** [comment]
This is being done right now: https://github.com/gradle/gradle/issues/2836

**Comment by jaredsburrows** [comment]
@oehme Yay!

**Comment by jaredsburrows** [comment]
@oehme Did this ever land? Do we still always have to apply:

```
plugins {
  id("com.gradle.build-scan") version "2.4.2"
}
```

**Comment by jaredsburrows** [comment]
Got it working, https://github.com/jaredsburrows/android-gif-example:

```
rootProject.name = "android-gif-example"

plugins {
  id("com.gradle.enterprise").version("3.0")
}

gradleEnterprise {
  buildScan {
    termsOfServiceUrl = "https://gradle.com/terms-of-service"
    termsOfServiceAgree = "yes"
  }
}

include(":app")
```
