### ISSUE TITLE
请教一下，gradle 7.2 怎么打带依赖的可执行jar包？gradle7.2:  How to build an executable jar package with dependencies?

### ISSUE THREAD

**Issue by 344672699** [gradle/gradle#18418]
请教一下，gradle 7.2 怎么打带依赖的可执行jar包？

I'd like to ask this question：
gradle7.2:  How to build an executable jar package with dependencies
in other word ， How to add dependencies desc into manifest file?

**Comment by scaventz** [comment]
As far as I know: 
1. There is a [Application Plugin](https://docs.gradle.org/6.6.1/userguide/application_plugin.html) for this purpose, but it has a known [issue ](https://github.com/gradle/gradle/issues/1989)on Windows.
2. If you are working with Springboot, please refer to [Spring Boot Gradle Plugin](https://docs.spring.io/spring-boot/docs/current/gradle-plugin/reference/htmlsingle/#introduction)

**Comment by blindpirate** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

There's no built-in plugin for that purpose, but you can heck out https://github.com/johnrengelman/shadow , which is the most popular community plugin to generate shadowjar/uberjar. You should search before asking. 

https://www.google.com/search?q=gradle7.2%3A+How+to+build+an+executable+jar+package+with+dependencies&oq=gradle7.2%3A+How+to+build+an+executable+jar+package+with+dependencies&aqs=chrome..69i57j69i61.956j0j7&sourceid=chrome&ie=UTF-8
