### ISSUE TITLE
androidTest jacoco can't exclude specific class 

### ISSUE THREAD

**Issue by Thoriny** [gradle/gradle#18427]
### Current Behavior
task jacocoTestReport (type: JacocoReport) {
    def fileFilter = [
            '**/R.class', '**/R$*.class', '**/BuildConfig.*', '**/Manifest*.*',
            '**/*Test*.*', 'android/**/*.*', '**/Dms$*.class', '**/DmsListener$*.class',
            '**/Dms.class', '**/Dms.class','**/Hud*.class'
    ]
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: generatedSources)
        }))
    }
}
### Context
I  want get higher coverage rate, Some classes should be excluded.
but it does't work.

### Your Environment
gradle: 6.3
AndroidStudio:4.2.1
wiondows 10

Build scan URL:

**Comment by blindpirate** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***
