### ISSUE TITLE
Return of Problems reading data from Binary store

### ISSUE THREAD

**Issue by jimshowalter** [gradle/gradle#18494]
### Expected Behavior

./gradlew dependencies should generate trees of dependencies and send them to standard out.

### Current Behavior

It blows up with the same kind of error reported in 2020 in https://github.com/gradle/gradle/issues/13316.

And the same list of failed attempts to fix it by deleting caches, recloning, rebooting, etc. applies in our case.

In the previous case the offending artifact was org.glassfish:jakarta.el and in this case it turned out to be com.sun.activation:jakarta.activation:1.2.2, but the behavior is identical.

Adding a dependency on com.sun.activation:jakarta.activation:1.2.1 fixed it for us.

Note that it only did this on one project that happens to involve jakarta activation. Our other projects don't have a problem.

### Context

It makes it impossible to build the project.

### Steps to Reproduce

I don't have time to try to reduce our project to something without intellectual property, but you know how you fixed this the last time it showed up.

### Your Environment

Mac OS, Big Sur 11.6.
Java 8.
Gradle 7.2.

**Comment by yahorsi** [comment]
have the same issue, any ideas pleeeeeeese

![image](https://user-images.githubusercontent.com/9819679/135927345-de4e1f09-9237-42f8-b39b-03dc6541e75f.png)

**Comment by AlexLandau** [comment]
We've been running into this error message periodically as our dependencies shift. I finally whittled down one of our cases to an open-sourceable repro, which triggers the error in Gradle 7.3: https://github.com/AlexLandau/gradle-binary-storage-problem

**Comment by ljacomet** [comment]
@AlexLandau Thanks for taking the time to share this. Will definitely have a look!

**Comment by abcfy2** [comment]
Seem issue when using micronaut 3.2.0 with gradle wrapper 7.2.

```sh
./gradlew dependencies
...
          +--- software.amazon.awssdk:utils:2.16.65 (*)
          +--- software.amazon.awssdk:aws-core:2.16.65 (*)
          +--- software.amazon.awssdk:metrics-spi:2.16.65 (*)
          +--- software.amazon.awssdk:apache-client:2.16.65 (*)
          \--- software.amazon.awssdk:netty-nio-client:2.16.65 (*)

nativeImageCompileOnly (n)
\--- project backend (n)

nativeImageTestClasspath
:backend:dependencies (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 0.58 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':backend:dependencies'.
> Could not resolve all dependencies for configuration ':backend:nativeImageTestClasspath'.
   > Problems reading data from Binary store in /home/fengyu/.gradle/.tmp/gradle3857053052571586601.bin offset 78382 exists? true

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
1 actionable task: 1 executed
Some of the file system contents retained in the virtual file system are on file systems that Gradle doesn't support watching. The relevant state was discarded to ensure changes to these locations are properly detected. You can override this by explicitly enabling file system watching.
Watching 0 directories to track changes

...
```

**Comment by ashutoshgaur0809** [comment]
Problem - C:\Users\Lucid\.gradle\.tmp\gradle419643532000288105.bin offset 0 exists? true Regarding Flutter

Solution:

✅ Flutter/Gradle Build Issue Solution (Binary Store/Gradle Cache Corruption)
If you're encountering errors like:

Problems reading data from Binary store in C:\Users\<YourName>\.gradle\.tmp\... offset 0 exists? true
Or your Flutter project fails to build, follow these step-by-step actions to fix it:

🧹 1. Clean Gradle Cache and Temp Files : Sometimes, corrupted .gradle binary/temp files cause unexpected errors. Run the following:
Windows:
rd /s /q "%USERPROFILE%\.gradle"
Or manually delete this folder:
C:\Users\<YourName>\.gradle

🧹 2. Clean Flutter Project Cache
Next, clean Flutter build and dependency cache:
flutter clean
flutter pub get

✅ 3. Test Another Flutter Project
Try running another working Flutter project (or create a new one):
flutter create test_app
cd test_app
flutter run
✅ If the new project works fine, your environment is likely okay — the issue is project-specific.

🔄 4. Create a Fresh Project and Migrate Your Code
Create a new Flutter project:


flutter create my_new_app
Replace the new project’s pubspec.yaml dependencies with your original project's dependencies.

Run:
flutter pub get
flutter run
During the flutter run, observe any errors/warnings — they may point to problematic packages.

🧪 5. Update or Pin Dependency Versions
Manually check for issues or updates with each package using:

flutter pub outdated
Then upgrade versions where appropriate:

flutter pub upgrade
Or pin to working versions from your test app.

🗃 6. Copy Updated Config Back Once the new project runs smoothly:

Copy the updated pubspec.yaml and android, ios, and lib directories back to your original project.
