### ISSUE TITLE
Build cache configuration is not inherited from top-level build in included build inside pluginManagement block

### ISSUE THREAD

**Issue by eugene-krivobokov** [gradle/gradle#18511]
Build cache configuration is not inherited from top-level build in included build when it's used only in `pluginManagement` block.

```kotlin
pluginManagement {
    includeBuild("...") // this build
}
```

### Expected Behavior

All included builds inherit build cache configuration from top-level build as described in https://docs.gradle.org/7.2/userguide/build_cache.html#sec:build_cache_composite

### Current Behavior

Build cache configuration is inherited in "regular" included builds but not in builds inside `pluginManagement` block.

### Steps to Reproduce 

- Checkout: https://github.com/avito-tech/avito-android/tree/MBS-12013-reproducer
```sh
docker run -p 5071:5071 gradle/build-cache-node:9.9`
./gradlew --stop
make clean_build
make clean_build_cache
./gradlew help
./gradlew buildScanPublishPrevious
```
- See remote cache operations

### Your Environment

Build scan URL: https://scans.gradle.com/s/lyjkmx5tjaucu/timeline?cacheability=cacheable&details=wrvlxf5g4svje&task-path=build-log
Gradle 7.2

**Comment by ljacomet** [comment]
This is unfortunately a chicken-and-egg problem. The build cache is configured in the Gradle settings, so any included build that can participate as a plugin or even a settings plugin will have to be evaluated _before_ the build cache configuration anyway.
Injecting the configuration at a later stage would be technically possible but also possibly confusing or useless.

Note for example that the fact the build cache configuration can apply to `buildSrc` is because its evaluation is now _after_ evaluating settings. When the order was reversed, this was not possible.

In this context, the workaround is to have the build cache configured in the included builds that appear in `pluginManagement`.
