### ISSUE TITLE
[Feature request]: Remove old dependencies

### ISSUE THREAD

**Issue by Drjacky** [gradle/gradle#18516]
It'd be good if we could delete old dependencies. For example, we have retrofit dependency which we use since 3 years ago.
So, there are too many versions of Retrofit jar files in the gradle cache folder.
It'd be nice if there was a command/script to allow us to remove the old versions:
- retrofit-v0.1 //Remove this
- retrofit-v1.9.0 //Remove this
- retrofit-v2.30 //Remove this
- retrofit-v2.9.0 //Keep this

### Expected Behavior
To remove old dependencies and only keep the newest versions.

### Current Behavior
There is no command/script to achieve this.

### Context
It helps to make more space on the machine.

**Comment by DPUkyle** [comment]
Hi @Drjacky - it is possible that the remaining metadata/artifacts are a side-effect of transitive dependency resolution.

Would you be able to share the output of the `dependencyInsight` report for a reproducer project?

**Comment by Drjacky** [comment]
A sample app could be: https://github.com/Drjacky/MVVMTemplate

But I do not understand what this has to do with a project!
What I meant is we could run a command or script that it search through all of the dependencies in this path: `/Users/drjacky/.gradle/caches/modules-2/files-2.1/HERE` and remove the old versions' folders.

In this example, we remove all of folders except `1.4.0-beta01`
<img width="227" alt="Screen Shot 2021-10-13 at 17 34 27" src="https://user-images.githubusercontent.com/2296754/137175793-54d3fc37-546a-43ae-a64e-2cee9218c8c0.png">
:

**Comment by DPUkyle** [comment]
I believe we do clean-up older dependencies. However, when our dependency resolution engine examines the graph, it's possible that the old versions of `retrofit` or `androidx.activity:activity` are present in the graph temporarily - even though conflict resolution does not leverage them in the final result. Those older dependencies which are only temporarily in the graph "count" as being accessed, and this might explain why they are remaining on disk for you. 

Perhaps substitute the `implementation` or `runtime` configurations for the in the arguments to the `dI` task? The report should confirm my suspicion about whether the older dependency versions are "touched" during resolution, hence marking them as "active" and causing them to not be cleaned-up.

**Comment by Drjacky** [comment]
runtimeOnlyDependenciesMetadata:
https://pastebin.com/rSiHQV46

compileClasspath:
> * What went wrong:
Configuration 'compileClasspath' not found in configuration container.


runtimeClasspath:
> * What went wrong:
Configuration 'runtimeClasspath' not found in configuration container.

**Comment by octylFractal** [comment]
Yes, so while not all of these are retained because of your project, `androidx.activity:activity` in particular is included with 3 different versions:
![screencap of build scan](https://user-images.githubusercontent.com/2093023/137192144-6c7a2aab-685f-429a-8a30-34ef9a994617.png)

For other versions, they should be [cleaned automatically](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:cache_cleanup) within 30 days as long as they are not being used by any builds. If they are not, try stopping your running daemons, as cleanup only [occurs when a daemon stops](https://github.com/gradle/gradle/issues/6084) currently.

**Comment by octylFractal** [comment]
> I have only one version of this dependency or other ones in the project - Yes, maybe they are defined in other projects but, I have not opened them for a while

As indicated in the build scan, even though only one is used, the metadata is still fetched for the other two versions. This means that those versions folder's are still needed to hold the POM files. I expect that if you look inside, you will see that the JARs for those are already removed.

> Some of the dependency versions' created/modified dates are more than a month, a year or two

Gradle does not update the created or modified times of files to track when they were last used, it has its own journal file.

Additionally, I looked at your build scan in more detail, and I believe nearly all of the version in your screenshot can be explained from the image you have provided, and the one project you're running.

- 1.0.0: This one seems to have simply not been cleaned up yet, though due to how recently it was created perhaps another project is using it.
- 1.1.0, 1.3.1, 1.4.0-alpha02: Created in the last 30 days.
- 1.2.2, 1.2.3, 1.2.4, 1.3.0-beta02, 1.4.0-beta1: Is resolved as part of your build scan, so it will have been used recently.

So looking at this one example, it seems as though everything is working properly.

**Comment by Drjacky** [comment]
Got it. Thanks for the follow-up.
Just wondering if there could be a command/script to run by the developer -knowing the risk if there is any - to clean the old versions.
I guess we're not losing anything; as if there is a need for those old versions when we open the project, it fetches it again.

**Comment by bigdaz** [comment]
You can safely delete the entire `files-2.1` directory and Gradle will download only the jars actually required.

**Comment by bigdaz** [comment]
Gradle User Home cleanup will remove any unused dependencies after 30 days.
The retention period can be configured and the cleanup can be forced [via an init-script](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home:cache_cleanup).
