### ISSUE TITLE
Allow plugins to be applied "on-demand" via CLI

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#1870]
## Goals

Provide users with a "works out of the box" experience with plugins not necessarily included in the Gradle distribution.

For example, `$ gradle lint` would apply "on-demand" (a.k.a. "auto-apply") Nebula's [gradle-lint-plugin](/nebula-plugins/gradle-lint-plugin)
## Motivation

This approach would provide the experience of first-class integration with certain plugins without requiring us to physically distribute them as part of the gradle distribution.
## History

Plugin auto-application has been discussed in several contexts, but most recently in the context of integrating the gradle-lint-plugin. See #24, and see [this post](https://groups.google.com/a/gradle.com/d/msg/engineering/M612G_nr4jg/e53DQE-uDAAJ) from the "Gradle 3.0" thread on the engineering list.

Discussed with @hansd that we should allow users to create templates that are remotely resolvable  to be used to bootstrap projects within an organization or throughout OSS projects.

2 options discussed:
- Allow plugins to be applied just-in-time via CLI
- Extend `gradle init` with `--generator` option that can be a VCS URL

**Comment by hansd** [comment]
I think this would also be valuable for plugins that are shipped with Gradle, e.g. running `gradle idea` without requiring to change the build script. And of course the buildscan plugin would really benefit from this capability.

**Comment by eriwen** [comment]
@hansd seems like it could be a win for configuration time if one could conditionally apply plugins like this as well. For example, if `gradle --apply-plugin=org.gradle.idea idea -I ./path/to/idea-config.gradle.kts`

**Comment by hansd** [comment]
Yes. Good point.

**Comment by adammurdoch** [comment]
I don't think we want to offer a way to apply plugins from the command-line. Instead, I think the way to tackle the use case is to _infer_ which plugins to apply based on what the user has asked Gradle to do:

- Run a particular task.
- Calculate a particular tooling model.
- Initialise a particular kind of build.

In other words, not this: `gradle --apply-plugin my-plugin some-task-provided-by-my-plugin`, but this: `gradle some-task-provided-by-my-plugin`.

This approach maintains the separation of the what from the how, so that the user says what and Gradle figures out the how. Expressing a plugin on the command-line _and_ what you want Gradle to do forces the user to do both these things.

**Comment by mat013** [comment]
I guess the main point is to provide some extension mechanism that makes it possible to run some predefined logic without the need of specifying a build script.

A simple mechanism that initial was thought of was most likely to use plugin mechanism mainly because most of the infrastructure is already is in place.

But let us say that we should go for that some task should be specified instead. Wouldn't it be an option to extend the plugin concept to also include these task description in some property file, which some registry could then read from? so we avoid introducing a new plugin look a like?

Gradle could then read from that registry and in order to resolve which plugin should be executed? I guess the property file should describe which plugin should be applied.

Alternatively maybe it should be possible to include gradle scripts in a plugin and the task description property file could then refer to the gradle script which would be executed?

**Comment by adammurdoch** [comment]
It would indeed be an option.

We certainly should be using plugins as the extension mechanism here. All we want to do here is  simply add new ways to make the decision that a plugin should applied, beyond a `apply plugin` statement in a build script.

We already use this approach in the tooling api, by applying the relevant plugins when, say, the eclipse model is requested by buildship. I think we should continue down this path.

There are plenty of options for the exact mechanism for calculating which plugins should be applied, and there's no reason for there to be one exclusive mechanism either. The mechanism(s) themselves might even be packaged up as a plugin, so people can implement whatever strategies they like.

**Comment by pioterj** [comment]
I looks like we are mixing two separate use cases in the history section of this issue description and in the [dev mailing list thread](https://groups.google.com/d/msg/gradle-dev/GC6P8kIYSZ8/Itd-nnQVDgAJ).

1. Ability to invoke a task without applying a plugin that provides it in the build script (e.g. `lint`, `idea`) so that such tasks can be used with minimum friction. 
2. Ability to define and consume [custom `init` plugin templates](https://github.com/gradle/gradle/issues/1686) so that users can get started using specific language or technology with Gradle easier (e.g. community language plugins like Kotlin, Python or Go).

I don't see this as two options but two separate use cases that may possibly share implementation details.

**Comment by mat013** [comment]
When you say you view this as two use cases what would the consequence of that be? That we need to split it up in two epics?

> I don't see this as two options 
Would it be wrong to say that option 1) that eriwen is saying would solve the issue with generating without being an abuse of feature 1)?

**Comment by pioterj** [comment]
@mat013 We already have two issues. I think we are good, I just wanted to call it out. 
- https://github.com/gradle/gradle/issues/1686 for custom `init` templates
- this issue for on-demand plugin application

**Comment by mat013** [comment]
But how about fixing #1870 first and then #1686 can be fixed by refactoring the init template to whatever solution we end up for  #1870 unless the solution does not fit really well. 

I am unsure if #1870 requires a design spec for or not. But I will try to read up on the tooling api that @adammurdoch was mentioning to understand how that works, and see if I can chip in with some suggestions.

**Comment by adammurdoch** [comment]
I think we should start by collecting some real use cases. So far, we have:

- generate the IDEA configuration for the build.
- generate the Eclipse configuration for the build.
- update the Gradle version used by the wrapper.
- view some reports (e.g. `gradle tasks`, `gradle help`)
- bootstrap a new build.
- generate a build scan.
- run lint over the build

The last 2 don't currently make sense to apply in an ad hoc way: the build scan plugin because you have to accept the user agreement in your build definition (but this is something that could potentially be changed to let's say a prompt), and the lint plugin because lint only make senses when also provided with a set of rules that should be part of your build definition.

Bootstrapping a new build itself needs some kind of extensibility mechanism, which I would treat separately, at least from a use case perspective.

We should also consider discoverability, for example, how do I find out I can run `gradle idea` or whatever and how do I do this from the command-line and the IDE?

**Comment by mat013** [comment]
Just to be sure.

When you say bootstrapping a new build is that generating a project from a template?

Otherwise how about these use cases:

Bumping version 
Ensure that there are no dependencies to snapshots

I was also wondering how are name collisions avoided. Should one full qualify the task name or whatever we call them. E.g. how would generate task be distinguished from one plugin from another?

**Comment by alkemist** [comment]
If the only convincing uses of this are the `idea` and `eclipse` tasks, it's dubious as to whether this is worth the investment given that the future here is that these tasks/plugins should not be necessary in their current form.

**Comment by eskatos** [comment]
Just an idea about bootstrapping new builds from templates in this context.
I picture a plugin based on the `gradle-node-plugin` that provides a task to invoke e.g. yeoman.
That sounds to me as a way to move the responsibility of templating/extensibility/hosting/etc out of Gradle. Doesn't solve discoverability of templates though.

**Comment by bamboo** [comment]
I'd love to (ab)use this feature to distributed whole applications as plugins.

Starting the latest version of an application published to a plugin portal:
```
gradle --refresh-dependencies --apply-plugin=myorg.myapp start
``` 

Running an application with additional features:
```
gradle --apply-plugin=myorg.myapp --apply-plugin=myorg.myapp.features.x start
```

**Comment by alkemist** [comment]
@bamboo you sir are a sadist.

**Comment by mat013** [comment]
I haven't looked at the tools api, however I thought about if this would be a solution for this epic?

So before I start I would like to introduce some terms:

* Keyword is the word we can use in order to specify what to do from the command line
* Keyword Plugin is a plugin that is able to react to the keyword. Each plugin is identified by a keyword plugin id
* Keyword Plugin Jar is the jar file which contains the Keyword Plugins. Each Keyword Plugin Jar is identfied by the typical syntax <reverse-domain>:<keyword plugin-jar-name>:<version>

**The first question that springs to my mind how do we specify what we would like to invoke from the command line?**

It has been suggested to use specify what to do rather than how. 

A keyword should have the same constraints as the task names, and it should be suffixed with @

So for instance if i would like to run invoke generate from the command line the command line would be: gradle generate@

One of the obstacles here is we run the risk of having keyword collisions if everybody are able to create keyword plugins.

So my suggestion is that in the general case the full qualified keyword syntax is mandatory and for gradle provided keyword plugins we can have a short syntax, for the full qualified the syntax would look like this:

<keyword>'@'<keyword plugin id>. 

e.g. if I have a keyword plugin jar called 'dk.emstar:template-generator:1.0.0' and I have a keyword 'generate@' then the full qualified should be generate@dk.emstar:template-generator:1.0.0

For keywords provided by gradle we can have introduce just the keyword and have the keyword plugin jar implitcit to be as follows com.gradle.keyword:<keyword withouth @>:latest.integration

So for instance say that I wrote 'gradle generate@' then it implicit means 'gradle generate@com.gradle.keyword:generate:latest-version'

**So how does gradle know what to invoke in the keyword plugin jar?**

I was thinking that there is a mapping file in META-INF/gradle-keywords
each file is a properties file where the filename is a keyword and contains an entry has the following syntax: plugin-id=<keyword plugin id> and another entry task=<task to be invoked>

So i guess the mechanism to resolve everything would be rather straightforward

1.  specify the keyword
2. resolve the keyword plugin jar
3. read the keyword file from META-INF/gradle.keywords
4. apply the specified plugin
5. execute the specified task 

The execution would be equivalent to run the following build.gradle script

```
buildscript {
    repositories {
        <additional repositories>
        <gradle provided plugin repository>
        
    }
    dependencies {
        classpath <keyword-plugin-jar>
    }
}
apply plugin: <keyword-plugin-id>

defaultTasks: <keyword>
```
**How are arguments provided to the plugin.**

I was thinking any argument after the keyword should be considered as argument to the keyword and should appear as properties on the project.

e.g. gradlew generate file=somefile format=java features=[getter, setter] 

the project would have have 3 properties

Alternatively we could specify how arguments could be mapped into the properties on the project in the keyword properties file

**The advantage using this approach:**

  * Most of the concepts are well known already
  * The existing resolution mechanism for keyword plugin can be reused, the infrastructure can be reused. 
  * There will be a rather well known extension mechanism (i.e. very similar to normal plugins), and maybe the codebase for gradle can be reduced by moving for instance init to be a keyword plugin instead
  * It will likely be easier to contribute as extension can be made more easily without people need to have deep knowledge about the internals of the gradle project

**Comment by remal** [comment]
Don't close this issue. This is an automatic message by [Fresh](https://github.com/c-hive/fresh) - a bot against stale bots.

**Comment by juan-f** [comment]
Another use case could be execute a particular plugin and task on the fly against 1000s of repos without the need of going one by one, adding the plugin to the build.gradle, and executing a task.
