### ISSUE TITLE
`v2.0-alpha-1` should not be included in range `[1.0, 2.0)`

### ISSUE THREAD

**Issue by benmarten** [gradle/gradle#1872]
In my build.gradle file:

```
compile 'com.android.support:support-v4:[10.0.0,26.0.0['
compile 'com.android.support:appcompat-v7:[10.0.0,26.0.0['
```

Running gradle dependencies, shows:

```
sourcesReleaseCompile - Classpath for compiling the sourcesRelease sources.
+--- project :MyProject
|    +--- com.android.support:support-v4:[10.0.0,26.0.0[ -> 26.0.0-alpha1
[...]
|    \--- com.android.support:appcompat-v7:[10.0.0,26.0.0[ -> 26.0.0-alpha1
```

I want to avoid including 26.0.0-alpha1... Why isn't gradle respecting ivy standard notation here? 

### Expected Behavior
Resolves to latest v25.
`com.android.support:support-v4:[10.0.0,26.0.0[ -> 25.x.x`

### Current Behavior
Resolves to latest v26.
`com.android.support:support-v4:[10.0.0,26.0.0[ -> 26.0.0-alpha1`

### Context
I was under the impression Gradle honors Ivy standard for dependency resolution. Ivy Standard: http://ant.apache.org/ivy/history/latest-milestone/settings/version-matchers.html

### Steps to Reproduce (for bugs)
Test project: https://github.com/benmarten/gradle-dependency-test

### Your Environment
macOS latest, gradle via brew latest as of writing.

**Comment by bigdaz** [comment]
I think the problem is that we are considering that `26.0.0-alpha1` < `26.0.0` when we order the versions, so that `26.0.0-alpha1` does indeed fall into the version range.

Can you please try with `[10.0.0,26[` and see if you get the same result?

**Comment by bigdaz** [comment]
Gradle honours a version range in a literal way. We treat versions as ordered, and then we decide if a version fits within a range based on whether it is higher or lower than the bounds of the range.

Given versions `26.1` and `26.1-alpha1`, Gradle decides that `26.1-alpha1` comes before (is less than) `26.1`. Then the range `[1.0, 26.1[` is interpreted as `1.0 <= X < 26.1`.  Note that this range would not (and should not) include `1.0-alpha1`.

Unfortunately there's no easy way to address this. One option is to make the bounds of a version range "smarter", so that '1.0-alpha1` is excluded from _both_ `[0, 1.0)` _and_ `[1.0, 2.0)`. A better option is probably to provide a mechanism to say "pre-release versions are OK" for a version range, and to omit pre-release versions (alpha, beta, SNAPSHOT, etc) by default.

Note there is a similar problem where `[1.0, 2.0)` will include `2.0-SNAPSHOT`, even though this isn't what most people want, most of the time.

As a workaround, the desired behaviour can be achieved by using `[10.0.0, 26[` as the version range.

**Comment by grv87** [comment]
+1 to this:
> provide a mechanism to say "pre-release versions are OK" for a version range

There was a discussion at https://discuss.gradle.org/t/how-to-get-latest-release-version-in-an-range/5814.
`resolutionStrategy` and some other features were implemented still then.
But they are very burdensome to use if you want to specify status for single dependency.

It would be more convenient to have this syntax like this:
```
dependencies {
  compile group: 'com.android.support', name: 'support-v4', version '[10.0.0, 26.0.0[', status: 'integration' // or 'release', or 'milestone' if it is from Ivy repo
  compile 'com.android.support:appcompat-v7:[10.0.0,26.0.0[' // 'release' by default
}
```
