### ISSUE TITLE
Loading test reports is sometimes very slow

### ISSUE THREAD

**Issue by w25r** [gradle/gradle#1881]
Sometimes, when a lot of tests are run (usually 1000+), when I open the test results in Google Chrome (on Mac), it takes a couple of minutes before I can navigate and look at the test results.  I've not duplicated this problem with Safari, which seems to handle it better.

### Expected Behavior
Open up index.html, which is entirely offline, in a few seconds.  Navigation to the various tabs should be near instantaneous.  

### Current Behavior
Open up index.html, wait a couple of minutes until page is done loading.  Switching tabs sometimes takes additional minutes.

### Context
If I've made a change that may break some integration tests, I run them all.  Then like to use the test report HTML to navigate to each failure and address it.  

### Steps to Reproduce (for bugs)
I've most often seen it reproduced by running and then loading the test results from a large project, e.g. 
```./gradlew :toolingApi:IntegTest```
But it is sporadic.  I've never seen the issue on Safari.  

### Your Environment
Macbook pro with Chrome and Safari

**Comment by w25r** [comment]
[Internal Slack discussion](https://gradle.slack.com/conversation/C03A0MT6S/p1492122522126634)

**Comment by eskatos** [comment]
Yep, seen the same for `:toolingApi:integTest`.
On Mac/Firefox the behavior is slightly different: nothing is displayed until everything is loaded, but it's still very slow.

**Comment by bigdaz** [comment]
I'm not certain, but it could be that this isn't a regression in our test reports, but instead the result of producing _much_ more output from our cross-version test suites:
https://github.com/gradle/gradle/commit/ea9b408f5f5e0fb21e3eee9e0125b0451b951857

I've added a fix so that we only print the daemon log output when a cross-version test fails _and_ it fails for a reason that will trigger a retry. Hopefully this will reduce the size of these test output files.
