### ISSUE TITLE
intTestHomeDir caching up-to-date problem

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#18948]
I just found myself in a situation where running a sample https://ge.gradle.org/s/27rhx4bfpdesy/tests/:docs:docsTest/org.gradle.docs.samples.SamplesTest/structuring-software-projects_kotlin_aggregate-reports.sample?top-execution=1 failed because it could not find new constants I added to files in the core-api project, org.gradle.api.attributes package.  When I deleted the `intTestHomeDir` directory and re-ran the same command, the current values were found and the tests passed. 

### Expected Behavior
This state should never occur.

### Current Behavior
In this state, the out of date cache is never replaced unless manually deleted.

### Context
Trying to update and test run a single sample in the docs project. 

### Steps to Reproduce 
Needs more investigation.  @big-guy did not encounter issues running the same command against the same commit locally.

**Comment by wolfs** [comment]
I think the reason is that this was a local build. For local builds, we use a timestamped version per day. That also means that when you build a new version, the distribution is new though some cached stated isn't regenerated. One of the cached states is the Gradle API jar, which is stored per version in `intTestHomeDir`.

This version per day is currently a tradeoff between having slow feedback times and correctness for developer builds. Do you suggest changing something there?

**Comment by tresat** [comment]
Perhaps testing samples or snippets in docs is a special case which ought to pay the penalty to regenerate the distribution by default, unless you set a flag to opt-out?  I don't really know what other people's typical workflow is, or have the data to say if this would ultimately result in a timesavings or not.

**Comment by tresat** [comment]
I think this would be a good change.

**Comment by wolfs** [comment]
@tresat Can you create a PR for doing that?

**Comment by tresat** [comment]
I'll give it a shot soon.
