### ISSUE TITLE
I cannot access isDebuggable in dynamic feature modules when i upgrade agp and gradle to 7.0 

### ISSUE THREAD

**Issue by beyondckw** [gradle/gradle#19031]
I cannot access isDebuggable in dynamic feature modules when i upgrade agp and gradle to 7.0 

android {
    buildTypes {
        getByName("release") {
            if (DEBUG_ENABLE) {
                isDebuggable = true           // right in app/build.gradle but error in dynamic-feature/build.gradle
            }
        }
    }
}

**Comment by donat** [comment]
Thank you for your interest in Gradle!

This is an issue with the Android Gradle Plugin which is developed by Google and cannot be addressed in the core of the Gradle Build Tool.

Please open such Android-related issues on the Android Issue Tracker at https://source.android.com/source/report-bugs

**Comment by mochadwi** [comment]
<img width="999" alt="Screen Shot 2022-10-17 at 12 44 24 PM" src="https://user-images.githubusercontent.com/7057959/196098163-51cd3236-72d3-40b8-8d66-82853e47c351.png">

sadly, not possible to create in this component :(

**Comment by mochadwi** [comment]
if in case anyone in the future wants to setup the `isDebuggable` using Kotlin DSL, we need to use `BuildType` instead of `DynamicFeatureBuildType`

<img width="675" alt="Screen Shot 2022-10-17 at 12 49 34 PM" src="https://user-images.githubusercontent.com/7057959/196098898-4a3ef467-1c50-4a20-a0cc-e368d8a983c9.png">
