### ISSUE TITLE
Consider reverting breaking change about test configuration

### ISSUE THREAD

**Issue by melix** [gradle/gradle#19058]
### Expected Behavior

As discussed with @ljacomet, the change to test framework configuration documented [here](https://github.com/gradle/gradle/issues/18606) is a major breaking change. It should probably have been a warning instead.

### Current Behavior

Upgrading a passing build to Gradle 7.3 breaks. See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/296
Any build generated by Micronaut in the past which doesn't configure a test framework explicitly is going to fail when upgrading to Gradle 7.3. Basically it means most of the builds generated, via launch.micronaut.io or the CLI tool, since if you say nothing Micronaut will use JUnit Platform..

### Context

The problem is that builds which used to pass, even if we understand that they were probably not configured as expected, now break. We have multiple users all reporting the same issue. In addition, it's actually pretty hard to figure out _why_ this is happening. In other words, it would be nice if Gradle captured where the `options` block is configured, so that instead of failing:

- it produces a _warning_ that the previous configuration will be discarded
- it tells _what_ configured the old `options`, so that we can trace back to what code was triggered too early

Later, possibly in 8.0, make this an error.

### Steps to Reproduce 

See https://github.com/micronaut-projects/micronaut-gradle-plugin/issues/296 for a reproducer and workaround.

**Comment by tresat** [comment]
After some internal discussion, we're going to be restoring the previous behavior here in a forthcoming 7.3.1 release.

As noted, this behavior is misleading, since test options which are configured prior to setting a testing framework will be discarded.  We will add a warning when this occurs, and will re-remove this behavior in the next major release so that this situation once again fails fast rather than giving a false impression that options have been configured.

We're sorry for any inconvenience this may have caused, we didn't realize this would affect so many projects.

**Comment by ljacomet** [comment]
Closing as this has been merged
