### ISSUE TITLE
Provide a method of excluding a transitive dependency across all configurations and projects

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#19064]
### Expected Behavior

I'd like to exclude a transitive dependency across all configurations and projects

### Current Behavior

I can't exclude a transitive dependency across all configurations and projects

### Context

I was trying to work on #19028 and replace `com.jcraft:jsch` with `com.github.mwiede:jsch`, but the dependency I'm trying to replace is still showing up.

I've tried a number of methods of excluding the dependency, but IntelliJ tells me that the dependency I'm trying to replace is still downloaded.

![image](https://user-images.githubusercontent.com/897017/142664369-413bf572-93c9-4a60-b91c-1e7ff87ca9bf.png)

I've tried the options in 

* https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:excluding-transitive-deps
* https://docs.gradle.org/current/userguide/dependency_version_alignment.html
* https://docs.gradle.org/current/userguide/dependency_capability_conflict.html

but nothing works. 

I've tried some custom code, but this also has no effect.

```kotlin
// <rootdir>/build.gradle.kts
allprojects {
    configurations.all {
        exclude("com.jcraft", "jsch") 
    }

    dependencies {
        modules {
            module("com.jcraft:jsch") {
                replacedBy("com.github.mwiede:jsch")
            }
        }
    }
}
```

**Comment by ljacomet** [comment]
This means that something else is pulling the dependency in. Your changes will impact _project_ dependencies, but it might also show up as a build dependencies.
In order to understand what's happening, you will need to figure out where it is used and by what.

I'll close this issue as it is more of a support question for now than an issue in Gradle itself. If a bug is identified, we can re-open it.
