### ISSUE TITLE
Provider#map doesn't allows to transform into nullable type in Kotlin DSL

### ISSUE THREAD

**Issue by ALikhachev** [gradle/gradle#19088]
### Expected Behavior
Provider#map allows to transform value of any type into any value of any type.

### Current Behavior
Provider#map doesn't allows to transform into nullable type

### Context
I faced the problem on Gradle 7.4-20211122230135+0000 nightly build. It embeds Kotlin 1.5.31 (the same as Gradle 7.3), but Gradle 7.3 doesn't make such a restriction on Provider#map.

### Steps to Reproduce 
1. Get the project from [gradle-buildscript-nullability.zip](https://github.com/gradle/gradle/files/7588739/gradle-buildscript-nullability.zip)
2. Invoke just `./gradlew` and see the fail
3. Change Gradle version to 7.3
4. Invoke the same command again and see that it passes successfully 

### Your Environment
Build scan URL: https://gradle.com/s/k5j5dqo4fth3i

**Comment by tresat** [comment]
Confirmed that if you change the wrapper version back to 7.3 the example succeeds, if set to the given or current 7.4 nightly (https://services.gradle.org/distributions-snapshots/gradle-7.4-20211210231011+0000-bin.zip), it fails.

You can reproduce the behavior within the Gradle build itself by adding:

```
    @Test
    @ToBeFixedForConfigurationCache
    fun `can map a provider to null`() {
        withBuildScript("""
            task("run") {
                project.provider { "Hey Gradle" }.map { it as String? }
            }
        """.trimIndent())

        build("run");
    }
```

to `KotlinBuildScriptIntegrationTest.kt`, which, when run, will produce:


> e: /Users/ttresansky/Projects/gradle/subprojects/kotlin-dsl/build/tmp/test files/KotlinBuild.Test/can_map_a_p.null/399mk/build.gradle.kts:2:45: Type mismatch: inferred type is String? but String was expected
> e: /Users/ttresansky/Projects/gradle/subprojects/kotlin-dsl/build/tmp/test files/KotlinBuild.Test/can_map_a_p.null/399mk/build.gradle.kts:2:45: Type mismatch: inferred type is String? but TypeVariable(S) was expected

The generic type arguments should become `Any?` when Kotlin sees the Java code in `Provider#map`

I've experimented with adding `@TypeQualifierNickname` per https://kotlinlang.org/docs/java-interop.html#jsr-305-support to explicitly defining the type arguments as nullable:

```
@Nullable
@TypeQualifierDefault({ElementType.TYPE_USE, ElementType.PARAMETER})
@interface NullableTypeArgs {}
```

by adding this to the `map` method, but this doesn't help - the same errors are produced with that test case.  I can see it is having an effect, because when I do this, I have to add explicit null-checks `!!` to some places in the project to get it to compile.

I've also tried replacing all instances of `Xjsr305=strict` with `Xjsr305=warn` or `Xjsr305=ignore`, which also produced the same errors.

**Comment by DPUkyle** [comment]
See #12388

**Comment by big-guy** [comment]
For 7.4, we reverted back to the old behavior (which isn't correct for other reasons mentioned in #12388).
