### ISSUE TITLE
TaskContainer.contains not working

### ISSUE THREAD

**Issue by cdalexndr** [gradle/gradle#19219]
I issue the following command `gradlew :backend:build` (no root project tasks are in execution graph)

### Expected Behavior
"Development build"

### Current Behavior
"Production build" 
`tasks.contains` is broken. Most likely an missing/invalid equals/hashCode methods on `Task` impl type.
Task `:backend:build` is considered the same as `:build` task.
Both project and task name should be taken into account, to uniquely identify a task.

### Context
I have a multi-project configuration (one root with sub-projects).
The root build script contains production related tasks.
I want to detect if the build is a production or development build by the running tasks.
Root project has some tasks with same name as in sub projects.

### Steps to Reproduce 
`root build.gradle snippet:`
```
gradle.taskGraph.addTaskExecutionGraphListener({
    TaskExecutionGraph graph ->
        def prodTasks = graph.allTasks.findAll { el -> tasks.contains(el) }
        if (prodTasks.size() > 0) {
            println "Production build" 
        } else
            println "Development build"
})
```

### Your Environment

Build scan URL:
Gradle 7.3.1

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

Your detection logic seems flawed and seems to be what relies on _name_ only and not the _project_ of the task to determine the output.
If Gradle confused tasks with the same name from different projects, it would simply be broken and that's not the case.

**Comment by cdalexndr** [comment]
The project `tasks` object contains only current project tasks, but if I call `tasks.contains(` with another project task with the same name, it returns true (**incorrect!**).
It seems that only the task name is compared, but it should also compare the tasks's project.

Here's a sample test repo: https://github.com/cdalexndr/gradle-19219
Run `gradlew :subproject:mytask`:
```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Developer\issues\gradle\taskcontainer_contains\build.gradle' line: 18

* What went wrong:
Failed to notify task execution graph listener.
> assert !tasks.contains(task)
         ||     |        |
         ||     true     task ':subproject:mytask'
         |[task ':buildEnvironment', task ':components', task ':dependencies', task ':dependencyInsight', task ':dependentComponents', task ':help', task ':init', task ':javaToolchains', task ':model', task ':mytask', task ':outgoin
gVariants', task ':prepareKotlinBuildScriptModel', task ':projects', task ':properties', task ':tasks', task ':wrapper']
         false

```

**Comment by cdalexndr** [comment]
Discuss url: https://discuss.gradle.org/t/taskcontainer-contains-returns-true-for-diff-project-task-with-same-name/41631

**Comment by Vampire** [comment]
@ljacomet may I ask why you think this is a usage question, not a bug?
- `tasks.contains` is `DefaultDomainObjectCollection#contains`
- this delegates to `getStore().contains`
- `getStore()` returns a `SortedSetElementSource`
- `SortedSetElementSource#contains` delegates to `values.contains`
- `values` is a `TreeSet` with `Namer.Comparator` configured with `Task.Namer` as comparator.
- `Task.Namer` just returns `Task#getName()`

If you now also take into consideration the JavaDoc of `TreeSet`:
> Note that the ordering maintained by a set (whether or not an explicit comparator is provided) must be consistent with equals if it is to correctly implement the Set interface. (See Comparable or Comparator for a precise definition of consistent with equals.) This is so because the Set interface is defined in terms of the equals operation, but a TreeSet instance performs all element comparisons using its compareTo (or compare) method, so two elements that are deemed equal by this method are, from the standpoint of the set, equal. The behavior of a set is well-defined even if its ordering is inconsistent with equals; it just fails to obey the general contract of the Set interface.

I'd say this is a Gradle bug.
Because `equals` is just the one inherited from `Object`, while the comparator deems tasks with the same name as equal, no matter what project they come from.
This is the cause that `task.contains` does not behave as expected as the Gradle usage is violating the `Set` contract.

**Comment by cdalexndr** [comment]
@Vampire I'm **not** saying this is a usage question. I've opened this issue because it is a **bug**.
After this got **closed as invalid**, I've opened a discuss thread to attract visibility so that it gets a second opinion and hopefully reopened.

**Comment by ljacomet** [comment]
As you indicated, the `tasks` container ends up using the `name` only as the identifier. This is because Gradle assumes that the container only deals with tasks for the current project.
So while it can be surprising, it is effectively a limitation of the current model.

Bug or not, this shows that before blinding calling `tasks.contains`, the caller has to verify the container and the task share the same project.
An alternative for implementing that logic would be to ask if the task graph contains any of the root project tasks, as `TaskExecutionGraph#hasTask(org.gradle.api.Task)` most likely behaves properly.

I could re-open this issue but there might not be any attention to fixing this, especially as the use case can be handled differently.

**Comment by Vampire** [comment]
Even if not fixing the `Set` contract violation,
maybe at least the `TaskContainer` could overwrite `contains` and check the project, that would then at least behave properly in the case described by OP I think.
And maybe the JavaDoc could be improved, because `TaskContainer` just says it holds "a set of Task instances", not that they have to be within the same project.
