### ISSUE TITLE
Version range without upper bound with square brackets does not work

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#19316]
The documentation at https://docs.gradle.org/7.3.1/userguide/single_versions.html says that
- you can use `[1.0,)` to just have a lower bound
- when the upper or lower bound is missing, the range has no upper or lower bound
- the symbol `[` can be used instead of `)`

So I tried to use `[1.0,[`, but that didn't work.
It tried to resolve that version verbatim.

**Comment by Vampire** [comment]
Ah, ok, thanks. 
I probably considered infinity as the exclusive upper bound. 
But the previous bullet point clearly states that in that case no bound exists, so I'd say this time it is just a me-problem.

**Comment by ov7a** [comment]
Well, to be fair It's not 100% clear. I think it can be improved. Let's keep this open, maybe somebody would want to fix that.

**Comment by chuckthemole** [comment]
@ov7a, I'm interested in contributing and have started looking into the issue. Would this edit be clearer?

current:
`The symbol ] can be used instead of ( for an exclusive lower bound, and [ instead of ) for exclusive upper bound. e.g ]1.0, 2.0[`

edit:
`The symbol ] can be used instead of ( for an exclusive lower bound and [ instead of ) for an exclusive upper bound. e.g. ]1.0, 2.0[. Note: The range ],2.0[ is not appropriate, as it lacks a lower bound, and can be rewritten as (,2.0[.`

Let me know and I can open a pr. Thanks!

**Comment by ov7a** [comment]
@chuckthemole 
Minor nit: I think the example from @Vampire `[1.0,[` is more appropriate since it's more common to use the latest version.
The PR would be welcomed, thanks!

**Comment by chuckthemole** [comment]
Thanks @ov7a. I've created a [PR](https://github.com/gradle/gradle/pull/30344). Let me know if there is anything else.
