### ISSUE TITLE
Java compiler constant analysis seems to be broken on 8u301

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#19353]
After upgrading JDK from 8u291 to 8u301, some tests start failing: https://ge.gradle.org/s/upnw3rem6jm4i/tests/overview

There might be some internal change in JDK compiler.

Steps to reproduce:

- Install JDK 8u301.
- `./gradlew -PtestJavaVersion=8 -PtestJavaVendor=oracle :language-java:eIT --tests CrossTaskConstantChangesIncrementalJavaCompilationUsingJarIntegrationTest`

**Comment by donat** [comment]
@asodja You did some changes in this area in the past. Do you have the bandwidth to take a look?

**Comment by asodja** [comment]
Checked and it seems this JDK does not track milliseconds of the files last modified timestamp so Gradle doesn't detect files as changed if there is a fast change. Will investigate with @wolfs and @blindpirate further.

**Comment by asodja** [comment]
There was a change in the JDK 8u301. `File.lastModified()` returns (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8177809) timestamp with milliseconds but previously it did not. Unfortunately, this is inconsistent with `Files.readAttributes(symlink, BasicFileAttributes.class)` that is used in `DirectorySnapshotter`.

Due to that this code breaks:
https://github.com/gradle/gradle/blob/5ec3f672ed600a86280be490395d70b7bc634862/subprojects/core/src/main/java/org/gradle/api/internal/changedetection/state/CachingFileHasher.java#L86
since we use `File.lastModified()` for a marker file and `Files.readAttributes(symlink, BasicFileAttributes.class)` for snapshotted files, to detect if we can use cached value or not. And since these two methods return inconsistent timestamps we detect this incorrectly: in that case we take cached value even though we shouldn't.

**Comment by donat** [comment]
Thank you for taking care of this, Anze!
