### ISSUE TITLE
Gradle JUnit Platform support doesn't support non-standard test descriptors with filter patterns

### ISSUE THREAD

**Issue by codecholeric** [gradle/gradle#19352]
When Gradle's JUnit Platform support is configured to exclude some test pattern, then all non-standard test descriptors will be ignored, even if they have no relation to the filter.

Take for example

```
test {
  useJUnitPlatform()
  filter {
    excludeTestsMatching "*IT"
  }
}
```

and the [ArchUnit test engine](https://www.archunit.org/userguide/html/000_Index.html#_junit_5). Furthermore, take a test 

```
@AnalyzeClasses(packages = "example")
public class SomeArchTest {
    @ArchTest
    public static final ArchRule example = classes().should().bePublic();
}
```

### Expected Behavior

The specified filter pattern should not exclude the rule `example` from being run, since it's neither in a class ending with `IT` nor a test name ending with `IT`.

### Current Behavior

The rule `example` is skipped.

### Context

I'm trying to solve the following issue on the ArchUnit issue tracker: https://github.com/TNG/ArchUnit/issues/743

### Steps to Reproduce 

I pushed the example here: https://github.com/codecholeric/issue-743
The project shows the described setup, i.e. activates JUnit Platform support, a filter for tests and one JUnit Jupiter and one JUnit ArchUnit test, of which only the Jupiter test is run when the pattern is active.

### Your Environment

Build scan URL: https://gradle.com/s/a2b2afnrgtojy

### Responsible Gradle Code

Within `org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.ClassMethodNameFilter` I can see the following code:

```
private boolean shouldRun(TestDescriptor descriptor) {
    Optional<TestSource> source = descriptor.getSource();
    if (!source.isPresent()) {
        return true;
    }

    if (source.get() instanceof MethodSource) {
        MethodSource methodSource = (MethodSource) source.get();
        return matcher.matchesTest(methodSource.getClassName(), methodSource.getMethodName());
    } else if (source.get() instanceof ClassSource) {
        for (TestDescriptor child : descriptor.getChildren()) {
            if (shouldRun(child)) {
                return true;
            }
        }
        if (descriptor.getChildren().isEmpty()) {
            String className = ((ClassSource) source.get()).getClassName();
            return matcher.matchesTest(className, null)
                    || matcher.matchesTest(className, descriptor.getLegacyReportingName());
        }
    }

    return false;
}
```

ArchUnit however uses a custom `TestSource` for the arch rule `@ArchTest example`, namely a [`FieldSource`](https://github.com/TNG/ArchUnit/blob/main/archunit-junit/junit5/engine-api/src/main/java/com/tngtech/archunit/junit/FieldSource.java). Unfortunately, the fallback behavior will decide to exclude this "unknown" type of source, even though it's not matched by the pattern.

I can try to provide some PR to fix this if you want, but I want to discuss first what the desired behavior is here. And what the reasoning behind the current implementation is. Spontaneously I could for example imagine to examine the sections of the test descriptor as fallback, and apply the pattern to each section? 
Or at least let tests run if their source is unknown instead of just skipping them? That would at least be consistent with the behavior when there is no source present... :thinking: However, applying the pattern to the test descriptor would have the advantage that the DSL would work for descriptors like ArchUnit's rule fields as well, instead of just silently ignoring those tests when applying the pattern.

**Comment by donat** [comment]
@gradle/core Could you follow-up on the design questions?

**Comment by tresat** [comment]
I think we ought to change the default/final result if none of the conditions match in `JUnitPlatformTestClassProcessor.ClassMethodNameFilter#shouldRun(TestDescriptor)` to `true`.  

We can't predict every implementation of `TestSource`, as this example goes to show, and since that interface is empty of methods, there's nothing about it we can use to determine if a test should run or not.  Defaulting to `false` here puts an unreasonable implicit restriction on the ability to mix standard tests with custom implementations (such as ArchUnit annotated field-based tests) in the `Test` task - any filters applied to the first type of test will also prevent any of the second type of test from running.  If the intent is to always keep different types of tests run by separate Gradle tasks, this should be made clear.

Note that the documentation on [TestFiler](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/testing/TestFilter.html) mentions only **test method name**
or **test class name**, so an argument could be made that:

```
test {
  useJUnitPlatform()
  filter {
    excludeTestsMatching "*Blue"
  }
}
```

and:

```
@AnalyzeClasses(packages = "example")
public class RulesBlue {
    @ArchTest
    public static final ArchRule example = classes().should().bePublic();
}
```

should cause the `example` field-based test to be excluded, but (using the same `test` spec):

```
@AnalyzeClasses(packages = "example")
public class RulesRed {
    @ArchTest
    public static final ArchRule ruleBlue  = classes().should().bePublic();
}
```

should **not** cause exclusion.  I think this is unintuitive behavior.  Regardless of whether or not we change this behavior by changing the default retuls of `shouldRun`, we should expand the existing documentation on `TestFilter` to note that the include/exclude patterns only apply to `MethodSource` and `ClassSource` types of `TestDescriptor`s.

**Comment by codecholeric** [comment]
Agreed, if the docs clearly say that it only applies to test method and class name, then changing it to match descriptor sections is probably not the best idea... Probably, if support would be added it should be a new type of filter then (e.g. `excludeTestDescriptorsMatching "*Blue"`)
Should I create a simple PR changing the default return value then? To just run every unexpected descriptor instead of skipping it?

**Comment by tresat** [comment]
Community PRs are always welcome!

If you look at `subprojects/testing-jvm/src/integTest/groovy/org/gradle/testing/fixture/AbstractTestFilteringIntegrationTest.groovy` there is a `can exclude tests` method that I think can be easily copied to add tests to exercise and demonstrate the new behavior.

**Comment by codecholeric** [comment]
I created a little PR here: https://github.com/gradle/gradle/pull/19433
I found this test `org.gradle.testing.junitplatform.JUnitPlatformFilteringIntegrationTest` which looked like it already matches this use case, so I hope it was okay to add a test there!
