### ISSUE TITLE
Wrong code gets generated when using MapStruct decorators with incremental compilation in Gradle 7.3

### ISSUE THREAD

**Issue by laech** [gradle/gradle#19366]
I've ran into a problem with using MapStruct's annotation processor with incremental compilation after upgrading to Gradle 7.3, I have also created a MapStruct issue here: https://github.com/mapstruct/mapstruct/issues/2682

### Expected Behavior

Expected the generated `PersonaMapperImpl.java` after incremental compilation to be:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-08T14:16:55+1300",
    comments = "version: 1.5.0.Beta1, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.3.1.jar, environment: Java 17 (Private Build)"
)
@Component
@Primary
class PersonMapperImpl extends PersonMapperDecorator {
}
```

### Current Behavior

Actual content of `PersonaMapperImpl.java`:

```java
@Generated(
    value = "org.mapstruct.ap.MappingProcessor",
    date = "2021-12-08T14:14:11+1300",
    comments = "version: 1.5.0.Beta1, compiler: IncrementalProcessingEnvironment from gradle-language-java-7.3.1.jar, environment: Java 17 (Private Build)"
)
@Component
class PersonMapperImpl implements PersonMapper {

    @Override
    public PersonDto personToPersonDto(Person person) {
        if ( person == null ) {
            return null;
        }
        PersonDto personDto = new PersonDto();
        personDto.name = person.name;
        return personDto;
    }
}
```

### Context

Used to work as expected in Gradle 7.2 but no longer works in 7.3, I have to force a full compilation to get the expected code to be generated, which is not practical for a large project.

### Steps to Reproduce 

1. Check out the demo project for this issue: https://github.com/laech/mapstruct-spring-gradle-incremental-issue
2. `./gradlew compileJava` (`PersonaMapperImpl.java` has the correct content at this point in time)
3. Then make a change in `PersonMapperDecorator.java`, such as adding a random comment.
4. `./gradlew compileJava` (this will run an incremental build,  `PersonaMapperImpl.java` now has the wrong content)

### Your Environment

Ubuntu 21.10
JDK 17

**Comment by ljacomet** [comment]
We've had regressions in incremental compilation in Gradle 7.3.
Can you try with 7.3.2?

**Comment by laech** [comment]
I've tried 7.3.2 and can confirm the problem still exists.

**Comment by laech** [comment]
7.3.3 also has the same problem.

**Comment by filiphr** [comment]
I did an analysis of the problem. The reason why it does not work for MapStruct is due to the fact that in the incremental compilation phase the call to `RoundEnvironment#getElementsAnnotatedWith` does not return the source annotations.

## Compiling in 7.2

Doing `roundEnvironment#getElementsAnnotatedWith(mapperAnnotation)` returns the `PersonMapper` with all of its annotations (also the ones with `@Retention(RetentionPolicy.SOURCE)`).

## Compiling in 7.3

Doing `roundEnvironment#getElementsAnnotatedWith(mapperAnnotation)` returns the `PersonMapper` without the annotations having `@Retention(RetentionPolicy.SOURCE)`.

-----------

It feels to me like in the second round some classes are coming only from their byte sources. Which might make sense for usual incremental compilations and perhaps you have done some improvements in that area. However, for annotation processing if you are adding an originating element to the compilation then you need to add its source, not its bytes source.

I hope that my analysis can help you pinpoint the regression in Gradle.

**Comment by asodja** [comment]
@oehme do you maybe know what change would cause that?

**Comment by oehme** [comment]
I'll have a look

**Comment by oehme** [comment]
The problem here is the interaction between the Mapstruct processor and Spring processor. Mapstruct is an isolating processor, so used on its own it would work with source retention annotations. But Spring is an aggregating processor. Since PersonMapper is touched by the Spring processor, Gradle considers it "aggregated" and presents it in the round environment next time, even when it's not recompiled from source. Mapstruct can't deal with that, because the source retention annotations are now missing. I hadn't considered this case when I wrote the documentation for incremental processors.

We'll have to adjust the documentation to state that *all* incremental processors must have class/runtime retention annotations. Mapstruct will have to change the retention of its annotations.

**Comment by oehme** [comment]
@asodja would you mind adjusting the incremental processing [docs](https://docs.gradle.org/current/userguide/java_plugin.html#aggregating_annotation_processors) accordingly? Right now class retention is only mentioned under "aggregating processors", but it should be under "Both categories have the following limitations:".

**Comment by filiphr** [comment]
@oehme forcing annotation processors to use only `CLASS` or `RUNTIME` retention annotations defeats the goals of the annotation processors. If Gradle mandates this then it could mean that some annotation processors back away from this. Fortunately for MapStruct only the `@DecoratedWith` has `SOURCE` retention, the others have `CLASS`. 

Why can't Gradle use the source file when an isolating processor is present? It only needs the originating element source file, not the rest.

**Comment by oehme** [comment]
>  defeats the goals of the annotation processors

How so?

> Why can't Gradle use the source file when an isolating processor is present? It only needs the originating element source file, not the rest.

That has the potential for serious performance regressions when isolating and aggregating processors are mixed. So there would have to be a strong reason to justify it.

**Comment by filiphr** [comment]
Well the goal of an annotation processor is to generate something from the source code. This means that a lot of annotation processors might be using the `SOURCE` annotation in order to reduce the generated bytecode, since their annotations are most likely useless with the `RUNTIME` or `CLASS` retention.

>I did a quick survey of Google Auto, Lombok, Butterknife, Realm, Spring, Micronaut and a few others. They all use class/runtime retention already. So I'm not too concerned about this.

You might be right about some of them. However, I did found some source annotations for some of those processors:

e.g.

* [Google Auto](https://github.com/google/auto/blob/master/value/src/main/java/com/google/auto/value/AutoAnnotation.java#L110)
* Almost all Lombok annotations are with `SOURCE` retention. e.g. have a look at [Data](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/Data.java)

**Comment by oehme** [comment]
> Well the goal of an annotation processor is to generate something from the source code

That's not accurate though. Java annotation processing explicitly supports processing class files rather than source files. In order for incremental annotation processing to work efficiently, Gradle uses class files instead of source files whenever possible. This saves the compiler a lot of time. Unfortunately we failed to document this for isolating processors, but I think compromising performance would be the wrong step. Instead I think we should go forward with the class retention requirement for all incremental processors and inform those who currently don't have it.

**Comment by asodja** [comment]
@oehme thanks for checking it. I can add this to docs. The unfortunate thing is, that this is a new limitation for the annotation processor projects and some should change the retention to work properly with Gradle. 

What kind of performance penalty would there be if we would support also this case?

Is this an issue just in the situation where the same generated type is modified by the aggregating processor and isolating processor or is that the case when an original type is visited by the aggregating and isolating processor? If the issue is just in the first case then this is a smaller issue I guess.

Also, how does this behave for `Lombok` currently that is kinda an exception, where the original type is modified? I would guess that there `SOURCE` is enough since the original type is modified and not the generated one. And how would that behave if it's changed to `CLASS`?

**Comment by oehme** [comment]
> The unfortunate thing is, that this is a new limitation for the annotation processor projects 

It's not new, the documentation was wrong. It would have failed back in Gradle 4.7 too. The reason people didn't run into this earlier is that the vast majority of processors are isolating. The most notable aggregating processor is Spring, which was made incremental around the same time that the bug in Gradle 6.8 was introduced. This is why people didn't notice the problem until I fixed the bug in 7.3

> What kind of performance penalty would there be if we would support also this case?

Every file that was inspected by an isolating processor and aggregating processor would have to be recompiled on every compile, no matter if it was affected or not. That's essentially the same problem as https://github.com/gradle/gradle/issues/17746, which was a big deal for Micronaut. Making the annotations class retention is such a straightforward workaround that I see no reason to trade performance. Class retention was designed for this purpose.

> Is this an issue just in the situation where the same generated type is modified by the aggregating processor and isolating processor

That's not possible. A file can only be created once, by one processor.

> or is that the case when an original type is visited by the aggregating and isolating processor

That's it, yes.

> Also, how does this behave for Lombok currently that is kinda an exception, where the original type is modified? I would guess that there SOURCE is enough since the original type is modified and not the generated one. And how would that behave if it's changed to CLASS?

The retention policty doesn't change the behavior, it just makes sure that the annotations are visible even when we're not compiling from source.

**Comment by asodja** [comment]
Thanks for the explanation and for checking other projects.

I will update the documentation and we can open an issue to the Auto project.

**Comment by oehme** [comment]
@filiphr are you on board as well with making the change to mapstruct?

**Comment by filiphr** [comment]
Yes I am @oehme. I analysed our codebase and we only had one annotation that was causing this. We will fix it in the next release, the issue is the one that @laech already reported.

**Comment by oehme** [comment]
Thank you both!

**Comment by asodja** [comment]
Closing with: This was an undocumented limitation. MapStruct will make required change in 1.5.0, check also https://github.com/mapstruct/mapstruct/issues/2682.
