### ISSUE TITLE
Toolchains + java 8 + scala 2.10 can pass wrong target parameter to the compiler

### ISSUE THREAD

**Issue by sacchettom** [gradle/gradle#19456]
### Expected Behavior
Specifying JDK 8 in the java toolchain, all scala 2.10.x builds should work correctly building with and targeting JDK8.

### Current Behavior
Tested this in gradle 7.3.2 and 7.3.3. With a toolchain defined as
```groovy
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}
```
The success of the build with scala 2.10.x depends on the scala library version that's being used as compile dependencies in the build - only the latest `2.10.7` will actually work out. The other versions will fail with the error
```
'jvm-1.8' is not a valid choice for '-target'
bad option: '-target:jvm-1.8'
```

### Context
We are switching from gradle 6 to 7 and are starting to use toolchains everywhere. We still have a few old builds that must be maintained with java 8 and scala 2.10.
Settings as before
```groovy
java {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}
```
works, but we would like to use toolchains instead especially as in the future Gradle may require running on java 11 only.

### Steps to Reproduce 
A minimal `build.gradle` like this shows the problem (gradle 7.3.3):
```groovy
apply plugin: 'scala'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

dependencies {
    implementation 'org.scala-lang:scala-library:2.10.4'
}
```
Just add a sample scala source, i.e. taken from scala docs put a `point.scala` in `src/main/scala/org/test/`:
```
class Point(var x: Int, var y: Int) {

  def move(dx: Int, dy: Int): Unit = {
    x = x + dx
    y = y + dy
  }

  override def toString: String =
    s"($x, $y)"
}
```
Launch `./gradlew clean compileScala -si` - the build will fail because of the bad target parameter.
```
Started Gradle worker daemon (0.608 secs) with fork options DaemonForkOptions{executable=/Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/bin/java, minHeapSize=null, maxHeapSize=null, jvmArgs=[], keepAliveMode=SESSION}.
Compiling with Zinc Scala compiler.
Prepared Zinc Scala inputs: 0.114 secs
Compiling 1 Scala source to /Users/*******/code/test-toolchain/build/classes/scala/main ...
'jvm-1.8' is not a valid choice for '-target'
bad option: '-target:jvm-1.8'

> Task :compileScala FAILED
```

Current fixes:
- update the dependency to 2.10.7, or
- remove the toolchain definition and go back to the old block
```groovy
java {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}
```

### Your Environment
Gradle 7.3.3 on OsX

**Comment by rpalcolea** [comment]
I think this is related to https://github.com/gradle/gradle/pull/18347

Per discussion with Gradle folks, this behavior is expected.  (I'm not part of Gradle team)

Gradle can't have all the opinions from the scala compiler so it tries to make the best guess based on the jdk you are asking for and the current version of scala getting used. 

From the original PR:

Few important bits here:

```
* This does not configure the targetCompatibility when using scala 3, it only detects scala-library version which includes 2.10.x, 2.11.x, 2.12.x and 2.13.x

* When scala version is older than 2.13.1, it creates a flag like "-target:jvm-1.8". Otherwise, it will set something like -target:17. Went this route as I noticed the scalac command has the following for such versions Target platform for object files. All JVM 1.5 - 1.7 targets are deprecated. (jvm-1.5,jvm-1.6,jvm-1.7,[jvm-1.8]) . Starting on 2.13.1, it started supporting newer versions (-target:<target> Target platform for object files. ([8],9,10,11,12))

* Gradle tool is not responsible for understanding if the version of Scala selected is compatible with the toolchain. While this implementation makes the best guest to compile to JDK 8 when using modern JDKs and old versions of Scala, there are cases where patch releases added support to new JDKs, for example, Scala 2.13.4 supports Target platform for object files. ([8],9,10,11,12) while Scala 2.13.5 supports Target platform for object files. ([8],9,10,11,12,13,14,15,16,17).
```

Now, the reason this fails is because you are trying to use a JDK 8 for a scala version that does not support it. Your scala version only works with JDK 5, 6, and 7 per https://github.com/scala/scala/blob/v2.10.4/src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala#L43-L45

```
java {
    sourceCompatibility = '1.8'
    targetCompatibility = '1.8'
}
``` 

is definitely not honored and this was a bug reported in https://github.com/gradle/gradle/issues/18211. Historically, Gradle didn't pick up the sourceCompatibility or targetCompatibility flags so basically when you compile Today with that configuration, you are getting the default from your compiler and not what you instructed. After some discussions with Gradle folks, it was decided to only add the support for toolchains going forward and this is why you see different behaviors between `sourceCompatibility`/`targetCompatibility` and toolchains configuration

I think if you want to use JDK 8 with scala 2.10.x you will have to upgrade as you suggest in your current fix. IF you want to use JDK 8 and compile to 6 or 7 byte code, I think you will have to configure the compiler options directly:

```
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.withType<ScalaCompile> {
    scalaCompileOptions.apply {
        additionalParameters = additionalParameters.orEmpty() + "-target:jvm-1.7"
    }
}

```

This way it would use JDK 8 to run the compilation but produce jvm 1.7 bytecode. 

Again, I think you will be better if you manage to upgrade since that's what you really want with your JDK 8 as the intention

Heads up @ljacomet

**Comment by sacchettom** [comment]
Hi @rpalcolea 

> Now, the reason this fails is because you are trying to use a JDK 8 for a scalac version that does not support it. Your scalac version only works with JDK 5, 6, and 7 per https://github.com/scala/scala/blob/v2.10.4/src/compiler/scala/tools/nsc/settings/StandardScalaSettings.scala#L43-L45

My understanding is that JDK 8 is supported from scala 2.10.2, please see https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html - what's not supported is the specific option in the compiler for that version, as people were at that time supposed to just run "with the default" and was added later as needed. i.e. the commit would be https://github.com/scala/scala/commit/69b79ba971ae1c8415da372432f55368617d1f2d

Speaking of which, I now also found the same issue in another build but with Java 11 and scala 2.12.14 :
```
'jvm-1.11' is not a valid choice for '-target'
bad option: '-target:jvm-1.11'
```
here I discovered indeed, thanks to you, that before this was generating java 8 bytecode from scala compiles despite the jdk 11 defined in the toolkit. Now (went from gradle 7.1.1 to 7.3.3) it's breaking with the message above. It seems the only solution would be to force the jvm 8 compatibility, or remove the toolkit usage indeed

**Comment by sacchettom** [comment]
Sorry, I misread part of your message. Checked out some of our builds (we have mixed scala versions in many of them, and often rebuild with different versions the same code).

Indeed how it seemed to work before was by using the "default" of the compiler that isn not (as I thought) the current jvm's - but the default the compiler was probably built in at the time.

i.e.
scala 2.10.4, 2.11.8 -> generates java 6 bytecode
scala 2.12.14 -> generates java 8 bytecode

So indeed the option to make things as before is to specify the older target inside the compile options as well. It's a bit annoying that the default may break the build though, as it seems the only reliable way to know what you can use is now to check the scalac code, or try to compile manually and see what it does

**Comment by ljacomet** [comment]
This was a known limitation when adding toolchain support to the Scala plugin. There is no intention of fixing that on the Gradle side.
