### ISSUE TITLE
Create a class to represent Gradle Properties

### ISSUE THREAD

**Issue by w25r** [gradle/gradle#1946]
### Expected Behavior
Gradle properties are rich objects, which allows us to treat similar properties with common logic.  This helps ensure that all Gradle properties have consistent behavior.  

### Current Behavior
Gradle properties are simply strings, and logic is duplicated for each one.  Sometimes there are inconsistencies, of even defects.  

### Context
See [this comment](https://github.com/gradle/gradle/pull/1927/files#r114682301) for a rough design spec.  

This will help prevent issues like #1869

**Comment by bmuschko** [comment]
@w25r This is so low priority I doubt we'll ever get to it until somebody tackles it in their spare time. Do you still think it is important or do we just want to close the issue?

**Comment by w25r** [comment]
I think @adammurdoch would beg to differ about it being low priority.  We merged #1927 under the pretense that the core team would not continue to create technical debt by not having this in place.

But I'll defer to him.

**Comment by adammurdoch** [comment]
Absolutely. It's nasty tech debt, which introduces confusing edge cases and inconsistencies in how Gradle decides whether to enable or disable a particular feature (parallel, continue, max-workers, configure on demand, build cache, log level, and so on). When we fix such an edge case we should refactor the code so that these build features are declared (internally) and implemented in a consistent (and much simpler) way, rather than have each feature flag implemented in some ad hoc and inconsistent way.

This issue should be called something like: "Gradle should offer a consistent way to enable build features"
