### ISSUE TITLE
Documentation: Clarify that auto-download only works for vendor AdoptOpenJDK

### ISSUE THREAD

**Issue by nlochschmidt** [gradle/gradle#19504]
Reading the documentation on the java toolChains feature, my colleagues and I understood the docs in a way where auto-provisioning would also work with a custom vendor e.g. `AMAZON`. However after a brief look at the code it is clear that the auto-provisioning will only ever work when no vendor or AdoptOpenJDK is specified.

My suggestion is to add a clear statement to https://docs.gradle.org/current/userguide/toolchains.html#sec:vendors that specifying a known vendor that is not AdoptOpenJDK will disable auto-provisioning.

What I am not completely clear about is whether specifying a custom AdoptOpenJDK baseUri (`org.gradle.jvm.toolchain.install.adoptopenjdk.baseUri`) would allow the auto-provisioning of other vendors.

**Comment by ov7a** [comment]
Sorry for the late reply.

This page has been updated a bunch of times since the issue was created. The relevant section is [Toolchain download repositories](https://docs.gradle.org/current/userguide/toolchains.html#sub:download_repositories), which suggests that available vendors depend on the configured repositories.

Feel free to open a new issue if you think that the documentation is still unclear.
