### ISSUE TITLE
Support local.settings.gradle file

### ISSUE THREAD

**Issue by yaugenka** [gradle/gradle#19660]
The recent composite build feature is awesome.  But there is one thing which is not very handy - the necessity to modify the existing project `settings.gradle` file which is committed to VCS.
The docs advise to create a separate composite build in this case with both projects includeBuild'ed, but creating and keeping a new project with a bunch of configuration files does not seem like a simple solution.
A better approach would be to add support for `local.settings.gradle` which the system would automatically pick local settings from.

**Comment by ov7a** [comment]
Sorry for the late reply.

The recommended way to do some local customization is to use [init scripts](https://docs.gradle.org/current/userguide/init_scripts.html#sec:basic_usage). 

There is also a feature request for [.env files](https://github.com/gradle/gradle/issues/24976).

We think that the existing features of Gradle are enough to achieve what you want. If you feel otherwise, please open a new issue with a more detailed use case and explanation of why the existing options do not work for you.

**Comment by devinrsmith** [comment]
I think an official way to overlay a user-specific properties file would be very welcome. I think it would solve a lot of issues that have come up over the years.

For example, it seems like it could be a very nice solution to https://github.com/gradle/gradle/issues/14235
