### ISSUE TITLE
Unix start script doesn't respect JAVA_OPTS when xargs isn't installed

### ISSUE THREAD

**Issue by roomscape** [gradle/gradle#19682]
### Expected Behavior

- Given I have a Java application that has been built and packaged using the `distribution` plugin
- and I build a docker image containing the application along with a minimal OS
- and I set the image's entrypoint to be the Unix start script generated by Gradle
- and I set some configuration in the `JAVA_OPTS` environment variable
- When I start the container
- Then I expect that my `JAVA_OPTS` configuration should be included in the command line used to launch the java process

### Current Behavior
The Unix startup script uses `xargs` "to parse quoted args". The minimal OS image I'm using doesn't contain `xargs`. When I run the startup script, I see a warning:
```
line 233: xargs: command not found
```
At this point I expect the script to fail. However, the script continues and the application starts up anyway. `JAVA_OPTS` is **not included** in the command line.

### Context
I use `JAVA_OPTS` to set the heap size appropriately for the size of the container I'm deploying. For example, in a 1GB container I might set `JAVA_OPTS=-Xmx700m`, to allocate 700 megabytes of heap and leave 300 megabytes of headroom. This worked fine under Gradle 6.

After upgrading to Gradle 7, the application doesn't respect `JAVA_OPTS` and starts up with the default amount of memory, which is 1/4 of the available memory. In my 1GB container, the application starts up with 250MB of heap.

My **automated tests didn't catch the issue**, because the container still starts up fine and has enough memory to respond to requests. The application only starts to fail when deployed and under load.

**If the start script requires `xargs`, I expect it to fail when `xargs` is not installed.**

### Steps to Reproduce 

https://github.com/roomscape/gradle-start-script

The linked repository contains a Gradle application and a Dockerfile that reproduces the problem. I reproduced the problem in docker since it's an easy way to create an environment where `xargs` isn't installed.

When running the docker container with `--env JAVA_OPTS="-Dfoo=bar"`, the application should print out 
```
Application was started with -Dfoo=bar
```

Instead it prints
```
/example/bin/example: line 233: xargs: command not found
Application was started with -Dfoo=null
```

### Your Environment
Building with Gradle 7.3.3 on OpenJDK 17
Running in Docker on redhat/ubi8-minimal:8.5-218

**Comment by ljacomet** [comment]
Thanks for your interest in Gradle.

I agree that the launch script should fail in that case and it should not be too complicated to add that check.

**Comment by Kurru** [comment]
Apparently this may be very broadly true. I've been seeing the same failure message when running my code which uses `openjdk:17-oracle`

My full Dockerfile
```
FROM gradle:7.2-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src/my_server
RUN ./gradlew clean installDist --no-daemon

FROM openjdk:17-oracle
EXPOSE 80
RUN mkdir /app
COPY --from=build /home/gradle/src/my_server/build/install/my_server /app/

ENTRYPOINT ["/app/bin/my-server"]
```

**Comment by hegyibalint** [comment]
@donat I'm seeing weird things with this feature...
As an example, this is a CI run from #20520: https://gitlab.com/jamietanna/cucumber-reporting-plugin/-/jobs/2361153793#L29

There is the message in the run logs:
`./gradlew: line 234: xargs: command not found`

But looking at the wrapper, this should be not possible:
https://github.com/gradle/gradle/blob/0510103d4925465e5b1336ae514aaf3fdf8aa540/gradlew#L209-L212

Am I not understanding something, or `die` doesn't kill the script?

**Comment by donat** [comment]
`die` should kill the script:

```
die () {
    echo
    echo "\$*"
    echo
    exit 1
} >&2
```

**Comment by edudar** [comment]
This turned out to be a breaking change for me, and I don't see any mention in upgrade docs that the script will die in 7.5 and on. I don't use any args syntax that `xargs` is supposed to help with, so having "xargs: command not found" in the logs was not a big deal; the build was working just fine. Not since 7.5, though. I still don't have any args that require `xargs` but builds simply die now.

**Comment by donat** [comment]
I understand that it's frustrating, although the idea was that it's better to fail explicity rather than accepting some builds and leaving others breaking in sneaky ways. If you use JAVA_OPTS or quoted args in your build then you'd have an unexpected outcome.

UUIC `xargs` is expected to be present in a standard POSIX shell which is a requirement for the wrapper script. What environment do you use? Do you have any blockers for installing `xargs`?

**Comment by edudar** [comment]
@donat builds were running using an ordinary `openjdk:17` container. I switched to a custom-built one with `findutils` added. I understand the reasoning; no problem here. I was just saying that mentioning this change in the docs could have been helpful. Ideally, not dying if not necessary, but at least a mention.

**Comment by joffrey-bion** [comment]
> IIUC xargs is expected to be present in a standard POSIX shell which is a requirement for the wrapper script. What environment do you use? Do you have any blockers for installing xargs?

@donat the current `openjdk:latest` doesn't have `xargs`. I think this is pretty significant. Not sure if this is an intended change in the `openjdk` image, but I wonder why this dependency is needed by Gradle in the first place.

Another point is that maybe `gradlew` shouldn't fail in the absence of `xargs` if none of the environment variables that are parsed in `gradlew` are set.

**Comment by NicklasWallgren** [comment]
We ran into this issue today as well. Reverted the `gradlew` to an earlier version.

**Comment by joffrey-bion** [comment]
> the current openjdk:latest doesn't have xargs. I think this is pretty significant.
> [...]
> the users control the docker image that is used, and it's quite natural for them to fallback to `openjdk:latest`

Let me backtrack on these statements. After further investigation, I noticed that [the `openjdk` docker image](https://hub.docker.com/_/openjdk) is actually deprecated (see https://github.com/docker-library/openjdk/issues/505). So I still don't know if removing `xargs` in the latest versions of these images was intentional or a bug, but I do know we shouldn't be using these images anymore anyway.

I went ahead and checked the alternative JVM images suggested in [the `openjdk` image overview](https://hub.docker.com/_/openjdk), as well as some other big players, and here are my results for whether or not `xargs` is present there:

* `openjdk:11` (deprecated) :white_check_mark: 
* `openjdk:17` (deprecated) :x: 
* `openjdk:latest` (deprecated) :x: 
* `amazoncorretto:latest` (java 8) :white_check_mark: 
* `amazoncorretto:11` :white_check_mark:
* `amazoncorretto:17` :white_check_mark:
* `amazoncorretto:17-alpine3.15` (from our tests) :white_check_mark:
* `azul/zulu-openjdk:11-latest` :white_check_mark:
* `azul/zulu-openjdk:17-latest` :white_check_mark:
* `azul/zulu-openjdk-alpine:11-latest` :white_check_mark:
* `azul/zulu-openjdk-alpine:17-latest` :white_check_mark:
* `azul/zulu-openjdk-centos:17-latest` :white_check_mark:
* `azul/zulu-openjdk-debian:17-latest` :white_check_mark:
* `eclipse-temurin:11` :white_check_mark: (formerly `adoptopenjdk`)
* `eclipse-temurin:17` :white_check_mark: (formerly `adoptopenjdk`)
* `ibmjava:8` :white_check_mark:
* `ibmjava:jre` :white_check_mark:
* `ibmjava:sdk` :white_check_mark:
* `ibm-semeru-runtimes:open-11-jre` :white_check_mark:
* `ibm-semeru-runtimes:open-17-jre` :white_check_mark:
* `ibm-semeru-runtimes:open-18-jre` :white_check_mark:
* `sapmachine:11` :white_check_mark:
* `sapmachine:17` :white_check_mark: 
* `sapmachine:18` :white_check_mark: 

This is pretty encouraging, and means that all the non-deprecated images that I tested *did* have `xargs` available. Which makes sense since this utility is part of the standard POSIX shell. So I guess it's OK if Gradle relies on it.

That said, my other comment still applies:

> Another point is that maybe the start script shouldn't force-fail in the absence of xargs if none of the environment variables that are later parsed with xargs are set.

**Comment by joffrey-bion** [comment]
That said, my other comment still applies:

> Another point is that maybe the start script shouldn't force-fail in the absence of xargs if none of the environment variables that are later parsed with xargs are set.

**Comment by khamburg-dev** [comment]
I disagree with forcing all users to have to install xargs when they may not even need it. Backward compatibility should be the norm. Instead of of this, you could have added a flag to force this behavior for users who wanted to opt into it. Is there a workaround for this (short of modifying my local copy of the wrapper script)? In my case, I have a corporate client that has prepared "golden images" that do not contain xargs, and it's not easy to get those changed. Installing the package on the fly is disallowed.

**Comment by wallind** [comment]
@joffrey-bion I dunno the specifics of the condition under the hood here, but wanted to thank you cause your comment saved me yesterday. Switching a project from Java 11 to 17 I started hitting this and switching from `openjdk` to `azul/zulu-openjdk` did the trick.

Thanks so much for your thorough investigation and documentation of options; saved me loads of time.
