### ISSUE TITLE
Inconsistent Javadoc annotations for org.gradle.api.tasks.testing.TestReport (gradle 7.4)

### ISSUE THREAD

**Issue by EdGue42** [gradle/gradle#19693]
The gradle 7.4 RC1 javadoc has inconsistent annotations, [getDestinationDir()](https://docs.gradle.org/7.4-rc-1/javadoc/org/gradle/api/tasks/testing/TestReport.html#getDestinationDir--) is marked **deprecated**, to be replaced with ** getDestinationDirectory()**. How can something be deprecated when the replacement is considered EXPERIMENTAL?

### Expected Behavior

Not applicable: code documentation only

### Current Behavior

Not applicable: code documentation only

### Context

We are using the "Deprecated" method calls. But in order to fix them, I have to use new APIs ... that are also creating a warning because "incubating"?!

### Steps to Reproduce 

Skipped, problem is obvious from the Javadoc alone.

### Your Environment

Not applicable: code documentation only

**Comment by tresat** [comment]
We're going to be un-@Deprecating the old properties for now in the next 7.4 RC.  The plan is to go through at least one minor revision cycle so that the replacements can be promoted to stable first, prior to deprecating the methods they are replacing.  Note that even though the replacement methods are @Incubating, there is every intention to proceed down this path.  Please see the linked PR.
