### ISSUE TITLE
Cannot use providers.systemProperty inside init script

### ISSUE THREAD

**Issue by Dkhusainov** [gradle/gradle#19758]
I have an init script which reads systemProp from gradle.properties via System.properties. When I do that gradle configuration cache complains about unsafe reads:
`Initialization script 'Z:\g\init.d\gradle-init.init.gradle': read system property 'ARTIFACTORY_PSW'`

Documentation says I should use providers service, which is not available during that phase. 

How can I read ENV/systemProp in init script without gradle complaining?

**Comment by Dkhusainov** [comment]
@gradle/configuration-cache

**Comment by mlopatkin** [comment]
Since Gradle 7.4 you can use System.getProperty to read system properties everywhere including init scripts and these would be correctly marked as inputs to the configuration phase (but not as problems). You can check [the updated docs](https://docs.gradle.org/7.4-rc-1/userguide/configuration_cache.html#config_cache:requirements:reading_sys_props_and_env_vars) for further information.
