### ISSUE TITLE
Is there a mirror image in China that can completely download project related dependencies

### ISSUE THREAD

**Issue by kimonic** [gradle/gradle#19948]
I've tried many methods. There are always some dependencies that can't be downloaded. Who can help me?

![image](https://user-images.githubusercontent.com/23020944/154451351-164c99aa-4aca-4f82-bb1d-50533252fa58.png)

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***
