### ISSUE TITLE
runtime.exclude group: '*' behave differently in Gradle 7 

### ISSUE THREAD

**Issue by l3onL** [gradle/gradle#19950]
Use start.spring.io, create a demo gradle project. 
In gradle-wrapper.properties. 
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
Add below config in build.gradle.
configurations {
	runtime.exclude group: '*'
}

### Expected Behavior
The bootJar task will produce 157KB jar file.

### Current Behavior
The bootJar task produces 8.8MB jar file.

### Context
Use thin jar file.

### Steps to Reproduce 
Any gradle version greater than gradle-6.9-bin.zip, will produce a fat jar. 
Change
distributionUrl=https\://services.gradle.org/distributions/gradle-7.4-bin.zip
to
distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip
produce thin jar.

### Your Environment
JVM 11. Spring boot 2.6.3

**Comment by ljacomet** [comment]
The `runtime` configuration has been deprecated for a while and was [removed in Gradle 7.0](https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal).

However, in the Groovy DSL, your code will result in the creation of a new `runtime` configuration but not extended by any of the Java plugin ones. You will need to migrate away from putting dependencies and tweaking the setup of `runtime` in order to migrate to Gradle 7.x

**Comment by l3onL** [comment]
Thanks for the link, change to runtimeOnly.exclude group: '*' solve the problem.
