### ISSUE TITLE
Java Build DSL

### ISSUE THREAD

**Issue by bowbahdoe** [gradle/gradle#20076]
What would the barriers be to supporting plain Java as an implementation language for build files? Is it just verbosity?

### Expected Behavior
A user should be able to write build files in pure Java

### Current Behavior
Only groovy and Kotlin are supported

### Context
When teaching Java, eventually there comes a point where a student needs to use a dependency. This could be because they want to write a minecraft mod or talk to a database or even just do some text formatting that is in a library.

When this point comes the only practical existing options are
- Introduce Ivy/(Ant, Shell scripts, Make)
- Introduce Maven
- Introduce Gradle

What I see in practice is that no matter what option I pick, students never end up with an actual understanding of what the build tool is doing. This is for a lot of reasons, but one of them is that no intro java student has enough time or context to learn both Java **and** Kotlin/Groovy/XML.

**Comment by martinandersson** [comment]
Java is adding more features all the time, including features that make the language more expressive and compact. Soon we'll have virtual threads after which point I can only hope that will spell the end of all other JVM languages.

Gradle is notoriously difficult to understand, all the DSL and magic is the chief reason. I doubt anyone would disagree lol. And I am also pretty sure most of us spend a majority of our time working on a Gradle build script just googling, many times the same questions over and over again because of the extreme level of complexity. What is the point really, saving a couple of keystrokes which would've taken 20 milliseconds to type versus spending hours googling?

We should absolutely have the option to use plain Java. Gradle need this for its own long-term survival in my humble opinion.

**Comment by bamboo** [comment]
Although it is not possible to write Java build scripts, it's possible to write almost all build logic in plain java via local plugins if that's your cup of tea:

```kotlin
// root settings file with build logic implemented in Java plugin
pluginManagement {
    // bring the Java plugins
    includeBuild("gradle/plugins/") 
}

plugins {
    // Apply Java build logic
    id("my-settings-plugin")
}
```

```kotlin
// gradle/plugins/build.gradle.kts
plugins {
    id("java-gradle-plugin")
}

gradlePlugin {
    plugins {
        create("my-settings-plugin") {
            id = "my-settings-plugin"
            implementationClass = "my.SettingsPlugin"
        }
    }
}
```

```java
// gradle/plugin/src/main/java/my/SettingsPlugins.java
package my;

import org.gradle.api.Plugin;
import org.gradle.api.initialization.Settings;

@SuppressWarnings("unused")
public class SettingsPlugin implements Plugin<Settings> {

    @Override
    public void apply(Settings settings) {
        // Java build logic goes here
    }
}
```

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is not something we'll likely implement. As @bamboo said, you can work around this.

This issue will be closed.
