### ISSUE TITLE
Transitive test dependencies not working using testFixturesApi using Gradle 7.4

### ISSUE THREAD

**Issue by svargh** [gradle/gradle#20085]
```
I am trying to migrate gradle 3.x  to gradle 7, but I am stuck in the test dependencyManagment

Project A: trader.libs.testing:
dependencies {

    testFixturesApi group: 'org.springframework', name: 'spring-test', version: '5.1.5.RELEASE'
    testFixturesApi group: 'junit', name: 'junit', version: '4.12'
    testFixturesApi group: 'org.hamcrest', name: 'hamcrest-all', version: '1.3'
    testFixturesApi group: 'org.mockito', name: 'mockito-core', version: '3.3.0'

}

Project B:  trader.spring
dependencies {
    api project(':trader.libs.spring')
    api project(':trader.libs.base')
    api project(':trader.libs.persistence')
    api project(':trader.libs.security')
    api project(':trader.commons.datetime')

    testFixturesApi project(':trader.libs.testing')

}

Project C1: trader.arbiter
dependencies {
    api project(':trader.libs.websockets')
    api project(':trader.spring')
    testFixturesApi project (':trader.spring')
}

Project C2: trader.arbiter - Works
dependencies {
    api project(':trader.libs.websockets')
    api project(':trader.spring')
    testFixturesApi project (':trader.spring')
    testFixturesApi project(':trader.libs.testing') 
}

### Expected Behavior
import org.junit.Test; in Testclass of  Project C1 should be possible possible.

I expect  the junit libs exposed in C1 over B -> A 
It would be nice if this use case is possible which I got  managed to get work in Gradle 3.


### Current Behavior
JUnit Classes and any library from A are not found in Project C1.
In in A and B those libs are found as described in 
https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures 


### Context


### Steps to Reproduce 
Create three projects A,B,C1 and using the plugins:
plugins {
    id 'java-library'
    id 'java-test-fixtures'
}

### Your Environment

------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.1 (Eclipse Adoptium 17.0.1+12)
OS:           Windows 10 10.0 amd64

```

**Comment by jbartok** [comment]
If I'm not mistaken this is the bit that you are missing: https://docs.gradle.org/current/userguide/java_testing.html#consuming_test_fixtures_of_another_project

**Comment by svargh** [comment]
I tried testImplementation(testFixtures(project(":trader.libs.testing"))) too, and it works for directly referenced projects.
But doesn't work when 
the dependency is not in the directly referenced. After many trials and errors I gave up.

Anyway, I found  this solution and removing the java-test-fixtures plugin:
In Project A trader.libs.testing: 
testImplementation group: 'junit', name: 'junit', version: '4.12' ...

In Project B trader.spring : 
testImplementation files(this.project(':trader.libs.testing').sourceSets.test.runtimeClasspath)

In Project C1 trader.arbiter:
testImplementation files(this.project(':trader.spring').sourceSets.test.runtimeClasspath)

**Comment by ljacomet** [comment]
I believe there are confusion in how to use features like test fixtures and dependencies between project.

Test fixtures are about extending an existing project with code that does not belong to the main jar but can be used for testing by consumers of that project.

From what I understand of your attempts:
* project A trader.libs.testing is a pure "test" project. Its main code is about testing. Code in `main` source set and dependencies in `api` and `implementation` are test related. This project does not need test fixtures defined.
* project B trader.spring uses project A as a _test_ dependency and gets all the test libraries transitively if they were declared as `api` in project A.
* project C1 should use project A directly if it needs the test dependencies. The only way it would get them through B was is B had test fixtures defined and then C1 depended on them as `testFixturesApi(testFixtures(...))`. This would mean changing the setup of B so that its usage of A is part of its test fixture variant.

The solution you share is really not a recommended practice. 

However, I do not see a Gradle issue here, more a usage one. Please share a full reproducer and ask in community Slack or https://discuss.gradle.org if you need more help setting up your project.
