### ISSUE TITLE
Unable to exec "git clone" command by providers.exec for configuration cache

### ISSUE THREAD

**Issue by chrispaulwu** [gradle/gradle#20167]
When I use : 
providers.exec {it.commandLine("git", "clone", "$repo", "$gitDir", "$branchPart", "$proxyPart") }
in order to checkout latest submodule code and compile

But cause:
Process 'command 'git'' finished with non-zero exit value 129

**Request**
Add an API to support this case ?

**Your Environment**
Gradle:  gradle-7.5-20220310231915+0000

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

**Comment by mlopatkin** [comment]
@chrispaulwu, it still isn't exactly clear to me what problem you're facing. The error code 129 shows that the command `git clone` failed to run, typically because of invalid arguments supplied or some misconfiguration. As the `providers.exec` is primarily aimed at getting the output of the process, investigating the actual failure reason might be a bit tricky, because the error output that may have some additional  clues is not printed to the console automatically. To get the error output, you can use something like:
```gradle
def gitClone = providers.exec {
  ...
  ignoreExitValue = true // Do not throw exception from get() when command fails 
}

println gitClone.standardError.asText.get()  // print the captured error output if any 
gitClone.result.get().assertNormalExitValue()  // fail the build if the return value is non-zero
```
Reading the error output can give some clues regarding what is going on.

>providers.exec() can only execute simple commands with return values

I'm not sure what you mean by this, as all commands have return values. However, `providers.exec` is tailored to simplify getting some sort of output of the command (output being the exit code and/or content of standard streams), so running commands for their side effects may be a bit inconvenient. In general, we suggest build authors to avoid running commands at the configuration time and use tasks instead, as tasks are typically more efficient (can be incremental, can run in parallel).

Regarding the use case from https://github.com/gradle/gradle/issues/20167#issuecomment-1066921087 - as this involves a complicated chain of the commands, it might be beneficial to wrap the logic into a custom [ValueSource implementation](https://docs.gradle.org/7.5-rc-1/userguide/configuration_cache.html#config_cache:requirements:external_processes). Within its `obtain` method, you can use injected `ExecOperations` instance or Java/Groovy APIs to run processes as you like. I would encapsulate the whole logic starting from the `rev-parse` inside and maybe even getting the remote commit too. You can return a dummy value from it if the rest of the configuration isn't really affected by the git execution, or some token value to invalidate the configuration cache and re-run the configuration phase from scratch.

**Comment by mlopatkin** [comment]
Potential UX improvements for the exec providers will be tracked in #23914. I don't see anything else actionable in this issue.
