### ISSUE TITLE
Upgrade gradle7.1.2 buildSrc can not find AppPlugin, LibraryPlugin, BasePlugin

### ISSUE THREAD

**Issue by kingkadienm** [gradle/gradle#20163]
When I was using gradle4.1, there was no problem with buildSrc, but when gradle was upgraded to 7.1.2, it reported unable to resolve class com.android.build.gradle.LibraryPlugin when building. For this I wrote a demo address https://github.com/kingkadienm/TestGradleForBuildSrc.git
![image](https://user-images.githubusercontent.com/25675286/158025065-37f3141d-50d1-44ba-a9b0-8a9101d4375c.png)

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue lacks information and/or a reproducer to track down the problem. Unless you provide that information over the next 7 days, this issue will be closed.

***

A number of things:
* Your reproducer has no usage instructions and has the Android dependency commented out.
* Migrating from Gradle 4 to 7 will have a number of important changes, one of them might be the Android version that works with it.
* This really should have been a question on discuss.gradle.org or Stackoverflow as it is unlikely there is a Gradle bug in there because of the above two points.
