### ISSUE TITLE
Imported BOM parsing fails if published with Gradle Module Metadata

### ISSUE THREAD

**Issue by melix** [gradle/gradle#20182]
### Expected Behavior

Consuming a BOM which imports another BOM should behave consistently independently of the fact it was published with Gradle Metadata or no.

### Current Behavior

The [Micronaut SQL BOM](https://repo1.maven.org/maven2/io/micronaut/sql/micronaut-sql-bom/4.2.0/) includes a "imported" BOM:

```xml
<dependency>
   <groupId>org.jdbi</groupId>
   <artifactId>jdbi3-bom</artifactId>
   <version>3.20.1</version>
   <type>pom</type>
   <scope>import</scope>
</dependency>
```

Consuming the SQL BOM into a simple build triggers a `NullPointerException` when Gradle serializes the parsed metadata: https://scans.gradle.com/s/m645kc5luamsi/failure#1

### Context

Micronaut publishes a number of BOMs which themselves may import other BOMs. After we published the latest release of Micronaut SQL, we had builds starting to fail with NPEs: https://github.com/micronaut-projects/micronaut-core/issues/7068

This is quite critical for us since we're in the progress of "aggregating" more BOMs instead of duplicating those into our own BOMs.

### Steps to Reproduce 

Use the following build file:

```gradle
plugins {
   id 'java-library'
}

repositories {
   mavenCentral()
}

dependencies {
   api(platform("io.micronaut.sql:micronaut-sql-bom:4.2.0"))
   implementation "org.jdbi:jdbi3-core"
}

tasks.register("fail") {
   doFirst {
       println configurations.compileClasspath.files
   }
}
```

Run the build with `gradle -g ghome --no-daemon fail` (the new Gradle home and no daemon are to make sure we get fresh metadata and serialize it with the next step). See the build fail.

Now, replace the repository definition with:

```gradle
plugins {
   id 'java-library'
}

repositories {
   
   mavenCentral {
       metadataSources {
           mavenPom()
           ignoreGradleMetadataRedirection()
       }
   }
}

dependencies {
   api(platform("io.micronaut.sql:micronaut-sql-bom:4.2.0"))
   implementation "org.jdbi:jdbi3-core"
}

tasks.register("fail") {
   doFirst {
       println configurations.compileClasspath.files
   }
}
```

Run `rm -Rf ghome/caches && gradle -g ghome --no-daemon fail`. This time the build **passes**, so its the introduction of Gradle Module Metadata which makes the build fail.

Note that directly using the imported BOM, `org.jdbi:jdbi3-bom:3.20.1` instead of `micronaut-sql-bom` works too, so it's really the _import_ which is causing troubles, probably because `jdbi3-bom` itself is not published with Gradle Metadata.

### Your Environment

Build scan URL: https://scans.gradle.com/s/m645kc5luamsi

**Comment by ljacomet** [comment]
There is something strange in the generated Gradle Module Metadata, which I believe Gradle does not handle well on the parsing side.

The `module` file contains the following constraint definition:
```
        {
          "group": "org.jdbi",
          "module": "jdbi3-core"
        },
```
which has no matching entry in the POM file.

Gradle should not allow publication of such a constraint as it simply makes no sense and provides no value. But since that seems to be possible for now - root cause unknown - something probably should be done on the parsing side.
I am considering simply ignoring such entries during parsing itself.

@melix Can you figure out how that constraint makes it there?

**Comment by melix** [comment]
mmm, that's a good catch. It seems that this comes from this line:

```
dependencies {
    constraints {
        ...
        api "org.jdbi:jdbi3-core"
    }
}
```

Which I agree makes no sense and should have been caught earlier (a constraint without version is pointless).

**Comment by ljacomet** [comment]
Actually, there are limited but valid use cases for constraint without version: attributes refinement.

constraints can serve two purposes:
* Define / restrict versions
* Clarify attributes.

For example, it is in effect possible to change a transitive dependency from a regular one to the platform one with a constraint.

The limit is that if they have common attributes, the constraint and the dependency cannot disagree on values. But dependency level attributes are rare.

So the opposite of my example above is not possible: you cannot change a transitive GMM dependency on a platform to not be a platform. That is because `category=library` from the constraint would conflict with `category=platform` on the dependency - as a platform dependency usually has dependency level attributes.

In addition the reason this constraint does not show in the POM is caused by Gradle skipping constraints without version. They would be effectively useless in Maven as the attributes concept cannot be represented.

So Gradle should handle that case properly:
* Keep the Maven POM behaviour - skip writing such `dependencyManagement` entries
* Continue writing constraints without version to GMM although we could forbid them when they do not contain attribute definitions
* Safely support GMM constraints without version in metadata serialization.
