### ISSUE TITLE
Add reason attribute for <component> elements in verification-metadata.xml

### ISSUE THREAD

**Issue by dsaff** [gradle/gradle#20260]
We want to move toward a world in which we verify signatures on all of our dependencies.  However, we can't get there because not all of our dependencies have valid signatures yet.  For these other dependencies, we add checksums to the [components](https://docs.gradle.org/current/userguide/dependency_verification.html#sec:checksum-verification) element in verification-metadata.xml.

However, we want to be sure that when we do this, we are tracking the blocking reasons why we can't use signature verification yet.  Specifically, we'd like to add a `reason` attribute to `<component>`, so that we can add a link to a bug that's tracking the effort to get a signed artifact:

```xml
<component group="g" name="g" version="3.1" reason="Unsigned github.com/foo/bar/issues/43489">
  <artifact name="g-3.1.jar">
    <sha256
      value="f5759b7fcdfc83a525a0336b625ebc282426f16ca137eb5902"
      origin="Generated by Gradle"
    />
  </artifact>
</component>
```

**Comment by donat** [comment]
Would it make sense to put the reason information to the `origin` attribute?

**Comment by dsaff** [comment]
It feels like `origin` has a well-defined purpose, at least as we're using it: it is an immutable value that describes how a value was added.  I like leaving it as-is to potentially be able to scrape for "what are all the `components` that were _not_ added by gradle?"  I think it would be less useful if it became more of a general-purpose free-form text comment.  Does that make sense?

**Comment by liutikas** [comment]
Any thoughts on a proposed fix?

**Comment by mathjeff** [comment]
Hmm it looks like if it were just the `<component>` type needing a reason maybe we could add " because unsigned [some-bug]" as a suffix to the origin field.

I think we'd probably also like a 'reason' field for the `<trust>` entry, too, in case of something like:

```
<trusted-artifacts>
          <trust file=".*kotlin-native-prebuilt-macos-.*" regex="true"/> <!-- b/228184608 -->
</trusted-artifacts>
```

which we could then transform into something like

```
<trusted-artifacts>
          <trust file=".*kotlin-native-prebuilt-macos-.*" regex="true" reason="228184608" />
</trusted-artifacts>
```

and could persist even if we regenerate verification-metadata.xml (the comments don't appear to persist through regeneration).

Would the Gradle team be open to a pull request?

**Comment by mathjeff** [comment]
The adding of a reason field to trust appears to have been straightforward enough but I noticed some tricky details about adding reason to component  (I'm thinking we might want to add it to sha256 instead - details below)

1. A component can have multiple child sha256 elements
   Each sha256 element could have a different origin and/or reason.
   Also, if Gradle automatically adds a new child sha256, it would to decide whether the reason is the same or not and potentially move the value up to the component or down to the children
   If Gradle guesses incorrectly (perhaps the previous reason was "unsigned bug 1" whereas the autogenerated reason is "unsigned" and perhaps a better description would be "unsigned bug 2")
     then it would be more difficult for the user to adjust the reasons

2. There's already an origin field in sha256
  So, we might be able to add the reason into the origin field

Some other factors to take into account:

3. If we have an actual reason field, it makes it easier in the future to allow enforcement that each of these trust elements needs a reason

4. Having reason directly on component allows us to be slightly more concise
  However, it doesn't seem to allow us to be much more concise, see https://android.googlesource.com/platform/frameworks/support/+/d4afec1b57e16f9dcccc9e2c9b4dea1192305860/gradle/verification-metadata.xml
  It appears that in practice, we usually have only about two sha256 children per component

After some more thought I came up with these possible solutions and tried to evaluate each one for difficulty of implementation, clarity in case of duplication, conduciveness to enforcement, and verbosity, and got

A) Put the reason text into sha256.origin
  +: East to implement
  +: Clear auto-update behavior when Gradle adds a new child sha256 to an existing component (because the component won't also have a conflicting origin)
  -: Less clear that we'll be able to enforce in the future that a reason is required
  -: Slightly more verbose usage: one origin per sha256 rather than one per component
  
B) Add a sha256.reason field
  +: Probably easy enough to implement
  +: Clear auto-update behavior when Gradle adds a new child sha256 to an existing component (because the component won't also have a conflicting reason)
  +: We'll be able to enforce in the future that a reason is required
  -: Slightly more verbose usage: one origin per sha256 rather than one per component
  
C) Add a component.reason field
  .: Might be tricky to implement based on the next point
  -: Unclear auto-update behavior when Gradle adds a new child sha256 to an existing component with a conflicting reason
  +: We'll be able to enforce in the future that a reason is required
  +: Concise usage: one reason per component
  
D) Make Gradle persist xml comments
  - Probably difficult to implement
  + Clear auto-update behavior when Gradle adds a new child sha256 to an existing component: doesn't need to add a comment
  - Less clear that we'll be able to enforce in the future that a reason is required
  + Concise usage: one reason per component
  

I'm thinking that the more important factors are probably the second factor (about clear behavior for autogenerated updates) and the third factor about (enforcement), which suggests option B (sha256.reason).

Any opinions?

I'm thinking that this means that we may want to change the plan into:

Add reason attribute to trust elements and also to sha256 elements
