### ISSUE TITLE
[maven-publish] runtime

### ISSUE THREAD

**Issue by Zhiqiang-Wu** [gradle/gradle#20351]
Why not default?

config:
![image](https://user-images.githubusercontent.com/56793420/161375172-d518e34e-61c5-47c1-95a4-e8429c7792ad.png)

pom file:
![image](https://user-images.githubusercontent.com/56793420/161375151-7cc24fa8-85b5-404b-a0ad-327dc1bceb88.png)

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

This issue will be closed after 7 days, unless you can provide more information.

----

Most likely because your dependencies are declared in `implementation`, so then they don't go into the `compile` for Maven scope.
