### ISSUE TITLE
Version catalog builders should not accept multiple `toml` files

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle#20383]
Meanwhile reproducing #20282, a new issue came up: multiple `toml` files can be imported into a single version catalog.
@ljacomet affirmed that this was the old behavior of the version catalog, and now it should not accept any form of multi-file import.

### Expected Behavior
Version catalog definitions should not accept more than one `toml` file import.

### Current Behavior
The issue relates to calling the `from` method with multiple files.
Calling the method multiple times is yielding the expected behavior.

### Steps to Reproduce 
(An all-in-one gist is here: https://gist.github.com/hegyibalint/472f9968df054b514ed855dbce322a41)
The core issue is the following, when applied in a `settings.gradle[.kts]`:
```kotlin
dependencyResolutionManagement {
    repositories { mavenCentral() }
    versionCatalogs {
        create("testLibs") {
            from(files("gradle/a.versions.toml", "gradle/b.versions.toml"))
        }
    }
}
```

### Your Environment
```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Oracle Corporation 11.0.15+3)
OS:           Linux 5.17.1-zen1-1-zen amd64
```

**Comment by melix** [comment]
Alternatively, reintroduce the ability to import multiple files. I don't recall why the restriction was added, but it sounds arbitrary limitation.

**Comment by ljacomet** [comment]
Because importing multiple files requires handling conflict in aliases. Having different prefix for different catalogs resolves that problem in a somewhat simpler way.

**Comment by melix** [comment]
Right. Alternatively you could allow importing multiple catalogs as long as there's no conflict...

**Comment by hegyibalint** [comment]
Our intention is to not handle conflict resolution and stick with a single file import. I understand that it's a letdown that you are already using multi-file imports, but we should watch out for feature creep with version catalogs - it should be a relatively simple feature.

For the time being, per-team, or a single big version catalog would be the way to go.

**Comment by gabrielfeo** [comment]
Splitting dependencies across files in a transparent way is important in large projects and monorepos. A single big catalog is impossible to integrate with CODEOWNERS support. On the other hand, splitting TOMLs as 1-catalog-per-team isn't very maintainable because it exposes to buildscripts which file each dependency comes from, then if a dependency changes owner, many projects' scripts would have to change. One alternative for such projects would be to move away from the standard Version Catalogs to whatever it used before Catalogs, but obviously Catalogs is the best way. Each of the previous solutions had their own issues, as we know.

Doesn't Gradle already alias conflict resolution? From what I understand, it
- [resolves non-version aliases to the last added value with a warning](https://github.com/gradle/gradle/blob/32436ca9b39a2332ff5eef1dc6549c17e04342c6/subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java#L618)
- [resolves version aliases to the first added value](https://github.com/gradle/gradle/blob/32436ca9b39a2332ff5eef1dc6549c17e04342c6/subprojects/dependency-management/src/main/java/org/gradle/api/internal/catalog/DefaultVersionCatalogBuilder.java#L273). This part is documented [here](https://docs.gradle.org/current/userguide/platforms.html#sec:overwriting-catalog-versions).

Support for this is basically implemented, what I mentioned above is done and tested on master. We'd just keep existing behavior and unlock a feature in a simple way (failing on conflict if there's multiple imports). I don't see how this approach would add much complexity to the end user and it doesn't add complexity to the code, as far as I can see.

These would be the basic changes I think: https://github.com/gabrielfeo/gradle/commit/a2648ac40eb6919ce9979a3474fbc228ec2504ed

**Comment by melix** [comment]
I agree with @gabrielfeo

**Comment by gmazzo** [comment]
I have another important use case, `buildSrc`. We want to be able to use Catalog in `buildSrc` without having invalidated the whole build just because a TOML dependency has changed.

So we tried to split `libs.versions.toml` in two:
- `buildSrc.libs.versions.toml`
- `libs.versions.toml`

This way, `buildSrc` will only re-build (and invalidate the whole main build) only if one of its dependencies has changed. 

The problem is that we can't aggregate both files into a single `libs` for the main build. Of course we can create a second catalog entry for the file, but we'll be forced to duplicate dependencies (and versions). 
Having a way to "import" versions from another `.toml` file (or the whole definition itself) will be a nice feature too.

**Comment by hegyibalint** [comment]
Yesterday we debated this issue again, taking into account the comments in here.

Our decision didn't change, as we would still like to _not_ empower the TOML with multiple imports.
Meanwhile Gradle can do conflict resolution, something which you _can_ do, you might _should not_. This point is supported by the fact that you can use code, instead of TOML to define more complex catalog behaviors. 

I've experimented with the ideas presented in this thread and realized that code-based catalog creation is much more flexible and suitable for custom use-cases. Again, the TOML should be a simple, one-stop-shop solution for 90% of the people.

Have a look [at this repo](https://github.com/hegyibalint/gradle-20388-multiple-toml) to see the working example.

**Comment by gabrielfeo** [comment]
Good point. Code can support these use cases much better.

Thank you for taking the time to make that example! If anyone else needs this for dependency updater bots + codeowners, I could get [Renovate](https://github.com/renovatebot/renovate) to parse the plain code version catalogs with [a simple config](https://github.com/gabrielfeo/gradle-20388-multiple-toml/blob/master/renovate.json#L6). Only downside is you must use string interpolation instead of version refs for it to parse correctly.

**Comment by hegyibalint** [comment]
No problems, thanks for bringing it up!

**Comment by efemoney** [comment]
This is a build-breaking change and should at least make it into the release notes :) https://docs.gradle.org/7.5-rc-1/release-notes.html

**Comment by TWiStErRob** [comment]
`<rant>`_Sad to see this happen the way it happened. One tool (Renovate) forces me to split my dependencies, and another (Gradle) forces me to join them... there's no winning._`</rant>`

Please please please reconsider allowing multiple files, this restriction will just yield hacks, the current conflict resolution is sufficient, but if you want, do a **straight up fail the build on any conflict** between files.

Developers will find a way to resolve the conflicts... this should be <1% of the use cases, right? and only temporarily until the conflict is resolved at source.

Maintaining the extra build logic as described in https://github.com/gradle/gradle/issues/20383#issuecomment-1104837616 creates a lot of friction in big teams, someone has to maintain the extra build logic, explaining the limitation to new team members, especially juniors, is just not fun. It goes against common developer experience principles, and creates extra work for apparently no reason.

To give a bit more reasoning:
In this issue you disabled `create("libs") { from(files("...toml")); from(files("...toml")) }`, BUT
`create("libs") { from(files("...toml")); library("x", ...) }` and `create("libs") { from("group:module:version"); library("x", ...) }` also has the same conflict resolution problem, even `create("libs") { library("x", ...); library("x", ...) }` has the same problem of conflict resolution problem.

So unless you forbid these combinations as well (_Please don't! 🙏_), there's no need to restrict loading multiple files into the same version catalog.

We can always roll our own file parsing and call `library` many times in sequence to merge multiple files to one place, but this feature is already present in Gradle, why not allow using it for those 99% non-conflicting use cases?

Note that this even has a performance impact which goes against [Gradle's basics](https://docs.gradle.org/current/userguide/what_is_gradle.html#gradle_overview):
We have to write a Kotlin plugin to generate an in-memory representation of the version catalog so that Gradle can generate a Java source file compiled into class and then used from Kotlin. I don't think I need to call out the difference between Kotlin compilation vs. TOML parsing, but I do anyway.

---

⚠ For those who like to live on the edge, here's a "one-line" replacement for `from(files(...))`:
```gradle
dependencyResolutionManagement {
	versionCatalogs {
		create(defaultLibrariesExtensionName.get()) {
			// Implicit behavior for default defaultLibrariesExtensionName:
			//from(files("gradle/libs.versions.toml"))
			// Load additional libraries from other files (stream will be closed internally):
			org.gradle.api.internal.catalog.parser.TomlCatalogFileParser
				.parse(file("gradle/other.versions.toml").inputStream(), this)
			// This is pretty much equivalent to parsing the file yourself and calling this multiple times:
			//library("my-alias-name", "group", "module").version("1.0")
		}
	}
}
```

---

As a side note: `from(file(...))` doesn't work, we have to call `from(files(...))` even though only a single file is supported.

**Comment by Jon889** [comment]
It's possible to define some in code and some in the implicit TOML file in the gradle directory.
(Not sure about defining some in code and the importing a specific TOML file)

How is that different to multiple TOML files in terms of conflicts?

**Comment by markst** [comment]
@TWiStErRob Thanks for sharing code snippet, appears no longer works in Gradle 8.7. Wondering if you're still using a workaround to support merging multiple `versions.toml`?

**Comment by TWiStErRob** [comment]
@markst https://github.com/search?q=org.gradle.api.internal.catalog.parser.TomlCatalogFileParser+org%3ATWiStErRob&type=code
