### ISSUE TITLE
`--tests` filter with Nested classes not working

### ISSUE THREAD

**Issue by melissachang** [gradle/gradle#20523]
Similar to #19808.

#19808 - Root tests were run, but not nested tests.
This issue - `--tests` completely ignored

### Expected Behavior

I'm trying to run only tests in [WorkspaceDaoTest.java](https://github.com/DataBiosphere/terra-workspace-manager/blob/main/service/src/test/java/bio/terra/workspace/db/WorkspaceDaoTest.java). I expect `--tests WorkspaceDaoTest` to do that.

### Current Behavior
`--tests` is ignored and all tests are run.

### Context
I made a change to `WorkspaceDao` I'm trying to cut down run time by only running `WorkspaceDaoTest`.

### Steps to Reproduce 
[I tried to create minimal reproducer but wasn't able to.](https://github.com/melissachang/gradle-issue-reproducer/tree/mc/tests-filter-nested-class). So here are steps.

```
git clone https://github.com/DataBiosphere/terra-workspace-manager.git
cd terra-workspace-manager/service
../gradlew unitTest --scan --tests WorkspaceDaoTest
```

As you can see from [build scan](https://scans.gradle.com/s/j33gquozrkvv2/tests/overview), tests from all files were run.

`--tests` works with file that doesn't have nested class ([build scan](https://scans.gradle.com/s/qia6vundzfsge/tests/overview)):

```
../gradlew connectedTest --scan --tests WorkspaceServiceTest
```

Here's another example where I tried more combinations. All of these have the bug; every test in every file is run.

```
./gradlew :service:unitTest --tests BigQueryReference.testBigQueryDatasetReference
./gradlew :service:unitTest --tests testBigQueryDatasetReference
./gradlew :service:unitTest --tests BigQueryReference
./gradlew :service:unitTest --tests ReferencedResourceServiceTest
./gradlew :service:unitTest --tests ReferencedResourceServiceTest.BigQueryReference
./gradlew :service:unitTest --tests ReferencedResourceServiceTest.BigQueryReference.testBigQueryDatasetReference
```

### Your Environment
Build scan URL: https://scans.gradle.com/s/j33gquozrkvv2/tests/overview

```
~/terra-workspace-manager (mc/expose-ufId): ./gradlew --version

------------------------------------------------------------
Gradle 7.4.1
------------------------------------------------------------

Build time:   2022-03-09 15:04:47 UTC
Revision:     36dc52588e09b4b72f2010bc07599e0ee0434e2e

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.12 (Azul Systems, Inc. 11.0.12+7-LTS)
OS:           Mac OS X 11.5 x86_64
```

**Comment by jbartok** [comment]
Confirmed as a genuine problem.

The initial assumption was that `--tests` being a task option needs to follow immediately after the task name (ie. without `--scan` being between them, see https://docs.gradle.org/current/userguide/custom_tasks.html#sec:using_task_option_command_line), but not true, that is not the cause of the problem.

If the `test` task is used instead of the custom `unitTest` one, then only the specified tests run, as expected, even with this unrecommended order of command-line options (`test --scan --tests ...`).

Must be related somehow to the way the `unitTest` task is defined and works, might be a genuine bug, we need to investigate further.

**Comment by pleecopperleaf** [comment]
Has this been fixed yet?
