### ISSUE TITLE
No way to apply --no-daemon: current process arguments format bug

### ISSUE THREAD

**Issue by dzharikhin** [gradle/gradle#20611]
### Expected Behavior

It should be possible to adjust jvm settings to match daemon criteria and run trully embedded with --no-daemon
### Current Behavior

There's no way to satisfy daemon criteria
### Context

When trying to run Gradle in --no-daemon mode, see "To honour the JVM settings for this build a single-use Daemon process will be forked" message. To run trully embedded we have to match daemon jvm options.
This check is executed in org.gradle.launcher.daemon.configuration.BuildProcess#configureForBuild it compares required options for daemon and actual options from current jvm.
Required options are parsed as command-line args, for example: `--add-opens java.base/java.util=ALL-UNNAMED` is parsed here as ["--add-opens", "java.base/java.util=ALL-UNNAMED"]
Current options are provided with `ManagementFactory.getRuntimeMXBean().getInputArguments()`, for example: `--add-opens java.base/java.util=ALL-UNNAMED` is parsed here as ["--add-opens=java.base/java.util=ALL-UNNAMED"]
So, JVM options never match
### Steps to Reproduce 

run gradle with --no-daemon option and follow https://docs.gradle.org/7.3.3/userguide/build_environment.html#sec:configuring_jvm_memory instructions
### Your Environment

Gradle 7.3.3
------------------------------------------------------------

Build time:   2021-12-22 12:37:54 UTC
Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.15 (Eclipse Adoptium 11.0.15+10)
OS:           Mac OS X 12.2.1 x86_64

**Comment by mvineza** [comment]
I encountered same issue. When I tried to switch to JDK 8, it works. Meaning the gradle daemon is disabled.

**Comment by GMZwinge** [comment]
I encountered the same issue on Windows 10 with the latest Gradle 7.4.2, and JVM Eclipse Adoptium 11.0.15+10.

**Comment by h0tk3y** [comment]
The suggested fix is:
* Change the default requirements for Java 9+ daemon args to use the single-argument format (`--add-opens=x.y/z.a=ALL-UNNAMED`), so that it could be possible to match them by passing custom `GRADLE_OPTS`;
* Remove some duplicated `--add-opens` arguments;
* Add `--info`-level logging that would make it easier to discover the arguments that the launcher JVM needs. If `org.gradle.jvmargs` are not empty, the build will print a message looking like this into the `--info` logs:

    >Checking if the launcher JVM can be re-used for build. To be re-used, the launcher JVM needs to match the parameters required for the build process: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -Xms300m -Xmx600m -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/Users/sergey.igushkin/Projects/Gradle/gradle/subprojects/launcher/build/tmp -Duser.country=US -Duser.language=en -Duser.variant -ea
    >

**Comment by oehme** [comment]
This change causes IntelliJ to create multiple daemons during import of any project with a `buildSrc` folder, because [this code](https://github.com/JetBrains/intellij-community/blob/631d4506166cf99fdcba69f35cafa1e752eb1386/plugins/gradle/src/org/jetbrains/plugins/gradle/service/execution/GradleExecutionHelper.java#L648) no longer works with the changed argument syntax.

**Comment by sergeykad** [comment]
There is no information about this behavior in the Gradle message: "To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
" or the documentation referenced by it. I understood that there are additional hidden parameters passed to the daemon only after finding this bug. 

Running without a daemon can be very useful in CI environment since there is a high probability that the daemon will not be reused anyway due to ephemeral containers. Running without a daemon writes all log messages in a single place which is also very useful in a CI environment.

**Comment by Fryie** [comment]
I concur with @sergeykad . Launching essentially two JVMs in a CI environment a) consumes more system resources than necessary, b) takes much longer. Especially for small projects, the time it takes to launch the build may take longer than the build / test run itself.
