### ISSUE TITLE
Kotlin build scripts support closure syntax but not lambda

### ISSUE THREAD

**Issue by idlsoft** [gradle/gradle#20617]
The following build.gradle.kts:
```
project.exec {
    commandLine = listOf("echo", "Hello, world!")
}
project.exec { exec ->  // this line does not compile
    exec.commandLine = listOf("echo", "Hello, world!")
}
```
fails to compile, and prints this:
```
build.gradle.kts:4:14: Type mismatch: inferred type is ([ERROR : <Unknown lambda parameter type>]) -> Unit but Closure<(raw) Any!>! was expected
```
`Project` has two `exec` methods, one accepts `Closure`, another `Action`. It looks like the scripting engine only sees the first one.

### Steps to Reproduce 
Create a `build.gradle.kts` with that content and run `gradlew`

### Your Environment
Tried it with 7.4.2 the latest 7.6 snapshot, which uses kotlin 1.6.21 - same result.

**Comment by bamboo** [comment]
Hi @idlsoft, the Gradle Kotlin DSL redefines `Action<T>` to be equivalent to Kotlin's `T.() -> Unit`, i.e., a function type with a receiver. In other words, the Action argument is the lambda receiver `this`.

The Kotlin compiler complains about the lambda with an explicit `exec -> ` parameter in your 2nd example because the explicit parameter makes the lambda incompatible with the `Action<T>` taking overload so the compiler tries to match the lambda against the remaining Closure overload and fails.

I hope that clarifies the behavior you're seeing.

**Comment by idlsoft** [comment]
Thanks for the quick reply, that explains it.

I had a piece of code that I kept moving between plugin and script, so the discrepancy was puzzling. Maybe supporting both would be nice?

Also the error message was a bit misleading. I originally encountered the problem with my own method, which had 2 overloads:
```
public void exec(String cmd) ...
public void exec(Action<ExecSpec> spec) ...
```
The error message said the argument should be String, never mentioning the second signature.

**Comment by hegyibalint** [comment]
There is no plan on changing this behavior.
