### ISSUE TITLE
Complete functional testing of console display

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#2061]
In order to prevent regressions, we should develop functional tests to assert the display of the console using a real, if small, build.

### Test Cases
 * Tasks are displayed in left-most position of WIP
 * Download progress is displayed
 * Initialization, Configuration, and Execution phases displayed

**Comment by adammurdoch** [comment]
We should try very hard to avoid these "add some tests" issues. The testing must be done as part of the story where the original work was done. A fix or a feature isn't done until there are tests to prove it and prevent breakages in the future.

**Comment by bmuschko** [comment]
This has been done.

**Comment by adammurdoch** [comment]
I'm not sure I agree:

- There are 2 test classes that are `@Ignored`.
- The _actual_ test coverage for output grouping is ignored when the test executor is parallel. This is back to front, and means the test doesn't actually run when expected. Instead, the test case should always run with parallel mode and be ignored when the executor is parallel.
- There are some tests that still scrape the output themselves instead of using the fixtures on `AbstractConsoleFunctionalSpec`, eg `ConsoleJvmTestWorkerFunctionalTest`.

**Comment by bmuschko** [comment]
I was not aware of that. I'll have a look.

**Comment by bmuschko** [comment]
Closing as issues have been addressed in `master`.
