### ISSUE TITLE
Intellij IDEA reports a fake error when accessing `libs` extension from `plugins` block

### ISSUE THREAD

**Issue by yevhenii-nadtochii** [gradle/gradle#20839]
### Expected Behavior
Nothing is reported for the code below:

```kotlin
plugins {
    java
    alias(libs.plugins.protobuf)
}
```

### Current Behavior
IDEA reports an error:

```kotlin
plugins {
    java
    alias(libs.plugins.protobuf)
          ^^^^

    // 'val Project.libs: LibrariesForLibs' can't be called in this context by implicit receiver. 
    // Use the explicit one if necessary
}
```

But the script is successfully compiled and executed.

### Context
Migration to a brand-new [version catalog](https://docs.gradle.org/current/userguide/platforms.html), which became stable in Gradle 7.4.2.

### Steps to reproduce

1. Declare a version catalog with a plugin.
2. Apply this plugin using the generated `libs` extension.

### Your Environment
IntelliJ IDEA 2022.1.1 (Ultimate Edition) (Build #IU-221.5591.52, built on May 10, 2022)
Gradle 7.4.2
macOS Monterey, v12.4

**Comment by 3flex** [comment]
I believe this is an IntelliJ problem: https://youtrack.jetbrains.com/issue/KTIJ-19369/False-positive-can-t-be-called-in-this-context-by-implicit-recei

**Comment by chachako** [comment]
@3flex I think it might not be an Intellij problem, because when I remove the [DslMarker](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-dsl-marker/), the problem: 
disappeared.https://github.com/gradle/gradle/blob/d871420cb980d0b54d002107f9e9187e5cf74ab2/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/PluginDependenciesSpecScope.kt#L35

https://github.com/gradle/gradle/blob/d871420cb980d0b54d002107f9e9187e5cf74ab2/subprojects/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/PluginDependenciesSpecScope.kt#L30-L31

Seems like this is where the problem happened
