### ISSUE TITLE
task input property name `os.arch` seems to have no effect.

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#20916]
### Expected Behavior
This should cause tests to never be `UP-TO-DATE` : 

```kotlin 
import kotlin.random.Random

tasks.withType<Test>{
    val random = Random.nextDouble().toString()
    println("random = $random")
    inputs.property("os.arch", random)
}
```

### Current Behavior

and input property of name `os.arch` seems to be treated differently and not caused the task to be out of date. 

`os.arch` seems to be a unique value that triggers this odd behavior. 

### Context
Using a string other than `"os.arch"` DOES work, for example, this does cause `Test` tasks to always be out of date as expected:

```kotlin 
import kotlin.random.Random

tasks.withType<Test>{
    val random = Random.nextDouble().toString()
    println("random = $random")
    inputs.property("cpu_architecture", random)
}
```

### Your Environment

Gradle 7.4.2
macOS 12.1.3

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

----

We have tried to reproduce the issue as you describe it, but we are not getting the described behavior. It works fine for us. Pls. provide a reproducer so that we can continue the investigation.

**Comment by yogurtearl** [comment]
Closing as I can not reproduce on Gradle 7.5.1
