### ISSUE TITLE
Upgrade Kotlin to 1.7.0 and maybe try out the K2 compiler?

### ISSUE THREAD

**Issue by ice1000** [gradle/gradle#20977]
https://github.com/gradle/gradle/blob/3d0ea66443f64e6767beb715f00cf50f001006df/build-logic/dependency-modules/src/main/kotlin/gradlebuild/modules/extension/ExternalModulesExtension.kt#L25

Currently, Gradle is using 1.6.21.

https://blog.jetbrains.com/kotlin/2022/06/kotlin-1-7-0-released/

**Comment by eskatos** [comment]
Once upgraded to Kotlin 1.7 we should revisit https://github.com/gradle/gradle-private/issues/1691

**Comment by akuleshov7** [comment]
Do not use K2 by for now, because it has a lot of limitations in alpha-stage. For example, we faced issues with backward compatibility with libraries compiled by previous versions: https://youtrack.jetbrains.com/issue/KT-52880/K2-Error-Class-is-compiled-by-the-new-Kotlin-compiler-frontend-and-cannot-be-loaded-by-the-old-compiler

**Comment by eskatos** [comment]
The embedded Kotlin was upgraded to 1.7.10 in https://github.com/gradle/gradle/pull/21032 for Gradle 7.6.

Trying out K2 has been extracted in https://github.com/gradle/gradle/issues/21284
