### ISSUE TITLE
Composite/includeBuild breaks dependency management rules

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#21019]
... via `nebula.dependency-recommender` plugin.

Reference [included build](https://github.com/apache/iceberg/blob/a7f7c1a9b78dd596c6c9eda1f0b621950b09f6f5/build.gradle#L41) is using the `nebula.dependency-recommender` plugin with a properties file for version management. This works fine in a "standalone build".

The approach does not work, when the above project's included. [This workaround](https://github.com/snazy/nessie/blob/tools-integration-tests/settings.gradle.kts#L257-L265) ([plus this part](https://github.com/snazy/nessie/blob/tools-integration-tests/settings.gradle.kts#L305-L322)) helps as a workaround, but it's not really nice.

Bumping the `nebula.dependency-recommender` plugin to the latest release didn't help.

(Gradle 7.4.2)

**Comment by ljacomet** [comment]
Unless I misunderstood something, it looks like you want the rules applied to the included build to leak to the parent build.

If that's the case, I would argue this is by design.

**Comment by snazy** [comment]
> looks like you want the rules applied to the included build to leak to the parent build

The problem is that the dependency resolution in the included build itself doesn't work at that point. The included build is not able to resolve its dependencies. I.e. just including the other build breaks it.

**Comment by snazy** [comment]
Reproducer in this repository: https://github.com/snazy/gradle-reproducers

**Comment by ljacomet** [comment]
If the included build updated its dependency declarations to leverage constraints and other Gradle constructs that have _transitive_ impact, you would not see problems.

In the current situation though, I confirm that the current behavior is by design and will unlikely change. Gradle should steer projects towards a state where the project consumption or binary consumption is transparent indeed, but by using the right constructs. Which in this case means updating the iceberg project to provide this and be composable.

**Comment by big-guy** [comment]
This is working as designed, but we know it's not ideal.  

If the recommender plugin included constraints instead of overriding the versions in the resolution graph via rule, downstream consumers would be able to resolve correctly.

We're unlikely to make these rules work transitively. In the future, we might support other ways of sharing the resolved version as a preferred version downstream.
