### ISSUE TITLE
Configuration cache should report a problem when trying to store a non-serializable Java lambda

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#21104]
Instead of failing upon loading with 
```
* What went wrong: |  
-- | --
  | Could not load the value of field `consumer` of task `:myTask` of type `TaskWithConsumerProperty`. |  
  | > LambdaOriginal$Lambda$1070/1766563449
```

**Comment by alllex** [comment]
Relevant test: `org.gradle.api.tasks.LambdaInputsIntegrationTest#task with nested property defined by non-serializable Java lambda disables execution optimizations`

**Comment by h0tk3y** [comment]
The suggested fix is to make all lambdas serializable in the build logic classpath, in the same way as it was done for non-serializable lambdas implementing the Gradle functional interfaces like `Action` or `Spec`. 

This gives other benefits as well: the Kotlin compiler generates some lambdas even for the `Action`/`Spec`/etc. in a way that they are wrappers around another lambda implementing `kotlin.jvm.functions.FunctionN` – and that one would not be serializable without this change.

**Comment by h0tk3y** [comment]
Closing as fixed by https://github.com/gradle/gradle/pull/23124.

**Comment by h0tk3y** [comment]
Let me reopen this issue as, in fact, the fix that we have does not actually deal with the problem, and some corner cases are still possible with non-serializable lambdas that come from custom class loaders.

We could add some more safety checks and detect classes that don't have a stable type representation, reporting them early rather than trying to serialize them and fail in deserialization.
