### ISSUE TITLE
build failed with exeption: org/fusesource/jansi/AnsiOutputStream

### ISSUE THREAD

**Issue by chill10n** [gradle/gradle#21122]
Hi. on kali (5.15.0-kali3-amd64) get an error after building and installing gradle from apt-get.

`└─# gradle --debug          
08:27:07.093 [INFO] [org.gradle.internal.nativeintegration.services.NativeServices] Initialized native services in: /root/.gradle/native

FAILURE: Build failed with an exception.

* What went wrong:
org/fusesource/jansi/AnsiOutputStream

java seems ok:

`└─# java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Debian-1, mixed mode, sharing)

i googled it but have not found any satisfying solutions. sdkman seems unavailable from my apt repos, which would have been advised to use by the gradle help docs. thus, is there still hope?

**Comment by donat** [comment]
Can you give us the output of `gradle --version`?

**Comment by chill10n** [comment]
hi. the 'gradle --version' doesnt work. i get the error above. its kind of fundamentally messed up.
i wont clean install kali and try another gradle version anytime in this life. sorry, but thanks for considering this.

**Comment by tlum** [comment]
The latest package on Ubuntu, for example, is 

```
Package: libjansi-java
Version: 2.4.0-1
Priority: optional
Section: universe/java
Source: jansi
Origin: Ubuntu

```
In v2.4.0 (Dec 3, 2020), AnsiOutputStream was moved to a new namespace

> Move IO implementation classes to a separate package  

#https://github.com/fusesource/jansi/commit/04d771c3c7f2a4c29301191e65e7ce3cdeb92918

For now we can blame whoever packaged gradle for Ubuntu - because apparently the package dependencies are wrong - but sooner or later this will need to be addressed since the code will need to be updated to reference the new namespace/package.

**Comment by adamsmd** [comment]
I had a similar issue and concur with @tlum.  Using "./gradlew" instead of the gradle distributed by Ubuntu indeed fixed it for me.

As a workaround for those who can't use "./gradlew", I noticed that "gradle ... 2>&1 | cat" seemed to get things working with the builtin version, where "..." is whatever command you want.  That idea it that prevents gradle from realizing it is connected to a terminal, and thus gradle doesn't try to load AnsiOutputStream.
