### ISSUE TITLE
Gradle plugin portal has wrong pom for de/undercouch/gradle-download-task

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#21271]
`.pom` with same coords is different on these 2 repos: 

Maven Central:
https://repo1.maven.org/maven2/de/undercouch/gradle-download-task/4.1.1/gradle-download-task-4.1.1.pom
AND
Gradle Plugin Portal:
https://plugins.gradle.org/m2/de/undercouch/gradle-download-task/4.1.1/gradle-download-task-4.1.1.pom

This can lead to dependency verification issues: 
```
 Dependency verification failed for configuration ':buildSrc:classpath'
  One artifact failed verification: gradle-download-task-4.1.1.pom (de.undercouch:gradle-download-task:4.1.1) from repository maven
  This can indicate that a dependency has been compromised. Please carefully verify the checksums.
```

`de.undercouch:gradle-download-task:4.1.1` is required for `org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.21` 

Source is at https://github.com/michel-kraemer/gradle-download-task

My request is that you either just remove `de.undercouch:gradle-download-task` from the gradle plugin portal entirely, 
OR update that pom to match maven central exactly.

Gradle 7.5

**Comment by michel-kraemer** [comment]
@yogurtearl 4.1.1 is a very old version (two years old). The issue has long been fixed in version 5. Since 5.0.5, we're even using the latest version of the `com.gradle.plugin-publish` plugin (1.0.0), which is further able to sign artifacts.

**Comment by michel-kraemer** [comment]
Unless there is a specific reason to use 4.1.1 in your build, I suggest upgrading.

**Comment by eskatos** [comment]
Hi @yogurtearl,

The pom difference is unfortunate. We won't modify the published pom on the plugin portal. The portal is considered append only and is exposed as a maven repository that folks can mirror or put behind a caching proxy.

As @michel-kraemer said, the best course of action is to upgrade given this has been fixed in subsequent versions.
Could you please open a Kotlin issue to ask the Kotlin team to upgrade?

About Gradle dependency verification, you can declare the checksums for the two pom variants.
See https://docs.gradle.org/current/userguide/dependency_verification.html#sec:trusting-several-checksums

**Comment by yogurtearl** [comment]
Thanks for the guidance. 

an `exclusiveContent` block that makes sure it only gets the pom from the desired place (maven central) helps as well.

**Comment by Goooler** [comment]
- https://youtrack.jetbrains.com/issue/KT-53822
- https://youtrack.jetbrains.com/issue/KT-50957

**Comment by yogurtearl** [comment]
related: https://github.com/michel-kraemer/gradle-download-task/issues/187
