### ISSUE TITLE
Nested Dependency not import with gradle 7.5

### ISSUE THREAD

**Issue by dilipdhankecha2530** [gradle/gradle#21433]
Basically, we want to update our gradle version from 5 to 7.5
For that we are update `distributionUrl` in `gradle-wrapper.properties`.

Now we have some library code that we already publish in our local maven repository and we want to use that as a dependency in our development for that we just implement that dependency in our build.gradle file as mentioned below.

```
 implementation('com.project:sub-module-1:1.0.0')
```

so with the help we can use the class that have above dependency but suppose `sub-module-1` project used `sub-module-2` as a dependency now if i want to use sub-module-1 into the other microservice then sub-module-2 i don't need to add as dependency that will need to add automatically.

But we are not able to use sub-module-2 classess without added into the project.

let me do some simple work,

A,B,C are microservices

Now B having A as a dependency and C having B as a dependecy the C must be able to use A's class(the published repo) with the B dependency.

But i am not able to use with gradle 7.5 is there any suggestion?

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on https://discuss.gradle.org or https://stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.

***

Have a look at [the documentation](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies) on the differences between API and implementation dependencies.
