### ISSUE TITLE
org.gradle.unsafe.configuration-cache-problems   error

### ISSUE THREAD

**Issue by wangxuyang518** [gradle/gradle#21461]
env：     

classpath 'com.android.tools.build:gradle:4.2.2'

distributionUrl=https\://services.gradle.org/distributions/gradle-6.9-bin.zip

when i run   ‘gradle --configuration-cache --info’

```java
Configuration cache is an incubating feature.
Now considering [E:\workspace\NetDemo] as hierarchies to watch
Watching the file system is enabled if available
Invalidating in-memory cache of C:\Users\01426239\.gradle\caches\journal-1\file-access.bin
Reusing configuration cache.

FAILURE: Build failed with an exception.

* What went wrong:
Could not create task ':help'.
> Could not create task of type 'Help'.
   > Class org.gradle.internal.instantiation.generator.AsmBackedClassGenerator$InvokeSerializationConstructorAndInitializeFieldsStrategy can not access a member of class org.gradle.api.
internal.AbstractTask with modifiers "protected"

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.
```

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A reproducer project can really help us track down and fix your problem quicker.  We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

You can use the following as a base for your reproducer: https://github.com/gradle/gradle-issue-reproducer

This issue will be closed after 7 days, unless you can provide more information.

You are most likely using a Java version we do not support. Could you pls. let us know what version it is?

Also, can you pls. try with Gradle 7.x, because most likely it will work.

**Comment by jjohannes** [comment]
This seems to be an issue with old Java versions (probably only outdated Java 8?).
