### ISSUE TITLE
Add `ConfigurableFileCollection#convention` method

### ISSUE THREAD

**Issue by rschmitt** [gradle/gradle#21752]
### Expected Behavior

The `Property<T>` interface defines two methods named `convention`, defined as follows:

```java
Property<T> convention(@Nullable T value);
Property<T> convention(Provider<? extends T> provider);
```

These methods are highly useful for plugin development: they allow the plugin developer to specify a clear default value for a given property, and they allow the user to override this value without first having to reset it.

### Current Behavior

`ConfigurableFileCollection` has have no direct equivalent to this feature. If a default value is present, the user must call `.setFrom()` or `.from.clear()` in order to override it (as opposed to contributing additional files to it). Additional calls may be necessary to reset things like include/exclude patterns.

### Context

This was briefly discussed [on Slack](https://gradle-community.slack.com/archives/CA745PZHN/p1661817115072489); the relevant context for my use case is that the default collection value is produced by a task that I don't want to run otherwise. I found that using a `Property<FileCollection>` works, at the expense of additional indirection that users will have to deal with; @tbroyer also proposed the following workaround:

```java
@Internal
public abstract ConfigurableFileCollection getMyProperty();

@InputFiles
/* does not need to be public */ FileCollection getActualFiles() {
    var myProperty = getMyProperty();
    if (myProperty.isEmpty()) {
      return getProject().files(…);
    }
    return myProperty;
}

// use getActualFiles() in the task action
```

**Comment by lacasseio** [comment]
I tried adding `convention` concept to a cloned API of `ConfigurableFileCollection` in Nokee, and it failed spectacularly. The issue boils down to what the convention means in the file collection. We could argue that it should behave like the convention on `ListProperty` and `SetProperty`, but regardless of the convention, those properties already have an empty iterable as values. This means that a trivial approach will be wrong:

```
def prop = objects.listProperty(String)
prop.convention(['a', 'b', 'c'])
assert prop.get() == [] // prop has an empty iterable as default value

prop.set(null) // now it will work
assert prop.get() == ['a', 'b', 'c']
```

Gradle properties have the concept of "no-value", but defaults to empty iterable.`FileCollection` doesn't have that concept. It simply defaults to an empty iterable via `setFrom()` which is basically the equivalent to `setFrom(new Object[0] {})`.

It can also be confusing when no value is present, which defaults to the convention. What happens when you add values to the collection: 1) should it append to the convention or 2) append to a new empty list which becomes the new value without overshadowing the convention, or 3) should it append to the convention which can be overwritten by setting a new value? There are good cases for all three options. It's also important to note that Gradle collection properties behave strangely:

```
def prop = objects.listProperty(String)
prop.convention('a', 'b', 'c')
prop.add('d')
assert prop.get() == ['d'] // the convention is overshadowed by the initial empty list + 'd'

prop.set(null) // clear empty list + added 'd' value
assert prop.get() == ['a', 'b', 'c'] // same as before, the prop has no-value, default to convention

prop.add('d')
assert prop.get() == <...> // an exception will be thrown because 'd' is added to no-value (not the convention)
```

I'm not against the idea. There are quite a few discussions that need to happen first before thinking of implementing a convention on file collection. Maybe some additional discussion on the current collection properties as well. In Nokee, we remove any trace of `convention` in collection APIs because of those issues.

The solution Nokee is now looking into is modelling `convention` and `value` as "value holder". A "value integrator" determines the final value and decides how to integrate the "value holders" into a single value. Each holders can be mutated individually. Additional holders can be included (i.e. convention of convention), and the integrator could be customized. We don't think this should be something users touch often, but it helps solve most use cases we encounter without adding too much complexity. It can also help clarify the intention, e.g. mutating the current value (regardless of convention vs value) vs mutating the convention or value individually.

**Comment by jbartok** [comment]
Relates to #18352

**Comment by lacasseio** [comment]
@abstratt How does the spike for the conventions address the concerns I raised earlier? The issue with `AbstractCompile.classpath` seems more like an internal functionality of the task, not something that should explicitly be introduced on `ConfigurableFileCollection`. As mentioned, when I tried adding this feature in Nokee, it was quickly rendered useless because the expectation is not easy to get right (if you can get it right in the first place). I'm assuming you will quickly fall into the rabbit hole of how to solve the following case:
```
fileCollection.convention('some/path')
fileCollection.from('some/other/path')
```

What should be the result? Using `conventionMapping` would basically be `fileCollection += files('some/other/path')`. However, according to the other `Property` implementation, using the convention would result in `fileCollection = files('some/other/path')`. Both are valid results, but neither is the correct solution. In some cases, you want the first, while in others, you want the second.

If I were to convert `AbstractCompile.classpath`, I would use an internal API for the task given that only the task and matching plugin use (or should use) the `conventionMapping`. You have more control over the integration of the values together. It would quickly unblock the current issue and allow more thinking into the `ConfigurableFileCollection#convention`. An example of why I don't vote for this API is that I refactored Nokee's model to avoid requiring this API, and the refactored API is much cleaner.

**Comment by abstratt** [comment]
Hi @lacasseio, 

[BTW: not sure if your comments are in any way based on the current state of #27134, which is not meant yet as a solution for this issue. Please disregard that branch for now.] 

One approach we are considering is to have conventions as a `Property` thing, and if you want convention for some mutable object, you need to first obtain its `Property` view to access the API for setting conventions (similar to how immutable objects often expose a `Provider` view).

IIUC, your point is about how an incremental mutation should behave in the presence of a convention. I agree with you that the desired behavior may depend on the use case. That is mostly under consideration in the context of #18352 - but is relevant here, as we want a similar solution for both collection/composite properties and configurable file collections. 

From your last paragraph, I am not sure what you meant. Do you mean Gradle does not to expose an API for setting conventions for file collections at this time (and do you have the same view to composite properties such as `ListProperty` as well)

**Comment by rschmitt** [comment]
Sorry, I don't remember any more. I may have been thinking of the `PatternFilterable` methods on `ConfigurableFileTree`.

**Comment by martinbonnin** [comment]
For the record, the Slack discussion mentioned in the original description is gone from Slack but still available on linen [here](https://www.linen.dev/s/gradle-community/t/2450281/is-it-bad-form-to-define-a-property-lt-filecollection-gt-ext#bcda524c-4cd8-4723-8e93-96f59540f120).

I came here looking for the exact same thing and glad `ConfigurableFileCollection.convention()` is now a thing 🎉 Looking forward to 8.7
