### ISSUE TITLE
JSON output of gradle dependencies

### ISSUE THREAD

**Issue by h4sh5** [gradle/gradle#21894]
### Expected Behavior

`gradle dependencies` should have an option to return a JSON formatted output of all dependencies. 

### Current Behavior

The current tree-like output is not easy to programmatically parse/search.

### Context

I am trying to get a programmatically usable dependency graph of Gradle build files. This is important for understanding the software supply chain and producing SBOM (Software Bill of Materials). The current output is unusable programmatically.

**Comment by 2013kaa** [comment]
@h4sh5 i love you))))this is what i'm waiting for my SCA!

**Comment by roanosullivan-work** [comment]
I'm very surprised this doesn't already exist

**Comment by kota65535** [comment]
I've created a plugin for doing this task, but it should be included in project-report plugin.
https://plugins.gradle.org/plugin/io.github.kota65535.dependency-report

**Comment by 2013kaa** [comment]
@kota65535 this is a wonderful gift for the new year!)) I'll try it a little later, but it looks super!

**Comment by sschuberth** [comment]
> I've created a plugin for doing this task, but I think it should be included in [project-report](https://docs.gradle.org/current/userguide/project_report_plugin.html) plugin. https://plugins.gradle.org/plugin/io.github.kota65535.dependency-report

I absolutely agree, esp. as the HTML report created by `HtmlDependencyReportTask` actually already embeds a JSON report created by the [JsonProjectDependencyRenderer](https://github.com/gradle/gradle/blob/master/subprojects/diagnostics/src/main/java/org/gradle/api/reporting/dependencies/internal/JsonProjectDependencyRenderer.java). So it should be rather straight forward to create a `JsonDependencyReportTask`.

BTW, the whole topic is also related to https://github.com/gradle/build-tool-roadmap/issues/42.

**Comment by sschuberth** [comment]
> So it should be rather straight forward to create a `JsonDependencyReportTask`.

@kota65535, as your plugin (Thank you!) basically does just that, would you be interested in contributing a `JsonDependencyReportTask` analog to `HtmlDependencyReportTask` to Gradle directly?

**Comment by kota65535** [comment]
@sschuberth Yes, I'm very interested in it.
How should I proceed? I'm a novice to contribute to such a large OSS project.

**Comment by sschuberth** [comment]
> How should I proceed? I'm a novice to contribute to such a large OSS project.

See https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md for a good starting point.

**Comment by jvandort** [comment]
I just saw the related PR -- please see my response there: https://github.com/gradle/gradle/pull/25592#issuecomment-1618878728

In general, I do not think we want to support a JSON API in addition to our existing Kotlin/Groovy/Java APIs -- particularly since we have no way of managing changes to that API as Gradle versions progress and things need to be changed/removed. We have a process for this for JVM types, and that is through our standard deprecation process. 

The existing `JsonProjectDependencyRenderer` was never intended to produce a stable structure for programmatic consumptions by third-parties. _any_ attempt to start producing JSON files for programmatic consumption by users would require planning -- particularly to ensure we have methods to modify and update the format of these output JSON files between Gradle releases.

**Comment by kota65535** [comment]
@jvandort Does this plugin provide a task that outputs project dependencies in JSON format?
https://github.com/gradle/github-dependency-graph-gradle-plugin

**Comment by sschuberth** [comment]
> @jvandort Does this plugin provide a task that outputs project dependencies in JSON format? 

It [does](https://github.com/gradle/github-dependency-graph-gradle-plugin/issues/34#issuecomment-1621207771), though its [JSON format is solely meant](https://github.com/gradle/github-dependency-graph-gradle-plugin/issues/34#issuecomment-1626880142) for consumption by the GitHub [Dependency Submission API](https://docs.github.com/en/rest/dependency-graph/dependency-submission?apiVersion=2022-11-28).

**Comment by tsjensen** [comment]
I think we should not invent a custom format, but instead output a proper [SBOM](https://www.ntia.gov/page/software-bill-materials).  
The easiest format for that is [CycloneDX](https://cyclonedx.org/docs/1.5/json/). It's still JSON, but in a way that other tools natively understand. There's a [Java library](https://github.com/CycloneDX/cyclonedx-core-java) to create it.

**Comment by sschuberth** [comment]
> I think we should not invent a custom format, but instead output a proper [SBOM](https://www.ntia.gov/page/software-bill-materials).

There was a time when I would have agreed to that. But the problem with SBOMs is that their concrete contents are not well-defined and vary by context (e.g. license vs security compliance). While the NIST came up with [The Minimum Elements
For a Software Bill of Materials (SBOM)](https://www.ntia.doc.gov/files/ntia/publications/sbom_minimum_elements_report.pdf), these are *so minimal* that the aforementioned use-cases cannot be served, e.g. because copyright information is missing.

> The easiest format for that is [CycloneDX](https://cyclonedx.org/docs/1.5/json/). It's still JSON, but in a way that other tools natively understand. There's a [Java library](https://github.com/CycloneDX/cyclonedx-core-java) to create it.

As someone who has worked a lot with SBOMs in general and SPDX and CycloneDX in general (in the context of [ORT](https://github.com/oss-review-toolkit/ort)), I can say that from my point of view it's better to let the build system / package manager (here: Gradle) output as much information as it has, rather than only writing out as much information as required at minimum by an SBOM format. Conversion tools could then use only the required information from the "complete" output to create an SBOM for a specific use-case / context.

**Comment by sschuberth** [comment]
> I think we should not invent a custom format, but instead output a proper [SBOM](https://www.ntia.gov/page/software-bill-materials).

BTW, Cargo currently has a [similar discussion](https://internals.rust-lang.org/t/pre-rfc-cargo-sbom/19842) going on.

**Comment by tsjensen** [comment]
Fully agree! But CycloneDX, for example, does not really limit what we put into an SBOM. At least all the information I can imagine Gradle to have could be expressed just fine.

Then we would still benefit from using a well-known format rather than some home-cooked one.

> BTW, Cargo currently has a similar discussion going on.

In the not-so-distant future, *all* build tools (or rather, package managers) will have an `sbom` command to output what they know about the dependencies in use. 🧙‍♂️

**Comment by cobexer** [comment]
Following up on [Justins comment](https://github.com/gradle/gradle/issues/21894#issuecomment-1618884212) we are closing this issue.

If you are interested in SBOM support please file a separate feature request.

**Comment by GregJohnStewart** [comment]
I know I'm terribly late to the party, but this is a pretty dissapointing shortcoming to not have this out of the box :(

Writing a script to scan projects and their dependencies, mixed gradle/maven. Also don't have an option to tweak the gradle projects.

I hate myself for this argument, but Maven supports this out of the box, and I'm really really missing this in Gradle
