### ISSUE TITLE
Update 4.0 release notes for gradle-script-kotlin to version 0.9.1

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#2205]
The release notes for 4.0 say that version 0.9.0 of the gradle-script-kotlin support is included. That should be changed to version 0.9.1. The build appears to use that version so it looks like just the release notes need to be updated.

**Comment by eskatos** [comment]
Thanks for reporting @baron1405 
Fixed by c0ae9491e61d62c2f203c143cade16c06df3d5f5

**Comment by bamboo** [comment]
An update: the `release` branch still contains `0.9.0` as can be seen [here](https://github.com/gradle/gradle/blob/daa1348e0e5dd866c3084f0f3c3ae339c3a5f96b/build.gradle#L290)
 and so I reverted the release note change in 78d6b5b1e5cdb3dd4e233eb2f2e2bf721c53ca9e.

`master` was upgraded to `0.9.1` to unblock the next release due to an internal API change but both versions are virtually the same.

I hope that clarifies the situation. Thanks, folks!
