### ISSUE TITLE
Java Compiler regression in 4.0-rc-1

### ISSUE THREAD

**Issue by fkorotkov** [gradle/gradle#2209]
Seems there is a regression in Java compiler's classpath. Here is an example: https://github.com/fkorotkov/gradle-4.0-rc-1-issue

You can check Travis to see it's working with 3.5 but failing with 4.0-rc-1: https://travis-ci.org/fkorotkov/gradle-4.0-rc-1-issue

Might be related to https://github.com/gradle/gradle/issues/2207

**Comment by bmuschko** [comment]
Thanks for providing the example project. Here's what I believe happened:

1. You provide Guava version 18.0. That is reflected in the dependency graph. Version 18.0 wins over "younger" version of that library in your dependency graph.

```
$ ./gradlew dI --dependency com.google.guava:guava --configuration compile
Parallel execution is an incubating feature.

> Task :dependencyInsight
com.google.guava:guava:18.0 (conflict resolution)
\--- compile

com.google.guava:guava:r08 -> 18.0
\--- com.jolbox:bonecp:0.7.1.RELEASE
     \--- org.apache.hive:hive-metastore:0.12.0-cdh5.1.3
          +--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3
          |    \--- compile
          +--- org.apache.hive:hive-service:0.12.0-cdh5.1.3
          |    \--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3 (*)
          \--- org.apache.hive:hive-exec:0.12.0-cdh5.1.3
               +--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3 (*)
               \--- org.apache.hive:hive-service:0.12.0-cdh5.1.3 (*)

com.google.guava:guava:11.0.2 -> 18.0
+--- org.apache.hive:hive-metastore:0.12.0-cdh5.1.3
|    +--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3
|    |    \--- compile
|    +--- org.apache.hive:hive-service:0.12.0-cdh5.1.3
|    |    \--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3 (*)
|    \--- org.apache.hive:hive-exec:0.12.0-cdh5.1.3
|         +--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3 (*)
|         \--- org.apache.hive:hive-service:0.12.0-cdh5.1.3 (*)
\--- org.apache.hive.shims:hive-shims-common:0.12.0-cdh5.1.3
     +--- org.apache.hive:hive-shims:0.12.0-cdh5.1.3
     |    +--- org.apache.hive:hive-exec:0.12.0-cdh5.1.3 (*)
     |    +--- org.apache.hive:hive-metastore:0.12.0-cdh5.1.3 (*)
     |    +--- org.apache.hive:hive-serde:0.12.0-cdh5.1.3
     |    |    +--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3 (*)
     |    |    \--- org.apache.hive:hive-metastore:0.12.0-cdh5.1.3 (*)
     |    \--- org.apache.hive:hive-common:0.12.0-cdh5.1.3
     |         +--- org.apache.hive:hive-jdbc:0.12.0-cdh5.1.3 (*)
     |         \--- org.apache.hive:hive-serde:0.12.0-cdh5.1.3 (*)
     \--- org.apache.hive.shims:hive-shims-common-secure:0.12.0-cdh5.1.3
          +--- org.apache.hive:hive-shims:0.12.0-cdh5.1.3 (*)
          \--- org.apache.hive.shims:hive-shims-0.23:0.12.0-cdh5.1.3
               \--- org.apache.hive:hive-shims:0.12.0-cdh5.1.3 (*)

(*) - dependencies omitted (listed previously)
```

2. Your dependency `org.apache.hive:hive-exec:0.12.0-cdh5.1.3` include Guava classes e.g. `com.google.common.base.Stopwatch`. I think we can agree on the fact that is poor practice as there cannot be dependency conflict resolution. If includes in a JAR then these classes should be shaded.

3. With 4.0 the dependency order might have changed. Keep in mind that dependency order on the classpath is not necessarily deterministic. In earlier versions of Gradle it might be the case that the Guava JAR was resolved first and therefore this issue didn't crop up but was waiting to be exposed.

Here are your options:

- Ask the Hive project to shaded the Guava classes.
- Try to see if you really need that dependency. If you don't then simply exclude it.
- Try to use a different version of the dependency that doesn't bundle the Guava classes.
- Try to mess with the classpath and try to force an ordering. I personally would only consider it as the last resort.

Hope this helps.

**Comment by fkorotkov** [comment]
Yeah. I found this nonsense in `hive-jdbc`, already asked a corresponding team to upgrade it but wanted to let you know about such regression. It might be a pretty big deal.

So it's not a bug but a feature? 😅 Then we can close the issues. 

But if classpath is deterministic then how can be sure Gradle builds are reproducible?

**Comment by bmuschko** [comment]
I was just corrected by a team member that the classpath is ordered. My bet. Either way it might be that the order changed between 3.5 and 4.0 but is still deterministic for that specific version.

**Comment by bmuschko** [comment]
This output compares the dependency order between Gradle 3.5 and 4.0-rc1. You see the change likely because of [intended dependency ordering](https://docs.gradle.org/4.0-rc-1/release-notes.html#changes-to-dependency-ordering).

**Gradle 3.5:**

[hive-jdbc-0.12.0-cdh5.1.3.jar, guava-18.0.jar, hive-common-0.12.0-cdh5.1.3.jar, hive-metastore-0.12.0-cdh5.1.3.jar, hive-serde-0.12.0-cdh5.1.3.jar, hive-service-0.12.0-cdh5.1.3.jar, hive-exec-0.12.0-cdh5.1.3.jar, commons-logging-1.1.3.jar, httpclient-4.2.5.jar, httpcore-4.2.5.jar, slf4j-api-1.7.5.jar, slf4j-log4j12-1.7.5.jar, hive-shims-0.12.0-cdh5.1.3.jar, commons-cli-1.2.jar, commons-compress-1.4.1.jar, bonecp-0.7.1.RELEASE.jar, derby-10.4.2.0.jar, datanucleus-api-jdo-3.2.1.jar, datanucleus-core-3.2.2.jar, datanucleus-rdbms-3.2.1.jar, jdo-api-3.0.1.jar, antlr-runtime-3.4.jar, libfb303-0.9.0.jar, avro-1.7.5-cdh5.1.3.jar, jetty-6.1.26.cloudera.2.jar, jetty-util-6.1.26.cloudera.2.jar, hive-ant-0.12.0-cdh5.1.3.jar, parquet-hadoop-bundle-1.2.5-cdh5.1.3.jar, commons-httpclient-3.0.1.jar, commons-io-2.4.jar, ST4-4.0.4.jar, ant-1.9.1.jar, zookeeper-3.4.5-cdh5.1.3.jar, groovy-all-2.1.6.jar, stax-api-1.0.1.jar, hive-shims-common-0.12.0-cdh5.1.3.jar, hive-shims-common-secure-0.12.0-cdh5.1.3.jar, hive-shims-0.23-0.12.0-cdh5.1.3.jar, xz-1.0.jar, jta-1.1.jar, stringtemplate-3.2.1.jar, antlr-2.7.7.jar, jackson-core-asl-1.9.13.jar, jackson-mapper-asl-1.9.13.jar, paranamer-2.3.jar, snappy-java-1.0.5.jar, servlet-api-2.5-20081211.jar, velocity-1.5.jar, junit-3.8.1.jar, ant-launcher-1.9.1.jar, jline-0.9.94.jar, commons-collections-3.1.jar, oro-2.0.8.jar, commons-codec-1.6.jar, commons-lang-2.5.jar, log4j-1.2.17.jar, libthrift-0.9.0.jar]

**Gradle 4.0-rc1:**

[hive-jdbc-0.12.0-cdh5.1.3.jar, hive-service-0.12.0-cdh5.1.3.jar, hive-exec-0.12.0-cdh5.1.3.jar, hive-metastore-0.12.0-cdh5.1.3.jar, bonecp-0.7.1.RELEASE.jar, hive-serde-0.12.0-cdh5.1.3.jar, hive-common-0.12.0-cdh5.1.3.jar, hive-shims-0.12.0-cdh5.1.3.jar, hive-shims-0.23-0.12.0-cdh5.1.3.jar, hive-shims-common-secure-0.12.0-cdh5.1.3.jar, hive-shims-common-0.12.0-cdh5.1.3.jar, guava-18.0.jar, commons-httpclient-3.0.1.jar, libfb303-0.9.0.jar, libthrift-0.9.0.jar, httpclient-4.2.5.jar, commons-logging-1.1.3.jar, httpcore-4.2.5.jar, hive-ant-0.12.0-cdh5.1.3.jar, slf4j-log4j12-1.7.5.jar, avro-1.7.5-cdh5.1.3.jar, slf4j-api-1.7.5.jar, commons-cli-1.2.jar, velocity-1.5.jar, commons-lang-2.5.jar, zookeeper-3.4.5-cdh5.1.3.jar, log4j-1.2.17.jar, commons-compress-1.4.1.jar, derby-10.4.2.0.jar, datanucleus-api-jdo-3.2.1.jar, datanucleus-core-3.2.2.jar, datanucleus-rdbms-3.2.1.jar, jdo-api-3.0.1.jar, ST4-4.0.4.jar, antlr-runtime-3.4.jar, commons-codec-1.6.jar, jetty-6.1.26.cloudera.2.jar, jetty-util-6.1.26.cloudera.2.jar, parquet-hadoop-bundle-1.2.5-cdh5.1.3.jar, commons-io-2.4.jar, ant-1.9.1.jar, groovy-all-2.1.6.jar, stax-api-1.0.1.jar, xz-1.0.jar, jta-1.1.jar, stringtemplate-3.2.1.jar, antlr-2.7.7.jar, jackson-mapper-asl-1.9.13.jar, jackson-core-asl-1.9.13.jar, paranamer-2.3.jar, snappy-java-1.0.5.jar, servlet-api-2.5-20081211.jar, jline-0.9.94.jar, junit-3.8.1.jar, ant-launcher-1.9.1.jar, commons-collections-3.1.jar, oro-2.0.8.jar]

**Comment by fkorotkov** [comment]
@bmuschko does it mean that Gradle now does DFS instead of BFS when constructing list of dependencies?

**Comment by bmuschko** [comment]
@adammurdoch Would you mind commenting on this change? We might have to be more specific in the release notes about what "consumer first" means.

**Comment by adammurdoch** [comment]
All 'consumer-first' means is that if A depends on B, then A always appears before B in the result (unless there is a cycle that includes A and B). The only other guarantee that Gradle offers is that a particular version of Gradle will always return a given dependency graph in a deterministic and consistent, but arbitrary, order. We do try hard to keep the order stable, so as to not break things, but sometimes we will change it on a major release.

**Comment by bmuschko** [comment]
@fkorotkov I hope our responses could answer your questions. Would you agree that the issue can be closed?
