### ISSUE TITLE
Adding `_` to a project name, causes `TYPESAFE_PROJECT_ACCESSORS` to silently fail to generate an accessor

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#22180]
Adding `_` to a project name, causes `TYPESAFE_PROJECT_ACCESSORS` to silently fail to generate an accessor

### Expected Behavior

Ideally, this "just works" and generates an accessor. 
else, at a minimum, generate an error rather than silently doing nothing (not generating an accessor)

in `settings.gradle.kts`
```kotlin
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("foo")
project(":foo").name = "foo_renamed"
```

### Current Behavior

This just silently fails to generate an access for `foo_renamed`

in `settings.gradle.kts`
```kotlin
enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("foo")
project(":foo").name = "foo_renamed"
``` 

### Your Environment
gradle 7.5.1

related: https://github.com/gradle/gradle/issues/18971

**Comment by ov7a** [comment]
Sorry for the late reply.

See the [relevant documentation](https://docs.gradle.org/current/userguide/declaring_dependencies_basics.html#sec:type-safe-project-accessors):
> Project accessors are based on project paths. For instance, the path :commons:utils:some:lib becomes projects.commons.utils.some.lib, while kebab-case (some-lib) and snake-case (some_lib) are converted to camel case: projects.someLib.

Note that it has been in the docs [since 7.0.0](https://github.com/gradle/gradle/blob/v7.0.0/subprojects/docs/src/docs/userguide/dep-man/01-core-dependency-management/declaring_dependencies.adoc).
