### ISSUE TITLE
4.0 rc1 hang with jarjar plugin

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#2222]
The following build.gradle seems to hang with 4.0 rc1. It used to work in 4.0 M1. Running `build`, it hangs resolving the files of `packaging` configuration (I stopped it after 4 minutes, there's no useful info in `--info`).

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'org.anarres.jarjar:jarjar-gradle:1.0.0'
    }
}
repositories {
    jcenter()
}
apply plugin: 'java'
apply plugin: 'org.anarres.jarjar'
ext {
    protobufVersion = '3.0.0'
    grpcVersion = '1.0.3'
    // We need to package in our own copy of netty dependencies, since Studio
    // can manually update its own netty library separately from us.
    // See also: https://mvnrepository.com/artifact/io.grpc/grpc-netty/1.0.3
    nettyVersion = '4.1.6.Final'
}
configurations {
    packaging
}
dependencies {
    packaging "com.google.protobuf:protobuf-java:$protobufVersion"
    packaging "io.grpc:grpc-auth:$grpcVersion"
    packaging "io.grpc:grpc-context:$grpcVersion"
    packaging "io.grpc:grpc-core:$grpcVersion"
    packaging "io.grpc:grpc-netty:$grpcVersion"
    packaging "io.netty:netty-handler-proxy:$nettyVersion"
    packaging "io.netty:netty-codec-http2:$nettyVersion"
    packaging "io.netty:netty-transport:$nettyVersion"
    packaging "io.netty:netty-codec-socks:$nettyVersion"
    packaging "io.netty:netty-codec-http:$nettyVersion"
    packaging "io.netty:netty-handler:$nettyVersion"
    packaging "io.netty:netty-buffer:$nettyVersion"
    packaging "io.netty:netty-resolver:$nettyVersion"
    packaging "io.netty:netty-codec:$nettyVersion"
    packaging "io.netty:netty-common:$nettyVersion"
    packaging "io.grpc:grpc-okhttp:$grpcVersion"
    packaging "io.grpc:grpc-protobuf:$grpcVersion"
    packaging "io.grpc:grpc-protobuf-lite:$grpcVersion"
    packaging "io.grpc:grpc-protobuf-nano:$grpcVersion"
    packaging "io.grpc:grpc-stub:$grpcVersion"
    compile "com.google.protobuf:protobuf-java:$protobufVersion"
    compile "io.grpc:grpc-all:$grpcVersion"
}
jarjar.repackage('jarjarLibs') {
    destinationName = archivesBaseName + '-' + version + '-jarjar.jar'
    from configurations.packaging
    from sourceSets.main.output.classesDirs
    classRename 'com.google.protobuf.**', 'com.google.protobuf3jarjar.@1'
    classRename 'io.netty.**', 'io.nettyjarjar.@1'
}
artifacts {
    archives(jarjarLibs.destinationPath) {
        name 'ProfilerServerApi'
        type 'jar'
        builtBy jarjarLibs
    }
}

**Comment by ghale** [comment]
The issue here is that the 'org.anarres.jarjar` plugin contains a task that is exposing a filtered view of the source files of the task as an output.  The build above then adds a configuration as part of the source files of the task (which is totally reasonable).  When we are traversing the task graph, we are resolving the outputs of the task which is then in turn causing that configuration to be resolved.

Looking at the implementation of that task, it really seems wrong to me that they would set up this property as a task output.  In fact, I can't imagine a use case where a resolved configuration would ever be a task output.  I've opened up an [issue with the plugin author](https://github.com/shevek/jarjar/issues/7) suggesting how this task should be improved.

On the Gradle side, we should handle this more gracefully and not deadlock.  https://github.com/gradle/gradle/pull/2253 seeks to address this by failing fast when we detect a situation that will lead to this sort of deadlock.

**Comment by oehme** [comment]
The fix is now on `release`.
