### ISSUE TITLE
Test resources not copied to output folder in some cases

### ISSUE THREAD

**Issue by guillerodriguez** [gradle/gradle#22296]
In some cases, not all test resources are copied to the build/resources/test folder.

See this SO question: https://stackoverflow.com/questions/73934745/gradle-not-copying-all-test-resources-to-output-dir

### Expected Behavior

When I run the `test` or `processTestResources` task, all test resources should be copied to the output folder.

### Current Behavior

Only a subset of files are copied: resources under foo/ are copied; resources under hello/ are not copied.

The problem is gone if I remove [this line](https://github.com/guillerodriguez/gradle-test-resources-issue/blob/c203138857a91fda916aff7b5ccb5b1310e0872a/build.gradle#L18). Please refer to the linked SO question for the details.

### Context

This is just a simplified tests case; in the original project, test resources are not being copied to the output folder and this makes unit tests fail.

### Steps to Reproduce 

https://github.com/guillerodriguez/gradle-test-resources-issue

### Your Environment

Issue can be reproduced with GH actions; see linked project.

**Comment by guillerodriguez** [comment]
Sorry, wrong repo URL. Fixed.

**Comment by eskatos** [comment]
Could you try changing the offending line to:
```groovy
    from(processTestResources) { include 'foo/' }
```

The rationale is that `from processTestResources { include 'foo/' }` configures the `processTestResources` tasks instead.

**Comment by guillerodriguez** [comment]
> Could you try changing the offending line to:
> 
> ```groovy
>     from(processTestResources) { include 'foo/' }
> ```
> 
> The rationale is that `from processTestResources { include 'foo/' }` configures the `processTestResources` tasks instead.

Yes, that fixes the issue. I had already noticed this by (blindly) playing around, but didn't understand why it worked (actually I still don't understand -- why do the parentheses make a difference?)

Also, is this documented anywhere? In the documentation for the copy task, section "[File copying in depth](https://docs.gradle.org/current/userguide/working_with_files.html#sec:copying_files)" explains how a task argument can be passed to `from`, and shows some examples that do not include parentheses (see example 33). Then the section about "[Filtering files](https://docs.gradle.org/current/userguide/working_with_files.html#filtering_files)" which talks about `include` and `exclude` does not mention any of this either.

**Comment by ljacomet** [comment]
I believe this is related to Groovy precedence when resolving the expression.

Without the parenthesis, Groovy interprets everything after `from` as the argument.
And so it fetches the reference to the `processTestResources` task, applies the configuration closure to it, and then passes the result to `from`.

So the end result is that you configured in-line the `processTestResources` instead of configuring the `from`.

Adding the parenthesis changes the meaning by clearly indicating that the result of calling `from` with a task is what is to be configured.

Closing the issue as this is more a Groovy specific thing that a Gradle issue, although I agree it is confusing when you encounter it.

**Comment by guillerodriguez** [comment]
OK, thank you for the clarification.

Perhaps the documentation for the copy task could mention this pitfall and/or include some examples.
