### ISSUE TITLE
maps for output files are not working deferredly

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#2237]
I have a task like

```
task generateDdlScratch(type: Xslt) {
   ...
   outputs.files(fileTree("$buildDir/db-scripts/") { include '**DDL**' }).withPropertyName 'outputFiles'
   ...
}
```

and some task that depends on its output files like 

```
task distScratchDatabase(type: Copy) {
   from generateDdlScratch
   into 'dist/db-scripts/'
}
```

This works fine. If the worktree is clean and i call `distScratchDatabase`, the files are generated and copied properly.

Now I upgraded Gradle and wanted to use a `Map` for `outputs.files` to be able to use task output caching somewhen in the future. Because of this I changed the task to

```
task generateDdlScratch(type: Xslt) {
   ...
   outputs.files { generateOutputFilesMap fileTree("$buildDir/db-scripts/") { include '**DDL**' } }.withPropertyName 'outputFiles'
   ...
}
```

with having everything in a closure so that the evaluation is done late as was the case with the `fileTree`. `generateOutputFilesMap` basically generates a unique property name per file and builds the map. The code is

```
ext.generateOutputFilesMap = { outputFiles ->
   def outputFilesEntries = project.files(outputFiles).collect {
      ["outputFile_${rootProject.relativePath(it).replaceAll(/\W/, '_')}", it]
   }
   if (outputFilesEntries.countBy { it[0] }.any { it.value != 1 }) {
      throw new ConfigurationException("Implementation of ${getClass().name - ~/_Decorated$/} is erroneous.\nMultiple output files with the same property name were calculated.\nPlease report to build system maintainers.")
   }
   outputFilesEntries.collectEntries()
}
```

Unfortunately this does not work like expected. If the output files are already there from a previous run, everything works fine. But if the files are not there yet, they are generated properly, but nothing is copied and instead the `distScratchDatabase` task is skipped due to `NO-SOURCE`. And even if it would not be skipped because other things are also copied, the newly generated files still would not be copied alongside.

Also this didn't change the situation:

```
task distScratchDatabase(type: Copy) {
   from { generateDdlScratch }
   into 'dist/db-scripts/'
}
```

**Comment by wolfs** [comment]
Would it be possible to use a different output directory for the `DDL` files instead of putting everything into one directory? This would make the build script much more simple.
Note that the task will never work with task output caching with this kind of dynamic outputs. The output property file names need to be known _before_ the task starts executing, since this is what we want to avoid. If we only know the output property file names after the task executed we can never match that up with a cached result.

**Comment by Vampire** [comment]
Hm, too bad then, because even if I would generate to different directories, the files still have names generated at runtime by the XSLT script depending on various conditions and I didn't want to duplicate the name calculation in the Gradle scripts.

Why wouldn't output files caching will not work? If you postulate that the same set of inputs (files + properties) will produce the same set of output files, then you could take the generated output files from a previous invocation if the inputs match. Why are the outputs needed explicitly anyway? Output caching should only be used on tasks that produce the same set of output files if the same set of inputs is given. In that case, it is enough to record the inputs, execute the task, record the outputs and stuff the outputs into the cache, with the inputs as key.

But anyway, even if there is some detail I'm not aware of currently with output caching, I didn't enable output caching anyway, but only returned the maps in case we use it in the future. The main problem is why the files are not resolved late properly.

**Comment by wolfs** [comment]
What I was trying to say is that, instead of using
```groovy
task generateDdlScratch(type: Xslt) {
   ...
   outputs.files(fileTree("$buildDir/db-scripts/") { include '**DDL**' }).withPropertyName 'outputFiles'
   ...
}
```

you should use
```groovy
task generateDdlScratch(type: Xslt) {
   ...
   outputs.dir("$buildDir/db-scripts/ddl").withPropertyName 'outputFiles'
   ...
}
```

This adds all the files in the directory as outputs to the task, works well with task output caching and is less verbose.

**Comment by wolfs** [comment]
Regarding your question why we need the outputs for task output caching:
We do not need the output files but the _names_ of the output file properties. Since we need to match up the outputs from the cached execution and unpack them into the new locations given by the current execution.
If a task has two output properties (for example an `html` report and and `xml` report) we need to know which output file location corresponds to each so we can expand them into the right directory.
This is why `outputs.files` is not supported for task output caching if no name for the output property is provided.
Note that you do not need to provide a name for each individual file in the output but for each logic output file property.

**Comment by Vampire** [comment]
Hm, good point about using `dir` instead of `files` could solve the issue. I'll check whether we can change this. Having the same output folder for different task alwas is a bad thing. Just look at `compileJava` and `compileGroovy` and the auto-cleanup. :-D

> Note that you do not need to provide a name for each individual file in the output but for each logic output file property.

I didn't get that. When using `outputs.files`, isn't then each individual file the logic output file property that needs naming? Or did you mean when e. g. using `outputs.dir` instead?

**Comment by wolfs** [comment]
>> Note that you do not need to provide a name for each individual file in the output but for each logic output file property.

> I didn't get that. When using outputs.files, isn't then each individual file the logic output file property that needs naming? Or did you mean when e. g. using outputs.dir instead?

Yes, you are right. When using `output.files` then each individual file is also an output file property. This is why you would need a name for each individual file. But you would need those locations before you pull the results from the cache since Gradle would then try to unpack each individual file to the individual provided location per file.

**Comment by Vampire** [comment]
Why can't it just use the path relative to the project directory that was there in the task-filling Gradle execution?

**Comment by wolfs** [comment]
This would break caching if you just change the output directory of the task or the structure of the project.

**Comment by Vampire** [comment]
True, but it would work better out-of-the-box. :-D

Anyway, I appreciate the information about the output caching, but still, shouldn't the files in my setup be resolved lazily like without the map, completely independent of the file output caching.

**Comment by wolfs** [comment]
Yes, they should. I'll need to wrap my head around it.

**Comment by Vampire** [comment]
Ok, great, happy wrapping. :-D

**Comment by wolfs** [comment]
I did enough wrapping now.
The reason why the approach does not work is that Gradle needs to know the definition of the task outputs before the task starts to execute. The definition of task outputs can be for example
- all files in a certain directory (`dir('build/some-dir')`)
- a filtered file collection of a certain directory (`files(fileTree('build/some-dir') { include 'some*.*' })`).

This is important since Gradle needs to know the output files for the up-to-date checks which happen just before the task would execute. When defining outputs dynamically based on the contents of a directory then the logic does not work as expected - output properties (and not just files) would be added during the execution of the task.

Does this answer explain the behavior or are you having more questions?

**Comment by Vampire** [comment]
But it does work like that when not using a `Map`. Of course the outputs change during the execution of a task. If you have a clean checkout, then there are no output files. After you have run the task, there are output files. So you would request the output before the task execution and compare them with the last outputs. If they are different, you execute the task and then again request the output to record what is there now and compare it to the situation when the task is run the next time. That is exactly how it should work and how it actually work right now if you don't use a `Map`. If you use a `Map` though, this semantic changes and you have to know which files will be produced up-front, as they are determined before the task is run and then remembered throughout the build. At least the behaviors should be consistent, shouldn't they? And I strongly opt for the current way to be the consistent behavior that should be used in both cases.

**Comment by wolfs** [comment]
Like I tried to explain above: Gradle supports that the output files of a single output property change between before and after execution. It does not support changing the declarations of output properties after execution started.
Without the `Map`, you are declaring _one_ output property called `outputFiles` which is a `FileTree` of a certain definition. This property is evaluated before and after the task executes and yields different results.
With the `Map`, you are declaring _many_ (number of output files existing) output properties with the individual file names as property names, each one pointing to a single file. Let's assume one of those output files called `TableDDL.sql` exists before the execution of the task. Then you would declare one output property called `outputFile_TableDDL_sql` pointing to `TableDDL.sql`. These are now the defined output properties of the task and any changes to those (`outputFile_TableDDL_sql`) won't be picked up as soon as execution of the task started. Changes to the single file `TableDDL.sql` will be picked up, though.

Is it now clearer?

**Comment by Vampire** [comment]
Hm, I see. Thanks for the explanation.
