### ISSUE TITLE
Introduce a mechanism to apply shared build logic to all projects in a manner compatible with Isolated Projects

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#22514]
When [Isolated Projects](https://gradle.github.io/configuration-cache/#project_isolation) is enabled, APIs that currently allow applying shared build logic to multiple projects (`allprojects`, `subprojects`, `gradle.beforeProject`, etc) become [problematic](https://github.com/gradle/gradle/issues/21485).

At this point we are interested in collecting use-cases / requirements so we can come up with a satisfactory solution.

**Comment by Tapchicoma** [comment]
One of the use-case is applying convention plugin with project common configuration to all projects

Another use-case is to apply external plugin to all/subprojects.

**Comment by melix** [comment]
So here are a few use cases in Micronaut:

- [adding a sanity check to verify that project names follow some convention](https://github.com/micronaut-projects/micronaut-build/blob/690cfa18f2f1321a20045e35426fc784045d5bff/src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java#L57-L68)
- [setting an ext property for backwards compatibility](https://github.com/micronaut-projects/micronaut-build/blob/690cfa18f2f1321a20045e35426fc784045d5bff/src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java#L49-L54)
- [conventionally set project group/version](https://github.com/micronaut-projects/micronaut-build/blob/690cfa18f2f1321a20045e35426fc784045d5bff/src/main/java/io/micronaut/build/MicronautSharedSettingsPlugin.java#L74-L86)
- [introspecting projects based on plugins applied](https://github.com/micronaut-projects/micronaut-build/blob/04437de6e6122ea256e125e370ee04e3ada6f90a/src/main/groovy/io/micronaut/build/MicronautBomPlugin.java#L164-L184)

There are probably more use cases, those are the ones I have in mind.

**Comment by martinbonnin** [comment]
Apollo uses `rootProject` to [register a global task](https://github.com/apollographql/apollo-kotlin/blob/fb51dafaa4b02a55b6926546927d176078513543/libraries/apollo-gradle-plugin-external/src/main/kotlin/com/apollographql/apollo3/gradle/internal/DefaultApolloExtension.kt#L273) that does some sanity checks accross all projects sharing the same GraphQL schema.

**Comment by cloudshiftchris** [comment]
Sharing a few project isolation use cases ([Slack discussion](https://gradle-community.slack.com/archives/CA745PZHN/p1667928119871619)).

As context these are predicated on an environment that consists of a custom Gradle distribution (with init script and settings plugin), and a core convention plugin that sets up projects (largely addresses the "conventions for convention plugins" issue of repeating build logic per-project in a silo'd convention plugin).

1. Consistently setting project version and group across modules, from what is set in the root project.  

```
    group = rootProject.group
    version = rootProject.version
```

The use of rootProject is not isolation friendly.

In the absence of other options have currently addressed this with a shared build service in our core convention plugin to set and retrieve these values.  While not currently an issue this approach introduces a timing-coupling, requiring the root project be evaluated first.

2. Access version catalog from sub-projects.

This one is either erroneous code on my part or perhaps has some legacy history:

```
public fun Project.versionCatalogs(action: VersionCatalogsExtension.() -> Unit) {
    rootProject.extensions.configure(action)
}
```

In any event, it is not necessary to access via rootProject - simply removing that addresses the issue.

3. In our custom Gradle distribution init scripts there are a few project-specific items to setup (code reduced to illustrate issue).

```
allprojects {
    // for the script itself, e.g. plugins
    buildscript {
        configurations.all {
            resolutionStrategy {
                cacheDynamicVersionsFor(1, TimeUnit.HOURS)
                cacheChangingModulesFor(5, TimeUnit.MINUTES)
            }
        }
    }

    configurations.all {
        resolutionStrategy {
            cacheDynamicVersionsFor(2, TimeUnit.HOURS)
            cacheChangingModulesFor(5, TimeUnit.MINUTES)
        }
    }
}
```

`allprojects` creates coupling between projects.

This one was readily solved by using beforeProject instead.

**Comment by lacasseio** [comment]
It's not strictly related to applying a plugin, but we have multiple cases where we _push_ configuration down into the projects using mentioned hooks.

The whole concept of [build adapter Nokee is developing for iOS support in Gradle](https://github.com/nokeedev/gradle-native/tree/master/subprojects/build-adapter-xcode) uses `Gradle#rootProject(Action)`, `Project#allprojects(Action)`, and `Project#project(String, Action)`. The settings plugin takes full ownership of the build layout and configuration, which is required to map everything to Gradle. If Gradle would provide a way to inject isolatable configuration action (similar to dependency resolution actions or `ValueSource` or `BuildService`), we could pass the required information isolated from everything else.

Our native IDE plugin refactoring will allow users to apply the plugin to the `Settings` and automatically enable IDE integration for all projects instead of applying the IDE plugin to each project individually.

Finally, Nokee's deep integration with Gradle relies on a init script which uses `BuildListener#beforeSettings` to configure the correct repositories and version alignment hooks. This is required to ensure the same Nokee version is used in all composite builds (included, buildSrc and source build). This is quite tricky to do correctly, and it's the only way to achieve this level of deep integration.

**Comment by ThadHouse** [comment]
I've removed most of my use cases of going into other projects, but I still have a few. 

1. I have a few tasks that extract resources embedded in a plugin for other tasks throughout a project to use. There are a few ways around this, but none are really as elegant or easy as just applying a task to the root project to do this extraction. Some way to have global tasks would completely solve this issue for me. Shared Build Services kind of work, but they mean I have to implement all the incremental and up to date checks myself, whereas as a task they automatically do exactly what I need.

2. I have a plugin that creates a task that needs to go across a few types of tasks across all projects in order to generate some metadata that must be in a single file. It only does the actual reaching at build time, so this might be ok, I just want to make sure it won't break.

**Comment by melix** [comment]
Another use case: init scripts, especially when using the Tooling API. For example saw [this](org.eclipse.jdt.ls.core/gradle/apt/init.gradle) yesterday.

**Comment by ysb33r** [comment]
Let's say we have some opinionated organisational plugins.

- We want to always have a consolidated Jacoco report and the root level, when one or more of the subprojects apply Jacoco plugin. one way is for that subprojectisto invoke a plugin at the root level which will created the consolidated report.
- In generic terms this is, when a specific plugin is applied to a subproject, we want to automatically have some additional functionality added at root level.
- There is also cases where we want to have something happen ONCE across the project i.e. we might want to check for the existence of certain OWASP files (from the Gradle Dependency Check plugin). We do not want those checks to happen in every subproject, becasue we might only have applied that to subprojects 4, 7 & 8. So if the subproject applies the plugin that does that at root level, the will only be one task executed.

**Comment by JavierSegoviaCordoba** [comment]
Not about applying a plugin but another use case is sharing a Gradle project property in the root project `gradle.properties` on all projects. That was working on Gradle 7, but it fails on Gradle 8.

**Comment by IgnatBeresnev** [comment]
With projects like [Dokka](https://github.com/kotlin/dokka), the most common scenario is people want to generate documentation for all subprojects, including any new ones that might appear in the future. It's usually only a couple of very specific subprojects that our users don't want to generate documentation for (and they're usually [filtered out with an `if`](https://github.com/Kotlin/kotlinx.serialization/blob/master/gradle/dokka.gradle#L8-L17)). 

If `subprojects {}` is recommended against, we have a hard time understanding how to deal with large user projects that already rely on `subprojects {}`. Especially if sources are generated. For example:
* [aws-sdk-kotlin](https://sdk.amazonaws.com/kotlin/api/latest/index.html) (~250 subprojects). The sources for the majority of the subprojects [need to be generated by hand](https://github.com/awslabs/aws-sdk-kotlin/blob/main/README.md#generate-sdks). 
* [ktor](https://api.ktor.io/) - many subprojects, but real ones this time. 

At the moment, these projects use `allprojects {}` or `subprojects {}` to apply and configure Dokka.

Compared to the simplicity of using `subprojects {}`, it might be very tough to persuade the users to first migrate their build scripts to be idiomatic and use convention plugins, or to enumerate all projects in a single place for Dokka (so that the aggregate multi-module documentation could be built on the root level), as most people don't see the benefit in it and just want it to work.

**Comment by Vampire** [comment]
I personally would not recommend putting any legacy and discouraged practices like `subprojects { ... }` in any documentation.
Especially if you target beginners, you right away show them the bad way and they will continue using it for long time instead of doing it good right away.

I'm not sure how much harder it is to use a convention plugin, especially when used with `buildSrc`. I'd say a convention plugin in `buildSrc` **is** the middle ground where convention plugins in included builds are the golden way. In your way, they use a legacy and discouraged way to apply plugins within a legacy and discouraged way to apply it to all projects. In the convention plugin way, they have the `plugins { ... }` block that applies the plugin and the configuration in an extra file that they then apply in the projects where they want to have the effect.

There's also no need to make a project "fully idiomatic", you can at any time start with your first convention plugin only centralizing the dokka configuration for projects and just apply that everywhere you want to have it. Theoretically, you could even apply it in a `subprojects { ... }` block, but that would be counterproductive of course. :-D

PS: https://github.com/adamko-dev/dokkatoo does not have such advice to use `subprojects { ... }` or `apply(...)` :-)

**Comment by martinbonnin** [comment]
> Due to this, we still haven't figured out how we should write the user-facing documentation for Dokka's Gradle plugin, and which configuration examples we should give.

@IgnatBeresnev what about giving the per-project instructions:

**subproject:**

```kotlin
tasks.dokkaHtml.configure {
    outputDirectory.set(buildDir.resolve("dokka"))
    // more stuff
}
```

**root project:**

```kotlin
tasks.dokkaHtmlMultiModule.configure {
    outputDirectory.set(buildDir.resolve("dokkaCustomMultiModuleOutput"))
    documentationFileName.set("README.md")
    // more stuff
}
```

Then leave users and Gradle figure out the details of how to factor their build logic code? As much as I'd like to see an "idiomatic"/"easy" way to do this, it doesn't feel like plugin authors should be opinionated about this.

**Comment by Vampire** [comment]
But without the `.configure` please.
It is redundant in both DSLs.
In Groovy on the other hand even the `tasks.dokkaHtml` is not so good as it disturbs task-configuration avoidance and should use `tasks.named<DokkaTask>('dokkaHtml') { ... }` instead.
And of course for latest Gradle I prefer using ` = ` instead of `.set(...)`. :-)

**Comment by Vampire** [comment]
You should probably instead have a task that writes this information to a file, define an outgoing configuration to which you attach this tasks result and then depend on this from the root project and aggregate the data. Similar to how the `test-report-aggregation` and `jacoco-report-aggregation` do it. Then you do not need to access the subproject models from the root project or aggregator project directly. See here for more information: https://docs.gradle.org/current/userguide/cross_project_publications.html

**Comment by Vampire** [comment]
Using `allprojects` or `subprojects` for depending on them should be fine.
Just the `allprojects { ... }` and `subprojects { ... }` and `project("...") { ... }` where you configure the other projects or directly querying properties of the other projects is bad.

**Comment by Vampire** [comment]
That's exactly what I said.
The lambdas are bad and against porject isolation, as is querying properties from the other projects' models.
But depending on them like `dependencies { allprojects.forEach { aggregateInfo(it) } }` is fine.

**Comment by loosebazooka** [comment]
Is there any way to get [ProjectComponentIdentifier](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/component/ProjectComponentIdentifier.html) to include more information from a project? Like `version`?

**Comment by hfhbd** [comment]
> But depending on them like dependencies { allprojects.forEach { aggregateInfo(it) } } is fine.

If this is the case, (and I trust Vampire), there should be a better API to not confuse users between `allprojects { }` and `allprojects.forEach { }`.
Or promote this feature in the docs, how to easily depend on all subprojects.

**Comment by bamboo** [comment]
[IdeaPluginConfigurator](https://github.com/JetBrains/intellij-community/blob/685aa2e09c080b27ed07a64d0d287badf4eb2d8d/plugins/gradle/tooling-extension-impl/src/org/jetbrains/plugins/gradle/tooling/internal/init/IdeaPluginConfigurator.gradle#L19) disabling download of sources and javadoc.

Via [IDEA-341827](https://youtrack.jetbrains.com/issue/IDEA-341827).

**Comment by bamboo** [comment]
Moving this feature to 8.8 to consider it in the larger context of _patterns for introducing APIs compatible with Isolated Projects_, with [#28011](https://github.com/gradle/gradle/issues/28011) as an another example of API that should be consistent with the chosen pattern.

**Comment by bamboo** [comment]
Fixed via #28581, and #28738 and #28875.

**Comment by martinbonnin** [comment]
@bamboo can you elaborate on how those APIs would work? 

I've read the [8.8-rc.1 changelog](https://docs.gradle.org/8.8-rc-1/release-notes.html) but the examples there are mostly read only? 

They allow to read the subproject path in a project-isolation compatible way but are not a substitute for things like `allprojects { it.pluginManager.apply("com.example") }`. Is there any guidance about how to apply build logic to all subprojects?

**Comment by bamboo** [comment]
Hi @martinbonnin, sure thing. 

The callbacks receive a still **mutable** `Project` instance which the code is free to apply plugins to, register extensions and tasks, etc. For example:

```kotlin
gradle.lifecycle.beforeProject {
  pluginManager.apply("java")
}
gradle.lifecycle.afterProject {
  println("Is it java? ${extensions.findByName("java")}")
}
```
