### ISSUE TITLE
DefaultTaskContainer´s create methods should add the task AFTER executing configure action

### ISSUE THREAD

**Issue by janjoerke** [gradle/gradle#2269]
### Expected Behavior
DefaultTaskContainer´s create methods should add the task AFTER executing configure action.

### Current Behavior
DefaultTaskContainer´s create methods adds the task BEFORE executing configure action.

### Context
Within the DefaultTaskContainer create methods adding the task to the DefaultDomainObjectCollection triggers the all method. At this moment the configure action has not yet been executed. Therefore the task referenced by the all method has not yet been configured.

### Steps to Reproduce (for bugs)
    public class MyTask extends DefaultTask {

        public String myParameter

        @TaskAction
        void doSomething() {}
    }
    
    tasks.matching {it instanceof MyTask}.all {
        // Configure action of DefaultTaskContainer create method, has not yet been executed
        // Prints null
        System.out.println(myParameter)
    }
    
    tasks.create("myTask", MyTask.class) {
        it.myParameter = "test"
    }

### Your Environment
Not relevant

**Comment by oehme** [comment]
This would be a breaking change. The configuration closure is just a convenience, tasks can also be added and then configured later, there should be no difference between the two.

However, we could consider adding a different overload that takes mandatory constructor parameters for the task, so that they have to be set before any `matching {}` and similar methods are called. This would also be useful for other domain object containers.

**Comment by oehme** [comment]
I created #2983 to track my proposed alternative, since other users have asked for that one too. I'm going to close this request, since we are not going to change how the configuration closures work.
