### ISSUE TITLE
Make annotation processors a first-class citizen

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#2300]
Right now we tell our users to add this snippet to their project if they want to use annotation processors:

```
configurations {
  apt
}

tasks.withType(JavaCompile) {
  options.annotationProcessorPath = configurations.apt
}
```

This should work out of the box and each SourceSet should have an `annotationProcessor` configuration. For backwards compatibility we can do what the Android team did: Emit a deprecation warning when we find annotation processors on the compileClasspath (and add it to the annotation processor path to keep the build running) and add a flag to `CompileOptions` to allow the user to ignore these processors. We can then turn that warning into a failure in the next major release and deprecate the flag, because its behavior will then be the default.

**Comment by tbroyer** [comment]
Having built-in support would help with integration in IDE. Fwiw, as of now, in Gradle 4.3+, the [`net.ltgt.apt`](https://github.com/tbroyer/gradle-apt-plugin#configuration) plugin's added value is:
 * automatic creation of the `apt` configuration (should probably have been called `annotationProcessor` in retrospect; might do that in a future version) for each SourceSet and automatic configuration of `compileJava.options.annotationProcessorPath` (same for `compileGroovy` too btw)
 * automatic configuration of `compileJava.options.annotationProcessorGeneratedSourcesDirectory` to a _sane default_ (currently `${project.buildDir}/generated/source/apt/${sourceSet.name}`; should probably add `${sourceDirectorySet.name}` too for those using `compileGroovy`)
 * automatic configuration of IDEA and Eclipse to add the `annotationProcessorGeneratedSourcesDirectory` as a (generated) source directory (for IDEA, at least for some older versions, this means un-excluding `${project.buildDir}` and re-excluding all subdirectories but the `generated` one)
 * add tasks to generate Eclipse's `.factorypath` and `.settings/org.eclipse.jdt.apt.core.prefs`, automatically called before the `eclipse` task, but you have to manually call them when importing in BuildShip (see https://github.com/tbroyer/gradle-apt-plugin#eclipse). Note that annotation processing in Eclipse has only one annotation processor classpath and one output directory; this is a limitation of Eclipse AFAICT; so this means annotation processing in the IDE is only an approximation
 * hook into the IDEA plugin to (try to) configure annotation processing in the IDE; this only works with the `idea` task. To make things simpler for those using the built-in Gradle support in IDEA, the `apt` dependencies are added to the project build path (which can have unexpected side-effects when the same dependency is used with different versions between `apt` and `compileClasspath`); this behavior can be disabled, for when you delegate build/run actions to Gradle (so you don't suffer the side-effects in the IDE for code completion and static analysis). See https://github.com/tbroyer/gradle-apt-plugin#intellij-idea

Integration within Gradle itself, and possibly exposing through the Tooling API, would make it possible for IDEs (IDEA / BuildShip) to automatically configure themselves appropriately.

The plugin also augments the DSL for SourceSet, SourceSetOutput and JavaCompile/GroovyCompile. SourceSet addition would be built into Gradle to support the proposed new configurations. JavaCompile/GroovyCompile are augmented with an `aptOptions` DSL that mainly allows configuring `processorArgs` (the `-Akey=value` javac arguments), and whether `annotationProcessing` should be done or not (`-proc:none`). The plugin uses this information to configure the IDEs too. Maybe IDEs could directly look at the `options.compilerArgs`, or maybe they'd benefit of similar APIs.

Currently, the main issues I'm facing in the plugin are IDE configuration (most issues filed against the plugin are related to IDEs, and most of them are misunderstandings or other developer mistakes rather than bugs or feature requests).

 * For IDEA, the problem is that there are many ways to use it: you can use `gradle idea`, or you can use the Gradle support in IDEA; in the latter case, you may want to run annotation processing in the IDE, or manually run `gradle classes` to re-generate sources when you need it, or you can delegate build/run actions to Gradle. Depending on what you want, you'll have to configure the plugin differently (and may have to do some manual configuration in the IDE).

 * For Eclipse, the main issue is that there's a single factorypath and output directory (well, I think ideally you'll want one Eclipse project per SourceSet, that would solve the problem, but I don't think it's possible); and of course in terms of DX, the need to manually run some tasks prior to importing in BuildShip.

**Comment by oehme** [comment]
Thank you for this thorough write-up @tbroyer. We'll take that into account when integrating this into the `java` plugin.

**Comment by tbroyer** [comment]
Fwiw, I'd happily contribute a PR to add `annotationProcessorPath` and `annotationProcessorConfigurationName` to SourceSet, and automatically creating `annotationProcessor`/`testAnnotationProcessor` configurations, configuring `JavaCompile`/`GroovyCompile` tasks' `options.annotationProcessorPath` to those new configurations (when not empty, otherwise to `null` so `getEffectiveAnnotationProcessorPath()` would behave the same as today; or something similar).

I'd also happily contribute a PR to log a warning when using annotation processors from the `classpath` (rather than using the `options.annotationProcessorPath`).

And finally, possibly, changes to the IDE plugins.

That would backport almost all features of `net.ltgt.apt` to Gradle proper.

I think those parts are, once agreed on principle, not controversial (whether and how to configure an `annotationProcessorGeneratedSourcesDirectory`, `-proc:none`, and/or `-Akey=value` probably need some prior discussion on the other hand).

I would mostly need guidance on writing the tests (which ones, where, how) for those PRs.

**Comment by oehme** [comment]
That would be great, let's start with the new Configurations and the deprecation warning. What you proposed for those sounds good to me, but it would be great if you could elaborate on the user interaction a bit more so others can follow the discussion. E.g. what will happen in Gradle 4.x if I have undeclared processors and what will happen in 5.x? How do I get rid of the warning when I don't want a processor that is leaking in transitively?

For the IDE plugin changes we'll need to involve the JetBrains team. 

We use Spock for both unit and functional testing. For this change I would mostly expect some functional tests that show the different scenarios like "user doesn't use `annotationProcessorPath`" or "user explicitly overwrote `options.annotationProcessorPath`" etc. See the existing JavaCompile [tests](https://github.com/gradle/gradle/blob/master/subprojects/language-java/src/integTest/groovy/org/gradle/api/tasks/compile/JavaCompileIntegrationTest.groovy) for some examples.

**Comment by tbroyer** [comment]
> it would be great if you could elaborate on the user interaction a bit more so others can follow the discussion. E.g. what will happen in Gradle 4.x if I have undeclared processors and what will happen in 5.x?

Assuming what we're talking about will ship in 4.5 (or 4.6), and would become an error in 5.0; the way I see it:
 * in 4.x `options.annotationProcessorPath` would default to the `annotationProcessor` configuration if not empty, to `null` otherwise (which means possibly fallback to the `compileClasspath`). This means that if I have processors in the `compileClasspath`, and no other specific configuration of the `JavaCompile` task, a warning would be displayed telling me to put the annotation processors in the `annotationProcessor` configuration (might be tricky to setup the appropriate message though, maybe use `options.annotationProcessorPath` and hope that users will look it up in the docs and see that the default value is a configuration?).
* in 5.0, `options.annotationProcessorPath` could unconditionally default to the `annotationProcessor` configuration (never `null`, and that `null` special behavior could be removed; see below), and annotation processors in the `compileClasspath` would simply be ignored. We could possibly add a warning, but then we'd have to add a toggle to disable it, so I'd rather just do nothing (`-processorpath` would always be passed to javac, so it would never lookup annotation processors from the compile classpath, effectively ignoring them if there's any).

Wrt the behavior of `options.annotationProcessorPath = null` in 5.0, if we want to totally remove it, then the parsing of `-processorpath` in `options.compilerArgs` should probably log a warning in 4.x; otherwise we'd have to continue defaulting `options.annotationProcessorPath` to either `annotationProcessor` if not empty, or `null` if empty, but then fail if it's effectively `null` and there's no `-processorpath`.
Let's discuss and do it separately though.

> How do I get rid of the warning when I don't want a processor that is leaking in transitively?

Disabling annotation processing with `-proc:none` or setting `annotationProcessorPath` to an empty collection would get rid of the warning.
When there's a `-processor …` argument in the `options.compilerArgs`, I would still log a warning telling the user to put the annotation processors in the `annotationProcessorPath` (either by using `task.options.annotationProcessorPath = task.classpath`, or possibly `configurations.annotationProcessor.extendsFrom configurations.compileClasspath`)

> For the IDE plugin changes we'll need to involve the JetBrains team.

Fwiw, I was talking about the `idea` and `eclipse` Gradle plugins, which could generate the appropriate configuration for the IDEs (`.factorypath` and `.settings/org.eclipse.jdt.apt.core.prefs` for `eclipse`, and the appropriate `*.ipr` content for `idea`)

**Comment by eximius313** [comment]
Cooperation with Buildship team would be probably a good idea too (https://github.com/eclipse/buildship/issues/329)

**Comment by wolfs** [comment]
@tbroyer Regarding annotation processor arguments (`-Akey=value`): starting with Gradle 4.5 there is now some support which would allow you to model an annotation processor in a rich way: see the [userguide](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_input_nested_inputs) and the new property [CompileOptions.compilerArgumentProviders](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.compile.CompileOptions.html#org.gradle.api.tasks.compile.CompileOptions:compilerArgumentProviders).

Would you think Gradle should provide something like a generic annotation processor so users would not be required to model their own? Or do you think that support + maybe some base class provided by a plugin is already enough?

**Comment by tbroyer** [comment]
@wolfs I must say I have never personally had the need to pass processor args (not entirely true, but not far from reality), and never needed to use arguments in the few processors I wrote.

So, IIUC, the goal is mostly such that annotation processor authors could also provide Gradle plugins modeling the processor arguments in a typesafe (and discoverable) API that could also validate the arguments before even calling the compiler, right? In such case, I'd say the current situation is enough.
Same if the use case is to make it easier to tie compiler arguments to a plugin's DSL (I have the feeling I could back `net.ltgt.apt` extension DSL with a `CompilerArgumentProvider` and remove dozens of lines of `TaskInputs`/`TaskOutputs` configuration).

BTW, there's a typo in the userguide (`@PathSensitivite`), and it could make it clearer why one would use this approach as opposed to the much simpler:
```gradle
compileJava {
  inputs.file inputFile withPathSensitivity PathSensitivity.NONE
  outputs.file outputFile
  doFirst {
    options.compilerArgs << "-AinputFile=${inputFile.absolutePath}"
                         << "-AoutputFile=${outputFile.absolutePath}"
  }
}
```

**Comment by childnode** [comment]
for me there are some documentation issues, at least for the javaPlugin
https://github.com/gradle/gradle/commit/5e99e01783da2f88ff02c5466fa87e25dfe4012e#r27722127

**Comment by oehme** [comment]
@tbroyer Would you be up for making annotation processors work with the IDEs out of the box too?

**Comment by tbroyer** [comment]
@oehme Well, I certainly _could_, but there are many design issues to be discussed first (see the end of https://github.com/gradle/gradle/issues/2300#issuecomment-350336010 above)

First, some people will prefer **not** to have annotation processing run in the IDE (I'm one of those, I've had too many issues with JDT APT I think it's not worth it), **or** will prefer to configure things differently / manually (see https://github.com/tbroyer/gradle-apt-plugin/issues/45); so things have to be disablable.

Next, you need to pick an output folder for the generated sources. `net.ltgt.apt` configures one automatically, so this isn't a problem (well, it could be one actually), but Gradle doesn't. In some cases, this could be the same as the `CompileOptions.annotationProcessorGeneratedSourcesDirectory` (I'm actually not even sure that's a good idea, though I couldn't see why it would be a bad one), but what if you have both Java and Groovy in the same project? what if they are configured with different generated sources directories (which you should do for proper build incrementality and build caching)

For IDEA:
 * when **not** using "module per source set" (such as with `gradle idea` afaict), afaict, you have to share the annotation processor path between main and test sources.
 * when mixing several languages in the same source set (and I don't even know whether IDEA would apply annotation processors other languages), you can only have one generated sources directory, which means you probably cannot share it with your compilation tasks if you configured one there (assuming you're not using joint compilation). IIUC, Gradle integration in IDEA already use a different output directory for classes in this case, because IDEA _only_ does joint compilation, with a single output directory; so that wouldn't be much different. See above about the need to pick an output folder for the generated sources.
 * most important for me: the current `IdeaModel` doesn't allow "unexcluding" children folders of excluded folders, which IDEA is capable of since 2016.3 or something. This prevents having the generated sources inside the build directory for instance (e.g. `build/generated/sources/apt/$sourceDirectorySet/$sourceSet`). In `net.ltgt.apt`, I'm doing something hackish in that I'm looking at the file system, and in case the generated sources directory is inside an excluded folder, I unexclude it and then exclude all child folders except the one where generated sources are. This means that the list of excluded folders will change depending on the tasks you've already executed before importing the project in IDEA. Ideally, you could just declare the generated sources folders (which the `IdeaModel` already models, but maybe this should be configured explicitly with another property) and it would automatically unexclude them. This would need to be done both in the `idea` plugin/task and in IntelliJ IDEA's Gradle integration.
 * not to mention the case where you add new source sets beyond `main` and `test`: the `IdeaModel` doesn't models the source sets themselves, and using "module per source set" when importing in IDEA can easily get things wrong and map generated sources folders to the wrong module/sourceset. This wouldn't happen if source sets could declare generated sources directories in `SourceSetOutput` and/or `SourceDirectorySet`. In `net.ltgt.apt`, I added a `SourceSetOutput.generatedSourcesDir`, but this would ideally need to be changed to be a list, with a `SourceSetDirectory.generatedSourcesDir`, similar to how you did with the `classesDir` vs. `classesDirs`. Then we'd still need JetBrains to use it when available.

For Eclipse:
 * all of the above apply, **and** you're in a situation where you cannot have "module per source set" (though you can have separate output folders): only one annotation processor path (`.factorypath`) for the whole project (main and test sources), and only one generated sources directory.

I haven't talked about the annotation processor arguments (in the form of `-Akey=value` compiler arguments), which people would likely want to be applied to their IDE configuration (see https://github.com/tbroyer/gradle-apt-plugin/issues/50)

Overall, I'm not sure I have enough experience with annotation processing in IDE (or Gradle internals related to IDEs) to really work on this. Personally, all I really want/need is to easily declare generated sources directory **and** have them automatically "unexcluded" when inside the build directory. If I have that, I don't really need `net.ltgt.apt`/`net.ltgt.apt-idea` any longer: I'd use small snippet to configure a `CompilerOptions.annotationProcessorGeneratedSourcesDirectory` and then add that folder as a source directory and generated source directory (and possibly "unexcluded" directory) to the `IdeaModel`.

**Comment by tbroyer** [comment]
Inspired by https://github.com/tbroyer/gradle-apt-plugin/issues/78: should source sets' `compileJavaTaskName` task's `options.annotationProcessorGeneratedSourcesDirectory` be automatically added to the source set's `allJava` and `allSource`? And if so, should the task be added as a build dependency of those source directory sets? (same for Groovy and Scala, and Kotlin/kapt)

This would directly affect tasks like Javadoc, Checkstyle, FindBugs, PMD and Jacoco. It should be noted that equivalent Maven plugins will use the project's `compileSourceRoots`, which will include the generated sources when using maven-compiler-plugin >= 3.2. For those tasks that actually work on bytecode and only/mostly use sources for reporting (FindBugs, Jacoco), this would be a good idea; but maybe not for Checkstyle or PMD? How about Javadoc?  
Fwiw, [Error Prone](http://errorprone.info) (which plugs right into / replaces javac) applies its checks to generated sources too, unless excluded with `-XepDisableWarningsInGeneratedCode` or `-XepExcludedPaths`.

Another side-effect for many people: it would automatically include generated sources into source JARs, when using a task like in https://docs.gradle.org/4.6/userguide/publishing_maven.html#publishing_maven:publish-custom-artifact or http://central.sonatype.org/pages/gradle.html#jar-files, or the `com.bmushko.nexus` plugin or similar (that was actually the purpose of that issue that spun off this comment here)

**Comment by oehme** [comment]
It sounds like a good idea, though I wonder if we'd break any plugins that assume they can depend on `allJava`, but run before `compileJava`.

If you'd only like to work on a subset of the problems, that's great too, e.g. the "unexclude" feature sounds very useful to all Idea users.

**Comment by eximius313** [comment]
Gradle 4.7 fully supports `annotationProcessor`.
Can Buildship enable annotation processing in Eclipse reflecting `annotationProcessor` in Gradle?

**Comment by xak2000** [comment]
I read documentation about new `annotationProcessor` feature, but can't find any information about it's configuration.

For example, with [net.ltgt.apt](https://github.com/tbroyer/gradle-apt-plugin#configuration) plugin I can do:

```
compileJava {
	 aptOptions.processors = [
	 	'org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor',
	 	'com.querydsl.apt.jpa.JPAAnnotationProcessor',
	 	'lombok.launch.AnnotationProcessorHider$AnnotationProcessor'
	 ]
	aptOptions.processorArgs = [
		"addSuppressWarningsAnnotation": "true",
		"querydsl.entityAccessors": "true"
	]
}
```

How can achieve the same with inbound `annotationProcessor` handling (without plugins)?

**Comment by eximius313** [comment]
well, its easy. Here you have an example: https://github.com/rzwitserloot/lombok/issues/1580#issuecomment-394489524

**Comment by oehme** [comment]
There are no special "aptOptions", you can use normal compiler options.

**Comment by tbroyer** [comment]
@xak2000 Specifically:
```gradle
compileJava {
    options.compilerArgs += [
        "-processor",
        "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor,com.querydsl.apt.jpa.JPAAnnotationProcessor,lombok.launch.AnnotationProcessorHider$AnnotationProcessor",
        "-AaddSuppressWarningsAnnotation=true",
        "-Aquerydsl.entityAccessors=true"
    ]
}
```

See https://docs.oracle.com/javase/8/docs/technotes/tools/unix/javac.html

…or you can use the `net.ltgt.apt` plugin for the added DSL (it will also configure `options.annotationProcessorGeneratedSourcesDirectory`, but otherwise just lets the built-in support in Gradle do its job).

**Comment by tbroyer** [comment]
> It sounds like a good idea, though I wonder if we'd break any plugins that assume they can depend on allJava, but run before compileJava. It would be a pretty exotic setup though :)

Fwiw, I added it to [`net.ltgt.apt` 0.16](https://github.com/tbroyer/gradle-apt-plugin/releases/tag/v0.16), let's see how people react to the change :wink: 
(it was easier for me to add it to `net.ltgt.apt` as it ensures there's an `annotationProcessorGeneratedSourcesDirectory`)

**Comment by tbroyer** [comment]
> Fwiw, I added it to `net.ltgt.apt` 0.16, let's see how people react to the change :wink: 

Causes a regression in Buildship and `gradle eclipse`: https://github.com/tbroyer/gradle-apt-plugin/issues/85

**Comment by tbroyer** [comment]
New feedback from the `allSource`/`allJava` change: https://github.com/tbroyer/gradle-apt-plugin/issues/78#issuecomment-399370942 TL;DR: it "breaks" many other plugins. I suggest reverting this change, and then adding some kind of `generatedSourcesDirs` (similar to `classesDirs`) to `SourceSetOutput`; or simply do nothing (I have no idea what the `idea` and `eclipse` plugins should do though…)

**Comment by oehme** [comment]
So it's mostly failing because people assumed that no generated code will be in there and it fails because the generated code doesn't pass their checkstyle rules. I guess we could work around that the way you said or do it the other way round and provide something like `handWrittenJava`:)

**Comment by chirkov86** [comment]
Hi! How can I configure Gradle 4.7 to use Lombok without 
`annotation processors were detected on the compile classpath`?
Unfortunately no live examples in docs especially for setting `annotationProcessorPath`.
Setting 
```
annotationProcessor('org.projectlombok:lombok:1.16.16')
testAnnotationProcessor('org.projectlombok:lombok:1.16.16')
```
helped for built-in `main` and `test` source sets, but couldn't help for manually added `integrationTest` .
BuildScan: https://scans.gradle.com/s/jl4souarjpwpq
Any help would be appreciated, thanks in advance.

**Comment by tbroyer** [comment]
@chirkov86
```
integrationTestAnnotationProcessor('org.projectlombok:lombok:1.16.16')
```
?

**Comment by chirkov86** [comment]
@tbroyer, thanks for the response! I tried but Gradle replies with `Could not find method integrationTestAnnotationProcessor()`

**Comment by eximius313** [comment]
@tbroyer 
> On the Eclipse front, nothing seems to have changed in Buildship (yet). Because there's no easy workaround (contrary to IntelliJ IDEA), this means that net.ltgt.apt-eclipse is still needed.

Is there an issue regarding this workaround already raised in Buildship?

**Comment by eximius313** [comment]
Thanks

**Comment by jjohannes** [comment]
First class support for annotation processing has been delivered since several Gradle version.

For additional requests, please open separate issues.
