### ISSUE TITLE
Gradle 7.6: Dependency verification is failing for latest version of a dependency even though it should not be resolved

### ISSUE THREAD

**Issue by davidburstrom** [gradle/gradle#23162]
### Expected Behavior

If a project

* is using dependency verification and
* it already has kotlin-compiler-embeddable:1.7.22 accounted for and
* it sets up a configuration like below (with a constraint with open upper bound)

```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.jetbrains.kotlin:kotlin-compiler-embeddable") {
            version {
                strictly("[1.4.0,)")
                prefer("1.7.22")
            }
        }
    }
}
```

it should simply resolve version 1.7.22 in the dependency tree.

### Current Behavior

Dependency verification fails saying that 1.8.0-RC metadata (or whichever is the current latest) is not accounted for.

### Context

I'd really want to use dependency verification. Adding the latest version is a no-go, as the build is not reproducible. The workaround it to turn off dependency metadata verification, which is not ideal either.

### Steps to Reproduce 
[gradle-dependency-verification-bug-issue-with-latest.zip](https://github.com/gradle/gradle/files/10229222/gradle-dependency-verification-bug-issue-with-latest.zip)
The self-contained example can be run with `./build.sh`. 

### Your Environment

* Gradle 7.6

**Comment by xaviarias** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team but the existence of a workaround makes it non-critical so it might take a while before a fix is made.

---

Workaround is do a key base trust from Kotlin so dependency verification trusts all artifacts.

`verification-metadata.xml`

```xml
<trusted-key id="6f538074ccebf35f28af9b066a0975f8b1127b83" group="org.jetbrains.kotlin"/>
```

Another workaround is to use a non-range version.

We will be looking whether the latest 6.x or latest 7.x still reproduces the issue.

**Comment by davidburstrom** [comment]
Hi @xaviarias! Thank you for providing a better workaround (the key base trust) than mine :)

**Comment by xaviarias** [comment]
Gradle versions 6.9.2 and 7.6 also fail on dependency verification.

**Comment by davidburstrom** [comment]
@xaviarias Sorry for the confusion, I have absolutely no idea why I wrote Gradle 6.8. It was supposed to be 7.6. I've updated accordingly.

**Comment by xaviarias** [comment]
After some investigation, in the current implementation the behavior is expected because of the need of POM metadata files on a version range resolution. 

Gradle will check variant information to make sure to only accept a version in the range that matches requested attributes (e.g. JVM  and language versions). And hence the verification failure for Kotlin v1.8 RC2 since Gradle will download the metadata for it.

There might be a possible optimization to avoid dependency verification for non-matching ranges, but for now the only workarounds are the before mentioned key base trust or use non-ranged versions.

**Comment by davidburstrom** [comment]
Thank you for the investigation!

The workaround not to use non-ranged versions is less than ideal, as the use-case is a library A that has a dependency on library B (e.g. checkstyle), but is designed to work with any given version of B greater than X. It would be up to the consumer of A to provide a version of B, while at the same time respecting the constraint.

While I can use the trusted-key solution in the library A project to stabilize the builds (until the key is rotated for whatever reason), a consumer project will also have to add the trusted-key solution for the same reason, if dependency verification is used there as well.

**Comment by davidburstrom** [comment]
Revisiting this ticket, I think you're onto something regarding avoiding dependency verification for non-matching ranges. If I understand you correctly, if there is a maliciously altered 1.8 RC2 POM, if it is non-matching anyway, there's no need to verify its integrity?
