### ISSUE TITLE
Tests of classes with Enclosed runner are run twice.

### ISSUE THREAD

**Issue by stefanbirkner** [gradle/gradle#2319]
The tests inside of a test class that is annotated with `@RunWith(Enclosed.class)` are run twice. This bug was already reported as [GRADLE-2843](https://issues.gradle.org/browse/GRADLE-2843) in 2013.

### Expected Behavior

The test should only run once.

### Current Behavior

The test runs twice.

### Context

I have longer build times because tests are executed too often.

### Steps to Reproduce (for bugs)

 This is a test class with an Enclosed runner

    @RunWith( Enclosed.class )
    public class Enclosed1Test {
        public static class InnerClass {
           @Test
            public void aTest() {
                Assert.assertEquals( "test", "test" );
            }
        }
    }

This is the resulting JUnit XML:

    <?xml version="1.0" encoding="UTF-8"?>
    <testsuite name="Enclosed1Test$InnerClass" tests="2" skipped="0" failures="0" errors="0" timestamp="..." hostname="..." time="0.004">
      <properties/>
      <testcase name="aTest" classname="Enclosed1Test$InnerClass" time="0.001"/>
      <testcase name="aTest" classname="Enclosed1Test$InnerClass" time="0.0"/>
      <system-out><![CDATA[]]></system-out>
      <system-err><![CDATA[]]></system-err>
    </testsuite>

### Your Environment

 * Build scan URL: https://gradle.com/s/527bd2yvp6rlk

**Comment by stefanbirkner** [comment]
@chilloutman tried to solve this problem in #489.

**Comment by stefanbirkner** [comment]
This may be an issue with the discovery of JUnit tests and be related to #2320.

**Comment by kcooney** [comment]
As someone who works on JUnit 4, I'm surprised that Gradle runs tests in static nested classes by default.

In the JUnit4 code base (which currently uses Maven) we often need to write tests to verify what happens when a test fails (either due to an initialization error in a runner or rule, or a normal test failure). To do that, we add a nested static class to use when we run the test, and then use the JUnit APIs to run this test directly. If we switched to Gradle and Gradle ran tests in nested static classes, those tests would fail.

In my day job (which uses Bazel), we occasionally write custom runners or rules, and we also write nested static test classes that are used to exercise these test fixtures.

Do people often write static nested test classes expecting them to run? I would have though anyone that wanted to do that would use the `Enclosed` runner.

I don't think Gradle should do something different for a class annotated with `RunWith(Enclosed.class)` since people can write their own runners with similar behavior as JUnit's `Enclosed` runnerl

**Comment by bmuschko** [comment]
> Do people often write static nested test classes expecting them to run?

I personally haven't encountered a project with this practice and I have seen plenty of projects in the wild.

> As someone who works on JUnit 4, I'm surprised that Gradle runs tests in static nested classes by default.

We'd have to check with the JUnit team to see what the default behavior _should_ be here. Feel free to follow up with them as well.

**Comment by kcooney** [comment]
Stefan and I are on the JUnit team 🙂

@stefanbirkner how does the JUnit 5 test discovery engine find JUnit4-style tests?

**Comment by stefanbirkner** [comment]
I will have a look at JUnit 5's discovery algorithm tomorrow, when I'm back home.

**Comment by bemnet4u** [comment]
Any update on this? I now now seeing a case where tests with Enclosed runner are not run anymore.

**Comment by bmuschko** [comment]
@bemnet4u No progress has been made. We'd welcome a contribution from the community.

**Comment by jkachika** [comment]
Was facing this issue for a while. Just figured that making the class abstract would run the tests only once.
```
@RunWith(Enclosed.class)
public abstract class EnclosedTests {
   // static inner classes using their own runners
}
```

**Comment by blindpirate** [comment]
@jkachika Which Gradle version are you using?
