### ISSUE TITLE
Gradle compilation cannot search resources resource problem

### ISSUE THREAD

**Issue by livk-cloud** [gradle/gradle#23197]
> When I use `AbstractProcessor` for file generation
> `javax.tools.StandardLocation.SOURCE_OUTPUT` Unable to get files in resources

```java

@AutoService(Processor.class)
public class SpringFactoriesProcessor extends AbstractProcessor {

    protected void generateConfigFiles() {
        Filer filer = processingEnv.getFiler();
        FileObject resource = filer.getResource(StandardLocation.SOURCE_OUTPUT, "", LOCATION);
    }
}

```

> I didn't get the file in resources, but Maven can get it, I want to know why
> this a bug with Gradle?

**Comment by xaviarias** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

---

This seems to be a Spring related question, you may reach out to their community.

If it turns out to be a bug in the end, please open a new issue with a full reproducer.
