### ISSUE TITLE
junitXml.mergeReruns not applied to class-level retries

### ISSUE THREAD

**Issue by chris-pirie** [gradle/gradle#23191]
Gradle 7.6, Gradle Enterprise Plugin 3.12; when running a suite of tests and seeing a class-level test failure, we are still getting a failure XML even when retries of the class are successful. Gradle Enterprise 2022.4 shows flaky as expected, but the Failure XML is not merged/removed with the successful retry.

![image](https://user-images.githubusercontent.com/35274949/208019442-be5bac95-cff6-4007-96f4-7607cae5d33c.png)

```
<testcase name="initializationError" classname="com.work.eclipse.ReadFirstPolicyUnitTest" time="0.0">
    <failure message="java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.Boolean...
```

### Expected Behavior
When test retry occurs and the tests pass, expect the failure to be removed just like when a individual test passes on retry.

### Current Behavior
Failure message in the XML persists even though the test retry passed, causing a failure our CI pipeline when validating XML's in JUnit Jenkins plugin.

### Context
Fails our CI runs, causing PR's needing to be re-run, with devs gambling for a successful rerun (drama! 😄)

### Steps to Reproduce 
Create a test that randomly throws an exception on a field initializer; ie:
```
private MyClass myClass = new MyClass();
```
And have constructor randomly throw exception.

### Your Environment
Not sure if it matters, but the exceptions only occurred when the test ran on a remote agent when leveraging Test Distribution. TD Agent v1.6.14

Gradle version 7.6
Gradle Enterprise v2022.4
Gradle Enterprise Plugin v3.12

Build scan URL: private; see Slack for details.

**Comment by xaviarias** [comment]
@marcphilipp could you please take care of triaging this? Thanks.

**Comment by marcphilipp** [comment]
Gradle currently creates synthetic test descriptors for class-level failures rather than reporting the failures on the class itself, e.g. here:
https://github.com/gradle/gradle/blob/3784f518b1979730beb12e9e48309a52d90e7929/subprojects/testing-jvm-infrastructure/src/main/java/org/gradle/api/internal/tasks/testing/junit/TestClassExecutionEventGenerator.java#L59

When a test class is retried successfully, there's no entry for those synthetic "tests" and they get included in the XML report as tests with a single failed execution. There are (at least) two options for solving this issue: (1) report failures on the class-level and generate these synthetic descriptors if the last execution of the test class failed only for the XML report, or (2) mark test descriptors for synthetic tests and filter them out in all but the last execution of a test class when writing the XML report.

**Comment by ghale** [comment]
@chris-pirie I have spent a good bit of time trying to reproduce the issue and have not been successful.  Which isn't to say that I don't think there's a scenario where this can occur.  Basically, when Gradle receives a test class failure before receiving any notification that a test method has started, we would create this synthetic test descriptor that can cause issues during the merge of reruns.  The problem is, I have not been able to reproduce a scenario where this occurs.  I've created a reproducer test that does exactly what you've described above (throws an exception during a field initializer) and am running that on a remote executor, but it always reports the test method being attempted when the initialization failure occurs, which means that it's able to merge the reruns properly.

The one thing that is different is that I'm using a newer version of GE/GE plugin (i.e. 2023.1/3.13).  I don't personally have access to an older instance where I could test this against the exact versions you mentioned.

@marcphilipp Is it possible that the newer version of TD is sending slightly different events back to the build process such that we're no longer triggering this issue?  I notice that especially GE plugin 3.12.4 has some changes related to class-level failures.

**Comment by chris-pirie** [comment]
I also cannot reproduce this. I had upgraded to 3.12.4 based on the release notes hoping to resolve this exact issue but ran into other non-gradle related failures. We have since resolved those issues and are currently using v3.12.6.

I cannot guarantee this is resolved since I only have a few days worth of builds with TD enabled. At minimum is happens way less often (I could replicate every test run pre-3.12.4).

**Comment by marcphilipp** [comment]
@ghale Could you please share your reproducer project?

**Comment by ghale** [comment]
See attached.  

I tried a couple of other variations, too, such as:
- throwing the exception from a static block in the main test class
- throwing the exception from a field initializer in the nested test class
- using parameterized tests
- always failing initialization (i.e. all reruns fail)

In every case, the junit xml always seems to capture the testcase (method) name and merge it correctly.  

[testFailingInit.tar.gz](https://github.com/gradle/gradle/files/11264393/testFailingInit.tar.gz)

**Comment by big-guy** [comment]
We haven't been able to reproduce this
