### ISSUE TITLE
Signing plugin does not sign Gradle module metadata artifact for Ivy publication

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#23302]
### Expected Behavior

The signing plugin should sign all artifacts in a publication.

### Current Behavior

The signing plugin does not sign the module metadata artifact for Ivy publications. It does sign the module metadata artifact for Maven publications.

### Steps to Reproduce 

Run `./gradlew publish` in this sample repository: https://github.com/gradle/configuration-cache-dependency-management

The Ivy module in `ivy-lib/build` does not contain a signature for the metadata artifact. The Maven module in `maven-lib/build` does contain a signature.

### Your Environment

Build scan URL:

**Comment by Chaoba** [comment]
It seems the root cause for this issue is that artifacts derived from module metadata are removed in this [commit](https://github.com/gradle/gradle/pull/23289/commits/1d8cfbef148333b48da01e18690588a4f555767d#diff-873366e0551f281d198beab67ae0900c49c2e77dfed7b8a4a2c891cf88179f61R530).

@adammurdoch I can create a PR for this if you double confirm the root cause.
