### ISSUE TITLE
8.0 RC 1 regression: CodeNarc plugin cannot resolve its dependencies

### ISSUE THREAD

**Issue by davidburstrom** [gradle/gradle#23343]
### Expected/Current Behavior

If I have a build script like

```
plugins {
    id("base")
    id("codenarc")
}

repositories {
    mavenCentral()
}

val codenarcGradle by tasks.registering(CodeNarc::class) {
    this.source(fileTree(".").include("*.gradle"))
}

tasks.named("build").configure {
    dependsOn(codenarcGradle)
}
```

and try to run `./gradlew build`, the build will fail with 

```
Execution failed for task ':codenarcGradle'.
> Could not resolve all files for configuration ':codenarc'.
   > Could not resolve org.codenarc:CodeNarc:3.1.0.
     Required by:
         project :
      > Cannot choose between the following variants of org.codenarc:CodeNarc:3.1.0:
          - runtimeElements
          - shadowRuntimeElements
        All of them match the consumer attributes:
          - Variant 'runtimeElements' capability org.codenarc:CodeNarc:3.1.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'external' but the consumer didn't ask for it
                  - Provides org.gradle.jvm.version '8' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'shadowRuntimeElements' capability org.codenarc:CodeNarc:3.1.0:
              - Unmatched attributes:
                  - Provides org.gradle.category 'library' but the consumer didn't ask for it
                  - Provides org.gradle.dependency.bundling 'shadowed' but the consumer didn't ask for it
                  - Provides org.gradle.libraryelements 'jar' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
```

### Context

I'm running CodeNarc on a set of Gradle scripts written in Groovy. This worked in Gradle 7.6.

### Steps to Reproduce 

[gradle-issue-codenarc.zip](https://github.com/gradle/gradle/files/10319761/gradle-issue-codenarc.zip)

### Your Environment

Build scan URL: https://scans.gradle.com/s/etlkrmzj44vaw/dependencies?toggled=W1swXSxbMCwwXV0

**Comment by ghale** [comment]
Thanks for reporting this, @davidburstrom.  The issue here is the upgrade of the default version of CodeNarc to use the latest, which has multiple variants to choose from.  This slipped past our test coverage because we don't have any tests that test against a non-JVM project.  We'll fix that, but in the meantime you can work around it with one of these options:

Option 1 - Apply the JVM ecosystem plugin.  This won't add any sourcesets or configurations or anything, but it will define some conventions that are sensible in JVM projects, one of which being that it should prefer variants with "external" bundling, which resolves the issue.
```
plugins {
    id("base")
    id("jvm-ecosystem")
    id("codenarc")
}
``` 

Option 2 - Downgrade the CodeNarc version to the previous default (i.e. "2.0.0") which doesn't have multiple variants published.
```
codenarc {
    toolVersion = "2.0.0"
}
```

Either of those should resolve the issue.  We'll look into fixing the problem for the next RC.

**Comment by davidburstrom** [comment]
Thanks you @ghale for the workaround suggestion, the first option was the best one for me.
