### ISSUE TITLE
Gradle 4 does not run Play Tests

### ISSUE THREAD

**Issue by schmitch** [gradle/gradle#2343]
### Expected Behavior
calling `./gradlew testPlayBinary` or `gradle testPlayBinary` should run JUnit tests.

### Current Behavior
runs nothing

### Steps to Reproduce (for bugs)
create a play application:
```
plugins {
    id 'play'
    id 'idea'
}

apply plugin: 'java'

model {
    components {
        play {
            platform play: playVersion, scala: scalaVersion, java: '1.8'
            injectedRoutesGenerator = true
        }
    }
}
```
and a simple test class put into the `test` folder:

```java
public class SimpleTest {

    @Test
    public void simpleTest() {
        assertEquals(1, 2);
    }

}
```

testPlayBinary should run and fail it.

### Your Environment
Mac OS X 10.12.5 and Java:
```
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
```

~~(Fun Fact on Gradle 3.5.1 my twirl templates do not compile -_- need to investigate)~~

**Comment by bmuschko** [comment]
@bigdaz @ghale @big-guy Could you comment on this issue?

**Comment by jjohannes** [comment]
I can confirm this. Looks like a 4.0 regression.

**Comment by jjohannes** [comment]
The issue is caused by applying the java plugin in addition to the `play` plugin. The Java plugin alters the `Test` tasks during application. The example works if `apply plugin: 'java'` is removed.

However, it used to work before 4.0. This commit caused the changed behavior: [Use FileCollection of classesDirs from SourceSetOutput directly instead of convention mapping](https://github.com/gradle/gradle/commit/b72eeca5a06b1fcd21518f079854bcc2a2cf9820)

Here is an integration test reproducing the issue: https://github.com/gradle/gradle/commit/58a19b81f60d77c3c99170ae7aa73b01a5534536
Reverting the commit above fixes it: https://github.com/gradle/gradle/commit/23143ec2f4fc2f6a0c18e42abf642b9370cc4119

@big-guy what's your take on this?

@schmitch For your concrete usecase: Do you need the Java plugin in addition to the play plugin?

**Comment by schmitch** [comment]
well at the moment I just toyed with various things with gradle and play.

**Comment by jjohannes** [comment]
After further discussing this with @big-guy, we decided to revert [Use FileCollection of classesDirs from SourceSetOutput directly instead of convention mapping](https://github.com/gradle/gradle/commit/b72eeca5a06b1fcd21518f079854bcc2a2cf9820) in 4.1.
