### ISSUE TITLE
Multiple dependency declarations return `null`.

### ISSUE THREAD

**Issue by nnym** [gradle/gradle#23452]
Dependency declarations that declare multiple dependencies return `null` which makes them non-nestable.

### Expected Behavior
```groovy
include(implementation(
    "abc:def:123",
    "ghi:jkl:456"
))
```
`abc:def:123` and `ghi:jkl:456` are added to the configurations `implementation` and `include`.

### Current Behavior
`implementation(..., ...)` returns `null` which is not a valid dependency notation so an exception is thrown. However, `include(implementation("abc:def:123"))` works.

### Context
I was trying to add multiple dependencies to multiple configurations. I understand that I can use
```groovy
include(
	implementation("abc:def:123"),
	implementation("ghi:jkl:456")
)
```
or
```groovy
include([
	"abc:def:123",
	"ghi:jkl:456"
].collect {implementation(it)})
```
but the ideal solution would be the example that I've shown under "Expected Behavior".

### Steps to Reproduce
https://github.com/auoeke/gradle-nested-dependencies/blob/groovy-dsl/build.gradle is an example build script that reproduces the problem.
https://github.com/auoeke/gradle-nested-dependencies/actions/runs/3878006872/jobs/6613692543

### Your Environment
OS: Artix Linux
JDK: Temurin 19.0.1+10
Gradle: 8.0-20230109000231+0000

#

https://github.com/gradle/gradle/blob/b93888cebcd246df1f822042cfe3323cd412f252/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/dsl/dependencies/DynamicAddDependencyMethods.java#L58-L61
I theorize that this issue can be solved by replacing the above code by `return DynamicInvokeResult.found(normalizedArgs.stream().map(arg -> dependencyAdder.add(configuration, arg, null)).toList());` or something similar.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed, response time may vary.

---

I am not sure this is a pattern we want to promote. If you have dependencies in multiple configurations like that, you may have surprises if you mutate them.

```
configuration1(configuration2("g:a:v"))
```

Can I ask why you do this instead of leveraging `extendsFrom`?

Note that the list notation does not work in the Kotlin DSL at all.

**Comment by melix** [comment]
I am not particularly fond of this idea and the associated PR. We have a mechanism for "common dependencies" which is configuration inheritance. This also has the advantage of being modeled properly (a configuration has a name, and plugins/build code can refer to those dependencies). The proposed notation is IMO confusing. I also remember we kind of phased out the ability to declare multiple dependencies at once, because it's also confusing.

**Comment by big-guy** [comment]
I don't think we want to support this kind of nesting pattern, sorry. If anything, we should deprecate that `implementation(...)` returns a `Dependency`. 

Like the others have said, this doesn't work at all in Kotlin DSL and there are alternatives.

I think the other better options are:
1. Use another configuration that the others extend from as the bucket of common dependencies
2. Duplicate the dependency on each configuration that requires it
3. Loop over configurations by name (like you mention above)

There may be other options depending on why you need to have the same declared dependencies in multiple configurations.

**Comment by auoeke** [comment]
> The proposed notation is IMO confusing. I also remember we kind of phased out the ability to declare multiple dependencies at once, because it's also confusing.

How are they confusing?

> I don't think we want to support this kind of nesting pattern, sorry.

That's quite unfortunate. Apology accepted.
