### ISSUE TITLE
Rectify Java toolchain related shortcomings

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#23519]
1. The error message `No compatible toolchains found for request specification: {languageVersion=11, ...` is misleading. A higher language level JVM could be considered "compatible" by some, but our matching is strict, so we don't consider those. This should be clear from the error message.

2. If no toolchain repositories are configured the error message should clearly indicate the lack of this configuration. Right now the error message is the generic `No compatible toolchains found...`.

3. In Gradle 7.6 we have deprecation nagging in case there are no toolchain repositories configured, but it gets activated only when auto-provisioning actually happens. This is not enough, not even for builds that rely on the feature, because even those only download a toolchain once and then just use it in subsequent runs. We should always nag, if toolchains are being used. This needs to be backported to `7.6.1`.

4. In Gradle 8.0 it is possible for a build to run successfully based on a previously auto-provisioned toolchain, but without having toolchain download repositories configured. This same build would clearly fail in a clean environment, so even when it succeeds, it should issue warnings about this fact. (We can clearly identify auto-provisioned toolchains, based on their location.)

5. Toolchain repository-related documentation should clearly state which repositories are real, usable ones, and which are made-up examples. 

6. Also, documentation should make it even clearer that there are two parts to configuring toolchain repositories: one is applying plugins of the definitions and then the explicit list of which ones to use and in what order.

**Comment by ljacomet** [comment]
Changes are merged

**Comment by pwagland** [comment]
Looking at comment 6, it is unclear to me how I am supposed to configure this. I have a 7.6.1 pre-release, and have added:
```
toolchainManagement {
  jvm {
    javaRepositories {
      repository('adoptium') {
        resolverClass = AdoptiumResolver
      }
    }
  }
}
```
to `settings.gradle`. However, it complains that `jvm` isn't valid, which I can live with, since the docs also state:
> The jvm block in toolchainManagement only resolves after applying a toolchain resolver plugin.

However, there is no indication in the docs, how one is meant to apply the default "AdoptiumResolver" plugin.
```
plugins {
  id 'AdoptiumResolver'
}
```
doesn't work, and so I'm not quite sure how to work out what the default resolver is to install. Or failing that, if I want the build to fail if it _isn't_ available locally, there is no clear documentation on how to disable that either, except by adding something to `gradle.properties`, which one can't put into the repository.

That is, if the current defaults _are_ good enough, how can we replicate them?

**Comment by ljacomet** [comment]
That `AdoptiumResolver` was a fake for the example, it has been renamed in docs.
The only real plugin produced by Gradle can be found [here](https://github.com/gradle/foojay-toolchains).

**Comment by pwagland** [comment]
Thanks @ljacomet, does that mean that as of 8.0, gradle will have no way to download a JVM, and that we will need to install that foojay resolver?

Can the docs please be updated to indicate that the only way to remove that deprecation warning is to configure it in such a way?

Am I also correct in assuming that the inbuilt toolchainResolvers are going to be removed, and not exposed as an API?
