### ISSUE TITLE
Deprecate org.gradle.cache.cleanup property

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#23533]
Now that we have this configurable via dsl, we want to remove the magic system property.

**Comment by ThadHouse** [comment]
Is there a way to deprecate properties? We were the ones that originally added that property, and we're fine with it being removed from newer versions, as long as it doesn't error out if that property exists on newer versions. We need to be able to support both newer and older versions of Gradle on the same system, and since that property only works if its globally set, newer versions of gradle can't error if its found.

**Comment by big-guy** [comment]
#23854

**Comment by ThadHouse** [comment]
@big-guy That is a problem. Its a global flag, and our builds need to support a mix on both Gradle 7 and Gradle 8. That PR will mean that gradle 8 will always print out a deprecation warning no matter what, with no way to solve it.

**Comment by ghale** [comment]
I think you might have misunderstood the instructions that PR adds to [the upgrade guide](https://github.com/gradle/gradle/pull/23854/files#diff-8e56453a198280f3047582317efbdbd49abab9aa6de52aa3073df4e4d4d045e4R264).  You can continue to have the property in gradle.properties as long as you _also_ set it via the DSL (either to disable it or to some other value).  This allows you to use the property for older versions of Gradle, but avoid the deprecation warning in Gradle 8.1+.  Does that make sense?

Does that resolve your problem, or am I misunderstanding?

**Comment by ThadHouse** [comment]
If you have the dsl property, it won't print the deprecation warning even if the property still exists? If thats the case thats good, its just not clear from the PR how that happens.
