### ISSUE TITLE
Since Gradle 7.6 my integration tests fail - but report "BUILD SUCCESSFUL"

### ISSUE THREAD

**Issue by Zordid** [gradle/gradle#23602]
I upgraded to Gradle 7.6 and at first everything seemed to be fine. Then I noticed a *decrease* in unit tests according to test reports in my Jenkins pipeline.
But I did not delete any tests.
Turns out: my integration tests fail with weird exceptions - but Gradle still reports "BUILD SUCCESSFULL" even though on the console you can see Exceptions and breaking tests.

The log reads like this:
```
+ ./gradlew :integrationTest
> Task :compileKotlin UP-TO-DATE
> Task :compileJava NO-SOURCE
> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE
> Task :jar UP-TO-DATE
> Task :inspectClassesForKotlinIC UP-TO-DATE
> Task :processIntegrationTestResources
> Task :compileIntegrationTestKotlin
> Task :compileIntegrationTestJava NO-SOURCE
> Task :integrationTestClasses
> Task :integrationTest

Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not read message from '/127.0.0.1:60814'.
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:94)
	at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionReceive.run(MessageHub.java:270)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:72)
	at org.gradle.internal.remote.internal.hub.InterHubMessageSerializer$MessageReader.read(InterHubMessageSerializer.java:52)
	at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:81)
	... 6 more

BUILD SUCCESSFUL in 2m 2s
7 actionable tasks: 3 executed, 4 up-to-date

It was by pure luck I saw these exceptions only because the number tests seemingly decreased...

```
### Expected Behavior
First: my tests should run just like they did with Gradle 7.5.1 before.
Second: I would love some explanation on that issue...
Thirdly: IF a build produces exceptions and skipped / omitted tests, it should not SUCCEED. It should fail.

### Current Behavior
My build succeeds even though the build is not properly done. Tests are missing without any notice which basically is the worst case scenario. Tests should never disappear unnoticed.

### Context
Happens locally on a MacBook as well as on a Jenkins server (Windows)

### Steps to Reproduce 
I have no idea on how to do this... :-(

### Your Environment

Build scan URL:
https://gradle.com/s/v77ms75oxijm6

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.

---

Maybe you can reduce one of the offending test so that you can share it with us.

**Comment by Zordid** [comment]
Downgrading this exact build to 7.5.1 yields a perfectly working build immediately. 
I really have no idea how I can make this a reproducible example. I don't even understand what this issue is hinting at. I don't know what this messaging is all about, is has nothing to do with our application - I can only guess it is some Gradle inner working things.

My biggest issue apart from having an issue: Why does Gradle allow an Exception, skipped tests and tests that have not even started to still result in a SUCCESS? How is that even possible? 

Had I not seen the decrease in test number, I would have lived with this for a very long time, never aware of any exception.

The least I think Gradle should do is: Exception -> BUILD FAIL...

**Comment by Zordid** [comment]
It's also not one offending test. I don't even know what test is run. It just happens. And the only thing changed is the Gradle jump from 7.5.1 to 7.6.

**Comment by Zordid** [comment]
Also, a for me very disturbing fact: why is one test "skipped" and a few others are not even mentioned anywhere - aka they did not run, neither pass nor fail... I thought skipping tests is some I can do on purpose by deactivating a certain test. But not like this... What does "skip" mean for Gradle?

**Comment by eskatos** [comment]
The error points to the messaging system for communication between the Gradle Daemon and the Gradle Test Executors. It seems something in your setup creates conditions for an error in the protocol. Without a reproducer we can't really dig deeper. Maybe you can extract something from your build that reproduces?

**Comment by Zordid** [comment]
Another question: how can I relate that exception to a *specific and concrete* test case? The log reveals nothing and looking at the console, I do not see any indication on which test runs when... Given my very first log in the OP - which test case was running?

**Comment by Zordid** [comment]
Is there a way to make a build FAIL if there is one skipped test? This would be at least a work around us realizing something went wrong.

**Comment by Zordid** [comment]
Hi @eskatos - I was able to remove almost ALL of our production code and still reproduce this issue. I have set up a repo that you can check out and see it for yourself: https://github.com/Zordid/gradle_issue_23602

**Comment by eskatos** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

----

I confirm I can reproduce with the provided reproducer. Thanks a lot for making it happen.

7.5.1 https://scans.gradle.com/s/sm4mbrxfmitoy/tests/overview
7.6 https://scans.gradle.com/s/yny3u2tahi2oa/tests/overview#:integrationtest-0-mq.mqit-1-mq-source-can-receive-a-null-bytes-message()-2

**Comment by Zordid** [comment]
Hi @jvandort! That's unfortunate to hear. This is already the most minimized version I was able to come up with.
I got other tests for Kafka using Testcontainers, but only this MQ tests exhibits this buggy behavior.
An important information for you: this example requires Docker (for Testcontainers) and amd64 architecture because the required MQ system is only provided for that architecture. In case you use Apple Silicon, things are a little bit more complicated and I don't even know if the behavior is identical.
For using Apple Silicon, you need to use podman instead of Docker and simulate an the amd64 architecture using an emulation.
Preferably you should do this on the fitting hardware...

I am sorry there is not much to downsize. But that the nature of dealing with integration tests and servers and networks in tests.

I hope you can get this running somehow. For us this is a complete deal breaker and even if you cannot find the cause, we would need a Gradle version that fails the build on such errors.

**Comment by jvandort** [comment]
I will give this a try on x86 hardware.

**Comment by jvandort** [comment]
The problem here appears two-fold. Your tests are throwing an exception, originating from the `com.ibm.mq:com.ibm.mq.allclient` library, however these exceptions are quite complex and are not properly de-serialized when they are sent from the test process to the Gradle daemon. I've been able to construct a simple test class to reproduce this behavior directly. In the process of de-serialization, we lose our place in the message stream, leading to the "Could not read message from" warning. The second issue is that even though we detect this problem reading the message stream, we do not end up subsequently failing the tests. 

Producing this slimmed reproducer is a major step towards solving this issue, but I will need to take some further time to investigate the root cause of the errors during serialization. I am not sure yet why this only shows an error in `7.6`, however it appears the test may have been failing pre-7.6 as well, though it is only apparent now. 

This issue is my current primary focus, and I should have some more details in the coming days. 

For reference, below is the slimmed reproducer class:
```
            package com.example;
            import org.junit.jupiter.api.Test;
            public class ExampleTest {
                @Test
                public void test() throws Exception {
                    throw new CustomException();
                }
                public static class CustomException extends Exception {
                    private Object writeReplace() {
                        return new WriteReplacer();
                    }
                }
                public static final class WriteReplacer implements java.io.Serializable {
                    private Object readResolve() {
                        return new RuntimeException();
                    }
                }
            }
```

**Comment by Zordid** [comment]
Thanks @jvandort for finding more interesting details. These tests are usually not failing, so I am not sure why exceptions are even sent between the test process and Gradle daemon. And, as mentioned on 7.5.1 this is not an issue - at least it never showed up. Do you think it makes a difference if I use JUnit tests or other test frameworks, like Kotest? (but I guess they also use a JUnit runner under the hood...) Thanks a lot!

**Comment by jvandort** [comment]
@Zordid It seems that you are unable to call `getBodyLength()` on a `BytesMessage` created by `context.createBodyLessBytesMessage()` since it is write-only. See:

https://github.com/Zordid/gradle_issue_23602/blob/main/src/main/kotlin/utils/SuspendLegacyExtensions.kt#L51
https://github.com/Zordid/gradle_issue_23602/blob/main/src/integrationTest/kotlin/mq/MQIT.kt#L133

That is the exception that I saw being thrown.

**Comment by Zordid** [comment]
@jvandort THANK YOU.

This is absolutely insane to me. On neither my work laptop, nor or CI, neither in IntelliJ nor Gradle Builds prior to 7.6 has this problem ever been visible. Now that you point this out, I also read it in the documentation, wrap my `getBodyLength()` call in another try catch block and SEE this exception being thrown.

To this minute the test (and all others) pass on Jenkins with Gradle 7.5 - but now that I once put this in a try catch block, it bubbles up all the time.

Now I can finally fix this real cause - but the question that remains unanswered is why this showed so strangely with Gradle 7.6 for the very first time. It would have been so easy if this test had always just failed with `JMSCC0046: It is not permitted to call method 'getBodyLength' on the message because the message body is write-only.` 

I simply cannot understand the circumstances, but are indeed happy to see a way out of this.

For Gradle I wish you can find out why all of the tests got stopped and the build still succeeds. This IMHO is an issue to tackle...

**Comment by Zordid** [comment]
You really, really helped me a lot finding a bug inside our application because of this. All in all, testing is so valuable and working together like this a pleasure.
Even inside IntelliJ my unit test always succeeded, but never actually ran!
I hope future versions of Gradle make the fact that there is something funny going on with such exceptions very obvious.
