### ISSUE TITLE
dependency verification should strip non-essential information from verification-keyring.keys

### ISSUE THREAD

**Issue by vlsi** [gradle/gradle#23607]
Gradle can keep a copy of PGP public keys under gradle/verification-keyring.keys, which is fine.
However, PGP keys can contain information that might be considered PII: names, email addresses, and pictures.
A side-effect is that the keyring consumes much more space than is really needed.

For example, the current keyring in gradle/gradle
https://github.com/gradle/gradle/blob/d94e21e0a8d3e2d24a0bbade29109ad9115fe1d8/gradle/verification-keyring.keys

contains the following public key: dddee87612e9fb95f5c8d91e411063a3a0ffd119
https://keyserver.ubuntu.com/pks/lookup?search=0xdddee87612e9fb95f5c8d91e411063a3a0ffd119&fingerprint=on&op=index
The key contains lots of irrelevant "signatures" (e.g. "revocation signature") which are not really used in the verification process.

I guess it might be worth keeping only public key packets, and removing custom attributes, etc.

It would make the keyring smaller.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

***

If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
