### ISSUE TITLE
Dependency variant attribute bindings are lost/broken when used in a referenced included build

### ISSUE THREAD

**Issue by mcumings** [gradle/gradle#23668]
Scenario:
- A build has a dependency which requires an attribute to be specified in order to disambiguate the dependency during variant resolution
- The build is included into an outer project using the included build mechanism

### Expected Behavior

The build can be included and dependency variant resolution succeeds, resolving the dependency using the attribute specified in the included build's build configuration.

### Current Behavior

When including the build into an outer project, it appears as if the attribute specification is lost.  The outer project then fails in a manner which seems to not be reconcilable:

```
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve io.github.pdvrieze.xmlutil:core:0.84.3.
     Required by:
         project : > project :buildPlugins > io.github.pdvrieze.xmlutil:serialization-jvm:0.84.3
      > The consumer was configured to find a library for use during runtime, compatible with Java 17, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0-rc-2'. However we cannot choose between the following variants of io.github.pdvrieze.xmlutil:core:0.84.3:
          - androidRuntimeElements-published
          - jvmRuntimeElements-published
        All of them match the consumer attributes:
          - Variant 'androidRuntimeElements-published' capability io.github.pdvrieze.xmlutil:core:0.84.3 declares a library for use during runtime, packaged as a jar:
              - Unmatched attributes:
                  - Provides attribute 'net.devrieze.android' with value 'true' but the consumer didn't ask for it
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 17)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0-rc-2')
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but the consumer didn't ask for it
          - Variant 'jvmRuntimeElements-published' capability io.github.pdvrieze.xmlutil:core:0.84.3 declares a library for use during runtime, packaged as a jar:
              - Unmatched attributes:
                  - Provides attribute 'net.devrieze.android' with value 'false' but the consumer didn't ask for it
                  - Doesn't say anything about how its dependencies are found (required its dependencies declared externally)
                  - Doesn't say anything about its target Java version (required compatibility with Java 17)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0-rc-2')
                  - Provides release status but the consumer didn't ask for it
                  - Provides attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' but the consumer didn't ask for it
 ...
```

Note in the above log output this attribute information:
```
Provides attribute 'net.devrieze.android' with value 'true' but the consumer didn't ask for it
```

This seems to indicate that the attribute specification in `buildCode/buildPlugins/build.gradle.kts` is no longer applied (i.e. `the consumer didn't ask for it`). 

Using the same build code but placed in buildSrc instead of in an included build works as expected.

NOTE: I tried using a `configurations.all { ... }` block in the outer project to specify the attribute in an attempt to resolve this but A) it had no effect, and B) this wouldn't solve the problem for plugin authors anyhow, since it would require consumers to reconcile internal plugin implementation details at the consumers' points of use.

### Steps to Reproduce 

Reproducer project attached: [repro-attribute-issue.tar.gz](https://github.com/gradle/gradle/files/10510962/repro-attribute-issue.tar.gz)

The project configuration as packaged will fail when `./gradlew help` is run.

Even in this failing state, the included build project works correctly when built independently from the outer project:
```
$ cd buildCode/buildPlugins/
buildCode/buildPlugins $ ../../gradlew build

BUILD SUCCESSFUL in 724ms
7 actionable tasks: 2 executed, 5 up-to-date
buildCode/buildPlugins $
```

The outer project's `build.gradle.kts` file references an empty plugin in both the `buildSrc` and `buildCode/buildPlugins` locations.  Commenting out the `id("included-build-plugin")` reference demonstrates that the `buildSrc` approach works as expected.

### Your Environment

```
------------------------------------------------------------
Gradle 8.0-rc-2
------------------------------------------------------------

Build time:   2023-01-17 10:25:18 UTC
Revision:     8dcd942c9efaac6cb7f577f3b7a7521d0801704d

Kotlin:       1.8.0
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.4.1 (Azul Systems, Inc. 17.0.4.1+1-LTS)
OS:           Mac OS X 12.6.1 aarch64
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

There are couple things at play here, making for a complicated user experience.

1. Attributes declaration are not "transitive"
So when you add you attribute with the following, it only applies to `io.github.pdvrieze.xmlutil:serialization-jvm` but the selection issue is with `io.github.pdvrieze.xmlutil:core`.
```
val attr = Attribute.of("net.devrieze.android", Boolean::class.javaObjectType)
dependencies {
    api("io.github.pdvrieze.xmlutil:serialization-jvm:0.84.3") {
        attributes {
            attribute(attr, false)
        }
    }
}
```
The [published metadata](https://repo.maven.apache.org/maven2/io/github/pdvrieze/xmlutil/serialization-jvm/0.84.3/serialization-jvm-0.84.3.module) of `io.github.pdvrieze.xmlutil:serialization-jvm` should itself indicate what value it needs for the `net.devrieze.android` attribute from `io.github.pdvrieze.xmlutil:core`. This is something to fix in the build of that project.

2. Resolution works in `buildSrc` and `buildPlugins` because a disambiguation rule is registered for the `org.jetbrains.kotlin.platform.type` attribute.
3. Application from `buildSrc` succeeds because the contribution on its plugin is resolved in the context of `buildSrc` itself.
4. Resolution fails in the importing project when applying the `buildPlugins` plugin because resolution is done through the applying project. Unfortunately that one does not have the disambiguation rule for `org.jetbrains.kotlin.platform.type` registered. I have no idea why. This is a question for the Kotlin Gradle Plugin team.

You might want to open an issue for this on the JetBrains YouTrack at https://kotl.in/issue.

There is nothing to be fixed in Gradle itself at this stage. We have plans to improve variant aware error messages in the future though.
