### ISSUE TITLE
Provide a mechanism to access or resolve all detached configurations for dependency verification

### ISSUE THREAD

**Issue by rygo-msft** [gradle/gradle#23666]
Dependency Verification is currently difficult to use with plugins that leverage detached configurations. Because the configurations are not accessible to us, we don't have a way to force them to resolve when updating our locks and verification metadata.

The only work-around is to identify the tasks that use detached configurations and execute them. This adds a lot of time to taking plugin updates when the process should be very straight forward.

### Expected Behavior

`Realizing` all tasks should be enough to identify all configurations which can then be resolved in a utility task.
See below code snippet for task example

### Current Behavior

Only concrete configurations can be resolved programmatically.

### Context

We leverage the below helper task and command to resolve dependencies. This task misses the detached configurations used by many plugins including the Android Gradle Plugin. Running the full set of tasks can be expensive, and the specific tasks tend to change version to version. With AGP 7, if you run `assembleRelease lintRelease` you will find dependencies that aren't resolved outside of detached configurations.

> gradlew resolveAndLockAll --write-locks -M sha256

```
project.tasks.register("resolveAndLockAll") {
        doFirst {
            assert gradle.startParameter.writeDependencyLocks
        }
        
        doLast {
            // Force all tasks to realize. To find any task-created configurations
            project.tasks.all { }

            def typeAttribute = Attribute.of("artifactType", String.class)
            project.configurations.findAll {
                it.canBeResolved
            }.each {
                logger.info "Resolve configuration $it"
                try {
                    // https://issuetracker.google.com/issues/241812824
                    def allJars = it.incoming.artifactView {
                        it.attributes.attribute(typeAttribute, "jar")
                    }.artifacts.artifactFiles.files
                } catch (e) {
                    handleResolutionException(project, it, e)
                }
            }
        }
    }
```

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is a tough one to solve as the flexibility of Gradle indeed means that some configurations can be created by tasks execution itself.

While moving forward with configuration cache and project isolation, these behaviours will become illegal.

Until then, this is unlikely to be solved for 100% of cases.

Because of that, I will be closing this feature request for now. We might get back to it in the future, following the evolution of Gradle.

One thing to do is to go to plugin authors and explain the issue and see if they could use properly registered configurations instead.
