### ISSUE TITLE
Improve handling of "clean" for lifecycle tasks like "classes"

### ISSUE THREAD

**Issue by Jaizkibel** [gradle/gradle#2367]
Executing this task always results in an "UP-TO-DATE" message

There is a old JIRA Ticket concerning this problem, wich was closed because nobody seemed to be interested in a fix any more:

[https://issues.gradle.org/browse/GRADLE-2172](url)

Now i am interested, because IntelliJ uses this task for the "Rebuild project" action when the "Delegate IDE build/run actions to gradle" option is activated

**Comment by bmuschko** [comment]
The `classes` task is a lifecycle task. It does not define any outputs. The only purpose it serves is to define dependencies on other tasks. If you want to clean the outputs of the Java compilation task specifically then you will need to execute `cleanCompileJava`.

**Comment by oehme** [comment]
We should find a better model for this, e.g. if you clean a lifecycle task - clean everything that it depends on. Just as an idea. The fact that `classes` is a lifecycle task is not visible to the user. If we don't make it work like the user expects, then we should remove clean tasks for lifecycle tasks. The fact that the IntelliJ team got trapped by this shows that this is confusing even for advanced users.

**Comment by bmuschko** [comment]
> then we should remove clean tasks for lifecycle tasks

+1

**Comment by ldaley** [comment]
Similarly, it would be interesting to know how many users actually understand what “lifecycle tasks” are. I don't think the number is high.

**Comment by oehme** [comment]
@vladsoroka Since the "Delegate build to Gradle" option was mentioned here: Calling `cleanClasses` has no effect, since `classes` is just a lifecycle task that depends on the actual compile tasks. I think the simplest thing would be to call `clean` when the user clicks "Rebuild Project".

**Comment by vladsoroka** [comment]
@oehme I was thinking about `--rerun-tasks` option to force sources rebuild, wdyt?
Btw, can I turn off up-to-date state pre gradle task using init script?

**Comment by oehme** [comment]
You can, using `task.upToDateWhen { false }`. What's the use case?

Using `--rerun-tasks` would work, though it's a pretty big hammer. How much do people use "Rebuild Project"? Rerunning every task would be pretty expensive if users call this often.

**Comment by vladsoroka** [comment]
@oehme the rebuild(project/module or recompile file) IntelliJ action means recompile sources without incremental compilation feature.
Since last year IntelliJ supports delegation of these actions to underlying build system, so we are experimenting with the gradle way to handle it.

> Using --rerun-tasks would work, though it's a pretty big hammer. 
Does it mean that `--rerun-tasks` will cause more overhead than `clean` task?
(Note, we are interested in compiling sources only, not jar/zip/etc archives)

Let's consider rebuild of the sources of the `main` sources set.
Will it be correct to run `classes` task with 'task.upToDateWhen { false }' options injected using init-script?

**Comment by vladsoroka** [comment]
@oehme Using 'clean' task is a big hammer also, e.g. I should be able to rebuild sources of the `test` sources set w/o affecting of the `main` sources and other non test related stuff (javadoc/sources jars etc).

**Comment by oehme** [comment]
The `classes` task has no outputs. Marking it as upToDate=false has no effect, as it does nothing.

Afaik `--rerun-tasks` would ignore the build cache, though @wolfs would know better.

If you just want to clean compile tasks, something like `tasks.withType(AbstractCompile) { upToDateWhen = { false }}` would work. The question though is why the user would want that, since Gradle cleans outdated classes anyway.

**Comment by wolfs** [comment]
`--rerun-tasks` would not pull from the build cache, but will upload build results into the build cache for cacheable tasks. I guess this is what the user wants. `upToDateWhen = { false }` has the same effect on the build cache - i.e. no pulling from the cache but pushing to the cache(s).
I guess when someone presses `Rebuild ...` in IDEA something went wrong and they want to re-execute everything - not using the build cache etc... So using `upToDateWhen = { false }` or `--rerun-tasks` might be the right approach.
