### ISSUE TITLE
Add extension and classifier properties to ArtifactResult

### ISSUE THREAD

**Issue by belovaf** [gradle/gradle#23702]
`ResolvedConfiguration::getResolvedArtifacts` return `ResolvedArtifact` which provides all the information about resolved artifacts including `extension` and `classifier`.
I really miss these properties in `ResolvedArtifactResult` returned by `ArtifactCollection::getResolvedArtifacts`.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

I do not think that exposing a Maven concept like `classifier` at that level makes sense. With `ResolvedArtifactResult` we are in the territory of variant aware resolution and the concept does not make sense there.

Could you share some use case(s) for needing this added APIs?

**Comment by belovaf** [comment]
Thank you for gradle! :)

I want to resolve some configuration with external dependencies and publish the resolution result as an outgoing variant with a flat (non transitive) dependency list.
But i can't create a dependency from a resolved artifact without all parts of dependency notation.

**Comment by TravDev01** [comment]
I'm running into the same problem. I'm trying to implement a plugin for a tool that completely works with maven tooling. Therefore I need a valid gav (with classifier and extension).

Everything works fine when I obtain the dependencies with `myConfig.getAllDependencies()`, except for project dependencies.
Project dependencies are not working in this way because the artifacts are not available there ([See DependencyMapNotationConverter](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/notations/DependencyMapNotationConverter.java#L55)).
Therefore I have to use ResolvedArtifactResult for project dependencies, where the extension and classifier for external Artifacts is not available.

I'm trying now to workaround it and mapping the results together, but it feels not correct.
Maybe I missed something in my implementation.

**Comment by TravDev01** [comment]
I was wondering how gradle construct a unique id when you have two identical artifacts which are only differs in classifier and extension and found out that the classifier and extension is available, but not exposed to the api.
The DefaultModuleComponentArtifactIdentifier has a IvyArtifactName where you can get the classifier and extension.

So is there any Chance to expose this to the api? Or is there any reason why not?
For Project dependencies it's exposed in PublishArtifactLocalArtifactMetadata.

I'm still looking for a elegant way to obtain the group and version for Project dependencies from ResolvedArtifactResult.

**Comment by sschuberth** [comment]
> I do not think that exposing a Maven concept like `classifier` at that level makes sense. With `ResolvedArtifactResult` we are in the territory of variant aware resolution and the concept does not make sense there.

But couldn't these Maven-specific concepts be mapped to generic attributes?

**Comment by ov7a** [comment]
Sorry for the late reply.

As @CRogers said, it can be resolved by accessing the filename. 
Gradle offering an API for that would be limiting with regards to the flexibility of the Gradle dependency model and couldn't be always correct.

So we're closing this as there is a workaround and it's unlikely to be implemented.

**Comment by CRogers** [comment]
> As @CRogers said, it can be resolved by accessing the filename.

To be clear, I don't think this is a reasonable solution to the problem, as it's super fragile since it depends on the internals of how gradle caches work. I presented it as a "look what we'd be forced to do". Were this format to change any point (and there is no guarantee it won't, as it's not part of the public api) the hack would no longer work. Similarly for using reflection and `toString()` - these are not real production quality fixes and liable to break at any time.

There must be some way of exposing this information in a configuration cacheable way - perhaps at a different level or via another maven specific api to get this `classifier`/`extension` info for maven artifacts?

**Comment by sschuberth** [comment]
> There must be some way of exposing this information in a configuration cacheable way

What about my idea from [above](https://github.com/gradle/gradle/issues/23702#issuecomment-1525890397) to use [attributes](https://docs.gradle.org/current/userguide/variant_attributes.html)?
