### ISSUE TITLE
Multi project dependency tree seems incorrect

### ISSUE THREAD

**Issue by mjaggard** [gradle/gradle#23814]
### Expected Behavior
When I have a `shared` project and a `api-v1` project that contains `implementation project(':shared')` as a dependency, it seems that the dependant project uses `compileJava` rather than `classes` as the task that is used.

### Current Behavior
Adding a `dependsOn myWeavingTask` to the `classes` task should make the dependent project depend on `myWeavingTask`. 

### Context
I'm trying to run some bytecode manipulation after the Java compilaiton. I've successfully made this work by changing the `destinationDirectory` of the `compileJava` task and then adding a `finalizedBy myWeavingTask` too. This works fine for a single project but in any dependant projects I get an error:
```
Execution optimizations have been disabled for task ':api-v1:compileJava' to ensure correctness due to the following reasons:
  - Gradle detected a problem with the following location: '/Users/me/myProject/shared/build/classes/java/main'. Reason: Task ':api-v1:compileJava' uses this output of task ':shared:myWeavingTask' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to https://docs.gradle.org/7.6/userguide/validation_problems.html#implicit_dependency for more details about this problem.
```

### Steps to Reproduce 
Described above. Reproducer project https://github.com/mjaggard/dependency-jpa

### Your Environment
MacOS, Gradle 7.6

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

`classes` is a lifecycle task that depends on both `javaCompile` and `processResources`.
Dependent projects don't need the resources for their own compilation, that's why they depend on `compileJava` only.

For post processing the output of `compileJava` you should be able to add a "doLast" action to `compileJava` instead. Don't forget to declare your inputs for this added action.

**Comment by mjaggard** [comment]
Well that explains my other issue that my dependent projects don't seem to have access to my shared resources!

Why is this the decision made? I would expect a dependant project in Gradle to work in the same way as if a shared library was packaged as a JAR and a dependency created that way but that would include packaged resources such as templates. I guess this is an awkward breaking change to make now 😔
