### ISSUE TITLE
gradle check ignores the local jdk

### ISSUE THREAD

**Issue by zz541843** [gradle/gradle#23843]
https://docs.gradle.org/current/userguide/toolchains.html#sec:auto_detection
This document says that gradle can read idea  jdk, but run gradle check still download adoptopenjdk, I then configured JAVA_HOME and ran gradle check again to read this jdk version.
How can I configure gradle so that it recognizes idea jdk ?

**Comment by zz541843** [comment]
![image](https://user-images.githubusercontent.com/72638366/218258130-2d9a5724-fe95-4762-8674-6898bbc9bc17.png)

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

The feature is about JDKs that have been downloaded by IntelliJ, not the ones IntelliJ knows about. If Coretto was downloaded by IntelliJ, then please provide a reproducer, otherwise, it's working as intended.
