### ISSUE TITLE
Executing Gradle builds on Jenkins page screenshots

### ISSUE THREAD

**Issue by hythloda** [gradle/gradle#23879]
The screenshots in the docs for the [Executing Gradle builds on Jenkins page](https://docs.gradle.org/current/userguide/jenkins.html) should be updated.

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.
 
***

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

***

In order to contribute updated screenshots, you will need a valid Jenkins setup.
Changes to be done in `jenkins.adoc`
