### ISSUE TITLE
@since should be used in public API

### ISSUE THREAD

**Issue by szpak** [gradle/gradle#2391]
It's very common to miss `@since` tag in Javadoc for elementes (annotations, methods, ...) in the Gradle public API. Due to that it's quite unpleasant for a plugin author to check with which version his/her plugin is compatible using for example [`@CacheableTask`](https://docs.gradle.org/4.0/javadoc/org/gradle/api/tasks/CacheableTask.html).

### Expected Behavior
Javadoc for public API (annotations, methods, ...) should contain `@since` tag (at least for new elements adding in Gradle 4.x+)

### Current Behavior
No information in which version given API element has been added.

**Comment by bmuschko** [comment]
Usually we are doing a relatively good job in adding and checking `@since` and `@Incubating` annotations. We also [started to add more automation](https://github.com/gradle/gradle/pull/2365) around these aspects though there's definitely room for improvement.

@lptr Could you please add the `@since` and `@Incubating` annotation to `@CacheableTask`?

**Comment by bmuschko** [comment]
We are actively working on improving the points you mentioned above and track this with internal issues. I am going to close this issue for now. Thanks for speaking up on these issues.

**Comment by szpak** [comment]
Great to hear. Probably I just had bad luck with some elements I was looking at in the past.

**Comment by bmuschko** [comment]
@szpak Certainly let us know if you find other place where `@since` is missing.
