### ISSUE TITLE
Gradle fails to compile kotlin with Transformer api

### ISSUE THREAD

**Issue by Sineaggi** [gradle/gradle#23935]
In a kotlin gradle plugin generated with gradle init, the following code fails to compile.
```kotlin
inline fun <T : Any> Provider<T>.filter(predicate: (t: T) -> Boolean): Provider<T> {
    return map { it.takeIf(predicate) }
}
```
The compile succeeded in gradle 7.6, but not gradle 8. (with a warning)
The compile succeeds using k2 (no warnings)
The compile succeeds using `kotlin-dsl` (no warnings)
Minimum reproducer attached [null-map-transformer.zip](https://github.com/gradle/gradle/files/10762218/null-map-transformer.zip)

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is expected behavior and there’s no plan to change it. This issue will be closed.

----

With Gradle 7.6 the provided code fails to compile with:
```
Can't inline 'predicate' here: it may contain non-local returns. Add 'crossinline' modifier to parameter declaration 'predicate'
```

After changing it to the following:
```kotlin
inline fun <T : Any> Provider<T>.filter(crossinline predicate: (t: T) -> Boolean): Provider<T> {
    return map { it.takeIf(predicate) }
}
```

With Gradle 7.6 it does compile with the following warning:
```
Type mismatch: inferred type is T? but T was expected
```

With Gradle 8.0 compilation fails with:
```
Type mismatch: inferred type is T? but T was expected
```

This is new correct strictness in the Kotlin compiler that you can disable with:

```kotlin
tasks.withType<KotlinCompile>().configureEach {
    compilerOptions.freeCompilerArgs.add("-XXLanguage:-TypeEnhancementImprovementsInStrictMode")
}
```

It does compile with the `kotlin-dsl` plugin because it adds this compiler argument for you.
It does compile with K2 enabled, most probably because K2 doesn't have the same checks yet.

What makes this a bit confusing is that the way the nullability of `Provider.map {}` is currently handled is far from perfect.  See the discussion in https://youtrack.jetbrains.com/issue/KT-55542
