### ISSUE TITLE
Sourceset: srcDirs: Support adding tasks

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#24034]
### Expected Behavior

```kotlin
plugins {
  java
}

val generateJavaCode by tasks.registering(Generator::class)

sourceSets.main {
  java.srcDirs(generateJavaCode)
}
```
### Current Behavior

```kotlin
plugins {
  java
}

val generateJavaCode by tasks.registering(Generator::class)

sourceSets.main {
  java.srcDirs("/build/generate/javaCode") // the output folder of generateJavaCode
}

tasks.compileJava {
    dependsOn(generateJavaCode)
}
```

### Context
Other tasks with a custom `ConfigurableFileCollection` supports `from(task)` adding the producer tasks to the task dependencies and adds the outputs to the the file collection. 
Writing a task generating java code is very common, but adding the files to the source set could be easier.

Related: Allow adding a single file to the source set.

**Comment by melix** [comment]
This already works, I'm often using this, but you have to use `srcDir`, not `srcDirs`, see [this example](https://github.com/melix/gradle-workshop-2022/blob/task-dependencies/buildSrc/src/main/groovy/org.demo.my-convention.gradle).

**Comment by hfhbd** [comment]
Thanks. Stupid question, why does it only works with `srcDir` not `srcDirs`? And this does not work if the Task generates a single file: `OutputFile`:
```
Source directory 'parser/build/generated/lexer/main/java/app/softwork/kobol/CobolLexer.java' is not a directory.
```

**Comment by melix** [comment]
> Stupid question, why does it only work with srcDir not srcDirs?

Not quite sure but I think it's simply because `srcDirs` expects a _list_ of directories, so multiple sources.

> And this does not work if the Task generates a single file: OutputFile:

Indeed, because the input to the compiler, via a Gradle source set, is a list of root directories, not files. So it cannot determine what is the "root" of your file. Where should it stop? `kobol`, `app`, `java`? There's no way Gradle can figure that out, especially because depending on what you generate, the relative path may be relevant or not, and the "root directory" before the relative path is entirely up to you (e.g, `build/generated/blah/foo/app/softwork/kobol`.

**Comment by hfhbd** [comment]
Thank you! That makes sense, so a valid workaround is refactoring the task to produce only `OutputDirectories`.
