### ISSUE TITLE
Flutter gradle build problem

### ISSUE THREAD

**Issue by Sadafj** [gradle/gradle#24044]
Could not find com.android.tools.build:gradle:8.0.1.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/8.0.1/gradle-8.0.1.pom
  - https://repo.maven.apache.org/maven2/com/android/tools/build/gradle/8.0.1/gradle-8.0.1.pom
  - https://jitpack.io/com/android/tools/build/gradle/8.0.1/gradle-8.0.1.pom
Required by:
    project :
Add google Maven repository and sync project
Open File
[idea.log](https://github.com/gradle/gradle/files/10832411/idea.log)

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

You have a network setup issue most likely. Investigate the [stacktrace](https://docs.gradle.org/current/userguide/logging.html#stacktraces) to figure out what the issue is.
