### ISSUE TITLE
latest.version does only work for single-digets 

### ISSUE THREAD

**Issue by EugenMayer** [gradle/gradle#24042]
When using `latest.release` we happen to learn that it seems to work for only single-digits.

Means it will resolve 1.3.9 as latest release, but if 1.3.10/11/12 exists, it will never select those

### Expected Behavior
It should always select the latest version, ordererd by semver

### Current Behavior
only works for single digits so 1.3.[0-9] works, while 1.3.[10) does not.
I did not yet happen to test this for minor/majors

### Context
gradle 7.6.1

### Steps to Reproduce 
use  `latest.release` with a package that has a 2-digits patch release for the most recent major/minor

## Other odd observations

using `1.+` will not either, only `1.3.+`

### Your Environment
gradle 7.6.1
java 17

**Comment by EugenMayer** [comment]
Interesting, i cannot even get 1.4.0 to work with `latest.release` any longer. I do run the latest sonatype-nexus as the artifactory. Is there some kind of index that might affect this issue on the nexus side?

**Comment by eskatos** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days, unless you can provide more information.
