### ISSUE TITLE
Gradle 2.9 org.gradle.internal.classloader.CachingClassLoader.addURL() disabled

### ISSUE THREAD

**Issue by asknico** [gradle/gradle#24058]
### Expected Behavior
Gradle 2.9, org.gradle.internal.classloader.CachingClassLoader.addURL() disabled

### Current Behavior
Exception in task dependencies: No signature of method: org.gradle.internal.classloader.CachingClassLoader.addURL() is applicable for argument types: (java.net.URL)

### Context
Connected to the target VM, address: '127.0.0.1:51258', transport: 'socket'
===> Exception in task dependencies: No signature of method: org.gradle.internal.classloader.CachingClassLoader.addURL() is applicable for argument types: (java.net.URL) values: [file:/D:/Program%20Files/Git_repo/vayhapi/vayhapi-web/build/classes/main/]
Possible solutions: dump()

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you can provide more information.
