### ISSUE TITLE
CVE-2022-4065: Bump version for "testng" plugin 

### ISSUE THREAD

**Issue by samruddhikhandale** [gradle/gradle#24062]
### Expected Behavior

Gradle installs the `testng` plugin with version >= 7.7.0 to patch the vulnerability mentioned in https://github.com/advisories/GHSA-rc2q-x9mf-w3vf.

### Current Behavior

`gradle v8.0.1` adds the `testng-6.3.1.jar` plugin. According to https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-4065, the security vulnerability is patched in `testng-7.7.0.jar`.

I would appreciate if the `testng` plugin is patched in an upcoming release. Thank you!

**Comment by jbartok** [comment]
Thank you for reporting this problem.

The issue is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before a fix is made.

**Comment by ov7a** [comment]
Unfortunately, this upgrade would require changes in [test filtering](https://github.com/gradle/gradle/blob/e2e3a155dab7d08f6de2fde2566eed23eff9213a/subprojects/distributions-dependencies/build.gradle.kts#L143). 
We'll investigate the impact of this vulnerability regarding Gradle builds.

**Comment by ljacomet** [comment]
The version 6.3.1 of TestNG does not have the necessary code to produce the path traversal. It does not extract files out of the archive. Instead, processing is done [in place](https://github.com/cbeust/testng/blob/080c80c2f4507e668130dbd373c74379f2f69b85/src/main/java/org/testng/TestNG.java#L337-L369).
The PR that introduced the issue is in versions `[6.13, 7.6.1]`:
* cbeust/testng#1596

Second, that CVE has a  very inflated score in my opinion:
* Only `.xml`, `.yaml` and `.yml` files can be extracted that way, not any file. The scope could be extended if custom `org.testng.xml.ISuiteParser` are available on the classpath.
* Second, this happens when running a supposedly malicious test JAR. If you have such a malicious JAR, chances are that the test execution itself will be compromised, which is _directly remote code execution_ then, including attempting to write any content to any file on disk. But managing to do that JAR injection and only attempt to exploit the path traversal problem seems quite unlikely.
* It feels like the vulnerability has been rated as if TestNG was used in a webapp that accepts random archives and not as a testing library used by developers and build tools. While there might be a webapp out there doing just that, it is not the common usage scenario.

I'll try to follow up to get the vulnerability score revised.

While the above means Gradle is not vulnerable, we still plan to update TestNG at some point, see:
* #24930 

I will close this issue as the CVE is not applicable.
