### ISSUE TITLE
Windows & Gradle 7.6.1 file lock not being released

### ISSUE THREAD

**Issue by lavandowska-datasite** [gradle/gradle#24082]
### Expected Behavior
I expect to be able to run my application and it's tests in separate windows/processes.

### Current Behavior
Since updating to 7.6.1 I'm experiencing the following error (on Windows) trying to launch more than one process (run the app and run the acceptance tests)
> Timeout waiting to lock artifact cache (C:\Users\me\\.gradle\caches\modules-2). It is currently in use by another Gradle instance.
> Owner PID: 6472
> Our PID: 15212
> Owner Operation:
> Our operation:
> Lock file: C:\Users\me\\.gradle\caches\modules-2\modules-2.lock

The lock is only released if `gradlew --stop` is run (killing all processes), but running the app again will re-instate the lock, sometimes on other files in the `caches` folder (such as fileHashes.lock or fileContent.lock).  

This does not happen if I change back to Gradle 7.6

### Context
I am unable to run acceptance tests as I cannot have more than one process

### Steps to Reproduce 

I will work on this but currently the gradle-issue-reproducer does not create a running application

### Your Environment

Build scan URL:
![image](https://user-images.githubusercontent.com/93616546/221913636-3e243e0b-4db3-4fa5-9439-7a9ec91c5fdb.png)

**Comment by lavandowska-datasite** [comment]
Updating to `8.0.2` appears to have resolved the issue, I'm going to give this more time and will close once I'm more confident.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you can provide more information.

***
Are you running your build in a isolated container? Is there anything that could prevent gradle daemon to talk to each other?

**Comment by lavandowska-datasite** [comment]
> Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.
>
I understand, it just has not been a priority to recreate the problem, as it requires a running service, not just a up-and-down execution (the reproducer template is of little help here).
I'm running either in IDEA or on the command line (git-bash), which has worked for over a year prior to last week.
