### ISSUE TITLE
build init plugin should enable configuration cache for generated builds

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#24101]
To help with adoption of the configuration cache, enable it for new builds.

### Expected Behavior

New builds generated using the build init task use configuration caching without the user needing to do anything for this.

Also, change the generation so as to not enable parallel execution.

### Current Behavior

New builds do not use the configuration cache, so that users need to be aware of this feature and enable it in order to get the benefits.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

***

`--parallel` should remain for now because you can still disable configuration cache by marking tasks as not compatible, and in this case `--parallel` is still useful. 

About CC encryption — special care should be taken regarding UX bootstrapping a new build.
