### ISSUE TITLE
DetachedConfigurations should not resolve to themselves

### ISSUE THREAD

**Issue by tresat** [gradle/gradle#24126]
If you add a `detachedConfiguration` with a project dependency to the same project, it (the detached configuration) should never resolve to itself.

See https://github.com/gradle/gradle/pull/24117#discussion_r1123631653 and the test https://github.com/gradle/gradle/pull/24117/files#diff-ab236d912b1136fc50c83239cd58a7095406a4b7fc0bfabcb9f452744580be6dR129.  This behavior should be deprecated.

**Comment by melix** [comment]
On a related note, I just faced the [very same bug that almost 10 years ago](https://discuss.gradle.org/t/is-the-default-configuration-leaking-into-independent-configurations/2088/6) which I had to [fix in a dirty way which isn't compatible with project isolation](https://github.com/micronaut-projects/micronaut-build/pull/521/files#diff-e8ae67a129e72799c5a79cfbf31fe0ebb7e409ce0780e81acbc19d9a97daf2c4R63). I think the `detactedResolver` API should be made public (because it's useful), but that alone wouldn't fix that problem, the detached resolver should also be made independent from the project configurations. Whatever you can do to properly fix this would be greatly appreciated, thank you!

**Comment by big-guy** [comment]
We need to deprecate allowing a detached configuration to be used for consumption.  We've already deprecated them for consumption, but we still allow you to set consumable to true.
