### ISSUE TITLE
The `useJUnitPlatform` setting in `KotlinDSL` does not work correctly since Gradle 8.0

### ISSUE THREAD

**Issue by geminiKim** [gradle/gradle#24149]
In the KotlinDSL environment, the settings that were working correctly until gradle 7.6.1 are not working correctly since 8.0.

I've checked the java + groovy environment and it doesn't have this problem.

```kotlin
tasks.register<Test>("restDocsTest") {
    group = "verification"
    useJUnitPlatform {
        includeTags("restdocs")
    }
}
```

### Expected Behavior
The test code with the value of `@Tag` from JUnit set to "restdocs" should be executed.

### Current Behavior
The `@Tag` is not recognized and the test code runs nothing.

### Context
I had an issue with my test code not running when I wanted it to.

### Steps to Reproduce 
If you get a `not-work-tests-gradle8` branch of this [repository](https://github.com/team-dodn/spring-boot-kotlin-template/tree/not-work-tests-gradle8) and do a `restDocsTest`, you can see the same issue.

And if you check `restDocsTest` on version `gradle 7.6.1` in the `main` branch of this [repository](https://github.com/team-dodn/spring-boot-kotlin-template), you'll see it working fine.

### Your Environment
I just migrated from gradle-wrapper 7.6.1 to 8.0

**Comment by ghale** [comment]
Thanks for the report @geminiKim.  I created a [simple reproducer](https://github.com/ghale/junitTagReproducer) and confirmed that this behavior changed between 7.6.1 and 8.0.2.  Note that the issue arises because of [the exclusion](https://github.com/team-dodn/spring-boot-kotlin-template/blob/not-work-tests-gradle8/build.gradle.kts#L67-L71) applied to all tasks with type `Test`:
```
tasks.withType<Test> {
    useJUnitPlatform {
       excludeTags("develop", "restdocs")
    }
}
```
So you can workaround the issue for now by removing the exclusion from the `restDocsTest` task (i.e. `excludeTags.remove("restdocs")`) or by conditionally applying the exclusion, etc.  

There's clearly a change in behavior here, which we are looking into, however, I'm not sure the previous behavior was actually correct.  I would expect a test to be executed only if it matched an included tag and did _not_ match an excluded tag.  The [junit docs](https://junit.org/junit5/docs/current/api/org.junit.platform.launcher/org/junit/platform/launcher/TagFilter.html) are vague and don't explicitly clarify the precedence, but seem to imply that interpretation is correct.  We're still investigating and trying to understand what change caused this and what the correct behavior is.

**Comment by ghale** [comment]
Ok, after digging into this some more, this behavior change was intentional.  What was happening in 7.6.1 (and before) was that every time `useJUnitPlatform() { ... }` was called, it was actually overwriting the framework configuration from previous calls.  So in your case, the second call to `useJUnitPlatform()` in the `restDocsTest` configuration was removing any configuration that was set in the `tasks.withType(Test) { ... }` block.  We actually considered this a bug and intentionally changed the behavior here so that 1) you could not set the test framework to to a different framework once it was configured, and 2) if you were setting it to the same test framework, you would be adding to the existing configuration rather than overwriting it.  1 was called out specifically in the upgrade guide, but 2 was only vaguely mentioned and it was not clear how that might affect builds that were relying on the previous behavior.

What we are going to do here is call this out more explicitly in the 8.x upgrade guide and in 8.2 we're going to add a warning when a tag is added to both includes and excludes so that it is clear that there could be a conflict.  Then we'll possibly make this an error in 9.0.

**Comment by geminiKim** [comment]
@ghale 
First, thanks for catching on so quickly.
I need to run test code separately for each group in CI, but how is the best way to do it per tag?

**Comment by geminiKim** [comment]
I was looking for a way and found the answer on my own, but I don't know if this is the best way to do it. 
Thanks again for the quick issue resolution. 😄 

--

Instead of `tasks.withType<Test>`, I used the following approach to create the desired behavior.

```
    tasks.test {
        useJUnitPlatform {
            excludeTags("develop", "restdocs")
        }
    }

    tasks.register<Test>("unitTest") {
        group = "verification"
        useJUnitPlatform {
            excludeTags("develop", "context", "restdocs")
        }
    }

    tasks.register<Test>("contextTest") {
        group = "verification"
        useJUnitPlatform {
            includeTags("context")
        }
    }

    tasks.register<Test>("restDocsTest") {
        group = "verification"
        useJUnitPlatform {
            includeTags("restdocs")
        }
    }
```
