### ISSUE TITLE
Nested cross-components dependencies resolved but not compiled

### ISSUE THREAD

**Issue by tomasAlabes** [gradle/gradle#24177]
When having dependencies in includedBuilds, if the dependency project is nested, the dependency is resolved but the compile classpath seems to not load that project.

### Expected Behavior
Project should compile if the dependency is loaded by gradle.
Having a multi-component + multi-project nested build, dependencies between components' projects are expected.

### Current Behavior
Project dependencies are resolved but compilation fails.

### Context

Having a complex multi-component + multi-project nested build, like the sample one: https://docs.gradle.org/current/samples/sample_structuring_software_projects.html
Just making one component have a nested project.

### Steps to Reproduce 

Created this repo to reproduce the situation, info in README: https://github.com/tomasAlabes/potential-gradle-bug

### Your Environment

Build scan URL: provided repo
Gradle version: 7.6.1 & 8.0.2

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).
***

It seems like your reproducer is missing several `settings.gradle.kts` files — one in `components` folder, and another in `app-one` folder, at least. Could you please add them to your reproducer repository and make sure the problem is reproducible on a clean `git clone`?
