### ISSUE TITLE
Suggestion: avoid distraction with config cache report

### ISSUE THREAD

**Issue by melix** [gradle/gradle#24248]
### Expected Behavior

When a build fails, avoid displaying the configuration cache report if no errors are found.

### Current Behavior

If a build fails (say tests are failing) and that the configuration cache is on but that no configuration cache problems are found, then the  link to the configuration cache report is visible just above `FAILURE`, which is distracting because this is usually the place where we look for the test reports:

![image](https://user-images.githubusercontent.com/316357/223963213-7e0267f8-cc18-4624-a391-530c500328d4.png)

### Context

Trying to fix errors with the configuration cache while working on regular Micronaut projects.

https://ge.micronaut.io/s/qgzu5bcmogumc

**Comment by liutikas** [comment]
By default, the behavior is good not to show the report, but I think there should still be a way to force produce a report even without configuration cache issues. Where this is useful is cases where you want to use the report to track file inputs tracked by the configuration cache in the report. It seems that `org.gradle.configuration-cache.internal.report-link-as-warning` might be the way to do it, but I could't get it to work with either `-Dorg.gradle.configuration-cache.internal.report-link-as-warning=true` or `-Porg.gradle.configuration-cache.internal.report-link-as-warning=true`.

**Comment by abstratt** [comment]
@liutikas To be 100% clear, the report is always generated - it is only the link to the report that is omitted if no problems exist. 

If you want the link to be shown in the build output even if there are no problems in the report, at this time, you need to run Gradle with the `--info` option (which will include other `INFO` level output). If this turns out to be a common feature, and `--info` is deemed to be an inadequate way to produce it, we may consider providing a user-facing option to force the link to the report to be always included in the output.
