### ISSUE TITLE
8.1 RC1 Operator assign shows as unused in kotlin-dsl included build

### ISSUE THREAD

**Issue by TWiStErRob** [gradle/gradle#24409]
### Expected Behavior
Import used, as it's required for compilation.

### Current Behavior
Import is used. If I Organize Imports, it makes the code red.

### Context
Just gave it a try, it compiles and runs correctly, only unused in IDEA.

### Steps to Reproduce 
1. Import https://github.com/TWiStErRob/net.twisterrob.cinema/pull/390 's 7b74ff5 commit in IDEA.
2. Open `net.twisterrob.cinema.heroku.plugins.DetektPlugin`
3. Observe unused import
![image](https://user-images.githubusercontent.com/2906988/226451259-ab5b7719-123d-4cbb-89d8-7c0b5c578922.png)

### Your Environment

Build scan URL: N/A

**Comment by asodja** [comment]
Thanks for trying the feature. I believe this is the same issue as [KTIJ-24390](https://youtrack.jetbrains.com/issue/KTIJ-24390).

There are actually 3 known issues with IDE integration, additionally to the linked one also: [KT-56941](https://youtrack.jetbrains.com/issue/KT-56941/) and [KT-56221](https://youtrack.jetbrains.com/issue/KT-56221/). [KT-56941](https://youtrack.jetbrains.com/issue/KT-56941/) and [KT-56221](https://youtrack.jetbrains.com/issue/KT-56221/) are already fixed in Kotlin 1.8.20 (we will most likely upgrade in Gradle 8.2), but the import issue still needs a fix on the IntelliJ side.

**Comment by asodja** [comment]
Note: one workaround that might make IntelliJ happy is to use `import org.gradle.kotlin.dsl.*` import, but for lots of projects star import might not be a welcome solution.

**Comment by TWiStErRob** [comment]
I'm converting my local convention plugins to `.gradle.kts`, that also helps as you mentioned in KTIJ-24390.

🤞 for a fix before 1.8.20, or in 1.8.21 quick follow. Since this is not fixable on Gradle side right now, I think this issue can be closed. Would you mind adding links to these issues at https://docs.gradle.org/8.1-rc-1/userguide/kotlin_dsl.html#ide_support and the release notes for this release, since it'll be always a problem with 8.1, even if people update the Kotlin Plugin in the project, right?

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is an issue with IntelliJ IDEA’s Gradle integration, which is developed by JetBrains and cannot be addressed in the Gradle Build Tool project.

**Comment by TWiStErRob** [comment]
Yes, I agree, but it can be documented, @ov7a ;)

**Comment by TWiStErRob** [comment]
Thanks for https://github.com/gradle/gradle/pull/24418!
