### ISSUE TITLE
8.1 RC1: notCompatibleWithConfigurationCache is not always honored

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#24411]
It appears that notCompatibleWithConfigurationCache() is not always respected when Task.project is used at execution time. An explicit --no-configuration-cache is required to avoid a build failure. An example [failure](https://github.com/ben-manes/caffeine/actions/runs/4475887889/jobs/7865718673) due to using `Project.javaexec` instead of the newer `ExecOperations`.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue lacks information about how to reproduce the problem you're having. A [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) can really help us track down and fix your problem. We may also be able to suggest workarounds or ways to avoid the problem if we can reproduce it.

We request you to provide a reproducer because we need to be sure we are looking at the exact problem you are facing.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer).

This issue will be closed after 7 days unless you can provide more information.

**Comment by mlopatkin** [comment]
First, I try to explain what we're seeing in the [`sd-kotlin-talks` reproducer](https://github.com/gradle/gradle/issues/24411#issuecomment-1478122947).

This is an unforeseen fallout from our changes to the notion of "task execution time". We have the `DependencyUpdatesTask` that resolves some configurations at execution time and is marked with `notCompatibleWithConfigurationCache`. As part of resolution, the "compileJava" task is materialized, as its provider is queried in some of the callbacks of the `compileClasspath` configuration. Task configuration of the `compileJava` legitimately calls `getProject` as it is expected to run at configuration time. This is where the difference between 8.0 and 8.1 lies.

In 8.0 `Task.getProject` is only forbidden when the task itself runs, so calling `getProject` of some other task doesn't fail the build (though it is still broken). In 8.1 the execution time barrier is global for all tasks. The `notCompatibleWithConfigurationCache`, however, is only applied to problems coming from the task which called it. When we call `getProject` of `compileJava` task, it emits an unsilenced problem that fails the build.

I suppose this is similar to what happens in the original report too, though it is hard to figure out without the configuration cache report.

When running dependendcyUpdates with `org.gradle.configuration-cache.problems=warn`, `notCompatibleWithConfigurationCache` has no effect, so we run from cache and most likely don't have a valid configuration to resolve in the task action, thus less warnings and "no dependencies found".

**Comment by ianbrandt** [comment]
I tested RC2, and it looks like this issue is resolved. Thanks!

That said, the fix may have revealed another regression impacting 8.1. I admittedly haven't had the chance to get my head around the issue well enough yet to write it up proper, but I want to get it in front of you all while 8.1 is still in the RC process. I'll reference @ben-manes comments for now, and then try to write it up ASAP. See here and the subsequent comments: https://github.com/ben-manes/gradle-versions-plugin/issues/666#issuecomment-1489440407.

**Comment by ianbrandt** [comment]
Filed https://github.com/gradle/gradle/issues/24636.
