### ISSUE TITLE
Document or unsupport org.gradle.configuration-cache.quiet option

### ISSUE THREAD

**Issue by abstratt** [gradle/gradle#24424]
The `org.gradle.configuration-cache.quiet`, supported since 8.1 RC1, is not documented. We should consider documenting it, or possibly removing it. If we we want to keep it but don't want to promote it at all to our users, we probably should only support the `unsafe` version (or adopt an `internal` fragment, possibly in the form of a system property, if our need for it is in some specific cases only).

Note that in the process of doing https://github.com/gradle/gradle/issues/24422, not realizing it was not documented, we inadvertently aliased the original `org.gradle.unsafe.configuration-cache.quiet` to the new `org.gradle.configuration-cache.quiet` option, which, if we don't want to promote it, is sending the wrong signal.

**Comment by TWiStErRob** [comment]
@abstratt There might be more to this.

A normal, idiomatic Gradle build never outputs anything other than BUILD SUCCESSFUL. Configuration Cache violates this by outputting a lot of state information to the console about caching. Quiet is useful in suppressing some of this, but it's still too noisy because it doesn't have effect on everything it outputs. I don't care if configuration cache was reused or not, unless I'm a build engineer. For everyday developers, the builds are just faster with configuration cache, and there's no need to link to the report that 0.01% of them will ever open during normal operation.

**Comment by abstratt** [comment]
For 8.1 (this ticket), we intend to keep this option as internal/undocumented, and will possibly remove it altogether later.

@TWiStErRob Could you please open a feature request for controlling the verbosity in the output for the configuration cache feature?

**Comment by TWiStErRob** [comment]
Yeah, many of use are trying to get the Gradle build output to be quiet, so that any output is a red flag that needs actioning. Configuration cache is not helping. Opened https://github.com/gradle/gradle/issues/24435 .
