### ISSUE TITLE
Working With Files doc errors

### ISSUE THREAD

**Issue by patrick-dedication** [gradle/gradle#24500]
### Expected Behavior

- The [copying_single_file_example](https://docs.gradle.org/current/userguide/working_with_files.html#sec:copying_single_file_example) should not link to [Project.file](https://docs.gradle.org/current/dsl/org.gradle.api.Project.html#org.gradle.api.Project:file(java.lang.Object)) as it is not used in the example

### Your Environment

Build scan URL:

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue which we will address.

***

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.
