### ISSUE TITLE
Support for PMD 7.0

### ISSUE THREAD

**Issue by ben-manes** [gradle/gradle#24502]
### Expected Behavior
Use the new major version for static analysis. The current release version works great (6.55.0).

### Current Behavior
1. The analysis fails due to a missing class because the ant task [used](https://github.com/gradle/gradle/blob/8288ce7b083902ab94329514316424bf6ac7635d/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy#L118) by PmdInvoker belongs to a separate dependency.
2. The rules are no longer bundled, so they also have to be added explicitly.

I am able to run the analysis after making these dependency additions for a Java project.

```gradle
pmd 'net.sourceforge.pmd:pmd-ant:7.0.0-rc1'
pmd 'net.sourceforge.pmd:pmd-java:7.0.0-rc1'
```

This results then in rule failures which seem reasonable,
1. Removed rules not matching the excludes pattern
2. New or updated rules detecting problems, which need to be addressed or suppressed.

### Context
Hopefully it is not a choice of either 6.x or 7.x so supporting a release candidate is acceptable. The default tool version shouldn't change until after the final release, of course.

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team but this area of Gradle is currently not a focus one so it might take a while before it gets implemented.

***

If you are interested in contributing to Gradle, this issue is actionable and ready for contribution but might be challenging for first-time contributors.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by jvandort** [comment]
#25122 resolves the dependency issue noted in the original post. 

In order to resolve this issue fully and for Gradle to officially support PMD 7.0, `org.gradle.quality.integtest.fixtures.PmdCoverage` would need to be updated to add an entry for 7.0.0-rc2 (or the most recent version) and verify all tests succeed.

**Comment by leandremucyo** [comment]
Is this issue resolved, with gradle 8.5 and toolVersion 7.0.0-rc1 and I am still getting `ClassNotFoundException: net.sourceforge.pmd.ant.PMDTask`

**Comment by OleksandrShkurat** [comment]
> Is this issue resolved, with gradle 8.5 and toolVersion 7.0.0-rc4 and I am still getting `ClassNotFoundException: net.sourceforge.pmd.ant.PMDTask`

You may identify the currently used PMD version here:

https://github.com/gradle/gradle/blob/master/platforms/jvm/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java

It's defined in a constant DEFAULT_PMD_VERSION

**Comment by sdavids** [comment]
Still an issue ...

```kotlin
pmd {
  toolVersion = "7.0.0"
}
```

```shell
./gradlew pmdMain
> Task :pmdMain FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pmdMain'.
> A failure occurred while executing org.gradle.api.plugins.quality.internal.PmdAction
   > java.lang.ClassNotFoundException: net.sourceforge.pmd.ant.PMDTask
$ ./gradlew --version

------------------------------------------------------------
Gradle 8.7
------------------------------------------------------------

Build time:   2024-03-22 15:52:46 UTC
Revision:     650af14d7653aa949fce5e886e685efc9cf97c10

Kotlin:       1.9.22
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.10 (Eclipse Adoptium 17.0.10+7)
OS:           Mac OS X 12.7.4 x86_64
```


The workaround mentioned in https://github.com/gradle/gradle/issues/24502#issue-1640617625 still works:

```kotlin
dependencies {
  pmd("net.sourceforge.pmd:pmd-ant:7.0.0")
  pmd("net.sourceforge.pmd:pmd-java:7.0.0")
}
```

**Comment by adangel** [comment]
With the simple test project at https://github.com/pmd/pmd-examples/tree/main/gradle/simple-project I _cannot_ reproduce the problem.

For me, it generally works since gradle 8.6. I also confirmed, that it is still working with gradle 8.7. Of course, only for my little example project.

I played around a bit with `--configuration-cache` and `--build-cache`, but I still couldn't reproduce the problem: changing "toolVersion" in build.gradle, changes the file "build.gradle" which invalidates the configuration cache. This causes that the correct classpath to run PMD is used.

The relevant lines are here:
https://github.com/gradle/gradle/blob/4437480ed2e6b4d449c0356c2ed65e7127a455e2/platforms/jvm/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java#L192-L207

**Comment by sdavids** [comment]
I tried reproducing it with [your project](https://github.com/pmd/pmd-examples/tree/main/gradle/simple-project) and:

```shell
$ mkdir /tmp/gradle-pmd-toolversion-7 && cd "$_"
$ mkdir -p src/main/java
$ printf 'rootProject.name = "gradle-pmd-toolversion-7"' > settings.gradle.kts
$ printf 'plugins {
  `java-library`
  pmd
}

repositories {
  mavenCentral()
}

pmd {
  toolVersion = "7.0.0"
}' > build.gradle.kts
$ printf 'class Example {}' > src/main/java/Example.java
$ gradle wrapper --gradle-version=8.7
$ ./gradlew pmdMain
$ ./gradlew --no-daemon --no-build-cache --no-configuration-cache --no-configure-on-demand --rerun-tasks clean pmdMain
```

In both cases I could not reproduce it anymore—in other words: the combination of PMD 7 and Gradle 8.7 works.

Guess it was a file lock or cache problem yesterday 🤷

**Comment by ben-manes** [comment]
This works for me as well when removing my workaround. I'd recommend stopping the daemon and retrying @sdavids. I've had a few cases where leaks across builds cause confusion due to the persistent java compiler, which is a relatively recent improvement to reduce build times. However, sometimes there are class leaks from canceled builds, so maybe in the classpath too. Use `./gradlew --stop` and retry.

**Comment by ben-manes** [comment]
oops, missed the race. looks like I can closing. Thanks for supporting v7!
