### ISSUE TITLE
Failure To Run Repo Server After Upgrade to Gradle 7

### ISSUE THREAD

**Issue by DavidAElf** [gradle/gradle#24634]
### Expected Behavior
On my project repo I have a script command that is supposed to allow a sub server to run for that specific repo.

### Current Behavior
When I run the script (Which previously ran fine with Gradle 6) it creates a standalone build file for that sub-server when running the commands:
../gradlew InstallDist

cp -avr conf/env build/install/module/conf/

sh build/install/module/bin/module

The build file is ultimately created when the ‘./gradlew’ command is used. When it tries to use that file when using the command ‘sh build/install/module/bin/module’ it responds with the below in the terminal:
 
-classpath: command not found
StartService: command not found
-Dproperties.home: No such file or directory
-Dlogback.co: command not found
-De: command not found
Error: Could not find or load main class viro

### Context
It stopped working upon upgrading to gradle 7.6 and makes it impossible to run regression tests as the sub-server fails when trying to run with the ‘-classpath’ passage mentioned above. It also looks as though the build file now uses POSIX instead of UNIX for the start up script.
I have found a temporary fix when looking at the build files. After the upgrade to gradle 7 the block on lines 206-209 set the classpath:

set -- 
           -classpath “$CLASSPATH”
           gov.path.StartService
           “$@“

and on lines 236-241 sets:

eval “set -- $(
             printf ‘%sn’ “$DEFAULT_JVM_OPTS $JAVA_OPTS $MODULE_OPTS” |
             Xargs -n1 |
             sed ‘ s~[^-[:alnum:]+,./:=@_]~&~g; ‘ |
             tr ‘n’ ‘ ‘
      )” ‘“$@“‘

If I remove those blocks and add in a similar line that was used in gradle 6, (line 183 listed below) it runs fine.

line 183 of gradle 6 build file.
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $MODULE_OPTS -classpath “”$CLASSPATH”” gov.path.StartService “APP_ARGS”

I currently do not have means to reproduce in a sample file and for privacy reasons cannot share repo details.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

We made a number of changes to script generation due to security issues, please see following closed issues: 
https://github.com/gradle/gradle/issues?q=is%3Aissue+unix+script+is%3Aclosed

If you can't find the reason for your problems please open a new issue with a full reproducer so we can investigate.
