### ISSUE TITLE
Changing the logic of `outputs.upToDateWhen` doesn't take affect unless `--no-daemon` is used.

### ISSUE THREAD

**Issue by noel-yap** [gradle/gradle#2467]
I have a custom task and was changing the `outputs.upToDateWhen` logic. Nothing, including defining it as `{ true }` took effect until I used `gradlew --no-daemon`.

### Expected Behavior

The daemon's cache should reflect changes to the build files.

### Current Behavior

The daemon didn't refresh its cache after changing the task's `outputs.upToDateWhen` setting.

### Context

I'm iteratively implementing a new task and expected changes to the task to be reflected in the build.

### Steps to Reproduce (for bugs)

1. Create a task
2. Execute the task
3. Set `outputs.upToDateWhen` to `{ false }`
4. Execute the task
5. Set `outputs.upToDateWhen` to `{ true }`
6. Execute the task # the task should be `UP-TO-DATE` but it's not
7. Execute the task with `--no-daemon` # the task is now `UP-TO-DATE`

**Comment by big-guy** [comment]
`outputs.upToDateWhen { true }` doesn't mean "the task is up-to-date."  It just means that the outputs are up-to-date for that particular spec.  Gradle will still do its own up-to-date checks.

The other thing that may be confusing is where the task's actions are defined.  If the actions are defined in the build script, the build script itself is an input to the task.  So changes to the build script will make the task out-of-date.

So if I had a task like:
```
task myTask {
    def outputFile = file("output.txt")
    outputs.file outputFile
    doLast {
        outputFile.text = "Done"
    }

    outputs.upToDateWhen { false }
}
```

Whenever I run this, `myTask` is out-of-date.  If I switch the false to true, the first time I run it, the task is out-of-date still (because the buildscript changed).  When I run it again, it would be up-to-date (all inputs are the same).  You'll see this at `--info` level logging.

> Task ':myTask' has additional actions that have changed

**Comment by noel-yap** [comment]
Thanks for the explanation.
