### ISSUE TITLE
Add a timeout for running tests

### ISSUE THREAD

**Issue by alexei-osipov** [gradle/gradle#2476]
Please provide a possibility to set default timeout for tests (JUnit tests) that executed from Gradle.

Note: this is related to https://github.com/gradle/gradle/issues/1096 but not the same. I would like to set a default timeout for individual tests, not entire Gradle task that runs all tests for a module.

Note:
JUnit's `@Test(timeout=X)` annotation is unsuitable because it must be place on each test.
JUnit's `@Rule` annotation is unsuitable because it must be place on each test class.
JUnit's `@ClassRule` can be used to solve the problem but it's not applicable to Gradle `Test` task.

See also https://issues.gradle.org/browse/GRADLE-1020

**Comment by staffanf** [comment]
I would really want this.
We have had examples of unit tests that locks up the whole build pipeline for 2h and then timeouts. This would allows us to set a low (like 5s) timeout for unittest classes and get much better/faster feedback of what went wrong.
This should also produce a better error message than what we get when jenkins kills the build due to a timeout.

**Comment by AartiJ** [comment]
It will be good if we have some update on this. Need this feature for test execution

**Comment by smougenot** [comment]
An idea on how to do that.

If it is JUnit tests specific and we do not like to use JUnit tools (adding annotations provided by JUnit), maybe it could be done with a gradle plugin using bytecode enhancement.
I might be wrong but I thing it is possible to do so.

**Comment by JamesXNelson** [comment]
I think you'd want to extend the specific unit test tools, and just add the specific annotations to the correct member's class file Attributes.

**Comment by OleksandrKucherenko** [comment]
any updates on this?!

**Comment by oehme** [comment]
For JUnit 5 this is already possible with its extension API. For Junit 4 there is RunListeners, which we would just need to [support](https://github.com/gradle/gradle/issues/1330). I don't think we should reimplement what the test frameworks already offer, but instead allow you to leverage their functionality.

**Comment by KidDaedalus** [comment]
Our expectation is that a good solution to orchestrating poorly behaved tests/product behavior would:

- DRY application of test timeout policy 
- Not require individual modification of 1000s of Junit test classes. This is both to save work and ensure that authors of new test classes can't forget to apply the policy. 
- Identify culpable tests by name 
- Provide opportunity to collect additional debugging information, such as a thread dump

Forgive my ignorance of Junit 5, @oehme, do you believe it could satisfy those requirements? In the JUnit 5 documentation I've read so far it seems like "extensions" are applied via test-class level annotation, which would mean a mass-refactoring followed by whack-a-mole of new test classes popping up without the required annotation.

**Comment by oehme** [comment]
Extensions can be registered automatically via a [service loader](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic) mechanism. This should indeed satisfy your requirements above.

**Comment by KidDaedalus** [comment]
Alright I'm going to give that a try. Thanks for the recommendation, Stefan!

**Comment by JamesXNelson** [comment]
Ah, if only my org didn't have ....looks over shoulder...  JUnit 3 tests still in the wild.

Really, I'd just settle for even a global "test task timeout" (maybe even just a global task timeout).  I don't care that things fail as quickly as possible, only that they actually fail when they've clearly exceeded normal runtimes.

**Comment by JamesXNelson** [comment]
Looking at the above linked issue, I see the existing feature requests and will go +1 over there.  thanks.

**Comment by KidDaedalus** [comment]
@oehme I've been reading Junit5 documentation and doing some experiments.
So far I have exactly the same problems implementing timeouts at the Junit5 level as I do the Gradle level:

* The "after" callback is never invoked if the test never terminates
* There is no "during" callback or similar designated place to supply mid-execution code
* Exceptions thrown from arbitrary other threads are not caught by any exception handler that has the power to kill or mark as failed a deadlocked test

See Junit5 issue [Introduce global timeouts for tests](https://github.com/junit-team/junit5/issues/80)

Indeed, Junit5 regresses the meager DRY-ness possible in 4 by making the *only* [inbuilt timeout mechanism](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertTimeoutPreemptively-java.time.Duration-org.junit.jupiter.api.function.Executable-) one that has to be written into the code of every. single. test. case. 

So it does not appear to me to be possible to timeout deadlocked tests or test classes with a Junit Extension.

Perhaps subclassing `VintageTestEngine` to do exactly the `assertTimeoutPreemptively` wrapping is what I'll have to do. Of course that introduces a barrier to changing test frameworks or junit5 engines that I didn't want to impose. I haven't really solved the problem if it's easy to elide the timeout and I don't really want to get into the business of policing my peers choices of test frameworks or junit engines.

Please advise - I'm happy to be corrected if I've misunderstood or overlooked something!

**Comment by oehme** [comment]
I may have misunderstood what is possible with JUnit 5 extensions. I had assumed they would be able to "wrap" a test so that it could be started on a different thread, similar to what the Timeout rule in JUnit 4 does. Looking more closely at the extension API, this doesn't seem possible indeed. Can you give more feedback on this @marcphilipp? Is there some way @KidDaedalus could implement a cross-cutting timeout with an extension? Or is that something only an engine can do?

**Comment by marcphilipp** [comment]
@KidDaedalus You're correct, that's currently not possible with a Jupiter Extension. There's an open issue to introduce an [additional extension point to alter the execution behavior](https://github.com/junit-team/junit5/issues/157) that provides some background on the rationale. In short, extensions should be composable and the engine should not hand over control of test execution to an extension.

However, your idea to let the engine know that it should cancel the execution of a test sounds very interesting! Would you mind opening an issue for the JUnit team to continue the discussion?

**Comment by oehme** [comment]
So as a workaround you could sublclass the jupiter and vintage extensions and let your colleagues use those. Would this be acceptable for you @KidDaedalus?

**Comment by KidDaedalus** [comment]
After quite a bit of experimenting I couldn't get to a satisfying Junit based solution for this problem. 
The VintageEngine is a thin wrapper around all of Junit4, and the bit I'd want to tweak is deep within Junit4. A custom Runner is the most natural place to add this sort of logic... but you can only use one Runner at a time and our tests have a mixture of the basic runner, the jmockit runner, and the spring runner. After going into the weeds on extending JUnit4 I feel like I understand why they wanted to move the direction they did for Junit5's extensible model! But that doesn't leave us any better off.

So I'm trying out two other solutions for this that are different kinds of hacky.
One is a "poison pill" that looks a bit like this, in kotlin (omitting some details for brevity):
```kotlin
class TimeoutEnforcer(
    val testName: String,
    val testCompleted: AtomicBoolean = AtomicBoolean(false),
    val sleepStepMs: Long = 100L,
    val testTimeoutMs: Long = 100000L,
    val onTimeout: () -> Unit = { throw TimeoutException("This is insufficient to terminate the deadlocked test :( ") }
) {
    suspend fun run() {
        var remainingTimeMs = testTimeoutMs
        while (remainingTimeMs > 0) {
            if (testCompleted.get()) {
                break
            }
            if (remainingTimeMs > 0) {
                remainingTimeMs -= sleepStepMs
                delay(sleepStepMs)
            }
        }
        if (!testCompleted.get()) {
            onTimeout()
        }
    }
}

class TimeoutEnforcerPlugin : Plugin<Project> {
    val logger = Logging.getLogger(TimeoutEnforcerPlugin::class.java)
    override fun apply(target: Project) {
        testTask.addTestListener(object : TestListener {
            override fun beforeSuite(suite: TestDescriptor) { }
            override fun beforeTest(testDescriptor: TestDescriptor) {
                val watchdog = TimeoutEnforcer(
                    testName = name,
                    onTimeout = ::poisonPill)
                watchdogMap[name] = watchdog
                launch {
                    watchdog.run()
                }
            }
            override fun afterTest(testDescriptor: TestDescriptor, result: TestResult) {
                println("afterTest $testDescriptor")
                val name = testDescriptor.getCanonicalName()
                watchdogMap[name]?.testCompleted?.set(true)
                watchdogMap.remove(name)
            }
            override fun afterSuite(suite: TestDescriptor, result: TestResult) { }
        })
    }
    fun poisonPill() {
        val threadDump = JstackWrapper().threadDump() // Calls jstack on the current JVM's pid
        // do some processing on the thread dump to find the culpable stacks
        logger.quiet(threadDump)
        exitProcess(-1)
    }
}
```
I can't do anything to the thread running the test... but I bring down the whole test worker JVM with a System.exit()! 
This has a number of unfortunate consequences and fills the logs with errors around the suddenly missing test runner that aren't about the test that failed, distracting developers from the problem in their code and making them think that it's Gradle that has a problem. 

So since that isn't ideal, I'm also experimenting with creating a plugin that uses [ASM](http://asm.ow2.io/) to modify test class bytecode to add a [Timeout](https://junit.org/junit4/javadoc/4.12/org/junit/rules/Timeout.html) to any Junit4 class that doesn't already have one.

Anyway, I understand that you very reasonably wish to leave the details of test execution encapsulated within the tools that own that domain. But I do hope that you'll think about how Gradle itself, within its own domain of task orchestration, can be more robust to being asked to orchestrate badly behaving code. A task-level notion of a timeout could have substantially reduced our pain in this area, perhaps something like what I mentioned in #1096

**Comment by oehme** [comment]
Thank you for that well-weighed feedback @KidDaedalus! There is also a request to limit overall build time (https://github.com/gradle/gradle/issues/5181). Maybe even that would be enough?

**Comment by felipecsl** [comment]
I've been playing with https://github.com/Nordstrom/JUnit-Foundation but it has the same limitations around having to set the JUnit test runner everywhere. Will try @KidDaedalus solution and report back with findings. Thanks for sharing!

**Comment by oehme** [comment]
We are not going to do per-test timeouts, as this is better handled by the test frameworks themselves. However, we are adding per-task timeouts to Gradle 5.0, see https://github.com/gradle/gradle/pull/6643

**Comment by sbabcoc** [comment]
I just saw the comment from @felipecsl. **JUnit Foundation** no longer uses a custom runner for activation. It uses byte code generation and attaches via a Java agent. This means that you can enable global timeout management without having to change your test code.

**Comment by sbabcoc** [comment]
@oehme I think the information I posted will be helpful to many folks still using JUnit 4. The library I refer to enables timeout management, automatic retry of failed tests, and event notifications in Gradle project tests. Where is the best place to publicize this information?

**Comment by marcphilipp** [comment]
If anyone stumbles on this issue in the future, JUnit has added support for default timeouts in the meantime: https://docs.junit.org/6.0.3/writing-tests/timeouts#default-timeouts
