### ISSUE TITLE
Dependency excludes defined in a `beforeResolve` hook should be respected

### ISSUE THREAD

**Issue by ewirch** [gradle/gradle#2480]
See [attached project](https://github.com/gradle/gradle/files/1150485/trans-dep-fail.zip). Assemble with Gradle 4 (the included Gradle wrapper is 4). The WAR will contain `WEB-INF/lib/XmlSchema-1.1.jar` (and a duplicate file error), even though this dependency is excluded and not print by `gradle dependencies`.

Build the same project using Gradle 3 and the WAR contents will be correct.

I created this issue with [Spring dependency plugin project](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/180) first, Since the sample project uses the plugin. But the contributors pointed out, that the same error also occurs when not using the plugin. See comment on the linked issue.

**Comment by bigdaz** [comment]
Thanks for the report: I've confirmed that this is a problem introduced in Gradle 4.0.

The underlying problem is that dependency excludes declared in a `beforeResolve` hook can be ignored due to some newly introduced caching. I've added a test that demonstrates the issue: https://github.com/gradle/gradle/commit/b28d8ee5811821852499372fd15ad6e760d209c6

**Comment by bigdaz** [comment]
I've added some ideas on how this could be fixed here: https://github.com/gradle/gradle/tree/dd/issue/2480. However, neither of the attempted fixes are particularly satisfactory.
