### ISSUE TITLE
Use of `Path.readLines` Kotlin extension is not recognized as a configuration input

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#24840]
We have a custom dependency setup in our application.

In a nutshell:
We have a file `dependencies`.
This follows a strict pattern:
```
deps.A = "group:artifact:version"
deps.B = "group:artifact:version"
toolsDeps.A = "group:artifact:version"
...
```

We have a custom settings plugin that reads this file and create a version catalog out of it.
Afterwards, we are able to use the dependencies declared from that file via the version cataog feature.

Now we are using the configuration cache.
If I now update a dependency (in the `dependencies` file), the configuration cache doesn't pick this up and I can't build with Gradle in case I use newly added classes and/or methods from the updated dependency (it is probably the same as I wouild add a new dependency).

Still, in the IDE (Android Studio) I can use the updated (or new) dependency.

### Expected Behavior

The configuration cache detectes the dependency change.

### Current Behavior

The configuration cache does not detect the dependency change and I end up in compile erros "No such method found".

### Steps to Reproduce

I basically mentioned anything above how it works.
Here are a code snippets from our VersionCatalogsPlugin:
```kotlin
class VersionsCatalogPlugin : Plugin<Settings> {

    @ExperimentalPathApi
    override fun apply(target: Settings) = with(target) {

        val dependencyGroupToDependencies = mutableMapOf<String, MutableList<Dependency>>()

        val dependencyFilePath = "dependencies"
        Paths.get("dependencyFilePath").readLines().forEach { line ->
            // Extract the the information to add the dependencies to the 
            // dependencyGroupToDependencies map
        }

        dependencyResolutionManagement {
            it.versionCatalogs { catalogContainer ->
                dependencyGroupToDependencies.forEach { (group, dependencies) ->
                    catalogContainer.create(group) { catalogBuilder ->
                        catalogBuilder.aliasForEach(dependencies)
                    }
                }
            }
        }
    }
}
```

### Gradle version

8.1

### Your Environment (optional)

* macOS 13.3.1
* openjdk 17.0.6 2023-01-17
* Android project
* .. Do you need more? :)

**Comment by ljacomet** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team and is prioritized by them.

***

Normally the configuration cache instruments IO related APIs to detect configuration inputs. It might be that `Paths.get("dependencyFilePath").readLines()` is not handled properly.

**Comment by mlopatkin** [comment]
The `Path.readLines` extension is not yet recognized by the configuration cache, consider using `File.readLines` which is supported.

**Comment by StefMa** [comment]
@mlopatkin thanks for the fast feedback.

Unfortunately this doesn't work either.
I did the following change:
```diff
- Paths.get("dependencyFilePath").readLines()
+ File("dependencyFilePath").readLines()
```
but nothing changed.
It still complained with `Unresolved reference: methodName`

**Comment by mlopatkin** [comment]
@StefMa looks like we're at the point where a minimal reproducer would help, to make sure that we're aligned.

What should happen is when the file at `dependencyFilePath` changes, the configuration is invalidated, and you see a message like:
```
Calculating task graph as configuration cache cannot be reused because file 'dependencyFilePath' has changed.
```
You can also check the configuration cache report (link to it should be printed at the end of the buyild) to make sure `dependencyFilePath` is there:
![image](https://user-images.githubusercontent.com/7620037/233709508-5084240d-bbc0-48e5-bb84-310273905c16.png)

If the configuration is invalidated, and the errors are still there, then the problem is likely somewhere else.

There also can be some issues if you use relative file paths to file and not something based on e.g. `settingsDir`, I recommend checking it too.

**Comment by StefMa** [comment]
I created an example project:
[CCIssue.zip](https://github.com/gradle/gradle/files/11345204/CCIssue.zip)
How to run?:
```
./gradlew assemble --configuration-cache
./gradlew assemble --configuration-cache
// Change the strikt version to 0.34.0
./gradlew assemble --configuration-cache
```

But it turned out.. It worked 🙈 😁 
It says to me:
> Calculating task graph as configuration cache cannot be reused because file 'versions.gradle' has changed.

To it seems we have somewhere another issue in our real project :/ 

However, I will close this issue for now as we wll move to the "official" version catalog (*.toml file in `gradle/`) anyways. So our custom plugin will be a thing from the past.

Nevertheless, thanks for your feedback.

**Comment by mlopatkin** [comment]
Glad everything sorted out!

`Path.readLines` actually works, because it is an inline function, so only its body (which is interceptable `File.readAllLines`) appears in the bytecode. Nevertheless, there is still some missing coverage, tracked in #23638.
