### ISSUE TITLE
Make version catalogs available in settings script's plugin block

### ISSUE THREAD

**Issue by ultimate-deej** [gradle/gradle#24876]
### Expected Behavior

I'd like to be able to apply plugins in the `plugins` block of settings.gradle[.kts] the same way as in my build.gradle[.kts] files, like so:
```
plugins {
    alias(libs.plugins.myPlugin)
}
```

### Current Behavior (optional)

Contents of settings.gradle/settings.gradle.kts:
```
plugins {
    alias(libs.plugins.myPlugin)
}
```

Kotlin:
```
e: file:///path/to/project/settings.gradle.kts:2:11: Unresolved reference: libs
```

Groovy:
```
Could not compile settings file '/path/to/project/settings.gradle'.
> startup failed:
  settings file '/path/to/project/settings.gradle': 2: only alias(libs.plugins.someAlias) plugin identifiers where `libs` is a valid version catalog
```

### Context

Trying to apply a settings plugin declared in a version catalog

**Comment by martinandersson** [comment]
> Thank you for your interest in Gradle!
> 
> This is the intended behavior, and there’s no plan to change it. This issue will be closed.
> 
> Version catalogs can't be used before they have been evaluated, which happens during settings evaluation, which is AFTER evaluating settings plugins. So basically a chicken and egg problem; nothing we can do about it.

Wrong on two counts.

1) Please don't presume your life-cycle explanation as _intent_. Or, riddle me this: What is the intent of the version catalog? The answer is: to centralize versions. So which "intent" do you wish to keep? Can't have them both 😉

2) Man has sat his foot on the moon but you say changing Gradle's life-cycle/whatever so that the version catalog evaluates before developers may naturally wish to use it for its **_intended_** purpose is "nothing we can do". Hey, great spirit. With this attitude I am sure Gradle will continue to evolve and prosper 🤦‍♂️

Gradle is a **build system** with **Version Catalogs** and yet we can't centralize plugin versions, well in some cases yes but in other cases no, it's just a huge thorn in the eye. Common now.

Please re-open the ticket.

**Comment by ultimate-deej** [comment]
For anyone who still needs a solution, there's a workaround: https://discuss.gradle.org/t/how-to-use-version-catalog-in-the-root-settings-gradle-kts-file/44603/5

It boils down to this:
- Create a local settings plugin. In the plugin's settings file, explicitly import your main version catalog.
- In the main settings file, add an `includeBuild` statements inside `pluginManagement` block (NOT at the top level).
- In the main settings file, apply the local settings plugin you just created and included.
- Now inside this local plugin you can use the version catalog in any way you like just as usual.
