### ISSUE TITLE
libs not found in kts file using apply(from = starting in 8.1

### ISSUE THREAD

**Issue by dalewking** [gradle/gradle#24908]
### Expected Behavior

I have a common ktlint.gradle.kts file in my root directory to apply ktlint to multiple projects. It is applied using a line of the form:

`apply(from = "$rootDir/ktlint.gradle.kts")`

The start of that file looks like this (which is enough to show the change in behavior):
```
val ktlintConfig: Configuration by configurations.creating

dependencies {
    ktlintConfig(libs.ktlint) {
        attributes {
            attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling.EXTERNAL))
        }
    }
}
```

This is referencing a ktlint library I have defined in libs.versions.toml.

That works up through version 8.0.2.

### Current Behavior

Starting with version 8.1 this no longer works and fails with an error:

```
Script compilation error:

  Line 4:     ktlintConfig(libs.ktlint) {
                           ^ Unresolved reference: libs

1 error
```

### Context (optional)

Prevents upgrading past 8.0.2

### Steps to Reproduce

Reference libs in a kts file included using apply

### Gradle version

8.1

### Your Environment (optional)

Mac OS

**Comment by Liamtoha** [comment]
Triage

**Comment by eskatos** [comment]
Accessing version catalogs from applied scripts via names was working by accident in Gradle < 8.1.
For sharing logic you should prefer using convention plugins instead of applied scripts.
In applied scripts you should use the API to access version catalogs as demonstrated above.
We do not plan to fix this.

**Comment by ZOlbrys** [comment]
I have a similar use case as original poster:

```
val ktlint: Configuration by configurations.creating

configurations {
    ktlint
}

dependencies {
    ktlint(libs.ktlint)
}
...
```

Gives me an error.  If I try the workaround you posted above I get an error:

```
FAILURE: Build failed with an exception.

* Where:
Script '<path_to_file>'/ktlint.gradle.kts' line: 8

* What went wrong:
Extension with name 'libs' does not exist. Currently registered extension names: [ext, npm, devNpm, optionalNpm, peerNpm]
```

@eskatos just to be clear, something like https://github.com/gradle/gradle/issues/24426 is no longer valid then?  It sounded like this was supposed to address issues accessing `libs` values in applied kotlin scripts - exactly what I'm doing here unless I am mistaken!

I appreciate any assistance with this matter, still learning about Gradle :) thank you!

**Comment by eskatos** [comment]
Applied scripts don't get accessors, see https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:accessor_applicability
For sharing logic you should prefer using convention plugins instead of applied scripts.
In applied scripts you should use the API to access version catalogs as demonstrated above.
We do not plan to fix this.
