### ISSUE TITLE
Subprojects should be able to register their own dependency substitution rules for when they are used in an included build

### ISSUE THREAD

**Issue by ZakTaccardi** [gradle/gradle#25001]
### Expected Behavior
An included subproject (`:lib` in this case) should have a way to indicate that this subproject "matches" `com.company.sdk:library` - without requiring the names to match up perfectly.

### Current Behavior (optional)

We currently need to do the following to get included builds to substitute external module dependencies for local included project dependencies.

```kts
// inside of main app repo's `settings.gradle.kts`
includeBuild("../sdk") {
    dependencySubstitution {
        substitute(module("com.company.sdk:library")).using(project(":lib"))
    }
}
```

### Context

Our company has a main app and an internal company SDK as separate github repos. From within our main app, we would like to be able to do any included build, easily, without having to write special dependency substitution rules.

A mechanism to write tests for this would be good too - I want to know that `com.company.sdk:library` will match `project(:lib)` _before_ having to manually test this in an included build and hoping there is a match.

**Comment by jbartok** [comment]
No, we will not do that. The contract is always that a project will automatically replace if it matches the coordinates. If it doesn't, then it's the including build that has to specify that information. One complicating factor is that the project name should reflect root coordinates. But, we have problems with that, because it would complicate all path references.

Related issue:
* https://github.com/gradle/gradle/issues/847
