### ISSUE TITLE
org.gradle.libraryelements inside of ResolvedComponentResult often doesn't match reality

### ISSUE THREAD

**Issue by tprochazka** [gradle/gradle#25012]
### Expected Behavior

```
runtimeConfiguration.incoming.resolutionResult.rootComponent.get().dependencies.foreach {
   if (dependency is ResolvedDependencyResult) {
        val packaging = it.selected.variants.single().attributes.getAttribute(
                Attribute.of("org.gradle.libraryelements", String::class.java)
        ) 
   }
}
```
Should return current dependency type like jar, aar, wat, etc.

### Current Behavior

But it actually returns very often just jar even when it is something else in reality.

I would tell that it works only when .module is inside of gradle modules-2 cache.
But I'm not sure.

### Context (optional)

I need to list all dependencies from the task in a way compatible with GradleCache. I was before using `ResolvedArtifactResult`, but it is not working with Gradle cache, even when documentation tells that yes. So I migrated my project to using `ResolvedComponentResult` instead and there is issue with packaging/artifact type/org.gradle.libraryelementsan 

### Steps to Reproduce

Use dependency like
```
implementation("androidx.cursoradapter:cursoradapter:1.0.0")
```

And get artifactType by

```
runtimeConfiguration.incoming.resolutionResult.rootComponent.get().dependencies.foreach {
   if (dependency is ResolvedDependencyResult) {
        val packaging = it.selected.variants.single().attributes.getAttribute(
                Attribute.of("org.gradle.libraryelements", String::class.java)
        ) 
   }
}
```
Screenshot from debugger:
![image](https://user-images.githubusercontent.com/172094/236579291-728bbe65-3d86-4a89-9f26-68513802db7c.png)

### Gradle version

8.1.1

### Your Environment (optional)

Windows 11, Java 17

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***
[`org.gradle.libraryelements`](https://docs.gradle.org/current/userguide/variant_attributes.html#ecosystem_independent_standard_attributes) is a variant level attribute that classifies what is the type of `library` you are looking at. `JAR` is used to indicate JVM libraries, covering for `war`, `ear` and `aar` broadly.

In order to see what you expect, you need to look at artifact level attributes and the [`attributType` attribute](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/type/ArtifactTypeDefinition.html).

**Comment by tprochazka** [comment]
So there is no way how to get artifact type? Why?

**Comment by tprochazka** [comment]
It is stored directly in metadata, in pom.xml file
