### ISSUE TITLE
Indicate that StartParameter.getProjectCacheDir is not a directory that plugins can write to

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#25096]
### Issue type

Inaccurate docs

### Problem description

https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#getProjectCacheDir-- seems to suggest that it is a reasonable place to put gradle plugin data that needs to survive buildDir removals.

### Page with the problem

https://docs.gradle.org/current/javadoc/org/gradle/StartParameter.html#getProjectCacheDir--

**Comment by ljacomet** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

---

The documentation should indicate that the project cache dir is for Gradle internals, something like:
> Sets the project's cache location. Set to null to use the default location. Note that this folder is reserved for Gradle internal state and plugins are not expected to write anything there.
