### ISSUE TITLE
Show Progress Bar with Build Success or Failure at end of build

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#2511]
Follow up to  #2447 

Goal: Show how much of the build completed before the outcome. 

```
<===------> 37% BUILD FAILED [35s]
250 actionable tasks: 35 from cache, 57 up-to-date
```

**Comment by big-guy** [comment]
I'm not sure if this is very useful.

I think for many builds, the number of failed tasks is always going to be a ~small number because you're not going to see more failed tasks without using --continue.  I'm not sure the percentage has any real meaning.  If you have 99% built and a failure, fixing it might mean redoing all 99% again or just re-running the last 1%.  If you have a failure at 1%, the other 99% might have failed too or you might get 30% built the next time before the first failure (because of a different ordering) without changing anything.

I also don't think showing the progress bar itself is a good representation of this.  We could just add the number of failed tasks to the summary like:

> BUILD FAILED in 3s
> 6 actionable tasks: 6 executed, 1 failed

I think this information is already in the build failure message, but it's probably at the top/hard to find.
