### ISSUE TITLE
Allow extra keys in versions catalog toml

### ISSUE THREAD

**Issue by cometkim** [gradle/gradle#25147]
### Expected Behavior

I want to extend `libs.versions.toml` data with some extra keys for third-party tooling. for example, adding `dev = true` to mark only dev-only libraries.

```
[libraries]
junit = { group = "junit", name = "junit", version = "4.13.2", dev = true }
```

### Current Behavior (optional)

I cannot use it because gradle checks the data schema too strictly.

```
java.lang.RuntimeException: org.gradle.api.InvalidUserDataException: On library declaration 'junit' expected to find any of 'group', 'module', 'name' or 'version' but found unexpected key 'dev'.
    at org.gradle.api.internal.catalog.DefaultDependenciesAccessors.generateAccessors(DefaultDependenciesAccessors.java:144)
    at org.gradle.configuration.BuildTreePreparingProjectsPreparer.generateDependenciesAccessorsAndAssignPluginVersions(BuildTreePreparingProjectsPreparer.java:87)
    ...
```

### Context

I've separated the dependency declarations into separate toml files so that I can share metadata with other tools as well as gradle.

However, the declaration in gradle contains too little information. You can make more integrations possible by loosening the schema checks just a little bit.

**Comment by jbartok** [comment]
Relates to
* #19517

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

We don't intend to allow for such random additions to the format because it might potentially break external tooling. 

***

If the only thing you need to achieve is to separate production and development dependencies, you can just declare a second version catalog (see [here](https://docs.gradle.org/current/userguide/platforms.html#sec:importing-catalog-from-file)).
