### ISSUE TITLE
Custom gradle distribution, daemon, and dependencies

### ISSUE THREAD

**Issue by jeffalder** [gradle/gradle#25203]
### Expected Behavior

I have an init-script plugin I'm packaging with my custom gradle distribution. When I create the zip file, I add it in `lib/plugins/my-plugin.jar`, and I have an init script that has this:

```groovy
initscript {
    dependencies {
        classpath files("${gradle.getGradleHomeDir()}/lib/plugins/my-plugin.jar")
    }
}

import my.plugin.PluginMain
apply plugin: PluginMain
```

I wrap gradle 8.1.1 and package it as 8.1.1-1a1 using a `Zip` task and setting the `version` in build.gradle that generates the distribution `-bin.zip`.

## I expect

I expect builds using 8.1.1-1a1 apply the initscript and the plugin and builds using 8.1.1 don't apply the initscript or the plugin.

### Current Behavior

Unfortunately, the resulting daemon only appears to know the _distributed_ version of gradle, 8.1.1. The daemon code doesn't recognize my 8.1.1-1a1 as different. So I'll get an error if the daemon starts with vanilla 8.1.1, then I try to run and 8.1.1-1a1 build.

```
* What went wrong:
Could not compile initialization script '/Users/jeffalder/.gradle/wrapper/dists/gradle-8.1.1-1a1-bin/t4ldwrtb8feiy4003o5xtatz/gradle-8.1.1/init.d/my-plugin.gradle'.
> startup failed:
  initialization script '/Users/jeffalder/.gradle/wrapper/dists/gradle-8.1.1-1a1-bin/t4ldwrtb8feiy4003o5xtatz/gradle-8.1.1/init.d/my-plugin.gradle': 1: unable to resolve class my.plugin.PluginMain
   @ line 7, column 1.
     import my.plugin.PluginMain
     ^
```

### Context (optional)

It has been fairly bumpy trying to distribute this new initscript plugin. I have a lot of confused users -- including myself.

I also suspect that I can fix the version issue if I can get the "right" version in the daemon. I just don't know how to set that.

### Steps to Reproduce

Repro test case:
1. Clone https://github.com/jeffalder/gradle-25203-repro
2. Run `./fail.sh`

Net:
1. Write a compiled (`.jar`) plugin and add it to lib/plugins in the custom gradle distro
2. Write an init script that adds the plugin to the classpath and loads it
3. Add init script to custom gradle distro in init.d
4. Start a daemon using _vanilla_ Gradle, same version as the custom gradle distro
5. Try to run anything in a project using the custom gradle distro.

### Gradle version

8.1.1

**Comment by jeffalder** [comment]
Ok. So the daemon figures its version from `DefaultGradleVersion`, which loads it from `org/gradle/build-receipt.properties` which contains, on my custom build:

```
% unzip -c gradle-base-services-8.1.1.jar org/gradle/build-receipt.properties
Archive:  gradle-base-services-8.1.1.jar
  inflating: org/gradle/build-receipt.properties
baseVersion=8.1.1
buildTimestamp=20230421123126+0000
buildTimestampIso=2023-04-21 12\:31\:26 UTC
commitId=1cf537a851c635c364a4214885f8b9798051175b
isSnapshot=false
versionNumber=8.1.1
```

Am I intended to rewrite that file? Is there another way to provide the Gradle version to the daemon and its connection?

**Comment by jeffalder** [comment]
Also - am I correct that even if I had specified the plugin as a maven dependency, it still would have failed?

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

You're right, the fact that the plugin is in the distro zip or coming from an external repository doesn't change the situation.

This happens because _repackaging_ the Gradle distribution will not change its version metadata and then the Gradle Daemon selection doesn't distinguish a vanilla distribution and a custom one. For this not to happen you need to kill daemons when changing from vanilla and custom distros.

This should be explained in the documentation and that is currently missing.
This is a valid documentation issue that we will address.

----

The only way to use a custom version number would be to build a Gradle distribution from source. Controlling the version number is currently unsupported though. If this is what you are after, please open a feature request in this regard.

You might get help from folks doing custom distribution in the community slack or the forum. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

**Comment by jeffalder** [comment]
@eskatos thanks for your response and for the bad news. :-) I'm _really_ not interested in rebuilding from source.

In my situation:
* Everyone using my custom distribution should be using the custom distribution for everything.
* We rarely publish multiple custom distribution versions on top of a single upstream Gradle version. 
* Our CI won't run into this issue because builds are isolated.

As this isn't likely to be an ongoing issue (because we'll be including the plugin in all future custom distributions), I'm not going to pursue anything further. It should be enough to tell folks to `./gradlew --stop` if they run into the issue.
