### ISSUE TITLE
--no-daemon does not work and returns an unhelpful error message

### ISSUE THREAD

**Issue by sergeykad** [gradle/gradle#25272]
### Expected Behavior

Starting Gradle with `--no-daemon`  flag will not start a daemon.

### Current Behavior

The daemon is used and the following not-helpful message is printed:
```
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.1/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
```

Running Gradle with `--info` flag produces a bit more information, but it is still not clear how to make Gradle run without the daemon. The link in the message does not provide any useful information either.

### Context (optional)

JDK 17

### Steps to Reproduce

Run `./gradlew --no-daemon build`

### Gradle version

8.1

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

The most likely explanation for the behavior you see is that the JVM you use for running Gradle is not [compatible](https://docs.gradle.org/8.1/userguide/gradle_daemon.html#compatibility) with the needs of your build (for example, you use Java toolchains, which require a different JVM version). Without a reproducer, we can't help.

**Comment by Phlegethon90** [comment]
You have to tune JVM options to accomplish this.

**Comment by sergeykad** [comment]
It is at the very least a documentation issue and you can see the relevant information here: https://docs.gradle.org/8.1/userguide/gradle_daemon.html#sec:disabling_the_daemon
The documentation and the error message state that adding `--no-daemon` is enough but it actually does not work in many cases. As @Phlegethon90 menioned

> You have to tune JVM options to accomplish this.

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

*** 

This works as expected, but we need to improve the documentation so that it becomes clearer.

In modern Gradle versions, "no-daemon" really just means "no long-lived daemon."
To use the launcher as the JVM running the build, several memory options need to be set, which should be explicitly documented.

**Comment by chanseokoh** [comment]
> To use the launcher as the JVM running the build, several memory options need to be set

Here's how to figure out such options: https://github.com/gradle/gradle/issues/2660#issuecomment-602628786

**Comment by Vampire** [comment]
What you have to set for `GRADLE_OPTS` actually depends on the wrapper you use and the project you try to start.

Old wrappers used no hard-coded max-heap setting and thus are considered compatible enough if you just specify the instrumentation agent.
With a newer wrapper, the max heap is set to `64m` which is considered too low, so you need at least to also increase that to some other value.

Other than that, there are a handfull of JVM args and system properties which are immutable or effectively immutable. If those are requested as daemon args, they also have to be in `GRADLE_OPTS` accordingly so that the current process is considered compatible and no single-use daemon is started.

The logic for all that is too complex, as it would need to be done in the `gradlew` scripts to build a proper `GRADLE_OPTS` if `--no-daemon` is given so that the started process is directly usable as build process.

In most cases it is much easier and safer to just not care and live with the single-use daemon. :-)

**Comment by sergeykad** [comment]
@Vampire Yeah, I understand it now. This issue is more about the documentation, since it does not reflect what you explained at all and promises that no daemon will be created.

**Comment by Vampire** [comment]
Yes and no.
The docs state "The Daemon is a long-lived background process".
Using `--no-daemon` neither an existing long-lived background process is reused, nor is a new **long-lived** background process started, but only a short-lived one.
So one could argue that the documentation is correct. :-D

It is a bit unclear though, that's why this issue exists and was accepted by the Gradle guys as documentation issue.

Just wanted to provide some insight here for others finding this issue. :-)

**Comment by Mrkchv** [comment]
We are encountering similar behavior of gradle version 8.1 when adding `org.gradle.daemon=false` to the global `gradle.properties` file and setting the `JAVA_TOOL_OPTIONS` environment variable with arguments identical to the project's `gradle.properties`.

Periodically, the assembly fails with an error: "org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)".

We run the assembly on our CI in a docker container and everything worked on gradle version 8.0.2. We don't need Gradle Daemon, since the assemblies are isolated from each other. I also tried to use the `GRADLE_OPTS` and `JAVA_OPTS` environment variables inside our docker image, but it didn't help.

**Comment by volo-droid** [comment]
> In modern Gradle versions, "no-daemon" really just means "no long-lived daemon."
> To use the launcher as the JVM running the build, several memory options need to be set, which should be explicitly documented.

@jbartok 
Would it be viable to have an option that sets the necessary memory configuration up (overriding it if needed) and thus completely disables single-use daemon creation? The current manual solution can be a bit cumbersome especially when a wrapper is involved. 

Alternatively, it'd be helpful have at least a message like: "Gradle cannot honor the requested --no-daemon option, because your current JVM/Gradle configuration is: XXX, but the project requests: YYY, if you'd like to avoid single-use daemon creation please set GRADLE_OPTS and JAVA_OPTS to YYY".

**Comment by byteflys** [comment]
> > In modern Gradle versions, "no-daemon" really just means "no long-lived daemon."
> > To use the launcher as the JVM running the build, several memory options need to be set, which should be explicitly documented.
> 
> @jbartok Would it be viable to have an option that sets the necessary memory configuration up (overriding it if needed) and thus completely disables single-use daemon creation? The current manual solution can be a bit cumbersome especially when a wrapper is involved.
> 
> Alternatively, it'd be helpful have at least a message like: "Gradle cannot honor the requested --no-daemon option, because your current JVM/Gradle configuration is: XXX, but the project requests: YYY, if you'd like to avoid single-use daemon creation please set GRADLE_OPTS and JAVA_OPTS to YYY".
> 
> UPD: I've found out a similar behavior has been already requested here: [#16110 (comment)](https://github.com/gradle/gradle/issues/16110#issuecomment-1337536189)

question is, how do i decide or get the right YYY

**Comment by Vampire** [comment]
Run with`--debug` to find in the output which arguments are used to start the daemon. Then set them all and remove one after the other to see which are necessary. Typically the memory arguments and the instrumentation agent. 

But really, the CLI process is really lightweight. It is in most cases pretty much wasted effort trying to avoid the daemon being started.

**Comment by gajicm93** [comment]
> Thank you for your interest in Gradle!
> 
> This is a valid documentation issue that we will address.
> 
> This works as expected, but we need to improve the documentation so that it becomes clearer.
> 
> In modern Gradle versions, "no-daemon" really just means "no long-lived daemon." To use the launcher as the JVM running the build, several memory options need to be set, which should be explicitly documented.

How is this closed? Is the documentation updated? I still have problem with this..

**Comment by Vampire** [comment]
Kind of, the according PR added the sentence 

> No Daemon :: If the `JAVA_OPTS` and `GRADLE_OPTS` match `org.gradle.jvmargs`, the Daemon will not be used at all since the build happens in the client JVM.

This is "a bit" simplified but should at least make it clearer that `--no-daemon` does not mean "no daemon". :-D

**Comment by gajicm93** [comment]
> Kind of, the according PR added the sentence
> 
> > No Daemon :: If the `JAVA_OPTS` and `GRADLE_OPTS` match `org.gradle.jvmargs`, the Daemon will not be used at all since the build happens in the client JVM.
> 
> This is "a bit" simplified but should at least make it clearer that `--no-daemon` does not mean "no daemon". :-D

I tried to make it match and it's still not working, and the log doesn't make it clear what's wrong..

**Comment by Vampire** [comment]
As I said, it is majorly oversimplified.
Use the `--debug` log to find the options used to start the daemon.
What you usually need to have as it is not modifiable after starting the JVM are the memory options and the instrumentation agent option, which most probably is the one you miss.
