### ISSUE TITLE
Provide consistent DSL for included projects and builds

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2527]
@adammurdoch commented on [Wed Mar 08 2017](https://github.com/gradle/composite-builds/issues/87)

We have:

`include(String projectPath)` where `projectPath` is a project path identifier (eg `a:b`), rather than a directory, and from which we infer the project directory

vs:

`includeBuild(Object buildDirectory)` where `buildDirectory` is converted to a directory, and from which we infer the build identifier.

We have:

`includeBuild(directory) { config action }`

but no

`include(project) { config action}`

We use the type `ProjectDescriptor` to represent a configurable definition of a project, and `ConfigurableIncludedBuild` to represent a configurable definition of a build. All aspects of a project can be configured, only dependency substitutions of a build can be configured.

We have various query methods to find a project descriptor to allow it to be further configured, but no such methods for a build descriptor.

These should all be consistent in pattern and terminology, and use strong types to represent various parameters, something like:

```
includeProject(File projectDir)
includeProject(File projectDir) { ConfigurableProjectDefinition p -> ... ]
includeBuild(File buildDir)
includeBuild(File buildDir) { ConfigurableBuildDefinition b -> ... }

DomainObjectContainer<ConfigurableProjectDefinition> getProjects()
projects(Action<? super DomainObjectContainer<ConfigurableProjectDefinition>)

DomainObjectContainer<ConfigurableBuildDefinition> getBuilds()
builds(Action<? super DomainObjectContainer<ConfigurableBuildDefinition>)
```

**Comment by bamboo** [comment]
Could the `collection(Action<? super DomainObjectContainer<element>>)` methods be added to the Groovy DSL via decoration?

They create a potential ambiguity in the Kotlin DSL.

**Comment by big-guy** [comment]
Is the ambiguity between the getter and the "collection" method?

**Comment by bamboo** [comment]
@big-guy yes, between the getter and the collection method in the context of an invocation. The ambiguity exists because the Kotlin DSL provides an overloaded `invoke` operator for `DomainObjectContainer`.

Thus the Kotlin expression `collection { }` can mean either `collection({ })` or `getCollection().invoke({ })` depending wether the `collection(Action<...>)` method is there or not.

The overloaded `invoke` operator executes the given configuration block against a decorated `DomainObjectContainer` that provides a richer API and additional overloads, it's what make [this example](https://github.com/gradle/kotlin-dsl/blob/03ce92299825c059da81485484c98e27e12c554f/samples/domain-objects/build.gradle.kts#L11) work.
