### ISSUE TITLE
Support composite builds for `plugins` block

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#2528]
@oehme commented on [Fri Oct 14 2016](https://github.com/gradle/composite-builds/issues/80)

Currently dependency substitution only works for plugins used in the `buildscript` block. Since we want people to use the `plugins` block instead, we have to make those work with composites. We'll probably need an additional plugin resolver that looks for plugins in the composite context. We'll also need some way for included builds to specify which plugins they expose. Both usages could be as simple as reusing our plugin marker publications (requires composites to support custom publications).

---

@bigdaz commented on [Tue Jul 18 2017](https://github.com/gradle/composite-builds/issues/80#issuecomment-316127617)

I finally took some time out to investigate this issue, and I was surprised how much functionality actually does work when using composite builds, `pluginManagement` and `plugins`.

I found 2 ways that make it fairly easy to develop a plugin using a composite build and the `plugins` block:
- If the plugin has been published with a marker artifact to a repository, referencing that repository in `pluginManagement` is sufficient. The pluginId will be resolved to a dependency using the repository, but the included build will then be used to satisfy that dependency.
- If the plugin has never been published with a marker artifact, then a 'Plugin resolution rule' can be used to specify the mapping of plugin id -> dependency coordinates. Again, the included build will satisfy that dependency.

So the main piece of missing functionality is the ability to change a plugin id, or add a new plugin id to an existing project, and for this to automatically be resolved in a composite build. For now, the new plugin id needs to be explicitly published (once) or a rule needs to be provided to map that id.

---

@oehme commented on [Tue Jul 18 2017](https://github.com/gradle/composite-builds/issues/80#issuecomment-316136984)

It would be great if this just worked out of the box. We know the publications of a project and we could change the plugin resolver to always look for the marker artifact even if no repos are defined. If the composite could respect custom publications, then the plugins block would work seamlessly.

> So the main piece of missing functionality is the ability to change a plugin id, or add a new plugin id to an existing project

I'm not quite sure what this means. A project already declares the plugins it contains through marker artifacts. 

---

@bigdaz commented on [Tue Jul 18 2017](https://github.com/gradle/composite-builds/issues/80#issuecomment-316142184)

I'm certainly not saying that things are complete, just that the missing functionality is perhaps not as much of a blocker as I had originally understood. This might affect our prioritization of this work.

> It would be great if this just worked out of the box.

Yep, for sure. I'd like to understand how a 'normal' project with custom plugins and a consuming build  using the `plugins` block would look. What changes would they need to make to temporarily switch to a composite build so they can work on the plugin?

It seems like they would already have a `pluginManagement` block with the custom plugin repository defined, which would mean all they would need to do is `--include-build ../my-plugin-build` and the composite would just work. It would "work" by resolving the plugin id from the repository, but in this use case that should be fine.

Please correct me if I'm making some incorrect assumptions here: I've just started looking at `pluginManagement`.

>> So the main piece of missing functionality is the ability to change a plugin id, or add a new plugin id to an existing project

> I'm not quite sure what this means. A project already declares the plugins it contains through marker artifacts. 

Sorry if I wasn't clear. The critical part of that sentence was _"and for this to automatically be resolved in a composite build"_. So of course it's possible to do these things, but these are cases where the composite build will break down.

---

@oehme commented on [Wed Jul 19 2017](https://github.com/gradle/composite-builds/issues/80#issuecomment-316344016)

> Yep, for sure. I'd like to understand how a 'normal' project with custom plugins and a consuming build using the plugins block would look. What changes would they need to make to temporarily switch to a composite build so they can work on the plugin?

They'd need to make no changes at all. The `java-gradle-plugin` plugin already adds the plugin marker publications, so the composite build could pick those up. The plugin resolver on the consuming side would then look for the marker artifact, which would get substituted for the project inside the composite.

> It seems like they would already have a pluginManagement block with the custom plugin repository defined, which would mean all they would need to do is --include-build ../my-plugin-build and the composite would just work.

This assumes that the plugin has been published already. This doesn't work when I'm just getting started or when I'm writing a plugin that's only meant to be consumed inside my repo (e.g. composite replacing `buildSrc`.

For already published plugins, things should work pretty well in the current state, as you said.

**Comment by adammurdoch** [comment]
I think this is "working" by exploiting a bug in the implementation of plugin resolution. I wouldn't consider this as implemented in any way.

**Comment by eskatos** [comment]
So, the path forward is twofold:
- plugin resolution doing dependency resolution, always, to get across composites
- composites exposing all publications from included build's projects to allow plugin marker artifacts to be resolved

On the plugin resolution side, things are quite messy.

Only the ivy and maven plugin repositories support is wired to the dependency resolution services. The Gradle Plugin Portal "plugin repository" is using the proprietary protocol to communicate with the portal, is not using dependency resolution services, hence not looking in the composite builds context.

The portal plugin repository is enabled by default. As soon as you add a custom plugin repository, the portal resolver is disabled, you then have to register it explicitly.

Meaning that if you don't declare any custom plugin repository, then plugin resolution cannot reach included build's projects. And that as soon as you add a custom plugin repository, it can.

Using the M2 url of the plugin portal, or any other url, like an empty local directory, is enough.

This is broken in many ways.

Here is a sample composite build demonstrating this and using a plugin resolution rule to work around the fact that plugin markers extra publication is not exposed by included build's projects: https://github.com/eskatos/composite-gradle-plugins-build

A quick fix is to always add a plugin resolver that do proper dependency resolution in front of all the plugin repositories. This could be done as a first step.

We already considered removing any special handling of the Gradle Plugin Portal ; effectively considering it as a regular maven repository. It feels to me that working on this issue is a good time to do it. It will remove quite a bunch of code paths & types in plugin resolution, make it simpler.

Once this is done, remains the lack of support for resolving custom publications across composite builds. The latter can be worked around with "just" a plugin resolution rule on the consumer side, which is much more understandable than the plugin repository "trick" described above.

**Comment by mkobit** [comment]
This would be really useful for iterating on plugins quickly when bugs are reported. Another use case would be for backwards compatibility testing with consumers. We already have TestKit for running against multiple versions and known test cases, but being able to to also rebuild against consumers easily would allow for earlier detection of problems.

I don't know if `--include-build` implies ordering now, but something like the following would be cool to:

1. build me first
1. retrieve consumers (in this example a consumer is known and hardwired)
1. then, run the build of that consumer with the substitution

```
~/home/myPlugin -> ./gradlew build --include-build https://githubcloneurl.git
```

**Comment by mkobit** [comment]
Also, I don't believe this is working (even by chance) anymore (at least in 4.2.1).

**Comment by eskatos** [comment]
The first part, plugin resolution using regular dependency resolution services, has been delivered as part of #3347 and will be included in Gradle 4.4-RC1.

The only missing piece now is resolving included builds custom publications.

It can be worked around by using a plugin resolution strategy mapping the plugin `id` to the main plugin artifact.

**Comment by bamboo** [comment]
Another technique that works quite well since [the `plugins` block started to allow requests for plugins already on the classpath](https://github.com/gradle/kotlin-dsl/commit/2b11b0861566c9f693ba143c67be45ee163760d6) is to [inject a dependency to the included build in the buildscript classpath of the root project](https://github.com/gradle/kotlin-dsl/commit/2b11b0861566c9f693ba143c67be45ee163760d6).

This makes all plugins visible from the classpath published by the included build available to all projects. 

The downside is that this injection is not completely transparent to build scripts as it requires any plugin dependency spec to one of these plugins NOT to include the version.

**Comment by mkobit** [comment]
Is this already planned as part of native - https://github.com/gradle/gradle-native/issues/522 ?

**Comment by big-guy** [comment]
@mkobit Yes, I was hoping we would have started by now so I could give you an update and let you know how you could help.  We haven't started yet and we haven't done the analysis of exactly what needs to change.  I'll let you know when we do start.

**Comment by mkobit** [comment]
https://github.com/gradle/gradle/issues/2529 is also worth considering here, as I find myself frequently using the shadow plugin to relocate dependencies so that they don't impact consumers.

**Comment by JLLeitschuh** [comment]
Now that the Gradle Kotlin DSL has become so reliant upon the `plugin` block, this should really become a higher priority.

https://github.com/gradle/kotlin-dsl/issues/1178

**Comment by adammurdoch** [comment]
This is fixed via https://github.com/gradle/gradle/pull/7709

**Comment by wolfs** [comment]
@adammurdoch Can this issue be closed?

**Comment by mkobit** [comment]
The user guide still says:

> Substituting plugins only works with the `buildscript` block but not with the `plugins` block.

**Comment by big-guy** [comment]
@mkobit this is changed in the nightly: https://docs.gradle.org/nightly/userguide/composite_builds.html

**Comment by mkobit** [comment]
Thanks @big-guy - I was thinking this got into 5.0 and was excited to try it out. Really looking to 5.1 now :+1:

**Comment by tprochazka** [comment]
I just tried to do that and I'm not able to make it work.

It always fails with

* What went wrong:
Plugin [id: 'com.myplugin'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Included Builds (None of the included builds contain this plugin)
- Plugin Repositories (plugin dependency must include a version number for this source)

I just put includeBuild("plugin") to the settings.gradle.kts and plugin folder contains plugin which defines com.myplugin
