### ISSUE TITLE
IntelliJ `@Language` injection annotation does not work in build scripts

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#25310]
### Expected Behavior

I would like to use [IntelliJ Language Injection annotation](https://www.jetbrains.com/help/idea/using-language-injections.html#language_annotation) to support writing languages in code.

This can be useful for a number of reasons:

* When generating code I can `@Language("kotlin")` to get auto complete.
* A URL property can be annotated with `@Language("http-url-reference")`, which makes the link clickable
* syntax errors in JSON can be highlighted `@Language("JSON")`
* and IntelliJ can suggest local file references `@Language("file-reference")` so I can ctrl+click on the path defined in a string to navigate directly to the file, and additionally IntelliJ will highlight files that do not exist.

### Current Behavior

I cannot access the `@Language` annotation

```kotlin
// build.gradle.kts

@org.intellij.lang.annotations.Language("JSON")
val myJson = """
    {
      "test": 123
    }
""".trimIndent()
```

A `@Language` annotation is available, but Gradle changes the package name

```
@org.gradle.internal.impldep.org.intellij.lang.annotations.Language("JSON")
val myJson = """
    {
      "test": 123
    }
""".trimIndent()
```

### Context (optional)

IntelliJ requires that the annotation exactly matches the one defined in the settings, `Preferences | Editor | Language Injections | Advanced`.

<img width="389" alt="image" src="https://github.com/gradle/gradle/assets/897017/6e3f0c33-2d73-4b52-9986-201af7d9766f">

Since Gradle has changed the package name to a different one, the language injection doesn't work.

### Steps to Reproduce

See above

### Gradle version

8.1.1

**Comment by jbartok** [comment]
Thank you for your interest in Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Try to add the necessary dependency to the buildscript classpath configuration.
The one you find is there because Gradle does shade the JetBrains annotations, but it should, in fact, not be exposed through the API.

**Comment by aSemy** [comment]
Thanks @jbartok, that makes sense. Since the annotation has no effect, perhaps it should be removed?

**Comment by KENNYSOFT** [comment]
It seems to be an issue of IntelliJ IDEA, not Gradle.

https://youtrack.jetbrains.com/issue/KTIJ-18438
