### ISSUE TITLE
Task stuck in 100% CPU loop within FinalizerGroup/DefaultExecutionPlan.finalizePlan  on Gradle 7.6+

### ISSUE THREAD

**Issue by chadlwilson** [gradle/gradle#25361]
### Expected Behavior

`./gradlew server:fastUnitTest` of https://github.com/gocd/gocd should execute fine for `Gradle 7.6+`, as it does on Gradle `7.5.1`.

This task is [defined here](https://github.com/gocd/gocd/blob/40f4b139f5fe99198679d91434c6c6b80f6b7dbd/server/build.gradle#L365-L397), and I cannot identify anything special about it to guess at the root cause or find a workaround.

### Current Behavior

On Gradle `7.6`, `7.6.1`, `8.1.1` and possibly other versions running this task just gets stuck `CONFIGURING` and never terminates.

Debug logs end with

```
2023-06-12T21:23:16.180+0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Completing Build operation 'Calculate task graph'
2023-06-12T21:23:16.180+0800 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationRunner] Build operation 'Calculate task graph' completed
2023-06-12T21:23:24.474+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-06-12T21:23:24.476+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-06-12T21:23:24.476+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-06-12T21:23:24.477+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-06-12T21:23:24.477+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-06-12T21:23:24.477+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-06-12T21:23:34.473+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-06-12T21:23:34.474+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-06-12T21:23:34.474+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2023-06-12T21:23:34.475+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2023-06-12T21:23:34.475+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2023-06-12T21:23:34.475+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
.... and on ever 10 seconds
```

Profiler samples always look something like

![image](https://github.com/gradle/gradle/assets/29788154/af0e46fd-c433-494c-bd1c-cab4f26babd7)
![image](https://github.com/gradle/gradle/assets/29788154/9ca10485-2b39-4f06-89b9-78d8c0e2c275)

### Context (optional)

The intent here is to just run a custom test task against an alternate java source set defined in a custom `configuration` earlier. I have not found a workaround for this.

### Steps to Reproduce

Requires JDK 17 on path or locatable via Gradle toolchain

```shell
git clone https://github.com/gocd/gocd
git checkout 23d5610cee3682e8e6e3375b58a6f240416954ec
./gradlew server:fastUnitTest --tests GoConfigDaoBasicTest
# See that it is stuck
```

Downgrade and see that it gets past configuring
```
./gradlew wrapper --gradle-version=7.5.1 --gradle-distribution-sha256-sum=db9c8211ed63f61f60292c69e80d89196f9eb36665e369e7f00ac4cc841c2219 --distribution-type=ALL
./gradlew server:fastUnitTest --tests GoConfigDaoBasicTest
# See that configuring completes and thinks start compiling/executing
```

### Gradle version

8.1.1

### Gradle version that used to work

7.5.1

### Your Environment (optional)

- Apple MacBook M1 Pro
- MacOS Ventura 13.4
- Java 17.0.7

**Comment by chadlwilson** [comment]
I note various work in this broad area, e.g in #21116 #21997 #21542 #21975

It has the broad same observable behaviour (livelock) as #20455 but understand that ticket is a generic issue and not really resolvable.

**Comment by ghale** [comment]
I've taken a look at this and, in fact, this it not a hang, but just some _really_ inefficient code.  It will actually finish calculating the task graph after about an hour and a half (depending on the horsepower of your machine).  There are about 1400 tasks that get executed with `fastUnitTest` and it appears that we have some logic that runs in at least O(n^2) time (maybe even O(n^3) time, I'm not sure) relative to the number of tasks.  

In any event, we need to optimize this.  In the meantime, the following workaround will get you around the problem (i.e. the issue is related to the fact that the test tasks are both dependencies of and finalized by the report task):

```
@@ -679,7 +679,7 @@ task allTestsJunitHtmlReport(type: TestReport) { TestReport thisTask ->
   description = "Run all api tests"

   forAllTask { Test eachTestTask ->
-    testResults.from(eachTestTask)
+    testResults.from { eachTestTask.binaryResultsDirectory.get().asFile }
     eachTestTask.finalizedBy(thisTask)
   }
   destinationDirectory = file("${project.buildDir}/reports/tests/allTests")
```

**Comment by chadlwilson** [comment]
Thank you very much! Will give that a go.

Do you think this might bes something to do with the changes for `finalizedBy` and `mustRunAfter` in Gradle 7.6 or so? https://github.com/gradle/gradle/issues/10549 (we have some `mustRunAfter`s I don't quite understand)

I don't quite understand why the same behavior isn't observed when running `./gradlew allTests`, or other individual test tasks, i.e what is special about trying to run this one single task that triggers the O(n^2+) processing.

Perhaps I could consider removing `allTestsJunitHtmlReport` as relevant when running an individual test task; i.e make it only apply when running `allTests`. I think [it was changed to finalize all tasks always](https://github.com/gocd/gocd/commit/0b4e8ab74814c884ae4d6d115b65690c0f0f3776) for some reason. Perhaps the issue is triggered by the weird `afterEvaluate` stuff?

I do note however that we have a 
- whole lot of warnings about needing to use `tasks.register` and `tasks.withType(..).configureEach` to defer configuration which may relate to why this is painful.
- some hacks in there still lingering around that seemed to be due to long-removed use of gradle-testsets-plugin including [the forAllTasks afterEvaluate](https://github.com/gocd/gocd/blob/97661a800a4aa610ebd907c99a2e20858c62d9a9/build.gradle#L655-L656)
- we also have other problems with some of the custom stuff being done here, like filtering test tasks with `--tests` not working properly and running tests for dependent tasks (!!), so probably I need to review/simplify everything in this "test task" area.

**Comment by ghale** [comment]
There was definitely a change in 7.6 that attempted to more properly handle finalizer tasks and introduces the problem you've found.  In the task graph, mustRunAfter relationships and dependsOn relationships are extremely similar, so it's likely the same problem as discussed in the issue you linked.

The reason it's not an issue with `allTests` is because `allTests` pulls all of the finalized `Test` tasks into the graph.  The problematic code comes into play when we are looking at the finalizer task and searching for un-scheduled dependencies that might also need to be pulled into the graph.  Since `allTests` causes all of the finalizer's dependencies to be scheduled, we never actually descend into the problematic logic - it's only when you request some subset of those tasks that we trigger the problem.  By removing the task dependency between the finalizer and the test tasks, we also avoid it as we just rely on the finalization relationship to ensure that the test tasks run first.  It _does_ mean that running `allTestsJunitHtmlReport` by itself will not cause any of the test tasks to execute, but I don't get the impression that's something that you would need.

One option to think about with respect to test report aggregation might be to use the [test report aggregation plugin](https://docs.gradle.org/current/userguide/test_report_aggregation_plugin.html) introduced in Gradle 7.4.  It's a little bit different than your current configuration in that it uses [test suites](https://docs.gradle.org/current/userguide/jvm_test_suite_plugin.html) and aggregates by test type (which can be any arbitrary string).  You'd have to convert your tests to use test suites, but your use case is pretty much what test suites were designed to address.  It would likely simplify the configuration a good bit, I think, but not without some effort during conversion.
