### ISSUE TITLE
For windows the value for environmental variable is having the wrong slash

### ISSUE THREAD

**Issue by mthavaf** [gradle/gradle#25388]
### Issue type

Wrong or misleading information

### Problem description

Currently it is,

_Instead of adding a specific version of Gradle to your Path, you can add %GRADLE_HOME%/bin to your Path._ 

It should be,

_**Instead of adding a specific version of Gradle to your Path, you can add %GRADLE_HOME%\bin to your Path. **_

### Page with the problem

https://docs.gradle.org/current/userguide/installation.html

**Comment by mthavaf** [comment]
can i raise fix for this?

**Comment by eskatos** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

----

This paragraph is specifically about Windows and using a backslash `\` instead of a slash `/` in path.

The paragraph in question is at: https://docs.gradle.org/current/userguide/installation.html#microsoft_windows_users_2

**Comment by eskatos** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by mthavaf** [comment]
@eskatos raised my first PR :)

**Comment by eskatos** [comment]
Thank you @mthavaf,
https://github.com/gradle/gradle/pull/25443 has been merged.
Your contribution will be in Gradle 8.3.

**Comment by mthavaf** [comment]
Thanks 😄
