### ISSUE TITLE
Instrumentation of multi-release JARs should not fail on newer versions

### ISSUE THREAD

**Issue by mlopatkin** [gradle/gradle#25434]
### Expected Behavior

When the multi-release JAR of the buildscript classpath contains a versioned directory for Java version that the current Gradle doesn't support, Gradle should be able to instrument the root directory and supported versioned directories without failures.

### Current Behavior (optional)

The instrumentation fails when it tries to instrument the classes in the unsupported versioned directory.

### Context

This issue makes it impossible to use newer libraries as part of the buildscript classpath, even if the library itself is backwards-compatible. It defeats the purpose of the MR-JAR.

See also #24390 and #24430.

**Comment by eskatos** [comment]
Thank you for the report.

The issue is in the backlog of the relevant team and is prioritized by them.

**Comment by ljacomet** [comment]
If the fix can be backported to 7.x, that is a good candidate I believe.

**Comment by mmoayyed** [comment]
Related issue. 

### Expected Behavior

Gradle should support multi-release JARs that offer support for JDK 21, such as Spring Framework 6.1 M1.

### Current Behavior (optional)

Building a project with JDK 17 that contains a multi-release JAR offering support for JDK 21 results in:

```
A problem occurred configuring root project 'cas'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/runner/.gradle/caches/jars-9/e68c7e667170499f021871f6fff47fa2/spring-core-6.1.0-M1.jar.
```

This is seen with Gradle 8.2 RC2 and JDK 17. 

### Context

Testing projects that offer JDK-21 support via MR JARs is at the moment not possible given the above error. At a minimum, I suspect Gradle ought to switch to ASM 9.5: https://asm.ow2.io/versions.html

The only viable alternative is to downgrade the specific JAR version that offers JDK 21 support (In this case going from Spring 6.1.x to 6.0.x)  Please note that force-downgrading the version using Gradle's dependency management and resolution is not possible; the crash above happens very early on before Gradle has had a chance to load the relevant rules.
