### ISSUE TITLE
Renderring errors in "Variant selection errors"

### ISSUE THREAD

**Issue by ov7a** [gradle/gradle#25508]
### Issue type

Typo

### Problem description

![image](https://github.com/gradle/gradle/assets/4946730/1ea28d53-4d3f-4f66-890f-91ae883064ec)

### Page with the problem

https://docs.gradle.org/current/userguide/variant_model.html

**Comment by jbartok** [comment]
This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

***

The fix should be done in `variant_model.adoc`, where a missing new-line prevents list rendering.

**Comment by jvandort** [comment]
In addition to the problem noted in the screenshot, which uses `*` for the bullet points, there are several rendering issues in the same document which use `-` for bullet points. They should also be fixed here

**Comment by CYBWEBALI** [comment]
There is no rendering issue.
![image](https://github.com/gradle/gradle/assets/88965204/5276912c-81ab-42a1-a300-0bd2cca60ae7)

I guess it is fixed.

**Comment by ov7a** [comment]
Turns out it was fixed by 
* https://github.com/gradle/gradle/pull/24818

It was merged a long time ago and was released with 8.2.

@AlimurtuzaCodes Sorry for the inconvenience.
