### ISSUE TITLE
ValueSource without result is always recognized as changed by configuration cache

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#25560]
### Expected Behavior

A `ValueSource` without a result should not always be considered as changed.
It can be used to call some external process during configuration phase in CC-compatible way
without the need to invalidate configuration cache.

If it is the intended behavior for a reason, at least the message should be adapted a bit to not report the value source as changed as it did not change.

### Current Behavior

A `ValueSource` without result is always reported as changed.

### Context (optional)

```kotlin
abstract class MyValueSource : ValueSource<Unit, ValueSourceParameters.None> {
    override fun obtain() {
    }
}

providers.of(MyValueSource::class) {}.get()
```

### Steps to Reproduce

Put the context answer in a build script, execute the build twice with configuration cache enabled.
Second time it is reported 
> Calculating task graph as configuration cache cannot be reused because a build logic input of type 'MyValueSource' has changed.

### Gradle version

8.1.1

### Work-around

```kts
abstract class MyValueSource : ValueSource<String, ValueSourceParameters.None> {
    override fun obtain(): String {
        return ""
    }
}
```

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

***

Having a `Provider<Unit>` (which is what builds of `ValueSource<Unit>`) is a bit weird, and we have another feature request(#22833) to run jobs at start of the build even if the cache is used that can solve the original use case of running the external process. However, fixing this corner case wouldn't hurt, and such VS should indeed never invalidate the CC.

>Under the hood is it just void in JVM?

Kotlin's `Unit` is `object`, so it isn't void but its own type, and it has an instance. The culprit is likely the fact that upon deserialization we get a different instance of `Unit`, because Kotlin objects don't have much protection there (like a custom `readResolve`). If that's the case, adding a [custom codec](https://github.com/gradle/gradle/blob/0ac0563498b00bad9e848db9f12037bcd9fe4fdd/subprojects/configuration-cache/src/main/kotlin/org/gradle/configurationcache/serialization/codecs/Codecs.kt#L332) for `Unit` should fix the issue.
