### ISSUE TITLE
when startscripts task disabled, installDist failed of bin folder missing

### ISSUE THREAD

**Issue by ziscloud** [gradle/gradle#2557]
when startscripts task disabled, installDist failed of bin folder is missing

### Expected Behavior
installDist task execute success

### Current Behavior
installDist failed

**Comment by big-guy** [comment]
Could you describe why you want to disable start scripts but still generate an application install?

If you just want a tarball/installed copy of your application without start scripts, you could use the `distribution` plugin instead: https://docs.gradle.org/current/userguide/distribution_plugin.html

**Comment by bmuschko** [comment]
We haven't heard back from you. I am going to close the issue. Feel free to reopen if you want to further discuss.

**Comment by amake** [comment]
I came to make this exact report.

My application is an "application" but we don't want the default scripts as we have our own homegrown scripts that predate our move to Gradle (from Ant).

We like the Application plugin for the `run` target and the way it automatically configures distributions. We like everything about it but the start scripts.

You can see our workaround for the issue described by ticket here:
https://sourceforge.net/p/omegat/svn/10228/tree/trunk/build.gradle#l467

**Comment by amake** [comment]
@bmuschko Can we at least reopen this ticket?

**Comment by bmuschko** [comment]
@amake The task exposes properties for providing custom start scripts. For more information please see https://docs.gradle.org/current/dsl/org.gradle.jvm.application.tasks.CreateStartScripts.html. You do not need to disable the task and build in workarounds.

**Comment by amake** [comment]
@bmuschko The task's properties do not allow us to achieve what we need.

We don't want the scripts put in `bin`, but overriding `outputDir` is not only cumbersome but it doesn't have the desired effect.

While we do have a platform-agnostic distribution that includes both Windows and *nix launch scripts, we also have platform-specific distributions that should only include one or the other. It doesn't appear possible to disable one script or the other.

If we don't want the default content of the scripts, and we don't want them at their default location, and we would have to go through contortions to change these (if it was even possible to get the desired result) then it really makes no sense for us to use the task rather than just disable it.

**Comment by bmuschko** [comment]
> The task's properties do not allow us to achieve what we need.

I think it would have been helpful if you could have stated the actual problem you are trying to solve with additional context around it. The original issue description gives very little information. I also couldn't tell whether you were the reporter of the issue based on your comment "I came to make this exact report". Maybe opening a question on the Gradle forum would work better for discussing your issue.

I read the following use cases from your comments:

1. As a user I want to be able to configure where the application plugin puts the start scripts.
2. As a user I want to be able to configure which OS-specific starts scripts are generated by the application plugin.

RE 1.: We just merged a [pull request](https://github.com/gradle/gradle/pull/2977) that allows you to configure the location.
RE 2.: You can just delete the start script you don't need as you do now in a `doLast` action. Please open an new issue if that doesn't fulfill your use case.

**Comment by amake** [comment]
> The original issue description gives very little information.

I am not the original reporter.

> I also couldn't tell whether you were the reporter of the issue based on your comment "I came to make this exact report".

I'm not sure how that is unclear to you, especially given that I am clearly not @ziscloud.

My use case is:

- As a user I want to be able to include in my application start scripts with custom
  - location
  - content
  - OS-specific variations

> You can just delete the start script you don't need as you do now in a doLast action.

You can't "just" do this, as archive tasks like `distZip` will still include the scripts.

> Please open an new issue if that doesn't fulfill your use case.

I don't know why that's necessary given the perfectly good issue we have right here. But if you insist then I guess I will have to do so.

**Comment by bmuschko** [comment]
> I'm not sure how that is unclear to you, especially given that I am clearly not @ziscloud.

Some people use two different GitHub accounts: one for work, one for private things. Thanks for clarifying but then I don't understand what you meant by "I came to make this exact report.". All good.

> As a user I want to be able to include in my application start scripts with custom...

Location and content is covered by functionality that already exists or the PR that will be released with the next minor version of Gradle.

> You can't "just" do this, as archive tasks like distZip will still include the scripts.

I'd have to have to have a deeper look at this but I am sure we can find _a_ solution. We can go from the new issue you are planning to create. Please also show the code you are currently using to make it work.

> I don't know why that's necessary given the perfectly good issue we have right here.

I don't think the original issue describes the use case and problem at all. That's why we closed it.

**Comment by amake** [comment]
> I don't understand what you meant by "I came to make this exact report."

Fair enough; my apologies. What I meant was "I also had this problem and was going to create a new issue for it, but then I found this ticket which already describes my problem, so instead of creating a new ticket I am commenting on this one".

I will describe the issue more thoroughly in a new ticket.

**Comment by vaibhavtripathi** [comment]
@amake Can you share the link to the new issue?

**Comment by amake** [comment]
@vaibhavtripathi Sorry, I haven't had time yet to write up my use case, so there is no ticket yet.
