### ISSUE TITLE
Redundant configuration usage activation deprecation warning with Kotlin feature variant source set

### ISSUE THREAD

**Issue by jonathan-yan** [gradle/gradle#25609]
### Expected Behavior

A Kotlin project declaring a feature variant using a source set other than "main" should not emit a redundant configuration usage activation deprecation warning on running `./gradlew --warning-mode=all build`.

### Current Behavior

A warning like the following is emitted:
```
> Configure project :
The resolvable usage is already allowed on configuration ':fooSupportRuntimeClasspath'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#redundant_configuration_usage_activation
```

### Steps to Reproduce

Run `./gradlew --warning-mode=all build` on the following project: [issue-example.zip](https://github.com/gradle/gradle/files/11952443/issue-example.zip).

### Gradle version

8.2

**Comment by gavvvr** [comment]
Facing similar issue with Kotlin plugin and a custom test suite starting with `test...`.

Here is the minimal build configuration:

```kotlin
plugins {
    kotlin("jvm") version "1.9.0"
}

testing {
    suites {
        val testInregtation by registering(JvmTestSuite::class) {
        }
    }
}
```

`./gradlew --warning-mode all` emits:

```
The resolvable usage is already allowed on configuration ':lib:testInregtationRuntimeClasspath'. This behavior has been deprecated. This behavior is scheduled to be removed in Gradle 9.0. Remove the call to setCanBeResolved(true), it has no effect. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#redundant_configuration_usage_activation
        at Build_gradle$1$1.execute(build.gradle.kts:7)
        (Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

At the same time if you rename custom test suite from `testInregtation` to `integrationTest`, the warning is gone.

**Comment by tresat** [comment]
As part of evolving Gradle's Configuration API, we soon want to make the allowed usage of a `Configuration` immutable upon creation.

As a small step toward this, Gradle 8.2.x emits deprecation warnings when a configuration has its usage redundantly set to the current value.  For example, if a configuration is already consumable, setting `consumable = true` would warn.  This might be harmless, but is likely a code smell that means work will be necessary soon, prior to when configuration usages become immutable.

We special cased skipping this warning for several common scenarios involving widely used plugins in the code [here](https://github.com/gradle/gradle/blob/b83d45811efcbbc0c1a5f166c0f34800f9982afe/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1840) as a temporary measure to avoid spamming warning messages to users who can't address them.  However we don't and can't cover scenarios involving additional `SourceSets` like this issue reports, since the names can't be known in advance.

This situation has been brought to the attention of the Kotlin team: https://youtrack.jetbrains.com/issue/KT-60879/Deprecation-warning-on-trying-to-configure-Configuration-multiple-times, but is not a high priority.  

We are also currently thinking about other ways to communicate recommendation information other than warnings, and this message in particular is something we might consider changing in near future versions of Gradle.

**Comment by bjhargrave** [comment]
Thanks for the follow up. 

> We are also currently thinking about other ways to communicate recommendation information other than warnings, and this message in particular is something we might consider changing in near future versions of Gradle.

Perhaps Gradle needs a `--pedantic` mode where it nags about such code-smell issues which are not in and of themselves problems.

**Comment by technoir42** [comment]
I'm seeing such warning when following an [example](https://docs.gradle.org/current/userguide/feature_variants.html#ex-declaring-a-feature-variant-using-a-separate-source-set) from the documentation on how to create a feature variant with a source set:

```gradle
sourceSets {
    api { // Warning: The resolvable usage is already allowed on configuration ...
        java {
            srcDir "src/api/kotlin"
        }
    }
}

java {
    registerFeature("api") {
        usingSourceSet(sourceSets.api)
    }
}
```
