### ISSUE TITLE
`TaskExecutionGraph#getAllTasks` does not behave as documented

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#25651]
### Expected Behavior

`TaskExecutionGraph#getAllTasks` behaves as documented

### Current Behavior

`TaskExecutionGraph#getAllTasks` does not behave as documented

JavaDoc says it throws `IllegalStateException` if the graph is not populated yes.
But the method never throws, it just delivers an empty list.
So either the implementation should be changed to throw is not yet populated, or the documentation should be changed to match the behavior.

### Steps to Reproduce

```kts
runCatching {
    println(gradle.taskGraph.allTasks)
}.onFailure { it.printStackTrace() }
val foo by tasks.registering {
    runCatching {
        println(gradle.taskGraph.allTasks)
    }.onFailure { it.printStackTrace() }
    doLast {
        runCatching {
            println(gradle.taskGraph.allTasks)
        }.onFailure { it.printStackTrace() }
    }
}
```

output:
```plain
[]
[]

> Task :foo
[task ':foo']
```

### Gradle version

8.2

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This is a valid documentation issue that we will address.

---

Indeed, it is a nasty behavior. But fixing the documentation would be easier because it might break things for existing builds. 

`taskGraph.allTasks` should be called only in sections where taskGraph is ready. Unfortunately, our current implementation is not expressive enough to enforce that.
