### ISSUE TITLE
Tests for `kotlin-dsl-plugin` and `kotlin-dsl-integ-tests` with embedded runner fails when upgrading AbstractCompile properties

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25686]
When upgrading AbstractCompile.classpath and AbstractCompile.sourceCompatibility/targetCompatibility we noticed that `:kotlin-dsl-plugins` and `:kotlin-dsl-integ-tests` integration tests fail since they have dependency on a Kotlin compiler.

It turns out we don’t instrument `:kotlin-dsl-plugins` and `:kotlin-dsl-integ-tests` integration tests when running with embedded runner: All such integration tests fails with embedded runner, since dependencies are not instrumented: [build scan](https://ge.gradle.org/s/qkuwcjogz7vum/tests/:kotlin-dsl-plugins:embeddedIntegTest/org.gradle.kotlin.dsl.plugins.precompiled.PrecompiledScriptPluginTemplatesTest/Gradle%20scripts%20from%20regular%20source-sets%20are%20compiled%20via%20the%20PrecompiledInitScript%20template?top-execution=1).

We have different options here:
1. Find a way to correctly instrument these tests
2. Or by default run with forked runner

**Comment by big-guy** [comment]
Does this impact TestKit's embedded runner too?

**Comment by eskatos** [comment]
For `:kotlin-dsl-integ-tests`, what happens if you change the dependency declaration for `:kotlin-dsl-plugins` to:
```kotlin
    integTestRuntimeOnly(project(":kotlin-dsl-plugins")) {
        isTransitive = false
        because("Tests require 'future-plugin-versions.properties' on the test classpath")
    }
```
This dependency should not be transitive because it's only required for making that properties file available.
The tests use the plugins from a local repo already.


For tests in `:kotlin-dsl-plugins` it would require to be a tad different because the tests are in the same project. But let's validate that it works in `:kotlin-dsl-integ-tests` first.

**Comment by eskatos** [comment]
The above doesn't work in embedded mode 🤦 😞

**Comment by mlopatkin** [comment]
> This dependency should not be transitive because it's only required for making that properties file available. The tests use the plugins from a local repo already.
> 
> For tests in `:kotlin-dsl-plugins` it would require to be a tad different because the tests are in the same project. But let's validate that it works in `:kotlin-dsl-integ-tests` first.

Thanks for the idea, I made it work for `:kotlin-dsl-integ-tests` by publishing and then consuming only the resource file. 
A quick summary of what doesn't work
* `isTransitive` doesn't work because plugin classes are on the test classpath still and loaded by the test classloader, so they don't see KGP classes (and, most likely, Gradle doesn't even try to load KGP in the first place)
* Using `resources` library elements doesn't work either, because plugin metadata descriptor file leaks into the test classpath and confuses Gradle which tries to load plugin classes from the test classloader because of that.
