### ISSUE TITLE
Backport cgroups fix to 7.6.x

### ISSUE THREAD

**Issue by ghale** [gradle/gradle#25802]
In 8.1, we fixed #17610 with #23944.  If we do a 7.6.3, we should backport this fix.

**Comment by OussamaHaff** [comment]
Hey!
Thank you @ghale and @Thrillpool for the fix 🙏  

We are suffering from the same symptoms mentioned in #17610 on a large Android codebase with Docker setup for CI.
We have been fine-tuning per project/module max heap to avoid JVM crashes on CI, but with a growing codebase it is no more sufficient to cover the symptoms.

Similar case to @CRogers's [comment](https://github.com/gradle/gradle/pull/23944#discussion_r1110040090), we will be thankful if you can backport the fix to Gradle 7.6.x since the upgrade to Gradle 8 will take us couple of months.

**Comment by ljacomet** [comment]
Done through:
* #26584
