### ISSUE TITLE
Cross compiling windows resources to Windows Arm64 is broken

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#25870]
### Expected Behavior

Compiling a window resource for a binary targeting arm64 on an intel host should work.

### Current Behavior

The resource compiler ran is the one for the target, which fails to run. --info shows the resource compiler for arm64 is used. 

### Context (optional)

Add arm64 builds to our project.

### Steps to Reproduce

[GradleResourceIssue.zip](https://github.com/gradle/gradle/files/12137416/GradleResourceIssue.zip)

Attached project is just missing the wrapper for Gradle 8.2, but has everything else required. Make sure the arm64 windows compiler is installed, then run the build task.

### Gradle version

8.2

### Your Environment (optional)

Windows 11 x64 host machine.

**Comment by ov7a** [comment]
Thank you for providing a valid reproducer.

The issue is in the backlog of the relevant team, but the existence of a workaround makes it non-critical, so it might take a while before a fix is made.

***

Thank you for your PR fixing this issue! I'll review it a bit later, but please ensure that tests are passing.

**Comment by eskatos** [comment]
Sorry for the confusion, we picked the wrong canned answer. There is indeed no workaround.
