### ISSUE TITLE
Gradle 8.3-rc-2 fails with com.gradle.enterprise 3.14.1

### ISSUE THREAD

**Issue by natros** [gradle/gradle#25934]
### Expected Behavior

BUILD SUCCESSFUL

### Current Behavior

```
> Task :mylib:lib:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':mylib:lib:test'.
> java.lang.NullPointerException (no error message)
```

### Context (optional)

Gradle fails when executing a test of an included build using com.gradle.enterprise 3.14.1. Works with 3.13.4

### Steps to Reproduce

[ge.zip](https://github.com/gradle/gradle/files/12182767/ge.zip)

- unzip ge.zip
- cd ge/myapp
- ./gradlew :mylib:lib:test
- **FAILS**
- sed 's/3.14.1/3.13.4/g' -i settings.gradle.kts ../mylib/settings.gradle.kts
- ./gradlew :mylib:lib:test
- **BUILD SUCCESSFUL**

### Gradle version

8.3-rc-2

### Your Environment (optional)

MacOS 13.5 intel

$ java --version
openjdk 11.0.20 2023-07-18 LTS
OpenJDK Runtime Environment Zulu11.66+15-CA (build 11.0.20+8-LTS)
OpenJDK 64-Bit Server VM Zulu11.66+15-CA (build 11.0.20+8-LTS, mixed mode)

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by pshevche** [comment]
@natros , this is an issue in interoperability of Gradle and Gradle Enterprise plugin when executing tests in included builds and with configuration cache enabled. We are aware of the problem and are working on a solution. Currently, the only possible workarounds are either to disable configuration cache for test tasks in included builds or to wait with the GE plugin upgrade. Since disabling configuration cache may significantly increase your build times, I'd recommend waiting with the upgrade. We'll notify you once the issue has been resolved. Sorry for inconvenience.
