### ISSUE TITLE
Decide how to upgrade `TextResource` for Property upgrades 

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#25973]
For example [Checkstyle.config](https://github.com/gradle/gradle/blob/f1c1f2ef8ac4241074a807f40b712961dcd792ab/platforms/jvm/code-quality/src/main/groovy/org/gradle/api/plugins/quality/Checkstyle.java#L224) is `TextResource`. Should we handle that as a `@Nested` property or we should do anything special.

**Comment by lptr** [comment]
We need to decide on the future of `TextResource` in general.

**Comment by jvandort** [comment]
Looking at the usages of this class, I think we can replace most of our usages (code quality, wrapper task, groovydoc, reporting) with file properties. We would then deprecate the TextResource-accepting methods.

For 9.0, we can leave `TextResource` around since it solves some use cases like:
- Downloading text files
- Applying remote buildscripts with `apply from: <TextResource>`

As a migration path, we can have `TextResource` implement `Provider<RegularFile>` or perhaps preferably add an `asProvider` method so users can easily transition to the new APIs.

**Comment by bamboo** [comment]
> As a migration path, ... perhaps preferably add an asProvider method so users can easily transition to the new APIs.

Yes, definitely `asProvider()` rather than a `Provider` subtype.

**Comment by asodja** [comment]
I'll mark this as `has:decision`: so basically we agreed to leave `TextResource` properties for 9.0. 

We should also provide  methods to bridge Provider API and TextResource API.

**Comment by mlopatkin** [comment]
> I think we can replace most of our usages (code quality, wrapper task, groovydoc, reporting) with file properties.

I wonder if we should have String properties instead. The users can go from files to strings easily with [fileContents](https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#fileContents(org.gradle.api.provider.Provider)) method, while the other direction is rather cumbersome. The naive implementation is going to have some overhead of parsing the origin and dumping it into some temporary file, but we can optimize it later.

I suspect that the need to accept non-files in a uniform way is what brought TextResource to live in the first place, so those who are using non-file sources now will be stuck with TextResource making it harder for us to remove it later.

**Comment by jvandort** [comment]
This has been marked with `has:decision`. Can we close this now?

**Comment by jvandort** [comment]
Closing, as a decision has been made
