### ISSUE TITLE
8.3-rc-3: The value for property 'languageVersion' is final and cannot be changed any further

### ISSUE THREAD

**Issue by Eng-Fouad** [gradle/gradle#26061]
### Current Behavior

When using Java plugin with `org.graalvm.buildtools.native`:

```
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(20)) // <-- the error occurs here
    }
}

graalvmNative {
    binaries {
        named("main") {
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion.set(JavaLanguageVersion.of(20))
            })
        }
    }
}
```

I got an error:

```
* What went wrong:
The value for property 'languageVersion' is final and cannot be changed any further.
```

### Expected Behavior

It was working fine in 8.2.1.

### Steps to Reproduce

Using Java plugin with "org.graalvm.buildtools.native".

### Gradle version

8.3-rc-3

**Comment by eskatos** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team and is prioritised by them.

----

I made a reproducer here: https://github.com/eskatos/issue-reproducers/tree/main/gradle/issue-26061
Build Scan for the failure: https://scans.gradle.com/s/5q2vmspnm7r2o/failure#1

@Eng-Fouad, please next time provide a valid complete reproducer to make it easier for us to triage issues.

**Comment by eskatos** [comment]
We found that reverting that PR fixes it
* https://github.com/gradle/gradle/pull/25126

**Comment by eskatos** [comment]
Related
* https://github.com/gradle/gradle/issues/25966

**Comment by jvandort** [comment]
As mentioned above, https://github.com/gradle/gradle/pull/25126 is indeed the cause of this behavior change. A brief explanation of the cause can be found in a related issue, [here](https://github.com/gradle/gradle/issues/25841#issuecomment-1648668064). After careful consideration, we have decided to accept this change in behavior for Gradle 8.3. 

The root cause of this change was the removal of an internal mechanism, `beforeLocking`, which provided `Configuration`s a means of lazily calculating attributes. https://github.com/gradle/gradle/pull/25126 removed our internal usage of this API, by migrating to the public, lazy, provider-accepting methods on `AttributeContainer` to configure `Configuration` attributes. In particular, the migrated attributes were `org.gradle.libraryelements` and `org.gradle.jvm.version`.

The specific root cause of this issue is the `org.gradle.jvm.version`, which has its value calculated by realizing the `javaCompile` task, and extracting the target JVM value for the configured test suite. Given the recent changes, querying the value of `org.gradle.jvm.version` will lock in the configured test suite, as is evident by this issue report. (Note, this is not necessarily desired behavior, but changing that is an even larger breaking change).

Digging deeper, the [GraalVM plugin is indeed querying](https://github.com/graalvm/native-build-tools/blob/95ec605ca06b753e9f01fe3087f7267f3106ccb9/native-gradle-plugin/src/main/java/org/graalvm/buildtools/gradle/NativeImagePlugin.java#L716-L731) the values of these the `runtimeClasspath`'s attributes -- at configuration time -- before the user has the opportunity to configure the toolchain. This effectively locks-in the toolchain when the plugin is applied. Note that this issue uncovers an _existing_ problem with the GraalVM plugin, where previously it was silently not copying these two attributes, as they were only present after `beforeLocking` was called. 

We have decided to accept this behavior change, primarily due to the fact that it will need to happen _at some point_ -- and because there are workarounds (see below). `beforeLocking` as it was designed inherently blocks important optimizations that we plan to include in future versions of Gradle, so reverting this change will only be a step backwards. 

In terms of solutions to this issue, the fix must be done by the GraalVM plugin. We recommend the following options, with our most recommended option first. (Note, we will have a detailed description of this issue in the upgrade guide upon the release of 8.3)

1. Declare the attributes for the native configuration _explicitly_, without copying them from `runtimeClasspath`. These attributes are well-defined and can be hard-coded when the configuration is created. 
2. Copy the attributes in the same manner as currently, except use the `attributeProvider` to lazily query the attributes of the source `Configuration` (`runtimeClasspath`). 
3. Wrap the creation of the `Configuration` in an `afterEvaluate`. While this _is_ a solution, we highly discourage it. [Kotlin is experiencing a similar problem](https://github.com/gradle/gradle/issues/25841), as it also copies attributes in a similar fashion. 

As for your own solutions, I see two options currently
1. Wait for GraalVM to fix this issue. Remain on Gradle 8.2 until the fix is released
2. Configure the toolchain in your own custom plugin, which is applied before the GraalVM plugin.

**Comment by melix** [comment]
I agree that solution 2 is the best. However, I would like to express my dissatisfaction about the process. Because while 2 is the best solution, this is again a new API which didn't exist before, which must be used. Using that new API is _not possible_ when you want to support multiple Gradle plugin versions. Of course, you will say "actually it is", but it's extremely cumbersome. I am currently in vacation and will work on a fix when I'm back, but this will involve _reflection_ so that for older version of Gradle this works, while also on newer releases. It would _really_ be better if Gradle didn't break backwards compatibility. This isn't about _binary_ compatibility but _runtime_ one.

**Comment by o-nix** [comment]
For me, upgrading `org.graalvm.buildtools.native` plugin to the latest helped.

**Comment by wisskirchenj** [comment]
> For me, upgrading `org.graalvm.buildtools.native` plugin to the latest helped.

for me it did not unfortunately :-( I am using gradle 8.4 and "org.graalvm.buildtools.native" version "0.9.28"
and I get the error...

**Comment by TWiStErRob** [comment]
Anyone finding this in the future: if you're not using GraalVM, you can also try to change `io.micronaut.application` plugin to `io.micronaut.minimal.application` which removes the transitive GraalVM plugin application.
