### ISSUE TITLE
Sync sets file to 0 bytes when source path is same as destination path

### ISSUE THREAD

**Issue by javaJake** [gradle/gradle#2608]
### Expected Behavior
Gradle skips commands to copy files that have the exact same source and target paths.

### Current Behavior
Gradle attempts to overwrite the target file with itself, which results in a file with 0 bytes (on Windows at least).

### Context
The build I've got configured uses a fairly complex Sync task that pulls from other project's tasks to gather a whole wide array of built files into a single location. It uses a generic task name to find all tasks of a certain type, and because the project the Sync task belongs to also has a task of that name, it gets some source == target copies.

### Steps to Reproduce (for bugs)
Make a Sync task that copies from and into the same location.

### Your Environment
Windows 7, 64-bit, JDK 1.8, Gradle 4.0

**Comment by javaJake** [comment]
Also, this possibly relates to https://github.com/gradle/gradle/issues/1643

**Comment by big-guy** [comment]
I think the behavior of a task like this should be to fail the build.  It seems like a mistake in the configuration of the task. The task would never be up-to-date and the semantics of a task that deletes and copies its outputs as inputs would be undefined.

If you're doing something like this:
```
task sync(type: Sync) { 
    from(allprojects.collect {
        tasks.withType(Sync).matching { it.name == "sync" }
    })
}
```

You could filter by the current task, so it won't rely on the outputs of itself. e.g.,
```
task sync(type: Sync) { thisTask ->
    from(allprojects.collect {
        tasks.withType(Sync).matching { it.name == "sync" && it != thisTask }
    })
}
```

This is a little hokey still. It would be better to model this as publications from the projects instead of reaching into the tasks, but we're working on making that sort of thing better with variant-aware dependency management.

**Comment by javaJake** [comment]
A failure works if you think this is an invalid configuration. As long as Gradle doesn't pretend everything works when it wrote 0 byte files, I'm happy and I'll continue to clean up the build as I find better ways of doing things.

**Comment by mkmaier** [comment]
I ran into the same problem (also on windows) when collecting projects outputs into a directory that was incidentally the output directory of one of those projects. This happens with both Sync and Copy.

I know this is wrong, but it took me a while to hunt this down (blaming imported Ant task at first) and I would have appreciated the fail-fast behaviour gradle usually exhibits when trying something that cannot work.
