### ISSUE TITLE
Gradle doesn't resolve JAR dependencies when *only* POM is in local maven repository

### ISSUE THREAD

**Issue by kutzi** [gradle/gradle#2631]
### Expected Behavior
Gradle should resolve the JAR even if there's already a POM in the local maven repository

### Current Behavior
Gradle doesn't resolve the jar and it's missing from the build artifacts

### Context
A runtime JAR was missing in production which led to issues

### Steps to Reproduce (for bugs)
See https://github.com/kutzi/gradle-pom-jar-bug

### Your Environment
gradle 2.13 or 3.5
Linux CentOS 7

**Comment by blindpirate** [comment]
The reason is that `packaging` is `pom` instead of more reasonable `jar` in `zookeeper`'s [`pom.xml`](https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.pom):

```
...
<groupId>org.apache.zookeeper</groupId>
<artifactId>zookeeper</artifactId>
<packaging>pom</packaging>
<version>3.4.6</version>
...
```
According to [maven lifecycles](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference), for lifecycles with `pom` packaging, there's no goals to generate jars, but it's still possible to generate jars from projects whose `packaging` is `pom`. So it seems that the if block [here](http://maven.apache.org/guides/introduction/introduction-to-the-lifecycle.html#Lifecycle_Reference) is unnecessary. I would submit a PR to do this.

**Comment by kutzi** [comment]
I've put there 'pom' to illustrate the issue when you have a Maven project which needs the POM only - which is a valid use case, but then a Gradle project needing the JAR.
In that case the Gradle project cannot resolve the JAR.

This may seem like a constructed use case to you, but in fact this was something hitting us in our CI environment.

**Comment by blindpirate** [comment]
Okay, I understand. In my investigation, this issue only happens when the dependency artifact's `packaging` is `pom`, for example, [zookeeper 3.4.6](https://repo1.maven.org/maven2/org/apache/zookeeper/zookeeper/3.4.6/zookeeper-3.4.6.pom):

```
...
<groupId>org.apache.zookeeper</groupId>
<artifactId>zookeeper</artifactId>
<packaging>pom</packaging>
<version>3.4.6</version>
...
```

Gradle found its `packaging` is `pom`, and `.m2` is managed by Maven, so if Maven decides not to download `jar` into `.m2`, Gradle will "respect" Maven's decison. For `pom` packaging, the absence of `jar` is totally legal.

**Comment by kutzi** [comment]
I don't know about the specs for dep-mgmt/packaging in Maven to say if it's legit to declare 'pom' but then delivering a jar, anyway. So: yes, it's maybe Zookeeper's 'fault' for declaring the wrong packaging type.
But still from an end users perspective, it would be nice if Gradle could handle this scenario gracefully - i.e. downloading the JAR anyway.

**Comment by bigdaz** [comment]
This issue is a combination of 2 features that Gradle uses to handle Maven POM files:

For a POM with `packaging == 'pom'`, Gradle will check if a jar file exists, and use it if it's found. In this way, a jar artifact is _optional_ for a module with `packaging == 'pom'`.
It looks like `mvn install` is downloading the POM file for `zookeeper` without downloading the jar file. So when Gradle finds a POM file with `packaging == 'pom'` and no associated artifact. So it assumes the optional jar file is missing.

This is an issue with using `mavenLocal` as an artifact repository. Sometimes Maven will leave it in an inconsistent state, and Gradle will suffer from this. 

To fix this problem, I suggest you put `mavenCentral()` ahead of `mavenLocal()` in your repositories list. In case you're wondering, there's very little performance benefit to putting `mavenLocal()` first.
