### ISSUE TITLE
Add SharedLibraryBinary properties for the Export file & the Program Debugging file

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle#2636]
Currently under the VisualCpp toolchain, a SharedLibraryBinary provides 2 files
1. the sharedLibraryFile (.dll)
2. the sharedLibraryLinkFile (.lib)

but when compiling with the debug buidType , some additionnal files are generated 
1. the Exports Library File (.exp)
2. the Program Debugging File (.pdb)
3. the Incremental Link File (.ilk)

and there is no way to reference and set the previous files in a build script. This issue requests to add the export and debugging file to a SharedLibraryBinary 

### Expected Behavior
published setter/getter of those 2 additional files

### Current Behavior
Not relevant

### Context
This extension will be use to move the SharedLibraryBinary related file outside of the standard build directory.

### Steps to Reproduce (for bugs)
Not relevant

### Your Environment
------------------------------------------------------------
Gradle 4.2-20170721201715+0000
------------------------------------------------------------

Build time:   2017-07-21 20:17:15 UTC
Revision:     78cd08b711e683bb56f97767d96c99bea1266e67

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.7.0_80 (Oracle Corporation 24.80-b11)
OS:           Windows 8.1 6.3 amd64

**Comment by bmuschko** [comment]
@lacasseio Would you mind having a look at this request?

**Comment by lacasseio** [comment]
Thanks @zosrothko for this feature request. We are aware some paths aren't exposed through the model. This is on purpose and is likely to change in the near future. The reason is simple, we strive to model what is require for Gradle to function properly and take the right decision. Each developer has various intentions for those files and we can't model them all at this time. We prefer leaving the modeling for these files and options to the users so they can build a strong model around them to suit their needs.

Instead of looking at exposing these paths through the model, let's explore what are you trying to achieve with those files? Is the goal to consume them inside other tools? What would be those tools and for what reason? Is it something that can be achieved through other means? How does it affect the build process?

Questions like those will help us understand the requirements and model something around solving the underlying issue instead of patching it by simply exposing paths. I will close this issue for now, but we can keep the discussion going and split the outcome into more actionable user stories.

**Comment by zosrothko** [comment]
The main reason for getting a way to expose those file is a packagin issue. For example, the NuGet distribution package manager provides 2 kind of package: one with only release files (dll + lib), the other with debug files (dll + pdb +ilk)  (Nuget call the later a "source" packaging"). 

So in the general case -- outside of the NuGet user's case -- the idea is to be able to put the pdb/ilk files in a separate directory that would be distributed separatly to avoid the "overbloat" syndrome when using a distribution package management. For sure, this could be done by filtering the original bin directory where all file type are merged, but it can be an helper to make it right the first time.

This is not critical, but a very nice to have. Moreover, in the case of a native package management build within and with gradle, having a internal model of those filetype  can improve the overall design instead of relying on copy/filter tasks.

**Comment by lacasseio** [comment]
It makes sense @zosrothko. I think those files will be modeled once we model NuGet support.
