### ISSUE TITLE
Capabilities information differs in dependency graph vs artifact collection

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#26377]
### Current Behavior

Variant capabilities are not the same if the:
- 1st one is computed from: `ArtifactCollection.getArtifacts().map { it.variant.capabilities }`
- 2nd one is computed from: `Configuration.incoming.resolutionResult.root.dependencies.map { it.resolvedVariant.capabilities }`

### Expected Behavior

Capabilities are the same.

### Context (optional)

In Android Studio there are 2 phases of dependency graph processing:
1) paths to jars are captured and each one is assigned identity
   1.1) the identity has capabilities as one of the components
2) in the 2nd phase, AGP traverses the dependency graph
  2.1) in doing that it gets the identity of nodes, and capabilities are one of the components
  2.2) identity is used to find the artifact (from the 1st phase)

Because capabilities are different, we cannot match the artifacts between phases 1 and 2.

### Steps to Reproduce

Using the attached project ([variant-capabilities.zip](https://github.com/gradle/gradle/files/12607583/variant-capabilities.zip)
), run `./gradlew depInfo` .

You should see:
```
> Task :app:depInfo
From dependency graph
[capability group='org.mozilla.geckoview', name='mylibrary', version='2.0', capability group='org.mozilla.telemetry', name='glean-native', version='2.0', capability group='com.foo', name='mylibrary', version='2.0']
From artifacts
[capability group='com.foo', name='mylibrary', version='unspecified']
```

i.e. capabilities are different.

### Gradle version

8.3

**Comment by jvandort** [comment]
I've boiled down your reproducer to this minimal reproducer: 
```
    def "test"() {
        settingsFile << "include 'producer'"
        file("producer/build.gradle") << """
            plugins {
                id("java-library")
            }

            group="com.foo"

            configurations {
                api {
                    outgoing {
                        capability("com.foo:producer:2.0")
                        capability("org.bar:not-in-artifact:1.0")
                    }
                }
            }

        """
        buildFile << """
            plugins {
                id("java-library")
            }

            dependencies {
                implementation(project(":producer"))
            }

            task resolve {
                def conf = configurations.runtimeClasspath
                def root = conf.incoming.resolutionResult.root
                def artifactVariants = conf.incoming.artifacts.artifacts.collect { it.variant }
                doLast {
                    println "Graph: " + root.dependencies.resolvedVariant.capabilities
                    println "Artifacts: " + artifactVariants*.capabilities
                }
            }
        """

        expect:
        succeeds("resolve")
    }
```

I can confirm this is broken. 

The root of the problem is in the `[DefaultLocalConfigurationMetadataBuilder](https://github.com/gradle/gradle/blob/fff8377acd771f1d883bb4f898d5e3a2191b0b9c/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/moduleconverter/dependencies/DefaultLocalConfigurationMetadataBuilder.java#L106-L114)`. When we generate the metadata for artifact variants, we fail to collect the capabilities defined on the parent dependency configurations. However, lower in the file, we do walk the configuration hierarchy and aggregate capabilities from parent configurations.

The current workaround for this issue is to declare your capabilities directly on the consumable configuration instead of on the parent dependency configurations.

**Comment by jvandort** [comment]
@bot-gradle test this
