### ISSUE TITLE
Ant native2ascii usage issue in Kotlin

### ISSUE THREAD

**Issue by sergey-morenets** [gradle/gradle#26406]
### Current Behavior

It's not possible to use ant.native2ascii function in Kotlin scripts

### Expected Behavior

This function should be available as it was available in Groovy script

### Steps to Reproduce

We tried to migrate our build scripts from Groovy to Kotlin and our build failed after that.
Here's block of working code in Groovy:

```
      ant.native2ascii(
         src : project.file("src/main/resources/txt"),
         dest : project.file("src/main/resources/ui") 
      )

```
And here's similar code in Kotlin:

```
ant.native2ascii(
         src = project.file("src/main/resources/txt"),
         dest = project.file("src/main/resources/ui") 
)
```

However we received an error with the last example:

`Unresolved reference: native2ascii`

So we investigated this issue and it turned out that **ant** is object of AntBuilderType (https://docs.gradle.org/current/javadoc/org/gradle/api/AntBuilder.html). And it's actually doesn't have native2ascii method. But it's not clear why this code worked in Groovy and how to migrate it to Kotlin. We couldn't find any examples in Gradle documentation.

### Gradle version

8.3

**Comment by sergey-morenets** [comment]
We also tried to use native2ascii functionality directly:

```
import org.apache.tools.ant.taskdefs.optional.Native2Ascii

val task = Native2Ascii()
task.setSrc(project.file("src/main/resources/txt"))
task.setDest(project.file("src/main/resources/ui"))
task.execute()
```

But got an exception:

`> Cannot invoke "org.apache.tools.ant.Project.log(String, int)" because "p" is null`

And it's not possible to assign project property:

`task.setProject(project)`

because of

`^ Type mismatch: inferred type is org.gradle.api.Project! but org.apache.tools.ant.Project! was expected`

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

**Comment by sergey-morenets** [comment]
Hi @jbartok 

Thank you for the quick response.
You can use this project to reproduce: https://github.com/sergey-morenets/gradle-ant
Just run this task: **gradle tasks**.

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

There are no plans to support using `ant` from Kotlin directly.

The problem here is that `AntBuilder` is made for Groovy dynamism and using it from statically compiled languages is awkward. There are two options: 
1. Extract the bit that uses ant into a Groovy script and apply it from Kotlin.
2. Use the Kotlin DSL [GroovyBuilder](https://docs.gradle.org/current/userguide/kotlin_dsl.html#the_kotlin_dsl_groovy_builder)
