### ISSUE TITLE
Gradle batch file does not print JAVA_HOME errors on standard error

### ISSUE THREAD

**Issue by atennapel** [gradle/gradle#26415]
### Current Behavior

The Gradle batch file does not print JAVA_HOME errors on standard error:
`ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.``
This does not align with the shell script, which does do that.

### Expected Behavior

Errors should go the standard error.

### Steps to Reproduce

Start Gradle using the batch file with an invalid JAVA_HOME setting. See that the error is printed to standard out, and not standard error.

### Gradle version

7.6.1

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

**Comment by jknair0** [comment]
Picking this up!
