### ISSUE TITLE
High memory usage for Android builds

### ISSUE THREAD

**Issue by mannol** [gradle/gradle#2646]
### Expected Behavior
It shouldn't use >2GB of ram for a build

### Current Behavior
It uses more than 2GB of ram for a build.

### Context
I have to close long running apps and change my workflow because all ram is eventually eaten

### Steps to Reproduce (for bugs)
Run a build notably: mutlidex build

I propose rewriting gradle in a more appropriate language like C, but that's just me.

**Comment by oehme** [comment]
Since you mention multidex, I take you are building an Android project. We'll need some more information to give you advice:

What Gradle version are you on?
What Android Plugin version do you use?
How big is your project? (A [build scan](scans.gradle.com) would be ideal)

You can build pretty large Android apps with less than 2G of RAM, especially with Android Plugin 3.0, so the information above would help us put your report into context.

For even better diagnosis, you can use the [Gradle Profiler](https://github.com/gradle/gradle-profiler) to create a JFR recording of your build, which would allow us to see exactly where the memory is spent.

**Comment by oehme** [comment]
Closing as there was no further feedback. Feel free to reopen with more information.
