### ISSUE TITLE
Gradle throws ZipException: "zip file is empty", when downloading from Nexus

### ISSUE THREAD

**Issue by rcrlik** [gradle/gradle#26542]
### Current Behavior

After updating from Gradle 8.0.2 to 8.1.1 we noticed that Gradle build started to throw "java.util.zip.ZipException: zip file is empty".

Later we found that the problem was corrupted plugin JAR file (Spring Boot Plugin) in self-hosted Nexus instance - it had 0B filesize. We don't know why it got corrupted but Gradle reported this rather cryptic error message.

Discussion at Gradle Forum: https://discuss.gradle.org/t/zipexception-with-gradle-8-1-1/46610

### Expected Behavior

It would be nice if Gradle message show a filename of the wrong JAR file or a bit more information what happened.
Stacktrace output was not very helpful to non Gradle developers.

### Context (optional)

No gradle task could be executed (help, clean, anything) because project couldn't be configured without a valid plugin file.

We had to pinpoint the file manually, remove it from Nexus, and let it re-fetch. Also we had to download local cache on all affected computers.

### Steps to Reproduce

- Somehow upload plugin JAR file to a repository with 0 bytes filesize.
- Direct Gradle to download plugin from this repo

Sorry for such a lousy description. We still don't know why this happened.

### Gradle version

8.1.1

### Gradle version that used to work

8.0.2

### Your Environment (optional)

OS: Linux, Ubuntu 22.04
Gradle: 8.1.1
Java: 17
DSL used: Kotlin
Repository: Nexus

**Comment by jbartok** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

In order to create a reproducer, you could leverage a file based repository, as documented [here](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring_custom_repository).

**Comment by rcrlik** [comment]
Then feel free to ignore this issue. I don't have resources to host a Nexus instance for this to reproduce the problem :)

I can only attach the stacktrace that I posted to Gradle Forum post. Sorry for inconvenience.

**Comment by jbartok** [comment]
@rcrlik there is absolutely no need to host anything, you can just use a simple folder on your local machine as a Maven repository. Just use a `file` URL to configure your `maven` block, like this:

```kotlin
repositories {
   maven {
       url = uri("file://D:/path/to/local/directory")
   }
}
```

**Comment by rcrlik** [comment]
@jbartok Sorry, it took me a while.

I tried your suggestion with the local directory and I cannot reproduce the original problem. I tried Gradle 8.1.1 and 8.3 and I received a nicer message.

When the POM file is empty, it fails with a message like this:
```
[Fatal Error] annotations-13.0.pom:1:44: Content is not allowed in prolog.
```

And when the JAR file is empty, it also gives me a nicer message:
```
ZipException opening "annotations-13.0.jar": zip END header not found
``` 

So in both cases it printed at least the name of the corrupted file. So debugging is easier.

I am not sure if there is a difference when the file is downloaded from the remote maven repo and if you want to keep this bug ticket for such a corner case. Because we found that are original issue was a bug in Nexus server after all.

Thank you for all previous help!

**Comment by Jacks0N23** [comment]
I faced with the same issue and I believe gradle also should fix this

The problem happens when we try to sync and while it gradle download some new dependencies. But if we're not connected to our company VPN we cannot get access to files cached in our Nexus. But Nexus still respond to request but with HTML content which gradle perceives as a normal response and saves it as, for example, a jar file. So maybe there is any way to handle it on gradle side?
