### ISSUE TITLE
Copying user.dir system property during test fails Jacoco

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#2659]
Given a Gradle multimodule project:
a
...b

if we do the following:
```
tasks.withType(Test) {
    systemProperties = System.properties.findAll{ k, v -> k.startsWith("user.dir")}
}
```
and launch the build from project `a` `./gradlew clean test`, the build fails with the following exception.
```
Exception in thread "main" java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_8ff85ea.PreMain
                at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
                at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
                at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
                at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:304)
                at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
FATAL ERROR in native method: processing of -javaagent failed
```

It appears that the class is present under `b/build/tmp`, but why is Jacoco relying on `user.dir` to find it?

### Steps to reproduce

JaCoCo version: 0.7.9
Operating system: CentOS 7.2.1511.
Tool integration: Gradle

### Expected behaviour
The build works without dependency on `user.dir`.

### Actual behaviour
Build fails as shown above.

**Comment by bmuschko** [comment]
The JaCoCo plugin might need some specific system property to run properly. In your assignment you are replacing all system properties. 

You should simply add them instead with `+=`. 

```
tasks.withType(Test) {
    systemProperties += System.properties.findAll{ k, v -> k.startsWith("user.dir")}
}
```

**Comment by asarkar** [comment]
@bmuschko 

> JaCoCo plugin might need some specific system property to run properly

I know and I even know which system property they are depending on: `user.dir`. The ticket clearly mentions that. Question is, **why**? Depending on a system property that they have no control on is fragile and causes unexpected failures.

> You should simply add them

No, I don't want to add one property at a time, it's simply not maintainable. The example you showed adding `user.dir` is exactly the opposite of what I need, because adding `user.dir` breaks Jacoco.

**Comment by bmuschko** [comment]
> Question is, why? Depending on a system property that they have no control on is fragile and causes unexpected failures.

Not quite sure why they need it. I suggest you ask on the JaCoCo mailing list for clarity.

> No, I don't want to add one property at a time, it's simply not maintainable.

That's fine. You can also replace the existing system property via `tasks.withType(Test).systemProperties['user.dir'] = ...`.

To better understand the use case you are trying to solve - why do you need to set a custom `user.dir`?

**Comment by asarkar** [comment]
@bmuschko 

> I suggest you ask on the JaCoCo mailing list

I did and they asked me to ask on the Gradle repo. 
> The JaCoCo grade plugin is maintained by the grade project. Please report the issue with them.

https://github.com/jacoco/jacoco/issues/574

> why do you need to set a custom `user.dir`

I don't. I just want to pass some runtime properties to the project, and since I don't know the full list beforehand, I copy all system properties. `user.dir` is the property that, if copied, creates problems as described in this ticket.

**Comment by bmuschko** [comment]
The JaCoCo plugin doesn't explicitly set the system property `user.dir`. I tried to reproduce the issue you are seeing but couldn't. Please provide a simplistic sample project on GitHub.

**Comment by asarkar** [comment]
I couldn't reproduce the problem in a standalone project using Jacoco 0.7.9 and Gradle 4.1. I'll double check with the real project, and report back.

**Comment by bmuschko** [comment]
Any additional feedback here?

**Comment by asarkar** [comment]
I still can't reproduce the issue. I'll report back next week, or close this ticket.

**Comment by asarkar** [comment]
[jacoco.zip](https://github.com/gradle/gradle/files/1257924/jacoco.zip)

@bmbaisch This issue can be reproduced using the attached project, and by running either of the following commands:

```
./gradlew --no-daemon --info clean test -p sub-module
./gradlew --no-daemon --info clean sub-module:test
```

**Comment by Godin** [comment]
`user.dir` property denotes working directory.
While JaCoCo library itself doesn't use it as was said by me in jacoco/jacoco#574,
JVM uses it for conversion of relative paths into absolute.

Gradle JaCoCo Plugin places JaCoCo agent into subdirectory of `sub-module/build`.
And as can be seen in output of `./gradlew-daemon --info clean sub-module:test` it adds following JVM argument to use this agent:
```
-javaagent:build/.../acocoagent.jar=destfile=build/.../test.exec
```
notice that both paths are relative (to agent and to file that agent will use for output).
You do a copy from the Gradle JVM, so that value of `user.dir` is working directory of Gradle JVM, but not the `sub-module` directory. And so agent can't be found by relative path. And that's why
```
./gradlew --no-daemon --info clean test -p sub-module
./gradlew --no-daemon --info clean sub-module:test
```
doesn't work, while
```
cd sub-module
../gradlew --no-daemon clean test
```
works.

**Comment by asarkar** [comment]
@Godin Thanks for the explanation, that's what I came to understand as well. If you see my original question, why is Jacoco relying on `user.dir` (indirectly, by using relative path)? Can't Jacoco use the absolute path of the project?

**Comment by Godin** [comment]
@asarkar once again: JaCoCo by itself does not rely on `user.dir` and does not use relative path.

Relative path is set by **Gradle JaCoCo Plugin**. JaCoCo and Gradle JaCoCo Plugin are two different projects maintained by different people. Please don't mix. I (being one of developers of first one - JaCoCo, but not second one - Gradle JaCoCo Plugin) tried to explain only where root cause of your problem comes from. And would prefer to leave question about usage of absolute path in Gradle JaCoCo Plugin to developers of this plugin, because they should know it (and its integration, as well as Gradle itself) definitely better than me.

FWIW not sure that you will not run into other problems (not connected at all with JaCoCo, e.g. with other Gradle plugins, or even not connected with Gradle at all) by setting `user.dir` into **Gradle working directory** (i.e. where it was started) that generally speaking can be far away from your project (see `gradle --project-dir`).

Hope this helps.

**Comment by asarkar** [comment]
@Godin
When I say "Jacoco" in an issue in the Gradle repo, I mean "Gradle Jacoco plugin". As had been mentioned, I started with a ticket in the Jacoco repo and they asked me to take up the issue with Gradle guys. So I did. I appreciate you taking the time to look into this issue but let's not turn this into "not my problem". Unless otherwise specified, we are solely discussing Gradle Jacoco plugin, and if we agree on that, I don't think there's any need to repeat the long name every time just to avoid a technicality.

**Comment by Godin** [comment]
@asarkar your ambiguous (to my taste) reference was completely unclear to me as for external reader accidentally coming to this thread (maybe for others too) till your last message. Especially that at the very beginning of thread there still were doubts about location of root cause. Maybe here better to use short and less ambiguous in this context word "plugin", instead of official name of another project.

> they asked me to take up the issue with Gradle guys

I do remember, because it was me, who asked you to do so.

> let's not turn this into "not my problem"

No one tries to turn it like that. Due to unresolved ambiguity of name at this time: still was assuming that you continue requesting changes from us - developers of JaCoCo library, while we are just external contributors here, like you are.

FWIW Usage of absolute path might lead to more frequent occurrences of issue #949 , which is quite common and well-known problem on Windows and maybe this explains why as of today relative path is used. Also there is opened PR #2485 that seems to be related to the issue discussed here. And seems that it tries to workaround problem #949 by allowing optional (configurable) use of absolute path, which is IMO not very convenient and not very intuitive.

Speaking more about #949 and that's where, again, opinion of Gradle developers is quite important:
* Java 9 will allow to specify "argument files containing options" for `java`
* prior to Java 8 there is [`JAVA_TOOL_OPTIONS`]( https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html) that also has limits, but most likely bigger
* maybe agent should not be extracted into directory of project, but into another location with shorter path, e.g. JaCoCo Maven Plugin directly uses Agent JAR that is stored in Maven local repository and this works well over many years
* maybe in fact this issue is more broader as it can happen not only with JaCoCo agent
* or maybe it should not be considered as blocking for this one

**Comment by bmuschko** [comment]
@asarkar Thanks for providing the code example. I can reproduce the issue. Question still stands from my end: Why exactly are you setting a different user directory for the test JVM? Just trying to understand the use case as the provided code example doesn't actually use the system property.

@Godin Thanks for the good discussion and additional pointers.

> FWIW Usage of absolute path might lead to more frequent occurrences of issue #949 , which is quite common and well-known problem on Windows and maybe this explains why as of today relative path is used.

I looked through the history of the file `JacocoTaskExtension` and couldn't really find an indication why a relative path is used. You might be right here that a shorter path avoids has a higher likelihood of avoiding potential path length issues on Windows.

> maybe agent should not be extracted into directory of project, but into another location with shorter path, e.g. JaCoCo Maven Plugin directly uses Agent JAR that is stored in Maven local repository and this works well over many years

That's not a bad idea though the path of the Gradle cache can be quite long as well. Maybe we just need to expose a configurable option to the end user that indicates the storage path. Then the user can change it if it happens to be too long.

**Comment by big-guy** [comment]
> That's not a bad idea though the path of the Gradle cache can be quite long as well. Maybe we just need to expose a configurable option to the end user that indicates the storage path. Then the user can change it if it happens to be too long.

This is very similar to what we do for Zinc compilation (we need to generate a jar file before we can do any Scala compilation).  We should/could do the same for JaCoCo.  Maybe even using an `ArtifactTransform`?

👎  on any configuration.  This should just work.

**Comment by asarkar** [comment]
@bmuschko 
>  Why exactly are you setting a different user directory

I believe I've answered this question before, but perhaps didn't do a good job at it. The reason is fairly simple - we use Spring framework that allows any configuration to be overridden from command line. Since we don't know what properties the user may choose to override, we copy all system properties to Gradle `bootRun` job. AFAIK, most frameworks allow the same type of configuration override.

**Comment by bmuschko** [comment]
> This is very similar to what we do for Zinc compilation (we need to generate a jar file before we can do any Scala compilation).

I guess in this case we don't actually need to modify the JAR file. We just have to put it into a know location.

> This should just work.

I believe there might always be the potential for a too long path on Windows.

**Comment by asarkar** [comment]
Windows is not a real OS. Breaking a tool so that it works on Windows is like stop producing Ferrari engines because they don't work for Hondas.
I like the suggestion of putting the agent in `~/.jacoco` or something along that lines. The home directory is well-defined for all OS, and the path to it is unlikely to be very long, no matter the username.

**Comment by bmuschko** [comment]
> Windows is not a real OS. Breaking a tool so that it works on Windows is like stop producing Ferrari engines because they don't work for Hondas.

Unfortunately, we cannot change the OS landscape in organizations. To-date Gradle has more users on Windows than on any other OS.

**Comment by big-guy** [comment]
I think this warning from the JVM applies:
https://docs.oracle.com/javase/tutorial/essential/environment/sysprop.html

> Warning: Changing system properties is potentially dangerous and should be done with discretion. Many system properties are not reread after start-up and are there for informational purposes. Changing some properties may have unexpected side-effects.

I think this is one of the "unexpected side effects" where the current working directory (`user.dir`) is not the same as the process's working directory and that breaks things.

**Comment by skjolber** [comment]
So, have anyone come up with a solution yet? Because I can't make this work with the systemProperties workaround, on Gradle 6.0.1. 

@bmuschko if @Godin is right about the classpath, is not this a trivial fix?

**Comment by asarkar** [comment]
@wolfs I see that several tickets are closed today as “not planned”. I understand that some tickets can’t be worked on immediately due to lack of resources, but closing tickets that report perfectly valid issues as “not planned”, whatever that means, seems flippant and heavy handed. Care to elaborate?

**Comment by ljacomet** [comment]
Hi @asarkar 

The recent activity is mostly us making sure that all issues _already closed_ by the stale bot are properly marked as "not planned" instead of looking like regular completed issues.
