### ISSUE TITLE
What counts as a reproducer(your not clear you just saying it does not count or you are lying)

### ISSUE THREAD

**Issue by Danjhop4** [gradle/gradle#26636]
### Issue type

Wrong or misleading information

### Problem description

Title says all

### Page with the problem

N/a

**Comment by Danjhop4** [comment]
I give you a reproduction capability template you did not eccept it

**Comment by big-guy** [comment]
Hi @Danjhop4,

We've repeatedly asked you to abide by the [code of conduct](https://gradle.org/conduct/), but you still make derogatory comments, imply we're lying or intentionally trying to not help you. You seem to understand this behavior isn't acceptable because you expect to be banned for it.

I'm sorry that you are having trouble using Gradle. I don't know what's the cause of your problem, but we're not going to be able to help you. 

Since you repeatedly open new issues that we have to triage and close, I'm blocking you.
