### ISSUE TITLE
Support optional Gradle dependency on Kotlin

### ISSUE THREAD

**Issue by rbento** [gradle/gradle#26641]
### Expected Behavior

**Goal**

- Ability to use Gradle with plain old Java / Groovy.

**Request**

- Ability to use Gradle with only Java and Groovy.
- Ability to disable/remove each and every trace of Gradle dependency on Kotlin.

### Current Behavior (optional)

- Gradle depends on Kotlin even when Kotlin DSL is not used.

### Context

1. I am interested in continuing using and recommending Gradle but have absolutely no interest in installing Kotlin on any target system.

2. Currently it is mandatory to have Kotlin installed to run Gradle, which could be made optional only for people interested in using Kotlin DSL.

3. Usage or dependency on Kotlin can boil down to a matter of preference. Why force it on Gradle users?

**Comment by ov7a** [comment]
Thank you for your interest in Gradle!

There’s no plan to change it. This issue will be closed.

***

1. You don't need to install Kotlin in order to run Gradle. It is shipped with it as a dependency.
2. Same thing here. 
3. Kotlin is a DSL of choice for us. Gradle itself uses Kotlin stdlib internally. It's hard to remove it.
