### ISSUE TITLE
Option to disable unwanted toolchain warnings

### ISSUE THREAD

**Issue by pgalbraith** [gradle/gradle#26706]
### Current Behavior

On a gradle 8.4 composite build running on Ubuntu there is an unreasonable amount of noise generated because of toolchain discovery trying to warn about a situation that I don't need to be warned about.  We really need an option to turn this noise off and/or only provide it when toolchain debugging is requested.  This is the same warning that used to be an error and was fixed with https://github.com/gradle/gradle/issues/22921 but unfortunately it was still left as a very noisy warning.

![2023-10-11_13-16](https://github.com/gradle/gradle/assets/19995454/cb8af9de-1b1b-427d-bd08-300d2e69c36c)

### Desired Behavior

Make this warning only appear when toolchain debugging is requested

### Context

Run a gradle 8.4 composite build (with many sub-builds) on Ubuntu 22.04 that has stock jdk 11 and jdk 17 apt packages installed.

**Comment by weickmanna** [comment]
Jup, this is unfortunate. It's really unsettling people that are expected to see nothing that even remotely looks like a warning or error message in our builds. And although it is not an error, it is not prefixed with "warning:", so it's not immediately clear that it is just a warning. I belive there should never be a message for a situation that isn't really a problem. Otherwise, there might be tons of other situations where you might also print out warning messages but it's just noise.

**Comment by octylFractal** [comment]
> Also, is that really such a common installation path in Linux systems? Ubuntu is very wide-spread, and I installed JDKs via apt, and I don't have these paths.

Yes, Arch Linux uses this path: see Package Contents of https://archlinux.org/packages/extra/x86_64/jdk-openjdk/
