### ISSUE TITLE
Confusing deprecation message for dependsOnTaskDidNoWork()

### ISSUE THREAD

**Issue by eljobe** [gradle/gradle#2671]
### Expected Behavior
I would like the following deprecation message to explain why the method is being removed. Is there a better way to accomplish what `dependsOnTaskDidNoWork()` used to do? Or, was it just dangerous, and removed to keep people from making common mistakes.

### Current Behavior
I run Gradle and get this message:
```
The Task.dependsOnTaskDidWork() method has been deprecated and is scheduled to be removed in Gradle 5.0.
```

### Context
I use the `org.ajoberstar.github-pages` plugin to publish a website to github pages. But, with Gradle 4.1, I am seeing the deprecation message above. I assume that this method must be used in the `github-pages` plugin. But, I'm not sure what to suggest to the plugin author to use instead of this method.

 * Build scan URL:  https://gradle.com/s/uodco7hnc4jvs

**Comment by wolfs** [comment]
It seems to come from this line: https://github.com/ajoberstar/gradle-git/blob/v1.5.0/src/main/groovy/org/ajoberstar/gradle/git/ghpages/GithubPagesPlugin.groovy#L90
The main reason to deprecate the method was:
> `dependsOnTaskDidWork()` doesn't have any real meaning. The task should describe its inputs, and the other tasks their outputs, and we should connect the tasks together via these.

The method is mostly used in `onlyIf`, which by itself should better be handled by up to date checks in general. In the version of the plugin you are using using the `onlyIf` call is somewhat pointless, since the task itself checks if the repo is clean and then does nothing.
A [newer version of the plugin](https://github.com/ajoberstar/gradle-git-publish/blob/master/src/main/groovy/org/ajoberstar/gradle/git/publish/GitPublishPlugin.groovy#L160) actually has a different task for making the commit itself and then the publish task for pushing the changes. The actual task seems to want to publish only if a specific task did some work (created a commit). If would be better to actually have the commit id published as an (optional) output of the commit task. Then the publish task could depend on the commit id and specifically push that commit.
@eljobe Does now everything make more sense?

**Comment by eljobe** [comment]
It does make sense, @wolfs. I'll attempt to make the deprecation warning match this explanation.
