### ISSUE TITLE
Echoing option for the Exec task

### ISSUE THREAD

**Issue by eaaltonen** [gradle/gradle#2674]
### Expected Behavior
Tasks of type `Exec` would have a configuration option that makes the build always print out the command to be executed just before executing it.

### Current Behavior
Command line printing is available with the `--info` option, but this:
* must be set outside the build script.
* applies to all commands executed by the build script.

### Context
In my case, I am invoking a compiler via a *Command line interface*. The compiler takes many options, and takes quite a while to complete. The echo would be useful in two ways:
* tell the developer what is happening
* allow to reproduce the compilation by hand, if necessary

This use case was previously discussed in the [gradle-dev group](https://groups.google.com/forum/#!topic/gradle-dev/jlfxQEvt-p8).

**Comment by eaaltonen** [comment]
I made a small toy repository to explore the proposed API addition.

My personal favorite for the of the option would be `printCmd`
https://github.com/eaaltonen/gradle-exec-task/blob/master/build.gradle
, which would accept any "truthy" value.

The feature could also provide quoting or escaping for whitespace, something I was too lazy to make for the toy repository.
https://github.com/eaaltonen/gradle-exec-task/blob/master/buildSrc/src/main/groovy/PrintExec.groovy

**Comment by eaaltonen** [comment]
### Concerning Bash set trace

Bash has long had a tracing feature enabled with `set -x`. It would be possible to display a consistent trace level co-operatively with bash if the `gradle` and `gradlew` executables pass the `PS4` (trace level) variable on to the java process.

**Comment by oehme** [comment]
There were good proposals on how to solve this on the dev list. One is to write a small task and plugin wrapping your tool (which is probably a good idea anyway, because it makes your build scripts more readable). Inside that task you can then log whatever you'd like at any level.

Alternatively, you can add your vote to #1010 so you could get the `--info` logging for just that one task.

I'm closing this request, as it is very unlikely we'd add another option to `Exec` with these good alternatives.
