### ISSUE TITLE
Make useful services available to workers in Worker API

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#2678]
This is a feature request to make the Gradle Project and Logger objects available to worker threads in the Worker API. The current restriction that all worker parameters be serializable makes it impossible to pass the project or logger to a worker thread. At best this leads to clumsy code that has to effectively remove Gradle constructs before calling a worker (e.g. converting a ZipTree to a Set<File>, switching from project.copy to a less capable mechanism, etc). At worst, the inability to access the project or logger is a blocker for adopting the Worker API.

**Comment by oehme** [comment]
The Project will not be available, as that would defeat the parallel safety of the worker API. 

Services like the logger and file operations on the other hand make perfect sense and should be made available through service injection.

**Comment by baron1405** [comment]
Thanks @oehme for the quick reply. I understand that exposing the Project would be problematic. One aspect of the Project that would be useful to expose besides file operations would be the ability to call ant tasks (e.g. I have a use case calling ant.get).

**Comment by oehme** [comment]
Yes, a stateless service that allows you to call Ant makes sense as well.

**Comment by baron1405** [comment]
Any ETA on this feature?

**Comment by baron1405** [comment]
Ping

**Comment by oehme** [comment]
No ETA I can commit to, we'll update this issue as soon as we have a milestone for it.

**Comment by JamesXNelson** [comment]
If nobody on the team has bandwidth to do something like this, it seems like something worth a community contribution (I would be happy to sign up to do it).  Main thing would be for someone on the team to define the requirements and maybe a few hints about where to do work.

**Comment by orangy** [comment]
I'd like to have it as well. I need to redirect worker's stdout to `logger.info` calls.

**Comment by mkobit** [comment]
I'd find something similar to `project.exec` and `project.javaexec` useful.

**Comment by JamesXNelson** [comment]
A thought I had about this... what about a read-only ProjectView, which just lets you read specific things, like path, logger, objects, providers, etc. that you might want to pass around without specifically pulling all of them out into (worst case) 10+ argument method calls?

This way, you can pass around "project-scoped bag of utilities", without actually passing around the mutable whole-world Project.  I'd be happy to do something of the sort if _helpwanted_ .

**Comment by JamesXNelson** [comment]
I suppose just such a thing could be created in a plugin or set of tools, which is what I'll do if it's not desirable to have in gradle itself.  It would be slightly easier if `Project implements ProjectView`, though likely better to do with an immutable class that has a `constructor(Project p)`.

**Comment by mkobit** [comment]
@big-guy it looks like this is on the queue for 5.5 RC1 - which parts from this ticket are planned to be included? Is there any way I can help with this?

**Comment by vanniktech** [comment]
In https://github.com/vanniktech/gradle-code-quality-tools-plugin/pull/191 I've wanted to leverage the Worker API. Currently, I'm using `project.javaexec` to run a java binary. Unfortunately, I have to maintain several incompatible versions of the dependency that I want to execute. Hence using the `classpath` approach of the worker API does not really work well and the string reflection approach suits my needs better since depending on the version I can pass different arguments as well as different main classes. (Detekt integration is slightly easier than ktlint where I have the problem with different main classes)

**Comment by big-guy** [comment]
this will be in 6.0

**Comment by vanniktech** [comment]
Can you reference some kind of documentation / sample?

**Comment by Vampire** [comment]
@vanniktech https://github.com/gradle/gradle/blob/master/subprojects/workers/src/integTest/groovy/org/gradle/workers/internal/WorkerExecutorServicesIntegrationTest.groovy

@big-guy from a quick look at the PR for this (if it is the only one),
is it correct, that you can neither access the `AntBuilder`, nor the `Logger`?
Both were mentioned here as being quite necessary and sensible.

**Comment by ChristianCiach** [comment]
I am trying to migrate this plugin to Gradle 6.0: https://github.com/tschulte/gradle-jnlp-plugin . Unfortunately, this plugin is incompatible with Gradle 6.0.

The plugin uses Ant to sign the jar files. As far as I know, there is no way to sign jar files by using Gradle without calling Ant.

I just found out that there is no way to call Ant from within a worker thread, so I am stuck now. We still need to deploy our application using Webstart, so this plugin is vital for us. Because of this, we are now stuck with Gradle 5.6, because the plugin doesn't work with Gradle 6.0 (this is excusable) and there is no way to make it work with Gradle 6.0 because of missing APIs.

**Comment by Vampire** [comment]
@ChristianCiach the Gradle `AntBuilder` is a wrapper around the Groovy `AntBuilder`, well actually a sub-class. Just use the Groovy `AntBuilder` directly, that works fine for the most part. Alternatively you could call the `JarSigner` in-process directly, but as it has no stable public API, it could break.

I used to use the JarSigner classes directly, as it was the only way to have parallel processing that does not kill the machine running the build, as the Ant task basically is just a wrapper around the standalone `jarsigner` tool. The API once actually broke for me between too Java versions.

Another alternative is, to do as the Ant task does and simply call the standalone tool use `javaexec`.

And finally you could try to use no isolation and have some static reference to the Gradle `AntBuilder` that you use in the workers, but I don't think that is a good idea.

**Comment by ChristianCiach** [comment]
@Vampire Thank you for your suggestions!

I already got it to work by using `ExecOperations.exec(..)` to call the jarsigner executable directly, but your suggestions seem to be more elegant. 

I didn't know that there are classes inside the JDK to do the jar signing. I will check them out. 

Using the AntBuilder is probably the easiest way to make the JNLP-plugin compatible while retaining all of its features. I will try that!

**Comment by Vampire** [comment]
All has its pros and cons.
The standalone tools are mostly just thin starters that invoke the respective classes via JNI, be it `java`, `javac` or `jarsigner`. The classes are the one that used to be in `tools.jar` in the JDK, but missing in the JRE. Now they are simply classes in modules that are not on the module path by default.

Using the Groovy `AntBuilder` can also have its own problems. I used it to call a 3rd party task and always created a new instance. That made me run out of meta space add too often the classes were loaded. But using one static was also no solution, because the task is not thread safe and also static might be conflicting easily with daemon usage and so on. 

I ended up having a custom registry with semaphores. If a worker needs the builder, it checks the existing semaphores, whether one builder is free and if not, creates a new one. This way I had as many builders as workers, but not more, even if new worker threads were made. Basically a custom `AntBuilder` pool.

But with a thread safe task, or a standard task that does not need to load additional classes and so on, it might again be completely different.
