### ISSUE TITLE
Expand list of file extensions used by cpp-library public headers

### ISSUE THREAD

**Issue by matthewvon** [gradle/gradle#26828]
### Issue type

Polishing

### Problem description

Requesting that the following change be made to DefaultCppLibrary.java.  I now have two third party libraries that utilize public header file extensions not recognized by gradle.  vorpal_wabbit uses ".hxx".  AWS S3 uses ".inl".

I note that gradle's "default.vcxproj.filters" already has a comprehensive list.  I have copied all of its missing file extensions into this fix.

I am unclear how to make a PR, against this repository.  Will create one if/when I figure it out.

<pre>
diff --git a/subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppLibrary.java b/subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppLibrary.java
index 2dac1076db1..b5504882969 100644
--- a/subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppLibrary.java
+++ b/subprojects/language-native/src/main/java/org/gradle/language/cpp/internal/DefaultCppLibrary.java
@@ -149,6 +149,11 @@ public FileTree getPublicHeaderFiles() {
         PatternSet patterns = new PatternSet();
         patterns.include("**/*.h");
         patterns.include("**/*.hpp");
+        patterns.include("**/*.hxx");
+        patterns.include("**/*.hm");
+        patterns.include("**/*.inl");
+        patterns.include("**/*.inc");
+        patterns.include("**/*.xsd");
         return publicHeadersWithConvention.getAsFileTree().matching(patterns);
     }
</pre>

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

***

One of the problems here is that C/C++ headers do not have a "fixed" list of headers or source file extensions. 
The proper fix should be to make this list configurable. However, we need to be at least consistent there (with this [file](https://github.com/gradle/gradle/blob/1295becbd5d1c33eb88d9baf8153a8073a7c4ee0/platforms/ide/ide-native/src/main/resources/org/gradle/ide/visualstudio/tasks/internal/default.vcxproj.filters#L17-L16)), and your PR fixes that. Thanks for providing a fix for that.
