### ISSUE TITLE
Virtual Threads Support

### ISSUE THREAD

**Issue by ganadist** [gradle/gradle#26927]
### Expected Behavior

Gradle should support `Java Virtual Threads` if it is performed on Java 21 or higher version.

### Current Behavior (optional)

N/A

### Context

Since Java 21, it supports [Virtual Threads](https://docs.oracle.com/en/java/javase/21/core/virtual-threads.html) as stable feature.
And I'm guessing this feature will provide better build performance for large projects if gradle is using it.
Because it requires smaller memory footprint than Platform Threads.

Related issues
* #25574
* #25488

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Support for virtual threads would mean having version specific code around thread management until Java 21 is the minimum supported version for running Gradle.

That decision has a cost, the team responsible for those areas will have to make a decision.

**Comment by jvandort** [comment]
While we could potentially enable virtual threads selectively if the user runs Gradle on java 21, this would be very situation-dependent. I can imagine features like filesystem snapshotting and downloading dependencies could potentially leverage virtual threads, but we already have systems in place to make these features performant. 

Since this feature request is very general, I do not find it actionable. The linked issue, #25488, is actually actionable and calls out a specific feature that could be improved with virtual threads. For that reason, I am closing this issue.
