### ISSUE TITLE
Ability to use createArtifactResolutionQuery with configuration cache? 

### ISSUE THREAD

**Issue by wojtek-kalicinski** [gradle/gradle#26999]
### Expected Behavior

I might be wrong on this, but I can't find a way to be able to lazily query artifacts in my task in a cache configuration compliant way.

I want to do exactly [this](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/snippets/dependencyManagement/workingWithDependencies-accessMetadataArtifact/kotlin/build.gradle.kts), i.e. access the POMs of my dependencies.

I thought something similar to how we can use `getRootComponent` to get a lazy `Provider<ResolvedComponentResult>` would be available, but I can't find a way.

### Current Behavior (optional)

In the example linked above `Project` is implicitly accessed from `doLast` (by calling `dependencies.createArtifactResolutionQuery`, so as I understand this will break conf cache.

### Context

I'm trying to help make a plugin that gathers licences from POM files compatible with conf cache and use well supported APIs, but I'm at a loss as to how to make it work right now.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team, but this area of Gradle is currently not in focus. It might take a while before it gets implemented.
***
You are right, there is currently no configuration cache compatible way.
Note that the snippet is no longer referenced from the documentation and thus obsolete. Because the used API will disappear at some point and will never be CC compatible.

**Comment by big-guy** [comment]
We intend to deprecate and remove this feature eventually. 

We want to expose POMs in a way that would be CC compatible here: #25589
