### ISSUE TITLE
Configurable Keystore for Gradle Configuration Cache

### ISSUE THREAD

**Issue by kaeawc** [gradle/gradle#27055]
### Expected Behavior

The Gradle Configuration Cache should change the behavior of [EncryptionService.kt](https://github.com/gradle/gradle/blob/master/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/EncryptionService.kt#L257) to either:
1. Use an environment variable, perhaps `GRADLE_CONFIGURATION_CACHE_KEYSTORE_PASSWORD`, so that we can inject the keystore password as a build secret on CI. This approach is probably easier, but there might be security concerns about caching a keystore that can eventually be cracked. I took a stab at it [here](https://github.com/gradle/gradle/compare/master...kaeawc:kaeawc/configuration-cache-password-env-var?expand=1).
2. Use environment variables to deterministically generate the keystore based on injected build secrets on CI. It appears that the `.lock` file in the `cc-keystore` directory is required for reading the keystore and I don't understand how that works, would need a little help on this approach.

### Current Behavior

The Gradle Configuration Cache currently uses [EncryptionService.kt](https://github.com/gradle/gradle/blob/master/platforms/core-configuration/configuration-cache/src/main/kotlin/org/gradle/configurationcache/EncryptionService.kt#L257) with a hard-coded password `cc`.

### Context

The encryption was added due to [the security vulnerability of exposing build secrets via caching the configuration cache](https://github.com/gradle/gradle-build-action/security/advisories/GHSA-h3qr-39j9-4r5v), but I've been able to see very significant performance wins in both [Hinge's large Android project](https://speakerdeck.com/kaeawc/from-laptop-builds-to-advanced-ci?slide=251) as well as extremely [small starter projects](https://github.com/kaeawc/android-ci/actions/runs/6846043784/job/18612122017) on CI, so I believe its in the interest of Gradle and the community to support a [method to share the configuration cache between machines](https://github.com/gradle/gradle/issues/13510) that doesn't expose build secrets.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue will be closed as a duplicate of

* #13510

Please add your use case and 👍 to that issue.

***

While the original issue predates the encryption feature making the cache sharable will need to account for the encryption feature.

**Comment by bigdaz** [comment]
@cobexer I agree that having a configurable keystore is necessary for making the configuration-cache shareable across different machines, the scope of this issue is _much_ smaller and I don't think it's helpful to merge these 2 issues.

The driver for this issue is to make the configuration cache safe to store and reuse in GitHub Actions.  This is a very narrow case of "reuse across machines", since the environment is completely controlled, the machines involved are near identical, and _the Gradle User Home is shared between the machines_. This functionality has been implemented, but had to be disabled due to the [potential to leak secrets in the configuration cache data](https://github.com/gradle/gradle-build-action/security/advisories/GHSA-h3qr-39j9-4r5v).

Currently, there is no way to truly secure the configuration cache data without encrypting or securing access to the Gradle User Home directory. Allowing a user to specify an encryption key for the configuration cache (instead of using the built-in hardcoded one) would be relatively straightforward, and would allow us to reuse configuration cache data safely in GitHub Actions.

In summary, I'd like you to consider this as a separate feature request for improving Gradle. By making it part of the much larger request of general configuration-cache reuse, it will effectively move into the "not in the foreseeable future" bucket, which would be sad.

**Comment by cobexer** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by mlopatkin** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by kaeawc** [comment]
@mlopatkin I'd be happy to contribute to the solution. From the above proposal is there a particular direction the team wants to take?

**Comment by mlopatkin** [comment]
> @mlopatkin I'd be happy to contribute to the solution. From the above proposal is there a particular direction the team wants to take?

Thank you for your suggestion. We need some time to discuss the desired shape of the solution, but we'll keep you posted.

**Comment by abstratt** [comment]
@kaeawc @bigdaz Since we are talking about using environment variables for the keystore password, or as an input for the keystore generation... some other options:

1. use an environment variable to provide the encryption key, and skip the use of a keystore altogether
2. provide an externally generated keystore placed at a custom location (provided as an option or env var) that is created ahead of calling Gradle

Did you consider any of these options? #1 was how the encryption key was configured in the first incarnation of the encryption feature. What are your thoughts, re: pros/cons?

**Comment by kaeawc** [comment]
@abstratt @bigdaz As long as we have backwards compatibillity with the existing keystores, I think either generating the keystore from env variables or using an env variable as the entire key is fine. With either route the idea would be for official Gradle CI actions/orbs/plugins to look for the existence of this env variable in deciding whether to store the configuration cache between runs.

As for your second suggestion, an externally generated keystore with environment variable path is more complex than an environment variable. I'd rather keep this change as simple as possible for people to use so that:
1. The official Gradle GitHub Action can start to make use of it and most OSS projects start to benefit.
2. Build engineers already have lots of footguns via configuration, fewer options is probably better.

I believe @bigdaz you were also in favor of just env variable as the encryption key, right?

**Comment by kaeawc** [comment]
@abstratt looks great, solves the need, thanks!

**Comment by abstratt** [comment]
This feature will be part of the 8.6 release. Please see release notes (and related documentation) in a recent nightly:

https://docs.gradle.org/nightly/release-notes.html#other-improvements

**Comment by JavierSegoviaCordoba** [comment]
@abstratt I am getting this issue:

```
* What went wrong:
[2023-12-13 10:15:31] Could not load the value of field `parameters` of `org.gradle.api.internal.provider.DefaultValueSourceProviderFactory$DefaultObtainedValue` bean found in field `obtainedValue` of `org.gradle.configurationcache.fingerprint.ConfigurationCacheFingerprint$ValueSource` bean found in Gradle runtime.
[2023-12-13 10:15:31] > Failed to instrument class org/jetbrains/kotlin/gradle/plugin/internal/CustomPropertiesFileValueSource$Parameters in ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:module-configuration]:buildSrc[:module-configuration]:root-project[:module-configuration](export)}
``` 

I have a `:module-configuration` which is a normal included build, there is no `buildSrc` in the project, so I am not sure why it is mentioned there.

**Comment by abstratt** [comment]
@JavierSegoviaCordoba I am confused. Is that really related to the present issue? What you describe seems to be mentioned in https://github.com/gradle/gradle/issues/25864.

**Comment by JavierSegoviaCordoba** [comment]
@abstratt I think we are not caching all necessary files consumed by the configuration cache.

@bigdaz do you know if there is a guide about what should we cache which would be a copy of the behavior of the Gradle Build Action?

I cannot use the Gradle Build Action in one project as it is using GitLab CI/CD.

**Comment by abstratt** [comment]
@JavierSegoviaCordoba Please open a new issue if you are seeing a problem with Gradle and provide (in that new issue) details that allow us to reproduce or at least understand what you are seeing.
