### ISSUE TITLE
Including a:b in settings.gradle.kts should not include a itself implicitly

### ISSUE THREAD

**Issue by elshad-faire** [gradle/gradle#27115]
### Expected Behavior

When I want to only include subset of Gradle subprojects, Gradle should not implicitly bring in more projects. Or at least, maybe there should be an option to force Gradle to only include the manually listed projects.

### Context

Hey team, currently, we are trying to improve local dev experience which is mainly dictated by Gradle experience. We have enabled configuration cache which helps but git rebases are painful because of configuration cache misses and IDE syncs.

We think [focus plugin](https://github.com/dropbox/focus) should help because it allows a developer focus on a subset of all Gradle subprojects. But it does not work for us. It took me a while to figure out that it does not work because of how the [include function in settings.gradle.kts](https://docs.gradle.org/current/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String[])) works:

"As an example, the path a:b adds a project with path a:b, name b and project directory $rootDir/a/b. It also adds the a project with path :a, name a and project directory $rootDir/a, if it does not exist already."

This was unexpected ...

We have so many cases that a and a:b are both Gradle projects. So would have to do a lot of refactoring in our repo to get focus plugin working (or any similar tool custom made or third party).

This is just one problem. There is another problem that is core to how Gradle works. For example, if project A depends on project B and project B has test dependency on project C then evaluating A indirectly evaluates C but A does not really care about C. So it is not possible to enhance the focus plugin so that it would only bring in project B when project A is focused.

We are at a stage that some Gradle conventions are causing so much overhead on an individual Gradle command for us. I guess what I am trying to ask for is, are these problems acknowledged at Gradle? Are there plans to fix these? I checked the roadmap and did not see anything mentioned for these.

Thanks.

**Comment by alllex** [comment]
> We have so many cases that a and a:b are both Gradle projects. So would have to do a lot of refactoring in our repo to get focus plugin working (or any similar tool custom made or third party).

Have you tried an alternative way of including the projects, by specifying the project directory separately?

An example of this is in the same `include` [function doc](https://docs.gradle.org/current/dsl/org.gradle.api.initialization.Settings.html#org.gradle.api.initialization.Settings:include(java.lang.String%5B%5D)):
```
include 'a-b' // use a dash or any other character to make it a plain name
project(':a-b').projectDir = file('a/b')
```

In this case, the project in the `<root>/a` is not included in the build.

---

> There is another problem that is core to how Gradle works. For example, if project A depends on project B and project B has test dependency on project C then evaluating A indirectly evaluates C but A does not really care about C. So it is not possible to enhance the focus plugin so that it would only bring in project B when project A is focused.

Could you file a separate issue for this, as it is an unrelated request?

**Comment by elshad-faire** [comment]
@alllex thanks for getting back to me.

I tried the suggestion. The problem with renaming a:b to a-b is that then we have to update all of our build files to use the new names when depending on projects. I am not saying that is not something we can't do but it will be painful...

> Could you file a separate issue for this, as it is an unrelated request?

Sure I will do that.

**Comment by elshad-faire** [comment]
I guess what I am trying to understand is if there is a way to workaround this issue without involving a lot of changes

**Comment by alllex** [comment]
We found another workaround that should not require renaming the projects. 

Before looking at the code, **please consider the following caveats**. The caveats are not specific to the workaround, but rather to your use-case of "not loading some of the projects".

When projects are excluded from the tree of projects (not loaded), this has side effects. For instance, a common pattern is to do `plugins { id("...") version "..." apply false }` in some project in the hierarchy, which makes the plugin available for all transitive children to apply. If the project is excluded, then the plugin is not available anymore.

Another side effect is the dynamic property look up. Calls like `project.property("abc")` or `project.findProperty("abc")` work by falling back to fetching the property value from a parent project, if it's not available on the direct project. This rarely happens in practice, because most of the time properties are defined only in the root `gradle.properties`, but still may have side effects in your setup.

There are possibly more caveats like this.

---

The workaround is to change the `projectDir` of all *unwanted* projects to a non-existent directory. In this case, Gradle assumes these projects have empty build scripts. That means projects will still be loaded, but should have a much smaller impact, because they are mostly empty. In other words, we _stub_ the unwanted projects.

Keep in mind that calls like `allprojects { ... }` and `subprojects { ... }` in parent projects will have effect on the stubbed projects as well.

The good news is that this preserves the logical hierarchy of projects. Like in the example above, the "focused" build would still have projects `:a` and `:a:b` loaded, but the project `:a` would be a stub.

I wrapped the workaround into a settings plugin, which you can apply, for instance, from an init script or even publish to your internal artifact repository and re-use it. In the example below, I apply it directly in the settings script only to make it concise. If you don't need this anywhere else, you can consider inlining the `apply` method body directly into your settings script.

```kotlin
// settings.gradle.kts

rootProject.name = "root"

include(":a")
include(":a:b")
include(":c")
include(":c:d")

abstract class StubbingPlugin : Plugin<Settings> {
    override fun apply(settings: Settings) {
        settings.gradle.settingsEvaluated {
            val focusProjects = getFocusProjects()
            if (focusProjects != null) {
                stubProjects(rootProject, focusProjects)
            }
        }
    }

    private fun getFocusProjects(): Set<String>? {
        // can read from file, etc
        return setOf(
            ":a:b",
            ":c:d",
        )
    }

    private fun stubProjects(root: ProjectDescriptor, projectsToKeep: Set<String>) {
        traverseProjectTree(root) { project ->
            if (project.path != ":" && project.path !in projectsToKeep) {
                project.projectDir = dummyDir(project)
            }
        }
    }

    private fun dummyDir(project: ProjectDescriptor) = File("blackhole/${dummyUniqueName(project)}")

    private fun dummyUniqueName(project: ProjectDescriptor) = project.path.trim(':').replace(":", "-")

    private fun traverseProjectTree(project: ProjectDescriptor, action: (project: ProjectDescriptor) -> Unit) {
        action(project)
        for (child in project.children) {
            traverseProjectTree(child, action)
        }
    }
}

apply<StubbingPlugin>()

// After settings have evaluated, FocusPlugin may replace some of the projects
// with "stubs" by changing their projectDir to a non-existent directory

// In this snippet projects `:a` and `:c` will be stubbed
```

**Comment by elshad-faire** [comment]
@alllex thanks for the suggestion. I think this one should work.
