### ISSUE TITLE
Nested actions fail to compile in groovy dsl

### ISSUE THREAD

**Issue by Sineaggi** [gradle/gradle#27320]
### Current Behavior

A triply nested configuration fails to compile with for example
```
A problem occurred evaluating project ':lib2'.
> Could not find method configureThis3() for arguments [build_4us9nqnqu54jbs3ilcctsf1r4$_run_closure4$_closure6$_closure7$_closure8@6182a3df] on object of type org.example.NestedConfig1.
```

### Expected Behavior

Just like in the kotlin dsl, the configurations should compile and resolve each nested action.

### Steps to Reproduce

[nested-extension-repro.zip](https://github.com/gradle/gradle/files/13603429/nested-extension-repro.zip)

With an extension setup like so
```java
public abstract class ExampleExtension {
    public void configureThis1(Action<? super NestedConfig1> action) {
        action.execute(new NestedConfig1());
    }

    public class NestedConfig1 {
        public void configureThis2(Action<? super NestedConfig2> action) {
            action.execute(new NestedConfig2());
        }
    }

    public class NestedConfig2 {
        public void configureThis3(Action<? super NestedConfig3> action) {
            action.execute(new NestedConfig3());
        }
    }

    public class NestedConfig3 {
        public void configureThisInnermost(Action<? super NestedConfig3> action) {
            action.execute(new NestedConfig3());
        }
    }
}
```

The following configuration block works in kotlin-dsl, but not the groovy-dsl.
```kotlin
example {
    configureThis1 {
        configureThis2 {
            configureThis3 {
                println("inner")
            }
        }
    }
}
```

### Gradle version

8.5

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***

Groovy DSL performs a conversion from `Action` to `Closure`. Because of that, you can't just call `new NestedConfig3()`. You need to call [ObjectFactory.newInstance()](https://docs.gradle.org/current/userguide/custom_gradle_types.html#dsl_support_and_extensibility). See [this section](https://docs.gradle.org/current/userguide/custom_gradle_types.html#nested_objects) of the documentation.

**Comment by Sineaggi** [comment]
@ov7a indeed in my example using `objects.newInstance` fixes the issue, thanks.
