### ISSUE TITLE
Configuration.getElements() eagerly triggers artifact transforms

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#27372]
### Current Behavior

Using `Configuration.getElements()` to define lazy mapping functions on to-be-produced artifacts should not trigger artifact transforms. Such transforms run too early for locally built artifacts and can produce a wrong result or an error. 

### Expected Behavior

`Configuration.getElements()` does not trigger artifact transforms.

### Reproducer project

**settings.gradle.kts**
```
include("app", "lib")
```

**lib/build.gradle.kts**
```
plugins { id("java-library") }
```

**app/build.gradle.kts**
```
plugins { id("java-library") }

abstract class IdTransform : TransformAction<TransformParameters.None> {
    @get:InputArtifact
    abstract val inputArtifact : Provider<FileSystemLocation>
    override fun transform(outputs: TransformOutputs) { outputs.file(inputArtifact) }
}
val transformed = Attribute.of("transformed", Boolean::class.javaObjectType)
configurations.runtimeClasspath { attributes.attribute(transformed, true) }
dependencies.artifactTypes.maybeCreate("jar").attributes.attribute(transformed, false)
dependencies.registerTransform(IdTransform::class) {
    from.attributes.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "jar").attribute(transformed, false)
    to.attributes.attribute(ArtifactTypeDefinition.ARTIFACT_TYPE_ATTRIBUTE, "jar").attribute(transformed, true)
}

dependencies { implementation(project(":lib")) }

tasks.register<Sync>("copyRT") {
    from(configurations.runtimeClasspath.get().elements)
    destinationDir = layout.buildDirectory.dir("out").get().asFile
}
```

Run: `gradle clean :app:copyRT`

Transform triggers for non existing `lib/build/libs/lib.jar`

### Gradle version

8.5 (reproducible with other 8.x versions and 7.6)

### Build scan URL (optional)

https://scans.gradle.com/s/ktwgohxcen6zq

**Comment by ov7a** [comment]
Thank you for providing a valid report.

The issue is in the backlog of the relevant team, but this area of Gradle is currently not a focus one, so it might take a while before a fix is made.

**Comment by Vampire** [comment]
It's not only when doing `Configuration#getElements()`, it is also when using `getElements()` on other `FileCollection`s that contain transformed things like `from(files().from(configurations.runtimeClasspath).elements)`.

@jjohannes did you find some work-around (I mean except of "somehow handling" absent artifacts within the transformation which can easily result in wrong results as the transform will not be retriggered even if the `InputArtifact` changes later on)?

**Comment by jjohannes** [comment]
No I am not aware of a workaround. It's also unfortunate that Gradle silently does the wrong thing and does not give an actionable error. 

I am afraid that this problem may cause sneaky caching issues. We did run into invalid cache states for local Jar files more than one time which required stopping the daemon and/or "--rerun-tasks" to get them fixed. I wasn't able to pin down the issue(s) yet, but I have the suspicion that it is related to transforms running at the wrong moment (through the 'extra-java-module-info' plugin).

**Comment by Vampire** [comment]
Ah, no, I think here two things are mixed up.

Something indeed is prematurely evaluating artifact transforms.
In a multi-project build here I just did a `gw dist -m` on a fresh work-tree and got some of my artifact transforms fail on missing input artifacts that would have come from project dependencies, as it seems somewhere the artifact transform is triggered during configuration phase when the tasks are not run yet of course, which then either causes the error due to file not found, or if a stale jar is there would then transform the stale jar so potentially end up with the wrong result as the old jar was transformed and then later used even though the jar is later rebuilt, but the artifact transform is of course not rerun.

I first also had the `extra-java-module-info` plugin applied and failed in that, so I had a look at the sources and among other things found the reference to this issue, thinking it also is my issues as I also used `.elements`.

But I commented out various things, including the `extra-java-module-info` plugin and the only relevant `.elements` call I had (unless I missed something) and the error still happened in my own artifact transforms with the project dependencies.

I did not yet find out why they are triggered prematurely at configuration time here, but will investigate further to find out who causes it or where I cause it.

The problem in your MCVE indeed is **not** a premature artifact transform evaluation.
The problem in your MCVE is, that calling `elements` is loosing task-dependency information.
If you execute with `-m` the artifact transform is not triggered, and you also see that the `jar` task is not triggered.
If you change the `from(...)` line to `from(configurations.runtimeClasspath)`, you see it works properly. (Just to show that `from` properly handles the task dependency)
If you keep the `from(...)` like in your MCVE but add `dependsOn(configurations.runtimeClasspath)`, you see it also works properly.

So to recap. While I indeed somewhere have a problem with premature artifact transform during configuration time before task dependency could have been run where I would welcome an error by Gradle as it will either fail if the jar is not present or produce the wrong result if a stale jar is present, the problem that shows in this MCVE is, that `elements` is loosing the task dependency information.

So we should probably split this issue into two.
One for missing error on premature artifact transform where task execution would have been necessary like doing this in your MCVE `from(configurations.runtimeClasspath.get().files)` or also `from(configurations.runtimeClasspath.get().elements.get())` once the other issue is solved.
And another one for `.elements` not carrying over task dependencies.

**Comment by Vampire** [comment]
Btw. a work-around for the premature artifact transform execution could maybe be (not tested yet) to provide the necessary variants / attributes in the local projects directly if possible, so that no artifact transform is necessary.
If the result files are also used at configuration time, this might of course then also not work properly as still the task was not run and either the file is missing or a stale one used, like when iterating over the runtime classpath at configuration time or something like that.

**Comment by Vampire** [comment]
Hm, the longer I look at this, the stranger it gets.
For the "`.elements` is loosing task dependencies" issues, this only happens if there is an artifact transform.
If you just comment out the line adding the attribute to the runtime classpath in your MCVE, it also starts to work fine, having the necessary task dependencies. o_O

**Comment by Vampire** [comment]
If you replace the `from(...)` by `from(configurations.runtimeClasspath.map { it.files })`, then you have the reproducer for the unwarned premature transformation that will fail with missing output if the input is not built yet, or use a stale artifact if one is present before it was rebuilt with the current state by the task execution.
Make sure to manually delete the jar from `lib` because the `clean` is running too late for reproducing this with error.

This also causes task dependencies to get lost even if you do not get an exception, probably because the transform step is marked as "already executed" and thus says "I don't have tasks to run I depend on" when asked.

Because if you comment out the `from(...)` line and add `dependsOn(configurations.runtimeClasspath)`, the task dependency is there.
If you then just comment in the `from(...)` line (don't change the `dependsOn`) the task dependency is lost again.

I guess for this the proper solution would be that the artifact transform action before executing needs to check whether it has task dependencies and if it has task dependencies that are not run yet fail execution with a meaningful error or something like that.

**Comment by Vampire** [comment]
So with this new information and the one from last comment I now think it is indeed not two separate bugs, but the same problem.

When premature artifact transform happens, it happened on absent or stale artifact.
After that the transform is marked as "already executed" and so does not say it needs tasks to be run when asked.
Due to this then the `.elements` or also `dependsOn(configurations.runtimeClasspath)` do not have the expected task dependency anymore.

If the premature artifact transform without upstream task dependency being done would properly fail, then the missing task dependencies should also not happen and instead one can go searching where the premature artifact transformation happens.



An additional question would be, whether `from(configurations.runtimeClasspath.map { it.files })` actually should trigger premature artifact transformation or not. But I guess here the problem is, that the task dependency is not stored in the `Provider<Configuration>` but in the `Configuration` itself, so the provider has to be resolved or something like that.

**Comment by Vampire** [comment]
From what I see, in the original MCVE the premature artifact transformation is coming from the `SkipEmptyIncrementalWorkStep` which then fingerprints the file inputs. And it seems it fingerprints (or tries to) the transformation results. Which might be correct, as a transformation can also suppress an artifact, or even invent one or multiple new ones even if the input artifact is absent. But then why is this checked before the dependency tasks are executed? This might be a second problem here maybe.

**Comment by Vampire** [comment]
Hm, or not.
With the original MCVE when the artifact transform is triggered,
the `SelectedTaskExecutionAction` is already at `taskGraph.execute(plan)` so the task graph was already calculated.
So that the dependencies are missing here is probably not because of premature artifact transform, but yet again another cause.
This might be another bug but would also be discovered more easily with the failure on transform without task dependencies executed already reported.

**Comment by Vampire** [comment]
Don't judge me, but this "little safeguard" in the project, e. g. in the MCVE does exactly that premature transformation protection. I'm sure there is a better way with less internals and private fields to get the task dependencies.

In all cases we mentioned so far (unless I forgot to test any), I now get "InvalidUserCodeException: Executing the transform IdTransform before task ':lib:jar' has completed is not supported" :-)

**Comment by Vampire** [comment]
And here a version that works with 7.6.4:
```kotlin
gradle.addListener(object : ArtifactTransformListener {
    override fun beforeTransformerInvocation(transformer: Describable, subject: Describable) {
        subject.runCatching {
            javaClass.getDeclaredField("artifact").apply { isAccessible = true }.get(subject)
        }.onSuccess {
            it.let { it as? ResolvableArtifact }?.visitDependencies(object : AbstractTaskDependencyResolveContext() {
                override fun add(dependency: Any) {
                    dependency.let { it as? TaskDependencyContainer }?.visitDependencies(object : AbstractTaskDependencyResolveContext() {
                        override fun add(dependency: Any) {
                            dependency.let { it as? TaskDependency }?.getDependencies(null)?.find { !it.state.executed }?.also {
                                throw InvalidUserCodeException("Executing the transform ${transformer.displayName} before $it has completed is not supported")
                            }
                        }
                        override fun getTask(): Task? = null
                    })
                }
                override fun getTask(): Task? = null
            })
        }
    }
    override fun afterTransformerInvocation(transformer: Describable, subject: Describable) {}
})
```

**Comment by Vampire** [comment]
I think the correct place for this check within Gradle would be in `org.gradle.api.internal.artifacts.transform.AbstractTransformExecution#execute` right before `executeWithinTransformerListener`, I'm just not sure how to properly get the task dependencies out of the `ResolvableArtifact` properly instead of that mess above.

**Comment by Vampire** [comment]
My case with premature artifact transform (or at least one of them) is reproduced in given MCVE by replacing the `from(...)` with
```kotlin
from(configurations.runtimeClasspath.flatMap { it.incoming.artifactView {}.artifacts.resolvedArtifacts }.map { emptyList<File>() })
```
or
```kotlin
from(configurations.runtimeClasspath.map { it.incoming.artifactView {}.artifacts.resolvedArtifacts })
```
while this works:
```kotlin
from(configurations.runtimeClasspath.map { it.incoming.artifactView {}.artifacts.resolvedArtifacts }.map { emptyList<File>() })
```
this also works:
```kotlin
from(configurations.runtimeClasspath.map { it.incoming.artifactView {}.artifacts.resolvedArtifacts }.flatMap { provider { emptyList<File>() } })
```
and this again fails:
```kotlin
from(configurations.runtimeClasspath.map { it.incoming.artifactView {}.artifacts.resolvedArtifacts }.flatMap { it })
```

So if `resolvedArtifacts` somehow makes it into the provider chain, the transform is triggered prematurely.

I guess this is a separate issue (discovered through my protection hack above), what do you think?

**Comment by Vampire** [comment]
BREAKING NEWS: Gradle 8.9-rc-2 fixes the prematures artifact transform problems. 🎉 

All variants, including the original MCVE from OP and all variants that should work I showed work as expected and do not or not prematurely execute the artifact transform.

Only the examples with erroneous user-code where I `.get()` or `files` the artifacts during configuration time or in a `map { ... }` still do trigger premature artifact transform.

So I think this issue could be stripped down to protect against premature artifact transform like with my hacky protection code above, just done properly and in Gradle itself. :-)

**Comment by Vampire** [comment]
Maybe slightly less ugly and a bit less hacky:
```kts
gradle.addListener(object : ArtifactTransformListener {
    override fun beforeTransformerInvocation(transformer: Describable, subject: Describable) {
        subject.runCatching {
            javaClass.getDeclaredField("artifact").apply { isAccessible = true }.get(subject)
        }.onSuccess { artifact ->
            if (artifact !is ResolvableArtifact) {
                return
            }
            artifact.visitDependencies(object : AbstractTaskDependencyResolveContext() {
                override fun add(dependency: Any) {
                    val taskExecutedValidator = { task: Task ->
                        if (!task.state.executed) {
                            throw InvalidUserCodeException("Executing the transform ${transformer.displayName} before $task has completed is not supported")
                        }
                    }
                    when (dependency) {
                        is Task -> taskExecutedValidator(dependency)
                        is TaskDependency -> dependency.getDependencies(null).forEach(taskExecutedValidator)
                        is TaskDependencyContainer -> dependency.visitDependencies(this)
                        is Buildable -> dependency.buildDependencies.getDependencies(null).forEach(taskExecutedValidator)
                        is WorkNodeAction -> dependency.visitDependencies(this)
                        else -> error("Unexpected dependency type: ${dependency::class.qualifiedName}")
                    }
                }

                override fun getTask() = null
            })
        }
    }

    override fun afterTransformerInvocation(transformer: Describable, subject: Describable) {}
})
```
