### ISSUE TITLE
gradle daemon keeps git repository files open

### ISSUE THREAD

**Issue by soloturn** [gradle/gradle#27552]
### Current Behavior

idea intellij and gradle-8.5 daemon keeps files out of the git repository open. is this intended or a bug?
```
❯ lsof | grep /src/
java      25956                   287r      REG               8,19   4885931 119538516 /src/.git/objects/pack/pack-3ab188d7695d3877e682c5dc06c8bf656991ff94.pack
java      25956                   288r      REG               8,19   4885931 119538516 /src/.git/objects/pack/pack-3ab188d7695d3877e682c5dc06c8bf656991ff94.pack
java      25956                   293r      REG               8,19   4885931 119538516 /src/.git/objects/pack/pack-3ab188d7695d3877e682c5dc06c8bf656991ff94.pack
java      25956                   295r      REG               8,19   4885931 119538516 /src/.git/objects/pack/pack-3ab188d7695d3877e682c5dc06c8bf656991ff94.pack
<and 150 more>


❯ ps -ef | grep java
25956    1175  3 09:24 ?        00:07:39 /usr/lib/jvm/java-21-openjdk/bin/java --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.prefs/java.util.prefs=ALL-UNNAMED --add-opens=java.base/java.nio.charset=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util.concurrent.atomic=ALL-UNNAMED -XX:MaxMetaspaceSize=384m -XX:+HeapDumpOnOutOfMemoryError -Xms256m -Xmx512m -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -cp /usr/share/java/gradle/lib/gradle-launcher-8.5.jar -javaagent:/usr/share/java/gradle/lib/agents/gradle-instrumentation-agent-8.5.jar org.gradle.launcher.daemon.bootstrap.GradleDaemon 8.5

❯ ps -ef | grep 1175
 1175       1  0 04:53 ?        00:00:00 /usr/lib/systemd/systemd --user
```

### Expected Behavior

no files open out of git repository.

### Steps to Reproduce

build a project with idea and gradle. 

### Gradle version

8.5

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
***
This is unlikely to be caused by core gradle, you may use tools like https://github.com/jenkinsci/lib-file-leak-detector to look for the source of the leak.
