### ISSUE TITLE
[security] support secrets mounts

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#27561]
### Expected Behavior

Support secrets mounts. I first became aware of them with docker, but I think there is support in kubernetes as well, and maybe other tools, but the mount directory has to be configurable. https://docs.docker.com/engine/swarm/secrets/
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.external-config.files.configtree

```kt
providers.getSecret("foo.bar") // use 12 factor https://12factor.net
```

in this case, it would get the value from

```
/run/secrets/foo/bar
```

### Current Behavior (optional)

I'm not aware of any good way to do secrets outside of `~/.gradle/gradle.properties`

### Context

I don't think this should be the only api option for secrets, but since docker is pretty ubiquitous as a runner now, I think it'd be prudent to support it.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

***
This feature should be implemented as an external plugin since it targets a specific technology, however note that configuration cache handling of secrets still is an [open issue](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:not_yet_implemented:secrets).
Related:
* https://github.com/gradle/gradle/issues/22618
