### ISSUE TITLE
Attributes on an ArtifactView are completely ignored

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#27637]
### Current Behavior

For some dependencies, resolving an ArtifactView requesting a specific attribute can sometimes ignore that attribute completely.

### Expected Behavior

The ArtifactView should respect the attributes that were requested.

### Context (optional)

I'm trying to build a plugin that will grab all dependencies and artifacts used by a project and build an offline cache. And one dependency has this issue. `org.junit:junit-bom:5.10.1`

### Steps to Reproduce

```
class DirectMetadataAccessVariantRule implements ComponentMetadataRule {
    @javax.inject.Inject
    ObjectFactory getObjects() { }
    void execute(ComponentMetadataContext context) {
        def id = context.details.id
        context.details.addVariant("moduleMetadata") {
            attributes {
                attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
                attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.REGULAR_PLATFORM))
                attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType, "platform-metadata"))
            }
            withFiles {
                removeAllFiles()
                addFile("${id.name}-${id.version}.module")
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    components {
        all(DirectMetadataAccessVariantRule)
    }
}

task runThing {
    doLast {
        def dep = project.dependencies.create('org.junit:junit-bom:5.10.1')
        def detached = project.configurations.detachedConfiguration(dep)

        def view = detached.getIncoming().artifactView(viewConfiguration -> {
            viewConfiguration.withVariantReselection()
            viewConfiguration.attributes(attributeContainer -> {
                attributeContainer.attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType, "platform-metadata"));
            });
        });
        view.files.each {
            println it
        }
    }
}
```

Run the `runThing` task

This fails with the following error

```
Execution failed for task ':runThing'.
> Could not resolve all files for configuration ':detachedConfiguration1'.
   > Could not resolve org.junit:junit-bom:5.10.1.
     Required by:
         project :
      > Cannot choose between the following variants of org.junit:junit-bom:5.10.1:
          - moduleMetadata
          - runtimeElements
        All of them match the consumer attributes:
          - Variant 'moduleMetadata' capability org.junit:junit-bom:5.10.1:
              - Unmatched attributes:
                  - Provides org.gradle.category 'platform' but the consumer didn't ask for it
                  - Provides org.gradle.docstype 'platform-metadata' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
          - Variant 'runtimeElements' capability org.junit:junit-bom:5.10.1:
              - Unmatched attributes:
                  - Provides org.gradle.category 'platform' but the consumer didn't ask for it
                  - Provides org.gradle.status 'release' but the consumer didn't ask for it
                  - Provides org.gradle.usage 'java-runtime' but the consumer didn't ask for it
```

But I am requesting "platform-metadata", unlike what the error says.

If I put the attribute on the Configuration rather then the ArtifactView, then this seems to work correctly. Which seems like a bug.

### Gradle version

8.5

### Build scan URL (optional)

https://scans.gradle.com/s/cxtr2mfirei2e

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
The issue comes from the fact that there are no attributes defined on the detached configuration.
This is why the error complains about only unmatched attributes.
An artifact view allows you to refine the view of artifacts however it requires proper resolution of dependency variants.
You could solve your usecase by defining your new variant in a custom category and making sure to define that attribute on the detached configuration.

Properly documenting ArtifactViews is tracked in:
* https://github.com/gradle/gradle/issues/26007

**Comment by Vampire** [comment]
@cobexer he did ask in the slack, I sent him here. :-D
I would agree with your evaluation if he would not have used `withVariantReselection()` on the artifact view.
But as he used `withVariantReselection()` on the artifact view, why does the configuration need to resolve unambiguously.
This seems to be a major shortcoming to me.
And it also is inconsistent with lenient.
If the configuration the view is based on cannot resolve because not all dependencies provide a variant, using "lenient" on the artifact view makes the view work.
I would have expected the same for the attributes as long as `withVariantReselection()` is used.

**Comment by ThadHouse** [comment]
@cobexer
Agree with @Vampire  above, everything I've seen shows `withVariantReselection()` changes how things are resolved, and this should work. In fact, with other dependencies, it does work. Its just a specific few that don't, and that doesn't make sense. The repro here was just one of the dependency declarations that did fail. So I still think this is a Gradle bug, and if not reopened I will create a new copy as that is what your response says to do.

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
We send this to the dedicated team for a more in depth analysis.

**Comment by big-guy** [comment]
@cobexer 's original assessment is still correct.  The configuration needs to have attributes.  

Dependency resolution consists of two steps:
- Building the graph
- Selecting the artifact

#26007 describes this and we should document this so it's not confusing. 

ArtifactViews always work by taking a resolved graph and then walking over it to select different artifacts.  With variant reselection, we allow the ArtifactView to consider any variant at a particular node, so in effect it looks like it can pick completely different variants.  The default behavior is to consider only variants that match the combination of artifact view attributes _and_ configuration attributes.  The shape of the graph cannot change with ArtifactView.

In this case, I think you want to resolve the configuration as if it were a runtimeClasspath and then use an ArtifactView on top of it.
