### ISSUE TITLE
Investigate necessity of Dependencies#module

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#27647]
I don't recall why we had to add this over just allowing the syntax in `DependencyCollector#add`. We should investigate if this is still necessary to include as part of the API, or if we can inline it to `DependencyCollector#add`.

**Comment by octylFractal** [comment]
Initial thoughts after taking a look is that we can remove `Dependencies#module`. There does not appear to be any ambiguities or implementation complexity associated with removing it.

**Comment by big-guy** [comment]
Looking at the history on this method again, I think we should keep it as is.

The singular module(String) is kind of weird because I think it's probably not necessary.
`implementation("org:foo:1.0")` and `implementation(module("org:foo:1.0"))` are identical. I think this was only added for documentation purposes.

The `module(String, String, String)` method is a bit different.

In the docs we say:
> You cannot declare dependencies with the Map notation from Kotlin and Java. Use multi-argument methods instead in Kotlin and Java.
> Kotlin: compileOnly(mapOf("group" to "foo", "name" to "bar")) becomes compileOnly(module(group = "foo", name = "bar"))
> Java: compileOnly(Map.of("group", "foo", "name", "bar")) becomes getCompileOnly().add(module("foo", "bar", null))
> 

In the top-level dependencies block, we supported:
- Groovy DSL: implementation group: "org", name: "foo", "1.0"
- Kotlin DSL: implementation(mapOf("group" to "org", "name" to "foo", "version" to "1.0")) and implementation(group = "org", name="foo", version="1.0")
- Java: add("implementation", Map.of("group", "org", "name", "foo", "version", "1.0"))

In addition, between Groovy and Kotlin DSL, we treated implementation("org", "foo", "1.0") differently. In Groovy, this is 3 dependencies and in Kotlin, this is group/name/version. Java might follow the Groovy behavior, but I didn't test that.

There are several considerations:
- Do we want to support named parameters?
- Do we add Map-taking methods in the public API for everything to use?
- How many places do we have to add this as another notation?

The decision was that we wanted to support named parameters in the DSL in the best way for the underlying language. In Groovy, this uses a Map. In Kotlin, this uses named parameters in an extension function.
This notation is only supported through module(...) method to isolate the rest of the DSL. module(...) is better for static languages/Java, so the Map-taking methods aren't necessary for the general API.
We avoid having to add another notation (we have only String, Dependency, Provider<Dependency>, ProviderConvertible) that has to be supported by DependencyCollector and DependencyModifier.

The biggest thing we give up is that you have to write an extra module(...):
- Groovy DSL: implementation module(group: "org", name: "foo", "1.0")
- Kotlin DSL: implementation(module(group = "org", name="foo", version="1.0"))
- Java: getImplementation().add(module("org", "foo", "1.0"))

But we avoid weirdness. If we supported 3 separate strings, I think things go a little side ways because you can then write:
```
implementation("org", "foo")
implementation(testFixtures("org", "foo")) 
implementation("org:foo:1.0", "org:bar:1.0", "org:baz:1.0") // compiles, but surprising
```
This is OK-ish, but I think the first two are more ugly than what we have now and there's some room for confusion. I don't think people would try:
```
implementation(module("org:foo:1.0", "org:bar:1.0", "org:baz:1.0"))
```

 I think there was an ambiguity with the existing notation.

If you have implementation("foo"), is that the name of the module or the full coordinates? We'd have to check for :'s
What about implementation(name="foo")? I don't know if Kotlin is smart enough to call the 3-string version of the method.
What about implementation(name="org:foo:1.0")?

My expectation is that most people are going to...
1. Use the single string notation
2. Use version catalog
3. Use module(...) in plugins

Since it's useful in plugins, simplifies the number of notations we need to support and doesn't introduce ugliness in the DSL, we should leave it.

Maybe we can ditch `module(CharSequence)` because it provides no benefit outside documentation and introduces some ambiguity.  `implementation(module("foo"))` isn't clear how it should be interpreted.

**Comment by octylFractal** [comment]
Of note for should-we-support-named-args:
[`implementation("` Gradle code](https://github.com/search?q=%22implementation%28%5C%22%22+%28path%3A*.gradle+OR+path%3A*.gradle.kts%29&type=code): 366k
[`implementation('` Gradle code](https://github.com/search?q=%22implementation%28%27%22+%28path%3A*.gradle+OR+path%3A*.gradle.kts%29&type=code): 58.4k
[`implementation(group` Gradle code](https://github.com/search?q=%22implementation%28group%22+%28path%3A*.gradle+OR+path%3A*.gradle.kts%29&type=code): 3.5k
[`implementation group:` Gradle code](https://github.com/search?q=%22implementation+group%3A%22+%28path%3A*.gradle+OR+path%3A*.gradle.kts%29&type=code): 47.4k

It's a relatively popular notation.

**Comment by big-guy** [comment]
More likely Groovy DSL notation:
`[implementation ' Gradle code](https://github.com/search?q=%22implementation+%27%22+%28path%3A*.gradle+OR+path%3A*.gradle.kts%29&type=code): 598k

**Comment by big-guy** [comment]
I think we should keep `module` for now or at least, not consider removing it until we've made progress on other things.
