### ISSUE TITLE
API for disabling remote caching of work units (tasks and transform executions)

### ISSUE THREAD

**Issue by runningcode** [gradle/gradle#27710]
### Expected Behavior

A user should be able to configure whether or not a work unit is stored/retrieved to/from the remote build cache.

The exact API should be discussed but there should be a way to configure a task class as well as to configure arbitrary tasks using the ad-hoc API.
A `@LocalCachingOnly` annotation would be one possiblity.

### Context

There are many cases where tasks get negative savings from the remote build cache.
1. Very large artifacts which are quicker to re-execute locally or retrieve from the local build cache.
2. Very small artifacts where the roundtrip time to the remote build cache dominates the download time.

**Comment by lptr** [comment]
What would you lose if you disabled the build cache completely using the existing functionality in these cases? Note that you'd still have up-to-date checks as a first-level cache to rely on.

**Comment by runningcode** [comment]
Another use case here that I just wanted to add is that if we have a transform which is too large to be stored in the remote build cache and it doesn't make sense to increase the max artifact size, it would be nice to be able to disable caching of that artifact.

**Comment by lptr** [comment]
> Another use case here that I just wanted to add is that if we have a transform which is too large to be stored in the remote build cache and it doesn't make sense to increase the max artifact size, it would be nice to be able to disable caching of that artifact.

Here as well the question is: what would you lose if you disabled caching completely for such an artifact?

For context: local caching without remote cache is only useful when you are traversing (already built) history; i.e. you are switching between branches, reverting commits or doing `git bisect`. In all other cases the local cache will only add overhead. This is because the local cache only stores work already done locally. The remote cache can actually bring you results built elsewhere.

Therefore I'd argue that if something is not worth caching remotely, it is likely not worth caching locally either.

**Comment by lptr** [comment]
Let's reopen this if we see evidence that doing this would help.
