### ISSUE TITLE
User manual search does not work for older versions

### ISSUE THREAD

**Issue by ov7a** [gradle/gradle#27769]
### Current Behavior

Current version (8.5):
<img width="512" alt="image" src="https://github.com/gradle/gradle/assets/4946730/6b1a73b9-3daa-4222-a624-01ac97cfde13">
Older version (8.3):
<img width="490" alt="image" src="https://github.com/gradle/gradle/assets/4946730/77bd909a-5105-4691-8429-9c372f341cfc">

### Expected Behavior

Search is available in both versions

### Steps to Reproduce

1. Visit https://docs.gradle.org/current/userguide/userguide.html
2. Search is available
3. Change the version to an older one
4. Search is unavailable

### Gradle version

8.5

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***
It used to work that way but was removed because of confusing behavior and confusing results.
Also, our analytics confirm that most users just browse `/current` docs anyway.
