### ISSUE TITLE
jgit CVE-2023-4759

### ISSUE THREAD

**Issue by uriahcarpenter** [gradle/gradle#27778]
### Current Behavior

[CVE-2023-4759](https://nvd.nist.gov/vuln/detail/CVE-2023-4759) was published on Sept-12-2023 with a base score of `8.8 HIGH`. The jgit venerability was remediated in version `6.6.1.202309021850-r` and backported to `5.13.3.202401111512-r`.

Gradle binary distributions versions up-to, and including, `8.6-rc-2` contain `jgit` jar version `5.7.0.202003110725-r` in the directory `lib/plugins/`.

[Github search](https://github.com/search?q=repo:gradle/gradle+AND+(path:*.gradle+OR+path:*.kts)+org.eclipse.jgit&type=code) of Gradle build files that contain `org.eclipse.jgit`

### Expected Behavior

Third-party security scanners should not report the Java library `jgit` contain the vulnerability documented in CVE-2023-4759.

### Steps to Reproduce

Issue is with Java library dependency of Gradle.

### Gradle version

8.6-rc2

**Comment by ljacomet** [comment]
We are aware of this issue and trying to update JGit as soon as possible. It is however more complex than expected due to the impact on related dependencies.

Note that the upgrade should be done for Gradle 8.7, see:
* #27291

As for the impact of the vulnerability, Gradle only leverages jgit for "source dependencies". Since this feature is about downloading and building a project, there are security risks if the target project is not "safe" and not only because of JGit but because Gradle will actually run the build logic from that project. So the exploit of the JGit vulnerability requires a build that points to a malicious repository.
Also, if your Gradle builds do not use that feature, you can safely remove the library from the distribution.

For the future, please follow our [security policy](https://github.com/gradle/gradle/security/policy) as requested in the issue template screen.

**Comment by ljacomet** [comment]
Fixed by:
* #27291
