### ISSUE TITLE
Library project depending on Spring Boot requires redundant version information

### ISSUE THREAD

**Issue by knob-creek** [gradle/gradle#27789]
### Current Behavior

The given library project builds fine, but cannot not be pubished (at least to maven local):
```
* What went wrong:
Execution failed for task ':generateMetadataFileForMavenPublication'.
> Invalid publication 'maven':
    - Publication only contains dependencies and/or constraints without a version. You need to add minimal version information, publish resolved versions (For more on this, ...
```
Adding a redundant version to the spring boot dependency fixes that (but violates the idea of spring boot dependency management).

### Expected Behavior

The given project should be deployed without the redundant spring boot dependency version

### Steps to Reproduce

Create a simple spring boot project, use the subsequent gradle.properties and build.gradle:

gradle.properties:
```
group=com.example
version=1.0.0
sourceCompatibility=21
```
build.gradle:
```
import org.springframework.boot.gradle.plugin.SpringBootPlugin

buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:3.2.2'
    }
}

plugins {
    id 'java'
    id 'java-library'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.2.2' apply false
    id 'io.spring.dependency-management' version '1.1.4'
}

apply plugin: 'io.spring.dependency-management'

dependencyManagement {
    imports {
        mavenBom SpringBootPlugin.BOM_COORDINATES
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
        }
    }
}
```

### Gradle version

8.5

### Your Environment (optional)

Windows, Red Hat JDK 21

**Comment by knob-creek** [comment]
The whole project:
[spring-lib.tar.gz](https://github.com/gradle/gradle/files/14025547/spring-lib.tar.gz)

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

Your issue appears to be a question about how to use Gradle. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think you have come across a Gradle bug, please file a new issue describing the problem and how to reproduce it.  

If you think Gradle is missing a feature, please file a new issue describing your use case for the feature.

***
You have a number of options:
1. file an issue on the Spring side so that the selected BOM is reflected in the published dependency of a library

1. You could add an explicit dependency on the spring boot platform https://docs.gradle.org/current/userguide/platforms.html#sub:bom_import

1. You could tell Gradle to publish the resolved version https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:resolved_dependencies

**Comment by blaghed** [comment]
@cobexer Could you kindly re-open this ticket so it can be properly addressed, please?
At the moment, Gradle 8.x (up to `8.10.2` at time of writing) is unable to comply with the specification behind Maven Dependencies, and only supports Gradle ones.
