### ISSUE TITLE
Provider<PasswordCredentials> isn't serializable in worker action

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#27821]
### Current Behavior

```stacktrace
Execution failed for task ':infrastructure:deleteFoo.
> A failure occurred while executing DeleteFooWorker
   > Could not isolate value DeleteFooWorker$Params_Decorated@543b94d of type DeleteFooWorker.Params
      > Could not serialize value of type DefaultPasswordCredentials
```

### Expected Behavior

You can pass a `Provider<PasswordCredentials` to worker parameters.

### Context (optional)

Workaround
```kotlin
abstract class DeleteFooWorker : WorkAction<DeleteFooWorker.Params> {
    interface Params : WorkParameters {
        val username: Property<String>
        val password: Property<String>
    }
}
```

### Steps to Reproduce

```kotlin
abstract class DeleteFooWorker : WorkAction<DeleteFooWorker.Params> {
    interface Params : WorkParameters {
        val credentials: Property<PasswordCredentials>
    }
}
```

### Gradle version

8.6-rc-3

**Comment by cobexer** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
***
Why do you want to pass the entire `Provider<PasswordCredentials>` to the worker instead of just passing the `String`?
