### ISSUE TITLE
Extend PluginManager API with withPlugins(vararg plugins) function

### ISSUE THREAD

**Issue by maksym-moroz** [gradle/gradle#27846]
### Expected Behavior

Add withPlugins function that will allow to react in case of several plugins being applied 

### Current Behavior (optional)

Currently you can only react to a single plugin being applied at a time so having a plugin that should be configured in case of several plugins being applied is tiresome (example: java/java-library and maven-publish)

### Context

I think this is a valid use case and if not I would like to see an idiomatic way to handle this

**Comment by cobexer** [comment]
Thank you for your interest in Gradle!

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.
***
You can execute code if multiple plugins are applied if you nest the `withPlugin(...) {}` closures into each other.
However both approaches with the new API you propose and the currently possible approach do not easily enable you to react to only some of the plugins being applied.

**Comment by big-guy** [comment]
IIUC, you want to be able to react to _any_ of the given plugins being applied, not all of them? 

You can currently do this by sharing the common configuration action:
```
Action<AppliedPlugin> commonConfiguration = appliedPlugin -> {
    // java or java-library were applied
};
withPlugin("java", commonConfiguration);
withPlugin("java-library", commonConfiguration);
```
As an alternative, instead of a commonConfiguration Action, you could just have a method that's shared:
```
private static void commonConfiguration(Project project) {
    // java or java-library were applied
}
...
withPlugin("java", appliedPlugin -> commonConfiguration(project));
withPlugin("java-library", appliedPlugin -> commonConfiguration(project));
```

The idea of the new API would be to add something like:
```
withPlugins("java-library", "java", appliedPlugin -> {
    // java or java-library were applied
});
```

But I think what we have is good enough for a few reasons:
- IMO, the verbosity makes it a little clearer that the same configuration is being used for multiple plugins and could run multiple times.
- More often, users request being able to only apply an action when _all_ a particular set of plugins are applied. We may want to use `withPlugins(...)` for that.
- Usually there's a base plugin that the plugins share that would be a better id to use.
- Instead of looking for a particular plugin, it may be possible to react to some other container's contents.
