### ISSUE TITLE
Gradle 8.6 contains `org.eclipse.jgit-5.7.0.202003110725-r.jar` which is flagged for CVE-2023-4759

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#27967]
### Issue type

Other

### Problem description

 `gradle-8.6-bin.zip` includes `org.eclipse.jgit-5.7.0.202003110725-r.jar` which is flagged for [CVE-2023-4759](https://nvd.nist.gov/vuln/detail/CVE-2023-4759)

`org.eclipse.jgit:org.eclipse.jgit`
Latest version listed here: https://central.sonatype.com/artifact/org.eclipse.jgit/org.eclipse.jgit/versions

Please update this jar to the latest version or remove it all together. 

### Context (optional)

Including jar files with know CVEs cause gradle to be quarantined.

**Comment by yogurtearl** [comment]
A backport to `5.x` of the vuln fix is available in `5.13.3.202401111512-r` and later.

**Comment by ov7a** [comment]
Thank you for the report.

Please, follow [our security policy](https://github.com/gradle/gradle/security/policy) in the future. Instead of creating an issue, please submit all security bug reports to [security@gradle.com](mailto:security@gradle.com).

***

This will be fixed by 
* https://github.com/gradle/gradle/pull/27291
Closing as duplicate
