### ISSUE TITLE
maven-publish publishToMavenLocal not generating checksums

### ISSUE THREAD

**Issue by mhalver** [gradle/gradle#2798]
Consider this a question/request for clarification unless it sounds like a bug.  I suspect that it may be an intentional change in behavior.  

When using the maven-publish plugin to publish to a local maven repository, checksum files (md5 and sha1) are not generated.  The section on this in _Gradle in Action_ (14.2.4) as well as any online tutorials I have found suggest that these files should be created and placed in the local maven cache.

When running the sample project below, I expect that the local maven cache for the project (`~/.m2/repository/com/test/Testproject/1`) will contain jar files for each project artifact, the pom file for the project, and md5 and sha1 files for each project artifact.  However, when I run it, the checksum files are not created and placed in the directory.

Here is my sample project, in which I am running `gradle assemble` followed by `gradle publishToMavenLocal`

**build.gradle**
```
buildscript {
    repositories {
        mavenCentral()
    }
}

plugins {
    id 'java'
    id 'maven-publish'
}

version = '1'

group = "com.test"

task sourcesJar(type: Jar) {
    classifier 'sources'
    from sourceSets.main.allSource
}

artifacts {
    archives sourcesJar
}

publishing {
    publications {
        testing(MavenPublication) {
            from components.java
            artifact sourcesJar
        }
    }
}
```

**settings.gradle**
```
rootProject.name = 'Testproject'
```

**src/main/java/com/test/Test.java**
```
package com.test;

public class Test {
    public void main(String... args) {
        System.out.println("testing");
    }
}
```

I am running Gradle 4.1 with Java 8 on Windows 7.

**Comment by mhalver** [comment]
I figured that it probably was an intentional change.  Do you know which version they first stopped being generated in the local cache?  I'm not sure which version _Gradle in Action_ used, but they still were being generated then (unless their examples are just really messed up).

**Comment by blindpirate** [comment]
Well, actually, I tried your code with `2.14`, `1.12`, `3.5` but none of them generates checksum files. I did see the chapter you mentioned in Gradle in Action, honestly, Gradle in Action may be a bit old, since Gradle is a software being extremely active developed, so I highly recommend prefer online documentation. BTW, where did you find the online documentation saying checksum files will be generated? I tried but couldn't find it.

**Comment by mhalver** [comment]
Strange, considering the publication date (2014), I can't imagine them using something older than 1.12.  It may be that the example is incorrect - maybe the author saw that they are generated remotely and just listed them in the directory listing for the book incorrectly.  I posted a question in the forum for the book, but don't know if I will get an answer.  If I do, maybe the author will clarify what is going on with that.

I can't find the online examples that I saw that in.  I'm not sure now if I was seeing what I thought that I was and maybe they were showing remote publication.  It wasn't in any official documentation, but random blogs.

The book does have this incorrect, however.  The author does show how to do this with the publishToMavenLocal command and how to do it with the way that you recommended above.  I bet that the author just incorrectly listed those files in both examples.  Hopefully he is still checking that forum, because that needs to be corrected if there is a future edition.

**Comment by blindpirate** [comment]
@bmuschko I think you're the best person to answer this question.

**Comment by bmuschko** [comment]
The book "Gradle in Action" is based on Gradle 1.7 which still observes the behavior shown in the book. I answered the [question you opened in the book forum](https://forums.manning.com/posts/list/41486.page). The behavior changed in Gradle 1.9 in order to fix [GRADLE-2762](https://issues.gradle.org/browse/GRADLE-2762). Please see the [release notes](https://docs.gradle.org/1.9/release-notes.html#external-contributions) for more information.

**Comment by blindpirate** [comment]
Thanks @bmuschko !
