### ISSUE TITLE
Gradle includes files from one configuration with different attributes into another

### ISSUE THREAD

**Issue by aSemy** [gradle/gradle#28053]
### Current Behavior

Gradle includes files from one configuration with different attributes into another

### Expected Behavior

Gradle does not include files from one configuration with different attributes into another

### Steps to Reproduce

[project.zip](https://github.com/gradle/gradle/files/14247500/project.zip)

run `./gradlew :apollo-kdoc:dokkatooGeneratePublicationHtml`

Observe error `e: java.lang.NoClassDefFoundError: com/apollographql/apollo3/ast/ApolloParser`

This is caused by Gradle is leaking one Configuration into another, despite the attributes being different.

```
--------------------------------------------------
Variant dokkatooHtmlPublicationPluginClasspathApiOnlyConsumable
--------------------------------------------------
Shared Dokka Plugins for consumers that will assemble a html Publication using the Dokka Module that this project produces

Capabilities
    - com.apollographql.apollo3:apollo-ast:4.0.0-beta.5-SNAPSHOT (default capability)
Attributes
    - dev.adamko.dokkatoo.classpath  = dokka-publication-plugins
    - dev.adamko.dokkatoo.format     = html
    - org.gradle.category            = library
    - org.gradle.dependency.bundling = external
    - org.gradle.jvm.environment     = standard-jvm
    - org.gradle.libraryelements     = jar
    - org.gradle.usage               = java-runtime
```

vs

```
--------------------------------------------------
Variant jvmRuntimeElements
--------------------------------------------------
Elements of runtime for main.

Capabilities
    - com.apollographql.apollo3:apollo-ast:4.0.0-beta.5-SNAPSHOT (default capability)
Attributes
    - org.gradle.category                = library
    - org.gradle.jvm.environment         = standard-jvm
    - org.gradle.libraryelements         = jar
    - org.gradle.usage                   = java-runtime
    - org.jetbrains.kotlin.platform.type = jvm
Artifacts
    - build/libs/apollo-ast-jvm-4.0.0-beta.5-SNAPSHOT.jar (artifactType = jar)
```

### Gradle version

8.5

**Comment by aSemy** [comment]
> As stated in our issue template, a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) is a must for us to be able to track down and fix your problem efficiently.

Are you sure? [I didn't see it](https://github.com/search?q=repo%3Agradle%2Fgradle+path%3A%2F%5E%5C.github%5C%2FISSUE_TEMPLATE%5C%2F%2F++minimal&type=code) 

<img width="625" alt="image" src="https://github.com/gradle/gradle/assets/897017/a73f5030-9677-4d27-aaf8-8bec25b5ca03">


> Having a description like "I expect X but observe Y" without providing the context and a description of what are you trying to do is hard to comprehend and time-consuming for us.

I provided the information requested by the issue template... If you're saying that the wording and phrasing is unclear, I can only agree, and I'd like it if the template was re-worded.

> Your reproducer is a whole project of yours

It's not a whole project, it's cut down to be smaller.

I find Gradle usually doesn't provide suitable tools or information to diagnose issues, which means creating a smaller reproducer is usually an extraordinary amount of effort.

> we're not the support to help you solve your issues.

I'm not looking for support, I'm reporting an issue.

> Sure, sometimes your reproducers can point to the issues in Gradle, but our resources are too limited to investigate every project with an error.

I'm sorry that your resources are limited, I can empathise. My resources are limited too.

**Comment by ljacomet** [comment]
How is this different from #27991 ?

Does the added answer over there clarify the situation?

And once again, documentation needs improvement - see #18846

**Comment by aSemy** [comment]
> How is this different from #27991 ?

This issue is a bug report, I think it's similar to https://github.com/gradle/gradle/issues/26463 

#27991 is a separate feature request.

> Does the added answer over there clarify the situation?

Thanks for asking, no it doesn't.

**Comment by ljacomet** [comment]
Ok, however, nothing is easily actionable for us in your report.

Your reproducer contains over a thousand files. Your description of the problem needs to be more extensive. Variant selection does not work as expected, but you do not provide in a clear way what attributes the consumer requests or what the producer provides.

* Could you share a minimal reproducer?
* Could you at least share the attributes:
  * on the consumer configuration,
  * on the producer variant you expect to be selected (or confirm that's the first one you shared)
  * on the selected variant (or confirm that's the second one you shared)

**Comment by Vampire** [comment]
Just in case someone stumbles upon this in the future. 
I added an analysis to the original issue at https://github.com/adamko-dev/dokkatoo/issues/165#issuecomment-3358646296.
This indeed turns out to **not** be a Gradle issue but clarification question. 
Gradle behaves as intended and documented, just the attributes of the involved configurations are not properly set up for nice cooperation. Both miss one of the attributes the other provides and should provide too, then there's play nicely together and the Gradle algorithm works as intended. :-)

**Comment by martinbonnin** [comment]
> Gradle behaves as intended and documented, just the attributes of the involved configurations are not properly set up for nice cooperation.

I think there is a general feedback here that the algorithm, despite being [well documented](https://docs.gradle.org/current/userguide/variant_aware_resolution.html#sec:abm-algorithm) (thanks for that!) is complex to understand and debug. 

The fact that missing attributes are matches bit me several times already. I know why we need it. You don't want to reject a variant just because it's not defining `org.gradle.jvm.version`. But that's still surprising and beyond that, the [algorithm](https://docs.gradle.org/current/userguide/variant_aware_resolution.html#sec:abm-algorithm) takes a lot of care to follow.

I don't have a magic solution here sadly but I would strongly encourage improving the debugging tools for when this kind of things happen. https://github.com/gradle/gradle/issues/34511 is a part of it. 

Or in that specific case, having the possibility to run depenendencyInsights on the `build.gradle.kts` compile classpath would also be interesting. Without more tooling, debugging these issues is very tedious.

**Comment by Vampire** [comment]
> Or in that specific case, having the possibility to run depenendencyInsights on the build.gradle.kts compile classpath would also be interesting. Without more tooling, debugging these issues is very tedious.

`depenendencyInsights` is not much special, it is a task like any other, just does not run in all project having it.
Other than that it is just a task of type `DependencyInsightReportTask`.
Nothing prevents you from registering a sepearate task of that type and there configure any `Configuration` you want like:

```kotlin
val foo by tasks.registering(DependencyInsightReportTask::class) {
    configuration = buildscript.configurations["classpath"]
    setDependencySpec("info.solidsoft.pitest")
    showingAllVariants = false
}
```

or also simply reconfiguring the `dependencyInsight` task like
```kotlin
val dependencyInsight by tasks.existing(DependencyInsightReportTask::class) {
    configuration = buildscript.configurations["classpath"]
}
```

this could also be done using an init script that you use on demand.

Of course, it might eventually make sense to have a built-in task configured with the buildscript configurations container instead of the project one, but at least the work-around in the meantime is quite trivial. :-)

**Comment by Vampire** [comment]
Here from your reproducer project:

<img width="1336" height="359" alt="Image" src="https://github.com/user-attachments/assets/dc7c43d0-585f-4ad0-be0b-a3c669814f18" />

**Comment by martinbonnin** [comment]
I'm not sure I understand how that works. Where should I put this?

```kotlin
val foo by tasks.registering(DependencyInsightReportTask::class) {
    configuration = buildscript.configurations["classpath"]
    setDependencySpec("info.solidsoft.pitest")
    showingAllVariants = false
}
```

The buildscript I want to investigate is `test/build.gradle.kts` but this is also the one that doesn't compile so I can't really add code there.

**Comment by Vampire** [comment]
Well, in that case you would just comment out what does not compile, or comment out everything besides the plugins block and if the plugins would not apply, make them all `apply false` for this investigation, that all is not necessary.
