### ISSUE TITLE
DefaultTask.dependsOn (setDependsOn) has a broken link to accepted parameter types

### ISSUE THREAD

**Issue by Tapchicoma** [gradle/gradle#28102]
### Issue type

Missing information

### Problem description

The description of [DefaultTask.dependsOn](https://docs.gradle.org/current/javadoc/org/gradle/api/DefaultTask.html#dependsOn-java.lang.Object...-) or [DefaultTask.setDependsOn](https://docs.gradle.org/current/javadoc/org/gradle/api/DefaultTask.html#setDependsOn-java.lang.Iterable-) has the following link for the possible accepted dependsOn types:
```
https://docs.gradle.org/current/javadoc/org/gradle/api/DefaultTask.html#dependencies
```

The problem is that this link leads nowhere.

### Page with the problem

https://docs.gradle.org/current/javadoc/org/gradle/api/DefaultTask.html

**Comment by Tapchicoma** [comment]
It looks like the correct link is:
```
https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#dependencies
```

**Comment by ljacomet** [comment]
This is a valid documentation issue.

***

This is caused by `DefaultTask` inheriting its javadoc from `Task` where the link [works fine](https://docs.gradle.org/current/javadoc/org/gradle/api/Task.html#dependsOn-java.lang.Object...-)

One fix could be to have that documentation entry live outside of Javadoc and then link there.
