### ISSUE TITLE
maven snapshot publishing broken metadata

### ISSUE THREAD

**Issue by loboc-fineos** [gradle/gradle#28153]
### Current Behavior

When updating a "-SNAPSHOT" artifact maven-metadata.xml is updated before the pom and artifact are uploaded leading to a temporary situation where CI's fail as metadata is pointing at something that doesn't exist yet.

### Expected Behavior

When updating a "-SNAPSHOT" artifact maven-metadata.xml is updated after pom and artifact are uploaded.

### Context (optional)

After switching from ivy to maven publishing we started to get intermittent failures saying artifacts don't exist.

### Steps to Reproduce

Run "gradlew publish" on a maven-publish project. Check last modified date on files on artifact repository, or access_log on the repository or a network capture.

### Gradle version

6.9.4

**Comment by ljacomet** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

This is really about making sure Gradle publishes the `maven-metadata.xml` files _after_ publishing the artifacts.
See https://github.com/gradle/gradle/blob/76bb26d2463cee093fbf7d7456ad9d8d60d6c61c/platforms/software/maven/src/main/java/org/gradle/api/publish/maven/internal/publisher/AbstractMavenPublisher.java#L74-L85
