### ISSUE TITLE
https://plugins.gradle.org/ API Rest

### ISSUE THREAD

**Issue by patton73** [gradle/gradle#28188]
### Expected Behavior

Do you have some API to query and search for plugins and their latest version? Similar to Maven central's API?

### Current Behavior (optional)

Cannot find those API.

### Context

Need to read latest plugin version given name or package.

**Comment by EdricChan03** [comment]
[shields.io has a badge for the Gradle Plugin Portal](https://shields.io/badges/gradle-plugin-portal-version) - the source essentially uses the same `maven-metadata.xml` file, used for Maven Central/any other Maven repository:

([source](https://github.com/badges/shields/blob/master/services/gradle-plugin-portal/gradle-plugin-portal.service.js):)

```js
  transformQueryParams: ({ pluginId }) => {
    const groupPath = pluginId.replace(/\./g, '/')
    const artifactId = `${pluginId}.gradle.plugin`
    const metadataUrl = `https://plugins.gradle.org/m2/${groupPath}/${artifactId}/maven-metadata.xml`
    return {
      metadataUrl,
      label: 'plugin portal',
    }
  },
```

You only need to append the `.gradle.plugin` suffix to the artifact's ID (so for e.g. the `org.jetbrains.compose` plugin would result in `org.jetbrains.compose:org.jetbrains.compose.gradle.plugin`, or [`org/jetbrains/compose/org.jetbrains.compose.gradle.plugin`](https://plugins.gradle.org/m2/org/jetbrains/compose/org.jetbrains.compose.gradle.plugin/maven-metadata.xml), similar to that of any other Maven repository)

**Comment by patton73** [comment]
If i understood well it should be something similar to this if you are looking for the researchgate gradle release plugin for example:

https://plugins.gradle.org/m2/net.researchgate/gradle-release.gradle.plugin/maven-metadata.xml

but what it happens in browser is that it redirects to 

https://jcenter.bintray.com/net.researchgate/gradle-release.gradle.plugin/maven-metadata.xml

And then it gets a 403 forbidden. 
Is some sort of authetincation needed?

Thanks.

**Comment by EdricChan03** [comment]
> https://plugins.gradle.org/m2/net.researchgate/gradle-release.gradle.plugin/maven-metadata.xml

This is not quite correct, the package name is supposed to be split with slashes (so `net/researchgate` instead of `net.researchgate`).

It also seems that the `gradle-release` variant doesn't have the `.gradle.plugin` suffix - some poking around on https://plugins.gradle.org/m2/net/researchgate shows 2 entries: gradle-release and release.

The ["release"](https://plugins.gradle.org/m2/net/researchgate/release/) directory is the version that was published using the `java-gradle-plugin`, which appends `.gradle.plugin` to the resulting artifact ID (there's a sub-directory named `net.researchgate.release.gradle.plugin`), while the [`gradle-release`](https://plugins.gradle.org/m2/net/researchgate/gradle-release) directory is likely what you're looking for.

**Comment by ov7a** [comment]
@EdricChan03 Thanks for the help!

FTR, for the Plugin Portal related issues, we have
https://github.com/gradle/plugin-portal-requests/issues
