### ISSUE TITLE
Allow registering task `@OutputFile` that does not create parent directory

### ISSUE THREAD

**Issue by mgroth0** [gradle/gradle#28234]
### Expected Behavior

To be able to register an `@OutputFile`, `@OutputFiles`, or `@OutputDirectory` in such a way that it does not automatically create any directories.

### Current Behavior (optional)

It seems that creating the parent dir of a output file is hardcoded, and that there is no way to disable it. The behavior is the same with `@OutputFiles` and `@OutputDirectory` (in which the directory itself is created).

### Context

I have a task that may write or delete a file, according to the inputs. When writing configured to write the file, this is not an issue. But when the task is configured to delete a file, the result might be that we get an empty folder where the was not one before.

**Comment by hfhbd** [comment]
I would configure the other way too: Gradle should create the parent directory of `@OutputFile` too to match the behavior of `@OutputDirectory`.

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by hfhbd** [comment]
@mgroth0 I guess I was just not aware of this behavior or I remember some build failures (in the past) so I always explicitly create the parent directories, will test it, but I agree, an option would be nice.

**Comment by lptr** [comment]
Could you elaborate on the use case some more? It should be perfectly fine for the task not to create the `@OutputFile` (or delete it if it exists already). But what's wrong with the parent directory?

To give some more context, we'd like to not let tasks have more control over handling their outputs. Instead, we want to move towards tasks that execute with as little reliance on the location of their outputs as possible. This is necessary for improved performance and reliability, and for features like sandboxed or containerized execution.

**Comment by lptr** [comment]
Why would you generate that file in the `src` directory hierarchy in the first place? Gradle recommends separating your primary inputs (i.e. source files) that you keep checked into version control, and outputs generated from them during the build (which should not be checked into version control). This file should live in somewhere like `$buildDir/generated-shortcuts/shortcuts.xml`.

**Comment by v1nc3n4** [comment]
Hi,

Thank you @mgroth0 for raising this issue. I faced the same situation in the past where I couldn't understand why Gradle was creating these parent directories and how to disable such behavior.

Ideally, the `@OutputFile` annotation should have an explicit parameter (e.g. `@OutputFile(createParentDirectories = true/false)`.
I think it would also be great the doc comments in the `@OutputFile` annotation are enriched because it does not help to read parent directories are created before the task is executed. The doc should also explain WHY Gradle actually creates these directories (i.e. touches the file system though the task may not).

Thanks in advance for your help and consideration.
BR

**Comment by lptr** [comment]
Let me close this issue as @mgroth0's problem seems to have come from creating the output outside `$buildDir`.

@v1nc3n4 if you would like to request configurable parent directory creation as a feature, please create a new issue for that.
