### ISSUE TITLE
Using toolchains it's not possible to change compiler of JavaCompile task

### ISSUE THREAD

**Issue by dejvu** [gradle/gradle#28385]
### Current Behavior

While having 2 modules "parent" as root project and "child" as child project where in parent defined part is:
```
subprojects {
    java.toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
```

and in child

```
tasks.withType(JavaCompile).configureEach {
    javaCompiler.set(javaToolchains.compilerFor {
        languageVersion = JavaLanguageVersion.of(8)
    })
}
```

results in
`The value for task ':child:compileJava' property 'javaCompiler' is final and cannot be changed any further.`

### Expected Behavior

No errors and compilation in child is done using toolchain for java language 8

### Steps to Reproduce

Provided in Current Behavior section

### Gradle version

8.6

**Comment by ov7a** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Related:
* https://github.com/gradle/gradle/issues/26061
