### ISSUE TITLE
Consistent dependency resolution silently downgrade a dependency, breaking runtime linkage

### ISSUE THREAD

**Issue by doublep** [gradle/gradle#28405]
### Current Behavior

Application fails at runtime with `java.lang.NoSuchMethodError: 'void org.jboss.resteasy.client.jaxrs.i18n.LogMessages.debugf(java.lang.String, int)'`.

### Expected Behavior

Gradle should refuse to downgrade dependency `jboss-logging` in configuration `runtimeClasspath`, because 3.4.3 is the required version. Consistent resolution should be able to raise dependency version, but not silently use a too old version, as it leads to runtime problems, as demonstrated.

### Context (optional)

The project uses this Gradle file:

    apply plugin: 'application'

    repositories {
        mavenCentral ()
    }

    java {
        consistentResolution {
            useCompileClasspathVersions ()  // To make 'runtimeClasspath' and 'compileClasspath' have the same library versions
        }
    }

    dependencies {
        compileOnly 'net.sourceforge.tess4j:tess4j:5.7.0'  // If this is commented out, the "application" works, because jboss-logging is not downgraded from 3.4.3 to 3.1.4
        compileOnly 'javax.ws.rs:javax.ws.rs-api:2.1.1'
        runtimeOnly 'org.jboss.resteasy:resteasy-client:5.0.9.Final'
    }

    configurations.compileClasspath.each { if (it.name.startsWith ('jboss-logging')) println it.name }
    configurations.runtimeClasspath.each { if (it.name.startsWith ('jboss-logging')) println it.name }

    application {
        mainClass = 'foo.Test'
    }

Its Java code simply instantiates a JAX RS client. It should be RESTEasy, as added to classpath by Gradle.

However, instantiation fails at runtime, because Gradle supplies inconsistent dependency JARs to Java. RESTEasy 5.0.9 uses jboss-logging 3.4.3. However, because of the requested consistent resolution, Gradle is required to provide the same jboss-logging version as on 'compileClasspath' (if it is there at all). Dependency Tess4j (only used here to demonstrate the resolution problem) pulls jboss-logging 3.1.4. Gradle then _silently_ downgrades runtime version to 3.1.4, ignoring RESTEasy needs, which breaks RESTEasy when the application is executed.

Same behavior if using `runtimeClasspath.shouldResolveConsistentlyWith (compileClasspath)`. In real project I use an additional custom configuration, but the standard ones were enough to reproduce the problem.

### Steps to Reproduce

1. Unpack this Gradle project: [resteasy.zip](https://github.com/gradle/gradle/files/14545801/resteasy.zip)
2. Inside the project execute `./gradlew run`.

### Gradle version

8.6

**Comment by ov7a** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

Please refer to [the docs](https://docs.gradle.org/current/userguide/resolution_strategy_tuning.html#resolution_consistency). The feature works as expected: consistent resolution is allowed to downgrade versions since it uses `strictly`. You can fix multiple ways, e.g. change the `compileClasspath` to use the right version by setting it explicitly.
