### ISSUE TITLE
Gradle Wrapper License Details

### ISSUE THREAD

**Issue by granthenke** [gradle/gradle#2852]
Because the Gradle wrapper scripts and properties files are "generated" from the Gradle project and checked in, their licensing details are important. 

Should the "Apache License, Version 2.0" header be generated and included on the gradlew, gradlew.bat, and wrapper/gradle-wrapper.properties files that are generated? 

### Expected Behavior
The gradle wrapper task includes a valid license header for the generated files to be checked in. 

### Current Behavior
No license header is included.

### Context
Recently experimental Gradle support was added to Apache Kudu. The lack of license header resulted in a lengthy discussion and investigation into how these files should be included with valid licenses.

**Comment by str4d** [comment]
The templates for the two scripts are here:

https://github.com/gradle/gradle/tree/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins

The properties file is generated here:

https://github.com/gradle/gradle/blob/master/subprojects/build-init/src/main/java/org/gradle/api/tasks/wrapper/Wrapper.java#L175-L186

**Comment by str4d** [comment]
I agree that the scripts should have license headers. I'm not sure the properties file should though; it's configuration data, rather than code, and arguably simple enough that it would count as a non-copyrightable statement of facts. Given the required configuration parameters for `gradle-wrapper.jar`, I don't see how anyone could reasonably "implement" the properties file independently in any other way.

That said, IANAL, and copyright law is its own special beast...

**Comment by granthenke** [comment]
This was fixed in https://github.com/gradle/gradle/commit/f61895fcfbf847d30e0f9adc9302beab162b1e50 tied to issue #8151
