### ISSUE TITLE
Make pmd's cache work with build cache

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#2862]
In #2223 , PMD plugin introduced analysis cache, which may cause issue when working with build cache. We need to provide some integration tests in the following scenario:

- run the task with some inputs that generates an analysis file
- make some changes to the inputs
- run the task again, this time get a cache hit and load from cache – this will leave the analysis file in place, even though it’s not relevant for the inputs anymore
- make some changes again
- run the task again: this time you might have problems because of the irrelevant analysis file

However, for the moment, it seems like the checksum for the cache is based on the hash of just the order and absolute file paths for the PMD classpath so changes to the contents of jars would be ignored: [https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java#L90](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java#L90), and the maintainer of pmd promised this would be fixed in later release. If not, we'll consider disable the incremental analysis in build cache.

**Comment by jsotuyod** [comment]
> However, for the moment, it seems like the checksum for the cache is based on the hash of just the order and absolute file paths for the PMD classpath so changes to the contents of jars would be ignored: https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java#L90, and the maintainer of pmd promised this would be fixed in later release. If not, we'll consider disable the incremental analysis in build cache.

PR submitted for PMD 6.0.0 - https://github.com/pmd/pmd/pull/615 👍

**Comment by wolfs** [comment]
@jsotuyod Could you somehow extend Pmd's API so you could actually use the data from Gradle which files changed since the last execution? Using [`IncrementalTaskInputs`](https://docs.gradle.org/current/userguide/custom_tasks.html#sec:implementing_an_incremental_task) would probably help a lot, maybe even making the use of the Pmd analysis cache superfluous when using Gradle. WDYT?

**Comment by jsotuyod** [comment]
@wolfs doing so would be too Gradle-specific. We built the feature to support all platforms making use of PMD and intend to support it and extend it as necessary for everyone. PRs are welcomed, but we have no concrete plans on building this ourselves in the short term.

Non the less, as far as I can tell, the current implementation should have no issue with the gradle-build cache, and shall there be any, they would probably still affect other platforms, making them top priority for us.

**Comment by wolfs** [comment]
@jsotuyod What I was referring to was that it could be possible to provide a list of changes to the PMD API (which is currently the Ant task from the Gradle viewpoint), instead of PMD trying to guess the changes. This way the Gradle plugin wouldn't need to use the analysis cache but could rely on the already calculated information for incremental builds instead.

**Comment by jsotuyod** [comment]
@wolfs I know. But again, doing so would mean moving change detection to the tools, which none other than Gradle do (specially not changes to pmd version, auxclasspath, etc.), hence the gradle-specific part.

Moreover, even if they did, different tools would use different implementations, which would lead to different behaviors. We'd rather provide a single tested implementation where, using PMD-specific knowledge of what is or is not relevant, we can provide the best experience.

For instance, adding a new dependency to my project would produce a change to my auxclasspath. Under Gradle, that means all files are considered out of date. However, that *may* not be actually true. If no configured rule makes use of DFA / type resolution, [changes to the auxclasspath are simply irrelevant](https://github.com/pmd/pmd/blob/master/pmd-core/src/main/java/net/sourceforge/pmd/cache/AbstractAnalysisCache.java#L93-L95).

Also of note, under your suggested implementation, the cache would still be needed, we would simply rely on inputs for invalidation / cache hits; but analysis results would still need to be serialized to the cache. Otherwise we would not be able to generate full-reports, but only report on the changed files (leaving out all non-changed files with violations), which is not the intention of the feature. The report should be *exactly the same* with incremental analysis, just way faster to compute.

**Comment by blindpirate** [comment]
Closed by #3125 . We're reverting pmd's new feature in `4.3RC1` since it seems not mature enough.

**Comment by henrik242** [comment]
@blindpirate Should this be reopened, with regard to #3125 ?

**Comment by henrik242** [comment]
Any progress @blindpirate  / @oehme ?

**Comment by Cinderhaze** [comment]
I am trying to configure pmd 6.1.0 with gradle 4.6, and It seems like the ability to set the incremental build cache has been reverted. Is there any way to pass in the `-cached` argument to the pmd plugin manually to remove the warning as a part of our build?  I saw that there is an internal `PmdInvoker.antPmdArgs` at https://github.com/gradle/gradle/blob/release/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/PmdInvoker.groovy#L44

Is there any way to set that manually, until the proper plugin solution gets merged?

**Comment by geekmug** [comment]
In the absence of support for the build cache, PMD 6.2 added a "-no-cache" option that disables this warning (https://github.com/pmd/pmd/pull/954).

**Comment by baev** [comment]
In our project we get a few hundreds lines per module with such warning and logs become unreadable. Is there any chances to get this fixed?

**Comment by CreeTar** [comment]
Still an issue, not impressed with you guys, sending a --no-cache is a 5-Minute-Fix, seriously... I'll fix it for you guys, if you cannot handle a single argument to fix this issue... *sad puppy eyes*

**Comment by regrog** [comment]
what about this?
https://docs.gradle.org/5.6-rc-1/release-notes.html#support-for-pmd-incremental-analysis

**Comment by wolfs** [comment]
So it looks like pmd's cache now works with the build cache. Closing.
