### ISSUE TITLE
Update Bouncy castle to latest to avoid CVE-2023-33201

### ISSUE THREAD

**Issue by yogurtearl** [gradle/gradle#28636]
### Issue type

Other

### Problem description

Update Bouncy castle to latest to avoid CVE-2023-33201

https://nvd.nist.gov/vuln/detail/CVE-2023-33201

https://github.com/gradle/gradle/blob/d8cad90101799383c990e394184f35a230bb544e/subprojects/distributions-dependencies/build.gradle.kts#L24

**Comment by ov7a** [comment]
Please follow [our security policy](https://github.com/gradle/gradle/security/policy) in the future. Instead of creating an issue, please submit all security bug reports to [[security@gradle.com](mailto:security@gradle.com)](mailto:security@gradle.com).

***

Reading the description of the vulnerability, it doesn't look severe for Gradle, though.

> Bouncy Castle For Java before 1.74 is affected by an LDAP injection vulnerability. The vulnerability only affects applications that use an LDAP CertStore from Bouncy Castle to validate X.509 certificates. During the certificate validation process, Bouncy Castle inserts the certificate's Subject Name into an LDAP search filter without any escaping, which leads to an LDAP injection vulnerability.
