### ISSUE TITLE
Gradle should honor version ranges constraints properly

### ISSUE THREAD

**Issue by melix** [gradle/gradle#2869]
- If `project` depends on `a` and `b`. 
- If `a` depends on `leaf` with a version range `[3;8]` and 
- `b` depends on `leaf` with a version range `[6;12]`, Gradle selects version `12`, where it should select version `8`, which is the highest version within both ranges.

### Expected Behavior

Gradle should be able to recognize that 2 versions have "compatible" ranges and choose a version within those ranges.

### Current Behavior

The current behavior is misleading: when `leaf` is added, it is seen as a dynamic dependency (it's a range). For `a` It's then resolved according to the published versions. We list all published versions, sort them by descending order, and select the highest matching version, which is `8`.

Then we reach node `b`, which also has a dependency on `leaf`, with a different range. `leaf` is also resolved, but this time the highest compatible version is `12`.

With both nodes added in the graph with conflicting versions, conflict resolution kicks in. It sees two versions, `8` and `12`, and selects the highest version, which is `12`.

### Context

Ideally, Gradle should remember that all versions within range are compatible, and maybe not immediately select.

**Comment by oehme** [comment]
This has been merged.

**Comment by sonicsnes** [comment]
@melix I'm curious if there is a convenient recommended way to reverse this change in our internal gradle fork. We use gradle in a pretty extensive ivy ecosystem, where we count on version ranges to pull in the highest matching version, rather than matching something pulled transitively (which is typically quite old in our case).

I'll probably wind up hacking this out of our branch since it doesn't appear to be configurable, but I'd appreciate any recommendations since the change also included a large refactor.

**Comment by melix** [comment]
I wouldn't recommend on reverting this change: we're intensively reworking the dependency management engine, and any custom change in that area is likely to be very complex to handle. This change was made to make the dependency engine more consistent by choosing the best matching version in both ranges.

So let's try to understand your use case. You are saying:

> we count on version ranges to pull in the **highest matching version**, rather than matching something pulled transitively (which is typically quite old in our case)

So say component A depends on `[3,8]` and component B depends on `[6,12]`, you want version `12` to be selected, even if version `13` is released since then, I assume (which would explain why you use a range rather than `latest.release`).

But if so, depending on `8` and `12` would do exactly what you want: conflict resolution would kick in and select `12`, so you don't need ranges at all.

If you have A depend on `[3,8]`, and B pulls in an "old" dependency on `1`, then `8` would be selected by conflict resolution, so I guess it's not your problem either.

Eventually, if you have A depend on `[3,8]` and B pulls in `4`, then we select `4` (because it's in the range). If you want `8` to be selected, then again you shouldn't have used a range in the first place: `8` would have done what you need.

By using a range, you're saying "any version between 3 and 8 is suitable". By using `8`, you're saying "8 is ok, but it can be upgraded (not downgraded)".

So can you explain more precisely your use case, to see if it's covered by the new dependency management rules we are implementing?

**Comment by sonicsnes** [comment]
In our ecosystem, minor versions of modules are released on a regular basis; 7.1, 7.2, 7.3, 7.4, .... However, on rare occasions, we must maintain two simultaneous major versions of modules, so in addition to the new 7.x releases, new 8.x releases may also be published alongside.

Most projects attempt to pull in the latest 7.x release, and thus depend on dynamic version range [7,8). However, if they transitively receive the dependency on gradle 4.3+, there is no way for them to indicate "latest 7.x version."

**Comment by melix** [comment]
Right, so if a project says:

* "I depend on [7,8)", and a transitive dependency pulls in `8`, then 8 is going to be selected. This behavior hasn't changed.
* "I depend on 8", and a transitive dependency pulls in `[7,8)`, then 8 is going to be selected. This behavior hasn't changed.
* "I depend on [7,8)" and a transitive dependency pulls in `7.3`, then 7.3 is going to be selected, even if 7.4 is out. This behavior hasn't changed either, as this commit only changes the behavior when there are concurrent _ranges_
* "I depend on [7,8)" and a transitive dependency pulls in `[7,7.3]`, then 7.3 is going to be selected, instead of 7.4 (assuming 7.4 is the latest 7.x release). This has changed, as previously we would have selected 7.4. However, the transitive dependency says "I depend on something between 7 and 7.3, not higher", so this is why the dependency engine chooses the best version within both ranges.

So can you point me at a concrete example, with the direct dependency range and the transitive dependency versions, where this pull request changes the behavior?

Thanks

**Comment by sonicsnes** [comment]
Yep, that is our current use-case.

**Comment by rhencke** [comment]
Is there any way to restore the prior behavior, such as via `resolutionStrategy`?  We (unfortunately) depend on the prior broken behavior heavily our builds.

**Comment by bigdaz** [comment]
@rhencke No there's not any way to revert to the old behaviour. Can you be more specific about how you depend on the prior behaviour? A build scan (or gist) showing the dependency report might be useful.

**Comment by rhencke** [comment]
@bigdaz If there's no way to revert to the old behavior, that's okay.  It would have been nice, but honestly, the way version ranges are used in this project has caused us a lot of headache, and knowing Gradle won't work this way moving forward means we're forced to finally fix it. ;)

But, for the sake of completeness:

I work in a system that (ab)uses version ranges as a way to grab the latest versions of projects across several teams for a given release, without having to know ahead-of-time which projects have and have not been updated.  Versions are always specified in a manner of `[base release, current release]`, because not all projects are compiled/delivered with every release.

It used to be this had the effect of (almost) always selecting the most recent version available for every component (including transitively), within the current release.  However, due to the nature of transitive dependencies, much older versions are now selected.  Sketching it out, it'd look something like...

```
# For version 3.0, only A and C were updated.
project A {
    references B[1.0, 3.0]
    references C[1.0, 3.0]
}
project C {}
```

```
# For version 2.0, only B and C were updated.
```
project B {
    references C[1.0, 2.0]
}
project C {}
```

When project A was built, prior to Gradle 4.3, this would result in C version 3.0 being selected. 
However, now, version 2.0 will be selected.

**Comment by rhencke** [comment]
(I did get the build scans, though, feel free to reach out at robert.hencke@kronos.com and I'll send them to you, if you want them.)
