### ISSUE TITLE
Transitive dependencies of API dependencies should not be exposed on consumers compile classpath

### ISSUE THREAD

**Issue by abuechler** [gradle/gradle#2875]
### Expected Behavior
Transitive dependencies of API dependencies should not be exposed on to consumers compile classpath, they should only be exposed on the runtime classpath of consumers.

### Current Behavior
As by the documentation for the java-library plugin: 

> [Dependencies appearing in the api configurations will be transitively exposed to consumers of the library, and as such will appear on the compile classpath of consumers.](https://docs.gradle.org/current/userguide/java_library_plugin.html)

### Context
This is a feature request and aims to have a more explicit and controlled way to define what is exposed on to consumers classpath. Since authors of a java-library project need to already separate between what are internal dependencies (through the implementation configuration) and what's exposed to consumers (through the api configuration) one could go even further and not expose those transitive dependencies of api dependencies automatically on the consumers compile classpath.

**Comment by oehme** [comment]
If you use library `foo` (it doesn't matter if you use it as an api or implementation dependency), then you need the API dependencies of `foo`, otherwise you can't compile against it. E.g. if `foo` uses a Guava `CharMatcher` on a public signature, then you need Guava to use that method. Implementation details of `foo` on the other hand will not be leaked (again - no matter if you use `foo` as api or implementation detail).

This already works correctly for project dependencies. What still needs to be fixed is making this work when resolving from Maven repositories. See #977

**Comment by abuechler** [comment]
@oehme What I found confusing is that this [bug](https://github.com/gradle/gradle/issues/977) (now re-labeled as feature) regarding the resolution of maven dependencies is described as a the correct/desired behavior in the java-library documentation. Anyway thanks for the explanation!

**Comment by oehme** [comment]
The documentation of the java-library plugin states that `api` dependencies will be exposed to clients, which is correct and desired.

The other issue you linked is about the fact that `implementation`/`runtime` dependencies currently get leaked if you go through a Maven repository. That is undesired and will be fixed.

**Comment by sg1303** [comment]
hi @oehme is there an issue open for the dependency leak issue you mentioned? did this ever get fixed?

**Comment by oehme** [comment]
https://github.com/gradle/gradle/issues/977, fixed in 4.5
