### ISSUE TITLE
Provider::zip incorrectly returns null when only one provider is set

### ISSUE THREAD

**Issue by scott-pollom** [gradle/gradle#28826]
### Current Behavior

When using the `Provider::zip` method to combine two providers, if one of the providers is not set (returns null), the resulting zipped provider unexpectedly returns null despite the other provider being set with a non-null value.

### Expected Behavior

I would expect the resulting zipped provider to use the result of the `BiFunction` parameter even if one of the providers is not set.

### Steps to Reproduce

Add the following to a `build.gradle` file:

```
def firstProvider = providers.provider { null }
def secondProvider = providers.provider { "Hello, World!" }

// Zip the two providers
def zippedProvider = firstProvider.zip(secondProvider) { first, second ->
    first ?: second
}

// Task to print the result of the zipped provider
task printZippedProvider {
    doLast {
        println "Zipped provider value: ${zippedProvider.orNull}"
    }
}
```

Running `./gradlew printZippedProvider` prints `Zipped provider value: null`

Note: the outcome is also the same when `firstProvider` is set and `secondProvider` is unset.

### Gradle version

8.7

**Comment by mlopatkin** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

The `Provider` cannot actually hold `null` values. Whenever the `provider`, `map`, `zip`, `flatMap`, etc. returns `null`, the resulting provider is actually unset/empty. It is not possible to transform or combine a value of an unset provider because there's no value to begin with, just like with `Optional`. However, `zip`'s javadoc seems to miss the necessary clause about it.

`Provider.orElse` should be used if a fallback is needed. In this particular case, `firstProvider.orElse(secondProvider)` achieves the expected result.

**Comment by scott-pollom** [comment]
Oh, that's surprising behavior. Thanks for updating the docs.

> `Provider.orElse` should be used if a fallback is needed. In this particular case, `firstProvider.orElse(secondProvider)` achieves the expected result.

Does `Provider.orElse` carry both providers' dependency information like `Provider.zip` does?

**Comment by mlopatkin** [comment]
>Does Provider.orElse carry both providers' dependency information like Provider.zip does?

That's a weak spot at the moment, though we want to [fix this](https://github.com/gradle/gradle/issues/24141). It only carries dependencies of the first provider.
