### ISSUE TITLE
Change in projectsLoaded execution starting in 4.0

### ISSUE THREAD

**Issue by john3300** [gradle/gradle#2888]
Submitting this issue as requested by Stefan Oehme in the original forum post for this:
https://discuss.gradle.org/t/change-in-projectsloaded-execution-starting-in-4-0/23993

### Expected Behavior

Here's the output from running the sample code below with 3.5:
```
$ gradle --console=plain build
Inside projectsLoaded
Inside rootProject
Inside beforeEvaluate
Blah
:buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
No dependencies

BUILD SUCCESSFUL

Total time: 0.929 secs

```
### Current Behavior

And here's the output from running it with 4.0. Notice how the debug statements stop after projectsLoaded.
```
$ gradle --console=plain build 
Inside projectsLoaded

FAILURE: Build failed with an exception.

* Where:
Build file '/home/bjohnson/gradletest/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating root project 'Test'.
> Could not get unknown property 'extvar' for project ':subA' of type org.gradle.api.Project.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED in 1s
```

### Context

Trying to set an extra property on the root project before it (and all the subprojects) gets evaluated.
This issue exists in 4.0 and 4.1.

### Steps to Reproduce (for bugs)

Here's a very simplified example that demonstrates the change in behavior and can be used to recreate the issue. The println statements are just for debug purposes.

**settings.gradle:**
```
rootProject.name = 'Test'
include ':subA'
gradle.projectsLoaded { g ->
    println "Inside projectsLoaded"
    g.rootProject {
        println "Inside rootProject"
        beforeEvaluate { project ->
            println "Inside beforeEvaluate"
            project.ext.extvar = 'Blah'
        }
    }
}

```
**root build.gradle:**
```
subprojects {
	println extvar
}
```

### Your Environment

 Should be easily reproducible with the sample code above.

**Comment by oehme** [comment]
I haven't investigated why this no longer works yet, but you don't have to wrap this in a projectsLoaded hook, because the rootProject hook is already lazy:

**Comment by john3300** [comment]
Removing the projectsLoaded hook eliminates this issue for me.  Obviously there is still some problem happening here, but this is an acceptable workaround for my purposes.  I'll leave it up to you if you want to close this or keep investigating it.  Thanks Stefan!

**Comment by oehme** [comment]
We'll definitely investigate, since this change in behavior was unintended. But I'm glad it works for you!

**Comment by blindpirate** [comment]
Potentially related to #2794 , investigating.

**Comment by blindpirate** [comment]
@oehme It's a very interesting issue! I can't wait to share my discovery.

This issue only occurs in `4.0` and `4.1`, but doesn't occur in `4.2`. Looks weird? Let's see this line first:

https://github.com/gradle/gradle/blob/f2a436204a281916b0388c113e7856b246654e38/subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java#L212

When invoking `rootProject()`, the project loading status will be checked. If the rootProject has been loaded, the action(closure) would be executed immediately, otherwise  it would be stored to be called in the future. How can we know if the rootProject has been loaded? It's in this line:

https://github.com/gradle/gradle/blob/cf92d02d594ec4d77dd6caf8aef0a505e6185b90/subprojects/core/src/main/java/org/gradle/invocation/DefaultGradle.java#L86

After the rootProject is loaded, the `rootProjectActions` will be set to `null`. However, this line doesn't consider the scenario where `rootProject` is called during `projectsLoaded()` method. In this scenario, the flow won't go into `if (!rootProjectActions.isEmpty())`, so the closure passed to `rootProject()` will be stored and never be executed. This `if` block is added in April, 2017: https://github.com/gradle/gradle/commit/cf92d02d594ec4d77dd6caf8aef0a505e6185b90#diff-37d652fb27f68b3f913dfa14b64f0e8fR85

Then why it doesn't happen in `4.2`? It's a coincidence. On Aug 24, 2017, an extra action was added to the `rootProjectActions`: https://github.com/gradle/gradle/commit/c3e336da7a3c285c8318adc23697ef649b525b6d#diff-8eca81de9e9d3a34f91a3ca4a64ea8f3R54

Thus the `if (!rootProjectActions.isEmpty())` takes effect, and the closure can be executed immediately.

We should take the scenario into account and make a more robust mechanism.

**Comment by oehme** [comment]
Thank you for this detailed analysis @blindpirate! With this information it should be relatively easy to fix. Let's consider this for the next sprint.
