### ISSUE TITLE
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file

### ISSUE THREAD

**Issue by wing328** [gradle/gradle#28940]
### Current Behavior

Hi all,

After updating jackson dependencies to newer versions, I got the following errors when using gradle to build the sub-module:

> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /home/runner/work/openapi-generator/openapi-generator/modules/openapi-generator-gradle-plugin/build/tmp/test/work/.gradle-test-kit/caches/jars-9/f192844ff5e46011454afb1bec1f3df0/jackson-core-2.16.2.jar.

ref: https://github.com/OpenAPITools/openapi-generator/actions/runs/8777643993/job/24082885723?pr=18300

Updated to the latest Gradle version (7.6.4, 8.7) but still got the same error.

Is there anyway to workaround the issue?

Thanks,
William
 

### Expected Behavior

The build is successful (no error)

### Steps to Reproduce

git clone --depth 1 https://github.com/openAPITools/openapi-generator -b update-parser2
cd openapi-generator/modules/openapi-generator-gradle-plugin
./gradlew build

### Gradle version

7.6.4, 8.7

### Your Environment (optional)

Windows, Linux

**Comment by ov7a** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Can you please provide a minimal isolated reproducer, please? For example, by extracting your test into a small gradle build.

**Comment by wing328** [comment]
@ov7a thanks for the response.

Have you tried the following to reproduce the issue?

```
git clone --depth 1 https://github.com/openAPITools/openapi-generator -b update-parser2
cd openapi-generator/modules/openapi-generator-gradle-plugin
./gradlew build
```

**Comment by ov7a** [comment]
@wing328 For the big project, there's a GH action run, so it's fine. 

But to address the issue, it would be hard to debug since it's a large project and it's run from Maven. Too many moving parts.
