### ISSUE TITLE
Set applicationDefaultJvmArgs default value to stdout.encoding=UTF-8 on Windows

### ISSUE THREAD

**Issue by cypher256** [gradle/gradle#28959]
### Current Behavior

In JEP 400, since Java 18, `file.encoding` on Windows is now UTF-8. However, stdout and stderr remain Windows locale dependent, so running the Application plugin will result in garbled characters regardless of the chcp setting.

### Expected Behavior

To address this issue, `stdout.encoding` and `stderr.encoding` have been officially added to the JDK since Java 19. The expected default values for JVM arguments in the Application plugin are.
```gradle
application {
    applicationDefaultJvmArgs = ['-Dstdout.encoding=UTF-8', '-Dstderr.encoding=UTF-8']
}
```

### Context

Prior to Java 19, `stdout.encoding` and `stderr.encoding` do not exist, so there is no effect on older versions.

**Related Issues**
#29356 Consider Setting Console CP to UTF-8 on Windows to enable UTF-8 Console Output
#19235 Unicode Encoding Problems on Windows
#19952 Application plugin should set terminal codepage and file.encoding to UTF-8 by default on Windows
#20267 JDK 18 System.out Encoding Problems

### Steps to Reproduce
Java 21, Gradle 8.7, Source Code Encoding: UTF-8
```java
// src/main/java/demo/App.java
package demo;
public class App {
    public static void main(String... args) {
        System.out.println("👍Java Code");
    }
}
```
```gradle
// build.gradle
plugins {
    id 'application'
}
java.toolchain.languageVersion = JavaLanguageVersion.of(21)
repositories.mavenCentral()
application {
    mainClass = 'demo.App'
    //applicationDefaultJvmArgs = ['-Dstdout.encoding=UTF-8', '-Dstderr.encoding=UTF-8']
}
println '👍Gradle Code'
```
```bat
:: Windows Command Prompt
gradle run
:: IBM437 OEM United States Default
chcp 437
gradle run
:: UTF-8
chcp 65001
gradle run
```

**Comment by cypher256** [comment]
If it is difficult to set the default value of `applicationDefaultJvmArgs` to `-Dstdout.encoding=UTF-8 -Dstderr...`, I think it would be useful to be able to pass `applicationDefaultJvmArgs` as an argument to `gradle run` as a system property. 

I know that I can set the environment variable `JAVA_TOOL_OPTIONS` to something like `stdout.encoding`, but I would like to avoid it as it has a big impact on other projects.

**Comment by ov7a** [comment]
The issue is in the backlog of the relevant team and is prioritized by them.

***

Note: when fixing that issue, make sure other issues referenced fixed as well.

**Comment by cpupg** [comment]
> The issue is in the backlog of the relevant team and is prioritized by them.
> 
> Note: when fixing that issue, make sure other issues referenced fixed as well.

I was following a tutorial on gradle, using version 8.7, when I ran into this problem and couldn't fix it for a long time. The official website says to add a gradle.properties to the root of the project and configure `org.gradle.jvmargs=-Dfile.encoding=UTF-8`. I tried, it didn't work, i also add below in `build.gradle` but also ditnt work:
```grovvy
tasks.withType(JavaCompile) {
options.encoding = "UTF-8"
}
```

As a developer, I don't think a build tool that takes a lot of time to learn or solve problems is a good tool. Students can use this time to learn the most currently used spirng, and enterprise developers and framework developers can use this time to optimize code or develop new features. If the developer is an Android developer, you might want to work on gradle before you write hello world.

As a developer, I don't think a build tool that takes a lot of time to learn is a good tool. Students can use this time to learn the most current spirng, enterprise developers and framework developers can use this time to optimize business code, or to develop new features, if the developer is an Android developer, may want to solve gradle problems before writing hello world.

Most projects still use maven as a build tool, even though maven's xml is very verbose, even if you configure the jdk version, you need to write several lines of xml, and in order to implement complex functions, plugins take up a lot of space. Developers using long-winded maven can quickly write their first demo, while developers using gradle are probably still figuring out how to make gradlew build bug free at this point.

**Comment by cypher256** [comment]
```gradle
application {
    applicationDefaultJvmArgs = ['-Dstdout.encoding=UTF-8', '-Dstderr.encoding=UTF-8']
}
```
Alternative to the above
```gradle
tasks.withType(JavaExec) {
	jvmArgs += '-Dstdout.encoding=UTF-8'
	jvmArgs += '-Dstderr.encoding=UTF-8'
}
```

**Comment by big-guy** [comment]
For the Gradle wrapper, we could enforce stdout/stderr encoding to utf-8, if we could guarantee all utf-8 output from all builds, but I don't think this is always the case. 

Gradle's a generic build tool and different applications built with Gradle may want utf-8 or not.  They can set the default in their build as necessary.
