### ISSUE TITLE
Poor performance of SourceDistributionProvider on the cold start

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#28986]
### Current Behavior

Execution of actions inside Cold Gradle Daemon in IDEA takes 6.6 seconds 

### Expected Behavior

Execution of actions inside Cold Gradle Daemon in IDEA takes 5 seconds 

### Context (optional)

Investigated log reload of a tine project on a Windows machine.

The telemetry shows that a lot of time is spent inside the `KotlinDslScriptModelProvider`

Attached snapshot shows that 1.7 seconds are spent by Gradle code in `KotlinDslScriptsModelBuilder` to resolve the readily available (downloaded and unpacked) sources. 

This seems unnecessary.

OpenTelemetry: <img width="300" alt="image" src="https://github.com/gradle/gradle/assets/539027/b514e359-059a-4304-bf65-0fed01adf579">

Zipped JFR: [GradleDaemon_2024_04_26_200508.zip](https://github.com/gradle/gradle/files/15134384/GradleDaemon_2024_04_26_200508.zip)

### Steps to Reproduce

Get the attached project, open and sync it in the IDEA. 
Stop the running Gradle daemon.
Execute sync once again.

### Gradle version

8.2

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

**Comment by eskatos** [comment]
The way the Gradle distro is turned into usable source directories for the IDE is by using two artifact transforms.
The first one unzips the distro, the second one selects the relevant directories from it.

These transforms are cached locally. Gradle needs to snapshot their inputs and outputs in order to have a cache hit.
The output of the first transform is the directory of the unpacked distribution.
The input to the second transform is the same.
The outputs of the second transform are all relevant source directories.
This is a lot of files and would explain why it takes a while on Windows' poor i/o.

Could you please provide a build scan of your observation?
They now contain insights on transforms that could help confirm that theory.

In any case we should rework this transformation pipeline. Merging the two transforms should greatly reduce the overhead.

**Comment by nskvortsov** [comment]
This is the part of JFR in question. Please note this is the `Wall time` (not CPU)
![image](https://github.com/gradle/gradle/assets/539027/335708d9-393a-4833-a065-9c54a3dfc1b3)

I will do the build scan shortly

**Comment by nskvortsov** [comment]
Unfortunately, I am unable to do the build scan. 
I need to configure the ToS agreement in a build script (as sync is non-interactive).

But the `develocity` plugin fails with the following error (tried Gradle 8.2, 8.4 and 8.7):

```
Build file 'C:\Users\Nikita.Skvortsov\tmp\untitled\build.gradle.kts' line: 1

An exception occurred applying plugin request [id: 'com.gradle.develocity', version: '3.17.3']
> Failed to apply plugin class 'com.gradle.scan.plugin.BuildScanPlugin'.
   > The build scan plugin is not compatible with Gradle 6.0 and later.
     Please use the Develocity plugin instead.
````

**Comment by nskvortsov** [comment]
will take a look, thank you!

**Comment by nskvortsov** [comment]
I can confirm the improvements. In my test environment it shows improvement from ~1600 ms to ~600 ms. Thank you!
