### ISSUE TITLE
GradleRunner withEnvironment() behaves differently in 8.8-rc-1

### ISSUE THREAD

**Issue by staktrace** [gradle/gradle#29000]
### Current Behavior

Setting `GradleRunner.withEnvironment` in a test for a gradle plugin seems to not set the environment variable for the gradle execution.

### Expected Behavior

It should set the environment variable during the gradle execution as it did in 8.7 and previous versions

### Context (optional)

We have a custom gradle plugin, and one of the tests for the plugin fails when run with gradle 8.8-rc-1.

### Steps to Reproduce

https://github.com/staktrace/20240429-gradle-88rc1-envvar contains a minimal reproducible test case. Follow instructions in the README

### Gradle version

8.8-rc-1

### Gradle version that used to work

8.7

### Build scan URL (optional)

https://scans.gradle.com/s/qt7d3u5jb4ywk/tests/overview

**Comment by asodja** [comment]
This is an interesting consequence of fixing `org.gradle.native` handling. 

Before Gradle ignored `org.gradle.native` flag, which was basically a bug. That was fixed with https://github.com/gradle/gradle/pull/28021 in 8.8. Unfortunately our ForkingTestClassProcessor had also a performance optimization that disabed loading native services in workers, and it did that by setting `org.gradle.native=false`: that system property is not set anymore with https://github.com/gradle/gradle/issues/28401. 
That worked fine before with Gradle <= 8.7, since Gradle <= 8.7 just ignored `org.gradle.native` flag.

So now if you use Gradle 8.7 wrapper that still sets `org.gradle.native=false` system and you test Gradle 8.8-rc-1, 8.8-rc-1 build will correctly handle that flag and disable the native services ->  so env. variables won't be passed in the build.

To fix that one of these options will work:
1. Use Gradle 8.8-rc-1 wrapper
2. Or do `System.clearProperty("org.gradle.native")` somewhere at the start of your test 
3. Or do `System.setProperty("org.gradle.native", "true")` somewhere at the start of your test
4. Or in your build script do 
```
tasks.withType<Test>().configureEach {
  systemProperty("org.gradle.native", true)
}
```

**Comment by staktrace** [comment]
Ah thank you for the explanation, that makes sense! For now we will set the property and presumably once we upgrade our main gradle version to 8.8 we can take it back out.

**Comment by asodja** [comment]
Fixed with https://github.com/gradle/gradle/pull/29218, we reverted the behaviour of `org.gradle.native` flag.

I also tested `withEnvironment(Map.of("FOO","")` example and it seems empty value is passed to the process.
