### ISSUE TITLE
javaToolchains incorrectly reports 'does not contain a java executable' on Debian and Ubuntu

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#29062]
### Current Behavior

Noisy warnings appear before correct toolchains are printed:
```
Path for java installation '/usr/lib/jvm/openjdk-11' (Common Linux Locations) does not contain a java executable
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable

> Task :javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Disabled

 + Private Build JDK 17.0.10+7-Ubuntu-123.10.1
     | Location:           /usr/lib/jvm/java-17-openjdk-amd64
```

### Expected Behavior

Only useful information is printed:
```
> Task :javaToolchains

 + Options
     | Auto-detection:     Enabled
     | Auto-download:      Disabled

 + Private Build JDK 17.0.10+7-Ubuntu-123.10.1
     | Location:           /usr/lib/jvm/java-17-openjdk-amd64
```

### Context (optional)

But this bugs **will affect any Debian-based system** where Java is installed using apt-get. This is because how OpenJDK package is constructed by Debian.

I will demonstrate what is **wrong with the current logic in Gradle**. Go to https://packages.debian.org/bullseye/openjdk-17-jdk and download the package:
```
% dpkg -c openjdk-17-jdk_17.0.11+9-1\~deb11u1_amd64.deb | grep 'lib/jvm/'
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/bin/
-rwxr-xr-x root/root     14392 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/bin/jconsole
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/include/
-rw-r--r-- root/root     12458 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/include/jawt.h
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/include/linux/
-rw-r--r-- root/root      1965 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/include/linux/jawt_md.h
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/man/
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/man/man1/
-rw-r--r-- root/root      1622 2024-04-22 10:53 ./usr/lib/jvm/java-17-openjdk-amd64/man/man1/jconsole.1.gz
drwxr-xr-x root/root         0 2024-04-22 10:53 ./usr/lib/jvm/openjdk-17/
lrwxrwxrwx root/root         0 2024-04-22 10:53 ./usr/lib/jvm/openjdk-17/src.zip -> lib/src.zip
```

The package creates `/usr/lib/jvm/openjdk-17/` but it creates it just to add a symlink to sources, and nothing else inside.

This warning:
```
Path for java installation '/usr/lib/jvm/openjdk-17' (Common Linux Locations) does not contain a java executable
```
should never be printed by Gradle. Because it's incorrect for Gradle to even look inside '/usr/lib/jvm/openjdk-17'. I don't know where the idea that this directory is supposed to contain any executable comes from.

Warnings are printed for users to take action. Here, it's not user's fault that this directory does not contain an executable. **The fault is on Gradle side.** The directory is fine. The only problem is that Gradle takes a look into a place it should not look for.  So no warning should be presented.

Similar report is in #22921 but the issue is closed despite the problem still appearing.

### Steps to Reproduce

Execute `touch settings.gradle.kts && gradle javaToolchains` on Debian or Ubuntu.

### Gradle version

8.7

### Your Environment (optional)

My local machine: Ubuntu 23.10

**Comment by Karmavil** [comment]
I know it is frustrating, and sorry for an extended answer..

Let's change the abstraction about what this is telling us instead of proving the software is wrong.
The message is actually right, that path does not contain an executable.
Looks like this situation has been created deliberately.

Please use a local JDK not a system-wide. If your system leaves behind a particular version you will have to do it anyway (download a local jdk).

Your java executable is available through the PATH environment, but given the message what the resolver is trying to use is the full path to the java home folder and openjdk-17 does not have it. So these are your options:

a) Set JAVA_HOME env variable to some of the paths where `javaToolchains` is telling you it has found what it needs.
    There are other options .. like setting `org.gradle.java.home` in a gradle.properties file in either:
      b) your GRADLE_USER_HOME
      c) In the root folder of you project . ([Read the documentation](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties))
      d) ...
They will override each other so read the docs.

Note: Currently, **_b_** and **_c_** are failing in my environment (that is what I'm here, to report a bug)
Also **_d_** is failing but let's just say that is lack of skills :) I don't want to push.. I'm using 8.7 while the system-wide version is 4.4.1 and I should check the documentation because I'm not sure if that version knows that setting

**Comment by pkubowicz** [comment]
Maybe the 'warning' should be moved to info-level logs?

In the standard situation, the message does not give an end user any useful advice – so should not be visible by default. But info level is quite verbose, it's fine to have this message there.

Changing the log level is easier than tweaking the logic, but while being easy, still will improve user experience.

**Comment by Karmavil** [comment]
Hmm its relevance? sure, but... 
I wouldn't downplay the importance of this issue in terms of the performance hit when using the resolver. 
I'm trying to understand if it's being used every time a task is executed, because it shouldn't .. unless the daemon is down. But even then, while using Gradle in development changes are we are specifying which path to use so in those cases a resolver doesn't seem optimal. Again, unless there is no daemon available.

I just raised this question on Slack as I'm trying to review the flow to understand if this is a mistake on my part (concepts, workflow, something else), or otherwise ask if doing so is really necessary.
I'm not confidence on getting an answer from it because the thread has become long/dense, full of outputs and observations, so I doubt someone will follow to last/recent replies there.

**Comment by Karmavil** [comment]
Alright,  I found a different workaround . 
I has some tests not very much. 

I'm using *gradle.properties* to set
`org.gradle.java.installations.auto-detect=false` 
[docs/reference](https://docs.gradle.org/current/userguide/toolchains.html#sub:disable_auto_detect)

That seems to work (avoid the toolchain auto discovery part) but it still download a particular JDK if it is required and it doesn't exist among the available JDKs

So it's a project or user level, I think I will set it to _**$HOME/.gradle/gradle.properties**_ so I don't see this problem anymore

I will update if I found any downside

**Comment by ljacomet** [comment]
This has been fixed through #28311  and will be released with Gradle 8.8.

You can try 8.8 RC1 to validate this already. Report back here if there is still an issue.

**Comment by pkubowicz** [comment]
8.8 RC1 works fine, thanks!

**Comment by philippludwig** [comment]
This is again broken with gradle 8.12. Compiling a project on debian stable is not possible.
