### ISSUE TITLE
Simplify writing custom interceptors for upgraded properties

### ISSUE THREAD

**Issue by asodja** [gradle/gradle#29363]
For custom interception we should simplify the whole process. Right now developer needs to know in details how interception annotation tool works. We should try to simplify that.

Developer should be able to define interceptor just as:
```
class AbstractDependencyReportTask {
    @ReplacesEagerProperty(adaptor = ConfigurationInterceptors.class)
    public abstract SetProperty<String> getConfigurations();
}

@Deprecated
@BytecodeUpgradeAdaptor
public static class ConfigurationInterceptors {
    @BytecodeUpgrade
    static Set<Configuration> getConfigurations(
        AbstractDependencyReportTask thiz
    ) {
        // Code...
    }

    @BytecodeUpgrade
    static void setConfigurations(
        AbstractDependencyReportTask thiz,
        Set<Configuration> configurations
    ) {
        // Code...
    }
}
```

We should recognize setters and getters and also take care of binary changes.
We should also make sure a class is marked as `@Deprecated` so users won't use it directly.

**Comment by lptr** [comment]
I've been thinking about this a bit, and I'd like to make a few changes:

- Let's call the class `${UpgradedPropertyName}PropertyAdaptor`; we'll need one for each custom-upgraded property.
- Make the adaptor a `static` inner-class of the upgraded task or extension type. This adds a bit of noise, but we can put it at the end of the class.
- Make the adaptor class package-private. We don't need the adaptor to be part of the public API, and if we put the generated code in the same package, it can access the adaptor class just fine -- we already agreed to make the methods package-private anyway.
- If we make the adaptor class package-private, there's no need to mark it as `@Deprecated` either.
- I'd lose the `@BytecodeUpgradeAdaptor` annotation. It's main function was to mark the class as an entry-point for IntelliJ's / ErrorProne's unused detection, but we'll be referring to it from the `@ReplacesEagerProperty` annotation, so it's not needed.

Here's how I think the resulting code should look like:

```java
public class AbstractDependencyReportTask extends ... {

    // ...

    static class ConfigurationsPropertyAdaptor {
        @BytecodeUpgrade
        static Set<Configuration> getConfigurations(AbstractDependencyReportTask thiz) {
            return thiz.getConfigurations()
                .map(configurations -> configurations.stream()
                    .map(configurationName -> ConfigurationFinder.find(thiz.getProject().getConfigurations(), configurationName))
                    .collect(ImmutableSet.toImmutableSet()))
                .get();
        }
    
        @BytecodeUpgrade
        static void setConfigurations(AbstractDependencyReportTask thiz, Set<Configuration> configurations) {
            thiz.getConfigurations().set(configurations.stream()
                    .map(Configuration::getName)
                .collect(ImmutableSet.toImmutableSet()));
        }
    }
}
```

**Comment by lptr** [comment]
How about this terminology?

- the "call-site" is the class that has the call with the old semantics that we want to upgrade
- the "source class" had the old API we want to upgrade (we can call it the "source API"); in the typical case the source and target classes are the same
- the "target class" has the new we API want to upgrade to (we can call it the "target API")
- the "adaptor" is the class that describes how the intercepted source behavior is to be _adapted_ to the target behavior
- there is also a generated "bridge" class that delegates to the "adaptor"

In the above example `AbstractDependencyReportTask` is both the "source" and the "target" class, with the new `SetProperty<String> getConfigurations()` method being the "target API," while "void setConfigurations(Set<Configuration>)` is the "source API." The "adaptor" is `ConfigurationsPropertyAdaptor`. The "call-site" is the user code that calls `setConfigurations()` that we are upgrading.

Because the "call-site" can be in any package, we can only inject replacement code that calls `public` APIs. However, we don't want the "adaptor" class or its methods to be part of the public API, because then it would add noise to auto-completion etc. Instead we keep them package-private, and add a generated `public` "bridge" type in the target package whose only job is to bridge the `public`-private barrier.

The decorator for `ConfigurationsPropertyAdaptor` looks like this:

```java
package org.gradle.api.tasks.diagnostics; // Same as the "target" class

@Generated
public class $$BridgeFor$$ConfigurationsPropertyAdaptor {
    public static Set<Configuration> getConfigurations(AbstractDependencyReportTask thiz) {
        return AbstractDependencyReportTask.ConfigurationsPropertyAdaptor.getConfigurations(thiz);
    }

    public static void setConfigurations(AbstractDependencyReportTask thiz, Set<Configuration> configurations) {
        AbstractDependencyReportTask.ConfigurationsPropertyAdaptor.setConfigurations(thiz, configurations);
    }
}
```

By using the `$$BridgeFor$$` prefix we make sure that even though the class is `public`, it will not pop up in auto-completion in the IDE unless the user explicitly looks for it.

Later, when we start to compile build logic against a published API JAR, we can omit these generated classes from the API JAR, and hence make them completely invisible to the compiler and IDEs.
