### ISSUE TITLE
java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file

### ISSUE THREAD

**Issue by jdeppe-pivotal** [gradle/gradle#29381]
### Current Behavior

After adding the JReleaser plugin, my build always fails with:
```
./gradlew clean

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gemfire-testcontainers'.
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file /Users/jdeppe/.gradle/caches/jars-9/4f807ddc79a2da43fe67c92ec0327351/jackson-core-2.17.0.jar.
```

### Expected Behavior

Gradle shouldn't just die with an exception - I'd at least like to see if there is an error with my build script.

### Context (optional)

This is the same issue as https://github.com/gradle/gradle/issues/28940

### Steps to Reproduce

I have a branch where I've made changes to my build here - https://github.com/gemfire/gemfire-testcontainers/commit/fe45ea9b694b2e2f6f6ea7e83a50dd884e9b862a

Simply running `./gradlew clean` should reproduce.

I've tried running with both JDK 1.8 and 11 with the same results.

### Gradle version

7.5.1

### Your Environment (optional)

Running on a M1 Macbook with Sonoma 14.5.

**Comment by mlopatkin** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

It would be better to at least have a full stacktrace (you need to run the build with `--stacktrace` to get that), but most likely you're hitting #27156. Upgrading Gradle to 7.6.4/8.4 should help in this case.

**Comment by jdeppe-pivotal** [comment]
Thanks! Upgrading to `7.6.4` fixed the issue.

**Comment by kaarthicksiyer** [comment]
Hi
I am facing the same issue on AGP 8.1.1 and Gradle 8.2 with RN version 0.74.0. This is the error I see on my end
> java.util.concurrent.ExecutionException: org.gradle.api.GradleException: Failed to create Jar file 
/.gradle/caches/jars-9/18366b31678c0171857be093a3b8ec22/bcprov-jdk18on-1.79.jar.
