### ISSUE TITLE
Implicit dependency error should not be caused when the implicit task is defined as finalizedBy

### ISSUE THREAD

**Issue by pocorall** [gradle/gradle#29433]
### Current Behavior

# Toy example

EDIT: I made mistake on the original post. I matched this example to the case of the real world problem.

```kotlin
val javaTask by tasks.registering(Copy::class) {
    from("srca")
    into("outtest")
    val st = tasks.named("scalaTask")
    finalizedBy(st)
}

val scalaTask by tasks.registering(Copy::class) {
    from("srcb")
    into("outtest")
    dependsOn(javaTask)
}

val androidTask by tasks.registering(Copy::class)  {
    from("outtest")
    into("target")
    dependsOn(javaTask)
    // if I add dependsOn(scalaTask) here, there will be no error. However, there is a problem in real world setting.
}
```
`gradle androidTask` cuases the error below

```
A problem was found with the configuration of task ':androidTask' (type 'Copy').
  - Gradle detected a problem with the following location: 'C:\java\workspace\gradle-test\outtest'.
    
    Reason: Task ':androidTask' uses this output of task ':javaTask' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':javaTask' as an input of ':androidTask'.
      2. Declare an explicit dependency on ':javaTask' from ':androidTask' using Task#dependsOn.
      3. Declare an explicit dependency on ':javaTask' from ':androidTask' using Task#mustRunAfter.
    
```

# Real world problem

The same problem happened when I wrote [a Gradle plugin to add Scala language support for Android](https://github.com/onsqcorp/scala-android-plugin). 
`javaTask` is equivalent to compiling Java, which is provided by Gradle, `scalaTask` is equivalent to compiling Scala, which is written my me, and `androidTask` is equivalent to the Android building tasks written by Android Build tool developers. Only `scalaTask` is able to controlled by me. The biggest problem in this situation is that the number of tasks equivalent to `androidTask` is undetermined. As the Android Gradle plugin evolves, number of tasks equivalent to `androidTask` is increased, and it breaks build for my Android app. As a workaround, I added `androidTask.dependsOn(scalaTask)` for all relevant tasks in Android Gradle plugin, [as shown here](https://github.com/onsqcorp/scala-android-plugin/blob/bd7d4f701d6f27db772b603676fe6b5f8ef6578d/src/main/java/com/soundcorset/scala/android/plugin/ScalaAndroidPlugin.java#L220). Up to now, I added `dependsOn` for 6 Android tasks, and I need to add more of it whenever new Android Gradle plugin releases, this causes maintainance burden to my plugin.

Because [scalaTask depends on javaTask](https://github.com/onsqcorp/scala-android-plugin/blob/bd7d4f701d6f27db772b603676fe6b5f8ef6578d/src/main/java/com/soundcorset/scala/android/plugin/ScalaAndroidPlugin.java#L153), javaTask cannot depends on scalatask. [javaTask only allowed to be finalizedBy scalaTask](https://github.com/onsqcorp/scala-android-plugin/blob/bd7d4f701d6f27db772b603676fe6b5f8ef6578d/src/main/java/com/soundcorset/scala/android/plugin/ScalaAndroidPlugin.java#L218).

### Expected Behavior

As `scalaTask` always finished before any other Android tasks depending on `javaTask`, the implicit dependency exception should not be caused.

### Steps to Reproduce

It is provided in the `Toy example` section.

### Gradle version

8.7

**Comment by ljacomet** [comment]
Could you review the following elements and possible update your report:

* That `outtest` folder is what we call an [overlaping output](https://docs.gradle.org/current/userguide/build_cache_concepts.html#concepts_overlapping_outputs). Is that a typo or part of your design? If the later, then this should be fixed first before digging deeper into the issue here.
* Having `scalaTask` `finalizedBy` `javaTask` does not mean that Gradle cannot run `androidTask` before `javaTask` since there are no relations between these two.


Can you explain the _real_ problem better?
What are the real inputs of `androidTask`?
How does the `scalaTask` contribute things there?

It is quite likely that you should look into `SourceSet` and how tasks consume [their `output`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html#org.gradle.api.tasks.SourceSet:output).

**Comment by pocorall** [comment]
I found a mistake on the Toy example above. I am sorry. Now I fixed it to match the real project I have.

**Comment by pocorall** [comment]
Why can't I have a setting to suppress this error, and let Gradle to automatically wire `dependsOn` for me? This automation will save much of the my chore.

**Comment by ljacomet** [comment]
> or I don't know how to avoid it in my case

Did you look into `SourceSet` and [their `output`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.SourceSet.html#org.gradle.api.tasks.SourceSet:output)?

This looks like there is no bug or missing feature in Gradle so far. We will not support overlapping outputs. It looks like this question should be dicussed with the Android Gradle Plugin team to see how best to support the integration of an additional language if their tasks does not support it. But since they have Java and Kotlin, I would be surprised it does not.

**Comment by pocorall** [comment]
OK. I will take look into it. Thank you for your time.
