### ISSUE TITLE
Update Working with Dependencies -> Learning the Basics section of User Manual

### ISSUE THREAD

**Issue by lkasso** [gradle/gradle#29580]
### Details
This is a Documentation change ONLY.

### Context
Update the first two sections of "Working with Dependencies":

1. Move [Terminology](https://docs.gradle.org/current/userguide/dependency_management_terminology.html) page to Glossary page
2. Update [Learning the Basics](https://docs.gradle.org/current/userguide/core_dependency_management.html):

| Page  | Section | Note |
| ------------- | ------------- | ------------- |
| Getting Started  | -------------  | Replaces [What is Dependency Management?](https://docs.gradle.org/current/userguide/core_dependency_management.html) with a summary of the following pages -> similar to other [Getting Started](https://docs.gradle.org/current/userguide/getting_started_eng.html) pages |
| 1. Declaring Dependencies  | -------------  | Existing page |
|   | [Understanding producers vs consumers](https://docs.gradle.org/current/userguide/library_vs_application.html#sub:producers-vs-consumers) | Existing page, this will be a condensed version |
|   | Adding a dependency  | New section that talks about the `dependencies{}` block + example |
|   | [Understanding types of dependencies](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:dependency-types) | Existing section, cleaned up - talked about module v file dependencies |
|   | Looking at an example | New section, example code|
|   | [Listing Project Dependencies](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html#sec:listing_dependencies) | Existing section, cleaned up - using `dependencies` task |
| 2. Dependency Configurations  | -------------  |  New page that includes content currently in [Declaring Dependencies](https://docs.gradle.org/current/userguide/declaring_dependencies.html)  |
|   |  [Understanding dependency configurations](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:what-are-dependency-configurations) | Existing section, cleaned up - what is `implementation`? |
|   |  Viewing configurations |  New section that uses tasks like `./gradlew :docs:dependencies —configuration=compileClasspath`, uses items from [Viewing Dependencies](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html) |
| 3. Declaring Repositories  | -------------  | Existing page |
|   | [Declaring a publicly repository](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring_public_repository)  | Existing section, cleaned up - about `repositories {}` block and google() |
|   | [Declaring a custom repository](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:declaring_custom_repository) | Existing section, cleaned up - maven{} and ivy{} and a custom URL |
|   | Declaring a local repositories | New section and a re-do of [The case for mavenLocal()](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:case-for-maven-local)  |
|   | [Understanding supported repository types](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-types) | Existing section, cleaned up - maven+ivy+flat dirs + authentication |
| 4. Centralizing Dependencies  | ------------- | New page  |
|   | Using platform | New section explaining platforms  |
|   | Using a version catalog | New section describing the version catalog  |
| 5. Dependency Constraints and Conflict Resolution | ------------- |  New page |
|   | [Understanding how Gradle handles conflicts](https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:conflict-resolution) | Existing section, cleaned up - explain types of conflicts |
|  | [Resolving version conflicts](https://docs.gradle.org/current/userguide/dependency_resolution.html#sec:version-conflict) | Existing section, cleaned up  - explain resolution strategy |

**Comment by Vampire** [comment]
@lkasso what happened to "re-do of The case for mavenLocal()"?
I do not find it anymore, but it contains very important information I often refer other users to.

**Comment by lkasso** [comment]
> [@lkasso](https://github.com/lkasso) what happened to "re-do of The case for mavenLocal()"? I do not find it anymore, but it contains very important information I often refer other users to.

Is this what you are looking for?
https://docs.gradle.org/current/userguide/supported_repository_types.html#sec:maven-local

**Comment by Vampire** [comment]
No, it is missing all the reasons why using `mavenLocal()` is an extremely bad idea.
Compare with https://docs.gradle.org/8.9/userguide/declaring_repositories.html#sec:case-for-maven-local

**Comment by lkasso** [comment]
Good point. I made a very succinct version of the old docs -> i.e, Don't use it!
I'm happy to put this section back if you want.

**Comment by Vampire** [comment]
I'd welcome that, yes. :-)
"You should ensure that using the local Maven repository is necessary" is really very succinct and I think it is important to make it really extra clear why it is a bad idea to use it and what drawbacks you earn for using it and that you should at least use a repository content filter and put it to last position in the list.

**Comment by lkasso** [comment]
> [@lkasso](https://github.com/lkasso) also the information about the "simple" way to share things cross-project seems to got lost. Here they (https://docs.gradle.org/8.10/userguide/cross_project_publications.html#simple-sharing-artifacts-between-projects) are still both referenced and shown: https://docs.gradle.org/current/samples/sample_cross_project_output_sharing.html
> 
> But the links since 8.11 forward to a different page that only shows the full-fledged approach.

@Vampire, this was a conscious decision. We don't want users to use the "simple way" to share artifacts across projects; it is bad practice.

**Comment by Vampire** [comment]
Oh, that's news to me.
But then the samples and sample description needs to be cleaned too to not mention it. :-)

Do you mind telling me why?
If you want to just share a file or something from one project to another inside one build,
I always considered this a valid and pragmatic technique I also recommended.
Using full variant-aware sharing seems a bit overkill and contribute to the "Gradle is too complex" mantra some people are stating.

**Comment by jvandort** [comment]
> Using full variant-aware sharing seems a bit overkill and contribute to the "Gradle is too complex" mantra some people are stating.

We definitely agree that full variant aware publishing is cumbersome for more simple use cases, and this is why we haven't completely removed the `targetConfiguration` selection option already. 

The idea of a `configuration` as something that can be selected via dependency resolution is mostly a remnant from back when Gradle's dependency resolution engine literally _was_ Ivy's dependency resolution engine. Things are much different internally now, and the concept of a "configuration" is almost entirely absent from Gradle's dependency resolution implementation.

Today, Gradle's dependency resolution engine is organized in a module/component/variant hierarchy. A module ("com.foo:bar"), has components ("com.foo:bar:1.0"), which themselves have variants ("com.foo:bar:1.0:apiElements"). 

Module are selected based on group/name (and can participate in module conflicts)
Components are selected based on the version requested (and can participate in version conflicts)
Variants are (mostly) selected based on attribute matching (and can participate in capability conflicts)

Using the term "configuration" here in the public API misrepresents the actual structure of a library from dependency resolution's perspective.

Selecting based on configuration name is for the most part legacy in the implementation and at the moment is pretty much patched on. Given this we have decided to stop advertising it in order to attempt to avoid proliferating its use. The days of `targetConfiguration`/the "simple" way of selecting variants is numbered -- though we do acknowledge that there needs to be a simpler model than full-blown attribute matching to replace it. 

Another downside to selecting based on "configuration" is that the variants being selected on (often) lack attributes. Features like artifact transforms and variant reselection rely on attributes being defined in order to be useful and we want to circle in on an API ecosystem that all works together.

Finally, selecting based on "configuration" is yet another way to do things. We would prefer to focus on the variant/attribute pattern, as it is quite prolific in Gradle these days, and make it simpler to use, rather than support two different ways of variant selection.
