### ISSUE TITLE
Ensure work graph is free of cross-project references when parallel CC serialization is enabled

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#29797]
Ensure the work graph is free of cross-project references when [parallel CC serialization](https://github.com/gradle/gradle/issues/27731) is enabled (`--configuration-cache --parallel`), by enabling the same set of constraints on cross-project configuration as enabled by _Isolated Projects_.

**Comment by jvandort** [comment]
Have we thought of using another flag instead of `--parallel`? `--parallel` does some weird stuff like disabling some cross-project locking, among other things I am probably unaware of.

**Comment by mlopatkin** [comment]
> Have we thought of using another flag instead of `--parallel`? `--parallel` does some weird stuff like disabling some cross-project locking, among other things I am probably unaware of.

I don't recall us looking into adding a new flag too much. We were lured by the fact of `--parallel` being available for a while, so the users may have already opted into it. Disabling cross-project locking is exactly what we're after, because we want configurations to be resolved at least as parallel as non-configuration-cached build can.

**Comment by mlopatkin** [comment]
We believe this issue is no longer relevant. Please file a new issue if necessary.

***

While the set of constraint is a subset to IP, maintaining it is going to be a burden. It doesn't look like it pulls its weight.
