### ISSUE TITLE
The window script set CLASSPATH should not traverse all liBs. This causes the command line to be too long and fail to start

### ISSUE THREAD

**Issue by zxuanhong** [gradle/gradle#29819]
### Current Behavior

1. The window script set CLASSPATH should not traverse all liBs. This causes the command line to be too long and fail to start
<img width="1207" alt="image" src="https://github.com/gradle/gradle/assets/62740686/2a52c1dc-8751-4bd0-a116-17e04d9f1ae1">

2. this maven appassembler-maven-plugin script
<img width="653" alt="image" src="https://github.com/gradle/gradle/assets/62740686/f7da4def-3937-488e-90c9-93437082a376">

3. The CLASSPATH script is changed to the path. The classpath script starts normally
<img width="932" alt="image" src="https://github.com/gradle/gradle/assets/62740686/74b9fd4e-40cb-49d7-9b2d-df27deff9217">

### Expected Behavior

Windows can start normally

### Steps to Reproduce

1. Distributing springboot
2. Start-up project

### Gradle version

8.8

**Comment by ov7a** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Screenshots are hard to investigate; please provide a proper reproducer.
Related:
* https://github.com/gradle/gradle/issues/5754
* https://github.com/gradle/gradle/issues/21712
