### ISSUE TITLE
Syntax error obfuscation

### ISSUE THREAD

**Issue by mcandre** [gradle/gradle#29883]
### Expected Behavior

When a Gradle project exhibits fundamental syntax errors, such as using invalid parameter names in `jar { ... }` blocks, then Gradle should report these syntax errors, before attempting network connections to package repositories.

### Current Behavior (optional)

Gradle obfuscates `jar { ... }` syntax errors behind any authentication conflicts with package repositories.

### Context

Show the most important errors first, and fail fast.

While it is true that certain build.gradle syntax cannot be fully analyzed prior to downloading Gradle plugins, there are some additional preliminary syntax checks we can pass over industry standard configuration blocks, such as `jar`. The user deserves more linter-like notices well before heating up the NIC.

**Comment by alllex** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.
