### ISSUE TITLE
gradle.properties not discovered when using -b switch

### ISSUE THREAD

**Issue by Espingo** [gradle/gradle#2997]
### Expected Behavior
If I set `org.gradle.daemon=false` in the _gradle.properties_ in the project build directory and set 
a _GRADLE_USER_HOME_ to the none default value. I expect that gradle start without dameon

### Current Behavior
Today, the org.gradle.daemon set to false seems to not take into account in this context.

### Steps to Reproduce (for bugs)
(On Linux)
```
echo "org.gradle.daemon=false" > <your project build dir>/gradle.properties
gradle -b <your project build dir>/build.gradle -g /tmp/.gradle properties
```
The properties seems to be set in properties:
extract of gradle outputs in stdout:
```
....
org.gradle.daemon: false
....

```
But the gradle build start with this log
`> Starting Daemon`

more details in the attached file (see 687.steps.txt)
[687.zip](https://github.com/gradle/gradle/files/1324364/687.zip)

### Your Environment
* Linux RedHat 7
* JDK 1.8.0_73
* Gradle 4.1 (or 4.2)

**Comment by oehme** [comment]
Please attach a full reproducible example project, otherwise it is hard to tell what the problem is.

**Comment by Espingo** [comment]
Unzip the attached file and follow steps describe in 687.steps.txt
[687.zip](https://github.com/gradle/gradle/files/1324358/687.zip)

**Comment by oehme** [comment]
Thanks for the thorough explanation, I can reproduce the problem. We try to read `gradle.properties` before the exact project directory is known. This is because we try to read the properties before we read the command line configuration, because the command line should take precedence over the properties.

In order to fix this, we'd need to split this up into three steps - First properly discover the layout from the command line config, then read the properties, then apply the rest of the command line config.

See https://github.com/gradle/gradle/blob/b7077b8faa3b1beafff58250fe97fe8881dee3c1/subprojects/launcher/src/main/java/org/gradle/launcher/cli/ParametersConverter.java#L75-L75

Would you be interested in providing a pull request to fix this problem?

**Comment by Espingo** [comment]
Ok I try to do my first pull-request for this project ;-)
