### ISSUE TITLE
Adding a library to a version catalog causes all third party plugin tasks to re-run

### ISSUE THREAD

**Issue by eartle** [gradle/gradle#29998]
### Current Behavior

I have a gradle project with build cache enabled and a version catalog. If I add a new library to my `libs.versions.gradle` and re-run. Any tasks from third party plugins, such as compileKotlin from the kotlin plugin, will re-run. 

### Expected Behavior

I would expect third party plugin tasks to be up-to-date after just a version catalog change.

### Context (optional)

We have a very large Android project where the version catalog changes often. These changes cause almost a full rebuild of the app when switching between branches and is very time consuming.

When this happens, the build analyser in android studio says it's because the class path of the task has changed.

I first discussed this issue over here https://discuss.gradle.org/t/adding-library-to-version-catalog-changes-build-classpath-therefore-invalidates-build-cache/48893 where a workaround was suggested to add all third party plugins to the settings.gradle to take them off the build class path. This works, but I expect has downsides and should probably be addressed within gradle itself.

### Steps to Reproduce

Here I link to a project where you can reproduce the problem by rebuild and adding and remove libraries from the version catalog. The compileKotlin task will re-run after changes.

https://drive.google.com/file/d/16U1m1aIvJNAwzy8kTCWzDaYeRq-NX6Ho/view

### Gradle version

8.8

**Comment by alllex** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

---

As mentioned by @Vampire in the [linked discussion](https://discuss.gradle.org/t/adding-library-to-version-catalog-changes-build-classpath-therefore-invalidates-build-cache/48893/11) (thanks for the thorough research!), this may not be entirely about the version catalog, but rather about the `buildSrc` classpath invalidation.

> The accessors generated from the version catalog are put to the buildSrc classloader.
So doing changes that cause different things to be generated, is like doing any other change in buildSrc, making all 3rd party tasks out-of-date as the runtime classpath changes due to that.

**Comment by illarionov** [comment]
@eartle you might also be interested in this https://github.com/gradle/gradle/issues/26020

**Comment by Vampire** [comment]
I would even say this is an exact duplicate of #26020

**Comment by Vampire** [comment]
And the composite build label here feels wrong

**Comment by eartle** [comment]
I did do a quick search and didn't find that other issue. Yep, I'll close this as a duplicate of #26020. Thanks!

**Comment by ov7a** [comment]
@illarionov @Vampire Thanks for finding a dupe!
