### ISSUE TITLE
Provide a standardised way to apply defaults to an extension

### ISSUE THREAD

**Issue by technoir42** [gradle/gradle#30039]
### Expected Behavior
Theoretical usage with the help of Gradle:

```kotlin
// HasDefaults is provided by Gradle
interface MyPluginExtension : HasDefaults {
    val enabled: Property<Boolean>

    @get:Nested
    val remote: MyNestedExtension // instrumented by Gradle to call initDefaults

    override fun initDefaults() { // called by Gradle
        enabled.convention(false)
    }
}

interface MyNestedExtension : HasDefaults {
    val url: Property<String>
    val timeoutSeconds: Property<Int>

    override fun initDefaults() { // called by Gradle
        timeoutSeconds.convention(60)
    }
}

override fun apply(project: Project) {
    val extension = project.extensions.create("myExtension", MyPluginExtension::class.java)
    // defaults are applied to extension
}
```

### Current Behavior (optional)

I've been using the following pattern throughout dozens of extensions to apply the default values:

```kotlin
// Defined in a common library:
interface HasDefaults {
    fun initDefaults()
}
```

```kotlin
interface MyPluginExtension : HasDefaults {
    val enabled: Property<Boolean>

    @get:Nested
    val remote: MyNestedExtension

    override fun initDefaults() {
        enabled.convention(false)
        remote.initDefaults()
    }
}

interface MyNestedExtension : HasDefaults {
    val url: Property<String>
    val timeoutSeconds: Property<Int>

    override fun initDefaults() {
        timeoutSeconds.convention(60)
    }
}

override fun apply(project: Project) {
    val extension = project.extensions.create("myExtension", MyPluginExtension::class.java)
    extension.initDefaults()
}
```

### Context

Some properties in a custom extension might have default values set by calling `Provider.convention(...)` after the extension has been created. Gradle should provide a standardised way to apply the conventions, including for arbitrarily nested extension properties.

**Comment by ov7a** [comment]
We need more information to understand the request. Could you please provide more context about what you want to achieve?

If we receive a clear use case description, we may be able to suggest a workaround.

This issue will be closed after 7 days unless you provide more information.

***

The expected approach to address that problem is to [apply conventions](https://docs.gradle.org/current/userguide/implementing_gradle_plugins_binary.html#sec:plugin_conventions) from plugin definition. This also applies for pre-compiled script plugins.

If this does not work for you, please provide more context/details to explain why.
