### ISSUE TITLE
Expand PropertyState DSL support

### ISSUE THREAD

**Issue by mdekstrand** [gradle/gradle#3005]
### Expected Behavior
Changing from a classical property to a `PropertyState`-based property in an extension or task implementation should not break build scripts.

### Current Behavior
1.  When changing a property `foo` from `T` to `PropertyState<T>`, the old non-assignment property syntax no longer works:

    ```groovy
    foo value
    ```

    The `foo = value` syntax still works.

2. When `foo` has type `PropertyState<String>`, assigning a `GString` to it does not work:

    ```groovy
    foo = "$buildDir/pizza"
    ````

    fails with the error:

    > Cannot set the value of a property of type java.lang.String using an instance of type org.codehaus.groovy.runtime.GStringImpl

### Context
I am trying to update [LensKit](https://github.com/lenskit/lenskit)'s Gradle plugin to use the documented `PropertyState` mechanism instead of the undocumented convention mappings. These errors cause build scripts for the old plugin to fail.

### Steps to Reproduce (for bugs)
Will follow up with this.

### Your Environment
Gradle 4.2, Java 8, seeing across platforms.

**Comment by bmuschko** [comment]
My personal take on this issue is the following:

1. If you want to support a GString type then the plugin will need to expose a (additional) method that takes a `GString`. Alternatively, the plugin could expose a method that takes an `Object` and then the implementation handles it based on the passed in type.
2. `GString` is a Groovy-type which means if you build a plugin that depends on the type then it can only be used with the Groovy DSL and not the Kotlin DSL.
3. I don't think want to provide any internal conversion of types for `Provider`s and instead leave that up to the plugin implementation.
4. This only worked before as convention mapping took in an `Object` type that was evaluated with the help of a closure or callable. The actual type was determined at runtime based on the return type of the closure/callable. The new API is simply strongly typed.
5. If you as a consumer still want to use a `GString` then you can if though the underlying `PropertyState` takes a `String`. You just have to call `toString()` on it. That might be less convenient but less "magical". At least this statement is from some of our users.

**Comment by bmuschko** [comment]
We had a look at our current state of the implementation again. We already prepared a way to hook into the Groovy DSL behavior in `PropertyInternal`. We could probably enhance the behavior to also cover the `GString` handling. Stay tuned!

**Comment by oehme** [comment]
@lacasseio Is this something you could look into? I think streamlining this would prevent a lot of confusion.

**Comment by big-guy** [comment]
@oehme I don't think we have any plans to get to this soon unless it blocks something in the native stream of work.

I think there are two things asked for here:

1. Supporting the "non-assignment" form of properties with the Provider API.
1. Supporting `GString` with `String` properties.

I don't think we intended to carry the "non-assignment" form of properties over to the Provider API.  We'll be adding some documentation to the Provider API with some recommendations for how to migrate a plugin using plain types to Provider/Property types in 4.4.  I think our advice would be to keep your API the same, deprecate the old methods and re-implement the old methods in terms of the new property (so calling the setter or "non-assignment" method would call the `set` method on the property). 

I think supporting `GString` values with `String` properties is a good idea.  I'm not sure if it makes sense as an eager `GString` -> `String` conversion (when setting the property) or if it makes more sense to treat `GString` as a type of Provider (allows for lazy evaluation). 

Are there any other items that fall under better DSL support?

**Comment by adammurdoch** [comment]
We should bust this into 2 issues. I think we should address both things. For the "non-assignment set the property value DSL"  issue we could either support this in a consistent and cross-cutting way (including for collection types), or we could deprecate this as a DSL thing in all of our types and infrastructure.

**Comment by mdekstrand** [comment]
Separating into 2 issues is fine with me.

Personally, the GString is the most important; if Gradle is deciding to deprecate the non-assignment property assignments, then I can add shim methods that log a deprecation warning to our plugin and move foward. I'm less interested in adding GString shim methods, because that feels like the kind of thing that Groovy is generally supposed to just handle, and the fact that it doesn't in Gradle scripts to me represents a deviation from expected Groovy behavior.

**Comment by ajoberstar** [comment]
Just to renew discussion on this, since it came up in one of my plugins. The other aspect of this issue is that Gradle's decoration is effectively undocumented, but is behavior that people rely on without realizing it.

Having the [Lazy Configuration documentation](https://docs.gradle.org/current/userguide/lazy_configuration.html) merely say the following isn't very helpful:

>  The Groovy Gradle DSL adds convenience methods to make the use of Providers mostly transparent in build scripts. 

2 issues here makes sense (or maybe 3 if you want documentation of the DSL decoration as a separate one). Personally, deprecating non-assignment makes sense to me, there are too many ways to do the same thing. The GString support though seems somewhat critical to an idiomatic Groovy DSL.

**Comment by adammurdoch** [comment]
GString support is fixed in https://github.com/gradle/gradle/pull/6536.
