### ISSUE TITLE
Upgrading from Gradle 8 to Gradle 8.9 causes DirectoryScanner.removeDefaultExclude() to not work properly on macOS.

### ISSUE THREAD

**Issue by Ernest-L** [gradle/gradle#30111]
### Current Behavior

The project configured DirectoryScanner.removeDefaultExclude('**/.gitignore') in setting.gradle. After upgrading from Gradle 8.8 to Gradle 8.9, the "copy" task runs normally under Windows environment, but it prompts the following error on MacBook.
error:
![image](https://github.com/user-attachments/assets/c4761bd7-57f2-47bd-b948-59b2d7e36eb2)

### Expected Behavior

I hope it can run normally on Mac, thank you.

### Steps to Reproduce

Code sample：
build.gradle
task abc{
    doLast {
        copy {
            from fileTree('src/main/dist')
            into("build/test")
        }
    }

}
setting.gradle:
import org.apache.tools.ant.DirectoryScanner
DirectoryScanner.removeDefaultExclude('**/.gitignore')

### Gradle version

8.9

### Your Environment (optional)

cpu: apple m3 pro
os: Sonoma14.5

**Comment by cobexer** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***
I tried your reproducer locally with 8.8, 8.9 and 8.10-rc1 and all of them work properly.

Please investigate your build and provide a reproducer as described above.
