### ISSUE TITLE
Validate parallel configuration with Isolated Projects

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#30117]
Check that Syncing with IDEA does indeed trigger parallel configuration.

**Comment by 6hundreds** [comment]
At the moment of the validation, there was an absence of parallel configuration during sync. IDEA is doing [sequential model building](https://github.com/JetBrains/intellij-community/blob/master/plugins/gradle/tooling-extension-impl/src/com/intellij/gradle/toolingExtension/impl/modelAction/GradleModelFetchAction.java#L274) during sync, what is prevents sync to be parallel.
To overcome this, we decided to force parallel configuration of all project even if any project configuration was requested(by the model building, in case of sync) when `isolatedProjects` enabled. The progress is being tracked [here](https://github.com/gradle/gradle/issues/30206). It's a temporal solution, since the final goal is having parallel and incremental sync.

**Comment by 6hundreds** [comment]
Parallel configuration for sync is forced currently by https://github.com/gradle/gradle/pull/30479
