### ISSUE TITLE
Not displaying fully qualified test class name

### ISSUE THREAD

**Issue by akhilrm** [gradle/gradle#30151]
### Current Behavior

After updating to Gradle 8.8, we notice that the tests does not display fully-qualified class name.

Example:

_ForYouScreenScreenshotTests > forYouScreenPopulatedAndLoading_dark_

<img width="538" alt="Screenshot 2024-08-11 at 1 15 36 PM" src="https://github.com/user-attachments/assets/4cce7c70-b5b2-4102-a2bf-3cb9bf4c08fd">

### Expected Behavior

In Gradle 8.7, the tests used to display fully-qualified class names.

Example:

_com.google.samples.apps.nowinandroid. feature.foryou.ForYouScreenScreenshotTests > forYouScreenPopulatedAndLoading_dark_

<img width="901" alt="Screenshot 2024-08-11 at 1 15 25 PM" src="https://github.com/user-attachments/assets/b2f9c434-4f0d-4cf8-9569-0f351fcacd72">

### Steps to Reproduce

git clone [https://github.com/android/nowinandroid](https://github.com/android/nowinandroid.git)
Run _./gradlew testDemoDebug_ and notice the output on console.
Now upgrade to Gradle 8.8.
Run the _./gradlew testDemoDebug_ command again and notice the output on console.

The issue is observed in 8.9 also.

### Gradle version

8.8

### Gradle version that used to work

8.7

**Comment by ov7a** [comment]
This is the expected outcome of 
* https://github.com/gradle/gradle/issues/24538
Note that the behavior for JUnit4 and JUnit5 was different - Junit4 had an FQN class name in the output, while JUnit5 (and JUnit4 test with Vintage engine) had a simple class name.

Note that this output is supposed to be for humans and not to be parsed. You can use test reports and tooling API integration to extract FQN. Alternatively, you can use a custom `TestListener` in the`testLogging` block or `DisplayName` feature in JUnit5 to customize the displayed class name. 

If you depend on the exact output, please share more details on why it's important to you. Otherwise, this issue will be closed in 7 days.
