### ISSUE TITLE
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 66

### ISSUE THREAD

**Issue by SaveliiLisnichenko** [gradle/gradle#30268]
### Current Behavior

When I try to run `gradlew build` it just spits out the error in the title. When I tried to upgrade to Gradle 8.8 since that version is compatible with Java 22 (which I'm using) it just tries to build it again and gives me the same error.

### Expected Behavior

I expected for the `gradlew build` command to just succeed at its' task, as it did in the previous project which I deleted because I needed to restart from scratch.

### Context (optional)

I am trying to make a forge Minecraft mod, and I need to run `gradlew build` to run `gradlew runClient` to test if my mod at least imports. And if `gradlew build` doesn't succeed, I can't run `gradlew runClient`.

### Steps to Reproduce

1. Start a new Java project in IntelliJ
2. Import forge's mod development kit into the directory
3. Change a bit of the details (i.e. mod_id, mod_id_group) in the gradle.properties file
4. Create a new folder/folder path matching mod_id_group, drag config into it, and create a new java file named after mod_id
5. Copy and paste code from ExampleMod java file and change all the mentions of examplemod to the value of mod_id
6. Delete the com.example.examplemod
7. Run `gradlew build`

### Gradle version

8.7

### Your Environment (optional)

IDE: IntelliJ IDEA 2024.2.0.2
Java version: 22.0.2
OS: Windows 11 64-bit

**Comment by ghale** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer, we may be able also to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

Can you provide a simpler reproducer for this issue?

The error indicates that you may not be running with the version of Java that you expect.  Bytecode version 66 refers to Java 22, so if you are receiving this error, it implies that you are running with an earlier version rather than 22.
