### ISSUE TITLE
Configure Kotlin Compiler Arguments for Kotlin DSL

### ISSUE THREAD

**Issue by Fabian-K** [gradle/gradle#30309]
### Expected Behavior

Additional Kotlin compiler arguments for Kotlin DSL can be specified

### Current Behavior (optional)

The Kotlin compiler arguments for Kotlin DSL seem to be fixed to https://docs.gradle.org/current/userguide/kotlin_dsl.html#sec:kotlin_compiler_arguments

### Context

I want to use experimental Kotlin features within build.gradle.kts files that require additional Kotlin compiler arguments. An example is Context Receivers which currently require "-Xcontext-receivers" to be enabled.

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Since this is a runtime concern, we might want to restrict that (since it may create unpredictable behaviors/interactions with Gradle core); it's up to the team to decide. You may try using binary plugins to use new features.

**Comment by eskatos** [comment]
Using binary plugins is indeed the recommended way to use experimental Kotlin compiler features. It's limitating in that you can only use them in the implementation of the plugins and they should not leak into the DSL the plugin exposes to the build scripts.

We don't want the Kotlin DSL runtime to vary too much between builds otherwise dealing with support questions will become too cumbersome.

We won't allow defining any and all compiler arguments. We only expose a few selected Kotlin compiler arguments as properties you can set on purpose (`org.gradle.kotlin.dsl.allWarningsAsErrors`, `org.gradle.kotlin.dsl.skipMetadataVersionCheck`). The embedded compiler API we use doesn't allow string based compiler arguments so we need to translate them to API calls.

I'm going to close this issue as we won't allow free configuration of Kotlin compiler arguments.
We can consider exposing other Kotlin compiler arguments but we need a good motivation for each one. Please open a dedicated issue per compiler argument explaining why we should consider it.

On context-receivers, please note that this KEEP is on hold and will most probably be replaced by another one: "context parameters" https://github.com/Kotlin/KEEP/blob/context-parameters/proposals/context-parameters.md
