### ISSUE TITLE
Reduce overhead of having many repositories 

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3049]
Forked off from #1369.

Many times a repository is only added to provide a small subset of the project's dependencies. Yet Gradle will still check all repositories for dynamic dependencies or when a dependency can't be found further up in the list.

The current approach is very basic and could be improved e.g. by remembering that a certain module was completely absent from a repository and never checking for that module there again until the cache times out.

**Comment by ljacomet** [comment]
@oehme I believe that we now have many things in place to reduce that overhead:
* Missing modules (`group:name` or `group:name:version`) are remembered forever, see #4436.
* Caching of dynamic versions and changing modules can be user controlled, and defaults to 24h.
* Before failing a build due to a missing dependency, Gradle will ignore cached results.

Given all that, I believe the pure performance aspect is covered and this can be closed.
Wdyt?

**Comment by melix** [comment]
I don't think this can be closed. There's still one issue which is not addressed: we're reduced the amount of requests that need to be made on a repository thanks to the `metadataSources` DSL, which lets us explain that's it's not worth looking for a jar file is metadata is missing. So far so good. But as soon as we will enable Gradle metadata, it's going to introduce a lot of requests to search for `.module` files when we know, at least in the beginning, that most modules will not provide it. So the situation is going to be worse than with looking for jar files.

While it should be possible to configure, say, `mavenCentral` not to look for Gradle metadata, this is not an acceptable solution.

So I'd refrain from closing this as we don't know what is going to be the impact of enabling Gradle metadata in practice, and how to improve the situation in general.

**Comment by oehme** [comment]
Yes I think #4436 addresses this issue.

**Comment by octylFractal** [comment]
This no longer applies.
