### ISSUE TITLE
Extend ExtensionAware with a custom DependencyCollector

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#30539]
### Expected Behavior

```kotlin
val api = objects.dependencyCollector()
(myBase.dependencies as org.gradle.api.plugins.ExtensionAware).extensions.add("api", api)
```

```kotlin
myBase.dependencies {
  api("bar")
}
```

### Current Behavior (optional)

```kotlin
myBase.dependencies {
  api("bar") // Unresolved reference: api
}
```

### Context

I want to extend a Gradle Managed Object (via ExtensionAware), in my case the KotlinDependencyHandler, with a custom DependencyCollector to add a custom dependency function.

Use case:
```kotlin
kotlin.sourceSets {
  main {
    dependencies { // this is KotlinDependencyHandler: ExtensionAware
        myCustomDependencyCollector("foo")
    }
  }
}
```

Reproducer: 
[sample.zip](https://github.com/user-attachments/files/16993484/sample.zip)

**Comment by ljacomet** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

I believe there is something missing in the way extensions are setup and how Gradle handles extensions methods for nested extensions.
But we could not find clear documentation on this topic.

**Comment by big-guy** [comment]
There's an underlying issue with how we generate extension functions based on extensions added at runtime. 

This is a similar issue: https://github.com/gradle/gradle/issues/9264

We don't generate extensions for deeply nested things and we cannot distinguish multiple instances of the same type even if we did.  In your example, every `KotlinDependencyHandler` would have every extension available. 

I'm not sure if we want to support extensibility like this in custom dependency blocks because it was intended to be more static.

**Comment by hfhbd** [comment]
> I'm not sure if we want to support extensibility like this in custom dependency blocks because it was intended to be more static.

With this limitation, do you have any plans/ideas to support Kotlin Multiplatform source sets that can be created by the user? Use-case: I have a custom code generator that should runs for each source set with different dependencies added by the user.
