### ISSUE TITLE
"Gradle sync" does not like a SYMBOLIC `...\AppData\Local\Temp` directory

### ISSUE THREAD

**Issue by olfek** [gradle/gradle#30555]
### Current Behavior

I get a `java.nio.file.FileAlreadyExistsException` followed by a `com.intellij.openapi.externalSystem.model.ExternalSystemException` (caused by the former).

I won't post the full logs here because there's some personal information in them. Sorry!

### Expected Behavior

No errors.

### Context (optional)

I use a piece of software called "RAM Disk" by "SoftPerfect" (https://www.softperfect.com/products/ramdisk)
to virtualize the `C:\Users\<USER>\AppData\Local\Temp` directory.

A symbolic link at `C:\Users\<USER>\AppData\Local\Temp` points to a folder inside the RAM disk.

### Self-contained Reproducer Project

N/A

### Gradle version

`8.10.1`

### Your Environment (optional)

```
     Edition  Windows 11 Pro
     Version  23H2
    OS build  22631.4169
  Experience  Windows Feature Experience Pack 1000.22700.1034.0
```

**Comment by olfek** [comment]
Same issue in the latest Gradle `8.10.1`

**Comment by olfek** [comment]
Updating the `TMP` and `TEMP` USER variables to point to the RAM disk has made the problem go away, **but this is only a workaround.**

**Comment by ljacomet** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer project, we may be also able to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project. 

This issue will be closed after 7 days unless you provide more information.

***

* Issues that are tied to commercial software are complicated for us to investigate. Ideally, find a reproducer that does require this software
* The exception is `com.intellij.openapi.externalSystem.model.ExternalSystemException` which points at an IntelliJ issue, not necessarily a Gradle issue. Does the problem happen when launching the build on the CLI?

**Comment by olfek** [comment]
@ljacomet ...

Reproducing it is pretty straight forward.

1. First remove the `C:\Users\<USER>\AppData\Local\Temp` directory.
2. In an elevated "Command Prompt" run: `mklink /d "C:\Users\<USER>\AppData\Local\Temp" "/some/other/path"` to create a symbolic link.
3. Observe that any Gradle based Android project opens in Android Studio with a "Gradle sync" error.
4. Observe that the few lines in the error log mention the path of the symbolic temp directory.

**Comment by ljacomet** [comment]
Understood.

But as I stated, the exception points at code _inside the IDE_ not Gradle.

What happens if you invoke the build on the command line? 
Does it fail?

**Comment by olfek** [comment]
Since Gradle apparently doesn't even have a `Sync Project with Gradle Files` function ...

https://issuetracker.google.com/issues/367439554
