### ISSUE TITLE
Build cache server error while falling over: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body

### ISSUE THREAD

**Issue by danroberts** [gradle/gradle#3060]
### Expected Behavior

If the build cache server is in the process of failing/falling over, and the request for the cached item fails, the build step should continue without using the build cache, as it does when the server is completely offline.

### Current Behavior

If the build cache server is slow the respond, the build step fails.

### Context

Our gradle enterprise shared build cache server recently went offline. Once it was totally offline, our CI builds would continue successfully, however, while it was in the process of failing, several CI builds failed with the following message:

```
FAILURE: Build failed with an exception.

* What went wrong:
 Could not load entry 2e898ad1858482e159bb8c9582ebd4ac from remote build cache
> org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 5229544; received: 4263892)
```

### Steps to Reproduce (for bugs)

You will need a gradle enterprise cache server which is slow to respond to the cache request. 

### Your Environment

 * Build scan URL:

**Comment by big-guy** [comment]
Which version of Gradle are you using?

**Comment by danroberts** [comment]
Pardon the omission -- version is 4.0.2

**Comment by KidDaedalus** [comment]
We also encountered builds failing when our Gradle Enterprise server was in the process of crashing. Similarly on build tool 4.0.2. We observed the failures with a custom task we made cachable. We did not observe any failures in built-in cachable tasks like javaCompile/checkstyle/test.

**Comment by danroberts** [comment]
@KidDaedalus this is also my scenario -- this is a custom task that I marked cacheable, built-in cacheable tasks were succeeding.

**Comment by big-guy** [comment]
This isn't the same issue, but it's a similar kind of failure that was fixed in 4.1:
https://github.com/gradle/gradle/issues/2434

We've made it so if we fail to understand the result from the remote build cache, we just continue on as if we didn't get a hit.  I think this change would prevent this problem for you.

Could you give 4.1/4.2 a try?

**Comment by bmuschko** [comment]
@danroberts Did you have a chance to try this with the latest version of Gradle?

**Comment by bmuschko** [comment]
As mentioned by @big-guy we believe that the issue has been fixed in newer versions of Gradle. We haven't heard back from you in the meantime. Closing this issue for now. Please provide additional information if you'd like to continue the discussion or run into the same issue with the proposed Gradle versions to try out.

**Comment by forresthopkinsa** [comment]
I'm running Gradle 4.4 and still encountering this problem.

**Comment by big-guy** [comment]
@forresthopkinsa A stacktrace, build scan and some details about your environment (e.g., if you're using GE for the build cache or something else) would be really helpful in tracking this down.  

We have tens of thousands of builds a week and don't encounter this problem, so any details would be appreciated.

**Comment by forresthopkinsa** [comment]
So, in most cases, if the build server returns a 500 error, then Gradle normally ignores it and continues on to the next repository?

I can't give a stack trace right now, because our build server isn't broken anymore, but I'm running a Composite build using the Gradle wrapper (version 4.4-all) on Ubuntu using BashOnWindows, referencing a Nexus build server (and using the Nexus Gradle plugin)

**Comment by forresthopkinsa** [comment]
haha shoot I'm in the wrong place. Sorry guys
