### ISSUE TITLE
initscript init.d documentation 

### ISSUE THREAD

**Issue by TheGoesen** [gradle/gradle#30610]
### Issue type

Wrong or misleading information

### Problem description

Documentation states 3+4

Put a file called init.gradle(.kts) in the $[GRADLE_USER_HOME](https://docs.gradle.org/current/userguide/directory_layout.html#dir:gradle_user_home)/init.d/ directory.

Put a file called init.gradle(.kts) in the $[GRADLE_HOME](https://docs.gradle.org/current/userguide/installation.html#sec:linux_macos_users_2)/init.d/ directory.

well the purpose of an init.d directory is obviously to use multiple script files, not just a single init.gradle file. So these entries should be changed to something like .. put a file using the extension .gradle(.kts)  in the ... directory. entries will be evaluated in alphabetic order

### Page with the problem

https://docs.gradle.org/current/userguide/init_scripts.html#sec:using_an_init_script

**Comment by ov7a** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

**Comment by ov7a** [comment]
FTR, it's better to have `.init.gradle.kts` suffix because it helps IDE to recognize the type of the script, so it would be better to mention it (cross-reference [this section](https://docs.gradle.org/current/userguide/kotlin_dsl.html#script_file_names)) in the updated version of the docs and use something like ` yourfilename.init.gradle(.kts)`.

**Comment by tj330** [comment]
Is this issue already taken? 
Can i work in fixing these?

**Comment by ov7a** [comment]
@tj330 AFAIK, no, feel free to open a PR.

**Comment by tj330** [comment]
Ok

**Comment by Kishorecoder96** [comment]
is this issue is fixed?
can i try to fix?

**Comment by TheGoesen** [comment]
This branch has been merged-> https://github.com/gradle/gradle/pull/30650
But the text on the web hasnt change... https://docs.gradle.org/current/userguide/init_scripts.html

**Comment by Kishorecoder96** [comment]
this issue may be caused because of using Ascii-Doc-style linking syntax, 
we can use the plain text to fix this  issue.Can i contribute ?

**Comment by ov7a** [comment]
Indeed, this is fixed already.
https://docs.gradle.org/8.11-milestone-1/userguide/init_scripts.html#sec:using_an_init_script
Note that the current version refers to 8.10.2 (the current latest release), and the fix is against 8.11 (the next release). That's why it isn't shown (yet).

Thanks @TheGoesen for noticing!
