### ISSUE TITLE
Parameter order incorrect in "Running Tasks" tutorial page - Step 2

### ISSUE THREAD

**Issue by jdbarras** [gradle/gradle#30659]
### Issue type

Wrong or misleading information

### Problem description

On step 2 of https://docs.gradle.org/current/userguide/part2_gradle_tasks.html#step_2_understanding_tasks the parameter order is backwards in the Groovy snippet.

```
tasks.register(Copy, "copyTask") {
    from("source")
    into("target")
    include("*.war")
}
```
should be 
```
tasks.register("copyTask", Copy) {
    from("source")
    into("target")
    include("*.war")
}
```

### Page with the problem

https://docs.gradle.org/current/userguide/part2_gradle_tasks.html#step_2_understanding_tasks

**Comment by ov7a** [comment]
This is a valid documentation issue.

We welcome documentation contributions. See [our contributing documentation guide](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#contributing-to-documentation) for more information.

***

This particular snippet is not tested and that's why it slipped through the cracks.

**Comment by tj330** [comment]
Can i work on this?

**Comment by ov7a** [comment]
Yes

**Comment by tj330** [comment]
Ok
