### ISSUE TITLE
Support SyncSpec in Action in FileSystemOperations.sync()

### ISSUE THREAD

**Issue by TobiasPongs** [gradle/gradle#30704]
### Expected Behavior

Make it work:
```
getFileSystemOperations().sync(s -> {
      s.preserve(f -> f.include("**/*.txt"));
      // ...
    });
```

### Context

The `FileSystemOperations` currently defines
```
    WorkResult sync(Action<? super CopySpec> action);
```
but should
```
    WorkResult sync(Action<? super SyncSpec> action);
```

The current workaround is to cast the `CopySpec` to a `SyncSpec`, because the internal implementation seems to create the correct instance.

**Comment by eskatos** [comment]
This feature request is in the backlog of the relevant team and is prioritized by them.

This issue is a good choice for first-time contributors to Gradle, it is actionable and ready for contribution.

See [CONTRIBUTING.md](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md) for more information.

***

This looks like an overlook that happened when `SyncSpec` was introduced. `FileSystemOperation` was not updated.

**Comment by tj330** [comment]
For clearing this issue, should i change both the FileSystemOperations interface and the implementing DefaultFileSystemOperations class?
