### ISSUE TITLE
Change the default reproducibleFileOrder = true in Gradle 9.0

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#30827]
### Expected Behavior

Creating a jar using Jar task in Gradle should be deterministic. The order of .class files in the jar should always be deterministic.

### Current Behavior (optional)

Gradle today defaults to `reproducibleFileOrder = false`

### Context

For Gradle 9.0, we should change the default to have a deterministic archive order.

**Comment by jvandort** [comment]
We should change this for 9.0

**Comment by sschuberth** [comment]
> Gradle today defaults to `archiveReproducibleFileOrder = false`

Shouldn't this just say [`reproducibleFileOrder`](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:reproducibleFileOrder), or will the property be renamed for 9.0?

**Comment by jvandort** [comment]
Renamed the title/description to use the correct property name

**Comment by jvandort** [comment]
It seems there may be performance implications of this change.

Instead of "streaming" files into the archive as we know them, we instead need to collect all entries in order to compute a reproducible order. 

I am not sure what the actual penalty is, but there is a chance it may be too expensive to move forward

**Comment by lptr** [comment]
Let's do this as part of:

- https://github.com/gradle/gradle/issues/30871
