### ISSUE TITLE
PublicationArtifact: Remove builtBy (and Buildable)

### ISSUE THREAD

**Issue by hfhbd** [gradle/gradle#31223]
### Expected Behavior

```java
/**
 * An artifact published as part of a {@link Publication}.
 *
 * @since 4.8
 */
public interface PublicationArtifact {
    /**
     * The actual file contents to publish.
     */
    Provider<RegularFile> getFile();
}
```

### Context

https://github.com/gradle/gradle/pull/30665 already replaced the `File getFile()` with `Provider<RegularFile> getFile();`, but the provider is able to carry the task dependency, so `void builtBy(Object... tasks)` should be removed.

The `Buildable` (https://github.com/gradle/gradle/issues/30534) should be removed too.

Use-case:
I want to lazily fetch the publication files but currently I need to use a provider:
```kotlin
val publishedFiles: Provider<List<File>> = provider {
  publishing.publications.withType<MavenPublication>().flatMap {
    it.artifacts
  }.map { it.file }
}

val shouldBe: List<Provider<RegularFile>> = publishing.publications.withType<MavenPublication>().flatMap {
  it.artifacts
}.map { it.file }
```

**Comment by jvandort** [comment]
Looking at your second example,

```
val shouldBe: List<Provider<RegularFile>> = publishing.publications.withType<MavenPublication>().flatMap {
  it.artifacts
}.map { it.file }
```

This eagerly resolves the publications in the container. The files within the publications may not be eagerly resolved, but the publications themselves are. This will not capture any publications added to the container after this code runs.

In practice, you will still need the surrounding `provider {}` call. 

Given that in 9.0, `getFiles` would return a `Provider<RegularFile>`, the only proper way to lazily refer to the files of a publication would be through a `Provider<List<Provider<File>>>`, since both the container of artifacts of a publication and the file of a artifact are lazy. 

Ideally, this would be condensable into `Provider<List<File>>`, by iteratively calling `zip`, though that would likely be quite inefficient. We have an internal Provider implementation that does something similar without relying on iterative zip calls, but that is currently not public API: https://github.com/gradle/gradle/blob/82937b89af179043f34052cd5d6a8818571cca8f/platforms/core-configuration/model-core/src/main/java/org/gradle/api/internal/provider/MergeProvider.java#L36

As to removing `Buildable`, that is tracked in https://github.com/gradle/gradle/issues/30534.

In general, I don't think we can remove `Buildable` from `PublishArtifact` _now_ since we need time to migrate people. We would need a deprecation cycle first since users are still calling `builtBy` manually. 

I think we should track this work in https://github.com/gradle/gradle/issues/30534

**Comment by jvandort** [comment]
> Why can a publication artifact built by multiple tasks?

It probably does not make sense for it to. Though I could think of a complex scenario where one task selects between multiple outputs files of another based on some calculation it makes in its action, meaning the artifact would depend on both tasks.

> Shouldn't be the provider set by a task output carrying the task dependency implicitly?

Yup, and this is what we're working towards. For the artifacts _you_ are producing, I would encourage you to make sure your outputs are tracked on the File provider and to not call `builtBy`, however existing build logic might not be doing this yet.

This is an older API and there are people using it, including Gradle internals. Deprecating this late in the release cycle will not give people enough time migrate off (including us). In terms of priority of doing this, the team working https://github.com/gradle/gradle/issues/30534 will decide on it.
