### ISSUE TITLE
Consider having Provider extend java.util.function.Supplier

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#31317]
### Expected Behavior

given

```java
  public static Try.WithResources1<Git> openGit(Supplier<File> projectDir) { ... }

  public static Function<Git, Optional<Ref>> getHeadBranch(Supplier<String> remote) { ... }
```

then this will compile

```java
    GitTools.openGit(this.getParameters().getProjectDir()).of(GitTools.getHeadBranch(this.getParameters().getRemote()));
```

### Context

I want to write as generically java code as possible for most functionality without doing things like wrapping things your get calls with lambdas or other functions. If approved I suppose I could spend the 30 minutes creating the PR, not certain if a test would be needed, but even that's simple.

It'd also be nice if Suppliers (instead of just Callables) could be taken.

**Comment by reinsch82** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

It's not clear whether we can preserve the lazy aspirations of the provider api with the `Supplier` interface since the only possible action is `get`

**Comment by mlopatkin** [comment]
This is the intended behavior, and there’s no plan to change it. This issue will be closed.

***

Calling `Provider.get()` at arbitrary time is often problematic, because you're losing all the features (both current and potential) associated with them: dependency tracking, provenance, etc. We're actually looking into limiting the ability to obtain the value to reduce the possibility of errors.

Given that converting a Provider to a Supplier is just a matter of writing `myProvider::get`, we're reluctant to do the proposed change.
