### ISSUE TITLE
eclipse plugin doesn't support multi module sample project

### ISSUE THREAD

**Issue by MrKuip** [gradle/gradle#31341]
### Current Behavior

In my project I use a layout like described in: https://docs.gradle.org/current/samples/sample_java_modules_multi_project.html

I am trying to create an eclipse project for this but it fails.
No .classpath file is created. Only an 'empty' .project

### Expected Behavior

Run 'gradlew eclipse' and start editing/developing the sourcecode in eclipse

### Self-contained Reproducer Project

see https://docs.gradle.org/current/samples/sample_java_modules_multi_project.html

### Gradle version

Gradle 8.11

**Comment by reinsch82** [comment]
Your issue appears to be a question about how to use Gradle. They should be asked in a different channel, so we will close it. Your question might be answered in Gradle documentation or on our community Slack or forums. Find links to these resources on [help.gradle.org](https://help.gradle.org/).

If you think our analysis is wrong, please provide us with more detailed information explaining why.

***

1. You should use [buildship](https://docs.gradle.org/current/userguide/gradle_ides.html#eclipse) to import the project into eclipse.
2. You should only apply the eclipse plugin if you have customization to the eclipse import.

Applying that plugin to the root project is most likely not what you want since this is not a java project, it should be applied to the project needing the customization or through the convention plugin of the sample.
