### ISSUE TITLE
Ignore irrelevant changes in environment variables

### ISSUE THREAD

**Issue by viluon** [gradle/gradle#31375]
### Expected Behavior

Builds with changes to environment variables that aren't queried via specific environment variable providers can still reuse the configuration cache.

### Current Behavior (optional)

Configuration cache cannot be reused if an unrelated environment variable changed.
```
Calculating task graph as configuration cache cannot be reused because environment variable 'ATUIN_HISTORY_ID' has changed.
```

### Context

This is effectively a re-opening of #29971, which I believe was closed due to a misunderstanding / insufficient activity of the reporter, even though it is a real issue. CI environments change environment variables on every run, which causes lots of needless configuration cache invalidation.

**Comment by ov7a** [comment]
We appreciate the effort, but we must ask for more information so that we can triage it. 

We do not see an immediate root cause, and we need a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example) for the triage. If we have a reproducer project, we may be also able to suggest workarounds or ways to avoid the problem.

The ideal way to provide a reproducer project is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.

This issue will be closed after 7 days unless you provide more information.


***

If confirmed, this will be a bug, not a feature request.

Either it is an invocation of 
* #20873

and something in your build logic (e.g. plugin) captures that environment variable, or it's a bug. To decide this, we need a reproducer. 

See also:
* https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:requirements:reading_sys_props_and_env_vars
