### ISSUE TITLE
Find when a configuration is resolved

### ISSUE THREAD

**Issue by tjni** [gradle/gradle#31505]
### Expected Behavior

I see deprecation messages like the following in my build scan:

```
Mutating the dependencies of configuration '<project>' after it has been resolved or consumed. This behavior has been deprecated.
    This will fail with an error in Gradle 9.0.
    After a Configuration has been resolved, consumed as a variant, or used for generating published metadata, it should not be modified.
```

This comes with a corresponding stack trace. However, I would also like to see where in my build the configuration has been resolved so that I can decide which location needs to be changed. Is this possible?

### Context

I am attempting to prepare some builds for Gradle 9.

**Comment by ov7a** [comment]
This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Currently, there's no easy way to discover where the failure comes from because it's technically hard to interpret the information. However, we might consider adding some pointers to the upgrade guide and linking to them from the message.

For now, you can add some `throws`/debug logic in `configuration.incoming.beforeResolve`

**Comment by tjni** [comment]
There are still a couple of things I'm struggling with. Please let me know if this isn't the right place to discuss this anymore, and I can move to forums, Slack, or somewhere else.

Specifically, the error message is:

```
Mutating the dependencies of configuration '<project>:api' after it has been resolved or consumed. This behavior has been deprecated.
```

I believe it is because in our plugins we add dependencies to the `api` and `implementation` configurations in an `afterEvaluate` block.

I have tried to throw in `configurations.api.incoming.beforeResolve`, but it does not fire. I have tried to put it in various places (near the beginning of the project's build.gradle file, at the top of the root project's build.gradle file in a subprojects block). I suppose that this makes sense, since `api` is neither consumable or resolvable.

When I throw an exception in beforeResolve targeting `compileClasspath`, it only throws during `compileJava`. So my best guess is that maybe `apiElements` or some other related configuration is consumed early, but I don't know how to validate that assumption.

Any additional suggestions would be greatly appreciated.

**Comment by big-guy** [comment]
It would be nice to get some better insight into this.

There are multiple ways a configuration can be observed.  `beforeResolve` isn't going to help in cases where the configuration is used from another configuration (e.g., `someConf.extendsFrom(api)`)

We'll see if there are any quick wins for 8.13

**Comment by jvandort** [comment]
I wrote https://github.com/gradle/gradle/pull/31658 to try to capture a bit more context whenever we observe a configuration. This will report whether the configuration being mutated was previously:
- Resolved
- Consumed as a variant
- Published
- Observed due to a child configuration doing one of the above

It is difficult to capture the original place of observation, as that would require capturing a stack trace for each time a configuration is observed. 

To debug things like this I would recommend [debugging Gradle](https://docs.gradle.org/current/userguide/troubleshooting.html#sec:troubleshooting_build_logic). See the "Debugging build logic" section.

You can put a breakpoint [here](https://github.com/gradle/gradle/blob/de3ab6a0773fb2cc076d63a095e33ee3bc96af15/platforms/software/dependency-management/src/main/java/org/gradle/api/internal/artifacts/configurations/DefaultConfiguration.java#L1143-L1154) and filter your breakpoint to only trigger when the configuration-being-mutated is the one being observed.
