### ISSUE TITLE
Version ranges use sometimes wrong brackets

### ISSUE THREAD

**Issue by pdolezal** [gradle/gradle#31536]
### Issue type

Wrong or misleading information

### Problem description

It seems that version ranges in the documentation are not correctly formatted (or what had happened). For instance, see [the page about them](https://docs.gradle.org/current/userguide/dependency_versions.html#sec:version-ordering): from that point down the version ranges have often a wrong right bracket – `[` instead of `)` or `]`. I think I saw that on other pages too.

As a Gradle newbie, I was somewhat confused first and I thought it was some Gradle idiosyncrasy 😅

### Page with the problem

https://docs.gradle.org/current/userguide/dependency_versions.html#sec:rich-version-constraints

**Comment by lkasso** [comment]
Hey @pdolezal, please note that:

- [ and ] indicate an inclusive bound -> [1.1, 2.0]
- ( and ) indicate an exclusive bound -> (1.1, 2.0) or (1.2, 1.5]
- ] can be used instead of ( for an exclusive lower bound -> [1.1, 2.0)
- [ can be used instead of ) for exclusive upper bound -> [1.0, 2.0[

Would you like me to add this to that doc page? Is there anything else that doesn't make sense?

**Comment by pdolezal** [comment]
@lkasso Hi, thanks for the reply. Well, the possibility that it stands for an exclusive bound came to my mind, because it was repeated multiple times, but I could not find any explicit explanation. If it is missing indeed, I'd vote for adding it ✌ Specifically, I would expect it [in the section _Understanding version declarations_](https://docs.gradle.org/current/userguide/dependency_versions.html#sec:single-version-declarations).

**Comment by lkasso** [comment]
I will go ahead and add it this week. I will make sure it gets released in Gradle 8.12
