### ISSUE TITLE
Component metadata rules should support modifying attributes of existing variants

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3159]
We should be able to define additional variants, with possibly different dependencies, for an existing module via _Component Metadata Rules_. Ground work of supporting variants in metadata rules is done as part of #3157. The `withVariant {}` API introduced there should be extended by:
1. Making the `VariantMetadata` interface extend `HasAttributes` and allow attribute modification through that.
2. Match variants by attributes - withVariants(attributes).

Possibly later:
- Extending `withVariant {}` to allow new variants to be added (e.g. offering a `withAdditionalVariant {}`) 
- Allow metadata rules to define/change the artifacts of a varian (e.g. add `withVariant { withArtifacts {} }`) - _is this really needed, or are new variant just "copies" of existing ones with the same artifacts?_

**Comment by jjohannes** [comment]
Also: match variants by attributes - `withVariants(attributes)`.

**Comment by melix** [comment]
Things left to do before closing:

- [ ] encapsulate the `addDependencyMetadataRule` methods and friends on `MutableModuleComponentResolveMetadata`
- [ ] support `withVariants`, and probably `withVariants(Spec)`
- [ ] support access to attributes in `ComponentSelectionRules`
- [ ] consolidate `status` so that it's backed by a real attribute
- [ ] add variant details to `ResolutionResult` (may become a ticket of its own)
- [ ] avoid applying rules again when resolving artifacts
- [ ] rename the internal `VariantMetadata` implementation
- [ ] document `VariantMetadataAdapter`

**Comment by melix** [comment]
Once #3904 is merged, this issue can be closed.
