### ISSUE TITLE
Apache Compress upgrade

### ISSUE THREAD

**Issue by pradeepr83** [gradle/gradle#31793]
Is there any plan to upgrade Apache commons compress from 1.26.1 to 1.27.0.

There is an issue when upgrading to spring boot 3.3.0 due to conflict in the version.

**Comment by pradeepr83** [comment]
apache compress version in spring boot gradle plugin upgraded to 1.26.2, which causes 
Caused by: java.lang.NoSuchMethodError: 'void org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(org.apache.commons.compress.archivers.zip.ZipArchiveEntry)'
which conflicts with the version in gradle distribution. 
Please help to check this.

**Comment by jbartok** [comment]
Spring-boot `3.3.x` is using commons-compress `1.25.0` (see [here](https://github.com/spring-projects/spring-boot/blob/3.3.x/spring-boot-project/spring-boot-parent/build.gradle)) and that should work; maybe some other dependency makes it so that an older version of commons-compress gets resolved, like in [this StackOverflow discussion](https://stackoverflow.com/questions/78638699/bootjar-task-fails-with-gradle-8-5-and-spring-boot-3-3-0-caused-by-spring-boot).

**Comment by glenpierce-impact** [comment]
Update:
Updating my gradle-plugins seems to have resolved this issue for me so far... I hope this is helpful to others.

The problem we face is with Spring-boot 3.4.5.

I'm trying to upgrade to that version of Spring-boot and when I run:
`./gradlew jib -x compileJava -x classes -Porg.gradle.java.installations.auto-detect=false`
I get an error that reads:

> * What went wrong:
> Execution failed for task ':my-project:bootJar'.
> > 'void org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream.putArchiveEntry(org.apache.commons.compress.archivers.zip.ZipArchiveEntry)'
> 

I'm not quite sure how to fix this error. I'm getting the same problem and I've tried.
```
configurations.configureEach {
    resolutionStrategy.force 'org.apache.commons:commons-compress:1.26.2'
}
```
