### ISSUE TITLE
issue running parallel tests with TestNG

### ISSUE THREAD

**Issue by mondrejko** [gradle/gradle#3190]
We have found an issue when running tests in parallel. We set the following on the test task: 

•	useTestNG 
•	maxParallelForks = project.gradle.startParameter.maxWorkerCount (although I believe that any value > 1 is likely to show the issue) 
•	forkEvery = 1000L 
•	reports.html.enabled = false 
•	reports.junitXml.enabled = true 

and then run our tests (89 methods in this case). The test run will display that all 89 tests were run, but the xml report (build/reports/tests/test/testng-results.xml, and Tests/Tests.xml) do not (they both contain a subset of the tests run). When running with html.enabled = true and junitXml.enabled = false, then the HTML report generate includes ALL tests. In addition, html.enabled = false, junitXml.enabled = true with maxParallelForks = 1 produces a correct XML report. 

It seems that while the HTML report properly includes tests run in all test worker threads, the XML report does not. As this XML report is what our Jenkins server uses in its reporting, it is incorrectly reporting the tests that were executed

**Comment by bmuschko** [comment]
Could you please provide us with a sample project that reproduces the issue on GitHub? The project should also include a checked-in Wrapper to indicate the version you are using.

> The test run will display that all 89 tests were run, but the xml report (build/reports/tests/test/testng-results.xml, and Tests/Tests.xml) do not (they both contain a subset of the tests run).

I am not quite sure which XML you are referring to here. XML report files are places under `build/test-results/test` (except if you reconfigured that location).

**Comment by mondrejko** [comment]
See https://github.com/mondrejko/parallel-testng

**Comment by bmuschko** [comment]
Thanks for providing the sample project. I tried this out on Jenkins by creating a Post-build Actions "Publish JUnit test report results" and pointing "Test report XMLs" to `build/test-results/test/TEST-*.xml`. I could not reproduce a deviating result than the one created by the HTML reports. In both cases I see 20 executed tests.

BTW: You will likely want to use `test.useTestNG.listeners << 'org.testng.reporters.XMLReporter'` instead of `test.useTestNG.useDefaultListeners = true` as it doesn't create the additional HTML overhead.

**Comment by mondrejko** [comment]
We are using the Publish TestNG Results plugin for Jenkins, pointing to the build/reports/tests/test/testng-results.xml file. It is this XML file that has the incorrect contents.

**Comment by bmuschko** [comment]
> We are using the Publish TestNG Results plugin for Jenkins.

Is there any functional benefit for using this Jenkins instead of the standard JUnit one? At the moment I cannot see one. I'd suggest going with the mechanism described above instead.

> It is this XML file that has the incorrect contents.

It looks to me like that never really worked properly. My guess is that the default TestNG report mechanism doesn't know about Gradle's parallel execution mechanism and therefore produces incorrect results. I tried with Gradle 3.0 and can see that same, incorrect behavior.

Would you be interested in working on a fix for this?
