### ISSUE TITLE
Actual worker count is `--max-workers`+1

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#3273]
### Context

In https://github.com/gradle/gradle/commit/2db9e648562e51d5d337a51fd2c9c2d392e17b19 we made some change to allow main thread (i.e. the thread which is waiting for build operation queue's completion) to execute some work. The consequence is, the actual worker number is `max-workers` number +1. Since we can't set `--max-workers=0` via command line, that means the work would always be executed parallelly. 

In most cases, this isn't a big problem. However, this does seem misleading (and error-prone! see https://github.com/gradle/gradle-private/issues/977). We have the following possible choices:

- Don't allow main thread to run any work. 
- Keep this behaviour, but clarify it in documentation. In addition, allow `--max-workers=0`

Personally, I like the former one.

**Comment by ghale** [comment]
At least for now, we need to keep the main thread executing work.  The issue here is that we have a shared, bounded execution thread pool _and_ worker leases.  What can happen is that multiple threads with obtained worker leases can submit at the same time, but one of them can flood the thread pool with workers that can't acquire a worker lease.  Meanwhile, other workers that _can_ acquire a lease will be stuck trying to get onto the thread pool.  It's not a deadlock situation, but it does decrease performance dramatically.  By allowing the main thread to process work, then we ensure that at least one thread that has already acquired a worker lease is always executing (regardless of the thread pool).

This isn't the only solution to the problem, but its the simplest until we design something better.  For now, we should make the `BuildOperationQueue` only submit up to `max-workers-1` workers to the thread pool - this should fix the issue when max-workers=1.

**Comment by blindpirate** [comment]
Yes, that should be the appropriate solution. Thank you very much @ghale !
