### ISSUE TITLE
Gradle application distribution does not read systemProperties

### ISSUE THREAD

**Issue by dgoetsch** [gradle/gradle#3282]
My bug is related to the executable Unix script that is produced by application plugin and used to run the application.

There is a bug in this file. I think the source is here: https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/resources/org/gradle/api/internal/plugins/unixStartScript.txt

That file seems to be executable script provided in the tar built with `gradle build`.  It is located in a tar file in `build/distributes/{distributionName}`.

When I extract the tar produced by `gradle build` in `build/distributions/{distributionName}`,
I expect that when I run the executable and provide a system property to the file like so `./{distributionName} -Dmyproperty=value`, the argument should be read into the jvm. However, it is not.

Investigating this issue, locally I changed :

```
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $DEVICE_OPTS -classpath "\"$CLASSPATH\"" com.redacted.ApplicationKt "$APP_ARGS"
```

to

```
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $DEVICE_OPTS "$APP_ARGS" -classpath "\"$CLASSPATH\"" com.redacted.ApplicationKt
```

and that solved the issue.

Changing line 165 from:

```
eval set -- \$DEFAULT_JVM_OPTS \$JAVA_OPTS \$${optsEnvironmentVar} <% if ( appNameSystemProperty ) { %>"\"-D${appNameSystemProperty}=\$APP_BASE_NAME\"" <% } %>-classpath "\"\$CLASSPATH\"" ${mainClassName} "\$APP_ARGS"
```

to

```
eval set -- \$DEFAULT_JVM_OPTS \$JAVA_OPTS "\$APP_ARGS" \$${optsEnvironmentVar} <% if ( appNameSystemProperty ) { %>"\"-D${appNameSystemProperty}=\$APP_BASE_NAME\"" <% } %>-classpath "\"\$CLASSPATH\"" ${mainClassName}
```

Should fix the issue.

### How to reproduce

```
$ gradle build
$ cd build/distributions/{projectName}
$ tar -xvf {project-dist}.tar
$ cd bin
$ ./{projectName} -DmyProp=value
```

**Comment by big-guy** [comment]
@dgoetsch Unfortunately, moving $APP_ARGS before the class name breaks the meaning of APP_ARGS.  This is because there are two kinds of arguments to JVM applications--the JVM's arguments (things like `-Dmyproperty=value`) and the application's arguments.

APP_ARGS are the arguments passed to your application.  If you need to interpret `-Dmyproperty=value` as a system property, you'll need to add that functionality to your application or pass those kinds of arguments to the JVM via DEFAULT_JVM_OPTS, JAVA_OPTS or DEVICE_OPTS.
