### ISSUE TITLE
Daemon should expire before a GC overhead limit exceeded error occurs

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#3292]
If the Old Generation (Tenured Space) is filled up but there is still quite some space in the Jung Generation, the strategy does currently not expire the daemon. Yet the garbage collection can throw and `GC overhead limit exceeded`.
Instead of only checking the total memory through the `TotalPhysicalMemoryProvider` we should check the individual pools.

### Expected Behavior
- Daemon should expire before garbage collection exception is thrown.

### Current Behavior
- If only the Old Gen is filled up, the daemon is not expired and follow up builds most likely fail with a `GC overhead limit exceeded` exception.

### Context
Here is a build scan where this happens in the `gradle/gradle` build on our CI:
https://builds.gradle.org/viewLog.html?buildId=8940411&buildTypeId=Gradle_Check_Java9Smoke_Java8_Oracle_Linux_javascript
(build scan `zkybxr7nqqkvo`)

<img width="411" alt="sc-build-scan" src="https://user-images.githubusercontent.com/1963746/32045457-986e05e2-ba40-11e7-9a64-0dafc0455960.png">

### Your Environment
 * Build scan URL: https://builds.gradle.org/viewLog.html?buildId=8940411&buildTypeId=Gradle_Check_Java9Smoke_Java8_Oracle_Linux_javascript (build scan `zkybxr7nqqkvo`)

**Comment by ghale** [comment]
Just some comments on this:

`LowMemoryDaemonExpirationStrategy` is intended to expire the daemon when _physical_ memory is low.  For garbage collection monitoring, `LowTenuredSpaceDaemonExpirationStrategy` and `GcThrashingDaemonExpirationStrategy` are used.  Essentially, these monitor the garbage collector over time and either expire it after the build (low tenured space) or attempt to expire it immediately (gc thrashing).  They have the disadvantage, though, that they are most suitable for catching slow leaks - if a leak is particularly fast, there is the possibility (probability) that they won't react in time, or that even if they do, they won't be able to actually do anything because they will be blocked by the thrashing garbage collector.

Some thoughts on making this better:

- We could look at tweaking the algorithms to see if we can get them to behave better under a wider range of circumstances.  The difficulty with this is actually constructing realistic test cases - different memory leaks can behave differently and drive different behavior in the garbage collector.  So settings that work well under one kind of leak, can work really poorly under another.
- We could simply make it a little more aggressive.  The balancing act is trying to determine whether a low heap situation is temporary or actually a leak.  We might consider reacting aggressively if the heap is fully expanded and the amount of freed memory after a garbage collection event is below a threshold.  The danger here is being too aggressive and expiring daemons that will actually recover.
- One of the issues is that the monitoring runs inside the daemon process and is also affected by the low heap situation.  We might consider moving the monitoring out of process to the client and have it query the daemon for it's latest gc stats.  It could then detect and react to a low heap situation from outside of the process by telling the daemon to stop after the build or even to stop immediately.  This also has the advantage that the client is the parent process and so could forcefully terminate the daemon if it just becomes unresponsive.

**Comment by ghale** [comment]
One other thought:

- We currently poll for garbage collection values because the IBM garbage collector does not provide a way to listen for garbage collection events (or rather you can listen for them, you'll just never receive any).  We could change this for the Oracle jvm since it does allow for registering listeners.  We could then react more quickly when the garbage collector starts panicking.  Of course, this would mean we would have two different strategies to maintain - a polling strategy for ibm and an event-driven strategy for oracle - which would be added complexity.

**Comment by jjohannes** [comment]
@ghale thanks for clarification and for the suggestions. I adjusted the title of this issue to reflect that there are different approaches we could take to avoid GC errors.

**Comment by mark-vieira** [comment]
We are seeing this in CI. I'm wondering if we can't "prevent" an OOME if we can at least handle them. We see cases where the daemon exhausts memory and then subsequent builds fail. The daemon continues to respond to build requests so it is at least _somewhat_ operational. If possible we would kill the daemon after one of these failures.

https://scans.grdev.net/s/6ylja5runtu3g/

**Comment by neowhoru** [comment]
We have a Gitlab CI Runner which should build around 20 Flavors (with resulting 2 APKs each).
When the command executes each "gradlew assemble$Flavor" command you can see an increase of memory in the daemon. 

I gave it 4GB with the gradle.properties but after it reaches them it stops with "GC Overheap limit exceeded". Any new build gets the same message directly.

I need to stop the daemon with gradlew --stop.
But this cannot be the solution to stop the daemon as it kills the whole process (and could interrupt other builds too).

**Comment by anshulvij** [comment]
We isolate the daemon for every build pipeline by providing Gradle a dedicated GRADLE_USER_HOME?
Does this mean that the **gradle --stop** command will only kill the daemons that are started from on particular pipeline and not affect others?

**Comment by mark-vieira** [comment]
@anshulvij yes, that is correct. The daemon registry lives in GRADLE_USER_HOME so any daemons using a different location are effectively unknown.
