### ISSUE TITLE
Dependency resolution ignores the rest repositories except the first one

### ISSUE THREAD

**Issue by zolotov** [gradle/gradle#3330]
Hi. 

Starting with Gradle 4.3 I have a problem with the [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin/issues/247#issuecomment-340829707).

The plugin registers two local `ivy` repositories [here](https://github.com/JetBrains/gradle-intellij-plugin/blob/11b5e97a67fb93d0a758080d2f45d559a43bcbdd/src/main/groovy/org/jetbrains/intellij/dependency/IdeaDependencyManager.groovy#L73) and [here](https://github.com/JetBrains/gradle-intellij-plugin/blob/11b5e97a67fb93d0a758080d2f45d559a43bcbdd/src/main/groovy/org/jetbrains/intellij/dependency/PluginDependencyManager.groovy#L62). Since Gradle 4.3 any dependency that should be resolved via the second repository fails with the following message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':compileClasspath'.
> Could not resolve org.jetbrains.plugins:coverage:2017.2.
  Required by:
      project :
   > Could not resolve org.jetbrains.plugins:coverage:2017.2.
      > inconsistent module metadata found. Descriptor: com.jetbrains:ideaIC:2017.2 Errors: bad group: expected='org.jetbrains.plugins' found='com.jetbrains'
        bad module name: expected='coverage' found='ideaIC'
```

Here is a project for recreating the issue: https://github.com/zolotov/gradle-intellij-plugin-dependency-issue, just run `./gradlew assemble`. The same project works fine on Gradle 4.2.

Is this a problem of the gradle-intellij-plugin? If so, could you point me to what should be changed there, please? Thank you.

**Comment by blindpirate** [comment]
Thanks for reporting. This is the expected bahavior (see [here](https://docs.gradle.org/current/release-notes.html#avoid-checking-other-repositories-when-dependency-resolution-in-one-repository-fails)). Instead of skipping the failure (artifact not found is NOT a failure) silently, we decide to throw it explicitly.

In your case, I noticed you registered two ivy repos:

- Repo1: [Ivy pattern 'file:/Users/zhb/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/ideaIC-2017.2-withKotlin.xml']

- Repo2: [Ivy pattern 'file:/Users/zhb/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/coverage-master-2017.2.xml']

A pattern tells Gradle where to look for ivy files. So the cause is, when you ask Gradle to search `org.jetbrains.plugins:coverage:2017.2` artifact, it first tries to access `Repo1` and fetch the metadata (`ideaIC-2017.2-withKotlin.xml`) successfully, which is not correct. `Repo1` should tell Gradle, "hey, the metadata you're looking for is not here!" , then Gradle would try the next repository.

To fix this, I'd advice to introduce some pattern. For example, you can register repos as follows:

- Repo1: [Ivy pattern 'file:/Users/zhb/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/ideaIC/2017.2/5155889067278eb216234aa0eeb8e1944644624c/ideaIC-2017.2/[module]-2017.2-withKotlin.xml']

- Repo2: [Ivy pattern 'file:/Users/zhb/.gradle/caches/modules-2/files-2.1/com.jetbrains.intellij.idea/plugins.jetbrains.com/[module]-master-2017.2.xml']

This can make sure Gradle won't fetch the unexpected result.

Please let me know if there's anything unclear.

**Comment by blindpirate** [comment]
@bigdaz Since you're an expert on this, I'd like to hear your opinions, are there better solutions?

**Comment by zolotov** [comment]
> To fix this, I'd advice to introduce some pattern. For example, you can register repos as follows

Sounds good. I'll try this and will update the issue. Thank a lot!

**Comment by zolotov** [comment]
It works. Thank you. The issue can be closed I think.

**Comment by blindpirate** [comment]
Glad to here that!

**Comment by zolotov** [comment]
@blindpirate looks like I still have a problem with this.

If I add two repositories 
1. `repo.ivyPattern("$path1/[module]-$channel-[revision].xml")` with artifact patter `$artifactPath1/[module]-master-[revision]/[artifact].[ext]`
1. `repo.ivyPattern("$path2/[module]-$channel-[revision].xml")` with artifact patter `$artifactPath2/[module]-master-[revision]/[artifact].[ext]`

And add two dependencies `dependency1` from `artifactPath1` and `dependency2` from `artifactPath2`, then `dependency2` is tried to be resolved via `artifactPath1` (even though it's not defined in the first ivy xml).

I can provide a sample project to recreate this if it's needed.

**Comment by zolotov** [comment]
Reproducible in Gradle 4.3.1

**Comment by blindpirate** [comment]
Very sorry for the late response.

Well, I think this is exactly how the repository works. Multiple repositories make up a repository chain then all dependencies would be searched in the chain in turn. You can't say, "I want dep1 to be resolved only in repo1 and dep2 only to be resolved in repo2".

In your case, looks like what you need is not repositories. Instead, would it be better if you register your dependency with [`files`](https://docs.gradle.org/current/userguide/dependency_management.html#sub:file_dependencies)?

**Comment by zolotov** [comment]
> You can't say, "I want dep1 to be resolved only in repo1 and dep2 only to be resolved in repo2".

It's ok to me to say "I want dep1 and dep2 to be resolved in repo1 OR in repo2". The problem is that both of them are resolved in repo1 only, which is success for the first one and fail for the second. Why repo1 is even used for dep2 if it's ivy.xml pattern is not matched?

Unfortunately, I cannot use `files` dependencies because there is no way to attach sources in IDE them.

**Comment by blindpirate** [comment]
I'm not sure I follow you. You mean even when the dep2's `ivy.xml` corresponding to repo1's pattern doesn't exist, repo2 wouldn't be searched?

Pattern is used to locate `ivy.xml`. For dep2, Gradle will render repo1's ivy pattern with dep2's information and try to search the dep2's `ivy.xml` with the rendered "pattern". If the target file exists, repo2 wouldn't be attempted. Otherwise, repo2 would be searched in the same way as repo1.

It would be great if you can provide me with a sample project.

**Comment by zolotov** [comment]
@blindpirate while preparing test project I've found a way how both dependencies were matched for the one ivy.xml. Sorry for wasting your time :(

**Comment by blindpirate** [comment]
Not at all, feel free to ask whatever you want. 

P.S. I'd thank your IDEA, which saved a lot time for me with "Set value" functionality when debugging.
