### ISSUE TITLE
Allow plugin authors to suppress deprecation warnings

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#3332]
Plugin authors often target a certain maximum version, making deprecation warnings beyond that version unhelpful. Gradle should allow a plugin author to specify that maximum version and suppress deprecation warnings for features that will be removed beyond that version threshold.

As a first step this needs some more design, i.e.

- How does a plugin author define the compatible Gradle versions?
- How fine-grained are warnings suppressed (think of hooks added by other plugins and build scripts etc.)?
- How can we inform plugin authors of deprecations if their plugins ignore warnings in this way? E.g. could TestKit help here?
- How do we inform plugin consumers that their build will no longer work with builds beyond the upper bound?

**Comment by adammurdoch** [comment]
I think we should start with plugin authors declaring a single target Gradle version, just like they declare a single target Java version.

Let's say I declare that 4.2 is my target Gradle version, the contract should _end up_ some thing like this:

1. Gradle compiles the plugin source against the Gradle 4.2 API. It might do this by failing when I attempt to build the plugin on a Gradle version other than 4.2, or it may go and find the Gradle 4.2 API (or maybe present an API that is compatible with 4.2 but warns me that it's not the actual target API and refuse to publish the result).
2. Gradle can use the plugin version on any Gradle version that provides the Gradle 4.2 API. Gradle should not attempt to use the plugin on any Gradle version <4.2 or >=5.0 and instead should fail (or perhaps warn me first and then attempt). If Gradle refuses to use a plugin version, it should let me know about any other plugin versions that happen to be available that it will accept. And offer a quick fix to switch to this version, even better.
3. The plugin source should use those APIs that were available and not deprecated as at 4.2. Gradle should not warn about any usages of an API that was not deprecated in Gradle 4.2, if it does decide to use the plugin version.
4. Gradle tests the plugin version against Gradle 4.2, by convention. It should fail when the plugin uses any APIs that were deprecated in Gradle 4.2 (or perhaps warn, it might be a bit drastic to fail).
5. Gradle tests the plugin version against the most recent Gradle version, by convention. It should warn when the plugin uses any API that were deprecated after 4.2.

Attribution is the tricky piece here. We don't yet know exactly which chunk of build logic is calling a deprecated API, and so can't conditionally warn or not.

One strategy we have here is to distinguish between 'almost certainly this plugin/script' and 'not sure'. For a not sure usage, we'd always warn. For an 'almost certainly' usage, we'd warn or not warn based on the above. Two places where we can be pretty certain is during the execution of the `apply()` method and during the execution of actions. We'd fire build operations for these, and use this stream of information in the deprecation logger. We can incrementally reduce the 'not sure' cases over time.

It might be useful to start with better attribution, rather than start with hiding warnings. In other words, we could start by providing "plugin x uses deprecated APIs and won't work in 5.0" warnings instead of "method x is deprecated and you should use method y instead". This already provides a lot of value (I think). Once this is reliable enough, we can start hiding warnings based on the attribution and other inputs.

**Comment by blindpirate** [comment]
## Tentative plan

### Extra elements in `resources/META-INF/gradle-plugins/<plugin-id>.properties` 

At first, let's introduce three more elements in `resources/META-INF/gradle-plugins/<plugin-id>.properties`:

```
implementation-class=com.mycompany.MyPlugin
min-version=4.0
target-version=4.2
repo=http://plugin.gradle.org/myplugin
```

These properties would be ignored by previous version of Gradle safely so there isn't much influence on previous version.

`min-version` is the minimum version of Gradle API used in the plugin. 
`target-version` is the expected version which plugin author works and fully tests with.

Therefore, all Gradle version would be divided into several sections:

```
| can't provide compatible API | can provide compatible API | can probably compatible API |
|------------------------------|------------|---------------|-----------------------------|
0                       min-version   target-version   next-major
0                            4.0           4.2             5.0 
```

- Gradle lower than `min-version` would refuse to apply the plugin. As an improvement, Gradle should display something like:

```
This plugin requires Gradle 5.0 API, which couldn't be fulfilled by current Gradle version (4.4), you can find more information and versions about <plugin-id> in:

http://plugin.gradle.org/myplugin
```

- `min-version` <= Gradle <= `next-major` could definitely provide all compatible API that the plugin requires.
  - APIs deprecated between `min-version` <= Gradle <= `target-version` would be kept unchanged, e.g. outputted in `WARNING` log level
  - APIs deprecated between `target-version` < Gradle <= `next-major` would be displayed in `INFO` log level.
- Gradle higher than `next-major` could probably provide compatible API but it's not guaranteed. Upon this situation, Gradle should warn something like before the build:

```
You're applying a plugin (target Gradle version 4.2) which might be incompatible with current Gradle version (5.0), you can find more information and versions about <plugin-id> in:

http://plugin.gradle.org/myplugin
```

### Extra API in `DeprecationLogger`

This needs us to make some change in `DeprecationLogger`. Some overloaded methods should be added to provide version information, i.e. in which version it's deprecated:

```
DeprecationLogger.nagUserWith("this has been deprecated in 4.2!", "4.2");
```

### Runtime check 

As pointed out by Adam, the most challenging part is attribution. Basically, the scenarios where we can track where the invocation comes from include:

- `apply()`
- Task actions
- Actions registered by plugin

This might provide some context to `DeprecationLogger`: which plugin this invocation comes from. `DeprecationLogger`(or someone else) could decide if the message should be outputted, and in which log level. What's more, in `TestKit` context, the deprecation warning should always be displayed in `WARNING` level so that plugin authors could realize there's something wrong with their usage of Gradle API.

For 4.4, I'd propose to support limited scenarios (`apply()` and task actions).

@bmuschko @oehme @adammurdoch I'd appreciate your opinions here.

**Comment by oehme** [comment]
Superseded by #3457
