### ISSUE TITLE
build cache: Define max size

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#3346]
If you use the local build cache there is no limit of bytes.
Which means the cache can grow and grow and grow...
It would be great if we can have a option like `local.cacheSize=1024 //1 MB cache size` to define the maximal size of the cache...

It would be great if new cache will remove the oldest one or something like that :) 👍 

> **Note:** I've removed your template because it doesn't fit very well in this issue (IMO). Sry for that 😅

**Comment by big-guy** [comment]
You can define a maximum size: https://docs.gradle.org/current/dsl/org.gradle.caching.local.DirectoryBuildCache.html#org.gradle.caching.local.DirectoryBuildCache:targetSizeInMB

This defaults to 5GB and the least recently used cache entries are deleted first.

**Comment by rjbell4** [comment]
@big-guy This seems to have changed in Gradle 4.6.  We can now only limit based on time, not based on size.

Personally, I see this as a loss.  Can we not _also_ limit by size?  If there's a lot of activity and context switching, I worry that the cache could grow without bound.

**Comment by wolfs** [comment]
@rjbell4 The problem with the size based limit was that it didn't prevent the build cache to go over that limit. It just would trim down the cache to the limit periodically (once a week initially). That means that the build cache would always be over the size limit.

We opted for a periodic cleanup, because that seems to be easier to configure. If your build cache directory grows too big with the periodic cleanup enabled, then you won't be able to make good use of the local build cache at all - so maybe you should disable it.

A size limit is also harder to configure, since we don't know the size of your artifacts. So we would choose a too high limit by default.

Did you actually have the problem that your build cache directory grew too large? If you run into that problem please come back to use and we will try to figure out what went wrong.

**Comment by rjbell4** [comment]
@wolfs I haven't seen this yet, as we are still working on completing and then rolling out our infrastructure.  But I anticipate us having a large number of large artifacts.  _You_ might not know the size of my artifacts, but _I_ do (or at least I should be able to find out), and I can therefore set our cache size to a reasonable value.  So if it's unset by default but available to be set, for example, I can see value in us being able to put an upper bound on the cache size.

I'm just generally concerned that a lot of "context switching" would pull in a lot of cached artifacts in a small about of time, and I really want the build cache to something that "just works" behind the scenes, not something that a user might need to specific concern themselves with.  It's not a good look if a user experiences problems because the cache filled up their remaining disk space.

**Comment by broecirr** [comment]
From a Gradle user's perspective, we have a load of smaller CI nodes running multiple builds with different Gradle versions. With the age limit, I'm left trying to guess what maximum age of build cache will reduce the disk space usage to the point where I don't have to log in and delete the cache occasionally. It feels like the cache size is the variable I'm actually trying to control and now I have a layer of abstraction between my builds and that value.
