### ISSUE TITLE
Spring Dependency Management plugin does not create proper Ivy metadata for dependencies

### ISSUE THREAD

**Issue by iNikem** [gradle/gradle#3451]
Here is my build script:

```
plugins {
  id "org.springframework.boot" version "1.5.8.RELEASE"
}

apply plugin: 'ivy-publish'

group 'eu.plumbr'
version '1.0-SNAPSHOT'

repositories {
  jcenter()
}

dependencies {
  compile('org.springframework.boot:spring-boot-starter-web')
}

publishing {
  publications {
    'Main'(IvyPublication) {
      from components.java
    }
  }
}
```
The version for `org.springframework.boot:spring-boot-starter-web` dependency is not specified in the build file, it is provided by  `org.springframework.boot` plugin.

Now I generate ivy.xml for publishing with `generateDescriptorFileForMainPublication` task

The following ivy.xml is generated:
```
<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0">
  <info organisation="eu.plumbr" module="test" revision="1.0-SNAPSHOT" status="integration" publication="20171110231740"/>
  <configurations>
    <conf name="compile" visibility="public"/>
    <conf name="default" visibility="public" extends="compile,runtime"/>
    <conf name="runtime" visibility="public"/>
  </configurations>
  <publications>
    <artifact name="test" type="jar" ext="jar" conf="compile"/>
  </publications>
  <dependencies>
    <dependency org="org.springframework.boot" name="spring-boot-starter-web" conf="compile-&gt;default"/>
  </dependencies>
</ivy-module>
```
### Expected Behavior
Dependency `spring-boot-starter-web` should have `rev` attribute with correct version, as required by Ivy file format.

### Current Behavior
There is no `rev` attribute so parsing this ivy file while consuming published dependency fails with `cvc-complex-type.4: Attribute 'rev' must appear on element 'dependency'`

**Comment by bmuschko** [comment]
The Spring Boot plugin applies the Dependency Management plugin under the covers. The Dependency Management plugin knows how to handle BOMs in Gradle. That's why you can declare a dependency `org.springframework.boot:spring-boot-starter-web` without a version. The Dependency Management plugin translate this information (including the resolved version) for use with the Maven Publish plugin for publishing purposes. I believe it does not configure the Ivy Publish plugin out-of-the-box. Is a correct assessment, @wilkinsona?

If you wanted to configure the information for the purpose of publishing to a Ivy repository then you'd have to map the resolved dependencies into the XML that can be understood by Ivy.

**Comment by iNikem** [comment]
The same problem happens with `org.jetbrains.kotlin.jvm` plugin from Jetbrains

**Comment by wilkinsona** [comment]
> I believe it does not configure the Ivy Publish plugin out-of-the-box. Is a correct assessment, @wilkinsona?

Yes, that’s correct.

@iNikem Integrating with the Ivy Publish plugin could be considered as an enhancement to the Dependency Management plugin. If you’d like to explore that possibility, please [open an issue](https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/new).

**Comment by bigdaz** [comment]
This will be the case for any plugin that uses `Configuration.beforeResolve` to modify dependencies: since Gradle does not resolve the configuration prior to publishing, these changes are not seen in the published metadata.

@wilkinsona FYI we've added a new `Configuration.withDependencies()`, which allows rule-based mutation of dependencies in a configuration, and these rules will apply when a configuration is consumed in _any_ way:
- As part of a project dependency
- As a substitute project in a composite build
- When the configuration is published using `ivy-publish` or `maven-publish`

Note that this API is still very-much incubating, so I'm not suggesting you migrate just yet. Just FYI.

**Comment by bigdaz** [comment]
@iNikem thanks for reporting. I'm closing this as the fix will need to be made in the Spring Dependency Management plugin.
