### ISSUE TITLE
Generated Gradle metadata should include correct version constraints for static dependency version

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#3454]
Incorrect version constraints are generated for a dependency declaration that uses a static version in the Gradle DSL.

### Expected Behavior

Given this:

```
dependencies {
    implementation 'group:lib:1.2'
}
```

This declaration says "require anything >= 1.2 and prefer 1.2", which should end up something like the following:

```
"version": { "prefer": "1.2", "rejects": ["<1.2"] }
```

("<1.2" isn't the correct syntax, it's just for illustration purposes)

### Current Behavior

The following constraint is generated instead:

```
"version": { "prefer": "1.2" }
```

This says "accept any version but prefer 1.2" which is incorrect.

**Comment by melix** [comment]
Comment from @bigdaz on #3440 :

Let's ignore the 'status' for now, since that shouldn't really be part of the version matcher at all.
Then, I think we can translate each version string input into either:
a) An exact version
b) A well-defined version range.
c) A deprecated, opaque version that we can't fully translate

For a & b, we can calculate the exact complement to use for `reject`.

input | prefer | reject | notes
------ | ------  | ------- | ------
1.2 | 1.2 | (,1.2[ 
strictly 1.2 | 1.2 | (,1.2[ + ]1.2,)
[1.2,) | [1.2,) | (,1.2[
strictly [1.2,) | [1.2,) | (,1.2[ | strictly has no meaning
(1,2,) | ]1,2,) | (,1.2] 
strictly (1.2,) | ]1.2,) | (,1.2] | strictly has no meaning
[2.0,3.0) | [2.0,3.0[ | (,2.0)
strictly [2.0,3.0) | [2.0,3.0[ | (,2.0) + [3.0,) 
1.+ | [1.0, 2) | (,1.0[ + [2,) | Not certain this is exactly the same meaning
1+ | n/a | n/a | No translation possible: cannot publish to module metadata
| + | (,) | (,) | None preferred (will use latest), but also none rejected
latest | (,) | (,) | Exactly the same as '+'

For reference, we already have a test for computing the complement for "strict": https://github.com/gradle/gradle/blob/6e07561ffb0997b327f3ed919580f5bc788cc12c/subprojects/dependency-management/src/test/groovy/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/strategy/DefaultVersionSelectorSchemeTest.groovy#L83-L123

**Comment by bigdaz** [comment]
We now persist `strictly`, `prefer` and `require` in module metadata, rather than attempting to decompose these into `prefer` and `reject`.
