### ISSUE TITLE
Missing default imports in userguide

### ISSUE THREAD

**Issue by taigi100** [gradle/gradle#3501]
In the userguide, chapter 18.8, Default Imports instead of having the list with default imports there's the following error: 
`Unresolved directive in <stdin> - include::../../../build/generated-resources/main/default-imports.txt[]`

Url: https://docs.gradle.org/current/userguide/writing_build_scripts.html#script-default-imports

**Comment by oehme** [comment]
@wolfs May I assign this to you since you recently converted this page?

**Comment by wolfs** [comment]
@taigi100 Thank you for reporting. This has been already fixed by https://github.com/gradle/gradle/pull/3255, but it seems the fix didn't make it into Gradle 4.3.

The documentation for the nightly already shows the fixed results: https://docs.gradle.org/nightly/userguide/writing_build_scripts.html#script-default-imports
