### ISSUE TITLE
Suggestion/Discussion: Public Gradle Slack Workspace/Gitter Channel

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#3518]
I had a conversation with @eriwen about this idea while at Kotlin Conf and offered to turn this into an issue that the community could weigh in.

In my opinion, one of the really valuable backbones of what is helping the Gradle Kotlin DSL community grow is the Gradle Kotlin DSL slack channel. This channel is currently through the larger [KotlinLang Workspace](http://slack.kotlinlang.org/).

I've learned a significant amount about how Gradle works and how to use the API through my interactions with @bamboo, @eskatos and the other community members that have since joined the chat.

I've been a member of this channel for ~11 months now and because of what I've learned I'm now able to help other developers with their problems and questions. I also regularly comment on issues opened against the project.

The Slack Channel made the project and the team members much more accessible which drew me into the community. I've since become pretty passionate about the project and have been contributing fixes and features to help move the project forward.

I propose that Gradle offer a public Slack Workspace or Gitter Channel for the general public.

There are various pros/cons that may come with this:

### Cons
- Issues/problems resolved through slack/gitter are not indexed and available to the public via search engine (problems resolved in the forum or stack overflow are).
- Gradle engineers may become distracted by requests for support.
- Without a paid Slack Workspace only the 10K most recent messages are searchable.
- Another communication medium that needs to be moderated.

### Pros
- Helps build a larger community around the Gradle project.
- Provides a medium with a fast feedback loop for developers that need support.
- Outside contributors will be able to help one another and can grow to be self supporting.
- Popular plugin authors can create channels specifically for support with their plugin without needing to create their own slack/gitter chat.
- Great medium for networking.

## Slack vs. Gitter

I've used both. For projects that are large and will have larger communities I think that Slack makes more sense.

### Gitter
If you are dealing with a smaller communities Gitter is much more accessible but your are much more likely to get "drive by support" style questions.
You can create a Gitter account using your GitHub account. Joining a channel is really easy.
Gitter supports GitHub flavored markdown in chat which means you can do language specific syntax highlighting.

### Slack
Requires more work to create an account/login. You have a different account per "Workspace".
Many companies are already using slack so developers can just add it into the existing app they are using for work.
There is also the option to integrate a gitter channel into a slack channel.

**Comment by eriwen** [comment]
@JLLeitschuh Thank you for submitting this issue. One thing that would be especially helpful here is to clarify where the [Gradle Forums](https://discuss.gradle.org) cannot fulfill the community needs.

**Comment by JLLeitschuh** [comment]
I can't really speak to the benefits/shortcomings of the forum format. Personally, I don't really ever use forums. I find (in general) the feedback loop is pretty slow. It's still kind of impersonal as well.

Maybe this would simply cater to people like me, some people like forums. I like the fast feedback loop of a chat system.

**Comment by twwwt** [comment]
@JLLeitschuh A fast feadback loop is less important than a qualified answer. In my opinion, a forum is a place where users have more freedom to take the time they need to come up with a well-thought answer. What is more, I think a chat lacks the ability to be topic-based; which is to say, a forum is more a question-answer-place (something similar to Stackoverflow) that can be searched. Correct me if Slack provides such features. So, while a chat might indeed be helpful to make progress more quickly (for someone that got stuck), it is also less helpful for someone that got stuck later at the same or a similar point because it is usually harder to find what has been asked before and what were the answers.

One could actually formulate the question starting from the other end: what precisely makes a fast feedback loop hard to achieve or even impossible to achieve in a forum? Certainly not technical aspects. Rather, the way users usually use forums. But that is not an argument against a forum, as I think.

**Comment by mkobit** [comment]
As another view point, the forums as they exist today are not topical.

Here are the current categories:

![gradle_forum_categories](https://user-images.githubusercontent.com/1447148/32969754-e28003f2-cbab-11e7-9485-f6046fec5a0a.png)

Which is essentially just the **Help** category.

I don't believe that these cover the different topics that people care about, and the forums make it more difficult for smaller sub communities to form around areas of interest. I find myself generally avoiding the forum due to low activity, (some) low effort posts, infrequent use of tags (https://discuss.gradle.org/tags/), and questions I would not answer or be interested in.

I could see a few areas where this could be more broadly expanded, and where natural growth of these communities might occur:

* contributing
* build-cache
* plugin-developers (can probably be broken down more)
* junit5
* kotlin-dsl
* android

A counter-point to having a Slack is that there are multiple different avenues of communication that exists today, and having more could lead to even more fragmented information:

* https://twitter.com/gradle
* This repository's issues
* https://blog.gradle.org/
* https://discuss.gradle.org
* https://stackoverflow.com/questions/tagged/gradle

I don't think adding a centrally supported chat (specifically Slack) will have a negative impact, as other communities have had great success when using it in addition to their other communication protocols:

* http://slack.kotlinlang.org/
* http://slack.k8s.io/
* https://dockercommunity.slack.com/
* GoLang

I think Slack is generally just "easier" for people to use right now, because they are already using it and already in the pattern of communicating that way. My guess is the community participation when Gradle moved from JIRA to GitHub grew a _huge_ amount, so moving to larger platforms might be another big benefit!

**Comment by eskatos** [comment]
Something to consider: the `#gradle` IRC channel on freenode has been around for a long time. Activity is not that high but constant with a small hundred of people on average.

- http://webchat.freenode.net/?channels=gradle using Freenode web chat
- `irc://irc.freenode.net:6667/%23gradle` using any irc client, console, desktop or web

IRC is not as _nice_ as Slack/Gitter/YouNameYourWebChat and many people don't like it. But the opposite is also true, tastes and colors. There are IRC gateways for Slack and others though. Some communities use those successfully (e.g. PouchDB).

**Comment by hzsweers** [comment]
Another alternative worth mentioning - https://github.com/blog/2471-introducing-team-discussions

**Comment by eriwen** [comment]
Hello everyone! Today I am excited to introduce you to [Gradle Community Slack](https://gradle-community.slack.com/)! You can email me eric@gradle.com for an invite. Hope to see you in there!

**Comment by ghilainm** [comment]
@eriwen Hellow, the link is not working anymore, is it still possible to join?

**Comment by JLLeitschuh** [comment]
Here is a link that currently works:
https://is.gd/xPCSJh

**Comment by ghilainm** [comment]
Doesn’t work for me 😩😭

**Comment by JLLeitschuh** [comment]
Here's one I just confirmed should work:
http://gradl.es/slack-invite-2019

**Comment by michalszynkiewicz** [comment]
It seems this link is not active anymore now

**Comment by eriwen** [comment]
Here we go: https://gradl.es/slack-invite-2020

**Comment by roded** [comment]
Is the Gradle slack still active?
