### ISSUE TITLE
Don't look for jars if pom file is missing when legacy Maven behavior is disabled

### ISSUE THREAD

**Issue by melix** [gradle/gradle#3623]
Provide a way to opt-out of the legacy Maven behavior, which is to try to find a jar file if a module doesn't provide a pom file. This can lead to lots of unnecessary network requests when a module will __not__ be found in a specific repository.

**Comment by bigdaz** [comment]
@melix I think we should also change the default behaviour when using the `experimentalFeatures` flag.

**Comment by bigdaz** [comment]
@melix I've "merged" your PR with a bunch of rework and refactoring. The big difference is that the link between the DSL `metadataSources` and the instances used in `ExternalResourceResolver` is much simpler and a lot more hard-coded. We translate the user config to a set of booleans to decide which metadata sources to use, and instantiate them directly if required. This is sufficient for what we need.

I brought over your `LegacyArtifactLookupResolveIntegrationTest` but I think we need a bit more test coverage for different combinations of `metadataSources`. Luckily the `FlatDirectoryArtifactRepository` is just an ivy repository with only the `artifact()` metadata source configured, but we probably want to test things like:
- Opt-out of `gradleMetadata()` and see that the `.module` file isn't requested
- Opt-in to `artifact()` with experimentalFeatures and see that we check for a `jar` file
- Some other combinations of metadata sources, including just `mavenPom()` or just `ivyDescriptor()` or just `gradleMetadata()`
  - We might want to update `AbstractModuleDependencyResolveTest` so that in most cases we just test a single metadata source, and then have some separate tests that verify they work in combination.
