### ISSUE TITLE
Finalizer task not invoked when dependent task failed

### ISSUE THREAD

**Issue by koral--** [gradle/gradle#3691]
Finalizer is task not invoked when dependent task failed in normal run. However it is invoked in dry run.
Dry run, `tearDown` task is listed.
```
$ ./gradlew -m foo
Parallel execution with configuration on demand is an incubating feature.
:plugin:doWork SKIPPED
:plugin:foo SKIPPED
:plugin:tearDown SKIPPED
```

### Expected Behavior
`tearDown` task should be invoked:
```
$ ./gradlew foo
Parallel execution with configuration on demand is an incubating feature.

> Task :plugin:tearDown 
Cleaning


FAILURE: Build failed with an exception.

* Where:
Build file '/home/koral/workspace/finalizer/plugin/build.gradle' line: 74

* What went wrong:
Execution failed for task ':plugin:doWork'.
> java.lang.Exception: test

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
2 actionable tasks: 2 executed

```

### Current Behavior
Normal run, `tearDown` task is not invoked.
```
$ ./gradlew foo
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/koral/workspace/finalizer/plugin/build.gradle' line: 74

* What went wrong:
Execution failed for task ':plugin:doWork'.
> java.lang.Exception: test

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed

```

### Steps to Reproduce (for bugs)
run `./gradlew foo` with provided sample:
```
task doWork {
    doLast {
        throw new Exception("test")
    }
}

task tearDown {
    doLast {
        println "Cleaning"
    }
}

task foo {
    dependsOn doWork
    finalizedBy tearDown
}
```
### Your Environment
Gradle 4.3.1

**Comment by nishantghan** [comment]
Was this issue resolved?

**Comment by big-guy** [comment]
I think this is working as designed.  `foo` is finalized by `tearDown`, but `foo` is never executed, so the finalizer does not need to run.

The dry-run case looks different because it shows the potential list of tasks, assuming that they all execute.

**Comment by rootkraut** [comment]
Hi @big-guy 

but why is foo never executed? We start the foo task with "./gradlew foo" then "doWork" is executed first because of the "dependsOn doWork" (note: exception is only thrown in the doLast) then the exception is thrown by "doWork" and then I also expect that the "finalizedBy tearDown" is executed for the foo task.

If this is not the intent of "finalizedBy" how can we gracefully handle exceptions?
We had the problem when we tried to shutdown external services but one of our task threw an error.

Thanks and best regards

**Comment by big-guy** [comment]
`foo` is never executed because its dependencies failed. 

It's kind of the same thing as this code:
```
doWork(); // throws Exception
try {
    foo();
} finally {
    tearDown();
}
```

You might be able to make this work the way you want by having the task that starts up the external service be finalizedBy the tear down _and_ the task that needs the external service to be finalized by the tear down.  It depends on what you need to do.

**Comment by dagguh** [comment]
Sometimes the task dependencies are out of your control. They might be dynamically generated by a plugin. It's hard to find all of them and attach `finalizedBy` to each of them.
