### ISSUE TITLE
Analyse performance of dependency resolution with improved pom support

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3723]
Currently, we only create dependency constraints for a `<dependencyManagement>` element in a BOM (POM with packaging='pom'). With this change, we'll treat `<dependencyManagement>` consistently for every consumed Maven POM.

This change may a broader impact:
- Performance implications of many more dependency constraints
- Behaviour changes due to honouring dependency management elements transitively

**Comment by jjohannes** [comment]
Some insights from the performance experiment on the _exclude rule_ example project.

There is a significant negative performance impact. However, the impact is already there with the current solution, where we only consume some of the dependencyManagement blocks.
So if we improve performance in general, which we should, the difference might be less significant (probably related to performances issues discussed in #3870).

- [Results with current implementation](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceExperimentCoordinator/10315417:id/report-performance-performance-tests.zip%21/report/tests/resolveDependencies-on-exclude-merging-project-with-advanced-pom-support.html)
- [Results with an experimental implementation of this issue](https://builds.gradle.org/repository/download/Gradle_Check_PerformanceExperimentCoordinator/10316015:id/report-performance-performance-tests.zip%21/report/tests/resolveDependencies-on-exclude-merging-project-with-advanced-pom-support.html)

Impact on resolutions result through the experimental change: https://e.grdev.net/c/3zhcrypekdgym/2icfyi32kd6ms/dependencies

**Comment by melix** [comment]
So here are the results of various experiments I have made on the [cc/dependency-management/measure-advanced-pom](https://github.com/gradle/gradle/tree/cc/dependency-management/measure-advanced-pom) branch.

There are some good and bad news. There were 2 different things we wanted to understand:

a. what is the impact of enabling the "advanced POM support" by default
b. what would be the impact of considering all `dependencyManagement` blocks as constraints, whether it's a BOM or not

I started with using the `exclude rule merging` performance test. The difference for a. is around 10% slower. It turns out that most of the difference doesn't come from adding dependency management block as pending dependencies: it's the fact that we use variant aware matching in this case (Maven dependencies are mapped to "real" variants when advanced pom support is enabled). In particular, attribute matching is very expensive, and coercion of attributes is even more:

![selection_134](https://user-images.githubusercontent.com/316357/35737423-afe38b28-082b-11e8-8b2e-999d89421cf5.png)

To identify the impact of _just_ BOM support, I disabled the mapping to variants. The results were conclusive, with an overhead of just about 2%, which is pretty reasonable.

First conclusion: variant selection is extremely expensive, more than the configuration based selection, and needs serious optimization.

I also noticed a few quick wins in terms of performance during dependency resolution, will isolate some commits and submit a pull request for those. Most of them are on _exclude rule merging_ itself, so not related to this topic. So, in order to measure the real impact of enabling dependency management blocks as constraints everywhere, I modified the template project that we use for exclude rule merging, to _not define excludes_. There might be a few excludes left, those defined in Ivy or Maven descriptors, for example, but most of dependency resolution is happening without exclude merging.

In that case, we can see that b. is significantly slower: at best, it's 30% slower. The difference is almost exclusively due to more conflict resolution and basically more components being resolved. In particular, a lot more component metadata is read from disk (when we re-enable variant generation, it's like 60% slower, which is just crazy at this point). Note that the test project is a pathological case, it's really big and has a lot of dynamic dependencies.

The flame graph shows multiple potential areas of improvement, but none of them are trivial. In particular, caching dependency substitution rules turns out to be a hotspot, because the cache key is expensive to compare. We also reset a lot of state, like removing incoming or outgoing edges, and it's expensive with `LinkedList`. Conflict resolution handling also shows up as costly. Basically, I think it's going to be hard to improve without changing the algorithms and the underlying data structures used during selection.

**Comment by melix** [comment]
I'm doing some more measurements on top of the `cc/dep[endency-management/perf-improvements` branch. I'll post some results here as I go.

First, with advanced POM support enabled, `CachingDependencySubstitutionApplicator` represents about a fourth of the `visitOutgoingDependencies` cost, which is pretty high knowing that in most cases if we're lucky, there's no substitution at all:

![selection_131](https://user-images.githubusercontent.com/316357/35797078-df058174-0a5e-11e8-8ef3-451dc053e74b.png)

**Comment by melix** [comment]
This [flame graph](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/10791817:id/results/performance/build/test-results-performanceAdhocTest.zip%21/flames/honestprofiler_resolve_large_dependency_graph-4.6-20180205133308_0000.svg) is the latest of all. It involves:

- "advanced" POM support enabled, including mapping to variants
- does **not** consider all `<dependencyManagement>` blocks as constraints (only those from BOMs)
- builds on top of the "performance fixes" branch

It clearly shows that we have 2 big contributors:

- getting component metadata, which indicates that at some point, we need the metadata for specific revisions. There are multiple paths there, from dynamic resolution to just selection of a variant
- variant selection, which is slow because of attribute matching. Just use the search button on the graph to search for "AttributeMatching" to give you an idea.
- conflict resolution, which triggers a lot of restarts

The conflict resolution is a direct consequence of having more constraints.

To make things faster, we can probably:

- investigate if it's possible to avoid getting metadata before hand, just knowing the version numbers (seems pretty hard)
- investigate parallel graph resolution (good luck with thread safety)
- optimize `ModuleMetadataStore`, which is the cache of binary descriptors. It turns out that the checks for existence of the metadata file itself are pretty costly. We do 2 checks (file exists, temporary file exists), which are very visible in that part of the graph. However, it's probably visible because we read a **lot** of descriptors from disk.

**Comment by melix** [comment]
Another discovery that can help performance: the `ExternalDependencyDescriptor#getMetadataForConfigurations` method is called, on the test project, 20% of times with the very same arguments as the last call. Since what happens in there is expensive, it means we have a cheap way to improve performance by caching the result of the call there. I have made such an experiment [here](https://builds.gradle.org/repository/download/Gradle_Util_Performance_AdHocPerformanceScenarioLinux/10793710:id/results/performance/build/test-results-performanceAdhocTest.zip%21/flames/honestprofiler_resolve_large_dependency_graph-4.6-20180205033915_0000.svg), which shows a significant reduction in time spent in `getMetadataForConfigurations` compared to the previous flame graph. It's still not free, but cheaper.

**Comment by bigdaz** [comment]
I'd be reluctant to add another layer of caching for `ExternalDependencyDescriptor#getMetadataForConfigurations` without first optimizing the hell out of the things that it's doing. I'm sure given some effort we can find inefficiencies that will buy us some time.

Every time we add another layer of caching, things get a bit more complicated...

**Comment by melix** [comment]
Note that by "caching" here I only mean "avoid recomputing", so it's local. But yeah, I agree with you.
