### ISSUE TITLE
Startup failed - problem with moving Curly Brackets to Next line

### ISSUE THREAD

**Issue by Yousha** [gradle/gradle#3805]
This bug is NOT related to Android Studio

### Expected Behavior
Success build

### Current Behavior
Startup fails in my build script
Because I moved `task`'s **BRACKET to the Next Line**
Instead of leaving them on same line

### Context
Nothing special, just a build like always

### Steps to Reproduce (for bugs)
Make a simple project (any type/language) then add the following line to its build.gradle file:
```
task clean(type:Delete) 
{
   delete rootProject.buildDir
}
```
then you will get this error:

> Error:(24, 0) startup failed:
> build file 'C:\Users\Y\Workspace\Java\Test\build.gradle': 24: Ambiguous expression could be a parameterless closure expression, an isolated open code block, or it may continue a previous statement;
>    solution: Add an explicit parameter list, e.g. {it -> ...}, or force it to be treated as an open block by giving it a label, e.g. L:{...}, and also either remove the previous newline, or add an explicit semicolon ';' @ line 24, column 7.
>          {
>          ^
> 1 error
Because Gradle cant handle it if the **BRACKET move to the Next Line**

### Your Environment
Oracle JDK 8 64bit

Windows 7 64bit

Gradle 4.4
Build time:   2017-12-06 09:05:06 UTC
Revision:     c f7821a6f79f8e2a598df21780e3ff7ce8db2b82
Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 20
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)

What's the problem with moving Brackets to the next line?!

**Comment by blindpirate** [comment]
Thanks for reporting, but I'm afraid that's intentional. Let me tell me what happened under the hood.

A Gradle script is actually a groovy script. In groovy, `{...}` may be interpreted as a closure (and maybe not, it depends on the context), which is so-called ["context-sensitive grammar"](https://en.wikipedia.org/wiki/Context-sensitive_grammar).

When you write:

```
task clean(type:Delete)  {
   delete rootProject.buildDir
}
```

Groovy parser will interpret it as:

```
task('clean', [type: Delete], {closure})
```

This is a method invocation, with method name `task`, 3 arguments:

- String 'clean'
- Map ["type": Delete.class]
-  A closure

In Groovy, when last argument of method invocation is closure, it can be put outside the parentheses.

When you move `{` to next line, it's totally different. Groovy won't see `{}` as the last argument of method invocation. Instead, it can't decide whether it's a closure declaration or code block. That's called "disambiguation" in a parser. So it happens.

**Comment by hatef77** [comment]
what should I delete here ? 
**''C:\Users\panama\build.gradle': 16: expecting '}', found '' @ line 16, column 20.
               jcenter**
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {


    repositories {
        maven { url 'https://maven.google.com ;jcenter' }
    }
    allprojects {
        repositories {
            maven { url '\'https://maven.google.com\' ;jcenter' }
        }
    }
    allprojects {
        repositories {
            maven { url '\'https://maven.google.com' }
            jcenter

**Comment by ahmedshabbirawan** [comment]
In my case i have missing the "}". So i have review the code and add it. 
its work fine
