### ISSUE TITLE
Allow dependency constraints to provide a descriptive reason

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#3820]
Dependency constraints alter the way a set of dependencies is resolved. Use cases include to provide a rule to reject a particular dependency version, or to substitute one module version with another. For these cases, it would be useful for a declared constraint to provide a descriptive reason as to why the constraint is required.

- Allow a dependency constraint to provide a description
- When a dependency constraint has an impact on the selection of a module version, make that reason available in the `ComponentSelectionReason` for that module node in the `ResolutionResult`

**Comment by melix** [comment]
So here's a summary of the spikes I've worked on for reporting. There are basically 4 different things:

1. adding a description to _rules_
2. adding a description to _dependencies_ and _constraints_
3. making the difference between selection by a constraint and a selection by a dependency
4. showing rich version constraints in the report

My experiments focused mostly on 1., 2. and 3. I have learnt how this plays with `ComponentSelectionReason`, which lead to this [first branch](https://github.com/gradle/gradle/tree/cc/dependency-management/spike-component-selection-reason). This reworks how `ComponentSelectionReason` is implemented, while maintaining backwards compatibility, in order to support richer descriptions. In particular, the "causes" are now a proper `enum`, with a default textual description which _can_ be overwritten. This greatly improves the implementation of 1., while being the root for the others.

Then I checked how to make it possible to report reasons to dependencies and/or constraints. I spiked it with a simple example. Imagine you have:

```
constraints {
   implementation('org:foo') {
      version { prefer '[1.0, 1.4]'; reject '1.4' }
      reason '1.4 has a critical bug'
   }
}
```
Then the dependency insight report would show:

```
:dependencyInsight
org:foo:1.3 (1.4 has a critical bug)
```
In other words, it makes it possible to attach a description to a constraint _or_ a dependency. If such a description is available, the report shows it. It's worth noting that because it builds on top of the branch, it _should_ be possible to have _all_ reasons here, so if metadata defines a reason, which is overwritten in a rule, it should be possible to show them both. I'm not sure we need to do it for the dependency insight report (because it's ascii, and it's hard to get a condensed view), but the API would make it possible.

Eventually, we need to be able to make a difference between a version selected by a constraint, and a version selected by a dependency (or, said differently, when a constraint had an influence in the selection of a version of a dependency). One option would be to use the same label, but it kind of conflicts. The second option is not to make a difference, and just let the constraint description be used if there's one. Last option would be to use a visual indicator that a constraint participated in selection (say, `(dc)`), and use the reason in addition if one was provided. In any case, all this _is_ using the same API, so is available in the `ResolutionResult`.

This solution also binds 1. and 2. together, by saying that the rule description is actually declared by setting a description on the constraint itself. This has the advantage of not having to create an adhoc infrastructure for the new rules.

However, I also reckoned that having a "reason" on dependencies and constraints _could_ be used by build authors for 2 different purposes:

a. describing the reason why the version is used ("1.1 is not binary compatible")
b. describing _why_ the dependency is here ("required for parsing JSON files")

The intent when we got started on "reason" was a., I wonder if it's a problem if people _also_ use it for b., and if we want to separate them.

Eventually, the spike doesn't deal at all with persisting this description. It would typically need to appear in the Gradle module metadata file.
