### ISSUE TITLE
gradle-4.4 native software support injects unexpected -I flags 

### ISSUE THREAD

**Issue by vvlevchenko** [gradle/gradle#3900]
With upgrade on cradle 4.4 we found that c/c++ plugins inject -I/usr/include for clang toolchain on mac and -I/usr/include/x86_64-linux-gnu on linux that affects applications that set up system root. as workaround we have to remove injected flags, see https://github.com/JetBrains/kotlin-native/commit/56a214c45449908a9e72cbc4f951da77fb408424.

**Comment by wolfs** [comment]
Starting with Gradle 4.4, we detect system includes for each compiler and add them to the includes of the compile path so they are tracked for change detection (incremental build + build cache).
You could try to edit `C{pp}Compile.includes` directly instead of modifying the actual arguments for the invocation.
How would you expect the feature to work? Should we check if the `--sysroot` argument is present and then change the current behaviour?
I guess the right thing to do would be to pass the corresponding `--sysroot` argument to `GccMetadataProvider.getCompilerMetaData` as additional arguments. The best thing would be to configure `DefaultGccPlatformToolChain.compilerProbeArgs` and add the `--sysroot` argument there, but that is not possible now.
WDYT?

**Comment by vvlevchenko** [comment]
It's really hard to say, perhaps it's better to track includes that user has specified rather then add additional ones.

> How would you expect the feature to work?

I'd like minimal impact of plugin on arguments supposed to be passed to compiler :)  
 
> Should we check if the --sysroot argument is present and then change the current behaviour?

If there're no other option we can live with it.

**Comment by coreybrenner** [comment]
I've hit this issue, as well, and others that are related.

We build our native software for dozens of platforms, using dozens of toolchains on a handful of host platforms.  The default handling of Gcc/Clang toolchains causes this failure with iOS platforms, and a pretty similar issue happens when trying to tune a Gcc toolchain to run the QNX toolchain's 'qcc' compiler driver.  Similarly, the VisualCpp toolchain configurator assumes a little too much, when setting up a C/C++ toolchain.  In this case, it makes it a lot tougher to configure a custom toolchain environment to run a very old version of the MSVC toolchain for a WindowsCE platform.

Is there a point of contact, or a group, for discussing how to dial back the "smartness" of Gradle's toolchain handling just a touch?  Is there a way to override the behavior of the compiler metadata gathering sweep, so that I could provide my own command line arguments?  Alternatively, how do I become a Gradle developer so I can help?

**Comment by big-guy** [comment]
Hi @coreybrenner, 

We have a project going now to revamp the way native builds are done with Gradle at https://github.com/gradle/gradle-native.  This [blog post](https://blog.gradle.org/introducing-the-new-cpp-plugins) talks about some of the progress we've made so far.  One of the important things has been proper dependency management (transitive dependencies, publishing/resolving binary dependencies, composite builds).

Cross-compilation and custom toolchains (like qcc) isn't on our short-term plan, but we know those are important use cases. We're building up a [set of samples](https://github.com/gradle/native-samples) to demonstrate what's possible.

The most useful thing you could do is describe some of your use cases (like you've started here) as issues on https://github.com/gradle/gradle-native and include any details about how you make things work today.  For this particular issue, it was important to get the system includes for the build cache key into the compilation task, but there may be some workaround to get this back to what it was.  [This is JetBrains workaround](https://github.com/JetBrains/kotlin-native/blob/38069d47ea254e55533de6abe6a7e1d022b577de/libclangext/build.gradle#L43-L55).

I've opened a [new issue](https://github.com/gradle/gradle-native/issues/493) so we can discuss it as a team next Monday.

**Comment by big-guy** [comment]
This issue was migrated to https://github.com/gradle/gradle-native/issues/493.
