### ISSUE TITLE
Generated eclipse project has wrong doubled name if root dir name equals subproject name

### ISSUE THREAD

**Issue by dpolivaev** [gradle/gradle#3903]
### Expected Behavior

Given root directory called "root" containing two subprojects in folders "root" and "depending"
eclipse plugin should generate two eclipse projects called "root" "and "depending"

### Current Behavior
Currently projects get  names "root-root" and "depending"

### Steps to Reproduce (for bugs)
* extract attached archive , 
* go to directory "root" containing files settings.gradle and build.gradle, and 
* execute "gradle eclipse"
* Check content of generated files root/root/.project and root/depending/.classpath
[gradle-bug.zip](https://github.com/gradle/gradle/files/1587146/gradle-bug.zip)

### Your Environment
gradle 4.4.1 , Windows 10, JDK 8

**Comment by bmuschko** [comment]
I believe Eclipse cannot handle two projects with the same name due to it's flat project structure. To remediate the situation, the Eclipse plugin tries to find unique project names.

**Comment by dpolivaev** [comment]
There is no third project. No .project file is needed or generated for the upper root directory. 
In the older gradle versions it worked as I expect, and the change has come with some Gradle update.
I noticed it because name of my existing eclipse project has changed as I described.

**Comment by donat** [comment]
@dpolivaev If you have both the root project and a child project named `root`, then the names must be deduplicated by the `eclipse` plugin, otherwise you won't be able to import all projects into Eclipse.

You can do two things. Either rename your root project in your `settings.gradle` file

rootProject.name = 'custom-root'

or customize the project name in the `eclipse` plugin configuration.

    apply plugin: 'eclipse'
    
    eclipse {
        project {
            name = 'custom-root'
        }
    }
