### ISSUE TITLE
Add information about variants to dependencies report

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#4006]
- Display selected variant in dependencies report
- Display variant matching result in dependency-insight report

Start with a spike.

**Comment by melix** [comment]
So, after multiple tries, I _think_ I have a spike that is close to what we want. To summarize, we want to:

- show the selected variant in the dependency insight report
- a selected variant consists of a display name and variant attributes
- the variant attributes constitute the _identity_ of the variant, the display name is here mostly for reporting

The initial spikes showed that adding variant information can easily add noise to the report, so the spike introduces a `--show-variant-details` flag. Without this flag, the outcome is not changed. If the flag is added, then we display additional information.

Part of the problem is the density of information we need: showing the attributes is nice, but doesn't help if we don't know what were the _requested_ attributes. So, here's a screencast showing what I have now:

![variant-details](https://user-images.githubusercontent.com/316357/35332674-1324c7aa-010c-11e8-8ff9-4a54b97669d6.gif)

We can see that with the flag, we display additional information, regarding variants. Today, it's mostly available on projects, that's why I used a project dependency in the report. It shows that we can display the variant display name, and additional information regarding the _requested attributes_:

```
> Task :dependencyManagement:dependencyInsight 
project :core
   variant "runtimeElements" [
      org.gradle.usage = java-runtime-jars (requested was: java-runtime)
      minified         = true (requested)
   ]
+--- runtimeClasspath
+--- project :versionControl
|    \--- runtimeClasspath
\--- project :resourcesHttp
     \--- runtimeClasspath
```

Here, it shows that the selected variant has 2 attributes:

- `org.gradle.usage`, with a value of `java-runtime-jars`. But it shows that the requested value was actually `java-runtime` (so we selected a _compatible_ variant)
- `minified`, with a value of `true`, which was also requested

Sometimes, we can find attributes on a variant which were _not_ requested, in which case it shows up like this:

```
:dependencyInsight
org.test:leaf:1.0
  variant "api" [
     org.gradle.usage  = java-api (requested)
     org.gradle.test   = published attribute (not requested)
     org.gradle.status = release (not requested)
  ]
\--- org.test:a:1.0
    \--- compileClasspath
```

The last case is when an attribute was requested, but the selected variant doesn't have it. For this, I chose to display them below:

```
:dependencyInsight
org.test:leaf:1.0
  variant "api" [
     org.gradle.usage  = java-api (requested)
     org.gradle.test   = published attribute (not requested)
     org.gradle.status = release (not requested)

     Requested attributes not found in the selected variant:
        org.gradle.blah   = something
  ]
\--- org.test:a:1.0
    \--- compileClasspath
```

And to check what it means in "real world", I generated a report for an Android project:

`gl :subvola:gorgoneum:teerer:polytonal:dependencyInsight --configuration debugAndroidTestRuntimeClasspath --dependency carnally --show-variant-details`

```
project :outissue:carnally
   variant "debugRuntimeElements" [
      com.android.build.api.attributes.BuildTypeAttr               = debug (requested)
      com.android.build.gradle.internal.dependency.VariantAttr     = debug (not requested)
      org.gradle.usage                                             = java-runtime (requested)
      com.android.build.gradle.internal.dependency.AndroidTypeAttr = Aar (requested)
   ]
+--- project :outissue:caricetum:midship
|    +--- project :outissue:airified
|    |    \--- project :fratry:sodden
|    |         \--- debugAndroidTestRuntimeClasspath
|    +--- project :outissue:situla
|    |    \--- project :fratry:sodden (*)
|    +--- project :outissue:extended
|    |    +--- debugAndroidTestRuntimeClasspath
|    |    +--- project :fratry:sodden (*)
|    |    +--- project :fratry:Krapina
|    |    |    \--- project :fratry:sodden (*)
|    |    +--- project :outissue:situla (*)
|    |    \--- project :fratry:Ormond
|    |         \--- project :fratry:sodden (*)
|    \--- project :outissue:caricetum:skiapod
|         \--- project :fratry:crankum
|              +--- debugAndroidTestRuntimeClasspath
|              \--- project :fratry:sodden (*)
+--- debugAndroidTestRuntimeClasspath
+--- project :outissue:airified (*)
+--- project :outissue:situla (*)
+--- project :outissue:phasmatid
|    \--- project :outissue:situla (*)
\--- project :fratry:sodden (*)

(*) - dependencies omitted (listed previously)
```

What do you think? Should I proceed? (/cc @bigdaz @adammurdoch )

**Comment by bigdaz** [comment]
This is definitely promising. I'm happy to keep working on this. We can tweak the exact layout/format later. For example, we might want to separate out the "Not requested but found" attributes, a bit like we separate out the "Requested but not found". But I think playing around with it on real-world projects will give us a better insight.
