### ISSUE TITLE
When to use gradlePluginPortal() ?

### ISSUE THREAD

**Issue by StefMa** [gradle/gradle#4020]
Hey guys,

I'm not sure if a github issue is correct or I would better to start that discussion on the gradle forums.
But I'll start here. Feel free to just close it 😉

I've notices that "all" bintray plugins are also available at https://repo.gradle.org/gradle/libs/
So I've wondered why the `plugins {}` closure don't work with all the plugins which are published to jcenter.
Let's take a look at [novodas bintray-release](https://github.com/novoda/bintray-release) for example. It is available [here](https://repo.gradle.org/gradle/libs/com/novoda/bintray-release/).
But I can't just say
```kotlin
plugins {
  id("com.novoda.bintray-release") version 0.8.0
}
```
But what I could do is:
```kotlin
buildscript {
  repositories {
    gradlePluginPortal()
  }
  dependencies {
    classpath "com.novoda:bintray-release:0.8.0"
  }
}

apply plugin: "com.novoda.bintray-release"
```
But then I've realized that the gradlePluginPortal() looks at https://plugins.gradle.org/m2/.
So I've tried to look at https://plugins.gradle.org/m2/com/novoda/bintray-release which immediately redirect to https://jcenter.bintray.com/com/novoda/bintray-release/.

To my questino
When should I use the `gradlePluginPortal()` as repository?
Instead of the redirect I can directly use `jcenter()`, right?
Where is the benefit of redirect the gradle portal to jcenter?

**Comment by jjustinic** [comment]
In the case of the Gradle Plugin Portal, the `plugins { }` block relies on a REST service provided by the Portal to translate the plugin ID to maven coordinates. This works for any plugin published to the portal.

While artifacts are currently hosted directly by the portal, they were originally hosted on JCenter, so there is a fallback redirect for anything not found directly in the portal. This also means that you can usually resolve non-plugin plugin dependencies without an extra source.

The redirect occurs because `com.novoda.bintray-release` was published to JCenter, not to the Plugin Portal. If you directly use `jcenter()` only, you will not be able to resolve any plugins published to the Plugin Portal only in your `buildscript { }` block. Using `gradlePluginPortal()` allows you to resolve any plugin in the `buildscript { }` block that is published to the Plugin Portal or JCenter(or Maven Central) without caring where it was published or defining multiple repositories.

**Comment by oehme** [comment]
Closing as this is a question better suited for the forum. Thanks for answering @jjustinic!

Btw Gradle 4.4 no longer uses the rest protocol, but treats the portal like any other Maven repository. It looks for plugin marker poms to map from plugin id to maven coordinates. These are auto generated when you use the `java-gradle-plugin` together with `maven-publish`. This made it possible to mirror the portal.
