### ISSUE TITLE
Add option for max daemons

### ISSUE THREAD

**Issue by mac-pro** [gradle/gradle#4051]
### Expected Behavior

Would you please add option for setting max daemon instances? For example in `gradle.properties`:

```
org.gradle.max-daemons=3
```

So when Gradle tries to start new daemon, it should check current active daemons and proceed to next step, which can be configured as well:

- `org.gradle.max-daemon-response`: can be `wait` (wait for a free slot to be available) or `break` (stop the build).

### Current Behavior

There's no option to control max daemons.

### Context

It would help me a lot. My machine is not capable of handling 3+ daemons at a time.

### Your Environment

Gradle 4.4.1.

Thanks,

**Comment by oehme** [comment]
Could you elaborate why you are seeing too many daemons and why your machine can't handle them?

Gradle only starts a new daemon if projects use different Gradle versions or incompatible JVM args or other daemons are currently busy.

Also, you can adjust the memory settings of the daemon to match what your project needs. For smaller projects you can go as low as 128MB heap.

**Comment by mac-pro** [comment]
Hi @oehme 

My machine has an Intel i5 with 2 cores, 6 GiB of RAM. I run a worker program 24/7 which takes 20% CPU usage. So I have 80% left for Gradle daemons and normal tasks.

I give each Gradle daemon 1.5 GiB of RAM to work. I tried lower values, but the build often crashed with `OutOfMemoryError` (if I remember correctly, it's a long time ago), of it just hung up. 1.5 GiB is the smallest value that I can use.

I often build apk files from an Android project. The project produces about 800 apks, each build takes about 2 minutes to finish. However I have to add 1 minute to "sleep" between builds, so the machine won't halt because of overheat. So for 800 apks, it needs ~2 days to finish.

While those builds run in background, I need to work on other project. When I fire up new Gradle daemon, my machine almost dies  :-D

The problem is while running the second Gradle daemon, sometimes I have to build one third project. If I forget about 2 running daemons, and fire up new one, my machine might halt. Halt means the system automatically powers off because of overheat.

There might be other solutions which I don't know about yet. But in general I think this new option would be great. For example, some package manager in Linux refuses to work if one other instance is running.

With this new option, I can fire new Gradle daemon, let it wait for new available slot, and start its job. For example, with my 1-minute-sleep solution above:

- I'll fire new daemon. It can wait for the other one to sleep.
- When the first daemon sleeps, the second one starts to work.
- If the first one wakes up, while the second one is still working, it can wait.

It looks like a good approach...

**Comment by oehme** [comment]
An 800 module build probably needs more than 1.5GB of RAM. Please analyse it using [build scans](scans.gradle.com) or the [Gradle profiler](https://github.com/gradle/gradle-profiler). My guess is that your machine is just spending all its time garbage collecting, which may be why the build takes so long. Fixing that might fix your other problems.

Regarding the power downs, you might want to take your machine to service. It's not normal that it would shut off, the cooling system should be designed to deal with the maximum heat that your CPU can produce.

**Comment by mac-pro** [comment]
Thank you I understand. I know my machine is old, that's why I have the Mac Pro avatar  :-D  (though they just released iMac Pro).

But I still love this could-be-feature. I think it sounds right, not just for my own needs.

**Comment by oehme** [comment]
A daemon count doesn't really say much. A single daemon with lots of work could already be too much. On the other hand even a slow system can be fine with a dozen small daemons. So if we want limits, we should instead talk about global CPU/memory limits. That might be useful, but won't help for your issue either I'm afraid. Your system is already overloaded with the 800 module build alone. Until there is a better use case for such a global limit feature, I'll close this feature request.

For your specific issue I encourage you to profile the build to find out why it is consuming so much CPU. My bet is on too much GC pressure. I'll be happy to help if you provide a JFR recording.

**Comment by Barteks2x** [comment]
This would still be a very useful feature. I have a few different projects that use different gradle versions (not every project using gradle wrapper uses the same version), and some of them use different JVM args for the gradle JVM (because it needs about 3GB heap to do a fresh gradle build, no way around that), and sometimes even using different JVM (different java version, and IDEs using gradle to import project structure).

After some time, memory usage tends to grow to about 800MB per daemon instance on average, and I have seen daemon count as high as 8 (!), while usually I have about 3 running daemons.

What I would expect it to do, is to start more daemons as needed, but the only keep one of them running in the background (last used one?). Instead, all of them are kept running because there is something different about them.

I don't care about the CPU usage, but the memory usage, combined with just about everything using insane amount of memory, means that even with 16GB of RAM in my system, I still do run out of it.

Unfortunately, even if this is implemented, I don't see how I would benefit from it, if it doesn't actually work in older gradle versions.

**Comment by jacek-lewandowski** [comment]
Indeed, the number of Gradle build up with if you work with multiple projects, many project version which require different Gralde arguments and so on. I really want that feature, especially I'd really like if the old unused daemon could be replaced by the new one, currently i need to manually call `gradle --stop` before switching the project to save system resources

**Comment by calvertdw** [comment]
I have an IntelliJ workspace with 41 Gradle projects added to it. When I launch a Gradle refresh, 41 daemons spin up, fill my RAM, and crash the system. I have 32 GB RAM installed. I think this issue is because I have set `-Xmx=5g` for my other project which needs that for a single build. So my workaround is to temporarily set `-Xmx=150m`, but it would be much more desirable for Gradle to implement a daemon limit, because then each project would build and become ready more quickly, in order, and without needing to temporarily set a Gradle JVM property or fork my Gradle properties, which have lots of other stuff in them.
```
$ gradle --status
   PID STATUS   INFO
 24735 BUSY     7.5.1
 24669 BUSY     7.5.1
 24727 BUSY     7.5.1
 24512 BUSY     7.5.1
 24806 BUSY     7.5.1
 24718 BUSY     7.5.1
 24703 BUSY     7.5.1
 24611 BUSY     7.5.1
 24587 BUSY     7.5.1
 24693 BUSY     7.5.1
 24709 BUSY     7.5.1
 24743 BUSY     7.5.1
 25065 BUSY     7.5.1
 24989 BUSY     7.5.1
 24775 BUSY     7.5.1
 25028 BUSY     7.5.1
 25085 BUSY     7.5.1
 24856 BUSY     7.5.1
 24914 BUSY     7.5.1
 24976 BUSY     7.5.1
 25169 BUSY     7.5.1
 24887 BUSY     7.5.1
 25046 BUSY     7.5.1
 24951 BUSY     7.5.1
 24967 BUSY     7.5.1
 25334 BUSY     7.5.1
 25368 BUSY     7.5.1
 25298 BUSY     7.5.1
 25192 BUSY     7.5.1
 25136 BUSY     7.5.1
 25114 BUSY     7.5.1
 25213 BUSY     7.5.1
 25242 BUSY     7.5.1
 25304 BUSY     7.5.1
 25476 BUSY     7.5.1
 25404 BUSY     7.5.1
 25504 BUSY     7.5.1
 25437 BUSY     7.5.1
 25540 BUSY     7.5.1
 25565 BUSY     7.5.1
```

**Comment by calvertdw** [comment]
Even worse, with so many daemons, it seems you get errors like this:
```
2: Task failed with an exception.
-----------
* What went wrong:
Timeout waiting to lock artifact cache (/home/duncan/.gradle/caches/modules-2). It is currently in use by another Gradle instance.
Owner PID: 24989
Our PID: 24669
Owner Operation: 
Our operation: 
Lock file:
...
```
