### ISSUE TITLE
Can't build gradle from sources from behind a proxy

### ISSUE THREAD

**Issue by lipnitsk** [gradle/gradle#4063]
See https://discuss.gradle.org/t/cant-build-gradle-from-sources-because-of-proxy/1859 and https://issues.gradle.org/browse/GRADLE-2463 for history.

From GRADLE-2463:
The problem comes in for any integration test that needs to hit the network. The user will have either setup their proxy info in ~/.gradle/gradle.properties, «gradle source»/gradle.properties or via env vars, but the integration tests run with a clean, controlled, environment.

To fix this we would need to to inherit these properties into the integration tests. This might throw off some integration tests that are testing proxy support.

**Comment by lipnitsk** [comment]
Is #2571 related to this also?

**Comment by oehme** [comment]
#2571 is unrelated (and I can't reproduce it either). The tests use their own user home to be isolated, so your user home settings won't affect them.

You don't need to run the tests to build Gradle from source, `gradle install` is enough. If you do want to run the tests in your environment, I suggest you adjust the `AbstractGradleExecuter` test fixture to add the arguments you need. 

I don't think we'll have capacity to look into this, since none of use build behind a proxy. If you find a generic solution, a PR is welcome though.

**Comment by lipnitsk** [comment]
Thanks for the help, I was able to run the integration tests by adding the following to `AbstactGradleExecuter.java`:
```public final ExecutionResult run() {
        this.withArgument("-Dhttp.proxyHost=myproxy.com")
            .withArgument("-Dhttp.proxyPort=8080")
            .withArgument("-Dhttps.proxyHost=myproxy.com")
            .withArgument("-Dhttps.proxyPort=8080");
```
