### ISSUE TITLE
Test filtering is slow with forkEvery set to 1

### ISSUE THREAD

**Issue by lipnitsk** [gradle/gradle#4067]
See https://discuss.gradle.org/t/test-run-slow-when-running-with-test-com-example-footest/18489 for history.

The proposed solution was to potentially make a change to `org.gradle.api.internal.tasks.testing.detection.DefaultTestExecutor` to filter tests before forking the JVM. I will try to take a stab at it, so creating this issue to reference in the PR.

**Comment by lipnitsk** [comment]
Related to #3851

**Comment by bmuschko** [comment]
I think that's the same issue https://github.com/gradle/gradle/issues/3851. I am going to close your issue as duplicate. Looking forward to your PR!

**Comment by kevinrushforth** [comment]
The not_scaled.png image looks much as I had expected -- the image size is correct, but rather than an uscaled image, you have an scaled image that reads 2x as many scaled pixels as it should have.

![not_scaled](https://user-images.githubusercontent.com/34689748/41158865-583fce1a-6adf-11e8-8401-3d2c88ec33e4.png)

**Comment by kevinrushforth** [comment]
Sorry for pasting a comment / image here...that was meant for an issue in another project.
