### ISSUE TITLE
Remove the build options that enable advanced POM support and Gradle metadata support

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#4086]
These options should be enabled in the model of the build, that is via the DSL or APIs, and not injected from the environment. We want to try very hard to avoid a situation where something that affects the _meaning_ of the build is not defined in the build itself. Both of these features fit into this category, as they affect how Gradle interprets the inputs of the build and how consumers interpret the output of the build.

### Expected Behavior

Builds are self contained and describe their requirements wrt dependency resolution.

### Current Behavior

If someone needs a build option to enable one or both of these features, then their build is not self contained.

**Comment by adammurdoch** [comment]
"build option" here means the Gradle property and command-line flags, not the ability to enable or disable the feature.

**Comment by jjohannes** [comment]
- We should not promote this as command line parameter. If someone activates this, and it works for them, it should be kept in the build until 5.0.
- We should give the possibility to enable this from the build script (if people use gradle.properties for local environment settings, it's not necessarily a file they commit to version control). We already have this possibility now by modifying start parameters (but that's awkward).

Alternative: turn build option into a DSL method like `gradle.enableFeaturePreview(NAME)`. Where name is just a string, similar to the properties we have now.
Or we add an _feature preview_ interface with strongly typed methods which turn into no-op methods and are directly deprecated with 5.0. And which is then reused and extended for similar feature previews in the future. 

`gradle.featurePreviews.improvedPomSupport()`
`gradle.featurePreviews.gradleMetadata()`

I think we should do the methods and depreciate them directly with 5.0 again.

**Comment by jjohannes** [comment]
If we keep this only as a property, we should at least remove it from the public StartParameter API:

https://github.com/gradle/gradle/blob/master/subprojects/core-api/src/main/java/org/gradle/StartParameter.java#L870-L908

**Comment by jjohannes** [comment]
We do `gradle.enableFeaturePreview(NAME)`

**Comment by melix** [comment]
Oh, of course... the native plugin for one.

**Comment by ljacomet** [comment]
After discussions, the idea would be to add the public api to `Settings` instead of `Gradle` thus narrowing the applicability. And leave core plugins needing to interact with it use internal APIs.

**Comment by bigdaz** [comment]
I'm going to throw a "spanner in the works" here and suggest that we consider ditching the entire 'feature preview' idea. Since I was the one who originally proposed it, I wonder now if it wasn't a great idea after all.

When we came up with the 'feature preview' idea originally, it had the following benefits:
1) Make it easy for people to try out the new features from the command line, to gather feedback
2) Avoid a matrix of options that need to be tested together
3) Allow us to make cross-cutting changes that only make sense for the entire build

However, 1) is being explicitly removed and in the end 3) didn't turn out to be required (now that pending dependencies are always enabled for resolution).

In the end, we've added 4 things:
1) The ability to publish gradle-metadata using `maven-publish` and `ivy-publish`
2) Looking for 'gradle-metadata' in a repository before falling back to ivy/pom files
3) Automatically mapping Maven scopes to variants
4) Constructing dependency constraints for POM files. This has 2 parts:
   i) Creating a constraint for every 'optional' dependency
   ii) Creating a constraint for every 'dependencyManagement' in a BOM

I think all of these features make sense on a per-repository basis, and I would like to suggest that instead of a separate `featurePreview` "feature", we add these as incubating properties on the repositories (where required).

So here's what I would propose:
- We already have a `metadataSources` DSL that allows for 2), and we could easily honour that same DSL in publishing to determine if gradle-metadata should be published or not. That would solve 1).
- We keep 3) and 4) bundled together under 'improved POM support', and we add that as an option to `MavenArtifactRepository`. (Or we could make them separate features on a repository, but we'd have to come up with decent names!)

Doing this would make the new dependency management features just like all of the other features we add to Gradle. 
1) Add a new feature that changes behaviour, allow users to opt-in to the feature
2) At some stage, enable the feature by default, allowing users to opt-out of the feature if they really need to
3) Once the feature is stable, deprecate the opt-out option

Note that this is just a suggestion. I just went back and read the [original email](https://groups.google.com/a/gradle.com/forum/?utm_medium=email&utm_source=footer#!msg/engineering/nJG23_GpAWA/RH_PTzCNAwAJ) where this idea was proposed, and it sounds kind of compelling :).
