### ISSUE TITLE
Create build init types for Play Framework

### ISSUE THREAD

**Issue by marcospereira** [gradle/gradle#4197]
It should be possible to create new Play Framework projects using the following command:

```bash
gradle init --type playframework-java
```

And for Scala projects:

```bash
gradle init --type playframework-scala
```
To make that happen, we need two new [build init types](https://docs.gradle.org/current/userguide/build_init_plugin.html).

**Comment by aadrian** [comment]
@marcospereira extensible init types would be more important, just like SBT does with `new`:
https://www.scala-sbt.org/1.x/docs/sbt-new-and-Templates.html
or how most other build tools allow.

To ensure quality, the standard 2 project templates you mention would need to be "official".

**Comment by marcospereira** [comment]
@aadrian agree. Do we already have some work regarding extensible init types?

**Comment by aadrian** [comment]
> Do we already have some work regarding extensible init types?

@marcospereira AFAIK no. 

The argument against "extensible init" that I mostly heard was that this would "lower" the quality of the generated projects since this way everybody could make templates :) . This is however not true, since the Gradle team could always provide the official and correct set of templates :) .

Would also decouple the templates from the release, since the templates could be hosted the same way on GitHub (not bundled with the releases)

To address this important missing feature, there were many attempts, even some Java based solutions like https://github.com/pledbrook/lazybones that provided all default Gradle project templates and more (now abandoned - but that code could be simply integrated into Gradle if the team would want to :) ).

**Comment by marcospereira** [comment]
> Would also decouple the templates from the release, since the templates could be hosted the same way on GitHub (not bundled with the releases)

That would be interesting for us. We would be able to generate Gradle based projects for each Play Framework sample. Today we are generating all the projects with both `build.gradle` and `build.sbt` which may be confusing to users.

**Comment by aadrian** [comment]
@wolfs why is not planned ? Having project templates is essential.

**Comment by ljacomet** [comment]
Hi @aadrian 

The recent activity is mostly us making sure that all issues closed by the stale bot are properly marked as "not planned" instead of looking like regular completed issues.

This is an area that the team cannot currently focus on. So its state reflects this now.
