### ISSUE TITLE
Free classloaders as soon as they are no longer used

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4237]
Gradle currently holds some reflection-related [data](https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/api/internal/DependencyInjectingInstantiator.java#L61) in a cross-build cache, which keeps all values from the current and the previous build session. This is generally a good idea, as it means that we can avoid redoing a lot of costly reflection when no classloader changed. However, it also means that when e.g. `buildSrc` is changed, the next build will need memory to accommodate both the old and new data. The old classes will only be GCed at the end of the build, even though the classloader has already been invalidated and is no longer used by Gradle. This can be confusing to users, as it can lead to OOMEs that only occur on `buildSrc` changes.

There are several options to solve his:
1. allow listeners on our classloader cache so that we can invalidate cached state when a classloader is released
2. store the reflection data directly in the ASM-generated subclasses, so it can be collected together with the class
3. put the derived data into the classloader cache, so it can be cleared when the classloader is released

**Comment by oehme** [comment]
I'm leaning towards number 3, as it provides the clearest lifecycle and very little overhead. I'm parking this for now, but will revisit for 4.7.

**Comment by ldaley** [comment]
This came up years ago when doing the “new model” work because that involved so much reflection on user types and in a few different places. The consensus intent then was to do something like your option 3, in provide some service for storing information about a class that was aware of its loader origin and tied the lifecycle of that information to the loader. 

https://github.com/gradle/gradle/blob/25cabfda24a2b01bf184c06584b02a28a7fcb347/subprojects/core/src/main/java/org/gradle/api/internal/AbstractClassGenerator.java#L69 does a similar thing, but uses weak references.

There's another weak ref map here: https://github.com/gradle/gradle/blob/1e1dd280e467a450e0aa1e366c4e1f076635d0a5/subprojects/base-services/src/main/java/org/gradle/internal/reflect/JavaReflectionUtil.java#L43

I'll bet there are others.
