### ISSUE TITLE
Release 4.5.1 does not use a tagged release wrapper

### ISSUE THREAD

**Issue by doctaweeks** [gradle/gradle#4286]
Unlike previous releases, 4.5.1 uses a snapshot wrapper rather than a tagged release.

**Comment by jjohannes** [comment]
I assume you are referring to the wrapper that Gradle itself uses when you checkout this tag: https://github.com/gradle/gradle/tree/v4.5.1

We do not have a strict rule which wrapper we use for building the release. Sometimes (as in this case) we use a snapshot newer than the previous release. Especially for fix releases where we do not have release candidates. But yes, these snapshots are not specifically tagged.

@doctaweeks did you encounter any concrete issue with your Gradle usage because of this?

**Comment by doctaweeks** [comment]
@jjohannes Correct, that is what I'm referencing. Based on what you've said, the problem is partially an assumption I had made regarding the releases wherein a wrapper would always be tagged for a release.

However, I would urge tagging versions used to build a release. Otherwise, it is not possible to script Gradle builds and ensure builds work consistently in the future. A build relying on a snapshot will only work as long as the snapshot is still present on the Gradle site (services.gradle.org/distributions-snapshots/). At least with tags one can re-create the intended wrapper.

**Comment by jjohannes** [comment]
As far as I know the snapshots are not removed (cc @wolfs). Just the HTML site does not list them anymore. So you are always able to reproduce a build for any commit of `gradle/gradle`.

I don't see us making any change here because sometimes there are good reasons to build the release from a snapshot that includes all the latest changes.

**Comment by wolfs** [comment]
@jjohannes We remove old nightlies from services.gradle.org. For example the nightly which was used for build `3.0 RC1` has already been removed: [3.0-20160720184418+0000](https://services.gradle.org/distributions-snapshots/gradle-3.0-20160720184418+0000-bin.zip)
