### ISSUE TITLE
Gradle 4.5.x complete distro docs have broken links

### ISSUE THREAD

**Issue by GrafDiffusore** [gradle/gradle#4294]
For example, "User Manual/DSL" links are broken, links to plugins (Java plugin etc) are broken too. Gradle 4.4.1 has working links.

**Comment by blindpirate** [comment]
Thanks for reporting, I've tried several links and didn't met a broken one. Could you provide more details, e.g. which url on which documentation is broken? That would be great.

**Comment by big-guy** [comment]
Paging @eriwen ☝️, I think this is related to the new docs layout work.

**Comment by eriwen** [comment]
Were one to serve the `docs/` directory, links would resolve; otherwise links especially between different types of docs like the DSL reference and userguide will not resolve. 

The only alternative I can think of right now is links to the live docs, which we do for guides (since those are not distributed yet). Do you all have other ideas?

**Comment by GrafDiffusore** [comment]
It would be great to retain pre-4.5 option where docs are usable for offline use (from filesystem, not via webserver). Kinda old school, but I'd like it.

**Comment by blindpirate** [comment]
@GrafDiffusore Thank you very much!
