### ISSUE TITLE
The tooling API should provide an easy way to get project GAV

### ISSUE THREAD

**Issue by asarkar** [gradle/gradle#4320]
### Current Behavior
It appears that there is no way to get the project group, name, and version from the API. By poking around, it seems the GAV is available from `ProjectPublications` model, but surely a project doesn't need to be published in order to have GAV.

### Context
N/A

### Steps to Reproduce (for bugs)
N/A

### Your Environment
Gradle Tooling API 4.3

**Comment by oehme** [comment]
If the project won't be published, what would be the point of having external coordinates?

The fact that things like "group" are part of the Project interface is historical. It belongs on the Publication interface.

**Comment by asarkar** [comment]
What I'm trying to point out is that the Tooling API is inconsistent with the main API. As a dev using the Tooling API, I expect it to provide the same information in the same manner as is available from the main API, because the only reason for the Tooling API to exist is to get programmatic access to the project. But as it currently stands, it's inconsistent and whimsical.

**Comment by oehme** [comment]
The Tooling API is specifically *not* meant to mirror the main Gradle API, because it is meant to be compatible across major versions. The main Gradle API will change faster then the Tooling API. That is why the Tooling API provides models targeted at specific use cases and only containing the information necessary for those use cases.

The Tooling API is extensible, so if you need other information than provided by the built-in models, you can always write your own.
