### ISSUE TITLE
JUnitPlatform support: static nested test classes are not picked up

### ISSUE THREAD

**Issue by BlueIce** [gradle/gradle#4427]
### Expected Behavior
Tests in static nested classes are executed and the build fails if there are failing tests in the nested class.

### Current Behavior
Tests in inner static classes are not executed and the build is not failing although there is a failing test.

### Context
Maybe this is related to https://github.com/gradle/gradle/commit/6d4f89b904c9a21ba9a568f1193f387f0fcc0010.

When the 'org.junit.platform.gradle.plugin' is used instead the expected behaviour is observed.

### Steps to Reproduce
Execute the following command in the attached project ([example.zip](https://github.com/gradle/gradle/files/1734962/example.zip)):
> ./gradlew clean test

### Your Environment
```
------------------------------------------------------------
Gradle 4.6-rc-1
------------------------------------------------------------

Build time:   2018-02-16 16:28:07 UTC
Revision:     ac6267d33138856ffe71b159ab8154e71e9da72e

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_151 (Oracle Corporation 25.151-b12)
OS:           Linux 4.9.0-5-amd64 amd64
```

**Comment by blindpirate** [comment]
Thanks for reporting. @marcphilipp Currently for the following class

```
class ExampleTest {

    static class InnerTest {
        @Test
        public void failingTest() {
            fail("fail test");
        }

        @Test
        public void anInnerTest() {
        }
    }

    @Test
    void aTest() throws Exception {
    }
}
```

We only pass the top-level class `ExampleTest` to JUnit Platform Launcher, as you told me previously in our slack channel. Looks like JUnit Platform will ignore the static nested class. Is this ignorance intentional? Should I do anything for static nested classes?

**Comment by marcphilipp** [comment]
Hmm, very good question. How does it work for `useJUnit()` currently for the following?

```java
@RunWith(Enclosed.class)
public class EnclosedJUnit4TestCase {

	public static class NestedClass {

		@Test
		@Category(Categories.Failing.class)
		public void failingTest() {
			fail("this test should fail");
		}

		@Test
		public void successfulTest() {
			assertEquals(3, 1 + 2);
		}
	}

}
```

I'm assuming Gradle will only pass the outer class?

**Comment by blindpirate** [comment]
@marcphilipp Well there're 2 classes in the code you pasted: `EnclosedJUnit4TestCase` and `EnclosedJUnit4TestCase$NestedClass`. Gradle will first scan these two classes and find they're annotated with `@RunWith` and `@Test`, then execute both of them (get runner and run).

For JUnit 5, there's no such scan to find out the annotations, all test classes are passed to JUnit Platform Launcher except the nested classes (because we discussed this on slack and I was told to do like this). That's why nested tests are not executed.

**Comment by marcphilipp** [comment]
**Proposal:**

1. Gradle should pass all classes, except [inner classes](https://docs.oracle.com/javase/specs/jls/se9/html/jls-8.html#jls-8.1.3) (i.e. non-static member classes). Member classes will be passed to the same worker as all of its enclosing classes.

2. The JUnit Vintage engine will remove duplicates. For example, when it's passed `EnclosedJUnit4TestCase` and `EnclosedJUnit4TestCase$NestedClass`, it will only execute `EnclosedJUnit4TestCase$NestedClass` once.

@blindpirate Would that work for you?

**Comment by blindpirate** [comment]
Well it works, but that means daemon needs to load all classes and distinguish nested classes and top-level classes (and pass all classes in the same top-level class to the same worker), which is we're trying to avoid (only load classes on worker side).

I'd like to know Jupiter engine's logic when it discovers a test class, how does it handle top-level class/non-static nested class/static nested class?

**Comment by marcphilipp** [comment]
> Well it works, but that means daemon needs to load all classes and distinguish nested classes and top-level classes (and pass all classes in the same top-level class to the same worker), which is we're trying to avoid (we try to only load classes on worker side).

Good point. Let's make it simpler: Let Gradle pass all classes, including all member classes. However, to avoid member classes from being executed multiple times, they need to be passed to the same worker as their enclosing class(es).

> I'd like to know Jupiter engine's logic when it discovers a test class, how does it handle top-level class/non-static nested class/static nested class?

Ideally, Gradle should in no way have to know how any engine handles test classes. For the sake of completeness, here's the `Predicate` currently used by Jupiter: https://github.com/junit-team/junit5/blob/master/junit-jupiter-engine/src/main/java/org/junit/jupiter/engine/discovery/predicates/IsTestClassWithTests.java. 😉

**Comment by blindpirate** [comment]
> Good point. Let's make it simpler: Let Gradle pass all classes, including all member classes.  However, to avoid member classes from being executed multiple times, they need to be passed to the same worker as their enclosing class(es).

That's exactly what I want to achieve, previously I doubt that there's no accurate approach to analyze which class files belong to the same top-level class according to the file name, but I guess this is not a big issue. Let's do this.

**Comment by oehme** [comment]
@blindpirate You can determine whether something is a top-level class by using ASM.

However, I think for now we should just do the same fix we did for JUnit 4 - Only ignore nested classes if their outer class is annotated with `@Enclosed`. 

There may be other cases where nested classes have to be passed to the same worker, but I don't think we've had such a report yet. It would definitely complicate the test scheduling logic, as we'd have to track what worker each test was submitted to in order to submit nested classes to the same worker. I'd like to avoid this for now if the only case we were trying to fix was `@Enclosed`.

**Comment by marcphilipp** [comment]
@oehme By `@Enclosed` you mean `@RunWith(Enclosed.class)`, right?

**Comment by oehme** [comment]
Yes, sorry :)

**Comment by marcphilipp** [comment]
No worries. 🙂

**Comment by blindpirate** [comment]
@marcphilipp @oehme How about this:

There are five kinds of classes (or interfaces):

- Top level classes
- Nested classes (static member classes)
- Inner classes (non-static member classes)
- Local classes (named classes declared within a method)
- Anonymous classes

Now we only pass top-level classes to JUnit 5, because nested class with `@Nested` in different worker process might cause duplicate results. Why don't we distinguish the nested class to 2 categories:

- Static nested class. They can be instantiated directly so they should be treated exactly same with top-level class
- Non-static nested class. They can't be instantiated directly, so we don't pass them to JUnit 5, and JUnit 5 can determine if they should be executed via `@Nested`.

This seems a simple solution for this issue: we pass the class to JUnit 5 only it's top-level or static nested class.

WDYT?

**Comment by oehme** [comment]
@blindpirate Inner and anonymous classes will never be run on their own by JUnit, so there is no problem there. They can't even be instantiated directly.

The reason why we excluded nested classes is that `@RunWith(Enclosed)` will result in static nested classes being executed *twice*. But excluding all nested classes was too much - we should only do so when the Enclosed runner is used.

**Comment by blindpirate** [comment]
No problem. That makes sens.
