### ISSUE TITLE
Add option to run failed tests first

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4450]
This is an alternate, simpler proposal to #2644. Instead of answering the question "did I fix the tests that failed?" it would keep running all tests, but execute the failed ones first. This means that the user gets quick turnarounds if something is still broken, while being informed about any new breakages as well. Together with `--fail-fast` this would provide very tight testing loops.

**Comment by big-guy** [comment]
Should this even be an option or just the default behavior?  If we know the set of failed tests, we can queue them up first.  I'm not entirely sure how this works in practice since I think we don't know the full set of tests before we start executing the first test. 

I think adding flags to `Test` is making things worse.  `--fail-fast` is fine, but we could consider making the behavior of `fail-fast` the default in a future version and use `--continue` to mean "keep going".  

For the spike mentioned in #2644, the part that was missing was "run the build again once all the failures are fixed".   The workflow it was trying to replicating was...

1. Change code.
1. Run `gradle check`.  Some things fail.
1. Run `gradle test --tests "*FailingTests*" otherFailingTask` to check that only the failures have been fixed.
1. Run `gradle check` again, to see if anything else has broke.

This is what I do all the time and others would probably do the same if the use of `--tests` for multiple tasks wasn't hard to do.

I think the hard part of "run the build again" is figuring out there are more tests/checks worth running.  Without that feature, I think the spike represents what needs to be done (albeit with a global flag instead of a flag on Test).  I'm not concerned that someone might run with `--fast-feedback` and believe that "BUILD SUCCESSFUL" means that all possible checks were successful, at least not as an initial release.

**Comment by oehme** [comment]
Making this the default is also an option. However, we would need to change test discovery to discover all tests first, then sort them then submit them. This is potentially slower than submitting as we discover. That's my only reservation I think.

**Comment by staffanf** [comment]
If you change the test discovery to discover all tests first, then listing tests from CLI might be low hanging fruit. See https://github.com/gradle/gradle/issues/2129

**Comment by oehme** [comment]
This is only about discovering potential test *classes* on the daemon side, not discovering the actual test *cases* on the worker side (which is highly framework specific and potentially expensive). Many of those classes might be ignored by the framework, e.g. because of categories.

I think these issues are pretty unrelated.
