### ISSUE TITLE
Composite zip dependencies fail to resolve

### ISSUE THREAD

**Issue by kMaiSmith** [gradle/gradle#4491]
### Expected Behavior
When I have a project that depends on a zip artifact from a composite build, Gradle should be able to resolve the dependency and find the zip

### Current Behavior
When depending on a zip archive (built by a Zip task) in the dependency project Gradle throws `Could not find dependency.zip (project :dependency).`
When depending on a jar archive (built by a Jar task from the java plugin) in the dependency project Gradle is able to resolve the dependency and fetch the jar

### Context
I'm converting and streamlining a build system for a proprietary platform from ant to Gradle which build and consumes oodles of odd archives and dependencies in zip formats.  Because of this bug I've had to find some workarounds that reduce the streamlined nature of the new build.

Example of what i am trying to accomplish: [link](https://github.com/kMaiSmith/gradleCompositeZipBug)

### Steps to Reproduce
I have created an example project ([link](https://github.com/kMaiSmith/gradleCompositeZipBug)) to demonstrate the bug.  The bug can be observed by running `./gradlew zipBug` from the root of the repository

A working example is also provided using a jar as the dependency instead of a zip.  This can be tested using `./gradlew workingJar`

In both examples, the archive created by the `dependency` build should be dumped into `tmp/`, only the jar is dumped, the zip fails to resolve

### Your Environment
* Linux subsystem for Windows on Windows 10
* OpenJDK Runtime Environment (build 1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12)
* Gradle 4.5.1

I have also demonstrated this on OSX using a similar version of oracle java.

**Comment by mumrah** [comment]
I am facing the same problem but with WAR artifacts. I have a project called "packaging" which consumes several WARs produced by other projects and assembles them into a final dist. The dependencies for ":packaging" looks like:

```
configurations {
  allWars
}

dependencies {
  allWars "my.company:serviceA:1.0.0@war"
  allWars "my.company:serviceB:1.1.0@war"
}
```

I get the same type of error as reported above: `> Could not find serviceA.war (project :services:serviceA).`

Gradle version is 4.9

**Comment by mumrah** [comment]
Has there been any progress on this?

**Comment by mumrah** [comment]
Also, this issue probably needs the `in:composite-builds` label

**Comment by marcphilipp** [comment]
@mumrah I'm afraid not.

**Comment by ghale** [comment]
You can now solve this problem with [attribute matching](https://docs.gradle.org/current/userguide/dependency_management_attribute_based_matching.html#header).  In the example project linked in the OP, you would do this by first declaring a configuration on the producer to associate the zip artifact with.  You'd also declare a unique attribute on this configuration to allow it to be selected over other variants in the project.
```
configurations {
    special {
        attributes.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, "special-usage"))
    }
}
```
And then declare the zip as an artifact of this new configuration:
```
artifacts {
    special testZip
}
```
Then on the consumer, declare the `special-usage` attribute on the `zipBug` configuration:
```
configurations {
    zipBug {
        attributes {
            attributes.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.class, "special-usage"))
        }
    }
    workingJar
}
```
This then causes Gradle to look for a variant in the dependency with the attributes that match the attributes of the consuming configuration.  It will find the `special` configuration on the dependency project and get its artifacts (the zip artifact) instead of the jar artifact.
