### ISSUE TITLE
JavaExec arg with quote and space is treated as two args

### ISSUE THREAD

**Issue by robstoll** [gradle/gradle#4510]
Consider the following task (the `--config` part is important`): 
```
def deprecationTestEnUK = task('deprecationTestEnUK', type: JavaExec, group: 'Verification') {
    dependsOn jar
    description = 'Runs deprecation tests (check if older tests can be run against newer versions).'
    classpath sourceSets.test_enUK0_6_0.runtimeClasspath

    main = 'org.junit.platform.console.ConsoleLauncher'
    args = [
        '--scan-class-path', configurations.enUK0_6_0.asPath,
        '--include-engine', 'spek-deprecation',
        '--config', 'forgive=".*spec:ch.tutteli.atrium.api.cc.en_UK.Iterable.*(error cases|failing cases).*"',
        '--details', 'none'
    ]
}
```
I figured I have to wrap the string after `forgive=` with `"` so that the space does not make problems. The contrary was the case, it works fine if I do not wrap it into `"` and it gets buggy if you do.

### Expected Behavior
Either I get an error that `"` should not be used within arguments or everything works fine and the whole string is treated as one argument (including the `"`)

### Current Behavior
The argument gets split up into two arguments (`forgive=".*spec:ch.tutteli.atrium.api.cc.en_UK.Iterable.*(error` and cases|*failing cases).*"`)

### Steps to Reproduce (for bugs)
See example above. Please let me know if you need further direction

### Your Environment
gradle 4.4.1

**Comment by ghale** [comment]
I don't think this is incorrect behavior.  The list of arguments to JavaExec are exactly that, the individual arguments that should be provided to the `main` method.  The `"` is used in shells to clue the interpreter that a sequence of characters should be considered a single argument because it normally delimits the arguments with a space and splits them up prior to passing them to the program.  Without anything to tell the shell that the space is part of an argument, it would consider it a delimiter and break the argument into two arguments.  It's simply not necessary in the `JavaExec` configuration because you're already specifying the individual arguments in a list instead.  

I don't think we want to error when we find a `"` in an argument because a literal `"` could be a valid character in an argument to a program.
