### ISSUE TITLE
If statement in many build scripts to set sourceCompatibility

### ISSUE THREAD

**Issue by hansd** [gradle/gradle#4528]
In many subproject build scripts we have the line `sourceCompatibility = javaVersion.java9Compatible ? 1.6 : 1.5`. We should move that into a function of a Gradle extension. 

Can someone shed some light on what is behind that check?

**Comment by wolfs** [comment]
The reason behind this statement is that Java 9 does not support compiling to the target version `1.5`. I guess the statement is even wrong now, since we don't necessarily use the version of Java which runs the build for compilation (see `java7Home`). Moreover, the build currently does not run with Java 9 at all, since the `buildSrc` tests are failing.

**Comment by wolfs** [comment]
We are now using the `moduleType` to determine the source compatibility: https://github.com/gradle/gradle/blob/3108927a623fb61f02d4963f17c221b3036c6f37/subprojects/code-quality/code-quality.gradle.kts#L35-L37

No more `if`s!
