### ISSUE TITLE
Error:No value has been specified for property 'checkstyleClasspath'

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#4545]
### Expected Behavior

`checkstyle` task works well.

### Current Behavior

> Error:No value has been specified for property 'checkstyleClasspath'
### Context

In order to check all sub projects's code style. I create a file `checkstyle.gradle` and apply it to `build.gradle` in root dir. Here is `checkstyle.gradle`.

    apply plugin: 'checkstyle'
    
    
    subprojects { project ->
    
        task checkstyle(type: Checkstyle) {
            configFile rootProject.file('checkstyle.xml')
            ignoreFailures false
            showViolations true
            classpath = files()
            source 'src/main/java'
        }
    
        // check code style after project evaluation
        afterEvaluate {
           project.tasks.findByName('checkstyle').execute()
        }
    }

An error occurs.

> \* What went wrong:<br>
> \>A problem occurred configuring project ':app'.<br>
> \>A problem was found with the configuration of task ':app:checkstyle'.<br>
    \> No value has been specified for property 'checkstyleClasspath'.

I do not know why error occurs.

**Comment by big-guy** [comment]
Please raise questions about how to do things on our [forums](https://discuss.gradle.org/). There are lots of helpful people there.

A few comments on what you posted:
- You're only applying the `checkstyle` plugin to the root project (it's outside the `subprojects {}`).  
- If you're using the `java` plugin to build your project, just applying the `checkstyle` plugin will do everything for you.  No need to create your own `Checkstyle` task.
- _Do not call_ `.execute()` on a task.  This is never correct.
- You're getting an error because the `Checkstyle` task needs [more configuration properties](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.Checkstyle.html) set (like the classpath of where to find Checkstyle).
