### ISSUE TITLE
HTTP build cache fails with wrong error message on some redirects

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#4547]
From @ldaley:

> Looks like the Apache HTTP client will implicitly retry in some circumstances. It will do this in response to an RST on sending headers. Our HTTP client is configured to retry up to 3 times if the connection drops during transmission. We either need to disable that, our change the http build cache service to deal with it.

From @big-guy:

> This retrying might be a new behavior introduced in Gradle 4.6 because of the [upgrade of HTTP Client from 4.4.1 to 4.5.5](https://docs.gradle.org/4.6/release-notes.html#httpclient-library-upgraded-to-version-4.5.5). Or maybe it's not, because the change of behavior is not in the release notes of HTTP client.

**Comment by ldaley** [comment]
It appears our HTTP client tries to recover from transient connection drops. It will implicitly retry the request. If the connection is still down, it will fail differently and we will ultimately observe that failure.

So, the problem exhibits now when the connection does drop in the middle of a transfer but an immediate subsequent reattempt succeeds (or at least gets as far as connection).

Our build cache services (i.e. the things that interact with remote stores) work with this contract:

https://github.com/gradle/gradle/blob/b8dba54fdb4034d319bddc217f5bf12a1a58104e/subprojects/build-cache/src/main/java/org/gradle/caching/BuildCacheService.java#L62

https://github.com/gradle/gradle/blob/b8dba54fdb4034d319bddc217f5bf12a1a58104e/subprojects/build-cache/src/main/java/org/gradle/caching/BuildCacheEntryWriter.java#L39

We currently expect `BuildCacheEntryWriter#writeTo()` to be called at-most-once. When our HTTP client retries, it calls this each time.

We require it to be called at-most-once because this is how we observe whether the service actually attempted the store or not. Contractually, it is not obligated to. It may look at the size of the thing to be stored and decide it's not worth it (e.g. network is too slow for this to be viable). Observing this is important for build scans, where we want to indicate what the build cache service is doing.

Options:

1. Disable automatic retry in our HTTP client
2. Change our model to allow multiple stores and/or store attempts
3. Change our API to separate “I'm going to try to store” from “give me the thing to store”

Option 1 is the simplest, but it does remove some robustness from using a HTTP store. That is, we lose some potential automatic failure recovery. I think this is an OK price to pay, and is better than the current situation where this fails and it looks like it's an internal Gradle error and not a network failure.

To implement this, we just need to call `HttpClientBuilder#disableAutomaticRetries()` when [obtaining a HTTP client to use](https://github.com/gradle/gradle/blob/253e444902eac5ce4a0c133e8a66b7ac86218fe4/subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/HttpBuildCacheService.java#L90) (which would unfortunately require some hole drilling).

**Comment by ldaley** [comment]
Actually, it's much easier. We just need to change [this](https://github.com/gradle/gradle/blob/253e444902eac5ce4a0c133e8a66b7ac86218fe4/subprojects/build-cache-http/src/main/java/org/gradle/caching/http/internal/HttpBuildCacheService.java#L149) to `false`.

**Comment by lptr** [comment]
@ldaley do you plan to address this in a PR?
