### ISSUE TITLE
maven-publish combined with artifactory-publish doesn't publish marker artifacts

### ISSUE THREAD

**Issue by edeandrea** [gradle/gradle#4783]
### Expected Behavior
When I configure my project to use the [Gradle Artifactory Plugin](https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin) with a project that also uses the `java-gradle-plugin` I would expect that the plugin markers get deployed to Artifactory.

### Current Behavior
When running the `artifactoryPublish` task, nothing is published to Artifactory, other than the build info.

### Context
When building internal plugins within our organization, we can't use the `plugins` DSL because our in-house-built plugins don't have valid plugin markers deployed.

### Steps to Reproduce (for bugs)
Here is a sample build file

```groovy
plugins {
    id 'java-gradle-plugin'
    id 'maven-publish'
    id 'com.jfrog.artifactory' version '4.7.0'
}

group 'com.mycompany.groupid'
version '1.0.0.1'

sourceCompatibility = 1.8

gradlePlugin {
	plugins {
		sample {
			id = 'my-sample-plugin'
			implementationClass = 'org.gradle.mavenpublish.SamplePlugin'
		}
	}
}

repositories {
	mavenCentral()
}

artifactory {
	contextUrl = 'http://my.artifactory.server/artifactory'

	publish {
		repository {
			repoKey = 'artifactory-publish-repo'
			username = 'user'
			password = 'pass'
		}

		defaults {
			publications 'pluginMaven', 'samplePluginMarkerMaven'
			properties = ['Deployed By': System.properties['user.name']]
			publishBuildInfo = true
			publishArtifacts = true
			publishPom = true
			publishIvy = false
		}
	}

	resolve {
		repository {
			repoKey = 'artifactory-resolve-repo'
			maven = true
		}
	}

	clientConfig.includeEnvVars = true
	clientConfig.envVarsExcludePatterns = '*pwd*,*password*,*PWD*,*PASSWORD*,*Password,*secret*,*SECRET*,*key*,*KEY*,sonar.login'
	clientConfig.info.buildName = 'test-publish'
	clientConfig.info.buildNumber = version
}

task printPubs {
	doLast {
		project.publishing.publications.each { publication ->
			println "Publication [name: $publication.name, groupId: $publication.groupId, artifactId: $publication.artifactId, version: $publication.version"
		}

		def pluginMaven = project.publishing.publications['pluginMaven']
		println "pluginMaven [name: $pluginMaven.name, groupId: $pluginMaven.groupId, artifactId: $pluginMaven.artifactId, version: $pluginMaven.version"
	}
}
```

When you run the `artifactoryPublish` task (substituting a valid Artifactory URL/username/password/publish repo name), you get this:

```
./gradlew artifactoryPublish

> Task :artifactoryDeploy 
Deploying build descriptor to: http://my.artifactory.server/artifactory/api/build
Build successfully deployed. Browse it in Artifactory under http://my.artifactory.server/artifactory/webapp/builds/test-publish/1.0.0.1


BUILD SUCCESSFUL in 2s
2 actionable tasks: 2 executed

```

What's interesting though is if you run the `printPubs` task that I wrote, you get this

```
 ./gradlew printPubs

> Task :printPubs 
Publication [name: pluginMaven, groupId: com.mycompany.groupid, artifactId: gradle-maven-publish-artifactory, version: 1.0.0.1
Publication [name: samplePluginMarkerMaven, groupId: my-sample-plugin, artifactId: my-sample-plugin.gradle.plugin, version: 1.0.0.1
pluginMaven [name: pluginMaven, groupId: com.mycompany.groupid, artifactId: gradle-maven-publish-artifactory, version: 1.0.0.1


BUILD SUCCESSFUL in 0s
1 actionable task: 1 executed
```

### Your Environment
I can't give a build scan due to legal reasons, but here is my environment:

```
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Mac OS X 10.12.6 x86_64
```

**Comment by ashtynmo** [comment]
I'm having this issue too, any update?

**Comment by marcphilipp** [comment]
Can you please enabled `--debug` and run `artifactoryPublish` again?

**Comment by lavcraft** [comment]
I think you need to configure valid publications in artifactry plugin

Like this: https://github.com/lavcraft/huntbugs-gradle-plugin/blob/master/build.gradle#L75

**Comment by ashtynmo** [comment]
Here is my output with `--debug`:
[artifactoryPublishDebug.txt](https://github.com/gradle/gradle/files/1965291/artifactoryPublishDebug.txt)


It does publish _something_ to artifactory, but it's missing the marker artifacts. My config looks something like:
```
artifacts {
    archives jar
}

artifactory {
    contextUrl = "${contextUrl}" /
    publish {
        repository {
            repoKey = 'maven'
            username = "${user}"
            password = "${password}"
            maven = true
        }
        defaults {
            publishConfigs('archives')
        }
    }
    resolve {
        repository {
            repoKey = 'maven'
            maven = true
        }
    }
}
```

**Comment by marcphilipp** [comment]
@ashtynmo The marker artifacts are not part of the `archives` configuration. You have to use `publications 'samplePluginMarkerMaven'` (assuming your use `sample` in  `gradlePlugin { plugins { sample { ... } } }`) instead of `publishConfigs('archives')`.

**Comment by marcphilipp** [comment]
@edeandrea The reason is that the Artifactory plugin's `ProjectEvaluationListener` [applies the `defaults`](https://github.com/JFrogDev/build-info/blob/master/build-info-extractor-gradle/src/main/groovy/org/jfrog/gradle/plugin/artifactory/extractor/listener/ProjectsEvaluatedBuildListener.groovy#L62) before the `MavenPublications` have been added.

When enabling the debug logging, you see:

```
16:17:32.992 [DEBUG] [org.jfrog.gradle.plugin.artifactory.task.helper.TaskHelperPublications]
Publication named 'pluginMaven' does not exist for project ':' in task ':artifactoryPublish'.
16:17:32.992 [DEBUG] [org.jfrog.gradle.plugin.artifactory.task.helper.TaskHelperPublications]
Publication named 'samplePluginMarkerMaven' does not exist for project ':' in task ':artifactoryPublish'.
```

As a workaround, you can configure publishing manually:

```gradle
gradlePlugin {
    automatedPublishing = false
	plugins {
		sample {
			id = 'my-sample-plugin'
			implementationClass = 'org.gradle.mavenpublish.SamplePlugin'
		}
	}
}

publishing {
    publications {
        pluginMaven(MavenPublication) {
            from components.java
        }
        samplePluginMarkerMaven(MavenPublication) {
            groupId gradlePlugin.plugins.sample.id
            artifactId gradlePlugin.plugins.sample.id + ".gradle.plugin"
            pom.withXml {
                def dependency = asNode().appendNode('dependencies').appendNode('dependency')
                dependency.appendNode('groupId', group)
                dependency.appendNode('artifactId', name)
                dependency.appendNode('version', version)
            }
        }
    }
}
```

**Comment by marcphilipp** [comment]
FWIW here's a complete sample project:
https://github.com/marcphilipp/gradle-sandbox/tree/master/4783-artifactory-plugin-publishing

**Comment by oehme** [comment]
The artifactory plugin tries to access the publications immediately when you mention them, even if you just refer to them by their name. It should instead do this lazily. Also it should support passing a `DomainObjectContainer<Publication>` so that users can do convenient things like telling it to upload *all* publications without having to list each individually.

This can't be fixed on the Gradle side, please let the artifactory team know. We're happy to assist if they need guidance.

**Comment by AlexeiVainshtein** [comment]
Hi @oehme , 
My name is Alexei and I'm one of the developers that maintaining the Artifactory Gradle plugin. 
I wanted to thank you for your suggestions and indeed we are working on fixing the issue when the evaluate is running to early. The implementation would be that in the afterEvaluate method to set the finalizedBy for all the projects but only if the configure on demand is configured, we will run the projectEvaluated for the needed projects. 
If the configure on demand is not passed, we then do the projectEvaluated in a later stage when all the projects were evaluated (projectsEvaluated method). Any suggestion from you regarding this would be appreciated. 
One thing I've came across that I do want to consult with you:

I've created a project and configured also the following within the build.gradle:

project.afterEvaluate { proj ->
  proj.configure(proj.publishing) {
        publications {
            mainJava(MavenPublication){
                from components.java
                artifact(file("$rootDir/gradle.properties")) {
                    extension "txt"
                }
            }
        }
    }
      proj.configure(proj.tasks['artifactoryPublish']) {
        publications 'mainJava'
  }

}
    
When running without the flag of configure on demand, all is working and the pom-default.xml file is being created and uploaded to Artifactory.
However, when running with the flag of configure on demand, the pom file is not being created and therefore the artifactoryPublish fails since the plugin expecting the file.
I've created a sample task hello that just prints hello to the terminal and when I run this task with configure on demand, still the pom is not being created. 
Therefore, this specific scenario is not related to the Artifactory Gradle plugin since in the above scenario the Artifactory Gradle plugin is not being invoked. 
It seems that configure on demand skipping the creation of the pom. Is this the desired behaviour from Gradle to skip this and not to create the file?
If needed I can send you a sample project.

**Comment by oehme** [comment]
Hey @AlexeiVainshtein,

what you referred to looks like a different issue. I'm happy to help of course, but can we discuss that one separately? 

The problem here has nothing to do with your ProjectsEvaluatedBuildListener. Instead, the problem here is that your `publications()` method tries to eagerly resolve all publications, even if the user just passes Strings. The method needs to be improved in two ways:

1. If the user passes a String, remember that String and only look up the publication when you actually need it later.
2. Add an overload `publications(DomainObjectCollection<? extends Publication> publications)` and use `publications.all {}` to listen to additions to that container. This will allow users to conveniently specify that they want to publish all publications or publications matching certain criteria. 

Once that is fixed we can look into your usage of `afterEvaluate` to make the Artifactory plugin play together better with a wider range of other plugins.

**Comment by AlexeiVainshtein** [comment]
Hi @oehme 

I just wanted to ask if you had a chance to go over what I've send previously? 

Thanks

**Comment by oehme** [comment]
Not yet, I'll get back to you next week.

**Comment by AlexeiVainshtein** [comment]
Great thanks appreciate this @oehme

**Comment by RoRoche** [comment]
I'm figuring the same issue, I don't understand what fix I have to apply.
Do I have to configure publishing manually?

**Comment by edeandrea** [comment]
The fix was incorporated into a newer version of the plugin (see jfrog/build-info#86).

**Comment by RoRoche** [comment]
I'm using 

```groovy
id "com.jfrog.artifactory" version "4.15.1"
```

but have the issue with markers not published.

**Comment by edeandrea** [comment]
I would bring it up with the JFrog team.

**Comment by sbilello** [comment]
@RoRoche  can you share your build.gradle?

**Comment by RoRoche** [comment]
plugins {
    id 'groovy'
    id 'java-gradle-plugin'
    id "com.jfrog.artifactory" version "4.15.2"
    id 'maven'
    id 'maven-publish'
}

group 'com.myCompany.myPackage.gradle'
version '1.0.0-SNAPSHOT'

project.description = 'A description'
project.group = 'com.myCompany.myPackage.gradle'
project.version = '1.0.0-SNAPSHOT'
project.ext.pluginId = 'com.myCompany.myPackage.gradle.myPackage-myPlugin'

dependencies {
    compile gradleApi()
    compile 'org.codehaus.groovy:groovy-all:2.5.4'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

gradlePlugin {
    plugins {
        myPlugin {
            id = project.pluginId
            implementationClass = 'com.myCompany.myPackage.gradle.MyPlugin'
        }
    }
}

artifactory {
    contextUrl = "${artifactoryHost}"
    def snapshotsRepoKey = "libs-snapshot"
    def releasesRepoKey = "libs-release"
    publish {
        repository {
            repoKey = version.endsWith('SNAPSHOT') ? snapshotsRepoKey : releasesRepoKey
            username = "${artifactoryUser}"
            password = "${artifactoryToken}"
            maven = true
        }
        defaults {
            publications 'pluginPublication'
            publishBuildInfo = true
            publishArtifacts = true
            publishPom = true
        }
    }
}

publishing {
    publications {
        pluginPublication(MavenPublication) {
            from components.java
            groupId project.group
            artifactId project.name
            version project.version
        }
    }
    repositories {
        maven {
            def snapshotsRepoUrl = "${artifactoryHost}/libs-snapshot"
            def releasesRepoUrl = "${artifactoryHost}/libs-release"
            url = version.endsWith('SNAPSHOT') ? snapshotsRepoUrl : releasesRepoUrl
            credentials {
                username "${artifactoryUser}"
                password "${artifactoryToken}"
            }
        }
    }
}

**Comment by briceburg** [comment]
For those lost; here is a simple build.gradle that works -- it publishes markers as well as plugin.   a more recent version of the jfrom artifactory plugin (I'm using 4.16.1) is required. thanks @edeandrea for upstream efforts there.


```groovy
plugins {
    id 'com.jfrog.artifactory' version '4.16.1' // https://www.jfrog.com/confluence/display/rtf/gradle+artifactory+plugin

    id 'java-gradle-plugin'
    id 'maven-publish'
}

group = 'com.acme.ci'
version = '0.0.1'
sourceCompatibility = '11'

gradlePlugin {
    plugins {
        platorm {
            id = 'com.acme.ci.platform'
            implementationClass = 'com.acme.ci.PlatformGradlePlugin'
        }
    }
}

repositories {
    mavenLocal()
    maven {
        url 'https://packages.acme.com/artifactory/acme-maven'
        credentials {
            username = "${artifactory_user}"
            password = "${artifactory_password}"
        }
    }
}

artifactory {
    contextUrl = "https://packages.cofense-tools.com/artifactory"
    publish {
        defaults {
            publications 'pluginMaven', 'platormPluginMarkerMaven'
            // 'platformPluginMarkerMaven' comes from gradlePlugin defs line 14
        }
        repository {
            repoKey = 'acme-maven'
            username = "${artifactory_user}"
            password = "${artifactory_password}"
        }
    }
}

compileJava.finalizedBy publishToMavenLocal
```

be sure to change platormPluginMarkerMaven to yourPluginNamePluginMarkerMaven as needed

**Comment by SergiiSopin** [comment]
I'm still having this problem in jfrog plugin v4.18.0. 

Setting `--configure-on-demand` to `true` helps, but it breaks something else on our project. 
Please take a look at this answer: https://github.com/gradle/gradle/issues/4783#issuecomment-393184042
