### ISSUE TITLE
limiting gradle deamon instances

### ISSUE THREAD

**Issue by c3ph3us** [gradle/gradle#4813]
why there is no gradle config property to limit a daemons creation
 (allowing to limit max working/avail/idle/incompatible instances) 

eg i dont want to start new daemon if there are some incompatible or busy one !!!

example implementation for the issue:

// limit global daemon creation
1)  daemon.instances.max=xx (running +  idle)
// limit on each state daemon creation
2) daemon.instances.max.running=xx
3) daemon.instances.max.incompatible=xx

// to auto stop idle / incompatible 
// if above counters are reached 
// to allow create new (compatible) instance 
4) daemon.instances.max.stop=true

// we cant create new instance then inform user 
-- on limit reached (for max running) 
-- or when stop flag is not set and we cant self / stop & make new one 

or provide a some sort of que for each gradle call

**Comment by remcomokveld** [comment]
Why was this issue closed? I think this would be great to have as an opt-in feature on low memory devices. Especially on Android builds where you typically need to assign at least 4GB of memory due to lint and dexing. I'd rather not have new daemons started automatically when the current one is either busy or incompatible
