### ISSUE TITLE
Javadoc does not take into account custom options

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#4841]
## Context

Original reported in #4834 

Java 9 adds some new options such as [`-html5`/`-html4`](https://docs.oracle.com/javase/9/javadoc/javadoc-command.htm), however, these new options are not included in UP-TO-DATE check.

https://github.com/gradle/gradle/blob/4f0dbbf637ae2c726714f0a6474b7b1be8f82409/subprojects/language-java/src/main/java/org/gradle/api/tasks/javadoc/Javadoc.java#L302

```
    @Nested
    public MinimalJavadocOptions getOptions() {
        return options;
    }
```

`MinimalJavadocOptions` only contains well-known options (`JFlags`/`author`, etc.), so UP-TO-DATE check won't scan `options.html5` as its input property.

## Expected behavior

We should make `options` property more generic, instead of keeping adding new options into it.

**Comment by apjanke** [comment]
I don't know if this is the right place to ask about this, but: Maybe `-html4`/`-html5` needs to be handled generically in some way at the Gradle level, to support projects that support building against either Java 1.7 or Java 9?

I'm working on [`google-maps-services-java`](https://github.com/googlemaps/google-maps-services-java), which currently builds against Java 1.7.

When building the project on a system where Java 10 is the default JVM, I [get a warning](https://github.com/googlemaps/google-maps-services-java/issues/467) about not specifying the version of HTML for the Javadoc.

```
[~/local/repos/google-maps-services-java]
$ ./gradlew build test

> Task :javadoc
javadoc: warning - You have not specified the version of HTML to use.
The default is currently HTML 4.01, but this will change to HTML5
in a future release. To suppress this warning, please specify the
version of HTML used in your documentation comments and to be
generated by this doclet, using the -html4 or -html5 options.
1 warning
```

But I can't just add an `-html4` or `-html5` option in `build.gradle` like this:

```
javadoc {
    options.addBooleanOption('html4', true)
}
```

because then the build will break when run against JDK 1.7.

```
$ ./gradlew clean build

> Task :javadoc FAILED
usage: javadoc [options] [packagenames] [sourcefiles] [@files]
javadoc: error - invalid flag: -html4
[...]
```

I think it should be possible, or at least would be nice, to be able to do a warning-free build under any supported version of the JDK for a given project.

Would it be possible and appropriate to add `html4`/`html5` options to the `javadoc` section that pass the `-html4`/`-html5` options to `javadoc` if and only if they are running against a version of the JDK that supports them?

Am I asking about this in the right place?

**Comment by apjanke** [comment]
I'm currently using this workaround:

```
javadoc {
    def currentJavaVersion = org.gradle.api.JavaVersion.current()
    if (currentJavaVersion.compareTo(org.gradle.api.JavaVersion.VERSION_1_9) > 0) {
      options.addBooleanOption('html4', true)
    }
}
```

Which seems all right, but a little gross.

**Comment by Vampire** [comment]
I would say no @apjanke.

This issue is about the up-to-date check not kicking in if some of the JavaDoc options change which should cause the documentation to be rebuilt but isn't.

You could simply check against which version you are building and set the option accordingly.

**Comment by apjanke** [comment]
Okay, thanks. I'll stick with our version-checking workaorund.

**Comment by Vampire** [comment]
@apjanke don't get me wrong, it might be a good feature, but you should open a separate ticket for it probably.

**Comment by apjanke** [comment]
Okay, cool. I've opened a separate ticket for it here: https://github.com/gradle/gradle/issues/5891.

Thanks!

**Comment by FuminZhou** [comment]
java 9/11 also supports some additional options/flags such as add-exports, patch-module, etc.. Either I don't quite know how to set this - I tried using options.addStringOption, but yielded no effect (The tmp java.options file has no mark of the options I tried to put in there); or the "minimal" java options filtered out these?

**Comment by jianglai** [comment]
Is there any update on this?

**Comment by tresat** [comment]
@bot-gradle test this
