### ISSUE TITLE
maven-publish: when publishing to S3, set a more specific "Content-Type" header on files

### ISSUE THREAD

**Issue by oakad** [gradle/gradle#4859]
Presently, when publishing to S3 "maven-publish" plugin sets the "Content-Type" header of all files uploaded to repository to "application/octet-stream". This is not particularly convenient when the S3 files are also exposed to other tools and/or wider web.

Would not it be more correct (and convenient) to set a more specific "Content-Type" header on uploaded files, so that xml files are properly tagged "text/xml" and jar files are tagged "application/java-archive"?

**Comment by osiegmar** [comment]
In addition to a correct `Content-Type` header, I was also missing a `Cache-Control` header/configuration. As this issue was  closed as 'not planned' I decided to create a Lambda@Edge function for this. In case anyone has similar requirements:

https://gist.github.com/osiegmar/3d695438173ddb47e2ce50cdc0a824ef

**Comment by ov7a** [comment]
Sorry for the late reply

This feature request is in the backlog of the relevant team and is prioritized by them.
