### ISSUE TITLE
GRADLE ERROR

### ISSUE THREAD

**Issue by luiscm** [gradle/gradle#4872]
![gradle_error](https://user-images.githubusercontent.com/310819/38028759-3f6349d8-326a-11e8-8d2d-0e40b73ee537.png)

**Comment by melix** [comment]
This is not an error, but a warning. Since JDK 9, some legal operations done by the Groovy runtime are shown as warnings, and there's nothing we can do to prevent them from happening. It will not prevent your builds from running, but will definitely spoil the logs. Two options:

1. Run Gradle with JDK 8, and use forking to enable usage of a different JDK for compiling/running tests/...
2. Use Kotlin build scripts instead of Groovy

**Comment by luiscm** [comment]
Thank you, I was wrong, I apologize to you, it's a WARN

**Comment by melix** [comment]
No need to apologize, the warning is indeed confusing, but it's coming from the JDK internals :(
