### ISSUE TITLE
Provide public GradleVersion API

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#4884]
### Expected Behavior
As a user, I may need to change my behavior based on various aspects of the version of Gradle being used. For example, knowing if the current version is greater than some threshold, or if it's a nightly snapshot.

### Current Behavior
This is considered a part of Gradle's internal API and should not be used by users.

### Context
This is one of the most highly-used internal APIs according to GitHub BigQuery data. Providing a supported API would be high-impact.

**Comment by daschneider** [comment]
We currently use the `GradleVersion` API and need a publicly supported API to obtain the version.

I'm not sure I'd agree this was originally intended to be an internal API.  The `org.gradle.util` package has an `internal` sub-package and this class was never in there.  This probably has lead a lot of people to view it as a public API and if their build scripts reference it they will break when moving to Gradle 5.0 (ours did).

**Comment by benjamin-bader** [comment]
I'd like to add my voice to this request.  I maintain a gradle plugin and need to do Gradle version checks.  Currently we have our own variant of `GradleVersion` because Gradle's own class is still internal (and thus subject to random repackaging).

This really feels like a public API, especially given that the version string itself is already public.

**Comment by donat** [comment]
Fixed in #16809.
