### ISSUE TITLE
JUnit platform-compatible test descriptor API

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4937]
JUnit platform has made us aware of additional concepts that we might want to add to our TestDescriptors, e.g. reporting entries and display names. We should think about ways to enhance our current TestDescriptor API to support these. A simple solution might be to just add them and accept that the descriptors are very JVM specific. Alternatively we could make them more generic and hierarchical to support other kinds of testing frameworks.

**Comment by jbduncan** [comment]
@oehme It might be worth reopening this issue because, if I understand the topic of this issue correctly, I believe Gradle doesn't yet support printing user-friendly display names for JUnit 5 parameterized tests and dynamic tests.

That being said, I haven't done a search for a separate issue that may already be tracking this, so if that's the case, feel free to ignore me.

**Comment by jbduncan** [comment]
Oh, never mind, I believe I found a related issue, which means this issue can remain closed https://github.com/gradle/gradle/issues/5975.
