### ISSUE TITLE
Support signing publications

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4943]
## Goals

Make it possible (and easy) to sign publications created with the maven-publish/ivy-publish plugins.

Signing a publication should sign all artifacts (in particular the POM) within a publication.
There should be an easy way to make signing conditional, e.g. only sign releases.

## Proposed DSL

```gradle
signing {
    sign publishing.publications.mavenJava, publishing.publications.testFixtures
    // or even
    sign publishing.publications.matching { /* some condition */ }
}

tasks.withType(Sign) {
    onlyIf { /* isRelease */ }
}
```

**Comment by Vampire** [comment]
@marcphilipp very much thanks, this is really amazing now and finally working easily as expected
I tried with the `gradle-4.8-20180421000019+0000-bin.zip` and it works great.
There is just one detail so far I found that is not too nice.
While playing around I still had old signature files lying around.
Yet I had no signatory for testing and `required` to `false`.
This caused the `signXXXPublication` tasks to correctly be `SKIPPED`.
The problem is, that the stale old and now surely not valid anymore signature files were published alongside the new artifacts.

**Comment by marcphilipp** [comment]
I've verified that using the same problem is also present when using the old `Upload`-based publishing infrastructure.

@Vampire I've created #5136 to handle stale artifacts when publishing. Feel free to add more details to the issue. Since it's more of a corner case, we will probably not address it right away.

**Comment by Vampire** [comment]
It's ok, just something I stumbeld upon and if I stumble upon something I usually either report it, fix it, or do both. :-)
