### ISSUE TITLE
Incremental class analysis should be added to the build cache

### ISSUE THREAD

**Issue by gustafg** [gradle/gradle#4951]
I'm not sure this is an actual issue, maybe it's more of a question.

I'm testing out the build cache on a Java multi module project. I've noticed that it seems pointless to use the cache for the top-level components in our build because they always need to be fully re-compiled every time a first time change is made after something was retrieved from the cache.

I test like follows:
1. I stop gradle daemon
2. I wipe ~/.gradle
3. I checkout our project to ~/build_area_A and execute ```gradle assemble```
4. I checkout our project to ~/build_area_B and execute ```gradle assemble``` this is much faster than step 3 because all build outputs arrive from the cache.
5. I change a file in ~/build_area_B and execute ```gradle assemble``` again. Now if I changed the wrong file the build time will be as long as in step 3 because gradle states: ```:module:compileJava - is not incremental. No class analysis data available from the previous build.``` for the module changed and all modules depending on it.

I guess I don't get why the class analysis isn't brought in from the cache aswell. It seems to defeat the purpose a bit?

**Comment by oehme** [comment]
Your observation is correct, the incremental analysis is currently not in the build cache, but definitely should be.

**Comment by CristianGM** [comment]
I saw that incremental compile is coming in the future to BuildCache, as you said on this issue, but I'm curious how would you achieve it.
It would require uploading all the classes of any incremental task, and when pulling you won't have a matching key so you would need to try with the latest upload 🤔
I mean, it seems like the best thing ever for improving CI speed, as long as the network doesn't become the new bottleneck.

**Comment by lptr** [comment]
What do we need for this? The requirements from the build cache side are:

- the analysis should be produced as an `@OutputFile` of the `JavaCompile` task
- it should not contain absolute paths

**Comment by oehme** [comment]
The [previous compilation data](https://github.com/gradle/gradle/blob/13feddd718896e6cdc8c8c2767630636d587d64c/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/recomp/PreviousCompilationData.java#L32) is not a dedicated file at this point, but uses our persistent cache infrastructure. Also this task-specific data only contains hashes of the files it last saw on its classpath. The actual snapshot of each [classpath entry](https://github.com/gradle/gradle/blob/106ffb113b4ebf0ddd803c65676f529311df943f/subprojects/language-java/src/main/java/org/gradle/api/internal/tasks/compile/incremental/classpath/ClasspathEntrySnapshotData.java#L24) does not belong to the task, but is shared between many tasks (because the same library can be on the classpath of many tasks). So to avoid lots of duplication, we'd need a way to store this data in the build cache for each classpath entry, not tied to a specific task.

**Comment by lptr** [comment]
This is a priority for us.

**Comment by oehme** [comment]
I'm gonna take a stab at this.
