### ISSUE TITLE
Add Header option to JavaCompile task

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#4970]
With Java 11 removing the javah tool, javac -h is now the recommended way to generate JNI headers. Because this task is already ran, an option should be added to the JavaCompile task to have it generate the headers without the need for a separate task. This is compatible all the way back to Java 8.

**Comment by liblit** [comment]
I now find myself in the same situation: I would like to generate JNI headers in the same compilation task that builds bytecode files, rather than running `javac -h` separately with all of the redundant work that implies. @ThadHouse, you closed this issue soon after opening it. Did you find a better alternative?

**Comment by liblit** [comment]
Excellent! Thank you for the speedy reply. I look forward to trying out your Gradle JNI plugin soon.
