### ISSUE TITLE
Add tests for `jdk.javadoc.doclet.Taglet.Location`

### ISSUE THREAD

**Issue by blindpirate** [gradle/gradle#4993]
### Context

We have a test which uses `com.sun.tools.doclets.Taglet` [here](https://github.com/gradle/gradle/blob/a74f8806dc1e0655f8b2b932541cc42610ee5a06/subprojects/language-java/src/integTest/resources/org/gradle/javadoc/JavadocIntegrationTest/canCombineLocalOptionWithOtherOptions/src/taglet/java/LocaleAwareTaglet.java#L17). It's has been deprecated in Java 9 and removed in Java 10. We should add a new test with new API here: https://docs.oracle.com/javase/10/docs/api/jdk/javadoc/doclet/class-use/Taglet.Location.html

Also see https://docs.oracle.com/javase/9/docs/api/deprecated-list.html

**Comment by natgaertner** [comment]
Hello, I thought I would look at adding this test as a nice contained way to start contributing. Unfortunately, there's a challenge with simply porting the old test over to the new API. It seems that the old javadoc implementation run through ```com.sun.tools.javadoc.main.Start``` implicitly created a ```com.sun.tools.javadoc.main.DocLocale``` that would call ```Location.setDefault``` as part of its constructor: https://hg.openjdk.java.net/jdk/jdk11/file/1ddf9a99e4ad/src/jdk.javadoc/share/classes/com/sun/tools/javadoc/main/DocLocale.java#l103

The new javadoc implementation run through ```jdk.javadoc.internal.tool.Start``` never does such a thing, breaking the test's dependency on fetching the locale data from the global static context of java.util.Locale. 

I searched quite a bit through the new doclet and taglet APIs: https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/Doclet.html
and could not find a way to pass locale data down to a custom Taglet. It simply does not seem to be accessible through the DocletEnvironment or Doclet itself.

Looking at the intention of the test, it seems like it wants to make sure some options are successfully getting merged into the javadoc task. Looking back at the commit that created this custom Taglet class: https://github.com/gradle/gradle/commit/d71659369f6cb210487f68d19b652d1758de7543 it seems that simply checking the "lang" attribute of the generated html was not enough to verify this. I admit to not quite understanding why.

In the newer Doclet api, it seems far easier to test that options are getting set correctly by creating a custom doclet rather than taglet, but I may be missing the point of the original taglet usage. If anyone has further context on this I'd be happy to keep looking at it.
