### ISSUE TITLE
Fail to resolve a dependency in a custom Ivy repo with the GRADLE_METADATA feature enabled

### ISSUE THREAD

**Issue by ilmat192** [gradle/gradle#5008]
### Current Behavior
When applied both [`com.moowork.node`](https://github.com/srs/gradle-node-plugin) and any plugin using the Gradle metadata feature (e.g. `cpp-application`), build fails with the following error:
```
Could not find org.nodejs:node:8.11.1.
     Searched in the following locations:
         https://nodejs.org/dist/v8.11.1/node.module
         https://nodejs.org/dist/v8.11.1/ivy.xml
```

`com.moowork.node` uses Gradle's dependency resolution system to download a Node.js distribution. To do this, it declares an Ivy repository with a custom pattern (see [source](https://github.com/srs/gradle-node-plugin/blob/02d006b013cd909f5262170470ebc2c7f30f5333/src/main/groovy/com/moowork/gradle/node/task/SetupTask.groovy#L178)) and declares
the distribution as a dependency. Such an approach works in usual circumstances but if the `GRADLE_METADATA` feature is enabled, this dependency cannot be resolved.

### Context
The issue was faced during work on a Kotlin multiplatform library which includes JS and native modules. The JS module uses `com.moowork.node` for testing while the native module is built by the Kotlin/Native plugin which enables the `GRADLE_METADATA` feature for dependency publishing and resolution. Here is the [commit](https://github.com/Kotlin/kotlinx.atomicfu/commit/09b266663f3acacca395b8da354c9b0758d5852a) reproducing the issue.

### Steps to Reproduce
The issue may be reproduced without any plugins by the following build script (on Mac OS, for other operating systems the dependency coordinates should be changed accordingly):

```
import org.gradle.api.internal.FeaturePreviews

services.get(FeaturePreviews.class).enableFeature(FeaturePreviews.Feature.GRADLE_METADATA)

repositories {
    ivy {
        url 'https://nodejs.org/dist'
        layout 'pattern', {
            artifact 'v[revision]/[artifact](-v[revision]-[classifier]).[ext]'
        }
    }
}

configurations {
    foo
}

dependencies.foo "org.nodejs:node:8.11.1:darwin-x64@tar.gz"

task test {
    doLast {
        println(configurations.foo.files)
    }
}
```

Disabling the `GRADLE_METADATA` feature fixes the issue. Changing metadata source for the repo in the following way:

```
metadataSources {
    artifact()
}
``` 

also fixes the issue.

### Environment
The issue is reproducible on Gradle 4.6 and the latest nightly build (4.8-20180411000011+0000)
 * Build scan URL: https://scans.gradle.com/s/clsxflw5yuys4

**Comment by melix** [comment]
Hi @ilmat192 ,

This is the expected behavior, and the reason why we have a feature preview flag, so that you can find such issues. When `GRADLE_METADATA` feature is activated, we also disable the legacy lookup for artifacts when metadata is missing.

This feature causes significant cache misses overhead, because for each repository, we look for metadata, and if it's missing, we try to get an artifact. Those days, almost all libraries are correctly published with both metadata (pom.xml, ivy.xml) and artifacts alongside, so this legacy mode is no longer required.

This means that if you have a repository that is setup like that, and that you enable the new Gradle metadata feature, you have to explicitly opt-in for artifact resolution by doing:

 ```
metadataSources {
    artifact()
}
```

Does it make sense?

**Comment by ilmat192** [comment]
Hi @melix ,
Thank your for the clarification! I think it makes sense so the only thing we need to do is to inform maintainers of `com.moowork.node` about this case. I'll make a PR in their repo.

Close the issue since it's not a bug.
