### ISSUE TITLE
To disable entering continuous build in runPlaybinary task

### ISSUE THREAD

**Issue by h-ngo** [gradle/gradle#5026]
For some reasons (probably default settings?), gradle rPB will automatically enter continuous build even without -t or --continuous tag

Log:

> Task :sample-play-rest:runPlayBinary 
Running Play App (:sample-play-rest:runPlayBinary) at http://localhost:7777/

BUILD SUCCESSFUL in 14s
10 actionable tasks: 4 executed, 6 up-to-date

Reloadable deployment detected. Entering continuous build. <------------ _Is there anyway to disable this?_

Gradle version: 4.4

**Comment by blindpirate** [comment]
Unfortunately, since 4.2, Gradle's `runPlayBinary` task will always rebuild and reload Play application automatically when file changes are detected, no matter whether `--continous` is enabled. This is because we think `runPlayBinary` task as a task for local development so its default behavior should act like this. As for your issue, I think a simple task declaration may meet your needs:

```
    task runPlayDist(type: Exec){
        dependsOn 'stage'
        commandLine 'build/stage/playBinary/bin/playBinary'
    }
```

 where stage task collects all application code/assets/configurations and dependency jars together, then generates start scripts for both Unix and Windows. To run the Play application without rebuilding and reloading at all, we just need to run the corresponding start script.
