### ISSUE TITLE
Provides access to the raw command line arguments to Gradle in StartParameter

### ISSUE THREAD

**Issue by sic-bre** [gradle/gradle#5041]
Currently when running Gradle there is no way at run time to determine the exact arguments that were passed on the command line to run the build.  StartParameter only provides the processed results after arguments have been parsed.  In certain cases such as an init.gradle script it would be useful to be able to determine the exact arguments that were used as provided by the user. 

### Expected Behavior
StartParameter should be extended with a new read only "List<String> args" property that contains the arguments to Gradle as passed at invocation time by the user.  Currently in the startup process passes args through the call chain GradleWrapperMain -> WrapperExecutor -> BootstrapMainStarter -> ProcessBootstrap -> Main -> CommandLineActionFactory -> CommandLineParse.parse() where it parses arguments and throws away the original List<String> args value.  This function should store the original args in the returned ParsedCommandLine object and subsequent processing should add this value to the user exposed StartParameter as a read only informational value.

### Current Behavior
Command line args is not preserved.

### Context
In an init.gradle script you sometimes want to change the default behavior of the build.  For example multiple inputs can affect the same StartParameter.isBuildCacheEnabled() value and there is not enough information remaining to determine the users intent.  Both org.gradle.caching and --build-cache / --no-build-cache flags affect the value of this StartParameter.  In an init.script where we want to change the default value from false to true it is important to distinguish between isBuildCacheEnabled being set by 1) it's default value, 2) being set by a property, or 3) being set by a command line --build-cache or --no-build-cache.

### Steps to Reproduce (for bugs)
N/A

### Your Environment
Gradle 4.6 and Gradle 4.7-rc-2 all environments.

**Comment by oehme** [comment]
I don't think adding access to the raw command line is the way to go here. Instead I think we should provide a way to put gradle properties into a custom distribution (instead of doing this with an init script). That way the distribution can provide company defaults which the user can override.

**Comment by sic-bre** [comment]
We do not use custom distributions at our site.  We are distribute a wrapper init.gradle that executes scripts from a remote URL that is maintained centrally, this same script is used on the CI servers.  This allows us to change the plolicy behavior of the init.gradle globally without having to tell every user to change which distribution they are to use.  It also has the advantage that it is a simple file to distribute:

```
initscript {
    apply from: 'https://server.standard.com/initscript.init.gradle'
}
apply from: 'https://server.standard.com/bootstrap.init.gradle'
```

Can you explain why read only access to the the command line arguments as provided by the user of the tool is causing such distress?  I really don't understand what the issue is here in that we are not asking to change the behavior of the tool in any way that isn't already possible.  Specifically what is wrong on giving the init.gradle script writer visibility into the inputs of the build?  What problems would it create to allow us to see what the developers typed on the command line at runtime?

**Comment by big-guy** [comment]
@sic-bre We really want to avoid exposing the "command-line" in `StartParameter` because the `StartParameter` does not represent the command-line for Gradle. Gradle can be started in several ways, only one of which has a command-line. `StartParameter` has also been a dumping ground for a lot of things that would be better modelled as separate things.

I think there are a few things tangled here:

1. You want to be able to define the default for a given Gradle feature, but still honor a user's intent. Without your init script, the priority is Command-line > User Home > Project.  So if a Project enables the build cache, but the user disables it in their home directory or on the command-line, the build cache will be disabled.  With your init script, the priority becomes Init script > Command-line > User Home > Project. If your init script enables the build cache, it will always be enabled.
2. In https://github.com/gradle/gradle/issues/5041#issuecomment-385030434, you want to be able to define the value for project property/system property that can be overridden by a user.

If we were to expose the command-line arguments, there are a few different issues:

- You would need to know how to properly interpret `-Dorg.gradle.caching=true` vs `--build-cache` vs `--no-build-cache`. You'll be essentially looking at "magic" strings.
- You would not know the user intent from builds started from `GradleBuild`, composite builds, Tooling API (any IDE import/interaction).
- You would not honor user intent for properties defined in the user's home directory.

I think you're looking for a priority order like:
Command-line > User Home > Init script > Project

But this is at odds with the other things that can be done in the init script. There's an implicit "Build script wins" priority, which looks like:
build.gradle > settings.gradle > Init scripts > Command-line or TAPI or Composite > User Home > Project

And there may be a case where a project would want to be able to say the default is different.

I think for 1) we can solve this in another way that fits into Gradle's usual behavior:

1. Ask users to download an `init.gradle` and a `gradle.properties` with "company defaults" into their user home. 
2. Ask users to download an `init.gradle` and write/rewrite `gradle.properties` in their user home with the "company defaults" as necessary.

For 2), I think you could follow a similar pattern, but I would need some concrete examples of those types of properties. You can still use the init script to enforce properties that should never be changed/deviated from.

Does that make sense?

There's a longer term solution we could do here that would better reflect the priority and provenance of a particular flag.  This isn't what we _will_ do, but to give you an idea, you could imagine something like (pseudo):

```
gradleConfiguration.buildCache.setDefault(false)
gradleConfiguration.buildCache.setFromProject(projectGradleProperties['org.gradle.caching'])
gradleConfiguration.buildCache.setFromHome(userHomeGradleProperties['org.gradle.caching'])
gradleConfiguration.buildCache.setFromUser(commandLineGradleProperties['org.gradle.caching'])
gradleConfiguration.buildCache.setFromUser(commandLineFlag['build-cache'])
gradleConfiguration.buildCache.setFromUser(tapiParameters['build-cache'])
// init.gradle:
gradleConfiguration.buildCache.setDefault(true)
```

And then under the covers, Gradle decides the priority explicitly. The default is `true`, but that is only honored if nothing else has expressed an opinion.

**Comment by sic-bre** [comment]
@big-guy I understand your comments but do not fully agree with them.

An init.gradle script is the only reasonable hook I've got to implement policy at the company level.  That script can either be distributed in a custom Gradle distribution or mandated and distributed to the end developers and CI servers.  Changing each individual project (potentially hundreds or thousands of branches) or instructing every developer (potentially hundreds) is not a scaleable option. 

If we change default Gradle behavior in the the init.gradle script the responsibility is on us to "get it right" and know what to do with the "magic strings".  So how with today's capabilities do we change the default caching behavior (as an example) without breaking the runtime behavior of the "magic stings" --build-cache and --no-build-cache in an init.gradle script?  As it stands today not matter what I do in the init.gradle script I wind up overriding the "magic strings" since I have know way of knowing what value they had.

Yes the Gradle runtime can be started (TestKit, etc.) in ways that don't have command line inputs.  In that case my code would not need to worry about command line overrides and depend solely on the StartParamter

**Comment by oehme** [comment]
> So how with today's capabilities do we change the default caching behavior (as an example) without breaking the runtime behavior

You can write `org.gradle.cache=true` to the user's home directory in the init script. Thus the only uncached build will be the very first that the user executes on a given machine. All subsequent ones will be cached by default.

**Comment by sic-bre** [comment]
The answers we have so far are:

1) Hope that every user keeps their ~/build.gradle file up to date with our "suggested" default values, this will not work in our environment.  This wasn't working for us due to the inconsistency and maintenance issues.

2) Manage every users ~/build.gradle file by overriding the value in the file from the init.gradle script.  Working for the naive users but upsetting the advanced users who think they "own" he ~/gradle.properties and will not want me touching it.  Maybe is possible we could analyze the file and only override the values if they were not previously set.

3) Use an init.gradle script (our current solution) but accept that --no-build-cache flag will be ignored.

I still think there should be a clean supported way to change the default value from the init.gradle script without having to touch the user owned override files.  That seems to just be a hack.

**Comment by ldaley** [comment]
I would like to provide an alternative interpretation. 

The problem with `StartParameter` is that it conflates:

1. What was requested of this invocation
2. What is Gradle's default behaviour
3. What is Gradle going to do

This is problematic when a build administrator wants to change (2), as is the case here. I think this is a perfectly reasonable request. 

Ideally, `StartParameter` would _only_ reflect what the invoker asked for. We would use something else for determining default behaviour, and something else for describing what should be done (probably not on a monolithic scale like `StartParameter`).

**Comment by aalmiray** [comment]
I believe the ability to access the unparsed command line arguments (independent of the specific use case as requested by the original poster) is still a good idea.

After all I think this information is captured and presented by build-scans, isn't it? In which case the behavior is already present albeit hidden in private APIs.
