### ISSUE TITLE
SSL peer shut down incorrectly

### ISSUE THREAD

**Issue by fusae** [gradle/gradle#5050]
First time install Android Studio, and gradle sync failed. For some reason, I must to download files through proxy. I set this `org.gradle.jvmargs=-DsocksProxyHost=127.0.0.1 -DsocksProxyPort=1080` in the file `gradle.properties`, using socks5.

And try again, but got the erorr: `SSL peer shut down incorrectly`.

Any suggestions would be appreciated!!

**Comment by marcphilipp** [comment]
Can you try adding `-Djavax.net.debug=ssl,handshake` and post the output here, please?

**Comment by wangyingagora** [comment]
build operations Thread 4, handling exception: javax.net.ssl.SSLException: SSL peer shut down incorrectly
%% Invalidated:  [Session-1, TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256]
build operations Thread 4, SEND TLSv1.2 ALERT:  fatal, description = unexpected_message
build operations Thread 4, WRITE: TLSv1.2 Alert, length = 26
build operations Thread 4, called closeSocket()
build operations Thread 4, called close()
build operations Thread 4, called closeInternal(true)

**Comment by wangyingagora** [comment]
@marcphilipp

**Comment by barnett-yuxiang** [comment]
> -Djavax.net.debug=ssl,handshake

it work, thx ^_^

**Comment by marcphilipp** [comment]
@fusae @wangyingagora Is this still an issue for you?

**Comment by rvasanthbabu** [comment]
Team, 
while running  ./gradlew UDPCurrentAdapter:eclipse --stacktrace, I am getting the below exception.

Caused by: **javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake**
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:394)
Caused by: java.io.EOFException: **SSL peer shut down incorrectly**

**Comment by blindpirate** [comment]
Closing due to long time inactivity.

**Comment by rodrigonmelo** [comment]
My application is getting this error:
SSL peer shutdown incorrect
020-10-05 16:43:11,313 [ 883049]   INFO - .project.GradleProjectResolver - Gradle project resolve error 
org.gradle.tooling.BuildException: Could not run phased build action using Gradle distribution 'https://services.gradle.org/distributions/gradle-6.1.1-all.zip'.
Caused by: org.gradle.internal.exceptions.LocationAwareException: A problem occurred configuring root project 'My Application'.

	... 75 more
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all artifacts for configuration ':classpath'.

Thank you for any help
