### ISSUE TITLE
Use correct memory metrics in containerized environments

### ISSUE THREAD

**Issue by fmattheus** [gradle/gradle#5102]
### Expected Behavior
gradle should try to access only the RAM, which is assigned to it, rather than RAM which isn't available.

### Current Behavior
When running in a container, gradle continually tries to access RAM which isn't available in the container.  The following message is printed.
`10:59:37.947 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] 27039702630 memory requested, 0 released, 5967699968 free
`
As you can see from the message.  Gradle is requesting 27039702630 bytes or ~25GB.  The container only has 12GB available, and gradle is configured to only use 4GB.  this has been set in many places, none of them able to stop this message.  Here is the list of attempted ways to limit the RAM usage:
- export GRADLE_OPTS='-XX:MaxRAM=4096m -Dorg.gradle.jvmargs="-XX:MaxRAM=4096m"'
- export JAVA_OPTS='-XX:MaxRAM=4096m'
- export JAVA_TOOL_OPTIONS=-XX:MaxRAM=4096m
- export _JAVA_OPTIONS='-XX:MaxRAM=4096m'
- org.gradle.jvmargs=-XX:MaxRAM=4096m in gradle.properties

### Context
After switching our build machine from a virtual machine to a container, some jobs have gotten much slower.  IE - One job takes 6 minutes now instead of 4.  I see the above message appearing constantly when running gradle with the --debug flag.  Java 8 sets default values of RAM usage when started without explicit parameters.  It bases this, unfortunately, of the physical server instead of the container, which is why we set the MaxRAM setting to override this, but either gradle is not passing this flag on to all processes, or is going around/ignoring the explicitly set flags.

### Steps to Reproduce (for bugs)
- Create a container with either lxd or docker explicitly setting the amount of RAM available (much lower than host system has available)
- Run a gradle build with --debug, and watch for the above mentioned  messages
- If unable to reproduce, I would be willing to provide an environment where this can be reproduced.

### Your Environment
https://scans.gradle.com/s/yvksnzgbcb2vu

**Comment by oehme** [comment]
You are misunderstanding that message. Gradle is not trying to get more RAM. Gradle is noticing that physical memory is low and trying to shut down some of its processes to compensate.

Now as to why your builds are slower: Is the machine oversaturated? Are you giving each build the same amount of memory as before?

**Comment by fmattheus** [comment]
Machine is a faster machine, with faster disks, less load than before.  I am giving gradle the same amount of RAM as previously.  If I up it from 4G to 8G I still get the same message.  I can also see that it's not actually using all of that RAM, actually it's not even using 1GB.

**Comment by oehme** [comment]
> If I up it from 4G to 8G I still get the same message. I can also see that it's not actually using all of that RAM

It's not about the memory you give Gradle. It's looking at machine memory. If your machine's overall memory is >90% full, Gradle will actively try to reduce its own memory overhead by killing off worker processes. So what we need to find out is why your machine is hitting that memory limit. Are you using forked compilation? If so, did you set a memory limit for the compiler process (otherwise it'll use the JVM default, which is very high).

**Comment by oehme** [comment]
Another speculation: Maybe the OS memory info we get from the JVM is bad and tells us that everything is full just because it is assigned to other containers. In that case we'd need a better data source to make our decisions.

**Comment by fmattheus** [comment]
The machine isn't running out of memory, that's the thing.  It sounds like it's using the wrong parameters to calculate the machine's memory.  IE - it's using the physical machine's total RAM, seeing how much free RAM the container has and that will definitely be less than 90% left.

**Comment by oehme** [comment]
We use meminfo on Linux, which gives us the machine's free memory (not the container's). So those 6GB free is all that the machine has left (according to meminfo). Given that Gradle is trying to free 27GB, I assume your sever has around 256GB of total RAM?

**Comment by fmattheus** [comment]
Yes, the machine has 256GB, and about 200GB free, the container has 6GB
free.

**Comment by oehme** [comment]
Got it, that explains it.

I think the discrepancy is because we use different APIs for total (MBean) and available (meminfo) memory. CC @ghale

**Comment by fmattheus** [comment]
Thanks so much for looking into this, Stefan!

**Comment by oehme** [comment]
For 5.0, we've done a first step in #7058. Gradle will now use a consistent data source for total and available memory. This means it will no longer see false memory pressure.

However, that datasource might still look at the host memory, so Gradle may take more memory than the container is allowed to. To fix this, we'll have to make Gradle aware of `cgroups`.

**Comment by Darkvater** [comment]
Having a similar problem here, but actually much worse. We have tests running and passing successfully on a 2gb docker container. However when the same container is run from a kubernetes pod it gets killed by the container as it is using too much memory. Kubernetes only passes if container has 4gb allocated to it. 

Using Gradle 4.10, all the flags, even adding -XX:+UnlockExperimentalOptions, -XX:+UseCGroupMemoryLimitForHeap to all javaexec, groovyexec and everywhere where possible. 

The problem is that Gradle spawns up a few worker processes (4 for our process) and a test process each nicely adhering to max memory limits, however as they are all different jvm's, their combined memory usage is over the container's limit. 
Gradle doesnt properly keeps track of this and by the time my actual test starts running Gradle is already using about about 2.5gb of ram (4 builders a 500m each, plus main Gradle process).

Is there any way of having the GradleWrapperMain be fully aware of the container limits and contain resources according to those limits?

**Comment by oehme** [comment]
Please give Gradle 5.0 RC1 a try. 4.10 definitely doesn't behave well.
