### ISSUE TITLE
Feature: Allow to store gradle properties (somewhere) in GRADLE_HOME

### ISSUE THREAD

**Issue by stmlange** [gradle/gradle#5144]
I'm currently using a gradle init-script residing in ``GRADLE_HOME`` (https://docs.gradle.org/current/userguide/init_scripts.html) that automatically applies for all my builds. However I was looking for a (global) way to define properties that will be used to configure the Gradle build environment (https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties). For example I don't want to specify ``org.gradle.daemon=false`` (or whatever configuration)  in each and every ``GRADLE_USER_HOME`` (considering multiple developers using the same distribution). is there an option I'm missing to specify such configuration?

### Expected Behavior
pickup ``gradle.properties`` from ``GRADLE_HOME`` (will be overwritten by any settings in ``GRADLE_USER_HOME``)
Alternatively it would be sufficient to set / configure the Gradle build environment via init-scripts as well.

### Current Behavior
``gradle.properties`` inside ``GRADLE_HOME`` or in ``GRADLE_HOME/init.d/`` does not seem to have an effect

**Comment by marcphilipp** [comment]
I'm afraid there's no such option. For custom properties you should be able to workaround this limitation by setting project properties from an init script in your distribution but for things like `org.gradle.daemon` that does not work. Since init scripts are read from `GRADLE_HOME` I don't see a reason why `gradle.properties` should not. However, it's currently not a priority.
