### ISSUE TITLE
Configuration of task "jacocoTestCoverageVerification" fails

### ISSUE THREAD

**Issue by ebruneton** [gradle/gradle#5171]
### Expected Behavior

In the simple project [asm.zip](https://github.com/gradle/gradle/files/1948603/asm.zip), which has 3  Java subprojects depending on each other and the Jacoco plugin, "gradle/gradlew build" should work.

### Current Behavior

The build fails with (both with Gradle 4.6 and 4.7)

> > Task :asm-tree:jacocoTestCoverageVerification FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Some problems were found with the configuration of task ':asm-tree:jacocoTestCoverageVerification'.
> > No value has been specified for property 'classDirectories'.
> > No value has been specified for property 'sourceDirectories'.
> 

For some unknown reason, it seems to fail due to the access to 'sourceSets.main.compileClasspath.asPath' in the 'println sourceSets.main.compileClasspath.asPath' line, because commenting out this line "solves" the issue. Likewise, moving the "apply plugin: 'jacoco'" line just after the "apply plugin: 'java'" line "solves" the issue (it was "solved" like this in https://gitlab.ow2.org/asm/asm/commit/b9cfb3297b40afb2317c5ace7c177a4259764c39).

### Context

The issue occured in https://gitlab.ow2.org/asm/asm/-/jobs/2491, for commit https://gitlab.ow2.org/asm/asm/commit/8776cc0d64203b46feddc7f8dd75c5a225c1f6f2

### Steps to Reproduce (for bugs)

See the simple project attached in section "Expected Behavior", which is a trimmed down version of the full project specified in "Context".

### Your Environment

Linux, Gradle 4.6 or 4.7. Also occurs with Docker and gradle:4.6-jdk8-alpine image.

**Comment by blindpirate** [comment]
Thanks for reporting. I take some time investigating this.

With `println sourceSets.main.compileClasspath.asPath` enabled, all dependencies will be resolved. So the execution order of the last `configure` statement is:

- apply plugin jacoco to asm-analysis project
- println sourceSets.main.compileClasspath.asPath
- resolve all dependencies of asm-analysis project
- because asm-analysis project depends on asm-tree project, asm-tree project will be fully evaluated
- apply plugin jacoco to asm-tree project

Now, jacoco plugin will register some `afterEvaluate` callback to project: https://github.com/gradle/gradle/blob/4f0dbbf637ae2c726714f0a6474b7b1be8f82409/subprojects/jacoco/src/main/java/org/gradle/testing/jacoco/tasks/JacocoReportBase.java#L234

But asm-tree project is already evaluated, so these `afterEvaluate` callback will never be executed.

Without `println sourceSets.main.compileClasspath.asPath`:

- apply plugin jacoco to asm-analysis project
- apply plugin jacoco to asm-tree project
- execute jacoco callback of asm-analysis project
- execute jacoco callback of asm-tree project

So my suggestion is, put all `apply` in one place and before any other actions:

```
subprojects {
  repositories { mavenCentral() }
  apply plugin: 'java'
  apply plugin: 'jacoco'
  check.dependsOn jacocoTestCoverageVerification

  group = 'toto'
  version = '6.1.2'
  test { useJUnitPlatform() }
  dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.1.0',
        'org.junit.jupiter:junit-jupiter-params:5.1.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.1.0'
  }
}

project(':asm-analysis') {
  dependencies { compile project(':asm'), project(':asm-tree') }
}

project(':asm-tree') {
  dependencies { compile project(':asm') }
}

configure(subprojects) {
  // Commenting this line fixes the issue
  println sourceSets.main.compileClasspath.asPath
}
```

**Comment by oehme** [comment]
You should never resolve dependencies at configuration time. To compute arguments lazily, use `[CommandlineArgumentProvider](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:argumentProviders)`s.
