### ISSUE TITLE
Dependency substitution is broken for those with <type> attributes in POM files

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#5174]
### Steps to Reproduce (for bugs)
(Sample project: [DependencySubstitutionBug.zip](https://github.com/gradle/gradle/files/1949410/DependencySubstitutionBug.zip).)

1. Create an empty Gradle project with the following build.gradle file:
```
plugins {
    id 'java-library'
}

repositories {
    jcenter()
    google()
}

dependencies {
    implementation 'com.google.android.gms:play-services-basement:15.0.0'
}

configurations.all {
  resolutionStrategy {
    dependencySubstitution {
	substitute module("com.android.support:support-v4:26.1.0") with module("com.google.guava:guava:23.0")
    }
  }
}

task listDependencies {
    doLast {
        configurations.compileClasspath.each { File file -> println file.path }
    }
}
```

2. Run ` ./gradlew dependencies`, observe that the dependencies are replaced correctly:
```
\--- com.google.android.gms:play-services-basement:15.0.0
     \--- com.android.support:support-v4:26.1.0 -> org.apache.commons:commons-math3:3.6.1
```

3. Run `./gradlew listDependencies`, build fails with the following error:
```
Execution failed for task ':listDependencies'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find support-v4.aar (org.apache.commons:commons-math3:3.6.1).
     Searched in the following locations:
         https://jcenter.bintray.com/org/apache/commons/commons-math3/3.6.1/support-v4-3.6.1.aar
```

For some reason, Gradle is still looking for `support-v4.aar`, even though it should have been replaced.

Note that `com.google.android.gms:play-services-basement` and several other libraries have this problem, while others do not. I'm not sure if the bug is in Gradle or in the libraries.

### Your Environment
Gradle 4.6

**Comment by jdochez** [comment]
some more details. the example provided is not exactly what we are experiencing inside. 
what we do is trying to replace 
commons/commons-math3/3.6.1/commons-math3-3.6.1.aar
with something like 
commons/commons-math4/1.0.0/commons-math4-1.0.0.aar

so we replace name and version accordingly 
but Gradle instead ends up looking for 
commons/commons-math4/1.0.0/commons-math3-1.0.0.aar

I got lost in the caching code but this method on DefaultModuleComponentArtifactIdentifier looks suspicious 
    @Override
    public String getFileName() {
        StringBuilder builder = new StringBuilder();
        builder.append(name.getName());
        builder.append('-');
        builder.append(componentIdentifier.getVersion());
        if (GUtil.isTrue(name.getClassifier())) {
            builder.append('-');
            builder.append(name.getClassifier());
        }
        if (GUtil.isTrue(name.getExtension())) {
            builder.append('.');
            builder.append(name.getExtension());
        }
        return builder.toString();
    }

shouldn't it be : 

    @Override
    public String getFileName() {
        StringBuilder builder = new StringBuilder();
        builder.append(**componentIdentifier**.getName());
        builder.append('-');
        builder.append(componentIdentifier.getVersion());
        if (GUtil.isTrue(name.getClassifier())) {
            builder.append('-');
            builder.append(name.getClassifier());
        }
        if (GUtil.isTrue(name.getExtension())) {
            builder.append('.');
            builder.append(name.getExtension());
        }
        return builder.toString();
    }

**Comment by melix** [comment]
Thanks for the report @hungvietnguyen , we'll look into this. In the mean time, I think you can workaround this issue by using the new component metadata rules API. Its purpose is to "fix bad metadata", so you could write a rule that replaces the dependencies of modules _before_ they appear in a graph:

build.gradle.kts
```kotlin
dependencies {
   components.withModule("com.google.android.gms:play-services-basement") {
       allVariants {
           withDependencies {
                removeAll { it.group == "com.android.support" && it.name == "support-v4" }
                add("org.apache.commons:commons-math3:3.6.1")
           }
       }
   }
}
```

**Comment by hungvietnguyen** [comment]
I noticed that the pom file of `com.google.android.gms:play-services-basement:15.0.0` has this tag: `<type>aar</type>`.
```
<dependency>
    <groupId>com.android.support</groupId>
    <artifactId>support-v4</artifactId>
    <version>26.1.0</version>
    <scope>compile</scope>
    <type>aar</type> <!-- *** <== HERE *** -->
</dependency>
```

If I remove that tag, it starts working. Maybe that gives a clue to debug this.

**Comment by mathjeff** [comment]
I discovered the same symptom of "could not find filename.aar" when the dependency substitution says to replace a direct module dependency with a project.
(Does that indicate "Dependency substitution is broken for those with <type> attributes" rather than "Dependency substitution is broken for those with <type> attributes in POM files"?)

(The use case for why we (AndroidX) would want to do this is we'd like to double-check that all libraries being currently built are compatible with each other (in addition to being compatible with module versions declared in their dependencies)).

I made a sample reproduction case at https://github.com/mathjeff/gradle-samples/tree/master/project-substitution_aar-not-found , which essentially says:

  dependencies {
    api("jeff.jeff-core:jeff-core:1.0.0@aar")
  }
  project.configurations.all {
    resolutionStrategy.dependencySubstitution {
      substitute(module("jeff.jeff-core:jeff-core:1.0.0")).with(project(":jeff-core"))
    }
  }

I didn't manage to get the workaround at https://github.com/gradle/gradle/issues/5174#issuecomment-384532039 to succeed in that case, though.
If anyone has any suggestions, that would be great :)

**Comment by melix** [comment]
In Gradle 6.6 you will be able to write a rule like this:

```
  resolutionStrategy.eachDependency { details ->
       if (details.requested.group == 'com.android.support' && details.requested.module=='support-v4') {
           details.useTarget("org.apache.commons:commons-math3:3.6.1")
           details.artifactSelection {
               selectArtifact("jar", "jar", null) // type jar, extension jar, no classifer
           }
       }
  }
```

Which solves this problem by saying that we want to substitute the dependency with a dependency on a different type.

**Comment by ljacomet** [comment]
@melix As 6.6 RC1 is right around the corner, can this be closed?

**Comment by melix** [comment]
Sure

**Comment by hungvietnguyen** [comment]
Hi @melix, it seems that the original issue is **not yet fixed**. I think there are 2 issues that were reported here:
1. Dependency substitution is broken for `com.google.android.gms:play-services-basement:15.0.0`. Specifically, `com.google.android.gms:play-services-basement:15.0.0` depends on `com.android.support:support-v4:26.1.0:aar` (note the tag `<type>aar</type>` in its pom file; without it, there wouldn't be an issue). If we replace `com.android.support:support-v4:26.1.0` with *anything* (jar or aar), the build will fail as originally reported.
2. Dependency substitution didn't work if a dependency was replaced with another dependency of a different type. According to your comment above, this issue has been fixed.

To demonstrate that the original issue is not yet fixed, please use the original attached project, update to Gradle 7.0, and change this line
```
substitute module("com.android.support:support-v4:26.1.0") with module("com.google.guava:guava:23.0")
```
into this line
```
// Both dependencies are of type `aar` (this eliminates the complexity around aar being replaced with jar)
substitute module("com.android.support:support-v4:26.1.0") with module("androidx.legacy:legacy-support-v4:1.0.0")
```

Run `./gradlew listDependencies`, the build will fail with:
```
Could not find support-v4-1.0.0.aar (androidx.legacy:legacy-support-v4:1.0.0).
     Searched in the following locations:
         https://dl.google.com/dl/android/maven2/androidx/legacy/legacy-support-v4/1.0.0/support-v4-1.0.0.aar
```

**Comment by melix** [comment]
I think I understand what's going on. When you're saying `substitute module("com.android.support:support-v4:26.1.0") with module("androidx.legacy:legacy-support-v4:1.0.0")` you're telling "whenever you see support-v4, replace it with "legacy-support-v4". Because `com.google.android.gms:play-services-basement:15.0.0` depends on `com.android.support:support-v4:26.1.0:aar` then you're substituting `com.google.android.gms:play-services-basement:15.0.0` with `androidx.legacy:legacy-support-v4:1.0.0:aar`.

However, you'll notice that there's this `:aar`, which is an _artifact selector_. In dependency substitutions, artifact selectors are _preserved by default_. So when we select `legacy-support-v4`, we will use the _same artifact selector as the original dependency`, which was (`name=support-v4`, `type=aar`) (note that the _name_ is preserved). This is why you get a file not found exception for `support-v4-1.0.0.aar` instead of what you expected, which is `legacy-support-v4-1.0.0.aar`.

So if you want to substitute with a _different artifact selector_, that is to say _no artifact selector_ in this case, then you need to write:

```
	    substitute module("com.android.support:support-v4:26.1.0") using(module("androidx.legacy:legacy-support-v4:1.0.0")).withoutArtifactSelectors()
```

I tried this on your test project and it resolves as expected: https://scans.gradle.com/s/mymepuztuwbg2/console-log#L2

Now you might say "but why do you preserve artifact selectors"? The reason is backwards compatibility. This is a breaking change to default to no artifact selector as Gradle has always performed substitutions by preserving, so by changing the default we would break passing builds today.

**Comment by hungvietnguyen** [comment]
Nice, thank you for the detailed explanation!!

> Now you might say "but why do you preserve artifact selectors"? 

It did have that question (or more precisely, "If the pom file wasn't wrong, and the dependency substitution rule wasn't wrong, why would the build break?"). It's good to see you've answered that before I even ask. :)

To be clear, I still think this is an issue in Gradle, because the artifact selector `(name=support-v4, type=aar)` was inferred by Gradle, it's not specified by the library or the build script. However, using `withoutArtifactSelectors()` is an easy-enough workaround, so the fix for this (if there can ever be a fix) is not super critical.
