### ISSUE TITLE
New User Manual site is very difficult to navigate

### ISSUE THREAD

**Issue by baron1405** [gradle/gradle#5205]
Try to find the User Manual section that talks about creating archive files such as a Zip. In the old layout, you could just look on the table of contents for Zip. With the new layout, it is completely unclear how to find that information. There is no search. The DSL reference for the Zip task does not point to the corresponding manual entry. In fact, the entire new user manual layout appears to be oriented to someone new to Gradle. For anyone else, the new layout is somewhere between very inefficient and useless. Please bring back a User Manual that a novice and experienced Gradle user can easily navigate.

**Comment by oehme** [comment]
@eriwen can you take a look at this request please?

**Comment by baron1405** [comment]
Thanks @eriwen for the detailed response! I guess old habits die hard and I go to the homepage docs link. Anything you can do the make the docs page/user manual more useful to those who want to search for a detailed item would be appreciated.

**Comment by madorb** [comment]
It would be great to make that link more clearly  available as personally I find the nonlinear structure makes it very difficult for me to progressively build my knowledge base about gradle. 

Some sections are simply sorted alphabetically (See under "Build Configuration Scripts") and some will refer to things as being previously mentioned... but since there is no clear logical order to consume the content in (even in the index), that doesn't hold true.

**Comment by eriwen** [comment]
Noted @madorb. Peter is considering how we can improve navigation, and I'd wager such a link will be much more prominent
