### ISSUE TITLE
Add public API to allow custom extensions to Gradle module metadata

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#5223]
I believe that allowing users to opt-in to extensions to Gradle's module metadata files may allow uses that we haven't thought of. 

For example, could one model JavaScript or Go dependencies with the current format? Wouldn't it be incredible if someone were able to achieve such things?

### Context
This [came up on Gradle Community Slack](https://gradle-community.slack.com/archives/CA7UM03V3/p1524938027000112), and I thought it might have a lot of merit.

**Comment by melix** [comment]
I think it's a bit premature. The Gradle module metadata file serves (at least) a couple of purposes:

1. model published software components, in particular variants and their dependencies
2. be independent of the ecosystem

It typically works great for both Java and Native ecosystems right now, and we're adding features as required, long thinking if there's no other way to model things. That's why, typically, we hesitated for a long time before integrating excludes there, because they don't model things properly.

Attributes are typically things that have a purpose in this model, which is dependency management, They are the key to variant aware dependency management, so they can't be used to model arbitrary data.

Last but not least, we think the module metadata file shouldn't be bound to Gradle, so typically interpretation of data found in a module file shouldn't depend on the application of a plugin. This could allow other tools to consume it.

So instead of opening the API, I think we should collect the use cases first, and see what is missing in the model to support it, and add things if they make sense.

**Comment by adammurdoch** [comment]
+1 to collecting use cases instead (each as a separate issue), rather than presuming an implementation.

In general, I probably wouldn't implement any use case by making the metadata extensible, but instead make the Gradle _model_ extensible in the right ways. The metadata can then be generated from the model. This approach means that the use case then will also work for project dependencies, within composite builds, buildSrc, and source dependencies, and when exporting the model to things other than a binary repo, such as an IDE or another build tool.

I think we should try very hard to keep the Gradle metadata as a simple serialization of the Gradle model only.

**Comment by oesolutions** [comment]
I reviewed the module metadata spec, the descriptions in the dependency management feature previews doc, and the comments here. My use case no longer seems like a very good fit since the data I'm looking to store is not really related to dependency management.

We currently model a deliverable product as a collection of resources to be installed (dependencies pointing to installable binaries). Each of these resources can have attributes that are handled by the deployment tools (these tools are implemented/backed by Gradle). An example resource attribute would be a system reboot flag, or target platform types for that resource. These attributes are tunneled through maven repositories in a similar fashion to the Gradle module metadata (we store a json file as part of the publications).

When I first saw the module metadata file I thought it could be a good replacement for our own json metadata artifact handling. What might be a better fit is if the artifact resolution query API could be extended to include additional artifact types.
