### ISSUE TITLE
Make archive tasks use public APIs to be a better example for the community

### ISSUE THREAD

**Issue by wilkinsona** [gradle/gradle#5239]
### Expected Behavior

Spring Boot's Gradle plugin contains a `BootJar` task that is largely similar to Gradle's `War` task. I'd like to add `getBootInf()` and `bootInf(Action<CopySpec>)` methods that are analogous to the `War` task's `getWebInf()` and `webInf(Action<CopySpec>)` methods. Those methods can be implemented without having to use internal API.

### Current Behavior

Implementing the above-described methods requires the use of `DefaultCopySpec` and its `addChild` method, both of which are internal API.

### Context

I want to offer functionality that's similar to the first-party `War` task in a third-party plugin.

**Comment by oehme** [comment]
The public API is there already, our tasks just don't use it, because the private API is slightly terser. I think this is a bad situation and we should decide to either use the public API ourselves or provide the same `addChild` API that we use for users.

Meanwhile, here is a [commit](https://github.com/gradle/gradle/commit/751e9f70038327643c87a30ae29dae3a3c5da5a8) that uses the public API in the War task.

**Comment by wilkinsona** [comment]
Thank you, @oehme.
