### ISSUE TITLE
org.gradle.tooling.events.task.TaskSuccessResult's isUpToDate() and isFromCache() are not mutually exclusive

### ISSUE THREAD

**Issue by hungvietnguyen** [gradle/gradle#5252]
### Current Behavior
When using the Tooling API to detect if a task's results were retrieved from the build cache, I noticed that org.gradle.tooling.events.task.TaskSuccessResult returns both isUpToDate()=true and isFromCache()=true when the task was FROM_CACHE.

This is probably a bug as UP_TO_DATE and FROM_CACHE should be mutually exclusive.

### Your Environment
Gradle 4.6

(Sorry for the brevity of the report. Let me know if you need more info.)

**Comment by big-guy** [comment]
This is intentional.  Tasks that are loaded from cache are also considered up-to-date because we did not execute the task's actions.  This also helps with backwards compatibility with older TAPI clients.

I understand that this is a little confusing because we have [task outcomes](https://docs.gradle.org/current/javadoc/org/gradle/testkit/runner/TaskOutcome.html) that use similar names (FROM_CACHE, UP_TO_DATE) that are mutually exclusive. `TaskSuccessResult` is intended to represent different properties of the task result, not specific states/outcomes.
