### ISSUE TITLE
Allow extension of the Native Library Resolver / Locator

### ISSUE THREAD

**Issue by JacisNonsense** [gradle/gradle#5274]
I'm writing a plugin that deals with the native side of gradle, in particular, dependency management.
In order to make linking libraries provided by the plugin easier on the user-side, I'm attempting to make these libraries available through the Map notation:
`lib library: "<name>"`

After some digging, I found that the code responsible for finding these libraries is the job of the DefaultLibraryResolver, which in turn uses an instance of the LibraryBinaryLocator interface to find the binaries matching the given name. These are internal classes, of course.

### Expected Behavior
To be able to add a LibraryBinaryLocator (or some other suitable interface that isn't internal) to this process in order to locate libraries registered by plugins that don't fit into the prebuilt library infrastructure.

### Current Behavior
No such ability exists, to my knowledge.

### Context
The plugin in question fetches native libraries from maven, or other sources. These binaries are not able to be registered as prebuilt libraries as they carry some extra attributes we need to access during compile. Being able to add a locator for these libraries would be the best way to ensure they get used in a fashion users are familiar with (the Map notation)

### Steps to Reproduce (for bugs)
N/A

### Your Environment
N/A

**Comment by lacasseio** [comment]
Thanks @JacisNonsense for the feature request.

I'm assuming you are using the software model native plugin. Due to a [change of direction regarding the software model](https://blog.gradle.org/state-and-future-of-the-gradle-software-model), we are introducing [new native plugins](https://blog.gradle.org/introducing-the-new-cpp-plugins). Those new plugins use Gradle's dependency management and [can already pull binaries from Maven](https://github.com/gradle/native-samples/tree/master/cpp/prebuilt-binaries). We still have some polishing to do with those plugin before making them stable, but I still encourage you to have a look at the [native samples](https://github.com/gradle/native-samples/tree/master/cpp) using those sample and see if that can solve your issues.

I'm going to close this issue and point you to the [Gradle native repository](https://github.com/gradle/gradle-native) to get a feel of any opened issues that you may require for your project to work on the new plugin. Don't hesitate to vote on the issues that are important to you.
