### ISSUE TITLE
Disable detached configurations?

### ISSUE THREAD

**Issue by vitalyster** [gradle/gradle#5284]
Gradle project configuration takes ages for me with "resolving dependencies for xxx:detachedConfiguration158" messages. Why so many configurations created? How to clean them? How to disable them? Can't find proper documentation for that.
Using Gradle 4.7 (older versions up to 4.2 at least have the same issue)
I'm using this project both with IDEA and command-line Gradle builds, so I'm not sure who exactly creates these detached configurations every time.

**Comment by oehme** [comment]
For configuration time performance issues, please provide the following information:

- a build scan by running `gradle help --scan`
- a JFR snapshot by using the [Gradle Profiler](https://github.com/gradle/gradle-profiler) running `gradle-profiler --profile jfr --warmups 10 --iterations 20 help`

Without this information we won't be able to help.

Answering your initial question: There is no way to "disable" detached configurations, they are there for a reason, usually because a plugin needs some dependencies for task execution. However, they should never be resolved at configuration time, so there must be some misconfiguration in your build or some bug in a community plugin you are using. The information I requested above will help us find out where that problem is.

**Comment by vitalyster** [comment]
both build scan and profile snapshot (for 'help' task) does not show any performance issues and there was no these "resolving dependencies for detachedConfigurationXXX" messages

**Comment by vitalyster** [comment]
I did scan on 'check' target I see dozen of detached configurations on "Dependencies" page of scans.gradle.com interface, and most of them are contains Spring Boot dependencies. Indeed, problem started when I switch my Spring project to Spring Boot 2 and looks like it is the issue with their Gradle plugin

**Comment by oehme** [comment]
In that case please share the build scan with them so they can fix any potential problems.

**Comment by gavenkoa** [comment]
I have probably same issue. It can be related to `'io.spring.dependency-management'` plugin.

See:

https://discuss.gradle.org/t/what-is-detachedconfiguration-i-have-a-lots-of-them-for-each-subproject-and-resolving-them-takes-95-of-build-time/31595
