### ISSUE TITLE
Add a '-g' CLI option to switch the gradle.properties file to a alternate one

### ISSUE THREAD

**Issue by zosrothko** [gradle/gradle#5312]
In the same way as the CLI option `-b`or the `-c`
```
-b, --build-file          Specify the build file.
-c, --settings-file       Specify the settings file.
```

there is a need to choose an alternate gradle.properties file. So this issue is proposing to add the `-g` to specify a alternate gradle.properties file.
```
-b, --build-file          Specify the build file.
-c, --settings-file       Specify the settings file.
-g, --gradle-file        Specify the gradle.propeties file
```

BTW and off topic, for a smoother gradle experience, I would have rename the `-s` option by `-k` and `-S` by `-K`, so that the `--settings-file` shortcut be `-s`

### Your Environment

 * Build scan URL:

**Comment by oehme** [comment]
What's the use case behind this request?

I think we should get rid of options like `-b` and `c`, not add even more. All use cases I've heard so far would be better solved by some conditional logic in the build.

**Comment by zosrothko** [comment]
For the -c, I am using 2 differents settings, one for Windows and one for Linux/OSX. It helps in settings a different build.script for Windows than for Linux/OSX as in settings.gradle.win with
```
rootProject.buildFileName = 'build.gradle.win'
```

Having a alternate gradle.properties is necessary because the Poco application is using external prebuild libraries for OpenSSL, MySQL, PostgreSQL, Redis and MongoDB that are located differently according the platform. Moreover, a user of Poco could also customize the location of such dependent prebuild libraries. Thus in order to have a portable build script, one needs to have multiple gradle.properties, one for each platform.

The options -b a -c should remain IMO

**Comment by oehme** [comment]
Using different settings files for that makes it harder for users to use the build. Instead please use conditional logic depending on the operating system.

Same goes for library locations - you can use conditional logic to determine the correct defaults and the user only adds things to their (one and only) gradle.properties when they want to overwrite something. This provides a much simpler user experience than having to pass different arguments depending on where you are running and also having to pass those args to the IDE.

This is exactly why I think we should remove those arguments - They encourage patterns that are not user friendly.

Unrelated, but looking at your build I'd like to encourage you to use `buildSrc`. There is a lot of imperative logic in them that would be better housed in a plugin, statically compiled and maybe even tested. The build script should really just contain declarative logic. This will have the nice benefit of faster configuration times.

I'm closing this issue because there is already a good, user-friendly way to model your requirements.

**Comment by oehme** [comment]
> That's not possible for now because there is a private Gradle additional extension named: SemiStaticLibraryBinary for Windows only build which is not used/does not work on Linux/OSX. Thus using 2 differents settings files is mandatory.

I don't know what you mean. You simply don't configure that when on Windows. Different settings files is never mandatory.

> That does not work for multiple CI platforms where one has no easy way no no way at all to change the gradle.properties

Again, I don't understand. How does this work currently and why can't you just replace it with some conditional logic?

> Please show me how to do so, I will take the more I could of your proposals.

https://docs.gradle.org/current/userguide/organizing_build_logic.html#sec:build_sources

**Comment by zosrothko** [comment]
" don't know what you mean. You don't have to configure that when on Windows, you can wrap whatever logic in an if-statement depending on the platform. Different settings files are never mandatory." Since this point is out of scope of this issue, I wo'nt explain further now but later if needed.

"Again, I don't understand. How does this work currently and why can't you just replace it with some conditional logic?" That's the point, it does not work currently and there is already a build logic that is splitting the case for Windows/Linux/MacOS using global variables found in gradle.properties. Ideally, one needs one gradle.properties for each CI platform as for exemple

1. On Travis:        gradle -g gradle.properties.travis build
2 On AppVeyor:  gradle -g gradle.properties.appveyor build
3. On VSTF:         gradle -g gradle.properties.vstf build

Moreover, if one Poco's user want to use a different gradle.properties without changing it, he could use
gradle -g my.gradle.properties build

**Comment by oehme** [comment]
Instead of having different gradle.properties you can:

- set project properties using environment variables, which definitely works on Travis at least
- use conditional logic in your build, either detecting the environment automatically or using something like `-Penv=travis`
- user overrides can be done in the users `~/.gradle.properties`

Overall I see no need for another switch or different build/settings files in general. You already have a full programming language at your disposal, so anything you want to do is possible.

**Comment by zosrothko** [comment]
"set project properties using environment variables, which definitely works on Travis at least".  In the gradle.properties, there are 14 properties that need to be changed to adapt the build to the current environment and no, no & no, I do not want to put a burden work on the user's poco side to setup 14 environment variables on Windows/Linux/MacOS while there is a simple, elegant, easy way to define those properties in their private gradle.properties using their favorite text editor.

"use conditional logic in your build, either detecting the environment automatically or using something like -Penv=travis". The build logic is already bloat (win32, win64, linux32, linux64 and osx) and I am not in favor of adding new conditional logic blocks, specially for each CI platform (at least 3 right now).

"user overrides can be done in the users ~/.gradle/.gradle.properties". Yes this will help to properly configure the build for each user, but not for the CI environment.

@adammurdoch @lacasseio What is your position on this extension request? Could you make it happen if you finf it reasonable? Thanks

**Comment by oehme** [comment]
As I said, you have a whole programming language at your disposal. If you absolutely want to model this with property files, just write some code that reads a property file and use a `-P` parameter so the user can tell you which property file to use. This does not require any additions to Gradle.

**Comment by zosrothko** [comment]
OK, will do this way

**Comment by grv87** [comment]
@zosrothko, there are existing plugins that cover your use case, such as https://github.com/stevesaliman/gradle-properties-plugin
