### ISSUE TITLE
Inconsistent API/DSL for configuring attributes on configuration/dependency

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#5400]
I expect a consistent API for mutating attributes, whether that's on a configuration or on an individual dependency.

The `attributes { attribute(foo, "bar") }` syntax works everywhere. 
The `attributes.attribute(foo, "bar")` syntax works for modifying a configuration, and in a component metadata rule, but is invalid for modifying dependency attributes.

This is valid and consistent:
```
configurations {
    compile {
        attributes {
            attribute(quality, "bar")
        }
    }
}
dependencies {
    components {
        withModule('com.google.guava:guava') {
            attributes {
                attribute(quality, "foo")
           }
        }
    }
    compile('com.google.guava:guava:23.0') {
        attributes { 
            attribute(quality, "foo") 
        }
    }
}
```

but this is not:
```
configurations {
     compile {
        // Works fine
        attributes.attribute(quality, "foo")
    }
}
dependencies {
    components {
        withModule('com.google.guava:guava') {
            // This is also fine
            attributes.attribute(quality, "foo")
        }
    }
    compile('org:test:1.0') {
        // This fails, stating that "Mutation of attributes is not allowed"
        attributes.attribute(quality, "foo")
   }
}
```

**Comment by melix** [comment]
I know it's inconsistent and it was an intentional design decision. Basically if we let users call `attributes.attribute(...)`, we have to make the attribute container mutable and it can leak anywhere, and we're not able to perform mutation validation anymore. This is why the javadocs for `getAttributes()` says:

> Mutation of the attributes of a dependency must be done through
> the {@link #attributes(Action)} method.

I'm fine to consider changing this for the sake of consistency, but then we need to realize we're giving away safety, as it becomes possible to accidentally mutate the container after a configuration has been resolved.

**Comment by bigdaz** [comment]
One option to make it consistent is to remove the mutability of `configuration.getAttributes()`.
