### ISSUE TITLE
Console output ordering problem with 4.8-rc-1

### ISSUE THREAD

**Issue by facewindu** [gradle/gradle#5422]
See [this TC log](https://builds.gradle.org/viewLog.html?buildId=12911553&buildTypeId=Enterprise_Master_Components_BuildScansServer_ScansServerTestE2e_Group3&tab=buildLog&_focus=1571)  of a failed build before switching to 4.8-rc-1.

And [this one](https://builds.gradle.org/viewLog.html?buildId=12920272&tab=buildLog&buildTypeId=Enterprise_Master_Components_BuildScansServer_ScansServerTestE2e_Group3&logTab=tree&filter=all&_focus=1576) after switching to 4.8-rc-1.

The exception text is printed between _Publishing build scan..._ and the build scan link.

I noticed the change of behaviour because the [TC build scan integration](https://builds.gradle.org/viewLog.html?buildId=12920272&buildTypeId=Enterprise_Master_Components_BuildScansServer_ScansServerTestE2e_Group3&tab=buildScan) doesn't work anymore.

**Comment by marcphilipp** [comment]
@ghale Are there some output related changss in 4.8?

**Comment by ghale** [comment]
This is because with the plain console we print error messages on a separate stream (stderr) than other output (stdout).  In situations where the output from both streams is then joined into a single stream, we can get some interleaving.  In other words, we can ensure that we print a message to stdout and stderr in the correct order, but we can't guarantee that whatever is joining them on the other side will flush the two streams in the same order that they were written.  You'll notice that even in the link above for the pre-4.8-rc-1 build, there was still some interleaving at the end of the build (i.e. the error message at the end of the build is interleaved with some of the task execution output).  We did make some changes in 4.8 regarding what messages get sent to stderr with the plain console, which could affect the buffering that TC is doing (and therefore affect when the messages get flushed to the joined log) but this interleaving is not new. 

We've got an issue to try to do as much as we can on our side to mitigate this effect (https://github.com/gradle/gradle-native/issues/670), but ultimately, it's largely outside of our control.

**Comment by ldaley** [comment]
We have to continue to provide some input to users that what they are now waiting for is the scan publishing. Batching up all the output would defeat that. We'll have to find another solution.

**Comment by ldaley** [comment]
@marcphilipp @ghale it is worth noting that the output in question here is _not_ written concurrently. Logically, the build scan plugin doesn't write to stdout until after the stderr is written earlier (i.e. after the related `println` calls have returned).

If gradle/gradle-native#670 can be done according to its title, that would indeed solve this. However, I don't really know what the conventional expectation is here for other systems. Is there an expectation of a happens-before contract on ordered console writes to different streams?

**Comment by ghale** [comment]
I'm not entirely sure I understand what you mean when you say a "happens-before contract", but regardless, I don't think we have any expectation in this scenario.  All we know is that we're not attached to a console, so we don't make any assumptions about what the consumer might want to do with the output.  We simply write to those streams in a particular (and determinate) order.  If the consumer is then joining those streams, we hope that they will do so in some meaningful way (such as in the order that the messages were written to the associated streams) but we don't have any expectations or assumptions about what they will actually do with the output.

On the other hand, if we detect that both stdout and stderr are attached to a console, then we can reasonably assume that there is a user watching the output and that the console would join the two streams.  In that case, we join the output on the Gradle side and write all messages as a single stream on stdout (i.e. we don't leave it up to the console to join the streams).  We did try to do this as a matter of course (always join the streams on the Gradle side, whether attached to a console or not) but this immediately raised negative feedback from users that _expected_ messages on separate streams and did _not_ want them joined.

There's a fair bit of skepticism whether https://github.com/gradle/gradle-native/issues/670 will improve the situation any (or at all), but it's something we wanted to try to see if we could prevent the interleaving as much as possible.
