### ISSUE TITLE
pmd plugin:java.lang.IllegalArgumentException: Unknown Language 'xml', supported Languages are java.

### ISSUE THREAD

**Issue by nareshl119** [gradle/gradle#5451]
### Expected Behavior

We should be able to run pmd custom rules for java and xml files.

### Current Behavior

We are getting below error while running xml custom rules with gradle.
java.lang.IllegalArgumentException: Unknown Language 'xml' for ruleXmlRuleDemo, supported Languages are java.

We also took the help from pmd team regarding this issue. Please check it here.
https://github.com/pmd/pmd/issues/1104

### Context

We are using pmd plugin with gradle to run custom pmd rules on our source code. We are able to run java custom rules without any issue. But, we are not able to run pmd xml custom rules on our xml files that are part of our source code.

### Steps to Reproduce (for bugs)

We are also sharing the source code. Please check and help us to fix the issue.

[pmd xml rules.zip](https://github.com/gradle/gradle/files/2015202/pmd.xml.rules.zip)

### Your Environment

 * Build scan URL:

**Comment by adangel** [comment]
The missing xml language problem stems from the default dependencies, that are added for the pmd plugin: https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/PmdPlugin.java#L175-L181
To support xml, the dependency `"net.sourceforge.pmd:pmd-xml:" + extension.getToolVersion()` needs to be added.
Currently it seems, that the gradle pmd plugin only intends to support java, so adding support for other languages should maybe also add configuration switches? Since for other languages, you want to analyze other sources - the sourceSets should be different, too. For xml, you want to analyze "*.xml" files, for Java, you want "*.java" files...

The current workaround for the "unknown language XML" problem, is, to add the dependency manually in build.gradle:

```
dependencies {
    // dependencies for the pmd plugin
    pmd 'net.sourceforge.pmd:pmd-xml:6.3.0'
    pmd 'com.sample:pmd xml rules:0.0.1-SNAPSHOT'
}
```

The issue right now, is: How to configure the correct `sourceSet`, so that the to be analyzed files for the pmd plugin include the "*.xml" files and not the java source files?

**Comment by oehme** [comment]
You can create your own PMD task if you want to analyze anything else but Java. We might change the default to analyze all sources (instead of just Java) depending on how PMD responds to files with unknown extensions.
