### ISSUE TITLE
Let unit test decide if JVM should be restartet afterwards

### ISSUE THREAD

**Issue by ChristianCiach** [gradle/gradle#5579]
We have many unit tests that leave active threads after execution, possibly interfering with following tests. Most unit tests, however, do not.

We are using an JUnit-5-Extension (`@ExtendWith`-annotation) to detect these unit tests. In an ideal world, these unit tests could be modified to properly clean up after themselves. In many instances however, this is not (easily) possible.

The next best way to solve this issue currently is to use "test.forkEvery = 1" in build.gradle, but of course, this slows down things A LOT, even though most of the times restarting the JVM is not necessary at all.

I would like to propose a special exit code (`System.exit(MAGIC_NUMBER)`) that can be used by unit tests to indicate to Gradle that the JVM should be restarted before executing the following tests - or some other mechanism to achieve the same goal.

**Comment by oehme** [comment]
It's of course possible and would work around some of those cases in Gradle, but what about running tests from the IDE? Or what if parallel testing is added to JUnit and such a bad test runs in parallel to a good test? The problem persists. 

I think the only proper way to fix this is to fix the tests. You said it's not *easily* possible, but for me that's not enough of a reason for a feature in Gradle. It would have to be *impossible* before I'd start considering it. If the test itself can't be fixed, there are some other potential workarounds: If you can already detect them, you could send an interrupt to those threads. Or you could move those ill-behaved tests into their own test task and setting `forkEvery` there.

I honestly don't think such a feature, though possible, will ever get implemented. I'm closing this issue in order to not raise any false hopes. If there are more people in support of this, I'd like to hear their use cases and why things can't be fixed in another way.
