### ISSUE TITLE
Change Settings#enableFeaturePreview(String) parameter type from String to Feature

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5686]
Please change the argument type of `Settings#enableFeaturePreview(String)` from `String` to `Feature`.

This provides in-IDE / build-compile fail-fast behavior (instead of build-runtime failure).

It also allows easy discovery of available features by just going to the source for the `Feature` enum.

If you must support previewable features other than those built-in to gradle (e.g., from plugins), then make `Feature` an interface, and change the existing `Feature` enum to something like:

    public enum GradleCoreFeature implements Feature

**Comment by marcphilipp** [comment]
@gradle/kotlin-dsl WDYT?

**Comment by eskatos** [comment]
@marcphilipp, I second @rgoldberg, using a `String` makes it hard to discover from the IDE and error prone (e.g. typo).
But there may be constraints I'm not aware of wrt listing those features.

**Comment by marcphilipp** [comment]
@ljacomet You've originally introduced `Settings.enableFeaturePreview()`, right? I assume it takes a `String` because the `Feature` enum is internal and imposes restrictions on compatibility (deleting enum constants etc.)?

**Comment by ljacomet** [comment]
That was the original thinking indeed.
But looking at the code, there is also a flag on a `Feature` to indicate if it is active or not. And I believe if we agree to keep inactive features declared, we should be good in terms of compatibility.
And with that flag, we could even do `in use -> deprecated and not in use -> removed` cycles to get rid of values.
Now there might have been also the concern of adding this to the public API while it is usually an advanced feature.

**Comment by rgoldberg** [comment]
As an as side, `active` is a confusing term as it almost seems to indicate that the feature preview has actually been enabled. I think a better term might be along the lines of `previewable`, `enableable`, or `activatable`

**Comment by melix** [comment]
-1

Despite the interest of completion, that we did consider, I think we shouldn't change this, for 2 reasons:

1. as @marcphilipp explained, we're using an enum internally, but we can't just expose it. By nature, experimental features are short-lived, subject to change, even in name (happened several times already). We even considered completion itself, and thought that it wouldn't make sense for the idea to show items for things which have long disappeared, or been made the default. Also, there are currently only 2 experimental features which are going to be made the default in 5.0. After that, it's unclear if we will have a lot of features which need a flag (dependency management is a good candidate for those because it's easy to change the behavior of a build by implementing new features).

2. it's very low priority. What we want is a low cost infrastructure to maintain. We have a very large bug and feature backlog, so I'd prefer working on this backlog than on opening an API for experimental features.

**Comment by bigdaz** [comment]
We're not planning on making this change, since we want to keep the `enum` internal. "Feature previews" should be rare, and considered experimental. I don't think we need to make them more discoverable.
