### ISSUE TITLE
Allow includeBuild calls to be in any order

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5699]
In Gradle 4.8, the order of `includeBuild` calls in `settings.gradle.kts` is important.

e.g., if project A has a `buildscript.dependencies.classpath` dependency on the coordinates of project B, then `includeBuild("B")` must be called before `includeBuild("A")` to resolve this dependency.  If A is included before B, then you'll get an unresolved dependency error.

Please allow `includeBuild` calls to be in any order.

Instead of reporting an error and aborting on an unresolved dependency, wait until all `includeBuild`s have run, then see if any of the included builds can supply the missing dependencies.

**Comment by adecker89** [comment]
I've run into this issue as well. What I've found during testing is that if all dependencies do exist, then all `includeBuild` dependencies will be eventually substituted to the correct project regardless of order. However, if a dependency does not exist and you've declared your `includedBuild`'s in the wrong order then you will get an error before the composite build dependencies can be substituted.

**Comment by rgoldberg** [comment]
@adecker89 I'm not exactly sure what you're saying.

Are you saying that if all the dependency coordinates can be resolved against their build's repositories set, then a composite build will build fine regardless of the order of the `includeBuilds`?

If that's the case, that doesn't help me because I have a custom Gradle plugin that is an included build, and it's not deployed on any repo.  I use that custom plugin in all of my other included builds.

If you're saying something else, what do you mean by "that if all dependencies do exist"?

**Comment by adecker89** [comment]
Yep, that's what I'm trying to say.

I mostly wanted to add some additional insight into the current behavior to help pinpoint the issue. I didn't really see this as workaround because it creates a lot of possible pain for integrating new projects that have not been published yet (or ones that will never be published in your case).

**Comment by ov7a** [comment]
Sorry for the late reply.

This issue needs a decision from the team responsible for that area. They have been informed. Response time may vary.

***

Note: the problem is still reproducible with the latest 9.5.1. However, this issue predates the pluginManagement.includedBuild. The team should discuss the future of the `includedBuild` containing build logic, their eagerness, and what can be done to have a more declarative approach to structuring build logic.

**Comment by 6hundreds** [comment]
This is mostly a valid thing, however using a `buildscript.dependencies.classpath` should be discouraged eventually in favour of plugin. I'm reopening it to make it more visible, although this is not going to be prioritized soon
