### ISSUE TITLE
Enhance --tests switch with support for comma-separated list of expressions

### ISSUE THREAD

**Issue by tcfurrer** [gradle/gradle#5719]
In some cases ([such as with the Netbeans Gradle Plugin](https://github.com/kelemen/netbeans-gradle-project/issues/392)), there are higher levels of code generating the value passed to the Gradle --tests switch.  In some of those cases (and perhaps also for some interactive cmdline users), it is more convenient to provide a comma-separated value to a single --tests switch, instead of multiple --tests switches.

Expected behavior is that:

  --tests A,B

Would be equivalent to:

 --tests A --tests B

Where of course "A" and "B" could be any of the types of wildcard expressions which are already supported today.

Since today there is no support for commas, adding this enhancement shouldn't invoke a significant backward incompatibility.

**Comment by oehme** [comment]
Comma is valid character in a test case name. We want to keep the number of special characters to a minimum. Since you can already define multiple patterns with multiple uses of the switch I don't see how the comma would provide much added value.

**Comment by sschuberth** [comment]
> I don't see how the comma would provide much added value.

Besides shorter syntax and convenience, a list also avoids the potential confusion about how multiple CLI options like `--tests` are handled. It's not uncommon that only the last given occurrence is taken into account instead of being accumulative.

> We want to keep the number of special characters to a minimum.

I'd wish this position would be reconsidered, also in the context of https://github.com/gradle/gradle/issues/6505.
