### ISSUE TITLE
Replacing a task is in Gradle 4.8 is non deterministic 

### ISSUE THREAD

**Issue by atorok** [gradle/gradle#5730]
###  Reproduction repo
https://github.com/atorok/gradle48_jdk11_replace_task

### Expected Behavior
I am aware that replacing tasks has some quirks, but with Gradle 4.8 it just became non deterministic. 
Replacing a task in Gradle should work (snippet from the repo above):
```
Task oldTestTask = project.tasks.findByPath('test')
    project.tasks.remove(oldTestTask)
    RandomizedTestingTask newTestTask = project.tasks.create(name: 'test', type: RandomizedTestingTask)
    newTestTask.dependsOn(oldTestTask.dependsOn)
    newTestTask.dependsOn('testClasses')
    Task checkTask = tasks.findByPath('check')
    checkTask.dependsOn.remove(oldTestTask)
    checkTask.dependsOn.add(newTestTask)
    println "test task is now ${project.tasks.findByPath('test').class}"
```

### Current Behavior
With Gradle 4.8 __only__, this doesn't sometime work.
Note the output below, running against the sample repo with no changes in-between.
```
[:~/work/elastic/gradle48_jdk11_replace_task] master(+122/-0,2) ± ./gradlew clean check -s

> Configure project :
test task is now class RandomizedTestingTask_Decorated
Gradle 4.8
10.0.1 (Oracle Corporation 10.0.1+10)
Found the following `test` tasks
:test -> class org.gradle.api.tasks.testing.Test_Decorated

> Task :clean
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses
> Task :test
> Task :check

BUILD SUCCESSFUL in 0s
4 actionable tasks: 4 executed
[:~/work/elastic/gradle48_jdk11_replace_task] master(+122/-0,2) ± ./gradlew clean check

> Configure project :
test task is now class RandomizedTestingTask_Decorated
Gradle 4.8
10.0.1 (Oracle Corporation 10.0.1+10)
Found the following `test` tasks
:test -> class RandomizedTestingTask_Decorated

> Task :clean
> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes
> Task :compileTestJava
> Task :processTestResources NO-SOURCE
> Task :testClasses

> Task :test
Running tests
random action

> Task :check

BUILD SUCCESSFUL in 0s
4 actionable tasks: 4 executed
```
It seems that JDK 11 makes this _more_ reproducible. 

### Context
The Elasticsearch build replaces the `test` task so tests are ran with:  http://labs.carrotsearch.com/randomizedtesting.html. Some of our test task configuration is also lost in the process resulting in elastic/elasticsearch#31324.

### Steps to Reproduce (for bugs)
Check out the repo and run `./gradlew clean check` multiple times.

### Your Environment
- Gradle 4.8
- 10.0.1 (Oracle Corporation 10.0.1+10)
- `Linux 4.16.8-1-ARCH #1 SMP PREEMPT`

**Comment by atorok** [comment]
This possibly has to do with the lazy task creation API. Gradle 4.7 uses `tasks.create` whereas 4.8 uses `tasks.createLater`

**Comment by marcphilipp** [comment]
Replacing a task in this way is not reliable as it depends on the order tasks get created in.

Have you tried using [overwrite](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:replacing_tasks) or `tasks.replace()`?

Alternatively, have you considered simply disabling the default `test` task, registering your task under a different name and making `check` depend on it? That might be clearer to users of your build.

**Comment by atorok** [comment]
I did try tasks.replace with similar results.
I also found #710 to be relevant to this discussion.

**Comment by marcphilipp** [comment]
@lacasseio Is there a reliable way to replace a lazily created task from a buildscript?

**Comment by lacasseio** [comment]
Thank @atorok for the issue and for taking the time to create a wonderful reproducible example. While working on the upcoming lazy task configuration, we opened a big can of worm around what task removal and replacement should really be. At the moment, we are heavily leaning toward deprecating some scenario around task removal and would suggest a different approach.

Debugging the code you provided, I see the issue is related to exactly why task replacement is somehow flawed with the current design. Thanks to the lazy task configuration work, we now add a dependency to a `TaskProvider` of `Test` to the `check` task. The code that removes the `test` task from the `dependsOn` of the `check` task won't remove the `TaskProvider` and will add a dependency to the new `test` task. The `check` task now depends on 2 tasks named `test`. Since the `dependsOn` is maintained as a `Set` and that Gradle assumes only one task of each name should exist, we get a flaky behavior. Since `dependsOn` can be any type of object, it is wrong to assume we can always remove the task instance itself.

There are two ways to support this use case that I can think of:
1) Create a distinct task with a different name and disable the `test` task using `test.enabled = false`
2) Get a `TaskProvider` of the `test` task using `tasks.named('test')`. Then you can remove the provider from the `dependsOn`. This solution is only for completeness as it is sensitive to one of the biggest flaw of task replacement which is registering a task action that assumes the type for a specific task name.

I will validate what we intend to do with such breakage as code like this depends on the internal implementation of the `java` plugin which is usually unsupported. However, there may be a strong case around the fact that this behavior has been around for a long time and could be considered as essentially public.

**Comment by atorok** [comment]
@lacasseio thanks for the detailed answer!  
We are going to create a task with a different name (elastic/elasticsearch#31324 is tracking this).
We used to replace the task with an implementation that has different fields, so we were breaking comparability not only for task actions, but task configuration as well. 
I think that enforcing type safety around task replacement is a good idea, but like you said it might break a lot of builds. 

To give some context: the elasticsearch ant build back in the day used a test runner that was developed for Lucene then split of into it's own project (http://labs.carrotsearch.com/randomizedtesting.html). When we migrated to Gradle, we kept this runner. Today Gradle still invokes it trough ant. We have a long term goal to use the default test task for this, however we currently get into a deadlock when we do (I'll submit an issue for that shortly). Other than that, there's some features that I think are we can't replicate easily in the Test task, like randomizing class order. I was thinking maybe we could implement like `useTestNG()` for our own `useRandomizedTesting()` to get any missing features, but I don't think there's an extensions mechanism for that, we would have to contribute it and it would have to be accepted. Randomized testing is not that popular but we found it to be extremely valuable. Sorry for going a bit off topic.

**Comment by lacasseio** [comment]
I'm happy the diagnostic was helpful for you. The lazy task configuration is aimed to be announced as incubating in the next release. Some names were are factored in the meantime.

It's nice to see the context around the Randomized Testing. I wouldn't suggest extending the `Test` task to support `useRandomizedTesting()` as we may move to specialized test task for each test framework. We haven't pushed the discussion too far with regards to JVM testing, however, for the native domain, we will be using a different test task type for each testing framework. I feel you should request for a public API to reuse the internal testing infrastructure so you can use it with Randomized Testing. However, I wouldn't wait for this feature to migrate and use a distinct task. The main benefit of using the internal testing infrastructure is you get support for forking, report generation and build scan support.

**Comment by atorok** [comment]
Support for forking is a big one for us. Randomized testing does have support for forking, even balancing the tests based on previous run-times, but  we have a multi project build and would benefit significantly from `--parallel`, having a test runner that doesn't know about Gradles `--max-workers` and parallelism makes this difficult as we can easily get into the situation of running too many forks.

We would like to move to the Gradle runner, but the single most important missing feature for us is pseudo-randomizing test case order based on a controllable seed. I see there's already a precedent in the Gradle code for changing the test case execution order. @lacasseio would you consider a contribution for that to the Gradle Test task ? We are able to do this  since most of the functionality of randomizedtesting is  implemented in a junit runner so we can still `@RunWith`, even if the tests are ran by Gradle.

**Comment by lacasseio** [comment]
In the general sense, if the feature can be implemented via the already provided public API, we are less likely to make it part of the Gradle core implementation. However, this change when the feature is used/required by a large audience. Think of it as a pattern that everyone uses or should be using. That been said, the best is to open a feature request and discuss this with the other engineers. I know it's not a clear answer because it's often a case-by-case analysis.

**Comment by atorok** [comment]
Thanks! I opened  #5760.
