### ISSUE TITLE
For ResolutionStrategy#eachDependency(Action), argument Action not called for transitive dependencies

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5757]
The [docs for `ResolutionStrategy#eachDependency(Action)`](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html#org.gradle.api.artifacts.ResolutionStrategy:eachDependency(org.gradle.api.Action)) say that the supplied argument `Action` "is triggered for every dependency (including transitive)", yet, in Gradle 4.8.1, it only is run for my explicitly included dependencies, not their transitive dependencies.

Are the docs wrong (and the code correct) or are the docs right (and the code buggy)?

A few questions:
 - is there a better term than "explicitly included dependencies"?
 - is determine if a dependency is explicit or transitive, or is it possible to just apply things to transitive dependencies, and not to explicit ones?

**Comment by melix** [comment]
Hi! Do you have a reproducible example? Does it work in 4.7?

**Comment by rgoldberg** [comment]
The issue is caused by a map entry `"ext" to "jar"` being included in the `Map<String, String>` passed as the dependency notation.

See the `build.gradle.kts` in the attached zip.

That map entry has been shouldn't have been there in the first place; removing it fixed the issue for me.

I don't know if including an ext of `"jar"` is supposed to result in `guava` having no transitive dependencies, or if they should still haven been fetched,
[build.gradle.kts.zip](https://github.com/gradle/gradle/files/2126945/build.gradle.kts.zip)

**Comment by oehme** [comment]
Adding `ext` will make Gradle only fetch a single artifact, not its transitive dependencies. This is expected behavior, though I don't think it's well-documented.

**Comment by rgoldberg** [comment]
Should I modify this issue to be for better documentation of this, should I open a new issue, or is an issue unnecessary for a documentation change?

**Comment by bigdaz** [comment]
The documentation could certainly be clearer around this point. Adding any artifact-defining attributes (`ext`, `type`, `classifier`) to a dependency declaration has the effect of telling Gradle to completely ignore the published metadata for the dependency module (including transitive dependencies). Instead, Gradle will resolve _only_ the defined artifact.

I understand that this behaviour is surprising, but it's been like that since Gradle 1.0 and is unlikely to be changed. We are developing variant-aware dependency resolution (with consumer-defined variants and a new metadata format) that will provide a better alternative when it is complete.

A PR improving the documentation for the present behaviour would be welcome. It's covered in the [user guide](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sub:resolve_specific_artifacts_from_dependency), as well as in the [DSL Reference](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.dsl.DependencyHandler.html) and [Javadoc](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/DependencyHandler.html) for `DependencyHandler`. Failing that, an issue describing the lack of documentation would be a start.
