### ISSUE TITLE
IDEA plugin: $MODULE_DIR$ macro behavior change & deprecation

### ISSUE THREAD

**Issue by rgoldberg** [gradle/gradle#5766]
IntelliJ IDEA 2018.1.4 changed the behavior of the `$MODULE_DIR$` macro & deprecated it, providing 2 replacement macros: `$MODULE_WORKING_DIR$` & `$MODULE_IML_DIR$`.

The IDEA plugin should be updated as necessary.

Per the [2018.1.4 release announcement](https://blog.jetbrains.com/idea/2018/05/intellij-idea-2018-1-4-is-released):

> Previously, the `$MODULE_DIR$` variable always pointed to the directory containing `.iml` files.
> However, projects imported from Gradle have the `.iml` file in the `.idea` directory.
> The `.idea` directory normally shouldn’t be used as the working directory for running tests, as this can cause test failures. In order to avoid test failures in such cases, we now point the `$MODULE_DIR$` variable to the module’s content root in case the `.iml` file is located in the `.idea` directory.
> 
> To avoid further misunderstanding, the `$MODULE_DIR$` macro is deprecated.
> 
> We’ve introduced 2 new macros:
> `$MODULE_WORKING_DIR$` for module content directory.
> `$MODULE_IML_DIR$` for directory containing the `.iml` file.

**Comment by oehme** [comment]
We can't just change this, as it would be a breaking change for older IDEA versions. So we'd have to add an option to the plugin. I don't think that's worth it, as you are much better off using IDEA's importer instead of running `gradle idea`. There now is the [`idea-ext`](https://github.com/JetBrains/gradle-idea-ext-plugin) plugin, which extends the `idea` DSL to configure almost any detail of IDEA's importer.

@nskvortsov Can you keep that old variable around for some more time so users who still use `gradle idea` are not broken?

**Comment by wolfs** [comment]
Note there is also a problem with `MODULE_WORKING_DIR` not working in run configurations: https://youtrack.jetbrains.com/issue/IDEA-194910
