### ISSUE TITLE
Plugins defined in plugins {} block are not run in the specified order

### ISSUE THREAD

**Issue by mmorrisontx** [gradle/gradle#5817]
When defining plugins in a plugins {} block, they are not always applied in the order that was given.

### Expected Behavior

```
plugins {
  id 'java'
  id 'com.google.protobuf' version '0.8.6'
  id 'com.example' version '1.0'
}
```
This buildfile should result in the application of java, followed by com.google.protobuf.

### Current Behavior

com.google.protobuf and com.example are applied first.

### Context

Since the `java` plugin is always executed after `com.google.protobuf` when specified in a plugins{} block, this means that `com.google.protobuf` always goes into its "wait for java before applying myself" mode. In the example above, this means the `com.example` plugin cannot configure the protobuf plugin when it is applied. Configuring protobuf in afterEvaluate is also not an option, as this is too late and the protobuf plugin has already processed several of its extension properties.

I know this could be resolved with changes to the plugins, but it still seems like a bug that the java plugin is always saved for last when specified in this way.

### Steps to Reproduce (for bugs)

* Check out https://github.com/sonicsnes/gradle-5817
* `gradle publishToMavenLocal` in example-plugin
* Notice that `gradle jar` in example-app-working passes
* Notice that `gradle jar` in example-app-broken fails (if you run with -i, you'll see that the java plugin was not applied at the time of the exception)
* Both should work.

### Your Environment

4.8.1

**Comment by judgeaxl** [comment]
In that case, I believe you can make your plugin listen for other plugins being applied, deferring your logic until you know which one it is. It’s somewhere in the plugin development guides, but I don’t have a link handy right now. I’d guess you can use the `withType` approach on the plugins collection, but you may want to double check that.

**Comment by lacasseio** [comment]
@sonicsnes I generally agree with @judgeaxl, but am willing to be convinced if we have a good use case. In your case, it seems you are already [reacting to the plugin in questions](https://github.com/google/protobuf-gradle-plugin/blob/master/src/main/groovy/com/google/protobuf/gradle/ProtobufPlugin.groovy#L108-L110), would you mind sharing why the order is important then?

**Comment by sonicsnes** [comment]
In the example above (and in our affected real plugin here at work), we control the source of a third plugin -- we do not have control over the implementation of protobuf-gradle-plugin.

Since protobuf-gradle-plugin consumes its configuration at afterEvaluate, but does not setup its extension until the java plugin has been applied, this provides no suitable location for protobuf-gradle-plugin configuration. Typically you would resolve this by initializing the java plugin first, which would trigger protobuf-gradle-plugin to setup its extensions immediately.

I guess it boils down to this:
(1) If this is to be considered a bug in gradle, we should work toward fixing it.
(2) If this is not to be considered a bug, the gradle docs should state that application order is not guaranteed when using the new plugins DSL, and I will raise an issue in protobuf-gradle-plugin to get a more appropriate spot to handle this sort of configuration.

**Comment by lacasseio** [comment]
We discussed it a little bit and it makes sense for the `plugins` block to be predictable and intuitive, even if we don’t want users to rely on that order. It also helps to work around some plugin bug. It shouldn't be hard to fix. @sonicsnes do you want to give it a shot?
