### ISSUE TITLE
Custom ArtifactCollection issue

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#5821]
When implementing a custom `ArtifactCollection`, a backing `FileCollection` is created using ` project.files(Callable<Collection<File>>)`. However, this did not run the tasks that produce the artifacts specified in the collection e.g. a jar produced by the Java plugin was not created. Changing the code above to `project.files(Callable<Provider<Collection<File>>>)` solved the issue for us.

Here is a sample project: https://github.com/gavra0/repro-artifact-collection.

To reproduce, run: `./gradlew clean fail`.

There is also a working implementation of `ArtifactCollection`. To use that verison, run: `./gradlew clean success`.

**Comment by oehme** [comment]
The `Provider` behavior looks buggy - it should probably fail just like the `Callable` case. The reason is that we [descend into composite file collections](https://github.com/gradle/gradle/blob/8b4149b63d4d3768f59e6f2a090f881cdb914706/subprojects/core/src/main/java/org/gradle/api/internal/file/collections/BuildDependenciesOnlyFileCollectionResolveContext.java#L74) in order to find additional build dependencies. There is a code path for `Callable`, but not for `Provider`. @adammurdoch is this intentional? I.e. do we recommend `Provider` as a way to say "just trust me on the dependencies, don't look deeper" or is this just an oversight?

Your file collection tries to transform the files when we ask it for its contents, which can't work since we're only just building the task graph at that point. What you'd need instead would be a file collection which doesn't look at its contents at all, but purely relies on the build dependencies provided by `builtBy`. We have such a thing internally, but I don't want to recommend using that. Depending on whether the different behavior with `Provider` was intended or not, that might be a solution. If it was unintended, then I think we should have some alternative for you, since this is a common use case.

Slightly off-topic: `ArtifactCollection` (like almost every interface in Gradle) is not meant to be implemented by clients. Please use your own abstraction where necessary, as we may add new methods to these interfaces without notice.

Also, no need to call `buildDependencies` - just pass the `Buildable` object itself to `builtBy`. Gradle knows to call `buildDependencies` on those.

**Comment by big-guy** [comment]
@gavra0 We made some improvements here with dependencies traveling with Providers.  Could you give this another try with 5.2 and reopen this if it's still an issue?
