### ISSUE TITLE
Path is not updated in case-insensitive system when copying files

### ISSUE THREAD

**Issue by regrog** [gradle/gradle#5880]
Coping files has some strange behavior when changing the path case in windows.
Also the task is up-to-date even if a folder case has being changed.

### Expected Behavior
The folder path should be updated with the new case.

### Current Behavior
The paths of the files copied to the destination are not updated and when these resources are accessed via linux, because it's case sensitive, the folders don't exist.

### Steps to Reproduce (for bugs)
[test-gradle.zip](https://github.com/gradle/gradle/files/2169616/test-gradle.zip)
In windows:
run `gradle copyIssue`
open src folder and change the case of the `main` folder
re-run `gradle copyIssue`
the task is **up-to-date** and the path isn't changed

### Your Environment
windows 10
gradle 4.8

**Comment by oehme** [comment]
As far as Windows is concerned, the path did not change. So I'd say this is expected behavior.

**Comment by trejkaz** [comment]
I guess it gets terrible when the file you just copied then ends up going into something like a zip, which might be unpacked on a case sensitive filesystem where it no longer works correctly...

**Comment by oehme** [comment]
@lptr What do you think about this? Is there some way we could detect these changes without breaking performance?

**Comment by lptr** [comment]
I was a bit surprised that Gradle would "optimize away" case changes, and mark the task as `UP-TO-DATE`, so I dug a bit deeper. What actually happens is not that the task is up-to-date, as indeed Gradle detects the change and re-runs the task, as it is printed in the `--info` log and build scans:

```text
The task was not up-to-date because of the following reasons:
--
Input property 'rootSpec$1' file src/main has been removed.
Input property 'rootSpec$1' file src/main/file.txt has been removed.
Input property 'rootSpec$1' file src/main/otherfile.txt has been removed.
```

The problem is that when Gradle asks for the `testlocation/Main` directory, the OS tells it that it it already exists. This is how a case-insensitive file system is expected to work. I don't think Gradle should handle this differently.
