### ISSUE TITLE
Javadoc warning when running against JDK 10

### ISSUE THREAD

**Issue by apjanke** [gradle/gradle#5891]
In a project written against JDK 1.7, when compiling against JDK 10, it gets a warning about the HTML format for the Javadoc not being specified. It would be nice if this were handled automatically.

### Context

I'm working on [`google-maps-services-java`](https://github.com/googlemaps/google-maps-services-java), which uses Gradle, and currently builds against Java 1.7.

I would like to be able to build this project 100% warning-free, on any JDK supported by the project (Java 1.7 through Java 11, ideally), with minimal configuration needed.

### Current Behavior

When building the project on a system where Java 10 is the default JVM, I [get a warning](https://github.com/googlemaps/google-maps-services-java/issues/467) about not specifying the version of HTML for the Javadoc.

```
[~/local/repos/google-maps-services-java]
$ ./gradlew build test

> Task :javadoc
javadoc: warning - You have not specified the version of HTML to use.
The default is currently HTML 4.01, but this will change to HTML5
in a future release. To suppress this warning, please specify the
version of HTML used in your documentation comments and to be
generated by this doclet, using the -html4 or -html5 options.
1 warning
```

But I can't just add an `-html4` or `-html5` option in `build.gradle` like this:

```
javadoc {
    options.addBooleanOption('html4', true)
}
```

because then the build will break when run against JDK 1.7.

```
$ ./gradlew clean build

> Task :javadoc FAILED
usage: javadoc [options] [packagenames] [sourcefiles] [@files]
javadoc: error - invalid flag: -html4
[...]
```

I'm currently using this workaround:

```
javadoc {
    def currentJavaVersion = org.gradle.api.JavaVersion.current()
    if (currentJavaVersion.compareTo(org.gradle.api.JavaVersion.VERSION_1_9) > 0) {
      options.addBooleanOption('html4', true)
    }
}
```

### Expected Behavior

I think it should be possible, or at least would be nice, to be able to do a warning-free build under any supported version of the JDK for a given project, without having to do special configuration that tests the JDK version it's building under.

Maybe Gradle could detect what version of javadoc it's running against, and automatically add a default `-html4` flag for newer versions of javadoc? And maybe provide a convenient `javadoc` property to set the HTML version with, instead of having to do an explicit procedural test against the Java version, which seems kind of icky?

### Steps to Reproduce (for bugs)

To reproduce:

* Install JDK 10 on your system, and point to it as your default
 * (This will happen on Mac by default if you just install JDK 10)
* Clone and build `google-maps-services-java`

```
git clone https://github.com/googlemaps/google-maps-services-java
cd google-maps-services-java
./gradlew clean build
```

### Your Environment

* macOS 10.13.5
* Gradle 4.8.1

 * Build scan URL: https://gradle.com/s/tp3m5hvnah5ys

**Comment by eriwen** [comment]
I reckon this is fixed by https://github.com/gradle/gradle/blame/master/subprojects/docs/docs.gradle#L308 which was added in Gradle 5.2. Can we close this as fixed @blindpirate?

**Comment by eriwen** [comment]
Here's the commit btw: https://github.com/gradle/gradle/commit/c21007a82a3f1c8b0fe6f645b54b90555bb390ad

**Comment by big-guy** [comment]
@eriwen not quite.  That issue was for the gradle/gradle build itself, this is talking about builds in general. 

I think a solution for this would look something like:
- The HTML version would be a new property known to the Javadoc task (maybe part of `CoreJavadocOptions`)
- By default, it would be unset and just use the default from javadoc
- If you are using a newer JDK and get the warning from OP, you could set this to HTML4. 
- When running on an older JDK where HTML4 is the only option, Gradle wouldn't pass anything extra.  When running on a newer JDK where HTML4 needs to be explicitly requested, Gradle would pass `-html4`.
- If you set the HTML version to HTML5, when running on older JDKs, we'd fail?  when running on newer JDKs, we'd pass `-html5`.

This way, people explicitly request a particular format and Gradle would try to honor it and warn/fail if it couldn't.

**Comment by eriwen** [comment]
Ah, of course. Thanks @big-guy.
