### ISSUE TITLE
Continuous build adds significant overhead

### ISSUE THREAD

**Issue by alexey-tsvetkov** [gradle/gradle#5939]
Steps to reproduce:
1. Clone https://github.com/alexey-tsvetkov/gradle-continuous-build-overhead
2. Run `./gradlew clean assemble`. On my computer it finishes in 5-8 seconds depending on whether the daemon is hot or not.
3. Change any Kotlin file. For example change `project_7/src/main/kotlin/utils_14.kt` from:
```
fun util_14() = 14
```
to:
```
fun util_14() = 7
```
4. Run `./gradlew assemble`. On my computer it finishes in 1 second.
5. Run `./gradlew assemble -t` and change the same file again. 

I'm seeing ~40-50 seconds (!) builds for any small change.
According to `--profile` completely up-to-date projects somehow take 5-6s to run:
[reports.zip](https://github.com/gradle/gradle/files/2186302/reports.zip)

Non continuous build scans:
1. Clean assemble build scan https://scans.gradle.com/s/bymn5u56553ig
2. Incremental assemble build scan https://scans.gradle.com/s/gighdoyy3uj76

**Comment by oehme** [comment]
The issue is in the Kotlin plugin, more specifically in [`inspectClassesForKotlinIC`](https://github.com/JetBrains/kotlin/blob/master/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/tasks/InspectClassesForMultiModuleIC.kt#L30). Instead of using a class directory as an input, it is given each class individually. I.e. instead of having `build/classes/kotlin/main` as an input, it instead has `build/classes/kotlin/main/Util1.class, build/classes/kotlin/main/Util2.class, build/classes/kotlin/main/Util3.class`. This leads to an explosion of registered watchpoints the more classes you add to a Kotlin project.

It should use `SourceSet#getClassesDirs` instead of trying to filter (and flattening) `SourceSet#getOutput`.

I'm sure we could make watchpoint calculation more efficient, but fixing the Kotlin plugin will have a much bigger impact.

**Comment by oehme** [comment]
I think I've found a [simple fix](https://github.com/gradle/gradle/pull/6401) on our end, but I still encourage you to improve the modeling in the Kotlin plugin. Using file trees instead of flat lists will be more efficient for many other purposes as well.

**Comment by alexey-tsvetkov** [comment]
@oehme thanks for looking into the issue! 
We will fix the problem on our side
https://youtrack.jetbrains.com/issue/KT-26208
