### ISSUE TITLE
Add cheaper/cached lookup of missing modules for "virtual platforms"

### ISSUE THREAD

**Issue by melix** [gradle/gradle#5947]
### Context

Follow-up to #5873 , whenever a "virtual" platform is used, performance of the build is reduced due to additional repository lookups:

1. we need to find out if the platform is "real", which implies fetching metadata for this platform
2. we need to find out if the modules belonging to a platform exist in a certain version

In both cases, if we have a _miss_, will will always retry all versions on all repositories in subsequent builds, because cache miss is un-cached in this case. We should find a cheaper way to perform the lookups, and most likely cache misses.

**Comment by bigdaz** [comment]
To clarify, for each repository we _do_ cache the fact that the module is missing. So if you have 2 repositories defined, and the module is missing from `repo1` (but found in `repo2`), we won't check `repo1` every time.

The issue is caused by the fact that if we try to resolve a module and it is cached as `missing` in _all repositories_, we then will try these repositories again, bypassing the cache. This is intended to solve the following use case:

- BuildA attempts to resolve `org:module:1.1`, but the user forgot to publish this module version, so resolution fails
- BuildB executes, publishing `org:module:1.1`
- BuildA executes again, without using `--refresh-dependencies`. We prefer making additional network calls rather than failing the build again.
