### ISSUE TITLE
tar.baseName not set by convention to project.archivesBasename

### ISSUE THREAD

**Issue by childnode** [gradle/gradle#5984]
### Expected Behavior
you don't have to define `tar.baseName` seperately
as described in https://docs.gradle.org/4.7/dsl/org.gradle.api.tasks.bundling.Tar.html#org.gradle.api.tasks.bundling.Tar:baseName
`project.archivesBaseName` is the default as like for [Jar.baseName](https://docs.gradle.org/4.7/dsl/org.gradle.api.tasks.bundling.Jar.html#org.gradle.api.tasks.bundling.Jar:baseName)

### Current Behavior
distTar distribution baseName is not set properly as documented and inconsistent to Jar task

### Context
gradle project with distribution plugin

### Steps to Reproduce (for bugs)
```
$ mkdir gradle47TarBaseNameBug
$ cd gradle47TarBaseNameBug
$ gradle init
$ ./gradlew wrapper --gradle-version 4.7
$ ./gradlew wrapper
$ echo "apply plugin: 'application'" >> build.gradle
$ echo "archivesBaseName = 'foobar'" >> build.gradle
$ echo "rootProject.name = '$(basename $PWD)'" >> settings.gradle
$ mkdir -p src/main/java
$ echo """
public class HelloWorld {
  public static void main (String[] args) {
    System.out.println(\"Hello World\");
  }
}
""" > src/main/java/HelloWorld.java
$ echo "mainClassName = 'HelloWorld'" >> build.gradle
$ ./gradlew distTar
$ [[ ! -f "build/libs/foobar.jar" ]] && "build/libs/foobar.jar not found but found $(find build/distributions/)"
$ [[ ! -f "build/distributions/foobar.tar" ]] && "build/distributions/foobar.tar not found but found $(find build/distributions/ -type f)"
```

## workaround / fixup
```
$ echo "tasks.withType(Tar) { baseName = project.archivesBaseName ?: project.name }" >> build.gradle
```

or better:
```
$ echo "tasks.withType(Tar) { baseName = jar.baseName }" >> build.gradle
```

might be related to #5230

P.S: FUG: version should be inherited from jar if you ask me, but this is another issue ;) i.e.
`distTar.version = jar.version`

**Comment by ghale** [comment]
So, what's happening here is that the `application` plugin is overriding the value for the distribution tar with the value of `applicationName` from the [JavaApplication extension](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.JavaApplication.html).  So the distribution tar is getting the default from `archivesBaseName`, but then the application plugin is explicitly setting it to the default for `applicationName` which is the name of the project.  You'll notice that if you add another tar task to the build (one not created by the application plugin) it will have the default from `archivesBaseName`.  

This is maybe not immediately apparent when looking solely at the `Tar` documentation, but this is expected behavior of the application plugin.
