### ISSUE TITLE
Gradle daemon running in wrong location

### ISSUE THREAD

**Issue by Janrupf** [gradle/gradle#5991]
When running with a gradle daemon methods like `toAbsolute*` or `getAbsolute*` are pointing to the original run location of the daemon. This has already been covered and marked as fixed, but this still occurs on gradle 4.8.

Old issues: https://issues.gradle.org/browse/GRADLE-1747 & https://issues.gradle.org/browse/GRADLE-1249
Even if methods like file(String) do exists, other ways should work like "normal" java too.

**Comment by marcphilipp** [comment]
Which version of Java are you running Gradle on?

**Comment by oehme** [comment]
In my opinion, we should have never "fixed" this, because relying on the current working dir pretty much always leads to broken code. For instance, multi-project builds won't work correctly if the code for a subproject assumes that the working dir is the subproject dir (it isn't). Composite builds won't work if the code for an included build assumes that its root directory is the working dir (it isn't). Invoking Gradle from a subproject directory won't work if the root project assumes that it is the working directory (it isn't). And on Java 11 we can no longer mutate the working directory at all (which is an understandable move from the JDK team, because it allows them to cache things).

The only correct way of creating files in Gradle is using `Project.file()` or creating files relative to some other file (e.g. `project.buildDir`).

**Comment by Janrupf** [comment]
I'm running Java 8.
And I can understand to not rely on the working directory, but that fact is weird:

For example: Daemon was running in `/some/path/`
Now gradle is executed in `/another/path`
```groovy
Paths.get(".") // will point to /another/path
Paths.get(".").toAbsolutePath() // will point to /some/path
```

Thats the problem with it. It is just crazy that there are kind of 2 working directories or something like that

**Comment by oehme** [comment]
That difference is probably because we mutate `user.dir` in Java <11, but I guess the `java.nio` API doesn't always respect `user.dir`. But that doesn't really matter anymore going forward, since Java 11 completely prevents this kind of mutation.

Also, the code you showed wouldn't work in any of the cases I mentioned above, even if it always returned the directory where Gradle was invoked. As soon as you do composite builds or run from a different directory, that kind of code would break down. That's why you always have to go through `Project.file` and friends.

So the real question becomes: How can we intercept calls like this and fail right away. This is already covered by #5187.
