### ISSUE TITLE
Starting and stopping a specific daemon for each project

### ISSUE THREAD

**Issue by madlexa** [gradle/gradle#5998]
### Expected Behavior
I'd like to run an instance of a daemon for each project on my server and use the daemon for running all project tasks.
When a project is finished, I'd like to stop the daemon which supports this project. 

### Current Behavior
I can run only one daemon for all my projects or multiple daemons if I use different values of the property `-Dorg.gradle.jvmargs`.
Now I can stop only all daemons at once `gradle --stop`.

### Question
How can I run a specific instance of a daemon and stop it when I want to?

**Comment by atorok** [comment]
I might be wrong on this, but I think lately Gradle always runs a daemon behind the scenes and stops it afterwards if your choice is "no daemon", so it might not be intuitive but I think `--no-daemon` already does what you want.

**Comment by oehme** [comment]
If you really want a single-use process, use `--no-daemon`.

But the real question is: Why do you want to stop the daemon at all? Stopping it means you lose all the performance benefit. My advice would be to just let Gradle do its thing. The daemon will expire eventually if it isn't used.

**Comment by madlexa** [comment]
Now I do it, but I have a performance degradation if I call the gradle again.
I want to run the daemon isolated for the project for several tasks and stop it when I want to.
I want stop daemon because: 
Each version of the gradle wrapper creates its own demon. In some cases there can be lots of demons, so the performance will degrade again.

**Comment by madlexa** [comment]
Do you mean that Gradle can't do this if I don't use Docker?

**Comment by madlexa** [comment]
If I use a Gradle wrapper with different versions for my projects then I have demons that take up memory

```java
public class DaemonParameters {
    public static final List<String> DEFAULT_JVM_ARGS = ImmutableList.of("-Xmx1024m", "-XX:MaxPermSize=256m", "-XX:+HeapDumpOnOutOfMemoryError");
    public static final List<String> DEFAULT_JVM_8_ARGS = ImmutableList.of("-Xmx1024m", "-XX:+HeapDumpOnOutOfMemoryError");
```

I can't stop any daemon because I don't know if this demon is needed or not.
I have many other problems related to this.
It is important to me.

**Comment by madlexa** [comment]
Because after all the build steps I have to clear the project space, but there is a chance to reproduce [the bug #937](https://github.com/gradle/gradle/issues/937)

**Comment by oehme** [comment]
Gradle should not keep any files locked. Please use the [file leak detector](file-leak-detector.kohsuke.org) to find out which plugin is causing the leak and report a bug to them. Stopping daemons is not the solution there, fixing the plugins is.

**Comment by madlexa** [comment]
How to set the parameter from the command line? Because I can't modify the build.gradle.

**Comment by oehme** [comment]
Why not?

**Comment by madlexa** [comment]
Because I work only with CI.
Thank you, I will take your advice `task.withType(JavaCompile) { options.fork = true }`.
But I need to run an instance of a daemon for each project.

**Comment by pavelsher** [comment]
I'd like to clarify the problem. As far as we understand currently it is impossible to stop a specific Gradle daemon. When one tries to do that, all daemons currently running on the machine will be stopped. Is it correct?

If so, this leads to a problem in CI environment, namely TeamCity. In TeamCity build is started by a TeamCity build agent. Some of our customers like to install more than one agent on the same machine. So potentially , more than one Gradle build can be executed on the same machine at the same time. Now, we'd like to stop Gradle daemon sometimes, to prevent interfering with agent resources (to prevent locking of files on the agent, for instance). But we can't do that, because we'll stop all of the daemons at once, and who knows how it will affect other currently running builds.

If we could tie Gradle daemon to something, like user home, or .gradle directory and be able to stop only this daemon, that would be great.

**Comment by oehme** [comment]
> Because I work only with CI.

I don't understand that.

> But I need to run an instance of a daemon for each project.

You don't need to. You need to find the *real* problem and fix it, as I explained before.

> But we can't do that, because we'll stop all of the daemons at once, and who knows how it will affect other currently running builds.

It won't stop a daemon that is still building something. The daemon will shut down after the build.

> Now, we'd like to stop Gradle daemon sometimes, to prevent interfering with agent resources

Please, find the issues instead of working around them. If there is a file leak in Gradle, we need to know about it. If there is one in a community plugin, the author needs to know about it. If there is one in your own build logic, you need to fix it. Stopping daemons is not a solution.

**Comment by pavelsher** [comment]
Seems you do not understand. I am not talking about a particular Gradle build which I can fix. I am talking about TeamCity -> Gradle integration. TeamCity build agent can start many different builds. Some of them can be badly written or use badly written plugins which can lock resources. We need a way to prevent it and for this we need to be able to stop Gradle daemon - but only a specific one, not all of them which are running on the machine at the moment.

Speaking about issues, you actually have them reported, this is one example: https://github.com/gradle/gradle/issues/937

**Comment by oehme** [comment]
> Some of them can be badly written or use badly written plugins which can lock resources. We need a way to prevent it and for this we need to be able to stop Gradle daemon - but only a specific one, not all of them which are running on the machine at the moment.

If you know which one is causing the problem, you should get in touch with that team and make sure the problem is fixed. Until it is fixed you can use `--no-daemon` for their build.

> Speaking about issues, you actually have them reported, this is one example: #937

This is a bucket of different problems, most of them caused by external tools/plugins that those users are using. If you find one that is caused by Gradle itself (and attach the stacktrace from the file-leak-detector), we'll be more than happy to fix it.

**Comment by pavelsher** [comment]
> If you know which one is causing the problem, you should get in touch with that team and make sure the problem is fixed. Until it is fixed you can use --no-daemon for their build.

We work at JetBrains and produce TeamCity product, we can't contact our customers teams. We need to provide a reliable solution for our users. 

> Until it is fixed you can use --no-daemon for their build.

This is what we do now. But our users ask us to allow using Gradle daemon in their builds because potentlially it can increase performance, but we can't allow that until we can reliably stop these daemons.

> If you find a file leak that is caused by Gradle itself (and attach the stacktrace from the file-leak-detector), we'll be more than happy to fix it.

Sure. Leak is a strong word here, as I understand usually it's a problem in a plugin. But then again, for our users, we must provide a solution which works in all of the cases. Otherwise, what are they paying for ;)

**Comment by oehme** [comment]
I'm confused. As you probably know, we use TeamCity ourselves and it already allows us to use the daemon. In fact, using the daemon is the default in Gradle. So what exactly are your users asking for?

**Comment by oehme** [comment]
We've been using the daemon for a long time on TeamCity and we use the Gradle runner, not the command line runner. We simply add the `--daemon` option under `Additional Gradle command line parameters`

I think you should do the following: Add an option to globally enable the daemon (which is false for backwards compatiblity, so users don't get surprised). If users activate this option, it is up to them to make sure their builds are behaving well. 

TeamCity should not be stopping daemons, that would punish users with well-behaved builds. Having long-lived well-warmed up daemons is one of the best performance improvements you can have. Our daemons on TeamCity often run hundreds or even thousands of builds before they shut down (usually because we upgrade to the next Gradle nightly).

**Comment by pavelsher** [comment]
> I think you should do the following: Add an option to globally enable the daemon (which is false for backwards compatiblity, so users don't get surprised). If users activate this option, it is up to them to make sure their builds are behaving well.

This is what we intended to do.

> TeamCity should not be stopping daemons, that would punish users with well-behaved builds

As I said in previous message, the problem is that badly behaving Gradle build can affect well behaving users. Moreover, what we don't like here is that users will come to us saying that there is a bug in TeamCity agent, as it can't remove some checkout directory, while the reason why it can't do that is some plugin which was left by a build of some previous team who used this agent.

**Comment by oehme** [comment]
> As I said in previous message, the problem is that badly behaving Gradle build can affect well behaving users.

I understand that, but punishing well-behaved users by killing their daemons is not the right solution. If TeamCity starts killing our daemons, that would be a blocker for us. 

A better solution might be integrating the file-leak-detector into every build and automatically tracking builds that leak files inside the checkout directory.

**Comment by nskvortsov** [comment]
> A better solution might be integrating the file-leak-detector into every build and automatically tracking builds that leak files inside the checkout directory.

Still, TeamCity need a reliable way to shutdown a Gradle Deamon that caused the file leak, even if it is properly reported to a responsible person or team. CI server can not allow resources to stay locked due to some team's broken build (imagine a server with tens of thousands of build configurations in thousands of teams, managed by it's own, separate team that has no access to actual sources)

**Comment by oehme** [comment]
@nskvortsov If you know which daemon caused the leak, you can send a kill signal to that process. As far as I know you already inject an init script into Gradle. You can use that init script to extract the PID of the current daemon and use that as an argument for `kill`

**Comment by nskvortsov** [comment]
@oehme we now once again are hit by this problem. Now an IntelliJ IDEA user has a number of projects opened (and closed after that) and gradle daemons stick around, using up memory. 
(see https://youtrack.jetbrains.com/issue/IDEA-202453 for details). 

Any chance an IDE / CI server is allowed to participate in Daemon lifecycle?

**Comment by oehme** [comment]
Well at the very least we could provide a `stopDaemons()` method on the GradleConnector interface, which would mirror the behavior of `gradle --stop`, i.e. killing all daemons. Would you mind opening an issue for that?

**Comment by nskvortsov** [comment]
done
