### ISSUE TITLE
Gradle plugin should allow declaring a minimum runtime target

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#6010]
### Expected Behavior

The expected behavior is twofold:
- Plugin loading considers the minimum runtime target on older Gradle version and provides a meaningful error message.
- The resolution of a plugin from the repository should make his best effort to resolve a plugin version that is compatible with the plugin's minimum runtime target.

### Current Behavior

The latest version of a plugin will always be chosen which may cause cryptic failures when the plugin uses newer APIs.

### Context

This is a common feedback from plugin authors.

### Your Environment

 * Build scan URL:

**Comment by adammurdoch** [comment]
There's a bunch of different things we might want to do with the declaration:

- Gradle plugin plugin provides the Gradle API for the target version at compile time.
- Gradle plugin plugin by convention runs functional tests against target version and current version (for example)
- Show this information in the plugin portal to humans.
- Suppress deprecation warnings for deprecations that have been added since that target version.
- ...

The point is that there are really a bunch of different pieces here:

1. Add some way to declare the target version
2. Use this information in a bunch of different, and independent, places to do something useful.

I don't think we need to implement both items in the description in order to add value, it would bes ok to implement just one of them. For example, it would be ok as a first step to have only new Gradle versions honour the metadata, and older Gradle versions can continue to attempt to load the plugin and fail in weird ways.
