### ISSUE TITLE
Can I replace java class in main dir with one in flavor?

### ISSUE THREAD

**Issue by CoXier** [gradle/gradle#6039]
### Expected Behavior

I am using `gradle` build system. Let me explain this a bit more specific.

I have a project and its structure is:

    project
      |
      |---src
           |-----main
           |       |-----java
           |              |------com/example/A.java
           |
           |-----flavor
                   |-----java
                          |------com/example/A.java

When I execute `./gradlew build`, as you see, I will get compile error because system find two same java class `A.java`.

**So can I replace A.java in `main` with the one in `flavor` ?**

In addition, I can use `exclude` in `gradle` to do that thing. But I want to know can I let build system do that automatically.

```gradle
    sourceSets {
        main {
            java {
                exclude 'com/example/A.java'
            }
        }
    }
```

Maybe you think I can add `if/else` in code then create different class instance such as `A a = new B()` and `A a = new C()`.

```
    A a;
    if(isProductBoss()) {
       a = new A();
    }else if (isProductEmployee) {
       a = new B();
    }else ... {
       a = new C();
    }
```
 **But it pack redundant class to my product.**

### Your Environment

 * Build scan URL:

**Comment by CoXier** [comment]
Hi, have you ever viewed this issue?

**Comment by ghale** [comment]
This does not appear to be an issue related to core Gradle functionality.  Since you're talking about flavors, I assume this is related to the Android plugin.  The relationships between source sets and when their compiled results are joined into a single classpath is specific to the Android plugin.  It would be more appropriate to raise your question on [their bug tracker](https://source.android.com/setup/contribute/report-bugs) instead.
