### ISSUE TITLE
Support passing env variables to TestKit build runs

### ISSUE THREAD

**Issue by mockitoguy** [gradle/gradle#6070]
My understanding is that passing env variables to build runs in TestKit is something desired but not prioritized yet. Based on the [TestKit doc](https://docs.gradle.org/current/userguide/test_kit.html):

_The TestKit does not expose a mechanism for fine grained control of environment variables etc. Future versions of the TestKit will provide improved configuration options_

This ticket is to track feature request to add env variables support to TestKit / GradleRunner API. Can you confirm that it is a desired feature? I hope the answer is 'yes' :). It is impacting our ability to use TestKit at LinkedIn. We might be able to provide a pull request.

**Comment by mockitoguy** [comment]
Friendly ping! We can offer a PR but need to know if this is a desired feature - passing env variables to TestKit build runs.

**Comment by mkobit** [comment]
:+1: - I've also found myself wanting to do this recently, especially when building plugins that wrap CLI tools.

**Comment by nicholas-s-perkins** [comment]
👍
Just started using the test-kit to try testing a build script and it was immediately obvious that we would want this.  It's not uncommon to replace old bash scripts with gradle scripts, and it's a natural to use env vars as the way to configure build scripts.

It looks like the underlying BuildLauncher already accepts envVars, so it's surprising that it wasn't just added to the TestKit API in the first place since it just would have to get passed down with the other args.

**Comment by mockitoguy** [comment]
Hey Gradle team, are you OK with allowing the users to pass env variables to TestKit build runs?

**Comment by oehme** [comment]
Sounds good to me, the underlying Tooling API capability is already there. If you'd like to provide a PR, that would be great.

**Comment by mockitoguy** [comment]
Can I get an early feedback on the PR #8089? It should be fairly small time commitment. Thank you!
