### ISSUE TITLE
gradleApi() dependency includes transitive dependencies; allow disabling of transitives

### ISSUE THREAD

**Issue by eric-milles** [gradle/gradle#6089]
Consider the following:

```gradle
ext {
  guavaVersion = '25.1'
  jUnitVersion = '4.12'
}

repositories {
  jcenter()
}

dependencies {
  compile 'org.codehaus.groovy:groovy:2.5.1:indy'
  compile "com.google.guava:guava:${guavaVersion}-jre",{
    transitive = false
  }
  testCompile "junit:junit:$jUnitVersion"
//testCompile gradleApi()
}
```

### Expected Behavior
As-is, the script resolves 4 dependencies: groovy-2.5.1-indy.jar, guava-25.1-jre.jar, junit-4.12.jar and hamcrest-core-1.3.jar.  When I add in `testCompile grandleApi()`, no groovy jar should be supplied since I already have one.  I'd like to disable transitive dependencies.  Maybe `gradleApi(false)`, `gradleApi(transitive: false)` or `gradleApi() { transitive = false }`.

### Current Behavior
3 additional dependencies are added for `testCompile grandleApi()` -- I only need `gradle-api-x.y.jar`.
![gradleapi-dependencies](https://user-images.githubusercontent.com/18193802/43216872-ad7bbad8-9005-11e8-9a45-8bd0699856b6.png)

### Context
The extra groovy dependency is in conflict with the one I already have supplied.

### Your Environment
Eclipse Oxygen/Photon
Gradle 4.9 (and others)
Java 8 (and others)
Windows 7

**Comment by oehme** [comment]
What's your use case? `gradleApi()` is meant for developing plugins, in which case it should be a dependency to your main code and you should be using the Groovy version that ships with Gradle.

**Comment by eric-milles** [comment]
I am trying to get access to the Gradle API for a Groovy DSLD for Gradle.  So when I open `build.gradle` in the Groovy editor I get content assist and semantic highlighting.

**Comment by oehme** [comment]
It shouldn't be on the project's classpath for that, as that would leak all kinds of unwanted things into the project. If buildscript auto-completion is your goal, the buildscript's classpath should be its own concept in groovy-eclipse.

The Gradle DSL is extensible, so just taking the core API will not get you very far. You need to take the classpath of the script you are editing into account. Also you need to inspect the extension objects that plugins add in order to provide auto-completion of all the different DSL blocks. We've spent several engineering years to get great IDE integration for the Kotlin DSL, just to give you a feel for the size of that task.

**Comment by eric-milles** [comment]
I have no illusions that it could be done easily/quickly.  I was looking to try out the little bit of DSLD that was part of STS at one point.  It gives me a real use case for trying to understand how DLSD can be used and where there are feature gaps.  But I need the Gradle API types on the classpath to be able to work with them.

The `gradleApi()` dependency seemed like the path of least resistance.  However, it does not support any attributes like other dependency entries do, so I cannot disable the undesired transitives.

**Comment by oehme** [comment]
I'm afraid you'll have to live with that limitation for now, since the `gradleApi()` dependency really isn't meant to be configurable. It's supposed to give you exactly what you'd get if your ran inside this Gradle version.

I think having an extension point in groovy-eclipse which allows one to define the classpath per script (instead of taking the project's classpath) would help solve this issue.
