### ISSUE TITLE
Question regarding the cache directory structure

### ISSUE THREAD

**Issue by kashike** [gradle/gradle#6103]
I'm curious about the reasoning for using a "flattened" directory structure for the local repository, rather than the expanded directory structure maven itself uses.

### Expected Behavior
`~/.gradle/caches/modules-2/files-2.1/`:
```
aopalliance
com
    google
        code
            findbugs
            gson
        errorprone
        guava
        inject
            extensions
        j2objc
        truth
            extensions
javax
    inject
junit
org
    apiguardian
    checkerframework
    codehaus
        mojo
    hamcrest
    junit
        jupiter
        platform
    opentest4j
    ow2
        asm
```

### Current Behavior
The existing repository is "flat":
`~/.gradle/caches/modules-2/files-2.1/`:
```
aopalliance
com.google
com.google.code.findbugs
com.google.code.gson
com.google.errorprone
com.google.guava
com.google.inject
com.google.inject.extensions
com.google.j2objc
com.google.truth
com.google.truth.extensions
javax.inject
junit
org.apiguardian
org.checkerframework
org.codehaus
org.codehaus.mojo
org.hamcrest
org.junit.jupiter
org.junit.platform
org.opentest4j
org.ow2
org.ow2.asm
```

I've left lots of directories out of the examples, but I'm sure everyone knows what the full structure looks like.

**Comment by bigdaz** [comment]
That directory forms part of the Gradle dependency cache, and is not designed to be used as a local repository. You'll notice that each artifact is included in a directory based on the checksum: this permits us to cache multiple different "versions" of artifacts that have the same coordinates. (This happens when different external repositories disagree on a particular module).

As to your specific question, this is the default repository layout supported by [Ivy](http://ant.apache.org/ivy/). Originally, Gradle's dependency resolution engine was built on top of Ivy, and I suppose there's been no cause to change the layout since then.

**Comment by kashike** [comment]
:+1:, and thanks for the detailed answer; I couldn't find anything that pointed to where the layout came from - searching in a codebase this large doesn't turn out too well.

The question primarily came from being very used to maven's structure, and my pain of trying to `cd` into an expanded directory. :joy_cat:
