### ISSUE TITLE
Lockfiles of removed configurations should be removed when `--write-locks` is provided

### ISSUE THREAD

**Issue by grv87** [gradle/gradle#6111]
### Expected Behavior
When Gradle is run with `--write-locks`, Gradle cleans lockfiles for all configurations that no longer exist.

### Current Behavior
Lockfiles for all nonexistent configurations are kept and should be removed manually.

### Steps to Reproduce (for bugs)
1. Use any existing project as example (e.g. https://github.com/grv87/gradle-dependency-locking-codenarc)
2. Lock all configurations with `--write-locks`
3. Turn off something, e.g. `codenarc` plugin
4. Run gradle with `--write-locks` again and see that lockfile still exists.

**Comment by ljacomet** [comment]
Thanks for the suggestion.

The issue is that using `--write-locks` will _only_ write dependency lock files for the configurations resolved based on the build tasks.
There is no guarantee that all configurations are resolved during a given build and removing files simply because the configuration has not be resolved would break use cases where it is expected that the set of resolved configurations varies between build invocations. One example of this would be a native build where some configurations can only be resolved on a given OS.

Also the dynamic nature of Gradle makes it hard to determine that a configuration really no longer exists, as it can be created by a task execution only.

**Comment by grv87** [comment]
Oh, I haven't consider dynamic configuration creation. I didn't see examples of this in practice.
So, implementing this requires removing support for that...

If there are no other ideas I would like to close this issue.
I would implement this in my custom plugin since I don't create configurations dynamically.
