### ISSUE TITLE
Provide default value for annotation processing source output

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#6225]
By default generated sources will be put into the classes directory which is less than ideal, because these source files will then be packaged into the JAR. Instead we should have a conventional location for these sources.

This is a breaking change, as some tools may rely on generated sources to be placed next to the class files.

**Comment by adammurdoch** [comment]
I think this was implemented a while ago. It looks like it was added in Gradle 5.2.

**Comment by jjohannes** [comment]
Yes. Generated sources are placed into `build/generated/sources` by default.

**Comment by tbroyer** [comment]
This issue is surfaced in [6.3-rc-1 release notes](https://docs.gradle.org/6.3-rc-1/release-notes.html), shouldn't the milestone be changed to the accurate version? (and indeed it was in 5.2, https://docs.gradle.org/5.2/release-notes.html#annotation-processor-improvements, actually tracked by #4956)

**Comment by ljacomet** [comment]
I updated the milestone, this is more correct indeed. Note that however it may not be reflected in the 5.2 release notes.

**Comment by tbroyer** [comment]
#4956 was already in the 5.2 release notes; this one is a dupe :wink:
