### ISSUE TITLE
New configure avoidance API is missing `maybeCreate` equivalent

### ISSUE THREAD

**Issue by JLLeitschuh** [gradle/gradle#6243]
https://docs.gradle.org/4.9/userguide/task_configuration_avoidance.html#sec:old_vs_new_configuration_api_overview

There should be a replacement for the `maybeCreate` API that is configuration deferred.

More explicitly, there should be a replacement for something like this:
```kotlin
val checkTask = tasks.maybeCreate<Task>("check").apply {
    description = "Check all sub-projects"
    group = LifecycleBasePlugin.VERIFICATION_GROUP

    dependsOn(jacocoRootReport)
}
```

**Comment by big-guy** [comment]
Do you have a different example than the lifecycle tasks (assemble, check, build)?

The answer for that is to apply `org.gradle.lifecycle-base` and do:
```
tasks.named(LifecycleBasePlugin.CHECK_TASK_NAME).configure { 
   dependsOn(jacocoRootReport)
}
```

**Comment by JLLeitschuh** [comment]
That's a really good solution to my above problem, thank you!

@big-guy Regardless, `maybeCreate` needs an equivalent for deferred configuration.
If I want to `maybeCreate` a task, I should be able to do so in a deferred way, correct?

**Comment by big-guy** [comment]
Maybe, I'm looking for a scenario where `maybeCreate` works better than some other solution (like the above). 

A few scenarios I've seen:
1. The task is derived from some other container of things and that container can have duplicates.  In that case, we may want to create the same task multiple time and add the other "thing" as configuration.  `maybeCreate` is convenient to hide this de-duping, but it can also hide problems if you really expect a 1:1 thing:task relationship.
1. Not for tasks, but configurations.  There are multiple plugins that create the same configuration (`compile`, `implementation`, whatever), but the plugins are largely independent of each other. `maybeCreate` makes it easier to apply multiple plugins that create the same configurations, but I'm not sure if that produces working builds all the time.
1. As above, but instead of multiple plugins, you have build scripts that happen to define the same configuration name and the plugin is applied later. 

I think for 1, we have another idea that makes it more convenient to express the connection between two containers.  e.g., you'd be able to directly see container-of-things is mapped to provider-of-tasks. We're working on this now.

For 2&3, these feel pretty different from 1. In these cases, it feels like `maybeCreate` is just a workaround and doesn't express anything in particular.  But that may still be useful enough.

**Comment by JamesXNelson** [comment]
One possible use case for `maybeCreate` would be to add a given task once per unique artifact added to a given configuration.  For example, a `preload` configuration that might create exactly one task per external resource downloaded, and the same resource may be specified by both user build script, and  other plugin code.

Still, not a very strong use case; it's not so hard to use Map.compute() or the like to gain idempotency.

**Comment by big-guy** [comment]
> For example, a preload configuration that might create exactly one task per external resource downloaded

I'm not sure what this means. This would necessarily mean you're realizing/resolving configurations at configuration time (so you're able to create the tasks).  What would those tasks do?

**Comment by JamesXNelson** [comment]
Sorry about the delays... holiday season and all.

The tasks in my example are being used to download a set of archives from a remote repository, then saves them to a local repository with complete metadata (sadly, maven) so the entire directory can be tarred up and used offline on machines with no network connection.

There will also be an additional translation layer, for platforms like j2cl.  Just going to worry about unprocessed jars for now, and will add the "pre-process foreign jars" part later.

Each unique dependency in the configuration creates 0-N additional tasks to prime the "local repository of external dependencies".

While it is possible to centralize this into a single script listing all possible dependencies to preload, and maintaining that separate list manually (ick), it would be ideal from a configuration-on-demand perspective for each project to add dependencies that it wants to be available while offline (or, something which blindly caches all external module dependencies from all configurations).  Having `maybeCreate` for each task for each dependency would make idempotency easier, so thirty projects can all add junit, but only one new task is created, w/out additional state management.

To handle configuration isolation, I was thinking to have a specific subproject, `:preload`, and only when the `:preload:preloadAll` task is run, have it gobble up the `preload` configuration objects of all other projects; if the more generic `preload` task is run for some/all projects, each one adds its configuration to `project(':preload').configurations.preload`.  For my example, a NamedDomainObjectSet can easily suffice, but it costs a bit more in abstraction / maintenance.

The more I think about `maybeCreate`, the more I lean towards "the costs outweigh the benefits".  It doesn't add really work unless all creators of the task use maybeCreate (as anyone using `create` instead of `maybeCreate` would break if they weren't run first, in which case maybeCreate is useless). Even if all creators use the lazy version, it can encourage dangerous behavior:


    Jar main = tasks.maybeCreate('jar', Jar, {
        iWasPickedToCreateTheJarTask = true
        // do the other maybeCreate closures also get run?
    })

If only the first closure is called, you get races; it's hard to imagine good things coming from "you must apply X before Y in all cases, else subtle bugs will feast upon your time".

If all maybeCreate closures all called, then the method name is misleading.  `tasks.getOrCreate()` might make better sense in the latter case;  If it was reduced down to tasks.getOrCreate(), now I can just do:

    if (!tasks.findByName('jar')) {
        tasks.create('jar' /*...*/)
    }

It seems to smell like using a crutch instead of learning to walk;
it may prevent you from building a proper abstraction,
or cause you to unknowingly depend on the execution order of things beyond your control.
While there may be a compelling use case still lurking,
I'm definitely much more interested in hearing about:

> another idea that makes it more convenient to express the connection between two containers. e.g., you'd be able to directly see container-of-things is mapped to provider-of-tasks. We're working on this now.

I've been tracking artifact transforms as an alternate route for my preload-shenanigans, and would be interested to learn of any other developments in the lazy-configuration roadmap.

**Comment by TWiStErRob** [comment]
For future readers, I used this as a workaround:
```kotlin
import org.gradle.api.Task
import org.gradle.api.UnknownTaskException
import org.gradle.api.tasks.TaskContainer
import org.gradle.api.tasks.TaskProvider
import org.gradle.kotlin.dsl.named
import org.gradle.kotlin.dsl.register

inline fun <reified T : Task> TaskContainer.maybeRegister(
	taskName: String,
	noinline configuration: T.() -> Unit
): TaskProvider<T> =
	try {
		named<T>(taskName)
	} catch (ex: UnknownTaskException) {
		register<T>(taskName, configuration)
	}
```

My use case: create a task from each subproject in the root project, but only one instance.
Each subproject that outputs lint tries to register and configure these tasks:
:mergeLintReportDebug
:mergeLintReportRelease
and add a `mergeTask.inputFiles.from(subprojectTask.outputReport)`-like dependency to it.

**Comment by Goooler** [comment]
Tweak the workaround a bit:

```kt
// TODO: https://github.com/gradle/gradle/issues/6243
inline fun <reified T : Task> TaskContainer.maybeRegister(
  name: String,
  noinline action: T.() -> Unit,
): TaskProvider<T> {
  return if (name in names) {
    named(name, T::class.java, action)
  } else {
    register(name, T::class.java, action)
  }
}

// TODO: https://github.com/gradle/gradle/issues/6243
inline fun <reified T : Any> NamedDomainObjectContainer<T>.maybeRegister(
  name: String,
  noinline action: (T) -> Unit,
): NamedDomainObjectProvider<T> {
  return if (name in names) {
    named(name, T::class.java, action)
  } else {
    register(name, action)
  }
}
```

BTW, the only open issue for succeeding this might be #8057.

**Comment by TWiStErRob** [comment]
Notice that @Goooler's workaround above is solving a different issue (probably one that's closer to the problem described in OP). It not only maybe registers and runs the action on creation, but also does a hidden `.configure()` if the task already existed.

My workaround was aimed at mimicking `.register(...) { }` which only runs the action on creation, once; and then if the caller so chooses they can do a chained `tasks.maybeRegister("name") { creationThings() }.configure { alwaysThings() }`.

**Comment by ov7a** [comment]
We discussed this issue again and decided to keep it closed.

What is described here is essentially task-based, but we plan to evolve Gradle to be data-based.

One approach to solve a problem like this is to use [`whenObjectAdded`](https://docs.gradle.org/current/javadoc/org/gradle/api/DomainObjectCollection.html#whenObjectAdded(org.gradle.api.Action)). Another approach is to do [the aggregation via dependencies](https://docs.gradle.org/current/userguide/how_to_share_outputs_between_projects.html#variant-aware-sharing).
