### ISSUE TITLE
Improve Directory Layout chapter

### ISSUE THREAD

**Issue by marcphilipp** [gradle/gradle#6326]
Follow-up on #6221.

@pledbrook in https://github.com/gradle/gradle/pull/6221#pullrequestreview-144740369:
> I would still like to see a bit more information on the annotated directories, but I don't think that needs to hold up the chapter, particularly as it could be a long discussion.
>
> Now that we have annotation markers in source samples, we should try to agree on an approach here. I think this is the first use of annotation markers in the user manual, so now would be a good time to do that.

**Comment by pledbrook** [comment]
On the annotation markers front, I noticed that the Asciidoctor user manual just appends them to the end of a line after just a few spaces. I hate it and find the samples untidy, but I recognise that it's a subjective opinion.

A more direct comparison can be found in the Groovy language reference:

 * [Aligned](http://groovy-lang.org/syntax.html#_interoperability_with_java)
 * [Not aligned](http://groovy-lang.org/syntax.html#_special_case_of_interpolating_closure_expressions) — see second example in that section

It's also worth bearing in mind that the Gradle User Manual does not use the icon-based marker, but normal text. That makes it less distinct when it's in the flow of text in the sample source.

I haven't seen an example with the annotations to the left of the sample text. @eriwen Do you have any links that we can use to compare?

**Comment by marcphilipp** [comment]
IMHO the annotation markers should look like in the guides, e.g. in https://guides.gradle.org/publishing-plugins-to-gradle-plugin-portal/#configure_the_plugin_publishing_plugin.

**Comment by eriwen** [comment]
Agreed that icons should be same as guides. I created https://github.com/gradle/dotorg-docs/issues/274 and will just do this when I get a minute. PRs also welcome, of course.

In my opinion, alignment doesn't matter much at all and I don't think we should much more time on it. Subjectively, I think the Groovy sample with unaligned callouts looks best because I don't have to mentally draw a long-ish line between the code and the number.
