### ISSUE TITLE
Periodic Cache Clearing breaks Gradle Wrapper for long periods of idle

### ISSUE THREAD

**Issue by JacisNonsense** [gradle/gradle#6371]
The newly introduced periodic cache clearing in 4.10-RC-1 currently cleans unused Gradle wrappers out of the system cache. This issue is here to try and reverse this change (but keep it for other artifacts). 

### Context
If a project is left idle for a long time, the cache will be cleared. When building with `--offline` (or without an internet connection), this causes artifacts to go missing. For artifacts (project dependencies and plugins), this is a fixable problem with a local repository, but for the gradle wrapper, it is not. 

Since the gradle wrapper distributionUrl is checked into version control, and only one distributionUrl can be set, it's impossible to have a local cache without also checking it into version control, which balloons in size due to the presence of a >70MB zip blob. 

### Possible solutions:
- Disable automatic clearing of the Gradle Wrapper, make it user triggered instead with a command-line flag (like `--thin-wrappers`). Automatic clearing of other dependencies can remain periodic. 

- Allow specification of more than one `distributionUrl` in the project wrapper properties (i.e. a local fallback if the online distribution can't be reached). This requires changes to the wrapper jar.

**Comment by ThadHouse** [comment]
One other very large issue with this change is that it has a chance to silently break people still on old gradle versions, if they ever start a project with a newer daemon. If a project is depending on the old cache behavior (even for just the wrapper) and is gradle 4.9 or before, and a 4.10 project is started on the same system, that 4.10 project could delete the wrapper for that 4.9 project, and then the 4.9 project breaks. So even with a breaking change like the caching, staying with an old version does not work and does not solve the breakage.

**Comment by marcphilipp** [comment]
@ThadHouse Why would the 4.9 project silently break? It would simply redownload the distribution and any missing artifacts.

**Comment by ThadHouse** [comment]
If that system is away from internet, it won't be able to download 4.9. So it will silently be deleted with no way for the user to easily recover if they are way from internet.

**Comment by JacisNonsense** [comment]
@marcphilipp for us specifically, we're using gradle as the build system for a league of 3000 robotics teams (~10,000+ software students) who write their code (Java or C++) during Jan-Feb of each year, and some teams don't compete until late March/April (or perhaps later in the year). It is common for competition venues not to have an internet connection (in fact, it's discouraged due to wireless interference). This is not a problem for normal deps (we can have a local repo that a plugin populates), but for wrappers it's a whole new beast (without gradle there is no plugin). These numbers increase when you think about teams booting up old robots, where deploy times are half a year or longer apart. We're talking about 1000s of users in this sense.

Local versions of a gradle distribution have been discussed, but we would either have to (a) store the gradle jar in version control (big no-no), or (b) store it somewhere known on the system (also a big no-no, you can no longer clone from git and have it work without installing extra tools, which defeats the purpose of the wrapper in the first place). The big issue influencing this is that the gradle wrapper jar only knows of one place to look for the distribution, i.e. we can't do online with a local fallback. We discussed having the plugin mutate the wrapper properties after copying the wrapper to a safe location, but this again breaks the ability to "clone and go".

We also want to avoid writing our own `gradlew`-like scripts, since certain IDEs (like intelliJ and eclipse) that hook into the gradle-wrapper directly will not be aware of any changes we make. 

For our purposes, the absolute minimum support we need is a user-home gradle property to disable the cleaning of `~/.gradle/wrapper/dists`, or some method to facilitate multiple distribution sources in `$PROJECT/gradle/wrapper/gradle-wrapper.properties`.

**Comment by ThadHouse** [comment]
One thing to note is that if supporting multiple URLs, which seams like the easiest solution to this problem, please make the extra URLs have some syntax to support environment variables. Otherwise an absolute path would still be hardcoded per system, and that does not solve the issue.

**Comment by ThadHouse** [comment]
One solution that was thought of was to have our projects place the wrapper into a non default directory using the `archivePath` and `distributionPath` options on the wrapper. If we set these to another directory, this would currently fix the issue for us, as gradle only deletes cached wrappers in the default directory. But for this to work, we would need a directory that is likely to not get used in the future. It would be nice if we could get a designated wrapper cache directory that was documented and would never be considered to be added to the cache deletion. My current tests were `permanentwrapper/dists` but any directory would work.

**Comment by PeterJohnson** [comment]
Maybe an analogy would help describe the issue.  Say for example Java 8 applications downloaded the Java 8 JRE and stored it globally for shared use by other Java 8 applications.  Java 8 is popular for years and there are thousands of installed applications.  Java 9 is introduced, and the Java 9 JRE can't run Java 8 applications.  Similar to Java 8, Java 9 applications download the Java 9 JRE for global shared use.  However, Java 9 also *deletes* the global Java 8 JRE if you haven't run a Java 8 application in the last 30 days.  Clearly this is an issue if I run a mix of Java 8 and Java 9 applications on a laptop with only occasional Internet access.  If it's been more than 30 days since I ran a Java 8 application, and then I'm on a plane and want to run it without Internet access, to my unpleasant surprise I find I can't... because Java 9 has deleted the Java 8 runtime.  This is a serious user WTF.

It would be different if Gradle was backwards compatible (e.g. 4.10 could be used with 4.9 projects).  However, this is not the case, so it's a serious break to have gradle 4.10 delete the gradle 4.9 runtime.

**Comment by ThadHouse** [comment]
I think there are actually 2 separate, but related issues here. The first is that Gradle 4.10 and above deleting 4.10 and above wrappers. That isn't a breaking change, but there should be a solution for people that don't want that behavior. 

The second issue is any gradle 4.10 project deleting the wrappers from 4.9 and before projects. This IS a breaking change, and one that has a much higher chance to unknowingly bite people during an inopportune time. Deleting old runtimes is REALLY bad for the old projects, because its unexpectedly possible. Yes I agree that behavior might not have been the ideal behavior, but I think people were depending on that behavior. I can think of tons of times where maybe I need to only build an old project once a month or so, and if I was on say an airplane this would be a huge unexpected issue. I really hope you guys at least think about taking this seriously, as I feel it has HUGE implications that won't pop up for about a month or so. As much as you guys don't agree, this IS a breaking change, that is randomly able to pop up, and not on a major version. That is horrible software engineering practices, and you might as well just call this release 5.0 at this point.
