### ISSUE TITLE
Support `exclusions` defined in `dependencyManagement` for BOM dependencies

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#6382]
See the conversation at https://github.com/nebula-plugins/gradle-nebula-integration/issues/14

**Comment by wilkinsona** [comment]
From a user's perspective, this feels the same as https://github.com/gradle/gradle/issues/1473. Given that I raised #1473, you probably won't be surprised to read that I think this is another situation where Gradle should not behave as it does now. My argument is that if Gradle is feeding Maven metadata into dependency resolution, then that metadata should result in the same behaviour as it does in Maven. Anything else is a potential headache for every author of a library that publishes Maven metadata and uses exclusions in its pom or bom.

A diligent library maintainer will take time to configure exclusions so that their users get the intended set of dependencies. The exclusions will be specified in the pom or bom and typically verified using Maven and something like Maven's Enforcer Plugin. When Gradle applies different semantics to the pom or bom, library maintainers have two choices:

1. Add additional exclusions to account for Gradle's different rules. The accuracy of these exclusions cannot be tested with Maven so a separate, Gradle-based set of tests needs to be introduced.
2. Explain to their users that Gradle behaves differently and how they can correct that behaviour to match Maven's.

Trying to provide a general-purpose solution for the second option is what led to our [dependency management plugin](https://github.com/spring-gradle-plugins/dependency-management-plugin) adding support for mimicking Maven's exclusion semantics. It does so for exclusions declared in both poms and boms. The implementation isn't particularly pleasant and, while it's been heavily optimised, is still slower than I would like. For each configuration that's being resolved, it requires an additional configuration resolution to get hold of all the poms so that the exclusions can be applied as Maven intended before the "actual" configuration is resolved.

As I've said before, I would be delighted to retire the dependency management plugin in favour of close-to-equivalent support in Gradle itself. I think the improved treatment of exclusions in boms as described in nebula-plugins/gradle-nebula-integration#14 would be a big step in that direction. Doing the same for poms would be another one.

**Comment by bigdaz** [comment]
Thanks for the feedback @wilkinsona. Let's continue the discussion about POM excludes on #1473. I'm curious to know how much of Maven's exclusion behaviour you've managed to replicate, when this behaviour is based on nearest-path dependency priority as well as being dependent on the order that exclusions are declared in a POM.

Regarding support for Maven BOM import, the current behaviour is definitely not a "done deal", although there are certain key principles of dependency management (and limitations in our resolution engine) in Gradle which will guide the end decision.  I'm working on a document that should outline these principles, the various options available, and hopefully will help us come to an agreement on how to proceed.

**Comment by wilkinsona** [comment]
The bulk of the exclusion code is [here](https://github.com/spring-gradle-plugins/dependency-management-plugin/blob/8621f24b52bcee6b0e9477c72667a0afaa19c3a6/src/main/java/io/spring/gradle/dependencymanagement/internal/ExclusionConfiguringAction.java). I haven't done an extensive comparison of exactly how close it is to Maven's behaviour, but, based on the drying up of complaints that it's wrong, it appears to be good enough. The intention is that it walks the dependency graph in the same manner as Maven does and it uses the poms themselves to get the exclusions so the ordering from the poms should be honoured.

**Comment by bigdaz** [comment]
This has now been implemented. This should make it easy for the Spring Boot team (and other platform BOM producers) to create a BOM that defines a platform as a set of modules complete with `<exclusions>`.

**Comment by rupebac** [comment]
So, if I understood correctly the resolution of this issue, now you are honouring the exclusions coming from any external BOM file, but you are still unable to add these exclusions when gradle is producing and publishing the platform as a bom file right ? (as there is still no exclusions in DependencyConstraint), Is this not somehow inconsistent?

The problem I am facing now is with composite builds, I want to define some exclusions that are applied for all the included builds. How should I do this? I understand that rules in a configuration are not part of a platform, so how to do it then?
