### ISSUE TITLE
Dogfood: Use `maven-publish` in `gradle/gradle` build

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#6454]
Instead of using the `maven` plugin for publishing libraries in our own build, we should use the `maven-publish` plugin. See https://github.com/gradle/gradle/blob/91467bbd010be0562c6036e8d722430f878332f3/buildSrc/subprojects/plugins/src/main/kotlin/gradlebuild/publish-public-libraries.gradle.kts#L29-L31

**Comment by wolfs** [comment]
@marcphilipp Any chance you can look into this?

**Comment by marcphilipp** [comment]
I briefly looked into this.

We're using custom configurations and custom logic to generate POMs:
https://github.com/gradle/gradle/blob/e9332b4957b49538b63d2af05fa72eea27c4494d/buildSrc/subprojects/plugins/src/main/kotlin/org/gradle/plugins/publish/GeneratePom.kt#L24-L62

Since we're lacking a way to define custom software components (cf. https://github.com/gradle/gradle/issues/1842), it doesn't seem like we're ready to switch to `maven-publish` just yet.

**Comment by marcphilipp** [comment]
If we use internal API now and not solve #1842 shortly after, we might forget about it. I think it should be a connected attempt once we've committed to #1842.

**Comment by adammurdoch** [comment]
I don't think we need any of that stuff any more. It's there from the days when the tooling API was not distributed as a shaded jar. Now, we only need a way to publish the tooling API shaded jar with slf4j-api as its only dependency.

To do this, we don't necessarily need a software component instance. This only really becomes important once we start publishing Gradle metadata for the tooling API (which I wouldn't do yet). We can instead add the shaded jar (and source and javadoc jars) as artfacts directly to a publication and then tweak the pom XML to add the dependency. I wouldn't block switching to the `maven-publish` plugin on us adding an API to define software components.

**Comment by jjohannes** [comment]
Done: #11743
