### ISSUE TITLE
JaCoCo: Root Report which aggregates results

### ISSUE THREAD

**Issue by davidnqd** [gradle/gradle#6460]
### Expected Behavior
The JaCoCo plugin already provides a way to merge JaCoCo results. Would it be reasonable for the plugin to automatically add an aggregate task to the root project of a multi-project project which leverage the tasks already added?

A few variants can be found here: https://gist.github.com/aalmiray/e6f54aa4b3803be0bcac

### Current Behavior

According to the [current documentation](https://docs.gradle.org/current/userguide/jacoco_plugin.html#sec:jacoco_tasks) the plugin does not add an aggregate task to the root project.

### Context

This is a minor issue to keep build scripts DRY and simple.

Thanks,
David

**Comment by bmuskalla** [comment]
We currently have no plans to provide this out of the box due to the different needs of different use cases. Nevertheless, we added a new sample to the sample collection showing how to easily set up a [multi-module jacoco report task](https://docs.gradle.org/6.4-rc-1/samples/sample_jvm_multi_project_with_code_coverage.html).
