### ISSUE TITLE
Reselect dependency version on selector removal during resolution 

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#6567]
As shown in [this test](https://github.com/gradle/gradle/blob/v4.10.0/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy#L1494-L1526), Gradle does not downgrade a version when the selector that caused the upgrade is removed from the graph.

Doing so would improve graph resolution by pruning no longer applicable upgrades.

**Comment by jjohannes** [comment]
This problem persists. There are a number of test cases now showing the effect of the issue and how dependency ordering can change the resolution result because of this:

https://github.com/gradle/gradle/blob/219e20add087290b9016a7de382dd5723da316e7/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/VersionConflictResolutionIntegrationTest.groovy#L1548-L1649

**Comment by jjohannes** [comment]
Have to clarify if https://github.com/gradle/gradle/pull/6562 can be revived or how else we can fix this.

**Comment by ljacomet** [comment]
The fix for this issue is the most likely culprit for #11789 so it will be pulled from Gradle 6.1.
A better fix will be worked on for Gradle 6.2.

**Comment by jjohannes** [comment]
Follow up:
- Locally revert https://github.com/gradle/gradle/commit/71f39806164a2741d9d95fe6e6b2e4666f2c704c and reproduce issue reported here https://github.com/gradle/gradle/issues/11789#issuecomment-572777215
  Test in the making: https://github.com/gradle/gradle/tree/jjohannes/reselection-issue
- Once test is ready, find a better solution for the re-selection to fix the problems. Maybe something like queuing the re-selection (in a separate re-selection queue) instead of performing it directly.
