### ISSUE TITLE
Only produce new gradle-wrapper.jar when classes changed

### ISSUE THREAD

**Issue by sghill** [gradle/gradle#6632]
It'd be helpful if upgrading the gradle wrapper through the recommended approach only resulted in a new `gradle-wrapper.jar` if its classes had changed.

From the [Upgrading the Gradle Wrapper docs](https://docs.gradle.org/4.10/userguide/gradle_wrapper.html#sec:upgrading_wrapper):

> The better and recommended option is to run the wrapper task and provide the target Gradle version as described in Adding the Gradle Wrapper.

Running `./gradlew wrapper --gradle-version <new-version>` always results in a new `gradle/wrapper/gradle-wrapper.jar`, which results in source control repositories growing faster than necessary.

### Expected Behavior

If there haven't been any changes to the classes included in `gradle/wrapper/gradle-wrapper.jar`, the jar should not be different.

### Current Behavior

The embedded `build-receipt.properties` is always different between versions, requiring a new binary to be checked in to source control with each version update.

Here is a diff of the unzipped jar contents from a 4.9 and 4.10 gradle-wrapper.jar:

```
$ diff 49/gradle/wrapper/jar-contents/ 410/gradle/wrapper/jar-contents/
Common subdirectories: 49/gradle/wrapper/jar-contents/META-INF and 410/gradle/wrapper/jar-contents/META-INF
diff 49/gradle/wrapper/jar-contents/build-receipt.properties 410/gradle/wrapper/jar-contents/build-receipt.properties
1c1
< versionNumber=4.9
\ No newline at end of file
---
> versionNumber=4.10
\ No newline at end of file
Common subdirectories: 49/gradle/wrapper/jar-contents/org and 410/gradle/wrapper/jar-contents/org
```

### Context

Attempting to stay up-to-date with the latest wrapper through the recommended approach leads to unnecessary repository growth. See also https://github.com/gretty-gradle-plugin/gretty/pull/74.

### Steps to Reproduce (for bugs)

Run `./gradlew wrapper --gradle-version <new-version> && git diff` from an existing git repository with an older version of the gradle wrapper checked in.

### Your Environment

 * Build scan URL: 
N/A

**Comment by marcphilipp** [comment]
The `build-receipt.properties` file is currently being read from the `gradle-wrapper.jar`:

https://github.com/gradle/gradle/blob/3ccc368a2684a34cd01ed58e0b1798e4f50de5c6/subprojects/wrapper/src/main/java/org/gradle/wrapper/GradleWrapperMain.java#L93-L113

However, it looks like it's only used in the HTTP User-Agent when downloading the distribution:

https://github.com/gradle/gradle/blob/0e5d6e9eddbcd9614b99937b93c02fb9547c3c37/subprojects/wrapper/src/main/java/org/gradle/wrapper/Download.java#L157-L165

Thus, I think it would be feasible to exclude `build-receipt.properties` from the wrapper JAR. I'm not sure, however, if that would already be sufficient to produce the exact same JAR. File order and timestamps seem to be already taken care of:

https://github.com/gradle/gradle/blob/1e4bb4edaaa74cde83ef0063e0b40f34dda1ae2f/subprojects/wrapper/wrapper.gradle#L56-L63

**Comment by big-guy** [comment]
Just as a data point and some perspective, the gradle/gradle build updates the wrapper more than any other project would (over 270 times) to various RC's, nightlies and final releases.  The wrapper jar is ~50KB, so assuming that git can never compress or dedup the wrapper jar, that's 14MB of a 200MB repository.  Not insignificant, but it's a slower growth than some may think.

If your project only updates on final releases and has been since 1.0, you would have only changed the wrapper jar ~50 times.

**Comment by javabrett** [comment]
I suppose I sort of trigged this issue in the linked issue by questioning a new `gradle-wrapper.jar` with each (or some) Gradle release rev in a project.  This can easily happen if you run the `wrapper` task as a matter of course when upgrading your build to a new Gradle version, and generates the binary churn in the repo.  So I thought I might add a few additional data-points on `gradle-wrapper.jar` as it applies to the `gradle` repo itself, following @big-guy :

- This will vary a little by filesystem etc., but the rough full-repo-on-disk size for a bare clone direct from GitHub is about 300388kb on my machine.
- This can be reduced quite a bit with an aggressive `git gc` (run in order to make a fair comparison): 203392kb.  This increase delta compression quite a bit.
- There are 316 commits on all branches which touch a file named `gradle-wrapper.jar`.
- There are 291 unique blobs containing `gradle-wrapper.jar` in their path in the repo.
- There are two `gradle-wrapper.jar` files in `master` head.  Interestingly they differ - `gradle/wrapper/gradle-wrapper.jar` is `versionNumber=4.10-rc-3`, whereas `subprojects/docs/src/samples/userguide/wrapper/sha256-verification/gradle/wrapper/gradle-wrapper.jar` is `versionNumber=4.3.1`.
- With all but the two current copies removed from all repo history (via BFG), and the repo repacked, the new size is 202536kb, so only 856kb is recovered.  So not the 14mb odd possible without repacked delta compression.

So basically, Git delta-compression can do amazingly well even with binaries, especially if the binary is created in some ordered fashion, and is something fairly predictable like a jar of bytecode from source that hasn't changed.  So the net repo growth is limited as observed by @big-guy , and it is even less than that.  But partly that relies on Git maintance tasks such as repacking, which don't always distribute well.

So maybe my hesitance to wrapper-churn is unfounded, but it always feels icky checking-in binary updates to Git, so I was looking for a strategy to make it easy to avoid that.

Per the linked issue, my habit has been to 1) Check-in a `gradle-wrapper.jar`, it so tiny there's no need for a wrapper-wrapper and 2) Update the wrapper jar much less frequently than the Gradle it points to, since it hardly ever changes ... only update it should it become ancient, or to pick-up a bug or security fix.

I guess what would be ideal would be a) an easy way to tell when there had been any material change to the Wrapper, b) when there's been an important fix to the Wrapper.  I suppose checking source or grepping the release notes might answer those.  Short of versioning and releasing the Wrapper separately, which is probably not worth it, that might be best available.

It would be a shame to remove the manifest information from the wrapper jar which identifies the build version, being necessary if the same binary were to be produced.

I also don't think it is sustainable for a build-chain to be expected to produce an identical binary from identical source in the long-term - even a JDK rev _could_ change that, so it would require locked toolchains.

One solution could be a back-reference mechanism from Gradle to the wrapper, but it would require passing the wrapper version to Gradle - if Gradle were called with a wrapper that was significantly behind and missing important changes, Gradle could prompt the developer to maybe upgrade the wrapper.

Or having run `./gradlew wrapper --gradle-version=4.10` we can just remember to `git checkout -- gradle/wrapper/gradle-wrapper.jar` before committing :).

**Comment by marcphilipp** [comment]
@eriwen Do we parse the User-Agent for download statistics? Could we remove the version from it?

**Comment by eriwen** [comment]
We do, but I imagine we don't strictly need the Gradle version in the User-Agent since that is part of the filename.

**Comment by wolfs** [comment]
@eriwen @marcphilipp I am not 100% which version we are talking about. When the wrapper jar is generated the `build-receipt.properties` of the Gradle version creating the wrapper jar is included.

This is **not** the Gradle version runnning the build.

While it is interesting to know which versions of the Gradle were used to produce wrapper jars which are used out there, it is probably not very interesting. The interesting information we want to obtain is which Gradle versions are used, independent of which wrapper jar is used.

Is this correct?

**Comment by marcphilipp** [comment]
That's my understanding as well.

**Comment by javabrett** [comment]
I noticed something interesting today which I probably should have been cognisant of but wasn't: the `wrapper` task is not idempotent when upgrading:

- Run `./gradlew wrapper --gradle-version 4.10.2 --gradle-distribution-sha256-sum b7aedd369a26b177147bcb715f8b1fc4fe32b0a6ade0d7fd8ee5ed0c6f731f2c` in a project with an older wrapper, and your `gradle/wrapper/gradle-wrapper.properties` gets the version bump - nothing else.
- Run `./gradlew wrapper --gradle-version 4.10.2 --gradle-distribution-sha256-sum b7aedd369a26b177147bcb715f8b1fc4fe32b0a6ade0d7fd8ee5ed0c6f731f2c` again and additionally `gradle/wrapper/gradle-wrapper.jar` is now touched.

This is perhaps unsurprising, since the first `wrapper` task runs under the older Gradle runtime supplied by the existing wrapper config, whereas the second execution runs under the newer 4.10.2 Gradle runtime.  Since the local/downloaded/unwrapped Gradle runtime is the supplier of `gradle-wrapper.jar`, assuming the pre-existing Wrapper jar is up-to-date, it doesn't change for the first command, but does for the second - per the above discussion, mainly because it contains a version-stamp file (although it could have real code-changes).

Although unsurprising, the behaviour is a little odd.

Presumably if you fail to check-in `gradle-wrapper.jar`, this behaviour won't repeat itself on the next Gradle upgrade-via-wrapper cycle, since `gradle-wrapper.jar` will already be out-of-date with the version in the current Gradle runtime, so will be touched immediately.

What if the `wrapper` task had a `--properties-only` option or similar ... if you remembered to add that, you wouldn't dirty your wrapper jar.

**Comment by wolfs** [comment]
@javabrett What you are describing is https://github.com/gradle/gradle/issues/884.
