### ISSUE TITLE
Artifact transform - prefer suffix chains if they exist

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#6718]
If a project publishes 2 variants, A and B, and consumer queries for C, with transform chains A -> B -> C and B -> C, the shorter chain should be chosen as it is a subchain of the longer one.

An actual use-case is where an Android library project publishes "android-classes" and "jar" variants, and consumer needs "dex". There is "android-class" -> "dex" chain, but also "jar" -> "processed-jar" -> "android-classes" -> "dex". At the moment, this fails with a build exception.

**Comment by gavra0** [comment]
To clarify, there are multiple use-cases that would nice to support:
1) A - B - C vs A - C => pick A - C (this is current behavior)
2) A - B - C vs B - C => pick B - C
3) A - B - C - D vs B -D => pick B - D

At the moment, only 2) is an issue for us, but it would be nice to support 3) as well.

**Comment by gavra0** [comment]
There is one more use case that we are hitting:
A - C vs B - D -C

Actual example is that we'd like to have transform X from "java-classes-dir" to "android-classes" (this is for classes published by Java only projects). However, we also have transforms from "jar" to "processes-jar", and "processes-jar" to "android-classes" (this is to handle external dependencies). For the moment, we work around this issue by not setting up transform X, so we are getting "jar" variant from the Java project, and doing some unnecessary work.

**Comment by ljacomet** [comment]
A first change made it into the future 5.1 release: `A -> B -> C` and `B -> C` will no longer be ambiguous and Gradle will pick `B -> C` as the transform to execute.

**Comment by ljacomet** [comment]
In the context of `A - C` vs `B - D - C`, Gradle will do transform disambiguation as long as the set of attributes from the source variant, with all transforms applied along each path do match - that is they are equivalent according to the attribute schema and its disambiguation rules.
However that use case made us realize it was most likely incompatible with requesting artifact dependencies as the chain different means that for things that can only pass through `B - D - C` but could be a dependency of a thing passing through `A - C` there is no transform that allows the dependency to be available in the intermediate state.

Up to now the artifact dependencies to a transform were provided in a lenient fashion, meaning that failing to find the right transform for a dependency would simply result in the dependency being dropped silently. With the introduction of the above disambiguation, we will move to a strict artifact dependency providing which should make issues very explicit instead of risking hard to understand / debug issues at a later stage.
