### ISSUE TITLE
Candidate set provided to `AttributeDisambiguationRule` contains null entry

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#6747]
This is a mirror bug for : 

https://issuetracker.google.com/issues/112231683

if you check out the small example project, you will be able to reproduce the NPE by changing 
libx/build.gradle

//            releaseDebug {
//            }

basically removing the build type on the library forces the resolution strategy to kick in in the app module. 

when android-kotlin plugin is disabled, it works. When it is enabled, NPE during configuration.

I have checked that we set up the AttributeMatchingStrategy<BuildTypeAttr> correctly independently of the kotlin plugin presence so it does not seem to be an android gradle plugin issue.

**Comment by mtrakal** [comment]
Adding info for users which are not from Google corp: https://issuetracker.google.com/issues/112231683 because they can't use link on https://github.com/gradle/gradle/issues/6747#issue-359988963

Link to repo: https://github.com/mtrakal/issue112231683 which allow reproduce this bug

**Comment by bigdaz** [comment]
Thanks for reporting this issue. I've done some debugging, and the fundamental issue is caused by the fact that [MultipleCandidateDetails.getCandidateValues()](https://github.com/gradle/gradle/blob/b0032a8a355379e5868b22d660f8be5cf857168e/subprojects/core-api/src/main/java/org/gradle/api/attributes/MultipleCandidatesDetails.java#L46) can currently contain a null value, if any of the variants are missing this attribute.

## Analysis

Applying the `kotlin-android` plugin adds a bunch of additional variants, none of which have the `BuildTypeAttr` attribute set, and this results in a null being added to the candidate values. In order to choose the correct variant, `AlternateDisambiguationRule` is invoked and attempts to call `getName()` on this null value, resulting in a NPE. This doesn't happen when the candidate values contain an exact match for the requested attribute, since `AlternateDisambiguationRule` has a simpler code path in this case (ie when there is a `releaseDebug` build type variant).

Note that this is further complicated by the fact that our exception reporting also barfs on the `null` candidate value, resulting in a _different_ NPE that masks the NPE emanating from `AlternateDisambiguationRule`.

## Solution

I'm attempting to find a fix that eliminates the null value from the candidate set, but this is proving elusive so far. If I manage to find a relatively simple fix I'll try to get it into the upcoming `4.10.2`, but otherwise it's likely to slip into `5.0`. 

In the meantime,  you should be able to update `AlternateDisambiguationRule` to check for `null` values when iterating over the candidates. I haven't been able to test this.

**Comment by bigdaz** [comment]
@jdochez We've implemented a fix which will be in the upcoming `4.10.2` release. It would be great if you could try it out before the release so we know for sure that the issue is fixed (and that the change didn't introduce any other problems).

You can grab a pre-release distro from http://services.gradle.org/distributions-snapshots/gradle-4.10.2-20180917175211+0000-all.zip

**Comment by bigdaz** [comment]
@mtrakal Please try out the above nightly that contains a fix for this issue. ☝️

**Comment by mikescamell** [comment]
@bigdaz We had this issue in our project as well and I can confirm that the pre-release distro works for us 👍

**Comment by mtrakal** [comment]
@bigdaz I can confirm that's working like a charm too :). Thanks a lot for the fix 👍  🥇

**Comment by Xexiz** [comment]
Awesome, works for me too with the 4.10.2 nightly :) I can finally remove the useless buildType in all my libraries modules which was a temporary hack in order to have all the same buildType in all modules!
Thanks

**Comment by h0tk3y** [comment]
IMO the fix for this issue somewhat introduces a conceptual flaw into attributes disambiguation process: there is no more a way to disambiguate an absent attribute (`null`) from a single value in case that value doesn't match the requested attribute. So if there are candidates with a certain value and no value (i.e. a value `foo` and null, and the requested value is `bar` or null) then no rule can disambiguate them since no rule even gets called.

In the code of the `kotlin-gradle-plugin`, we have a rule that makes sure a `project(...)` dependency gets resolved into one of the `*Elements` configurations, not one of the deprecated ones which `canBeConsumed = true` and still have no proper Usage attributes (unless specified otherwise with e.g. `configuration: 'compile'`). 

We add a special attribute `<...>.localToProject` to those configurations which we don't want to be chosen, and the rule prefers the `null` value over any other value, so none of the configurations marked with the attribute could be chosen over the configurations not marked with the attribute.

Prior to 4.10.2, this worked fine. In 4.10.2+, ambiguity arises due to the `null` value not disambiguated properly from a single alternative value:

```
Cannot choose between the following variants of project ::
  - metadataApiElements
  - metadataCompile
  - metadataCompileOnly
  - metadataDefault
All of them match the consumer attributes:
  - Variant 'metadataApiElements':
      - Found org.gradle.usage 'kotlin-api' but wasn't required.
      - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.
  - Variant 'metadataCompile':
      - Found org.gradle.usage 'kotlin-api' but wasn't required.
      - Found org.jetbrains.kotlin.localToProject ':' but wasn't required.
      - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.
  - Variant 'metadataCompileOnly':
      - Found org.gradle.usage 'kotlin-api' but wasn't required.
      - Found org.jetbrains.kotlin.localToProject ':' but wasn't required.
      - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.
  - Variant 'metadataDefault':
      - Found org.gradle.usage 'kotlin-api' but wasn't required.
      - Found org.jetbrains.kotlin.localToProject ':' but wasn't required.
      - Found org.jetbrains.kotlin.platform.type 'common' but wasn't required.
```

**Comment by melix** [comment]
Thanks for the insight @h0tk3y .

> We add a special attribute <...>.localToProject to those configurations which we don't want to be chosen, and the rule prefers the null value over any other value, so none of the configurations marked with the attribute could be chosen over the configurations not marked with the attribute.

I think this is the problem, it should have been setup the other way around: attributes are used to _select_ a configuration, not to exclude them. So preferring `null` should have been an error in the first place. The selection algorithm makes use of configurations _with_ attributes, and should select a configuration that has the appropriate value.

So one option is just to add the attribute to every configuration, and set a value like `internal` and have a compatibility rule that says that this value is _not_ compatible with any queried value.
