### ISSUE TITLE
Unable to sign Gradle metadata .module file when publishing

### ISSUE THREAD

**Issue by JakeWharton** [gradle/gradle#6788]
### Expected Behavior
The signing plugin sees the `.module` file and includes it in its signed artifacts.

### Current Behavior
A `.module` file is invisible to the signing plugin and does not show up in the `MavenArtifactSet` for manual signing.

### Context
I cannot release my library to Maven Central though Sonatype as it requires all artifacts to be signed. I'm using the new [Kotlin multiplatform](https://github.com/h0tk3y/k-new-mpp-samples#publishing-and-mpp-library-dependencies) plugin which requires the use of this Gradle feature and the `maven-publish` plugin.

### Steps to Reproduce (for bugs)
1. Create a Java project
2. Jump through the requisite hoops so that `maven-publish` and `signing` work together (e.g., https://medium.com/@nmauti/sign-and-publish-on-maven-central-a-project-with-the-new-maven-publish-gradle-plugin-22a72a4bfd4b)
3. Add `enableFeaturePreview('GRADLE_METADATA')` to `settings.gradle`
4. Publish to local maven repo and observe all artifacts signed except the `.module`

### Your Environment
Gradle 4.10.1, JDK 1.8.0_144

**Comment by melix** [comment]
Thanks for the bug report. We're going to investigate this, but in the meantime, please be aware that we strongly discourage publishing `.module` files on Maven Central or any public repository at this point, because the file is not stable yet. In particular we will make no guarantee of backwards compatibility until the file format is 1.0.

**Comment by JakeWharton** [comment]
Yeah makes sense. Thanks. I was planning on publishing this as experimental (since all of Kotlin multiplatform is experimental as well).

**Comment by marcphilipp** [comment]
@JakeWharton Since Gradle 4.8, you no longer have to jump any hoops to make `maven-publish` work with `signing`.

Here's a sample project that shows how to do it:
https://github.com/marcphilipp/gradle-sandbox/blob/master/6788-module-signing/build.gradle.kts

It will in fact sign all files in the publication, including the `.module` file.
