### ISSUE TITLE
Renaming unrelated task makes test task not up-to-date

### ISSUE THREAD

**Issue by pkubowicz** [gradle/gradle#6864]
### Expected Behavior
Running tests is expensive, so they should be up-to-date when unrelated changes are done in build scripts

### Current Behavior
Tests task is marked as not up-to-date

### Context
I am running tests using Pact library, which produces contract files. I need to clean the output directory (`$buildDir/foo` in the simplified project below) before running tests, as the library has unpredictable merging mechanism.

### Steps to Reproduce (for bugs)
Use https://github.com/pkubowicz/gradle-tests-uptodate
1. Run `./gradlew barJar --console=verbose` - tests are run
2. Repeat `./gradlew barJar --console=verbose` - everything up-to-date
3. Edit `build.gradle`, changing `baz123` task name to `baz1234`
   - note that `barJar` is not related to this task in any way
4. Run `./gradlew barJar --console=verbose` - tests are re-run, although nothing related to `barJar` has changed

### Your Environment
Gradle 4.10.2, happens also on 4.8
 * Build scan URL: https://scans.gradle.com/s/em3pkt2jw7usg

**Comment by big-guy** [comment]
This is working as designed, but I understand it's a little confusing.

Using `doFirst` or `doLast` in a build script adds the build script as an input to the task because that's the implementation of the closure. This means any change to the build script affects the `doFirst` or `doLast` actions and that affects up-to-dateness.  That's the source of [`Task ':test' has additional actions that have changed`](https://scans.gradle.com/s/em3pkt2jw7usg/timeline?task=si6uhuz4tdufy).

e.g., if you were doing this:

```
def outputToDelete = file("$buildDir/foo")

test {
    doFirst {
        delete outputToDelete
    }
}
```

It's not enough to track the plain text contents of the `doFirst` block, we need to track more. Like a task's class implementation, we track the classloader, which tracks all of the classes/jars that are part of it. For build scripts, this also includes the build script file itself. 

I think you have a few options:

1. If you're using buildSrc, move the bit of logic that configures the `test` task into a plugin in buildSrc. This moves/limits the problem to just changes to buildSrc, which may be less frequent than changes to the build script.
1. You could create a pact plugin and publish it somewhere. This could be an evolution from 1 above. This would behave like you would expect and the `test` task would only be out of date when the pact plugin changed (or any of the usual Gradle things).
1. Delete these files in some other way. Maybe there's a way to configure pact to delete these files automagically?
1. We had talked about deleting outputs automatically on the Gradle side if we knew the task wasn't incremental, but I don't think we ever did that, did we @wolfs?
