### ISSUE TITLE
More consistent http flakiness handling

### ISSUE THREAD

**Issue by melix** [gradle/gradle#7355]
## Context

This is a follow up to #7333. There are several things we can do to improve handling of flakiness:

- expose public options for the internal flags related to http connections or connectivity retries
- investigate whether we can move the retry strategy deeper, for example at the `ExternalResource` level, so that more areas of Gradle can benefit from smarter retry strategies
- investigate whether build cache connectivity issues should be handled differently, and potentially with different build options
- investigate whether build cache requests should use `ExternalResource` too as to benefit from generic improvements in that area

**Comment by DavidMihola** [comment]
Just to make sure I am understanding this correctly: It is currently (as of 5.3.1) _not_ possible for users to configure the retry/backoff parameters described in https://github.com/gradle/gradle/pull/7333#issue-221948232 (`org.gradle.internal.repository.max.tentavies` and `org.gradle.internal.repository.initial.backoff`).

**Comment by melix** [comment]
It _is_ possible, just not supported.

**Comment by DavidMihola** [comment]
Thanks a lot for the quick reply!

OK, so when I set the total number of attempts to 1 by adding the system property 
`-Dorg.gradle.internal.repository.max.tentatives=1`
to my command line options it does indeed disable any retries.

But when I add the following line to `gradle.properties`
`org.gradle.internal.repository.max.tentatives=1`
I don't see any effect.

Is that what because it is an _internal_ property or am I doing something wrong?

But in any case, I was now able to do what I wanted to, so thanks again!

(BTW: You had a typo in the first property name in your other comment which I linked to above).

**Comment by bigdaz** [comment]
You can set system properties from a `gradle.properties` file: https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties

**Comment by DavidMihola** [comment]
Ah, yes - I don't know I missed that in the manual... Thanks a lot!

`systemProp.org.gradle.internal.repository.max.tentatives=1`

Incidentally, setting it via `org.gradle.jvmargs=-Dorg.gradle.internal.repository.max.tentatives=1` did work after all. I just had a typo in there... :-(
