### ISSUE TITLE
Ensure calculated durations are always non-negative

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#740]
Difference between invocations of `System.currentTimeMillis()` cannot be trusted to calculate durations because it can produce a negative value due to how CPU clock synchronization occurs in various environments. See http://steveloughran.blogspot.fi/2015/09/time-on-multi-core-multi-socket-servers.html

Anytime we do this:

```
long start = System.currentTimeMillis();
… do stuff …
long timePassed = System.currentTimeMillis() - start;
```

We should use:

```
long start = System.nanoTime();
... do stuff ...
long timePassed = TimeUnit.NANOSECONDS.toMillis(System.nanoTime() - start);
```

For actions that take fewer than 15 microseconds, you’ll sometimes notice that the difference between two reads of `nanoTime()` might be 0; however, it won’t produce negative values because it is always going to be monotonically increasing.
### Expected Behavior

All durations calculations (e.g. those for build times) should _never_ produce a negative value.
### Current Behavior

We sometimes encounter negative durations during builds that negatively affects logic and produces inaccurate logs.
### Context

This causes sporadic failures on Gradle CI, at the very least.

**Comment by bigdaz** [comment]
Note that

**Comment by bigdaz** [comment]
Something to be wary of when switching to use `System.nanoTime()`. From the Javadoc:
```
The values returned by this method become meaningful only when the difference between two such values, obtained within the same instance of a Java virtual machine, is computed.
```

In our dependency metadata cache, we record a timestamp value for each entry so that we can [determine the age of the entry](https://github.com/gradle/gradle/blob/1dfc8c946ba5f0c20cf2698b4e7956f0122933bb/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/modulecache/DefaultCachedMetaData.java#L35-L35) when using it later. While we are calculating a duration in this case, because this calculation is across JVMs, I don't think we can benefit from the monotonic clock of `nanoTime`.

**Comment by bigdaz** [comment]
I've made a [change to handle backward clock-shift](https://github.com/gradle/gradle/commit/def3268e7ad634db5fd8ba0bc868cfb9d90c8684) in dependency metadata checks. While not perfect, this change will help with the case where we set `cacheChangingModulesFor 0, 'seconds'` and a backward clock-shift occurs between the build that caches a dependency and a build that uses it. Previously, we'd reuse the cached dependency if it had a negative age: now if you say '0 seconds', we only use entries with age exactly zero (which is the case for entries created in the same build).
