### ISSUE TITLE
`VisitableURLClassLoader` should be registered as `parallelCapable`

### ISSUE THREAD

**Issue by jochenberger** [gradle/gradle#749]
Since `VisitableURLClassLoader` does not override any methods related to class loading and does not hold any state, it should be registered as parallel capable.
I see a lot of locking in `VisitableURLClassLoader.loadClass` in one of my tasks (that compiles a set of Groovy classes).
See https://blogs.oracle.com/dholmes/entry/parallel_classloading_revisited_fully_concurrent, https://docs.oracle.com/javase/7/docs/api/java/lang/ClassLoader.html.

**Comment by eriwen** [comment]
Hi @jochenberger, thanks for the request.

Can you please expand on why this change is important and concretely explain how this affects your build (e.g. from a user perspective)?

**Comment by jochenberger** [comment]
It makes parallel loading/compilation of classes possible. See [ClassLoader.loadClass(String, boolean)](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/ClassLoader.java#ClassLoader.loadClass%28java.lang.String%2Cboolean%29) and [ClassLoader.getClassLoadingLock(String)](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/lang/ClassLoader.java#ClassLoader.getClassLoadingLock%28java.lang.String%29). If the ClassLoader isn't parallelCapable, it synchronizes over the `this` instead of an object that's tied to the class name.
See [URLClassLoader.java](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/net/URLClassLoader.java?av=f#779) for an example.

**Comment by eriwen** [comment]
@jochenberger Ok. I'm really looking for: "In what way and how much would a typical user benefit if we did this change and nothing more?" We want to know if this would affect everybody, or just those running `--parallel` and whether the gain is significant enough that we should do this _instead of other_ performance optimizations.

**Comment by jsotuyod** [comment]
The change would only impact under multithreading (`--parallel`). The synchronization is still performed, just under different objects, and without threads, the JVM could remove the synchronization on runtime in either case.

I haven't profiled gradle for this scenario, but have seen it in other tools such as PMD (which performed this very change not long ago, see https://github.com/pmd/pmd/pull/101). 

Still, the important thing here, is that this is low hanging fruit. `VisitableURLClassLoader` is already thread-safe, so the change is literally just adding :


```
static {
  ClassLoader.registerAsParallelCapable();
}
```

No tests need to be changed / added, since this is part of the JRE, and current tests would detect misbehavior / performance regressions. 

I volunteer to submit this as a PR if you think this is taking focus away from the core team.

**Comment by jochenberger** [comment]
I would have created a PR, but I don't want to be forced to sign a CLA. But I'd appreciate if you did it @jsotuyod.

**Comment by lhotari** [comment]
+1 
I've had this on my performance wish list for some time. I'd appreciate if @jsotuyod sends a PR for this.
There is also this Oracle JDK doc about the feature: http://docs.oracle.com/javase/7/docs/technotes/guides/lang/cl-mt.html

**Comment by lhotari** [comment]
However there is a risk in this change. Explained in [Recommendations for Multithreaded Custom Class Loaders](http://docs.oracle.com/javase/7/docs/technotes/guides/lang/cl-mt.html)

> Custom class loaders that do not have a history of deadlocks do not require any changes. In particular, you do not need to change custom class loaders that follow the recommended acyclic hierarchical delegation model, that is, delegating first to their parent class. For backward compatibility, the Java SE 7 release continues to lock a class loader object unless it registers as parallel capable.

**Comment by jochenberger** [comment]
Fixed via #772
