### ISSUE TITLE
"Problems reading data from Binary store" while running shadowJar task

### ISSUE THREAD

**Issue by emmanuelguerin** [gradle/gradle#7494]
Hello,
While running an internal build, we encountered an issue when adding a single dependency to the graph.
Before adding the dependency, everything works:
- https://scans.gradle.com/s/z6p4fdo2sjzeq/ (gradle 4.8.1)
https://scans.gradle.com/s/z6p4fdo2sjzeq/dependencies?toggled=W1sxXSxbMF0sWzEsOF1d

After adding the dependency, we get this failure during the shadowJar task execution, while resolving dependencies:
- https://scans.gradle.com/s/5y2vqeoxllax2/ (gradle 4.8.1)
https://scans.gradle.com/s/5y2vqeoxllax2/dependencies?toggled=W1sxXSxbMSw0XV0
- https://scans.gradle.com/s/jhgieg5xwgbre/ (gradle 4.10.2)
https://scans.gradle.com/s/jhgieg5xwgbre/dependencies?toggled=W1s2XSxbNiw0XV0

We had to rollback to gradle 4.6 to make the build pass:
- https://gradle.com/s/o7vno7ly4bvlc
https://scans.gradle.com/s/o7vno7ly4bvlc/dependencies?toggled=W1sxXSxbMSw1XV0

It doesn't seem to be related to parallelization. Happens with or without it.
Just running a gradle dependencies on the same configuration produces no error.

Reproduced on Mac OS and Linux

This is a continuation of a discussion on #6823

**Comment by emmanuelguerin** [comment]
@melix Here is the new issue

**Comment by melix** [comment]
@ljacomet Can you check if this could already be fixed with your recent changes?

**Comment by ljacomet** [comment]
Without a reproducible case, it is always hard to tell. The problem is that we need to understand which part of the graph is causing the deserialization failure. Once that's understood, we need to figure out the root cause that led to an inconsistent graph being serialized.

@emmanuelguerin Any chance you can test with the [Gradle 5.0 M1](https://gradle.org/release-candidate/)?
It contains the fix for #6907 and other previous fixes around resolution graph state.

**Comment by emmanuelguerin** [comment]
We are not 5.0 compatible yet because of the publishing delayed issue. I’ll
try to test something quick and dirty.

Le mar. 23 oct. 2018 à 11:40, Louis Jacomet <notifications@github.com> a
écrit :

**Comment by emmanuelguerin** [comment]
I finally got to test this in Gradle 5.0. The issue disappears.

**Comment by emartynov** [comment]
I don't know if it is a regression but we have next:

```
* What went wrong:
Execution failed for task ':libs-rx:kaptGenerateStubsTestKotlin'.
> Could not resolve all dependencies for configuration ':libs-rx:testCompileClasspath'.
   > Problems reading data from Binary store in /tmp/gradle5616282196080974387.bin (exist: false)
```

What are the next steps? What information more you need?

We are on Gradle 5.2 and Kotlin 1.3.21 and Android Gradle Plugin 3.4.0-beta03.

**Comment by nniesen** [comment]
The problem is that is completely random. I had a build fail 3 times on CI server and then 3 hours later, it ran just fine with no changes. The same error couldn't be reproduced locally at the same time. The issue is present in 6.5 and all the way back to at least 3.2, from search. It seems to be a threading issue where Gradle deletes it's own temp file before it should. That seems to be why random changes "fix" the issue. It would be helpful if the error reported the dependency in question but that might not help since the entire temp file is not present.
