### ISSUE TITLE
Use intellij import delegating test execution to Gradle

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#7520]
We can import the `gradle/gradle` project into Intellij using the native import (https://github.com/gradle/gradle/issues/3980).

We should be able to delegate test execution to the Gradle runner.

**Comment by wolfs** [comment]
The main issue with this is https://youtrack.jetbrains.com/issue/IDEA-169795 currently: integration tests cannot be executed since Intellij tries to run the `test` task.

In order to enable delegation, switch to the Gradle test runner and delegate build/run actions to Gradle:
![image](https://user-images.githubusercontent.com/423186/47446721-1c18a200-d7bc-11e8-82fc-7e941d9f75d1.png)

Manually changing the task in the run configuration works and allows to run the test.

![image](https://user-images.githubusercontent.com/423186/47446547-c217dc80-d7bb-11e8-9015-af6efebf17e7.png)

![image](https://user-images.githubusercontent.com/423186/47446648-f9868900-d7bb-11e8-8b15-100b671f3119.png)

**Comment by jjohannes** [comment]
This is an issue independent of whether you use the 'module per source set' import option or not.

**Comment by oehme** [comment]
Right now this is hard-coded in the Tooling API. It simply runs the `test` task when the client requests a test to run. I've discussed this with the IDEA team and we identified the following issues in choosing the right task:

- It can be complicated to tell which test is part of which test task, since you can have complex filters, e.g. JUnit tags. Making this detection 100% correct would take a lot of resources
- Even if you know exactly which test is in which task, you can have multiple tasks running the same test. E.g. our embedded, forking and no-daemon suites. There's no way to tell automatically what to do, you'll have to ask the user which one they meant.

Based on this my proposal to the IntelliJ team looked something like this:

The TAPI client passes a test to run. Gradle doesn't pick a task up-front, but instead first configures the project and then looks at all the test tasks in order to find the ones that could contain this test. This can be somewhat fuzzy to improve performance, e.g. it might only take include/exclude patterns into account and ignore JUnit tags. If there is only one task, run it. If there are multiple ones, send a request back to the TAPI client so it can prompt the user to choose.

The IntelliJ team argued that this would lead to a bad user experience, since you could end up clicking on run, grab a coffee and later come back to see a prompt instead of a finished test. Instead they would like to be able to present the user a list of potential tasks up-front. This would require a different approach:

The TAPI client requests a model containing a list of all the test tasks and which files they include. Again, this can be a superset, to improve performance. When the user clicks on a test in the UI, the IDE checks this list (which it already has in memory) and can immediately present a selection box if the request is ambiguous. It is then up to the IDE to pass the task it wants to run back to the TAPI. This approach could be implemented in IntelliJ without any changes to the TAPI. 

Another approach could be to add some disambiguation DSL to the `idea` model, so that Gradle can always do an automatic choice (and fail if an ambiguity is found).

**Comment by jjohannes** [comment]
I had a look at the sources to understand what we need to do to implement one of the approaches. Or what would be a good first step without too much effort. I think the current situation is a bit different as I understood it first. @oehme please correct me if I got something wrong.

There are effectively two mechanisms to run tests through the tooling API:

1. Use the normal `BuildLauncher` and start a test task.
2. Use the [`TestLauncher`](https://github.com/gradle/gradle/blob/master/subprojects/tooling-api/src/main/java/org/gradle/tooling/TestLauncher.java) which allows you to start a test without specifying a task (in theory).

IDEA is currently using the first method and is initially starting the `cleanTest` and `test` tasks for the corresponding project. This is [hardcoded in IDEA](https://github.com/JetBrains/intellij-community/blob/1a59715f9c4c6cb254896028f8b50e8b0583e6bc/plugins/gradle/java/src/execution/test/runner/GradleTestRunConfigurationProducer.java#L42) *not* in Gradle. The tasks can the be manually adjusted since this is done through a build configuration as pointed out [above](https://github.com/gradle/gradle/issues/7520#issuecomment-432733691).

The `TestLauncher` accepts starting a test without a task. What Gradle is doing then is starting **ALL** [test tasks in all subprojects](https://github.com/gradle/gradle/blob/0bafbe487677d951ecfa66daae6db2c3e1ac21a7/subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationAction.java#L108-L118) with the a test filter – which means most tasks won't run any test. This is practically unusable in large builds with many test tasks. I am not really sure if this is something we even want to support on the long run. Maybe @oehme can shed some light on this (is this used in Buildship in some way?).

One variation of the ideas above that came to my mind when looking at his:
IDEA only passes a test to run and no tasks. For this it user a varied/extended TestLauncher provided by Gradle. Gradle the runs only the first test task it finds for the test(s). Resolving a potential conflict by selecting the "first found". IDEA then picks up which test task ran and puts that into the run config. If there is another test task for the same test which the user would like to choose she can edit the run config. In addition we could (in a next step) extend the `idea` model to control which task Gradle picks in case of a conflict.
This avoids the need for a new selection box and still allows the user to choose a different task after the initial test run - with the exiting mechanism of editing the run configuration. So I think it's close to what we have at the moment.

**Comment by jjohannes** [comment]
No it's not failing. I think because of [this setFailOnNoMatchingTests(false)](https://github.com/gradle/gradle/blob/0bafbe487677d951ecfa66daae6db2c3e1ac21a7/subprojects/tooling-api-builders/src/main/java/org/gradle/tooling/internal/provider/runner/TestExecutionBuildConfigurationAction.java#L58).

Since I had the IDEA source already checked out, I tried it out and changed it so that IDEA would use the TestLauncher. Then I ran `org.gradle.api.plugins.announce.AnnouncePluginIntegrationTest`. The tests executed 6 times (for each of the different `integTest` variations we have). These executions were correctly picked up by IDEA and reported and I could navigate the test results as expected in the the _Run Tool Window_. But it also ran all other Test tasks of the Gradle build, executing 0 tests. So it had to compile the whole Gralde project and whatever else these noop test tasks depend on.

**Comment by jjohannes** [comment]
Actually it eventually failed when it tried to configure `distributedFullPerformanceTest` which only runs on CI.
I guess we should improve this _test task selection_ code. How does Buildship use this exactly?

**Comment by wolfs** [comment]
@jjohannes I realized last Friday that delegating test execution to Gradle is not easy any more, when using "module per source set".

When using one module per project, IDEA would try to run the `Test` task when executing any test in the project. Then one would only need to change the task to run.

When using module per source set, IDEA doesn't recognize the `integTest` source set as something which has a test task. So it always runs the integ test via IDEA and via Gradle. See [Slack](https://gradle.slack.com/archives/CBSJ2GUTV/p1543615691018200).

**Comment by jjohannes** [comment]
Both issues, that the wrong task is picked (https://github.com/gradle/gradle/issues/7520#issuecomment-432733691) and that delegation to Gradle does not work at all (https://github.com/gradle/gradle/issues/7520#issuecomment-443687679) are fixed by https://youtrack.jetbrains.com/issue/IDEA-203517.

(The fix is on IDEA master and will go into an upcoming 2018.3.x release)

**Comment by jjohannes** [comment]
The fix has been released with IntelliJ `2018.3.2`. I am closing this issue.

For other problems with the IntelliJ import, please open separate issues and add them to the Epic #6809.
