### ISSUE TITLE
Importing ant build with target rename option causes dependency missmatch with gradle tasks

### ISSUE THREAD

**Issue by rzillmann** [gradle/gradle#7544]
### Expected Behavior
Renamed imported ant targets which depend on another target should take into account that the dependency might be (already) a gradle task

### Current Behavior
Imported target dependencies are also translated to the renamed task which causes the parent task to fail as such a task is not present within the build.xml or build.gradle

### Context
The company im working for is starting to migrate an old and huge ant project to gradle.
As the size of the old build makes it impossible to migrate all at once we chose to do it partialy after reading that gradle and ant are good buddys and its possible to couple them while transitioning.
The gradle documentation even mentions that an ant target can depend on a gradle task.
However, that comes with some hiccups if you choose to rename the imported task (For example to make it more clear that it is an ant target) as the renaming affects the dependencies too.

### Steps to Reproduce (for bugs)
**build.gradle**
```
task target2{
    doLast {
        println 'Hello, from Gradle'
    }
}
```

**build.xml**
```
<project>
    <target name="target1"  depends="target2">
        <echo>Hello, from Ant</echo>
    </target>
</project>
```
BUILD FAILED in 0s
Imported Ant target 'a-target1' depends on target or task 'a-target2' which does not exist
15:33:15: Task execution finished 'a-fest'.

If the gradle task is renamed to a-target2 this no longer happens.

### Test case (DefaultAntBuilderTest)
```
    def 'imported ant target can depend on gradle task' () {
        File buildFile = new File(project.projectDir, 'build.xml')
        buildFile.withWriter { Writer writer ->
            def xml = new MarkupBuilder(writer)
            xml.project {
                target(name: 'target1', depends: 'target2')
            }
        }

        when:
        ant.importBuild(buildFile) { taskName ->
            'a-' + taskName
        }

        then:
        project.getTasks().create('target2')
        def task = project.tasks.'a-target1'
        def task2 = project.tasks.'target2'
        task instanceof AntTarget
        task.target.name == 'target1'
        task2 instanceof DefaultTask
        task.taskDependencies.getDependencies(task).name.sort() == ["target2"]
    }
```

**Comment by ghale** [comment]
Well, alternate scenario here would be that the ant targets are being renamed because they collide with Gradle task names and you want to use the ant target rather than the Gradle task.  For instance, there is a task named `test` in both the Gradle build and the ant build and so we want to only use the ant task for dependencies in ant and only use the gradle test task for dependencies in gradle.  I may not want it to use a Gradle task if the ant task doesn't exist.  

I don't think we want to change the behavior here in a way that would change the existing functionality.  In other words, I think different users might have different desired heuristics for what to do if the renamed task doesn't exist, and the current configuration mechanism doesn't provide good ways to express that.  It sounds like what you're looking for is "use an ant target with the provided name (task name prepended with 'a-') if it exists, or use a gradle task with exactly the provided name".  

One workaround that currently exists that would handle your scenario is using a [task rule](https://docs.gradle.org/current/userguide/more_about_tasks.html#sec:task_rules) to bridge missing ant tasks to gradle tasks.  So something like:

```
def ANT_PREFIX='-a'
ant.importBuild(buildFile) { taskName -> ANT_PREFIX + taskName }
tasks.addRule("Bridges renamed ant targets to gradle tasks when missing") { taskName ->
    if (taskName.startsWith(ANT_PREFIX)) {
        tasks.create(taskName) { dependsOn(taskName - ANT_PREFIX) }
    }
}
```

In this case, if `a-target2` already exists (because it was imported from the ant build) it will pick up that task, otherwise, the rule will fire and match, creating an `a-target2` with a dependency on the `target2` Gradle task.  If the Gradle task doesn't exist, you'll get a similar exception, just on the missing Gradle task instead of the renamed ant task.  Would something like that work for you?

**Comment by rzillmann** [comment]
Sorry for necro: Totally forgot about this as i'm no longer working in this context. So im fine with this not being worked on.

Keep up the good work.
