### ISSUE TITLE
Continuous build: File watcher regression in 2.11

### ISSUE THREAD

**Issue by delego-wlritchi** [gradle/gradle#756]
In a project with the war plugin applied, tasks that take src/main/webapp as an input directory fail to correctly watch this directory when run as a dependency of the classes task. There's probably a non-plugin-specific cause, but I can't pinpoint it.
### Expected Behavior

When modifying a file under src/main/webapp, I expect tasks declaring this directory as an input directory to be retriggered when they are part of a continuous build, regardless of whether they are run as a target task or as a dependency of some other task.
### Current Behavior

When such a task is run as a dependency of the classes task, changes under src/main/webapp do not retrigger the build.
### Context

In a project using the war plugin, I am trying to automatically run a custom task for JS/CSS processing when src/main/webapp is changed, so that I can quickly and easily see code changes in the browser.
### Steps to Reproduce (for bugs)
- Clone https://github.com/delego-wlritchi/gradle-watch-bug
- Run ./gradlew classes -t
- In a new terminal, modify a file under src/main/webapp. Observe that the build is not retriggered.
- Now modify the toplevel file. Observe that the build is retriggered as expected.
### Your Environment
- Gradle Version: 2.11 through 3.2-rc-1
- Last worked correctly in: 2.10
- Operating System: Arch Linux 64-bit
- JVM version: OpenJDK 1.8.0_102

**Comment by oconnelc** [comment]
I haven't isolated at what point it changed, but I have done some preliminary investigation into the cause: 

In the file: WatchServiceRegistar.java in the method watch:  

    void watch(FileSystemSubset fileSystemSubset) throws IOException {
        lock.lock();
        try {
            LOG.debug("Begin - adding watches for {}", fileSystemSubset);
            final WatchPointsRegistry.Delta delta = 
                watchPointsRegistry.appendFileSystemSubset(fileSystemSubset, getCurrentWatchPoints());
                Iterable<? extends File> startingWatchPoints = delta.getStartingWatchPoints();

This method gets called twice. The first time to start the watching of src/main/java, which is added by the JavaPlugin, which is added by WarPlugin.java. In this all the src/main/webapp is rejected in the FileWalker, defined within the watch method: 

    Files.walkFileTree(dirPath, new SimpleFileVisitor<Path>() {
    @Override
    public FileVisitResult preVisitDirectory(Path path, BasicFileAttributes attrs) throws IOException {
        if (!path.equals(dirPath)) {
            if (delta.shouldWatch(path.toFile())) {
                watchDir(path);
                return FileVisitResult.CONTINUE;
             } else {
                 LOG.debug("Skipping watching for {}, filtered by WatchPointsRegistry", path);
                 return FileVisitResult.SKIP_SUBTREE;
             }
         } else {
            return FileVisitResult.CONTINUE;
         }
     });

The call to the delta.shouldWatch is rejected because src/main/webapp is not a child of src/main/java. 

In the second pass, a new Delta is created with the following parameters: 

fileSystemSubset: with files = $projectDir/topLevel and tree=$projectDIr/src/main/webapp
getCurrentWatchPoints() = {$projectDir/src/main, $projectDir} 

when calling the delta.getStartingWatchPoints(), the starting points only contains: $projectDir. 

In the for loop that iterates over the starting points,  src/main/webapp is skipped because the entire src dir is skipped.  This is because the src/main/webapp is defined as a root within the delta. As a result, no watchpoint is ever registered because the delta.shouldWatch() returns false for the src directory and prevents the rest of the subtree from being registered. 

I'm not sure what the correct way to resolve this.
