### ISSUE TITLE
Task dependencies resolve serially

### ISSUE THREAD

**Issue by DanielThomas** [gradle/gradle#7571]
A recent change to the UI made it more obvious that configurations resolved as part of resolving task dependencies are resolved serially, and can add significantly to build time (previously you'd notice them resolving on various workers). 

Task configuration dependencies happen serially on the main thread, and don't receive any benefit from parallelization:

```
visitDependencies:1512, DefaultConfiguration$ConfigurationTaskDependency (org.gradle.api.internal.artifacts.configurations)
getNodeValues:96, CachingTaskDependencyResolveContext$TaskGraphImpl (org.gradle.api.internal.tasks)
getNodeValues:211, CachingDirectedGraphWalker$GraphWithEmpyEdges (org.gradle.internal.graph)
doSearch:121, CachingDirectedGraphWalker (org.gradle.internal.graph)
findValues:73, CachingDirectedGraphWalker (org.gradle.internal.graph)
getDependencies:64, CachingTaskDependencyResolveContext (org.gradle.api.internal.tasks)
resolveDependenciesFor:46, TaskDependencyResolver (org.gradle.execution.taskgraph)
getDependencies:89, LocalTaskInfo (org.gradle.execution.taskgraph)
resolveDependencies:62, LocalTaskInfo (org.gradle.execution.taskgraph)
addToTaskGraph:168, DefaultTaskExecutionPlan (org.gradle.execution.taskgraph)
addTasks:126, DefaultTaskExecutionGraph (org.gradle.execution.taskgraph)
```

Relates to https://github.com/gradle/gradle/issues/6113, which addresses parallelism within the resolve itself.

### Your Environment
Gradle 4.10.2

**Comment by melix** [comment]
Just commenting with what I have explained yesterday during our meeting:

- task dependencies are resolved at _configuration time_. Configuration is mostly serial.
- during task dependencies resolution, there shouldn't be _any_ external request being issued, except:
   - when a dependency substitution happens (an external module is replaced with a local project, so we have to fully resolve the graph in order to find if and where the substitution should happen)
   - when using a _composite build_ (for the same reason, composite builds depend on dependency substitutions)

If you see "dependency resolution", in terms of fetching metadata from external repositories, or worse, jars being downloaded during configuration, then there are a couple of possibilities:

- a task is resolving at configuration time, which it shouldn't
- it's a `buildSrc` dependency and it's probably plugins being downloaded

In both cases, metadata should be fetched in parallel (for dependency edges).
