### ISSUE TITLE
Investigate issues relating to dependency `type` attribute and Android builds

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7595]
There are a couple of open issues relating the publishing and resolving of Maven modules from Android builds, relating to the setting of the `type` attribute:

- #3170 is about Gradle not including the `type` attribute in the published POM dependencies.
    - The issue assert that this bug only impacts Maven consumers of the the published POM. In a Gradle-only ecosystem with POM publications, the missing `type` attribute is not a problem.
- #7594 shows that Gradle doesn't always function well when the `type` attribute _is present_ in the published POM dependencies. So if we fix #3170, we might make things worse for users that don't care about Maven interoperability.
- The Google Crashlytics installation docs require/suggest that users add `@aar` and `transitive = true` to the dependency declaration. https://fabric.io/kits/android/crashlytics/install
    - @autonomousapps asked Aurimas about this, and it was claimed that this is a workaround for #3170.

We should really properly understand how things currently work, so that we can make firm recommendations. Note that the use of `@aar` can be problematic due to #1487, which requires users to also add `transitive = true` to override the default non-transitive behaviour.

**Comment by liutikas** [comment]
While #3170 does not break Gradle users, it does produce POM files that are not up to spec. According to [the POM reference](https://maven.apache.org/pom.html) if type is omitted it is assumed to be a `jar`. We ship the most popular Android libraries out there (android.support/androidx) and thus we have clients with all sorts of build systems (including maven). It is not acceptable for us to ship broken POMs, hence we apply 2 workarounds

1. when we specify a binary dependency, we add type classifier e.g. `com.foo:bar:1.0@aar`
2. when it is a project dependency, [using reflection we look up project type and set type classifier explicitly](https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/buildSrc/src/main/kotlin/androidx/build/MavenUploadHelper.kt#132).

When we do the first workaround, we also have to specify `{transitive = true}` because gradle default is to *not* be transitive when a classifier is specified.
