### ISSUE TITLE
Upgrading to Gradle 5.0-rc1 breaks Dokka use in `buildSrc/`

### ISSUE THREAD

**Issue by liutikas** [gradle/gradle#7598]
Upgrading to Gradle 5.0-rc1 breaks Dokka use in `buildSrc/`

### Expected Behavior
I can continue to use Dokka documentation plugin in my project after upgrading to Gradle 5.0-rc1

### Current Behavior
`./gradlew tasks` fails with:
```
e: /ssd/ssd1/temp/HopefullyThisBreaks/buildSrc/src/main/kotlin/test/Test.kt: (1, 35): Unresolved reference: DokkaPlugin
> Task :buildSrc:compileKotlin FAILED
```

### Context
We cannot move to using Gradle 5.0-rc1

### Steps to Reproduce (for bugs)
https://github.com/liutikas/gradle5_0_rc1_breaking_dokka

Instructions are:
`./gradlew tasks` will break with Gradle 5.0-rc1, but not 4.10.1

### Your Environment
N/A

**Comment by SUPERCILEX** [comment]
Same here, Kotlin compilation just broke completely for me.

https://github.com/SUPERCILEX/Robot-Scouter
Setup: `./gradlew setup`

**Comment by liutikas** [comment]
Note that Gradle 5.0 milestone 1 did not have the same issue

**Comment by SUPERCILEX** [comment]
It did for me. 🤔

**Comment by eskatos** [comment]
Thanks for the report @liutikas, I can reproduce starting with 5.0-milestone-1.

The resolved dependencies differ between [4.10.2](https://scans.gradle.com/s/7igyn4tra4ykw/dependencies?focusedDependency=WzAsMCw4LFswLDAsWzhdXV0&toggled=W1swXSxbMCwwXV0) and [5.0](https://scans.gradle.com/s/fx6wq7s4em6zg/dependencies?focusedDependency=WzAsMCw4LFswLDAsWzhdXV0&focusedDependencyView=dependencies_or_failure&toggled=W1swXSxbMCwwXV0).

With 5.0, using the `gradlePluginPortal()` repository instead of `jcenter()` somehow fixes the issue. The transitive dependencies are [properly resolved]((https://scans.gradle.com/s/jtvpptsfkcy3m/dependencies?focusedDependency=WzAsMCw4LFswLDAsWzhdXV0&toggled=W1swXSxbMCwwXV0)).

5.0 includes changes to dependency resolution that might impact how the metadata for Dokka artifacts published to jcenter is consumed by Gradle - @gradle/dependency-management , could you have a look?

**Comment by ljacomet** [comment]
So the issue comes from the way the dependency of `dokka-android-gradle-plugin` are declared.

In the Gradle plugin portal, we have the following declaration:
```
<dependency>
  <groupId>org.jetbrains.dokka</groupId>
  <artifactId>dokka-gradle-plugin</artifactId>
  <version>0.9.17</version>
  <scope>compile</scope>
  <type>jar</type>
  <optional>false</optional>
</dependency>
```

But in JCenter, the pom file says:
```
<dependency>
  <groupId>org.jetbrains.dokka</groupId>
  <artifactId>dokka-gradle-plugin</artifactId>
  <version>0.9.17</version>
  <scope>runtime</scope>
</dependency>
```

The important part is the `scope` entry. With Gradle 5.0 we activated the `IMPROVED_POM_SUPPORT`, previously a feature preview, and one of the effect is to respect better the declared Maven `scope`. Which means that for Gradle, when consuming JCenter metadata, there is no `compile` time dependency to `dokka-android-gradle-plugin`, only a `runtime` one.

2 options to move forward:
* If you believe the metadata is correct, then you need to add the dependency explicitly to your build: 
  * `implementation 'org.jetbrains.dokka:dokka-gradle-plugin:0.9.17'`
  * and you should consider using `implementation` instead of `compile` for the other dependency as well
* if you believe the metadata is wrong, then you can patch it using a `ComponentMetadataRule`:
  * This rule will fix the metadata by adding the dependency to the `compile` scope as well.
  * Consider reporting the wrong metadata to Jetbrains so that future versions can be published correctly
```
dependencies {
    components {
        withModule('org.jetbrains.dokka:dokka-android-gradle-plugin', DokkaGradlePluginFix)
    }
}

class DokkaGradlePluginFix implements ComponentMetadataRule {
    @Override
    void execute(ComponentMetadataContext context) {
        context.details.withVariant('compile') {
            withDependencies {
                add('org.jetbrains.dokka:dokka-gradle-plugin:0.9.17')
            }
        }
    }
}
```

Note that again the `dokka-gradle-plugin` has all its dependencies declared as `runtime` in JCenter, but not the Gradle plugin repository. So any further transitive dependency that is required will have to be brought in using either of the two approaches above.

**Comment by eskatos** [comment]
Thanks for the analysis @ljacomet!

Having the same artifacts published with different metadata doesn't feel right.
@liutikas, could you please raise that issue to [Dokka](https://github.com/Kotlin/dokka)?

**Comment by big-guy** [comment]
@ljacomet Do you think this could be closed?

**Comment by ljacomet** [comment]
Yes, closing as this change of behavior is expected in Gradle and fix belongs in another project.
