### ISSUE TITLE
BOM import (`platform` dependencies) should work without `java` plugin applied

### ISSUE THREAD

**Issue by bigdaz** [gradle/gradle#7600]
Unfortunately, when we introduced the `VariantDerivationStrategy`, it broke BOM import for any project without the `java` plugin applied. This is confusing, as there is no warning that the `platform` function will have no impact on a dependency declaration.

From a user point of view, there is no reason that BOM import should not work without the `java` plugin applied.

### Expected Behavior

I can use declare a `platform` dependency and it will work for BOM import without the `java` plugin applied.

### Current Behavior

When the `java` plugin is not applied, a `platform` dependency is treated like a regular dependency. If the target is a Maven BOM, then the `dependencyManagement` elements are not added as dependency constraints.

**Comment by melix** [comment]
I disagree that there's no reason. Actually this is on purpose, since derived variants need to have Java specific attributes. If we didn't do this, then we would reintroduce the problem that some native builds would have to interpret Java specific attributes, which is not correct. Instead, there should be a derivation strategy _per ecosystem_.

**Comment by bigdaz** [comment]
Your reasons are technical, and relate to the way that we've implemented BOM support. As a user, I would expect this to just work regardless of the plugins that I have applied.

The fact that there's no warning about it makes it hard to work out what's going on.

**Comment by melix** [comment]
It's not really technical: it's about the semantics. We don't want to derive variants if the consumer is native, we only want to do this if it's JVM based. There's no reason to do it by default, as there are assumptions on what is a platform that are baked in.

At best, I'd change this ticket to be something like producing an error if you use `platform(...)` and that there's no derivation strategy in place. That would be arbitrary, but would cover, I think, the problem you mention that it's silently ignored otherwise.

**Comment by bigdaz** [comment]
Think about me as a naive user, and my question is: "Why can't BOM import just work? Why does it matter what plugins I have applied?" I think these are reasonable questions, and I wouldn't understand why your answer is referring to variants. 

I'm sure if we think BOM import should work in all cases, we can find a smart way to make it work. I understand that our current implementation of deriving multiple variants for Maven modules doesn't make this easy, but I don't think it provides a good user-focussed reason for why this shouldn't work.

Maybe there's something inherent in BOMs and Maven repositories that makes it impossible for us to make this work. But if we're going to say that "BOM import will never work without a BOM-aware ecosystem plugin", then I'd like to have a good _user-focused_ reason why.

**Comment by melix** [comment]
I understand but what is the likelihood that you use _BOM_ import without a Java plugin applied? It's a concept of the Java ecosystem after all...

**Comment by ljacomet** [comment]
Closing as there is no plan to change anything without a real use case.

**Comment by Kinchkun** [comment]
Hi,

we use Gradle for your iOS-Development. We have developed a custom Xcode-Plugin, for Dependency-Management and Building.

We would like to use BOM with Gradle 6.

Does this issue still holds, that this isn't supported bei Gradle and there are no plans to support ist?

**Comment by melix** [comment]
There is no plan to support this because a BOM is defined in the context of a Java project. It has no semantics outside. You don't _have_ to use a BOM with Gradle 6, you can use the native Gradle 6 features and define your own platform.

**Comment by jjohannes** [comment]
@Kinchkun  To give some pointers:

If you publish a platform with the [Java Platform](https://docs.gradle.org/current/userguide/java_platform_plugin.html#sec:java_platform_publishing) plugin you will now also get a Gradle Module Metadata file. If you consume that (with Gradle 6). `platform()` dependencies will work. 

In theory, "plain" BOMs can also work if you define a Component Metadata Rule in your plugin that mimics what `VariantDerivationStrategy ` does (see this [doc section](https://docs.gradle.org/current/userguide/variant_model.html#sec:mapping-maven-ivy-to-variants) for background). 
But the simpler and better solution would be to rely on platforms published with Gradle Module Metadata.

**Comment by Kinchkun** [comment]
Thank you both for our fast reply.

We use gradle for our Java, Android and iOS Development. We have a high rate of modularisation. Currently, every module defines it own set of dependency which doesn't scale very well.

We looked at gradle module metadata at first, but it appears to us that this doesn't work for non-java Projects: https://discuss.gradle.org/t/gradle-module-metadata-for-non-java-projects/33819

But if I understand this correctly, we can use the Java-Platform plugin to produces .module files which can be consumed by any gradle project?

Sounds good. We will try it out.

**Comment by melix** [comment]
To be clear, you are working on an _unsupported ecosystem_ (iOS). As such, there's a lot to invent, but Gradle makes it possible. There's absolutely no limitation on Gradle Module Metadata, which is also used outside of the Java ecosystem (it's one of the key requirements, actually, we _also_ use it in the native ecosystem). The issue you're linking to is unrelated: it basically says that you cannot use Gradle Module Metadata with projects which do not declare components. There's a [public API](https://docs.gradle.org/current/userguide/publishing_customization.html#sec:publishing-custom-components) to declare components, so you absolutely can use it.

Now, it's always better if we support the ecosystem altogether, but it's a lot of work. You _can_ work with your own, declare your own attributes, and get everything working. This means you'd have your little world working, it doesn't mean it would be compatible with the larger ecosystem if one day we decide to support iOS.

As for using the "Java Platform" plugin. Again, it's aimed at building _platforms for the Java ecosystem_. It knows about the semantics of Java and it creates variants with Java attributes, just like when you work with BOMs. So, either you pretend that everything in your iOS world is in fact Java components, and then you can use BOMs and Java Platform, in which case, just apply the `java-base` plugin and you're done. Otherwise, you have to build your own ecosystem and mimic what the Java Platform does. It's not hard, but you have to understand a bit more. The userguide contains [information for plugin developers](https://docs.gradle.org/current/userguide/variant_model.html) if you want to go down that route.

**Comment by Kinchkun** [comment]
Thank you. We are very happy with gradle for our iOS Development. Of course we had to invest into developing the necessary plugins. However, we never used of the "software component" concept of gradle, mostly because we don't understand it purpose. But It seems promising and we will start evaluating it.
