### ISSUE TITLE
CopySpec expand doesn't seem to work with multiple expands

### ISSUE THREAD

**Issue by devinrsmith** [gradle/gradle#7634]
This [guide](https://docs.gradle.org/current/userguide/working_with_files.html#example_filtering_files_as_they_are_copied) seems to suggest that expand works with multiple invocations.

I've got a simple repo here reproducing the issue I ran into: https://github.com/devinrsmith/gradle-expand-test

**Comment by ghale** [comment]
There's a couple of things here:
- The guide should not advertise this as it doesn't work and doesn't add anything to the example - it just happens to work because all of the property expansions are handled by the first `expand()` call.
- The api allows you to call expand multiple times, which causes multiple transforms to be registered, but if all of the expansions are not handled in the first transform, `SimpleTemplateEngine` throws an exception.  We should probably allow multiple calls to `expand()` but gather up all of the properties and do a _single_ transform with the aggregated properties instead.
