### ISSUE TITLE
Task annotations on java fields

### ISSUE THREAD

**Issue by larsgrefer** [gradle/gradle#7688]
According to their documentation, the task annotations (`@Input`, `@OutputFile`, ...) have to be placed on the getter-method when using java:

> This annotation should be attached to the getter method in Java or the property in Groovy. Annotations on setters or just the field in Java are ignored.

This documentation seems to be wrong. I'm successfully using the annotations on java fields: https://github.com/freefair/gradle-plugins/blob/869c0b64c3d8caea95e6fbddccf7ed6f1f57bdc7/jsass-plugin/src/main/java/io/freefair/gradle/plugins/jsass/SassCompile.java#L150-L226 (The getters and setters are generated by lombok)

I'd like to propose to explicitly allow these annotations to be placed on java fields.

**Comment by marcphilipp** [comment]
Are you sure the annotations work, e.g. are taken into account for up-to-date checking?

**Comment by marcphilipp** [comment]
I finally had a chance to look into this issue. Your code works, because you generate getters and we merge annotations from getters and corresponding fields:

https://github.com/gradle/gradle/blob/d73a0d258ba295db698fb19f893e476b34c86552/subprojects/core/src/main/java/org/gradle/api/internal/tasks/properties/DefaultPropertyMetadataStore.java#L188

@gradle/build-cache Do you think we should document this better?

**Comment by wolfs** [comment]
I don't think we should document this better. We currently gather the annotations from the fields, since that is what happens when you annotate Groovy properties:
```
class MyTask extends DefaultTask {
    @Input
    String myInput
    ...
}
```

You will will get a validation error if the annotations are placed on a private getter and we will not discover the annotation on the field if there is no public getter.

What is the advantage for you to be able to annotate private fields without getter with the task input/output annotations?

**Comment by marcphilipp** [comment]
I think @larsgrefer's use case is similar to the Groovy one: He'd like to use Lombok to generate the getters for him. We had a discussion in https://github.com/marcphilipp/nexus-publish-plugin/pull/5#discussion_r232490815 about whether these annotations need to be on getters or fields.

**Comment by Lanchon** [comment]
note that javac replicates a method's annotations to its synthetic derivatives (eg: accessor methods of private methods to be invoked by inner classes). it may do the same for field annotations.

likewise, groovy **might** replicate a field's annotations to its getter, IDK.

now on to my issue....

> You will will get a validation error if the annotations are placed on a private getter

why??? this was totally ok on gradle 2. take a look at this code:

https://github.com/DexPatcher/dexpatcher-gradle/blob/v1.0.0/src/main/groovy/lanchon/dexpatcher/gradle/tasks/DexpatcherTask.groovy#L98-L99

the objective is to allow either one file or one directory as the property value, but only ONE value. there is no @InputFileOrDirectory annotation, and @InputFiles allows collections. in the general case, what is being done here is relying on standard property validation but with some preprocessing done before it. why was this deprecated? how should it be handled on gradle 5?
