### ISSUE TITLE
TestReport only generated if successful

### ISSUE THREAD

**Issue by PaulWoitaschek** [gradle/gradle#7727]
When running `TestReport`, the result is only created if the tests are all successful:

```groovy
tasks.register("allUnitTests", TestReport.class) {
  def dst = new File(rootDir, "/artifacts/")
  destinationDir(dst)
  reportOn("a:testUnitTest", "b:testUnitTest")
}
```

This kind of defeats the purpose of `TestReport`. I especially want the report if a test failed.
Tested using Gradle 4.10.2

**Comment by PaulWoitaschek** [comment]
To reproduce this, just let [CoreTest.java](https://github.com/gradle/gradle/blob/master/subprojects/docs/src/samples/testing/testReport/groovy/core/src/test/java/org/gradle/sample/CoreTest.java) fail.
```java
package org.gradle.sample;

import org.junit.Test;

public class CoreTest {
    @Test
    public void ok() {
        System.out.println("hello from CoreTest.");
        throw new AssertionError();
    }
}
```

Now a `gradle testReport` won't have any output.

**Comment by PaulWoitaschek** [comment]
Don't close this, this is important. We don't need reports for successful tests but for failed tests!

**Comment by n-hebert** [comment]
Hello.

My team also needs this. I'm busy working around this issue in my own scripts right now and anything I can spot is simply ugly.

I notice @ghale marked this as in testing, does that mean it's implemented?
If you'd like to show a branch where it's available to hack on that might help this as it's been open a long time and perhaps could use extra eyes + hands.

If not, could someone from the Gradle team contribute some hacking thoughts so that someone can start working on patching?
It would be very good to see some feedback from the Gradle team that this is in progress or desirable so if someone does go to the effort of putting in a PR it won't be turned down.

**Comment by n-hebert** [comment]
Hello,

I'm still interested in removing the trailing ` || ( echo "Failed build && ./gradlew testReport && exit 1)`  from my CI script's test build to work around this misfeature. 

Is there any Gradle team member who can weigh in on the value, timeline, requirements for a PR, etc.?
