### ISSUE TITLE
Instability in modules-2 metadata directory makes dependency caching difficult

### ISSUE THREAD

**Issue by jribe** [gradle/gradle#7750]
We cache the `${GRADLE_USER_HOME}/caches/modules-2` directory (and the jars-3 cache and wrapper dir) in our CI builds in order to reduce time spent fetching dependencies. Our current solution re-uploads cached directories if their contents have changed during the build. We are able to exclude the `*.lock` files from diffs and uploads, but `module-artifact.bin`, `module-versions.bin`, and `resource-at-url.bin` are problematic. Those files change on every build, but excluding them from the cache results in gradle re-downloading the world.

Ideally, these caches that contain large amounts of downloaded data would be designed such that they aren't modified unless the cache's contents have changed.

**Comment by oehme** [comment]
This is also commonly asked by TravisCI users.

**Comment by ljacomet** [comment]
The issue you face is that the files under `${GRADLE_USER_HOME}/caches/modules-<modulesversion>/metadata-<metadataversion>/*.bin` contain absolute paths _and_ are frequently updated since they are indexes to repository / module combinations.

If you were to cache instead `${GRADLE_USER_HOME}/caches/modules-<version>/files-<filesversion>` only, you would see much less changes.
These are the metadata and jar files required by Gradle without any absolute path information.

When running a build with that information copied over, your build will only issue `HEAD` requests to fetch the checksum of the files, then locate them in that cache.

**Comment by ljacomet** [comment]
You might be interested in watching to work done for #1338 

The `.bin` files are indeed quite volatile and expected to change often.
