### ISSUE TITLE
NoDaemon Java11 Openjdk Windows (persistentCache) fails on release branch

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#7811]
See https://builds.gradle.org/viewType.html?buildTypeId=Gradle_Check_NoDaemon_Java11_Openjdk_Windows_persistentCache&branch_Gradle_Check_NoDaemon_Java11_Openjdk_Windows=release&tab=buildTypeStatusDiv

@blindpirate investigated and confirmed it's another JDK argument file parser bug. Similar to https://bugs.openjdk.java.net/browse/JDK-8210810

**Comment by blindpirate** [comment]
I pushed a workaround https://github.com/gradle/gradle/commit/238bd408f99ee4da81a4090adf857db7ceeeb6ab by simply renaming the test case.

**Comment by ParkerM** [comment]
For those who may be googling, (and also for my own clarification), I assume this is what started causing this sudden `sealing violation: package jdk.internal.jimage is sealed` failure in the current release of openjdk11-openj9. Please correct me if I'm misguided.

Debug output in Gitlab CI with gradle 5.0-rc-5 and kotlin-dsl on the `adoptopenjdk/openjdk11-openj9:alpine-slim` image:

```sh
./gradlew assemble --stacktrace --debug --scan
...
02:32:43.132 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:32:47.520 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Load build' completed
02:32:47.537 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Could not open cache directory 4x2w3na12fz5beul6a9kbeu76 (/builds/my/package/.gradle/caches/5.0-rc-5/gradle-kotlin-dsl/4x2w3na12fz5beul6a9kbeu76).
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > sealing violation: package jdk.internal.jimage is sealed
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Try:
02:32:47.538 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]  Run with --scan to get full insights.
02:32:47.540 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
02:32:47.541 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
02:32:47.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.cache.CacheOpenException: Could not open cache directory 4x2w3na12fz5beul6a9kbeu76 (/builds/builds/my/package/.gradle/caches/5.0-rc-5/gradle-kotlin-dsl/4x2w3na12fz5beul6a9kbeu76).
02:32:47.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:80)
02:32:47.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.open(DefaultPersistentDirectoryStore.java:42)
02:32:47.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheFactory.doOpen(DefaultCacheFactory.java:94)
02:32:47.547 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheFactory.open(DefaultCacheFactory.java:68)
02:32:47.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.cache.internal.DefaultCacheRepository$PersistentCacheBuilder.open(DefaultCacheRepository.java:117)
02:32:47.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.kotlin.dsl.cache.ScriptCache.cacheDirFor(ScriptCache.kt:67)
02:32:47.548 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.kotlin.dsl.provider.StandardKotlinScriptEvaluator$InterpreterHost.cacheDirFor(KotlinScriptEvaluator.kt:253)
...
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.lang.SecurityException: sealing violation: package jdk.internal.jimage is sealed
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider$JrtFsLoader.loadClass(JrtFileSystemProvider.java:147)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.jrtfs.SystemImage.open(Unknown Source)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.jrtfs.JrtFileSystem.<init>(Unknown Source)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(Unknown Source)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:127)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at java.base/jdk.internal.jrtfs.JrtFileSystemProvider.newFileSystem(JrtFileSystemProvider.java:106)
02:32:47.595 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	at org.jetbrains.kotlin.cli.jvm.modules.CoreJrtFileSystem$handlers$1.fun(CoreJrtFileSystem.kt:40)
...
```

**Comment by blindpirate** [comment]
@ParkerM I'm afraid the problem you encountered has nothing to do with this issue. This issue (#7811) is simply caused by https://bugs.openjdk.java.net/browse/JDK-8210810 (I'm 100% sure because I submitted this bug report and I [fixed this issue for JDK](https://bugs.openjdk.java.net/browse/JDK-8210810)). I have no idea what's going on with your project, but it can't be https://bugs.openjdk.java.net/browse/JDK-8210810 because it only happens on Windows.

It would be great if you can create a reproducible sample of your problem. We'd be glad to investigate and fix it (if it's a bug).

**Comment by ParkerM** [comment]
Example here with gradle 5.0: https://travis-ci.com/ParkerM/gradle-jdk11openj9-bug
Docker for windows gives the same error seen in Travis CI here: https://travis-ci.com/ParkerM/gradle-jdk11openj9-bug/builds/92637796

**Comment by blindpirate** [comment]
@ParkerM seems like it's a bug in `openjdk11-openj9:jdk-11.0.1.13-alpine-slim`. I've created an issue https://github.com/AdoptOpenJDK/jitwatch/issues/293

**Comment by ParkerM** [comment]
@blindpirate Awesome reproduction! I've been messing with different configurations for a while and have been able to consistently reproduce the error among different images. (typically the `jdk.internal.jimage is sealed` error, though it does change under certain circumstances. See the [build history](https://travis-ci.com/ParkerM/gradle-jdk11openj9-bug/builds) for examples of this error.)

I tried using [phusion/baseimage](https://github.com/phusion/baseimage-docker) with the jdk11-openj9 binaries from AdoptOpenJDK and got the exact same error for the project. I then tried compiling from sources in `phusion/baseimage` using the instructions from eclipse.org [here](https://www.eclipse.org/openj9/oj9_build.html#version-11), cleaned up and rebuilt the image using my generated release and still got the exact same error. I tried with `-Xint` to rule out JIT/AOT issues and got the same results, only in slow motion. I can't seem to reproduce the error outside of docker.

The hotspot image also threw an error around the same execution stage when I tried it, so it's difficult to determine if the issue lies with gradle/kotlin-dsl, openj9, or jdk11 in general (or perhaps a profound case of PEBKAC). The official Oracle JDK image seemed to work fine when I tried it for a sanity check. The strange occasional changes in the thrown error are what sort of made me think it could be related to the classpath issue.

If you end up locating the correct location for the issue please let me know and I can add any context if needed. Apologies for the noise.

**Comment by blindpirate** [comment]
Here it is: https://github.com/AdoptOpenJDK/openjdk-docker/issues/87
