### ISSUE TITLE
BasePlugin calls configurations.all, making it impossible to use `configurations.register()` efficiently

### ISSUE THREAD

**Issue by JamesXNelson** [gradle/gradle#7830]
I am writing a plugin which allows users to easily added extra source sets, with publishing and other goodies wired up "for free".  To make this easier for user, I want to detect when they actually use some special-named configuration, but the BasePlugin [is using configurations.all](https://github.com/gradle/gradle/blob/master/subprojects/plugins/src/main/java/org/gradle/api/plugins/BasePlugin.java#L169), making lazy resolution impossible.

### Expected Behavior
Instead use .configureEach, to avoid eager resolution.

### Current Behavior
BasePlugin uses configurations.all(), preventing work avoidance.

### Context
I can probably work around this with my own state machina, but would much rather avoid that complexity.  Note that SourceSets are, likewise, eagerly resolved.  Removing this eager resolution might cause some downstream breakage, but no time like a major version increment to do so!

// Remaining template items elided for brevity

**Comment by big-guy** [comment]
Yes, this is something we should fix, but this is too late for 5.0.

You should only really use register for tasks right now.

**Comment by JamesXNelson** [comment]
Ok, no worries.  I have np switching to nightlies, or even putting together a patch if you'd like.

**Comment by big-guy** [comment]
The problem isn't so much that we need to switch things from `all {}` to `configureEach {}`, but we also need to provide a way to express "the contents of this container is determined by the contents of this other container" or "this value in this container needs the value(s) from this other container". If we just switch `all {}` to `configureEach {}`, things will break. 

`Configuration` was high on the list to tackle after tasks because they're relatively expensive to create and would drive solutions for that sort of problem.

One things to keep in mind is that for many containers, like source sets, we're likely to fully realize them anyways because they're needed for determining which tasks are available.

**Comment by JamesXNelson** [comment]
Ok, thank you for the detailed explanation.  

In building my own layer around this, it's clear that it's much more complex than I expected.

Feel free to close the issue unless you actually want to edit/keep it around to track progress on making `Configuration` lazy.  I'll work under the assumption that I can get lazy resolution on Configuration later, and just give user some explicit dsl that can become implicit later.
