### ISSUE TITLE
ClassNotFoundException when resolving cached task results using Gradle daemon

### ISSUE THREAD

**Issue by lacasseio** [gradle/gradle#784]
_This bug have been reproduced and confirmed_

### Expected Behavior
Succeed

### Current Behavior
Reported on the [forum](https://discuss.gradle.org/t/3-2rc1-classnotfoundexception-resolving-cached-task-results-using-gradle-daemon/20228/1).

### Context
Invoking a project with a custom `Serializable` class as input to a task will cause an exception on the second time the project in invoked. The task disable up-to-date check.

### Steps to Reproduce (for bugs)
Code sample can be found [here](https://github.com/bs-git/gradle-classnotfound-test).

### Your Environment

 * Build scan URL:

**Comment by lacasseio** [comment]
Work was spent trying to find the root of the issue as well as creating a simple test case. Commit 13e7c86 summarize the work. It seems to be an issue with deserializing a custom `Serializable` class as input from cache.

**Comment by lhotari** [comment]
This is likely to be caused by the changes made to fix https://issues.gradle.org/browse/GRADLE-3537

**Comment by lacasseio** [comment]
@lhotari You are right and it is related in part to this issue. I simplified my test case and will start looking in Gradle class loaders.

**Comment by adammurdoch** [comment]
The value for a task property can come from pretty much any ClassLoader, so fixing this by mixing together 2 hard coded ClassLoaders is a partial solution. It also introduces issues where a class with the same name is present in both places.

I can see 3 potential solutions:

1. When creating a cache entry, store the _serialized_ binary value for each property in the cache entries, rather than the value itself. When comparing a property value against a new value to check if it has changed, deserialize the binary value from the cache entry using the ClassLoader of the new value and use `equals()` on the result.
2. Attach a logical id to each ClassLoader that Gradle creates. When creating a cache entry, store the serialized binary value for each property along with the id of the ClassLoader for the value. When comparing the property value against a new value, deserialize the binary value using the ClassLoader with the associated id.
3. Store the serialized binary value for each property in the cache entries. When comparing a property value against a new value, serialize the _new value_ and compare the resulting binary values. Deprecate using a property value with a custom `equals()` method.

**Comment by adammurdoch** [comment]
Option #3 is essentially the one that will be used when locating entries in the task output cache. It's probably not a great idea to use different approaches for the various kinds of output caching.

**Comment by lacasseio** [comment]
This limitation is quite tricky to solve. I [committed a new patch](https://github.com/gradle/gradle/commit/99747c0b59b9919b24f22fd72de1187fcb9e726e) with a new direction to solve this issue.

In a nutshell, this issue worked previously as it would simply grab the classloader for the current task class which happens to be the build script classloader where the serialized type is declared. The change in Gradle 3.2 fixed the scenario where the class was a Gradle core type and the serialized type was declared in `buildSrc`. In this case, we would be getting the core classloader (through the task class) that have no knowledge of the `buildSrc` and build script declared types. The solution would get the project level class loader. However, this class loader doesn't have any knowledge of the build script declared types. In order to solve this limitation while honoring the previously fixed use case.

Without any change to the local caching system, using the build script classloader directly would solve this problem. The problem I'm having is this classloader isn't referenced anywhere. Commit 99747c0b59b9919b24f22fd72de1187fcb9e726e try to expose the classloader by making a distinction between attaching the script to the `ProjectInternal` instance and setting the script. Once the script is set to the `ProjectInternal` instance, it can be retrieved later. The part I'm uneasy with is the special handling for when the build script is empty.

**Comment by big-guy** [comment]
@lptr Do you have any insight on this? It seems like this would affect our handling of serializable properties for up-to-date checks/caching.

**Comment by lptr** [comment]
What happens if you remove the previous enum value? Can you deserialize value `SomeEnum.FOO` if the enum via the build script classloader is declared as `enum SomeEnum { BAR, BAZ }`?

**Comment by lacasseio** [comment]
@lptr Touché! Thanks @bamboo, @adammurdoch and @lptr for helping me to see the various limitation with the proposed solution. I opened issue gradle/gradle#919 to address option 3 from the proposition above. I will mark this issue as blocked. We will discuss this further to prioritize this work.

In the meantime, the proposed workaround are:
- Move any custom `Serializable` type captured as task input inside `buildSrc` to expose them to the project's `ClassLoader`.
- Remove unused task input capturing from custom task class definition **only if it make sense**.

**Comment by bmuschko** [comment]
Same [issue was reported](https://github.com/bmuschko/gradle-cargo-plugin/issues/154) by a user of one of my plugins.

**Comment by lacasseio** [comment]
@adammurdoch It seems this was fixed with your work around `ValueSnapshot` (https://github.com/gradle/gradle/commit/ee61d0038ab42ea1f838e66e25578c96389f73b0) in Gradle 3.4. Can you confirm it's the expected behavior so we can close this issue?

**Comment by lacasseio** [comment]
I'm closing this issue as it seems fixed in Gradle 3.4. Please reopen if you get that problem again.
