### ISSUE TITLE
AspectJ Plugin not Working in Gradle 5.0

### ISSUE THREAD

**Issue by dbuos** [gradle/gradle#7861]
Error in aspectj compilation after upgrade to gradle 5.0 in spring security project.

### Expected Behavior
Build executed successfully 

### Current Behavior
Build failed with error 
```
Some problems were found with the configuration of task ':spring-security-aspects:compileJavaAspect'.
> No value has been specified for property 'options.extensionDirs'.
> No value has been specified for property 'options.encoding'.
> No value has been specified for property 'options.debugOptions.debugLevel'.
> No value has been specified for property 'options.forkOptions.executable'.
```

### Context
I'm [trying](https://github.com/spring-projects/spring-security/issues/6148) to update [spring-security](https://github.com/spring-projects/spring-security) to gradle 5.0 but after applying the change, the build of aspectj not work anymore 

### Steps to Reproduce (for bugs)
Upgradle gradle version to 5.0 of a project that uses aspectj plugin as in this [commit](https://github.com/dbuos/spring-security/commit/05771794160723aa837af61c9b601145859c355a) 

###  Environment

 * Build scan URL: https://scans.gradle.com/s/gnwb7z3qwgzjw

**Comment by big-guy** [comment]
I believe this is because the `Ajc` task has registered inputs that were invalid, but Gradle previously ignored them/did not validate them.

This is copying all properties from `compileJava` to `compileJavaAspect`:
https://github.com/dbuos/spring-security/blob/master/buildSrc/src/main/groovy/aspectj/AspectJPlugin.groovy#L51

Gradle doesn't allow properties to have non-null values in 5.0.  What can happen is if `compileJava` has an optional property that's null that will get copied to `compileJavaAspect` as a _required_ property. 

The fix is to only add properties that are required by the Ajc task. It might be better/easier to see if there's a new plugin that does this for you. https://plugins.gradle.org/search?term=aspectj

**Comment by dbuos** [comment]
@big-guy Thanks a lot! I do filter the props in order to copy only not null values and it's working now
