### ISSUE TITLE
Checkstyle task is unstable at scale

### ISSUE THREAD

**Issue by mockitoguy** [gradle/gradle#7867]
### Problem

At LinkedIn we found Checkstyle task unstable, causing Gradle to crash (daemon disappears) roughly 1/10K invocations in various projects. We created our own "forked checkstyle" but it added complexity that has been causing maintenance ever since. We found that invoking Checkstyle in a separate jvm (calling Checkstyle "main" class, not ant task) resolves the crashing issue.

### Suggested solution

Let's get Checkstyle task use Worker API instead of IsolatedAntBuilder. Is Gradle team ok with this? We can try to put together a PR but first we want to know if this would be a desired change.

Related ticket: #1157

**Comment by big-guy** [comment]
This is a good idea @mockitoguy.  We don't need an IsolatedAntBuilder for this to work, I think.

- Add checkstyle 7.0 as a compileOnly dependency to codeQuality
- Create a new `CheckstyleRunnable` that can be fed to a `WorkerExecutor` that calls Checkstyle's main method. It can build up the command-line arguments based on what you already have.
- You can either pass all the appropriate arguments to `CheckstyleRunnable` or package them all up into a `CheckstyleSpec` that represents the configuration. It depends on how complicated it all is.
- We can get rid of the `CheckstyleInvoker`

I think this should be invisible to users as long as calling the main method is about the same as the Ant task.

We won't be able to push this into the next release (5.1), but let us know when you think you may start on it.

**Comment by mockitoguy** [comment]
I'll take a stab at it. Let's see how it goes. 5.2 release will work. Thank you for design tips!

**Comment by mockitoguy** [comment]
This is tricky. Checkstyle main calls System.exit(). I've tried to work around it using SecurityManger but it did not work for me. I opened a ticket in Checkstyle project: https://github.com/checkstyle/checkstyle/issues/6234

@big-guy, 2 questions:
a) have you had this use case before? Worker API calling 3rd party code that calls System.exit().
b) would you consider using project.javaExec() instead of the worker API?

**Comment by big-guy** [comment]
Ah, you're right.

Another approach would be to steal bits out of the Ant task.  Maybe Checkstyle has a more programmatic API you could use that way:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java#L301

A plan B could be `javaexec`.  The worker API has other advantages in that we'd start running multiple checkstyle tasks at once.

**Comment by romani** [comment]
>At LinkedIn we found Checkstyle task unstable

Please share details.

>We created our own "forked checkstyle" 

Please provide link to review changes

>Let's get Checkstyle task use Worker API instead of IsolatedAntBuilder.

Ant integration in hosted in checkstyle repo/jar only for historical reasons, no reason to use it. There are ways to use checkstyle API directly, please review maven or eclipse plugin for details, or checkstyle's Main class.

**Comment by DPUkyle** [comment]
Based on comments on checkstyle/checkstyle#6234, I dug through the `maven-checkstyle-plugin`'s source to see how it avoids the `System#exit()` call; it turns out that invoking `com.puppycrawl.tools.checkstyle.Checker` might be the key: [Usage in CheckstyleExecutor](https://gitbox.apache.org/repos/asf?p=maven-checkstyle-plugin.git;a=blob;f=src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java;h=dcf3fba6e3c1bb17399d3a86f43c0355f77c2f99;hb=HEAD#l248)

**Comment by romani** [comment]
If we want to succeed to make smth in good form, please invite us on review of design and implementation, we might provide some advices.
Maven plugin might be most close implementation of what you need, eclipse-cs project has deeper integration.
It might be good to update https://github.com/sevntu-checkstyle/checkstyle-samples to show user more examples of Gradle.

**Comment by mockitoguy** [comment]
@big-guy, using Checkstyle Java API has higher risk of getting incompatible changes because Checkstyle does not have semver Java API. Do you think calling main() would be OK for you? I've also asked Checkstyle folks (https://github.com/checkstyle/checkstyle/issues/6234#issuecomment-445405153).

**Comment by big-guy** [comment]
IMO, the Checkstyle Java API is probably going to be better in the long run, even if it's a little harder to keep compatible between versions. If it's anything like the Ant task, I don't think we had very many problems with keeping it working across a wide range of Checkstyle versions.

**Comment by romani** [comment]
Reason of not following server - https://checkstyle.org/#Development_Cycle :( .

Please try to avoid reusage of Ant task, we still have plans to move it separate project/jar , to make checkstyle more modular and easy to embed.

In our plans for Api related changes https://github.com/checkstyle/checkstyle/issues?q=is%3Aopen+is%3Aissue+label%3Acheckstyle8
Most of changes are for custom Checks implementations, not for execution in general.

>I don't think we had very many problems with keeping it working across a wide range of Checkstyle versions.

I could suggest to appear your plugin in our CI as integration tests, so we will be aware of damages on moment of PR to us, so at least we can discuss a way to ease problems at plugin.

**Comment by romani** [comment]
example of who is using our CLI:
android team - https://android.googlesource.com/platform/prebuilts/checkstyle/+/master/checkstyle.py#177 and we never changed such CLI parameters.

>  At LinkedIn, we will stick to a single version of Checkstyle for foreseeable future, upgrading very infrequently

damage from API is really minor, each out new release can fail your CI, as we might fixed a bug  and now Check find +100 violations. So users stay on old versions usually because they can not afford to update codebase to fix new violations. 

----

The good idea for plugin to clearly define what version of checkstyle it supports (and if it possible change version of checkstyle):
https://github.com/checkstyle/sonar-checkstyle#description--features
https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html
Users might want to use plugin latest version , but not the latest checkstyle version.

**Comment by big-guy** [comment]
> > IMO, the Checkstyle Java API is probably going to be better in the long run

> I'm curious why?

If you're forced to use the `Main`/CLI interface and run Checkstyle with `javaexec`, then that's going in the opposite direction than we want to go. It's also going to be much harder to get any structured data out of the result of the Checkstyle run (beyond good/bad + some output scraping). If we use the API, we can always make something work for at least particular versions of Checkstyle and we're more likely to notice something isn't quite right when we upgrade.

Looking at the reasons for not following semver, my biggest takeaway is that they don't feel like they have a very good separation of their API or how to manage changes to it without breaking lots of things. And in some cases, they need to break things to improve. I think there are really many different APIs:
- Checkstyle XML configuration
- Checkstyle "Checker" API (that Maven uses)
- Checkstyle Ant task
- Checkstyle CLI
- Checkstyle plugin/check API

So far, we've been using the "Ant task" API and it's been slow to change and hasn't been a burden to maintain. I'll grant you that the "Checker" API is likely harder to maintain, but it looks like what is needed here. We don't care about the XML configuration or plugin/check APIs, but I think those all contribute to "what's the version of Checkstyle?" that Checkstyle needs to worry about.

The oldest version we currently support is 5.9 and we default to use 8.12. We test against 5.9, 6.2, 6.9, 6.12, 7.0, 7.6 and 8.12. It looks like the Maven plugin is built against 6.2? and works all the way up to 8.12 with few changes.

I would suggest something like this:
- Pick a reasonably recent version (e.g., 7.0) of Checkstyle. Compile against that.
- For any versions older than that, use the current Ant task invoker. Add a deprecation warning.
- For any versions newer than that, we have a `Checker`-driven runnable that can be fed to the worker API.
- Expand test coverage for a few more versions using the "new" way.

We try to bump the versions of our default tools every release, but if something is a little harder to do, then it'll be delayed. This means, at worst, we'll fall into the same situation as the Maven plugin. We'll support a particular version and maybe nothing newer if it's too hard to update. Since we use Checkstyle, I think we have some incentive to keep it working. I don't have any expectations that you're on the hook to provide future updates.

I think we want to execute `Checker` in a way similar to:
https://github.com/checkstyle/checkstyle/blob/master/src/main/java/com/puppycrawl/tools/checkstyle/Main.java#L330-L397

I think we don't need any classloader magic because all of that is done for you when Gradle runs the worker API's runnable.

**Comment by mockitoguy** [comment]
@big-guy, thank you! The plan makes perfect sense. I wanted to make sure we nail down the high level approach before we code it. I'll start working on it.

**Comment by romani** [comment]
@big-guy ,

> If we use the API, we can always make something work for at least particular versions of Checkstyle and we're more likely to notice something isn't quite right when we upgrade.

Lets cooperate on this.  Please give us a project that use checkstyle and report error violations is any appear and where we can substitute version of checkstyle by some bash command. We will use such project in our PullRequest integration testing.
This will let us catch braking compatibility before we merge damaging changes. CI will fail, so no merge happen.
Benefit for you: we will try to not damage if possible, we/you will be alarmed in advance, we give guidance on how to upgrade if change must happen.
Please create issue in our repo to discuss details if you are interested.

> And in some cases, they need to break things to improve. I think there are really many different APIs

yes.

> So far, we've been using the "Ant task" API and it's been slow to change

if you know how to improve it - you are welcome.
We just do not have much users of them.

>  I'll grant you that the "Checker" API is likely harder to maintain, but it looks like what is needed here

we know about this ... and we try to not change it if possible.

> It looks like the Maven plugin is built against 6.2?

6.18 - https://maven.apache.org/plugins/maven-checkstyle-plugin/history.html
but Checkstyle is already at 8.14, with 2.5 year in front.
BUT it is compatible with 8.14 and we use maven plugin in our integration testing (only changes in pom.xml is required https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/upgrading-checkstyle.html).

> Pick a reasonably recent version (e.g., 7.0) of Checkstyle. Compile against that.

it is better to consider history of AntTask - https://github.com/checkstyle/checkstyle/commits/master/src/main/java/com/puppycrawl/tools/checkstyle/ant/CheckstyleAntTask.java
here is breaking changes that we did at 8.0 - https://github.com/checkstyle/checkstyle/issues/4449
I am not sure how your plugin is affected by this. But is better to consider history of AntTask to make a decision on what version to choose.
Please beware that we switched to jdk8 at http://checkstyle.sourceforge.net/releasenotes.html#Release_7.0
