### ISSUE TITLE
Only set newest version as default in SDKman when releasing Gradle

### ISSUE THREAD

**Issue by vpavic** [gradle/gradle#7921]
### Expected Behavior

Upgrade of SDKMAN candidates shouldn't offer `4.10.3` as an upgrade over `5.0`.

### Current Behavior

Upgrade of SDKMAN candidates offers `4.10.3` as default candidate (and thus upgrade over `5.0`).

### Context

n/a

### Steps to Reproduce (for bugs)

```bash
$ sdk ug
==== BROADCAST =================================================================
* 05/12/18: Gradle 4.10.3 released on SDKMAN! #gradle
* 04/12/18: Grails 3.3.9 released on SDKMAN! #grailsfw
* 03/12/18: Vertx 3.6.0 released on SDKMAN! #vertx
================================================================================

Upgrade:
gradle (4.10.2, 5.0 < 4.10.3)

Upgrade candidate(s) and set latest version(s) as default? (Y/n):
```

### Your Environment

 * Build scan URL: n/a

**Comment by big-guy** [comment]
Ah, this is not intended.

@jjohannes @wolfs is this something you could look into?  I think we just want to put 5.0 as the default version again: https://sdkman.io/vendors#endpoints

**Comment by marc0der** [comment]
You will need to use `sdkDefaultVersion` in addition to the `sdkReleaseVersion` task in your release pipeline. This has always worked for Gradle GA builds up to now.

All the details about our release plugin are on the vendors page of our site:
https://sdkman.io/vendors

**Comment by wolfs** [comment]
I saw that we run `sdkMajorRelease` as part of the final release build, which sets the default version. The difference this time is that we did a final release with a smaller version (`4.10.3`) after the next version (`5.0`) already has been out.

**Comment by vpavic** [comment]
IMO your release build should somehow be aware which _MAJOR.MINOR_ represents the current release, and use `sdkDefaultVersion` conditionally on that fact.

**Comment by jjohannes** [comment]
We had the same situation with 4.0 and 3.5.1. Back then we explicitly excluded the `sdkDefaultVersion ` task from the release build for 3.5.1. But we forgot to do that this time.

So there are two things to do:
- fix the situation we have right now by manually triggering `sdkDefaultVersion ` for 5.0 again 
- do something like what @vpavic suggests so that this won't happen again in the future

**Comment by blindpirate** [comment]
Fixed by manually setting default version to `5.0`:

```
# zhb @ bs-MacBook-Pro in ~ [20:37:58] C:130
$ sdk current

Using:

gradle: 5.0

# zhb @ bs-MacBook-Pro in ~ [20:38:07]
$ sdk ug

All candidates are up-to-date

# zhb @ bs-MacBook-Pro in ~ [20:38:16]
$ sdk upgrade gradle

gradle is up-to-date
```

Leave this issue open to track the improvement.

**Comment by blindpirate** [comment]
However, `sdkDefaultVersion` is a part of `sdkMajorRelease` which can't be turned off partially: https://github.com/sdkman/sdkman-vendor-gradle-plugin/blob/23cfaee1dbcdecd62d325809a00c89e79f8129e5/src/main/groovy/io/sdkman/vendors/SdkMajorRelease.groovy#L15

I guess we should conditionally switch to [`sdkMinorRelease`](https://github.com/sdkman/sdkman-vendor-gradle-plugin/blob/23cfaee1dbcdecd62d325809a00c89e79f8129e5/src/main/groovy/io/sdkman/vendors/SdkMinorRelease.groovy#L3) which only do releasing and annoucing, no defaulting:

- If current releasing version is newer than latest released version, call `sdkMajorRelease`.
- Otherwise, call `sdkMinorRelease`.

**Comment by blindpirate** [comment]
Thanks @marc0der @vpavic !
