### ISSUE TITLE
Scheduled artifact transform fails with "Transformation hasn't been executed yet"

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#7950]
For a scheduled artifact transform, if the first transform in a chain fails, the whole build fails with `Transformation hasn't been executed yet` without any further context.

See e.g. https://issuetracker.google.com/120461540.

The build should not fail but instead, when the transformed configuration is resolved, the failure of the first transform should be reported with enough context to know what has been transformed.

**Comment by wolfs** [comment]
This line seems to be the culprit: It sets `result` to `operation.getResult()`, even though this is null in case of failure: https://github.com/gradle/gradle/blob/ada368dc98746cccfa450918b2a3cf91adb3abfe/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/transform/TransformInfo.java#L191

This has already been fixed for 5.1 and we now have a test verifying that it keeps working: https://github.com/gradle/gradle/blob/4d88e6fda1cfcf3cfb85e8cb1e953bd908074c0a/subprojects/dependency-management/src/integTest/groovy/org/gradle/integtests/resolve/transform/ArtifactTransformCachingIntegrationTest.groovy#L834-L900

**Comment by hungvietnguyen** [comment]
According to https://issuetracker.google.com/119951660#comment10, this issue is not yet completely fixed in Gradle 5.1 and 5.2 nightly.

The stack trace looks slightly different, but the error message remains the same:

```
java.lang.IllegalStateException: Transformation hasn't been executed yet
        at org.gradle.api.internal.artifacts.transform.TransformationNode.getTransformedSubject(TransformationNode.java:66)
        at org.gradle.api.internal.artifacts.transform.TransformationNode.access$400(TransformationNode.java:38)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ChainedTransformationNode$1.describeSubject(TransformationNode.java:181)
        at org.gradle.api.internal.artifacts.transform.TransformationNode$ArtifactTransformationStepBuildOperation.description(TransformationNode.java:200)
        ...
```

I've asked the user to provide a sample project, but hopefully the above can already give some clues.

**Comment by carlonzo** [comment]
Here I finally managed to create [a sample project](https://drive.google.com/file/d/1PIGzMl2IlhMcpD688viSRYsefoLb-hM6/view?usp=sharing). 

The issue is with the plugin from NewRelic applied (they run a transformation which I believe breaks), android multidex enabled (I cant understand why) and Jetifier (the androidx transformation)
To reproduce the issue you need to run:
`./gradlew :app:generateDebugSources :app:compileDebugSources --stacktrace` (both tasks together.
CC @hungvietnguyen

**Comment by carlonzo** [comment]
@wolfs as you closed this ticket, should I open a new one?

**Comment by hungvietnguyen** [comment]
I think there are 2 issues in this case:
- Transform failures need a clearer error message. I've filed https://github.com/gradle/gradle/issues/8250.
- The root cause of the failure appears to be a Gradle bug. I've filed https://github.com/gradle/gradle/issues/8253.
