### ISSUE TITLE
gradle opens thousands of files and exceeds the file limit

### ISSUE THREAD

**Issue by yurivict** [gradle/gradle#7973]
Project using gradle: https://github.com/broadinstitute/gatk
Most likely you forget to close files.

Version: gradle-4.6

Gatk report: https://github.com/broadinstitute/gatk/issues/5499

Failure log: http://beefy11.nyi.freebsd.org/data/head-i386-default/p486731_s341608/logs/gatk-4.0.11.0.log

OS: FreeBSD

**Comment by oehme** [comment]
The issue is unlikely to be in Gradle itself, as we have thousands of tests verifying that Gradle and its core plugins do not leak files. However, the build you linked uses a highly outdated Gradle version (3.1). So the first step should be upgrading to Gradle 4.10.3 or 5.0.

If the problem persists, please use the [file-leak-detector](http://file-leak-detector.kohsuke.org/) on your build. If the leak is actually in Gradle, please attach the leak report.

**Comment by yurivict** [comment]
This happens with gradle-4,6.
