### ISSUE TITLE
getCandidateClassFiles doesn't work

### ISSUE THREAD

**Issue by quentinflahaut** [gradle/gradle#8093]
Gradle v5

my project contains this:
```
sourceSets {
    main {
        java {
            srcDirs = ['src/main/java']
        }
    }
    test {
        java {
            srcDirs = ['src/test/java']
        }
        resources {
            srcDirs = ['src/test/resources']
        }
    }
}
```
I have severals test class in my src/testjava folder 

In my gradle.properties, `test.getCandidateClassFiles().size()` return 0
Here is the gradle code of the method:
```
public FileTree getCandidateClassFiles() {
        return getTestClassesDirs().getAsFileTree().matching(patternSet);
    }
```
I did further investigation and I got this:
`println test.getTestClassesDirs().getFiles()`

> [C:\ng\src\svn\platform\apollo\apollo-core\sparql-processing\build\classes\java\test]

`println test.getTestClassesDirs().getAsFileTree().getFiles()`

> []

However the result should be the same.

**Comment by big-guy** [comment]
@quentinflahaut We need a little more context with what you're trying to do and what's not working.

Our forums are a better place to get help https://discuss.gradle.org/ or our Slack instance https://discuss.gradle.org/t/introducing-gradle-community-slack/26731

> I did further investigation and I got this:
>> println test.getTestClassesDirs().getFiles()
>> [C:\ng\src\svn\platform\apollo\apollo-core\sparql-processing\build\classes\java\test]
> 
>> println test.getTestClassesDirs().getAsFileTree().getFiles()
>> []
>
> However the result should be the same.

These should not be the same.  The first one is printing a flat list of files (`testClassesDirs` is a collection of directories, so this will only be the roots) and the other is printing a tree of files.  `getAsFileTree` creates a `FileTree`, which walks the directories and gathers all of the subdirectories/files.  Since the directories are all empty, you get nothing back.
