### ISSUE TITLE
Module's source code (annotation) no longer used as testAnnotationProcessor for its test?

### ISSUE THREAD

**Issue by wisechengyi** [gradle/gradle#8110]
I ran into this issue trying to upgrade gradle from 4.10.2 to 5.0.

### Given a project as follows

```bash
A/src/main/MyImplAnnotation.java
A/src/test/MyObject.java // relies on `MyImplAnnotation.java` to generate `MyObject_Impl.java`
A/src/test/Test.java // does something with `MyObject_Impl`
```

For Gradle < 5.0, this works.

For 5.0+, there would be a ClassNotFound error on `MyObject_Impl` because project's source code does not seem to/cannot be used as annotation anymore for test sources.

Could you kindly clarify whether this is the expected behavior or a bug?

### Workaround 

My current workaround is to move the tests into a separate module `B` as follows:
```
A/src/main/MyAnnotation.java
B/src/test/MyObject.java // relies on `MyAnnotation.java` to generate `MyObject_Impl.java`
B/src/test/Test.java (does something with `MyObject_Impl`)
```
Then have `B`'s `build.gradle` contain:
```
testAnnotationProcessor project('A')
```

**Comment by tbroyer** [comment]
I believe this is because `testAnnotationProcessor` is empty. In 4.10, `compileTestJava.options.annotationProcessorPath` would then default to the `testCompileClasspath`, which would then include the annotation processor from the _main_ source set. In 5.0 though, this fallback no longer happens, so the tests are compiled without any annotation processor.

You'd want to have `testAnnotationProcessor` extends `runtimeClasspath` or `testImplementation`; or something like that.

**Comment by wisechengyi** [comment]
Thanks @tbroye! That seems to do the trick.

I'd still like someone from gradle to clarify whether this is intended tho.

**Comment by oehme** [comment]
Yes, this intended, Gradle ignores annotation processors on the compile classpath.
