### ISSUE TITLE
Annotation Processor cannot read version

### ISSUE THREAD

**Issue by nieqiurong** [gradle/gradle#8124]
When I imported BOM using enforcedPlatform, annotation Processor could not get the version, and it was normal to use API or implementation.
`
    implementation(enforcedPlatform("org.springframework.boot:spring-boot-dependencies:2.1.0.RELEASE"))
    annotationProcessor 'org.springframework.boot:spring-boot-configuration-processor'
    api 'org.springframework.boot:spring-boot-autoconfigure'
    api 'org.springframework.boot:spring-boot-starter-jdbc'
`
![image](https://user-images.githubusercontent.com/15142701/50511289-024f5000-0ac8-11e9-94e7-bbf256048540.png)
![image](https://user-images.githubusercontent.com/15142701/50511364-52c6ad80-0ac8-11e9-946c-d9602c218997.png)

**Comment by tbroyer** [comment]
You imported the BOM in the `implementation` configuration, and `annotationPRocessor` configuration is completely separate, so the dependency constraint doesn't apply (it does apply **in this case** to the dependencies declared in `api` configuration, despite `implementation` extending `api` –and not the other way around, so no _inheritance_– because, I believe, the configuration actually resolved here is `compileClasspath`, which extends `implements` and encompasses both configurations, applying the constraints coming from `implementation` to the dependencies coming from `api`)

You'd need to **also** import the BOM to any `annotationProcessor` configuration (`testAnnotationProcessor` possibly, etc.) where you use that annotation processor.
