### ISSUE TITLE
IncludeBuild cause dependencies to be resolve during configuration time

### ISSUE THREAD

**Issue by Jonatha1983** [gradle/gradle#8174]
IncludeBuild cause dependencies to be resolve during configuration time.

### Expected Behavior
Dependencies resolution should be in execution phase even in a composite build.

### Current Behavior
When including (even an empty) project with includeBuild  dependencies are resolved during configuration time. 

During Configuratoin: 
![image2019-1-4_13-26-32](https://user-images.githubusercontent.com/3816566/50781620-86ff5280-12ae-11e9-944a-03ca0091bb42.png)

![image2019-1-4_13-23-51](https://user-images.githubusercontent.com/3816566/50781623-88c91600-12ae-11e9-9c9e-ef37c4f5832e.png)

During Execution
![image2019-1-4_13-26-2](https://user-images.githubusercontent.com/3816566/50781649-9d0d1300-12ae-11e9-89f7-25aa6f7aaec0.png)
![image2019-1-4_13-26-53](https://user-images.githubusercontent.com/3816566/50781654-9ed6d680-12ae-11e9-963c-5cf4f9919e93.png)

### Steps to Reproduce (for bugs)

settings.gradle
`rootProject.name = 'myProject'
// uncoment to see the resolution during configuratoin 

 //includeBuild 'includeBuildFolder'
`

build.gradle
`plugins {
    id 'java'
}
 
repositories { jcenter() }
 
configurations { myConfig }
 
Dependency[] dep = []
 
dependencies {
    myConfig 'org.apache.commons:commons-collections4:4.1'
    myConfig 'org.apache.commons:commons-collections4:4.1:sources'
    myConfig 'org.apache.commons:commons-math3:3.5'
    myConfig 'org.apache.commons:commons-math3:3.5:sources'
    myConfig 'commons-lang:commons-lang:2.6'
    myConfig 'commons-cli:commons-cli:1.4'
    myConfig "net.wimpi:jamod:1.2"
    myConfig "net.wimpi:jamod:1.2:sources"
    myConfig 'org.glassfish.jersey.core:jersey-client:2.22.1'
    myConfig 'org.glassfish.jersey.containers:jersey-container-jdk-http:2.22.1'
    myConfig 'org.glassfish.jersey.core:jersey-common:2.13'
    myConfig 'org.glassfish.jersey.bundles.repackaged:jersey-guava:2.13'
    myConfig 'net.minidev:json-smart:1.2'
    myConfig 'com.thetransactioncompany:jsonrpc2-base:1.35'
    myConfig 'com.thetransactioncompany:jsonrpc2-client:1.14.4'
    myConfig 'com.thetransactioncompany:jsonrpc2-server:1.10.1'
    myConfig 'org.jsoup:jsoup:1.7.2'
    myConfig 'io.netty:netty-buffer:4.1.8.Final'
    myConfig 'io.netty:netty-buffer:4.1.8.Final'
    myConfig 'io.netty:netty-codec:4.1.8.Final'
    myConfig 'io.netty:netty-codec-http2:4.1.8.Final'
    myConfig 'io.netty:netty-codec-http:4.1.8.Final'
    myConfig 'io.netty:netty-codec-socks:4.1.8.Final'
    myConfig 'io.netty:netty-common:4.1.8.Final'
    myConfig 'io.netty:netty-handler-proxy:4.1.8.Final'
    myConfig 'io.netty:netty-resolver:4.1.8.Final'
    myConfig 'io.netty:netty-transport:4.1.8.Final'
 
    dep += add("myConfig", 'io.netty:netty-transport:4.1.8.Final')
    dep += add("myConfig", 'io.netty:netty-common:4.1.8.Final')
    dep += add("myConfig", 'org.jsoup:jsoup:1.7.2')
}
 
def sourcesFirst1 = {
    configurations.myConfig.fileCollection(dep)
}
 
tasks.register("myCopy", Copy) {
    from sourcesFirst1
    into project.buildDir.toPath().resolve("aFolder")
}`

includeBuildFolder/build.gradle
`plugins {
    id 'java'
}`

includeBuildFolder/settings.gradle
`rootProject.name = 'includeBuildFolder'

`

### Your Environment
Build time: 2018-12-21 23:03:45 UTC
Revision: bf26765

Kotlin DSL: 1.1.0
Kotlin: 1.3.11
Groovy: 2.5.4
Ant: Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM: 1.8.0_101 (Oracle Corporation 25.101-b13)
OS: Windows 7 6.1 amd64

**Comment by ljacomet** [comment]
Including a build is about substituting a binary dependency with a project one. Gradle does not know if that happens on a _declared_ dependency or on a _transitive_ one. So in order to properly compute the tasks to be executed, Gradle needs to understand where the substitution takes place.
And the consequence of that is the full resolution of configurations involved in task graph computation.

**Comment by ljacomet** [comment]
No it is not by _design_, it is a necessity of the implementation. And the fact that there is no parallelism is also something Gradle would like to change in the future.

I'll see about having a note in the documentation indicating that composite builds have an impact on configuration time since they may force full configuration resolution.

**Comment by bigdaz** [comment]
Composite builds are implemented using dependency substitution rules, and whenever a dependency substitution rule is applied, Gradle must resolve configuration inputs when composing the task execution graph. This is because any resolved configuration may contain a project dependency, which will then contribute additional tasks to be executed. (Without dependency substitution, we can avoid full resolution since we know that an external dependency will only depend on other external dependencies, and won't introduce a project dependency).

Note that this early resolution does not change which configurations are resolved, but changes _when_ they are resolved. The major impact is that by resolving them early (during task graph generation), we are unable to resolve them in parallel.

**Comment by bigdaz** [comment]
This behaviour is documented in https://docs.gradle.org/current/userguide/customizing_dependency_resolution_behavior.html#sec:dependency_substitution_rules. I guess we should link to this from the composite builds documentation.

**Comment by Jonatha1983** [comment]
It has also another side effect:
While resolving during execution we gain some tasks execution started before or in parallel to the resolution (in case they do not depend on the specific configuration)  in this mode we lose this parallelism since those tasks are blocked on a configuration resolution they do not need at all.

Thanks for the reference

**Comment by ljacomet** [comment]
That's an effect of the boundary between the _configuration_ and _execution_ phases of Gradle.

Working on better highlighting the configuration resolution impact of composite builds.

**Comment by boaznahum** [comment]
In our case (Jonathan), we use composite build for buildscript only.  Can this fact ease things ?

**Comment by big-guy** [comment]
Ideally, there should not be a large performance penalty with dependency resolution when dependency substitutions are involved.  Included builds implicitly include dependency substitutions and force serialized graph resolution during task graph building.
