### ISSUE TITLE
Gradle Build Failure NDBENCH -- cannot find de.undercouch.download??? -- Help!

### ISSUE THREAD

**Issue by kikichoupette** [gradle/gradle#8186]
<[kchou@den02tez ndbench]$ gradle --stacktrace | more

FAILURE: Build failed with an exception.

* Where:
Build file '/scratch/kchou/netflix/real_netflix/ndbench/build.gradle' line: 14

* What went wrong:
Plugin [id: 'de.undercouch.download', version: '3.4.2'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'de.undercouch.download:de.undercouch.download.gradle\
.plugin:3.4.2')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on discuss.gradle.org or stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.
