### ISSUE TITLE
Wrong input annotation on PluginUnderTestMetadata class

### ISSUE THREAD

**Issue by etiennestuder** [gradle/gradle#8188]
This annotation seems wrong:
https://github.com/gradle/gradle/blob/v4.10.3/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/PluginUnderTestMetadata.java#L94

It also seems to me that the getPaths() method could be private.

//cc @oehme @lacasseio

**Comment by big-guy** [comment]
It's correct only because we don't have a good way to say "this task cares about the _paths_ in this file collection and not the contents".

If anything, https://github.com/gradle/gradle/blob/v4.10.3/subprojects/plugin-development/src/main/java/org/gradle/plugin/devel/tasks/PluginUnderTestMetadata.java#L55 is wrong.  We don't care about the contents of the jars.

Are you seeing something broken with this?

**Comment by oehme** [comment]
The underlaying question was why this task isn't cacheable. Now that you mention it, it makes sense since we actually care about absolute paths for this to work.

**Comment by etiennestuder** [comment]
> Are you seeing something broken with this?

No. I just looked at the source and made the wrong conclusion. I think you are right that getClasspath() should not be annotated.
