### ISSUE TITLE
Cleanup stale output files from incremental task after Gradle version change

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#821]
When one changes Gradle versions or moves packages, output files from incremental tasks are not cleaned up, causing some tasks to be incorrectly considered `UP-TO-DATE`.

### Expected Behavior
Gradle should detect that outputs from incremental tasks are invalid due to at least Gradle version  and inputs changes. 

### Current Behavior
Output files from incremental tasks are not invalidated upon certain changes to inputs. 

### Workaround
Users are sometimes forced to run `clean` after upgrading Gradle or moving files around.

### Context
There are two sides to the issue
1) Detecting when we are in the situation
2) Cleaning up

regarding 1) When we do the Gradle upgrade this means that we have no history for a task. We have no history for a task exactly when we run the task for the first time with this version of Gradle (and nobody deleted .gradle).

regarding 2) What should we do when we have no history for a task? What we want to do is to delete all the files in the output directories/files of the task. This would be fine as long as we do not have overlapping output directories (if we ignore things like have / as an output directory). With overlapping output directories we need to delete everything in the output which has not been produced by another task ran by the same Gradle version. In order to do that, we need to find out (via the task history), which files have been produced by other tasks in that directory.
We can do this in an ad-hoc way - so whenever we have no history we search the task history for tasks producing files in the output directory and delete all the other files. Or we could create an index which could answer this kind of question - i.e. given a file, has this file been produced by another Gradle task. Having an index like that would have an performance impact.

- JIRA issue: [GRADLE-1501](https://issues.gradle.org/browse/GRADLE-1501)
- Failing test created https://github.com/gradle/gradle/commit/456e0630f41d137b6c9bb0885accbf22d0c092b8

### Steps to Reproduce (for bugs)
1. Create `Main.java` and `Redundant.java` with some trivial code in them
2. Compile them by running `compileJava`
3. Remove `$projectDir/.gradle` (simulating a version upgrade)
4. Remove `Redundant.java`
5. Compile again
6. `Redundant.class` is still in the `build/classes` directory, even though its source is gone

### Your Environment
This occurs in all environments.

### Candidate Fixes
A way to fix this is to detect whether we have information about the previous execution of the task, and if not, we'd clean its output directory explicitly. This would only work if we could guarantee that the task has exclusive access to its outputs, i.e. no other task writes to any of the same files/directories.

### Use Cases
- Gradle upgrade occurs and source files removed
- Gradle upgrade occurs and tasks with overlapping output directories
- Gradle upgrade occurs and some tasks have output directories outside of buildDir
- Gradle upgrade occurs and some tasks have different output directories than before the upgrade
- `.gradle` project cache dir is deleted
- Gradle upgrade occurs and some tasks are removed from the build completely
- Gradle upgrade occurs and input files for a task become empty

**Comment by bmuschko** [comment]
[Google Doc](https://docs.google.com/document/d/1oqA-KNolZoqBknlA3fdzzR88YJflCxk08LZx5tYrnlQ/edit) describing some of the scenarios.

**Comment by wolfs** [comment]
I suppose that https://github.com/gradle/gradle/issues/917 is also one the the scenarios which could be part of this bug.

**Comment by adammurdoch** [comment]
Should consider fixing #973 when fixing this issue

**Comment by bmuschko** [comment]
PR containing spec and test cases: https://github.com/gradle/gradle/pull/984

**Comment by eriwen** [comment]
@bmuschko Did we split this issue into spec and implementation yet? If so, where is the other part?

**Comment by bmuschko** [comment]
@eriwen You can find the [link to the issue dealing with spec/tests](https://github.com/gradle/gradle/issues/984) above your comment.

**Comment by eriwen** [comment]
@bmuschko That's the PR. So I take it that represented spec/tests and this issue represents implementation? I got the feeling that we were planning on an Epic and split out stories. Still the case?

**Comment by bmuschko** [comment]
@eriwen I guess we should make this an epic and then create another issue that just addresses the Java compilation stale output as we might work on follow-up stories.

**Comment by big-guy** [comment]
We had a good chat with Adam on Monday about this (see me about the raw notes).

For a first increment (since the work that Ben did), we think that we...

- We could say we own everything in the `build` directory. For everything else we would need permission. If `clean` would have removed it then we are allowed to remove it
- Record output directories for tasks. If we encounter an output directory which did not exist before and is safe to delete then we can just wipe it out just before we execute a task.

**Comment by bjhargrave** [comment]
In Gradle 3.4 (#1018), Gradle can delete the output folder. This is causing my [Bnd Gradle plugin](https://github.com/bndtools/bnd/tree/master/biz.aQute.bnd.gradle) issues since it makes sure the output folders exist (and creates them if necessary) during evaluation, but then the directories are missing during execution because #1018 runs after all evaluation is complete. I have had to add recreating the output folders during execution to stop the plugin from failing on Gradle 3.4.

Perhaps instead of removing the output folders, you instead remove their contents. This way the folder will remain but be empty.

**Comment by bmuschko** [comment]
@bjhargrave Can you explain why your plugin needs to verify that the `buildDir` exists?

**Comment by bjhargrave** [comment]
> @bjhargrave Can you explain why your plugin needs to verify that the buildDir exists?

It is not `buildDir`. It is `sourceSets.main.output.classesDir`.

The Bnd Gradle plugin (for Workspace builds) uses bndlib to understand the project structure during evaluation and uses this info to configure the Gradle java tasks including `sourceSets.main` and `sourceSets.test`. In particular, the bndlib code ensures the classesDir exists. Later during execution of the `jar` task for a project with no Java source code (so `compileJava` task does not run and create the classesDir), bndlib code is called and it expects the classesDir, that it created earlier to still exist. Since Gradle has removed the classesDir between evaluation and execution time, the bndlib code fails since its assumption is broken.

I have made fixes to the Bnd Gradle plugin for our next version, but someone using the current Bnd Gradle plugin with Gradle 3.4 will not be able to clean build (e.g. `.gradle` is deleted) when that have projects with no java source code.

So my point is that all Gradle really needs to do is to empty the classesDir (or any other such dir) rather than remove the dir. Obviously, if the dir does not exists, then it does not need to be cleared. But if it does exist, then just empty it rather than remove it.

**Comment by oehme** [comment]
Writing files at configuration time is a performance antipattern, so moving the creation of that folder to execution time is the right way to go. Alternatively, your jar task could just tolerate some input directories not existing (which is what we usually do).

**Comment by bjhargrave** [comment]
> Writing files at configuration time is a performance antipattern, so moving the creation of that folder to execution time is the right way to go.

Sure, but I am using existing bndlib code which creates the folders it needs when called during project evaluation so the Bnd Gradle plugin can get the information is needs to configure the Gradle project. I really cannot change bndlib, which is used by tools other than Gradle, to conform to Gradle best practices. It is what it is.

> Alternatively, your jar task could just tolerate some input directories not existing (which is what we usually do).

I have done that for the next release of the Bnd Gradle plugin. And I have documented this as a [known issue with Gradle 3.4 along with a workaround](https://github.com/bndtools/bnd/wiki/Changes-in-3.3.0#known-issues).

My point is that there is no need to remove the folders. Just empty them. It is the contents of the folders you do not trust, not the folders themselves.

**Comment by wolfs** [comment]
We can close this Epic now that #2572 is merged. Please reopen as necessary.

**Comment by lptr** [comment]
\ő/
