### ISSUE TITLE
Dependency resolution fails on Gradle 5.1

### ISSUE THREAD

**Issue by ashiishsharma** [gradle/gradle#8218]
I am facing an issue with my gradle project during migration to Gradle 5.1 from Gradle 4.10.2 :

**Issue :**

    ./gradlew clean build
    > Task :subprojects:lib-abc-admin:compileJava FAILED
    
    FAILURE: Build failed with an exception.
    
    * What went wrong:
    Execution failed for task ':subprojects:lib-abc-admin:compileJava'.
    > Could not resolve all files for configuration ':subprojects:lib-abc-admin:compileClasspath'.
       > Could not find org.glassfish.jersey:jersey-bom:.
         Required by:
             project :subprojects:lib-abc-admin   
    
    BUILD FAILED in 2s

In previous version Gradle 4.10.2, this error was getting circumvented by the following switch:

    enableFeaturePreview("IMPROVED_POM_SUPPORT")

But in gradle 5 this switch has been deprecated, seems like this doesn't work anymore and I am getting the errors.

**Any alternatives / suggestions / solutions ?**

    Toolchain Details :
    
    ------------------------------------------------------------
    Gradle 5.1
    ------------------------------------------------------------
      
    Kotlin DSL:   1.1.0
    Kotlin:       1.3.11
    Groovy:       2.5.4
    Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
    JVM:          11.0.1 (Oracle Corporation 11.0.1+13-LTS)
    OS:           Linux 4.19.8-200.fc28.x86_64 amd64

[Build Scan is here](https://scans.gradle.com/s/iigxznwz26t2m/)

**Comment by ljacomet** [comment]
Different approach were tried for supporting BOMs. In Gradle 5.0, through feedback from the community (see #4422), we ended up deciding on an explicit notation to import a BOM.
So you will need to update dependencies on modules that are BOMs to that notation. See [documentation](https://docs.gradle.org/5.1.1/userguide/managing_transitive_dependencies.html#sec:bom_import) for details.
And since the `IMPROVED_POM_SUPPORT` feature is not enabled by default, you can remove the `enable...` line from your `settings.gradle(.kts)`

**Comment by ljacomet** [comment]
Of course, sorry for the typo. Edited.

**Comment by ashiishsharma** [comment]
Able to migrate after checking the suggested solution.
Thanks !!!
