### ISSUE TITLE
Add `stopDaemons()` to `GradleConnector` interface

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#8219]
A tooling API client (e.g., IDE), sometimes needs to be able to stop Gradle daemons, spawned during it's operations. A good example is stopping a daemon on closing a project in the IDE to free up system resources (e.g., see [this report](https://youtrack.jetbrains.com/issue/IDEA-202453) for IntelliJ IDEA)
A Continuous integration server can also be interested in such feature. See discussion in #5998 

### Expected Behavior

`GradleConnector.stopDaemons()` would be a good step towards a `ProjectConnection.stopDeamon()`

### Current Behavior

Now there is now way (other than ugly relfection/internal API usage) to control daemons from the IDE.

### Context

An IDE user works with a multiple (3+) projects simultaneously or one after another. As different Gradle versions are used by each project, a daemon stays around a the project is closed (keeping memory).

### Steps to Reproduce (for bugs)

n/a

### Your Environment

n/a

**Comment by amakeev** [comment]
relates to #8010

**Comment by tcfurrer** [comment]
Until there is a way for an IDE to start its own private daemon, that cannot be shared by any other running gradle processes, it seems like it would be unsafe to allow the IDE to stop _any_ gradle daemons.

Example 1:
The IDE starts a gradle daemon.  Later, another unrelated gradle process on the same host begins using that daemon.  Then the user closes the IDE.  At this time, if the IDE kills the gradle daemon it started, the other process's running gradle tasks get forcibly interrupted.  Obviously that's unacceptable.

Example 2:
The IDE starts a gradle daemon.  Later, another gradle process runs and uses the same daemon.  The other process happens to leave the daemon idle sometimes.  The IDE happens to get closed while the daemon is idle.  If the IDE is allowed to stop the daemon, then the performance of other process is effected the next time it executes a gradle command, because it will have to start a new daemon.  This collateral damage to performance is undesirable, but may be acceptable (especially since IDE exit isn't something that happens frequently).

**Comment by nskvortsov** [comment]
@tcfurrer I agree that IDE definitely should never kill a Gradle daemon that is busy: interrupting user's build is not acceptable. With regards to the idle daemons (only started by IDE itself, of course), cleaning up system resources allocated by an application looks reasonable and expected behavior.

Potentially, Gradle daemon management could go "extra mile" and track daemon usages from different clients. So if a daemon was only used by a single client (an IDE), it could be shut down by this client. And if the daemon was used by another client (e.g., gradle command line) it should stay alive.

**Comment by big-guy** [comment]
Something like this is coming in 6.5: https://docs.gradle.org/nightly/javadoc/org/gradle/tooling/GradleConnector.html#disconnect--
