### ISSUE TITLE
Support overriding default properties in custom distribution

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8269]
### Context

An initial [PR](https://github.com/gradle/gradle/pull/7680) implemented the ability to have a `daemon.properties` file in a custom distribution, to override some defaults, and in particular the daemon defaults. This was discarded after a comment saying that the issue wasn't related to the change of memory settings. However, we now have reports that on some particularly large builds, the default memory settings for Gradle may be now too low. For some organizations this can be problematic as changing the default may involve updating a large number of projects.

The idea would therefore be to restore this PR but with a slightly different scope:

- Add a `gradle.properties` to the Gradle distribution that has the lowest precedence with any other `gradle.properties`
- Everything you can do in `gradle.properties`, you can do here.

## Open questions

- Does this work well enough that you can get away with doing everything via `org.gradle.jvmargs`?
- Do we need an alternative to `org.gradle.jvmargs` that is more structured (e.g., `org.gradle.daemon.memory.max`) so we can pass the appropriate arguments depending on the JVM version?
- Do we differentiate between Gradle distributions that would differ only in `gradle.properties` content?

**Comment by jjohannes** [comment]
PR for `gradle.properties` in installation directory: #9296.

Regarding the open questions:
- If needed, adding additional properties for defining memory options (in addition to the generic `org.gradle.jvmargs` ) should be handled in a separate issue. These options should then be supported in _all_ `gradle.properties` files.
There should be a strong use case for this, as it would add additional maintenance burden and also complexity for the users – e.g. if the new options conflict with what is set in `org.gradle.jvmargs` the behavior can become hard to understand.
- No special handling of the _same_ distribution with different `gradle.properties` is needed. If the properties influence daemon reuse or caching, this is already handled by the existing mechanisms - since we just add a new location for the _properties_ file and no new specific properties.
