### ISSUE TITLE
BOM vs Gradle Composite not working

### ISSUE THREAD

**Issue by cdietrich** [gradle/gradle#8273]
We have a composite gradle build with two included builds.
We make use of the gradle 5.x BOM support.
but gradle trys to resolve the bom against buildscript dependencies

### Current Behavior

getting an error message like
```
* What went wrong:
A problem occurred configuring project ':xtext-core'.
> Could not resolve all artifacts for configuration ':xtext-core:classpath'.
   > Could not find org.eclipse.xtext:xtext-dev-bom:2.17.0-SNAPSHOT.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.pom
       - https://jcenter.bintray.com/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.jar
       - https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.pom
       - https://repo.maven.apache.org/maven2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.jar
       - https://plugins.gradle.org/m2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/maven-metadata.xml
       - https://plugins.gradle.org/m2/org/eclipse/xtext/xtext-dev-bom/2.17.0-SNAPSHOT/xtext-dev-bom-2.17.0-SNAPSHOT.pom
     Required by:
         project :xtext-core > org.xtext:xtext-gradle-plugin:2.0.2 > project :xtext-lib:org.eclipse.xtend.lib
         project :xtext-core > org.xtext:xtext-gradle-plugin:2.0.2 > project :xtext-lib:org.eclipse.xtend.lib > project :xtext-lib:org.eclipse.xtext.xbase.lib
         project :xtext-core > org.xtext:xtext-gradle-plugin:2.0.2 > project :xtext-lib:org.eclipse.xtend.lib > project :xtext-lib:org.eclipse.xtend.lib.macro
```

### Steps to Reproduce (for bugs)

find attached example 

[Archiv.zip](https://github.com/gradle/gradle/files/2772624/Archiv.zip)

```
xtext-umbrella/releng/gradle-composite
 ./gradlew wrapper
```

### Your Environment

 * Build scan URL: 
cannot create can cause of problem

**Comment by ov7a** [comment]
Sorry for the late reply.

This is still reproducible with 9.5.1, but I'm not sure if it's expected or not

[8273.zip](https://github.com/user-attachments/files/28802692/8273.zip)

**Comment by ljacomet** [comment]
The issue here is that you expect an included build to be resolved as a [`pom`/`import` in a Maven POM file](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#dependency-scope). But during the process of POM parsing, Gradle only looks for artifacts in repositories, it never goes back up to ask if Gradle itself could fill those coordinates.

And even if it did, the included build is not set up for Maven publication, which would be mandatory in order to respect the `import` request, as inlining `dependencyManagement` entry is the whole point of such dependencies.

One way to resolve this, if the use case still matters, is to publish those builds locally first, but that's effectively beyond what included builds provide in Gradle.

However, we could look at improving the error message so that it is clearer what the underlying problem is.
