### ISSUE TITLE
How to reconfigure other tasks during the execution time

### ISSUE THREAD

**Issue by remy-tiitre** [gradle/gradle#8359]
I'm not even sure if its possible. But FindBugs and now SpotBugs allows to generate one report per execution. In our project we have defined it to be an xml one. Then this can be reused during the sonarqube run. But when there are errors I want developers to be able to execute a task that create html report. I have found no way to do this. My first idea was:
```
tasks.create(name: 'spotbugsHtml', dependsOn: [spotbugsMain, spotbugsTest]) {
    tasks.withType(com.github.spotbugs.SpotBugsTask) {
        reports {
            xml.enabled = false
            html.enabled = true
        }
    }
}
```

But as expected this will override all spotBugs tasks during the configuration phase, so its no different than setting the html as default. I would need something like this:
```
tasks.create(name: 'spotbugsHtml', dependsOn: [spotbugsMain, spotbugsTest]) {
    doLast {
        tasks.withType(com.github.spotbugs.SpotBugsTask) {
            reports {
                xml.enabled = false
                html.enabled = true
            }
        }
    }
}
```

So is this even possible what I try to do. Reconfigure some other tasks during the execution phase?

**Comment by big-guy** [comment]
Yes, that's possible.  In this particular case, it's safe-ish to do because you're not modifying the dependencies of the FindBugs/SpotBugs tasks.
You'll want to do something like:

```
task configureHtml {
  doLast {
    tasks.withType(FindBugs) {
       xml.enabled = false
       html.enabled = true
    }
  }
}
tasks.withType(FindBugs) {
   mustRunAfter configureHtml
}
```

And then someone can run `gradle configureHtml findBugsMain`.

Alternatively, you could key this off of a project property.  e.g., `gradle -PhumanReadable findBugsMain` and look for that when configuring your tasks:
```
    tasks.withType(FindBugs) {
       if (project.hasProperty("humanReadable")) {
          xml.enabled = false
          html.enabled = true
       }
    }
```

I would also ask the SpotBugs maintainers if it's possible to allow SpotBugs to produce multiple reports at the same time.  Then you could just enable both XML and HTML.
