### ISSUE TITLE
Add a `JAVA_API_JARS` usage

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8396]
For consistency with `JAVA_RUNTIME` vs `JAVA_RUNTIME_JARS`, outgoing configurations should prefer a `JAVA_API_JARS` value. Basically we think a _consumer_ only should use `JAVA_API`, or `JAVA_RUNTIME`, when it doesn't care in which form the runtime should come. Producers on the other hand should be as specific as they can.

**Comment by ljacomet** [comment]
The changes around using `JAVA_API_JARS` and `JAVA_RUNTIME_JARS` instead of `JAVA_API` and `JAVA_RUNTIME` at publication time have an impact on the `versionMapping` as now one needs to update the values passed to `usage` in order to get the expected behavior.
We should try to find a solution so that the previous usage still produces the expected output. In addition it should nag about a change asking users to update their build.

**Comment by melix** [comment]
I think we should probably update the mapping code so that instead of checking for equality, it actually checks compatibility.

**Comment by melix** [comment]
Closing as delivered in #8433 .
