### ISSUE TITLE
Infinite recursion when adding sources to JacocoReport

### ISSUE THREAD

**Issue by davidburstromspotify** [gradle/gradle#8398]
### Expected Behavior
JacocoReport tasks in 5.1.1 should handle scenarios like

```reportTask.additionalSourceDirs += otherReportTask.sourceDirectories```

It used to work in 4.10.2.

### Current Behavior
Given the scenario above in Gradle 5.1.1 there's an infinite recursion while snapshotting the input:

    at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:130)
    at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
    at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:164)
    at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResolve(DefaultFileCollectionResolveContext.java:109)
    at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolveAsFileCollections(DefaultFileCollectionResolveContext.java:92)
    at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCollectionConverter.convertInto(DefaultFileCollectionResolveContext.java:164)

There is however a migration warning while using `JacocoReport.setAdditionalSourceDirs()`, suggesting that `JacocoReport.getAdditionalSourceDirs().from()` should be used instead. That solution works as a workaround for the problem.

It seems strange that the implementation for `JacocoReport.setAdditionalSourceDirs` uses `setFrom` whereas the deprecation warning says something else.

### Context
This caused migration issues from 4.10.2 to 5.1.1.

### Steps to Reproduce (for bugs)

See the above description.

### Your Environment
MacOS 10.14.2, Gradle 4.10.2/5.1.1

**Comment by big-guy** [comment]
The underlying issue is that
```
reportTask.additionalSourceDirs += otherReportTask.sourceDirectories
```
means 
```
reportTask.additionalSourceDirs = reportTask.additionalSourceDirs + otherReportTask.sourceDirectories
```

So when resolving the files in `reportTask.additionalSourceDirs`, it contains itself. This worked in <5.0 because the setters overwrote the field instead of modifying it. This causes problems when other tasks try to reference the property since the instance can change. As an example...

```
otherReportTask.sourceDirectories = files("foo")
reportTask.additionalSourceDirs += otherReportTask.sourceDirectories
// some time later...
otherReportTask.sourceDirectories += files("bar")
```
It looks like `reportTask.additionalSourceDirs` would contain "foo" and "bar", but it doesn't.

Where the updated version does work:
```
otherReportTask.sourceDirectories.from(files("foo"))
reportTask.additionalSourceDirs.from(otherReportTask.sourceDirectories)
// some time later...
otherReportTask.sourceDirectories.from(files("bar"))
```
Instead of overwriting the `sourceDirectories` property, we're adding to the same underlying instance.

> It seems strange that the implementation for JacocoReport.setAdditionalSourceDirs uses setFrom whereas the deprecation warning says something else.
This is to keep things working mostly as you'd expect a setter to work.  `from()` is usually what you want because you're just adding to whatever is there. `setFrom` is needed to replace whatever has been set.  If we used `from` here, this wouldn't work:

```
reportTask.additionalSourceDirs = files("some-default-path")
// some time later, we actually want a different path
reportTask.additionalSourceDirs = files("the-new-path")
```
This would have both "some-default-path" and "the-new-path" instead of just "the-new-path".

Given that we have a deprecation message and the build fails in an obvious way (vs silently doing the wrong thing), I don't think we're going to change this behavior back.  In Gradle 6.0, the setters will go away entirely and `+=` will not work at all.

**Comment by maarre** [comment]
This is the same bug? https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/issues/136

**Comment by lukas1** [comment]
@big-guy Any suggestions on how to achieve `reportTask.additionalSourceDirs += otherReportTask.sourceDirectories` in newer versions of Gradle?

Would something like this be correct implementation? 

```
reportTask.additionalSourceDirs.from(reportTask.additionalSourceDirs.from + otherReportTask.sourceDirectories)
```

I've noticed this kind of solution in the PR that mentions this issue (https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/pull/153), but it almost looks like the piece of code that you say cannot work properly, so I'm confused, whether the PR contains wrong code, or I'm misunderstanding something (I'm aware, that the difference between the PR and this line `reportTask.additionalSourceDirs = reportTask.additionalSourceDirs + otherReportTask.sourceDirectories` is in the usage of `setFrom`, but being ignorant about Gradle internals, I actually don't know if that's relevant or not)
