### ISSUE TITLE
Ability to configure the duplicate daemon expiration timeout

### ISSUE THREAD

**Issue by jsiwrk** [gradle/gradle#8408]
When multiple compatible daemons are started, Gradle expires the non-recently used daemons after a fixed idle timeout of [10 seconds](https://github.com/gradle/gradle/blob/master/subprojects/launcher/src/main/java/org/gradle/launcher/daemon/server/MasterExpirationStrategy.java#L32). It would be useful to make this timeout configurable.

### Expected Behavior
The duplicate daemon grace period is configurable with a property, similarly to the existing `org.gradle.daemon.idleTimeout` property (which does not affect the expiration of duplicate daemons).

### Current Behavior
The duplicate daemon grace period is hardcoded to a value of 10 seconds.

### Context
Our build process executes builds (Gradle builds, and also other types of builds) in parallel, and we have found the 10-second timeout to be too short for some build environments. The effect is that Gradle daemons are continously stopped instead of being reused.

### Your Environment
Gradle 4.10.2 (although the behaviour should be the same in the current Gradle version, since the code that controls this fixed timeout has not changed)

**Comment by ghale** [comment]
It would be interesting to understand more about your use case.  The idea here is to try to keep at least one daemon around that can potentially fill the requirements of a future build.  We don't want to have bunch of idle daemons lying around that may not be used, so we try to keep a daemon around for each unique set of requirements that we have seen in the past (resources permitting).  If we have multiple daemons that can meet the same requirements, then we'll expire all but one to avoid consuming a bunch of resources for a single set of requirements.

What it sounds like is that your builds are bursty and that you start many daemons concurrently with duplicate requirements.  Then there is a lag in between builds and the duplicates expire before another burst occurs.  Does that sound about right?  

If so, a couple of questions:
- What timeout would be more suitable for you?
- What is coordinating those bursts?  
- Do the bursts follow a pattern for a given set of daemon requirements?  (i.e. is it always a burst of say 8 concurrent builds or is it sometimes 3, sometimes 7, sometimes 5?)
- Is the parallelism constrained?  (i.e. is there an upper limit on the number of parallel builds or does it just spin up as many concurrent builds as are necessary?)
- Are the parallel workers of the coordinator identifiable across builds?  

If the answer to the last two are yes, one thing you could do is bake the identifier of the worker into the daemon requirements (for instance by setting a system property).  This would make the daemons incompatible from each other and you would end up with a unique daemon for each worker which would live until the normal idle timeout expired (or memory pressure caused them to expire).

In general, we like to avoid adding these sorts of configurable system properties if we can help it.  The 10s timeout was just sort of arbitrary and seemed like a good value, but we might consider changing it if there is a value that makes more sense.  Another potential (but more complicated) approach would be to recognize this sort of bursty behavior and try to keep the right number of daemons around for a set of requirements (i.e. if I always end up with 4 duplicates running builds concurrently, try to keep 4 daemons for that set of requirements running instead of 1).

**Comment by jsiwrk** [comment]
Agreed there must be a good reason for introducing such a new property. Not sure if my case is common either. Thanks anyway for considering.
	
> What it sounds like is that your builds are bursty and that you start many daemons concurrently with duplicate requirements. Then there is a lag in between builds and the duplicates expire before another burst occurs. Does that sound about right?

Yes, that's exactly what (I think) it's happening.

> What timeout would be more suitable for you?

Increasing the timeout to 5 minutes worked in our case (the number of daemons started during the build was stable). Probably could be lowered.

> What is coordinating those bursts?

A proprietary build coordination tool (of which I have a limited knowledge; sorry if my answers are vague). This tool is used for local builds (not CI), on often slow machines. The tool starts other types of builds apart from Gradle (e.g. ant).

> Do the bursts follow a pattern for a given set of daemon requirements?

Probably not. There is a single set of requirements.

> Is the parallelism constrained?

By the number of CPU cores I think.

> Are the parallel workers of the coordinator identifiable across builds?

No.
