### ISSUE TITLE
Recompile specific files in source set

### ISSUE THREAD

**Issue by nskvortsov** [gradle/gradle#8425]
Common workflow of debugging a problem in IDE involves recompiling and hot-swapping a single (or small number) of classes, potentially ignoring set modified set of other sources.

### Expected Behavior

Gradle `:compile` task allows specifying exact recompile target, e.g. `--single com/example/MyClass.java`

### Current Behavior
End user is forced to do incremental compilation of the whole module, including all modified files, potentially denying the hot swap (e.g., if some unrelated file can not be compiled)

### Context
Context is commonly used "Recompile file" action in IntelliJ IDEA with "Delegate build/run operations to Gradle" enabled

**Comment by Alefas** [comment]
I do a lot of hacking, which requires some checks in working app. So recomilation of single file with following hot swap to check something is very important usecase for me.

Not compiled other files generally it's not the only case when I want to recompile ony single file. Problem can be if too much files changed so recompilation will be slow. Or it can be in case when I'm sure hot swap will not work because of new methods, in this case I want to recompiler single file, which I know changes just method bodies.

**Comment by oehme** [comment]
This doesn't fit Gradle's model of a task at all, so I'm highly doubting that we'll ever do this. It would require fundamental changes, not just a quick hack in the Java plugin.

I'd propose a solution on the IDEA side instead: Stash the changes that you don't want, then call Gradle as usual.
