### ISSUE TITLE
Resolving all repositories, even if the correct version is found in the first

### ISSUE THREAD

**Issue by BorzdeG** [gradle/gradle#8430]
sample project: https://github.com/bug-samples/gradle-resolving-diff-jvm

### Your Environment
 * Build scan URL (OracleJDK): https://scans.gradle.com/s/i2wmqmxq7orjy/

 * Build scan URL (OpenJDK): 

13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] 
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] ----------
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] Gradle version: 5.2
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] Plugin version: 2.1
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] Request URL: https://scans-in.gradle.com/in/5.2/2.1
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] Request ID: bb13a2c2-cb70-4a34-ac4c-b4c1a1cb6975
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] Exception: javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
13:22:11.801 [QUIET] [com.gradle.scan.plugin.BuildScanPlugin] ----------

**Comment by ljacomet** [comment]
I am not sure what's expected from Gradle on this issue.

The repositories in the test project are declared as follows:
```
repositories {
    mavenCentral()
    jcenter()
}
```

This means that Gradle will search in Maven Central first, which has the dependency.

Now the build with OpenJDK RI seems to have all sort of SSL related issues, since publishing a build scan failed as well.

So before investigating on the Gradle side, I would recommend verifying that it is not an issue with the OpenJDK distribution for Java 8. Maybe its default truststore is not properly populated.

Could you confirm that running something like https://github.com/ChristopherSchultz/ssltest with OpenJDK works when trying to do SSL to the Maven Central, JCenter and build scan URLs?

**Comment by BorzdeG** [comment]
The artifact "org.flywaydb: flyway-core" version "5.2.4" should be the same in all repositories. Finding it in the first repository does not need to look for it in others.

In this example, expected:
1) look for "org.flywaydb:flyway-core:5.2.4" in the mavenCentral.
2) found this artifact in mavenCentral. Stop searching

In fact, what happens:
1) look for "org.flywaydb:flyway-core:5.2.4" in the mavenCentral
2) found this artifact in mavenCentral. We continue the search for this artifact further
3) look for "org.flywaydb:flyway-core:5.2.4" in the jcenter
4) could not connect to the jcenter. They reported that we could not find "org.flywaydb:flyway-core:5.2.4" because they could not connect to the jcenter.

Search all repositories should be only for dynamic versions of artifacts, but not for permanent ones.

**Comment by bigdaz** [comment]
> 1. look for "org.flywaydb:flyway-core:5.2.4" in the mavenCentral.
> 2. found this artifact in mavenCentral. Stop searching

This is the current behaviour. You can see here that mavenCentral is the only location searched: https://scans.gradle.com/s/i2wmqmxq7orjy/performance/networkActivity

**Comment by BorzdeG** [comment]
Oh, now the situation is not reproduced and the log with the error was not saved. Yes, it searches only in one repository. Close issue
