### ISSUE TITLE
Loss of flexibility from RegularFileProperty.set(File) setting an absolute path by default

### ISSUE THREAD

**Issue by rgozim** [gradle/gradle#8434]
Preserve `File` object as created when used in `RegularFileProperty`

```gradle
final RegularFileProperty outputFile = project.objects.fileProperty()
outputFile.set(new File("interested_in_file_name_or_partial_path"))
```

### Expected Behavior
```gradle
outputFile.get().asFile == "interested_in_file_name_or_partial_path"
```

### Current Behavior
```gradle
outputFile.get().asFile == "/pathToProjectRoot/interested_in_file_name_or_partial_path"
```

### Context
Because `RegularFileProperty` creates a `File` object under the hood with an absolute path, it is not possible to optionally append `RegularFileProperty` to a `DirectoryProperty`. In my example, I would like to have a DSL that can set a base output directory and inner DSL objects that can optionally override this by specifying an absolute path. By default, Inner DSL objects could use a partial path and concatenate their output directory/file to that of the base output directory.

```gradle
dsl {
    outputDir = "$buildDir/mydir"

    children {
        child {
            // would result in $buildDir/mydir/finalfile.txt
            outputFile = "finalFile.txt" 
        }
        otherChild {
            // would result in $projectDir/src/main/generated/finalFile.txt
            outputFile = file("src/main/generated/finalFile.txt")
        }
    }
}
```

**Comment by adammurdoch** [comment]
I think a more flexible option would be to allow you to create `RegularFileProperty` instances with a specific base directory provider, rather than the default base directory provider.

For example, let's say we add a new method `DirectoryProperty.fileProperty()` that returns a new `RegularFileProperty`. This new property would use the value of the directory property to resolve relative values (taking into account changes to the original directory property).

Then, when your plugin creates a child object, it can use this method to create the `outputFile` property value. The `outputFile` property will then automatically track changes to the `outputDir` property, if set to a relative value, or can be set to an absolute value.

You should be able to put something like this together now using `DirectoryProperty.file(path)` in your plugin now, but it won't be as convenient as if we added a new method. Would you be interested in doing a PR to add this? No problem if not, we will add this at some point.

We don't want to have file properties return relative `File` objects because then it becomes very easy for plugins or build scripts to accidentally depend on the working directory of the build process, rather than using locations calculated from the project directory (or some other absolute path).
