### ISSUE TITLE
versionMapping changes the resolved versions of Gradle projects in POM

### ISSUE THREAD

**Issue by jfbibeau** [gradle/gradle#8462]
### Expected Behavior
The version of a project's published JAR is set in the POM as a dependency. 

### Current Behavior
We noticed after applying `versionMapping` in Gradle 5.2 to our publications that all the resolved versions of project dependencies (ie: compile project('blah')) have changed in the POM. 

### Context
This is a bit confusing, hopefully the context makes sense:
* We publish versions x.y.z of our project JARs after a successful build, by setting the version attribute in the publication
* Before applying versionMapping, x.y.z shows up in the POM dependencies, which is what we want.
* After applying `versionMapping` for api/runtime, the version of our project dependencies in the POM has changed to x.y. 
* After some digging it appears that x.y is what we set the project.version attribute to.
* In other words, we are building release candidates for x.y, so we want all the JARs to be named project-x.y.jar. However when publishing the candidate, we publish all JARs as x.y.z (where z is the build number), so we'd want all POM dependencies to be x.y.z as that is what is resolved/published.

### Steps to Reproduce (for bugs)
1. Unzip attached project
2. cd to gradle-playground/projectB
3. `gradlew publishMavenJarPublicationToMavenLocal`
4. `vi ~/.m2/repository/gradle-playground/projectB/1.0.5/projectB-1.0.5.pom` 
5. Observe the project dependency to A:
```
    <dependency>
      <groupId>gradle-playground</groupId>
      <artifactId>projectA</artifactId>
      <version>1.0</version>
      <scope>runtime</scope>
    </dependency>
```
Even though in A's build.gradle:
```
    publications {
        mavenJar(MavenPublication) {
            from components.java
            version '1.0.5'
        }
    }
```
[optional]
6. Remove versionMapping from B's build.gradle
7. Re-run `gradlew publishMavenJarPublicationToMavenLocal`
8. Observe the POM now has 1.0.5 version correctly set.

### Your Environment
macOS 10.14.2
Gradle 5.2
[gradle-repro.zip](https://github.com/gradle/gradle/files/2847046/gradle-repro.zip)

**Comment by ljacomet** [comment]
This is as expected.
When using `versionMapping` you ask Gradle to replace declared versions with resolved ones. So Gradle will match all declared dependencies and replace their declared version with the resolved one.
However _during publication_ you change the version that a project is published under. That information is not even known by the dependency resolution engine.

You have two options in this context:
* Update the build so that the computed version is not only assigned during publication but also during build, effectively setting the `project.version` property instead of just the publication version.
* Stay away from `versionMapping` if your build cannot be changed as above.

**Comment by ljacomet** [comment]
My answer lacks a bit of context on the difference when using `versionMapping` or not:
* When not using `versionMapping`, Gradle will identify a project through the available publications in the current build. That is why the correct version is used in that case, since the publication for `projectA` knows about its _publication_ version.
* When using `versionMapping`, see comment above.

**Comment by jfbibeau** [comment]
Thanks @ljacomet for the explanation!
