### ISSUE TITLE
StopActionException causes build to fail

### ISSUE THREAD

**Issue by allanlewis** [gradle/gradle#8474]
### Expected Behavior

* My `integrationTest` task should be skipped.
* The build should succeed.

### Current Behavior

* The build fails.

### Context

The docs for [`StopActionException`][1] state:

> Note that throwing this exception does not fail the execution of the task or the build.

I'm throwing this exception based on whether a project property is set. I'd like to skip the `integrationTest` task when either of two project properties isn't set (or is null).

### Steps to Reproduce (for bugs)

[gradle-stop-action-exception.zip](https://github.com/gradle/gradle/files/2851118/gradle-stop-action-exception.zip)

### Your Environment

 * Build scan URL: https://scans.gradle.com/s/iiamluwcqpjx2

[1]: https://docs.gradle.org/5.2.1/javadoc/org/gradle/api/tasks/StopActionException.html

**Comment by big-guy** [comment]
This only works if you're throwing `StopActionException` from a task's action (IOW, when the task is executing).

Your build is failing much earlier, during the configuration phase and before any tasks have started to execute.  You'll see this if you don't even run `integrationTest` (try `gradle tasks`).

I think there's an easier way to do this, instead of waiting for task execution time and then aborting, you can also do something like:
```
integrationTest {
    onlyIf {
       setOf("slackRoom", "slackToken").all { project.findProperty(it) != null }
    }
}
```

This would skip `integrationTest` if either `slackRoom` or `slackToken` are not set.

**Comment by allanlewis** [comment]
Thanks, @big-guy!
