### ISSUE TITLE
Generate `publishToXXX` to aggregate `publishYYYToXXX` tasks

### ISSUE THREAD

**Issue by orangy** [gradle/gradle#8509]
For each publication and each repository Gradle generates a `publishXXXToYYY` task. There is also `publishToMavenLocal` which aggregates all `publishXXXToMavenLocal` tasks. Why it doesn’t create `publishToYYY` aggregate tasks that will publish all publications into a specific repository? I can of course create it myself, but that’s something to copy around with every build file.

**Comment by melix** [comment]
Such a task already exists: it's simply called `publish`.

**Comment by orangy** [comment]
As far as I understand, `publish` executes for all repositories. If I have bintray repository and local folder repository, `publish` will push into both. That's not what I need.

**Comment by melix** [comment]
Got it, reopening.

**Comment by orangy** [comment]
That was fast :) However, why the name is so long? `publishAllPublicationsToMavenRepository`, why not just `publishToMavenRepository`? That would actually make `publishToMavenLocal` more or less in line with generic rule.

**Comment by melix** [comment]
The reason is the one in the comment of the PR: there are already a _lot_ of `publishXXX` tasks, and adding this means another one. Having too many tasks will lead to confusion, so its name is here to give a hint about what it does. It's also consistent with the individual tasks which are named `publishFooPublicationToBlah`
