### ISSUE TITLE
Reduce the number of times we evaluate task properties

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#852]
We seem to evaluate properties backed by callables many times (~4+ per property?)

Given a build:
```
task foo {
   inputs.property("someProp") {
        println "input evaluated"
        0
   }
   inputs.file( {
        println "input file evaluated"
        project.file("input")
   })
   outputs.file( {
        println "output evaluated"
        project.file("somefile")
   })

   doLast {
     file("somefile").text = ""
   }
}
```

Output is:

> input file evaluated
> :foo
> output evaluated
> output evaluated
> input evaluated
> output evaluated
> input file evaluated
> output evaluated

It would be great if we could get to one evaluation for all cases, but we should at least only have 2 evaluations (once before the task, once after).

**Comment by eriwen** [comment]
@big-guy Can you give more `Context` about why we might want to prioritize this, please?

**Comment by big-guy** [comment]
If it's expensive to calculate the value of the property, we would unnecessarily evaluate the same property multiple times and incur the calculation penalty each time. 

You could also have an unstable property, where each time Gradle gets the value of the property it changes to something else.  This would led to correctness issues where the up-to-date checks sees one value, the snapshotting sees another and the task implementation sees yet another.

There's a separate related issue that a task implementation is free to evaluate a property as many times as it likes, so it could run into the same problems as above.  That's out of scope.

**Comment by adammurdoch** [comment]
Inputs need to be also evaluated during task graph calculation, in case they happen to be `Buildable`.

I would move towards some strongly typed replacements to using closures and arbitrary code as the _direct_ values for task properties. For example, we already have `FileCollection` with various factory methods you can use to declare both the value and the tasks that build the value, and you can conveniently pass closures and arbitrary code to these factory methods. We can make these more convenient. When we're passed a `FileCollection` as an input, we don't need to calculate its values in order to calculate the task graph, as the `FileCollection` carries both the future value and the details of the tasks required to produce the value. We should add the same kind of thing for input files and output files and directories.

We should also, independently of this, move towards making task properties immutable immediately prior to task execution (of the whole task not just the task's actions), so that the value does not change during the execution of the task. We might start by simply not re-evaluating the property value each time it is queried once task execution has started, but not care whether the value itself is mutable or not.

Again, strongly typed objects help with this kind of issue as they carry the information that Gradle can use to ensure they become immutable at the relevant point in time with good visibility to the user. For example, if given a `FileCollection` that matches `lib/*.jar` as a task input, we can firstly query and snapshot the matching files, and then validate that nothing that later executes that produces another jar file in `lib`.
