### ISSUE TITLE
Unit test execution order should be deterministic

### ISSUE THREAD

**Issue by cesar1000** [gradle/gradle#8520]
Gradle's default test executer does not enforce an ordering of tests, which makes unit test execution indeterministic. In cases where tests leak their state (which is certainly undesirable, but not a rare occurrence), test ordering would affect the outcome. Reproducing these flakey conditions is extremely hard without the ability to replicate the test execution order.

In my view, the test executor should accept an optional seed for randomizing the order of the tests (with the default being, say, lexicographical order), and this seed should be declared as a task input. In the default case, the seed is undefined and tests run in a set order - which would guarantee that users get the same test results locally and in CI. A separate CI job may potentially run tests on random seeds to detect test ordering issues.

As an added bonus, ordering tests enables the ability to shard test execution. The executor could then take two extra parameters, shard number and shard count, to allow for test execution be split for parallel execution.

We've used this configuration internally for several years by overriding the default executor to implement ordering and sharding, and it would be ideal if that was made available by default.

**Comment by tcfurrer** [comment]
Wow, how did this request go for so long without any attention?  My team has run into this several times.  We have very large test lists which take several hours to run.  Whenever someone in the team makes a mistake that creates a new memory leak, we find ourselves wanting to narrow down the test suite to a minimal set of tests that reproduce the problem, so that it's easier to root cause.  But every time we run, Gradle doesn't always cooperate.   And it's annoying that we have to sometimes reproduce the issue on a specific machine or OS just because that effects Gradle's test ordering.

I understand that to a first order, it "should be unnecessary" and "is bad practice" for test suite order to matter at all, and thus need to be controlled.  But to a second order, there are times when controlling order would be extremely helpful, and I don't see what would be so bad about Gradle providing some options for controlling this.

Also it seems like it should be a pretty easy thing to implement, at least with only a couple of simple options like alphanumeric sort with or without random scrambling with seed.

Perhaps the real reason this isn't happening is because it involves slippery-slope risk. People will start to want more complex features for controlling test order, as is happening with JUnit5's test method execution order already... except they ARE providing these complex features to their users, ironically.

Also, it doesn't have an obvious slam-dunk elegant design.  Alphanumeric sorting (or really any other kind of sorting that isn't explicit) is only meaningful when the test suite is being re-run with exactly the same set of tests, but not so meaningful over time when the test suite is changing.  So ordering control would be great for root-causing failures, but not great for maintaining a specific ordering across active development (it would just be a dangerous abuse there, unless more complexity was added to unambiguously control ordering).

Another reason may be that it is possible to write a plugin for this, and the Gradle team is just wanting others to do that?  I'm not sure about this point.  It would be really nice if someone from the Gradle team could simply comment on this, and let us know what they are thinking on this topic, and how we might solve it for ourselves.  If that conversation already happened somewhere, I couldn't easily find it in a few minutes of searching...

**Comment by tcfurrer** [comment]
Another detail is how the cross product between ordering and parallelism would be dealt with.  I guess that may be a can of worms in general (especially if anyone ever implements work stealing, which I'm strongly in favor of for the long term), but again for the specific case of just making it possible to reproduce a failing suite run where the failure depends on execution order... I would usually be happy with being required to disable parallelism in order to get deterministic ordering.

**Comment by cesar1000** [comment]
We've been running ordered tests for years by replacing the test executor with a custom one that takes in a seed - it straightforward and it does the job. However, I don't think a plugin would work in this case, since the interfaces change frequently and require regular maintenance. A basic implementation is straightforward, and it would be trivial for Gradle to adopt.

I'd like to point out something else: the order of execution of the tests should be declared as an input to the task, since it affects test execution. To me, it's not a matter of flexibility, it's one of correctness.

**Comment by dlishingman-intuit** [comment]
@cesar1000 Do you mind sharing your custom test executor?

**Comment by cesar1000** [comment]
@dlishingman-intuit sorry for the delay - it's just four classes, and much of the code is based on the default Gradle executor. I pasted them in a [gist](https://gist.github.com/cesar1000/b610c1c95169ca6e83c173d888321632). You should be able to add the plugin to `buildSrc` to try it out.

**Comment by dlishingman-intuit** [comment]
@cesar1000 thanks a lot, very helpful!

**Comment by AlexLandau** [comment]
I've been experimenting with this a bit (specifically in the context of JUnit Platform). One of the easier (and safer?) possible changes to achieve deterministic test ordering would be to make [DefaultTestClassScanner#ClassFileVisitor](https://github.com/gradle/gradle/blob/d1d34ff7ad45073448ad01bd87827a8e6b753e89/subprojects/testing-jvm/src/main/java/org/gradle/api/internal/tasks/testing/detection/DefaultTestClassScanner.java#L75) implement [ReproducibleFileVisitor](https://github.com/gradle/gradle/blob/d1d34ff7ad45073448ad01bd87827a8e6b753e89/subprojects/core-api/src/main/java/org/gradle/api/file/ReproducibleFileVisitor.java).

Unfortunately, this always uses alphanumeric sorting (so it doesn't discourage relying on test ordering) and can't be extended to more advanced approaches, like the random-from-a-seed ordering. However, this would still solve the problem we have of "my test change passed on my pre-merge build but failed on yours". (This is a particular problem for us as we migrate existing tests from JUnit 4 test suites to JUnit 5.)

**Comment by cesar1000** [comment]
In my opinion, this is a huge gap in the correctness of Gradle's support for unit testing: test ordering affects test execution, and it should be made an explicit input to the test task. A test run should be repeatable, like any other task, and it should be our choice if we want to run tests in a random order to detect test ordering dependent. Enabling sharded execution on top of ordered test run would be a welcome added bonus.

I think that this is particularly relevant in the context of Gradle's renewed interest in the detection of flaky tests, and I'd be curious to hear about arguments for and against implementing this feature.

**Comment by marcphilipp** [comment]
Related issue for JUnit Jupiter: https://github.com/junit-team/junit5/issues/1948

**Comment by cesar1000** [comment]
Let me share some extra context, since I realize that the arguments I brought up, which speak of correctness and repeatability, may sound somewhat abstract.

The Twitter for Android codebase uses ~300 modules and runs ~20K unit tests with every commit. We run tests every time we push changes for code review, which is typically hundreds of times per day. Development is distributed among many teams, which own isolated portions of the codebase.

In this environment, the stability, repeatability and performance of our builds is critical:

* Build verification is time consuming, and test flakiness is extremely damaging to developer productivity. In particular, a broken master blocks tens on developers, which is unacceptably costly.
* Discrepancies between build results in the local environment and CI are frustrating, and cause developers to lose trust on the reliability of the tooling team and the CI verification.
* Errors in CI must be readily reproducible locally in order to enable a fast resolution.
* Developers should never be exposed to errors that they haven't introduced themselves. In a larger team, it’s unthinkable that one developer would be on the hook for fixing somebody else’s broken test.
* In the presence of large modules, sharding is a fundamental tool for parallelizing the verification.

Running tests in a non reproducible order gets in the way of all these goals. By forcing our tests to run in an order configured by a fixed seed we achieve the following goals:

* Test runs are entirely reproducible, and produce identical results locally and in CI.
* Using different seeds (in dedicated tests) allows us to detect ordering issues in a controlled environment.
* Making the seed an input to the test task ensures that the cache is always reliable.
* Developers can trust consistently that the errors they run into are their own. No more wasted time arguing with others about who should fix an error.
* Sharding is trivial to implement, with sharded results being stored in the cache.
* Combining deterministic test ordering with a couple of other tools (resetters of global state, test schedulers), our flakiness is essentially zero.

I appreciate the value of being able to identify dependencies on test ordering, but haphazardly exposing all developers to all test ordering issues is not an effective way to go about it. The job of the build tool is to provide a reliable environment that’s deterministic and flexible, and to offer developers the diagnostics tools they can use to find their own bugs.

**Comment by melix** [comment]
I think this should be configurable. In absolute, your tests _should not_ depend on ordering. If they do, then it should be explicit in the tests. Now, we reckon that it can be hard to figure out, or simply the test engine that you are using doesn't support explicit ordering.

We also have this feature in Gradle that we re-run the failed tests first, in order to get faster feedback locally. Last but not least, we have parallel execution of tests.

All-in all, this behavior should therefore be configurable. I think @bmuskalla has the right answer when he says that ideally we should have an option to have randomized order with a configurable seed. This seed should be collected as part of test results and build scans, so that one trying to reproduce the issue locally can rerun the test suite with the same seed.

**Comment by knut-estalea** [comment]
I have a situation where one test does some sort of byte code manipulation and redefines classes. Although the test passes the polluted class later causes a failure in another test. In order to narrow down the sequence of tests that cause the failure I need to be able to control the order of execution.

My thwarted attempt was to disable parallelism with `--max-workers=1` and then:
 1: Log the name of the test
```
test {
     beforeSuite { descriptor ->
        logger.lifecycle(" --tests " + descriptor)
    }
}
```
2: Explicitly run the tests in that order with `./gradlew test --tests A --tests B --tests C` and so on using the list from the previous step.
3: "Binary search" by cutting the list in half and rerun.

Unfortunately step 2 doesn't work, the tests run in a different order than I specify them on the command line.

**Comment by AlexLandau** [comment]
@knut-estalea: If it helps your particular case, I've found that the JUnit Platform [console launcher](https://junit.org/junit5/docs/current/user-guide/#running-tests-console-launcher) respects the order of tests given by multiple `--select-class` arguments. (NB: until 5.7 is released, you may need to add `--include-classname=.*` when running the console this way; see https://github.com/junit-team/junit5/issues/2259)

While Gradle (with `useJUnitPlatform()`) uses the same JUnit Platform APIs code that this console launcher is using, it doesn't expose the "select" configurations, instead only modifying the "include" filter, which doesn't affect ordering.

**Comment by knut-estalea** [comment]
Thanks @AlexLandau. Your suggestion was indeed the way I ended up tackling it (except I'm still on Junit4, so `java org.junit.runner.JUnitCore A B C ...`). I mentioned the problem here because it would be nice if Gradle could better support these kinds of use cases.

**Comment by EugenMayer** [comment]
It is hard to understand why this is still hanging in the air. 

Nobody in here argues with the fact, that tests should not depend on each other. So let's strike this argument for the list why this feature is needed and let's not repeat ourselfs on this argument over and over again.

I fact, having a deterministic order of tests helps you find that tests are dependent by accident (leaking) and all you want to have is reproducing this so you can find the cause and get back to "actually independent".

Having this as an opt-in feature, so using an optionally provided see or just something like `--use-alphanumeric-run-order` for simplicity would already fix all the mentioned issues and task.

It is not expected that this is active by default, let it be random by default, but let us enable to find those leaking tests.

Thanks!
