### ISSUE TITLE
Deprecation warning for deprecated configurations

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#8585]
The `compile` and `runtime` configurations are deprecated since years already, but there is no deprecation warning if you use them.
You can only see it from the docs, from the source or from the output of the `dependencies` task.
I myself only recognized it many versions after it was deprecated.
Many sites and turorials like e. g. mvnrepository.com or search.maven.org (wrote both a note) still advice to use `compile` and so this is what also makes it into the heads of people, especially if they come from Maven and are used to its scopes.
Imho if those configurations are used, a deprecation warning should be printed like for any other deprecated feature usage.
Most people I tell they are deprecated were not even aware of that as it is not clearly visible.

**Comment by melix** [comment]
So a bit more details on what we're planning to do. There are different things we're going to deprecate, and things we're going to remove.

For 6.0 and the `compile` and `runtime` configurations we need to:

- send a deprecation warning whenever a user (or a plugin) _declares a dependency_ in those configurations: nobody should use this configuration to declare dependencies, they should choose between `implementation` and `api`. Difficulty: the warning depends on which plugin is applied (there is no `api` for `java`, only for `java-library`)
- send a warning whenever a user (or a plugin) _resolves_ those configurations: they don't carry enough context and resolution is going to be _wrong_. It happens to work with some good defaults we use, but as we rollout more features this is definitely going to break (and already does in some cases)

For the `compileOnly` and `runtimeOnly` configurations:

- send the same warning when a user (or a plugin) _resolves_ those configurations: like `compile` or `runtime`, they are not meant for this. Because they predate the variant aware resolution era, they didn't have the appropriate flags. In order not to break builds, we didn't do anything about this.
- if possible, warn whenever such a configuration is _consumed_ by another project (either directly or via variant aware resolution)

Of course, this is _per source set_ (main, test, ...).

For 7.0 we need to:

- remove the `compile` and `runtime` configurations
- set the `canBeResolved` and `canBeConsumed` flags of the `compileOnly` and `runtimeOnly` configurations appropriately

**Comment by melix** [comment]
Here's an idea how such deprecations could show up in build scans:

![Selection_267](https://user-images.githubusercontent.com/316357/55633746-4768d980-57bd-11e9-8fd2-2552b76cb0f1.png)

**Comment by ljacomet** [comment]
In addition, we should no longer resolve `compile`, `runtime` and `compileOnly` in the `dependencies` and `dependencyInsight` tasks as well.

**Comment by eskatos** [comment]
How to surface the deprecated usage in IDEs could also be considered. For example, provided the list of deprecated configurations is available somehow, the Kotlin DSL generated accessors for deprecated configurations could be annotated with `@Deprecated(replaceWith = ..)` in order to be understood as such by IDEs. For Groovy scripts I guess the IDE should be given the same data to be able to highlight deprecated configuration usages.

**Comment by jjohannes** [comment]
I have spiked this in #9353, incorporating the requirements listed in this issue as follows:
- https://github.com/gradle/gradle/pull/9353/commits/4d1d9a10e010c1d163398b208b6e19c9a834b3b7
Add a deprecation mechanism to configurations. The mechanism allows you to define _alternative_ configurations that will be printed as part of the deprecations warning. This mechanism allows you to separately deprecate: 
  1. the ability to declare dependencies on the configuration
_(For this, the warning will say that the configuration will be removed otherwise it says that a specific usage of the configuration will become an error.)_
  2. the ability to consume the configuration 
  3. the ability to resolve the configuration. 
- Issue the warnings only in the places where a configurations is actually used/consumed/resolved.
  1.  https://github.com/gradle/gradle/pull/9353/commits/4cdb4457acc20f4c6fa7a5ef1938ce4f5a3d674 (declare)
  2. https://github.com/gradle/gradle/pull/9353/commits/b6d95e28f4d7a38ef0a0091105715bc69d4a3f7e (resolve)
  3. https://github.com/gradle/gradle/pull/9353/commits/4c042f6c42c6d944f17dfaa19eadc0484f14e3a8 (consume through attribute matching), https://github.com/gradle/gradle/pull/9353/commits/a461f0fad01a5770fba9d587492f9d25bde775ba (consume by directly defining the target configuration)
- https://github.com/gradle/gradle/pull/9353/commits/4329898b46bb860fa091c4dba1c9de5dcebeed2c
Exclude configurations where the resolving is deprecated from the reports:
- https://github.com/gradle/gradle/pull/9353/commits/7029b0bbae15bad5feab0ebac65a0216c9cdcbcb
Declare the deprecations for the Java plugins. I am not sure what we want to suggest in cases of consumption. Most likely, a plugin is doing something "undesired" in these situations and a more involved change is required to fix the issue. Maybe we don't want to suggest concrete replacement configurations then and just say "please use attributes" or something like this.
- https://github.com/gradle/gradle/pull/9353/commits/7d32e920c7168638af890cf2a5cc8fe0eac5cd78
Adjust documentation about _compileOnly_.

Since the deprecation information is stored in the configurations in this solution, it should be possible to use it to generate the annotations of the Kotlin DSL accessors. And we can add the needed information for build scans to the `ResolveConfigurationResolutionBuildOperationDetails` build operation. (I have not spiked these two things yet.)

I think the deprecation mechanism should be an internal API as it is bound to Gradle's versioning and is thus only useful for plugins delivered with Gradle. An issue to solve for the implementation is that the `ConfigurationInternal` interface is not part of `core`. We might need to move it or add another internal interface for the deprecation mechanism. 

I wonder: do we also need to add a warning when a configuration that will be removed is _extended_?

**Comment by jjohannes** [comment]
Progress on this:
-  ~Let the `gradle/gradle` build use 'implementation' dependencies #9509~
(on `master`)
- Reduce usage of compile/runtime configurations in tests and samples of `gralde/gradle` #9588 
(in review - on `master` afterwards)
- Deprecation of compile/runtime configurations #9353 (in progress - will only be merged for `6.0`)

**Comment by vlsi** [comment]
Are there plans to split `testCompile` into `testApi` and `testImplementation`?

Even though I do understand people should refrain from "depending on test artifacts", it does look weird when `compile` is deprecated while `testCompile` is recommended.

**Comment by jjohannes** [comment]
It's maybe not completely clear from the title/description of this issue, but `testCompile` will be deprecated as well. As will any `*Compile` configuration you get by creating a custom source set.

There is already a `testImplementation` configuration which you should use instead.

For sharing code between tests, we recommend the use of [_test fixtures_](https://docs.gradle.org/5.6-rc-1/userguide/java_testing.html#sec:java_test_fixtures), which is supported in Gradle `5.6` (RC available now) and which offers the `testFixturesApi` configuration.

**Comment by vlsi** [comment]
> For sharing code between tests, we recommend the use of test fixtures,

Thanks for the pointer. testFixturesApi seems to cover what I need.
