### ISSUE TITLE
Adding a class in a package with same name as a class in another package may break incremental compilation

### ISSUE THREAD

**Issue by gavra0** [gradle/gradle#8590]
Adding a top-level class may break incremental compilation if the added type changes the type resolution.

For the following example, the incremental compilation breaks.
```
// foo/A.java
package foo;
import bar.*;
public class A {
  Other getOther() { return null; }
}
// bar/Other.java
package bar;
public class Other {}
```
In the second run, add `foo/Other.java`:
```
package foo;
public class Other {} 
```
After the second run `foo/A.class` will not be updated and it will contain incorrect reference to `bar.Other` instead of `foo.Other`.

**Comment by lptr** [comment]
@oehme could you take a look at this please?

**Comment by oehme** [comment]
I can, is there a specific release deadline you have in mind?

**Comment by lptr** [comment]
None that I know of. The reason I pinged you is that the issue was assigned to the build cache team, and wanted to make sure it doesn't get lost.

**Comment by melix** [comment]
So the problem here is more a shadowing/Java semantics problem than a mapping one. It doesn't have to be in a top-level package: if you have one class `A` which is added in the same package as another class `B`, then it takes precedence over any other `A` class defined in the same package as `B` if `B` used a star import.

So we need to keep track of all "Simple class name -> List<Package>" mappings, so that if a class `A` is modified, we know we need to recompile all classes named `A` in other packages, just in case.

This looks like a rather uncommon edge case so no bug fixing is planned short term, but happy to reconsider the decision if you think it's common enough.

**Comment by gavra0** [comment]
Please do not close it, in case other users hit this problem having an issue to point them to is quite useful.

**Comment by melix** [comment]
I think that for this to be fixed we need to track all _resolution attempts_ during compilation. I'm not sure that the javac APIs would let us know about this.

**Comment by gavra0** [comment]
I think this is doable if using https://docs.oracle.com/javase/10/docs/api/com/sun/source/tree/TreeVisitor.html APIs. Combining this info with the resolution rules specified in the spec, it should be possible to get this information (you'd also get precise constants tracking for free with a compiler plugin).
