### ISSUE TITLE
TaskExecutionListener.afterExecute sent long after task completes when Workers are used.

### ISSUE THREAD

**Issue by jdochez** [gradle/gradle#8630]
When using 
https://docs.gradle.org/current/javadoc/org/gradle/api/execution/TaskExecutionListener.html

the afterExecute() method javadoc's are clearly stating that the callback will be called immediately after the task completes. 

However if the task spawns a few Worker items and does not wait for their completion the afterExecute() will be called at random times and certainly long after the last worker completed (which should represent the logical completion time for the task). 

It seems the event is only sent once Gradle is looking for the next task to pick and is updating the outstanding "running" ones. 

The information in the Gradle scans is also incorrect, making task profiling incorrect and unpredictable.

**Comment by ducrohet** [comment]
Just a heads up. Workers are turned on by default in 3.5 canary 12. This means console output and build scan are going to start showing wrong data because of this.

**Comment by adammurdoch** [comment]
A task isn't complete until all of its worker actions have completed _and_ its task actions have completed. The event fires once this has happened. This way, the timing information is actually correct.

**Comment by ducrohet** [comment]
That is not what we are seeing.
Here's a scenario representing what we see.
Let's say task A uses workers and is a dependency of B which has other dependencies that run long after A is done. What we see is A getting its end event fired just before B starts rather than when A's worker end.

We show some traces using our own profiling code which tracks a task actions and workers vs a scan of the same build. In our profiling code we actually correct (in post-processing) the end event to the task to be the end of the latest task action or workers.
I'll send you details.

**Comment by bigdaz** [comment]
The observed behaviour can be explained by the fact that Gradle will _always_ acquire the project-mutation lock before completing a task action. 

So in the example above:
- After `task A` submits the work items, it releases the project lock
- `task A1` (another dependency of `taskB`) grabs the lock and starts executing
- All work items of `task A` complete, but `task A` must wait `task A1` to complete so it can acquire the project lock, collect the failures and fire the "complete" event.

With the current implementation, Gradle will always acquire the project lock in order to complete the task action. This behaviour could be improved: there are certainly cases where this is not necessary (eg. when no user code will be invoked after the task action completes).  

However, the handler for `TaskExecutionListener.afterExecute` has access to the `Project` object, and thus Gradle must acquire the lock before such a listener is invoked.

**Comment by ducrohet** [comment]
That makes sense. The question is whether there are any plans to change this?
It makes the gradle scan output very misleading.

**Comment by bigdaz** [comment]
We are definitely planning on fixing build scans so that they correctly report task execution times, including the time spent waiting for workers to complete, waiting for locks, etc. We'd also like to make additional timing information available via `org.gradle.tooling.events.ProgressListener`.

We don't have current plans to address the issue reported here: `TaskExecutionListener.afterExecute` sent long after task completes when Workers are used.

**Comment by bigdaz** [comment]
@ducrohet @jdochez  It turns out that fixing this at the build scan level is not really practical, so we're instead going to fix the issue directly in Gradle (#9611). In essence, this will mean that as soon as the last work item completes the task will be marked as complete, _assuming that no additional work is configured for the task_.

If the task has additional actions configured (e.g an extra `doLast`), or if a `TaskExecutionListener` is added to the graph, then we will need to reacquire the project-mutation lock prior to completing the task. In these cases, the current behaviour will remain unchanged.

Since it appears that you are using a `TaskExecutionListener` in the Android plugin, we'll need to find an additional fix in order for you to benefit from this improved behaviour.  So I'm curious: what do you use a `TaskExecutionListener` for in the Android plugin? (Please link to the sources if that's easy)

Depending on the requirements, we might decide to add some additional events to `org.gradle.tooling.events.ProgressListener`, or we might choose to add a new `TaskExecutionListener` API that does not provide access to the backing `Project` instance.

**Comment by jdochez** [comment]
@bigdaz , we use it to measure task execution spans. This is useful internally to create chrome traces but also for users who opted in, we upload task execution span data to our server and create performance/usage graphs from it.

Find code [there](https://android.googlesource.com/platform/tools/base/+/f63a15fd91a15e418d934bb134854e53e99920cc/build-system/gradle-core/src/main/groovy/com/android/build/gradle/internal/profile/RecordingBuildListener.java) and in associated classes in the same package. 
let me know if you need more details.

**Comment by bigdaz** [comment]
@jdochez Thanks. There's already a [Tooling API mechanism](https://github.com/gradle/gradle/blob/master/subprojects/tooling-api/src/main/java/org/gradle/tooling/events/ProgressListener.java) for getting the task start/finish times without requiring a task listener. Is there a reason you couldn't use that? Are you collecting this data for build invocations that are _not_ triggered by the Tooling API?

**Comment by jdochez** [comment]
@bigdaz That's correct, first it predates the Tooling API mechanism you referenced and second, a lot of our users build from the command line and we want those numbers. Having said that, we have worked around internally the issue I initially filed so I cannot say we are in need of a solution for the TaskListener implementations. As long as the build scans are correct, feel free to close this.

**Comment by eugene-krivobokov** [comment]
> There's already a Tooling API mechanism for getting the task start/finish times without requiring a task listener

Is it possible to register this ProgressListener inside a custom plugin?
We collect high-level build metrics in it.
