### ISSUE TITLE
Property convention doesn't work when a property's value has been explicitly cleared

### ISSUE THREAD

**Issue by king-tyler** [gradle/gradle#8635]
### Expected Behavior
Explicitly setting a property to `null` and providing a convention value should return the convention's value.

### Current Behavior
Gradle fails with `IllegalStateException: No value has been specified for this provider`

### Steps to Reproduce
```
def prop = objects.property(String)
prop.set(null)
prop.convention('a')
println prop.get()
```

### Your Environment
Gradle 5.2.1

**Comment by big-guy** [comment]
@adammurdoch WDYT?

**Comment by adammurdoch** [comment]
This was intentional, but maybe not the best choice. The convention is used only until someone expresses an opinion about the property's value, and setting the value to `null` currently means 'there is no value' and counts as expressing an opinion. We could probably change setting the value to `null` to mean 'discard any explicit value' instead, so that the convention would apply again after this. I'd probably also replace `set(null)` with a new method that explicitly discards the value and also forbid `set(null)`, via deprecation.

**Comment by big-guy** [comment]
@king-tyler do you have a "real world" example of why you would explicitly set a property to null?

**Comment by adammurdoch** [comment]
https://github.com/gradle/gradle/pull/9776 changes the behaviour of `set(null)` to use the property's convention, if set.
