### ISSUE TITLE
Support classifiers in composite build dependency substitution

### ISSUE THREAD

**Issue by Kameecoding** [gradle/gradle#8666]
### Expected Behavior

Gradle should correctly find and substitute dependencies that have classifiers.
### Current Behavior

Gradle ignores the classifier and tries to substitute with the unclassified dependency.
### Context

We have dependencies on multiple artifacts (with classifiers) between composite builds.

###  Example

https://github.com/napstr/gradle-composite-classifiers

### Related issue

https://github.com/gradle/gradle/issues/1553

**Comment by ljacomet** [comment]
Could you provide a setup that reproduces the issue? Would help clarify exactly what you are trying to achieve.

**Comment by napstr** [comment]
Ahoy, not OP, but I have encountered the same issue. I have created a small (arguably contrived) example demonstrating the issue here: https://github.com/napstr/gradle-composite-classifiers
Please let me know if you need more information.

**Comment by LukasWysocki** [comment]
Shouldn't the "waiting for:contributor" label be removed as the reproducer is now provided?
BTW: Hit the same problem.

**Comment by thelateperseus** [comment]
I also hit this problem. Can someone from the Gradle team take a look at the example provided by @napstr ?

**Comment by lstreepy** [comment]
We're having the exact same problem, which prevents us from using composite builds at all in our scenarios.

**Comment by jjohannes** [comment]
The underlying modeling issue is that is causing this misaligned behaviour is that  the _classifier_ concept is too 'weak' to carry enough knowledge.  Looking at https://github.com/napstr/gradle-composite-classifiers:

I think the original description is not completely accurate. Gradle is looking for the right artifact - `projectA-tests.jar` - but does not know how to build it in the context of a composite, because the published metadata does not give any information about that as well (in `pom`, classified jars are not mentioned). So `projectA-tests.jar` becomes a simple artifact and the information by which task it was built is lost.
Although there might be a way to fix this for the composite case, as in theory Gradle knows this when everything is done locally, there is a better way to model this sort of thing now in Gradle 6 which is [feature variants](https://docs.gradle.org/6.0-rc-1/userguide/feature_variants.html#sec::declare_feature_variants).

So in the sample _Project A_ you can remove the test jar task declaration and the customizations in the publishing block and do the following  instead:

**projectA/build.gradle**
```
java {
  registerFeature('tests') {
    usingSourceSet(sourceSets.test)
  }
}

publishing {
  publications {
    mavenJava(MavenPublication) {
      from components.java
    }
  }
}
```

Note that there is no more _custom artifact_ declaration in the publication itself.  With Gradle 6 we discourage that in general and instead you should define everything in terms of [components with variants](https://docs.gradle.org/6.0-rc-1/userguide/publishing_customization.html#sec:adding-variants-to-existing-components). Which is what `registerFeature()` is doing in the background.

Now when you publish with Gradle 6, Gradle will also publish a [Gradle Module Metadata](https://docs.gradle.org/6.0-rc-1/userguide/publishing_gradle_module_metadata.html) file which contains the information about the test variant. This variant can then be consumed by Project B and that works for both the published and the composite case. Because both times we now deal with a well-modeled variant of the _projectA component_ and not just with an artifact.

**projectB/build.gradle**
```
dependencies {
  testImplementation('org.example.projectA:projectA:0.0.1-SNAPSHOT') {
    capabilities {
      requireCapability('org.example.projectA:projectA-tests')
    }
  }
}
```

**Comment by napstr** [comment]
@jjohannes thank you for the detailed guide! I have already tried out the new Gradle module metadata and it was a mostly positive experience. It will be some time until I can try the features/capabilities feature that you described so let's hope some of the other users that voiced their interest in this issue can try it out and report back :)

**Comment by Kameecoding** [comment]
@jjohannes does this support zip files, simple files or directories?

because I haven't been able to find a way to declare that a project produces a zip distribution and another project is dependent on that zip.

**Comment by jjohannes** [comment]
@Kameecoding yes definitely. The _feature variants_ mention above are specifically designed for Java/JVM libraries, but the underlying _variant-aware dependency management_ can be used to share arbitrary artifacts between projects. 

This is documented here: https://docs.gradle.org/current/userguide/cross_project_publications.html#sec:variant-aware-sharing

If you only have local projects, you can share folders. If you want to publish as well, an artifact is usually a single file (simple or zip).

**Comment by krico** [comment]
@jjohannes your example is totally awesome!
It took me quite some time to find it though...  
I would suggest adding at least a pointer to it from https://docs.gradle.org/current/userguide/composite_builds.html

**Comment by scottsue** [comment]
Is there a potential timeline for this?  Composite builds would make things much more efficient as we have a multi-project layout with dependencies.  At the moment it is very cumbersome having to continually refresh Gradle dependencies when working across projects

**Comment by melix** [comment]
There's not really any timeline because there's not really a fix we can apply. That's why the [strategy described above by Jendrik](https://github.com/gradle/gradle/issues/8666#issuecomment-546908885) is a better fit. Does it work for you?

**Comment by scottsue** [comment]
Apologies I didn't see the example described above as a potential fix.  I'll see if I can get it going in our environment

**Comment by scottsue** [comment]
Thanks @melix / @jjohannes.  That looks to have worked!

**Comment by swpalmer** [comment]
If classifiers are not supported in composite builds, what is the best-practice for consuming something like javadoc jars in another project?  The standard still seems to be to use classifiers for 'javadoc' and 'source'.  I have a project that I want to use composite builds with that needs to collect javadoc jars from 3 other projects.  (I also have generic zip artifacts I need to access in composite builds, but variants will likely work for that.)

**Comment by swpalmer** [comment]
It's not clear to me how classifiers can work between sub-projects, but not for composite builds.  Doesn't Gradle have access to the same information in both cases? It has the build.gradle file for all projects involved.

**Comment by jjohannes** [comment]
@swpalmer As I elaborated [above](https://github.com/gradle/gradle/issues/8666#issuecomment-546908885), Gradle might be able to support this, but it is unlikely that we will invest into making this work as the way forward for Gradle is to use/recommend [variant aware dependency resolution](https://docs.gradle.org/current/userguide/variant_model.html) for all dependency resolution use cases.

For consuming Javadoc:

The build producing the Javadoc should use the [withJavadocJar feature](https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_packaging) of Gradle:

```
java {
    withJavadocJar()
}
```

On the consuming side you can then request the Javadoc variant on a _resolving configuration_:

```
configurations.create("javaDocPath") {
        attributes.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage, Usage.JAVA_RUNTIME))
        attributes.attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category, Category.DOCUMENTATION))
        attributes.attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType, DocsType.JAVADOC))
        extendsFrom(configurations.runtimeClasspath) // <-- if you want the Javadoc of all the runtime classpath
}
```

We are aware that especially the APIs for consuming are hard to use. And that's a topic we plan to improve on in an upcoming 7.x release (#9834).

**Comment by swpalmer** [comment]
Thanks for the update.  I did eventually figure out to use:

    withJavadocJar()

for producing the javadocs, and: 

    attribute(DocsType.DOCS_TYPE_ATTRIBUTE, objects.named(DocsType,DocsType.JAVADOC))

on the consuming side.  Sorry, I should have came back to post an update.

Isn't that single attribute enough?  I understand why on the producing side all three attributes should be provided, but the javadoc doctype seems to be enough to get the javadocs as a consumer.  Is it considered bad practice to not specify all three attributes when consuming?  It's already a bit verbose compared to the classifier that I'm replacing, though I do get that much richer information is being communicated.

One big issue with the variant-based APIs is that the right thing to do is difficult to discover on your own. It's not so much the "hard to use" aspect as it is hard to find the right documentation or an example that fits.  Those pre-defined constants for Usage, Category, and DocsType don't appear to be mentioned in the variant documentation.

**Comment by jjohannes** [comment]
Yes in this case the `DocsType.JAVADOC` is enough because it already clearly identifies a variant. So it is enough for the matching engine to deliver the right result.

If you strictly follow what the attributes intended meaning, you _should_ set the other two attribute (Usage and Category) because they are related as documented [here](https://docs.gradle.org/current/userguide/variant_attributes.html#ecosystem_independent_standard_attributes). (The constants are linked from there but only in Javadoc.) However, this is more important when implementing plugins or publishing libraries that may be used in a new context in combination with other things. Then the more information a variant has, the higher the chance is that Gradle can match the right one (if there are multiple) or give a good error (if a variant is missing).

So yes, the issue is a combination of not-good-enough documentation and too verbose/unclear API. I think we have to improve this on both sides.

**Comment by quentinflahaut** [comment]
@napstr I forked your repository and pushed a workaround that I used to do for this problem:
https://github.com/quentinflahaut/gradle-composite-classifiers
However it doesn't work on gradle 7 .. :(
Does someone have an idea to make this workaround keep working on gradle 7 ?
