### ISSUE TITLE
Add ability to set platform-bom for all dependencies configurations

### ISSUE THREAD

**Issue by Alexuy** [gradle/gradle#8723]
### Expected Behavior

It would be nice set platform BOM file for all dependencies configurations, like this:
```
    dependencies {
        all(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
        )
    }
```
For example, you may see that with using spring dependencyManagement plugin.

### Current Behavior

Now, i need set platform BOM for every dependencies configuration, like this:
```
    annotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
    )

    implementation (
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
    )

    testAnnotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
    )

    testCompileOnly(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
    )

    testImplementation(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
    )

    testRuntimeOnly(
            platform("org.springframework.boot:spring-boot-dependencies:$ver.springBoot"),
    )
```

**Comment by altro3** [comment]
Perhaps this is already implemented and I just do not know about it, could you answer, please?

**Comment by ljacomet** [comment]
There is no plan to offer a baked in DSL solution for adding a single dependency to all configurations as it is not a frequent occurrence.

For example, in the report, the BOM platform really does not belong to any of the `test*` configurations.

As can be seen [in the documentation](https://docs.gradle.org/5.2.1/userguide/java_plugin.html#sec:java_plugin_and_dependency_management), these are used either by `testCompileClasspath` or `testRuntimeClasspath` which are the _resolved_ configurations and they all extend `implementation` so the constraints sourced from the BOM platform _will_ be available. And the same stands for `compileClasspath` and `runtimeClasspath`.

Also note that the following is valid (but should not be used for this):
```
configurations.all {
    // Manipulate the configuration
}
```

**Comment by altro3** [comment]
It is a pity ... Well, you will have to continue using the spring dependency-management-plugin.

It seems to me that in order to start using your depndency management implementation you need to add more flexibility to the settings and options for using this feature.

In this case, I want only to limit the developers in choosing the versions of libraries, so that we avoid fragmentation in our microservice architecture, but I don’t want to limit them to versions from the bom file. Unfortunately, in the implementation of this need, the spring approach wins.

**Comment by melix** [comment]
As @ljacomet explained, you don't need this. By declaring your platform constraints on the `api` configuration they _will_ be inherited in most cases. 

By using `dependencies.all` and basically using a hammer, for sure you avoid asking yourself questions, but those are _good_ questions to ask. Like, what does it mean to use the same constraints on the `annotationProcessor` configuration? If it makes sense, sure go ahead, but be explicit. The Spring approach is a hammer that has consequences.

**Comment by melix** [comment]
`runtimeOnly` is _not_ a configuration that is resolved. So it has absolutely no meaning to add the constraints there. The configuration which is going to be resolved is _compileClasspath_, which will inherit from `api`, and therefore you will get your constraints.

**Comment by altro3** [comment]
I realized that your approaches are different, although initially I thought that the platform would allow me to get rid of another external plug-in. But, as I said, the approach of the spring command is closer to us, we will have to leave everything as it is and continue to use the plugin, but about the Platform we just have to keep in mind :-)

**Comment by altro3** [comment]
@melix soryy, mb. Bad example, i mean annotationProcessor, compileOnly, implementation and testImplementation - developers should not think about which version we use, but connect only our BOM file

**Comment by melix** [comment]
Again, the only relevant case in your example is `annotationProcessor`. `compileOnly`, `implementation`, `testImplementation` are just buckets of dependencies (or constraints). If you want your platform to "leak" everywhere, then you should declare it as an `api` dependency. The consequence is that when you resolve _compileClasspath_ or _runtimeClasspath_ or _testRuntimeClasspath_, because they _all_ extend `api`, you will get the constraints applied.

And I would argue that there's absolutely no reason why you should share the BOM with `annotationProcessor` , which is a "compiler plugin" and can use very different dependencies.

Gradle works by inheritance of configurations, so `compileClasspath` _extends from_ `api`, `implementation` **and** `compileOnly`, so there's no reason to duplicate the application of the BOM to all of those.

**Comment by altro3** [comment]
Simply, I don’t understand only one thing - you provide the opportunity to use one BOM file for all dependency configurations, all I asked for is just a simplification so that I can not duplicate the dependence on my BOM file in each individual configuration.

Perhaps you misunderstood me. The option that I described in the issue is not mandatory, I just asked for a mechanism that will give me the opportunity not to duplicate the dependency on the platform in each dependency configuration

**Comment by melix** [comment]
And I'm explaining to you that you don't have to duplicate it. Because the only relevant configurations are the ones you _resolve_ (that is to say _compileClasspath_, _runtimeClasspath_, _testCompileClasspath_, _testRuntimeClasspath_), and that those configurations _extend from_ the `api` and `implementation` configuration, the *only* thing you have to do is to declare the platform on the `api` or `implementation` configuration. (_annotationProcessor_ apart). Everything else is redundant declaration that will only slow down your build.

**Comment by altro3** [comment]
@melix Oh, sorry! Now I understand. You need to add the use of the java-library plugin and add the api block with one dependency - a platform like this:
```
plugins {
     id 'java'
     id 'java-library'
}
<...>
dependecies {
     api (
         platform ("org.springframework.boot: spring-boot-dependencies:$ver.springBoot"),
     )

<...>
}
```
and leave this dependency for the annotation Processor.

Then this is what you need. Thank!

Only the last question: does the platform need to be added to the testAnnotationProcessor block?

**Comment by melix** [comment]
You don't need to apply both `java` and `java-library`: `java-library` is enough. And no, you don't need to add it to `testAnnotationProcessor` (just like you don't duplicate all your dependencies between iplementation and test).

**Comment by altro3** [comment]
Big thanks you for help! :-) Now everything became clear.

PS Yes, I have never used the java-library plugin, because You released it recently. For 8 years of using gradle, I’ve got used to the java plugin.

**Comment by melix** [comment]
Same would work with the `java` plugin: just use the `implementation` dependency, it would behave the same (because of inheritance as I explained).

**Comment by ChristianCiach** [comment]
When using spring boot, I usually have to apply the platform to at least three configurations: `api`, `annotationProcessor` and the spring-specific configuration `developmentOnly`. This is cumbersome and that's the reason why we continue to use the spring dependency management plugin. Just FYI.

**Comment by nbrugger-tgm** [comment]
Yes it is annoying to add the bom for every custom configuration by plugins (even inbuilt ones)
Example: 
 - `war` plugin: `providedRuntime`
 - `org.liquibase.gradle` plugin: `liquibaseRuntime`
 - `java` plugin: `annotationProcessor`, `api`
 - `io.micronaut.aot` plugin: `aotPlugin`
 
There are many plugins that add scopes where it makes sense to apply the platform to
- You do not want to provision your db with a different version at compile time (liquibaseRuntime) than at runtime
- You do not want to have the same dependency in `providedRuntime/Compile` than in `implementation` or `annotationProcessor`
- You do not want to use a different version of micronaut for your app (`api`, implementation ...) and `aotPlugin`
- You do not want to use a different mapstruct version at runtime than with your `annotationProcessor`

Also `configurations.all` doesn't work any more since not every configuration is declarable so one does need to create a helper which makes it hard for new talent to understand what is going on

```kotlin
dependencies {
     platform("a.b:c:123")
}
```
is much easier to understand than
```kotlin
fun DependencyScope.globalPlatform(platform: Any) {
        configurations.configureEach {
            if (isCanBeDeclared) {
                this@globalPlatform.add(name, platform(platform))
            }
        }
}
```

**Comment by altro3** [comment]
@melix Hi! it was me under a different account (I don't remember why I changed my account). In general, the problem as such has not been solved so far. The minecraft plugin partially solves the problem, but only when using the micronaut and standard configurations.

As it was correctly noted, there are still 100,500 plugins with their own configurations that you want to use in the same version space.

Still, I would like to have a mechanism for setting the platform for all configurations (as well as many others, judging by the comments)

**Comment by FyiurAmron** [comment]
There's also `kapt`, FWIW. TBH, the argument "it's only `implementation`, you don't need it" doesn't really hold.
