### ISSUE TITLE
The inherited tests are not runned if that superclass is in an Android Library module

### ISSUE THREAD

**Issue by BraisGabin** [gradle/gradle#8766]
I opened this issue in [the android tracker](https://issuetracker.google.com/issues/124024521) but they pointed me here as a gradle bug.

I have an abstract class that have some methods annoted with `@Test`. Then I extend this class and check that some specific implementations pass those tests. This worked fine when I had all my code in one module.

But when I move this class in a `test-commons` module and the specific implementations in other modues that test are not runned anymore when I execute `./gradlew test` (they do run as expected when I use AS).

I created a little project to demostrate this issue: https://github.com/BraisGabin/agp-junit-error

I found that this problem is related with the android libraries. Because if I move the code to a java library it works properly. You can check this behaviour if you checkout this commit: https://github.com/BraisGabin/agp-junit-error/commit/f0adc6faa2cbd3bd54ce3a2659215b1b9b89a4b1

I'm using Junit 4.12 and I tested it with gradle `4.10.1` and `5.2.1`

**Comment by drewhamilton** [comment]
Just want to chime in that my team is just now running across this issue as well.

Possibly notable is that [the documentation](https://docs.gradle.org/current/userguide/java_testing.html#sec:test_detection) mentions scanning *jar* files on the classpath but not aar files. Since Android libraries are aar files, perhaps this is as simple as adding a second extension to scan for superclass tests? Just a guess though; I'm not familiar with the Gradle source code.
