### ISSUE TITLE
Unable to specify an include directory

### ISSUE THREAD

**Issue by donalmacc** [gradle/gradle#879]
### Expected Behavior
When defining a component, I should be able to define a directory to be added to the search path. Not all directories should be known as source sets to gradle.

### Current Behavior
To add an include directory to a component, either the directory needs to be added as a source set (along with a file filter), or a prebuilt library must be specified, and linked with an API dependency.

### Context
We are using the google test plugin to generate test suites for our code. Our tests are testing the internal functionality of our library, and the test code is placed in a `Test` directory and as such should have access to the headers defined in our `Private` folder. However, we do _not_ want to export those headers for other libraries to use (they're Private). As such, we want to add the Private folder to the list of search paths for the compiler. 

### Steps to Reproduce (for bugs)
[IncludeTestGradle.zip](https://github.com/gradle/gradle/files/597273/IncludeTestGradle.zip)
Execute `gradle build` from the directory. Note the private header inside PrivateIncludes can't be found. (search path isn't set up)

### Your Environment
gradle 3.1, Windows 10 x64, MSVC 2013

**Comment by lacasseio** [comment]
Thanks @donalmacc for the well-formed issue. There is 2 issues I can see here and 1 workaround.

### Issue 1: _Public_, _private_ and _protected_ includes issue
Currently, Gradle doesn't model any distinction between public (exported API) headers, private headers and protected (internal API) headers. This is a direction we want to go. The JVM already started modeling a similar behavior with exported API. This requires a lot of work in order to get it right. It becomes especially challenging with [transitive dependencies](https://github.com/gradle/gradle/issues/801).

### Issue 2: Side-by-side compilation unit/headers are not handled properly
A pattern often found in native is to locate private headers side-by-side with the compilation unit and `#include` them via a relative path. Unfortunately, the working directory for the compiler is set to the `Project.getProjectDir()` which force you to specify the relative path from that point. This is counter-intuitive regarding the mentioned pattern. This shouldn't be hard to fix and could be easily done via a contribution.

### Workaround regarding specific include path
A specific include path can be added via compiler flag (`/I` on VC++ and `-I` on GCC and Clang). These flags are specified at the binary level:
```
model {
  components {
    main(NativeExecutableSpec) {
      binaries.withType(NativeBinarySpec) {
        cppCompiler.args "-I /path/to/includes"
      }
    }
  }
}
```
This workaround does have its limitation regarding Visual Studio IDE integration. The `visual-studio` plugin won't pick up those flags which will cause the IntelliSense to fail for symbols defined in those include paths. Those paths can be added through the manipulation of the `vcxproj` generation.

**Comment by zxtwonder** [comment]
I am building our potentially cross-platform and cross-language build environment entirely on gradle and the lack of support for adding component private include path is a blocking issue. Adding compiler flag is not maintainable across a lot of components and different tool chains...

At the meantime, there seems to be a better workaround, taking advantage of source set dependency and NativeDependencySet. Basically, we have the source set depend on a specially generated NativeDependencySet, which returns the private include paths from its getIncludeRoots() function. As a result, the private include paths are added when compiling the source set, but will not be exposed to dependents of this component due to gradle's dependency is not transitive.

This workaround is tool chain neutral and plays nice with VS integration.

Simplified code to demonstrate the concept:
1. Construct NativeDependencySet to return private include paths (in Java)
`
    public static NativeDependencySet getPrivateHeaders(FileCollection privateHeaders, FileCollection emptyCollection) {
        return new NativeDependencySet() {
            @Override
            public FileCollection getIncludeRoots() {
                return privateHeaders;
            }

            @Override
            public FileCollection getLinkFiles() {
                return emptyCollection;
            }

            @Override
            public FileCollection getRuntimeFiles() {
                return emptyCollection;
            }
        };
    }
`

2. Add the dependency set to the source set (in build.gradle)
`
    sources {
        cpp(CppSourceSet) {
            source {
                srcDir 'srcDir'
                include '*.cpp'
            }
            exportedHeaders {
                srcDir 'publicHeaderDir'
            }

            lib BuildUtil.getPrivateHeaders(
                    files('privateHeaderDir1', 'privateHeaderDir2'),
                    files())
        }
    }
`

**Comment by lacasseio** [comment]
Thanks for sharing this with us @zxtwonder.

**Comment by lacasseio** [comment]
No additional work will be done on the software model plugins unless it's a blocker for current users. The majority of this issue is now fixed in the new native plugin. Reopen on [gradle/gradle-native](https://github.com/gradle/gradle-native).
