### ISSUE TITLE
Links to Java platform classes go to 404 from Gradle documentation

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#8809]
This tries to link to `java.lang.String` from the JDK docs:
https://docs.gradle.org/current/javadoc/org/gradle/api/invocation/Gradle.html#getGradleVersion--

which goes to this URL:
https://docs.oracle.com/en/java/javase/11/docs/api/java/lang/String.html?is-external=true

And this is a 404.  I'm not sure if this has stopped working recently.

It seems like we should be linking to JDK8 docs instead of JDK11 since that's the minimum version we support.

@eriwen is this new?

**Comment by eriwen** [comment]
Seems like it might be related to https://github.com/gradle/gradle/commit/568a0b932fc7e879c7f212db14d19a9499ce1a3c @big-guy

**Comment by lacasseio** [comment]
It seems to be an issue still present with JDK 11.0.2. It seems to be fixed in JDK 11.0.3 and the later JDK 12. Instead, I reverted the change and used `--source 8` which solve the issue for now. We can revisit later. The change is going through CI now and we can verify it fix the links.

Couple open questions:
- Should we write a test to ensure this never happens?
- Should we include the fix in 5.3.1 as it will limit the documentation bug until we roll a backport to the already published documentation?

**Comment by lacasseio** [comment]
PR: https://github.com/gradle/gradle/pull/8863

**Comment by lacasseio** [comment]
The breakage affects 5.2-rc-1 documentation onward.

**Comment by big-guy** [comment]
I say let's leave 5.2/5.2.1/5.3 broken for now. I opened a new issue to fix it. I think it's finicky to fix.

I've cherry-picked it to release for 5.3.1.
