### ISSUE TITLE
Gradle doesn't use Maven repository URLs from pom.xml when looking for transitive dependencies

### ISSUE THREAD

**Issue by unix-junkie** [gradle/gradle#8811]
Consider I have a project `A` which depends on library `B` which, in turn, has a transitive dependency `C`, so that the dependency graph looks like this:

```
A -> B -> C
```

Both `B` and `C` are hosted at two different custom _Maven_ repositories (let's say, `https://repo.example.com/xyz/` for `B` and `https://repo.something.org/abc/` for `C`), and `B`'s `pom.xml` references `https://repo.something.org/abc/` to aid the dependency resolution:

```xml
  <dependencies>
    <!-- C -->
    <dependency>
      <groupId>org.something</groupId>
      <artifactId>abc</artifactId>
      <version>4.5.6</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
  <repositories>
    <repository>
      <id>abc</id>
      <url>https://repo.something.org/abc/</url>
    </repository>
  </repositories>
```

Whenever any _Maven_ project references `B`, _Maven_ successfully resolves the location of the transitive dependency (`C`).

### Expected Behavior

_Gradle_ should implicitly resolve the location of the transitive dependency (`C`), similarly to _Maven_

### Current Behavior

_Gradle_ (5.0, 5.1 and 5.2) does not, requiring that repository URLs for _each_ transitive dependency are explicitly listed in the `repositories {}` section of a `B` API client.

### Context

I've written a custom _Gradle_ plug-in which relies on a library available from a non-standard _Maven_ repository. Now, all projects which use this plug-in must explicitly reference that repository in their build files:

```kotlin
// build.gradle.kts
buildscript {
    repositories {
        maven("https://repo.something.org/abc")
    }
}
```

More context is available [here](https://stackoverflow.com/questions/55246488).

### Steps to Reproduce

* Create 2 _Gradle_ projects (`B` and `C`) which depend on each other (via either `implementation()` or `api()`). 
    * Make sure `B`'s classes indeed depend on those from `C`.
    * Make sure `B`'s `pom.xml` references `C`'s _Maven_ repository location.
* Publish `B` and `C` into two different _Maven_ repositories.
* Create a client project (`A`) which depends only on `B`.
* List the `B`'s repository location in the `A`'s `repositories {}` section.
* Try to build `A` via `gradle build`. The build will fail.

If the above steps are not clear enough, let me know, and I'll provide and publish self-contained examples.

### Your Environment

```
$ uname -a
Linux unit-725 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux
$ java -version
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
$ gradle -version

------------------------------------------------------------
Gradle 5.1.1
------------------------------------------------------------

Build time:   2019-01-10 23:05:02 UTC
Revision:     3c9abb645fb83932c44e8610642393ad62116807

Kotlin DSL:   1.1.1
Kotlin:       1.3.11
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_152 (Oracle Corporation 25.152-b16)
OS:           Linux 4.9.0-8-amd64 amd64
```

**Comment by ljacomet** [comment]
Thanks for the report.

There are actually good reasons for the behavior of Gradle:
* Gradle places a lot of importance on the _source_ of a dependency. For Gradle, `org:foo:1.0` from Maven Central and `org:foo:1.0` from JCenter are considered different things. This is why repository ordering and [filtering](https://docs.gradle.org/5.3/userguide/declaring_repositories.html#sec::matching_repositories_to_dependencies) matters.
* Repository hijacking has been [demonstrated as an attack vector](https://blog.autsoft.hu/a-confusing-dependency/) and so having a system that effectively, transitively and transparently, allows dependencies to be downloaded from any repository is not safe.

Because of these reasons, this is a change that is unlikely to happen.

There are however options for your plugin:
* [Shadow](https://github.com/johnrengelman/shadow) that exotic dependency into your own plugin
* Motivate the owner of that library to publish it to a well known repository, or in your plugin's repository
* Configure your plugin's repository to also mirror that other repository

**Comment by unix-junkie** [comment]
@ljacomet Louis, thank you for the clarification!

**Comment by big-guy** [comment]
@ljacomet I think we can go ahead and close this based on your reasoning.  This related issue was closed for a similar reason: https://github.com/gradle/gradle/issues/4106
