### ISSUE TITLE
gradle --no-daemon starts a daemon and logs to ~/.gradle/daemon

### ISSUE THREAD

**Issue by schildbach** [gradle/gradle#8832]
### Expected Behavior
If I pass `--no-daemon` I'd expect to not use the Gradle daemon. At least versions 3.4.1 and 4.4.1 behave as expected.

### Current Behavior
At least on versions 5.2.1 and 5.3, Gradle daemon is used and logfiles at `~/.gradle/daemon` created. This is a security risk for me since very sensitive information is logged without my content. I pass `--no-daemon` to prevent such information leakage.

### Steps to Reproduce (for bugs)
* `rm -r ~/.gradle/daemon`
* `gradle --no-daemon --help`
* `ls -la ~/.gradle/daemon`, your stuff will be there.

### Your Environment

* Ubuntu Bionic
* Various versions of gradle, manually installed

**Comment by big-guy** [comment]
`--no-daemon` doesn't prevent a daemon process from running (even in 3.4.1 and 4.4.1).  It only prevents a long running daemon. When the requested build requires JVM settings that are incompatible with the one currently running, Gradle will start a "single use daemon".  You should see a message at the start of the build.   

In Gradle 5.0, the default memory limits for the JVM started by the gradle/gradlew shell script changed from unlimited to 64MB and the Daemon changed from 1GB to 512MB. You're probably seeing a single-use daemon because of this.  You can tweak this to get back to the old behavior: https://docs.gradle.org/current/userguide/upgrading_version_4.html#rel5.0:default_memory_settings, but keep in mind that this doesn't completely eliminate the use of the daemon.  IDE integration and Gradle TestKit tests can also require Gradle daemons.

WRT the security concerns:

Is the very sensitive information something that Gradle is logging or something particular to your builds? I'd be interested in preventing sensitive information from being left around in Gradle logs.  Could you open a new issue about this?

**Comment by schildbach** [comment]
@big-guy Thanks for the clarification. May I suggest the description of the option is wrong? `gradle --help` says:

> Do not use the Gradle daemon to run the build.

I filed the separate issue: #8833
