### ISSUE TITLE
how to implement Maven's optional features with Gradle？

### ISSUE THREAD

**Issue by halower** [gradle/gradle#8848]
```  maven code
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zookeeper-discovery</artifactId>
            <version>${spring-cloud-zookeeper.version}</version>
            <optional>true</optional>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.zookeeper</groupId>
                    <artifactId>zookeeper</artifactId>
                </exclusion>
            </exclusions>
        </dependency> 
```

**Comment by blindpirate** [comment]
Please take a look at https://github.com/gradle/gradle/issues/867

**Comment by halower** [comment]
thank you for your replay,but ，are you sure this plugin solves the problem, and my scenario is an option that contains internal exclusions?

**Comment by ljacomet** [comment]
Since optional dependencies are simply ignored by Maven, I am not sure what you hope to replicate?

If this is about declaring optional dependencies from a Maven build, have a look at [feature variants](https://docs.gradle.org/5.3/userguide/feature_variants.html#header).

And since dependency level exclusions are translated to Maven, you should be able to produce a pom file with the above.
