### ISSUE TITLE
Renaming a project to an already existing project gives an error message

### ISSUE THREAD

**Issue by sjrd218** [gradle/gradle#8884]
I have a large multiproject setup where the root project name has to be renamed and then a project inside the multiproject is renamed to the original root name. This causes the projectDir to be incorrect when running tasks in subprojects.

This setup seemed to work find in gradle 4.7, but is broken in 4.10.x and 5.3.x.

Project setup:
```
excellent (renamed in settings.gradle to excellent-project)
├── awesome
│   └── build.gradle
├── build.gradle
├── excellentapp (renamed in setting.gradle to excellent)
│   ├── build.gradle
│   └── spectacular
│       └── build.gradle
└── settings.gradle
```

### Expected Behavior
Project dir should show correct path to renamed project in subproject task.
In the example project excellentapp should show path ${rootDir}/excellent/excellentapp

### Current Behavior
Project dir is incorrect and points to a path that doesn't exist.
In the example project excellentapp has path ${rootDir}/excellent/excellent

### Context
Trying to upgrade a large project from 4.7 to 4.10.3 so that I can then upgrade to 5.3.x.

### Steps to Reproduce 
See attached zip for reproducible project setup.
[excellent.zip](https://github.com/gradle/gradle/files/3019539/excellent.zip)

### Your Environment
Gradle 4.10.3 or 5.3.1 on Mac OSx 10.13.6

**Comment by lacasseio** [comment]
What is happening here is the rename of `:excellentapp` shadow the other project `:excellent` created by `include 'excellent:spectacular`. This should be resolved just like we are resolving names conflict with composite build. It should be an error trying to rename a project into an already existing project. Instead of renaming the project, you should change the `projectDir` of the `project(':excellent')`.

Let's focus this issue on better error messages:
- [ ] Renaming a project to an already existing project throws an exception:
```
include 'foo-app'
include 'foo:bar'
project(':foo-app').name = 'foo' // should throw an exception
```

### Open Question
What should happen here:
```
include 'foo-app'
project(':foo-app').name = 'foo' 
include 'foo:bar'
```

//cc @big-guy Do you agree with this next step and pitch in on the open question.
