### ISSUE TITLE
MultipleCandidatesDetails.getConsumerValue() returns null in AttributeDisambiguationRule

### ISSUE THREAD

**Issue by ducrohet** [gradle/gradle#8885]
Bug reproduces using Gradle 5.2 or 5.3[.1] and the [attached project](https://github.com/gradle/gradle/files/3019832/MyApplication4.zip).

The setup is the following:
- (android) `app` module with a flavor dimension and 2 flavors.
- (android) `dynamicfeature` module with no flavor. Depends on the app module

Variant aware dependency management fails by default due Gradle's inability to find a _single_ matching configuration on the `app` module to build the `dynamicfeature` module. This is normal.

The solution is to add `missingDimensionStrategy 'foo', 'flavor1'` on the `dynamicfeature` feature. This works too.

However, if one mistakenly adds the line to the `app` module instead, then this triggers the following NPE:

```
Caused by: java.lang.NullPointerException
        at com.android.build.gradle.internal.dependency.AlternateDisambiguationRule.execute(AlternateDisambiguationRule.java:46)
        at com.android.build.gradle.internal.dependency.AlternateDisambiguationRule$ProductFlavorRule.execute(AlternateDisambiguationRule.java:92)
        at org.gradle.internal.action.InstantiatingAction.execute(InstantiatingAction.java:61)
        ... 149 more

```

This fails in one of our custom `AttributeDisambiguationRule` because `MultipleCandidatesDetails.getConsumerValue()` returns null.

What's weird is that applying the `missingDimensionStrategy` really only impacts the resolved `configuration` on the `app` module and these should not be involved when trying to resolve dependencies of the `dynamicfeature` module. I don't really understand why we get in this state, or what Gradle is trying to disambiguate.

We will fix this by defensively checking for null but this seems weird to me. In fact, checking for null and just returning right away in our rule just end up with the expected error where Gradle cannot find a single match. So I'm not sure why this rule is called with null.

To repro, use the attached project and run `./gradlew dynamicfeature:generateDebugFeatureTransitiveDeps`

(edit: typos, grammar)

**Comment by ljacomet** [comment]
The disambiguation process of Gradle will look at all participating attributes _on the producer_, starting with the attributes on the consumer.

But that means if there is not a single solution when all consumer attributes have been disambiguated, Gradle will attempt to see if there is a way to disambiguate based on the producer schema. And in that context, there is indeed no consumer value.

So as you indicated, if you cannot disambiguate without a consumer value, you should check for that and return immediately from the disambiguation rule.

Note that since it was added to the api the `getConsumerValue()` method indicates that it can return `null`.

**Comment by ducrohet** [comment]
Shouldn't this first go through a compatibility rule (`AttributeCompatibilityRule`). We have one of these and I can't see how this would mark a `null` consumer value as compatible.

Looking at our code [here](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/build-system/gradle-core/src/main/java/com/android/build/gradle/internal/dependency/AlternateCompatibilityRule.java), this could only happen if the producer is `null` too (which would not lead to a disambiguation rule). Otherwise, we'll fail with an NPE in the rest of the method.

Still seems strange to me.

**Comment by ljacomet** [comment]
It does not go through a compatibility rule because that attribute is not _requested_ by the consumer.

So the selection process is:
* Collect compatible Gradle variants based on _requested_ attributes
* Disambiguate Gradle variants based on _requested_ attributes
* Disambiguate Gradle variants based on _extra_ attributes carried by the producers

**Comment by ljacomet** [comment]
Closing as no changes planned for this
