### ISSUE TITLE
Dynamic Versions Published with java-platform and versionMapping

### ISSUE THREAD

**Issue by sghill** [gradle/gradle#8887]
When using the [`java-platform` plugin](https://docs.gradle.org/5.3.1/userguide/java_platform_plugin.html) with the [versionMapping to resolutionResult](https://docs.gradle.org/5.3.1/userguide/publishing_maven.html#publishing_maven:resolved_dependencies) publishing configuration, I noticed I'm getting dynamic versions in the publication.

### Expected Behavior

Versions in the `<dependencyManagement>` section of the pom (and gradle metadata) should be resolved just like the regular `<dependency>` entries when versionMapping to resolutionResult is enabled.

Or, if this can't be done, I think I should get a warning similar to #8886:

```
 Maven publication 'pub' contains dependencies that will produce a pom file that cannot be consumed by a Maven client.
  - org.slf4j:slf4j-api:1.7.+ declared with a Maven incompatible version notation
```

### Current Behavior

versionMapping to resolutionResult is configured, but the requested version selectors make it into the publication (example: `1.7.+`) instead of the resolved version at build time (`1.7.26`).

### Context

Ideally I'd like to construct a platform with dynamic versions that is published regularly with resolved versions. This way I can publish new platforms frequently to minimize change, but my downstream builds only need to know which version of the platform they're on.

### Steps to Reproduce 

1. Download [dynamic-version-in-pom.zip](https://github.com/gradle/gradle/files/3019960/dynamic-version-in-pom.zip)
2. `unzip dynamic-version-in-pom && cd dynamic-version-in-pom`
3. `./gradlew publish` (will publish to `build/mvn-repo`)
4. See published pom and gradle metadata file contain dynamic versions

### Your Environment

Build scan URL: https://scans.gradle.com/s/ulxvjlszug5z2

**Comment by melix** [comment]
Hi @sghill ,

This behavior is intentional. A platform only carries constraints, so there's no resolution happening, so when you try to get versions from resolution, it doesn't work because ... nothing is ever resolved. This doesn't mean that there isn't a way to do it. There is, but you have to explain to Gradle what is your intent. The following build file shows how to do it. The idea is that:

- you will create a _resolvable configuration_ that is going to use the same dependencies as the platform
- it must tell what _usage_ it is for (so, api for the api of the platform, and you'll need a runtime version for the _runtime_ platform)
- then you configure publishing so that it resolves this configuration and uses it to "replace" version numbers

```
plugins {
   id 'java-platform'
   id 'maven-publish'
}

repositories {
   jcenter()
}

dependencies {
   constraints {
      api("org.apache.commons:commons-lang3:+")
   }
}

configurations {
   platformApiClasspath {
      extendsFrom(api)
      canBeConsumed = false
      canBeResolved = true
      attributes {
         attribute(Usage.USAGE_ATTRIBUTE, project.objects.named(Usage, 'java-api'))
      }
   }
}

dependencies {
    platformApiClasspath("org.apache.commons:commons-lang3")
}

publishing {
   publications {
      maven(MavenPublication) {
         from components.javaPlatform
         versionMapping {
            usage('java-api') { fromResolutionOf('platformApiClasspath') }
         }
      }
   }
}
```

Note that I'm using `extendsFrom(api)` so that I don't have to redeclare the version numbers. I do have to replicate all dependencies though. So basically what we are doing is creating a consumer of the platform in the platform itself. I'm also directly adding the dependencies to a _classpath_ configuration, which is acceptable in this case, but I wouldn't empathize on this being a pattern :)

**Comment by navdeepsekhon** [comment]
This was very useful. Thanks @melix

**Comment by nniesen** [comment]
@melix Thank you! Very helpful and great explanations but I have a some questions:

1. Is there are way to use the platform constraints to generate the `platformApiClasspath` dependencies?
2. If not, is there a way to programmatically verify every constraint has a corresponding `platformApiClasspath` dependency?
3. Any chance the 'java-platform' plugin could just have an option to produce resolved dependencies? e.g., The plugin creates and populates the platform api/runtime classpaths from the constraints so we just have to specify the versionMapping like in a regular gradle project?
4. Is the api vs runtime distinction really meaningful in this context? The platform pom remains but the module groups the dependencies by usage. However, this seems irrelevant since it seems it's the dependency declaration in the consuming project that determines ultimate usage of the dependency. I also had issues getting both sets of versions to resolve and ultimately I went with all runtime which seemed more appropriate for a platform where I can't control downstream usage.

**Comment by nniesen** [comment]
> 4. Is the api vs runtime distinction really meaningful in this context?
Yes, it is meaningful. I had to change everything to api so the artifacts would be exported to consumers. Runtime worked fine for Gradle 5.x consumers but with Gradle 6.x it wouldn't find any of the versions. This is due to Gradle 6.x also using the .module information which maintains the api/runtime distinction. I was able to verify this by simply deleting the .module file and then everything worked again. It makes some sense that everything in the platform needs to be api so the artifact versions are "exported" to the consumer of the platform and it doesn't impact that fact that the dependency declaration in the consuming project that determines ultimate usage of the dependency.

**Comment by nniesen** [comment]
> 4. Is the api vs runtime distinction really meaningful in this context?
Another issue we encountered is that even though the api versions in the publish .pom file were all resolved, the .module file still had unresolved/dynamic runtime dependencies. Rather than duplicate the dependencies yet again for a runtime version mapping, we just disabled the .module file publishing. I assume adding the java-runtime version mapping would have worked as well but did not verify that.

**Comment by nniesen** [comment]
> > 1. Is the api vs runtime distinction really meaningful in this context?
> 
> Another issue we encountered is that even though the api versions in the publish .pom file were all resolved, the .module file still had unresolved/dynamic runtime dependencies. Rather than duplicate the dependencies yet again for a runtime version mapping, we just disabled the .module file publishing. I assume adding the java-runtime version mapping would have worked as well but did not verify that.

As an FYI, we ended up having both platformApiClasspath and platformRuntimeClasspath so that we'd have both pom and module files with resolved dependencies.
