### ISSUE TITLE
java-library plugin makes impossible to have project dependency on Java9-modular kotlin project

### ISSUE THREAD

**Issue by ilya-g** [gradle/gradle#8897]
Applying `java-library` plugin to a project that is supposed to become a JPMS (jigsaw) module causes problem when depending on such project with a project dependency in another JPMS module.

### Current Behavior

Currently a project where both java and kotlin are used produces output in directories `build/classes/java/main` and `build/classes/kotlin/main`. Note that even a pure kotlin project has to use java source set and compiler invocation to build `module-info.java` module declaration.

When such project `A` is depended upon in another project `B` with a project dependency and `java-library` plugin is applied to the project `A`, the project `B` gets these two class output directories of the project `A` in its modulepath instead of the resulting jar of the project `A`. This causes problems in the JPMS modular environment: 
- it finds `module-info.class` in `build/classes/java/main`
- however some/all classes of this module is in `build/classes/kotlin/main`

### Expected Behavior

One of solutions to this problem proposed by @oehme is to build ABI jar of the project `A` and depend on it in the project `B`. This way the content of the module `A` won't be exploded in two directories.

### Steps to Reproduce 
See this example project: https://github.com/ilya-g/kotlin-jlink-examples/tree/gradle-issue-8897/gradle

### Your Environment

```
------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------
Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          9.0.1 (Oracle Corporation 9.0.1+11)
OS:           Windows 10 10.0 amd64
```

**Comment by jjohannes** [comment]
This is working in `6.4` (current nightly [gradle-6.4-20200323230320+0000](https://services.gradle.org/distributions-snapshots/gradle-6.4-20200323230320+0000-bin.zip)). If we detect that a local project is a module, the "jars" of all dependencies are used (and not the class folders). In the sample this works, because the "app" project is a module (has a `module-info.java`).

Note that `6.4` also comes with basic support for using the module path:

```
tasks {
    "compileJava"(JavaCompile::class) {
        modularClasspathHandling.inferModulePath.set(true)
    }
}
````

However, in the sample it can not be used like that, because the Kotlin standard libraries are not published as modules - they neither have a _module-info.class_ nor an _Automatic-Module-Name_ manifest entry.

**Comment by msgilligan** [comment]
@ilya-g If you haven't upgraded to Gradle 6.4 yet, as a workaround you could try setting `-Dorg.gradle.java.compile-classpath-packaging=true` as described here: https://docs.gradle.org/6.4-rc-2/userguide/java_library_plugin.html#sub:java_library_known_issues_windows_performance
