### ISSUE TITLE
Remote cache usage is not resumed after temporary network drop

### ISSUE THREAD

**Issue by davidburstromspotify** [gradle/gradle#8924]
### Expected Behavior
If the remote cache doesn't respond (for whatever reason), usage of it will be disabled for the remainder of the build. The expected behaviour is that the cache will be used again when Gradle detects that the remote cache is available again, e.g. through a configurable periodic background ping.

### Current Behavior
As stated above, the remote cache availability will only be requeried when a new build is started.

### Context
This affects particularly CI builds which will execute several thousands of potentially long running but cached tasks. If the cache doesn't respond in the beginning of the build, they will often time out.
Although network quality also can be improved outside of Gradle, this would improve CI build stability a lot.

**Comment by lptr** [comment]
There are two kinds of issues here:

1) Likely non-transient failure while communicating with the remote cache

There are problems like HTTP 401 or 403 that are a clear sign that the remote cache is not configured properly, and no amount of retrying will fix it. Being lenient here (=disable caching instead of failing the build) only leads to users not noticing the issue and going on without a remote cache. So instead we should fail the build immediately with a clear message.

2) Likely transient failure while communicating with the remote cache

This is about HTTP 500 or timeouts. We could be more resilient here, e.g. by disabling only after the third problem, or re-enabling after a minute (as proposed in the issue description). This makes sense because transient network errors can be a thing.

However, we need to make sure that transient problems don't go unnoticed. If the user has a bad connection on CI where they rely on a resilient protocol to keep things mostly working is probably a sign that they need to fix something in their infrastructure.

Maybe a summary at the end of the build could work. We should also show these problems prominently in build scans.

**Comment by lptr** [comment]
3. Artifact size too big

When the cache server refuses to store an artifact because it exceeds the size limit, we should not disable caching at all.

**Comment by lptr** [comment]
This is still on.
