### ISSUE TITLE
Plugin development: generate plugin descriptor from annotation on a plugin class

### ISSUE THREAD

**Issue by Dkhusainov** [gradle/gradle#8965]
Currently the fastest way to create plugin descriptors for plugins is to use `gradlePlugin` DSL. 

While this is a way better than creating them by hand, it still lacks the "typesafety" or validation. What if I renamed class or moved it to another package? It wouldn't be as bad if IDE's refactor tool worked on kts files, but it doesn't. You have to remember which plugin is referenced where. The problem is especially relevant for monorepo projects with lots of modules, that all have plugins in them.

**Feature request**:
Create a new plugin `java-gradle-plugin-annotation`, which will add dependency on a `jar` with annotation class and an annotation processor task to build lifecycle that generates plugin descriptors from annotated classes.

This way when you create a new plugin, everything you need to write is on one place.

Google's `AutoService` does something simular, so we don't need to go too far for examples.

**Comment by gildor** [comment]
Also, this annotation (for example it can be named `@GradlePlugin`) should have id parameter, so it removes boilerplate to configure the plugin:
```
@GradlePlugin(id = "greeting")
class GreetingPlugin : Plugin<Project>()
```

I think an additional plugin is not necessary it may be bundled to `java-gradle-plugin` and enabled explicitly using`gradlePlugin ` DSL.

**Comment by big-guy** [comment]
I think it's perfectly fine for a community plugin to try to add something like this, but I don't think this is something we're likely to add.  This would mean our annotation would only work for particular languages that our annotation processor worked for.  You can write a Gradle plugin in almost any JVM language.  

I also think this is a little harder than it seems, since you need to integrate with the 2 other ways to generate this descriptor (written by hand or generated by the plugin).  There's more information we'd like to put into the DSL (beyond id and implementation classpath) that may not fit into an annotation.
