### ISSUE TITLE
Please try to keep compatibility for external plugins

### ISSUE THREAD

**Issue by zolotov** [gradle/gradle#9010]
In two recent versions (4.5 and 4.7-rc1) there were runtime incompatibility changes in  IvyDescriptorFileGenerator. Which lead to problems for users of my plugin: https://github.com/JetBrains/gradle-intellij-plugin/issues/379 and https://github.com/JetBrains/gradle-intellij-plugin/issues/388.

I understand that the class is located in `internal` package (btw, should it be there?), but could you please try to keep compatibility at least when it is easy to do (I believe adding a parameter to a constructor is an easy change)?

Thank you!

**Comment by lptr** [comment]
Unfortunately, the cost of keeping APIs backwards compatible is quite high, that's why we try to draw a clear line between the ones we support in this way and the ones we don't.

At the same time we realize that there is internal functionality in Gradle useful for a wide audience that we should expose via public APIs. If you believe that `IvyDescriptorFileGenerator` fits that bill, please make a case for making it public. A PR leading in that direction would also help.

Meanwhile another option to consider is to copy the subset of `IvyDescriptorFileGenerator`'s functionality that is relevant to your plugin. Or perhaps Ivy has some public APIs you could use directly to achieve your goals. Either way you make your code independent of Gradle's internal changes.

**Comment by zolotov** [comment]
> Unfortunately, the cost of keeping APIs backwards compatible is quite high

No doubts, that's why I ask not to always keep it but at least trying to keep it. In these particular cases keeping compatibility were almost free.
