### ISSUE TITLE
Disallow setters for known mutable property types

### ISSUE THREAD

**Issue by wolfs** [gradle/gradle#9068]
We should at least disallow it on the parameters object for artifact transforms. We could also do it for other instances of work configuration.

For tasks we would need to deprecate the possibility first and then we can remove it in a future major version.

Types affected:

- [x] `ConfigurableFileCollection`
- [x] `Property`
- [ ] `DomainObjectCollection`

**Comment by lptr** [comment]
We should do the same deprecation for `Property` types, as they are also things that should be mutated via methods on the object instead of using setters on the parent type.

**Comment by big-guy** [comment]
It's the same for `Provider` too.  Maybe we should have a marker type for all immutable-but-configurable properties? 

I think it's:
- Provider
- Property (and children)
- FileCollection, FileTree
- ConfigurableFileCollection, ConfigurableFileTree
- DomainObjectCollection (and children)

I think there may be some one off things too (but I'm thinking more for Task things)

**Comment by lptr** [comment]
We discussed this, and in the first round we'd like to limit the scope to types that are already mutable in-place, because the setter can be removed without having to change the getter to preserve the mutability of the type that owns the property itself.

For properties with immutable types like `FileCollection` the change is breaking. It might make sense to introduce warnings that result in breaking changes in 6.0 instead. I'll create an issue for this.

**Comment by lptr** [comment]
It's a good point about `DomainObjectCollection` though, added it to the issue description.

**Comment by lptr** [comment]
Actually, what is the recommendation on using `DomainObjectCollection` vs `ListProperty` and `SetProperty`?
