### ISSUE TITLE
gradle does not respect commandline task ordering

### ISSUE THREAD

**Issue by diacone** [gradle/gradle#9145]
The tasks from subproject do not respect task ordering given as gradle arguments. I'm quite certain that this used to work, but I'm not sure when it stopped.

### Expected Behavior
The tasks are not run in parallel as they should maintain the order from commandline.

When the tasks are at the same project, it works correctly:
`./gradlew  :ccc :aaa --parallel`

### Current Behavior
The tasks are run in parallel.

### Steps to Reproduce 
```
task aaa {
    doFirst {
        println path
        Thread.sleep(1000)
    }
}

task ccc {
    doFirst {
        println path
        Thread.sleep(5000)
    }
}

project (":sub") {
    task bbb {
        doFirst {
            println path
            Thread.sleep(5000)
        }
    }
}
```

`./gradlew  :sub:bbb :aaa --parallel`

### Your Environment
Gradle 5.3.1
Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_191 (Oracle Corporation 25.191-b12)
OS:           Linux 5.0.5-200.fc29.x86_64 amd64

**Comment by big-guy** [comment]
I think you might be confusing two things here.  Tasks in the same project cannot run in parallel without the worker API, so it's not surprising that you see the order you expect because nothing can be executed in parallel.

Tasks that are in different subprojects _can_ run in parallel with `--parallel`. In that case, Gradle is respecting the order, but the order of the output you're seeing is due to batching.  Since `:aaa` completes before `:sub:bbb`, it's output is shown first and then the output of `:sub:bbb`.  If you change around the tasks a bit to make `:aaa` take longer, you can see what you were expecting.  We try to minimize the amount of interleaving and show continued progress, so showing output from a completed task before showing _some_ of a running task's output is a consequence of this.

You can see this in the build scan:
https://scans.gradle.com/s/yrjeyqyuj2xba/timeline
`:sub:bbb` is started at 0.851 and `:aaa` is started at 0.853. This is the order from the command-line.

Without `--parallel`, you can see the order is right too:
https://scans.gradle.com/s/5f432upkzo6ui/timeline
This is the same as the "same project" case with `:aaa` and `:ccc`.

The order of the output is a bit of a timing game.  If `:sub:bbb` has produced output and nothing else has for awhile, we can sometimes flush in the order you expect:
```
task aaa {
    doFirst {
        Thread.sleep(3000)
        println path
    }
}

task ccc {
    doFirst {
        println path
        Thread.sleep(5000)
    }
}

project (":sub") {
    task bbb {
        doFirst {
            println path
            Thread.sleep(5000)
        }
    }
}
```

Produces:
```
> Task :sub:bbb
:sub:bbb

> Task :aaa
:aaa
```

In all cases, however, we are running `:sub:bbb` before `:aaa` as requested from the command-line.  If the order is significant, this should be in the build script.

**Comment by diacone** [comment]
I'm afraid this is not the case. May be this over-simplified example looks
like that. But we have failing builds because of that.

If you run the tasks in rich mode, you can clearly see that those tasks are
run in parallel. They start seconds before they can possibily run if the
order is respected.

Dne út 16. 4. 2019 19:23 uživatel Sterling Greene <notifications@github.com>
napsal:

**Comment by diacone** [comment]
Try this example:

```
def f = file("out.txt")
f.delete()

project(":sub") {
    task bbb {
        doFirst {
            Thread.sleep(5000)
            f << path << "\n"
        }
    }
}

task aaa {
    doFirst {
        f << path << "\n"
    }
}
```
```
$ ./gradlew :sub:bbb :aaa
$ cat out.txt 
:aaa
:sub:bbb
```

**Comment by big-guy** [comment]
That looks completely reasonable to me.

`:sub:bbb` and `:aaa` are allowed to run in parallel. This has been the case for as long as `--parallel` has existed. There are no dependencies between them and the command-line does not mean run this task and then run that task.   `:sub:bbb` starts and sleeps, `:aaa` starts and immediately writes to the file and then `:sub:bbb` writes to the file.  The command-line order is preserved WRT starting a task.

If your builds rely on the order of tasks on the command-line, this needs to be expressed in the build script itself, not in the command-line order. 

Are your builds failing due to a particular kind of task running in an unexpected order?

**Comment by diacone** [comment]
Ok, what about `clean build`? There is no relation between those two, right? I simply want to run first and then the other. 

Clean in parallel and then build in parallel.

But the point is that I believe that the behavior has changed.

Also the documentation says that the tasks are executed in specified order.

**Comment by big-guy** [comment]
They are executed in the specified order.  Tasks are allowed to run in parallel and Gradle figures out the dependencies between things.

`gradle task1 task2` is not the equivalent of `gradle task1` followed by `gradle task2` because Gradle can find tasks selected by `task2` to execute before all of the tasks selected by `task1`. 

With `clean` involved, you're probably seeing https://github.com/gradle/gradle/issues/2488.  This is a hole in the way Gradle schedules tasks that create outputs and tasks that delete those same outputs.  e.g., the clean and compile tasks look independent from each other and Gradle does the wrong thing (schedules the compile followed by the clean). I think this happens with the clean task depends on other non-clean tasks.  This changed in 3.x/4.x, I believe. 

The workaround has been to add something like this:
```
def cleanTask = tasks.getByName("clean")
subprojects {
    tasks.configureEach {
        // Workaround for https://github.com/gradle/gradle/issues/2488
        if (it != cleanTask) {
            mustRunAfter(cleanTask)
        }
    }
}
```

**Comment by bartek-wesolowski** [comment]
It would be nice to update the documentation, because it might be misleading saying that the tasks are executed in the order they're specified:
https://docs.gradle.org/current/userguide/command_line_interface.html#executing_multiple_tasks
