### ISSUE TITLE
Process exception in flutter. Gradlew.bat exiting abnormally in VS Code

### ISSUE THREAD

**Issue by tyler555** [gradle/gradle#9177]
I recently updated VS Code and am now having this issue when debugging that I never had previously :

* Error running Gradle:
ProcessException: Process "C:\Users\Tyler\Desktop\FriendsApp\friendsapp\android\gradlew.bat" exited abnormally:
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
Unable to start the daemon process.
This problem might be caused by incorrect configuration of the daemon.
For example, an unrecognized jvm option is used.
Please refer to the user guide chapter on the daemon at https://docs.gradle.org/4.10.2/userguide/gradle_daemon.html
Please read the following process output to find out more:
-----------------------
Error occurred during initialization of VM
Could not reserve enough space for 1572864KB object heap

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
  Command: C:\Users\Tyler\Desktop\FriendsApp\friendsapp\android\gradlew.bat app:properties
Please review your Gradle project setup in the android/ folder.

Any help would greatly be appreciated.

**Comment by big-guy** [comment]
How much physical memory does your machine have? 

> Starting a Gradle Daemon, 1 incompatible Daemon could not be reused

This means there are two Gradle daemons running and I think each one is configured for a ~1.5GB heap (based on the error message).  Since it reports the daemon as incompatible, this could mean a few different things:

- The already running Gradle daemon and the build that fails want to use different versions of Java
- The already running Gradle daemon has different JVM parameters (system properties, memory)

It's hard to tell which one is the case from just the failure.  This is not likely a Gradle regression, but something particular to your configuration.  You can try asking for more help on our [forums](https://discuss.gradle.org/) or our community Slack.  JVMs fail to start on Windows like that when they're low on memory, especially when the JVM requests a minimum heap size.  Is there anything you can tweak in the flutter config to change the parameters to Gradle (1.5GB is not the default)?
