### ISSUE TITLE
Add middle distribution level to gradle wrapper.

### ISSUE THREAD

**Issue by ThadHouse** [gradle/gradle#9199]
Currently, only `bin` and `all` distributions for the wrapper are provided. This was great for end users of the projects, but now with the Kotlin DSL, it might not be the best solution. The `bin` distribution provides no Javadocs for intellisense, where as the `all` distribution comes with the javadocs, in addition to the full source tree, the full user docs, the dsl docs, and a full set of samples. On windows, the all distribution takes at least an order of magnitude longer to download an extract, and it gets really annoying. This is also an issue for developing plugins. Usually only the intellisense javadocs are needed, without much else. The internet has all the other information when needed.

I'm proposing either a 3rd layer of distribution that includes the javadocs in addition to everything in `bin`, or potentially just adding javadocs to bin. That will give intellisense for kotlin dsl and plugins, which will be a huge help.

**Comment by big-guy** [comment]
@eskatos @bamboo is there something we could do here on the Kotlin DSL side of things?  e.g., if we generated a gradle-XX-docs.zip with only the documentation (no samples, no source), could we coax IntelliJ into looking at that zip?

**Comment by ThadHouse** [comment]
I would prefer a solution that doesn't only work in IntelliJ. I use VS Code, and am not willing to switch to IntelliJ. I mainly care about this for plugin development, not Kotlin DSL. Kotlin DSL was just another use case.

**Comment by eskatos** [comment]
Current distributions sizes:
- `-bin` 83M
- `-all` 128M
- `-src` 36M

`-src` cannot be used as a wrapper and contains the Gradle sources plus its build, including buildSrc, all samples, fixture, tests etc... Its contract is that you can build Gradle from source with it. That's the distribution the IntelliJ Kotlin DSL script editor consumes on-demand. It's way too big for this purpose, making first time use painful, and the solution is very adhoc.

In order to provide both navigation to sources and javadoc IDEs only need the source.

All the production sources of Gradle fit in a 11MB ZIP file ATM. A distro that both can be used as a wrapper and provides sources and javadocs in IDEs, always, would be ~95M. If we can accept the extra initial weight I think doing that for `-bin` would simplify things for everyone.

FWIW, javadocs would fit in a 7M ZIP file ; the `-all` distro also include all test fixtures and test sources.

**Comment by big-guy** [comment]
Maybe we can offset some of that by removing some unused dependencies or in 6.0 when we remove some deprecated plugins.

**Comment by eskatos** [comment]
The IDEs will need to know where to find the sources in the distribution somehow, maybe there's a conventional way. We should find out before changing the distributions.

**Comment by ThadHouse** [comment]
Something on a related note is why is the plugin API generated, rather then published to a maven repo and just used like a normal dependency? Ides know how to grab javadocs linked to maven dependencies, so that would be trivial.

I guess another way would be to generate the jar and the javadocs jar into a local maven repo, and just have the gradleAPI() dependency look in that generated maven repo. That would solve the plugin use case, and work across ides for plugin development.
