### ISSUE TITLE
Including optional features of upstream libraries is broken (5.4)

### ISSUE THREAD

**Issue by mkalb** [gradle/gradle#9208]
This issue #1253 added a feature with version 4.6. It is broken with version 5.4.

### Expected Behavior
The version of the optional library is to be determined.

Dependency Report:

```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- log4j:log4j:1.2.17
|    \--- javax.mail:mail:1.4.3
|         \--- javax.activation:activation:1.1
\--- javax.mail:mail -> 1.4.3 (*)
```

### Current Behavior
The dependency can no longer be resolved.

Dependency Report:
```
runtimeClasspath - Runtime classpath of source set 'main'.
+--- log4j:log4j:1.2.17
\--- javax.mail:mail FAILED
```

### Steps to Reproduce 
Minimal project (build.gradle):

```groovy
plugins {
  id 'java-library'
  id 'project-report'
}

repositories {
  jcenter()
}

dependencies {
  implementation 'log4j:log4j:1.2.17'
  runtimeOnly 'javax.mail:mail'
}
```

**Comment by ljacomet** [comment]
The support of `optional` dependencies that was added behind a `featurePreview` in Gradle 4.6 up to 4.10 did not make the cut in Gradle 5.0 and beyond.

The main reasons are documented as part of the discussion in #5434 but in short can be resumed to: Giving any kind of visibility in Maven `optional` dependencies was causing issues as this is not expected by the producers of these Maven libraries.

Since then, Gradle 5.3 has introduced dedicate support for [this](https://docs.gradle.org/5.3/userguide/feature_variants.html), although consumption remains limited to consumers of Gradle Module Metadata.

**Comment by mkalb** [comment]
Thank you very much for the quick explanation.
I'm disappointed that this feature (for which I've been waiting eight years) has been thrown out after a short time.
http://gradle.1045684.n5.nabble.com/Use-optional-dependencies-td3326783.html

**Comment by ljacomet** [comment]
Closing as this is expected. Note that the idea to introduce this as an opt-in mechanism is not totally ruled out.
