### ISSUE TITLE
Project dependencies with non default configurations are not picked up correctly

### ISSUE THREAD

**Issue by gizmomogwai** [gradle/gradle#926]
The problem arose in a legacy project in which I try to introduce gradle. It's setup is a little special, so I tried to narrow the problem down.

The narrowed down problem looks like this:
I have a multi-project build consisting of 3 modules (m1, m2 and main).
Each of these modules defines a configuration (in this example the configuration is called "one") and brings with this configuration some java classes (in src/one/java).
The main module references those dependencies in its dependencies block by using path: ... and configuration: parameters to the project dependency.

### Expected Behavior
I would expect, that main can be build and picks up the classes from the configuration in the modules.

### Current Behavior
The java sources are not found by gradle.
Curiously intellij-idea can setup the project correctly (when importing the gradle model) if there is only one such project dependency. the gradlew commandline fails always.

### Context
As described in the introduction I am trying to migrate a legacy project. The setup of the project consists of many modules, that each can have some platform specific java sources.
The sources of one module are structured in a way, that only the combination of the platform specific and the platform unspecific sources can be compiled successfully (kind of cyclic dependencies).
For this I wanted to come up with several sourcesets for each module, each containing the general sources + one platform specific source folder.

A main module then could reference one consistent set of subprojects with their configuration.

### Steps to Reproduce (for bugs)
https://github.com/gizmomogwai/gradle-experiments
is an example project. To reproduce just run gradlew build.
To see the import problems to intellij-idea remove on of the dependencies in the main module (then it works, but does not compile), put it back in and import -> its totally broken.

### Your Environment
./gradlew --version                                                                               1s 173ms
------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------
Build time:   2016-11-22 15:19:54 UTC
Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_77 (Oracle Corporation 25.77-b03)
OS:           Mac OS X 10.12.1 x86_64

IntelliJ IDEA 2016.3
Build #IC-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by bmuschko** [comment]
To make this work you will need to bundle the compiled class files of your custom source set into a JAR and declare it an "outgoing" artifact of the project. I sent you a [pull request](https://github.com/gizmomogwai/gradle-experiments/pull/1) that demonstrates the fix.

**Comment by gizmomogwai** [comment]
@bmuschko thanks for the demonstration. it actually works very well in gradle, but intellij-idea seems to have problems with this. I will open up a bug report there. One more question:
Could you explain why this works this way? Is the regular java-plugin doing the same by convention for normal source-sets?

**Comment by bmuschko** [comment]
I believe IntelliJ doesn't automatically discover custom source sets in order to add them to a specific scope. However, you can always go down the route of using the Gradle Idea plugin to provide the information to IntelliJ. For the modules that declare a custom source set you can do the following:

```apply plugin: 'idea'

idea.module {
    sourceSets.one.allSource.srcDirs.each {
        sourceDirs += it
    }

    scopes.COMPILE.plus += [configurations.oneCompile]
    scopes.COMPILE.plus += [configurations.oneRuntime]
}```

Keep in mind that you'll need to generate the project files from the command line.

BTW: You don't necessarily have to set up custom source sets. You can also add `src/one/java` to the existing `main` source set. That would mean that you don't need to set up any of the custom source sets and other configuration we talked about. It will just work out-of-the-box.

The Java plugin does something similar under the covers. It defines the main source set, the compiled class files are added to the `jar` task. Then the artifact produced by `jar` is added to the `default` configuration. Default is used as the path for any project dependency so you don't have to declare a `path` property. 

Why do you have to do that? The reason is that Gradle needs to build a JAR that contains the class files to be added to the classpath of another project. Therefore, the JAR file needs to be built first.

**Comment by gizmomogwai** [comment]
Thanks for the explanations. My problem is, that each of my legacy modules does have actually 3 "specific" sourcefolders. One is mock/pc one, and two more are for special target platforms. So the main-sourceset is already taken for the easy path, but I need two more configurations to get jars for the two additional configurations (at least thats what i came up with). I added a appendix to the jar-names of your application, so that I get nice jars for the specific implementations (e.g. m1-one.jar or m1-two.jar).

If you compare my setup e.g. to sl4j it is as if the specific configurations would also already contains the api, and one implementation for android or log4j or java logging. When all is compiled you could simply put sl4j-android.jar into your classpath (no need for a pure api-jar anymore).

I am not sure if this is the best way to go. If there would be only one variant, I would definetively put all the sources into the main configuration.

**Comment by bmuschko** [comment]
The only other alternative I can think of is to point the `main` source set to the other source directories, create multiple JAR tasks (for each of the variants) and then filter an inclusion/exclusion pattern. Not sure if that's easy in your case. Maybe you already have the code separated by a specific package. Otherwise, using custom source sets sounds like a good solution to the problem.

Can we close the issue?

**Comment by gizmomogwai** [comment]
Also a good idea! The problem in my case is, that the platform specific folders contain the same classes (with different implementations). So the compiler does not like this :))

Sure, I am happy to close this ticket. Thanks a lot for your help!!!!
