### ISSUE TITLE
Please don't break backward compatibility if it's possible

### ISSUE THREAD

**Issue by remal** [gradle/gradle#9286]
`org.gradle.api.reporting.internal.TaskReportContainer(Class type, Task task)` constructor is now deprecated. Please leave it as it is, as there different plugins that rely on it (com.github.spotbugs, name.remal.sonarlint, for example).

Please try not to break backward compatibility if possible. Personally I don't see any reason to break it for this class.

**Comment by rpalcolea** [comment]
not from gradle team but ideally those plugins shouldn't use internal APIs. It would be better if the plugins use public APIs, that way breaking changes are not introduced easily

**Comment by JLLeitschuh** [comment]
@remal I recommend opening issues with those plugin authors about this issue.

When you do so, link them back to this issue for tracking purposes.

**Comment by big-guy** [comment]
We do try to not break existing builds or plugins, even to the point of leaving in internal APIs that would otherwise be removed/changed when the cost to do so is low and the benefit is obvious. 

In this particular example, there are a couple of things tangled up:
1. There's no good public API for what TaskReportContainer does.  The Report/Reporting/ReportContainer APIs never really came together in a useful way. 
2. We need to be able to keep track of configuration actions, so we can attribute configuration time to the right plugins/tasks/domain objects/etc.  This is important and cross-cutting. 

We can't promise that this API won't be removed, but there's not a strong urgency to do so right now.  To future proof your builds/plugins, it would be best to avoid the use of internal APIs.

**Comment by semen-levin-epam** [comment]
@JLLeitschuh Actually, I'm an author of the second plugin. And for this particular case there is no good way to make the plugin to support both deprecated and normal constructors, as I have my own class, that extends `TaskReportContainer` and it should invoke one of the constructors. Unfortunately, reflection can't be used here.

For now I see these options:
1. Build another version of my container with Gradle 5.1 in classpath. It's quite inconvenient:(
1. Generate my container's class using ASM. It's definitely doable, but requires some time...

**Comment by semen-levin-epam** [comment]
@JLLeitschuh Actually, I'm an author of the second plugin. And for this particular case there is no good way to make the plugin to support both deprecated and normal constructors, as I have my own class, that extends `TaskReportContainer` and it should invoke one of the constructors. Unfortunately, reflection can't be used here.

For now I see these options:
1. Build another version of my container with Gradle 5.1 in classpath. It's quite inconvenient:(
1. Generate my container's class using ASM. It's definitely doable, but requires some time...

**Comment by remal** [comment]
@JLLeitschuh Actually, I'm an author of the second plugin. And for this particular case there is no good way to make the plugin to support both deprecated and normal constructors, as I have my own class, that extends `TaskReportContainer` and it should invoke one of the constructors. Unfortunately, reflection can't be used here.

For now I see these options:
1. Build another version of my container with Gradle 5.1 in classpath. It's quite inconvenient:(
1. Generate my container's class using ASM. It's definitely doable, but requires some time...

**Comment by JLLeitschuh** [comment]
@remal I think a better ask is to ask the Gradle team to add the functionality you want into the public API. Consider opening an issue describe the use case you are trying to cover and why the current API is lacking.

**Comment by adammurdoch** [comment]
Yes please, we'd much prefer that we work together to make the public APIs better, rather than have plugins reach into the internals of Gradle. This way, we've all agreed on what pieces need to be stable (the public APIs) and which pieces are free to change (the internals of Gradle, and the internals of the plugins), which means a much better experience for everyone.
