### ISSUE TITLE
Gradle wrapper not respecting GRADLE_OPTS

### ISSUE THREAD

**Issue by byrd-railroad19** [gradle/gradle#9289]
### Expected Behavior
The contents of `GRADLE_OPTS` environment variable should be passed to the invocation of gradle when using wrapper.

### Current Behavior
```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

### Context
I believe the issue is with line 125 of the generated wrapper file.  The macos specific JVM arguments are being added to `GRADLE_OPTS` instead of `JAVA_OPTS`

### Steps to Reproduce 
Generate a test project
`gradle init --type basic --dsl groovy --project-name test`
Invoke with environment variable set
`GRADLE_OPTS='-i' ./gradlew`

### Your Environment
Build scan URL:  https://scans.gradle.com/s/rtf2u625kw44s/

**Comment by big-guy** [comment]
This is working as intended.  [`GRADLE_OPTS` (and `JAVA_OPTS`)](
https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_environment_variables
) affect the arguments to the JVM running Gradle.  They're not the command-line arguments for the build itself.

`GRADLE_OPTS='-i' ./gradlew` is passing `-i` to the JVM, not Gradle.  This is why it fails since `-i` is an option only understood by Gradle.
