### ISSUE TITLE
Build cache does not track JVM version for all tasks

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#9301]
The [classloader hasher](https://github.com/gradle/gradle/blob/e975872ae2cf1d521b73f1107cae772ca09c63cd/subprojects/core/src/main/java/org/gradle/groovy/scripts/internal/RegistryAwareClassLoaderHierarchyHasher.java#L35) currently tracks the full version number, including patches. This makes it very unlikely that people will actually get cache hits from a remote cache node unless the environment they work in is highly regulated. We should consider whether this is the right trade-off between performance and correctness.

The code linked above also contains an odd duplication, hashing the vendor twice.

**Comment by big-guy** [comment]
Isn't that tracking only the VM vendor and not the version at all?

>         String javaVmVersion = String.format("%s|%s|%s", System.getProperty("java.vm.name"), System.getProperty("java.vm.vendor"), System.getProperty("java.vm.vendor"));

java.vm.name = OpenJDK 64-Bit Server VM
java.vm.vendor = Oracle Corporation

java.vm.vendor is repeated twice.

**Comment by oehme** [comment]
Indeed, I thought vm.name contained the full version too. Then we might not be tracking the version correctly at all.

**Comment by lptr** [comment]
I’m pretty sure the second `vm.vendor` was supposed to be `vm.version`. But I would be surprised if this was how we tracked Java versions everywhere. Let me check this out next week.

**Comment by paplorinc** [comment]
It seems unused, is that part referenced by a third part (or reflection maybe)?

**Comment by oehme** [comment]
Not sure what you mean by unused. It's definitely used, it's the hasher for all classpaths in Gradle.

@lptr we track the jvm version for JavaCompile and Test tasks explicitly (because it can be different from the build VM). I'm afraid those are also the only tasks we tested this for.

**Comment by lptr** [comment]
OK, here's how I understand what's happening. So this is definitely a bug. The main question is: what is its effect, and what would be the right behavior instead.

The _classloader hierarchy hashes_ we are working with here are used in Gradle to determine the fingerprint of objects of types that are unknown to Gradle. These are:

- work action types (e.g. task types, additional `doFirst()`/`doLast()` task actions, artifact transform types, work item actions etc.)
- simple property values (`@Input MyObject getMyObject();`)
- complex property values (`@Nested MyObject getMyObject();`)

In each of these cases the fingerprint of the value contains the hash of the classloader hierarchy that was used to load the type itself, so if something in that hierarchy changes (=some dependency is modified), then we recognize the difference.

The hash of a classloader is calculated by combining the hashes of each classloader among the ancestry, starting from the concrete classloader, walking toward the parent, until we reach a known root classloader.

The hash of a classloader is defined differently for different classloader types. Script classloaders (that only load a Groovy script, say) use the hash of the source code of the script for example. Classloaders created by Gradle are assigned a hash based on the hash of the files on the classpath. And there are so called "known root classloaders" that have a custom hash assigned to them.

Here's an example of how we could calculate the hash of an object whose type was defined in a Groovy build script:

```text
ClassLoaders$BootClassLoader
 ^
 |
ClassLoaders$PlatformClassLoader [KNOWN ROOT]
 ^
 |
ClassLoaders$AppClassLoader [KNOWN ROOT]
 ^
 |
MixInLegacyTypesClassLoader
 ^
 |
FilteringClassLoader
 ^
 |
CachingClassLoader (the Gradle API classloader) [KNOWN ROOT]
 ^
 |
ScriptClassLoader (the Groovy script's classloader)
```

We start by calculating the `ScriptClassLoader` which is the hash of the build script's source code. We then combine it with the parent's hash.

The parent is a known root classloader (=the Gradle API classloader) that has a hash assigned based on the Gradle version itself.

The idea with known root classloaders like this is that we can stop traversing upwards already, because that hash already contains everything we wanted to track about the higher part of the classloader hierarchy itself.

So (at least in this case) we never get to the hash of the `AppClassLoader` or the `PlatformClassLoader` (or its parent).

Practically this means that we treat the Gradle API as completely independent of the Java VM it is running on. Is this a good decision? It does provide a lot of flexibility in any case, and nobody reported a problem, yet.

OK, so when _do_ we use the system classloaders, and what happens when we do? Can we ever bump into them at all, given that most classes are loaded via Gradle's own classloaders that usually have a known root before reaching the system classloaders?

When you have a property of a type from Java like `File` used as an `@Input`, then we serialize it and use its classloader hash. So yeah, built-in Java types can end up using affected by this issue.

What this means in practice is that a task with an `@Input File getFile()` property would be treated the same across different versions of an Oracle JVM, but would be treated as different if ran on an Oracle vs IBM JVM, because we only track the name and vendor, but no version information. This clearly doesn't make much sense.

As to whether any user code can be affected, that's not so clear to me. Should user code be loaded with a custom classloader (i.e. one created by non-Gradle code), then the result would be an invalid classloader hash. So that's not an issue.

Can user code be loaded via a Gradle-managed classloader that is not also rooted in a known classloader like "Gradle API"? I don't know. Maybe we do something like this when running worker API items in `CLASSPATH` or `PROCESS` isolation mode—but we don't fingerprint anything there, so again the problem doesn't arise.

(And while we are talking about system classloaders, is there a point in that we track both `ClassLoaders$AppClassLoader` and `ClassLoaders$PlatformClassLoader` (but not `ClassLoaders$BootClassLoader`)? Probably not, as we should only ever see `ClassLoaders$AppClassLoader` in any case.)

OK, so what should we do about this? I think there are the following questions to answer:

* when comparing two executions of the "same" work item (e.g. task, transform etc.), how should we take the Java VM's version used into account?
  * vendor: we can ignore it or take either the specification vendor (`java.vm.specification.vendor = Oracle Corporation`) or the VM vendor (`java.vm.vendor = AdoptOpenJDK`) into account
  * version: we can ignore it, or take either the specification version (`java.vm.specification.version = 11`), the VM version (`java.vm.version = 11.0.3+7`) or the full Java version (`java.version = 11.0.3`) into account
  * we can also take the VM name (`java.vm.name = OpenJDK 64-Bit Server VM`) into account or ignore it

(On a related note, we should also figure out how to treat the version of the Java compiler used for (and the VM used to run) `JavaCompile`.)

**Comment by lptr** [comment]
After some thoughts I think we should track the following things:

* for any type (Gradle-related or not) we should take into account the VM specification:

```properties
java.vm.specification.name = Java Virtual Machine Specification
java.vm.specification.vendor = Oracle Corporation
java.vm.specification.version = 11
```

* for the Java compiler's version we should take into account the Java specification:

```properties
java.specification.name = Java Platform API Specification
java.specification.vendor = Oracle Corporation
java.specification.version = 11
```

Doing so means the following:

* the `name` is essentially ignored, as `java.specification.name` and `java.vm.specification.name` are more or less fixed strings
* the `vendor` is taken into account, because we've seen major differences between vendors' implementations of both the compiler and the VM (like how `IBM JDK6` builds used to fail when all tests on Oracle Java 6 VMs passed)
* we'd only track the major version number; while complete correctness would require tracking the full version (`11.0.3` for the compiler and `11.0.3+7` for the VM), because we've seen bugfixes in patch releases of the Oracle VM in the past that had an effect on compiled classes or execution order. However, doing so would mean that everyone would have to use exactly the same version, which sounds unnecessarily restrictive in a real-world environment involving actual developers with their self-managed JDKs etc.

**Comment by lptr** [comment]
As to the current situation: I think it's a good idea to remove the duplicate `vm.vendor`, and we should mostly be fine. We definitely shouldn't change things until 6.0 to avoid breaking existing builds in a minor version.

**Comment by oehme** [comment]
> The classloader hierarchy hashes we are working with here are used in Gradle to determine the fingerprint of objects of types that are unknown to Gradle. 

I don't understand, why are they only used for "unknown" types? Aren't they used for task implementations too?

> Practically this means that we treat the Gradle API as completely independent of the Java VM it is running on. Is this a good decision? It does provide a lot of flexibility in any case, and nobody reported a problem, yet.

This seems wrong, we shouldn't just stop hashing when we encounter the Gradle API. The version of the JVM can definitely have an impact, as can a different bootstrap classpath (e.g. on JDKs with additional APIs).

I agree with your proposed behavior.

**Comment by lptr** [comment]
@adammurdoch can you please take a look at the plan to address this?

**Comment by wolfs** [comment]
I think @lptr's proposed change strikes a good balance between reliability and effectiveness of caching.

The current state in ignoring the Java version/vendor for tasks in general completely is also not too bad IMO: The expectation for me is that the same Java bytecode would have the same effect on all JVMs, no matter the version. It only won't if there is a bug. If there is a bug, then the task will probably fail anyway, so we won't cache the result. So the only thing which would possibly happen is that a task passes locally when coming from the cache but fails when actually executed. That seems to be good enough for me.

Taking the Java vendor/version into account for e.g. people using Gradle for native development would mean that all of them would need to use the same Java version for running Gradle in order to have cache hits. While this is not a bad practice, the native developers would maybe surprised by this requirement, given that they only work with the native code.

**Comment by lptr** [comment]
So should we, or shouldn't we track the JVM version/vendor for classloaders?

**Comment by lacasseio** [comment]
I agree that for native development, the JVM version should be irrelevant. Some task bridging the native with JVM may require this like JNI but we don't have such task yet.

**Comment by sorin-florea** [comment]
I have reopened this because for most types that we track, they are loaded via one of our classloaders, and thus we never hit the system classloader. We only use the JVM version when tracking a task or transform or nested type that was loaded directly through the system classloader.
