### ISSUE TITLE
How to use jetty.server.Server

### ISSUE THREAD

**Issue by amjltc295** [gradle/gradle#9357]
Hi, I'm new to Java and Gradle. I need to use `org.eclipse.jetty.server.Server` to write a web package like Flask in python, as there seems to be no counterpart for Python's HTTPServer in the Java built-in library.
I noticed that the jetty plugin is deprecated and I used Gretty instead as suggested. However, I failed to import the org.eclipse.jetty module with `error: package org.eclipse.jetty.server does not exist`.
I tried to add the jetty plugin in `build.gradle` but it was not found.
How could I set up the `jetty.server.Server`? Is downgrading the Gradle version the only choice? Is there any workaround or alternative for `jetty.server.Server`?

**Comment by amjltc295** [comment]
I found that I might mix up Gradle dependency and plugins. The jetty plugin is deprecated and replaced by gretty, while the jetty package could still be used by java code through the gradle dependency setting.
Please correct me if I am wrong.

**Comment by bmuskalla** [comment]
Thank you for your interest in Gradle!

Please ask such a [usage question](https://github.com/gradle/gradle#need-help) on discuss.gradle.org or stackoverflow.com where to get answers by the community of Gradle users.

If, after investigation, it turns out to be a Gradle bug or missing feature, please file another issue describing the problem or use case and add a reproducer.
