### ISSUE TITLE
optional dependencies for registered features are in the wrong scope in published POM

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9379]
I build a library project that optionally supports different other libraries depending on what is available at runtime.
I found that Gradle now supports these via registered features.
So I did it like
```kotlin
java {
    val main by sourceSets
    registerFeature("lib1Support") { usingSourceSet(main) }
    registerFeature("lib2Support") { usingSourceSet(main) }
}
dependencies {
    "lib1SupportApi"("lib:one:1.0.0")
    "lib2SupportImplementation"("lib:two:2.0.0")
}
```

All seems to work as expected, it compiles and in the generated POM from `generatePomFileForMyPublication`, the dependencies are listed with `optional` set to `true`.

The issue is, that I would have expected `lib:two:2.0.0` to be in `runtime` scope in the generated POM as it is in the `...Implementation` configuration.
But actually both dependencies are put into the `compile` scope.

**Comment by ljacomet** [comment]
That is indeed a limitation of the current implementation. That shortcut was taken since anyway the `optional` dependencies in a Maven POM can never be used by either Gradle or Maven.

Note that the dependency will be in the right variant in the Gradle Module Metadata.

If you feel like improving this is important, a PR would be welcome: see `DefaultMavenPublication#dependenciesFor`

**Comment by ljacomet** [comment]
Because of the _documentation only_ aspect of `optional` dependencies in Maven, this is very unlikely to get any traction.
Unless someone steps up to take care of this, I would close this issue.

**Comment by ljacomet** [comment]
Closing given the lack of reaction and Gradle Module Metadata being correct in this case.

**Comment by jjohannes** [comment]
For possible follow up work in this area: #11254
