### ISSUE TITLE
publishing plugins do not use configuration avoidance API

### ISSUE THREAD

**Issue by Vampire** [gradle/gradle#9381]
I tried to do the following:
```kotlin
publishing {
    publications {
        register<MavenPublication>("my") {
            val java by components
            from(java)

            pom {
                description(project.description)
            }
        }
    }
}
```
But unfortunately this does not work properly.
What I mean is, that the description does not get set in the POM, as the description property is set after this is evaluated.
To make it work properly I had to do it like this:
```kotlin
publishing {
    publications {
        register<MavenPublication>("my") {
            val java by components
            from(java)

            pom {
                afterEvaluate {
                    description(project.description)
                }
            }
        }
    }
}
```
From a little debugging I'd say the reason is, that the `PublishingPlugin` does `extension.getPublications().all(new Action<Publication>() {`and the `MavenPublishPlugin` does `mavenPublications.all(new Action<MavenPublicationInternal>() {` which then both individually cause the eager configuration of the publication.

**Comment by Vampire** [comment]
Another workaround would be to set the description in `gradle.properties` instead of programmatically.

**Comment by lacasseio** [comment]
Thanks for trying out the configuration avoidance APIs. Unfortunately, the laziness in the domain object containers only works with the `TaskContainer`. There is a missing API to link two containers lazily. We prototype something last week, but some refactoring in those container codes need to be achieved before we can release the API. Bare with us while we move forward on this.

**Comment by Vampire** [comment]
Ah, sorry.
Somehow I thought this will also work.
I wasn't aware this is for now only working with tasks.
But it should all work properly if I use `register` now already and will work avoiding when it is implemented properly in Gradle core, right?

**Comment by lacasseio** [comment]
In theory, yes. There are some pitfalls. The main one is linking two containers lazily. We have a plan but need to do some refactoring before we can move forward.

**Comment by jjohannes** [comment]
I think laziness is sufficiently supported by the publishing plugin by using the provider API for all properties. So this is working fine (tested with Gradle 6):

```
publishing {
    publications {
        register<MavenPublication>("my") {
            val java by components
            from(java)
            pom {
                description.set(provider { project.description })
            }
        }
    }
}
```

**Comment by cspurk** [comment]
@jjohannes I tend to disagree that “laziness is sufficiently supported by the publishing plugin”. You have shown that it’s possible to lazily set a POM description, however, that’s not possible for [the POM packaging](https://docs.gradle.org/6.6/javadoc/org/gradle/api/publish/maven/MavenPom.html#setPackaging-java.lang.String-) or even [the publication version](https://docs.gradle.org/6.6/javadoc/org/gradle/api/publish/maven/MavenPublication.html#getVersion--), for example.

This is not only an issue for the `MavenPublication` type but also for the `IvyPublication` type. For example, I have tried to lazily set the publication revision without success. When I `./gradlew publish` in the following sample project, the published revision is `42` instead of the expected `123`:

```groovy
plugins {
    id 'java'
    id 'ivy-publish'
}

group = 'com.example'

def myRevision = objects.property(String).convention('42')

publishing {
    repositories {
        ivy {
            url = 'file:///tmp/myRepo'
        }
    }
    publications.register('myPublicationName', IvyPublication) {
        revision = myRevision.get()
        from components.java
    }
}

myRevision.set('123')
```

Am I doing something wrong or should we maybe reopen this ticket?
