### ISSUE TITLE
InputChanges doesn't report changed directories for incremental builds

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9387]
When an incremental build is run, if a file changes/is added/is removed, its parent directory isn't reported as changed even it's reported as added when a clean build is run.

**Comment by wolfs** [comment]
For a clean build, the parent directory is reported as changed, since it was not there before. For an intcemental build, a directory (parent or not) will be reported if it changed (i.e. if it has been removed or added). If the parent directory keeps existing, then it is not reported as changed, as expected.
