### ISSUE TITLE
Workaround for afterEvaluated which not triggered after project was evaluated

### ISSUE THREAD

**Issue by rbenb** [gradle/gradle#9395]
Hi,

**The problem:**
When having project a and project b, trying to call a.afterEvaluated from b won't be triggered since a already evaluated.
We need to be able to do additional steps even though a already have been evaluated.

**Suggested workaround:**

afterEvaluated(Project p, Action<Project> c) {
        if (p.getState().executed) {
            c.execute(p);
        } else {
            p.afterEvaluate c;
        }
}

Is it safe to rely on getState().executed? 
Is there any reason why this can cause issues now or in the future?

Thanks.
Roi.

**Comment by noproxy** [comment]
When ```getState().getExecuted() == false```,  it can be assured that the Gradle has not started call any ``afterEvaluate`` actions.  The actions you register at now will be called. 
https://github.com/gradle/gradle/blob/2e4bf002e55d32a8bc08d3d3350859b1f7040b0d/subprojects/core/src/main/java/org/gradle/api/internal/project/ProjectStateInternal.java#L47-L52

I think you can rely on it because it's one of the public api in ```org.gradle.api.ProjectState```.

BTW, it should have been warned or thrown error to register afterEvaluate action when the state  is CONFIGURED.   See #1135
