### ISSUE TITLE
Deprecate legacy publishing plugins (maven and ivy)

### ISSUE THREAD

**Issue by jjohannes** [gradle/gradle#9408]
They are superseded by the maven-publish and ivy-publish plugins.

**Comment by melix** [comment]
We should be relatively confident that we can do so before. For example, the Spring team somehow _sorts dependencies_ before writing the POM files (apparently to make diffs easier). While we don't encourage this (because ordering is important), this is a use case which is _not_ covered by the new publishing plugins.

**Comment by bigdaz** [comment]
Once the legacy `maven` plugin has been removed, we should be able to remove a bunch of 3rd-party dependencies from the `maven` subproject:
```
    implementation(library("pmaven_common"))
    implementation(library("pmaven_groovy"))
    implementation(library("maven3_wagon_file"))
    implementation(library("maven3_wagon_http"))
    implementation(library("plexus_container"))
    implementation(library("aether_connector"))
```

**Comment by jjohannes** [comment]
Also check existing `@Deprecated` in the `ivy` and `maven` projects. If they concern the new plugins, remove the deprecated part for Gradle 6. If they concern the old plugins, just leave them in and deprecate everything else in addition.

**Comment by jjohannes** [comment]
There are also some samples left in [docs/src/sample](https://github.com/gradle/gradle/tree/cad0ed7f572bd35d53a33a208022d3e68edb84cb/subprojects/docs/src/samples ) that use `:uploadArchive` instead of maven- or ivy-publish. We should update them.
