### ISSUE TITLE
BOM resolution failure when the plugins block is used for a locally published plugin

### ISSUE THREAD

**Issue by aloubyansky** [gradle/gradle#9424]
It appears using `enforcedPlatform` (or `platform`) for a Gradle plugin which is available only in the local repo breaks the dependency resolution. Here is a minimal reproducer and instructions
https://github.com/aloubyansky/playground/tree/gradle-plugin-bom

Thanks!

**Comment by ljacomet** [comment]
Thanks for the report and the reproducer.

**Comment by ljacomet** [comment]
The issue was caused by the metadata being loaded without the Java derivation strategy being applied _and_ the in-memory processed metadata cache not taking into account the derivation strategy in its cache key
The first part has been fixed as part of this issue, the second part will be fixed in #9415 as its occurrence in practice is near impossible.
