### ISSUE TITLE
InputChanges.getFileChanges for List of file collections

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9443]
I have a property that returns a list of file collections of variable size (generated at runtime). How can I get the file changes for that property given that only `FileCollection` is accepted.

**Comment by wolfs** [comment]
Currently, you can't. Can you describe your use-case a little bit more? Maybe there is a different way to solve it. If there isn't, then maybe we need to change the API.

For context, we only allow querying `FileCollection` and `Provider` via input changes, since those are the property types we expect tasks to be composed of. Normally, we expect the input file properties to be a `ConfigurableFileCollection`, a `DirectoryProperty` or a `RegularFileProperty`.

**Comment by SUPERCILEX** [comment]
Yeah, I already solved it, but it still feels a tad clunky:
```kt
// Old:
variant.sourceSets.map { project.fileTree("src/${it.name}/$PLAY_PATH") } // List<ConfigurableFileTree>

// New:
project.fileTree("src").apply { // ConfigurableFileTree
    for (dirName in resSrcDirNames) include("/$dirName/**")
}
```

If you think my solution is adequate, feel free to close this issue.

**Comment by wolfs** [comment]
How about this:
```
public ConfigurableFileCollection getInputFiles();

...

getInputFiles().from(variant.sourceSets.map { project.fileTree("src/${it.name}/$PLAY_PATH") })
```

**Comment by SUPERCILEX** [comment]
@wolfs My current solution is fine, but just FYI, yours doesn't work since `from` is supposed to resolve to a single file:
![image](https://user-images.githubusercontent.com/9490724/57946671-c445a380-7891-11e9-941f-259fd4f9832e.png)

**Comment by wolfs** [comment]
@SUPERCILEX Strange, this works for me:
```
interface MyBean {
    ConfigurableFileCollection getInputFiles()
}

println objects.newInstance(MyBean).inputFiles.from([fileTree("my-base-dir"), fileTree("my-other-base-dir")]).files
```

**Comment by SUPERCILEX** [comment]
@wolfs It worked, thanks!
```kt
@get:SkipWhenEmpty
@get:PathSensitive(PathSensitivity.RELATIVE)
@get:InputFiles
protected val resSrcTree by lazy {
    project.files(resSrcDirNames.map {
        project.fileTree(it).apply { exclude("**/.*") }
    })
}
```
