### ISSUE TITLE
Can not have script named "signing.gradle.kts" in buildSrc

### ISSUE THREAD

**Issue by AndrewReitz** [gradle/gradle#9444]
When using the kotlin dsl in buildSrc if you add a plugin file named `signing.gradle.kts` in the `src/main/kotlin` directory, then apply it to your project with 
```
plugins {
    id("signing")
}
```

It will never be applied to the project.

### Expected Behavior

The plugin should be applied to the project.

### Current Behavior

Plugin is not applied to the project.

Sample project can be found here https://github.com/AndrewReitz/buildSrc-plugin-issue

**Comment by big-guy** [comment]
This is caused by an overlap with built-in plugin id and your script id.  Gradle ships with a `signing` plugin.
You can see this in the build scan:
https://scans.gradle.com/s/eq7c3hcmd5yua/plugins?expanded=WzI0XQ

I would recommend using a package name for your script so it doesn't get flattened into the default namespace.
