### ISSUE TITLE
API to access gradle build cache key of task

### ISSUE THREAD

**Issue by llaforest** [gradle/gradle#9456]
### Expected Behavior
When a task execute, I would like to be able to access the build cache key that gradle computed

### Current Behavior
There is no API to do that so it can be seen only within log files

### Context
We are building docker images and it would be very inefficient to have to save them and copy them to the gradle cache. We would like to use the docker registry (local or remote) like a gradle cache but we need access to the cache key so we can validate all inputs are unchanged and go with upToDateWhen closures.

**Comment by lptr** [comment]
The cache key Gradle calculates is an implementation detail that we don't want users to rely on. This is why there is no public API to access it. Its value can and will change due to factors that might not be suitable for your usage. Calculating your own key using inputs specific to your use case is recommended instead.

**Comment by llaforest** [comment]
I would use the cache key the same way gradle uses it. If the implementation changes, it invalidates all the gradle build cache and this is fine with me. It would also be fine with me if it invalidated my docker cache implementation.
I think if it was just documented as unreliable then developers would be able to make their own choices.
The fact is that it is not always possible or efficient to put stuff in the gradle cache but I think the idea of caching goes beyond that.
Why force people to recode something that works fine?
