### ISSUE TITLE
Tooling API: offer a way to stop inactive daemons only 

### ISSUE THREAD

**Issue by amakeev** [gradle/gradle#9539]
Currently, when an IDE shuts down, it also tells all daemons to stop (to free the memory used by the now-inactive Gradle daemons).

This might lead to a problem, if a user has a running Gradle build in background ([report](https://youtrack.jetbrains.com/issue/IDEA-185242))

As a simplistic solution, the IDE could tell all inactive daemons to stop, leaving all other running Gradle processes intact.

relates to #8010, #8219

**Comment by tcfurrer** [comment]
Stopping an inactive daemon could still have impact on the performance of gradle processes that are independent of the IDE that started the daemon.  So if there were a way to request all inactive daemons to stop, it would need to be something that is done very infrequently.  Otherwise it could significantly hurt performance.  If it were only called at IDE exit time, that's very infrequent, so it would probably be OK.  But if the API provided a way to request that daemons stop... it seems like there is at least some potential for misuse.  On the other hand, the concerns about freeing memory are also a real issue sometimes.

A more accurate thing would be if somehow each agent using the gradle daemon had a unique identity (i.e. the process ID, or anything else), and that identity was used to track all memory usage inside the daemon, so that this agent could request that the memory consumed by the daemon on its behalf be freed.  That allows for the possibility that the daemon continues running and holding its memory that "belongs" to other agents.

**Comment by big-guy** [comment]
This is what the new (6.5) API tries to do https://docs.gradle.org/nightly/javadoc/org/gradle/tooling/GradleConnector.html#disconnect--

I'll update the Javadoc to make that clearer.
