### ISSUE TITLE
Tasks that had empty inputs should not be annotated with UP-TO-DATE

### ISSUE THREAD

**Issue by hansd** [gradle/gradle#955]
When a tasks input directories are empty or do not exists it is annotated with UP-TO-DATE in the command line output. 

### Expected Behavior
I find this behavior very confusing. When you don't do a clean build it suggests this task actually did work previously. In the case of a clean build it is even more confusing. How can the build output be up to date when I did a clean?

### Steps to Reproduce (for bugs)
To reproduce use the samples/quickstart/java project and remove the src/test/resources directory. Here is the build scan when doing a clean build with a link to the output line: https://scans.gradle.com/s/oxyuvkpdesxvq/log#L13

**Comment by huxi** [comment]
My original PR #668 was setting those tasks to [SKIPPED](https://github.com/gradle/gradle/pull/668/commits/65823524f19973cba4eaa5269e9d8fadc3eebb36#diff-6cade20aec360b51abe21f7cb989a548R51).

Similarly, I suggested that the task should say [CLEANED](https://github.com/gradle/gradle/pull/668/commits/65823524f19973cba4eaa5269e9d8fadc3eebb36#diff-6cade20aec360b51abe21f7cb989a548R70) (or something along those lines) if the task previously generated output but lost its inputs subsequently causing the outputs to be deleted.

Would this be the expected behavior?

**Comment by huxi** [comment]
The rationale for a separate `CLEANED` state is the following:
Assume a task that created thousands of files in a directory hierarchy and this task loses its input.

Gradle would take a recognizable amount of time removing those files and directories (especially on non-SSD systems) and then just state `UP-TO-DATE` (currently) or `SKIPPED` (my suggestion), at the same time reporting that it took a few seconds.

It would look to a user like Gradle took that long to realize it didn't have to do anything while in fact it was actually hard at work the whole time. Subsequent runs would again be very fast.

I realize that this is only an edge case and that most users wouldn't even take notice but I'd still prefer more info about what's actually going on over surprising behavior ("_Why did it take so long?_").

**Comment by lptr** [comment]
@hansd: what is the expected behavior from your point of view? To me using `SKIPPED` would be a better option. We did not change it previously (when merging @huxi's PR), because it would have been somewhat of a breaking change. With 4.0 coming up we can do this more easily.

@huxi: I'm a bit confused. When a task with empty inputs had to removed previously created outputs we [report it as executed](https://github.com/gradle/gradle/blob/3ad1f0e85639f7bfcd1ded6e3f81af7ea1e46aac/subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/SkipEmptySourceFilesTaskExecuter.java#L78-L78), and not as `UP-TO-DATE`. I think that's the right way to handle such a situation, because in such a case the task _did_ do some work.

**Comment by huxi** [comment]
@lptr That seems to have changed in the meantime. My knowledge of the code predates the `TaskExecutionOutcome` enum. `CLEANED` (or whatever it would have been called) was meant as a special version of `SKIPPED`, indicating that the task did not execute but cleanup was performed instead.

I'm still wondering whether this would justify a different `TaskExecutionOutcome` value because actual task execution is something quite different than the unspecific cleanup of previously generated task outputs. The task itself isn't actually being executed, _something else_ (the general task cleanup logic) is.

If a task had a `println` in its body than that would not be executed even though the build output indicating execution would suggest that it should. This could be a source of confusion.

This is not a big thing because it really *is* an edge case. I simply like to see - as explicitly as possible - what is happening/taking time in a given build. While I wouldn't open an issue about this, it still feels like the build system is kind of "lying" to me by not "telling the whole story".

**Comment by lptr** [comment]
Please note that we never expose "executed" as a term to users. We display no status text next to the task name on the console, `TaskState` doesn't expose this property at all (`getExecuted()` does something different), and TestKit reports the `TaskOutcome` as `SUCCESS`. I think the source of confusion here is the internal `TaskExecutionOutcome.EXECUTED`, which users have no access to. We could rename it for clarity, though.

Anyway, let's keep this issue about how we report tasks that were skipped because their `@SkippedWhenEmpty` properties were empty. The logical thing to do would be to use `SKIPPED` instead of `UP-TO-DATE`, I think we all agree on that. Let's do this for Gradle 4.0.

**Comment by hansd** [comment]
I don't think we should use SKIPPED necessarily. For me SKIPPED indicates that a task is disabled, e.g. you might skip as task because you detect a certain setting in your runtime environment. So having empty inputs is an important case that I think deserves special treatment. But I don't feel very strong about it.

**Comment by lptr** [comment]
One vote for `SKIPPED` is that we call the annotation `@SkipWhenEmpty`.

**Comment by hansd** [comment]
Well, it is all about allowing the user to reason properly of what is going on.

**Comment by adammurdoch** [comment]
It might be useful to not show them at all. When these tasks have no source, they are not required.

**Comment by hansd** [comment]
Absolutely. That is the end goal IMO for the commands line output. I even prefer to have just dynamic progress information and the only permanent output for the commands line should be warning/errors. But in a build scan for example I still want to be able to distinguish between no work vs up to date.

**Comment by big-guy** [comment]
We ended up introducing 'NO-SOURCE' for these tasks.
