### ISSUE TITLE
Gradle reports task up to date when it is not

### ISSUE THREAD

**Issue by miokowpak** [gradle/gradle#9554]
I have this task:

```
    apply plugin: 'com.moowork.node'

    node {
        version = '8.14.0'
        yarnVersion = '1.16.0'
        download = true
    }

    task install(type: YarnTask, dependsOn: configurations.devNodeModules.allDependencies) {
        args = ['install', '--check-files']
        inputs.file('package.json')
        inputs.file('yarn.lock')
        outputs.dir('node_modules')
    }
```

If I run this task in a clean repo, the `node_modules` directory is correctly created.  However, if I delete the `node-modules` directory, and re-run the task, gradle reports that it is up to date.

### Expected Behavior

When I re-run the task, it reports it is out of date and regenerates the directory.

### Current Behavior

The task is reported as up to date.

### Context

Works fine in gradle 5.4, `gradle-5.5-20190527013009+0000-bin.zip` and  `gradle-5.6-20190525002310+0000-bin.zip`. It appears to have stopped working in `gradle-5.6-20190526000036+0000-bin.zip`.

This task is installing node_modules for me.  Other tasks that depend on this task expect those files to be there, when they are not, the build breaks.  Specifically, if I run a clean command and then attempt to rebuild everything, the build will fail.

**Comment by wolfs** [comment]
@miokowpak Thank you for reporting. Does the same problem appear when you remove the `node_modules` directory and the `.gradle` directory before you run the first build?

**Comment by miokowpak** [comment]
It appears that if I remove both directories prior to my first build, everything appears to work as expected.

My apologies if removing the `.gradle` directory is a required step when uploading that I missed.

**Comment by wolfs** [comment]
@miokowpak It is not necessarily a step that you missed, the task should work without you deleting those directories.

From what you report, the following happened: On the first run of your build, the `npm_modules` directory already existed and the task did not change anything in the directory. Therefore, Gradle determines that the outputs of the task is nothing, since it didn't change anything in the directory. As a consequence, when you remove the `npm_modules` directory later on, the task is `UP-TO-DATE`.

If the `npm_modules` directory would be within the `build` directory, then Gradle would determine that it is safe to delete and would have deleted it on the first run of the task for preparing the outputs of the task and everything would have worked as expected. I understand that the location of the `npm_modules` directory is predetermined by `npm`, and therefore the plugin normally won't change anything about it.

In general, when Gradle tracks outputs in a directory, it works best if only Gradle itself (and its tasks) does changes to the output directory. For example for `npm`, running `npm` on the command line to install new modules may also confuse the `npm` task later on, since it doesn't know the created file belong to the output of the task.

The current workaround is that you only use the Gradle task to update the `npm_modules` directory. Then everything should work as expected.
