### ISSUE TITLE
Gradle linux memory consumption

### ISSUE THREAD

**Issue by manthesepeasrock** [gradle/gradle#9577]
Making sequential builds without killing gradle deamon leads to lots of memory consumed that is only released by killing the java process. I used JProfile to check what happens when making some builds on the same deamon, and I believe that the issue is that loaded classes are not disposed after the build finishes, and every new build after that adds more classes to the process.

### Expected Behavior
No incremental RAM usage on every build

### Current Behavior
RAM usage is always increasing in an alarming rate, forcing the system to use the swap partion and making it unresponsive until the java process is killed

### Steps to Reproduce 
Link for the JProfile snapshot of the gradle process while making 3 or 4 builds with minor changes to the project: [https://drive.google.com/file/d/1O_gj0CMWVnzxhr3GpOq0UTvdZIpOllO1/view?usp=sharing](https://drive.google.com/file/d/1O_gj0CMWVnzxhr3GpOq0UTvdZIpOllO1/view?usp=sharing)

### Your Environment
gradle.properties:

> org.gradle.jvmargs=-Xmx3096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
> org.gradle.parallel=true
> org.gradle.daemon=true
> org.gradle.configureondemand=true
> org.gradle.caching=true
> 
> kapt.use.worker.api=true
> kapt.include.compile.classpath=false
> kapt.incremental.apt=true
> 
> android.useAndroidX=true
> android.enableJetifier=true
> android.enableR8=true
> android.enableWorkers=true

system:
> Ubuntu 19.04
> 16Gb RAM
> 8Gb Swap

**Comment by big-guy** [comment]
Hi @manthesepeasrock 

I don't see anything too concerning in the snapshot you provided, although I do see that the number of classes loaded is going up a lot. Which version of the JDK are you using?  Are you seeing high GC time or OutOfMemory errors?  Unless you're seeing build failures with your current settings, I don't think there's necessarily a problem.  

Gradle needs to keep around classes between builds because that keeps them warmed up in the JVM and subsequent builds can benefit from that.  The number of classes loaded does seem high in your case, but I can't tell if they would eventually be GC'd from the snapshot alone. 

I don't believe that the increasing class count alone would account for system wide troubles.  Are there multiple JVMs running (you can check with `jps`) that happen to be shutdown when you kill the daemon? The JVM is limited to ~3GB in your example, so it should not be able to consume more than that. 

What I would expect is that if there was a memory leak, the build would fill up the heap over time and permanently remain high.  Eventually, builds would hang or fail with OOM errors.

**Comment by manthesepeasrock** [comment]
Hi @big-guy , thanks for the fast response :)
forgot to mention that I'm using gradle 5.4.1, but this was an issue on older versions too

java -version
> openjdk version "11.0.3" 2019-04-16
> OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu219.04.1)
> OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu219.04.1, mixed mode)

jps
> 28323 Jps
> 17156 Main
> 17878 GradleDaemon
> 21391 KotlinCompileDaemon

I think we don't see an OOM error because when the ram fills up and the swap starts to be used the system comes to a crawl and I have to kill the java process

**Comment by manthesepeasrock** [comment]
@big-guy just made a more lengthy snapshot, I do not have OOM erros, but the ram consumed is still alot, I was only running Android Studio, JProfile and GitKraken but still had my ram fill up.

JProfile snapshot: [https://drive.google.com/file/d/1mTRK82Bc7C2UM7IakcYOyzNCen75NbDG/view?usp=sharing](https://drive.google.com/file/d/1mTRK82Bc7C2UM7IakcYOyzNCen75NbDG/view?usp=sharing)

jps output after finishing the JProfile session:
jps
> 2672 KotlinCompileDaemon
> 31290 UnixLauncher
> 31725 Main
> 32605 GradleDaemon
> 1373 KotlinCompileDaemon
> 7165 Jps
> 2382 GradleDaemon

And a screenshot from the system manager:
![2019-05-31_12-22](https://user-images.githubusercontent.com/11760727/58703212-cc2c3a00-839f-11e9-8a41-5bf606d0a42b.png)

**Comment by oehme** [comment]
Loaded classes going up is not normal and usually points to a faulty plugin. To help you analyze we'll need a heap dump instead of a continuous recording though. Can you create one after a few builds please?

**Comment by manthesepeasrock** [comment]
Hi @oehme, 

Here is the [heap dump](https://drive.google.com/open?id=159VJvtKD6lnBdX-SSHelB0EMSb94JwB5) from JProfiler and the [Snapshot](https://drive.google.com/open?id=15jCE4mFYpNyH0I-HSjoPSOCtK2IKVxtN) from were the heap dump was generated

**Comment by oehme** [comment]
Looks like a known memory leak caused by unclosed ForkJoin pools in the Android plugin. I think that was fixed in more recent versions, but I might be mistaken. Can you make sure you're on the latest version? If that doesn't fix it, please open an issue for the Android team with this heap dump attached.

**Comment by manthesepeasrock** [comment]
Thanks @oehme 

We are using com.android.tools.build:gradle:3.5.0-beta03, I will try with the newer version on the canary channel, if the issue is still there I will report it to them. Tks ;)

**Comment by orcchg** [comment]
still an issue even for stable **com.android.tools.build:gradle:3.5.0**

**Comment by anik-kucse** [comment]
is there any update about this?

**Comment by diaraujo13** [comment]
I have same problem on my Linux Mint 19.03

<img src='https://imgur.com/3QqSqSj.png' />
<img src='https://imgur.com/5xhRgiT.png' />

**Comment by andrewfrench-fluxfederation** [comment]
I've had the same experience on Ubuntu 18.04, 19.04, 19.10 & 20.04 using Android Studio 3.5 all the way through to 4.1 Canary 8. Basically the daemons keep consuming RAM until Android Studio is killed or all the RAM on the machine is used and my laptop turns into a paperweight for 20mins.

**Comment by nalin243** [comment]
I have been having the same experience. I can't work on android studio for more than 30 minutes at a time because the ram used keeps increasing and eventually I have to shut it down.

**Comment by zde-nekz** [comment]
Same experience here. I did small test on Ubuntu 20.4. 
Running Android Studio and emulator memory usage was 4.9GB. 
after 1.build 9.4
2. build  10.6
3. build 10.8
4. build 11.2
and so on until all 16GB RAM is used and computer slows down and freezes.

**Comment by zhaoguomanong** [comment]
same bug on ubuntu 16.04LTS,  using android studio from 2017 to today. all versions has this memory consumption bug.

**Comment by DimensionalCoder** [comment]
Please reopen this issue. Android Studio is becoming unusable after each Gradle build.

**Comment by zhaoguomanong** [comment]
100% reproduced issue, pay much attention on it please.

**Comment by blindpirate** [comment]
Can you please provide a heap dump? That would be awesome. Without a heap dump I'm afraid we can't help much.

**Comment by zhaoguomanong** [comment]
@blindpirate  can you give me the jmap complete command to dump heap? when dumping?
 Do you have linux desktop? It's very easy to reproduce.
1. open android studio for linux
2. build  app project, -> clean build ->build app, do these actions continuously...
3. use ps aux | grep -i gradle to see the process memory consumption, you will see the memoery increase continuously

**Comment by blindpirate** [comment]
> open android studio for linux

Which version of AS? Linux? JDK version/vendor?

> build app project, -> clean build ->build app, do these actions continuously...

Different app project behaves differently, the plugins used in the build can leak memory. It's apparently not every app project leaking, otherwise we'll get complaints from the entire community.

> you will see the memoery increase continuously

That's how JVM works. You need to run `jmap` to get heap dump of `GradleDaemon` process when the memory consumption is unbearable. Please search for the `jmap` command to be used: https://stackoverflow.com/questions/15130956/how-to-analyse-the-heap-dump-using-jmap-in-java

**Comment by NickWilde263** [comment]
Im also have issue where gradle trying consume all memory (include swap) and eventually make whole system not responding (because run out of swap space i use 4 GB of RAM and 4 GB of swap i trying to limit with org.gradle.jvmargs=-Xmx1000M -Xmn9M in the gradle.properties but nothing change in term of memory consumption but i still can use text mode terminal to kill the gradle with SIGTRAP instantly crash it with immediate 96% RAM and swap relief

**Comment by urgentx** [comment]
Has been happening to me for the last year on Android Studio + Ubuntu 18.04/20.04. Always update to the latest AGP. There end up being 3 java processes which eventually eat up all the memory. After I close Android Studio, 2 of them always remain, so I kill them manually.

**Comment by Arthur-Feng** [comment]
I am facing the same problem. There is my build environment

> Manjaro Linux with Linux Kernel 5.4, 16G RAM 5G swap
> Android Studio 4.1.1
> Gradle 5.6.4 whit Gradle Android Plugin 3.6.0

All the RAM will be eaten up after a few times build and start using swap, and system will be slow soon. Then I have to close Android Studio and restart it.

But strange thing is I just updated Linux Kernel from 4.19 to 5.4. Under Linux Kernel 4.19 with all the same build environment the RAM will be used soon but won't be eaten up and cause the system slow. Now I have to stay in Linux Kernel 4.19 to using Android Studio.

**Comment by NickWilde263** [comment]
> Has been happening to me for the last year on Android Studio + Ubuntu 18.04/20.04. Always update to the latest AGP. There end up being 3 java processes which eventually eat up all the memory. After I close Android Studio, 2 of them always remain, so I kill them manually.

i need to use boot into text mode(my linux only eat 46 MB of RAM  in text only) only to decompile minecraft for my 1.16.3 forge MDK and it almost eat all system memory including swap(122 MB left) then reboot again to graphical mode (my linux eat 600 MB)

**Comment by zanzara** [comment]
any updates  on that topic?
Because it stil remains.
I am running Kernel 6.1 and latets Android-Studio.
Gradle has smt with Version 7 
and thought android-Studion was close, gradle (java) consumes still some GBs of RAM!!!

Any remedies so far?

**Comment by Kudlayra** [comment]
> Any updates on that topic? Because it still remains.
> 
> I am running Kernel 6.1 and latest Android-Studio. Gradle got smt with Version 7
> 
> And thought Android-Studion has been closed, gradle (java) still consumes some GBs of RAM!!!
> 
> Any remedies so far?

i  fixed it in this way:

https://stackoverflow.com/a/79023162/19323132

**Comment by ashish293** [comment]
> > Any updates on that topic? Because it still remains.
> > I am running Kernel 6.1 and latest Android-Studio. Gradle got smt with Version 7
> > And thought Android-Studion has been closed, gradle (java) still consumes some GBs of RAM!!!
> > Any remedies so far?
> 
> i fixed it in this way:
> 
> https://stackoverflow.com/a/79023162/19323132

This worked for me.
