### ISSUE TITLE
Cannot convert the provided notation to a File or URI: true.

### ISSUE THREAD

**Issue by mcjp78** [gradle/gradle#9581]
### Expected Behavior
Should accept the FileTrees just fine and carry on.

### Current Behavior
Gives the error Cannot convert the provided notation to a File or URI: true.

### Context
I am trying to build a fat jar of a limited set of dependencies. There are only 5 dependencies. When I build a larger jar with more "stuff" in it, it appears to work as expected.

### Steps to Reproduce 
1. Add EXACTLY 5 Jars and attempt to add them to a jar with this code.
``` 
val firstLevel = project.configurations.getByName("limit")
            .resolvedConfiguration.firstLevelModuleDependencies.map { it.moduleArtifacts }.flatten()
        val trees =
            obfusFirstLevel.map { if (it.file.isDirectory) project.fileTree(it.file) else project.zipTree(it.file) }
        return project.files(trees)
```
That's it.
### Your Environment
```
------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          11.0.3 (Oracle Corporation 11.0.3+12-LTS)
OS:           Windows 10 10.0 amd64

```

**Comment by big-guy** [comment]
Hi @mcjp78!

It would be really helpful if you could provide a more complete example of the problem.  From your description, it's hard to tell where exactly you're trying your code and where things like `obfusFirstLevel` come from.

> Cannot convert the provided notation to a File or URI: true.

This seems to indicate that you're passing a boolean (true) to fileTree or zipTree instead of a File-like thing (File, String, Path, URI, etc). 

You can also take a look at https://github.com/johnrengelman/shadow, which is a plugin that provides fat jars (though, this may be overkill for what you're doing).

For now, I'm going to close this issue.  We can reopen it if you've found something that should work.
