### ISSUE TITLE
Support debugging tests via tooling API

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#9610]
Gradle should provide proper API to execute tests in debug mode.

### Context

Currently, the Tooling API offers a `TestLauncher` to execute tests, but it doesn't offer a debugging capability. Because of that IDEs have to resort to parameterizing the `test` task with `--tests` arguments. IntelliJ IDEA along with injecting custom debug parameters (ports) via an [init script](https://github.com/JetBrains/intellij-community/blob/ae6f7b344b3c267e71c687697d495017008a9df2/plugins/gradle/src/org/jetbrains/plugins/gradle/service/project/BaseGradleProjectResolverExtension.java#L859). The implementation there has a couple of drawbacks that have a negative impact on the perceived performance of Gradle.

### Design

TestLauncher should have a `withDebugMode(int port, boolean suspend)` method. If called, all JVMs executing tests should start with the `-agentlib:jdwp=transport=dt_socket,server=y,suspend=${suspend ? 'y': 'n'},address=${port}` JVM argument.

### Test Coverage

- If the tests are launched in debug mode then debuggers can be attached to the specified port.
- If the port is taken then the execution fails.
- If tests are launched in debug mode then all other, debug-related JVM arguments are removed (e.g. -Xdebug, -Xrunjdwp, -agentlib:jdwp, -Xrunjdwp:).
- If the test execution is canceled during debugging then the test JVM should shut down.
- If the test execution is canceled before the debugger could be attached then the test JVM should shut down.
- The test task is never UP-TO-DATE when test debugging is requested.

### Future work

Later we can extend the implementation such that if the requested debug port is 0 then Gradle automatically chooses a debug port and sends it back to the client in a progress event.

**Comment by oehme** [comment]
> The clean<TestName> needs to be called to work around the up-to-date check and force Gradle to re-execute the selected tests.

That's unrelated to debugging though. The IDEA team always wants tests to rerun, no matter if debugging or not. We can probably add this as an option to the test execution TAPI as well and then do `upToDateWhen { false }` under the hood of that mode is requested.

**Comment by oehme** [comment]
Looks good overall.

> withDebugOptions(int port), that covers the simple use-case

I'd probably add the `suspend` option to that simple use case

> s a next step, we could have a withDebugMode() method that doesn't take an argument and reports the chosen port via a progress event.

Why do we need an extra method for that? Isn't port `0` the way to specify that you want an auto-assigned one? Otherwise we'll get a bunch of overloads, e.g. what if I want an auto-assigned port, but additional args...

We also have the unrelated points in the description above (see my previous post), which we should remove, as they are confusing the reader about what the real problem is we want to solve here.

**Comment by donat** [comment]
Thanks for the suggestions. I've updated the original description according to your suggestions. I'll proceed with the implementation.

**Comment by nskvortsov** [comment]
Some IDE-specific thoughts.
 * having `suspend=n` does not make much sense, as the user expects the breakpoints to work right away.
 * As long, as the `server=y` is used, we need an event, saying that forked jvm is up and waiting for connection. Otherwise, `server=n` should be used.
 * If `TestLauncher`  effectively launches all test tasks passing the test pattern to them, won't it cause all test classes to be checked for up-to-date state? Feels like it can be a performance penalty.
* To migrate to `TestLauncher` API we need some reliable way to obtain test output and to attach it to specific test. How can we do it?

**Comment by vladsoroka** [comment]
Can we debug also other non-test gradle tasks in the same way? I.e. using the progress tooling debug events. 
E.g. the sequence can be looked as following: 
StartTaskDebuggingEvent (with debug parameters info) -> StopTaskDebuggingEvent(with debug parameters info)
Note, the target JVM process used for the task running can be the gradle daemon itself.

This can greatly improve/simplify our existing debugging of the gradle applications/tasks/tests/buildscript code.

**Comment by oehme** [comment]
> As long, as the server=y is used, we need an event, saying that forked jvm is up and waiting for connection. Otherwise, server=n should be used.

That's a good point and could get rid of the need for an event, by letting the IDE provide the server part and letting the debugged application connect to it, rather than the other way round.

@nskvortsov @vladsoroka the other points seem unrelated to this particular ticket, but more general issues with the Tooling API. I suggest that you collect them and go through them with Donát in the next sync call, so he knows what other features/improvements we need to make in order to make the Tooling API work well for you.

**Comment by LouisCAD** [comment]
This issue is the last one delaying 5.6 RC1, right?
