### ISSUE TITLE
`reproducibleFileOrder` does not work with include/exclude patterns

### ISSUE THREAD

**Issue by ketan** [gradle/gradle#9646]
### Context

I was attempting to create a zip file with identical set of files, but the zip file contents are different, even though `reproducibleFileOrder` and `preserveFileTimestamps` are turned on for reproducible builds.

### Steps to Reproduce 

1. Download the file `https://mirrors.edge.kernel.org/pub/software/scm/git/git-1.8.2.3.tar.gz`
2. Create the following `build.gradle` file

    ```
    apply plugin: 'base'

    task extractTar(type: Copy) {
      from tarTree('git-1.8.2.3.tar.gz')
      into "${project.buildDir}/tmp"
    }

    task goodZip(type: Zip) {
      archiveBaseName = 'good'
      reproducibleFileOrder = true
      preserveFileTimestamps = false

      from(extractTar) { include 'git-1.8.2.3/bundle.c' }
      from(extractTar) { include 'git-1.8.2.3/connect.c' }
    }

    task badZip(type: Zip) {
      archiveBaseName = 'bad'
      reproducibleFileOrder = true
      preserveFileTimestamps = false

      from(extractTar) { include 'git-1.8.2.3/connect.c' }
      from(extractTar) { include 'git-1.8.2.3/bundle.c' }
    }
    ```
3. run `gradle clean goodZip badZip`
4. run `diff build/distributions/*`
5. The output files `bad.zip` and `good.zip` will differ.

### Your Environment

Build scan URL: https://gradle.com/s/qh744lzolsa4u

**Comment by wolfs** [comment]
@ketan Thank you for reporting!

`reproducibleFileOrder` is meant to work with the same configuration of the copy task. It only has an effect when reading files from a directory (the files are sorted) and not when reading e.g. from a `tar` file. Reproducible file order means: the environment where the task runs will not influence the file order in the resulting JAR. A different configuration will affect the file order, though.

In your case, you could do
```
    from(extractTar) {
        include 'git-1.8.2.3/connect.c' }
        include 'git-1.8.2.3/bundle.c' }
    }
```

Then the file order would be the same, no matter which order of the includes you configure, since the TAR file will only be walked once.

**Comment by Lanchon** [comment]
I was about to report yet another instance of this, but i suspected it was a design trade off and i was right.

i suppose you can replace a Zip/Jar task with a Sync task to a tmp dir, then Zip/Jar in one go with reproducibleFileOrder set to sort this out. and yes, it's a simple enough solution/workaround.

the only problem is that so many times the archiving tasks are already setup for you by plugins, and you can't really do this. the best that you can do is extract and re-archive... 3 times the work. and then you also get pre-made tasks that consume the resulting archive, so this also dangerous and breaks silently unless you are 100% exhaustive modding the downward task chain. 

so... maybe consider adding another option that does this from an abstract base for all archiving tasks. if the option is set, it consumes the copy spec to copy to an empty tmp dir and passes a synthethic simple spec down the hierarchy. otherwise it passes the original spec. seems it might be low hanging fruit for you guys.

**Comment by Lanchon** [comment]
(@wolfs)

**Comment by wolfs** [comment]
@Lanchon Can you give me the use-case you are trying to solve? You want to reproduce the same archive even if the build script changes?

**Comment by Lanchon** [comment]
@wolfs, you know what? you are completely right. disregard this and focus development on useful things.

this would be squarely feature creep. i can't think of a proper use case.

> You want to reproduce the same archive even if the build script changes?

yes. i expected this and discovered it was not the case. my use case was this: i was doing gradle upgrade and major surgery to the build scripts, but wanted to make sure none of this affected the outputs. and because i run reproducible builds, i just hashed the artifacts and periodically rechecked that they remained constant as i evolved the build.

i cannot think of another use. i should have done a script to unpack and diff the content of archives. but i was lazy so just i hashed them instead. in short: my laziness is no reason for you tu add a feature.

thank you!
keep it up
