### ISSUE TITLE
Execute task after all others?

### ISSUE THREAD

**Issue by SUPERCILEX** [gradle/gradle#9657]
Is it possible to execute a task "after" the build has completed aka after all other tasks have run. Sort of like `finalizedBy` but for the entire build.

**Comment by big-guy** [comment]
It depends on what you're trying to do.

It's not a task, but there's [gradle.buildFinished](https://docs.gradle.org/current/dsl/org.gradle.api.invocation.Gradle.html#org.gradle.api.invocation.Gradle:buildFinished(org.gradle.api.Action)).  I wouldn't do anything expensive there (since it needs to be called all the time).

**Comment by SUPERCILEX** [comment]
Dope, thanks 👍
