### ISSUE TITLE
Are up-to-date checks and incremental java compilation not meant to be used on CI servers?

### ISSUE THREAD

**Issue by patkovskyi** [gradle/gradle#9664]
**UPDATE:**
Today I finally was able to get incremental Java compilation and UP-TO-DATE checks to work across machines by caching directories I listed below (initially, I had an error in dir moving logic). 
Although, my question remains: are these features not meant to be used on CI? If so, why? 

What made me ask this question: I figured that these features [require your BUILD_DIR to be an absolute path which does not change between builds](https://github.com/gradle/gradle/issues/9337), and this may be hard to achieve in CI environments. Also, it's not immediately clear which folders need to be cached in order for these features to work, so a user has to do some guesswork here.

**ORIGINAL TEXT**
I am trying to make incremental build (up-to-date checks) and incremental java compilation to work on CI servers. After spending significant time on these attempts, I feel like I can't make any progress on my own and need advice from the community. Maybe these features were never meant to work across machines? I know that the build cache feature was made to address this, but it works as "all-or-nothing" cache and does not provide incremental compilation.

I am using Gradle Wrapper 5.4.1 and Gradle 5.4.1. I am using standard compileJava task.
Here's a list of directories I cache across my build runners: 
1. GRADLE_USER_HOME/caches (absolute path, same on all runners)
2. PROJECT_DIR/.gradle (different path on each runner because PROJECT_DIR contains runner id)
3. BUILD_DIR (absolute path, same on all runners)

When compileJava starts on a new runner, it simply deletes cached classes as stale, saying:
```
Deleting stale output file: /root/build/generated/sources/annotationProcessor/java/main
Deleting stale output file: /root/build/classes/java/main
...
Task 'compileJava' is not up-to-date because:
  No history is available.
```

Both features work locally. I also tried moving the project folder to emulate PROJECT_DIR change across runners, features still work. Moreover, I tried sending archived PROJECT_DIR folder to my colleague, and to my surprise, incremental build and compilation worked across our machines. But since Gradle does not give any insight into why files are considered stale, I can't figure out why it does not work on CI. I am using Gitlab CI, Gradle builds run inside a Docker container, but there's no magic going on there AFAIK, so everything should work the same way it does between my and colleague's machines.

**Comment by lptr** [comment]
Up-to-date checks were not designed to work across machines. Why not use the build cache, which is designed exactly for this use case?

**Comment by patkovskyi** [comment]
Mainly because build cache does not support incremental tasks. Any change in inputs leads to a cache miss and full re-execution of a task. In particular, incremental Java compilation does not work with build cache.

Plus, there are tasks which have UP-TO-DATE checks but are not marked as cacheable.

**Comment by lptr** [comment]
We recommend running clean builds with a remote build-cache on CI. This means no incremental tasks or compilation. The reason we don't recommend incremental tasks on CI is because in many cases it's hard to get them right, especially custom ones, and there can be bugs that you want to avoid on CI. That said, specifically the incremental Java compiler and any other incremental task included with Gradle itself should be stable enough to use on CI.

If you understand this risk, it's okay to run non-clean builds on CI, too. What you'd get with that is that you'd get incremental tasks and incremental compilation _compared to the previous build that ran on the same machine._ This can be quite random depending on how your CI allocates agents, but even then it can improve performance somewhat.

Sharing the contents of our incremental build caches is untested and is likely not going to work. Even if it would, it is unlikely that it would provide any significant improvement over using a remote build cache with non-clean builds on CI.

This is our general wisdom for typical build environments. Maybe yours is different, in which case it would be great if we could learn more about it. Can you maybe publish a few build scans from the following builds?

* clean build
* non-clean build with small code change
* clean build with small code change using build cache
* non-clean build with small code change using build cache

I'm going to close this issue, as there's nothing actionable for it yet, but please feel free to reply nevertheless. We can reopen if needed later.

**Comment by patkovskyi** [comment]
Thank you for an informative answer!

For my build, incremental Java compilation is not too beneficial right now since the project is small. However, I was able to make it work _across machines_ by caching a bunch of Gradle folders. The way I protect myself from "dirty" builds on CI: when building master branch, I execute "clean" task before other ones.

I don't think there's a need to reopen this issue. There's a related issue I filed earlier  https://github.com/gradle/gradle/issues/9337 If Gradle team decides to improve incremental compilation feature, I think it would be nice to fix it.
