### ISSUE TITLE
Tasks with input files marked 'skip when empty' should delete outputs only when it is known to be safe to do so

### ISSUE THREAD

**Issue by adammurdoch** [gradle/gradle#973]
Currently, the outputs for these tasks are deleted when all source is removed, regardless of whether this is the desired outcome or not. Instead, we should delete these files only when we know this is what the user wants, consistent with whatever we come up with for cleaning up stale files more generally.

### Your Environment

 * Build scan URL:

**Comment by eriwen** [comment]
From #1012 

### Expected Behavior


When using the exclude method and actually all files from sourceDir are excluded, the destination dir should remain unchanged

### Current Behavior


When using the exclude method and actually all files from sourceDir are excluded, 
Then **ALL** the ecluded files that are already present in the **DestinationDir** are **DELETED**

### Steps to Reproduce (for bugs)
e.g. in my file system:
* sourceDir with several (and only! )  *.sql files
* destDir  with the same files copied from sourceDir

then executing the following task

```java
task testBBLCopy (type: Copy) {
	from sourceDir
	//exclude { details -> true }
	exclude '**/*.sql'
	into destDir
	includeEmptyDirs = false
}
```
### Your Environment
Mac OS X ElCapitan 10.11.6
Gradle Distribution: Gradle wrapper from target build
Gradle Version: 3.2
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home
JVM Arguments: None
Program Arguments: None
Gradle Tasks: testBBLCopy

**Comment by wolfs** [comment]
@ danreb25 Could you elaborate why that is a problem for you? Do you have other copy tasks copying into the same destination directory? Where does your destination directory reside? Inside the `build` directory?
Doesn't executing the copy task after a clean have the same end result as deleting all the files in the destination directory when there is nothing to copy (i.e. the destination directory is empty)?

**Comment by danreb25** [comment]
Hi wolfs sorry for the delay,

*__why that is a problem for you?__ 

I expect the  ```Copy task``` to copy files from sourceDir to destinationDir and not to "SYNC"
 my destinationDir with the sourceDir. I would use the ```Syn Task``` for this.  




Action on fileSystem|GradleTask runned|   |Origin Dir | Destination dir
------------ |------------ |------------ |------------ | -------------
initial state | null | -->|[tex1.txt;tex2.txt;tex3.txt]|  :white_check_mark:[text4.txt]
null | myCopyTask | -->|[tex1.txt;tex2.txt;tex3.txt]|  :white_check_mark:[text4.txt;tex1.txt;tex2.txt;tex3.txt]
rm from OriginDir tex1.txt;tex2.txt  | null | -->|[tex3.txt]|  :white_check_mark:[text4.txt;tex1.txt;tex2.txt;tex3.txt]
null | myCopyTask | -->|[tex3.txt]|  :white_check_mark:[text4.txt;tex1.txt;tex2.txt;tex3.txt]
null | myCopyTask (rerunned) | -->|[tex3.txt]|  :white_check_mark:[text4.txt;tex1.txt;tex2.txt;tex3.txt]
rm from OriginDir tex3.txt | null | -->|[-]|   :white_check_mark: [text4.txt;tex1.txt;tex2.txt;tex3.txt]
null | myCopyTask | -->|[-]|  :red_circle: [text4.txt]


in breaf when there is nothing in the filtered files in OriginDir all the previous copied files (and only those copied sith the gradle task) are deleted. 

With Gradle 3.1 when running the step 3 the task was considered up-to-date and the file wasn't deleted in the destinationDir

The problem exists since gradle 3.2> (tested also on 3.3)



*__Do you have other copy tasks copying into the same destination directory?__
yes
*__Where does your destination directory reside?__
Outside the build directory
*__Doesn't executing the copy task after a clean have the same end result as deleting all the files in the destination directory when there is nothing to copy (i.e. the destination directory is empty)?__
I still need to test this one more in depth

**Comment by rsshilli** [comment]
I'm still seeing this behavior in Gradle 4.8.1

**Comment by wolfs** [comment]
@rsshilli Where are you copying to? Somewhere in the `build` directory?

**Comment by rsshilli** [comment]
Yes.  We copy in the results from a previous test into `build/test/report` as part of the CICD system, and then run another test which copies source code into a number of directories such as `build/test/features` (but nothing into the report directory) and voila, the report directory is destroyed.
