### ISSUE TITLE
Kotlin DSL Lazy plus operator for Provider<FileCollection>

### ISSUE THREAD

**Issue by gildor** [gradle/gradle#9738]
it's a quite common case to combine file collections, especially configurations, something like this:

```groovy
configurations.compile + configurations.testCompileClasspath
```

This syntax works in Groovy, but not in Kotlin, in Kotlin it will be:

```kotlin
configurations.compile.get() + configurations.testCompileClasspath.get()
```

Which is eager (same as in groovy tho)

I propose to add a lazy version of plus override for Provide<FileCollection>, that may be implemented like this:

```kotlin
operator fun Provider<out FileCollection>.plus(
    provider: Provider<out FileCollection>
): Provider<FileCollection> = map { it + provider.get() }
```

There are similar extensions in `ConfigurationDeprecatedExtensions.kt`, but all of them are deprecated, and probably there is a good reason for that, it mixes eager and lazy FileCollections and the result is always eager, the proposed operator don't have this problem and shouldn't cause conflict with other APIs.

It allows to have this lazy and idiomatic syntax for Kotlin DSL
```
configurations.compile + configurations.testCompileClasspath // Result is Provider<FileCollection>
```

**Comment by big-guy** [comment]
`Provider<FileCollection>` doesn't make much sense.  A `FileCollection` is `Provider`-like, so you shouldn't need to use a `Provider<FileCollection>`.

Part of the issue has to do with a mixing of `Configuration` (which is a `FileCollection`) and a `NamedDomainObjectCollection` (which has `Provider` accessors).  Kotlin uses the `Provider` accessors by default, which makes this a little awkward. 

`configurations.compile + configurations.testCompileClasspath` is equivalent to `configurations.compile.plus(configurations.testCompileClasspath)` and `configurations.compile` and `configurations.testCompileClasspath` are both `Configuration`s.

I assume that the result of this is being assigned to something, instead of (with the proposed operator change):
```
// myTask.myProp is a Provider<FileCollection>
myTask.myProp = configurations.compile + configurations.testCompileClasspath
```
You should instead use a `ConfigurableFileCollection`:
```
// myTask.myProp is a ConfigurableFileCollection
myTask.myProp.from(configurations.compile, configurations.testCompileClasspath)
```
Or if you can't use `ConfigurableFileCollection`, you should just use `project.files()`:
```
// myTask.myProp is a FileCollection
myTask.myProp = files(configurations.compile, configurations.testCompileClasspath)
```

`project.files` and `ConfigurableFileCollection.from()` handle both `Provider<FileCollection>` and `FileCollection`.
