### ISSUE TITLE
No way for reload default gradle libraries

### ISSUE THREAD

**Issue by Tenischev** [gradle/gradle#974]
Gradle haven't way for reload his default libs (located in 'gradle-\*.\*/lib' and 'gradle-\*.\*/lib/plugins').

### Expected Behavior
In building process used a libraries with exactly version which declared in 'dependencies'.

### Current Behavior
If library with same name\package already load in Runtime process then it not will be reloaded (yes, it's how common java loader process work).

### Context
In my case it's xercesImpl library. Gradle use is old 2.9.1 version of this library and in my project i use a more newest 2.11.0 version.
You can find addition inforamtion and people with same problem on:
https://discuss.gradle.org/t/oddity-in-the-output-of-dependencyinsight-task/7553
https://issues.gradle.org/browse/GRADLE-2812
Maybe you add some flag, or will be use separete java Runtime process... reload default java loader...

### Your Environment
Gradle version 2.14.1

**Comment by formalizator** [comment]
Same with asm library. 
Gradle 3.0

Junit test run fails with Caused by: java.lang.SecurityException: class "org.eclipse.persistence.internal.helper.XMLHelper"'s signer information does not match signer information of other classes in the same package

Debug fails on ASM constructor signature.
Despite exact version in compile dependencies.

**Comment by oehme** [comment]
Gradle does not leak its dependencies into your project, so there must be something else going on. Please provide a reproducible example project showing the issue you are facing.
