### ISSUE TITLE
Gradle 5.5 RCs and 5.6 nightlies warns about buildSrc not having a gradle plugin service

### ISSUE THREAD

**Issue by ZacSweers** [gradle/gradle#9758]
### Expected Behavior
No warnings should be printed. I don't use buildSrc for plugins, just for shared dependency management and functions

### Current Behavior
The following warning is emitted

```
> Task :buildSrc:jar
:jar: No valid plugin descriptors were found in META-INF/gradle-plugins
```

### Context
It's not breaking my builds, but it is noise and appears to be indicative of some mismatched expectation

### Steps to Reproduce 
Sample project: https://github.com/zacsweers/catchup

Run `./gradlew help` from a clean state, `buildSrc` will recompile and display the warning above

### Your Environment
Build scan URL: https://scans.gradle.com/s/pghlud3xzqrmi

**Comment by pun-ky** [comment]
also visible in Gradle 6.0

**Comment by ZacSweers** [comment]
Yeah would be great to know if there's anything else needed to get an acknowledgement from the Gradle team on this.

**Comment by ZacSweers** [comment]
No ack yet, but just an FYI that the repro project above will no longer show this as I now have a gradle plugin present in its `buildSrc`

**Comment by big-guy** [comment]
This is expected.  With the `java-gradle-plugin` applied, the expectation is that Gradle plugins are being created and when it looks like there aren't any, Gradle complains.

If the build was trying to create a plugin and was missing those descriptors, it would be harder to use the plugin build as an included build or write tests with TestKit or apply the plugin by ID. 

I think it's OK to use `java-gradle-plugin` in buildSrc because it makes it easier to write plugins in buildSrc and test them.  If you only have individual classes you're using from buildSrc (and not a plugin), you don't have to apply the `java-gradle-plugin`.  

Some builds may not be explicitly applying `java-gradle-plugin` since `kotlin-dsl` also applies it.

**Comment by ZacSweers** [comment]
> Some builds may not be explicitly applying java-gradle-plugin since kotlin-dsl also applies it.

This was the missing piece for me. Thanks

**Comment by ZacSweers** [comment]
I actually don't find this answer satisfactory. Proposing a PR to disable this with more details here, as it's warning about something as if it's programmer error when it is in fact not.
