### ISSUE TITLE
Dependency locking operation modes

### ISSUE THREAD

**Issue by ljacomet** [gradle/gradle#9907]
Since its introduction, feedback has been gathered over the usage of dependency locking.

Part of that feedback concerns modes of operation when locking is activated.

### Strict mode

Some users would like the ability to have even stricter locking, where having a locked configuration _without_ lock state is invalid and causes a violation.

### Dev mode

(name subject to change 😉 )

Some users and some scenarios could benefit from a _dev mode_ for locking, where the lock information would be used in a lenient fashion instead of strict.
For example:
* in a development workflow, I may want some flexibility with dependency versions while trying things out but not want _all_ versions to suddenly upgrade.
* in a composite build situation, I may want flexibility for the transitive of the substituted dependency but not want _all_ versions to suddenly upgrade.

The issue with the locking feature, in its current state, is that if it is turned off, all ranges can potentially upgrade to the latest version of dependencies. And as seen above that's usually not a desired effect.

The idea would be to enable a mode that would work similarly to `--update-locks` but without the need to pass a flag and instead rely on some configuration of the `dependencyLocking` block.

**Comment by rgoldberg** [comment]
1. Dev mode could be renamed Lenient mode.

2. I'd suggest having three modes:
- Fail, Error or Strict: fails on violations
- Warn: outputs warnings about violations, but doesn't fail
- Ignore, Silent, or Lenient): completely ignores violations

3. Instead of only having a mode, maybe provide more granularity by having an individual trinary setting (FAIL / WARN / IGNORE) for each aspect of the proposed modes, and have one trinary default setting, which can be overridden for any of the individual settings.

4. I know that the following is different than what was written in https://github.com/gradle/gradle/issues/4749#issuecomment-483223085, but it seems to me that locks should work in the following way:

- Generating locks always generates them for all dependencies, including source-substituted ones
- A trinary setting (FAIL / WARN / IGNORE) for source-substituted-dependency lock violations (both for missing locks and for version mismatches)

Not generating locks for source-substituted dependencies seems to defeat the modular purpose of composite builds.  A build should be able to be built as a standalone or as part of any composite.  If I generate the locks from a composite, but then I (or someone else) works on one of its included builds (that had a source-substituted dependency) outside of that composite, then the locks won't be correct.  There doesn't seem to be any harm in generating a lock if it can be ignored when sources are substituted, but there definitely is harm once if there is no lock and if you work in a context where sources are no longer substituted.

**Comment by ljacomet** [comment]
@rgoldberg  Thanks for your feedback on this!
A first version is currently in draft, see the link above.

I do not think going to such a granular configuration is needed. The added complexity does not feel right compared to the use cases discussed so far.

Regarding your point 4, I understand the desire to have the system behave correctly in the composite case, but it is nearly impossible to achieve in the general case: Not only will the substituted dependency be impacted, you will also potentially impact _any_ dependency from the main build since the composite could bring conflicting versions and cause upgrades. And so the fine grained setting will not cover all cases, while the more coarse grained one is clear about it.
And in that sense, I feel the existing composite solution combined with the proposed modes pretty much covers the different composite use cases:
* Devs always use the composite, then it is fine to not lock that single version. Coupled with #6846, you could even express it correctly for isolated CI builds.
* Composites are the exception: you leverage the `LENIENT` mode, by turning it on the moment you are building a composite.

**Comment by rgoldberg** [comment]
@ljacomet Thanks for the response. A few questions:

> Composites are the exception: you leverage the `LENIENT` mode, by turning it on the moment you are building a composite.

- Does that mean that `LENIENT` is automatically enabled for composites? If so, is it possible to manually switch it to `STRICT`?

- Will there be 3 modes: NORMAL, STRICT, LENIENT? Or just 2: STRICT, LENIENT?

- It seems like LENIENT is just the ability to specify certain dependencies whose versions aren’t checked for locks. Is that correct? If so, would LENIENT do anything if no specific dependencies are specified?

- say I have an included build, B, that some other included builds depend upon. What if each dependent build wants a different version of the module for B? Would B be substituted for all dependencies on B’s module identifier, regardless of version? If so, that seems too coarse. Say I need to fix a bug in B 1.2.5, but don’t have time to update uses of B 1.0.7 elsewhere in my composite. I would think that substitutions should be able to be limited to the specific version of a module. Maybe add in a switch to make substitutions by exact version match vs. all versions (or you could allow an ad hoc version range, though that probably wouldn’t be used as much as exact match / all versions). If you support exact version substitutions, then I myself would like to use dependency locking for substituted modules. I understand that maybe others wouldn’t want or need it, or that it might not be worth the time / complexity for you guys to make, but just adding my vote to any counter you might have for interest in that.

Thanks

**Comment by ljacomet** [comment]
* No, it is always opt-in. Though configuring a build to switch to `LENIENT` when in a composite should be easy
* 3 modes: `STRICT`, `DEFAULT`, `LENIENT`
* No, `LENIENT` is a general behavior: it will load the lock state, to anchor dynamic versions, but otherwise be lenient about modifications of the dependency resolution, allowing versions to change and modules to be added or removed
* What you discuss here is a more fine grained composite system. Gradle dependency management supports substitutions for a complete GAV, that means `version` included. I do not know if that works with composites though.
