### ISSUE TITLE
Gradle should support Maven's "nearest" artifact resolution strategy

### ISSUE THREAD

**Issue by sschuberth** [gradle/gradle#9930]
E.g. in a mixed Maven / Gradle multi-module project, where a Maven project publishes JARs to the local Maven repository and the Gradle project depends on these JARs, it's important that Maven and Gradle resolve any version conflicts in transitive dependencies in exactly the same way. That's because the Maven project implicitly puts all its dependencies into Maven Local, and the Gradle project has *only* Maven Local as its repository defined. So if Gradle resolves a conflict to a different version than Maven, it will not find that version in Maven Local, and the build fails.

### Expected Behavior

There should be an easy way to set Maven's "[nearest](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies)" resolution strategy instead of Gradle's default "newest" resolution strategy, e.g. via something like

```
configurations.all {
  resolutionStrategy {
    // Use Maven's "nearest" version conflict resolution strategy.
    useNearest()
  }
}
```

### Current Behavior

There is no easy way to resemble the behavior of Maven's "[nearest](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies)" version conflict resolution strategy. However, @uklance once created a [plugin](https://github.com/uklance/gradle-aether) for this purpose.

### Context

The different default resolution strategies in Maven vs. Gradle can cause confusion for people switching from Maven to Gradle and may result in unexpected build results. In cases like the above-mentioned mixed Maven / Gradle multi-module project, it makes Maven / Gradle interaction more complicated than necessary. 

References to similar discussions:

https://github.com/gradle/gradle/issues/2212

**Comment by jjohannes** [comment]
There are no plans to ever support something like this in Gradle as we don't believe this is a good strategy. And supporting this as an alternative would make resolution much more complex. It is also unclear how this would behave with certain [rich versions](https://docs.gradle.org/current/userguide/rich_versions.html) that are not supported in Maven.

There are now many more option in Gradle (since Gradle 6.x at leas) to [control versions through dependency constrains](https://docs.gradle.org/current/userguide/rich_versions.html). If you publish a library, you can also make use of this through the Gradle Module Metadata that is published in addition to pom files.
