### ISSUE TITLE
Incremental Java compilation w/ annotation processing seems broken

### ISSUE THREAD

**Issue by snazy** [gradle/gradle#9946]
If I understand all the caveats about incremental java compilation w/ annotation processors correctly, changing a single Java source (say, add a new line to the .java file) should only compile that class and nothing else.

I've setup a tiny Gradle 5.5.1 project with two Java class files that uses `compile-command-annotations`:
``` 
plugins {
  id "java-library"
}

repositories {
...
}

dependencies {
  annotationProcessor(group: "net.nicoulaj.compile-command-annotations", name: "compile-command-annotations", version: "1.2.2")
  compileOnly(group: "net.nicoulaj.compile-command-annotations", name: "compile-command-annotations", version: "1.2.2")
}
```
that has two pretty much empty Java source files.

Incremental compilation works without the apt, but with the apt, a full recompilation is triggered.
```
[org.gradle.api.internal.tasks.compile.incremental.SelectiveCompiler] Full recompilation is required because the generated resource 'META-INF/hotspot_compiler in CLASS_OUTPUT' must have exactly one originating element, but had 0. Analysis took 0.001 secs.
```

Already tried to tweak the apt to write to SOURCE_OUTPUT, but without any luck.

The apt's `META-INF/gradle/incremental.annotation.processors ` defines and uses the `Filer` API:
```
net.nicoulaj.compilecommand.CompileCommandProcessor,isolating
```

[gradle-incr-ann-proc.tar.gz](https://github.com/gradle/gradle/files/3387482/gradle-incr-ann-proc.tar.gz)

**Comment by bjornvester** [comment]
Just a friendly tip from a fellow developer (I am not a Gradle developer, just a happy user).

The annotation processor itself needs to adhere to a set of rules and constraints. When you specify that your processor has the "isolating" category, you must provide exactly one originating element using the Filer API.

Gradle warns you about the fact that it didn't find any originating elements at all, and since it cannot determine which element was the one corresponding to the output, it disables incremental compilation.

You didn't show how you implemented the processor, but I expect you didn't supply the originating element you get from the RoundEnvironment instance to the Filer API. If you look at the [Filer JavaDoc](https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Filer.html), notice that the "create" methods take an optional list of elements as the last parameters. You probably missed that.

If this is not the case, maybe you can share the code for your annotation processor?

BTW, if you have any issues with using Gradle, may I suggest that instead of creating issues on Github, you come hang out with us in the [Gradle Slack channel](https://gradle-community.slack.com/) or use the [forums](https://discuss.gradle.org/)? People are usually very quick and helpful, and often times you get immediate feedback :)

**Comment by snazy** [comment]
@bjornvester thanks a lot for the hints! I think, that (missing element to filer-api call) explains it - and it makes sense.
[This is the relevant part of that apt](https://github.com/nicoulaj/compile-command-annotations/blob/master/src/main/java/net/nicoulaj/compilecommand/CompileCommandProcessor.java#L245-L261) that writes a _single_ resource file from multiple source elements.

Making that support incr. compilation is then a bit more tricky. It sounded so simple. *sigh*

**Comment by snazy** [comment]
To elaborate a bit: the apt takes the annotations from an arbitrary number of source files/elements and produces a single output file.
I think, the best would be to create one output file per element and then merge these files later using proper input/output properties.

**Comment by bjornvester** [comment]
If you are OK with changing the annotation retention policy from SOURCE to CLASS, I think you can also get away with making it an "aggregating" processor instead of "isolating". If not, I think you are right in that merging single outputs at the end might the best approach.

As a comforting thought, know that you are not alone in struggling with these things :D

**Comment by snazy** [comment]
@bjornvester was right. It was the apt writing a single "unmanaged" file.
Sorry for the noise! Not a Gradle issue.
