### ISSUE TITLE
Use input snapshots to skip empty work

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#9980]
There's no need to walk the inputs twice just to do this.

**Comment by wolfs** [comment]
Note that currently the `SkipWhenEmptyTaskExecuter` ignores empty directories for input directories and input file trees. So we would need to know if the file collection cares about empty directories or not when only looking at the input snapshot for the source properties.

We could do a breaking change for 6.0 to always ignore empty directories for sources (aka `@SkipWhenEmpty`) and then use the input snapshot.

**Comment by wolfs** [comment]
In order to use the input snapshot we would need to snapshot the inputs for the sources before we check if there are any sources. If no sources are there this requires the same amount of work as checking if the file collection is empty, since the only thing to do is to check if the root files exist and if the source directories contain any files.

Moreover, we currently validate the inputs after we check if there are no sources and before we fingerprint the inputs. So we would need to decide if we want to validate tasks with no sources as well.

**Comment by lptr** [comment]
On validation: I think it would make sense to validate every task, even if it doesn't have sources—we want to know if there are problems even if we don't hit them just now. However, much of the performance improvement added by empty-source avoidance comes from the fact that we don't process the `classpath` of `GroovyCompile` tasks when there are no Groovy sources in a source set etc. Validation would mean we'd need to evaluate these unused properties, too.

Aside: it looks like there are some similarities here with artifact transforms, where there are also primary inputs that need to be snapshot separately to the rest of the inputs.

**Comment by wolfs** [comment]
I think fixing this is also important when we want to use file-system watching as a backend for continuous build, since `DefaultEmptySourceTaskSkipper` registers the possible inputs which cause a rebuild: https://github.com/gradle/gradle/blob/511d7ba78fb55eb10f16c9ffd90a32428b9938f9/subprojects/core/src/main/java/org/gradle/api/internal/tasks/execution/DefaultEmptySourceTaskSkipper.java#L66-L73
